### ISSUE TITLE
Change index.php to Nextcloud colors and logo

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1]
cc @jancborchardt

**Comment by enoch85** [comment]
Somewhat done here, haven't checked the outcome though: https://github.com/nextcloud/vm/commit/1f0959fba72014c17db7f3da6e31d03a98ccd83a

**Comment by jancborchardt** [comment]
Commented at https://github.com/nextcloud/vm/commit/1f0959fba72014c17db7f3da6e31d03a98ccd83a#commitcomment-17741409 :)

**Comment by enoch85** [comment]
Fixed with https://github.com/nextcloud/vm/commit/06b5dd114be972fdfd7469950e361c2c8fe540f8
