### ISSUE TITLE
Migrate data from OLD Nextcloud server to new Nextcloud server

### ISSUE THREAD

**Issue by markovp** [nextcloud/vm#1000]
It will be nice to have some howto or guideline how to migrate data from old server to new server. 
I know how to backup data and restore on same server, but migration ...

Example: 
OLD server: Ubuntu 16.0.4, Nextcloud 15.0.14, DB MySQL 5.7.28
NEW server: Ubuntu 18.0.4, Nextcloud 17.0.2, DB PostgreSQL 10.10

Especialy how to migrate database from MySQL to PostgreSQL and upgrade ...

**Comment by enoch85** [comment]
Please ask in the forum.

Thanks.

**Comment by enoch85** [comment]
Btw, I don't know if this still works, but you could try (make a backup first): https://www.techandme.se/we-migrated-to-postgresql/
