### ISSUE TITLE
Change the preview script to match nextcloudpi

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1001]
Hello,

I recently saw the [blogpost](https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/) by nachoparker concerning the previewgenerator.
Would be really nice if you could change the previewgenerator.sh script to match the settings, that nachoparker recommends:

![image](https://user-images.githubusercontent.com/42591237/71531826-bdcfdd80-28f0-11ea-9197-3a88858a448a.png)

Also an option to choose, if I want to install imagick or not would be really nice, because it is not a must have if you get the settings right.

Maybe also beeing able to choose the formats I want to enable for preview during the setup would be really appreciated.

Also I think 4 am is a better time to run the previewgenerator.

Beeing able to choose a user for that the cronjob is running would also be really nice.

**Comment by enoch85** [comment]
Merged
