### ISSUE TITLE
What about an openVPN-Server, a Pi-hole and an Emby Media Server?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1005]
Hello,

would be really nice, if I could install an openVPN-Server as an app (prepared).
Don't know, if this works inside the VM: https://github.com/Nyr/openvpn-install

Also beeing able to install a local DNS Server (Pi-Hole) would be really nice.
I think the standard installation won't work: https://github.com/pi-hole/pi-hole 
Because Nexcloud already uses these Ports.

Also what about an emby media server? 
https://github.com/MediaBrowser/Emby
Would be really nice, if ssl would work then out of the box.
Don't know if possible but working hardware-transcoding inside the VM would be really welcome.

Thanks for all your great work!

**Comment by enoch85** [comment]
Nice ideas, but not for the Nextcloud VM imho.

If the user wants to add that, then it's up to the user, but not as standard.

There are docker images for all the stuff you linked, much better to put them as separate services if you ask me.

**Comment by szaimen** [comment]
I agree, they shouldn't get installed by default.

But maybe they could get added as options here?
https://github.com/nextcloud/vm/blob/9c73939ac395f0091e7ca33c73311eb869dfffcf/nextcloud-startup-script.sh#L426
So that the apps-script is ready and just can get triggered if the user wants to.

Would be really welcome additions IMO.

**Comment by enoch85** [comment]
ok let's break it down a bit:

This VM is for Nextcloud and stuff related to Nextcloud, nothing else. 

1. Pi-Hole - has nothing with Nextcloud to o at all, and is best run in your home-network as a service behind your router.
2. VPN service, why?
3. Emby looks a lot like Plex, which also is a totally separate service apart from Nextcloud which is best run on a separate server.

There are Dockers like: https://github.com/binhex/arch-rtorrentvpn and https://github.com/plexinc/pms-docker and https://github.com/pi-hole/docker-pi-hole, but that's for a Media Server, not a cloud like Nextcloud is.

**Comment by szaimen** [comment]
Okay, I know understand a bit better what you mean.
But actually Bitwarden has nothing to do with Nextcloud either (to my knowledge) and yet, there is an install script available. 
So why not making the services also easily installable to the Nextcloud VM?

And yes I aggree, if running Nextcloud VM on a hosted Server, at least Emby doesn't make a lot of sense, but they all are really nice additions, if you are running the VM on a Server at your home.

But an OpenVPN-Server in combination with a Pi-Hole makes also a lot of sense when running the VM on a hosted Server, since if you want to hide your real IP-address on the internet and encrypt all of your traffic, it is perfect in combination with an DNS-side adblocker imo.

And BTW: Emby is the open-source pendant to Plex and has gained a lot of attraction in the short past and I think fits better here then Plex.

**Comment by enoch85** [comment]
> So why not making the services also easily installable to the Nextcloud VM?

We started out with Passman which does the same thing, but since Passman isn't maintained as much I opted for Bitwarden instead to get the same thing but with better maintenance. 

The VM isn't for home users per say, we most of the users are enterprises or small business. Imo it would look a bit "unserious" to make the options above available. Like "Ehh, what does this do in the Nextcloud VM" since there's no relation between them.

**Comment by enoch85** [comment]
Closing this as it's not in the scope of this VM.

**Comment by szaimen** [comment]
> Closing this as it's not in the scope of this VM.

If I would make an PR with another msg_box after the whiptail [here](https://github.com/nextcloud/vm/blob/9c73939ac395f0091e7ca33c73311eb869dfffcf/nextcloud-startup-script.sh#L427), would you consider it to merge if it is well enough thought out?

So I would just ask if you want to install home apps? and then you can press no, or just hit [ENTER] to continue.
These Home-Apps then could be positioned in another folder...

**Comment by enoch85** [comment]
Since this is the official Nextcloud VM, I'm restricted to what goes in or not. Having Bitwarden approved wasn't an easy decision either.

Adding stuff as proposed above has nothing to do with Nextcloud, so sorry, not even a PR would make me think about it.

**Comment by szaimen** [comment]
> Since this is the official Nextcloud VM, I'm restricted to what goes in or not. Having Bitwarden approved wasn't an easy decision either.
> 
> Adding stuff as proposed above has nothing to do with Nextcloud, so sorry, not even a PR would make me think about it.

Okay
