### ISSUE TITLE
Let us discuss the remember_login_cookie_lifetime

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1006]
I would like to discuss whether this should be the default in the VM:
https://github.com/nextcloud/vm/blob/9c73939ac395f0091e7ca33c73311eb869dfffcf/nextcloud_install_production.sh#L412

Maybe it could get transfered to the startup script? Because this is probably something you want to configure and therefore would fit inside the startup-script imho.

Or if you don't want to move it to the startup-script, maybe it could be available as an apps-script?

**Comment by szaimen** [comment]
I thought about this a bit more and I think it would fit perfectly here: 
https://github.com/nextcloud/vm/blob/9c73939ac395f0091e7ca33c73311eb869dfffcf/nextcloud-startup-script.sh#L375
because it isn't really an additional app, but should be configurable during the initial setup.
Then if the value doesn't get change by the user during this step, it would be the default value (1800).

**Comment by enoch85** [comment]
You could prepare a PR where the default is 1800 seconds, with a `msg_box` that describes what it does, and a value for changing it to preferred value.

FYI, the reason it's not 0 is that it makes the web UI upload stop as it's forcefully logging out the session after that period of time.

Try different scenarios first, then make a PR with your findings.

Thanks a lot!

**Comment by szaimen** [comment]
Do you agree, that it fits here:
https://github.com/nextcloud/vm/blob/9c73939ac395f0091e7ca33c73311eb869dfffcf/nextcloud-startup-script.sh#L375
Or where should it be located inside the start up script?
