### ISSUE TITLE
RAM check no longer on line 34

### ISSUE THREAD

**Issue by dbolton** [nextcloud/vm#1007]
## Steps to reproduce
1. sudo bash nextcloud_install_production.sh
2. continue till RAM check message

## Expected behaviour
Instructions on RAM check say "If you want to bypass this check you could do so by commenting out (# before the line) 'ram_check X'...somewhere around line #34"

## Actual behaviour
It should say "around line 98".

**Comment by enoch85** [comment]
Thanks for the issue!

Maybe you want to contribute by making a PR? :D

**Comment by dbolton** [comment]
Here you go!
https://github.com/nextcloud/vm/pull/1008
