### ISSUE TITLE
onllyoffice can't be instsalled because of  CERT verify

### ISSUE THREAD

**Issue by liao20081228** [nextcloud/vm#1014]
the test result is returned by the function,check_open_port(), said the port 80 and 443 always are closed. but I have opened the forward port on my router 。so I insert a ”#” into the line “check_open_port 80 ....” and “check_open_port 443 ....” in active_ssl.sh. then I active the SSL successfully, and the nextcloud can be accessed by these port from the internet. So I guess my ISP banned the port scan.     

**I START to install onlyoffice step by step**:
1. $sudo bash /var/scripts/app/onlyoffice.sh
2. waiting .......

**the screen show as follow**:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Running pre-hook command: service apache2 stop
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for office.xxxxx.xxxxx
Waiting for verification...
Cleaning up challenges
Running post-hook command: service apache2 start
Failed authorization procedure.office.xxxxx.xxxxx (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://office.office.xxxxx.xxxxx/.well-known/acme-challenge/WUBTXXXXXXXXXXXXXBLeXExcO-3B9eN6Rg: Timeout during connect (likely firewall problem)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: office.xxxxxxxxxx.xxxxxx
   Type:   connection
   Detail: Fetching
   http://office.xxxxxxxxxx.xxxxxx/.well-known/acme-challenge/WUBTXXXXXXXXXXXXXXXXXXXXXXXB9eN6Rg:
   Timeout during connect (likely firewall problem)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

the screen show “It seems like no certs were generated, please report this issue here: https://github.com/nextcloud/vm/issues"
```

**My Environments**:
my server is    Ubuntu 18.04 sever。and CPU is intel i7-4790k，memory is 8Gib, disks are  SSD 240Gib and HDD 1Tib.

**And I suggestion  are as follow**:
1. the implement of check_open_port may use another way. Because  "is closed on" was always  returned by 
`curl -s -H 'Cache-Control: no-cache' 'https://ports.yougetsignal.com/check-port.php' --data "remoteAddress=${WANIP$}&portNumber=$1"`
2. OR  let users decide whether to check these ports.

3. the onlyoffice CERT verification may use DNS or/and FILE, not  FILE only.

**Comment by enoch85** [comment]
The port scan happens outside of your network, so my guess is that your ISP blocked port 80, or some other fishy thing to do being a fishy ISP. :)

**Comment by enoch85** [comment]
Just as an FYI, I ran exaclty the same check just 30 minutes ago setting up another server, and it worked. So, no errors in the script anyway.

**Comment by liao20081228** [comment]
> The port scan happens outside of your network, so my guess is that your ISP blocked port 80, or some other fishy thing to do being a fishy ISP. :)

yes， I agree。 I try to solve the problem by using 
``` 
default_le="--rsa-key-size 4096 --renew-by-default --no-eff-email --agree-tos --uir --hsts --server https://acme-v02.api.letsencrypt.org/directory -d $SUBDOMAIN"
certbot certonly --manual --manual-public-ip-logging-ok --preferred-challenges dns $default_le
```
in active_sssl.sh  insted of  
```
certbot certonly --standalone --pre-hook "service apache2 stop" --post-hook "service apache2 start" --agree-tos --rsa-key-size 4096 -d "$SUBDOMAIN"
```
but Similar errors continue to occur。

**Comment by enoch85** [comment]
How did you get TLS for your main domain? Using the built in LE script?

I'm asking because they use exactly the same setup TLS-wise, except from in the main script you can validate with DNS as well.

**Comment by liao20081228** [comment]
I use the script active_ssl.sh.  I  delete  “check_open_por 80” and “check_open_por 443” in active_ssl.sh.  after failed to verify by "http://cloud.xxxxxxxxxx.xxxxxx/.well-known/acme-challenge/WUBTXXXXXXXXXXXXXXXXXXXXXXXB9eN6Rg" ，it automatic to jump the DNS verification, and I set the TXT record in my DNS provider. then ...... I succeed in activating the https.

**Comment by enoch85** [comment]
OK, so port 80 or 443 is blocked. Talk to your ISP.

Thanks!
