### ISSUE TITLE
Nextcloud runs automatic initial config every reboot

### ISSUE THREAD

**Issue by hammeractual** [nextcloud/vm#1016]
## Steps to reproduce
1. Reboot the server
2. Login
3. The automatic initial config begins again

## Expected behaviour
No more automatic initial config

## Actual behaviour
The automatic initial config runs every reboot

## Server configuration

**Nextcloud server version:** (see your admin page)
Nextcloud 17 using VM from https://www.hanssonit.se/nextcloud-vm/

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
Use DHCP

**Is port 80 and/or 443 open?**

Port 80 & 443 are open

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots

https://imgur.com/qU0JN2J

**Comment by enoch85** [comment]
The first setup script is removed in the end of the script. So, if it wasn't removed, then the first setup script didn't finish properly.

Please try again.

**Comment by hammeractual** [comment]
> The first setup script is removed in the end of the script. So, if it wasn't removed, then the first setup script didn't finish properly.
> 
> Please try again.

So, should I reinstall the vm from the begining? Or there is another way to resolve it?

**Comment by enoch85** [comment]
> should I reinstall the vm from the begining?

Yes, that's correct.

There's [another soulution](https://shop.hanssonit.se/product/premium-support-per-30-minutes/) though.

**Comment by hammeractual** [comment]
> > should I reinstall the vm from the begining?
> 
> Yes, that's correct.
> 
> There's [another soulution](https://shop.hanssonit.se/product/premium-support-per-30-minutes/) though.

Thanks for the information ;)

But, perhaps there is something that you can improve or fix in the installation/config script. 
Because, even though I did reinstalling the VM from the beginning, the problem still appears.

Here is the screnshoot. [https://imgur.com/O3CwTHf](url)

Thank you.

**Comment by enoch85** [comment]
There's nothing to improve. Either you run the setup script from start to finish, or you don't :)

Look at this: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L667
