### ISSUE TITLE
hi , so i'm new in using nextcloud vm , so the problem is after a successful installation when trying to excute occ commands it show me could not open input file nextcloud/occ , after trying to fetch in var/www/html/... i can't find the path to nextcloud/occ , 

### ISSUE THREAD

**Issue by aymene1995** [nextcloud/vm#1017]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by szaimen** [comment]
have you tried to execute `nextcloud_occ` as root user?

**Comment by enoch85** [comment]
@aymene1995 As @szaimen said, please use the built in Alias `nextcloud_occ`.

The path to Nextcloud is not `var/www/html/` it's `var/www/`
