### ISSUE TITLE
Onlyoffice: if the cpu load spikes up while loading previews in Nextcloud, onlyoffice is not reachable

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1018]
## Steps to reproduces
1. Install Nextcloud VM
2. install the onlyoffice server with the apps-script
3. open a folder in nextcloud with many pictures -> the preview files get loaded or generated -> the cpu load spikes up to 100%
4. onlyoffice is not reachable.

## Expected behaviour
Onlyoffice shoud work no matter what the rest of the VM is doing

## Actual behaviour
Onlyoffice is not reachable.

## Server configuration
I am running the latest Nextcloud VM

## Ideas how to solve it
Maybe the Nextcloud VM should reserve some ressources to the onlyoffice server to keep it running? (of course preview loading/generating is slower than, but it wouldn't crash the onlyoffice server)

**Comment by enoch85** [comment]
This is probably an error with OnlyOffice. Did you try Collabora? Is it the same thing?

I prefer Collabora over Onlyoffice actually. It seems to me that Collabora is more stable. Almost every issue I get regarding the two, OnlyOffice is the one not working as expected.

**Comment by szaimen** [comment]
I found this:
https://github.com/nextcloud/vm/issues/961#issuecomment-544225015
Disabling the evasive module also fixes the problem for me.
So I would suggest something like 
```
If [ ${Apache2ctl -M | grep evasive} != "" ]
then
    sudo a2dismod evasive
```
before installing onlyoffice

**Comment by enoch85** [comment]
@szaimen That's only valid if you installed the ""Extra Security". But sure, we could add a check for that.

I'm quite busy now, new year, new budget, and a lot of work. Please make a PR and I'll review it when I have time.
