### ISSUE TITLE
Configure and adding cifs-mounts as optional app-script?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1022]
I actually use CIFS-mounts very often to access files of my host machine from the VMs. And this could therefore be something useful for the VM. 

At least for script-testing it would be really nice, if it could get done through an appscript. But of course also if you don't want to store all userfiles inside the Volume. (external storage app). 

Also the Nextcloud-SMBclient seems to work very unreliably in the latest past (I couldn't add an SMB-Share on 17.0.2) and system mount is much more stable, reilable and fast in my experince. 
So could this be a useful addition for the Nextcloud VM?

What do you think about this?
I would like to work on this next if you would accept PRs on this topic.

**Comment by enoch85** [comment]
Do you mean mounting SMB shares in the VM directly as a root file system?

**Comment by szaimen** [comment]
> Do you mean mounting SMB shares in the VM directly as a root file system instead of `/mnt/ncdata`?

Maybe this or just as an additional path e.g. /mnt/data

**Comment by enoch85** [comment]
I'm OK with adding *additional* SMB mounts as an option. I'm not OK with replacing `/mnt/ncdata`.

All mounts should happen in `/mnt/smbshares/` as root for all shares. So if there are multiple shares then it would look like:
`/mnt/smbshares/1`
`/mnt/smbshares/2`
`/mnt/smbshares/3`
and so on.

Thank you very much @szaimen!

**Comment by szaimen** [comment]
Actually if you wuld want to use the smbmount with the external storage app, then you need to use the ww-data user as file owner amd directory owner... So I would prefer that...

**Comment by enoch85** [comment]
> ww-data user as file owner and directory owner... So I would prefer that...

Yes, that's what I expected you to do. :)
