### ISSUE TITLE
Run previewgenerator at startup. Will the exits also exit the startup script?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1023]
If running the new previewgenerator script during the startup script. Will the exits inside the new script also exit the startup script?

**Comment by enoch85** [comment]
It shouldn't exit the startup script as it's run as it's own script. So it will exit the previewgenerator script, not the script that it's called from.

Try and find out.

**Comment by szaimen** [comment]
I will do that tomorrow 👍

**Comment by enoch85** [comment]
Great, thanks!

**Comment by szaimen** [comment]
I have tested it and exit in the previewgenerator doesn't exits the startup script. => this issue isn't an issue.
