### ISSUE TITLE
Error: It seems like no certs were generated

### ISSUE THREAD

**Issue by gerardjm** [nextcloud/vm#1031]
## Steps to reproduce
1. Execute script
2.
3.

## Expected behaviour
Install Onlyoffice

## Actual behaviour
Error: It seems like no certs were generated and not installed

## Server configuration

**Nextcloud server version:** (see your admin page)
17.02

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Hansson Hyperv Virtual Machine

## Network
**Do you use DHCP?**
NO
**Is port 80 and/or 443 open?**
YES
## Logs / Screenshots

To activate the new configuration, you need to run:
  systemctl reload apache2
/etc/apache2/sites-available/onlyoffice.domain.conf was successfully created.
certbot 0.31.0
certbot 0.31.0
onlyoffice.sh: line 158: le_subdomain: command not found
It seems like no certs were generated, please report this issue here: https://github.com/nextcloud/vm/issues

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi!

Thanks for posting your issue!

Actually, we just changed the way certs are generated, so you need to update to the latest script to get the latest functions.

Download the RAW file here: https://github.com/nextcloud/vm/blob/master/apps/onlyoffice.sh
