### ISSUE TITLE
Hyper V install - Display stays black when booting ?

### ISSUE THREAD

**Issue by Mike-kk-de** [nextcloud/vm#1032]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi,

I need more info to be able to debug.

Thanks!

**Comment by Mike-kk-de** [comment]
Hi,

i already solved it. thanks.
It was the Graphicdriver vom AMD Onboard. Using the default Microsoft Display Driver did the trick.


Für Rückfragen stehe Ich gerne zur Verfügung
Mit freundlichen Grüßen
Michael Ramb
|rambedv.de<http://rambedv.de/>
Inh. Michael Ramb | Büroanschrift: Grüner Weg 2, 47906 Kempen
Technik: Flughafenstr. 34 , 41066 Mönchengladbach
Telefon: 02152-8925700 | Telefax: 02152-8925710 | Mobil: 0173-9377211
E-Mail: ramb@rambedv.de<mailto:ramb@rambedv.de>

Finanzamt Kempen | Steuernummer: 115/5154/1029 | Ust-Id.-Nr. DE119166790

Von: Daniel Hansson <notifications@github.com>
Gesendet: Montag, 13. Januar 2020 14:32
An: nextcloud/vm <vm@noreply.github.com>
Cc: Michael Ramb <ramb@rambedv.de>; Author <author@noreply.github.com>
Betreff: Re: [nextcloud/vm] Hyper V install - Display stays black when booting ? (#1032)


Hi,

I need more info to be able to debug.

Thanks!
