### ISSUE TITLE
Notify about app updates 

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1037]
@szaimen If you feel like it, please create a PR for app updates as well.

As we discussed in https://github.com/nextcloud/vm/pull/1035

**Comment by szaimen** [comment]
As a note to myself:
occ app:disable updatenotification
send a notification that app updates got installed if [ $(occ_command app:update --all) != "" ]

**Comment by enoch85** [comment]
`if [ -z stuff ]` checks if a $var is empty btw, `if [ -n stuff ]` checks if it's not empty.
