### ISSUE TITLE
nextcloud_install_production.sh installation script appears broken

### ISSUE THREAD

**Issue by infidelus** [nextcloud/vm#1039]
## Steps to reproduce
1. Run script
2. get to 'Configuring update notifications specific for this server...'
3. script errors out

## Expected behaviour
Tell us what should happen

Script should complete resulting in successful installation.  Script worked yesterday.

## Actual behaviour
Tell us what happens instead

Configuring update notifications specific for this server...
{updatenotification.sh} failed to download. Please run: 'sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/updatenotification.sh.sh|.php|.py' again.
If you get this error when running the nextcloud-startup-script then just re-run it with:
'sudo bash /var/scripts/nextcloud-startup-script.sh' and all the scripts will be downloaded again

Have tried twice from clean VM (VirtualBox) install.  Failed at same place both times today.

## Server configuration

**Nextcloud server version:** (see your admin page)

17.0.2.1

**Server OS** (Ubuntu server is default)

Ubuntu

**How did you install the VM?** (Scripted install from master **OR** Released version)

Release version - 18.04.3

## Network
**Do you use DHCP?**

No, static configuration

**Is port 80 and/or 443 open?**

Yes

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```
Empty logfile as script didn't finish install

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Thanks! Made some updates today, missed this bug.
