### ISSUE TITLE
What about putting all app options into a seperate script?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1041]
What about putting the whole section followed by this line https://github.com/nextcloud/vm/blob/e051e3240e7a3026e7e39e05bae148b93ef6e5f1/nextcloud-startup-script.sh#L432 into an app script or main script that can get called by the startup script? (it would end at line 515)

Then you would have the possibility to execute only this script afterwards (when trying to install a new app) and see all available apps in one place. This would be better imo then having to look elsewhere for available apps...

Btw: I would also like to put https://github.com/nextcloud/vm/blob/e051e3240e7a3026e7e39e05bae148b93ef6e5f1/nextcloud-startup-script.sh#L375 into a new script, that could get called by the startup script...

**Comment by enoch85** [comment]
I vote no, please see comment in #1038 

Feel free to close.

**Comment by szaimen** [comment]
The idea was especially having a main menu for installing additional apps later on, but if you don't like it, I am okay with that.

**Comment by enoch85** [comment]
Let me think about it.

**Comment by szaimen** [comment]
I would imagine something like the nextcloud update script:
You call an apps.sh static script, that is inside $SCRIPTS directory, that automatically fetches the main script additional_apps.sh from the repository. The additional_apps.sh script is then the main menu to install additional apps. Then you would not longer need the $SCRIPTS/apps dir.
What do you think?

**Comment by enoch85** [comment]
Hmm. Problem with that is that you need to keep everything backwards compatible. It mostly is already, but yeah...

What you mean is something like the `update.sh` script where you just run `update.sh` to get the latest `nextcloud_update.sh`, but like a built in function instead. So something like:

`sudo bash install_app.sh collabora` or
`sudo bash install_app.sh talk`or
`sudo bash install_app.sh fts`

Right?

Make a PR and we'll discuss, I actually think it's a pretty good idea. :)

**Comment by szaimen** [comment]
Not completely, but I will make a PR and show you what I mean with that.
