### ISSUE TITLE
Onlyoffice out of the box?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1048]
Have you seen this on the Nextcloud 18 publication site?
![image](https://user-images.githubusercontent.com/42591237/72716160-0ede9480-3b72-11ea-8201-188cb3af7bf4.png)
So does that mean, that the onlyoffice script is no longer needed?
I have to try it myself later on.
Here is the link: https://nextcloud.com/blog/the-new-standard-in-on-premises-team-collaboration-nextcloud-hub/

**Comment by szaimen** [comment]
I found this: https://apps.nextcloud.com/apps/documentserver_community

**Comment by enoch85** [comment]
I haven't had the time to investigate yet, a lot of stuff happening in my day-to-day life right now.

**Comment by enoch85** [comment]
Had a quick look in my personal NC 18, didn't find any "magic button" for installing OnlyOffice.. :)

**Comment by szaimen** [comment]
The trick is to install this app:
https://apps.nextcloud.com/apps/documentserver_community

**Comment by enoch85** [comment]
Wooow! If it's that easy I'm amazed! Please try and come back with the results.

**Comment by szaimen** [comment]
> Wooow! If it's that easy I'm amazed! Please try and come back with the results.

Yes, I am also very satisfied by that!
I have already tested it on an upgraded Test VM and it works. 
But I am not sure, if that is as reliably as the scripted install since it is an really new app.
We could of course just change the script to `install_and_enable documentserver_community`
What do you think?

**Comment by szaimen** [comment]
I have tried it but I think you have to install onlyoffice first:
so this should do the trick:
```
install_and_enable_app onlyoffice
install_and_enable_app documentserver_community
```
But it is not reliably in the moment, since the documentserver is that big:
https://github.com/nextcloud/server/pull/18976

**Comment by szaimen** [comment]
So I would propose testing this when the bugfix is released (probably with 18.0.1) and thinking about substituting the code in the onlyoffic.sh file then.

**Comment by oezh** [comment]
My onlyoffice stoped working after update from 17 to 18. https://oo.server.com/healthcheck returns True, Saving on Nextcloud Connector config returns Ok with no errors (for both, Docker from onlyoffice.sh and Community Document Server on their respective address). But when going to files and click an office file it gets downloaded instead of opened in onlyoffice. Also, the "create new" (+) file button doesn't show any office mime type file. Seems like missing config or something. Am I missing something?

**Comment by oezh** [comment]
Seems to be problem with Full Text search app. Disable it and only office works Ok again.

**Comment by enoch85** [comment]
cc @Ark74 @daita 

>  Seems to be problem with Full Text Search app.

@szaimen Just read this: https://github.com/nextcloud/documentserver_community#setup-from-git So it seems like docker is needed after all.

**Comment by szaimen** [comment]
> @szaimen Just read this: https://github.com/nextcloud/documentserver_community#setup-from-git So it seems like docker is needed after all.

Yes, but for the user is no setup and configuring needed, so kind of perfect.

**Comment by Ark74** [comment]
And a possible nightmare for hosting companies.

A nice time to own a VPS company :+1:

**Comment by enoch85** [comment]
@szaimen I will actually do some support for OnlyOffice next week, will have a look at it then, and might change something. We'll see.

**Comment by enoch85** [comment]
I tested to do "the recomended way", using make and just installing the app. Didn't work. 

So I guess this has to wait until it's stable.

**Comment by szaimen** [comment]
This was my proposal:
> So I would propose testing this when the bugfix is released (probably with 18.0.1) and thinking about substituting the code in the onlyoffice.sh file then.

**Comment by enoch85** [comment]
What's needed:

1. Docker
2. Build essentials
3. Run the make install
4. Install the Onlyoffice apps.

If you make a PR I'm happy to review!

**Comment by szaimen** [comment]
I've just upgraded a test vm (with working certificate) to 18.0.1 and this works:
```
install_and_enable_app onlyoffice
install_and_enable_app documentserver_community
```

But you could test it as well.

> Docker
> Build essentials
> Run the make install
> Install the Onlyoffice apps.

So this is not needed (only if you install it from git and not from the appstore)

**Comment by enoch85** [comment]
> and this works

Great news! Did it work straight out of the box, no additional stuff needed?

**Comment by szaimen** [comment]
Yes but it needs its time! (A few minutes for installing the documentserver on my machine)

**Comment by enoch85** [comment]
> Yes but it needs its time! 

Is it possible to catch errors on the way? What does the output look like?

**Comment by szaimen** [comment]
> Is it possible to catch errors on the way?

no, I don't think so. I've just tested it on 18.0.0 and there was a timeout issue, which was thrown out. But the occ_command should handle this ;)

> What does the output look like?

Now if I test it, it works always but it just says documentservery installed and enabled since it is like a normal app. 

Just test this PR out, if you are intereted :)

What is needed though is maybe a spinning wheel to show that the documentservery is getting installed since you get no visual feedback and it can need a few minutes which can leed to the wrong idea, that something didn't work...
But spinner_loading doesn*t work here...

**Comment by szaimen** [comment]
I could try to explain how it works if you want...

**Comment by enoch85** [comment]
This is now fixed
