### ISSUE TITLE
one last addition for the 18.0.0 release?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1052]
I would like to add the following option to the startup script to let the user configure, whether he wants to get all shares in his root directory or in a folder.
`occ_command config:system:set share_folder --value="/Shared"`

I would then add this as an option to here: https://github.com/nextcloud/vm/blob/cb9d8bc36a4b53c1d01cd0702c15a61c7dc7f2b4/nextcloud-startup-script.sh#L375

I think this makes a lot of sense, since your root directory gets very fast really cluttered, if you get a lot of shares. (imo this should be the default setting for every nextcloud instance)

**Comment by enoch85** [comment]
Add it to the smbmount script instead, right?

**Comment by szaimen** [comment]
No, this works for all instances. Not only if smbshares is configured.
(All shares that you get will appear in the Shared folder and not in your Nextcloud root directory)

**Comment by enoch85** [comment]
Please make a PR and we'll discuss.

**Comment by szaimen** [comment]
> Please make a PR and we'll discuss.

done 👍

**Comment by enoch85** [comment]
Weäll continue the discussion in the PR instead.
