### ISSUE TITLE
Things to fix before new release

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1053]
- [x] Check if sha256sum is installed before checking sum of the downloaded Nextcloud  tar.
- [x] `grep -r` for all the places where we should replace `sudo -u www-data php $NCPATH/occ`

**Comment by enoch85** [comment]
cc @szaimen Feel free to add stuff.

**Comment by szaimen** [comment]
- [ ] update docs based on https://github.com/nextcloud/vm/pulls?utf8=%E2%9C%93&q=author%3Aszaimen+
- [ ] https://github.com/nextcloud/vm/pull/1051
- [ ] https://github.com/nextcloud/vm/pull/1054

**Comment by enoch85** [comment]
I want to make a new release this weekend. 

So, share-folder and the points I added are enough for me. We can do the docs stuff meanwhile.

**Comment by enoch85** [comment]
I will test tomorrow, if nothing comes up I'll start with a new release.
