### ISSUE TITLE
Update the docs based on my PRs

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1055]
This is intended as a checklist for updating the docs based on [my PRs](https://github.com/nextcloud/vm/pulls?utf8=%E2%9C%93&q=author%3Aszaimen+)
- [ ] sudo -i 
nextcloud_occ; run_update_nextcloud (minor); additional_apps; nextcloud_configuration
- [ ] update available apps and default apps
- [ ] put share_folder explanation into the docs

**Comment by szaimen** [comment]
@enoch85 btw: I would also link to the home website of your docs on this github repo readme file since there you get there an overview of available documentation.

**Comment by enoch85** [comment]
> @enoch85 btw: I would also link to the home website of your docs on this github repo readme file since there you get there an overview of available documentation.

You mean this: https://github.com/nextcloud/vm#full-documentation? :)

**Comment by szaimen** [comment]
> > @enoch85 btw: I would also link to the home website of your docs on this github repo readme file since there you get there an overview of available documentation.
> 
> You mean this: https://github.com/nextcloud/vm#full-documentation? :)

Yes 👍

**Comment by enoch85** [comment]
Just updated the FAQ a bit. Check out if there's anything you would like to add:
https://docs.hanssonit.se/s/bj101nihv0jgrmfm09f0/faq/d/bj101pihv0jgrmfm0a10/nextcloud-vm?currentPageId=bj101sqhv0jgrmfm0a1g

**Comment by szaimen** [comment]
I think it is quite good, maybe a hint that nextcloud_configuration can get executed later on would be also good.
BTW: i've just send you en e-mail with some documentation in it ;)

**Comment by enoch85** [comment]
Let's close this.
