### ISSUE TITLE
18.0.1

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1057]
- [x] https://github.com/nextcloud/vm/pull/1054 share-folder

cc @szaimen

**Comment by szaimen** [comment]
- [ ] https://github.com/nextcloud/vm/issues/1048 OnlyOffice script change?
- [ ] tba

**Comment by enoch85** [comment]
@szaimen Please work on the docs. Make a document and send me so that I can upload it, or try to make your own on docs.hanssonit.se.

We'll move OnlyOffice to "maybe some day" since I've tested it several times now, and the current implementation works.

**Comment by szaimen** [comment]
> @szaimen Please work on the docs. Make a document and send me so that I can upload it.

Thanks for the offer. That sounds very reasonable! 👍

The thing is, that I am currently working on my Bachelorthesis and the docs will need a lot of time as well, I suppose. 
I will have time for this starting at the 12.2... I hope this is not too late for the 18.0.1 release.

**Comment by enoch85** [comment]
@szaimen Fine with me, we all have a life to attend. :)

**Comment by szaimen** [comment]
> @szaimen Please work on the docs. Make a document and send me so that I can upload it.

Which file format do you need? I would start working on this approximately tomorrow evening.

**Comment by enoch85** [comment]
What ever works with you.

Libreoffice Writer maybe?

**Comment by szaimen** [comment]
I've started with the document but am not ready yet.

**Comment by enoch85** [comment]
OK, no rush, I don't plan to release 18.0.1 until all PRs are merged anyway.
