### ISSUE TITLE
Fix choice in while loops

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1058]
https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L165-L166

Fix in all places!

**Comment by enoch85** [comment]
apps/previewgenerator.sh:    done 11< results
apps/previewgenerator.sh:    done 8< results
nextcloud_install_production.sh:choice=$(< results)
nextcloud_install_production.sh:choice=$(< results)
nextcloud_install_production.sh:done 11< results
nextcloud-startup-script.sh:done 9< results
additional_apps.sh:done 11< results

**Comment by enoch85** [comment]
Done in https://github.com/nextcloud/vm/pull/1059

**Comment by enoch85** [comment]
Just for reference:

`whiptails` with `--checklist` must be:

```
while read -r choice <-------
do <-------
    case "$choice" in <-------
        ..................
        ;;
        *)
        ;;
    esac
done < results <-------
rm -f results
```

`whiptails` with `--radiolist` must be:
```
choice=$(< results)  <-------
    case "$choice" in  <-------
    .....................
        ;;
        *)
        ;;
    esac
rm -f results
```

**Comment by enoch85** [comment]
FYI @szaimen

**Comment by szaimen** [comment]
But I guess you could also solve at least the radiolist like in the cookielifetime script
(With if and elif)

**Comment by enoch85** [comment]
Actually, I think this was strange: https://github.com/nextcloud/vm/blob/master/apps/smbmount.sh#L266-L295 and I was about to change it to this https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L160-L179

But I thought maybe you had a plan. Everything is solved now anyway, testing as we speak.

**Comment by szaimen** [comment]
> Actually, I think this was strange: https://github.com/nextcloud/vm/blob/master/apps/smbmount.sh#L266-L295 and I was about to change it to this https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L160-L179
> 
> But I thought maybe you had a plan. Everything is solved now anyway, testing as we speak.

Both methods should work 👍

**Comment by enoch85** [comment]
> Both methods should work +1

I think we should use the same code everywhere. Please change to the standard used in all other places.

Thanks!

**Comment by enoch85** [comment]
`whiptails` are still broken........

Too tired now, have to sleep.

If you have time, please test all of them and try to fix it. 

Thanks!

**Comment by enoch85** [comment]
OK, think I found it. The number must be equal to the number of choices. 

We must revert to the old method: https://github.com/nextcloud/vm/commit/cc0e28b77388d90c2fd00dd5b58bde4e35c9e460#diff-2912af18ccc7a96fbdf15892788006f2

**Comment by szaimen** [comment]
Wouldn't something like this work for radiolist and checklist?
That would be the cleanest way to do it imo.
Sry, have no time to look into this in the moment.

choice=$(whiptail --radiolist  "text" "$WT_HEIGHT" "$WT_WIDTH" 4 \
"option 1" "description 1" ON \
"option 2" "description 1" OFF \
"option 3" "description 1" OFF 3>&1 1>&2 2>&3)

case "$choice" in
    "option 1")
        run command 1
    ;;
    "option 2")
        run command 2
    ;;
    "option 3")
        run command 3
    ;;
    *)
    ;;
esac

choice=$(whiptail --checklist  "text" "$WT_HEIGHT" "$WT_WIDTH" 4 \
"option 1" "description 1" ON \
"option 2" "description 1" OFF \
"option 3" "description 1" OFF 3>&1 1>&2 2>&3)

for element in "$choice"
do
    case "$element" in
        "option 1")
            run command 1
        ;;
        "option 2")
            run command 2
        ;;
        "option 3")
            run command 3
        ;;
        *)
        ;;
    esac
done

**Comment by szaimen** [comment]
And do we need the backslashes in the whiptile list?

**Comment by szaimen** [comment]
And i am actually not sure if we need the for loop for the checklist

**Comment by enoch85** [comment]
Let me fix it temporarily for now, we can improve the whiptails in 18.0.1.

**Comment by enoch85** [comment]
> And i am actually not sure if we need the for loop for the checklist
(So I would test if my proposed solution for the checklist works without the for loop, but if not, it should work as it is)

What I would prefer is something that we can copy and paste without thinking. Generic code that aren't specific to the lines it's used for.

So, if we can use something where we don't have to remember what the "11" did in the `while` loop in 3 years, *that's* what I want to use. :)

**Comment by szaimen** [comment]
> What I would prefer is something that we can copy and paste without thinking. Generic code that aren't specific to the lines it's used for.
> 
> So, if we can use something where we don't have to remember what the "11" did in the `while` loop in 3 years, _that's_ what I want to use. :)

That is exactly what the proposed code should do 👍

**Comment by enoch85** [comment]
Great!

Can you please test all scenarios?

1. Choose all options
2. Choose all but one
3. Choose all but 2
4. Choose all but 3
5. ...
6. ...
7. ...
8. Choose only 1 option at the time
9. Choose Each option separately

I will dig in later tonight.

**Comment by szaimen** [comment]
> Great!
> 
> Can you please test all scenarios?
> 
> 1. Choose all options
> 2. Choose all but one
> 3. Choose all but 2
> 4. Choose all but 3
> 5. ...
> 6. ...
> 7. ...
> 8. Choose only 1 option at the time
> 9. Choose Each option separately
> 
> I will dig in later tonight.

I cannot test this atm. I can do it this evening.

**Comment by enoch85** [comment]
> I can do it this evening.

Thanks! Same here. :+1:

**Comment by szaimen** [comment]
I am testing this now. Seems not to work. but I will come up with a solution.

**Comment by szaimen** [comment]
So I ways not absolutely correct: the radiolist algorithm does work perfectly, but not the checklist.

**Comment by enoch85** [comment]
`checklist` is a hard nut to crack. :)

**Comment by enoch85** [comment]
Just tested the current code btw, everything works as expected.

Release time!

**Comment by szaimen** [comment]
I found a working solution!
```
choice=$(whiptail --checklist  "text" "$WT_HEIGHT" "$WT_WIDTH" 4 \
"option 1" "description 1" ON \
"option 2" "description 2" OFF \
"option 3" "description 3" OFF 3>&1 1>&2 2>&3)


case "$choice" in
    *"option 1"*)
        echo "run command 1"
    ;;&
    *"option 2"*)
        echo "run command 2"
    ;;&
    *"option 3"*)
        echo "run command 3"
    ;;&
    *)
    ;;
esac
```

**Comment by szaimen** [comment]
Now everything should work. 

### Here the summary:

everything works now in a consecutive order:
`msg_box -> inputbox -> radiolist -> checklist`

msg_box:
`whiptail --msgbox "text" "$WT_HEIGHT" "$WT_WIDTH"`

inputbox:
`input=$(whiptail --inputbox "text" "$WT_HEIGHT" "$WT_WIDTH" 3>&1 1>&2 2>&3)`

radiolist:
```
choice=$(whiptail --radiolist  "text" "$WT_HEIGHT" "$WT_WIDTH" 4 \
"option 1" "description 1" ON \
"option 2" "description 2" OFF \
"option 3" "description 3" OFF 3>&1 1>&2 2>&3)

case "$choice" in
    "option 1")
        run command 1
    ;;
    "option 2")
        run command 2
    ;;
    "option 3")
        run command 3
    ;;
    *)
    ;;
esac
```

checklist:
```
choice=$(whiptail --checklist  "text" "$WT_HEIGHT" "$WT_WIDTH" 4 \
"option 1" "description 1" ON \
"option 2" "description 2" OFF \
"option 3" "description 3" OFF 3>&1 1>&2 2>&3)


case "$choice" in
    *"option 1"*)
        echo "run command 1"
    ;;&
    *"option 2"*)
        echo "run command 2"
    ;;&
    *"option 3"*)
        echo "run command 3"
    ;;&
    *)
    ;;
esac
```

**Comment by szaimen** [comment]
of course we could make the radiolist to look like the checklist (the only change would be --radiolist instead of --checklist) but that is you decision.

**Comment by szaimen** [comment]
Btw: if we do the checklist like it is done here, we should remove the --seperate_output option from the whiptails.

**Comment by szaimen** [comment]
@enoch85 any thoughts on this?
https://github.com/nextcloud/vm/issues/1058#issuecomment-578426862

**Comment by enoch85** [comment]
> @enoch85 any thoughts on this?

Do you use git in CLI? If not, please do. It's much easier to find occurrences like `whiptail` which you can `grep -r whiptail` and replace in all places instantly. 

I'm OK with changing if it works equal or better than the current implementation. 

Though I don't get the difference between: https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L160-L180 and this suggestion?

Example, here you use ` 3>&1 1>&2 2>&3)` and you put the` whiptail` as a variable `$choice`. Why?

Also maybe I'm slow, but what does this mean:

>everything works now in a consecutive order:
msg_box -> inputbox -> radiolist -> checklist

>msg_box:
whiptail --msgbox "text" "$WT_HEIGHT" "$WT_WIDTH"

>inputbox:
input=$(whiptail --inputbox "text" "$WT_HEIGHT" "$WT_WIDTH" 3>&1 1>&2 2>&3)

**Comment by szaimen** [comment]
> Example, here you use ` 3>&1 1>&2 2>&3)` and you put the` whiptail` as a variable `$choice`. Why?

Because I like it more having the output in a variable and not in a file, that I have to remove later on.
BTW: what `3>&1 1>&2 2>&3` does is it redirects the output to the variable. So in conclusion you are just redirecting the output of the whiptail to the variable. In comparison: `2>results` creates a file.

> I'm OK with changing if it works equal or better than the current implementation.

I think so, with my implementation you need no longer a loop. You just could try the script above: https://github.com/nextcloud/vm/issues/1058#issuecomment-578426601

What I mean with consecutive order is, you add things based on the predecessor: 
1. The msg_box is the default one with whiptail, whiptail-option, text and Height/Width.
2. for the inputbox, (in comparison to msg_box) you add redirecting the output to a variable and change the whiptail-option. 
3. for the radiolist, (in comparison to inputbox) you add list-options and the case-statement, and change the whiptail-option. 
4. for the checklist, (in comparison to radiolist) you change the case-statement and the whiptail-option.

I hope this explains everything.

> It's much easier to find occurrences like whiptail which you can grep -r whiptail and replace in all places instantly.

I am really not sure, if that would work here, since the formatting would get changed and the options are inside the whiptail, so I would use that to get all places, but change it by hand later on.

**Comment by szaimen** [comment]
@enoch85 my comment should now be readable. I have also added some things to it so please read it again, if you already have done that.

**Comment by enoch85** [comment]
OK, now I get it, it's better to put it in a variable to remove the need for reading from a file, simply put.

Let's do this then!

> I am really not sure, if that would work here

Yes, it works: 

```
root@xps13:~/vm# grep -r whiptail
apps/smbmount.sh:    SERVER_SHARE_NAME=$(whiptail --inputbox "Please enter the server and Share-name like this:\n//Server/Share" "$WT_HEIGHT" "$WT_WIDTH" 3>&1 1>&2 2>&3)
apps/smbmount.sh:    SMB_USER=$(whiptail --inputbox "Please enter the username of the SMB-user" "$WT_HEIGHT" "$WT_WIDTH" 3>&1 1>&2 2>&3)
apps/smbmount.sh:    SMB_PASSWORD=$(whiptail --inputbox "Please enter the password of the SMB-user $SMB_USER" "$WT_HEIGHT" "$WT_WIDTH" 3>&1 1>&2 2>&3)
apps/smbmount.sh:args=(whiptail --title "Mount SMB-shares" --checklist --separate-output "This option let you mount SMB-shares to connect to network-shares from the host-computer or other machines in the local network.\nChoose which one you want to mount.\nIf nothing is shown, then there is nothing to mount.\nSelect or unselect by pressing the spacebar" "$WT_HEIGHT" "$WT_WIDTH" 4)
apps/smbmount.sh:args=(whiptail --title "List SMB-shares" --checklist "This option let you show detailed information about your SMB-shares.\nChoose which one you want to show.\nSelect or unselect by pressing the spacebar" "$WT_HEIGHT" "$WT_WIDTH" 4)
apps/smbmount.sh:args=(whiptail --title "Unmount SMB-shares" --checklist "This option let you unmount SMB-shares to disconnect network-shares from the host-computer or other machines in the local network.\nChoose what you want to do.\nSelect or unselect by pressing the spacebar" "$WT_HEIGHT" "$WT_WIDTH" 4)
apps/smbmount.sh:args=(whiptail --title "Delete SMB-mounts" --checklist --separate-output "This option let you delete SMB-shares to disconnect and remove network-shares from the Nextcloud VM.\nChoose what you want to do.\nSelect or unselect by pressing the spacebar" "$WT_HEIGHT" "$WT_WIDTH" 4)
apps/smbmount.sh:    choice=$(whiptail --title "SMB-share" --radiolist  "This script let you manage SMB-shares to access files from the host-computer or other machines in the local network.\nChoose what you want to do.\nSelect one with the [ARROW] keys and select with the [SPACE] key. Confirm by pressing [ENTER]" "$WT_HEIGHT" "$WT_WIDTH" 4 \
apps/previewgenerator.sh:    whiptail --title "Choose file formats" --checklist --separate-output "Now you can choose for which file formats you would like to generate previews for\nSelect or unselect by pressing the spacebar" "$WT_HEIGHT" "$WT_WIDTH" 4 \
apps/previewgenerator.sh:    whiptail --title "Choose file formats" --checklist --separate-output "Now you can choose for which file formats you would like to generate previews for\nSelect or unselect by pressing the spacebar" "$WT_HEIGHT" "$WT_WIDTH" 4 \
apps/previewgenerator.sh:        PREVIEW_USER=$(whiptail --inputbox "Enter the Nextcloud user for which you want to run the preview-generation" "$WT_HEIGHT" "$WT_WIDTH" 3>&1 1>&2 2>&3)
apps/additional_apps.sh:whiptail --title "Which apps do you want to install?" --checklist --separate-output "Automatically configure and install selected apps\nSelect by pressing the spacebar" "$WT_HEIGHT" "$WT_WIDTH" 4 \
lib.sh:[ -n "$OO_INSTALL" ] && SUBDOMAIN=$(whiptail --title "T&M Hansson IT - OnlyOffice" --inputbox "OnlyOffice subdomain eg: office.yourdomain.com\n\nNOTE: This domain must be different than your Nextcloud domain. They can however be hosted on the same server, but would require seperate DNS entries." "$WT_HEIGHT" "$WT_WIDTH" 3>&1 1>&2 2>&3)
lib.sh:[ -n "$OO_INSTALL" ] && NCDOMAIN=$(whiptail --title "T&M Hansson IT - OnlyOffice" --inputbox "Nextcloud domain, make sure it looks like this: cloud\\.yourdomain\\.com" "$WT_HEIGHT" "$WT_WIDTH" cloud\\.yourdomain\\.com 3>&1 1>&2 2>&3)
lib.sh:[ -n "$COLLABORA_INSTALL" ] && SUBDOMAIN=$(whiptail --title "T&M Hansson IT - Collabora" --inputbox "Collabora subdomain eg: office.yourdomain.com\n\nNOTE: This domain must be different than your Nextcloud domain. They can however be hosted on the same server, but would require seperate DNS entries." "$WT_HEIGHT" "$WT_WIDTH" 3>&1 1>&2 2>&3)
lib.sh:[ -n "$COLLABORA_INSTALL" ] && NCDOMAIN=$(whiptail --title "T&M Hansson IT - Collabora" --inputbox "Nextcloud domain, make sure it looks like this: cloud\\.yourdomain\\.com" "$WT_HEIGHT" "$WT_WIDTH" cloud\\.yourdomain\\.com 3>&1 1>&2 2>&3)
lib.sh:[ -n "$TLS_INSTALL" ] && TLSDOMAIN=$(whiptail --title "T&M Hansson IT - Let's Encrypt" --inputbox "Please enter the domain name you will use for Nextcloud.\n\nMake sure it looks like this:\nyourdomain.com, or cloud.yourdomain.com" "$WT_HEIGHT" "$WT_WIDTH" cloud.yourdomain.com 3>&1 1>&2 2>&3)
lib.sh:    whiptail --title "Nextcloud VM - T&M Hansson IT - $(date +"%Y")" --msgbox "${PROMPT}" "$WT_HEIGHT" "$WT_WIDTH"
static/cookielifetime.sh:choice=$(whiptail --radiolist  "Configure the logout time (in seconds) which will forcefully logout the Nextcloud user from the web browser when the timeout is reached.\n\nSelect one with the [ARROW] keys and select with the [SPACE] key. Confirm by pressing [ENTER]" "$WT_HEIGHT" "$WT_WIDTH" 4 \
static/cookielifetime.sh:            COOKIE_LIFETIME=$(whiptail --inputbox "Configure the logout time (in seconds) which will forcefully logout the Nextcloud user from the web browser when the timeout is reached.\n\nPlease enter the Cookie Lifetime in seconds, so e.g. 1800 for 30 minutes or 3600 for 1 hour\n\n You can not set a value below 30 minutes (1800 seconds)." "$WT_HEIGHT" "$WT_WIDTH" 1800 3>&1 1>&2 2>&3)
nextcloud_install_production.sh:if [ "$(dpkg-query -W -f='${Status}' "whiptail" 2>/dev/null | grep -c "ok installed")" == "1" ]
nextcloud_install_production.sh:    print_text_in_color "$IGreen" "whiptail OK"
nextcloud_install_production.sh:    apt install whiptail -y
nextcloud_install_production.sh:whiptail --title "Choose disk format" --radiolist --separate-output "How would you like to configure your disks?\nSelect by pressing the spacebar and ENTER" "$WT_HEIGHT" "$WT_WIDTH" 4 \
nextcloud_install_production.sh:whiptail --title "Set DNS Resolver" --radiolist --separate-output "Which DNS provider should this Nextcloud box use?\nSelect by pressing the spacebar and ENTER" "$WT_HEIGHT" "$WT_WIDTH" 4 \
nextcloud_install_production.sh:whiptail --title "Install apps or software" --checklist --separate-output "Automatically configure and install selected apps or software\nDeselect by pressing the spacebar" "$WT_HEIGHT" "$WT_WIDTH" 4 \
nextcloud-startup-script.sh:whiptail --title "Extra configurations" --checklist --separate-output "Choose what you want to configure\nSelect by pressing the spacebar" "$WT_HEIGHT" "$WT_WIDTH" 4 \
root@xps13:~/vm# 
```

Please prepare a PR where we set a new standard for all whiptails.

**Comment by szaimen** [comment]
> > I am really not sure, if that would work here
> 
> Yes, it works:

Was I meant was the automatic replacement for all whiptails but okay 👍
I will prepare a PR.
