### ISSUE TITLE
Make the option to exit smbmont.sh more obvius

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1065]
@szaimen Please add an option which is "Exit this script" instead of having to TAB to cancel to exit. Right now that's not obvious at the moment. 

Please also fix the last `whiptail` so that it follows the standard of the rest of the scripts.

Thanks!

**Comment by szaimen** [comment]
I will do that if you are okay, with the new way of doing whiptails: https://github.com/nextcloud/vm/issues/1058#issuecomment-578426862

**Comment by szaimen** [comment]
I would then also fix it in cookielifetime

**Comment by szaimen** [comment]
all should be fixed with https://github.com/nextcloud/vm/pull/1069
