### ISSUE TITLE
Check if the whole network-manager package is really needed for network_ok()

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1067]
As the title says.

**Comment by szaimen** [comment]
@enoch85 Couldn't you use this: (ping should be default on Ubuntu installs)
```
    # Test internet connection
    if ! ping -c1 -W1 github.com &>/dev/null
    then
        echo "Couldn't reach github.com. Exiting..."
        exit 1
    fi
```

**Comment by enoch85** [comment]
Yes and no. The issue here is that we need backwards compatibility and just restarting `networking` doesn't do it, at least from my testing. `ifconfig` isn't even a tool in 18.04 anymore, and has to be manually installed.

https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L85-L89

I'm thinking we will ditch compbility with 16.04 once 20.04 is out and tested for a few months. Would make my life easier, and yours too. :) I'd like it to be as clean as possible, and regarding the network part, a lot of stuff changed from 16.04 to 18.04 since `netplan` was introduced.

**Comment by szaimen** [comment]
Ah okay, I thought that the `network_ok` function was only checking if it can reach github.com...

**Comment by enoch85** [comment]
It's now deprecated in 20.04
