### ISSUE TITLE
nextcloud_install_production.sh not working

### ISSUE THREAD

**Issue by tammer123** [nextcloud/vm#1073]
## Steps to reproduce
1. sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh)"

## Expected behaviour
Normal script install

## Actual behaviour
After doing `sudo -u ncadmin sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh)"`

```
curl OK

bash: line 22: is_process_running: command not found

bash: line 23: is_process_running: command not found

bash: line 28: print_text_in_color: command not found

bash: line 37: print_text_in_color: command not found

bash: line 46: print_text_in_color: command not found

bash: line 63: debug_mode: command not found

bash: line 66: root_check: command not found

bash: line 71: print_text_in_color: command not found

bash: line 72: ask_yes_or_no: command not found

Your console font configuration will be updated the next time your system
boots. If you want to update it now, run 'setupcon' from a virtual console.

update-initramfs: deferring update (trigger activated)

Processing triggers for initramfs-tools (0.130ubuntu3.9) ...

update-initramfs: Generating /boot/initrd.img-4.15.0-72-generic

bash: line 78: msg_box: command not found
```

And after reboot the circle goes again.

## Server configuration

**Server OS** 

Ubuntu 18.04.3 LTS

**Comment by tammer123** [comment]
Fixed it myself. Just needed to `chmod +x nextcloud_install_production.sh` and it worked.

**Comment by tammer123** [comment]
I retract what I said before. Still the same error/loop.

**Comment by enoch85** [comment]
It seems to me that you don't have internet. The lib.sh can't be fetched, hence the functions can't be fetched which results in that error.
