### ISSUE TITLE
Updating to Nextcloud 18 causes css issues.

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/vm#1075]
Upgrading from 17 to 18 using the /var/script/update.sh script causes css issues. It is also taking forever to get a reply from the server now.

Here's the update log:
[update.zip](https://github.com/nextcloud/vm/files/4123829/update.zip)
![image](https://user-images.githubusercontent.com/7028351/73290676-d7ed2c00-41cc-11ea-909a-0539aa01336b.png)

**Comment by BetaLeaf** [comment]
I may or may not have interrupted the update. It seemed to freeze, but when I read back the log after rebooting, it was showing the update success splash screen. I think it finished, but I may be wrong too.

**Comment by BetaLeaf** [comment]
![image](https://user-images.githubusercontent.com/7028351/73290921-37e3d280-41cd-11ea-9de6-4164e032d357.png)

**Comment by BetaLeaf** [comment]
Is there any way to fix/downgrade/restore/etc and get my installation working again?

**Comment by enoch85** [comment]
I didn't find anything unusual in the logs, except this:

```
Disabled incompatible app: announcementcenter
Disabled incompatible app: apporder
Disabled incompatible app: audioplayer
Disabled incompatible app: audioplayer_editor
Disabled incompatible app: bookmarks
Disabled incompatible app: calendar
Disabled incompatible app: camerarawpreviews
Disabled incompatible app: checksum
Disabled incompatible app: contacts
Disabled incompatible app: cookbook
Disabled incompatible app: dicomviewer
Disabled incompatible app: drawio
Disabled incompatible app: event_update_notification
Disabled incompatible app: external
Disabled incompatible app: extract
Disabled incompatible app: files_accesscontrol
Disabled incompatible app: files_automatedtagging
Disabled incompatible app: files_fulltextsearch
Disabled incompatible app: files_markdown
Disabled incompatible app: files_photospheres
Disabled incompatible app: files_readmemd
Disabled incompatible app: files_trackdownloads
Disabled incompatible app: forms
Disabled incompatible app: fulltextsearch
Disabled incompatible app: fulltextsearch_elasticsearch
Disabled incompatible app: gallery
Disabled incompatible app: groupfolders
Disabled incompatible app: issuetemplate
Disabled incompatible app: mail
Disabled incompatible app: metadata
Disabled incompatible app: music
Disabled incompatible app: news
Disabled incompatible app: notes
Disabled incompatible app: onlyoffice
Disabled incompatible app: polls
Disabled incompatible app: previewgenerator
Disabled incompatible app: printer
Disabled incompatible app: quota_warning
Disabled incompatible app: radio
Disabled incompatible app: sharerenamer
Disabled incompatible app: socialsharing_diaspora
Disabled incompatible app: socialsharing_email
Disabled incompatible app: socialsharing_facebook
Disabled incompatible app: socialsharing_twitter
Disabled incompatible app: spreed
Disabled incompatible app: tasks
Disabled incompatible app: uploaddetails
Disabled incompatible app: video_converter
```

In other words, TONS of plugins which may or may not be compatible with NC 18. 

And it seems the script was aborted as you say before completion. That may be the cause as well. Above that it seems from the first picture that some PHP is missing to "translate" the code into readable by browser.

Would need to investigate this and sorry, but this is not a support forum. Maybe you can ask for help [here](https:help.nextcloud.com)

**Comment by BetaLeaf** [comment]
Your link is broken. Does the update script make a backup that I can restore from?

**Comment by BetaLeaf** [comment]
I also thought it might be an app, so I disabled every app that I could. Did integrity checks, code checks, permission checks, everything passes, just this css error. The server still works fine from clients, just not from web browsers.

**Comment by BetaLeaf** [comment]
trimmed a bit of the message below to remove unnecessary stuff like timestamps:
```
"app":"core","url":"/settings/apps","message":"Failed to compile and/or save /var/www/nextcloud/core/css/server.scss"
"app":"cssresourceloader","url":"/settings/apps","message":"Could not find resource css/server.css to load"
```

**Comment by enoch85** [comment]
> Your link is broken. Does the update script make a backup that I can restore from?

Yes, all backups are in `/var/NCBACKUP` or `/mnt/NCBACKUP`.

> Could not find resource css/server.css to load"

Get the css file from Github, download it and try. Should work.

**Comment by BetaLeaf** [comment]
I already tried downloading a new copy of the latest nextcloud and that didn't fix it. I'll try to restore from backup now.

**Comment by BetaLeaf** [comment]
ok so I am 100% sure that the update was interrupted. The sql backup file was not finished being created. Hoping I can use the existing db, else I will have to rebuild the db

**Comment by BetaLeaf** [comment]
Ok so downgrading seems to fix it.

Backed up the existing db and www files.
I downloaded the latest nextcloud 17, replaced /var/www/nextcloud/, chown -R www-data:www-data, and then did php occ upgrade. All is good now

**Comment by enoch85** [comment]
Great! Glad you solved it!
