### ISSUE TITLE
make a function from "check if a specific nextcloud-app is enabled"

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1082]
as the title says.
ref https://github.com/nextcloud/vm/pull/1081#discussion_r378848659

I will work on this when #1081 and #1072 are merged.

**Comment by enoch85** [comment]
IMO, no need to add logic for that as that's already handled here: https://github.com/nextcloud/vm/blob/master/lib.sh#L680-L711

**Comment by szaimen** [comment]
I would say it is definitely needed and would work like this:

```
is_this_enabled() {
if occ_command app:list --output=json | jq -e '.enabled | .$1' > /dev/null
then
    return 1
else
    return 0
fi
}
```

e.g. we could use it in notify_admin_gui
or now in the PR of new way of installing onlyoffice

**Comment by enoch85** [comment]
OK, please name it `is_app_enabled` and add it to lib.sh, then change all the scripts where this is needed.

Advice, clone this repo and use `grep -r` to search foru occurances like "occ:app enable"

**Comment by szaimen** [comment]
I would like to do this when the other PRs are merged because of conflicts...

**Comment by szaimen** [comment]
### The are the outputs when I grep for:

**no_check:**
```
vm/apps/collabora.sh:if occ_command_no_check app:list --output=json | jq -e '.enabled | .documentserver_community' > /dev/null
vm/apps/onlyoffice.sh:    if occ_command_no_check app:list --output=json | jq -e '.enabled | .documentserver_community' > /dev/null
vm/apps/previewgenerator.sh:if [ -n "$(occ_command app:list | grep encryption | awk '{print $3}')" ]
vm/lib.sh:if ! occ_command_no_check app:list --output=json | jq -e '.enabled | .notifications' > /dev/null
vm/static/nextcloud_configuration.sh:            if ! occ_command app:list --output=json | jq -e '.enabled | .text' > /dev/null
```

**occ app:enable:**
`vm/lib.sh:    sudo -u www-data php ${NCPATH}/occ app:enable "$1"`

**command app:enable:**
```
vm/apps/spreedme.sh:occ_command app:enable spreedme
vm/lib.sh:            occ_command app:enable "$1"
```

**Comment by szaimen** [comment]
I could also provide a function: is_app_installed, that would look like this:
# example: is_app_installed documentserver_community
is_app_installed() {
if [ -d "$NC_APPS_PATH/$1" ]
then
    return 0
else
    return 1
fi
}

we could use that here:
```
vm/apps/fulltextsearch.sh:if [ -d $NC_APPS_PATH/fulltextsearch ]
vm/apps/fulltextsearch.sh:if [ -d $NC_APPS_PATH/fulltextsearch_elasticsearch ]
vm/apps/fulltextsearch.sh:if [ -d $NC_APPS_PATH/files_fulltextsearch ]
vm/apps/previewgenerator.sh:    if [ -d "$NC_APPS_PATH/previewgenerator" ]
vm/apps/spreedme.sh:if [ -d "$NC_APPS_PATH/spreedme" ]
vm/lib.sh:if [ ! -d "$NC_APPS_PATH/$1" ]
vm/lib.sh:        if [ -d "$NC_APPS_PATH/$1" ]
```

**Comment by szaimen** [comment]
@enoch85 Shall I do that in another PR?

**Comment by enoch85** [comment]
Sure, why not. :)

**Comment by enoch85** [comment]
Remember to grep all occurrences where it can be replaced.
