### ISSUE TITLE
Executing Production  installation script

### ISSUE THREAD

**Issue by scotsimba** [nextcloud/vm#1085]
I'm newbie and tested the script on test VM instance yesterday and all went well. However when I created a new VM so we could use nextcloud actively the following error was reported: 
So hopefully this shall make more sense to you:
"### _Testing if network is OK...
Checking connection...
Online!
Testing if network is OK...
Checking connection...
Online!
grep: /var/www/nextcloud/config/config.php: No such file or directory
grep: /var/www/nextcloud/config/config.php: No such file or directory
sudo: php: command not found
/dev/fd/63: line 897: [: : integer expression expected
sudo: php: command not found
/dev/fd/63: line 933: [: : integer expression expected
sudo: php: command not found
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!_"

## Steps to reproduce
1. ran the script in SUDO mode.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Sorry, I can't reproduce this. Just ran the installation script 6 times in a row.

Thanks for reporting though, keep em coming! :)
