### ISSUE TITLE
checksums error

### ISSUE THREAD

**Issue by mrusklon** [nextcloud/vm#1086]
hi, I install the nextcloud on a clean ubuntu on 18.08, the script downloaded the nextcloud and says:
https://i.imgur.com/fyN86yD.png

what's wrong?

**Comment by enoch85** [comment]
Your internet connection is probably too slow, or there are some corruption happening on the way from the Nextcloud server to yours resulting in that the package becomes corrupt.

Call your ISP and ask them what's going on, or check your internet connetion.

In any case, try again later and it will most probably work.
