### ISSUE TITLE
Is this me or you?

### ISSUE THREAD

**Issue by mbrandenburg123** [nextcloud/vm#1098]
![IMG_5801](https://user-images.githubusercontent.com/61292149/74969851-2b205c00-53d2-11ea-93bc-19c17634363c.JPG)

## Steps to reproduce
1. Initial Set up
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Packaged 2TB VM

## Network
**Do you use DHCP?**
yes
**Is port 80 and/or 443 open?**
yes
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Seems you're having issues with your internet connection. 

It works here.

**Comment by mbrandenburg123** [comment]
I'll give it another go.

**Comment by mbrandenburg123** [comment]
![IMG_5803](https://user-images.githubusercontent.com/61292149/74971152-78053200-53d4-11ea-9d64-3cc3b60fd44c.JPG)
Seems network is ok.

**Comment by enoch85** [comment]
OK, will spin up a VM and try it from here

**Comment by enoch85** [comment]
Works from here: https://cloud.hanssonit.se/s/EsH7ewD96CZXk6E

**Comment by enoch85** [comment]
Check your internet connection, and then try again in a while. It might just be temporary.

**Comment by mbrandenburg123** [comment]
Whatever the issue was, it resolved itself. All is well. Thank you.

**Comment by enoch85** [comment]
> it resolved itself.

So how did you solve it? :)

**Comment by mbrandenburg123** [comment]
I dumped the entire VM and started over. Funny though, I was going to ask you the same question. :)

**Comment by mbrandenburg123** [comment]
Completely un-related observation. I purchased the 2TB hyper-v version from you. I initially did a test upload to the cloud via Win 10 client around 500GB of misc images and video files. Everything functioned just fine after a successful upload. My issue is, after I deleted the entire contents of the cloud via the web gui in Win 10 and then deleted the entire contents of the Nextcloud trash bin, it doesn't appear to have freed up the space on the virtual disk. It looks as the server is retaining these files somewhere?

![2020-02-26 07_21_27-Deleted Items - mbrandenburg@aminc com - Outlook](https://user-images.githubusercontent.com/61292149/75359481-4f17ed80-5869-11ea-99ef-e3bddfff021e.jpg)

![2020-02-26 07_22_51-Deleted Items - mbrandenburg@aminc com - Outlook](https://user-images.githubusercontent.com/61292149/75359492-54753800-5869-11ea-9e44-0cc88ddf7bec.jpg)

![2020-02-26 07_23_54-Settings - Nextcloud](https://user-images.githubusercontent.com/61292149/75359524-61922700-5869-11ea-849d-e6a852ac9916.jpg)

**Comment by enoch85** [comment]
The disks are thin, so you need to free the space with zeros and then delete it if you want it to show correctly in Nextcloud. A topic about it: https://community.webcore.cloud/tutorials/zero_free_space_shrink_thin_provisioned_vmdk/

It's not an issue though. It's just an issue if you run out of space, but we have thought of that already and will clear snapshots and then trashbin if that happens automatically when running the update script built into the VM.

**Comment by mbrandenburg123** [comment]
Good enough. Thank you again for your very prompt reply and I really appreciate your outstanding packaged VM. It is by far the easiest and fastest way to deploy a Nextcloud server. Well worth the small investment on my part.

**Comment by enoch85** [comment]
Thanks!
