### ISSUE TITLE
Provide an option to reinstall the gallery app on Nextcloud 18?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1099]
Currently, there is no way to view picture previews when sharing a folder with a link. 
Also the new fotos app on Nextcloud 18 isn't currently working with the external storage app.
https://github.com/nextcloud/photos/issues/128
https://github.com/nextcloud/photos/issues/154

Do you think that these are enough reasons to provide an option to enable the gallery app again?
the following script is based on [this comment:](https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/20)
It has worked without any issue in my testing.
Since it is kind of a Nextcloud-change, I would put it as an additional option in the nextcloud_configuration script. then we can remove it again, when both features are added to the photos app.

```
if network_ok
then
    # Download and install gallery app
    cd "$NC_APPS_PATH"
    git clone https://github.com/nextcloud/gallery.git
    cd gallery/js/vendor/dompurify/src
    wget https://raw.githubusercontent.com/cure53/DOMPurify/1.0.11/dist/purify.js -O purify.js 
    occ_command app:enable gallery
fi
```

**Comment by szaimen** [comment]
BTW: don't you think, that the previewgenerator.sh does fit better in the nextcloud_configuration script? since it configures nextcloud?

**Comment by enoch85** [comment]
> BTW: don't you think, that the previewgenerator.sh does fit better in the nextcloud_configuration script? since it configures nextcloud?

Preview Generator is an app, so no. :)

Regarding the other question: no, let Nextcloud fix it instead. Starting to do specials in the VM will easily get crazy down the road. I'm sure there's a reason for the Gallery app not working anymore in NC 18.

The VM should be as default as possible to avoid any bugs in let's say 5 years from now.

**Comment by szaimen** [comment]
okay 👍
