### ISSUE TITLE
Inform the user weekly about the biggest database tables?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1108]
Hi, a few weeks ago, I had a problem with my database which was growing rapidly because of the maps app. I think it would be really helpful, if we would inform the admins about the biggest database tables to identify problems instantly. I would put it in the updatenotification.sh to run weekly as an cronjob.

Here is the already working code:
```
DATABASE_STATS=$(sudo -Hiu postgres psql nextcloud_db -c "SELECT relname,n_live_tup FROM pg_stat_user_tables ORDER BY n_live_tup DESC LIMIT 18;" | sed '1,2d;$d' | sed '$d' | sed 's/ //g' | sed 's/|/ | /g')
notify_admin_gui \
"weekly-database-stats" \
"database_table | number_of_rows
$DATABASE_STATS
(showing 18 entries)"
```
it would then look like this:
![image](https://user-images.githubusercontent.com/42591237/75115071-d42db780-565b-11ea-93b3-b6dba3c81b29.png)

**Comment by enoch85** [comment]
Seems like a rare case. 

I've been using ownCloud since 2013, and Nextcloud since it was founded and never had these issues.

I don't know what I would do with this information either, especially as a regular user. It just seems confusing.

I vote no.

**Comment by enoch85** [comment]
Great idea though! :+1:

**Comment by szaimen** [comment]
> I vote no.

Okay

> Great idea though! 👍

Thanks!
