### ISSUE TITLE
Administration/Overview gives security warnings

### ISSUE THREAD

**Issue by pdwalker** [nextcloud/vm#1111]
## Steps to reproduce
1. default install
2. login as admin
3. go to Administration/Overview

## Expected behaviour
Expected not to see the following security warnings:
    
    Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.
    Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.

## Actual behaviour
we get those warnings.

is this expected behaviour?

## Server configuration

**Nextcloud server version:** (see your admin page)
18.0.1

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
from the https://cloud.hanssonit.se/s/zjsqkrSpzqJGE9N?path=%2F18.0.1%20STABLE
Nextcloud_VM_www.hanssonit.se.ova

## Network
**Do you use DHCP?**
yes

**Is port 80 and/or 443 open?**
yes

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Do you run this behind a proxy?

**Comment by pdwalker** [comment]
No.  I access the VMs ip directly.

**Comment by enoch85** [comment]
Strange, that should already be fixed. 

I'll have a look.

**Comment by pdwalker** [comment]
i can provide access to the vm if you wish (in an hour)

**Comment by enoch85** [comment]
No, this is a general issue. Will need to be fixed for everyone if it's a bug.

The bug may be in Nextcloud and not the VM, so I need to confirm that first.

**Comment by pdwalker** [comment]
I actually have the same problem in a manual installation.  I was trying your version to see if you had solved the issue and how you got around it.  Just my luck.

**Comment by pdwalker** [comment]
closed issue.  

I don't know why, but everything appears ok now.  All I did was reboot the vm and access the site specifically via https://<ipaddress>

The problem is clearly on my side.  Sorry about that.

**Comment by enoch85** [comment]
No worries!
