### ISSUE TITLE
apt-select -m up-to-date -t 5 -c -C us failed

### ISSUE THREAD

**Issue by Direwolf64** [nextcloud/vm#1112]
#656  Steps to reproduce
1. Run config script for first time
2.
3.

## Expected behaviour
Tell us what should happen
Expected configuration to succeed.
## Actual behaviour
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='launchpad.net', port=443): Max retries exceeded with url: /ubuntu/+archivemirrors (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f558d808450>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
apt-select -m up-to-date -t 5 -c -C us failed

## Server configuration
Ubuntu 18.04 VM on VMWare ESX-i 6.7U3
**Nextcloud server version:** (see your admin page)
18.0.1.3
**Server OS** (Ubuntu server is default)
Ubuntu 18.04
**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install from <https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh/#L1>
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes
#### Log file (/var/log/nextcloud/nextcloud.log)
```
https://0bin.net/paste/9lSGx5cHkvT3rR6V#IT3+Q+k53n7dhAy8exV2d5FCzpjyyCTWT-SVMvd3aim
#### Installation log (command output)
```
Insert the CLI output here
https://0bin.net/paste/4X0vhslT5WbFmttE#oKBqW-52pRQMy/YQQ+YizLzuQU/FRDuHNmIPoUCHq06

**Comment by enoch85** [comment]
Thanks for reporting this!

I'll have a look later.

**Comment by enoch85** [comment]
I just tested it here, works like a charm.

It must have been a temporary error, please try again.
