### ISSUE TITLE
install onlyoffice "something got wrong during the installation...."

### ISSUE THREAD

**Issue by Laurent-grain** [nextcloud/vm#1114]
## Steps to reproduce
1.A fresh install of my vm nextcloud (vm downloaded fromm t&m hanson)
2.I launch the script for installing onlyoffice
3 Everything seems to be OK because It say to me: .onlyoffice was succefully installed. I press Ok, and after a message say "something got wrong during the installation....."

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)
18.0.1
**Server OS** (Ubuntu server is default)
ubuntu 18.04
**How did you install the VM?** (Scripted install from master **OR** Released version)
script
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```
the log file is empty
#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by BoardWatcher** [comment]
I have the same issue as well.  Exactly the same conditions as described above.  This was my first attempt to install NextCloud.  Everything said installation was successful as above.  SSL configuration also complete.

**Comment by enoch85** [comment]
@szaimen The PR you made is now presented. 

How can we solve this?

**Comment by BoardWatcher** [comment]
Hi;

Yes;  I've determined that you cannot have both collabroa and OnlyOffice
installed at the same time. Rerun the apps.sh file and choose Office
again.  It will offer to remove collabora and install just office and
you'll be good to go.

Sent Digitally,
Charles Naslund, CDR USNR RET, ASAE, BSCS, MBA
Charles@Naslund.nz <charles@naslund.nz>

**Comment by szaimen** [comment]
Hm... Probably this is the problem here (in ainstall_and_enable_app):
installcmd="$(occ_command_no_check app:install "$1")"
(Do you see the double quotes?)
But I don't get why the documentserver_communty app installs without problems and the onlyoffice app just not at all...

**Comment by enoch85** [comment]
@Laurent-grain Could you please provide the full CLI output log so that we can debug this issue?

Thanks!

**Comment by szaimen** [comment]
I guess there was no output. But the check that I have added was for testing if onlyoffice or documentserver_community is installed at the end.

In my case it succesfully uninstalled docker-onlyoffice and installed the documentserver_community but somehow didn't install the onlyoffice app at least it wasn't installed at the end. I manually had to install the app again.
Maybe it is enough to not remove the app when reinstalling here https://github.com/nextcloud/vm/blob/30aa9458589afb9953f4a0181f96bdd001cbd58b/apps/onlyoffice.sh#L68?

**Comment by enoch85** [comment]
> Maybe it is enough to not remove the app when reinstalling here 

Sure, fine with me, only during reinstall though.

**Comment by szaimen** [comment]
Yes, that is during the reinstallation

**Comment by enoch85** [comment]
This should be fixed now, please try again.

**Comment by Laurent-grain** [comment]
Hello
Sorry but I was out off office and I couldn't see your response.
For me I'v try to uninstall onlyoffice et install it again but I 've the same result.
Collabora is not installed
I've take some screenshot .
[Error Nextcloud onlyoffice.pdf](https://github.com/nextcloud/vm/files/4288289/Error.Nextcloud.onlyoffice.pdf).
If I try to acces on nextcloud log repository with this command cd/var/log/nextcloud, I 've permission denied ;(

**Comment by szaimen** [comment]
@Laurent-grain Please could you check in your nextcloud app list if the onlyoffice and documentserver_community apps are installed?

**Comment by Laurent-grain** [comment]
Hello
In webinterface I see only office 4.1.4 active but nothing about  documentserver_community.  Community. Document Server is available for downloading and for activation.
As /log/nextcloud, I've "permission denied" when I want acces to the nextcloud folder /var/www

**Comment by szaimen** [comment]
hm... so the documentserver_community doesn't seem to get installed...
Could you run in your cli:
```
sudo -i
nextcloud_occ app:install documentserver_community
```

**Comment by szaimen** [comment]
@enoch85 I think we didn't covered the case if you have docker onlyoffice installed and are not on 18.0.1 or higher: then the installation continues and the script will try to install documentserver_community although you are on 18.0.0 where the installation didn't run successfully.

**Comment by Laurent-grain** [comment]
root@cloud:~# sudo -i
root@cloud:~# nextcloud_occ app:install documentserver_community
Error: cURL error 28: Operation timed out after 120000 milliseconds with 207228188 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
root@cloud:~#

Version of NC 18.0.1

**Comment by Laurent-grain** [comment]
root@cloud:~# sudo docker ps -a
sudo: docker: command not found
root@cloud:~#

**Comment by szaimen** [comment]
> root@cloud:~# sudo -i root@cloud:~# nextcloud_occ app:install documentserver_community
> Error: cURL error 28: Operation timed out after 120000 milliseconds with 207228188 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
> root@cloud:~#
> 
> Version of NC 18.0.1

Thank you very much! Here we have located the error. Will try to see what we can do here.

**Comment by szaimen** [comment]
@enoch85 I think we will have to increase the version to at least 18.0.2:
https://github.com/nextcloud/server/pull/19439

Sry, I was sure that this was already implemented with NC18.0.1...

"Luckily" NC18.0.2 is going to be released in around a week.

**Comment by Laurent-grain** [comment]
OK. I 've just to wait a week and launch an update and after restart the install of only office by the script of the vm ? that's right ,

**Comment by szaimen** [comment]
Yes, you first have to upgrade to 18.0.2 (we will then merge the PR) and afterwards, you can launch the this script again and it should work. 👍

**Comment by Laurent-grain** [comment]
thanks a lot

**Comment by szaimen** [comment]
You are welcome, thanks for your patience!

**Comment by BoardWatcher** [comment]
Will we be able to download the update once it's available?  I have a
current download link which appears to expire soon as I just purchased your
VM and have the same issues.

Thank you,
Sent Digitally,
Charles Naslund, CDR USNR RET, ASAE, BSCS, MBA
Charles@Naslund.nz <charles@naslund.nz>

**Comment by enoch85** [comment]
> Will we be able to download the update once it's available?

It's possible to run the onlyoffice script now as well. It all depends on your internet speed. Below 2 Mb/s and it will fail. 

Once the fix is out, it will be sorted. This is a Nextcloud thing, rather than a VM thing.

You could path it now as well, but it would require some Linux and Git skills.
