### ISSUE TITLE
what default adress index?

### ISSUE THREAD

**Issue by mrusklon** [nextcloud/vm#1133]
what is the address in nextcloud after default installation by install script? A stub hangs on the localhost, then what?

Sorry for my English

**Comment by enoch85** [comment]
There is no default address. It's the IP address of the server you install it to, which can be anything really.

http://your.ip.address.here

**Comment by mrusklon** [comment]
my ip = my apache2 start page. But not nextcloud. so I ask the question, where can I see the parameters? Thanks!

**Comment by enoch85** [comment]
Then you didn't follow the instructions: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm-first-setup-instructions
