### ISSUE TITLE
Not Connected to Network After Installation 

### ISSUE THREAD

**Issue by SkyPhantom1** [nextcloud/vm#1138]
## Steps to reproduce
1. Open Nextcloud VM in vmware
2. Go through entire installation process
3. Reboot

## Expected behaviour
I should be able to access my nextcloud vm through ip address or dns

## Actual behaviour
I am unable to access vm through my network and it's listed as inactive in my router. However during the install process I was able to access the vm with both the ip address and dns. 

## Server configuration

**Server version:** (see your admin page)
18.0.1
**Server OS** (Ubuntu server is default)
Default 
**How did you install the VM?** (Scripted install from master **OR** Released version)
Released 
## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
Yes
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots

https://imgur.com/a/J4MSTT0

**Comment by enoch85** [comment]
Either you don't have DHCP, or you've set a wrong static IP.

This is rather a support ticket than a bug. For such enquirers, please use https://help.nextcloud.com or buy hands on support in the shop: https://shop.hanssonit.se/

**Comment by SkyPhantom1** [comment]
Solved: reinstalled, decided not to use Netplan, and setup a static ip through my router instead.

**Comment by enoch85** [comment]
That's the preferred way to do it.
