### ISSUE TITLE
Cannot install Nextcloud, Script Errors

### ISSUE THREAD

**Issue by sarbaso** [nextcloud/vm#1139]
Hi there, 

i need some assistance on this.

1.Error in Script
The Errors appears after the succesfull implementation of Lets Enrypt SSL
systemctl restart php7.2-fpm.service failed -> i choosed before not to update the PHP Apache Site

2.Error in Script
Posting notificatuin to users that are admins, this might take a while ->
Posting "Sorry but something went wrong, Please report this issue to https://github.com/nextcloud/vm

what can i do ?

I payed a year ago for a 500gb image and thought that i can use this image these days too
but somehow i cannot end the installation.

Please assist on this

Kind Regards

Hamid
![2020-03-03 16_00_41-Nextcloud - VMware Workstation](https://user-images.githubusercontent.com/61747069/75789186-97537600-5d69-11ea-84c0-79370c67ceaf.png)
![2020-03-03 16_11_37-Nextcloud - VMware Workstation](https://user-images.githubusercontent.com/61747069/75789257-b3571780-5d69-11ea-80b1-7a0f78f5c18f.png)

**Comment by szaimen** [comment]
@enoch85 it seems like calculate_max_children is missing in the lib?

**Comment by enoch85** [comment]
@szaimen And we have a compatibility issue on our hands. :D

@sarbaso TO be able to debug we need more info.

1. Does this happen during the first install?
2. Exactly where during the script does this fail?
3. Did you choose any options before you ran this, or is it just default?
4. What does the logs say? Apache+ PHP-FPM?

Thanks!

**Comment by enoch85** [comment]
Sorry, no need for the info. I saw now what was wrong and actually remember removing it. 

It should be fixed now, please try again.
