### ISSUE TITLE
After upgrade to 18.x  Collabora isn't running

### ISSUE THREAD

**Issue by cbacit** [nextcloud/vm#1144]
## Steps to reproduce
1.  I have run  bash /var/scripts/apps/collabora.sh & bash /var/scripts/apps/onlyoffice.sh 
2.  bash /var/scripts/update.sh 
3. but still I don't see it as an option in the file system.  I don't know why... Even the store says it isn't installed.  Please 

## Expected behaviour
Tell us what should happen I should be able to open up documents or create them.  

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)
18.0.4
**How did you install the VM?** (Scripted install from master **OR** Released version)
1 TB VM
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by szaimen** [comment]
@enoch85 any idea what the problem could be here?

@cbacit could you try to run the following command:
`sudo bash /var/scripts/apps.sh`

**Comment by enoch85** [comment]
I believe this already is fixed through support.
