### ISSUE TITLE
NC losing SSL certificate at reboot

### ISSUE THREAD

**Issue by arandax** [nextcloud/vm#1145]
Hello,
I'm hosting the VM on esxi, used the script to setup the ssl certificate throug let's encrypt scritp (activate-ssl.sh) on my third level domain (remote.xxxxx.it), everything ok, exept that when I reboot the VM, if I connect through the browser, I find non valid certificate.. (released to nextcloud instead of my domain). tryed it using xxxxx.duckdns.org, same problem, works until reboot. 
Any ideas?

## Steps to reproduce
1. registered NC VM on esxi 6.7 update 3
2. configured
3. installed certificate through script.

## Expected behaviour

Certificate should be working
## Actual behaviour

Certificate work until VM reboot then uses other certificate Released to: nextcloud, released from: nextcloud, valid from 21/12/2019 until 18/12/2029
![ssl](https://user-images.githubusercontent.com/59771093/76166063-ed565e00-615b-11ea-95df-5cb9b61946fa.JPG)

## Server configuration

**Nextcloud server version:** 18.0.1

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
Unifi DHCP

**Is port 80 and/or 443 open?**
ports 80 and 443 open and forwarded
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
You need to keep port 80 open (as per instructions in the documentation) for Let's Encrypt to automatically update your certificates.

**Comment by arandax** [comment]
Thank for the reply!
I confirm that port 80 is still open, didn't closed it.

**Comment by enoch85** [comment]
It works here.

Maybe it would be better if you asked in the forum. Github is only for reporting bugs. 

You can find the forum here: https://help.nextcloud.com

**Comment by arandax** [comment]
Thanks, just opened a thread on the forum as you suggested.
https://help.nextcloud.com/t/nc-losing-ssl-certificate-at-reboot/73337

**Comment by enoch85** [comment]
Thanks!
