### ISSUE TITLE
 Two-Factor Admin Support  plugin

### ISSUE THREAD

**Issue by Mikam1974** [nextcloud/vm#1149]
Hi,

After installing Nextcloud 18 via script. All looks good, except when trying to install the TWO factor Admin support plugin.

I get the error message "
Two-Factor Admin Support
Nextcloud Two-Factor Authentication Admin Support Provider
App "Two-Factor Admin Support" cannot be installed because the following dependencies are not fulfilled: Following databases are supported: sqlite, mysql 
Since am planning to use it on a large scale, I really need users to use the two-factor authentiction, therefore being an admin, that plugin is essential in order to support.

Thanks
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by szaimen** [comment]
Since the Nextcloud VM is using PostgreSQL as database this app will not work.
You can follow the conversation about support for PostgreSQL here: https://github.com/ChristophWurst/twofactor_admin/issues/35

**Comment by szaimen** [comment]
As a workaround you could enable https://apps.nextcloud.com/apps/twofactor_nextcloud_notification
and use https://apps.nextcloud.com/apps/impersonate to impersonate a user which needs access to his account in the case he has lost all twofactor codes.
