### ISSUE TITLE
A couple errors...

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#1151]
Not sure if this is expected behavior, but thought I'd report it just in case. Clean Ubuntu 18.04 starting point.

![20200318-161653](https://user-images.githubusercontent.com/6325833/77010177-ae848d00-693f-11ea-8931-e0ecdfa875e3.jpg)
![20200318-163918](https://user-images.githubusercontent.com/6325833/77010182-b04e5080-693f-11ea-9580-08b8a8ecf167.jpg)

**Comment by enoch85** [comment]
Thanks!

I'll have a look at the first one.

The second error is known and it's due to a bug in Talk.

**Comment by enoch85** [comment]
This should now be fixed.
