### ISSUE TITLE
activate-ssl.sh script fails if multiple domain names entered

### ISSUE THREAD

**Issue by AndreyZnamenskiy** [nextcloud/vm#1156]
## Steps to reproduce
1. run /var/scripts/acitvate-ssl.sh script
2. enter **multiple comma separated domains**:    box.domain.org,cloud.domain.org
3.

## Expected behaviour
keys generated, certs issued and apache conf files updated

## Actual behaviour
ERROR
Can't open /etc/letsencrypt/live/box.domain.org,cloud.domain.org/dhparam.pem for writing, No such file or directory
139707151884736:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:72:fopen('/etc/letsencrypt/**live/box.domain.org,cloud.domain.org/**dhparam.pem','w')
139707151884736:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:79:

## Server configuration

**Nextcloud server version:** 18.0.3

**Server OS** Ubuntu Linux 18.04.2

## Network
static IP.

**Comment by enoch85** [comment]
Thanks for posting your issue.

It's not expected to be able to validate several addresses at once. You could do one at the time though.

If you want to make a PR, you're welcome! :)

**Comment by AndreyZnamenskiy** [comment]
@enoch85  Thank you for your response. 
Actually, cert was issued correctly (with **both** SANs), as far as I can understand issue is with apache sites-available configuration step, pointing to non-existand `box.domain.org,cloud.domain.org` folder.

**Comment by enoch85** [comment]
Whuut, that shouldn't even be possible. But great to know it worked. :D
