### ISSUE TITLE
Scripted install, warning on 2GB machine

### ISSUE THREAD

**Issue by lukas-buergi** [nextcloud/vm#1157]
## Steps to reproduce
1. Run nextcloud_install_production.sh on a machine with "2GB of RAM"

## Expected behaviour
It should not complain about having less than 2GB of RAM if the amount of RAM is close to 2GB

## Actual behaviour
It complains about not having 2GB of RAM on the "2GB" machine, because a few megabytes are missing (i.e. 19xx MB of RAM, probably because some small amount needs to be permanently mapped to some device so not all of the 2GB show up to the OS/userspace).

## Server configuration

**Nextcloud server version:** current

**Server OS** debian stable

## Suggested solution
Check for something like 100MB less than the round GB number, i.e. 1900MB.

**Comment by enoch85** [comment]
Hi!

Thanks for your report.

RAM is read in 1024 bits, meaning that 2 GB is really 2048MB. So, If you set 2000MB RAM, then it will be 1.9GB RAM which is too small, yes. 

Not a bug.

**Comment by enoch85** [comment]
Sorry, it's hardcoded. 

Here's the function of you're interested in improving it: https://github.com/nextcloud/vm/blob/master/lib.sh#L620-L639

Please send a PR if you do.

**Comment by lukas-buergi** [comment]
@enoch85 Sure, here you go: https://github.com/nextcloud/vm/pull/1158

**Comment by enoch85** [comment]
As it says in the `msg_box` when the check fails - you can disable it, on your own risk.
