### ISSUE TITLE
The script install Postgresql and then   "Database <pgsql> is not supported"  

### ISSUE THREAD

**Issue by Mx74** [nextcloud/vm#1159]
In Install.php line 124:
                                      
  Database <pgsql> is not supported.  
                                      

maintenance:install [--database DATABASE] [--database-name DATABASE-NAME] [--database-host DATABASE-HOST] [--database-port DATABASE-PORT] [--database-user DATABASE-USER] [--database-pass [DATABASE-PASS]] [--database-table-prefix [DATABASE-TABLE-PREFIX]] [--database-table-space [DATABASE-TABLE-SPACE]] [--admin-user ADMIN-USER] [--admin-pass ADMIN-PASS] [--admin-email [ADMIN-EMAIL]] [--data-dir DATA-DIR]

**Comment by enoch85** [comment]
Strange, because I just did 6 installations and none of them failed.

**Comment by Mx74** [comment]
So, because it's strange, issue closed?

 
 

Envoyé: jeudi 26 mars 2020 à 20:06
De: "Daniel Hansson" <notifications@github.com>
À: nextcloud/vm <vm@noreply.github.com>
Cc: Mx74 <kart74@caramail.fr>, Author <author@noreply.github.com>
Objet: Re: [nextcloud/vm] The script install Postgresql and then "Database <pgsql> is not supported" (#1159)


 

Strange, because I just did 6 installations and none of them failed.

**Comment by enoch85** [comment]
No, it's closed because I posted I posted a video of when it was working = no bug in the scripts.

**Comment by AidarBabanov** [comment]
I have the same error, can you reopen the issue?

**Comment by enoch85** [comment]
I honestly don't know where this comes from. No installation ever failed for me, and I do several per week.

Without proper steps to reproduce it's impossible for me to debug.

**Comment by rudolfvesely** [comment]
I had the same issue and the solution is to install `php-pgsql`. It might be useful to check for `php-pgsql` in the install script.
