### ISSUE TITLE
Install of both ONLYOFFICE and Collabora?

### ISSUE THREAD

**Issue by guerby** [nextcloud/vm#1163]
nextcloud_install_production.sh uninstalls ONLYOFFICE when installing Collabora, I wonder if it would be possible to have both installed by the script?

If no what are the issues preventing a simultaneous install?

**Comment by enoch85** [comment]
@guerby You can only run one at the time, so that's expected behaviour. That's a server limitation in the server core. But I don't see why you would like to run to at all?

Please as in the Nextcloud forum [here](https://help.nextcloud.com).

**Comment by guerby** [comment]
For reference our user both have Microsoft formated and OpenOffice formated documents so having collaborative edition without having to convert back and forth would be useful.

**Comment by e-alfred** [comment]
@enoch85 Maybe this discussion on why both are sometimes necessary is helpful for you:

https://github.com/nextcloud/android/issues/5729

**Comment by enoch85** [comment]
Let me put it this way: when it's officially supported we might add it in the VM as well. 

Thanks for the input!

**Comment by guerby** [comment]
@enoch85 Hi, based on a 19.0.0 vm script install with onlyoffice if I follow the instructions from nextcloud blog post:

https://nextcloud.com/blog/how-to-install-collabora-online-in-nextcloud-hub/

(install apps CODE then collabora online)

I get a working OnlyOFFICE+collabora nextcloud, and the nextcloud blog post seems to imply it is now officially supported.

**Comment by enoch85** [comment]
@e-alfred If you really want it implemented, please create a PR where we can discuss. :+1:

**Comment by guerby** [comment]
@enoch85 I've seen you've reopened this PR, should I open another one? Let me know, thanks!

**Comment by enoch85** [comment]
@guerby This is not a PR, this is an issue. 

A PR is where you fork this repo, make the changes and send it to this repo - with a PR (Pull Request). Here's some info: https://linuxhint.com/pull_request_github/

**Comment by enoch85** [comment]
Update, we've now made it possible to install both OnlyOffice and Collabora from a menu.

With that change, the basics are already in place and it would be easier for you to make a PR. 

If you want to run the new setup, just run: `sudo bash /var/scripts/menu.sh` and choose Additional Apps --> Documentserver

**Comment by szaimen** [comment]
Hi @guerby and @e-alfred, if you are available for testing: I've created #1953 which should finally allow to install both documentserver. Any feedback on the PR is welcome!

**Comment by enoch85** [comment]
We won't do this.
