### ISSUE TITLE
Revert changes to the onlyoffice install script?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1164]
Can we somehow restore the old way of installing onlyoffice? 

I had to find out that the documentserver_community has many bugs and isn't ready for production the hard way.

**Comment by enoch85** [comment]
The more that uses it, the more bugs will be found. That's a good thing - then they can be reported and fixed.

We use it in production at work with around 45 users. No issues at all. So I'd say no, let's leave it as is.

**Comment by szaimen** [comment]
Okay 👍
