### ISSUE TITLE
NC don't start after reboot.

### ISSUE THREAD

**Issue by tmsd2001** [nextcloud/vm#1165]
I can't show my admin page, my version is 18.x.x.
At start, I can see an error with sys-devices-virtual-misc-vmbus.
And at my search for the reasons I see the error "No space left on device"
My Root device is a 250 GB Disk und I remove 10 GB, but the error is still there.

Filesystem    Size  Used Avail Use% Mounted on
udev            3,8G     0  3,8G   0% /dev
tmpfs           773M  1,4M  772M   1% /run
/dev/sda2       229G  219G     0 100% /
tmpfs           3,8G     0  3,8G   0% /dev/shm
tmpfs           5,0M     0  5,0M   0% /run/lock
tmpfs           3,8G     0  3,8G   0% /sys/fs/cgroup
/dev/loop0       92M   92M     0 100% /snap/core/8689
/dev/loop1       94M   94M     0 100% /snap/core/8935
ncdata          3,6T  976G  2,6T  28% /mnt/ncdata
tmpfs           773M     0  773M   0% `/run/user/1000

What can I do?

**Comment by enoch85** [comment]
Hi,

Run the built in update script in /var/scripts), it will automatically remove snapshots on ZFS and emtpy the trashbin to free up some space.

Other than that, you can always reach out for support: https://shop.hanssonit.se/

**Comment by tmsd2001** [comment]
Unfortunately I no longer get any free disk space.
I delete all logs, old files, snapshots and backups.
Free the lsof | grep delete memory.
Inodes are free and diskspace 12 GB but use 100%.
Disk Use show only 18 GB

0 | /proc
14319068 | /var
11328 | /etc
4 | /lib64
100 | /root
92 | /home
16 | /lost+found
867404 | /lib
128 | /tmp
281504 | /snap
4 | /cdrom
1376 | /run
4 | /media
0 | /sys
15248 | /bin
18344 | /sbin
4 | /srv
145120 | /boot
2806952 | /usr
0 | /dev
24 | /opt

I would take a bigger hdd, is it better to clone the old or new installation?
For a new installation, where can I still find the instructions?

**Comment by tmsd2001** [comment]
For the beginning, I used the variant with clone the disk to a bigger one.
NC seems to be running.
But why df shows 100% and du only 8% disk use is still unclear.

**Comment by tmsd2001** [comment]
I think I found the lost memory.
I have a mounted backup drive, I thought at least.
The drive was not mounted and the backup goes to the local drive.

**Comment by enoch85** [comment]
Glad you found it! :)
