### ISSUE TITLE
How do I compress VHDX? (Normal commands aren't working)

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/vm#1166]
So I am trying to compact the VHDX which contains the data portion of my Hyper-V VM to reclaim free space on my host machine. I'm the only user, it says I am using 1.2 TB. I have already cleaned out my trashbin and versions with occ before trying to compress. My VHDX after compression did not change size and is still at 8 TB allotted (it's dynamic expanding). I'm also using ZFS as setup in the install script. One SSD for Ubuntu OS and core apps and One HDD for Nextcloud's Data exclusively. The HDD is what I am trying to compact. This is the script I normally use for compacting dynamically expanding VHDX but it doesn't work for this VM. What am I doing wrong?
```powershell
$sVHD_Path = "S:\Virtual Machines\Virtual Hard Disks\ncdata.vhdx"
Mount-VHD -Path $sVHD_Path -ReadOnly
Optimize-VHD -Path $sVHD_Path -Mode Full
Dismount-VHD $sVHD_Path
```

**Comment by enoch85** [comment]
Thanks for your question @BetaLeaf. I'm afraid you would get better answers on Google, or https://help.nextcloud.com

I'm a VMware guy more than Hyper-V.

Please post your findings here so that others can make use of it. 

Thanks!

**Comment by enoch85** [comment]
One month - no response --> closing.
