### ISSUE TITLE
Mailserver alongside Nextcloud VM

### ISSUE THREAD

**Issue by karkraeg** [nextcloud/vm#1167]
I felt brave and installed with the scripts, everything went exceptionally well - my nextcloud on an VPS is up and runinng. Now I’m wondering if I could run a mailserver on the same server. If so, which package would you recommend and what should I keep in mind when doing so? Would [mail-in-a-box](https://mailinabox.email) or [Mailcow](https://mailcow.email) be an option?

**Comment by conamu** [comment]
Actually, it went really well for me too. I combined the nextcloud installer and iredmail installer, configured my dns and ports for mailserver traffic and in about 3 hours you got yourself a full fledged Mail and Cloud service. I love this stuff :D.
I would recommend installing it on a seperate VM. The Iredmail install script recommends installingt it on a clean machine and also requires its own webserver for management of domains, users, and mailboxes.
This is a really good tutorial.
https://www.linuxbabe.com/mail-server/ubuntu-18-04-iredmail-email-server
I am using Rainloop Mail as Nextcloud App as Webmail Client.

You could run a mailserver on the same server, but i dont recommend it if you dont know how the separate services work in Mail transfer.
Alternatively, if you end up blacklisted everywhere, you can relay your sent emails to a service like mailgun to get the top delivarability.

**Comment by karkraeg** [comment]
Thanks! I’ll look into it, but right now I dont have a second VPS available.

**Comment by enoch85** [comment]
Closing this as we won't add it. Thanks for your input though.
