### ISSUE TITLE
vague/unclear prompt "if you want to bypass this check..."

### ISSUE THREAD

**Issue by rjhornsby** [nextcloud/vm#1182]
## Steps to reproduce
1. run nextcloud_install_production.sh
2. wait for the prompt in question that begins with "If you want to bypass this check..."

## Expected behaviour

After `nextcloud_install_production.sh` runs for a bit, it pauses to display an ncurses style prompt (see screenshot) that begins with "If you want to bypass this check..." and ends with "YOU HAVE BEEN WARNED!"

While there's the somewhat oblique reference about 3/4 into the lead sentence to something called "ram_check X" it's not clear what _this_ is referring to in the beginning "...bypass _this_ check..."

It's unclear what this prompt is trying to communicate. Certainly it's suggesting there are consequences for bypassing the check - but otherwise the dialog beginning with "If you want to bypass this check..." is confusing and vague.

## Actual behaviour

The only choice to the prompt is `<OK>`, so after puzzling over the dialog for a couple of minutes, hit `<OK>` - then and only then does it become clear what's going on because the script exits with an error:

```
Error: 2 GB RAM required to install Nextcloud!
Current RAM is: (.90 GB)
```

The prompt only makes sense with the added context of this error message. The prompt was raised because of an error. Unfortunately, nothing in the prompt itself (prior to seeing the error message, after accepting the `<OK>`) indicates a problem.

Maybe a prompt that includes something to the effect of "there's an error (not enough RAM), script will now exit. If you wish bypass the memory requirement check [do this], but note the consequences" would help.

Alternatively, if there was no prompt at all and just a quick "what to comment out" shell message along with the error that would be enough. The pause/prompt isn't really necessary - the script is about to exit anyway. IMHO.

## Server configuration

**Nextcloud server version:** 18.0.3

**Server OS** Raspbian Buster

#### Screenshots

attached below (sorry don't have an imgur account)

![Screen Shot 2020-04-18 at 14 40 02](https://user-images.githubusercontent.com/5077610/79670032-947bdb80-8185-11ea-8234-3212dadf3456.png)

**Comment by enoch85** [comment]
Hi, 

The script is intended for Ubuntu Server, I can see that you run this on Buster. 

Please try Ubuntu 18.04 and report back if you got the same issue.

Thanks!

**Comment by enoch85** [comment]
@rjhornsby Hey, feel free to make a PR with the changes you think is better.

The check is warning about that you can bypass the RAM and CPU check, but warns if you do.

The code in question is here: https://github.com/nextcloud/vm/blob/master/lib.sh#L636-L646
