### ISSUE TITLE
talk.sh  /var/www/occ: command not found

### ISSUE THREAD

**Issue by fsardillopiz** [nextcloud/vm#1183]
## Steps to reproduce
1.wget https://raw.githubusercontent.com/nextcloud/vm/master/apps/talk.sh
2.bash talk.sh

## Expected behaviour
The script works without errors

## Actual behaviour
script error
## Server configuration
server installation path is /var/www/cloud

**Nextcloud server version:** (see your admin page)
18.03
**Server OS** (Ubuntu server is default)
Ubuntu 18.04

## Logs / Screenshots
sudo: /var/www/nextcloud/occ: command not found
/dev/fd/63: line 952: [: : integer expression expected
/dev/fd/63: line 992: [: : integer expression expected
Could not open input file: /var/www/nextcloud/occ

**Comment by enoch85** [comment]
> server installation path is /var/www/cloud

That's the error. It's not the default path. (Could not open input file: /var/www/**nextcloud**/occ)

**Comment by fsardillopiz** [comment]
thanks for your reply!
where can I change the default path on the secript

**Comment by enoch85** [comment]
Just set `export NCPATH=your/path` in the top of the script.

If that doesn't work, you need to change the lib file from where the variables comes from, which is a bit tricky if you're not a sysadmin.
