### ISSUE TITLE
Files missing error at security check

### ISSUE THREAD

**Issue by jsuhm** [nextcloud/vm#1185]
## Steps to reproduce
1. Install the last VM version (18.0.3)
2. Configure it with the startup script
3. Go to https://my.site.tld/settings/admin/overview

## Expected behaviour
All checks passed

## Actual behaviour
"There are some errors regarding your setup.
    Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation. (List of invalid files… / Rescan…)"

## Server configuration

**Nextcloud server version:** (see your admin page)
18.0.3 up to date

**Server OS** (Ubuntu server is default)
Ubuntu

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install

## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes
## Logs / Screenshots

In https://my.site.tld/settings/integrity/failed:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- 3rdparty/php-opencloud/openstack/env_test.sh.dist
- activity
	- FILE_MISSING
		- check-handlebars-templates.sh
		- compile-handlebars-templates.sh

**Comment by enoch85** [comment]
Hi,

Thanks for your issue. This is not related to the VM scripts itself. Nextcloud is already installed when when you get it so this must be some extra app you installed that produced these errors.

So question is, which app did you install?

**Comment by enoch85** [comment]
Please try the latest release.
