### ISSUE TITLE
Short Question Ubuntu LTS 20.04

### ISSUE THREAD

**Issue by Xyz00777** [nextcloud/vm#1186]
I only wanted to know if the install script is compatibel with ubuntu 20.04 LTS. Tester or not testet?

Regards Patrick

**Comment by enoch85** [comment]
Here's the 20.04 branch: https://github.com/nextcloud/vm/tree/20.04_testing

Feel free to test and report back.

**Comment by enoch85** [comment]
Sorry, this is not possible anymore.

The branch just switched to master, since we will release it in a few days.
