### ISSUE TITLE
notify_admin_gui is still buggy

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1189]
I got "Can't write output" with only one user on the system

cc @szaimen

**Comment by enoch85** [comment]
@szaimen Try to run it with one user several times. It fails like 50% of the times...

**Comment by enoch85** [comment]
Fixed it with `| cut -d "-" -f2 | grep -q " admin"`

**Comment by szaimen** [comment]
Thanks for the additional testing!
I would actually vote for 
`| cut -d "-" -f2 | grep -xq " admin"`

Since it would be possible to have a displayname like "Max admin" which isn't in the admin group but would get notified here as well...
grep -xq would make sure to only choose the user of the whole line is fitting.

**Comment by enoch85** [comment]
OK, please add an `-x` to the command.

And please test it properly with all different scenarios. 

Thanks!

**Comment by enoch85** [comment]
Okay, everything was working fine until we added `-x`

Now same thing appears again:

```

                           
  Unable to write output.  
                           

app:list [--output [OUTPUT]] [--shipped SHIPPED]

Posting notification to users that are admins, this might take a while...
Posting 'Please setup SMTP' to: admin

                           
  Unable to write output.  
                           

app:list [--output [OUTPUT]] [--shipped SHIPPED]

Posting notification to users that are admins, this might take a while...
Posting 'Do you need support?' to: admin
```

@szaimen I thought you tested all possible scenarios?

**Comment by enoch85** [comment]
Sorry, it's `is_app_enabled` that's buggy...

**Comment by szaimen** [comment]
Hm... thats strange!
It works still really reliably in my teseting (have downloaded the newest VM)
in which situation does that error appear for you?

**Comment by enoch85** [comment]
I'm trying out the scripts on digitalocean now with 1 CPU.

It's fixed now anyway. :)
