### ISSUE TITLE
Automatically configures pm.max_children for php-fpm... 

### ISSUE THREAD

**Issue by jaccobrouwerfmbrnl** [nextcloud/vm#1191]
## Steps to reproduce
1. Import the appliance into VMware Workstation Player
2. Follow the instructions and select set static IP address
3. Do not select any extra applications

## Expected behaviour
What I would expect to happen is that the installation would successfully complete.

## Actual behaviour
Instead of a successfull installation after changing the UNIX password and creating a new user and password i Receive the following error:
Automatically configures pm.max_children for php-fpm...
sed: can't read /etc/php/7.4/fpm/pool.d/nextcloud.conf: No such file or directory
Sorry but something went wrong. Please report this issue to ttps://github.com/nextcloud/vm/issues
and include the output of the error message. Thank you!

## Server configuration
2 Processors
4 GB of Memory
Default disk setup 40 and 500 GB VMware Image from https://www.hanssonit.se/nextcloud-vm/
Bridged network setup with a DHCP address at the beginning and a fixed IP address later on.

**Nextcloud server version:** (see your admin page)
Because the installation does not complete I have no idea what the version number is.

**Server OS** (Ubuntu server is default)
Ubuntu server LTS 18.04

**How did you install the VM?** (Scripted install from master **OR** Released version)
VMware Image from https://www.hanssonit.se/nextcloud-vm/ and imported the VMware Image regarding the instructions from https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm-first-setup-instructions

## Network
**Do you use DHCP?**
DHCP in the first stage of the setup and a fixed IP address later on.

**Is port 80 and/or 443 open?**
Both ports are forwarded and open.

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by jaccobrouwerfmbrnl** [comment]
![nextcloud-deployment-error](https://user-images.githubusercontent.com/64271120/80232895-ee811300-8655-11ea-825e-ea42bd490cf5.PNG)

**Comment by enoch85** [comment]
> Ubuntu server LTS 18.04

Please download the latest VM. Ubuntu 18.04 is old nowadays ;)

**Comment by enoch85** [comment]
If you don't have the link, send me a PM and I'll fix it if it wasn't too long since you bought it.
