### ISSUE TITLE
Terminal SSH access

### ISSUE THREAD

**Issue by carlsimmons81** [nextcloud/vm#1194]
## Steps to reproduce
1. Follow the script
2. Reset username and password
3. Log in with username and password works in GUI but not via command line

## Expected behaviour
I would like to be able to log in via the command line

## Actual behaviour
Invalid username or password.

## Server configuration

**Nextcloud server version:** (18.03)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master)

## Network
**Static*

**Is port 80 and/or 443 open?** No, I connect via VPN.

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Please read this section in the documentation: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm-first-setup-instructions?currentPageId=W6yo9OPiqQz3_Mpy

**Comment by carlsimmons81** [comment]
Daniel,

I’m sorry but that doesn’t help me at all.  I’ve been all through that document before I submitted the ticket.  It does not help me log in via SSH on my mac or within the VM directly running on my QNAP.

 

Thank you,

Carl

**Comment by enoch85** [comment]
Look, it's quite simple:

1. The default password is `nextcloud` once the VM is deployed (before the startup script) which is documented in the README when you download, and also in the documentation I linked above, and like everywhere on the internet if you just look for it. :)
2. In the startup script you are prompted to change it.
3. Now you can't login
4. So, what did you change it to?

Maybe do it again (remove the VM, mount it again and start over), and this time, use the SSH terminal from the get go to be sure that all keystrokes work correctly (console can be a bit tricky) - if you read the instructions you should know that already though: https://github.com/nextcloud/vm/blob/master/static/instruction.sh#L24-L27

Just a simple reminder. :)

I don't know how I can be more clear than that.

Good luck! :+1:
