### ISSUE TITLE
My nextcloud self-destroyed

### ISSUE THREAD

**Issue by conamu** [nextcloud/vm#1198]
## Steps to reproduce
1. Installed nextcloud 18 with script
2. it ran normally for a couple of weeks

## Expected behaviour
It should run normally

## Actual behaviour
I found that my client is not synching anymore.
Nextcloud on its index page says, that it appears that i want to reinstall.
But i didnt do a reinstallation, i looked into the config and it was empty.
## Server configuration

**Nextcloud server version:** 18

**Server OS** Ubuntu 18.04 LTS

**How did you install the VM?** Scripted

## Network
DHCP

**Is port 80 and/or 443 open?** yes

**Comment by conamu** [comment]
I there anyway, that i can see what happened? in the status it just say it stopped apache server.
After a reboot i looked into the config and it was empty.

Onl thing there is this:

`<?php
$CONFIG = array (
  'instanceid' => 'ocpcrcox9lmb',
);`

**Comment by conamu** [comment]
I just saw, that in my nextcloud log, it updated automatically to the release released on the 24th of april.
do configs get backed up after updates?

**Comment by conamu** [comment]
UPDATE: Managed to find backups

**Comment by enoch85** [comment]
Glad to hear the issue was resolved!

May I ask if you made use of the backups made by the update script, or your own backups?

Runing the automated updater is always a risk, hence a proper backup is always a good idea.

**Comment by conamu** [comment]
Yes i am using the backups. Although i have the data, sql dump and apps, im unable to restore everything. my only problem was that the partition dedint resize with the vm disk, i didnt know that i would have to resize the partition too. Im still stuck but i still got the original server. slowly runnng out of options.

Does the way you restore backups with your script defer from the way you do it with a manual nextcloud install? 

if yes, id gladly appreiate it if there is a script for that.
i already tried out replacing the apps and config, changing the sql password, replacing the whole nextcloud folder and turnserver config but it always results in an internal server error.

**Comment by enoch85** [comment]
All backups of the server are save here: https://github.com/nextcloud/vm/blob/master/lib.sh#L17

I have no script for that, but it's pretty well documented in the Nextcloud documentation: https://docs.nextcloud.com/server/18/admin_manual/maintenance/backup.html
