### ISSUE TITLE
Rebrand the VM TOTALLY

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#12]
Right now there are a lot of references to Tech and Me, as I developed it there from start. I would appreciate a PR that changed the branding to "Nextcloud Community" instead.

Welcome with your PR! :)

**Comment by mar1u5** [comment]
I will look into that tomorrow :wink:

**Comment by mar1u5** [comment]
- How should we go with the copyright mentions? (c) 2016 Nextcloud Community instead of Technology and Me?

**Comment by mar1u5** [comment]
Just some questions: 

- How should we go with the copyright mentions? (c) 2016 Nextcloud Community instead of **Tech and Me**?
- Should we move Documentation stuff to Nextcloud?
- Should we remove also your email and replace it with a link to the Forum?

@enoch85

**Comment by enoch85** [comment]
@mar1u5 Thanks! 

- The copyright still stands the same, Tech and Me, because I made it :)
- All the documentation is already on Tech and Me, so no need to write a brand new wiki for it. It will just be 2 places to maintain instead of 1.
- Which email do you mean?

**Comment by mar1u5** [comment]
**index.php**

Don't hesitate to ask if you have any questions. My email is:daniel@techandme.se. 
Same for the donation-link. Should it stay?

**Comment by enoch85** [comment]
Aah right! Change that please. Feel free to rewrite the text there overall.

**Comment by enoch85** [comment]
Please also add links to where you should post issues on the first page, and if you tired the VM maybe add instructions as you would have wanted them to be presented. <-- in the index.php
