### ISSUE TITLE
nextcloud 18.0.3 script failure in php 7.4

### ISSUE THREAD

**Issue by jwallmon** [nextcloud/vm#1200]
i paid & downloaded nextcloud for hyper-v.  

during the install/setup I received an error during the php 7.4 install.

i made screenshot of the error & have attached it.  

at the moment, i'm looking through other posts/websites to see if i can get around php 7.4 & use the prior php version.  or see what else i can do to get nextcloud working.

thank you,
- john 

![Nextcloud error - php 2](https://user-images.githubusercontent.com/64416220/80378386-95d69380-886a-11ea-89aa-69bb18d84396.PNG)

**Comment by enoch85** [comment]
Yes, this is known.

You can't use the old VM anymore. Please get the latest one and try again.

You can find the latest release here: https://www.hanssonit.se/nextcloud-vm/

**Comment by jwallmon** [comment]
Daniel,

I understand what you’re saying… but I this is not an old VM I am using.  I just bought & downloaded the VM end of last week. I paid for this VM on Apr 23, 2020.  (I can email you my receipt, if needed.)

If this is a known issue, then I would not expect to find this bug in their latest VM.  Unless it was resolved, tested, & the VM updated within a few days ago.

I’ll contact T&M Hansson to see if they have an even more updated VM available for download.

John

**Comment by enoch85** [comment]
> If this is a known issue, then I would not expect to find this bug in their latest VM

As I said, you're not using the latest VM, this bug doesn't exist in the new VM.

> Unless it was resolved, tested, & the VM updated within a few days ago.

That's exactly what happened.

Please download it again (using the same link) and try again.

**Comment by enoch85** [comment]
https://help.nextcloud.com/t/regarding-nextcloud-vm-and-os-versions/79636
