### ISSUE TITLE
Update to Nextcloud 18.0.4

### ISSUE THREAD

**Issue by IdefixRC** [nextcloud/vm#1202]
Not sure if this is an error or expected behavior (warning only)

## Steps to reproduce
1. run update script from 18.0.3 to 18.0.4

## Actual behaviour
During the upgrade the following error message appeared:
 Your current Ubuntu version is 18.04 but must be between 20.04 - 20.04.6 to upgrade Redis.   

## Server configuration

**Nextcloud server version:** 18.0.3

**Server OS** Ubuntu server

**How did you install the VM?** installed from script

**Comment by IdefixRC** [comment]
Update: the update to 18.0.4 seems to have worked despite the error. If the above is not critical maybe a change to the notification text should be done.

**Comment by enoch85** [comment]
The message is there for a reason:

https://www.techandme.se/ubuntu-20-04-and-our-vms/

Thanks for posting your issue though! 👍
