### ISSUE TITLE
Nextcloud Installation aborted - Your current version are still not compatible with the version required to run this script

### ISSUE THREAD

**Issue by lautor80** [nextcloud/vm#1203]
## Steps to reproduce
1. VM ware installation with Hyper-V
2. Installation started
3. Logged in with ncadmin user
4. Error occured
   Your current version are still not compatible with the version required to run this script
   Your data directory is invalid
   Ensure there is a file called ".ocdata" in the root of the data directory
   ...

## Expected behaviour
Tell us what should happen

## Actual behaviour
The installation should continue

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots

https://imgur.com/lPLYBle

**Comment by enoch85** [comment]
Please download the latest VM using the same link when you bought it (it's valid for 10 days) and then try again.

The new VM was released the 24:th of April.

You can also read this: https://www.techandme.se/ubuntu-20-04-and-our-vms/

**Comment by lautor80** [comment]
I bought and downloaded it yesterday, so it should have been the latest
version. Did it today again. The result is still the same. The installation
is stopping because of the given error.
[image: Error Nextcloud installation.PNG]

How to proceed?

BR Torsten

Am Di., 28. Apr. 2020 um 16:05 Uhr schrieb Daniel Hansson <
notifications@github.com>:

**Comment by lautor80** [comment]
Please find enclosed the entire report what happened.

+-----------------------------------------------------------------------+
|      Welcome to the first setup of your own Nextcloud Server! :)      |
|                                                                       |
| To run the startup script type the sudoer password, then hit [ENTER]. |
| The default sudoer password is: nextcloud                             |
|                                                                       |
| You can find the complete install instructions here:                  |
| Nextcloud VM              = https://bit.ly/2S8eGfS                    |
| Nextcloud Home/SME Server = https://bit.ly/2k2TNaM                    |
|                                                                       |
| To be 100% sure that all the keystrokes work correctly (like @),      |
| please use an SSH terminal like Putty. You can download it here:      |
| https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html        |
| Connect like this: ncadmin@local.IP.of.this.server                    |
|                                                                       |
| You can schedule the Nextcloud update process using a cron job.       |
| This is done using a script built into this server that automatically |
| updates Nextcloud, sets secure permissions, and logs the successful   |
| update to /var/log/nextcloud/update.log                               |
| Just choose to configure it when asked to do so later in this script. |
|                                                                       |
|  ###################### T&M Hansson IT - 2020 ######################  |
+-----------------------------------------------------------------------+
[sudo] password for ncadmin:
Fetching all the variables from lib.sh...
Testing if network is OK...
Checking connection...
Online!
Testing if network is OK...
Checking connection...
Online!
/dev/fd/63: line 939: [: : integer expression expected
/dev/fd/63: line 979: [: : integer expression expected
Your data directory is invalid
Ensure there is a file called ".ocdata" in the root of the data directory.

Your data directory is not writable
Permissions can usually be fixed by giving the webserver write access to
the roo


                t directory. See
https://docs.nextcloud.com/server/18/go.php?to=admin-dir_permis



sions.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in
/var/www/nextcloud/lib/private/


                                        Console/Application.php:167
Stack trace:
#0 /var/www/nextcloud/console.php(98):
OC\Console\Application->loadCommands()
#1 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#2 {main}Sorry but something went wrong. Please report this issue to
https://git


                    hub.com/nextcloud/vm/issues and include the output of
the error message. Thank y


                                    ou!
sudo -u www-data php /var/www/nextcloud/occ -V failed
root@nextcloud:~#


Am Di., 28. Apr. 2020 um 16:05 Uhr schrieb Daniel Hansson <
notifications@github.com>:

**Comment by enoch85** [comment]
OK, so you both imported *both* disks?

Most often these errors occurs because the user doesn't mount the second drive.

**Comment by lautor80** [comment]
Yes I assigned both harddisk drives as virtual drives as mentioned in your
video.

[image: image.png]   [image: image.png]

The installation is starting from HDD

[image: image.png]

The script starts doing is starting it's job.

First deviation to your video appears here

[image: image.png]

If I do press ENTER after a while where nothing happened I get to the login
which will also work.
But then the error is happening.

Please give me further advice.

BR Torsten


Am Mi., 29. Apr. 2020 um 09:25 Uhr schrieb Daniel Hansson <
notifications@github.com>:

**Comment by enoch85** [comment]
Related: https://github.com/nextcloud/vm/issues/1204

**Comment by enoch85** [comment]
Hi again,

Please try this script: https://github.com/nextcloud/vm/blob/master/static/change-to-zfs-mount-generator.sh 

Does it solve your problem?

**Comment by lautor80** [comment]
Hi Daniel,

the script was doing its job.
Now I'm stucked quite at the end with an error.

[image: image.png]
something is going wrong with the creation of the nextcloud user.

BR Torsten

Am Fr., 1. Mai 2020 um 11:06 Uhr schrieb Daniel Hansson <
notifications@github.com>:

**Comment by enoch85** [comment]
Sorry, I can't see the picture. Please go to Github directly, instead of answering by email.
