### ISSUE TITLE
ZFS doesn't mount the second drive /mnt/ncdata (.ocdata missing due to that)

### ISSUE THREAD

**Issue by jwallmon** [nextcloud/vm#1204]
## Steps to reproduce
1.  setup new hyper-v vm per nextcloud instructions
2.  went through setup & answered questions
3.  setup static ip

## Expected behaviour
i should see the nextcloud logon page 

## Actual behaviour
no blue logon page.  white background.  black text...
Your data directory is invalid Ensure there is a file called ".ocdata" in the root of the data directory. Your data directory is not writable Permissions can usually be fixed by giving the webserver write access to the root directory. See https://docs.nextcloud.com/server/18/go.php?to=admin-dir_permissions. 

## Server configuration
- default hyper-v settings per nextcloud setup steps

**Nextcloud server version:** (see your admin page)
- new hyper-v downloaded yesterday (Apr 27, 2020)

**Server OS** (Ubuntu server is default)
ubuntu

**How did you install the VM?** (Scripted install from master **OR** Released version)
- i just followed the script prompts per the vm

## Network
**Do you use DHCP?**
no.  static ip.  

**Is port 80 and/or 443 open?**
yes

## Logs / Screenshots
![1 - nextcloud - web page](https://user-images.githubusercontent.com/64416220/80525659-943ac780-895f-11ea-8592-9d09ac200b47.PNG)

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```
![2 - nextcloud-log file](https://user-images.githubusercontent.com/64416220/80525624-8a18c900-895f-11ea-9c8e-7d9749a11b57.PNG)

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Send me an email and refer to this issue and we can book a session and have a look.

https://www.hanssonit.se/#contact

**Comment by jwallmon** [comment]
Hi,

I’m ready.

What do you need me to do?

**Comment by enoch85** [comment]
> https://www.hanssonit.se/#contact

**Comment by enoch85** [comment]
Let's keep the everything in one issue.

This is also related: https://github.com/nextcloud/vm/issues/1203

I'll have a look at Hyper-V deployment tomorrow, it's bed time here.

**Comment by enoch85** [comment]
So I think I may have a solution.

Please try this script: https://github.com/nextcloud/vm/blob/master/static/change-to-zfs-mount-generator.sh

Before you run it, make a snapshot of your VM and:

1. Download the RAW file via CLI (wget file.sh)
2. Run it with sudo bash file.sh
3. Reboot
4. Post the outcome here.

Thanks!

**Comment by jwallmon** [comment]
Thank you, Daniel. I’ll try this in the morning

Had to deal with some power issues Tues evening. And it finally coming back early this morning. So, havnt been able to play with the VM

I did figure out that the .ocdata issue was because there was nothing in the /mnt/ncdata folder. I touched it. Now i have a permissions issue. Since i have time i dont mind figuring it out myself.

I’ll try your steps tomorrow. See what happens.

John

On Apr 30, 2020, at 8:07 PM, Daniel Hansson <notifications@github.com> wrote:

﻿

So I think I may have a solution.

Please try this script: https://github.com/nextcloud/vm/blob/master/static/change-to-zfs-mount-generator.sh

Before you run it, make a snapshot of your VM and:

  1.  Download the RAW file via CLI (wget file.sh)
  2.  Run it with sudo bash file.sh
  3.  Reboot
  4.  Post the outcome here.

Thanks!

**Comment by enoch85** [comment]
Important before you run the script: **remove any changes you did to /mnt/ncdata**

So in yur specific case, I would:
1. `rm -rf /mnt/ncdata` (`zpool list` is empty)
2. Follow the steps above

**Comment by enoch85** [comment]
OK, I just got it confirmed, the fix works on a broken system. 

@jwallmon Could you please also confirm?

I will push this to master now

**Comment by jwallmon** [comment]
Ok... took me a bit of time to figure out how to get the raw file from github.  I work with Windows computers all day & still figuring out the behind the scenes of Ubuntu.

Yep.  It also worked for me.  No more ZFS error when it boots up.

I made it to the logon screen & am now logged in.

Now I can work on configuring it for our company- Active Directory, Outlook integration, etc.

Thank you.

John

**Comment by enoch85** [comment]
Thank you very much for confirming! Now I feel confident this is the fix!

Have a nice weekend!

**Comment by enoch85** [comment]
FYI: This is now completely fixed. Just uploaded all new versions of VMs with the latest patch.

**Comment by Railsimulatornet** [comment]
Unfortunately I have to run the ./change-to-mount-generator.sh file after every restart.

Is there a permanent solution here? Thanks in advance
