### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by child-duckling** [nextcloud/vm#1206]
## Steps to reproduce
1. No Clue (sorry :( )
2.
3.

## Expected behaviour
Tell us what should happen
Successful install 
## Actual behaviour
Tell us what happens instead
password authentication failed for user "ncadmin"
## Server configuration
This happened during the install process
**Nextcloud server version:** (see your admin page)
N/A
**Server OS** (Ubuntu server is default)
Ubuntu server
**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install from master
## Network
**Do you use DHCP?**
n/a
**Is port 80 and/or 443 open?**
n/a
#### Log file (/var/log/nextcloud/nextcloud.log)

n/a

#### Installation log (command output)

https://0bin.net/paste/91nm9DUvdbxcCKG3#3wlekOzSp6amMGPZrpUxBrv+7FN6uUKGt288O7+gCjC

#### Screenshoots

n/a

**Comment by enoch85** [comment]
Thanks for posting!

If you need help with installing there's this option: https://shop.hanssonit.se/product/installation-of-nextcloud/

The script works, but you have to run a clean environment else it will fail. So, setup a new server (VPS), don't install anything, and try again.

Hope it helps!
