### ISSUE TITLE
.ocdata

### ISSUE THREAD

**Issue by malteserlp** [nextcloud/vm#1207]
## Steps to reproduce
1. Install Nextcloud on ESXi 5.5
2. 
3.

## Expected behaviour
It should work.

## Actual behaviour
Your data directory is invalid
Ensure there is a file called “.ocdata” in the root of the data directory.
Your data directory is not writable

## Server configuration

**Nextcloud server version:** (see your admin page)
dont know. id say 18
**Server OS** (Ubuntu server is default)
VMware ESXi
**How did you install the VM?** (Scripted install from master **OR** Released version)
inserted vhd in ESXi
## Network
**Do you use DHCP?**
yes
**Is port 80 and/or 443 open?**
yes
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
didnt have one
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi, thanks for posting your issue. 

Can you try this command: `sudo zfs import ncdata`, does it help?

Also, please try on latest VMware Player, just to see if this is a bug in ESXi 5.5 or not.

**Comment by enoch85** [comment]
Please continue the discussion here: https://github.com/nextcloud/vm/issues/1204

**Comment by enoch85** [comment]
Hi again,

Please try this script: https://github.com/nextcloud/vm/blob/master/static/change-to-zfs-mount-generator.sh

Does it solve your problem?
