### ISSUE TITLE
Add to docs

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1209]
https://github.com/nextcloud/vm/pull/1054#issuecomment-578301714

https://github.com/nextcloud/vm/issues/1208#issuecomment-621920602

**Comment by enoch85** [comment]
Also change keyboard picture to US.

**Comment by enoch85** [comment]
@szaimen This is now added: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=bsjb8mahv0jgtdjtc7o0

Please comment if I should add some more text, or change anything.

Thanks!

**Comment by szaimen** [comment]
👍 lgtm, I would only change the titles to:
8.4 How to efficiently use the "SMB-mount" script
8.5 How the "Share-folder" setting works and some aspects to consider

Also maybe the textsize is sometimes a bit small in comparison to the very big screenshots? (and also not everywhere the same)

**Comment by enoch85** [comment]
A little bit long titles IMHO. Could you make the shorter than a *meaning*? ;)

**Comment by szaimen** [comment]
> A little bit long titles IMHO. Could you make the shorter than a _meaning_? ;)

Hm then my sugestions maybe as a subtitle?

Actually, the title for point 8.5 is okay (with my addition) but the current title for point 8.4 isn't correct since this section doesn't describe how the smbmount script itself works. It describes only how you should use it in your VM if possible...
