### ISSUE TITLE
Postgres Authentication

### ISSUE THREAD

**Issue by conamu** [nextcloud/vm#1214]
Hi!
I had to reinstall, since i ran into partitioning issues. 
I have all the necessary files to import my old data and users and its also pretty important for us.

So i tried to login to postgresql with psql using this command:
`sudo psql -U ncadmin -W nextcloud_db < nextclouddb.sql`

I only get a peer authentication failed error, both for ncadmin and for postrgres standard user.
I also logged in with the password provided in the nextcloud config.

is there a way to activate login or to import the db another way?

Thanks for your help!

**Comment by szaimen** [comment]
Hi, for logging in you could try:
`sudo -Hiu postgres psql nextcloud_db`

But this is actually more suited for https://help.nextcloud.com. 
Please ask there.

**Comment by conamu** [comment]
Thanks, that worked!
