### ISSUE TITLE
"Error" after fresh installation of Nextcloud-VM

### ISSUE THREAD

**Issue by nociex** [nextcloud/vm#1218]
## Steps to reproduce
1. Install Nextcloud on QNAP NAS with VirtualizationStation 3
2. Start Nextcloud
3. Error will happen

## Expected behaviour
I always get this error:

http://i.epvpimg.com/tsm7aab.png

## Server configuration

**Nextcloud server version:** (see your admin page)
Newest

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Imported VM in VirtualizationStation 3 with 12GB RAM and 4 Core.
Then I started the VM.

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots

http://i.epvpimg.com/tsm7aab.png

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi,

Thanks for your report!

It's no an error, it's cloud init in Ubuntu finishing up some details.
