### ISSUE TITLE
What is the default login for the latest Nextcloud vm?  It doesnt seem to be posted anywhere. I am going to change the password but I cant even get that far.

### ISSUE THREAD

**Issue by MotionlessMerc** [nextcloud/vm#1222]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by conamu** [comment]
You set it yourself if you used the script. Its the user you exchange ncadmin with. If you used the vm im afraif i cant help, never used it.

**Comment by MotionlessMerc** [comment]
found it in a forum, default login for nextcloud vm is user: ncadmin  password: nextcloud

**Comment by enoch85** [comment]
@MotionlessMerc 

**1.** When you download the VM it's written:
![Screenshot from 2020-05-07 20:28:53](https://user-images.githubusercontent.com/4511254/81331123-66f9c200-90a1-11ea-96db-c3411034a854.png)
**2.** When you downoaded the VM there's a README where it's written:
![Screenshot from 2020-05-07 20:30:01](https://user-images.githubusercontent.com/4511254/81331220-8d1f6200-90a1-11ea-9c14-1f903b3316ed.png)
**3.** When you mounted the VM and started it for the first time, it's written:
![Screenshot from 2020-05-07 20:31:18](https://user-images.githubusercontent.com/4511254/81331336-ba6c1000-90a1-11ea-8664-6770151afcd0.png)
**4.** If you still managed to miss it, it's also in the documentation: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm-first-setup-instructions?currentPageId=W6yo9OPiqQz3_Mpy
**5.** If you don't find the documentation (which also is linked in the README and during the first setup + on the downloads page - well...
> found it in a forum

Please let me know if I should put it somewhere else as well.

Also, as @conamu says, you change it to your own during the first setup. After that, it's not default anymore - it's the password you set yourself.

I hope that sort out any questions regarding the default password.
