### ISSUE TITLE
[Question] Using 40GB vm imge get only 40GB for data?

### ISSUE THREAD

**Issue by Haxy89** [nextcloud/vm#1229]
Hello all,

I have a question regarding to vm image, using this free vm image https://cloud.hanssonit.se/s/zjsqkrSpzqJGE9N I get only 40GB for my nextcloud data? Is true? What is difference between 500Gb, 1TB etc. payed images?

Regards

**Comment by enoch85** [comment]
Compare all our different versions: https://cloud.hanssonit.se/s/AZmZdEztK9JtPcm

Hope it helps!
