### ISSUE TITLE
Apache doesn't start (Nextlcloud VM, VMWare Player on Windows SBS 2011)

### ISSUE THREAD

**Issue by necrevistonnezr** [nextcloud/vm#123]
## Steps to reproduce
1. Install VMWare Player on Windows Small Business Server 2011
2. Start Nextcloud VM

## Expected behaviour
Apache should start

## Actual behaviour
Apache doesn't start 

## Server configuration
**Server version:** 11.0.1 
**Updated from an older installed version or fresh install:** Fresh install

**Comment by enoch85** [comment]
Thanks for your report.

Just saying that Apache doesn't start is very vauge. I need more than that to know where to start looking. 

I.e: 
1. Where in the script does it not start? Or is it after the script is run and the VM is setup?
2. Do you have logs?
3. Did you change anything manually?

**Comment by necrevistonnezr** [comment]
Everything installs fine but Apache doesn't start on rebooting the VM. 
I haven't changed anything manually and currently have no logs.
I suspect that the Windows SBS is using port 80?

**Comment by enoch85** [comment]
I don't know anything about Windows, sorry. Can you check /var/logs/apache2/error.log on the server. Also check the access.log in the same folder.

Post the output. Thanks!

**Comment by Ark74** [comment]
@necrevistonnezr by any chance are you using your nextcloud instance locally?
Or are you running it on a VPS?
In case your are using it on a VM locally, please start over we just closed a bug for local install.
https://github.com/nextcloud/vm/commit/4380f32123c9a820a54414016dc61e40c40f3b46

**Comment by necrevistonnezr** [comment]
Yes, I tried it locally on a Windows Small Business **Server** 2011 - I think the standard Apache Ports 80 and 443 are in use by the Windows Server.

**Comment by enoch85** [comment]
@necrevistonnezr What exactly do you mean with "Apache doesn't start"? Does it not start in the VM, or does the page doesn't show up due to firewall settings?

**Comment by necrevistonnezr** [comment]
"journalctl -xe" shows an error "Apache Service did not start... ip ' ' not valid .... exit code" (sorry, I cannot specify further as I'm not in front of the machine but in a train)

**Comment by enoch85** [comment]
@necrevistonnezr Ok, when you have the full logs available, please post them here.

**Comment by necrevistonnezr** [comment]
`/var/log/apache2/error.log` is empty.
`/var/log/apache2/access.log` as well.
`systemctl status apache2.service` gives the attached output.
![2017-02-15_133356](https://cloud.githubusercontent.com/assets/8191935/22974611/752f8ddc-f383-11e6-81f6-2c8351b8e579.png)

**Comment by enoch85** [comment]
Thanks for the printscreen. It clearly says that something is wrong in `/etc/apache2/conf-enabl...` (Syntax error)

It's probably referring to `phpmyadmin.conf`. Take a look in that file and see if there is something wrong in that file. 

This issue is not in the VM, it's in your config. --> closing.
