### ISSUE TITLE
change run_update_nextcloud to update_nextcloud

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1233]
I would vote for doing this because it makes sense. Is also only applicable for new installations, hence doesn't destroy anything.

https://github.com/nextcloud/vm/blob/981e6c2c6cb95e9a9d60e8558ab218bd9df0f240/static/change-root-profile.sh#L47

**Comment by szaimen** [comment]
I've searched for run_update_nextcloud in all sites on run_update_nextcloud, and it is only mentioned on this site:
https://docs.hanssonit.se/s/bj101nihv0jgrmfm09f0/faq/d/bj101pihv0jgrmfm0a10/nextcloud-vm
So after a change it is no longer a blocker, is it?

**Comment by enoch85** [comment]
OK, make a PR. :+1:

**Comment by szaimen** [comment]
done 👍
