### ISSUE TITLE
https://ports.yougetsignal.com/ return 403 Forbidden

### ISSUE THREAD

**Issue by Haxy89** [nextcloud/vm#1234]
Port forwarding service returns 403 causes tls settings scrips failed

**Comment by enoch85** [comment]
*Siigh* Have they blocked it?!

Will have to check, thanks for your report.

**Comment by enoch85** [comment]
Seems like someone is spamming it: https://ports.yougetsignal.com/check-port.php

`{"status":"failure","message":"System temporarily offline due to heavy load."}`

Let's wait and see, I've sent them an email.

**Comment by Haxy89** [comment]
Ok, Thanks!

**Comment by enoch85** [comment]
Please try again
