### ISSUE TITLE
OnlyOffice does not works localy when external domain was added during installation

### ISSUE THREAD

**Issue by Haxy89** [nextcloud/vm#1235]
#Steps to reproduce
1. Setup clear Ubuntu server vm
2. Use https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/bj0vl4ahv0jgrmfm0950/build-your-own-nextcloud-vm to build nextcloud vm
3. During set up set TLS for private domain
4. After installation disable port forwarding on your router (I use vpn)
5. Everything works fine except OnlyOffice, it still want to use external domain instead local ip (see settings)

## Expected behaviour
OnlyOffice should use nextcloud machine ip when in local network and domain address when outside

## Actual behaviour
Seems like OnlyOffice always wants to use domain event when in local network

## Server configuration

**Nextcloud server version**
NEWEST
**Server OS** (Ubuntu server is default)
NEWEST
**How did you install the VM?** (Scripted install from master **OR** Released version)
https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/bj0vl4ahv0jgrmfm0950/build-your-own-nextcloud-vm
## Network
**Do you use DHCP?**
NO
**Is port 80 and/or 443 open?**
When generating tls cert, after that close these ports, I use vpn to connect from outside my network
## Logs / Screenshots

<img width="327" alt="1" src="https://user-images.githubusercontent.com/37550896/81480972-48283680-922d-11ea-9448-4ac768219d08.PNG">

#### Log file (/var/log/nextcloud/nextcloud.log)

<img width="719" alt="2" src="https://user-images.githubusercontent.com/37550896/81480973-49596380-922d-11ea-8e1e-ae9f2b30b3bf.PNG">

Thanks for helping

**Comment by enoch85** [comment]
> Thanks for helping

This is a bug tracker, not the way of getting support.

With that said, local IP is not supported, you need the domain with TLS.

**Comment by enoch85** [comment]
In other words, just follow the setup instructions (run the script and don't make custom changes) and it will work. 

For custom changes you're on your own. You can also get support here: https://help.nextcloud.com.

**Comment by Haxy89** [comment]
Local IP is not supported?
What these last two options are for:

![](https://user-images.githubusercontent.com/37550896/81480972-48283680-922d-11ea-9448-4ac768219d08.PNG)

Using external domain when in local network will cause a looks
