### ISSUE TITLE
fresh install via script leads to redirect loop "The page isn’t redirecting properly"

### ISSUE THREAD

**Issue by chwba** [nextcloud/vm#1238]
## Steps to reproduce
1. Setup Ubuntu server 20 on a VM
2. use nextcloud production script to install nextclouid
3. follow installation procedure until completion
4. let it reboot
5. run the startup script
6. open the associated domain
Important note: accessing the nextcloud gui by browsing to the IP directly works.

## Expected behaviour
reach the nextcloud login page

## Actual behaviour
the browser shows an error "The page isn't redirecting properly"

## Server configuration
Ubuntu Server 20
**Nextcloud server version:** (see your admin page)
"The newest one that the installtion script would install"
**Server OS** (Ubuntu server is default)
Ubuntu Server
**How did you install the VM?** (Scripted install from master **OR** Released version)
A bought VM from a hoster, the frontend gui is https://www.virtualizor.com/, virtualization is KVM
## Network
**Do you use DHCP?**
No, static IP
**Is port 80 and/or 443 open?**
yes
#### Log file (/var/log/nextcloud/nextcloud.log)
this log is empty

#### Installation log (command output)
Thats not possible, because i did not take a screenshot before the reboot

#### Screenshoots
None

**Comment by enoch85** [comment]
Which apache confs are enabled?

This is probably related to a proxy in front of your backend server (Nextcloud)

**Comment by chwba** [comment]
I am only using cloudflare, so if you consider that a proxy, then yeah. How would I proceed to fix this? I ran the installation script, not sure which apache confs it activated, how could I find out? Also, wouldnt it make sense to have nextcloud use cloudflares SSL certificate, is there a way to add it?

**Comment by enoch85** [comment]
Well, Cloudflare does it's thing with the redirects as well, so maybe check your settings there to begin with?

**Comment by chwba** [comment]
Which settings should I check over there? I set the A entry to the backends IP and created a bypass rule for Cache and Performance, SSL is set to flexible mode, anything else?
