### ISSUE TITLE
Script-based-installation: Script can't see second driver added to vm

### ISSUE THREAD

**Issue by Haxy89** [nextcloud/vm#1241]
I have two disks added to vm, screen from fdisk -l:
![image](https://user-images.githubusercontent.com/37550896/81676298-fa3f4880-944f-11ea-80ef-e908d1384456.png)

But scrips throw me an error that can't see second disk (250Gb)
![image](https://user-images.githubusercontent.com/37550896/81677255-11cb0100-9451-11ea-858e-7cfc64e2ba0d.png)

VM is Ubuntu server 20.04, script from: https://docs.hanssonit.se/s/bj0vl1ihv0jgrmfm08j0/build-your-own/d/bj0vl4ahv0jgrmfm0950/nextcloud-vm

**Comment by enoch85** [comment]
1. You should not add a second disk and mount it. 
2. It should be **vdb** and not vda.
2. It should not be a partition disk, it should be a **second** disk.

Hope it helps!

**Comment by Haxy89** [comment]
What?
There is a second disk vdb!
![image](https://user-images.githubusercontent.com/37550896/81685002-e26bc280-9457-11ea-990a-f2538b49a96e.png)

vda is 50gb first disk where ubuntu is installed

**Comment by Haxy89** [comment]
Many thanks for help and fast closing this BUG (no [Support]) ;)
Prepared bug fix for you https://github.com/nextcloud/vm/pull/1242

**Comment by enoch85** [comment]
Sorry! Missed that one.

Nice fix, I was about to do the same actually but you got ahead. :)
