### ISSUE TITLE
Add more folders - organize

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1245]
Maybe we should create more specific folders like:

- Configurations scripts
- Really static scripts (never changes)
- Network related
- Etc, etc...

The add more functions like:
- `run_configuration_script`
- `run_network_script`

cc @szaimen

**Comment by szaimen** [comment]
hm yes, the only problem is, that everything relies on the current sort-order. So if somebody is trying to start over with an older VM, it could happen, that it will not work, if we move some scrips to another folder.

e.g. the nextcloud_configuration script has to be in the static folder because otherwise it will not work for anyone that uses an older VM

What could be a solution to solve that problem?

I could only imagine to put a run_configuration_script into the old nextcloud_configuration which would then download the new script but it would not be really neat because we couldn't delete the nextcloud_configuration script inside the static folder...

BTW: what about new functions like:
```
# call like: run_script folder_variable name_of_script
# e.g. run_script APP additional_apps
run_script() {
    rm -f "${SCRIPTS}/${2}.sh" "${SCRIPTS}/${2}.php" "${SCRIPTS}/${2}.py"
    if curl_to_dir "${!1}" "${2}.sh" "$SCRIPTS"
    then
        bash "${SCRIPTS}/${2}.sh"
        rm -f "${SCRIPTS}/${2}.sh"
    elif curl_to_dir "${!1}" "${2}.php" "$SCRIPTS"
    then
        php "${SCRIPTS}/${2}.php"
        rm -f "${SCRIPTS}/${2}.php"
    elif curl_to_dir "${!1}" "${2}.py" "$SCRIPTS"
    then
        install_if_not python3
        python3 "${SCRIPTS}/${2}.py"
        rm -f "${SCRIPTS}/${2}.py"
    else
        print_text_in_color "$IRed" "Downloading ${2} failed"
        print_text_in_color "$ICyan" "Script failed to download. Please run: 'sudo curl -sLO ${STATIC}/${1}.sh|php|py' again."
        exit 1
    fi
}

# call like: download_script folder_variable name_of_script
# e.g. download_script APP additional_apps
download_script() {
    rm -f "${SCRIPTS}/${2}.sh" "${SCRIPTS}/${2}.php" "${SCRIPTS}/${2}.py"
    if ! { curl_to_dir "${!1}" "${2}.sh" "$SCRIPTS" || curl_to_dir "${!1}" "${2}.php" "$SCRIPTS" || curl_to_dir "${!1}" "${2}.py" "$SCRIPTS"; }
    then
        print_text_in_color "$IRed" "{$2} failed to download. Please run: 'sudo curl -sLO ${!1}/${2}.sh|.php|.py' again."
        print_text_in_color "$ICyan" "If you get this error when running the nextcloud-startup-script then just re-run it with:"
        print_text_in_color "$ICyan" "'sudo bash $SCRIPTS/nextcloud-startup-script.sh' and all the scripts will be downloaded again"
        exit 1
    fi
}
```

**Comment by szaimen** [comment]
BTW: I think this is cleaner:
```
# For legacy reasons
[ -n "$NC_UPDATE" ] && nc_update && unset NC_UPDATE
# New function to get the needed variables. (no longer NC_UPDATE=1 is needed; you can call just nc_update
nc_update() {
CURRENTVERSION=$(sudo -u www-data php $NCPATH/occ status | grep "versionstring" | awk '{print $3}')
NCVERSION=$(curl -s -m 900 $NCREPO/ | sed --silent 's/.*href="nextcloud-\([^"]\+\).zip.asc".*/\1/p' | sort --version-sort | tail -1)
STABLEVERSION="nextcloud-$NCVERSION"
NCMAJOR="${NCVERSION%%.*}"
NCBAD=$((NCMAJOR-2))
}
```

**Comment by enoch85** [comment]
A lot to think about. I will answer when I have time. 

Thanks for your suggestions!

**Comment by szaimen** [comment]
BTW: Wouldn't it be better to execute here:
https://github.com/nextcloud/vm/blob/92582d354c760c5b67b53062ad0ed346883d6cbb/static/main_menu.sh#L30
run_app_script additional_apps
?

**Comment by szaimen** [comment]
I though about what we could do to move some scripts to other folders and this is what I came up with:

after #1246 is merged, we could simply do the following to remain backwards compatibility but beeing able to move e.g. configuration scripts over to new folders:
```
run_static_script() {
if [ "${1}" == "server_configuration" ] || [ "${1}" == "nextcloud_configurarion" ]
then
    run_configuration_script "${1}"
else
    run_script STATIC "${1}"
}

download_static_script() {
if [ "${1}" == "server_configuration" ]
then
    download_configuration_script "${1}"
else
    download_script STATIC "${1}"
}
```

**Comment by enoch85** [comment]
Let's continue in https://github.com/nextcloud/vm/issues/1290 instead.
