### ISSUE TITLE
nextcloud_install_production.sh fails to find a second disk.

### ISSUE THREAD

**Issue by omnidelic** [nextcloud/vm#1248]
Problem: nextcloud_install_production.sh fails to find a second disk. I've tried both the auto and manual options.

Configuration: Ubuntu Server 20.04 installed on a Nuc10 with 2 disks. Second disk is formatted ext4 and mounted on /mnt/ncdata during server install.

$ df -h

	Filesystem      Size  Used Avail Use% Mounted on
	udev             16G     0   16G   0% /dev
	tmpfs           3.2G  1.6M  3.2G   1% /run
	/dev/nvme0n1p2  468G   11G  434G   3% /
	tmpfs            16G     0   16G   0% /dev/shm
	tmpfs           5.0M     0  5.0M   0% /run/lock
	tmpfs            16G     0   16G   0% /sys/fs/cgroup
	/dev/nvme0n1p1  511M  7.8M  504M   2% /boot/efi
	/dev/loop0       55M   55M     0 100% /snap/core18/1705
	/dev/loop1       69M   69M     0 100% /snap/lxd/14804
	/dev/loop2       28M   28M     0 100% /snap/snapd/7264
	tmpfs           3.2G     0  3.2G   0% /run/user/1000
	/dev/sda1       1.8T   77M  1.7T   1% /mnt/ncdata

And then following line 21 thru 30 in format-sda-nuc-server.sh

$ umount /mnt/*
$ fdisk -l | grep sda | awk '{print $2}' | cut -d ":" -f1 | head -1

Output is /dev/sda which *should* pass. What am I missing?

**Comment by Haxy89** [comment]
„Second disk is formatted ext4 and mounted on /mnt/ncdata during server install.”

Do not mount second disk before run the installation script

**Comment by omnidelic** [comment]
Unmounted the second disk and ran the script again, still fails to find the disk. I did a manual format and mount during the server install, should I have just ignored the second disk at that point?

**Comment by Haxy89** [comment]
„Unmounted the second disk and ran the script again, still fails to find the disk.” 
Show the error.
Paste fdisk -l before run nic installation script

**Comment by omnidelic** [comment]
I didn't change anything, just unmounted /dev/sda1 and then ran the install script again.

	Filesystem      Size  Used Avail Use% Mounted on
	udev             16G     0   16G   0% /dev
	tmpfs           3.2G  1.6M  3.2G   1% /run
	/dev/nvme0n1p2  468G   11G  434G   3% /
	tmpfs            16G     0   16G   0% /dev/shm
	tmpfs           5.0M     0  5.0M   0% /run/lock
	tmpfs            16G     0   16G   0% /sys/fs/cgroup
	/dev/nvme0n1p1  511M  7.8M  504M   2% /boot/efi
	/dev/loop0       55M   55M     0 100% /snap/core18/1705
	/dev/loop1       69M   69M     0 100% /snap/lxd/14804
	/dev/loop2       28M   28M     0 100% /snap/snapd/7264
	tmpfs           3.2G     0  3.2G   0% /run/user/1000

**Comment by Haxy89** [comment]
This is not „fdisk -l” command output

**Comment by omnidelic** [comment]
Disk /dev/loop0: 54.97 MiB, 57614336 bytes, 112528 sectors
	Units: sectors of 1 * 512 = 512 bytes
	Sector size (logical/physical): 512 bytes / 512 bytes
	I/O size (minimum/optimal): 512 bytes / 512 bytes


	Disk /dev/loop1: 68.99 MiB, 72318976 bytes, 141248 sectors
	Units: sectors of 1 * 512 = 512 bytes
	Sector size (logical/physical): 512 bytes / 512 bytes
	I/O size (minimum/optimal): 512 bytes / 512 bytes


	Disk /dev/loop2: 27.9 MiB, 28405760 bytes, 55480 sectors
	Units: sectors of 1 * 512 = 512 bytes
	Sector size (logical/physical): 512 bytes / 512 bytes
	I/O size (minimum/optimal): 512 bytes / 512 bytes


	Disk /dev/nvme0n1: 476.96 GiB, 512110190592 bytes, 1000215216 sectors
	Disk model: Samsung SSD 970 PRO 512GB
	Units: sectors of 1 * 512 = 512 bytes
	Sector size (logical/physical): 512 bytes / 512 bytes
	I/O size (minimum/optimal): 512 bytes / 512 bytes
	Disklabel type: gpt
	Disk identifier: 0A8CB26E-EAF8-4101-91F3-540FB0ECFEEA

	Device           Start        End   Sectors   Size Type
	/dev/nvme0n1p1    2048    1050623   1048576   512M EFI System
	/dev/nvme0n1p2 1050624 1000212479 999161856 476.4G Linux filesystem


	Disk /dev/sda: 1.84 TiB, 2000398934016 bytes, 3907029168 sectors
	Disk model: Samsung SSD 860
	Units: sectors of 1 * 512 = 512 bytes
	Sector size (logical/physical): 512 bytes / 512 bytes
	I/O size (minimum/optimal): 512 bytes / 512 bytes
	Disklabel type: gpt
	Disk identifier: A3238DF1-9F07-43CE-BEBA-213181C8C67A

	Device     Start        End    Sectors  Size Type
	/dev/sda1   2048 3907026943 3907024896  1.8T Linux filesystem

**Comment by Haxy89** [comment]
"cat /sys/devices/virtual/dmi/id/sys_vendor" command output?

**Comment by omnidelic** [comment]
$ cat /sys/devices/virtual/dmi/id/sys_vendor
	Intel(R) Client Systems

**Comment by Haxy89** [comment]
Soo currently https://github.com/nextcloud/vm/blob/master/static/format-chosen.sh script does not support your sys vendor. Please provide a PR with patch for https://github.com/nextcloud/vm/blob/master/static/format-chosen.sh in line 49 should be
"elif [[ "$SYSVENDOR" == "DigitalOcean" || "$SYSVENDOR" == "Intel(R) Client Systems" ]];"

**Comment by omnidelic** [comment]
Thanks, this makes sense. Hoping I submitted correctly, this is my first ever PR :)

**Comment by enoch85** [comment]
Thanks for helping out @Haxy89!

@omnidelic Is this run on Digitalocean?

**Comment by omnidelic** [comment]
No, it's a baremetal install on an Intel NUC. It would be cleaner to add another if statement rather than adding it into the Digitalocean test. I'll submit another PR.

**Comment by omnidelic** [comment]
Can confirm this PR fixed my install issue. Thanks for your help!
