### ISSUE TITLE
Deadlock Exceptions

### ISSUE THREAD

**Issue by 104e85bd** [nextcloud/vm#1252]
I had recently reinstalled this Nextcloud installation as I was experiencing these issues prior as well, and thought something didn't install properly. This is a fresh installation I made using your VM script a few days ago, on Ubuntu 20.04 LTS. There is no previous database or data uploaded from the previous installation. When uploading larger file sets, I'm getting a lot of Deadlock Exception errors in the logs and the uploads are failing. I have a few of these Nextcloud installations with your script, and some previous installations do not experience these issues with the same file uploads. 

Here is a copy of one of the errors in the log:
`Doctrine\DBAL\Exception\DeadlockException: An exception occurred while executing 'UPDATE "oc_filecache" SET "size" = GREATEST(?, "size" + ?) WHERE ("storage" = ?) AND ("path_hash" IN ('d41d8cd98f00b204e9800998ecf8427e', 'd41d8cd98f00b204e9800998ecf8427e', '29ff0edf73a32cb03e437d88fd049245', 'e46cc72327dfc3ccaf32f0a167e6c6d1', 'b9e4f984d1a3519533b44d1e9e8b0ae7', 'f5a69dde47a9b441b6738727fdc895ee', 'c38519de347bf04e646d61b6dcee73be', '02de4c080f1d78aa53c2505542187728')) AND ("size" > '-1')' with params [-1, 1309434, 2]: SQLSTATE[40P01]: Deadlock detected: 7 ERROR: deadlock detected DETAIL: Process 166883 waits for ShareLock on transaction 185765; blocked by process 166804. Process 166804 waits for ShareLock on transaction 185822; blocked by process 166883. HINT: See server log for query details. CONTEXT: while rechecking updated tuple (15,29) in relation "oc_filecache"`

**Comment by conamu** [comment]
It indicates some process may be interrupting data Transfer.

I always invrease the php fpm timeout time a bit, as we are working with multi GB files and that helped solving many error log throws. 

It could be worth a try for you, but i think you might have some other issue.

**Comment by enoch85** [comment]
@conamu Where do you increase the timeout? That would be something for a PR maybe?

**Comment by 104e85bd** [comment]
> @conamu Where do you increase the timeout? That would be something for a PR maybe?

Daniel, is there anything from your end to help this issue and what I should do, or is this outside of the scope of what you 'support' within your VM scripting. I addressed it here as I only use your scripts for my Nextcloud deployments, and its peculiar that it's a repeating problem I've had with some of my deployments, and not others.

**Comment by conamu** [comment]
I dont know how all this with the pulls and merges and so on go on github. Kinda the first project where im contributing a tiny bit. I can comment tommorrow on this, then i can post the file location and parameters.

Basically, php_fpm caused a lot of timeouts and re-initialisation of downloads and uploads, causing false time estimates and longer time take for data transfer. I modified 2 things in php_fpm.conf, that eliminated this.

Will leave the standart path of this file, along with the params.

**Comment by enoch85** [comment]
@conamu Thanks, still waiting here. I have my suspicions about where you are referring to, but it would be nice with some confirmation. :)

**Comment by conamu** [comment]
Sorry, kinda got carried away with the new Nextcloud release haha.

I digged around a bit in my configs as im not really documenting all thus, i definatly should have 🤣.

So, the path /etc/php/7.2/fpm/php.ini

Contains the active config of php, atleast this was the only file my nextcloud responded to in the form of showing actual changes.

What i have done:

Look at the beginning of the File on the Category "Resource Limits"

max_execution_time = 18000
max_input_time = 18000
memory_limit= 512M

This sets the max time for each php scriot to 18000 seconds. I think you can definatly turn that down but it worked for me getting rid of all errors.

**Comment by enoch85** [comment]
Aah ok, thanks, that's actually already set, but to 3600 seconds which is really much already.

We can try to raise it to 7200 even though it shouldn't be needed. Will prepare a PR.

**Comment by enoch85** [comment]
@104e85bd Why was this closed? Is the issue resolved?

**Comment by 104e85bd** [comment]
@enoch85 Sort of. It seems to occur when I have multiple tabs open to the Nextcloud, so I would say it's a client issue and some sort of collision on the front end layer. I can leave it open in case others experience the issue and we can see if it has anything to do with the installation?

**Comment by enoch85** [comment]
Well, as stated above I don't think it has anything to do with the installation.

3600 seconds should be very much more than needed.
