### ISSUE TITLE
[BUG] Missing config variable for audit admin app

### ISSUE THREAD

**Issue by ghost** [nextcloud/vm#1253]
Admin audit app is installing and log file is creating:
```
occ_command config:app:set admin_audit logfile --value="$VMLOGS/audit.log"
install_and_enable_app admin_audit
```
but logging setting is missing so audit.log is never used.
Docs: 
https://docs.nextcloud.com/server/16/admin_manual/configuration_server/logging_configuration.html?#admin-audit-log

Missing part:
```
'log.condition' => [
        'apps' => ['admin_audit'],
],
```

Please add missing part to install script

**Comment by enoch85** [comment]
Thanks for pointing that out, it's now fixed!
