### ISSUE TITLE
Setup script not compatible with recommended server version

### ISSUE THREAD

**Issue by nicolas-arnold** [nextcloud/vm#1264]
Hey there,

this is probably a simple one:

The current docs recommend Ubuntu 18.04 LTS [see here](https://docs.nextcloud.com/server/18/admin_manual/installation/system_requirements.html), whereas the linked setup script fails with the message "This script can only be run on Ubuntu 20.04 (server)".

So at least there is something off sync. Is it recommended to use an older version of the setup script in the case of running 18.04?

If the last chapter on VM is something rather different, it should be more clearly documented that the chapter "Installation via install script" is not an alternative way to achieve what's stated below the top-level headline: `This document provides a complete walk-through for installing Nextcloud on Ubuntu 18.04 LTS`. 

Thanks for all the effort!

_I know this is not a place for discussing setup problems, but I consider the documentation to be part of the code, that's why I'm raising this issue here. I assume the recommended linux version to work well with all the described installation options._

**Comment by enoch85** [comment]
We migrated the Nextcloud installation scripts to be compatible with Ubuntu 20.04, so you cant install with 18.04 any more.

If you find any occurrences where it refers to 18.04 using these scripts, please let me know. You could also contribute by yourself by adding a PR to sort the issue. Simply change the file in question, and send a PR to the repo in question.

**Comment by enoch85** [comment]
You can read more here: https://www.techandme.se/ubuntu-20-04-and-our-vms/
