### ISSUE TITLE
unable to run script

### ISSUE THREAD

**Issue by jnazario** [nextcloud/vm#1265]
## Steps to reproduce
1. loaded OVA
2. ran first installed
3.

## Expected behaviour
run script

## Actual behaviour
ailed to download sudo curl -sLO https://raw.githubusercontect.com/nextcloud/vm/master/lets-encrypt/activate-ssl.shl.sh|.php|.py

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi,

Please download the latest version of the VM, you're running an old version.

Thanks!

**Comment by jnazario** [comment]
Im unable to as its requiring me to purchase which I had already last year. Can you send me link to new version?

Josbel Nazario

**Comment by enoch85** [comment]
Please read this: https://help.nextcloud.com/t/regarding-nextcloud-vm-and-os-versions/79636
