### ISSUE TITLE
Second script failure

### ISSUE THREAD

**Issue by jamessirius** [nextcloud/vm#1274]
Tried to install on Ubuntu 20.04 on AWS

sudo bash /var/scripts/nextcloud-startup-script.sh
Fetching all the variables from lib.sh...
Testing if network is OK... 
Checking connection...
curl: (6) Could not resolve host: github.com
curl didn't produce a 200 status, is the site reachable?
Setting correct interface...
Checking connection...
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	github.com
Address: 140.82.118.4

Testing if network is OK...
Checking connection...
Online!
dpkg-query: no packages found matching zfsutils-linux
This function is only intened to be run if you have ZFS installed.
{locales} failed to download. Please run: 'sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/locales.sh|.php|.py' again.
If you get this error when running the nextcloud-startup-script then just re-run it with:
'sudo bash /var/scripts/nextcloud-startup-script.sh' and all the scripts will be downloaded again

**Comment by enoch85** [comment]
Please download the latest VM and try again. We just released version 19.

Thanks!

**Comment by jamessirius** [comment]
Thanks - but using the scripts rather than the VM. Is there a new version of the script?

**Comment by enoch85** [comment]
It gets constantly updated: https://github.com/nextcloud/vm/commits/master

**Comment by enoch85** [comment]
I fail to reproduce the same error on the latest version --> closing.

**Comment by jamessirius** [comment]
Okay, thanks for trying anyway :)
