### ISSUE TITLE
Make it possible to choose the Docker or Nextcloud App (OnlyOffice Collabora)

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1275]
@szaimen Same thing with Collabora now that happened to OnlyOffice, I think we should move in the same way as we did with OnlyOffice.

Basically, copy the OnlyOffice script, change to Collabora and then move the old script to `/old`.

**Comment by szaimen** [comment]
@enoch85 but that would only make sense after after collabora was changed, no?

**Comment by enoch85** [comment]
https://twitter.com/CollaboraOffice/status/1268113534308814848

**Comment by szaimen** [comment]
So just remove that script?

**Comment by enoch85** [comment]
> Basically, copy the OnlyOffice script, change to Collabora and then move the old script to /old.

1. Move the old script to old
2. Make a new script which is copied from OnlyOffice
3. Change the variables to fit Collabora

**Comment by enoch85** [comment]
https://nextcloud.com/blog/how-to-install-collabora-online-in-nextcloud-hub/

**Comment by enoch85** [comment]
Hmm, when thinking about it, maybe it's better to just leave it as is? Collabora is now fixed and as an end user, maybe its better to choose between Docker or internal App?

**Comment by szaimen** [comment]
> Hmm, when thinking about it, maybe it's better to just leave it as is? Collabora is now fixed and as an end user, maybe its better to choose between Docker or internal App?

👍 Maybe this would have been the better way for onlyoffice, too?

**Comment by enoch85** [comment]
We could do both, with another menu :)

Menu 1:
(Online editing)
    a) Collabora
    b) OnlyOffice
Menu 2:
    a) Docker (extra subdomain required)
    b) Integrated in Nextcloud (no extra subdomain required)

**Comment by szaimen** [comment]
> We could do both, with another menu :)
> 
> Menu 1:
> (Online editing)
> a) Collabora
> b) OnlyOffice
> Menu 2:
> a) Docker (extra subdomain required)
> b) Integrated in Nextcloud (no extra subdomain required)

Hm, isn't that a bit overkill?
But yes, this should be possible 👍

**Comment by enoch85** [comment]
Think "whiptail" rather than menu. The logic is fully possible at least. Don't have so much time now I'm afraid. :/

**Comment by enoch85** [comment]
We should activte OnlyOffice as a docker again.

When choosing either of them, ask the user if he/she wants to install with or without Docker and explain the differences in a `msg_box` followed with a `whiptail`.

**Comment by 104e85bd** [comment]
Sorry for the duplicate issues. I second the notion to create the option to install via Docker again.

**Comment by szaimen** [comment]
I am thinking about this since a while and I've come to the conclusion that installing onlyoffice the nextcloud recommended way is so dead simple, that a script for this isn't really needed. What do you think?

I actually find it still a bit overkill to let the user the choice which way he wants to install onlyoffice since he can easily install the documentserver_community from the nextcloud GUI...

**Comment by enoch85** [comment]
Well, even if overkill I think we should make it possible. I mean, why not. :)

**Comment by szaimen** [comment]
The only downside is the big development effort. A pseudocode looks like this:
```
# 1. Hardwarecheck

# 2. We need the following functions:
is_documentservercommunity_installed
is_collabora_installed
is_onlyofficedocumentserver_installed

uninstall_documentservercommunity
uninstall_onlyofficedocumentserver
uninstall_collabora

install_documentservercommunity
install_onlyofficedocumentserver

# 3. Execution 
if is_collabora_installed
then uninstall_collabora

if ! is_documentservercommunity_installed && ! is_onlyofficedocumentserver_installed
then option to install choose documentservercommunity or onlyofficedocumentserver
-install_documentservercommunity or install_onlyofficedocumentserver

if is_onlyofficedocumentserver_installed
then option to remove, reinstall it or install documentservercommunity
-remove: uninstall_onlyofficedocumentserver
-reinstall: uninstall_onlyofficedocumentserver && install_onlyofficedocumentserver
-install documentservercommunity: uninstall_onlyofficedocumentserver && install_documentservercommunity

if is_documentservercommunity_installed
then option to remove, reinstall it or install onlyofficedocumentserver
-remove: uninstall_documentservercommunity
-reinstall: uninstall_documentservercommunity && install_documentservercommunity
-install onlyofficedocumentserver: uninstall_onlyofficedocumentserver && install_documentservercommunity
```
Do we really want this?

**Comment by szaimen** [comment]
Hm, I think I have an alternative idea which wouldn't be that much of an effort...
