### ISSUE TITLE
Updatenotification script doesn't check if cron update entry is commented

### ISSUE THREAD

**Issue by k-matti** [nextcloud/vm#1276]
https://github.com/nextcloud/vm/blob/master/static/updatenotification.sh line 38 only checks if entry exists in crontab but should also check if it is not commented.

I disable auto update by commenting crontab update entry but now I am getting wrong notification from updatenotification script:

`        "Nextcloud $NCVERSION just became available. Since you are running Automatic Updates at $AUT_UPDATES_TIME:00, you don't need to bother about updating the server manually, as that's already taken care of."`

instead I should get:

`        "Nextcloud $NCVERSION is available. Please run 'sudo bash /var/scripts/update.sh' from your CLI to update your server."`

**Comment by szaimen** [comment]
@enoch85 should we really check if the entry is not commented?

@k-matti why not just delete that line? Then the notification should work as it was meant to be.

**Comment by k-matti** [comment]
I agree I can remove it.
VM official doc says it should be commented so script should be working with this

**Comment by szaimen** [comment]
@enoch85 maybe change the documentation?

**Comment by enoch85** [comment]
- [ ] Change documentation to state that the crontab entry should be removed instead.
