### ISSUE TITLE
[BUG] Updatenotification doestn't appear when using web interface on mobile

### ISSUE THREAD

**Issue by k-matti** [nextcloud/vm#1277]
Firefox on ubuntu 20.04:
![image](https://user-images.githubusercontent.com/66017397/83740944-d7bbdc00-a657-11ea-9006-dfe31b3c6ef3.png)

IOS Safari:

![20-06-04 11-30-52 1415](https://user-images.githubusercontent.com/66017397/83741100-0b970180-a658-11ea-8942-f302f48deb3d.png)

**Comment by szaimen** [comment]
You could try to reload the website on Safari. 
If the notification doesn't show up, it is an upstream error. 

You can report this here:
https://github.com/nextcloud/server/issues
