### ISSUE TITLE
Use logrotate to store logs

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/vm#1280]
## Steps to reproduce
1. Use Nextcloud
2. Check logfiles at `/var/log/nextcloud`
3. Two files are kept: `nextcloud.log`and `nextcloud.log.1`

## Expected behaviour
More than one log file should be saved for archive

## Actual behaviour
One file is kept.

## Solution
Added nextcloud.log to logrotate using webmin and save e.g. 30 log files.

## Server configuration

**Nextcloud server version:** 19.0.0

**Server OS** (Ubuntu server is default)

**How did you install the VM?** Bought with device

#### Screenshoots
<img width="705" alt="Bildschirmfoto 2020-06-07 um 14 01 30" src="https://user-images.githubusercontent.com/2069590/83968163-8580f200-a8c7-11ea-8495-423386f329cd.png">

<img width="654" alt="Bildschirmfoto 2020-06-07 um 14 01 51" src="https://user-images.githubusercontent.com/2069590/83968179-99c4ef00-a8c7-11ea-93da-9e578eb54fc3.png">

**Comment by enoch85** [comment]
Hi @rakekniven 

Thanks for your suggestion, I actually thought Nextcloud logs were rotated more than one time per default. 

I don't know if it would be possible to add another setting to `config.php` which set the numbers of logs to keep?

Using Webmin isn't possible as we can't control Webmin through CLI, so it must be a CLI solution. Any suggestions?

**Comment by rakekniven** [comment]
No need to use webmin IMHO.

In `/etc/logrotate.d` you can place a file to do this.
Cannot give you an example right now as I do not have ssh access to my NUC.

Would that work for your scripts?

**Comment by enoch85** [comment]
Sure, it sounds like it at least. 

I don't have very much time on my hands right now, so if you want you could make a PR and make it happen faster. 

I will look at this when time allows.

**Comment by rakekniven** [comment]
Add file `nextcloud.log.conf` to `/etc/logrotate.d` with the following content:

`/var/log/nextcloud/nextcloud.log {`
`        daily`
`        rotate 30`
`}`

This will copy your log daily and keep 30 log files.

For sure we can decrease the number if you like.

**Comment by rakekniven** [comment]
Check the source of this repo but did not find a way to add my config.

**Comment by rakekniven** [comment]
> I will look at this when time allows.
Ok, it is not urgent.

**Comment by enoch85** [comment]
Wouldn't that mess with this? https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L415-L416

**Comment by rakekniven** [comment]
No, that variable sets the limit before "nextcloud.log" is copied to "nextcloud.log.1".
After that "nextcloud.log.1" will be overwritten again. So you do not get many logs.

**Comment by enoch85** [comment]
So what you're saying is that the Nextcloud option has to be removed, and replace with logrotate?

**Comment by rakekniven** [comment]
Yes, that makes sense or set it to "0".
See https://docs.nextcloud.com/server/19/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=log_rotate_size

**Comment by szaimen** [comment]
I would argue, that 10 files a 10MB is a good size for nextcloud logs. So I would start a PR and do this:
```
Add file nextcloud.log.conf to /etc/logrotate.d with the following content:

/var/log/nextcloud/nextcloud.log {
daily
rotate 10
}
```

The question is: shall this be an option in nextcloud_configuration maybe with the possibility to change the value to something own or shall it get only executed in the install_production script?

Am I missing something? is the log_rotate_size really needed?  or can we just use this in there: https://github.com/nextcloud/vm/blob/e8ef2e2437567cb7ed561183ce3b0a58f98b1646/nextcloud_install_production.sh#L431

**Comment by rakekniven** [comment]
I would not set the size to 10MB.
What will happen if your log file is getting bigger than 10MB on one day?
From my understanding nextcloud will swap the file and logrotate will not save your precious log with full content.

**Comment by szaimen** [comment]
I've set it to unrestricted (0)

**Comment by ruedigerkupper** [comment]
With which Nextcloud Version will this arrive? We run NC 30.0.2 and rotation is still done by Nextcloud itself (it appears)? Do I need to enable any setting? In particular I woul like to increase the number of files to keep in the archive.
Thanks!

**Comment by ruedigerkupper** [comment]
Oh, da…. Sorry, I didn't realize this was an issue report for Nextcloud VM and not standard Nextcloud.
All well, I'l manually set up log rotation on our server then. Sorry for causing irritations :-).
