### ISSUE TITLE
Server is restarted even there was no update

### ISSUE THREAD

**Issue by k-matti** [nextcloud/vm#1283]
```
 then
        sed -i "s|exit|shutdown -r +1|g" "$SCRIPTS"/update.sh
        echo "exit" >> "$SCRIPTS"/update.sh
    fi
```
These lines in automatic_updates.sh cause that server is restarted every time update.sh is run even when there was no update

**Comment by enoch85** [comment]
Also, when you setup automatic updates you are asked if you want to restart. You can choose not to, and do it manually instead. It's up to the end user.

Closing this.

@szaimen FYI.
