### ISSUE TITLE
Create a new "official" branch

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1284]
Had a talk with @karlitschek today and there will be some changes to how the VM are presented on the [downloads page](https://nextcloud.com/install/#instructions-server).

To avoid confusion for the end users (some think that the bought versions of Hansson IT gives the [enterprise support](https://nextcloud.com/enterprise/), that's not the case) there will be a new "Official VM" which is stipped from everything related to Hansson IT.

Basically there will be two options:
1. The main and official (stripped-down vanilla) Nextcloud VM (no Hansson IT or anything like that)
2. An option to download the full blown Hansson IT VM

### What I'm thinking:

**Make a VM that automatically deploys the latest version.**
Make it run the install script (modified and stripped down) with a default username and password. (ncadmin/nextcloud) which will install everything from the ground up. This would remove the need for making new releases and one single OVA could be used, and not changed.

**No need for a startup script**
The current VM comes with a lot of extras which are set in the startup script. It installs apps that the user wants, adds TLS, and make some modifications to make sure the user gets a full blown Nextcloud experience (OnlyOffice, Collabora, Talk and so on). The official VM will not - it should only be a plain Nextcloud installation. So in other words, the only thing needs changing is the default password. We could make that whole thing a function and use it in the installation script directly, as well in the startup script of the full blown VM to avoid extra maintenance work.

**Change permissions**
The current VM use a built in update script to make sure everything (the whole server) is updated with the latest dependencies, it also sets secure permissions. The offiicial VM will not contain a update script. Updates should be handled in the GUI. So in other words, set `www-data` permissions all over.

**Remove the whole /var/scripts folder**
Since the official Nextcloud VM will be a "vanilla" install, there's no need to offer any improvements or modifications at all - hence the whole scripts folder in the VM is not needed.

### What we need to do:
1. Create a new branch in this repo with a modified install script.
2. Create a new OVA (I will do that) which automatically runs the install script once booted.
3. Release the official OVA on Nextclouds server 
4. Add some documentation containing passwords and such.

### When the new OVA is ready
1. Make a PR to change the Nextcloud Downloads page. Make the official VM stand out, and add an option below (or on the side) to download the full blown VM made by Hansson IT (as discussed)

@szaimen You're very welcome to come aboard on this.
@karlitschek Please let me know if we are on the same page here.
@jospoortvliet FYI

Feel free to edit this post if needed.

**Comment by child-duckling** [comment]
Want this!

**Comment by jospoortvliet** [comment]
Sounds good! Clean, simple - if people want more convenience or control they can get your VM, install manually, grab a docker, a snap, or use any other solution!

**Comment by ajayramaswamy** [comment]
Also please consider if you can move the official VM base os to Debian Stable 10 while keeping the Hansson IT version based off Ubuntu so that those of us who dont like the whole snap based packaging in Unbuntu 20.04

**Comment by enoch85** [comment]
@ajayramaswamy The idea here is to make it as easy as possible to maintain. As the current VM is Ubuntu based, and the scripts are customized to fit Ubuntu, then making a Debian won't happen since I'm already overloaded with stuff to do.

You're free to make a PR and make it happen though. :)

**Comment by enoch85** [comment]
Btw, I'm planning to start with this around the release of 19.0.1 just so that you know.

**Comment by bobdig** [comment]
May I ask what the difference would be to a vanilla Ubuntu-Server-installation where you select the  nextcloud snap(?) in the installation process?

**Comment by enoch85** [comment]
@bobdig A VM is a full server environment, a snap is software inside a VM (server).

So I guess the difference here would be that in the VM Nextcloud is installed "bare bone" on the VM itself, whilst installing it as a snap is a totally different thing.

**Comment by karlitschek** [comment]
Good plan! Thanks!!!!

**Comment by enoch85** [comment]
WIP #1302

**Comment by enoch85** [comment]
For those who are interested: https://github.com/nextcloud/vm/tree/official

Still not tested by live users, but several times by myself. Please give feedback in this issue, or email github@hanssonit.se.

Please note; I might remove this branch in the future since it may not be the final solution (I hope it won't be).

Thanks!
