### ISSUE TITLE
Latest VM always displays "Your current version are still not compatible with the version required to run this script"

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/vm#1287]
## Steps to reproduce
1. Download latest VM from https://cloud.hanssonit.se/s/zjsqkrSpzqJGE9N (19.0.0 HUB)
2. Import both disks into a Proxmox VM using `qm importdisk`
3. Boot VM and login with ncadmin/nextcloud

## Expected behaviour
Install script should work correctly

## Actual behaviour
The message "Your current version are still not compatible with the version required to run this script" displaying "Nextcloud 18.0.3":

![image](https://user-images.githubusercontent.com/10073629/84491224-7d98c780-aca4-11ea-8de7-307df9b4f220.png)

## Server configuration
**How did you install the VM?** OVA download and disks imported

**Comment by e-alfred** [comment]
It seems like the Nextcloud release under /var/www/nextcloud/ is 18.0.3. Is this a packaging error?

**Comment by enoch85** [comment]
I triee the VM yesterday (installed it to a customer), and it was 19.

Please try again.

**Comment by e-alfred** [comment]
It seems like importing the VMDK files is problematic, can you provide some RAW images for import/use with KVM?

**Comment by enoch85** [comment]
Nothing that I've planned, but contributions are welcome!
