### ISSUE TITLE
 collabora connection lost permanently

### ISSUE THREAD

**Issue by Tino-ko** [nextcloud/vm#1289]
Hi,

I use the Hyper-V - 2 TB Nextcloud VM from hanssonit.se.
After installation, Collabora connects correctly to the Collabora Online Server (in the LAN, office.NAME.local).
If I then open the Collabora configuration menu again and click on "save", the connection will be lost and will no longer connect.

For the test I set up a bare installation, only with Collabora and SSL. The same.
Thereafter only with Collabora without ssl. The same..

Any ideas?

Thanks
Tino

-->
## Steps to reproduce
1. Install VM with Collabora To install. The assistant does everything alone...
2. Open Nextcloud Website nextcloud.[NAME].local an go to -> Settings -> Administration -> Collabora Online Development version
3. Check if the server is online. If so, click save.

## Expected behaviour
Connect Collabora to the server.

## Actual behaviour
no connection possible

## Server configuration

**Nextcloud server version:**
19.0.0

**Server OS** (Ubuntu server is default)

**How did you install the VM?** 
Scripted install from hanssonit.se Hyper-V  image.)

## Network
**Do you use DHCP?**
No

**Is port 80 and/or 443 open?**
Yes. Also 9980

**Comment by enoch85** [comment]
Hi, 

Thanks for posting your issue.

It's known and I haven't had time to investigate it further, but I do know that there are issues in later versions of their Docker. This started to happen after Collabora 3.6 was released and I'm still waiting for a fix from Collabora.

The quick fix is to run OnlyOffice instead.

**Comment by Tino-ko** [comment]
OK. 
My problem is that the internal domain has to be changed to an public one.
Is there a way to solve that?

**Comment by enoch85** [comment]
Sure, just run the Collabora script again.

1. `sudo bash /var/scripts/update.sh`
2. `sudo bash /var/scripts/menu.sh`
3. Choose Apps, then Collabora.
