### ISSUE TITLE
Scripts that should move to "addons"

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1290]
- automatic_updates.sh
- cookielifetime.sh
- locales.sh
- locate_mirror.sh
- prune_zfs_snaphots.sh
- zfs-prune-snapshots.sh
- redis-server-ubuntu.sh
- security.sh

@szaimen Makes sense?

**Comment by szaimen** [comment]
> @szaimen Makes sense?

I would say yes, but I currently cannot remember the folders that should be added.

**Comment by enoch85** [comment]
> I would like to add:
> 
> - Menus
> - Configuration
> - Network
> - Addons
> 
> Anything more?

No, I think those should fit all. At least in combination with static, old and apps.

**Comment by szaimen** [comment]
What would you put into the configuration folder if those get into the addons folder?

**Comment by enoch85** [comment]
> What would you put into the configuration folder if those get into the addons folder?

Not sure, let's figure it out when I have some more time. Or maybe you have a good structure in your back pocket laying around? :)

**Comment by szaimen** [comment]
No, currently not...
