### ISSUE TITLE
Documentation taking over 6 minutes to load

### ISSUE THREAD

**Issue by payne8** [nextcloud/vm#1294]
## Steps to reproduce
1. Click the link in the readyme to view the documentation
https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm
https://docs.hanssonit.se/s/bj0vl1ihv0jgrmfm08j0/build-your-own/d/bj0vl4ahv0jgrmfm0950/nextcloud-vm

## Expected behaviour
Tell us what should happen
Documentation should load.

## Actual behaviour
Tell us what happens instead
A blank page. 
CSS, Vendor javascript and documize scripts take 1-4.3 minutes to load.
Page finishes loading after 6.9 minutes.

## Server configuration

**Nextcloud server version:** NA

**Server OS** NA

**How did you install the VM?** NA

## Network
**Do you use DHCP?** NA

**Is port 80 and/or 443 open?** NA

## Logs / Screenshots
![image](https://user-images.githubusercontent.com/5124686/84720667-e352b100-af3b-11ea-9b65-f12868f0280a.png)

#### Log file (/var/log/nextcloud/nextcloud.log)
NA

#### Installation log (command output)
NA

#### Screenshoots
https://imgur.com/a/K24fiTK

**Comment by enoch85** [comment]
Ouch, that's bad. Thanks for informing!

Documize is on a decent server with good bandwidth, but from time to time the server is hammered with load. So It might just be temporary. 

I just tested, and it takes roughly 1-2 seconds on LTE from my mobile.

Nothing to do here, so I'm closing.
