### ISSUE TITLE
Slow WebDav, database index issues?

### ISSUE THREAD

**Issue by tmsd2001** [nextcloud/vm#1295]
Nextcloud 18.0.6

I heard about a patch that should make the WebDav work much faster.
It is about an index creation in the database.
Is there also a possibility to apply this in version 18.0.6 with Postgresql or do we have to wait for version 19.

**Comment by enoch85** [comment]
Verdion 19 is already out. 

Please check releases in this repo.

**Comment by tmsd2001** [comment]
ok, thanks, is it known whether the patch is already there?

**Comment by tmsd2001** [comment]
looks like the index has not yet been added. WebDAV is just as slow as before.
Refer:
[https://github.com/nextcloud/server/pull/20716](url)

**Comment by tmsd2001** [comment]
ok, I checked the database and found the index. The WebDAV connection is nevertheless very slow. I use davfs on armbian Ubuntu 20.04 LTS.
I enter the source IP to the brute-force whitelist too.
But there is about a 1 minute break between each operation.

**Comment by enoch85** [comment]
Sorry, this had nothing to do with how the VM is setup. Please ask in the forum @ https://help.nextcloud.com. 

Running armbian might be the cause, since you're probably using a slow CPU?
