### ISSUE TITLE
Disable additional apps that aren't yet supported on newer Nextcloud releases

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/vm#1296]
## Steps to reproduce
1. Try to install apps that are unsupported by Nextcloud through the `menu.sh` script like for example Fulltextsearch.

## Expected behaviour
Either don't show this app as an option to install until it is supported on Nextcloud 19 by @daita or allow users to enable the app (if it works on Nextcloud 19 anyway like Fulltextsearch).

## Actual behaviour
The app can be selected and installs until it tells the user that it is not supported.

## Server configuration

**Nextcloud server version:** (see your admin page) 19

**Server OS** (Ubuntu server is default) Ubuntu 20.04

**How did you install the VM?** Script

## Network
**Do you use DHCP?** No

**Is port 80 and/or 443 open?** Yes

**Comment by enoch85** [comment]
cc @szaimen Any ideas?

I haven't checked but the `install_enable_app()` should take care of that right?

**Comment by szaimen** [comment]
I think what he is suggesting is that e.g. the fulltextsearch.sh option shouldn't get shown inside the apps.sh menu if the needed Nextcloud apps like fulltextsearch aren't compatible with the new Nextcloud Version yet.

Don't know if that is possible or makes sense at all...

**Comment by e-alfred** [comment]
> e.g. the fulltextsearch.sh option shouldn't get shown inside the apps.sh menu if the needed Nextcloud apps like fulltextsearch aren't compatible with the new Nextcloud Version yet.

Yes, at least the check should be done before starting the installation at all. Currently, it installs everything and then tells the user at the end that the app isn't compatible and sending an error message to all Nextcloud admins on the VM. This takes time and resources ending in getting no additional feature for the user.

**Comment by enoch85** [comment]
> Don't know if that is possible or makes sense at all...

Agreed. We already have functions in place to [check that(https://github.com/nextcloud/vm/blob/master/lib.sh#L764-L793).

Closing.
