### ISSUE TITLE
Add option to Bitwarden script to disable registration to prevent unauthorized creation of accounts

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/vm#1297]
## Steps to reproduce
1. Install Bitwarden through the "additional apps" option
2. Register users

## Expected behaviour
After all necessary users are registered, the script for Bitwarden should allow to disable user creation through the web interface to prevent creation of unauthorized accounts.

## Actual behaviour
Bitwarden by default allows everyone to create an account, especially if it is open on the internet this is an issue.

## Server configuration

**Nextcloud server version:** (see your admin page) 19

**Server OS** (Ubuntu server is default) Ubuntu 20.04

**How did you install the VM?** Script on custom VM

## Network
**Do you use DHCP?** No

**Is port 80 and/or 443 open?** Yes

**Comment by enoch85** [comment]
Thanks for your suggestion. Maybe it's better to bring this up with Bitwarden directly which made the original install script (which the VM runs).

You can find their repo here: https://github.com/bitwarden/server

Leaving this open in case we fix a workaround for it anyway.

**Comment by e-alfred** [comment]
Well, this is a bit of a security risk/nuisance if Bitwarden is accessible over the public internet because everyone could register a user maybe even resulting in a DOS attack of some kind.

A more secure workflow would be this:

1. Admin installs Bitwarden using the script.
2. Admin sets up all users using the Bitwarden web interface.
3. Admin disables registration after setting up all users through the script (should be added to the "Server Configuration" section).
4. Admin can enable/disable registration if a new user should be added to Bitwarden.

**Comment by e-alfred** [comment]
Well, this is a bit of a security risk/nuisance if Bitwarden is accessible over the public internet because everyone could register a user maybe even resulting in a DOS attack of some kind.

A more secure workflow would be this:

1. Admin installs Bitwarden using the script.
2. Admin sets up all users using the Bitwarden web interface.
3. Admin disables registration after setting up all users through the script (should be added to the "Server Configuration" section).
4. Admin can enable/disable registration if a new user should be added to Bitwarden.

The right options should be these: https://github.com/bitwarden/server/issues/631

**Comment by enoch85** [comment]
@e-alfred You're welcome to contribute! :+1:

**Comment by enoch85** [comment]
@e-alfred Please test the PR, it's now ready for review.

Thanks!
