### ISSUE TITLE
Nextcloud VM will not load in Firefox.  Opera OK...  Timeout issue?

### ISSUE THREAD

**Issue by Dayagiym** [nextcloud/vm#1301]
## Steps to reproduce
1. Place URL in URL bar (Firefox).  Wait...
2.Wait longer.  Nothing...
3. Place URL in URL bar (Opera).  Bing!

## Expected behaviour
page should load fine

## Actual behaviour
page does not load (Firefox), also Sync Client "No Connection...  Timeout"

## Server configuration

**Nextcloud server version:** (see your admin page)
NcVM 19 fresh install this week
**Server OS** (Ubuntu server is default)
Ubuntu 20.04
**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted from here on Bare-Metal
## Network
**Do you use DHCP?**
reserved ip from router...  no problem here

**Is port 80 and/or 443 open?**

## Logs / Screenshots

![PageSpeed_Insights](https://user-images.githubusercontent.com/67354725/85496539-b59fe480-b599-11ea-9953-4857d1d85e0b.png)

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi, thanks for your issue.

Have you tried in incognito mode?

**Comment by Dayagiym** [comment]
Hello Daniel,
Thanks for the quick response. It is now working fine. I have no idea what the issue was, it's possible that my modem/router is acting up. It was happening in conjuction with my new upgrade to Ubuntu 20.04 and your NcVM script, so I thought it might be related.
I've been using your VMs for a few years now, but just switched over two or so months ago to using your script on bare-metal servers. The main reason is that I have no other use for these servers and one of them does not support modern virualization. It is kind of overkill, but they are holding a lot of data now with a bunch of mirrored zfs drives.

Thanks for your help!

--
Dayag Anashiym
Parchment Press
Community in Boulder, CO
p:303.385.3179
e:dayag@parchment.press (mailto:dayag@parchment.press)

June 24, 2020 3:21 PM, "Daniel Hansson" <notifications@github.com (mailto:notifications@github.com?to=%22Daniel%20Hansson%22%20<notifications@github.com>)> wrote:
	Hi, thanks for your issue.

	Have you tried in incognito mode?

**Comment by enoch85** [comment]
Glad you solved it!
