### ISSUE TITLE
Getting scripts from Github

### ISSUE THREAD

**Issue by TobiasKoenn** [nextcloud/vm#1305]
Getting scripts from Github

#### Screenshoots
https://imgur.com/a/sr0OR8p

**Comment by enoch85** [comment]
Hi, you're running an old VM, please read this: https://www.techandme.se/ubuntu-20-04-and-our-vms/

**Comment by TobiasKoenn** [comment]
Thanks a lot.
Where can i get a new VW

**Comment by enoch85** [comment]
You can find it here: https://github.com/nextcloud/vm/releases
