### ISSUE TITLE
nextcloud_install_production.sh error

### ISSUE THREAD

**Issue by Achim222** [nextcloud/vm#1307]
Hi,
i have a clean debian 10.0 standard and  the error:

root@test:~# bash nextcloud_install_production.sh
nextcloud_install_production.sh: line 6: syntax error near unexpected token `newline'
nextcloud_install_production.sh: line 6: `<!DOCTYPE html>'
root@test:~# 

thanks!

**Comment by enoch85** [comment]
Hi,

Please try Ubuntu Server 20.04. Does that work?

**Comment by enoch85** [comment]
Debian isn't supported, closing.
