### ISSUE TITLE
nextcloud_install_production.sh: line 6: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by Achim222** [nextcloud/vm#1309]
hi,
i have Ubuntu Server install and this Error:

sudo bash nextcloud_install_production.sh
nextcloud_install_production.sh: line 6: syntax error near unexpected token `newline'
nextcloud_install_production.sh: line 6: `<!DOCTYPE html>'

cat /etc/issue
Ubuntu 20.04 LTS \n \l

cat /proc/version
Linux version 5.4.0-40-generic (buildd@lcy01-amd64-011) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020

thanks

**Comment by enoch85** [comment]
Strange, line 6 is [this line](https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L6) and have never been an issue before. 

Works for me as well.

Were do you run this Ubuntu Server? Is it your own, or a VPS?

**Comment by Achim222** [comment]
mhhhh.... i have Proxmox and Ubuntu run under VM.

**Comment by enoch85** [comment]
Just relased all new versions (8 different VMs) and this was not present in any of those.

Please check your configuration again.

Thanks!
