### ISSUE TITLE
Talk high performance server

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1310]
I stumbled accross @morph027 repo: https://gitlab.com/packaging/nextcloud-spreed-signaling/-/tree/master

Super cool stuff!

Maybe you would like to help get it in the VM @morph027? Would be nice if we could have it as an option under apps, in other words, a new apps script. :)

**Comment by morph027** [comment]
Sure, why not. I'm not up to date with latest VM development, is Coturn present already?

I've created packages of [nats](https://gitlab.com/packaging/nats-server/) too.

So all components are available, we just need to knit them together (like [here](https://morph027.gitlab.io/blog/nextcloud-spreed-signaling/) or [here](https://decatec.de/home-server/nextcloud-talk-mit-eigenem-signaling-server-high-performance-backend/) -  i can take care of the german words ;) )

I'll try to have a look at the current installation files to get a picture of the latest version of VM. If you like, you can already start scripting and just wire up all the repos for HPB, Nats, Janus (and CoTURN probably).

**Comment by enoch85** [comment]
Aah great!

Actually, we have Talk already, but the free version. So Coturn? [Yes](https://github.com/nextcloud/vm/blob/master/apps/talk.sh). 

Question is, should we offer two different versions of Talk, one which is free, and one which is this high, performance stuff?

I the latter, I can at least make a script with the baseline and we can build on that. 

Btw, do can you write to this repo? Otherwise it's better that you fork it and we work in your repo.

Thanks!

**Comment by enoch85** [comment]
Just had a look at the Docker, do you think that would be the easiest way forward?

**Comment by enoch85** [comment]
Your Caddy solution seems great though.

**Comment by morph027** [comment]
I have a fork which just needs to be updated.

I would leave the talk plugin as it is, as the HBP can be enabled additionally in the admin UI (need to find a way to do this via occ command or so).

Is Docker installed already? I'm a huge Docker/Container fan, but you always need to walk the extra mile to setup something in production properly.

Caddy (or whatever reverse proxy solution like nginx, traefik) also enables us to run the HBP and NC on the same server (i've read @jospoortvliet  concerns on twitter about it, but this actually works on the same machine).

I'll try to write some todo's for this task and then we can tackle 'em.

**Comment by enoch85** [comment]
> Is Docker installed already?

Just call a function to make it happen: `install_docker`. So it's quite easy. :)

**Comment by enoch85** [comment]
@morph027 Any update here?

> I'll try to write some todo's for this task and then we can tackle 'em.

Could you please fork this repo so that we can work in your repo for this?

Thanks!

**Comment by morph027** [comment]
Sorry, was busy @ work ...

Before starting actual implementation, i'd like to clarify how we want to do this. Docker? Packages? Which reverse proxy?
I'll try to take a look today.

**Comment by enoch85** [comment]
> Docker? Packages? Which reverse proxy?

What do you think is most stable?

**Comment by morph027** [comment]
I prefer packages, as Docker adds another layer of complexity which is not necessary when not running in some sort of cluster.

Which webserver is currently service the VM? Apache with mod-php?

**Comment by enoch85** [comment]
OK great!

> Apache with mod-php?

Apache with PHP-FPM

**Comment by morph027** [comment]
Ok. Then we "just" need to add a vhost for HPB (like nextcloud-vm.example.com**/hpb**) to apache which just proxies to the signal gateway endpoint according to the [docs](https://github.com/strukturag/nextcloud-spreed-signaling#apache).

**Comment by enoch85** [comment]
OK, that seems easy enough. What about putting the signaling traffic on another web server, like Nginx?

I'm still waiting for you to fork so that we can start building. :D

**Comment by morph027** [comment]
Fork is alive :) https://github.com/morph027/vm

> What about putting the signaling traffic on another web server, like Nginx?

This then does require a second ip address for the server, as it can't listen on the same interface like apache.

We can either use a virtual host with SNI like something.example.com -> nextcloud and whatever-the-user-types.example.com for the signaling server in apache, but then we need to add the second domain to LE certbot too. Not sure if the current scripts can handle this.

Running in a path is using the existing LE cert, so the change is quite easy.

**Comment by enoch85** [comment]
> Not sure if the current scripts can handle this.

Actually, we made the whole certbot stuff a function, so yesi t's possible. Basically:

```
# Install certbot (Let's Encrypt)
install_certbot

# Generate certs and  auto-configure  if successful
if generate_cert  "$SUBDOMAIN"
then
    # Generate DHparams chifer
    if [ ! -f "$DHPARAMS_SUB" ]
    then
        openssl dhparam -dsaparam -out "$DHPARAMS_SUB" 4096
    fi
    printf "%b" "${IGreen}Certs are generated!\n${Color_Off}"
    a2ensite "$SUBDOMAIN.conf"
    restart_webserver
    # Install Collabora App
    install_and_enable_app richdocuments
else
    last_fail_tls "$SCRIPTS"/apps/collabora.sh
fi
```

**Comment by morph027** [comment]
see https://github.com/nextcloud/vm/pull/1317

**Comment by enoch85** [comment]
Thanks! Finally we have something to work with.

Due to lack of time here as well (same as for you I suppose?), it might not happen tomorrow (probably not), but it feels good that we at least started something. Thanks!!

**Comment by enoch85** [comment]
This is now fixed!
