### ISSUE TITLE
VM install failing on OVA and Hyper V / GitHub Script error

### ISSUE THREAD

**Issue by stillzy** [nextcloud/vm#1312]
I have attempted to do an OVA install on ESXI 6.7 and got a failure during the script (see imgur).  So I thought possibly an issue w/ the free OVA and purchasaed the Hyper-V VHDxs and got the same issue (see imgur)

https://imgur.com/a/ZAWEExd

I am unsure on what log file you are looking for if you tell me where in var/log i can export it.

**Comment by enoch85** [comment]
Hi,

Thanks for posting your issue.

It's now fixed! Please confirm.
