### ISSUE TITLE
activatge-ssl failed to download please run sudo curl -sL0 https://raw.githubusercontrent.com/nextcloud/vm/master

### ISSUE THREAD

**Issue by mickeyace** [nextcloud/vm#1316]
## Steps to reproduce
1.Downloaded a new version of the installer from your site yesterday. 
2.Setup -VM in Hyper-V per your instructions, Network says 200 status online. Everything seems fine until it trys to get the scripts from github. 
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)
Server 2019 main os, running Nextcloud in VM - Hyper-V
**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
Static IP- Confirmed working
**Is port 80 and/or 443 open?**
YES
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi,

Please download the latest VM. Also read here: https://www.techandme.se/ubuntu-20-04-and-our-vms/

Thanks!

**Comment by mickeyace** [comment]
Thank you for the quick response. That worked perfect. I really appreciate you awesome work.


Robert Mancuso
803-403-9067 call/text
RMancuso@ExpressComputer.biz
www.ExpressComputer.Biz
[cid:image003.png@01D655D2.761948F0]
[Google Review]<https://search.google.com/local/writereview?placeid=ChIJ_____w-j-IgRMQOWdrk200I>
