### ISSUE TITLE
404 Error for the install "script"

### ISSUE THREAD

**Issue by child-duckling** [nextcloud/vm#1319]
## Steps to reproduce
1. Install Ubuntu 20.04 Server in a fresh VM
2. SSH into it from host computer
3.Run wget https://github.com/nextcloud/vm/blob/official/prep_vm.sh

## Expected behaviour
Tell us what should happen
Installation starts

## Actual behaviour
Tell us what happens instead
Connects to Github then 404 Not Found

## Server configuration
Clean Ubutu 20.04 Server VM with 2GB of RAM and 2 Processers
**Nextcloud server version:** (see your admin page)
N/A
**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Followed Intructions from README
## Network
**Do you use DHCP?**
N/A
**Is port 80 and/or 443 open?**
N/A
#### Log file (/var/log/nextcloud/nextcloud.log)
```
N/A
```

#### Installation log (command output)
```
ncadmin@nc:~$ wget https://github.com/nextcloud/vm/blob/official/prep_vm.sh
--2020-07-14 23:15:18--  https://github.com/nextcloud/vm/blob/official/prep_vm.sh
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-14 23:15:19 ERROR 404: Not Found.
```

**Comment by child-duckling** [comment]
Wrong Branch :/

**Comment by child-duckling** [comment]
Nevermind, apparently I don't how gihub works. :facepalm:

**Comment by szaimen** [comment]
I guess the correct command should be:
`wget https://raw.githubusercontent.com/nextcloud/vm/official/prep/prep_vm.sh`

**Comment by enoch85** [comment]
@szaimen Correct.

**Comment by szaimen** [comment]
Maybe it would make sense to change that command here?
https://github.com/nextcloud/vm/tree/official#setup
