### ISSUE TITLE
10.0.2

### ISSUE THREAD

**Issue by tal2301** [nextcloud/vm#132]
Hi I download the Vm version 10.0.2 but when it is done installing I see that version 11 has been installed.
How can I make sure i am downloading version 10.0.2 because thats the version i need
Thanks

**Comment by enoch85** [comment]
The VM automatically updates during the first boot.

To disable this you have to hash out this line in the startup script:https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L693
