### ISSUE TITLE
Revert OnlyOffice to Previous Method

### ISSUE THREAD

**Issue by 104e85bd** [nextcloud/vm#1322]
There's a well known issue with the built in OnlyOffice server where by changes are not saved to the actual file and appear to only work within OnlyOffice.

https://github.com/nextcloud/documentserver_community/issues/12

Until this is fixed, wouldn't it be better to continue to use the old method with the Docker installation? That is shown to still work and not produce this issue. I lost a lot of work due to this stupid bug.

**Comment by rkkoszewski** [comment]
Is this really something that got added (and can be reverted) or is this a regression (which requires fixing)?

**Comment by 104e85bd** [comment]
> Is this really something that got added (and can be reverted) or is this a regression (which requires fixing)?

I'm not a developer, so I may not be able to provide the correct answer. 

However, previously this project used Docker to install the backend document server for OnlyOffice. Since the built in integration was announced with Nextcloud Hub, the developers stopped using the previous method in favor of the new one.

**Comment by enoch85** [comment]
Hey guys,

There's already an issue about this: https://github.com/nextcloud/vm/issues/1275

Please continue the discussion there instead.
