### ISSUE TITLE
Can't install FullTextSearch on with latest NC (19.01)

### ISSUE THREAD

**Issue by kellybyrd** [nextcloud/vm#1324]
## Steps to reproduce
1. Run main_menu, select additional apps, then FullTextSearch
2. Notice the failure:  ```Error: App "Full text search" cannot be installed because it is not compatible with this version of the server.```

## Expected behaviour
FullTextSearch should install. If FullTextSearch is known to be incompatible with my currently installed NC, `fulltextsearch.sh` should check for that before pulling docker images and trying to install it only to fail. Maybe a check similar to `lowest_compatible_nc`?

## Actual behaviour
Docker images are pulled, containers started, many many log lines go by, only to be given the error message in the `Steps to Reproduce` above

## Server configuration

**Nextcloud server version:**  Installed with NC 19.0, used upgrade scripts to upgrade 19.01. Same failure on both.

**Server OS** Default Ubuntu in OVA

**How did you install the VM?** Downloaded OVA

## Network
**Do you use DHCP?** Yes

**Is port 80 and/or 443 open?** Yes

## Logs / Screenshots
https://0bin.net/paste/2bIQalxLNZQ1LFaG#L77nH6IWFVp+Vz-A2W9ri6h8/g73v5Aw4mk7yJ2gGyC

**Comment by enoch85** [comment]
Hi,

Thanks for your issue. 

This is an issue with the app itself, please check here: https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/107

**Comment by enoch85** [comment]
Please try again and report back. I think the issue is fixed now.

**Comment by kellybyrd** [comment]
Yup,  know the problem is between FTS and NC 19, but figured it would be a nice for your scripts to not try to install a known broken app. Looking at your recent commit history, it looks like the patch didn't quite work? In any case, 
I just confirmed that I see the "Full Text Search needs to be updated by the developer..." dialog. Thanks for fixing that!

**Comment by kellybyrd** [comment]
I don't have time to test now, but it looks like https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/114 may have fixed the FTS issue. When I have a bit, I'll try removing the NC version check in a local copy of the downloaded fts install script and send a PR your way if it works.

**Comment by enoch85** [comment]
Thanks @kellybyrd 

I do believe there are more to it than just that app though.
