### ISSUE TITLE
503 Service Unavailable on latest update

### ISSUE THREAD

**Issue by deljones** [nextcloud/vm#1327]
Hello, 

This is what happened...

I was running v18.0.6. Yesterday or the day before there was an auto-update to v18.0.7 which clearly went wrong because I now get

>503 Service Unavailable - The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later

So I run the update.sh script which then bumped me up to v19.0.1, however on restart I still get the same problem

I then ran:

>sudo -u www-data php /var/www/nextcloud/occ maintenance:mode --off

Which gave:

>Maintenance mode already disabled

Now I am stuck. Can anyone help, please?

Dj

**Comment by enoch85** [comment]
Please run `sudo bash /var/scripts/menu.sh` and choose Server Configurations --> Activate TLS.

I think the problem is missing PHP-FPM in your Apache config, and rerunning the TLS setup will fix it.

**Comment by deljones** [comment]
@enoch85 many many thanks... That worked. I'm very greatful to you.

Dj

**Comment by deljones** [comment]
@enoch, before this issue is closed, can you confirm if I can ignore the attached. I've read the articles about the change in Ubuntu and PHP in the new VM but the attached confused me a little.?

Regards

Dj

![PHPsetup](https://user-images.githubusercontent.com/2440463/87888181-17c9f900-ca23-11ea-8f44-bf2febcd77e8.jpg)

**Comment by enoch85** [comment]
Great that it worked!

Yes, at some point Nextcloud won't allow older PHP, in this case PHP 7.2. To be able to upgrade to Nectcloud 20, you need either [this](https://shop.hanssonit.se/product/migrate-nextcloud-to-new-os-and-server-18-04/) or [this](https://shop.hanssonit.se/product/upgrade-php-version-including-dependencies/).

You can read more regarding the VMs [here](https://www.techandme.se/ubuntu-20-04-and-our-vms/).

Easiest though would be to download the latest VM and move the data if you don't care about shared links, users or other DB related stuff.

**Comment by deljones** [comment]
Thanks again.. 

Dj
