### ISSUE TITLE
Install scripts should ask me where I want my data directory and make sensible suggestions.

### ISSUE THREAD

**Issue by dunkelziffer** [nextcloud/vm#1330]
## Steps to reproduce
1. Install Nextcloud via nextcloud_install_production.sh and nextcloud-startup-script.sh on a fresh Ubuntu VPS

## Expected behaviour
The script asks me, where I want my data folder. Further, it suggests a sensible default that is outside of /var/www to comply with the recommendations from https://docs.nextcloud.com/server/19/admin_manual/installation/harden_server.html#place-data-directory-outside-of-the-web-root

## Actual behaviour
It does not ask me.

## Further information
irrelevant

**Comment by enoch85** [comment]
Hi @dunkelziffer 

The data path is very nested in to all the scripts and making it configurable would mean a lot of extra functions and if statements. Also, as the datapath is ZFS there are things to consider for that as well.

Right now the datapath is `/mnt/ncdata`, you are free to change it, but you have to remount ZFS and change all the other places where the datapath is set.

Sorry, I will not work on this. We have a default, and it will stay that way. If you want to move it, it's up to you. I don't see why that would be necessary though?

**Comment by dunkelziffer** [comment]
I used your script to install Nextcloud on a VPS. I cannot configure multiple drives there, therefore I used the single drive option. For that option, the data folder is within /var/www which is not recommended: https://docs.nextcloud.com/server/19/admin_manual/installation/harden_server.html#place-data-directory-outside-of-the-web-root

For this use case it looks like it would be sufficient to let us set the script variable $NCDATA ourselves.

**Comment by enoch85** [comment]
On a VPS you should be able to mount a second drive, right?

One disk setup still uses `/mnt/ncdata`: https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L177 as that's hardcoded in the scripts. You won't benefit from ZFS though.

Data path during installation:
https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L380
https://github.com/nextcloud/vm/blob/master/lib.sh#L12-L13

**Comment by dunkelziffer** [comment]
I guess that's my error then. To me it looked like the Nextcloud default directory was in use, but it seems i didn't look hard enough. Consider this case closed, then.

Additionally, I will contact my VPS provider and see whether it is possible to mount a second drive. In your opinion, would partitioning the drive and mounting the second partition with a zfs file system be sufficient, or is an actual physical seond drive needed?

Just to clarify: I assumed that this was not possible for my VPS as the script failed with the first option selected.

**Comment by enoch85** [comment]
Regarding the second disk, just add it, don't do anything with it. The script will mount and format it correctly.

Feel free to donate. :)

**Comment by dunkelziffer** [comment]
So a second physical disk is needed and a partition won't do?

**Comment by enoch85** [comment]
> So a second physical disk is needed and a partition won't do?

A separate disk, yes. Not a partition.
