### ISSUE TITLE
Query of WAN-IP fails.

### ISSUE THREAD

**Issue by GoaMetz** [nextcloud/vm#1335]
Heho,

it looks like calling https://ipv4bot.whatismyipaddress.com runs into a timeout most of the time.
Ramping up the maxtime does'nt fix it.
Using http instead of https does.

**Comment by szaimen** [comment]
It works for me within a few ms.
Maybe a dns or isp problem on your side?

**Comment by enoch85** [comment]
Works for me as well. 

Please try another network, and report back.

Thanks!

**Comment by enoch85** [comment]
Tested again, nothing wrong...
