### ISSUE TITLE
Open the wiki?

### ISSUE THREAD

**Issue by oparoz** [nextcloud/vm#134]
Some people may have some questions which may quickly fill the readme, so maybe it's best to open the wiki?

How is the VM partitioned?
How do I create more space?
Which apps are installed?
Is let's encrypt enabled?
How do I change the port on which NC runs?
How can I add another host? What domain/IP can I use? Do I need to modify the network config?

**Comment by enoch85** [comment]
@oparoz Anyone is free to contribute. 

Right now we have all the information on Tech and Me: https://www.techandme.se/category/nextcloud/

**Comment by oparoz** [comment]
> @oparoz Anyone is free to contribute.

Yes, but the wiki is closed which means community members can't contribute.

**Comment by enoch85** [comment]
Good point.

**Comment by enoch85** [comment]
And it's open! https://github.com/nextcloud/vm/wiki

**Comment by oparoz** [comment]
Thanks :)
