### ISSUE TITLE
webmin and bitwarden not accessible

### ISSUE THREAD

**Issue by mamama1** [nextcloud/vm#1347]
Hi

I have just deployed the Home/SME appliance with 40GB (downloaded today) for VMware (ESXi 6.7) and I chose to install fail2ban, netdata, bitwarden, onlyoffice, fulltextsearch, previewgenerator, ldap and talk.

I'm a sysadmin who is installing this for a private deployment at home, no commercial stuff, only for the family but I want it to be secure, obviously.

now to the errors:
talk said during the install that it could not find nextcloud and told me to first install nextcloud and then run talk setup again. meh don't care too much about that.

bitwarden installed fine, i used a subdomain of the nextcloud domain (like pw.nextcloud.mydomain.com). DNS, port forwardings, etc are in place, let's encrypt deployment worked like a charm.
unfortunately, bitwarden is not reachable via the browser, neither via http (8080) nor https (8443).

for me it doesn't look like the bitwarden docker container is listening on IPv4:

```
tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN      2999/netdata
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN      2999/netdata
tcp        0      0 127.0.0.1:9200          0.0.0.0:*               LISTEN      2234/docker-proxy
tcp        0      0 127.0.0.1:9300          0.0.0.0:*               LISTEN      2130/docker-proxy
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1057/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1171/sshd: /usr/sbi
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1386/postgres
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2987/master
tcp        0    464 192.168.38.2:22         192.168.25.156:25369    ESTABLISHED 7285/sshd: ncadmin
tcp6       0      0 :::8443                 :::*                    LISTEN      2252/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      1226/apache2
tcp6       0      0 :::19999                :::*                    LISTEN      2999/netdata
tcp6       0      0 :::8080                 :::*                    LISTEN      2369/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      1226/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      1171/sshd: /usr/sbi
tcp6       0      0 ::1:25                  :::*                    LISTEN      2987/master
udp        0      0 127.0.0.1:40727         127.0.0.1:40727         ESTABLISHED 1386/postgres
udp        0      0 127.0.0.1:8125          0.0.0.0:*                           2999/netdata
udp        0      0 127.0.0.53:53           0.0.0.0:*                           1057/systemd-resolv
raw6       0      0 :::58                   :::*                    7           11807/systemd-netwo

```

also, i can't see a webmin port (10000).

nextcloud itself seems to work just fine.

any ideas?
thanks!

**Comment by enoch85** [comment]
Hi,

Thanks for posting!

Are the ports open in your firewall? Dumb question maybe, but just have to make sure.

I will install everything on a fresh VPS in a few days. I'll let you know the outcome.

**Comment by mamama1** [comment]
Hi,

yes they are opened. Or do you mean in the appliances firewall? That I haven't checked...

From the outside, the webmin port isn't opened, of course, but from my LAN network to the DMZ where the appliance is, it is allowed.

**Comment by enoch85** [comment]
Well, everything is working from here. Please see attached video: https://cloud.hanssonit.se/s/yz6Cskrigi7bz8Z

Please check your FW settings or buy support [here](https://shop.hanssonit.se/)

Thanks!

**Comment by mamama1** [comment]
Hi,

I totally goofed it, it was kind of late (like today again, lol).
Bitwarden was open from the internet but not from my LAN (lol again).

However, webmin still doesn't work, also there was no option to install it and also according to netstat nothing is listening on port 10000. I watched your video, thanks for making the effort of trying to reproduce this but I think you didn't try to access webmin, unless I have accidentally missed that part?
Not that I need it, I just would like to be sure that everything is in good shape.

Thanks!

**Comment by enoch85** [comment]
> unless I have accidentally missed that part?

Yup, I missed to access it. :( I just tried again on a local install I have and it's working great! Can't help you there. Sorry!

**Comment by mamama1** [comment]
strange. does netstat show it on your installation listening on port 10000?
and: is it optional during installation, i.e. should i be able to select/deselect it during installation or is it installed always by default? when running the menu.sh, I can't choose to install or uninstall it but I can't quite remember whether it was there during initial installation.

sorry for bothering you with this, these are the very last questions regarding this topic.

**Comment by enoch85** [comment]
> strange. does netstat show it on your installation listening on port 10000?

```
root@nextcloud500gb:~# netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      1893/perl           
tcp        0      0 127.0.0.1:9200          0.0.0.0:*               LISTEN      1843/docker-proxy   
tcp        0      0 127.0.0.1:9300          0.0.0.0:*               LISTEN      1817/docker-proxy   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1185/systemd-resolv 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1309/sshd: /usr/sbi 
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1482/postgres       
tcp6       0      0 :::443                  :::*                    LISTEN      1326/apache2        
tcp6       0      0 :::80                   :::*                    LISTEN      1326/apache2        
tcp6       0      0 :::22                   :::*                    LISTEN      1309/sshd: /usr/sbi 
```

> and: is it optional during installation, i.e. should i be able to select/deselect it during installation or is it installed always by default? 
>
> when running the menu.sh, I can't choose to install or uninstall it but I can't quite remember whether it was there during initial installation.

It's not included in menu.sh as it's installed by default in the installation script before every release - just to be sure it's there, and working, in every release out there.

**Comment by enoch85** [comment]
JFTR: Use an address like this: https://192.168.2.125:10000

**Comment by mamama1** [comment]
ok thanks for the clarification. no idea why it doesn't start on my installation, ip doesn't matter imo, as it doesn't even listen:

```
root@files:/var/log# netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9200          0.0.0.0:*               LISTEN      2163/docker-proxy
tcp        0      0 127.0.0.1:9300          0.0.0.0:*               LISTEN      2093/docker-proxy
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1033/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1147/sshd: /usr/sbi
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1357/postgres
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2956/master
tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN      3025/netdata
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN      3025/netdata
tcp6       0      0 :::8080                 :::*                    LISTEN      2285/docker-proxy
tcp6       0      0 :::80                   :::*                    LISTEN      1184/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      1147/sshd: /usr/sbi
tcp6       0      0 ::1:25                  :::*                    LISTEN      2956/master
tcp6       0      0 :::8443                 :::*                    LISTEN      2219/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      1184/apache2
tcp6       0      0 :::19999                :::*                    LISTEN      3025/netdata

```

will have to dig into the logs and probably retry the installation with a fresh VM to see how it is there...

**Comment by mamama1** [comment]
it seems like webmin was simply not installed. i downloaded the script https://github.com/nextcloud/vm/blob/master/apps/webmin.sh and executed it and webmin installed just fine and is now accessible. i will definitely deploy another ova and see whether that will do the same...

**Comment by enoch85** [comment]
> ip doesn't matter imo

Correct, but HTTPS and :10000 does. :)

> it seems like webmin was simply not installed 

Aah, ok, so you use the scripted version? The only time it was not installed in the VM was in the first releases of the Ubuntu 20.04 VM due to that it was not installable.

**Comment by mamama1** [comment]
nah i deployed the 40GB VMware Appliance, no idea why webmin wasn't installed..

**Comment by mamama1** [comment]
![install-02](https://user-images.githubusercontent.com/21132277/89829427-d8db1f00-db5a-11ea-8804-74f053d20fa7.PNG)
ha - i guess it wasn't installed because i didn't choose to do so during the installation.

i thought it wasn't deselectable...?

**Comment by szaimen** [comment]
> ![install-02](https://user-images.githubusercontent.com/21132277/89829566-1cce2400-db5b-11ea-92ff-727820a416c4.PNG)
> 
> ha - i guess it wasn't installed because i didn't choose to do so during the installation.
> 
> i thought it wasn't deselectable...?

That is the magic of those sccripts :D

**Comment by enoch85** [comment]
Actually, we recently changed the scripts. So what you're seeing is a new feature in an old image.

Magic, yes it is. :D
