### ISSUE TITLE
Scripts and functions to remove for NC 20.0.0

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1354]
- `menu/configuration.sh` (isn't needed anywhere)
- `static/automatic_updates.sh` (moved to addons)
- `static/locales.sh` (moved to addons)
- `static/locate_mirror.sh` (moved to addons)
- `static/redis-server-ubuntu.sh` (moved to addons)
- `static/security.sh` (moved to addons)
- `addons/smartctl.sh` (moved to data)
- `static/change-to-zfs-mount-generator.sh` (moved to data)
- `static/format-chosen.sh` (moved to data)
- `static/format-sda-nuc-server.sh` (moved to data)
- `static/format-sdb.sh` (moved to data)
- `static/prune_zfs_snaphots.sh` (moved to data)
- `static/server_configuration.sh` (move to menu)
- `static/nextcloud_configuration.sh` (move to menu)
- `static/menu.sh` (move to menu)
- `static/main_menu.sh` (move to menu)
- `static/configuration.sh` (move to menu)
- `static/apps.sh` (move to menu)
- `static/additional_apps.sh` (move to menu)
- `static/static_ip.sh` (moved to network)
- `static/trusted.sh` (moved to network)
- `static/update-config.php` (moved to network)

@szaimen Feel free to add.

**Comment by szaimen** [comment]
functions to remove for NC20:
- [ ] yesno_box
- [ ] download_static_script
- [ ] download_le_script

But not run_main_script!!!
- [ ] run_static_script
- [ ] run_app_script

**Comment by szaimen** [comment]
> @szaimen Feel free to add.

What about `menu/configuration.sh`?

**Comment by enoch85** [comment]
I think the `COLLABORA_INSTALL` is deprecated as well. On mobile now.

**Comment by szaimen** [comment]
> I think the `COLLABORA_INSTALL` is deprecated as well

No, I don't think so:
https://github.com/nextcloud/vm/blob/e255051d962de5be642ce8066281da83d6417745/apps/collabora_docker.sh#L148

**Comment by enoch85** [comment]
@szaimen Well, isn't this setup directly in the script? https://github.com/nextcloud/vm/blob/master/lib.sh#L123

**Comment by enoch85** [comment]
We could set `NCDOMAIN` directly in the script as well and remote the `COLLABORA_INSTALL` altogether.

**Comment by szaimen** [comment]
> What about `menu/configuration.sh`?
> 
> Is this needed anywhere?

I haven't found a place where it gets downloaded nor executed hence I've put it on the list, too.

**Comment by szaimen** [comment]
@enoch85 what about this one?

**Comment by enoch85** [comment]
Yup, please go ahead with a PR if you have time.
