### ISSUE TITLE
recommendations for the VMware appliance configuration

### ISSUE THREAD

**Issue by mamama1** [nextcloud/vm#1358]
Hi

I'm a VMware admin for many years now and I have to say that the VM configuration of the VMware appliance is a bit off ideal and that's why I wanted to share some suggestions:

- Raise VM hardware level - many performance optimizations have been implemented and with V12 many performance issues mitigations in relation to spectre and meltdown patching have been implemented
- disable memory and cpu hot-add as this slows down the VM performance. It is a nice feature but how many people REALLY need it so much that they're willing to accept the performance penalty
- use the VMware Paravirtual storage controller for best performance, or please, at least the LSI Logic SAS one
- for the love of god please use the VMXNET3 instead of the E1000 adapter which is far beyond crappy
- not sure about the video card configuration (enabled 3D support, huh?)
- sooner or later EFI and secure boot should be enabled but that's more security-related than performance-related.

For many if not most home users the current config won't matter but corporate admins would love to see those changes, I'm sure ;-)

Otherwise, thanks for a great appliance and great scripts. Very good job!

All the best

**Comment by enoch85** [comment]
Thanks for the pointers. 

> Raise VM hardware level - many performance optimizations have been implemented and with V12 many performance issues mitigations in relation to spectre and meltdown patching have been implemented

That would break compatibility with older versions. Many companies still run ESXi 5.5. You are free to raise the version once mounted though.

> disable memory and cpu hot-add as this slows down the VM performance. It is a nice feature but how many people REALLY need it so much that they're willing to accept the performance penalty

Sure, will do that for next base image.

> use the VMware Paravirtual storage controller for best performance, or please, at least the LSI Logic SAS one

I just use VMware suggested values. Have been working for years, so I didn't see any reason to change.

> for the love of god please use the VMXNET3 instead of the E1000 adapter which is far beyond crappy

See above. I know it's crappy, but for compability issues and default suggestions.

> not sure about the video card configuration (enabled 3D support, huh?)

Will change for next base image

> sooner or later EFI and secure boot should be enabled but that's more security-related than performance-related.

Will look into that for the next base image.

**Comment by mamama1** [comment]
EFI will become available only with newer hardware versions, I guess.
I appreciate that you do not want to break compatibility but lets be honest, ESXi 5.5 is EOL for a veeeeeery long time now, even 6.7 has a best before date which is not too far away. Even 6.0 is unsupported since almost half a year now.
Any reasonable company should have moved away from ESXi 5.5 by now and if they haven't, they're used to compatibility issues everywhere, anyway. Apart from this, THEY can still go and change the HW version in the vmx file to a lower number.
BTW Ubuntu 20.04 is not even supported on ESXi 5.5 or 6.0 :-)

Talking ESXi 6.7, e1000 isn't supported either with Ubuntu 20.04, you would have to use e1000e, which is even crappier so vmxnet3 is the way to go (and recommended).
LSI Logic Parallel is supported but the Paravirtual one is recommended as well:

Reference: https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=software&testConfig=16&productid=50237&releaseid=485&supRel=485,&deviceCategory=software&details=1&releases=485&operatingSystems=266&productNames=15&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc&testConfig=16

**Comment by enoch85** [comment]
Hey, what about this:

You make an OVA and send it to me with what you think is decent. 

INSTALLATION
Download Ubuntu 20.04 Server https://ubuntu.com/download/server/thank-you?version=20.04&architecture=amd64
Install it and:
1. Choose the defaults all through the whole installation execpt for 3 and 4 below.
2. When asked you create a user enter the following:
    a) USER: ncadmin
    b) PASSWORD: nextcloud
    c) SERVER NAME: nextcloud
3. Choose to use LVM for the disk, and please notice that you choose the correct disk. The installer may choose the disk meant for data (sdb) automatically which is wrong.
4. Choose to install OpenSSH-Server (nothing else)
5. Finish the installation and reboot
6. Export it as OVA

Do this with:
1. 40 + 40 GB disk
2. 40 + 512 GB disk
3. 40 + 1024 GB disk
4. 40 + 2048 GB disk 

All disks should be thin.

Thanks :+1:

**Comment by mamama1** [comment]
Will do as soon as I've got my 1 TB machine up and running which I have bought yesterday ;)

**Comment by enoch85** [comment]
Thanks!

Please set the version as low as decently possible though. I will have lots of emails otherwise.

**Comment by enoch85** [comment]
And last but not least, don't do anything with the second disk (for data). Just leave it there unformated and unmounted in the guest system.

**Comment by enoch85** [comment]
Putting this here: https://github.com/nextcloud/vm/issues/910

**Comment by mamama1** [comment]
> Hey, what about this:
> 
> You make an OVA and send it to me with what you think is decent.
> 
> INSTALLATION
> Download Ubuntu 20.04 Server https://ubuntu.com/download/server/thank-you?version=20.04&architecture=amd64
> Install it and:
> 
> 1. Choose the defaults all through the whole installation execpt for 3 and 4 below.
> 2. When asked you create a user enter the following:
>    a) USER: ncadmin
>    b) PASSWORD: nextcloud
>    c) SERVER NAME: nextcloud
> 3. Choose to use LVM for the disk, and please notice that you choose the correct disk. The installer may choose the disk meant for data (sdb) automatically which is wrong.
> 4. Choose to install OpenSSH-Server (nothing else)
> 5. Finish the installation and reboot
> 6. Login and run: `sudo lvextend -l 100%FREE --resizefs /dev/ubuntu-vg/ubuntu-lv`
> 7. Poweroff
> 8. Export it as OVA
> 
> Do this with:
> 
> 1. 40 + 40 GB disk
> 2. 40 + 512 GB disk
> 3. 40 + 1024 GB disk
> 4. 40 + 2048 GB disk
> 
> All disks should be thin.
> 
> Thanks 👍

sudo lvextend -l 100%FREE --resizefs /dev/ubuntu-vg/ubuntu-lv says:

> New size given (4863 extents) not larger than existing size (5120 extents)

df -h shows only a 20G / mount but fdisk -l /dev/sda says that the main partition is 39G big.

Sorry, never liked LVM (totally useless in a VM environment, imho) and never got used to configure/use LVM so no idea where to go from here..?

**Comment by enoch85** [comment]
Yeah, that's a bug in the Ubuntu installer...

You need this image (don't update it): https://cloud.hanssonit.se/s/FAnfk3273NExreM

**Comment by mamama1** [comment]
thanks for providing the ISO, it wasn't available anymore from official sources. will try it with that one later.

**Comment by HueDa90** [comment]
same issue here. i want to go from 40g to 1024g,

New size given not larger than existing size.

any ideas or documention how to do it the right way?
do i have to extend first or second hdd in esxi?

**Comment by mamama1** [comment]
Second HDD. I wanted to do the same and ended up buying the 1 TB VM to support the hard work that has been done to provide the VM.

The 40 GB version should be good enough for you to evaluate whether the 1 TB VM is worth about EUR 40,- to you or not.
Of course, nobody stops you to extend the disk and zfs pool if you know how to do it (I don't know it).

**Comment by enoch85** [comment]
Hey @mamama1, any news here?

**Comment by enoch85** [comment]
@mamama1 What happend? Busy times?

Anyway, got this from a user:

> Daniel , just for your info and your Vmware customers (Probably your FAQ page,) the OVA import or any for that sake, fails under VCenter 6.5 and  has to be done under either VCenter 6.7 or any ESXi. It’s a VCenter 6.5 bug. Don’t know about earlier versions of VCenter.

How do we solve that?

**Comment by mamama1** [comment]
> What happened? Busy times?

sorry, yes. Will do the OVAs as soon as I got some spare time. The whole Nextcloud/Bitwarden project took longer than expected so I kind of used up the ideal time slot for doing this.



> Daniel , just for your info and your Vmware customers (Probably your FAQ page,) the OVA import or any for that sake, fails under VCenter 6.5 and has to be done under either VCenter 6.7 or any ESXi. It’s a VCenter 6.5 bug. Don’t know about earlier versions of VCenter.

I highly doubt that importing OVAs is broken in general for vSphere 6.5.

The only thing I can imagine what could have hit that user is that one has to have proper, trusted (usually local Enterprise PKI) SSL certificates installed, otherwise the import task fails. He could still use ovatool.exe though, which allows for overriding invalid SSL certificates. Also using Firefox is a solution for this issue because you can add permanent SSL exceptions there. Even running Chrome using the --ignore-certificate-errors parameter would fix this particular issue.

Anyway, if he wants anyone to troubleshoot this further, he'd at least have to provide some error messages or log files or anything like that. If he wants us to believe that this is a known bug in vSphere 6.5, I'd ask him to provide a VMware KB number.

**Comment by enoch85** [comment]
Thanks!

Regarding this issue, Ubuntu 20.04.1 is now released, and it would be great if we could have the BASE image/VM updated as soon as possible.

I understand that you are busy, no worries. Just sayin. :)

**Comment by enoch85** [comment]
@mamama1 He linked this KB: https://kb.vmware.com/s/article/2151085.

**Comment by mamama1** [comment]
Well, ok, I wasn't aware of that bug, probably because I didn't really touch 6.5 much but went straight from 6.0 to 6.7.
Nonetheless, there is a fix in an updated vCenter version (patch release, not a major release or anything like that) and there is even a workaround if you don't want/can't update your installation (which you should always do).

So I'd say, nothing to see here, keep on rolling...

**Comment by szaimen** [comment]
Can we make the new root volume 45GB big? Then LVM snapshots would be possible without sacrifice, no?

**Comment by enoch85** [comment]
@mamama1 Would be great if you could find the time to start working on the new base images. 

Just a friendly reminder. :)

**Comment by enoch85** [comment]
I'm working on this now FYI.

**Comment by enoch85** [comment]
It can now be found here: https://cloud.hanssonit.se/s/zjsqkrSpzqJGE9N?path=%2FTESTING

It will be released today as 20.0.4 in all versions.

cc @mamama1

**Comment by mamama1** [comment]
Awesome! Sorry, didn't have absolutely any time for anything lately...

**Comment by enoch85** [comment]
Time will tell if I get a lot of "the OVA is not working with XYZ hypervisor." :) I opted for Paravirtualization for the disks, I agree with you there. 

Let's hope for the best!

**Comment by enoch85** [comment]
> Thanks for the pointers.
> 
> > Raise VM hardware level - many performance optimizations have been implemented and with V12 many performance issues mitigations in relation to spectre and meltdown patching have been implemented
> 
> That would break compatibility with older versions. Many companies still run ESXi 5.5. You are free to raise the version once mounted though.
> 
> > disable memory and cpu hot-add as this slows down the VM performance. It is a nice feature but how many people REALLY need it so much that they're willing to accept the performance penalty
> 
> Sure, will do that for next base image.
> 
> > use the VMware Paravirtual storage controller for best performance, or please, at least the LSI Logic SAS one
> 
> I just use VMware suggested values. Have been working for years, so I didn't see any reason to change.
> 
> > for the love of god please use the VMXNET3 instead of the E1000 adapter which is far beyond crappy
> 
> See above. I know it's crappy, but for compability issues and default suggestions.
> 
> > not sure about the video card configuration (enabled 3D support, huh?)
> 
> Will change for next base image
> 
> > sooner or later EFI and secure boot should be enabled but that's more security-related than performance-related.
> 
> Will look into that for the next base image.

So all of the above should now be fixed. Made a new release today with Ubuntu 22.04 - all VMs are now updated.

What I could see I couldn't choose certain stuff in VMware Workstation (I know they exist in ESXi), but if you want to change them, just go ahead and do it.

Hope you'll enjoy the new VMs! :)
