### ISSUE TITLE
Improve Bitwarden even more

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1363]
@szaimen As discussed.

Stuff left:

1. A better more clear IMGUR screenshot with removed host keys
2. Try the suggestion to add a seperate user for Bitwarden since their support  thought that was the best soulution. I suggest `ncbitwarden` but maybe it has to be `bitwarden`?

`You will want to configure the Bitwarden Server to use a **bitwarden** service account. $USER=bitwarden You will want to have your installation owned by the bitwarden service account, and you should be logged in as bitwarden. After those are verified, you will want to make sure the UID and GID in the /bwdata/env/uid.env file are set to your bitwarden service account id numbers in Linux. `
```
When using the bitwarden service account you will also need to follow these steps:

1. Make sure the docker group has been created.
sudo groupadd docker

2. Add the bitwarden account to the docker group
sudo usermod -aG docker $USER

3. Create the bitwarden service file (may want to store it with your bitwarden installation)
sudo vi bitwarden.service

[Unit]
Description=Bitwarden
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
User=ncbitwarden
Group=ncbitwarden
ExecStart={INSTALL_DIR}/bitwarden.sh start
RemainAfterExit=true
ExecStop= {INSTALL_DIR}/bitwarden.sh stop

[Install]
WantedBy=multi-user.target

4. Copy the bitwarden service file to systemd.
sudo cp bitwarden.service /etc/systemd/system/bitwarden.service

5. Set permissions on bitwarden service file under systemd.
sudo chmod 644 /etc/systemd/system/bitwarden.service

6. Optional (reload for testing)
systemctl daemon-reload

7. Add service to start with system boot.
sudo systemctl enable bitwarden.service
```

I have to go now, maybe you could have a look at that? Thanks!

**Comment by szaimen** [comment]
Before we start with fixing this: where should be the new location of bwdata? 
I ask since the /root directory doesn't fit anymore if using a dedicated bitwarden account...

**Comment by enoch85** [comment]
Exactly! I was thinking we put it in the users $HOME. Do you have a better suggestion?

**Comment by enoch85** [comment]
Maybe `/opt` but then we need to change permissions of that sub-folder to the bitwarden user. I actually don't know what's best practice here. :(

**Comment by enoch85** [comment]
I will join you soon, have to finish a job here. Maybe you can prepare a PR meanwhile? Should be quite straight forward.

**Comment by szaimen** [comment]
I'll start a PR but will have something to do later...

**Comment by szaimen** [comment]
> Exactly! I was thinking we put it in the users $HOME. Do you have a better suggestion?

I guess this is the best place for this...
