### ISSUE TITLE
set default_locale in config.php

### ISSUE THREAD

**Issue by mamama1** [nextcloud/vm#1373]
Hi

I would suggest to set default_locale and maybe even default language in config.php to a user defined value or to a value which derives from timezone and/or keymap settings...?

not too important but a nice to have...

**Comment by enoch85** [comment]
I don't see why?

The default for the CLI is US., 

For Nextcloud it autodetects your location (if you allow that ofc) and set the display language according to that.

**Comment by mamama1** [comment]
interesting, nextcloud didn't detect my locale properly and defaulted to en_US.
nevermind - if it is supposed to autodetect based on the browser, the problem might have been my client setup.

**Comment by enoch85** [comment]
We automate some locales, but if we don't have an option for your specific locale, it will default to US.

I'm on mobile now, can link later.

**Comment by mamama1** [comment]
I use de_DE, nothing special, imho... maybe it really has something to do with my browser.

**Comment by enoch85** [comment]
If you're taling about the browser, yes, it's on your end - or a bug in Nextcloud. 

If you're talking about CLI: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L175 & https://github.com/nextcloud/vm/blob/master/addons/locales.sh#L21-L23
