### ISSUE TITLE
No option to set static IP address when DHCP & Internet Fully operational

### ISSUE THREAD

**Issue by TracyIi** [nextcloud/vm#1376]
## Steps to reproduce
Mount ova in VMWare Player and let it  run through its startup, choose to set static IP address from the menu

## Expected behaviour
per the instructions:
"4.1 TLDR;
  
The startup-script needs a working internet connection to run. It will check in the following order:

DHCP OK? --> Yes --> Can we reach internet? ---> Yes --> Continue to run the script --> Ask to set static IP later as an option.
DHCP NOT OK? --> Ask to set static IP --> Can we reach internet? ---> Yes --> Continue to run the script.
DHCP NOT ACTIVATED? --> Ask to set a static address right from the get go.
SET STATIC IP if all of the above fails.
So all and all, it will only ask to set static IP if if can't reach internet with DHCP. You will get the option to set static IP later though."

## Actual behaviour
No option was offered to set a static IP address

## Server configuration

**Nextcloud server version:** (see your admin page)
Nextcloud 19.0.1

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Open ova file with VMWare Player

## Network
We do use DHCP, but wanted to use a static IP address for this server.

**Is port 80 and/or 443 open?**
Yes

#### Log file (/var/log/nextcloud/nextcloud.log)
```
log file is empty

```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi,

Thanks for  posting your issue.

If you have a working internet connection, yo won't be offered to set one as a first task of the setup - as it says in the documentation. But, you are offered to set it up during the installation in the menu "Server Configuartion": https://github.com/nextcloud/vm/blob/master/menu/server_configuration.sh

Did I understand you correctly that you weren't offered that menu at all?

**Comment by TracyIi** [comment]
I wasn’t offered the server configuration menu at all

Tracy L. Horstman | Leidos
Sr. Stf. UNIX Administrator | Defense & Intelligence
Automated Movement and Identification Solutions (AMIS)
Radio Frequency - In-Trans Visibility III (RF-ITV III)
6909 Metro Park Dr
Suite 110 – 01083W
Alexandria, VA 22310
Phone:  571-319-8205
Mobile:  571-606-6812
tracy.l.horstman@leidos.com<mailto:tracy.l.horstman@leidos.com> | leidos.com/defense<http://www.leidos.com/defense>
tracy.l.horstman.ctr@mail.mil<mailto:tracy.l.horstman.ctr@mail.mil> (DISA Enterprise Email)

[cid:image001.png@01D39C0B.B12658D0]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by enoch85** [comment]
OK, did you complete the whole setup and there were no option at all to set static IP?

**Comment by enoch85** [comment]
I'm asking because you should be offered a menu in like the middle of the setup...

**Comment by TracyIi** [comment]
No, I was never offered a menu to set the static IP address
I was offered a menu put a (*) by the option to set a static IP address but didn’t get a menu to do it before it completed the entire setup

Tracy L. Horstman | Leidos
Sr. Stf. UNIX Administrator | Defense & Intelligence
Automated Movement and Identification Solutions (AMIS)
Radio Frequency - In-Trans Visibility III (RF-ITV III)
6909 Metro Park Dr
Suite 110 – 01083W
Alexandria, VA 22310
Phone:  571-319-8205
Mobile:  571-606-6812
tracy.l.horstman@leidos.com<mailto:tracy.l.horstman@leidos.com> | leidos.com/defense<http://www.leidos.com/defense>
tracy.l.horstman.ctr@mail.mil<mailto:tracy.l.horstman.ctr@mail.mil> (DISA Enterprise Email)

[cid:image001.png@01D39C0B.B12658D0]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by enoch85** [comment]
Hmm, strange, needs to be checked!

cc @szaimen If you have time. This is urgent.

**Comment by szaimen** [comment]
yah, I found the problem.
I'll come up with a fix soon

**Comment by enoch85** [comment]
Another issue is that we use the old lib file, and it's looking in STATIC... I will fix that now.

**Comment by TracyIi** [comment]
I got around it by unplugging the network cable so it would fail and then allow me to put in the IP address, subnet mask, gateway & DNS

Thanks!
Tracy

Tracy L. Horstman | Leidos
Sr. Stf. UNIX Administrator | Defense & Intelligence
Automated Movement and Identification Solutions (AMIS)
Radio Frequency - In-Trans Visibility III (RF-ITV III)
6909 Metro Park Dr
Suite 110 – 01083W
Alexandria, VA 22310
Phone:  571-319-8205
Mobile:  571-606-6812
tracy.l.horstman@leidos.com<mailto:tracy.l.horstman@leidos.com> | leidos.com/defense<http://www.leidos.com/defense>
tracy.l.horstman.ctr@mail.mil<mailto:tracy.l.horstman.ctr@mail.mil> (DISA Enterprise Email)

[cid:image001.png@01D39C0B.B12658D0]
This email and any attachments to it are intended only for the identified recipients. It may contain proprietary or otherwise legally protected information of Leidos. Any unauthorized use or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify the sender and delete or otherwise destroy the email and all attachments immediately.

**Comment by enoch85** [comment]
@TracyIi Thanks again for posting your issue! This is now fixed in master (just waiting for checks to pass).

@szaimen Thanks for responding so quickly!
