### ISSUE TITLE
Restore subtlitle of OnlyOffice (Integrated)

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1379]
I would actually change that back to 
`"OnlyOffice (Integrated)" "(Online editing - no subdomain required)"`
https://github.com/nextcloud/vm/blob/f00d35644efbf48939ef778dc22311037e4c8052/menu/documentserver.sh#L23
Since in the script itself is no cpu- and ram-check (and also not needed, afaik) and no requirement for a subdomain...

_Originally posted by @szaimen in https://github.com/nextcloud/vm/pull/1369#issuecomment-676785688_

**Comment by szaimen** [comment]
Thanks for the fix! But actually the integrated collabora needs 2gb of ram!
But Integrated onlyoffice not!

**Comment by enoch85** [comment]
Fixed.
