### ISSUE TITLE
Trying to install certificate behind reverse proxy

### ISSUE THREAD

**Issue by matthieuscerri** [nextcloud/vm#1397]
## Steps to reproduce
1.Install nextcloud on ubuntu 20.04 vm
2. place behind nginx reverse proxy
3.try to obtain ssl cert to install all apps

## Actual behaviour
Tell us what happens instead

Maybe there should be a prompt to create a self signed certificate ? 

## Server configuration

**Nextcloud server version:** (see your admin page) version 19

**Server OS** (Ubuntu server is default) ubuntu 20.04 lts

**How did you install the VM?** (Scripted install from master **OR** Released version)

installed via latest master script

## Network
**Do you use DHCP?**
Static ip via dhcp reservation
**Is port 80 and/or 443 open?**
Yes to the reverse proxy
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi,

Thanks for posting.

Actually, there's already built in Apache Vhosts for Nextcloud. Just check in the Apache sites-available dir. ;)
