### ISSUE TITLE
Change some implementations after #1396

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1399]
Just as a reminder to change some implementations after #1396

- [x] 1. SCRIPT_NAME https://github.com/nextcloud/vm/pull/1396#discussion_r483057386 #1400
- [x] 2. yesno_box https://github.com/nextcloud/vm/pull/1396#discussion_r483057684 #1401
- [x] 3. input_box https://github.com/nextcloud/vm/pull/1396#discussion_r483058440 #1402

**Comment by szaimen** [comment]
@enoch85 I am currently thinking about changing all `whiptail --radiolist`'s to `whiptail --menu`'s because of a few advantages. 

I made a pro-contra list:

### pro (for whiptail-menu):
- better distinguishable from the checklist
- doesn't need a guide how to use it (is relatively intuitiv, espacially in contrast to the radiolist, imho)
- it is faster for the user because you don't need to select an item with the spacebar
- needs a bit less code (doesn't need the ON or OFF value behind every option)

### contra (against whiptail-menu):
- it looks a bit unfamiliar (but I think you/we will get used to it 😉)

What do you think?

**Comment by enoch85** [comment]
Sounds promising, but do you have a real life example to show?

**Comment by enoch85** [comment]
Found this: https://www.bradgillap.com/guide/post/bash-gui-whiptail-menu-tutorial-series-1#advancedMenu

Is that what you mean?

**Comment by szaimen** [comment]
Yes, here is an example from the smb-mount script:
### whiptail --radiolist:
```
    choice=$(whiptail --title "$TITLE" --radiolist "This script let you manage SMB-shares to access files from the host-computer or other machines in the local network.\nChoose what you want to do.\nSelect one with the [ARROW] keys and select with the [SPACE] key. Confirm by pressing [ENTER]" "$WT_HEIGHT" "$WT_WIDTH" 4 \
    "Add a SMB-mount" "(and mount/connect it)" ON \
    "Mount SMB-shares" "(connect SMB-shares)" OFF \
    "Show all SMB-mounts" "(show detailed information about the SMB-mounts)" OFF \
    "Change a SMB-mount" "(change password, username &/or share of a mount)" OFF \
    "Unmount SMB-shares" "(disconnect SMB-shares)" OFF \
    "Delete SMB-mounts" "(and unmount/disconnect them)" OFF \
    "Exit SMB-share" "(exit this script)" OFF 3>&1 1>&2 2>&3)
```
![image](https://user-images.githubusercontent.com/42591237/92220014-a4c5f600-ee9b-11ea-8443-faf28bc1878f.png)

### whiptail --menu:
```
    choice=$(whiptail --title "$TITLE" --menu "This script let you manage SMB-shares to access files from the host-computer or other machines in the local network.\nChoose what you want to do." "$WT_HEIGHT" "$WT_WIDTH" 4 \
    "Add a SMB-mount" "(and mount/connect it)" \
    "Mount SMB-shares" "(connect SMB-shares)" \
    "Show all SMB-mounts" "(show detailed information about the SMB-mounts)" \
    "Change a SMB-mount" "(change password, username &/or share of a mount)" \
    "Unmount SMB-shares" "(disconnect SMB-shares)" \
    "Delete SMB-mounts" "(and unmount/disconnect them)" \
    "Exit SMB-share" "(exit this script)" 3>&1 1>&2 2>&3)
```
![image](https://user-images.githubusercontent.com/42591237/92219938-88c25480-ee9b-11ea-9a51-0479f7e15087.png)

**Comment by enoch85** [comment]
Thanks for a perfect example!

Problem with the menu is that we can't pre-select like with the radiolist. 

In some cases we want to pre-select, like in the install script and Activate TLS for example. Is it possible to pre-select with the menu?

**Comment by szaimen** [comment]
Do you mean those menus?
https://github.com/nextcloud/vm/blob/ecf21910296c17a8670add66504403868fcf3059/nextcloud_install_production.sh#L176
https://github.com/nextcloud/vm/blob/cf6363494f243dc5789413eeec1aca27fa0b774f/nextcloud_install_production.sh#L205
https://github.com/nextcloud/vm/blob/ecf21910296c17a8670add66504403868fcf3059/menu/server_configuration.sh#L36
I mean, yes, we cannot pre-select, but we can move the default one to the top, which should be good enough, imo.
And btw: the third one (sever-configuration-menu with activate-tls option) is not a --radiolist but a --checklist, which wouldn't get changed
