### ISSUE TITLE
Reported by email

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1407]
Message Body:
hello im just trying to install a new vm i get ti the point where im ask to select tls/extra security and static ip i selected these press ok extra security installed moved on to static ip it says something about ip may change using ssh
press ok to continue i did but instead of getting a screen asking me for a static ip i get a constant script saying
/var/scripts/static_ip.sh: line 76 inputbox command not found
did you forget the /subnet?
im installing home-sme 19.0.1 hub on virtualbox
im doing the say as a previous install that worked fine just trying to test some differnet apps to see what works best for me
many thanks for the work you do

Cc @szaimen could you have a look? I'm on mobile. It's quite urgent as we just made a new release 

Thank you very much!

## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by szaimen** [comment]
hm, I am not completely sure but it sounds like he is not using the latest NcVM release...
BTW: I have problems reading the message and understanding what the problem is...

**Comment by szaimen** [comment]
static_ip.sh works for me (in a test-vm)

**Comment by enoch85** [comment]
Just tested without internet (as users would get it) to force static_ip to be run. And it works as intended, all functions are in place, even in the local lib. 

*peew* :)
