### ISSUE TITLE
Generated Redis password with space breaks Redis

### ISSUE THREAD

**Issue by fabiankessler** [nextcloud/vm#141]
I've done a clean install with the latest release 11.0 and the browser greeted me with 

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request.
> Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
> More details can be found in the server log.

The command

`journalctl -xe`

then said:

> Feb 23 14:46:25 nextcloud run-parts[2249]: run-parts: executing /etc/redis/redis-server.pre-up.d/00_example
> Feb 23 14:46:25 nextcloud redis-server[2255]: *** FATAL CONFIG FILE ERROR ***
> Feb 23 14:46:25 nextcloud redis-server[2255]: Reading the configuration file, at line 396
> Feb 23 14:46:25 nextcloud redis-server[2255]: >>> 'requirepass XX9xx9x9xxXXxx9X9# foobared'
> Feb 23 14:46:25 nextcloud redis-server[2255]: Bad directive or wrong number of arguments
> Feb 23 14:46:25 nextcloud systemd[1]: redis-server.service: Control process exited, code=exited status=1
> Feb 23 14:46:25 nextcloud systemd[1]: Failed to start Advanced key-value store.

The line is not in the mentioned /etc/redis/redis-server.pre-up.d/00_example but instead in the /etc/redis/redis.conf

The password (modified digits and letters) has a hash sign, followed by a space. Redis does not start because of this. Removing the space worked to start Redis.

But then I also needed to tell Nextcloud to use this password. That is in /var/www/nextcloud/config/config.php and the password there was 'XX9xx9x9xxXXxx9X9#' that is, everything up to including the hash sign.

Ah, now I get it. I believe foobared is the default password. So your script does not remove that, and prepends the generated one. Something like that. Anyway, it's a how stopper, please fix ;-)

**Comment by enoch85** [comment]
@fabiankessler 
>Removing the space worked to start Redis.

Exactly what do you mean by that?

What would fix this issue? I can out the code in if you have a solution. 

Thanks!

**Comment by enoch85** [comment]
@Ark74 Can you have a look? I'm quite busy now.

**Comment by enoch85** [comment]
@keengene Please have a look.

**Comment by keengene** [comment]
My bad.

> I believe foobared is the default password. So your script does not remove that, and prepends the generated one. Something like that. 

This is exactly what happens. Fixed and PR'ed.

**Comment by enoch85** [comment]
@fabiankessler Please try again and confirm that this is fixed. Thanks!

**Comment by enoch85** [comment]
Tested and works.

**Comment by fabiankessler** [comment]
(My VM was functional after my manual fix, I won't re-install a new VM)

**Comment by enoch85** [comment]
@fabiankessler Thanks for letting us know about this error! Very appreciated.
