### ISSUE TITLE
Debug the startup script

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1415]
@szaimen 

Just ran the latest VM and we have a major bug in there.

I don't know which commit that cause it, but we need to investigate like right now.

![Screenshot from 2020-09-07 12:10:35](https://user-images.githubusercontent.com/4511254/92376694-400cd480-f103-11ea-8421-6b52942dcd74.png)

**Comment by enoch85** [comment]
I think it happens here: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L358

**Comment by enoch85** [comment]
Please download the latest released VM and run the script and test all prompts.

I'll do the same. 

Thanks!

**Comment by szaimen** [comment]
> Please download the latest released VM and run the script and test all prompts.
> 
> I'll do the same.
> 
> Thanks!
 I am on it 👍

**Comment by szaimen** [comment]
this looks like there is a '&' missing, no?
https://github.com/nextcloud/vm/blob/cbc20d1881f1341db2b8b231b83acfdc611278bb/nextcloud-startup-script.sh#L358
So that it results in 
`bash $SECURE && spinner_loading `

**Comment by szaimen** [comment]
for me it looks like the failure was caused here:
https://github.com/nextcloud/vm/blob/cbc20d1881f1341db2b8b231b83acfdc611278bb/nextcloud-startup-script.sh#L367
But this worked in my testing... So I am not sure how to reproduce it...

**Comment by szaimen** [comment]
acutally together with the other failed commands it looks to me like the library wasn't successfully imported but this works for me.
What did you do to trigger this?

**Comment by szaimen** [comment]
It looks to me like this function never returns a failure:
https://github.com/nextcloud/vm/blob/cbc20d1881f1341db2b8b231b83acfdc611278bb/nextcloud-startup-script.sh#L69
So this just continues after a wait for 40 seconds and then just continues with the script without presenting you with the option to run the static_ip script... But I could be wrong...

**Comment by szaimen** [comment]
So I would change this:
https://github.com/nextcloud/vm/blob/cbc20d1881f1341db2b8b231b83acfdc611278bb/lib.sh#L827
to this:
```
if ! site_200 github.com
then
    return 1
fi
```

**Comment by szaimen** [comment]
Could you reproduce the issue? What are your findings?

**Comment by enoch85** [comment]
I ran the latest scripts on a VPS and the issue never came back.

Now I have to pick up my daughter in school so I can't continue right now. Sorry.

>  bash $SECURE & spinner_loading 

No, that's correct as is.

> What did you do to trigger this?

I first ran without internet, then connected it again, so maybe the startup script was using the local (old) lib?

**Comment by szaimen** [comment]
> I ran the latest scripts on a VPS and the issue never came back.
> 
> Now I have to pick up my daughter in school so I can't continue right now. Sorry.
>
> > bash $SECURE & spinner_loading
> 
> No, that's correct as is.

okay 👍
 
> > What did you do to trigger this?
> 
> I first ran without internet, then connected it again, so maybe the startup script was using the local (old) lib?

hm, I'll have a look

**Comment by szaimen** [comment]
I tested without internet access and it fails to run the startup script as expected (and als runs static_ip as expected). So I cannot reproduce the issue.

**Comment by enoch85** [comment]
I will test one more time, if we can't reproduce it I'll close.

**Comment by enoch85** [comment]
Not reproducible...

**Comment by enoch85** [comment]
I think it was my router that failed on me. I noticed the other day that it was bricked. I had to open it and replace the USB-drive with a new one.

Cause: internet went down during the script run.
