### ISSUE TITLE
Issue with accesing adminer after enabling TLS for nextcloud

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1430]
So I've just found an issue:

The same happens, after I activate only tls for the nextcloud domain ->
I can no longer acces adminer on the local `ip/adminer.php` but get redirected to the nextcloud domain.
Any idea how to fix this?

**Comment by szaimen** [comment]
The same happens, after I activate only tls for the nextcloud domain -> 
I can no longer acces adminer but get redirected to the nextcloud domain.
Any idea how to fix this?

**Comment by szaimen** [comment]
maybe this could be a starting point https://www.youtube.com/watch?v=mG2yxweBtBc&feature=emb_title

**Comment by enoch85** [comment]
Is adminer.conf active?

**Comment by szaimen** [comment]
Yes, adminer.conf is in /etc/apache2/conf-enabled

**Comment by enoch85** [comment]
Maybe https://github.com/nextcloud/vm/pull/1447 fixes this as well?

**Comment by szaimen** [comment]
this was fixed by #1447
But if I open http://ip-address:8443, I get the following issue. But I guess there is no workaround, is there any?
![image](https://user-images.githubusercontent.com/42591237/93014945-80fa6280-f5b5-11ea-82a7-109eb40cd9e9.png)

**Comment by szaimen** [comment]
BTW: I would suggest using a different port since it is possible that some user still use the old bitwarden on port 8443:
https://github.com/nextcloud/vm/blob/75bf1bbffcde90dd5d62ffef6cac960f0605a57b/apps/tmbitwarden.sh#L64

**Comment by enoch85** [comment]
> But if I open http://ip-address:8443,

Yes, that's expected. We don't link **http://** anywhere, and the information in the text tells the user to change to https anyway. I don't consider it a bug - but maybe we can improve it later.

Anyway, new PR merged, can we close this issue now?

**Comment by szaimen** [comment]
I've opened #1452 which fixes this issue
