### ISSUE TITLE
Network NOT OK. Fresh VM Install

### ISSUE THREAD

**Issue by highaltidude** [nextcloud/vm#1436]
Fresh install with OVA downloaded from Nextcloud. Install ran fine and setup is throwing errors. Server has access to Internet and can ping github.com

"Network NOT OK. You must have a working network connection to run this script."

Testing if network is OK...
Checking connection...
Online!
Testing if network is OK...
Checking connection...
curl: (6) Could not resolve host: github.com
curl didn't produce a 200 status, is the site reachable?

Any assistance is appreciated.

**Comment by enoch85** [comment]
Hi,

That's just temporary it seems, since you got OK the first time, maybe the second check failed. Where you offered to set a static IP since it failed?

Please try again and report back.

**Comment by highaltidude** [comment]
I was not. After it fails it goes back to the command prompt.

**Comment by enoch85** [comment]
OK? That seems very strange. :thinking: 

I tested the 19.0.2 VM today two times, one without internet, and one with. Both worked. 

Can you please record a video of the whole process and upload it here?

Thanks!

**Comment by highaltidude** [comment]
Work computer, can't record video. Essentially it boots, i use the default login, initial setup script prompt and errors out.

Tried a new OVA download, same issue. ESXi 6.7

**Comment by highaltidude** [comment]
We can mark this one closed. Adguard was blocking something. Working now! Thanks for your help!

**Comment by enoch85** [comment]
Glad you solved it!
