### ISSUE TITLE
What is new and undergoing testing?

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1437]
Just recently we introduced two new things that we will test for a while before they go live in all scripts.

- add a border after the scripts header (e.g. in main_menu)

We might add more in the future. This list is just to keep track of what we not fully implemented yet.

@szaimen, feel free to add.

**Comment by enoch85** [comment]
@szaimen We should add this all over: "A new function for re-installing, currently only exists in Adminer"

**Comment by szaimen** [comment]
> @szaimen We should add this all over: "A new function for re-installing, currently only exists in Adminer"

This will be my next project.

**Comment by szaimen** [comment]
Shall this be one PR for each script? Or one big PR for everything?

**Comment by enoch85** [comment]
> Shall this be one PR for each script? Or one big PR for everything?

Please make it one per script.

Thanks!

**Comment by szaimen** [comment]
I think this should be all.

**Comment by szaimen** [comment]
@enoch85 shall we take the opportunity and rewrite the office scripts to allow parallel installations of different office solutions?
I have an idea how to do this which will also make the office scripts much shorter.

**Comment by enoch85** [comment]
> @enoch85 shall we take the opportunity and rewrite the office scripts to allow parallel installations of different office solutions?
I have an idea how to do this which will also make the office scripts much shorter.

If it's supported, yes. But I have a feeling it will just lead to issues. Dual dockers are not supported, only integrated, right?

**Comment by szaimen** [comment]
> If it's supported, yes. But I have a feeling it will just lead to issues. Dual dockers are not supported, only integrated, right?

It is a bit complicated to explain by words what my idea is.
I will make a PR and you will see.

**Comment by szaimen** [comment]
This will be different PRs than the currently existing ones, though.
So I guess I will wait until they are ready (and merged) so that I don't run into conflicts and can start the work on the new and better base :)

**Comment by enoch85** [comment]
@szaimen Please remove the border and close this issue.

Thanks!

**Comment by szaimen** [comment]
Do you mean that the border shall get removed from locales.sh, main_menu.sh and menu.sh?

**Comment by enoch85** [comment]
Yes please 🙏
