### ISSUE TITLE
Stick to stable kernel (4.4)

### ISSUE THREAD

**Issue by Ark74** [nextcloud/vm#144]
I'm testing the the installation script with CODE, i see it installs the latest hwe kernel, which  at this time is linux 4.8.0-34
The kernel 4.8 doesn't have AUFS support, since it's not an upstream stable release.

Ubuntu 16.04 install 4.4 kernel by default, which has aufs support and it is still a LTS kernel release.
This will result on a failure when installing the CODE container, unless the docker storage driver is changed manually.

Cheers!

**Comment by enoch85** [comment]
Hmm, interesting.

@Ark74 Can you do some research on how to keep the latest kernel and still get CODE running?

**Comment by enoch85** [comment]
Just remembered... I run kernel 4.8 on my production server, and I have no issues with CODE (Collabora)

**Comment by Ark74** [comment]
I got the very ambiguous "Access Denied" so i'm trying with a clean installation with aufs precharged (linux-image-extra-virtual linux-image-extra-$(uname -r) ) and the 4.8 kernel installation disable.

I'm testing with a clean vm i'll report.

**Comment by Ark74** [comment]
I found an issue, lest's encrypt won't create the certificate for the office.nextcloud.com domain, the one used for the docker image.
We should add -d $domain to

`./letsencrypt-auto certonly --agree-tos --webroot -w $NCPATH -d $domain`

**Comment by enoch85** [comment]
@Ark74 Yes, it's creating the cert here: https://github.com/nextcloud/vm/blob/master/static/collabora.sh#L251

**Comment by Ark74** [comment]
This is the history line i get every time:

=========================
Start script installation:

Change mirror: N (PR #149  )
Change kblayout: n
Select Apps:
(None)

Reboot 1 

Message Block
Press any key to start the script. Press CTRL+C to abort.

Use VPS : Y
Setup Keyboard: N

Select apps:
* Collabora

Input 
office domain: office.domain.com
nc domain: nc.domain.com

Check port 443: Ok

Run collabora script.
Add extra security: N

Set up Timezone
(UTC)
User system password update
NC password update

Congratulation message block
(Key to continue)

Setup SSL: y
Continue: y
Port 443 open: y
domain available: y

Enter domain: nc.domain.com
is it correct?: Y

input email: my@email.com
agree: A
Share mail: N

System reboot

**New login, scripts ends, no more follow on the CODE docker installation.**

=========================
Here i manually download collabora.sh and run it and ends with this behavior. https://github.com/nextcloud/vm/issues/144#issuecomment-282528993

**Comment by Ark74** [comment]
Is this normal? https://github.com/nextcloud/vm/issues/144#issuecomment-283899350

**Comment by enoch85** [comment]
This is fixed.

**Comment by Ark74** [comment]
Nice
