### ISSUE TITLE
scripts must be run as root if lib.sh doesn't exist already

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1441]
To be able to run any script using fetch_lib, the user must run as root - otherwise it won't be able to get the lib.sh to /var/scripts and the the scipt bugs out with that lib doesn't exists and that internet doesn't work.

This needs to be fixed. We should probably check if sudo and print the correct error message. Right now the error is toally wrong.

We should probably make scripts writable by everyone as well, or maybe not, I don't know right now.

cc @szaimen

**Comment by szaimen** [comment]
I would suggest adding `chmod 777 /var/scripts/fetch_lib.sh`
And add a root-check to the fetch_lib file itself.
```
if [[ "$EUID" -ne 0 ]]
then
    print_text_in_color "$IRed" "You must run this script as root!"
    exit 1
fi
```
