### ISSUE TITLE
adjust the bitwarden-mailconfig script to fit the new input_box_flow function

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1453]
follow up to #1449

**Comment by enoch85** [comment]
We should grep the current value in Bitwardens config file.

If empty = ask user to add a value
If not empty = "Do you want to use the current value?

**Comment by enoch85** [comment]
Ping @szaimen

**Comment by szaimen** [comment]
This can now copy over many things from the smtp-mail script since it already has a comparable and superior UX.

**Comment by enoch85** [comment]
@szaimen Maybe the next stability project?

**Comment by szaimen** [comment]
I'd rather focus on the rewrite of the office scripts...

**Comment by enoch85** [comment]
> I'd rather focus on the rewrite of the office scripts...

Question: Does that add a new feature, or more stability? :)

**Comment by szaimen** [comment]
I would say more stability since it will be much easier to read and much less code ;)

**Comment by enoch85** [comment]
@szaimen Is this still valid?

**Comment by szaimen** [comment]
Yes, I fear. The plan was to borrow some ideas from the smtp-mail script to make the configuration easier and more straight-forward but I currently don't have time for this...
