### ISSUE TITLE
Do something about the passwords promt during first setup

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1454]
Now when we have the fancy `input_box_flow` merged, maybe we could do something about the prompts for password during the first setup? 

1. ncadmin password
2. New Nextcloud user

That way we can also make sure that the password is correctly written as we could write the output directly on screen - thus minimizing "I lost my password becasue the keystrokes were incorrect in console / putty."

**Comment by szaimen** [comment]
1. https://ccm.net/faq/790-changing-password-via-a-script
2. https://help.nextcloud.com/t/solved-create-user-with-occ-problem-with-password/26433/2

**Comment by szaimen** [comment]
### A starting point:
#### for 1.:
```
msg_box "We will now change the password for the unix-user"
UNIX_PASSWORD=$(input_box_flow "Please type in the new password for the unix-user")
echo -e "$UNIX_PASSWORD\n$UNIX_PASSWORD" | (passwd --stdin "$(getent group sudo | cut -d: -f4 | cut -d, -f1)")
```
#### for 2.:
```
msg_box "We will now change the username and password for the nextcloud-admin user"
NEWUSER=$(input_box_flow "Please type in the name of the nextcloud-admin user")
export OC_PASS=$(input_box_flow "Please type in the new password for the nextcloud-admin user")
occ_command user:add "$NEWUSER" --password-from-env -g admin
```
