### ISSUE TITLE
a script for configuring a SMB-server

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1462]
Hey, I know that we have currently many things that are under construction and not done yet, but what do you think about a script for configuring a SMB-server? I've yesterday/tonight made one 😉
It works already quite nicely but I have to make some polishing like comments and wordings, have a look if travis works, and so on...

**Comment by enoch85** [comment]
I think it's outside for the scope of the Nextcloud VM.

We should provide a VM that brings Nextcloud and it's features (with exception of Bitwarden due to badly maintained password managers like that in Nextcloud), an SMB server is a totally different thing if you ask me.

Nextcloud should act as a client for the SMB server. Nextcloud *is not* an SMB-server.

**Comment by szaimen** [comment]
> I think it's outside for the scope of the Nextcloud VM.
> 
> We should provide a VM that brings Nextcloud and it's features (with exception of Bitwarden due to badly maintained password managers like that in Nextcloud), an SMB server is a totally different thing if you ask me.
> 
> Nextcloud should act as a client for the SMB server. Nextcloud _is not_ an SMB-server.

Okay, I guess then I will have to host it on github myself...
Would you like to see the script nontheless?
I can make a PR which we not merge and you could try it out for yourself if you want.
I think what it makes great is the real deep integration into the files_external app of Nextcloud!

**Comment by szaimen** [comment]
@enoch85 If you want to see the script just tell me ;)

**Comment by enoch85** [comment]
>If you want to see the script just tell me ;)

I guess you made it public in your repo?

**Comment by szaimen** [comment]
> > If you want to see the script just tell me ;)
> 
> I guess you made it public in your repo?

No, not yet. I would still like to get this into the VM ;)

**Comment by enoch85** [comment]
@jospoortvliet @karlitschek 

What do you guys think? Should we add an SMB-server script to the VM?

**Comment by szaimen** [comment]
I mean [nextcloudpi](https://github.com/nextcloud/nextcloudpi) has implemented something like that but it has a different focus than the VM, of course and I've gone a bit different approach then their samba-server functionality ;)

**Comment by szaimen** [comment]
@enoch85 I'll create a PR and you can test it yourself in a test-vm (of course makes most sense if you are in a private network together with the VM to be able to test the samba-functionality out)

**Comment by szaimen** [comment]
I've created #1471 for this purpose
