### ISSUE TITLE
vm os suggestion: use thin lv instead of regular lv

### ISSUE THREAD

**Issue by mailinglists35** [nextcloud/vm#1481]
with manual partitioning in terminal before launching the installer from the live iso, ubuntu 20.04 can be installed on thin lv, which gives the advantage that issuing fstrim would release the storage blocks all the way down to the last device that supports discards.

for example I could fill the vm space then I could release it after mass deleting files so the backing qcow2 files would free it's blocks when guest is configured with `discard='unmap'`

don't forget to enable less than 100 thin_pool_autoextend_threshold value in lvm.conf and thin_pool_autoextend_percent

random example setup steps https://www.theurbanpenguin.com/thin-provisioning-lvm2/

**Comment by enoch85** [comment]
@mailinglists35 Thanks for your suggestion.

**Comment by enoch85** [comment]
Wouldn't this allow overcommit of the storage? Not a good thing to add in a default setup. 

The user would then have to have a really close look at the storage at all times, which I don't think should be a default setting.

**Comment by enoch85** [comment]
@mailinglists35 Hey, still no answer?

**Comment by szaimen** [comment]
If I understand this issue correctly, this should be fixed with https://github.com/nextcloud/vm/pull/1518
@mailinglists35 please reopen if this isn't the case.
