### ISSUE TITLE
Domain not accessible after changing ip-adres in config.php, old domain is

### ISSUE THREAD

**Issue by Verdomme** [nextcloud/vm#1486]
Hello, 
The installation of Nextcloud VM package with VirtualBox went flawless. I got it up and running. No problems there. But changing the internal ip-adres of the laptop where i've installed the Nextcloud VM doesn't direct me to this new adres. I made the change in config.php (/var/www/nextcloud/config/config.php), saved it and rebooted VirtualBox. The new ip-adress is visible beneath trusted domains array. This is what is looks like with the new ip adres: 
**0 => 'localhost',
1 => '192.168.178.75'**
But it is not reachable. I had this ip-adres fixed in my router and opened all necesarry ports. 
The webmin is only reachable by the old ip-adres that was automaticlly generated when I first installed Nextcloud VM.

Did I overlook something or is there something else that is hindering Nextcloud?

Thank you.

**Comment by enoch85** [comment]
Thanks for posting your issuse. 

Two things:
1. Post the output of `ip a` in your VM
2. Post the output of either `ipconfig` (Windows) or `ip a` (Linux) on your server that hosts Nextcloud (is that your laptop?)

**Comment by Verdomme** [comment]
Thanks for replying, 
I'm just a newbie, i'm glad I that I can find my way into the system. I've got Nextcloud VM running on my laptop indeed. It's an Apple, but that doesn't need to spoil the show. Here's the ifconfig as it's called in MacOSX:

[ifconfig.docx](https://github.com/nextcloud/vm/files/5257224/ifconfig.docx)

**Comment by Verdomme** [comment]
Srry, wrong button!

**Comment by Verdomme** [comment]
And the ip a output from VM: 
![ip a](https://user-images.githubusercontent.com/71660447/93809063-1bf5db00-fc4d-11ea-8a52-f8d6809483ea.jpg)

**Comment by enoch85** [comment]
You don't have an IP to the VM. 

You probably setup the network wrong in VirtualBox. If it's NAT, change to "Bridged mode".

This is not a bug, so I'd check https://help.nextcloud.com for further support.
