### ISSUE TITLE
Enable unattanded upgrades?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1495]
@enoch85 
I wonder what you think about unattended upgrades?
Would this feature make sense for the NcVM?
https://ostechnix.com/install-updates-security-patches-automatically-ubuntu/
https://ostechnix.com/how-to-disable-unattended-upgrades-on-ubuntu/

**Comment by enoch85** [comment]
No. it's just causing more issues than gain in my experience. I don't trust unattended upgrades.

**Comment by szaimen** [comment]
Okay, enabling this doesn't make sense then. 👍
