### ISSUE TITLE
Docker error on update.sh script

### ISSUE THREAD

**Issue by silenx** [nextcloud/vm#1497]
Hello,
i’m using NC 19.0.3 on ubuntu server 18.04

This is the output of docker ps -a
28245ad4d08c collabora/code:latest “/bin/sh -c 'bash st…” 8 weeks ago Up 34 minutes 192.168.99.5:9980->9980/tcp co
de
17baf414376b ark74/nc_fts:latest “/tini – /usr/local…” 2 months ago Up 34 minutes 0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp ft
s_esror
e2d62754b836 containrrr/watchtower:latest “/watchtower --clean…” 3 months ago Up 34 minutes 8080/tcp wa
tchtower

-->
## Steps to reproduce
1. Run update.sh script
2.
3.

## Actual behaviour
docker: Error response from daemon: Conflict. The container name “/watchtower” is already in use by container “e2d62754b83669e714bbb0b3d448adc978cb6a9687c75579dcc0513e
dea2287b”. You have to remove (or rename) that container to be able to reuse that name.
See ‘docker run --help’.
Collabora docker image just got updated!
Posting notification to users that are admins, this might take a while…
Posting ‘Docker image just got updated!’ to: B792C65F-960E-4F12-A752-DA5768194273
Posting ‘Docker image just got updated!’ to: ncadmin2
docker: Error response from daemon: Conflict. The container name “/watchtower” is already in use by container “e2d62754b83669e714bbb0b3d448adc978cb6a9687c75579dcc0513e
dea2287b”. You have to remove (or rename) that container to be able to reuse that name.
See ‘docker run --help’.
Full Text Search docker image just got updated!

Script finish his cycle without error.

## Server configuration

**Nextcloud server version: 19.0.3

**Server OS** Ubuntu Server 10.04.5 LTS

**How did you install the VM?** (Scripted install from master **OR** Released version)
Script from master

**Comment by enoch85** [comment]
Thanks for reporting this!

Do you have Bitwarden installed on your system?

**Comment by silenx** [comment]
> Thanks for reporting this!
> 
> Do you have Bitwarden installed on your system?

No, server is dedicated to nextcloud only

**Comment by Danteba** [comment]
Hello, I'm receiving the same error...

docker: Error response from daemon: Conflict. The container name "/watchtower" is already in use by container "1d594c866bf1386315ebeab3a5f07db4aa68d5b36af24e28898230056f96bf9a". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Collabora docker image just got updated!
Posting notification to users that are admins, this might take a while...
Posting 'Docker image just got updated!' to: dante
docker: Error response from daemon: Conflict. The container name "/watchtower" is already in use by container "1d594c866bf1386315ebeab3a5f07db4aa68d5b36af24e28898230056f96bf9a". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Full Text Search docker image just got updated!
Posting notification to users that are admins, this might take a while...
Posting 'Docker image just got updated!' to: dante

I'm using Nextcloud 19.0.3 on Ubuntu 20.04

**Comment by enoch85** [comment]
Hey guys, 

Can you please try to run the update script again? This issue should be solved now.

Please report back.

Thanks!

**Comment by silenx** [comment]
Docker error is go away, but every time i run update script i get the update notification:
Collabora docker image just got updated!
Posting notification to users that are admins, this might take a while...
Posting 'Docker image just got updated!' to: B792C65F-960E-4F12-A752-DA5768194273
Posting 'Docker image just got updated!' to: ncadmin2
time="2020-09-29T19:19:22Z" level=info msg="Running a one time update."
Full Text Search docker image just got updated!
Posting notification to users that are admins, this might take a while...
Posting 'Docker image just got updated!' to: B792C65F-960E-4F12-A752-DA5768194273
Posting 'Docker image just got updated!' to: ncadmin2

So .. i always get update notification ( cli and web gui ) even if there is no update

**Comment by szaimen** [comment]
This is a different issue but should be solved differently, imo.
@enoch85 I would suggest not sending a notification every time the script runs. Can we somehow check if the container actually got updated?

**Comment by Danteba** [comment]
In my case, I have to wait **several** minutes after every update, because I have more than 400 ldap users, and just one admin... ;-)

**Comment by szaimen** [comment]
> In my case, I have to wait **several** minutes after every update, because I have more than 400 ldap users, and just one admin... ;-)

One reason more to only send the notification if the docker container was actualy upgraded or to disable the notification for the docker container updates completely.

**Comment by szaimen** [comment]
@enoch85 What do you thinkg? ⤴

**Comment by Danteba** [comment]
The docker problems is resolved.

But I had to wait **an hour** for the process to finish... 

--------------
ncadmin@nextcloud:~ date
**Tue 29 Sep 2020 07:05:32 PM -03**
ncadmin@nextcloud:~ sudo bash /var/scripts/update.sh
[sudo] password for ncadmin:
Fetching latest packages with apt...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Trying to upgrade the Redis PECL extension...
Getting current PHP-version...
PHPVER=7.4
Updating channel "pecl.php.net"
Channel "pecl.php.net" is up to date
Nothing to upgrade
Trying to upgrade igbinary, smbclient, and APCu...
Nothing to upgrade
Nothing to upgrade
Nothing to upgrade
**time="2020-09-29T22:06:04Z" level=info msg="Running a one time update."**
Collabora docker image just got updated!
Posting notification to users that are admins, this might take a while...
Posting 'Docker image just got updated!' to: dante
**time="2020-09-29T22:28:32Z" level=info msg="Running a one time update."**
Full Text Search docker image just got updated!
Posting notification to users that are admins, this might take a while...
Posting 'Docker image just got updated!' to: dante
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Sourcing file '/etc/default/grub'
Sourcing file '/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.4.0-48-generic
Found initrd image: /boot/initrd.img-5.4.0-48-generic
Found linux image: /boot/vmlinuz-5.4.0-47-generic
Found initrd image: /boot/initrd.img-5.4.0-47-generic
done
Maintenance mode already disabled
Trying to automatically update all Nextcloud apps...
Your apps are already up to date!
Checking for new Nextcloud version...
You already run the latest version! (19.0.3)
ncadmin@nextcloud:~$ date
**Tue 29 Sep 2020 07:58:25 PM -03**

--------------

I saw that the following process was launched for every user:

`php /var/www/nextcloud/occ user:info john.smith`

**Comment by enoch85** [comment]
> @enoch85 What do you think? arrow_heading_up

I don't know if it possible to check if there was an update make or not.

Right now I don't have time to investigate either I'm afraid. The script works as intended for now, but I agree that it would be better if we somehow either:

1. Cache the result of admins
2. Only post the output if there actually was an upgrade.

@Danteba You should really consider getting yourself an enterprise license: https://shop.hanssonit.se/product/nextcloud-enterprise-license-50-users/

**Comment by silenx** [comment]
Only one question: is ok to have old watchtower container running?

**Comment by szaimen** [comment]
> Only one question: is ok to have old watchtower container running?

I am acutally not sure, @enoch85?

**Comment by enoch85** [comment]
> is ok to have old watchtower container running

The old implementation had watchtower run all the time for seamless upgrades of all docker containers. The reason why we changed the default behaviour was that Bitwarden couldn't be updated automatically. 

But I decided to keep watchtower running if Bitwarden wasn't installed in the new approach, to keep getting the benefits of the seamless updates.

So yes, it's totally safe to have it running in the background, that's what it's for. Removing it altogether and only run it once the update script is run would also be an option, but you would then loose automatic updates of your containers even when the update script isn't run.

**Comment by silenx** [comment]
Ok, for me issue can be closed.
@enoch85 and @szaimen  thank you for support

**Comment by szaimen** [comment]
If we leave watchtower running on instances that don't have bitwarden installed, maybe we shouldn't call the docker_update_specific functions since it should get updated automatically?
If yes, we should then also readd watchtower to run continuosly on those instances
