### ISSUE TITLE
ERROR 404 : Not Found

### ISSUE THREAD

**Issue by cketan** [nextcloud/vm#15]
![error 404](https://cloud.githubusercontent.com/assets/20305691/16714258/c7c2caec-46da-11e6-9e1b-8060a8adc28b.JPG)

While updating the VM 9.0.51 to 9.0.52 it is showing awaiting for response .. 404 not found

**Comment by enoch85** [comment]
Thank you for reporting this! This is a know issue and is already fixed in the new version: https://github.com/nextcloud/vm/commit/010a33ff9237fe8733e11a38ed1d73dd00ef4592

**Comment by cketan** [comment]
thanks Daniel :+1:
