### ISSUE TITLE
Collabora script finished successfully but getting cert error 

### ISSUE THREAD

**Issue by latebeat** [nextcloud/vm#151]
Hi,

I run the script and it finished successfully. Nextcloud is at **cloud**.mydomain.com and collabora at **office**.mydomain.com

Unfortunately, when I navigate to https://office.mydomain.com I still get the letsencrypt cert for **cloud**.mydomain.com instead of office so I'm not getting the green padlock and can't seem to edit documents. 

I downloaded the latest script, re-run but without any success. The correct certs seem to be in /etc/letsencrypt/live/office.mydomain.com/ so I'm not sure what I need to change for collabora to serve the correct TLS certs. 

Please help!

Thank you
Anestis

## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Server version:** (see your admin page)

**VM version**

**Updated from an older installed version or fresh install:**

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi @latebeat Thanks for your report!

Try change this. https://github.com/nextcloud/vm/pull/150/files#diff-0b1bdecaf3ba1d394a1db6ad83355188L183

Does it help?

**Comment by latebeat** [comment]
Ok so I was not able to re-run the script. For some reason if I rerun it fails at checking if NC is installed:

``Checking if Nextcloud is installed...

It seems like Nextcloud is not installed or that you don't use https on:
cloud.domain.com.
Please install Nextcloud and make sure your domain is reachable, or activate SSL
on your domain to be able to run this `script.`

Both false since, NC is working fine. 

However, I edited the /etc/apache2/sites-enabled/office.domain.com.conf directly and changed the VirtualHost to *:443 as you suggested and now office.domain.com works! 

Unfortunately, that didn't resolve the issue all the way as now I'm getting the following error message  (no cert error though any more):


> Well, this is embarrassing, we cannot connect to your document. Please try again.

**Comment by enoch85** [comment]
@latebeat Yeah, we just merged a new commit to fox those errors. Please run this code: https://github.com/nextcloud/vm/commit/ccbc8778f7c3edf86465d4e7a592e42a7b56d94d#diff-0b1bdecaf3ba1d394a1db6ad83355188R121
