### ISSUE TITLE
Block access from country by IP in Apache

### ISSUE THREAD

**Issue by XSR1** [nextcloud/vm#1519]
It would be nice if we could add Geoipblocking feature:
https://www.itsfullofstars.de/2017/07/block-access-from-country-by-ip-in-apache/

**Comment by szaimen** [comment]
I guess this is a better guide:
https://linuxconfig.org/redirect-or-block-traffic-based-on-geographical-location-apache-geoip-mod

**Comment by szaimen** [comment]
Here are the country codes:
https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes

**Comment by szaimen** [comment]
AF – Africa
AN – Antarctica
AS – Asia
EU – Europe
NA – North America
OC – Oceania
SA – South America
