### ISSUE TITLE
How to run script - collabora not running

### ISSUE THREAD

**Issue by Ark74** [nextcloud/vm#152]
Hi!,
I've been using the installation script and it always exits before running the collabora script.
My imagination is that i'm running it wrong.

As for now, i download the nextcloud_install_production.sh and let it run until completion, but as stated before, the installation finish without collabora (CODE) getting installed.
Maybe i have to clone the project then run nextcloud_install_production.sh
Otherwise i think i found an issue.

Thanks.

**Comment by Ark74** [comment]
Even though downloading the collabora.sh script and manually run it.
It completes the installation successfully and with latest kernel 4.8 :1st_place_medal:  #150

**Comment by enoch85** [comment]
The script checks 2 things before it continues.

1. If Nextcloud is installed and the domain has SSL (https)
2. If the subdomain exists.

If either one of them are false, the script will exit.

So, running the startup script and install collabora directly wont work if you haven't enabled SSL before, which is done later on in the startup script with Let's Encrypt. This means that you can't expect it to work on the first try. The correct procedure is:

1. Run the startup-script 
2. Don't run the Collabora installation (if you haven't enaböed SSL on your cloud domain before)
3. Finish the startup script and enable SSL
4. Reboot and run Collabora.

**Comment by Ark74** [comment]
>  1. Run the startup-script

This is run automatically after the installation script finishes. Everything fine.

>  2. Don't run the Collabora installation (if you haven't enaböed SSL on your cloud domain before)
>  3. Finish the startup script and enable SSL

AFAIK, the starup script asks to install some apps, Collabora among them, but it check for SSL as a requirement, so it installs SSL, but right after it installs SSL it reboots but it won't call the Collabora script as it does with the Startup script when the installation ends.

What i mean is:
Running the startup script is a requirement for the installation became completed.
Then, collabora (or any other app ) should be a requirement (if selected) for the startup script became completed.

`Install_script` -> _runs_ `Startup_script` **therefore** `Install_script` completed :ballot_box_with_check: 
`Startup_script` -> _selects_ `collabora.sh` **then** `Startup_script` -> _runs_ `SSL_script` **therefore** `Startup_script` completes :ballot_box_with_check: 

>  4. Reboot and run Collabora.

As the previous comment, maybe  
`SSL_script` -> should _run_ `collabora.sh` as `Install_script` called `Startup_script` automatically in order to finish. :heavy_check_mark: 

IMHO, `collabora.sh` should not be manually run if it was previously selected on the `startup_script` menu, maybe download the app script and set its execution at rc.local to be run at the next reboot when SSL finishes.

**Comment by enoch85** [comment]
As I see it there are two options.

1. Run the Let's Encrypt script before installing any apps
2. Don't require SSL on the cloud domain.

What do you think @nextcloud/vm?

**Comment by Ark74** [comment]
Good idea,
I would vote for the first option, since more than one app will require Nextcloud a secure connection, CODE docker included.

Let's hear other opinions on this.

**Comment by enoch85** [comment]
Merged a fix for this... We now run the SSL script before Collabora.
