### ISSUE TITLE
run apt upgrade at the beginning of the startup script?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1521]
Hey, I wonder if it would make sense to run `apt upgrade -y` at the beginning of the install script?

**Comment by enoch85** [comment]
Do you mean part one or two?

**Comment by szaimen** [comment]
> Do you mean part one or two?

part one

**Comment by enoch85** [comment]
No, I just removed that yesterday to keep the images smaller of the released version actually. https://github.com/nextcloud/vm/commit/fe5e86f92ddc978f80a7c6bb39e4c53549cc1361

Why would you like to add that?

**Comment by szaimen** [comment]
> Why would you like to add that?

I am under the impression that it works more stable and reliable if it runs an update at the beginning.
I think I know how to solve that.

**Comment by szaimen** [comment]
I changed my mind. This is not needed.
