### ISSUE TITLE
Use lvm snapshots as restore system for the update script?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1522]
Hey, using lvm snapshots for the update script would make the restoring much easier by simply running
```
lvconvert --merge /dev/ubuntu-vg/SnapshotName
reboot
```
Together with ZFS restore we could simplify and automate the process by a lot if an update fails. (obviously we couldn't get rid of backing up the data to the backup directory for old instances)

The only thing is that this would obviously only work for new instances and we would need to retain free space which, to reach the normal 40GB for the system drive, would mean, that we had to make the system drive e.g. double the size like 80GB and then have the normal capacity of 40GB for data. (this should be the default configuration that is made by the ubuntu server installer)

Here is a good source:
https://www.tecmint.com/take-snapshot-of-logical-volume-and-restore-in-lvm/

for later:
```
check_free_space() {
if vgs &>/dev/null
then
    FREE_SPACE=$(vgs | grep ubuntu-vg | awk '{print $7}' | grep g | grep -oP "^[0-9]+\.[0-9]" | sed 's|\.||')
fi
if [ -z "$FREE_SPACE" ]
then
    FREE_SPACE=0
fi
}
if [ "$FREE_SPACE" -ge 25 ]
then
    # TODO: check if a snapshot with the same name already exists. Exit if yes and suggest manually deleting or merging it.
    # TODO: create the snapshot
    # TODO: check if it gets created successfully
elif [ "$FREE_SPACE" -eq 0 ]
then
    # TODO: do the normal backup
else
   # TODO: report a fail
fi
```

**Comment by enoch85** [comment]
In that case we would only use 50% of the capacity of the disk, as that's the new default in Ubuntu.

That would mean 20 GB as default space for:
- DB
- Logs
- And eeeverything else.

When it comes to expanding LVM, should we script that and put it in server configuration instead? And if we do, then snapsots would stop functioning (as you say).

**Comment by enoch85** [comment]
I'm not sure we should increase storage to 80 GB.Have to think about that.

**Comment by szaimen** [comment]
If I think about it, 10GB of free space should already be plenty enough for snapshots. If we want to make it as small as possible, 1GB would most likely enough, too.

**Comment by szaimen** [comment]
I'll go with 2.5GB. It sounds like a good size, imo.
