### ISSUE TITLE
sudo bash /var/scripts/menu.ch stopped working

### ISSUE THREAD

**Issue by igrokit** [nextcloud/vm#1528]
-->
## Steps to reproduce
1. login as ncadmin
2. run 'sudo bash /var/scripts/menu.sh'

## Expected behaviour
Menu should come up

## Actual behaviour
Getting the following output:
---
ncadmin@apo:~$ sudo bash /var/scripts/menu.sh 
[sudo] password for ncadmin: 
Running the main menu script...
Testing if network is OK...
Waiting for network to restart...
Checking connection...
**{main_menu} failed to download. Please run: 'sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.sh|.php|.py' again.**
If you get this error when running the nextcloud-startup-script then just re-run it with:
'sudo bash /var/scripts/nextcloud-startup-script.sh' and all the scripts will be downloaded again
---

Following instructions:
sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.sh 
is downloading main_menu.sh to the local folder. What next?

Then trying the next suggestion:
ncadmin@apo:~$ sudo bash /var/scripts/nextcloud-startup-script.sh
bash: /var/scripts/nextcloud-startup-script.sh: No such file or directory

## Server configuration

**Nextcloud server version:** 19.0.1

**Server OS** (Ubuntu server is default)

**How did you install the VM?** Released version

## Network
**Do you use DHCP?**  No

**Is port 80 and/or 443 open?** Yes

#### Log file (/var/log/nextcloud/nextcloud.log)
Log does not contain anything related to this isue

**Comment by enoch85** [comment]
Hi,

Did you try again?

It works here.

**Comment by igrokit** [comment]
Unfortunately, still get the same error

Running with DEBUG=1 in menu.sh produces this:

```
ncadmin@apo:~$ sudo bash /var/scripts/menu.sh 
+ root_check
+ is_root
+ [[ 0 -ne 0 ]]
+ return 0
+ mkdir -p /var/scripts
+ print_text_in_color '\e[0;96m' 'Running the main menu script...'
+ printf '%b%s%b\n' '\e[0;96m' 'Running the main menu script...' '\e[0m'
Running the main menu script...
+ network_ok
+ version 18.04 20.04 20.04.6
+ local h t v
+ [[ 20.04 = \1\8\.\0\4 ]]
+ [[ 20.04 = \2\0\.\0\4\.\6 ]]
++ printf '%s\n' 18.04 20.04 20.04.6
++ sort -V
+ v='18.04
20.04
20.04.6'
++ head -n1
+ h=18.04
++ tail -n1
+ t=20.04.6
+ [[ 20.04 != \1\8\.\0\4 ]]
+ [[ 20.04 != \2\0\.\0\4\.\6 ]]
+ print_text_in_color '\e[0;96m' 'Testing if network is OK...'
+ printf '%b%s%b\n' '\e[0;96m' 'Testing if network is OK...' '\e[0m'
Testing if network is OK...
+ netplan apply
+ countdown 'Waiting for network to restart...' 3
+ print_text_in_color '\e[0;96m' 'Waiting for network to restart...'
+ printf '%b%s%b\n' '\e[0;96m' 'Waiting for network to restart...' '\e[0m'
Waiting for network to restart...
+ secs=3
+ '[' 3 -gt 0 ']'
+ echo -ne '3\033[0K\r'
+ sleep 1
+ : 3
+ '[' 2 -gt 0 ']'
+ echo -ne '2\033[0K\r'
+ sleep 1
+ : 2
+ '[' 1 -gt 0 ']'
+ echo -ne '1\033[0K\r'
+ sleep 1
+ : 1
+ '[' 0 -gt 0 ']'
+ site_200 github.com
+ print_text_in_color '\e[0;96m' 'Checking connection...'
+ printf '%b%s%b\n' '\e[0;96m' 'Checking connection...' '\e[0m'
Checking connection...
++ curl -LI github.com -o /dev/null -w '%{http_code}\n' -s
+ CURL_STATUS=200
+ [[ 200 = \2\0\0 ]]
+ return 0
+ run_script STATIC main_menu
+ rm -f /var/scripts/main_menu.sh /var/scripts/main_menu.php /var/scripts/main_menu.py
+ download_script STATIC main_menu
+ rm -f /var/scripts/main_menu.sh /var/scripts/main_menu.php /var/scripts/main_menu.py
+ curl_to_dir https://raw.githubusercontent.com/nextcloud/vm/master/static main_menu.sh /var/scripts
+ '[' '!' -d /var/scripts ']'
+ rm -f /var/scripts/main_menu.sh
+ curl -sfL https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.sh -o /var/scripts/main_menu.sh
+ curl_to_dir https://raw.githubusercontent.com/nextcloud/vm/master/static main_menu.php /var/scripts
+ '[' '!' -d /var/scripts ']'
+ rm -f /var/scripts/main_menu.php
+ curl -sfL https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.php -o /var/scripts/main_menu.php
+ curl_to_dir https://raw.githubusercontent.com/nextcloud/vm/master/static main_menu.py /var/scripts
+ '[' '!' -d /var/scripts ']'
+ rm -f /var/scripts/main_menu.py
+ curl -sfL https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.py -o /var/scripts/main_menu.py
+ print_text_in_color '\e[0;91m' '{main_menu} failed to download. Please run: '\''sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.sh|.php|.py'\'' again.'
+ printf '%b%s%b\n' '\e[0;91m' '{main_menu} failed to download. Please run: '\''sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.sh|.php|.py'\'' again.' '\e[0m'
{main_menu} failed to download. Please run: 'sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.sh|.php|.py' again.
+ print_text_in_color '\e[0;96m' 'If you get this error when running the nextcloud-startup-script then just re-run it with:'
+ printf '%b%s%b\n' '\e[0;96m' 'If you get this error when running the nextcloud-startup-script then just re-run it with:' '\e[0m'
If you get this error when running the nextcloud-startup-script then just re-run it with:
+ print_text_in_color '\e[0;96m' ''\''sudo bash /var/scripts/nextcloud-startup-script.sh'\'' and all the scripts will be downloaded again'
+ printf '%b%s%b\n' '\e[0;96m' ''\''sudo bash /var/scripts/nextcloud-startup-script.sh'\'' and all the scripts will be downloaded again' '\e[0m'
'sudo bash /var/scripts/nextcloud-startup-script.sh' and all the scripts will be downloaded again
+ exit 1
ncadmin@apo:~$ 

```

```
ncadmin@apo:~$ sudo ls -lsa /var/scripts/
total 40
4 drwxr-xr-x  2 root    root    4096 Okt  5 18:46 .
4 drwxr-xr-x 18 root    root    4096 Aug  4 18:18 ..
4 -rw-r--r--  1 root    root      54 Jun  4 01:59 history.sh
4 -rwxr-xr-x  1 root    root     411 Jul 13 17:49 letsencryptrenew.sh
4 -rw-r--r--  1 root    root    1912 Jul 15 16:03 locate_mirror.sh
4 -rw-r--r--  1 root    root     515 Okt  5 18:46 menu.sh
4 -rwxr-xr-x  1 ncadmin ncadmin  448 Jul 13 17:44 nextcloud.sh
4 -rwxr-xr-x  1 root    root    2297 Jul 13 17:44 setup_secure_permissions_nextcloud.sh
4 -rwxr-xr-x  1 root    root    3132 Okt  3 18:59 updatenotification.sh
4 -rwxr-xr-x  1 root    root     661 Jul 13 17:44 update.sh
```

**Comment by enoch85** [comment]
I have no idea. Your internet seems OK, so it should download properly.

Have you tested the suggested command? Also, have you tried downloading it directly from Github?

**Comment by igrokit** [comment]
https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.py
this one gets a "404: Not Found"

**Comment by igrokit** [comment]
I have tested the suggested commands, yes.. I mentioned this in the first message.

Following instructions:
sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/main_menu.sh
is downloading main_menu.sh to the local folder. What next?

Then trying the next suggestion:
ncadmin@apo:~$ sudo bash /var/scripts/nextcloud-startup-script.sh
bash: /var/scripts/nextcloud-startup-script.sh: No such file or directory

**Comment by enoch85** [comment]
I've tested:

1. Run `menu.sh` as root
2. Run `menu.sh` as ncadmin (regular user)
3. Deleted both `fetch_lib` and `lib` from /var/scripts

All of the above works, so there's nothing wrong script wise.

The startup script should only be run the first time,not when setup is already done.

**Comment by igrokit** [comment]
thanks. I will order some support from you.

**Comment by enoch85** [comment]
Just to make sure it doesn't happen again: https://github.com/nextcloud/vm/commit/ab5ca3bceee9b60716c8d4d812c660c728bef7ed
