### ISSUE TITLE
Report 0 byte files

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1534]
```
filesystems[0]="$NCDATA"
cd "$NCDATA"

emSub="Warning: Nextcloud Contains 0 Byte Files"

for fs in "${filesystems[@]}"; do

        while read -d '' -r; do
                arr+=( "$REPLY\n" )
                done < <(find $fs -size 0 -print0)

done

if [[ ! -z ${arr[@]} ]]; then
        send_mail "emSub" "${arr[@]}"
fi
```

Credits to @Wdavery

**Comment by enoch85** [comment]
Maybe add a function to check all users in `NCDATA` as well?

If we're going to scan the whole `NCDATA` folder, it might take time!

**Comment by szaimen** [comment]
> send_mail "emSub" "${arr[@]}"

I guess this should be
`send_mail "$emSub" "${arr[@]}"`

**Comment by szaimen** [comment]
Is this still needed?

**Comment by enoch85** [comment]
It's a feature to check if Nextcloud produces 0-byte files, which actually happens from time to time with the desktop client. You should probably check for your self. 

We could add it in one of the menus, with a big warning that it will take time, especially if the data folder is large.

**Comment by szaimen** [comment]
So this is not meant to run continuosly in the bacground?

**Comment by enoch85** [comment]
Correct. :+1:

**Comment by enoch85** [comment]
This is the issue: https://github.com/nextcloud/server/issues/3056

**Comment by szaimen** [comment]
I've just checked my personal folder via SMB and it seems like at least my account is not affected...

**Comment by enoch85** [comment]
> my personal folder

Do you mean your complete data mount?

> via SMB

Do you use SMB as the main data drive mounted in `/etc/fstab`?

**Comment by szaimen** [comment]
> > my personal folder
> 
> Do you mean your complete data mount?

Yes

> > via SMB
> 
> Do you use SMB as the main data drive mounted in `/etc/fstab`?

All my data is on an external BTRFS drive that is encrypted with Veracrypt. Every user has a personal folder on this drive.
I have created a SMB-share for each personal folder on this drive. The same directory also gets mounted to Nextcloud using the local external storage feature. This way I can access the same files via Nextcloud and SMB.
Here is a bit more indepth explation on this: https://szaimen.github.io/Nextcloud-NAS-Guide/docs/create-shares

**Comment by enoch85** [comment]
Most of the reporters in that issue are saying that it's due to the Desktop client, or Android client. 

Android client when internet is laggy, and Desktop client for the same reason.

Are you using any of those?

**Comment by szaimen** [comment]
Yes, I am using both: Desktop and Android client but I guess my internet is as stable as it gets because I am usually at home and since I am using a local DNS server, my Nextcloud is not even bound to a working internet connection. 😅
(Only the local network must work in my case which it does pretty well)
