### ISSUE TITLE
[Feature Request] Add bashtop as an alternative to netdata

### ISSUE THREAD

**Issue by horvan** [nextcloud/vm#1537]
That's not an Issue at all.

I just like to ask if you guys can add bashtop from https://github.com/aristocratos/bashtop as an alternative to netdata to this brilliant script collection.

It needs less ressources and shows allmost al relevont data from netdata right in the terminal. 
![bashtop](https://user-images.githubusercontent.com/5676367/95426320-fbfd3180-0945-11eb-8807-892d00247688.png)

**Comment by enoch85** [comment]
It's already in master actually ;)

https://github.com/nextcloud/vm/blob/master/menu/additional_apps.sh#L71-L93
