### ISSUE TITLE
Enable TLS 1.3 in Apache 

### ISSUE THREAD

**Issue by XSR1** [nextcloud/vm#1540]
Enable latest TLS protocol 1.3?

https://www.tecmint.com/enable-tls-in-apache-and-nginx/

**Comment by enoch85** [comment]
TLS 1.3 isn't supported in the current Ubuntu release (20.04) afaik due to that Apache2 is too old.

But, I'm not 100% sure.

**Comment by protvis74** [comment]
I think TLS 1.3 is supported in the current Ubuntu release (20.04). According to the package list apache2 2.4.41 is included.
see here.
https://packages.ubuntu.com/search?suite=focal&arch=amd64&searchon=names&keywords=apache2

The requirement for enabling TLS 1.3 is Apache version 2.4.37 or greater like mentioned in the post from XSR1 above.

So it should be no problem to enable TLS 1.3.

**Comment by enoch85** [comment]
Ok, will have a look.

Thanks!
