### ISSUE TITLE
deSEC ddclient

### ISSUE THREAD

**Issue by XSR1** [nextcloud/vm#1541]
Please add support deSEC. It's free DNS hosting service. 

https://desec.io/

**Comment by enoch85** [comment]
@szaimen Do you have an idea?

**Comment by szaimen** [comment]
If I understand it correctly the guy wants to have ddclient support for deSEC (as the title says)
Here are the docs for that: https://desec.readthedocs.io/en/latest/dyndns/configure.html#option-2-use-ddclient

**Comment by XSR1** [comment]
Settings for IPv4:
`# Default system settings
use=if, if=ens32
use=cmd, cmd='curl https://checkipv4.dedyn.io/'

# DDNS-service specific setting
protocol=dyndns2
server=update.dedyn.io
ssl=yes

# user specific setting
login=[domain]
password='[TOKEN]'

# Hostname follows:
[domain]
`
Settings for IPv6:
`# Default system settings
usev6=if, if=ens32
use=cmd, cmd='curl https://checkipv6.dedyn.io/'

# DDNS-service specific setting
protocol=dyndns2
server=update6.dedyn.io
ssl=yes

# user specific setting
login=[domain]
password='[TOKEN]'

# Hostname follows:
[domain]
`

**Comment by XSR1** [comment]
# Hostname follows:
[domain]

Settings for IPv6:
# Default system settings
usev6=if, if=ens32
use=cmd, cmd='curl https://checkipv6.dedyn.io/'

# DDNS-service specific setting
protocol=dyndns2
server=update6.dedyn.io
ssl=yes

# user specific setting
login=[domain]
password='[TOKEN]'

# Hostname follows:
[domain]


Tested And working

**Comment by XSR1** [comment]
My Mice is dying..
