### ISSUE TITLE
[add to docs] VMware Performance Comparison SCSI Controller and NVMe Controller

### ISSUE THREAD

**Issue by XSR1** [nextcloud/vm#1543]
I think (and I have tested) VMware Paravirtual and NVMe Controller offers creater perfomance (IOPS) when using SSD drive.

https://www.thomas-krenn.com/en/wiki/VMware_Performance_Comparison_SCSI_Controller_and_NVMe_Controller

**Comment by XSR1** [comment]
I think you are doing amazing job with this project! I really liked!
Speed with vm:s is always important for me and yes I know there is setting for manual selection for it..

**Comment by enoch85** [comment]
Thanks!

How would you suggest we change this? In the released OVAs?

**Comment by XSR1** [comment]
Yes in OVAs, but below settings I think this is good for SSD and not hard drive. Maybe SSD Edition?

https://ibb.co/P5jrfH5
https://ibb.co/bJKwkbx

And when install asks about disk setup:
Select: 2 Disks Manual: `nvme0n2`

**Comment by enoch85** [comment]
@XSR1 So we should expect that everyone using the VM puts it on SSD?

**Comment by szaimen** [comment]
@XSR1 Does this have performance- or other disadvantages when the VM is stored on a HDD?

**Comment by XSR1** [comment]
The main benefit of NVMe interface over SCSI is that it reduces the amount of overhead, and so consumes fewer CPU cycles. Also, there is a reduction of IO latency for your VMs. So it offers better Performance (at least with Windows).

So if you have SSD you should use NVMe controller. With Hardrive drive you should use recommended SCSI controller.

There could be diffrent ova if there is enough demand? For example "Nextcloud_VM_SSD.ova"? For selling product, like [here](https://shop.hanssonit.se/product-category/virtual-machine/nextcloud-vm/): ?

**Comment by szaimen** [comment]
Hi @XSR1, thanks for answering.
Concerning offering two different versions each for hdds and ssds, I guess @enoch85 has to evaluate if it is worth the additional effort.

**Comment by enoch85** [comment]
> Concerning offering two different versions each for hdds and ssds, I guess @enoch85 has to evaluate if it is worth the additional effort.

Sorry, but it's already much to maintain, so I won't do this. You are free to edit the VM configuration as you like, but the default will always be legacy to ensure that everyone gets a smooth ride. If you want to tweak it, sure, but that's nothing we'll offer as a default setup - then we would have to offer like 20 different default setups, because everyone wants different defaults.

This is something for the docs though, so I'll keep it open.

**Comment by tyleroconnell** [comment]
Given the docs are on docs.hanssonit.se, is this something that only @enoch85 can complete? Would you be open to moving the docs to the Wiki section to make this self-contained and easier for others to contribute to?

**Comment by enoch85** [comment]
@tyleroconnell I've been thinking of moving the docs to Github, but I'm not 100% sure yet.

I'll come back to you on that one.

**Comment by enoch85** [comment]
@tyleroconnell I've been thinking and if we would decide to move to Github, then all the links posted everywhere would break. 

Of course we could redirect the traffic, but it seems cumbersome in relation to that the documentation doesn't updates that frequently.

I could invite you to the current docs if you'd like though?

**Comment by enoch85** [comment]
This is now in the docs: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=W7DvK-PiqQz3_Mr3
