### ISSUE TITLE
nextcloud_install_production.sh seems to not work as it did before

### ISSUE THREAD

**Issue by khalsajing** [nextcloud/vm#1548]
## Steps to reproduce
1. Downloaded nextcloud_install_production.sh from github.
2. chmod a+x to make it executable.
3. sudo bash ./nextcloud_install_production.sh
4. This script was working okay until the latest 'change wording'.

## Expected behaviour
It should install nextcloud (latest version).

## Actual behaviour
$ sudo bash ./nextcloud_install_production.sh
[sudo] password for sistum:
curl OK
Running in normal mode...
lshw OK
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  net-tools
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 196 kB of archives.
After this operation, 864 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/main amd64 net-tools amd64 1.60+git20180626.aebd88e-1ubuntu1 [196 kB]
Fetched 196 kB in 0s (531 kB/s)
Selecting previously unselected package net-tools.
(Reading database ... 71105 files and directories currently installed.)
Preparing to unpack .../net-tools_1.60+git20180626.aebd88e-1ubuntu1_amd64.deb ...
Unpacking net-tools (1.60+git20180626.aebd88e-1ubuntu1) ...
Setting up net-tools (1.60+git20180626.aebd88e-1ubuntu1) ...
Processing triggers for man-db (2.9.1-1) ...
whiptail OK
RAM for Nextcloud OK! (5.71 GB)
CPU for Nextcloud OK! (3)
$

## Server configuration
Nextcloud did not get installed; so no server configuration available.

**Server OS** (Ubuntu server is default)
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install from master - nextcloud_install_production.sh

## Network
**Do you use DHCP?**
No. Static IP. SSH works fine.

**Is port 80 and/or 443 open?**
Confirmed. Yes.

## Logs / Screenshots
 n/a

#### Log file (/var/log/nextcloud/nextcloud.log)
n/a

Insert your nextcloud.log file here
n/a

#### Installation log (command output)
n/a

Insert the CLI output here
n/a

#### Screenshoots
n/a

**Comment by enoch85** [comment]
We have a new switch for silent installations: `--provisioning`

Please consider to donate or [sponsor](https://github.com/sponsors/enoch85) this project if you use it heavily.

Thanks!

**Comment by DalenW** [comment]
Can confirm this issue. I run the script and it does nothing... Fresh install of Ubuntu Server 20, all packages updated before running the script. Here's what was outputted:

> dalen@server~$ sudo bash nextcloud.sh
> curl OK
> Running in normal mode...
> lshw OK
> net-tools OK
> whiptail OK
> RAM for Nextcloud OK! (7.27 GB)
> CPU for Nextcloud OK! (4)
> dalen@server~$

**Comment by szaimen** [comment]
@DalenW @khalsajing
Could you please run the script with `bash -x nextcloud_install_production.sh` and post the output here? Thanks!

**Comment by DalenW** [comment]
@szaimen Here's that output you wanted. Just in case it helps.

https://pastebin.com/Yzq9VjCp

**Comment by khalsajing** [comment]
Confirmed that the output of 'bash -x nextcloud_install_production.sh
 is the same as reported by @szaimen in https://pastebin.com/Yzq9VjCp

**Comment by khalsajing** [comment]
Sorry. Closed by mistake. Reopened.

**Comment by jndeverteuil** [comment]
> @enoch85 I've found the bug:
> This exit is outside of the condition and gets called everytime at the end of download_script:
> 
> https://github.com/nextcloud/vm/blob/0747a64bcd101297d4f86b907dd5d353f093324e/lib.sh#L1037

I can confirm that using the commit 209497cb6afa43daa2275f6843369a979bc645e8 worked for me, thanks !

**Comment by khalsajing** [comment]
@DalenW. Confirming that the output posted by @szaimen in https://pastebin.com/Yzq9VjCp is identical to mine.

**Comment by enoch85** [comment]
Thanks for reporting everyone, this is now fixed.

Please confirm.

**Comment by DalenW** [comment]
@enoch85 It's working now, thanks.

**Comment by khalsajing** [comment]
Working. Thank You.
