### ISSUE TITLE
Follow up to geoblock

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1552]
Follow up to #1551 

Implement a mechanism to update the database.

Maybe host the Maxmind country files here on github?

https://www.miyuru.lk/geoiplegacy

**Comment by enoch85** [comment]
PR is now merged.

**Comment by szaimen** [comment]
`curl -s https://github.com/nextcloud/vm/tree/master/addons | grep -oP '[a-z0-9_-]+\.sh'`

**Comment by enoch85** [comment]
I can also add that the current release doesn't run GeoBlock even if chosen.

**Comment by szaimen** [comment]
> I can also add that the current release doesn't run GeoBlock even if chosen.

Thanks for.reporting. it seems like i've forgotten one star 😅
https://github.com/nextcloud/vm/blob/6939fea92c6123bc51fee063660e40462c88e2e1/menu/server_configuration.sh#L88

**Comment by szaimen** [comment]
> I can also add that the current release doesn't run GeoBlock even if chosen.

This will be fixed with #1559

**Comment by szaimen** [comment]
TODO:
fix IPv4_name IPv4 name
fix IPv6_name IPv6 name
