### ISSUE TITLE
DHCP Network check fails, curl didn't produce 200 status

### ISSUE THREAD

**Issue by GogoAkira** [nextcloud/vm#1553]
Successfully installed Nextcloud VM version 20 from `https://download.nextcloud.com/vm/Nextcloud-VM.ova` by going into `/var/scripts` and running the static ip script beforehand, this is awesome :D thanks guys BUT :D see below...

VM ova file is imported into XCP-NG, the VM from hanssonit.se failed to import by the way.

I don't code so anyone who stops by here please do help with explaining scripting fundamentals to me :) if you have nothing better to do.

Is it not supposed to work on dhcp anyway? 

Running the script regularly as soon as I log in it says `curl didn't produce 200 status` and then it continues and installs some things but it breaks again after it installs Nextcloud 20 and the script stops.

Screenshots https://imgur.com/a/GPJxivK

 `(/var/log/nextcloud/nextcloud.log)` is non existent, no installation log either

dpgk log just to show stuff did install https://0bin.net/paste/sg3+vk8V#22sbNzMgepdHt0f9WryhZI2QpKrxeMWNEtIK3wX9juB
There are other logs but they didn't look relevant.

...... so anyway if I edit line 78 in `/var/scripts/nextcloud_install_production.sh` file `CURL_STATUS="$(curl -sSL -w "%{http_code}" "${1}" | tail -1)"` to `CURL_STATUS="$(curl -sSL -w "%{http_code}" github.com | tail -1)"` I can run sudo ./nextcloud_install_production.sh and I don't get the immediate curl didn't return 200 status, but I still get it after Nextcloud 20 installs and network check runs again. If after editing this line I log out and run whatever runs first it still shows the initial curl didn't return 200 status and continues, somewhere along these lines the static ip script kicked off which is what worked by accident for me :) as I broke it a little and it said script couldn't get a dhcp address ... 

What does ${1} point to, does it point to anything or what is it :)  in the context up there.? Why would curl not return error on immediate start when changing this and running the script directly.  To me it kind of seems that curl from here doesn't know which url to test unless this whole piece of code is ran and github.com comes after it just like above the code on line 68     `sleep 3 && site_200 github.com` does this run the site_200 code plus the url? 

So anyway for now I just have to run the static ip scrip before and everything works fine, can not resume script after it already installed postgress it wants a clean VM, after I tried running with static ip after network fails. Next is to learn more about scripting and syntax :)

**Comment by enoch85** [comment]
A lot of text here, but basically; the verbose message `curl didn't produce 200 status` is just there to let you know what the site in question can't be reached.

You are offered to run the static IP script if DHCP fails, just hold on and you'll see. :)

I hop that answers your question. :+1:
