### ISSUE TITLE
After the installation of f2b initiates.

### ISSUE THREAD

**Issue by EasyCompZLD** [nextcloud/vm#1556]
![Schermafbeelding 2020-10-14 om 05 04 52](https://user-images.githubusercontent.com/67462665/95938824-f89cf680-0dda-11eb-8e30-42aef1f2f763.png)

Got nothing more to say

![loadcat](https://user-images.githubusercontent.com/67462665/95938839-0783a900-0ddb-11eb-8660-f92a5ef8bdb2.gif)

**Comment by szaimen** [comment]
@EasyCompZLD Please try again. This time it should work.

**Comment by EasyCompZLD** [comment]
It's updated?

**Comment by szaimen** [comment]
> It's updated?

Yes it is.

**Comment by EasyCompZLD** [comment]
Oké I'll try it later. How fast can you respond? ;-p time now 13:01 UTC +1 ams
