### ISSUE TITLE
Impossible to use because all ISP in the country blocks all ports less than 1000

### ISSUE THREAD

**Issue by baditaflorin** [nextcloud/vm#1562]
## Steps to reproduce
1. Try to follow this https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6-83ePiqQz3_MrT/publish-your-server-online
2. All ISP in the country will block every port smaller than 1000
3. You buy this but cannot use from home https://shop.hanssonit.se/product/nextcloud-home-sme-server-4tb-2/

## Expected behaviour
Tell us what should happen
Not sure, maybe It can be done with duckdns or another dynamic IP service, but I did not see any documentation for this. 
There was something in the initial install, that did not work and now I cannot access that setting. 

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)
Latest version. 
**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
nextcloud-home-sme-server

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**
Cannot open port 80/443 to the world

#### Log file (/var/log/nextcloud/nextcloud.log)
```
-rw-r----- 1 www-data www-data     0 Oct 13 17:29 nextcloud.log ```

#### Installation log (command output)
```
I was using the keyboard and mouse from the installation so I could not copy```

**Comment by szaimen** [comment]
@enoch85 I guess this is your turn... ⬆️

**Comment by enoch85** [comment]
Solution 1: Buy a certificate and implement it in your Apache configuration. Then you can choose whichever port you want. Let's Encrypt is bound by 443 and 80.
Solution 2: Change ISP. Any ISP that doesn't allow freedom on the internet is a bad ISP IMHO.
Solution 3: Use the DNS option with Let's Encrypt, and `#` out the port checks. Then change the ports in the Apache config.

All setup scripts except the first one can be reached by :`sudo bash /var/scripts/menu.sh`
