### ISSUE TITLE
SMTP Relay with msmtp does not work

### ISSUE THREAD

**Issue by baditaflorin** [nextcloud/vm#1563]
## Steps to reproduce
1. Try to use google documentation https://support.google.com/a/answer/176600?hl=en for 
```
SMTP Relay URL=smtp-relay.gmail.com    
   │ Encryption=NO-ENCRYPTION       
         │ SMTP Port=25           
   │ SMTP Username=user@domain.com    
  │ SMTP Password=****************                                                            
Recipient=myemailthatwillgettheemail@gmail.com   
                 ```                                                             
3.

## Expected behaviour
Tell us what should happen
Allow you to set SMTP and receive alerts, emails. 

## Actual behaviour
Tell us what happens instead
```
root@nextcloud:~# cat /var/log/msmtp
mail: /usr/bin/msmtp -t: No such file or directory
Can't send mail: sendmail process failed with error code 1
```
## Server configuration

**Nextcloud server version:** (see your admin page)
latest
**Server OS** (Ubuntu server is default)
latest
**How did you install the VM?** (Scripted install from master **OR** Released version)
https://shop.hanssonit.se/product/nextcloud-home-sme-server-4tb-2/
## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**
Cannot open port 80 or 443, ISP blocks all ports under 1000
 
#### Log file (/var/log/nextcloud/nextcloud.log)
```
empty file```

#### Installation log (command output)
```
```

#### Screenshoots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by szaimen** [comment]
@baditaflorin have you used an app password for that or just your regular password?
https://support.google.com/accounts/answer/185833?hl=en

**Comment by baditaflorin** [comment]
I tried simple user/pass with an account that I created in google suite for our domain.

**Comment by szaimen** [comment]
Okay then please try again with an app password for that account.

Also please test if the `Use the Gmail SMTP server` method works for you

**Comment by szaimen** [comment]
This is what I would suggest you should try:
![Screenshot_20201015-030230_Brave](https://user-images.githubusercontent.com/42591237/96061346-4412db80-0e93-11eb-9a79-e28d4330aa13.jpg)

**Comment by szaimen** [comment]
Please report if https://github.com/nextcloud/vm/issues/1563#issuecomment-708809167 works for you, thanks!

**Comment by baditaflorin** [comment]
Same, getting error code 1 and exits. And the log does not provide anything useful. 
What can I do to produce a more verbose response?
Or in what other logs could I find more information...

```
dclinet-configuration.sh  fetch_lib.sh      lib.sh	 nextcloud-startup-script.sh  setup_secure_permissions_nextcloud.sh  updatenotification.sh
ncadmin@nextcloud:/var/scripts$ sudo bash menu.sh
[sudo] password for ncadmin:
Running the main menu script...
Testing if network is OK...
Waiting for network to restart...
Checking connection...
Downloading the Server Configuration Menu...
Downloading the SMTP Mail script...
Installing SMTP Relay with msmtp...
dpkg-query: no packages found matching msmtp
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  ttf-dejavu-core
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libgsasl7 libntlm0
Suggested packages:
  msmtp-mta
The following NEW packages will be installed:
  libgsasl7 libntlm0 msmtp
0 upgraded, 3 newly installed, 0 to remove and 22 not upgraded.
Need to get 264 kB of archives.
After this operation, 1260 kB of additional disk space will be used.
Get:1 http://mirrors.rit.edu/ubuntu focal/universe amd64 libntlm0 amd64 1.5-2 [14.1 kB]
Get:2 http://mirrors.rit.edu/ubuntu focal/universe amd64 libgsasl7 amd64 1.8.1-1 [114 kB]
Get:3 http://mirrors.rit.edu/ubuntu focal/universe amd64 msmtp amd64 1.8.6-1 [136 kB]
Fetched 264 kB in 1s (218 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libntlm0:amd64.
(Reading database ... 189070 files and directories currently installed.)
Preparing to unpack .../libntlm0_1.5-2_amd64.deb ...
Unpacking libntlm0:amd64 (1.5-2) ...
Selecting previously unselected package libgsasl7:amd64.
Preparing to unpack .../libgsasl7_1.8.1-1_amd64.deb ...
Unpacking libgsasl7:amd64 (1.8.1-1) ...
Selecting previously unselected package msmtp.
Preparing to unpack .../msmtp_1.8.6-1_amd64.deb ...
Unpacking msmtp (1.8.6-1) ...
Setting up libntlm0:amd64 (1.5-2) ...
Setting up libgsasl7:amd64 (1.8.1-1) ...
Setting up msmtp (1.8.6-1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
```





```
ed to get 264 kB of archives.
After this operation, 1260 kB of additional disk space will be used.
Get:1 http://mirrors.rit.edu/ubuntu focal/universe amd64 libntlm0 amd64 1.5-2 [14.1 kB]
Get:2 http://mirrors.rit.edu/ubuntu focal/universe amd64 libgsasl7 amd64 1.8.1-1 [114 kB]
Get:3 http://mirrors.rit.edu/ubuntu focal/universe amd64 msmtp amd64 1.8.6-1 [136 kB]
Fetched 264 kB in 1s (218 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libntlm0:amd64.
(Reading database ... 189070 files and directories currently installed.)
Preparing to unpack .../libntlm0_1.5-2_amd64.deb ...
Unpacking libntlm0:amd64 (1.5-2) ...
Selecting previously unselected package libgsasl7:amd64.
Preparing to unpack .../libgsasl7_1.8.1-1_amd64.deb ...
Unpacking libgsasl7:amd64 (1.8.1-1) ...
Selecting previously unselected package msmtp.
Preparing to unpack .../msmtp_1.8.6-1_amd64.deb ...
Unpacking msmtp (1.8.6-1) ...
Setting up libntlm0:amd64 (1.5-2) ...
Setting up libgsasl7:amd64 (1.8.1-1) ...
Setting up msmtp (1.8.6-1) ...
Unpacking msmtp-mta (1.8.6-1) ...
Setting up msmtp-mta (1.8.6-1) ...
msmtpd.service is a disabled or a static unit, not starting it.
Processing triggers for systemd (245.4-4ubuntu3.2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  ttf-dejavu-core
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libkyotocabinet16v5 libmailutils6 libmysqlclient21 mailutils-common mysql-common
Suggested packages:
  mailutils-mh mailutils-doc
The following NEW packages will be installed:
  libkyotocabinet16v5 libmailutils6 libmysqlclient21 mailutils mailutils-common mysql-common
0 upgraded, 6 newly installed, 0 to remove and 22 not upgraded.
Need to get 2394 kB of archives.
After this operation, 12.8 MB of additional disk space will be used.
Get:1 http://mirrors.rit.edu/ubuntu focal/universe amd64 libkyotocabinet16v5 amd64 1.2.76-4.2build1 [318 kB]
Get:2 http://mirrors.rit.edu/ubuntu focal/universe amd64 mailutils-common all 1:3.7-2.1 [272 kB]
Get:3 http://mirrors.rit.edu/ubuntu focal/main amd64 mysql-common all 5.8+1.0.5ubuntu2 [7496 B]
Get:4 http://mirrors.rit.edu/ubuntu focal-updates/main amd64 libmysqlclient21 amd64 8.0.21-0ubuntu0.20.04.4 [1222 kB]
Get:5 http://mirrors.rit.edu/ubuntu focal/universe amd64 libmailutils6 amd64 1:3.7-2.1 [437 kB]
Get:6 http://mirrors.rit.edu/ubuntu focal/universe amd64 mailutils amd64 1:3.7-2.1 [138 kB]
Fetched 2394 kB in 2s (1408 kB/s)
Selecting previously unselected package libkyotocabinet16v5:amd64.
(Reading database ... 189010 files and directories currently installed.)
Preparing to unpack .../0-libkyotocabinet16v5_1.2.76-4.2build1_amd64.deb ...
Unpacking libkyotocabinet16v5:amd64 (1.2.76-4.2build1) ...
Selecting previously unselected package mailutils-common.
Preparing to unpack .../1-mailutils-common_1%3a3.7-2.1_all.deb ...
Unpacking mailutils-common (1:3.7-2.1) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../2-mysql-common_5.8+1.0.5ubuntu2_all.deb ...
Unpacking mysql-common (5.8+1.0.5ubuntu2) ...
Selecting previously unselected package libmysqlclient21:amd64.
Preparing to unpack .../3-libmysqlclient21_8.0.21-0ubuntu0.20.04.4_amd64.deb ...
Unpacking libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.4) ...
Selecting previously unselected package libmailutils6:amd64.
Preparing to unpack .../4-libmailutils6_1%3a3.7-2.1_amd64.deb ...
Unpacking libmailutils6:amd64 (1:3.7-2.1) ...
Selecting previously unselected package mailutils.
Preparing to unpack .../5-mailutils_1%3a3.7-2.1_amd64.deb ...
Unpacking mailutils (1:3.7-2.1) ...
Setting up mysql-common (5.8+1.0.5ubuntu2) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Setting up libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.4) ...
Setting up libkyotocabinet16v5:amd64 (1.2.76-4.2build1) ...
Setting up mailutils-common (1:3.7-2.1) ...
Setting up libmailutils6:amd64 (1:3.7-2.1) ...
Setting up mailutils (1:3.7-2.1) ...
update-alternatives: using /usr/bin/frm.mailutils to provide /usr/bin/frm (frm) in auto mode
update-alternatives: using /usr/bin/from.mailutils to provide /usr/bin/from (from) in auto mode
update-alternatives: using /usr/bin/messages.mailutils to provide /usr/bin/messages (messages) in auto mode
update-alternatives: using /usr/bin/movemail.mailutils to provide /usr/bin/movemail (movemail) in auto mode
update-alternatives: using /usr/bin/readmsg.mailutils to provide /usr/bin/readmsg (readmsg) in auto mode
update-alternatives: using /usr/bin/dotlock.mailutils to provide /usr/bin/dotlock (dotlock) in auto mode
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  liblockfile-bin liblockfile1 ttf-dejavu-core
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  bsd-mailx* msmtp* msmtp-mta*
0 upgraded, 0 newly installed, 3 to remove and 22 not upgraded.
After this operation, 702 kB disk space will be freed.
(Reading database ... 189116 files and directories currently installed.)
Removing bsd-mailx (8.1.2-0.20180807cvs-1) ...
update-alternatives: using /usr/bin/mail.mailutils to provide /usr/bin/mailx (mailx) in auto mode
Removing msmtp-mta (1.8.6-1) ...
Removing msmtp (1.8.6-1) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for man-db (2.9.1-1) ...
(Reading database ... 189058 files and directories currently installed.)
Purging configuration files for msmtp (1.8.6-1) ...
Purging configuration files for msmtp-mta (1.8.6-1) ...
Purging configuration files for bsd-mailx (8.1.2-0.20180807cvs-1) ...
Processing triggers for systemd (245.4-4ubuntu3.2) ...
Reading package lists... Done
Building dependency tree
  bsd-mailx postfix
Suggested packages:
  procmail postfix-mysql postfix-pgsql postfix-ldap postfix-pcre postfix-lmdb postfix-sqlite sasl2-bin | dovecot-common resolvconf postfix-cdb postfix-doc
The following packages will be REMOVED:
  mailutils*
The following NEW packages will be installed:
  bsd-mailx postfix
0 upgraded, 2 newly installed, 1 to remove and 22 not upgraded.
Need to get 0 B/1265 kB of archives.
After this operation, 4089 kB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package postfix.
(Reading database ... 189055 files and directories currently installed.)
Preparing to unpack .../postfix_3.4.13-0ubuntu1_amd64.deb ...
Unpacking postfix (3.4.13-0ubuntu1) ...
dpkg: mailutils: dependency problems, but removing anyway as you requested:
 libapache2-mod-evasive depends on bsd-mailx | mailx; however:
  Package bsd-mailx is not installed.
  Package mailx is not installed.
  Package mailutils which provides mailx is to be removed.

(Reading database ... 189226 files and directories currently installed.)
Removing mailutils (1:3.7-2.1) ...
update-alternatives: using /usr/bin/bsd-from to provide /usr/bin/from (from) in auto mode
Selecting previously unselected package bsd-mailx.
(Reading database ... 189198 files and directories currently installed.)
Preparing to unpack .../bsd-mailx_8.1.2-0.20180807cvs-1_amd64.deb ...
Unpacking bsd-mailx (8.1.2-0.20180807cvs-1) ...
Setting up postfix (3.4.13-0ubuntu1) ...

Postfix (main.cf) configuration was not changed.  If you need to make changes,
edit /etc/postfix/main.cf (and others) as needed.  To view Postfix
configuration values, see postconf(1).

After modifying main.cf, be sure to run 'systemctl reload postfix'.

Setting up bsd-mailx (8.1.2-0.20180807cvs-1) ...
update-alternatives: using /usr/bin/bsd-mailx to provide /usr/bin/mailx (mailx) in auto mode
Processing triggers for ufw (0.36-6) ...
Processing triggers for systemd (245.4-4ubuntu3.2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for rsyslog (8.2001.0-1ubuntu1.1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  libgsasl7 libkyotocabinet16v5 libmailutils6 libmysqlclient21 libntlm0 mailutils-common mysql-common ttf-dejavu-core
0 upgraded, 0 newly installed, 8 to remove and 22 not upgraded.
After this operation, 13.0 MB disk space will be freed.
(Reading database ... 189209 files and directories currently installed.)
Removing libmailutils6:amd64 (1:3.7-2.1) ...
Removing libgsasl7:amd64 (1.8.1-1) ...
Removing libkyotocabinet16v5:amd64 (1.2.76-4.2build1) ...
Removing libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.4) ...
Removing libntlm0:amd64 (1.5-2) ...
Removing mailutils-common (1:3.7-2.1) ...
Removing mysql-common (5.8+1.0.5ubuntu2) ...
Removing ttf-dejavu-core (2.37-1) ...
```

**Comment by baditaflorin** [comment]
Tried with another account where I also enabled enable Less secure app access

─────────┤ Nextcloud VM - 2020 - SMTP Relay with msmtp ├────────────────────────┐
                                                                              │                                                                                               │
                                                                              │ It seems like something has failed.                                                           │
                                                                              │ You can look at /var/log/msmtp for further logs.                                              │
                                                                              │ We will now reset everything except the logfile so that you are able to start over again.     │
                                                                              │ Please run this script once more time if you want to make another try.

**Comment by szaimen** [comment]
The problem is I cannot reproduce this. Could you maybe create a testaccount for me and send the credentials to my mail address (look here: https://github.com/szaimen)
I need the mailaddress, password and one app-password.

**Comment by enoch85** [comment]
I've tested the SMTP script on multple servers, all of them work. Since we can't reproduce this, it's probably something on your network, or server.

**Comment by baditaflorin** [comment]
I was able to set SMTP using a personal account with app password, was not able to do this using a Google Suite account. 

Tried with smtp and smtp-relay endpoints 

```
mail: /usr/bin/msmtp -t: No such file or directory
Can't send mail: sendmail process failed with error code 1
send-mail: the server sent an empty reply
send-mail: could not send mail (account default from /etc/msmtprc)
Oct 18 03:42:36 host=smtp-relay.gmail.com tls=on auth=on user=smtp@mydomain.com from=smtp@mydomain.com recipients=myemail@gmail.com errormsg='the server sent an empty reply' exitcode=EX_PROTOCOL
Can't send mail: sendmail process failed with error code 76
```

Get:1 http://mirrors.rit.edu/ubuntu focal/universe amd64 libntlm0 amd64 1.5-2 [14.1 kB]
Get:2 http://mirrors.rit.edu/ubuntu focal/universe amd64 libgsasl7 amd64 1.8.1-1 [114 kB]
Get:3 http://mirrors.rit.edu/ubuntu focal/universe amd64 msmtp amd64 1.8.6-1 [136 kB]
Fetched 264 kB in 2s (148 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libntlm0:amd64.
(Reading database ... 189060 files and directories currently installed.)
Preparing to unpack .../libntlm0_1.5-2_amd64.deb ...
Unpacking libntlm0:amd64 (1.5-2) ...
Selecting previously unselected package libgsasl7:amd64.
Preparing to unpack .../libgsasl7_1.8.1-1_amd64.deb ...
Unpacking libgsasl7:amd64 (1.8.1-1) ...
Selecting previously unselected package msmtp.
Preparing to unpack .../msmtp_1.8.6-1_amd64.deb ...
Preparing to unpack .../msmtp-mta_1.8.6-1_amd64.deb ...
Unpacking msmtp-mta (1.8.6-1) ...
Setting up msmtp-mta (1.8.6-1) ...
**msmtpd.service is a disabled or a static unit, not starting it.**
Processing triggers for systemd (245.4-4ubuntu3.2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libkyotocabinet16v5 libmailutils6 libmysqlclient21 mailutils-common mysql-common
Suggested packages:
  mailutils-mh mailutils-doc
The following NEW packages will be installed:
  libkyotocabinet16v5 libmailutils6 libmysqlclient21 mailutils mailutils-common mysql-common
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 2394 kB of archives.
After this operation, 12.8 MB of additional disk space will be used.
Get:1 http://mirrors.rit.edu/ubuntu focal/universe amd64 libkyotocabinet16v5 amd64 1.2.76-4.2build1 [318 kB]
Get:2 http://mirrors.rit.edu/ubuntu focal/universe amd64 mailutils-common all 1:3.7-2.1 [272 kB]
Get:3 http://mirrors.rit.edu/ubuntu focal/main amd64 mysql-common all 5.8+1.0.5ubuntu2 [7496 B]
Get:4 http://mirrors.rit.edu/ubuntu focal-updates/main amd64 libmysqlclient21 amd64 8.0.21-0ubuntu0.20.04.4 [1222 kB]
Get:5 http://mirrors.rit.edu/ubuntu focal/universe amd64 libmailutils6 amd64 1:3.7-2.1 [437 kB]
Get:6 http://mirrors.rit.edu/ubuntu focal/universe amd64 mailutils amd64 1:3.7-2.1 [138 kB]
Fetched 2394 kB in 2s (1393 kB/s)
Selecting previously unselected package libkyotocabinet16v5:amd64.
(Reading database ... 189000 files and directories currently installed.)
Preparing to unpack .../0-libkyotocabinet16v5_1.2.76-4.2build1_amd64.deb ...
Unpacking libkyotocabinet16v5:amd64 (1.2.76-4.2build1) ...
Selecting previously unselected package mailutils-common.
Preparing to unpack .../1-mailutils-common_1%3a3.7-2.1_all.deb ...
Unpacking mailutils-common (1:3.7-2.1) ...
Selecting previously unselected package mysql-common.
Preparing to unpack .../2-mysql-common_5.8+1.0.5ubuntu2_all.deb ...
Unpacking mysql-common (5.8+1.0.5ubuntu2) ...
Selecting previously unselected package libmysqlclient21:amd64.
Preparing to unpack .../3-libmysqlclient21_8.0.21-0ubuntu0.20.04.4_amd64.deb ...
Unpacking libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.4) ...
Selecting previously unselected package libmailutils6:amd64.
Preparing to unpack .../4-libmailutils6_1%3a3.7-2.1_amd64.deb ...
Unpacking libmailutils6:amd64 (1:3.7-2.1) ...
Selecting previously unselected package mailutils.
Preparing to unpack .../5-mailutils_1%3a3.7-2.1_amd64.deb ...
Unpacking mailutils (1:3.7-2.1) ...
Setting up mysql-common (5.8+1.0.5ubuntu2) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Setting up libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.4) ...
Setting up libkyotocabinet16v5:amd64 (1.2.76-4.2build1) ...
Setting up mailutils-common (1:3.7-2.1) ...
Setting up libmailutils6:amd64 (1:3.7-2.1) ...
Setting up mailutils (1:3.7-2.1) ...
update-alternatives: using /usr/bin/frm.mailutils to provide /usr/bin/frm (frm) in auto mode
update-alternatives: using /usr/bin/from.mailutils to provide /usr/bin/from (from) in auto mode
update-alternatives: using /usr/bin/messages.mailutils to provide /usr/bin/messages (messages) in auto mode
update-alternatives: using /usr/bin/movemail.mailutils to provide /usr/bin/movemail (movemail) in auto mode
update-alternatives: using /usr/bin/readmsg.mailutils to provide /usr/bin/readmsg (readmsg) in auto mode
update-alternatives: using /usr/bin/dotlock.mailutils to provide /usr/bin/dotlock (dotlock) in auto mode
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...

**Comment by enoch85** [comment]
With Gmail you usually have to allow external "apps" to send emails through them, it's a Google security feature.
