### ISSUE TITLE
[enhancement] add ability to skip instead of just requiring Reinstall/Uninstall

### ISSUE THREAD

**Issue by baditaflorin** [nextcloud/vm#1564]
┌──────────────────────┤ Nextcloud VM - 2020 - Fail2ban ├──────────────────────┐
│ It seems like 'Fail2Ban' is already installed.                               │
│ Choose what you want to do.                                                  │
│ Navigate with the [ARROW] keys and confirm by pressing [ENTER]               │
│                                                                              │
│ You can view this script later by running 'sudo bash /var/scripts/menu.sh'   │
│                                                                              │
│                             Reinstall Fail2Ban                               │
│                             Uninstall Fail2Ban                               │
│                                                                              │
│                                                                              │
│                     <Ok>                         <Cancel>                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────

## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by szaimen** [comment]
@baditaflorin You can already skip by selecting the "Cancel" button below or pressing the escape button.
Please reopen if that isn't what you are looking for.
