### ISSUE TITLE
Additional Apps does not check properly for some installed apps

### ISSUE THREAD

**Issue by baditaflorin** [nextcloud/vm#1565]
In this case, Netdata is already installed, but here in the menu it does not appears as installed. 
![image](https://user-images.githubusercontent.com/2330999/96050391-34d76200-0e82-11eb-83fa-124e6ca174c0.png)

## Steps to reproduce
1. Already installed a lot of additional apps
2. restarted the server
3. enter into menu and try to install another additional app

## Expected behaviour
I will see with a [*] (star) next to all the apps that I have already installed, 

### Later edit for clarifications. 
Some **previously installed apps** will have the star, some will not
## Server configuration
https://shop.hanssonit.se/product/nextcloud-home-sme-server-4tb-2/
**Nextcloud server version:** (see your admin page)
How do you see the admin page?

**Server OS** (Ubuntu server is default)
https://shop.hanssonit.se/product/nextcloud-home-sme-server-4tb-2/

**How did you install the VM?** (Scripted install from master **OR** Released version)
https://shop.hanssonit.se/product/nextcloud-home-sme-server-4tb-2/

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Empty file```

#### Installation log (command output)
```
You cannot insert CLI output because you are doing modal dialog that will disappear when you exit the script.  
```

#### Screenshoots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by szaimen** [comment]
@baditaflorin you are understanding the start wrong.
It doesn't select items that are already installed but selects items that are suggested.
@enoch85 Maybe we should make this a bit clearer?

**Comment by enoch85** [comment]
@baditaflorin This is because the startup script is still existing, and you didn't finish the first setup properly.
