### ISSUE TITLE
Boot problems after updating from 19.0 to 20.0

### ISSUE THREAD

**Issue by LowRadiance** [nextcloud/vm#1572]
Hi,

I tried to update today from Version 19.0 to 20 with that update.sh script. The system did a lot of updates and ended up without any reported error.

After that, I got an "Error" 503, Service unavailable.

I thought that it seems a good idea to reboot, but: I always received a kernel panic, saying many things, but was unable to mount VFS and stopped.

I tried a few times, but always the same result.

As I'm for sure no expert in that, is there any know issue with that ? The VM runs In a HyperV environment under Windows 2016.

Regards

Thomas

**Comment by szaimen** [comment]
No, afaik there is no known issue with the update script.
Could you please screenshot the kernel messages and post them here? Maybe we find something helpful in there...
I would suggest you to restore a backup for now.

**Comment by szaimen** [comment]
Also very helpful woud be if you would get access to the update log and post it here.

**Comment by szaimen** [comment]
It should be this file: `/var/log/nextcloud/update.log`
Thanks!

**Comment by LowRadiance** [comment]
good, will do that these days and get the update.log before rebooting.

**Comment by szaimen** [comment]
Afaik, we don't actually store everything in the log file if you run the update script manually. In this case copying the log from the terminal over would be the better way, I guess. Another possibility is probably `sudo bash /var/scripts/update.sh > log.txt`

**Comment by enoch85** [comment]
Was the update made on a Ubuntu 18.04, or 20.04 OS?

Usually, a rebeoot fixes most issues.

**Comment by LowRadiance** [comment]
Hey,

its Ubuntu 20.04 LTS. This is based on a VM, which I bought from your shop few month ago..

**Comment by LowRadiance** [comment]
> 
> 
> Was the update made on a Ubuntu 18.04, or 20.04 OS?
> 
> Usually, a reboot fixes most issues.

In this case, it does the opposite -))

**Comment by enoch85** [comment]
I've updated around 20 servers the last week. I have no issues. 

Do you have automatic updates turned on? If yes, please revert froma backup, remove it, and then do the update manually instead.
