### ISSUE TITLE
Native English speakers are wanted!

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1577]
Both @szaimen and I are not native English speakers, and the text in the inform boxes might be a bit off in some places.

We would really need someone that looked through all the `msg_box`, `yesno_yes`, `yesno_no` and other informative boxes in general that are presented to the users in the scripts.

Payment can be discussed when the PR is merged.

Thanks!

**Comment by tyleroconnell** [comment]
@enoch85 @szaimen I'd be happy to help! I'm a native English speaker that came across this repo when looking for a simple and easily maintainable solution to manage Nextcloud with my hypervisor. I'm more than willing to contribute free of charge, given all the time I hope your work will save me 😄

To confirm so I can complete this PR in one go, you'd like me to review the text contained within any instance of: `msg_box`, `yesno_box_yes`, `yesno_box_yes`, `input_box`, and `input_box_flow`? Any others?

**Comment by enoch85** [comment]
Wow @tyleroconnell that's great!

Yes, correct, those boxes and basically everything in [lib.sh](https://github.com/nextcloud/vm/blob/master/lib.sh) that contains text presented to the user. Easiest way to find out is to search for `$1` `$2` `$3` and see if you can find any occurrences were text is presented to the user.

It would be great to actually check *everything* but that's much I know. :)

A single big PR would work, yes. :)

**Comment by szaimen** [comment]
@tyleroconnell thanks from my side, too!

As a small remark: for now it should be enough to inspect all scripts outside the [not-supperted folder](https://github.com/nextcloud/vm/tree/master/not-supported) and the [old folder](https://github.com/nextcloud/vm/tree/master/old), I guess.

**Comment by enoch85** [comment]
Here's something to work with:


Filtered Findings (70)

migrate/docker/readme.md|5 col 115| "soley" is a misspelling of "solely"
migrate/docker/readme.md|17 col 26| "administor" is a misspelling of "administer"
nextcloud-startup-script.sh|110 col 22| "recomended" is a misspelling of "recommended"
nextcloud-startup-script.sh|206 col 14| "desinged" is a misspelling of "designed"
nextcloud_update.sh|293 col 58| "compability" is a misspelling of "compatibility"
not-supported/remotedesktop.sh|94 col 22| "successfuly" is a misspelling of "successfully"
not-supported/smbserver.sh|526 col 64| "directoy" is a misspelling of "directory"
not-supported/smbserver.sh|920 col 45| "additonal" is a misspelling of "additional"
not-supported/smbserver.sh|1263 col 52| "succesfully" is a misspelling of "successfully"
not-supported/offshore-backup-wizard.sh|73 col 22| "wich" is a misspelling of "which"
not-supported/offshore-backup-wizard.sh|192 col 64| "direcotry" is a misspelling of "directory"
lib.sh|571 col 74| "recomend" is a misspelling of "recommend"
lib.sh|680 col 46| "emtpy" is a misspelling of "empty"
lib.sh|815 col 6| "Adress" is a misspelling of "Address"
lib.sh|824 col 63| "happend" is a misspelling of "happened"
lib.sh|1228 col 78| "paitent" is a misspelling of "patient"
not-supported/daily-backup-wizard.sh|65 col 22| "wich" is a misspelling of "which"
not-supported/daily-backup-wizard.sh|249 col 64| "direcotry" is a misspelling of "directory"
not-supported/borgbackup.sh|462 col 28| "succesful" is a misspelling of "successful"
CHANGELOG.md|65 col 47| "libary" is a misspelling of "library"
issue_template.md|17 col 12| "behaviour" is a misspelling of "behavior"
CHANGELOG.md|88 col 32| "occurances" is a misspelling of "occurrences"
issue_template.md|20 col 10| "behaviour" is a misspelling of "behavior"
issue_template.md|51 col 5| "Screenshoots" is a misspelling of "Screenshot"
static/index.php|98 col 20| "recomended" is a misspelling of "recommended"
static/index.php|119 col 102| "recomended" is a misspelling of "recommended"
static/docker_overlay2.sh|166 col 7| "experiance" is a misspelling of "experience"
static/nhss_index.php|98 col 20| "recomended" is a misspelling of "recommended"
static/nhss_index.php|119 col 102| "recomended" is a misspelling of "recommended"
static/instruction.sh|29 col 28| "maintenace" is a misspelling of "maintenance"
geoblockdat/README.md|7 col 109| "verfiying" is a misspelling of "verifying"
disk/smart-monitoring.sh|46 col 13| "Continous" is a misspelling of "Continuous"
disk/format-sdb.sh|103 col 65| "memeber" is a misspelling of "member"
disk/format-chosen.sh|124 col 65| "memeber" is a misspelling of "member"
disk/change-to-zfs-mount-generator.sh|65 col 71| "emtpy" is a misspelling of "empty"
network/geoblock.sh|129 col 15| "explicitely" is a misspelling of "explicitly"
network/static_ip.sh|168 col 26| "manaully" is a misspelling of "manually"
nextcloud_install_production.sh|19 col 48| "requierments" is a misspelling of "requirements"
network/static_ip.sh|226 col 27| "sucessfully" is a misspelling of "successfully"
nextcloud_install_production.sh|558 col 17| "distrubuted" is a misspelling of "distributed"
nextcloud_install_production.sh|895 col 9| "adress" is a misspelling of "address"
addons/locate_mirror.sh|23 col 30| "gurantees" is a misspelling of "guarantees"
menu/additional_apps.sh|30 col 115| "experiance" is a misspelling of "experience"
menu/nextcloud_configuration.sh|51 col 52| "behaviour" is a misspelling of "behavior"
menu/server_configuration.sh|38 col 135| "experiance" is a misspelling of "experience"
README.md|65 col 39| "Improvments" is a misspelling of "Improvements"
menu/server_configuration.sh|55 col 21| "beeing" is a misspelling of "being"
old/modsecurity.sh|29 col 21| "defence" is a misspelling of "defense"
old/modsecurity.sh|40 col 47| "defence" is a misspelling of "defense"
old/modsecurity.sh|88 col 44| "seperate" is a misspelling of "separate"
old/format-sda-nuc-server.sh|53 col 65| "memeber" is a misspelling of "member"
apps/previewgenerator.sh|237 col 12| "behaviour" is a misspelling of "behavior"
apps/onlyoffice_docker.sh|138 col 65| "seperate" is a misspelling of "separate"
apps/smbmount.sh|306 col 45| "additonal" is a misspelling of "additional"
apps/onlyoffice_integrated.sh|190 col 10| "paitent" is a misspelling of "patient"
apps/onlyoffice_integrated.sh|201 col 13| "presist" is a misspelling of "persist"
apps/collabora_docker.sh|124 col 65| "seperate" is a misspelling of "separate"
apps/tmbitwarden.sh|53 col 49| "seperate" is a misspelling of "separate"
apps/tmbitwarden.sh|56 col 40| "seperate" is a misspelling of "separate"
apps/tmbitwarden.sh|90 col 45| "correclty" is a misspelling of "correctly"
apps/tmbitwarden.sh|357 col 58| "compability" is a misspelling of "compatibility"
apps/tmbitwarden.sh|365 col 23| "sucessfully" is a misspelling of "successfully"
apps/tmbitwarden.sh|378 col 8| "beacuse" is a misspelling of "because"
apps/fail2ban.sh|182 col 25| "sucessfully" is a misspelling of "successfully"
apps/clamav.sh|190 col 20| "succesfully" is a misspelling of "successfully"
apps/collabora_integrated.sh|66 col 10| "paitent" is a misspelling of "patient"
apps/bitwarden-rs.sh|304 col 50| "sucessfully" is a misspelling of "successfully"
apps/talk.sh|210 col 65| "seperate" is a misspelling of "separate"
apps/adminer.sh|42 col 8| "distrobution" is a misspelling of "distribution"
apps/adminer.sh|123 col 25| "sucessfully" is a misspelling of "successfully"

**Comment by lantrix** [comment]
Rolling through these now 🥳

**Comment by lantrix** [comment]
> It would be great to actually check _everything_ but that's much I know. :)

I spell checked everything document by document, manually.

**Comment by enoch85** [comment]
Grammar is still needed to be checked.

**Comment by tyleroconnell** [comment]
Sorry for not working on this sooner but I can tackle grammar on Wednesday.

**Comment by enoch85** [comment]
Thanks a million times!

**Comment by UNlDAN** [comment]
I would never have guessed you guys were not English speakers, your English is GREAT!

**Comment by enoch85** [comment]
This can be closed for now.

Thanks again @tyleroconnell!

**Comment by tyleroconnell** [comment]
No problem @enoch85. I definitely echo what @UNlDAN said in terms of the English prompts being pretty great from the start!
