### ISSUE TITLE
Move previewgenerator and fail2ban-menu over to nextcloud_configuration menu?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1589]
Hey, I would like to discuss whether it makes sense to move the previewgenerator and fail2ban menu over to the nextcloud_configuration menu since this is directly Nextcloud related and fits from the topic perfectly into this menu, imo.
All other Apps in the additional_apps menu are not that directly related to Nextcloud.
What do you think?

**Comment by szaimen** [comment]
Maybe we could rename nextcloud_configuration to nextcloud_menu?

**Comment by enoch85** [comment]
Naah, I think they're good at the current location.

Previewgenerator is an app, and fail2bansort of as well..

Maybe move Fail2ban to ADDONS, but not needed.

**Comment by szaimen** [comment]
okay

**Comment by szaimen** [comment]
Just one proposal
