### ISSUE TITLE
Switch to Docker CE

### ISSUE THREAD

**Issue by oparoz** [nextcloud/vm#159]
Docker now exists in EE and CE editions. The scripts which installs docker should be modified to download the CE edition from their repos.

https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository

**Comment by enoch85** [comment]
What's the main difference between the two of them, and why CE?

**Comment by oparoz** [comment]
https://blog.docker.com/2017/03/docker-enterprise-edition/

You need to buy a license to be able to use EE

**Comment by enoch85** [comment]
Ah ok, but why not use the built in `docker.io` that comes with Ubuntu?

**Comment by oparoz** [comment]
I have  no idea who maintains that package. All I know is that the CE edition is going to be maintained by the team behind Docker.
