### ISSUE TITLE
We should remove the current talk script and the talk menu

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1606]
I think we should remove this script and the talk menu. 

1. Rename talk_signaling.sh to talk.sh
2. Remove the menu for Talk

Reason? You can choose if you want signaling or not when installing Talk.

_Originally posted by @enoch85 in https://github.com/nextcloud/vm/pull/1597#issuecomment-712142393_

**Comment by enoch85** [comment]
Done
