### ISSUE TITLE
Update VHOST for Collabora

### ISSUE THREAD

**Issue by oparoz** [nextcloud/vm#162]
CODE 2.0 requires a slightly different VHOST.

See  https://nextcloud.com/collaboraonline/

**Comment by enoch85** [comment]
Nope it's exactly the same.

**Comment by oparoz** [comment]
Actually, they're not.

You're missing the ProxyPassMatch rule.

**Comment by oparoz** [comment]
Let me try to do a PR

**Comment by enoch85** [comment]
You mean [this](https://github.com/nextcloud/vm/blob/master/static/collabora.sh#L225) and [this](https://github.com/nextcloud/vm/blob/master/static/collabora.sh#L237)?

**Comment by oparoz** [comment]
I was looking at that:
https://raw.githubusercontent.com/nextcloud/vm/be76636b28444844832eda6536d6eb6b3aed85fc/static/collabora.sh

Not sure how I landed on an outdated version...

Sorry!
