### ISSUE TITLE
OnlyOffice says "editor version has been updated" and the page tries to reload but never does

### ISSUE THREAD

**Issue by HTGuru** [nextcloud/vm#1620]
## Steps to reproduce
1. Load any .docx or .xlsx or create one.
2. Message "Editor version has been updated. The page will be reloaded to apply the changes" displayed instead of document or spreadsheet loading
3. Click OK to message
4. The page shows "ONLYOFFICE Loading..." but never does.

Since this broke the VM reporting as an issue here.
In /settings/admin/onlyoffice
ONLYOFFICE Server settings
ONLYOFFICE Document Service Location specifies the address of the server with the document services installed. Please change the '<documentserver>' for the server address in the below line.
Document Editing Service address:
https://serverFQDN/apps/documentserver_community/ 
Above was originally wrong after install but easily corrected and ONLYOFFICE worked perfectly.
Assuming it's Still correct after script upgraded system to Nextcloud 20.0.0 and Onlyoffice 6.1.0

## Expected behaviour
Tell us what should happen
OnlyOffice should load document that was clicked on. Was working perfectly until auto update on 17/10/2020

## Actual behaviour
Tell us what happens instead
page tries to reload but never does
## Server configuration

**Nextcloud server version:** (see your admin page)
Nextcloud 20.0.0 and all apps successfully updated after running and completing sudo bash /var/scripts/update.sh

**Server OS** (Ubuntu server is default)
Ubuntu 20.04
Operating System: | Linux 5.4.0-52-generic x86_64

**How did you install the VM?** (Scripted install from master **OR** Released version)
Downloaded Released version VM 40GB .ova, installed on ESXi, flawlessly ran startup script at first console login.
## Network
**Do you use DHCP?**
NO
**Is port 80 and/or 443 open?**
YES, both
## Logs / Screenshots

![SNAG-0481](https://user-images.githubusercontent.com/73324421/96953950-59ee5500-14c0-11eb-8e29-14d115359e99.jpg)
![SNAG-0482](https://user-images.githubusercontent.com/73324421/96953963-64105380-14c0-11eb-8f1c-c7de54575294.jpg)

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```
https://0bin.net/paste/5Dunod7B#GkVeUK8HPGjJJzkX33UWRjskE2VI8qGFLu5gxIqKOL1
#### Installation log (command output)
```
Insert the CLI output here
```
no longer available

#### Screenshoots
Posted above

**Comment by enoch85** [comment]
Thanks for your detailed issue!

> Above was originally wrong after install but easily corrected and ONLYOFFICE worked perfectly.

That's a VM issue, the rest it OnlyOffice.

So, what was the wrong URL, and what did you change to, to get it working?

**Comment by HTGuru** [comment]
Unfortunately, I did not document precisely what the incorrectly propagated post VM install script Only Office Document Editing Service address URL was after Only Office was installed by the VM script.

One thing about it I remember for sure is that it had a double slash in it where it couldn’t possibly belong. It was probably right after the FQDN.

If I had to guess I would say it looked like this:
https://serverfqdn//apps/documentserver_community/

I think Only Office started working just by removing the extra slash but I’m not entirely positive. I may have had to change the Document Editing Service address part after the double slash too.

My VM was downloaded when the base was Next Cloud 19.0.0 I believe and may have been upgraded to 19.0.2 by the time the script had finished.

One additional fact not previously mentioned, Only Office is running on the Next Cloud server VM. It is not running in a separate VM.

So initially two more questions here:

1. Out of curiosity is the URL actually still correct the way it appears now or could an auto update have modified it yet again?

2. What is the next step to resolve this Only Office issue since all your VM documentation makes it clear to only run your scripts on the back end and not use the Nextcloud front end to update.

**Comment by enoch85** [comment]
The issue with double // was fixed a while back.

Please reinstall with the latest script, and report back if it doesn't work.

Thanks.

**Comment by HTGuru** [comment]
So just to be clear,

Are you are saying this issue will require building and entirely new NC instance from scratch?

As in downloading a new .ova an beginning the entire process over again and then migrating the data?

Or hopefully you are saying to delete Only Office and reinstall it with the latest menu script.

sudo bash /var/scripts/menu.sh

If it’s the latter then I will give in a go. If it’s the former, ther has to be some other way.

I have looked for other solutions on every possible support forum but found like else but for one thread were people claim they fixed it by clearing the browser cache.

This did not work for me and since the issue is present in both the iPhone and iPad apps in seems like a lucky break for those few, not a legitimate solution to the problem.

Since this was all working perfectly I must assume that this was broken during an automatic update from the cron.

Are there any logs that I could post to give more insight?

As a last resort before I would start from scratch, if needed, would you take this on directly if I purchased support time?

**Comment by enoch85** [comment]
> sudo bash /var/scripts/menu.sh

Correct. That's one of the reasons we built the menu. :+1: 

No logs needed, the issue should be fixed already. :)

**Comment by HTGuru** [comment]
Thanks, That’s certainly what I was hoping for!

I’ll give it a try ASAP and report back.

Just one additional question: When you say “reinstall” should I simply run the Only Office option from the menu script or will it be necessary to first uninstall and then install it again?

**Comment by szaimen** [comment]
> Just one additional question: When you say “reinstall” should I simply run the Only Office option from the menu script

Yes 👍

**Comment by HTGuru** [comment]
OK,

Ran:
sudo bash /var/scripts/menu.sh

Chose Only Office, chose the reinstall option and yes indeed it did fix the problem!

Thank you very much, the menu script reinstall fixes the problem!

**Comment by enoch85** [comment]
Glad we could help you!
