### ISSUE TITLE
Install Nextcloud is not possible because of an network issue

### ISSUE THREAD

**Issue by herrschlupp** [nextcloud/vm#1626]
Hello,
I try to intall nextcloud, but it's not possible.

Nextcloud don't get an connection to the internet within the installation process.
I got always the message "network settings are not correct".

But this is not possible. DNS is ok up and running. There is no IP adress conflict and my network is running corectly.

Has anybody an idea what I have todo?

Thanks
-herrschlupp

**Comment by Ginfred** [comment]
Replace it
`    # Check if IFACE is empty, if yes, try another method:
    if [ -n "$IFACE" ]
    then
        cat <<-IPCONFIG > "$INTERFACES"
network:
   version: 2
   ethernets:
       $IFACE: #object name
         dhcp4: false # dhcp v4 disable
         dhcp6: false # dhcp v6 disable
         addresses: 
         - $LANIP # client IP address
         gateway4: $GATEWAYIP # gateway address
         nameservers:
           addresses: [$DNSs] #name servers
IPCONFIG

        msg_box "These are your settings, please make sure they are correct:

$(cat /etc/netplan/01-netcfg.yaml)"
        netplan try
        set_systemd_resolved_dns "$IFACE"
    else
        cat <<-IPCONFIGnonvmware > "$INTERFACES"
network:
   version: 2
   ethernets:
       $IFACE2: #object name
         dhcp4: false # dhcp v4 disable
         dhcp6: false # dhcp v6 disable
         addresses: 
         - $LANIP # client IP address
         gateway4: $GATEWAYIP # gateway address
         nameservers:
           addresses: [$DNSs] #name servers
IPCONFIGnonvmware
`
in **/var/scripts/static_ip.sh**

I found some problems with variables
