### ISSUE TITLE
Let's encrypt not working, 443 not open, can't set domain (FQDN)

### ISSUE THREAD

**Issue by flotpg** [nextcloud/vm#163]
## Steps to reproduce
1.fresh boot  after unpack of vm image
2.vm gets ip
3.lets encrypt doesn't work, cause public ip isn't detected corrected

## Expected behaviour
want to set FQDN of public domain somewhere to get lets encrypt working

## Actual behaviour
Let's encrypt failes, cause it uses local IP

## Server configuration

**Server version: current** (see your admin page)

**VM version: current**
<img width="651" alt="nextcloud01" src="https://cloud.githubusercontent.com/assets/20798074/23666961/b4f038b6-035c-11e7-8cc9-36961c1d078e.png">
nextcloud says 443 isn't open, it is, i checked with netcat. How does it detect it's ip address? We've multiple WAN IPs.
<img width="1106" alt="nextcloud02" src="https://cloud.githubusercontent.com/assets/20798074/23667008/d7e1c5ba-035c-11e7-8201-2a24fa56d638.png">

**Comment by Ark74** [comment]
It uses nmap to look for it.
I had a similar issue.
What happens if you visit your NC domain?

**Comment by flotpg** [comment]
Hey Ark74,

this is what happens:
<img width="798" alt="netxcloud03" src="https://cloud.githubusercontent.com/assets/20798074/23667421/120f6ed0-035e-11e7-857f-9188b9dbb83f.png">

**Comment by Ark74** [comment]
Ohh! the same issue.
Just ssh your server and add your domain to /var/www/nextcloud/config/config.php

And you'll be good to go :)

**Comment by Ark74** [comment]
@enoch85 
I think this is related to the latest PR #161

**Comment by Ark74** [comment]
I had that behavior too.

**Comment by enoch85** [comment]
Aah ok, we need to update the config parameters based on what the user types as domain.

**Comment by flotpg** [comment]
Ok, working now, but how to get /var/scripts/activate-ssl.sh working

i checked the script,
WANIP4=$(dig +short myip.opendns.com @resolver1.opendns.com)
ADDRESS=$(hostname -I | cut -d ' ' -f 1)

Both result in correct IPs...

**Comment by enoch85** [comment]
Please test this: https://github.com/nextcloud/vm/pull/164

**Comment by flotpg** [comment]
wget also fails, commented them out, now letsencrypt fails:
`Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/ncadmin/.local...ncrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1

It seems like no certs were generated, we do two more tries.`

will try #164 now

**Comment by flotpg** [comment]
Nope, still claiming port is not open.

**Comment by enoch85** [comment]
Aah, I must ask if the port is open after the domain value is set. As you can see it returns an empty value.

**Comment by enoch85** [comment]
@flotpg Please test it again. 

Thanks!

**Comment by flotpg** [comment]
@enoch85 running, entered domain name, waiting to finish, keep you updated.

**Comment by flotpg** [comment]
sorry, I was to fast ;)
waiting for second try to finish

**Comment by enoch85** [comment]
@flotpg OK, changed the check a bit, please try again.

**Comment by flotpg** [comment]
@enoch85 nope, sorry - still the same. I think it's somewhere related to the firewall design.
I can't lynx https://nextcloud01.ontpg.com on the machine itself (it's in a DMZ)... will check the firewall

Nothing blocked, but i guess it has something to do with dest-nat:

wan-ip <  dst-nat to > vlan-dmz > ip in dmz

Machine from DMZ can't access itself cause the traffic never really goes out to the isp and back...
I will try if there's a way to make it possible... But i think this normal, so there should be a way to check availability from outside or a fallback for scenarios like this.

**Comment by enoch85** [comment]
@flotpg What if you try this command? `nmap -sS -p 443 -O scanme.nmap.org`

**Comment by flotpg** [comment]
`ncadmin@nextcloud01:~$ sudo nmap -sS -p 443 -O scanme.nmap.org

Starting Nmap 7.01 ( https://nmap.org ) at 2017-03-07 20:32 CET
Nmap scan report for scanme.nmap.org (45.33.32.156)
Host is up (0.17s latency).
Other addresses for scanme.nmap.org (not scanned): 2600:3c01::f03c:91ff:fe18:bb2f
PORT    STATE  SERVICE
443/tcp closed https
Too many fingerprints match this host to give specific OS details
Network Distance: 12 hops

OS detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 5.59 seconds`

from external 
`MacBook-Pro:~ flo$ sudo nmap -sS -p 443 -O nextcloud01.ontpg.com

Starting Nmap 7.40 ( https://nmap.org ) at 2017-03-07 20:34 CET
Nmap scan report for nextcloud01.ontpg.com (83.171.138.212)
Host is up (0.048s latency).
rDNS record for 83.171.138.212: host-83-171-138-212.customer.m-online.net
PORT    STATE SERVICE
443/tcp open  https
Warning: OSScan results may be unreliable because we could not find at least 1 open and 1 closed port
OS fingerprint not ideal because: Missing a closed TCP port so results incomplete
No OS matches for host

OS detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 5.12 seconds`

**Comment by flotpg** [comment]
Done, same:
MacBook-Pro:~ flo$ sudo nmap -sS -p 443 -O nextcloud01.ontpg.com

Starting Nmap 7.40 ( https://nmap.org ) at 2017-03-07 20:34 CET
Nmap scan report for nextcloud01.ontpg.com (83.171.138.212)
Host is up (0.048s latency).
rDNS record for 83.171.138.212: host-83-171-138-212.customer.m-online.net
PORT    STATE SERVICE
443/tcp open  https
Warning: OSScan results may be unreliable because we could not find at least 1 open and 1 closed port
OS fingerprint not ideal because: Missing a closed TCP port so results incomplete
No OS matches for host

OS detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 5.12 seconds

**Comment by enoch85** [comment]
Thanks! We are on to something here.

**Comment by flotpg** [comment]
tried again, nothing new.

**Comment by enoch85** [comment]
This is a firewall issue. But I'll leave it open just in case someone find's a solution to check ports from another (external) IP / domain.

**Comment by flotpg** [comment]
Technically yes, but in the wild most corporate firewalls are designed like this
- allow very specific (in-interface, out-inteface, protocoll, port, dst-address, src-address)
- deny all

Which results in a behaviour like this. The machine never needs to access itself in the field...

**Comment by enoch85** [comment]
An online port checking tool that can be used in bash would solve this issue I think. Just need to find one...

**Comment by flotpg** [comment]
Solved by creating a src-nat rule which translates to the WAN IP, but cert generation fails (branch master):
`OSError: Command /home/ncadmin/.local...ncrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "en_US:en",
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Enabling site 000-default.
To activate the new configuration, you need to run:
  service apache2 reload

It seems like no certs were generated, we do three more tries.
`

ubuntu letsencrypt package worked out of the box.

**Comment by enoch85** [comment]
Will have a look at the ubuntu package.Thanks for letting me know. If you want to, you could start a PR with the suggested changes. Would be awesome!Best regardsDaniel HanssonTech and MeSent from mobile, sorry for typos.Den 8 mars 2017 2:44 em skrev flotpg <notifications@github.com>:Solved by creating a src-nat rule which translates to the WAN IP, but cert generation fails (branch master):
`OSError: Command /home/ncadmin/.local...ncrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
LANGUAGE = "en_US:en",
LC_ALL = (unset),
LC_CTYPE = "UTF-8",
LANG = "en_US.UTF-8"
are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Enabling site 000-default.
To activate the new configuration, you need to run:
service apache2 reload
It seems like no certs were generated, we do three more tries.
`
ubuntu letsencrypt package worked out of the box.

**Comment by flotpg** [comment]
Hey, I don't how to do this.  Which changes do you mean?

**Comment by enoch85** [comment]
@flotpg As you said, when you changed to the ubuntu package of let's encrypt, it worked. So change from the git version to Ubuntus version is what I meant.

**Comment by flotpg** [comment]
Ah ok, so a PR for "change from the lets encrypt git version to Ubuntu's version"

**Comment by enoch85** [comment]
@flotpg Yes please. :)

I suggest you try it in a dev environment so that you can test all the PATHS and stuff.

**Comment by enoch85** [comment]
Done now. This issue should be solved.
