### ISSUE TITLE
empty data directory after update Ubuntu 18.04 => 20.04

### ISSUE THREAD

**Issue by DennyLandrock** [nextcloud/vm#1651]
After updating from Ubuntu 18.04 to 20.04 the data directory "nmt/ncdata" is empty. The error message says your data directory is invalid. Thanks for the help!

**Comment by enoch85** [comment]
Thanks for your issue, but that description doesn't help much at all. 

Please fill in the issue template and describe the exact steps of the update.

I've done probably 100 upgrades and that never happened to me. So, putting the support label on this one.

**Comment by enoch85** [comment]
Closing since no response for a week.
