### ISSUE TITLE
fulltextsearch_elasticsearch and mail app - unhandled exception

### ISSUE THREAD

**Issue by santesson** [nextcloud/vm#1656]
Using release 2020-20-31 I get this error:

Installing fulltextsearch_elasticsearch...
Installing files_fulltextsearch...
{
    "search_platform": "OCA\\FullTextSearch_ElasticSearch\\Platform\\ElasticSearchPlatform",
    "app_navigation": "0",
    "provider_indexed": "",
    "cron_err_reset": "1604598601",
    "tick_ttl": "1800"
}
An unhandled exception has been thrown:
TypeError: Return value of "OCA\FullTextSearch\Command\Configure::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#1 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\Base->run()
#2 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#3 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#4 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#5 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#7 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:configure {"search_platform":"OCA\\FullTextSearch_ElasticSearch\\Platform\\ElasticSearchPlatform"} failed

**Comment by enoch85** [comment]
Yeah, that happens sometimes. Don't know why. Most probably something with the app itself.

Please just run the installation again and choose to reinstall and the issue should be solved.

Thanks!

**Comment by santesson** [comment]
I've tried this a few times already. So far, only uninstalling the mail app helps.

Thanks!

**Comment by enoch85** [comment]
cc @daita @ChristophWurst --^ FYI

**Comment by ChristophWurst** [comment]
dependency conclict
