### ISSUE TITLE
Reverse Proxy w/ SSL Offloading -> access Nextcloud over port 80?

### ISSUE THREAD

**Issue by killtux** [nextcloud/vm#1660]
Hey guys!

I like to use the nextcloud vm with my HAproxy w/ SSL offloading.
So i installed without the letsencrypt SSL option

after everything is installed i only see the introduction page, even if i click on the first link to access nextcloud instance:
![image](https://user-images.githubusercontent.com/36768145/98746107-17c87d00-23b5-11eb-897e-7dff2fc908f2.png)

i think that comes from the pre-configured traffic redirection from port 80 to 443 that is mentioned in the documentation. where can i undo that so my proxy can access nextcloud through port 80 since SSL is handled there?

I would be really thankful for every hint, since i am trying to figure it out for the last 3 days.

 thanks a lot <3

**Comment by killtux** [comment]
sorry for tagging but @enoch85 can you give me a hint how to get it back to normal?

Suggestion for future versions of the VM/Script: 
Let the user choose when running the installation (without Letsencrypt), if he wants traffic redirected (default) or not?

**Comment by enoch85** [comment]
Sorry for the late answer.

This is more of a support question than a bug. Running it behind Nginx Reverse Proxy is no issue at all. I do it myself. Just leave the default configs and forward on port 80 **or** 443 to the backend. You might need to add `IP-ADDRESS:80` instead of `*:80` and add the servername as well.

Hope it helps!

> Let the user choose when running the installation (without Letsencrypt), if he wants traffic redirected (default) or not?

You're welcome to contribute. :+1:

**Comment by killtux** [comment]
Adding the ServerName in the /etc/apache2/sites-enabled/nextcloud_http_domain_self_signed.conf was enough. 
Thanks for your help and the great VM!

**Comment by biejay** [comment]
Hi, I need to revive this old topic.
The last answer really helped me and now I can successfully open Nextcloud in the Browser.

But WebDav does not work (So I can not open a network drive in windows). Could you give some explanation what I have to configure in Nginx Proxy Manager and the Nextcloud Installation? Thanks!

**Comment by killtux** [comment]
> Hi, I need to revive this old topic. The last answer really helped me and now I can successfully open Nextcloud in the Browser.
> 
> But WebDav does not work (So I can not open a network drive in windows). Could you give some explanation what I have to configure in Nginx Proxy Manager and the Nextcloud Installation? Thanks!

Did you set the forwards for webdav discovery?
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html#service-discovery

**Comment by biejay** [comment]
Yes, already had that in my configuration. I restarted the Proxy Manager and now it works, thanks!
