### ISSUE TITLE
Improve security rating

### ISSUE THREAD

**Issue by Ark74** [nextcloud/vm#167]
Nextcloud have come up with this new secutiry rating scan app.
https://scan.nextcloud.com/

The best result the VM script gets is an **A**
Because of,

_Host-Prefix 

Just by commenting # 
`#    Alias /nextcloud "/var/www/nextcloud/"`

... we can get an **A+** :+1: 

Maybe if not used we can get rid of it.

**Comment by enoch85** [comment]
Yes remove it pls.
