### ISSUE TITLE
Installing nextcloud VM appliance

### ISSUE THREAD

**Issue by bones1014** [nextcloud/vm#1672]
when trying to install NextCloud the appliance gave the error:
Can't create or write into the data directory /mnt/ncdata

![image](https://user-images.githubusercontent.com/74389768/99019377-cc7fad00-2521-11eb-85c6-8afa3f6a2702.png)

First time setting it up.

## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Thanks!

I will have a look.

**Comment by enoch85** [comment]
@bones1014 Please confirm that it works as intended.

Thanks!

**Comment by bones1014** [comment]
I'm not sure what I'm supposed to be doing. I see a link to a file.

**Comment by enoch85** [comment]
Run the installation again, confirm that it works. :+1:

**Comment by bones1014** [comment]
Do I need to redownload anything before I run the install?

**Comment by enoch85** [comment]
@bones1014 You don't need to download it again, but you need to remove the VM and then mount it again as you did the first time.

**Comment by bones1014** [comment]
It works now. Thank you very much!

**Comment by enoch85** [comment]
No problem! Thanks for posting your issue, and confirming it works. :)

**Comment by mcbuble** [comment]
Thanks , yes it's works awesome

**Comment by enoch85** [comment]
Thanks @mcbuble!
