### ISSUE TITLE
Make every update log specific with date

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1680]
Instead of just adding stuff to the update.log we should append `$date` to the filename so that we don't grow a single file.

It's better because:
1. The latest stuff is appended to the end of the log, and after a while it becomes several thousands of lines. This fix would only print a single update run
2. We can delete old logs, let's say 30 logs back since they are probably not needed

I also think that we should put all update logs in `$VMLOGS/update/update-$(date).log`.

**Comment by szaimen** [comment]
@enoch85 I would propose creating a new file during the update and merging it into one in the end.
Also we should get rid of spinner_loading in the update script, because it really spams any logfioe.

**Comment by enoch85** [comment]
> I would propose creating a new file during the update and merging it into one in the end. 

Isn't that the same as now, once single big file. That's what we don't want. :)

> Also we should get rid of spinner_loading

As a Linux novice you'd then think that nothing is happening during update and abort the script. Not a good idea. Been there, done that. :/
