### ISSUE TITLE
Nextcloud Production Version / Misleading script name

### ISSUE THREAD

**Issue by smartens** [nextcloud/vm#1682]
## Steps to reproduce
1. Use nextcloud_install_production.sh to install Nextcloud

## Expected behaviour
The script name is misleading. I was searching for an install script which installs the production channel version of nextcloud (https://nextcloud.com/release-channels/). Nextcloud is offering on Docker hub the production/stable version 19.0.4 (https://hub.docker.com/_/nextcloud).

## Actual behaviour
Instead of installing the production version the script installs the latest version.

```
Fetching the latest Nextcloud version...
20.0.1
Downloading nextcloud-20.0.1...
```

**Comment by enoch85** [comment]
Thanks for your issue. :+1: 

It's made for production, and installs the latest version of Nextcloud. 

The scripts itself is production ready, is the VM. I run all my Nextcloud servers with the latest version and have done so for years. The first maintenance version of a major version is what's usually solving the "bad" bugs, and running 20.0.1 in production is no issue *at all* if you ask me.

What Docker choose to call it is up to them, here we do what's been working for years.

I hope that answers your question. :robot:

**Comment by smartens** [comment]
Sure. I see your point. But it's not Docker who is choosing this name. It's the nextcloud team. Further, this repo is incorporated into the official nextcloud github account so I was 100% sure that it will align with the naming scheme the nextcloud team is using.

**Comment by szaimen** [comment]
@smartens I wonder where did you hear that 19.0.4 is the latest production release and not 20.0.1?

**Comment by enoch85** [comment]
He's right in the sense that the "production" train is one major version behind.

But as I said it's not *not* production just because it's 20.0.1.

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

-------- Originalmeddelande --------
På 17 nov. 2020 22:49, szaimen skrev:

**Comment by smartens** [comment]
> But as I said it's not *not* production just because it's 20.0.1.

I just wanted to give feedback. It's not that I say your setup is not production ready.

I'm just trying to say that if somebody visits the nextcloud website, informs him/herself about nextcloud, finds out that they have a production release channel, goes to github and finds your repo, will think that it will install the production release channel version of nextcloud.

**Comment by enoch85** [comment]
It's noted.

Thanks for your input!

**Comment by szaimen** [comment]
Hey @smartens, you can now use the `--not-latest` flag during the `nextcloud_install_production.sh` script.
