### ISSUE TITLE
An unhandled exception deleting "ncadmin"

### ISSUE THREAD

**Issue by silverdr** [nextcloud/vm#1684]
## Steps to reproduce
1. Run install script as a sudo enabled user named differently than `ncadmin`
2. Install and configure webmin
3. 

## Expected behaviour
The user should be created successfully and added to the admin group. No attempt to delete non-existent user `ncadmin` should be performed

## Actual behaviour
Configuring Webmin...
Starting webmin...
The user "silverdr" was created successfully
User "silverdr" added to group "admin"
Deleting ncadmin...
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Deck\Db\AssignmentMapper::findByUserId() in /var/www/nextcloud/apps/deck/lib/AppInfo/Application20.php:136
Stack trace:
#0 [internal function]: OCA\Deck\AppInfo\Application20::OCA\Deck\AppInfo\{closure}()
#1 /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php(101): call_user_func_array()
#2 /var/www/nextcloud/lib/private/Hooks/PublicEmitter.php(40): OC\Hooks\BasicEmitter->emit()
#3 /var/www/nextcloud/lib/private/User/User.php(266): OC\Hooks\PublicEmitter->emit()
#4 /var/www/nextcloud/core/Command/User/Delete.php(65): OC\User\User->delete()
#5 /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php(258): OC\Core\Command\User\Delete->execute()
#6 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run()
#7 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#9 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#10 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#12 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ user:delete ncadmin failed

## Server configuration

**Nextcloud server version:** (see your admin page)
20.x

**Server OS** (Ubuntu server is default)
Ubuntu 20.04.x

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install - don't know whether master or released version

## Network
**Do you use DHCP?**
No

**Is port 80 and/or 443 open?**
Yes

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by szaimen** [comment]
@enoch85 I think this is an issue from the Deck app.
We could either don't allow to install the Deck app during the nextcloud_install_production.sh script for now or use `nextcloud_occ_no_check` here: https://github.com/nextcloud/vm/blob/c6ab30e8728538e443318816fe33cd7bf4b93005/nextcloud-startup-script.sh#L416

**Comment by szaimen** [comment]
This is actually a big problem because the startup script fails because of this... @enoch85 what do you think about my ideas how to solve this?

**Comment by silverdr** [comment]
> This is actually a big problem because the startup script fails because of this...

Precisely. For now I can try w/o Deck but it seems like a rather important issue.

**Comment by szaimen** [comment]
the deck issue seems to be already fixed https://github.com/nextcloud/deck/issues/2569 but as long as there is no new deck release, we have to workaround since the startup script will fail if deck is installed

**Comment by szaimen** [comment]
There was a new deck release. https://github.com/nextcloud/deck/releases/tag/v1.2.1
So I guess we only need to wait 1-2h until the new version is in the app store and then it should work again.

**Comment by enoch85** [comment]
Thanks for debugging @szaimen
