### ISSUE TITLE
attribute 'SHA256' 2TB_Nextcloud_VM_www.hanssonit.se-disk2.vmdk does not match 

### ISSUE THREAD

**Issue by Swiss-M** [nextcloud/vm#1691]
## Steps to reproduce
1. Try to install _2TB_Nextcloud_VM_www.hanssonit.se.ova_ from 31.10.2020 on VirtualBox 6.1
2.
3.

## Expected behaviour
I just bought again the new package to avoid having trouble and being able to install this smoothly like the 40gb package.

## Actual behaviour
It doesn't want to load the OVA to the VM

## Logs / Screenshots

```
Digest mismatch (VERR_NOT_EQUAL): Attribute 'SHA256' on '2TB_Nextcloud_VM_www.hanssonit.se-disk2.vmdk' does not match ('d37c5681f6bceb1404b4e7aca02267c7c2f227721f2cbd94c0109dc369242bc5' vs. '6be26e87d667297ba732c21f82eb0853cfe2a076db5bd97539c90dabbf855086').

Code d'erreur : | VBOX_E_FILE_ERROR (0x80BB0004)
-- | --
Composant : | ApplianceWrap
Interface : | IAppliance {86a98347-7619-41aa-aece-b21ac5c1a7e6}

```

#### Screenshoots
[https://imgur.com/lwRMItq](url)

Please help because I bought your package in order to avoid any compatibility or issues.

**Comment by enoch85** [comment]
Which hypervisor is this?

**Comment by enoch85** [comment]
Maybe this is related? https://github.com/nextcloud/vm/issues/910

**Comment by Swiss-M** [comment]
I am in VirtualBox 6.1
This is when I try to load the appliance. it fail at the end.

Somehow I managed to run it after several reboot and while an other VM was running, making the VirtualBox crashing but loading all the files on the folder I specified. I don't know if it's clean or stable. I ll try tomorrow.

**Comment by enoch85** [comment]
Use VMware instead, VirtualBox is known for having issues: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=bhjtk3ahv0jgro7odn50

If you still have issues, please report back.

**Comment by enoch85** [comment]
@Swiss-M Any news?

**Comment by Swiss-M** [comment]
Hello @enoch85 

So I have been playing around these past days at night.
I tried with VMware but unsuccessfull, I installed **VMware Fusion 11** on my mac. I mount it (couldn't find network option bridge) it's not the same look than what you are using on your demo video. Then when launching the VM I got several errors, so I thought it's not the right software to use.

Which VMware should I use (on mac OSX) to be sure it works?
Your link point to **VMware Workstation 16 Player** which is not for mac OSX.

I also tried a new install on virtualbox, unsuccessfull as well.

So for the moment I kept the one I managed to install and trying to see if it is stable.
Is there any tutorials or way to check if my install is clean and stable?

Such as:
1. access config files
2. how to remove unused app or settings such as adminer etc.
3. how to access files that are on the drive without nextcloud (in case of a crash or big issue)?

I did the security check with nextcloud on my install got the A+ rating so on this side it's good.

Thanks

**Comment by enoch85** [comment]
Basically, 

1. Install Ubuntu 20.04 server on a VM or barebone server.
2. Run the install script.
3. Done.

**Comment by Swiss-M** [comment]
Well ok but that’s what I tried to do with VirtualBox 6.1 and it failed several time and then I got by I don’t know which luck something and managed to launch the VM and run your script. 

On VMware I don’t know which one I have to use on macOSX in order to make it works, I tried Fusion but got multiple errors when trying to launch the VM after loading the .ova

There is so many differnent VMware and the one you used in your video turorial doesn’t exist anymore, so I m a bit lost for a newbe.

**Comment by enoch85** [comment]
For Mac, you should run Fusion. But running a server from your laptop, really? :)

**Comment by Swiss-M** [comment]
I have an old mac mini server that I use especially for this yes ;) it is made for that 

Last question this is why I am a bit concern on the stablility of this install.
I have upload 86 Gb of data on the nextcloud to test it out
_I m running into some 403 Forbidden etc. so I believe something might be wrong._ 

But in term of space on the disk this is weird:

This is disk n°1 (I believe the OS, ubuntu and NC)
[https://imgur.com/MmFDxZs](url)

This is disk n°2 (my actual storage for NC)
[https://imgur.com/mVeYhxd](url)

This is from NC dashboard showing that I m using 86 Gb
[https://imgur.com/GyZwxDm](url)

What are the extra 164 Gb is it a nextcloud things or is it related to the VM itself ?
How can I check what is inside the 2TB.vdi ?

PS: I m retrying to run the .OVA on VMware Fusion tonight

**Comment by enoch85** [comment]
> I have an old mac mini server that I use especially for this yes ;) 

Touché! 

> I m running into some 403 Forbidden etc. so I believe something might be wrong.

Seem like something is off yes.

I've installed it on several Mac with fusion where VirtualBox failed (which it usually does btw).

Let me know the result. :)

**Comment by Swiss-M** [comment]
@enoch85 

> Let me know the result. :)
It worked on VMware Fusion 11 (had to change settings inside the mac preferences)

So I have a clean fresh install to build on! Thank's a lot for these scripts.

My last newbie question is how do I place my virtual drive on my external 2 Tb HDD?
[https://imgur.com/Kx2JEBb](https://imgur.com/Kx2JEBb)

The install is on the SSD of my mac and I would like the whole 2Tb Virtual Drive to be on my external USB 3 HDD how do I do that?

Thank you

**Comment by enoch85** [comment]
No worries, just spread the word! :)
