### ISSUE TITLE
Download 

### ISSUE THREAD

**Issue by AnnymousID** [nextcloud/vm#1697]
**NextCloud cannot install the service normally and cannot start normally.**

**Download Nextcloud-VM.ova File**

**Download URL:**
https://download.nextcloud.com/vm/Nextcloud-VM.ova

**import OVA File in VMwareWorkstations16Pro**

**PowerOn VMs 

prompt:**

Fetching all the variables from lib.sh...
Testing if network is OK...
Checking connection...
curl: (52) Empty reply from server
curl didn't produce a 200 status, is the site reachable?
Setting correct interface...
Checking connection...      
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	github.com
Address: 192.30.255.113

Testing if network is OK...
Checking connection...
curl: (52) Empty reply from server
curl didn't produce a 200 status, is the site reachable?

Nextcloud VM - 2020

Network NOT OK. You must have a working network connection to run this script. Please post this issue on: https://github.com/nextcloud/vm/issues

**Comment by enoch85** [comment]
Hi, please try the full feathered VM instead of the scaled down one: https://github.com/nextcloud/vm/releases/tag/20.0.1

Report back the results.

Thanks!
