### ISSUE TITLE
Syntax Error?

### ISSUE THREAD

**Issue by EDavidF** [nextcloud/vm#17]
When I run `sudo nextcloud_install_production.sh ` on US16.04 clean install, I get:
`Checking server OS and version...
nextcloud_install_production.sh: 75: nextcloud_install_production.sh: Syntax error: redirection unexpected`
Any ideas?

**Comment by enoch85** [comment]
@EDavidF Hmm.... that shouldn't happen, and it works here.

Could you please try to find the cause so that I can fix it?

Thanks!

**Comment by enoch85** [comment]
oh, you have to run `sudo bash` no just `sudo`.

**Comment by EDavidF** [comment]
On August 4, 2016 10:16:37 AM MST, Daniel Hansson <notifications@github.com> wrote:
>oh, you have to run `sudo bash` no just `sudo`.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/vm/issues/17#issuecomment-237620453

Will try that. I miss-typed my orig post. I did use <sudo sh...>. (Away from machine now and on phone. Will re-try when I get back. Thank you!)

**Comment by enoch85** [comment]
@EDavidF I just tested a fresh install with Ubuntu 16.04, and there where no such error. Maybe it's temporary. Please let me know if it persists.
