### ISSUE TITLE
nextcloud-startup-script.sh - Your current version are still not compatible with the version required to run this script.

### ISSUE THREAD

**Issue by h45h3ncryp73d** [nextcloud/vm#1704]
## Steps to reproduce
1. Run sudo bash nextcloud_install_production.sh
2. Reboot
3. Login (as newly added user) to continue setup ...

## Expected behaviour
Setup should probably finish and install NC

## Actual behaviour
Error - Your current version are still not compatible with the version required to run this script?

## Server configuration
2 vCPU / 4GB ECC RAM / 160GB + 1TB

**Nextcloud server version:**
N/A

**Server OS** (Ubuntu server is default)
Ubuntu LTS 20.04.1

**How did you install the VM?** (Scripted install from master **OR** Released version)
master

## Network
**Do you use DHCP?**
No

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots
https://0bin.net/paste/VrL9D2I4#Gg6nn+Fx+NbXZGYsgc2BRI1LNjdrDUvWflULeYeOZMu

#### Log file (/var/log/nextcloud/nextcloud.log)
N/A

#### Installation log (command output)
https://0bin.net/paste/VrL9D2I4#Gg6nn+Fx+NbXZGYsgc2BRI1LNjdrDUvWflULeYeOZMu

#### Screenshoots
N/A

**Comment by enoch85** [comment]
You didn't mount the data disk properly, or the data disk is unavailable. Another reason might be a failing internet connection, or permission issues.

None of the above are caused by the scripts anyway.

If you need help installing, please check this out: https://shop.hanssonit.se/product/installation-of-nextcloud/

**Comment by h45h3ncryp73d** [comment]
My experience is that script doesn't do well on VPS with Ubuntu LTS 20.04.1 and disks set in LVM group. When disks are setup in ordinary manner - without LVM everything went fine ...
