### ISSUE TITLE
MariaDB Fails to Start After Upgrade

### ISSUE THREAD

**Issue by ozinfotech** [nextcloud/vm#1705]
## Steps to reproduce
1. Log in to Nextcloud via PuTTY
2. Run `sudo bash /var/scripts/menu.sh`
3. Choose the option to update Nextcloud

## Expected behaviour
Usually this process goes quite smoothly without any hiccups and the system updates.

## Actual behaviour
MariaDB did not start in the middle of the upgrade. The script continued, and then showed it had worked successfully, but then I could not log in to Nextcloud nor could any of the desktop clients. For some reason, I thought we had already purged MariaDB and was using something else.

## Server configuration

**Nextcloud server version:** 20.0.0

**Server OS** Ubuntu 20.04.1 LTS

**How did you install the VM?** VM purchased from Hansson IT

## Network
**Do you use DHCP?** Yes

**Is port 80 and/or 443 open?** Yes, both

## Logs
Had to revert to backup due to cloud being in production. Was not able to get logs at the time, but can do so later tonight when users are not in the application.

#### Screenshoots
https://imgur.com/a/6oxeFHO

**Comment by szaimen** [comment]
@enoch85 MariaDB?

**Comment by enoch85** [comment]
Yeah, probably a several year old VM.

It went like this:

MySQL ---> MariaDB ---> PostgreSQL.

**Comment by szaimen** [comment]
Okay, and is the update script even meant to be still compatible with MariaDB?

**Comment by enoch85** [comment]
No, It should be blocked: https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L110

This is the main reason why we put that check there in the first place. It' checks for mysql-common which is a part of MariaDB as well.

@ozinfotech Please revert to backup, change DB to PostgreSQL. I'll go ahead and add a check for Mariadb as well.

**Comment by enoch85** [comment]
I was wrong, the script doesn't check for `mysql-common`....

**Comment by ozinfotech** [comment]
I reverted from backup, but I'm not sure how to change to PostgreSQL. We should have changed to it during our last support session with @enoch85 with ticket number **#15777 Upgrade database to PostgreSQL**. This was on August 21.

**Comment by enoch85** [comment]
Sorry @ozinfotech Please try again.

Also the output of: `sudo dpkg -l | grep mariadb` would be interesting.

**Comment by ozinfotech** [comment]
Here is the output. I wanted to make sure I didn't need to do anything else before I ran the script again:

```
[redacted]@cloud:/home/[redacted]# sudo dpkg -l | grep mariadb
ii  libmariadb3:amd64                      1:10.3.25-0ubuntu0.20.04.1                  amd64        MariaDB database client library
ii  mariadb-client-10.2                    10.2.32+maria~xenial                        amd64        MariaDB database client binaries
ii  mariadb-client-core-10.2               10.2.32+maria~xenial                        amd64        MariaDB database core client binaries
ii  mariadb-common                         1:10.3.25-0ubuntu0.20.04.1                  all          MariaDB common metapackage
iF  mariadb-server-10.2                    10.2.32+maria~xenial                        amd64        MariaDB database server binaries
ii  mariadb-server-core-10.2               10.2.32+maria~xenial                        amd64        MariaDB database core server files
```

**Comment by ozinfotech** [comment]
And 

> Yeah, probably a several year old VM.
> 
> It went like this:
> 
> MySQL ---> MariaDB ---> PostgreSQL.

I purchased this from the old TechAndMe site in late 2017. So it definitely is older. It's been excellent for us though.

**Comment by enoch85** [comment]
Hmm, maybe we never purged the MariaDB while upgrading to PostgreSQL...

Do you use MariaDB for anything else? If not it can safely be removed.

You can check which DB Nextcloud is using with: `sudo grep db /var/www/nextcloud/config.php`

**Comment by ozinfotech** [comment]
I've left Nextcloud alone and not installed anything else other than what was already on the virtual machine I downloaded. I'm going to purge MariaDB, since it appears PostgreSQL (**psql**) is the one showing in the _config.php_ file. I'll do a couple of incremental backups in between steps just to see if I can get everything squared away and updated.

**Comment by enoch85** [comment]
Sounds good, please let me know the final result!

**Comment by ozinfotech** [comment]
I was able to purge MariaDB and everything was still running fine. Yet after the Nextcloud update, I get the following error when trying to go to the web site:

**Service Unavailable**

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
_Apache/2.4.41 (Ubuntu) Server at subdomain.domain.com Port 443_

These are the error I saw during the script: https://imgur.com/a/6Xh3M0i

**Comment by szaimen** [comment]
hm... I've thought I've fixed those error mesages with #1702 - and they don't lead to the server getting unavailable, afaik.
Maybe you could share your nextcloud log?
I'm pretty sure that it will help to debug why your server doesn't work after updating it.

**Comment by ozinfotech** [comment]
@szaimen Is there a way to send a private message? I'd rather not have the log files public.

**Comment by szaimen** [comment]
Of course, just send it to my mail-address (visible on my github profile page).
or use a pastebin...

**Comment by ozinfotech** [comment]
Email sent.

**Comment by enoch85** [comment]
Probably due to that Redis got upgraded.

Have you tried rebooting the server?

**Comment by ozinfotech** [comment]
***facepalm*** Oh boy, do I feel like a dunce. Yup @enoch85 that did the trick.

Rebooting: the cause of, and the solution to, many computer problems.

**Comment by ozinfotech** [comment]
Thanks @enoch85 and @szaimen!

**Comment by enoch85** [comment]
Glad you solved it!

**Comment by enoch85** [comment]
![image](https://user-images.githubusercontent.com/4511254/102238579-3232d080-3ef6-11eb-9904-2a8fcf817c59.png)
