### ISSUE TITLE
Fix Shellcheck warning

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1707]
Check warning on line 1228 in lib.sh
GitHub Actions / Shellcheck testing

lib.sh#L1228

[shellcheck] reported by reviewdog 🐶
Don't use variables in the printf format string. Use printf '..%s..' "$foo". [SC2059](https://github.com/koalaman/shellcheck/wiki/SC2059)

Raw Output:
./lib.sh:1228:16:info:Don't use variables in the printf format string. Use printf '..%s..' "$foo". [SC2059](https://github.com/koalaman/shellcheck/wiki/SC2059)

**Comment by szaimen** [comment]
Is this still a thing?

**Comment by enoch85** [comment]
Yes I think so. Just didn't have the time.

**Comment by enoch85** [comment]
It's the spinner loading function:

spinner_loading() {
    pid=$!
    spin='-\|/'
    i=0
    while kill -0 $pid 2>/dev/null
    do
        i=$(( (i+1) %4 ))
>>>>>>>>        printf "\r[${spin:$i:1}] " # Add text here, something like "Please be patient..." maybe?
        sleep .1
    done
}
