### ISSUE TITLE
Domain not found (activate-ssl.sh)

### ISSUE THREAD

**Issue by Andy1256** [nextcloud/vm#171]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

In which files does the domain name have to be registered?
Or is this Script only for the VM and not for manually nextcloud Install?

Thanks for your Answer!

## Server configuration

**Server version:** (see your admin page)
Nextcloud 11

**VM version** (master / released version)
Migrating from ownCloud 9 self hosted.
Not the Nextcloud VM.

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?**
Yes, with Reserved.

**Is port 80 and/or 443 open?**
Yes, 443 is open.

## Logs / Screenshots

Checking if Domainname exists and is reachable...
Nope, it's not there. You have to create Domainname and point it to this server before you can run this script.

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Without the domain in question it's hard to pin down the error here. Is it reachable when you visit it from any other computer? Have you pointed the domain name to the server you run the script from?

Running from master shouldn't be an issue, as the [description](https://github.com/nextcloud/vm#build-your-own-vm-or-install-on-a-vps) says it needs to be a clean Ubuntu server. 

And yes, the scripts in this repo are written with the VM in mind, but that doesn't mean they won't work on any system.

**Comment by Andy1256** [comment]
How do I make this pin to the server, maybe I have do this wrong?
Yes, i can open the Webinterface under the Domain Adress from another Computer.

**Comment by enoch85** [comment]
The scripts work without any issue here. I think it's very strange that the scripts doesn't recognize the domain as it runs a simple `wget` [(here)](https://github.com/nextcloud/vm/blob/master/lets-encrypt/activate-ssl.sh#L189) and if the check fails you get the error message.

Did the rest of the scripts work?

Closing as this is not an issue.

**Comment by williamvdh** [comment]
I have exactly the same problem. The script gives the error "Nope, it's not there. You have to create Domainname and point it to this server before you can run this script." while the port (443) is open and the DNS settings are correct. A little earlier (5 rows or so) the SSL script shows the correct external IP. I have tried reinstalling 6 times (removing VM files, extracting again, etcetera): 3 times with VMware and 3 times with VirtualBox. URL: eucloud.nl and IP 80.100.47.83.

**Comment by enoch85** [comment]
@williamvdh It's most likely a firewall or DNS issue. I tried to reach your domain and IP with both curl and wet, but non of them succeeds.

When did you change the DNS? Sometimes it can take up to 48 hours before the domain name is properly propagated: https://www.whatsmydns.net/#A/eucloud.nl

**Comment by williamvdh** [comment]
@enoch85 Thanks for checking, but the server wasn't running anymore, I just started it up again.  It is reachable: https://eucloud.nl/

**Comment by enoch85** [comment]
Ok, you have to put the domain as trusted domain, then it will work.

**Comment by williamvdh** [comment]
The setup script is not finished yet.. I could not install Let's Encrypt (hence the SSL error) nor the online text editor. So the beforemtnioned issue is still there.. Regarding propagation, 20/21 DNS servers are up-to-date, so after trying 6 times it would be very coincidental that is was a propagation problem.

**Comment by enoch85** [comment]
This issue is now fixed. Download the lates master and try again: `wget https://raw.githubusercontent.com/nextcloud/vm/master/lets-encrypt/activate-ssl.sh && sudo bash activate-ssl.sh`

**Comment by williamvdh** [comment]
@enoch85 Thanks for the very quick fix! The basic setup did work now and the SSL is correct. However, alost the same error message is popping up when trying to install Collabora via collabora.sh (Checking if office.eucloud.nl exists and is reachable... Nope, it's not there. You have to create office.eucloud.nl and point it to this server before you can run this script.)

**Comment by enoch85** [comment]
@williambargent Ok, I'll look into that as well.

**Comment by enoch85** [comment]
@williambargent Done. :)

**Comment by williamvdh** [comment]
That did the trick :) Thanks!
