### ISSUE TITLE
"Error updating .htaccess file" at the end of the update process

### ISSUE THREAD

**Issue by e-caste** [nextcloud/vm#1715]
## Steps to reproduce
1. `sudo bash /var/scripts/update.sh`

## Expected behaviour
The update finishes correctly.

## Actual behaviour
At the end of the update I get the following message:
```
Restoring the status of apps. This can take a while...
Setting RewriteBase to "/" in config.php...
System config value htaccess.RewriteBase set to string /
Error updating .htaccess file, not enough permissions or "overwrite.cli.url" set to an invalid URL?
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess failed
Posting notification to users that are admins, this might take a while...
```
After this error is thrown, everything works correctly, so I wouldn't classify it as a critical bug. The only exception is that a new login from the iOS Nextcloud Talk app does not work unless I add the line `'overwriteprotocol' => 'https',` to `/var/www/nextcloud/config/config.php` (only the first time this error presents itself, then it is saved).  
This error has begun appearing after I had manually modified the config file I mentioned above. I have not modified the permissions of the .htaccess file mentioned in the error message.

## Server configuration

**Nextcloud server version:** 20.0.3

**Server OS** Ubuntu Server 18.04

**How did you install the VM?** Scripted install from master

## Network
**Do you use DHCP?**
No, static IP.

**Is port 80 and/or 443 open?**
Only 80 since I am using a reverse proxy on another VM.

## Logs / Screenshots

See error messages above.

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by szaimen** [comment]
@e-caste what is `overwrite.cli.url` set to in config.php?

**Comment by e-caste** [comment]
@szaimen it is set to `'https://subdomain.domain.tld'` (where subdomain, domain, and tld are actually valid values, I'm just censoring it here). I am behind a reverse proxy, so I'm not sure if that value is correct, or even if I should set it. Some online tutorials suggested to set it to this value, so that's why I did it.

Output of `sudo ls -l /var/www/nextcloud/.htaccess && sudo ls -l /mnt/ncdata/.htaccess`:
```bash
-rw-r--r-- 1 www-data www-data 3032 Dec  9 20:30 /var/www/nextcloud/.htaccess
-rw-r--r-- 1 root www-data 542 Jan 22  2020 /mnt/ncdata/.htaccess
```

**Comment by szaimen** [comment]
> ```shell
> -rw-r--r-- 1 root www-data 542 Jan 22  2020 /mnt/ncdata/.htaccess
> ```

I guess here lies the problem.
Please try `sudo chown www-data:www-data /mnt/ncdata/.htaccess`, run the update script again and report back. Thanks!

**Comment by e-caste** [comment]
@szaimen thank you! Unfortunately for now I can't check if this actually fixes my issue, since the script detects the latest version as already correctly installed:
```
Checking for new Nextcloud version...
You already run the latest version! (20.0.3)
```

**Comment by szaimen** [comment]
Hm... @enoch85 what do you think could the problem be here?

**Comment by enoch85** [comment]
> what do you think could the problem be here?

Hmm, I have no idea actually. Never seen this before.

The latest update script sets the correct permissions if one file 3 levels down have the wrong permissions. So it's not a permission issue I think.

@szaimen `root:www-data` is actually correct. It's part of the secure permissions that the VM runs on. Though testing `www-data:www-data` would be nice just to rule that one out.

**Comment by szaimen** [comment]
@e-caste Maybe this is the problem:
https://help.nextcloud.com/t/not-enough-permissions-when-trying-to-setup-pretty-urls/38964/8

**Comment by szaimen** [comment]
> @szaimen it is set to `'https://subdomain.domain.tld'`

The correct value should be `'https://subdomain.domain.tld/'`

**Comment by enoch85** [comment]
I just checked how we set the domain using the scripts, so this must have been done manually. We do it correctly:

https://github.com/nextcloud/vm/blob/master/network/trusted.sh#L21

**Comment by e-caste** [comment]
The update from 20.0.3 to 20.0.4 went fine with the permissions suggested by @szaimen above (`sudo chown www-data:www-data /mnt/ncdata/.htaccess`). 
Also, I don't have a trailing slash in the `overwrite.cli.url` parameter of `config.php` and it seems to work fine. 
You can close this issue if you think you have all the info you need.

**Comment by enoch85** [comment]
This is now fixed for everyone.
