### ISSUE TITLE
Nextcloud vm spam my dns server with queries pointed to it own

### ISSUE THREAD

**Issue by k-matti** [nextcloud/vm#1720]
Netplan setting of VM with Nextcloud (I use menu.sh to set this network):
![image](https://user-images.githubusercontent.com/66017397/102105885-3694b600-3e30-11eb-822e-5acc6db1969a.png)

I have around 1000 queries in my pihole instance:

![image](https://user-images.githubusercontent.com/66017397/102105997-575d0b80-3e30-11eb-80df-d75430577de9.png)

192.168.0.55 is my Nextcloud vm IP

**Comment by enoch85** [comment]
@szaimen?

**Comment by szaimen** [comment]
Hm... @k-matti do those requests happen every 5 minutes? For me this sounds like the nextcloud background jobs somehow access the nextcloud URL. But without further debugging from your side I am only able to guess...

**Comment by szaimen** [comment]
@k-matti please reopen with more info.
