### ISSUE TITLE
Login only after complete startup

### ISSUE THREAD

**Issue by leenen** [nextcloud/vm#1723]
## Steps to reproduce
1. Startup VM
2.
3.

## Expected behaviour
The startup should be completed before presenting the login request

## Actual behaviour
The login prompt should appear after the boot process reached the cloud init target

## Server configuration
standard
**Nextcloud server version:** (see your admin page)
20.04.1
**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Released version
## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
both open
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Sorry, I don't understand this issue. Could you be more specific please?

**Comment by leenen** [comment]
Hi Daniel,

 

As you can see in the screen copy attached, the login prompt appears before the startup process has come to an end. This means one better waits a while before giving the login credentials.

 

Regards,

John Leenen

**Comment by enoch85** [comment]
Hi,

That seems to be some kind of raceconfition in Ubuntu. 

Nothing that we can solve in the VM. Please make a bug report upstream.

Thanks!
