### ISSUE TITLE
UUID does not change to bare MAC even after changing appropriate files

### ISSUE THREAD

**Issue by UNlDAN** [nextcloud/vm#1726]
I have no idea who came up with UUIDs when MACs have worked just fine for years. In any case, I tried changing the proper values for Ubuntu to send MAC and not UUID and it still won't work. Thank you for your assistance.

## Steps to reproduce
1. Make a hyper-v VM with Ubuntu and give it a random MAC. Now you have an IP e.g 192.168.1.10
2. Install nextcloud-vm then change the MAC 
3. Edit  dhclient.conf  to send MAC.
4. Reboot
5. Check the IP address, it is the same

## Expected behaviour
It should have a different IP set in the router's DHCP reservation table. 192.168.1.11

## Actual behaviour
The same IP remains

## Server configuration

**Nextcloud server version:** **20**

**Server OS** (Ubuntu server is default) **Ubuntu**

**How did you install the VM?** (Scripted install from master **OR** Released version) **Script**

## Network
**Do you use DHCP?** **Yes**

**Is port 80 and/or 443 open?** **Yes**

## Logs / Screenshots

[Paste of /etc/dhcp/dhclient.conf :](https://0bin.net/paste/MlOmPvJr#r-TdolaQ97nbQspjkKxFvU/eYBSRRRKsa72CfISd1qr)

[Paste of "/etc/netplan/01-netcfg.yaml"](https://0bin.net/paste/R8JGX1vs#eKMvXZz9xu0+BM5VMX8mHYQYpQ0eVbZOz0zYRI7DyVQ)

#### Log file (/var/log/nextcloud/nextcloud.log)
[Paste of /var/log/nextcloud/nextlcoud.log :](https://0bin.net/paste/tl-r2Ltw#OkmiUoyic5qHOQvafFYC1ReBVsQR5QSOD2d24zOKGHT)

#### Paste of "ip a" in ubuntu

```


1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 56:b6:11:11:11:25 brd ff:ff:ff:ff:ff:ff
    inet 192.168.162.127/24 brd 192.168.162.255 scope global dynamic eth0
       valid_lft 689882sec preferred_lft 689882sec
    inet6 fe80::54b6:11ff:fe11:1125/64 scope link
       valid_lft forever preferred_lft forever

```

**Comment by enoch85** [comment]
Thanks for your report! :+1: 

I never had issues with locking the DHCP address in any firewall, ever. I don't know if you have some kind of special config?

Try setting static IP with the static IP script instead. You can find it in the Menu script. Choose "Server Configuration".

Hope it helps!

**Comment by enoch85** [comment]
`56:b6:11:11:11:25` <--- btw, that seems to be a valid MAC address.

**Comment by enoch85** [comment]
You could also try `dhclient` from your command line.

**Comment by UNlDAN** [comment]
Thank you boss. Always appreciate your efforts.

**Comment by UNlDAN** [comment]
Will report back dhclient after.

**Comment by enoch85** [comment]
@UNIDAN How did it go?

**Comment by UNlDAN** [comment]
> @UNIDAN How did it go?

I have not been able to go to the location yet, I will be back there in a few weeks. Will make sure to report back.

**Comment by UNlDAN** [comment]
> @UNIDAN How did it go?

Did not work. It failed to get the IP/

**Comment by enoch85** [comment]
You can by support if you need hands on help: https://shop.hanssonit.se/product/installation-of-nextcloud/

**Comment by UNlDAN** [comment]
> You can by support if you need hands on help: https://shop.hanssonit.se/product/installation-of-nextcloud/

Thank you! I ended up reinstalling the VM. Will definitely keep it in mind next time.
