### ISSUE TITLE
morph027 janus repo not working anymore for bionic

### ISSUE THREAD

**Issue by himpierre** [nextcloud/vm#1727]
## Steps to reproduce
1. add morph017 janus repo
2. do an apt update
3. errot occurs 

## Expected behaviour
apt update should run fine.

## Actual behaviour
```
Err:11 https://packaging.gitlab.io/janus/bionic bionic Release
  404  Not Found [IP: 35.185.44.232 443]
Reading package lists... Done                       
E: The repository 'https://packaging.gitlab.io/janus/bionic bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

This is the apt file:
```
root@signaling:/etc/apt/sources.list.d# cat morph027-janus.list
deb [arch=amd64] https://packaging.gitlab.io/janus/bionic bionic main
root@signaling:/etc/apt/sources.list.d#
```

## Server configuration

**Nextcloud server version:** 20.0.4

**Server OS** Ubuntu Bionic

**Comment by szaimen** [comment]
Please have a look here: https://gitlab.com/packaging/janus/-/issues/1

**Comment by himpierre** [comment]
Thank you!

Am 17. Dezember 2020 17:10:05 MEZ schrieb szaimen <notifications@github.com>:
>Please have a look here: https://gitlab.com/packaging/janus/-/issues/1
