### ISSUE TITLE
Unable to locate package nats-server

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/vm#1728]
## Steps to reproduce
1. Execute the script talk.sh
2. Reinstall Spreed.
3. Install Talk Signaling.

## Expected behaviour
The package nats-server should be installed and the talk.sh script should finish.

## Actual behaviour
The package nats-server can not be found and installed and the talk.sh script fails. nats-server also can't be installed manually, even if following the instruction of the README.md on [this repo](https://gitlab.com/packaging/nats-server/).

## Server configuration

**Nextcloud server version:** 20.0.3 (snap, 20/latest)

**Server OS** Ubuntu Server 20.04

## Network
**Do you use DHCP?**
Yep.

**Is port 80 and/or 443 open?**
Yep.

#### Screenshots

![grafik](https://user-images.githubusercontent.com/23138465/102593046-a480fc00-4114-11eb-94a4-90d0b871c713.png)

**Comment by enoch85** [comment]
@morph027  Is there an issue with the packages?

**Comment by morph027** [comment]
Will doublecheck

**Comment by enoch85** [comment]
@Pilzinsel64 Is this the snap install of Nextcloud, or the VM?

**Comment by morph027** [comment]
> Will doublecheck

Hm, looks like the gitlab pages has been reset somehow. I've triggered a new build (including new version 2.1.9) and it works again. Sorry for the disruption!

```
root@cd18eaee2d2e:/# curl -sL -o /etc/apt/trusted.gpg.d/morph027-nats-server.asc https://packaging.gitlab.io/nats-server/gpg.key
root@cd18eaee2d2e:/# echo "deb [arch=amd64] https://packaging.gitlab.io/nats-server nats main" > /etc/apt/sources.list.d/morph027-nats-server.list
root@cd18eaee2d2e:/# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                           
Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease                                         
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease            
Get:5 https://packaging.gitlab.io/nats-server nats InRelease [1356 B]      
Get:6 https://packaging.gitlab.io/nats-server nats/main amd64 Packages [429 B]
Fetched 1785 B in 1s (1517 B/s)  
Reading package lists... Done
root@cd18eaee2d2e:/# apt-c
apt-cache   apt-cdrom   apt-config  
root@cd18eaee2d2e:/# apt-cache policy nats-server
nats-server:
  Installed: (none)
  Candidate: 2.1.9-p0
  Version table:
     2.1.9-p0 500
        500 https://packaging.gitlab.io/nats-server nats/main amd64 Packages
```

**Comment by Pilzinsel64** [comment]
I tried to installed it manually too, and it didn't work.
I am on a Raspberry Pi 4 (4GB RAM) with Ubuntu Server 20.04(.10 I guess). I downloaded the "talk.sh" and "fetch_lib.sh" and edited the occ command from "sudo -u www-data php ..." to "nextcloud.occ" because I am using the latest stable snap version.

**Comment by morph027** [comment]
Ah, thats the point. I'm not building for arm right now. I could do, but i'm not sure if all the other packages are available for arm.

**Comment by enoch85** [comment]
@morph027 If possible to build for ARM please do. :+1: 

@Pilzinsel64 You should try out the VM instead which the scripts were built for, not the snap. :)

**Comment by enoch85** [comment]
You could use the build scripts to build the whole VM on the RPi 4, but you'd have to start clean. FYI.

**Comment by morph027** [comment]
@Pilzinsel64 can you show me an example of your sources list like

`cat /etc/apt/source.list /etc/apt/sources.list.d/*`

I need to know the architecture to build for ;)

**Comment by morph027** [comment]
But just having nats does not help. signaling server a.k.a. high performance backend also needs to be build for other architectures. Not really a problem, just takes a while to setup the build process (need to incorporate my own private build server as gitlab runners can't run arm images yet).

**Comment by morph027** [comment]
nats-server packages are available for amd64, arm6, arm7 and arm64 now :rocket:

**Comment by enoch85** [comment]
> @Pilzinsel64 can you show me an example of your sources list like

@Pilzinsel64 Please provide what @morph027 asked for and I'll go ahead and close this.

Thanks! :+1:

**Comment by Pilzinsel64** [comment]
I retired it now after you created the arm64 build and installing nats-server did work!

And as I guess, installing "signaling" still doesn't work.

But you said you need some infos from me.
The output of the command @morph027:
```
cat: /etc/apt/source.list: No such file or directory
cat: '/etc/apt/sources.list.d/*': No such file or directory
```

And the architecture is "Armv8 (64 Bit)".

Btw, thank you very much for your help and providing the arm64 builds. This scripts are very good, even for the snap version. There are only a few variables to edit (e.g. the occ command).

And about the VM on my raspberry pi ... I don't know if this is a good idea, because it's not a system with much power. Maybe in some years, when I have a real searver. For now the snap installation catches all my needs for a private instance. And I haven't to do a lot administration.

**Comment by enoch85** [comment]
And about a VM on my raspberry pi instead the snap .

You don't install it as a VM. You run the build scripts to build a server with the VM scripts. So, it's bare bone.

Numerous people did it in the past, and it runs very good (without any issues at all actually) since it's based on Ubuntu 20.04.

Give it a try. You will be amazed. :) https://github.com/nextcloud/vm#full-documentation

**Comment by enoch85** [comment]
Btw, is should be:

`cat /etc/apt/sources.list`
`cat /etc/apt/sources.list.d/*`

**Comment by Pilzinsel64** [comment]
Oh, then this looks more right:
![grafik](https://user-images.githubusercontent.com/23138465/102687408-26ddee80-41ef-11eb-9786-4c5b4183c478.png)

**Comment by morph027** [comment]
Okay, great, so arm64 builds are the proper way to go. I'm still struggeling a bit with the pipeline setup for crosscompile builds of signaling server. Will let you know, when it's done.

**Comment by morph027** [comment]
Okay, arm64 packages are available now.

I needed to disrupt the repo a bit as upstream versions differ from the ones is used (before upstream was versioned). The README has a note. I wasn't able to create a transition package due to file conflict between packages,

Existing installations will just work but won't get updates (as 0.2.0 is lower than YYYYMMDDHHMM), new installations will pull the proper version.

So in order to get updates, one needs to remove the talk app and start from scratch.

**Comment by szaimen** [comment]
@morph027 I've tried to reinstall the high-performance-backend and it was successful. Thanks for your work!

**Comment by enoch85** [comment]
@morph027 As always - excellent!

**Comment by OkhamG** [comment]
Hi, I'm getting the same error "Unable to locate package nats-server" on Ubuntu 22.04 and 24.04

@morph027 Do the packages still exist, please?

@enoch85 Do you have any ideas, please?

Best Regards

**Comment by skaylink-stefan-heitmueller** [comment]
Will have a look...

**Comment by morph027** [comment]
Will have a look.

**Comment by morph027** [comment]
Pipeline has been fixed, packages should be available.
