### ISSUE TITLE
Insallation issue... Bash /var/scripts/change_db_pass.sh failed

### ISSUE THREAD

**Issue by deek-f** [nextcloud/vm#1738]
## Steps to reproduce
1.Install nextcloud
2.
3.

## Expected behaviour
nextcloud installs

## Actual behaviour
this error on setp screen.

Bash /var/scripts/change_db_pass.sh failed (screenshot attached)
![failed](https://user-images.githubusercontent.com/76526708/103009313-85c4a000-452e-11eb-8478-60d7c321aeb9.PNG)

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
@deek-f 

Thanks for posting your issue.

How old is this VM?

**Comment by deek-f** [comment]
Hi Daniel,
Purchased in May this year & setting up as a brand new machine.

Thanks
Derek

**Comment by enoch85** [comment]
Okay, then that's probably too old to still being able to run the first setup properly.

We made some major changes to the startup script some months ago.

To test, please downlad the latest free VM. If that works then that's it. You'd then need to get the latest version from the shop.

I'll go ahead and close this since it's most likely the reason. If not. Just let me know. 👍🏻

**Comment by deek-f** [comment]
Wait, what?   That's why I purchased in may, because the version I had
previously purchased was too old...

**Comment by enoch85** [comment]
You can still modify the version you have by modifying the scripts from git history.

In your case, I think it would be enough to have a look at which scripts that are being downloaded and change that to the current locations.

Hope it helps!
