### ISSUE TITLE
Activate TLS script support for custom ports

### ISSUE THREAD

**Issue by robertoleons** [nextcloud/vm#1746]
## Steps to reproduce
1. Run the Activate TLS script from menu.

## Expected behaviour
This is more like a feature request than a bug. I have the requirement to deploy using a custom port (ex: 9443), I did the apache configuration changes and everything works fine, but I can't use the "Activate TLS" option, since the scripts have the ports 80 & 443 hardcoded. I would really appreciate it if the Let's Encrypt automated configuration would let me specify the custom ports wanted to be used.

## Actual behavior
Even if the local script is modified with the custom ports being used, the validation phase does not work, since it is referencing the default 80 & 433 ports.

## Server configuration

**Nextcloud server version: 20.0.4

**How did you install the VM?: Deployed OVA to a vSphere environment.

## Network
**Do you use DHCP?: No

**Is port 80 and/or 443 open?: No, I changed apache to 8081 & 9443

**Comment by szaimen** [comment]
@enoch85 ?

**Comment by enoch85** [comment]
No, LE works on the standard ports. If you need to use other ports because 80 and 443 are taken - get yourself a proxy. :)
