### ISSUE TITLE
redirect root e-mails & update procedure

### ISSUE THREAD

**Issue by mamama1** [nextcloud/vm#1755]
Hi

using the nextcloud vm, i have found that a massive amount of mails is waiting in the local root user and www-data mailbox (/var/mail/root, /var/mail/www-data).

These mails contain stuff like this:

> From root@myhost  Sat Sep  5 18:06:30 2020
> X-Original-To: root
> From: root@myhost (Cron Daemon)
> To: root@myhost
> Subject: Cron <root@files> /var/scripts/update.sh minor >> /var/log/nextcloud/update.log
> MIME-Version: 1.0
> Content-Type: text/plain; charset=UTF-8
> Content-Transfer-Encoding: 8bit
> X-Cron-Env: <SHELL=/bin/sh>
> X-Cron-Env: <HOME=/root>
> X-Cron-Env: <PATH=/usr/bin:/bin>
> X-Cron-Env: <LOGNAME=root>
> Date: Sat,  5 Sep 2020 18:06:30 +0200 (CEST)
> 
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> PHP Notice:  Trying to access array offset on value of type bool in /usr/share/php/PEAR/REST.php on line 187
> PHP Notice:  Trying to access array offset on value of type bool in /usr/share/php/PEAR/REST.php on line 187
> PHP Notice:  Trying to access array offset on value of type bool in /usr/share/php/PEAR/REST.php on line 187
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> 
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> Sourcing file `/etc/default/grub'
> Sourcing file `/etc/default/grub.d/init-select.cfg'
> Generating grub configuration file ...
> Found linux image: /boot/vmlinuz-5.4.0-45-generic
> Found initrd image: /boot/initrd.img-5.4.0-45-generic
> Found linux image: /boot/vmlinuz-5.4.0-42-generic
> Found initrd image: /boot/initrd.img-5.4.0-42-generic
> done
> /var/scripts/update.sh: line 35: shutdown: command not found

Besides the weird errors (PHP notice and "shutdown: command not found"), shouldn't these mails get delivered to an external mail address, preferably and by default?

Idk if I recall correctly but I think I have been asked about an admin mail address and that I have provided one.

Since this seems to be postfix(?), would I just create an alias in /etc/aliases to achieve my goal? Will this get screwed up with some later vm update?

Also: I'm running on nextcloud 19.0.6 currently but it constatly keeps telling me, that 20.0.4 is available. I haven't found any documentation on the upgrade procedure. Does the update script handle this and 20.0.4 is just not being considered stable yet? Do I have to run something like /var/scripts/update.sh major by myself? Do I have to just click update in the nextcloud admin webinterface?

Thanks!

**Comment by enoch85** [comment]
> Also: I'm running on nextcloud 19.0.6 currently but it constatly keeps telling me, that 20.0.4 is available. I haven't found any documentation on the upgrade procedure. Does the update script handle this and 20.0.4 is just not being considered stable yet? Do I have to run something like /var/scripts/update.sh major by myself? Do I have to just click update in the nextcloud admin webinterface?

Try `sudo bash /var/scripts/menh.sh` 20.0.4 is no issues at all. Runs fine on all my machines.

The other question is for @szaimen since he implemented the mail thing a while back.

**Comment by szaimen** [comment]
@mamama1 My recommendation would be to reinstall automatic-updates since we've fixed or at least redirect the error messages to the update logfile, now. Also smtp-mail should actually configure the alias file and automatically send error messages to your recipient address, so I am not sure what gets wrong here (I actually get error messages from cronjobs). I would suggest to reinstall smtp-mail as well.

**Comment by szaimen** [comment]
@mamama1 I wonder why your admin account doesn't seem to get updatenotifications. You should actually get this Nextcloud notification with those exact instructions: https://github.com/nextcloud/vm/blob/3c1070677be8b50615b80d094c0d37e40113e3fe/static/updatenotification.sh#L82-L87

**Comment by szaimen** [comment]
@mamama1 any update here?

**Comment by mamama1** [comment]
Hi

sorry for replying late.

> > Also: I'm running on nextcloud 19.0.6 currently but it constatly keeps telling me, that 20.0.4 is available. I haven't found any documentation on the upgrade procedure. Does the update script handle this and 20.0.4 is just not being considered stable yet? Do I have to run something like /var/scripts/update.sh major by myself? Do I have to just click update in the nextcloud admin webinterface?
> 
> Try `sudo bash /var/scripts/menh.sh` 20.0.4 is no issues at all. Runs fine on all my machines.

Thanks, I did sudo bash /var/scripts/update.sh as found in a PDF documentation and that did the trick...



> @mamama1 My recommendation would be to reinstall automatic-updates since we've fixed or at least redirect the error messages to the update logfile, now. Also smtp-mail should actually configure the alias file and automatically send error messages to your recipient address, so I am not sure what gets wrong here (I actually get error messages from cronjobs). I would suggest to reinstall smtp-mail as well.
> 
> 1. `sudo bash /var/scripts/menu.sh` -> `Server Configuration` -> `Automatic updates` -> reinstall
> 2. `sudo bash /var/scripts/menu.sh` -> `Server Configuration` -> `SMTP Mail` -> reinstall

Thanks, both executed and the test mail did arrive. Let's see how things will work.

BR
