### ISSUE TITLE
Using Web based updater to go from NC 18.0.12 to 19.0.6 gets stuck in maintenance mode at the end

### ISSUE THREAD

**Issue by bapjg** [nextcloud/vm#1756]
## Steps to reproduce
My system is on your Nextcloud VM, version 18.0.12. An invitation to update appeared on the user Admin screen, so I clicked to initiate the update to 19.0.6

Initial problems occurred due permission problems which were solved by 
     sudo chown -R www-data:www-data /var/www/nextcloud/

The update went well. To the question "Keep Maintenance Mode Active ?", I answered "No (for usage of the web based updater)" which is my case. This was confirmed by a text message "Maintenance mode will get disabled".

I then got the "Done with a tick mark" indication with a button "Go back to you nextcloud instance to finish the update", which I proceeded to click.

I then received a message (in French, as I am using the French version of the software) "Update required. Please use the command line updater as the automatique update is deactivated in config.php".

What should I do now ?

Thanks for any assistance or ideas.

## Expected behaviour
I expected the system to go out of maintenance mode and back to normal operation.

## Actual behaviour
See above

## Server configuration

**Nextcloud server version**: 18.0.12 trying to update to 19.0.6

**Server OS** Ubuntu 18.4.5
For info
apachectl -v					yielded Apache/2.4.29
php -v						yielded PHP 7.2.24-0Ubuntu0.18.04.7

**How did you install the VM?** Over a year ago so I have forgotten. From memory, I just started the supplied VM and answered the questions

## Network
**Do you use DHCP?**No, static IP

**Is port 80 and/or 443 open?**Using HTTP falls over to HTTPS

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Web based updater used
```

**Comment by szaimen** [comment]
@bapjg Thanks for the report! 

There is a reason why the permissions didn't allow to update your instance via the webupdater:
the VM actually includes an update script which doesn't run into any of those issues*, so please use the forum now that you've used the web updater. https://help.nextcloud.com/search?q=update

*) It is located here: `/var/scripts/update.sh`

**Comment by bapjg** [comment]
Thanks for your response.
As I have rolled back my VM to its pre-webUndate condition, I shall use the script that you suggested :
    /var/scripts/update.sh

**Comment by szaimen** [comment]
Yes, that should certainly work, afaik.
`sudo bash /var/scripts/update.sh`

**Comment by enoch85** [comment]
@bapjg Since you're on 18.0.12 you need to run `sudo bash /var/scripts/update.sh minor`

Major versions needs to be done manually. You can get support here: https://shop.hanssonit.se/product/upgrade-between-major-owncloud-nextcloud-versions/

**Comment by bapjg** [comment]
Thanks to all who answered my cry for help.
With the various suggestions, I was able to upgrade my system to NC20 successfully.
Again, all my thanks to everybody
