### ISSUE TITLE
Update script should check if postgresql is used before updateing

### ISSUE THREAD

**Issue by horvan** [nextcloud/vm#1760]
If someone updates the VM on a server where Nextcloud-VM is driven by  Postgres-SQL and a MySQL-Server is installed the update-Script currently shows the message below:

### Message to surpress if PostgreSQL is used

![Bild_2021-01-10_120636](https://user-images.githubusercontent.com/5676367/104121117-4a9edb00-533c-11eb-8294-8ce324b79f9e.png)

This may be intended to make money or just as a warning that Mysql is not supported anymore. 

But If Postgres and MySQL are installed side by side this is a bug. 

So there should be a function to check which database driver is used in settings.php to avoid that message if it is not needed

That happens on Ubuntu 20.04 when the script is used to update to Nextcloud 20.04 Of course there is a way to do this manually by using the nextcloud-Updater. 

But the message itself is somewhat annoing.

### dpkg -l output

[pckglist.txt](https://github.com/nextcloud/vm/files/5792513/pckglist.txt)

##### Line 729 - 734
```bash
mariadb-client-10.3                  1:10.3.25-0ubuntu0.20.04.1                 amd64        MariaDB database client binaries
ii  mariadb-client-core-10.3             1:10.3.25-0ubuntu0.20.04.1                 amd64        MariaDB database core client binaries
ii  mariadb-common                       1:10.3.25-0ubuntu0.20.04.1                 all          MariaDB common metapackage
ii  mariadb-server                       1:10.3.25-0ubuntu0.20.04.1                 all          MariaDB database server (metapackage depending on the latest version)
ii  mariadb-server-10.3                  1:10.3.25-0ubuntu0.20.04.1                 amd64        MariaDB database server binaries
ii  mariadb-server-core-10.3             1:10.3.25-0ubuntu0.20.04.1                 amd64        MariaDB database core server files
```

##### Line 1094 - 1098
```bash
ii  postgresql                           12+214ubuntu0.1                            all          object-relational SQL database (supported version)
ii  postgresql-12                        12.5-0ubuntu0.20.04.1                      amd64        object-relational SQL database, version 12 server
ii  postgresql-client-12                 12.5-0ubuntu0.20.04.1                      amd64        front-end programs for PostgreSQL 12
ii  postgresql-client-common             214ubuntu0.1                               all          manager for multiple PostgreSQL client versions
ii  postgresql-common                    214ubuntu0.1                               all          PostgreSQL database-cluster manager
```

### Some more system information

````bash
          .-/+oossssoo+/-.                
        `:+ssssssssssssssssss+:`           -------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-2.11) 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-60-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 day, 12 hours, 38 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1224 (dpkg), 4 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/0 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon E5-2630 v4 (4) @ 2.199GHz 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: 00:02.0 Vendor 1234 Device 1111 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 6090MiB / 11981MiB 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/                            
  +sssssssssdmydMMMMMMMMddddyssssssss+                             
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
````
### Corrosponding section in config.php to check:

```php
 ),
  'datadirectory' => 'xxx',
  'dbtype' => 'pgsql',
  'version' => '20.0.4.0',
  'overwrite.cli.url' => 'xxx',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',

```

**Comment by enoch85** [comment]
The reason we check for MariaDB is this https://github.com/nextcloud/vm/issues/1705

Before that we only checked if PostgreSQL was configured in `config.php`. I added a PR to revert that commit, but I'm not sure that's the way forward yet.

**Comment by horvan** [comment]
I see your point, but by now some of us have a broken VM update script and have to use Nextclouds Updater because the script never working as it did before. So there should be a way round even for that. I'll take a look into the referenced one and apply the pr to test if it will work again.

**Comment by horvan** [comment]
In Fact the update.sh script relies on  the nextcloud_update.sh within the repo itself. So you can't change this without loosing funtionallity, because evry single instance out theere with a MySQL-Server beides the Postgress one installed while using the script initially will fail updateing now. 

So in my opion this has to be reverted untill there is a proper solution. Nextcloud will recive Updates in between. But right now. The Instances using V´M are not able to update anymore if there is something different than postgresql installed beside it.

**Comment by enoch85** [comment]
If you send a PR I'll review it.

This is not an issue for anyone as long as you do what's intended. Run Nextcloud, only Nextcloud, without having MySQL installed.

**Comment by enoch85** [comment]
@horvan No response here?

I'm leaning towards staying as it is to be 100% sure there's no mixup which leads to a destroyed server with old installations.
