### ISSUE TITLE
nextcloud webinterface down after installing apps

### ISSUE THREAD

**Issue by lawitzer84** [nextcloud/vm#1765]
## Steps to reproduce
1. logged in to the webinterface
2. installed apps: onedrive as external drive
3. webinterface wasn't reachable anymore

## Expected behaviour
nextcloud webinterface should work

## Actual behaviour
http error 500

## Server configuration

**Nextcloud server version:** (see your admin page)

20.0.4

**Server OS** (Ubuntu server is default)
Hannson IT nextcloud VM

**How did you install the VM?** (Scripted install from master **OR** Released version)
Hannson IT nextcloud VM
## Network
**Do you use DHCP?**
yes
**Is port 80 and/or 443 open?**
yes
#### Log file (/var/log/nextcloud/nextcloud.log)
```
[nextcloud.log](https://github.com/nextcloud/vm/files/5794273/nextcloud.log)

Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```
Fetching latest packages with apt...
[\] Updating lib...
[|] Setting secure permissions...
Creating possible missing Directories
chmod Files and Directories
[|] chown Directories
[\] chmod/chown .htaccess
An unhandled exception has been thrown:
Error: Interface 'OCA\Files_External\Lib\Config\IBackendProvider' not found in /                              var/www/nextcloud/apps/files_external_onedrive/lib/AppInfo/Application.php:38
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(444): include()
#1 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autol                              oad\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(108): c                              lass_exists()
#5 /var/www/nextcloud/lib/base.php(644): OC\AppFramework\Bootstrap\Coordinator->                              runRegistration()
#6 /var/www/nextcloud/lib/base.php(1091): OC::init()
#7 /var/www/nextcloud/console.php(49): require_once('/var/www/nextcl...')
#8 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#9 {main}Sorry but something went wrong. Please report this issue to https://git                              hub.com/nextcloud/vm/issues and include the output of the error message. Thank y                              ou!
sudo -u www-data php /var/www/nextcloud/occ config:system:set log_type --value=f                              ile failed

**Comment by szaimen** [comment]
Hey, thanks for the report!
Please track https://github.com/hevelius/files_external_onedrive/issues/50 for further for resolution.
