### ISSUE TITLE
Install process block when installing solr

### ISSUE THREAD

**Issue by BobSquarePants** [nextcloud/vm#177]
## Steps to reproduce
1. install VM with collabora, nextant
2.
3.

## Expected behaviour
no blocking during install process

## Actual behaviour
Stay block on that error:
[![Nextcloud_Community_VM_PRODUCTION-2017-03-20-06-.png](https://s28.postimg.org/vq9c5umyl/Nextcloud_Community_VM_PRODUCTION_2017_03_20_06.png)](https://postimg.org/image/sjesm82ih/)

## Server configuration

**Server version:** (see your admin page)
https://cloud.techandme.se/index.php/s/lTjoMr5smSYHIiM

**VM version** (master / released version)

**Updated from an older installed version or fresh install:**
Fresh

## Network
**Do you use DHCP?**
yes

**Is port 80 and/or 443 open?**
443 yes
80 was not

#### Screenshoots
[![Nextcloud_Community_VM_PRODUCTION-2017-03-20-06-.png](https://s23.postimg.org/w9rf9cp6z/Nextcloud_Community_VM_PRODUCTION_2017_03_20_06.png)](https://postimg.org/image/mcgegahl3/)

**Comment by Ark74** [comment]
Did you complete the installation  and startup script?
What are you running the script in? 
VM, VPS?

I've just tested and Solr is installing and working fine.
Please try again, if you see any error during the installation process report it.

**Comment by enoch85** [comment]
@Ark74 I've seen this behavior as well, don't know what's causing it tbh.

**Comment by Ark74** [comment]
It happens only when installing both collabora & nextant.
If you only install Nextant it doesn't show up.

**Comment by enoch85** [comment]
This is now fixed.

**Comment by BobSquarePants** [comment]
Did you have already an idea when the new release will be out with this fix ?
Thx for the quick and good job

**Comment by enoch85** [comment]
@BobSquarePants Easy, just download the latest script or extract the VM and run it again. It's in master and automatically downloaded.
