### ISSUE TITLE
Automatic Update Error

### ISSUE THREAD

**Issue by github-cli** [nextcloud/vm#1772]
## Steps to reproduce
automatic upgrade or run 
"sudo -u www-data php /var/www/nextcloud/occ db:convert-filecache-bigint" manually after
## Expected behaviour
no error message

## Actual behaviour
error message from automatic update (see screenshot)

## Server configuration

**Nextcloud server version:** (see your admin page)
20.0.5
**Server OS** (Ubuntu server is default)
Ubuntu Server

**How did you install the VM?** (Scripted install from master **OR** Released version)
hansson install script
## Network
**Do you use DHCP?**
no
**Is port 80 and/or 443 open?**
yes
## Logs / Screenshots

https://paste.ubuntu.com/p/g52HMCRZSZ/
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
https://paste.ubuntu.com/p/kgpPkZ4H7H/

```

#### Installation log (command output)
```
not a fresh install, error is from automatic update script
```

#### Screenshots
https://imgur.com/g1PTDPX

**Comment by szaimen** [comment]
@enoch85 this seems to me like a mail app issue...

**Comment by enoch85** [comment]
Yeah, 99% of the times it's apps installed causing these specific issues.

That's why we recommend to keep your installation as small as possible, and also keep backups and/or do snapshots before the upgrade is taking place.

Without more information it's hard for us to investigate the real cause.

**Comment by szaimen** [comment]
https://paste.ubuntu.com/p/g52HMCRZSZ/

@ChristophWurst is this issue already known?

**Comment by github-cli** [comment]
mail app is still working it seems
@enoch85 I have a backup and the install is still working so I could restore the VM from a few weeks ago.
the update took place automatically so a snapshot wasnt possible but I do backups every now and then
If you tell me what information you need, I will gladly provide it... If you think its a non-issue I can also just leave it as is

**Comment by enoch85** [comment]
I think one shouldn't run automatic updates if you care about stability: https://github.com/nextcloud/vm/blob/master/addons/automatic_updates.sh#L12-L13

Revert from backup if you don't loose important data (since it was an old backup) and then do a manual upgrade with the script. When done, remove automatic updates from `crontab`.

If the issue persists, do some more investigation (google the actual error for example) and tell us the cause so that we can fix it in the code. :+1:

**Comment by github-cli** [comment]
I dont experience any actual issues after this, I just thought I would report it to help.
I run nextcloud only for the family so absolute stability is not such an issue, if its gone for a day or two there is no issue, so I dont mind having automatic updates enabled.
But I just noticed that I do have a backup of the VM but the ncdata folder/share is on a separate drive, not sure if the "upgraded" database is on there as well and restoring would therefore be counterproductive.
anyhow, I dont want to take up your valuable time! if its not something worth investigating it looks like the vm is currently still running stable

**Comment by ChristophWurst** [comment]
> @ChristophWurst is this issue already known?

Well not this particular one but it's know that Mail ships some symphone libs that can cause conflicts with server or other apps. I think that explains the error you are experiencing.

**Comment by enoch85** [comment]
Thanks for confirming!
