### ISSUE TITLE
Issue encounter using the "Registration" app.

### ISSUE THREAD

**Issue by crispywisp** [nextcloud/vm#1783]
## Steps to reproduce
1. Install "Registration" app.
2. Logout Admin account.
3. Register an account with an e-mail.

## Expected behaviour
Error after clicking on the Send Link button.

## Actual behaviour
Error Message:
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.

## Server configuration

**Nextcloud server version:** (see your admin page)
Nextcloud 20.0.5

**Server OS** (Ubuntu server is default)
Operating System: | Linux 5.4.0-64-generic x86_64 (Ubuntu)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install

## Network
**Do you use DHCP?**
The server's IP is reserved.

**Is port 80 and/or 443 open?**
Yes.

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```https://0bin.net/paste/gXXl6qPN#MTef4d-sI5bRo2+1yRnfDuJ44+QTZUPifcEPy/6zKAs

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by szaimen** [comment]
@crispywisp Thanks for the report!
Please follow https://github.com/nextcloud/registration/issues/267 for further resolution.
