### ISSUE TITLE
Why uninstall `unattended-upgrades`

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#1785]
Hi, I'm just curious why the script uninstalls `unattended-upgrades`?

I have that package installed on all my debian/ubuntu machines so that they are updated automatically, but I noticed that the script uninstalls it.

**Comment by enoch85** [comment]
1. Unattended upgrades might mess with the kernel and crash the server
2. The /boot partition might become full if nothing is autoremived default behaviour
3. We use our own script which does everything for you, including Nextcloud and it's dependencies
4. The default settings in unattended upgrades are not "secure".

I've seen several issues with unattended upgrades,and had servers crash when rebioted due to reasons above when I was new with Linux. We have our own script which is better and xan be made automated.

**Comment by thejohnha** [comment]
It seems like an overreach for the nextcloud script to manage the OS. After all, Debian installs `unattended-upgrades` and `apt-listcharges` by default. I'll quote from the [Debian wiki](https://wiki.debian.org/UnattendedUpgrades):

"As of Debian 9 (Stretch) both the unattended-upgrades and apt-listchanges packages are installed by default and upgrades are enabled with the GNOME desktop. Rudimentary configuration is accessible via the "Software & Updates" application (software-properties-gtk)."

Shouldn't the nextcloud updater just focus on updating nextcloud and its components instead of managing the operating system?

I've managed hundreds of debian-based systems without any issues with `unattended-upgrades`. Which defaults are you referring to when you say that they are not "secure"?

**Comment by enoch85** [comment]
Well, you as an admin for several hundred of Debian systems have the experience to fix errors when they show up. A Windows user who's first experience with Linux is the VM does not have that capability.

Using unattended-upgrades is just a matter of time before it breaks your system, as it touches the kernel as well. Sure, you could configure it to be "safe", but it's not that by default.

And as I already said, if you want to keep your system up to date, use the built in script and do it manually. If you are living on the edge, just install unattended-upgrades again and be happy. :)

**Comment by thejohnha** [comment]
Thanks @enoch85 -- so just to be clear, if I install `unattended-upgrades` after the script finishes, there shouldn't be a conflict even if I choose the Automatic Update option in the vm script?

**Comment by enoch85** [comment]
> shouldn't 

You never know. I prefer to do manual updates to be 100% sure.

**Comment by thejohnha** [comment]
I see that `update.sh` updates the Nextcloud version, but I couldn't find where it updates the OS. Could you help me find where that happens please? Thank you.

(Also, shouldn't `apt-get` be used instead of `apt` throughout?)

**Comment by enoch85** [comment]
You need to do that by yourself, or you can get support here: https://shop.hanssonit.se/product/migrate-nextcloud-to-new-os-and-server-18-04/

**Comment by thejohnha** [comment]
I'm not referring to OS major version upgrades, I'm referring to regular security patches etc. that `unattended-upgrades` normally does for me. But if the script uninstalls `unattended-upgrades`, I'm trying to figure out how your nextcloud script manages OS updates. thank you Daniel!  ;-)

**Comment by szaimen** [comment]
I'd say it's here:
https://github.com/nextcloud/vm/blob/fd211640d1eebb79d807074e41b4e3f58d6f36a7/nextcloud_update.sh#L117
https://github.com/nextcloud/vm/blob/fd211640d1eebb79d807074e41b4e3f58d6f36a7/nextcloud_update.sh#L219

**Comment by enoch85** [comment]
@thejohnha 

The update script updates **all** dependencies for Nextcloud, *including* the OS stuff as you call it. :+1: Basically, no need for unattended upgrades if you don't like living on the edge.

**Comment by thejohnha** [comment]
Thank you very much pointing me to `nextcloud_update.sh:219`!  :-)

Also, regarding my comment about `apt` I have heard that it's best practice to use `apt-get` instead of `apt` in scripts... Thanks again, Daniel :-)
