### ISSUE TITLE
Nextcloud update.sh fails after Ubuntu update from 18.04 to 20.04 in VM

### ISSUE THREAD

**Issue by e-caste** [nextcloud/vm#1788]
## Steps to reproduce
1. On Ubuntu 18.04: `do-release-upgrade`
2. Restart after update is finished (without removing obsolete packages, that breaks Ubuntu in my case)
3. `sudo bash /var/scripts/update.sh`

## Expected behaviour
Nextcloud updates minor version correctly.

## Actual behaviour
Nextcloud update crashes with the following stacktrace. Note that I'm still able to use Nextcloud from the web and the mobile apps.
```
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: could not find driver in /var/www/nextcloud/lib/private/DB/Connection.php:72
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1449): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(892): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /var/www/nextcloud/lib/private/DB/Connection.php(202): Doctrine\DBAL\Connection->executeQuery()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): OC\DB\Connection->executeQuery()
#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(217): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /var/www/nextcloud/lib/private/AppConfig.php(345): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 /var/www/nextcloud/lib/private/AppConfig.php(110): OC\AppConfig->loadConfigValues()
#7 /var/www/nextcloud/lib/private/AppConfig.php(301): OC\AppConfig->getApps()
#8 /var/www/nextcloud/lib/private/legacy/OC_App.php(949): OC\AppConfig->getValues()
#9 /var/www/nextcloud/lib/private/Server.php(668): OC_App::getAppVersions()
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#11 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#12 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#13 /var/www/nextcloud/lib/private/ServerContainer.php(156): OC\AppFramework\Utility\SimpleContainer->query()
#14 /var/www/nextcloud/lib/private/Server.php(1677): OC\ServerContainer->query()
#15 /var/www/nextcloud/lib/private/Server.php(1017): OC\Server->getMemCacheFactory()
#16 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#17 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#19 /var/www/nextcloud/lib/private/ServerContainer.php(156): OC\AppFramework\Utility\SimpleContainer->query()
#20 /var/www/nextcloud/lib/private/Server.php(1977): OC\ServerContainer->query()
#21 /var/www/nextcloud/lib/private/Files/View.php(118): OC\Server->getLockingProvider()
#22 /var/www/nextcloud/lib/private/Server.php(395): OC\Files\View->__construct()
#23 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}()
#24 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet()
#26 /var/www/nextcloud/lib/private/ServerContainer.php(156): OC\AppFramework\Utility\SimpleContainer->query()
#27 /var/www/nextcloud/lib/private/Server.php(1324): OC\ServerContainer->query()
#28 /var/www/nextcloud/lib/base.php(595): OC\Server->boot()
#29 /var/www/nextcloud/lib/base.php(1091): OC::init()
#30 /var/www/nextcloud/console.php(49): require_once('/var/www/nextcl...')
#31 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#32 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ -V failed
```

## Server configuration

**Nextcloud server version:** 20.0.4
DB version: PostgreSQL 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit
PHP version:  7.2.24

**Server OS**
Ubuntu 20.04

**How did you install the VM?** Scripted install from master when the default was Ubuntu 18.04.

## Network
**Do you use DHCP?** No.

**Is port 80 and/or 443 open?** Yes, only using 443 behind reverse proxy.

## Logs / Screenshots

Possibly related, this was shown to me during the Ubuntu update from 18.04 to 20.04:
![Screenshot 2021-02-01 at 09 14 54](https://user-images.githubusercontent.com/48513706/106434365-c094ee80-6471-11eb-9249-1227bfe3a8fc.png)

 `sudo apt install postgresql-12 postregresql-client-12` yields
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package postgresql-12
E: Unable to locate package postregresql-client-12
```

**Comment by enoch85** [comment]
@e-caste Hi :wave: 

If you need help with upgrading your OS, you have an alternative here: https://shop.hanssonit.se/product/migrate-nextcloud-to-new-os-and-server-18-04/

You could also try to ask for help in the Nextcloud forum.

OS upgrades is nothing that the Nextcloud VM scripts will take care of. With that said, I've done several (probably about 50) upgrades as you described, and they never failed.

**Comment by e-caste** [comment]
Thank you, a quick web search pointed me in the right direction.  
What worked for me on Ubuntu 20.04:
`php --version` --> 7.4
`sudo add-apt-repository ppa:ondrej/php`
`sudo apt install php7.4 php7.4-pgsql php7.4-xml php7.4-zip php7.4-mbstring php7.4-gd php7.4-curl`
`sudo -u www-data php /var/www/nextcloud/occ -V` --> Nextcloud 20.0.4 (no exception anymore)
`sudo bash /var/scripts/update.sh`

<img width="827" alt="Screenshot 2021-02-03 at 11 27 17" src="https://user-images.githubusercontent.com/48513706/106734341-33899b00-6613-11eb-9162-e778fb865527.png">

**Comment by enoch85** [comment]
It's not perfect, but as long as it works I'm happy for you. :+1:

**Comment by e-caste** [comment]
@enoch85 thank you, just out of curiosity, is the imperfect part related to the separate ppa for php? I have read a comment by you on the Nextcloud forums where you advised against it since it doesn't provide automatic security updates. Would this be a problem if I update my Ubuntu VM frequently?
