### ISSUE TITLE
Working on root domain instead slash domain

### ISSUE THREAD

**Issue by ilijoski** [nextcloud/vm#179]
What should I change in the script for Nextcloud to be start like "root" service on http://hostname , instead on http://hostname/nextcloud ? 

I have installation by using this script, and after installation, manually changed the path on Apache server. Now nextcloud is running in root of hostname, but there is issue with built-in icons of Nextcloud:

http://cloud.ilijoski.mk/s/sjDs1Z7kyL1dl1X

As you can see there is no icons for drop-down menu, no upload icon, and few more icons not shown in this screenshot.

In source code of web browser i see this:
http://cloud.ilijoski.mk/s/nVVM48lMgrAaR1I

And if I remove "nextcloud" in path, I can see icon:
http://cloud.ilijoski.mk/s/EdJ8HynS3VCAKgx

'm not developer... I see the reason for problem, but I can't find right solution. Is there anything which I can change now (after installation), or I need to repeat installation with something changed on the script? 

Thanks in advance

**Comment by enoch85** [comment]
You don't need to change anything. If you used the scripts (both nextcloud_installation_production.sh & nextcloud-startup-script.sh) you should already have the root path without Nextcloud. 

Run the scripts again and don't change anything and you're all set.

**Comment by ilijoski** [comment]
Ok, but after running the script now, i receive the (expected) message that script should be run on clean server. 
Maybe I was not totally clear that I wrote, because now I will tell you specifically what would like to get:
I want nextcloud login page to be accessable on link http://myhost instead (by default after script) http://myhost/nextcloud .

I have changed the path for default webpage on Apache server to be /var/www/nextcloud (instead by default /var/www) , and now everything works good. Except some icons are not shown, because wrong generated path of them. 

And because of that I ask should I change something on the script, to be run (on clean server), and after instalation nexcloud login page to be on http://myhost, OR, maybe, I can change something now (on installed server) for icons issue to be fixed? 

Sorry for amateur questions :) Its not big issue, but anyway nextcloud will look better if have all icons on menus.

**Comment by enoch85** [comment]
Again, the default path will be: `http(s)://example.com/login` if you enter `example.com` (it will automatically redirect) if you run the SSL script. The installation is *not* complete by just running the installation script.

First of all, you are doing it wrong. You shouldn't change the default.conf, there already exists pre-configured config files in the sites-avaliable dir. Second, you should run the Let's Encrypt script (SSL) when doing the final setup running the second script that are *automatically* presented to you after a reboot when you have run the first install script.

Please read the instructions: https://github.com/nextcloud/vm#installation Please notice point 3 which will automatically take you to the second install script that does the final setup for you. :)

**Comment by ilijoski** [comment]
FYO, after running Let's Encrypt script (activate_ssl.sh), now nextcloud is not accessible at all :) I will reinstall server again, and run both scripts as u said, I hope that will go smooth :) Thank you!

**Comment by Ark74** [comment]
How did it go?

Actually you just run the installation script and everything else is presented to you as you go on the installation.
At this point in time you should not have issues with the script, i've just tested 30 minutes ago and it works fine.

**Comment by enoch85** [comment]
@Ark74 I'm pretty confident that the scripts are wokring. What I think is that @ilijoski only ran the install script then started to change stuff on his own which isn't working as the LE script expect the pre-configured stuff to be unchanged - in this case the pre-configured Apache conf files.

**Comment by ilijoski** [comment]
Yes, @enoch85 is right. Only one thing what I have changed after installation of (first script installation_nextcloud_production.sh) was on Apache that first webpage default path to be /var/www/nextcloud instead /var/www . When I run activate_ssl.sh script, i didn't make back changes, and maybe because of that now nothing is accessible. For me, amateur IT (which is obvious :) ) its better to reinstall blank new server, and run installation_nextcloud_production.sh , then activate_ssl.sh scripts. Instead troubleshooting where is the problem for not working. Just for update, after I run all tasks from begin, will update here for future users of nextcloud to know how to NOT play with config files if they are not sure :)

**Comment by enoch85** [comment]
@ilijoski You don't even have to download the scripts manually. Just follow the instructions once the VM is rebooted after the first script is done installing. :+1:
