### ISSUE TITLE
Elasticsearch migration for FTS?

### ISSUE THREAD

**Issue by Ark74** [nextcloud/vm#1794]
With the news of AWS forking Elastichsearch because of the licence change.
- https://www.elastic.co/pricing/faq/licensing
- https://aws.amazon.com/es/blogs/opensource/stepping-up-for-a-truly-open-source-elasticsearch/

For Fulltextsearch, if possible a transparent migration (7.10), should we move into it?
- https://opendistro.github.io

@daita 
@enoch85

**Comment by enoch85** [comment]
For me it doesn't matter, as long as we follow licensing regulations.

If a migration is the best option, then go for it. :+1:

**Comment by enoch85** [comment]
@Ark74 What do you think?

**Comment by Ark74** [comment]
I'll try to research and do some testing this weekend to see if this is even possible, then we might be able to drop some ideas on it.

**Comment by enoch85** [comment]
Thanks!

**Comment by Ark74** [comment]
I've done some testing.
Opendistro for Elasticsearch bundles several plugins and provides a security functionality redundant to readonly rest.

It would require to re-structure the way it works so far, but on the good side of things the images will come ready from upstream. I'll have to study more the subject in order to connect it to the Nextcloud VM.

@enoch85 if you allow me, let this open and I'll update according the progress I make, and hopefully submit a PR.

**Comment by enoch85** [comment]
Fine with me. Great job @Ark74!

**Comment by enoch85** [comment]
Hi @Ark74 Any progress here?

**Comment by Ark74** [comment]
Las time there where issues with the app.
I've seen there are updates, will try again.

**Comment by enoch85** [comment]
Hi @Ark74 Still issues with the app?

**Comment by enoch85** [comment]
Is this still valid?

**Comment by Ark74** [comment]
Sorry @enoch85  this project got buried over so many other stuff, I'll send a MR if I can move it forward.
Closing for now.

**Comment by enoch85** [comment]
ping @Ark74
