### ISSUE TITLE
Remove "Thank you for downloading the Nextcloud VM..." landing page, and route /nextcloud to root

### ISSUE THREAD

**Issue by audioeptesicus** [nextcloud/vm#1798]
As the title states, I'm having difficulty figuring out how to change the nextcloud address from https://drive.mysite.com/nextcloud to https://drive.mysite.com. I've done this on previous installs of Nextcloud, and have had success, but I am having difficulty figuring this out on the latest version of nextcloud.

My Nextcloud Ubuntu 20.04.1 VM running the latest version of Nextcloud sits behind an Nginx VM providing reverse proxy for all my services.

**Comment by audioeptesicus** [comment]
My mistake... I changed my proxy_pass in my Nginx config from http to https which resolved the issue.

**Comment by enoch85** [comment]
JFTR, this is already done in the VM. We don't show `/nextcloud` once everything is setup.

Glad you solved it. :+1:
