### ISSUE TITLE
movies preview

### ISSUE THREAD

**Issue by paolotws** [nextcloud/vm#18]
Hi,
in my new Nextcloud VM (from your image) there are not movies preview.
As for owncloud I made the following steps:

1. in config.php I added:  
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Movie',
    1 => 'OC\\Preview\\Image',
    2 => 'OC\\Preview\\MP3',
    3 => 'OC\\Preview\\TXT',
    4 => 'OC\\Preview\\MarkDown',
  ),

2. in Ubuntu I installed: ffmpeg and ffmpegthumbnailer

There are other configurations to do?
The nextcloud migration from the old owncloud on another server shows correctly the movies preview but I can't view the differences between the two servers.
Thank you
Paolo

**Comment by enoch85** [comment]
> I can't view the differences between the two servers.

Is that a question? I don't really understand what you are asking for here.

**Comment by paolotws** [comment]
Sorry,
now all goes well, probabily was a problem of browser's cache.
Thank you 
Bye
