### ISSUE TITLE
Parse Error on iPhone, iPad - All Browsers and App

### ISSUE THREAD

**Issue by earlyXbird** [nextcloud/vm#1801]
Safari can't Open the Site. Cannot Parse the reply.

I am Unsing the version from 05.02.2021. Used the Installation Script on Ubuntu 20.04 Proxmox LXC Container.

**Comment by enoch85** [comment]
Hi,

This is not VM related per say. It's probably due to lack of support in Safari with Nextcloud, or something else.

Have you tried Firefox?

**Comment by earlyXbird** [comment]
Tried Firefox. Using Nginx as Reverse Proxy on Proxmox. Tried to Access Nextcloud via local ip and it Works. May it is a Problem with The reverse proxy settings

**Comment by earlyXbird** [comment]
Tried turnkey Linux nextcloud appliance -> is Working. The nginx may Not the Root Cause

**Comment by enoch85** [comment]
Check your Apache config. I'm pretty sure you missed something in there.

We use pretty strict settings, so you might need to configure it to work with your reverse proxy.
