### ISSUE TITLE
Enhancement: Install Azure-tuned kernel for Hyper-V based VMs as a performance improvement

### ISSUE THREAD

**Issue by schories** [nextcloud/vm#1803]
For all Hyper-V based VMs - either on-prem with Window Server/Windows 10 or in Azure - it makes sense to use the latest "Azure-tuned" Ubuntu Kernel instead of the generic one.

a) Hyper-V Integration: https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v#notes

b) Ubuntu Azure-tuned Kernel meta package: https://packages.ubuntu.com/focal/linux-azure

I therefore created PR 1802 (https://github.com/nextcloud/vm/pull/1802) which enhances nextcloud_install_production.sh with:

- check (based on dmidecode and dmesg results) and install Azure-tuned kernel for Hyper-V based VMs (both, Windows on-prem and also in Azure)
- using Ubuntu meta package "linux-azure"
- to benefit from improved performance by using latest virtual Hardware Enablement (HWE) kernel for up to date Linux Integration Services

As this is your great script, Mr. Hansson, I merely took an educated guess where and how to place the few additional lines. So please feel free to adapt/edit/change the PR as you please.

For Hyper-V users who can't wait:

a) login via ssh in to your Nextcloud VM
b) run "apt install linux-azure"
c) reboot to run the new Azure-tuned Hyper-V-optimized kernel

## Steps to reproduce
1. Run enhanced nextcloud_install_production.sh within a Hyper-V based VM
2. Hyper-V should be detected by both - dmidecode and dmesg
3. Then Ubuntu's linux-azure meta package should used to successfully install the Azure-tuned Ubuntu Kernel

**Comment by enoch85** [comment]
Hi,

Thanks for your PR! :rocket: 

I'd actually start by taking a look at https://github.com/nextcloud/vm/blob/e73452c80b40ecc33ca319a1e9019a1b20db78d9/nextcloud_install_production.sh#L910 and the already existing stuff here: https://github.com/nextcloud/vm/blob/24f1720e5eda9b7ce922ea5d1a9521bcbec10baa/disk/format-sdb.sh#L36 and here:https://github.com/nextcloud/vm/blob/24f1720e5eda9b7ce922ea5d1a9521bcbec10baa/lib.sh#L38

We could extend with a check for Azure, using the already existing logic IMHO.

Please also use `print_text_in_color` instead of `echo`.

Thanks again!

**Comment by schories** [comment]
Thanks, yes as I expected - there are much better places. I'll update accordingly.

> Please also use print_text_in_color instead of echo.

I did. But only for successful messages - as have seen echo is used for normal output. So, please, let me know how to proceed with normal messages - as red is for real errors and cyan for "user input required" as far as I understood. Sorry, I have to ask again as it is still not really clear to me.

Thank you once again, Daniel.

**Comment by enoch85** [comment]
For the print function we use it like this:

ICyan = informal
IGreen = success
IRed = failed

We try to avoid using `echo` as much as possible.

Thank *you*. :)

**Comment by enoch85** [comment]
@schiessle Any progress here? Do you need help with something?

**Comment by schories** [comment]
I was busy with other/work related topics. I apologize. I will continue tomorrow and hopefully have finished it on Saturday. Thank you!

**Comment by enoch85** [comment]
No rush! Was just curious :)

**Comment by schories** [comment]
On it. Will be tomorrow. :/

**Comment by szaimen** [comment]
@schories any update here? :)

**Comment by szaimen** [comment]
ping @schories

**Comment by enoch85** [comment]
This is now done
