### ISSUE TITLE
Feature Request: use `apt install certbot` instead of `snap install certbot`

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#1807]
Hi guys (@szaimen and daniel), would you consider replacing the snap version of certbot with the version included in ubuntu?

The reason I'm asking is that there are issues when installing `snapd` packages in an LXC container. And the normal ubuntu version of certbot works great.

Thanks for all your hard work 👍

**Comment by szaimen** [comment]
Actually thats not my turn.
@enoch85 has to decide.

**Comment by enoch85** [comment]
The answer is no, snap updates automatically and is very convenient. If it doesn't work in upstream I would report the issue there instead of doing a workaround here.
