### ISSUE TITLE
Introduce notify_push in master

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1809]
Talked with @jospoortvliet today and we should try to introduce https://github.com/nextcloud/notify_push

It's a daemon, so instead of spawning every 30 minutes or so for a new notification, it' happens instantly.

cc @szaimen

**Comment by szaimen** [comment]
Yah, I've already seen that app and it sounds promising!
What I am still not sure about is what is required to set this up:

If I am correct those sections are needed:
https://github.com/nextcloud/notify_push#setting-up-the-service
https://github.com/nextcloud/notify_push#starting-the-service
https://github.com/nextcloud/notify_push#apache
https://github.com/nextcloud/notify_push#nextcloud-app

Concerning the apache reverse proxy part: to which apache conf file could we add this? 
Or is it possible to create and use a new one?

**Comment by szaimen** [comment]
We cannot implement this as long as the app is not published to the appstore and no release is available
