### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by Hamsterman** [nextcloud/vm#181]
I am running Hyper V (Windows Server 2016) and I have installed a completely fresh ubuntu-16.04.2-desktop-amd64.iso

Then I am using the latest script and running it like this

sudo bash ./Nextcloud.sh

It returns the following

line 19: curl : command not found

and then right after creation of user

bash: nextcloud_install_production.sh: no such file or directory

Then all kind of stuff happens - it all looks good. When suddently

gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:        imported: 1 (RSA: 1)
gpg: can't open '/tmp/gpg/nextcloud-.zip.asc'
gpg: verify signatures failed: file open error
Package NOT OK! Installation is aborted...

**Comment by Hamsterman** [comment]
If I first do a

sudo apt install curl

Both errors are removed

**Comment by enoch85** [comment]
@Hamsterman Thanks for reporting this back to us. This is not a bug, it's a user error. Please follow the instructions and let me know if you still have issues, thanks! :)

The command for a clean install should be: `sudo bash nextcloud_install_production.sh` like it says here: https://github.com/nextcloud/vm#build-your-own-vm-or-install-on-a-vps

**Comment by Hamsterman** [comment]
Well I just copied the code directly to my own .sh file. Thats why the name change. Otherwise it's the same. I haven't tried the wget method. Could it be that the wget gets another version ?

**Comment by enoch85** [comment]
@Hamsterman Why bother copy it to your own file if you don't mind me asking? sudo bash equals ./ so that could be the cause i don't know. Also, alot of stuff could gor wrong when copying such a big file.

Follow te instructions and let me know if it works. Thanks!

**Comment by enoch85** [comment]
Aaah, I didn't read properly. You need Ubuntu **server** not desktop.

**Comment by Hamsterman** [comment]
Alright - thanks
