### ISSUE TITLE
Caddy

### ISSUE THREAD

**Issue by ShalokShalom** [nextcloud/vm#1818]
I read your blog article [here](https://www.techandme.se/we-migrated-to-postgresql/) and see a very high similarity between Apache and Caddy.

Did you evaluate using Caddy?
https://caddyserver.com/

**Comment by enoch85** [comment]
It would mean a total rewrite. 

I don't know so much about Caddy, and I know good ol' Apache, stable as a rock. 

I don't think Caddy will be an option.

**Comment by ShalokShalom** [comment]
Ok, I see. 
The thing is that I went through the installation and it was super easy and intuitive. 
The only thing that did not work is let's encrypt and it's quite true to its name, so cryptic it seems to me.
I assumed the switch would mean no more hastle than the switch from MySQL to Postgres and some would say MySQL is stable as a rock too.

**Comment by szaimen** [comment]
Hm... If I think about this, the only possible situation when this might could be considered is when a new major LTS release of Ubuntu gets released (e.g. 22.04 LTS) and the scripts get adjusted to fit this release. But I guess one of the requirements is that caddy gets shipped from ubuntu sources which isn't the case currently, afaics. Also all Apache features that are currently implemented in the scripts should be also available in Caddy, which also isn't the case, afaics (e.g. Geoblocking isn't possible, or?).

**Comment by ShalokShalom** [comment]
I would just like an easy way, to enable Let's encrypt.

**Comment by szaimen** [comment]
> I would just like an easy way, to enable Let's encrypt.

In Caddy or in the NcVM?

**Comment by ShalokShalom** [comment]
In your VM.

**Comment by szaimen** [comment]
There is one: run inside your NcVM:
`sudo bash /var/scripts/menu.sh` -> choose `Server Configuration` -> `Activate TLS`

**Comment by enoch85** [comment]
Let's close this, Caddy won't happen in a near future.
