### ISSUE TITLE
Virtualbox

### ISSUE THREAD

**Issue by ShalokShalom** [nextcloud/vm#1820]
The documentation says Virtualbox is not recommended and since it improved a lot in the last years and because the documentation is outdated on it anyway, is it interesting to me to know, why. 

The outdated part is the bridge, which is said to be not active by default and instead, NAT is. 

That is not correct on my current installation of Virtualbox on KaOS Linux with Virtualbox 6.1.18 and [here](https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/machine-setup-nextcloud-vm?currentPageId=W7DvK-PiqQz3_Mr3)  is the misleading documentation, just see the second to last line.

P.S: Also [this document](https://cloud.hanssonit.se/s/AZmZdEztK9JtPcm) is outdated, since it lists 2GB of default RAM, while it is 4.

**Comment by enoch85** [comment]
Thanks for the pointers. 

We still have a lot of support tickets from users with VirtualBox related issues, not so many from VMware or Hyper-V users.

I will update the documentation soon.

**Comment by enoch85** [comment]
Updated and done! :+1:

**Comment by ShalokShalom** [comment]
I dont know why, the preview still shows 2Gb for me:

![Screenshot_2021-02-15-23-05-57-36_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/6344099/107997285-ae26c300-6fe2-11eb-8dee-120c7778b7ad.jpg)

The line about the NAT/Bridging thing is still visible for me personally. 

And you know how many people use Virtualbox vs VMWare and Hyper-V?

Since only Virtualbox is open source and thats the first reason why I use it and I guess lots of other people do so as well, so I assume the user amount is considerably higher.

VMware is not even in the repos of Debian and CentOS.

**Comment by enoch85** [comment]
It's most likely due to cache. It's changed anyway.
