### ISSUE TITLE
Update from 20.0.5 to 20.0.7 crashes at ocsms

### ISSUE THREAD

**Issue by TuxDuck** [nextcloud/vm#1826]
## Steps to reproduce
1. Run update script: sudo bash /var/scripts/update.sh

## Expected behaviour
Tell us what should happen

Simple update

## Actual behaviour
Tell us what happens instead

Update crashes trying to update ocsms

## Server configuration

**Nextcloud server version:** (see your admin page)

Was 20.0.5
Now 20.0.7

**Server OS** (Ubuntu server is default)

Ubuntu Server 20.04.2 running Nextcloud within LXD container

**How did you install the VM?** (Scripted install from master **OR** Released version)

Scripted install

## Network
**Do you use DHCP?**

Yes

**Is port 80 and/or 443 open?**

Both port 80 and 443 open

#### Log file (/var/log/nextcloud/nextcloud.log)
```
https://0bin.net/paste/TpqBl227#uDxmDh0iG0H6u4ADFwDWDVtIcOBk5gCDJGQ-7ZFeqJs
```
#### Installation log (command output)
```
Installing ocsms...
An exception occurred while executing 'SELECT "user_id", "datakey", "datavalue" FROM "oc_ocsms_user_datas" WHERE "datakey" LIKE ?' with params ["lastReadDate-%"]:

SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "oc_ocsms_user_datas" does not exist
LINE 1: SELECT "user_id", "datakey", "datavalue" FROM "oc_ocsms_user...
                                                      ^
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ app:enable ocsms failed
Posting notification to users that are admins, this might take a while...
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!'

**Comment by szaimen** [comment]
@enoch85 this looks like a bug with the ocsms app but the update shouldn't crash either way.

This should be fixed by changing 
https://github.com/nextcloud/vm/blob/8d1fbce04ebcf9f655550edee5f3cd40d6b13797/lib.sh#L1082
to
```shell
 nextcloud_occ_no_check app:enable "$1" 
```
What do you think?

**Comment by TuxDuck** [comment]
I have "worked around" the issue by simply uninstalling the app for now. At this point, I am testing NC out and merely playing around with some non‑critical apps. This was one of them. I'm glad to have stumbled onto something that needs attention, but am in no hurry about it.
