### ISSUE TITLE
Upgrade issue v20 -> v21: OCC no longer works because of Undefined class constant 'MAJOR_VERSION' in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Utils.php:118

### ISSUE THREAD

**Issue by github-cli** [nextcloud/vm#1834]
## Steps to reproduce
1. Update from v20 to v21
2.
3.

## Expected behaviour
no error and nextcloud still working

## Actual behaviour
errors and nextcloud no longer working (seems occ commands fail)

## Server configuration

**Nextcloud server version:** v20 before, now v21

**Server OS** (Ubuntu server is default)
Ubuntu Server

**How did you install the VM?** (Scripted install from master **OR** Released version)
Hansson script for VM

## Network
**Do you use DHCP?**
no, static ip

**Is port 80 and/or 443 open?**
yes, both

## Logs / Screenshots

https://paste.ubuntu.com/p/wV7T34dGWk/

#### Log file (/var/log/nextcloud/nextcloud.log)
```
[nextcloud.log](https://github.com/nextcloud/vm/files/6016279/nextcloud.log)
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Strange, tested here and works fine. 

Which command did you try to execute?

**Comment by github-cli** [comment]
at first some command which was supposed to upgrade database indices but it seems any OCC command has issues now:
root@nextcloud:~# sudo -u www-data php /var/www/nextcloud/occ -V | pastebinit
https://paste.ubuntu.com/p/b3c8R8p5Ph/

**Comment by enoch85** [comment]
![image](https://user-images.githubusercontent.com/4511254/108608031-5c0be600-73c4-11eb-8ce2-40fcf6ecb551.png)

Just upgraded from 20.0.7 to 21.0.0 on one of my test instances, and everything was 100%.

When you upgrade, always use the built in update script: `sudo bash /var/scripts/update.sh`

**Comment by szaimen** [comment]
Looks like I found the problematic app in the provided logs:
files_external_gdrive

**Comment by szaimen** [comment]
@github-cli Could you maybe post the content of your config.php file here?

**Comment by github-cli** [comment]
@szaimen sure, i redacted some stuff, if you need the full file I can send it via PM or something?
I removed the first and last line as php files were not permitted on paste
https://paste.ubuntu.com/p/4dSN8yQDff/
@enoch85 yes, I did update via that script, it even told me the command in the update notifications

**Comment by szaimen** [comment]
@github-cli thanks!

As you can see in the `app_install_overwrite` array, are there a lot of apps that can get enabled although they are not compatible yet with new Nextcloud major versions.
To fix this, I would strongy advice you to restore your VM to the state before you've tried the update the delete this array with 
```
sudo -i
nextcloud_occ config:system:delete app_install_overwrite
```
and then try the update again, if you've made sure that all apps that you are using are compatible with the new version.

@enoch85 Maybe we should build this command directly into the update script?

**Comment by github-cli** [comment]
@szaimen Thank you!
I think the install created some backups before the update, is there a way to restore from those or will I need to use an older VM-backup? If I need to restore the VM from a backup, can I somehow keep the version of the contacts/calendar I currently have on my phone and overwrite this as there are the only changes between now and my last backup.

**Comment by szaimen** [comment]
Best way is to restore your VM from Backup. You could try to download your current contacts and calendars from the webinterface before the restore though and import them again into the restored backup, manually.

Otherwise it might be possible for you to fix your instance on NC21 but I would advise against it.

**Comment by github-cli** [comment]
contacts are unaccessible via UI like almost everything else.
I can restore the vm from backup but i would need to overwrite contacts/calendar with the version from my phone, is this possible?
What is this backup the update script does? I thought this may be to revert in case the update fails

**Comment by szaimen** [comment]
Yes, you should be able to restore the old installation from the backup manually (the Backup should be stored here: `/mnt/NCBACKUP`) but please head for further guidance over to https://help.nextcloud.com since this isn't a bug in the script itself. Thanks!

**Comment by github-cli** [comment]
thanks, I posted there in support in looks for help.
Appreciate your help so far, good night.

**Comment by szaimen** [comment]
Just one last idea: maybe it is already enough to just disable all incompatible apps to get the webinterface working again so that you can export the calendar and contacts data from the webinterface, revert to the last backup and import it there.

**Comment by github-cli** [comment]
Thanks, if you mean via "nextcloud_occ config:system:delete app_install_overwrite" then I cannot execute that command because of the aforementioned error, if you mean via GUI, then the apps page is inaccessible...
or do you mean manually editing the config.php and deleting the whole app_install_overwrite array?
unfortunately neither of these seem to work or did you mean something else?

**Comment by szaimen** [comment]
What I mean is that you can remove them manually by e.g. executing:
```
sudo rm -r /var/www/nextcloud/apps/files_external_gdrive
```

**Comment by github-cli** [comment]
how would i know which ones are incompatible? I deleted the gdrive (and rebooted) but the behavior did not change
I tried accessing the database via adminer to pull the data but the ncadmin user no longer works
Unable to connect to PostgreSQL server: FATAL: Peer authentication failed for user "ncadmin"
only real pain would be the contacts, any way to force sync from the phone to the server instead of the other way around?

**Comment by szaimen** [comment]
> how would i know which ones are incompatible?

Those are most likely incompatible:
```
files_external_dropbox',
    1 => 'files_external_gdrive',
    2 => 'keeweb',
    3 => 'gallery',
    4 => 'occweb',
    5 => 'workflow_ocr',
    6 => 'ransomware_detection',
    7 => 'audioplayer',
    8 => 'fulltextsearch',
    9 => 'fulltextsearch_elasticsearch',
    10 => 'files_fulltextsearch',
    11 => 'geoblocker',
    12 => 'audioplayer_editor',
    13 => 'breezedark',
    14 => 'extract',
    15 => 'checksum',
    16 => 'camerarawpreviews',
    17 => 'facerecognition',
    18 => 'files_retention',
    19 => 'bookmarks_fulltextsearch',
    20 => 'files_fulltextsearch_tesseract',
    21 => 'joplin',
```


> only real pain would be the contacts, any way to force sync from the phone to the server instead of the other way around?

There is no way to this, afaik. 
Maybe you could back them up with an app on you rphone and restore them after you've restored the server and reconfigured the connection?

**Comment by github-cli** [comment]
just FYI, restored the server, then contacts with a contacts restore app, all back to normal on v20 now.
should I simply refrain from updating to v21 or wait a while until those apps are compatible or something else?
There is no special need for me to upgrade to v21 but I am happy to test if wanted/needed as this nextcloud instance is only being used by myself and my wife :-)

**Comment by szaimen** [comment]
Great to hear that everything worked out! :)
I acutally always recommend to wait until at least the first point release is out but if you are brave, you could try to update to NC21 again if all apps you are using have updates available for this new major release.

BTW: This time it shouldn't break your NC after the update because of #1835

**Comment by github-cli** [comment]
restored everything, took a fresh backup and did the update again, still same errors:
https://paste.ubuntu.com/p/mdf22QybGZ/
[nextcloud.log](https://github.com/nextcloud/vm/files/6025995/nextcloud.log)
If you would like me to debug this I am happy to help, if not I am fine with staying on v20 :-)

**Comment by szaimen** [comment]
Thanks for the heads up and testing again!
Obviously, I didn't dig deep enough into the update script because then I would have seen that my fix needs to be at a different place to become effective.
New fix is at #1848

**Comment by github-cli** [comment]
Would you like me to try again with /var/scripts/update.sh already or does it take a while?

**Comment by szaimen** [comment]
> Would you like me to try again with /var/scripts/update.sh already or does it take a while?

Would be great, but please wait until #1848 is merged :)
(the fix should then become effective around 10 min after the merge)

**Comment by Aurnytoraink** [comment]
I there a way to do it without backup ?

**Comment by enoch85** [comment]
@github-cli  ...or you can help us test the actual script before we merge it. ;)

**Comment by github-cli** [comment]
sure thing, how would i do that? it fresh-pulls it from github everytime, no?
or do i only download the nextcloud_update script and execute it locally?

**Comment by enoch85** [comment]
> or do i only download the nextcloud_update script and execute it locally?

Exactly! 

1. Go to the PR
2. View changed files, 
3. Hit the 3 dots and choose to view the file
4. Get the RAW version
5. use `wget` or curl` to get it to your server
6. Run it and post your findings here.

Thanks! :heart_eyes:

**Comment by github-cli** [comment]
Happy to help if I can...
Did that, worked fine... now on a working v21 :-)
thanks @szaimen and @enoch85

**Comment by Terrox** [comment]
> Looks like I found the problematic app in the provided logs:
> files_external_gdrive

me too. the Internal Server Error in Nextcloud didn't help me work this out.
Just either rename the folder to _OFF  OR set enabled=no in the database oc_appconfig -> files_external_gdrive sorted it out.
Also noticed the External Storage App was disabled.

**Comment by STaRDoGG** [comment]
@Terrox Ty Bud, you saved me a lot of time with this tip:

> Just either rename the folder to _OFF OR set enabled=no in the database oc_appconfig -> files_external_gdrive sorted it out.

I  just set it to `no` in my db and reloaded, and all is good now. I should add that `files_external_dropbox` was causing it as well, so I had to disable it too.

**Comment by Terrox** [comment]
> 
> 
> @Terrox Ty Bud, you saved me a lot of time with this tip:
> 
> > Just either rename the folder to _OFF OR set enabled=no in the database oc_appconfig -> files_external_gdrive sorted it out.
> 
> I just set it to `no` in my db and reloaded, and all is good now. I should add that `files_external_dropbox` was causing it as well, so I had to disable it too.

I think you might still have weird External Mount configs in your Global or User settings that might cause Nextcloud Desktop Client to stop working until those configs are deleted. I vaguely remember that being another problem that I didn't notice until later.

**Comment by bf8392** [comment]
> OR set enabled=no in the database oc_appconfig -> files_external_gdrive sorted it out.

totally saved me GREAT GREAT thanks =)

**Comment by ruedigerkupper** [comment]
Confirming that files_external_gdrive caused the problem for me, too. Since I use the Nextcloud snap, I could solve it by
# snap revert nextcloud
# nextcloud.occ app:disable files_external_gdrive
# snap refresh nextcloud
Perhaps this is the safest way for snap users.
