### ISSUE TITLE
Move extract to its own script because of the dependencies?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1842]
Hey,

I wonder if we should move the extract app to its own script because of the dependencies?
So that you are able to install and uninstall it any time?
https://github.com/nextcloud/vm/blob/4dc4c79320f3cff212b3a6ecf8809067d0a69cfd/nextcloud_install_production.sh#L871-L877

**Comment by enoch85** [comment]
Sure, please go ahead.
