### ISSUE TITLE
Status flag missing for whiptail checklist

### ISSUE THREAD

**Issue by alexzaech** [nextcloud/vm#1844]
https://github.com/nextcloud/vm/blob/39620a70c6a4475f6b03932efb44e9c41a7188e6/menu/additional_apps.sh#L51

should be

```"Notify Push" "(Push Notifications for Nextcloud)" OFF \```

I guess

**Comment by szaimen** [comment]
Thanks for the report!
I was sure that I've added it. Will be solved with #1845.
