### ISSUE TITLE
Update.sh fails to update 20.0.6 to 20.0.7

### ISSUE THREAD

**Issue by gpz1100** [nextcloud/vm#1846]
## Steps to reproduce
1. /var/scripts/update.sh minor
2.
3.

## Expected behaviour
update successfully.

## Actual behaviour

Latest release is: 20.0.7. Current version is: 20.0.6.
New version available, upgrade continues!
Checking connection...
Backing up files and upgrading to Nextcloud 20.0.7 in 10 seconds... Press CTRL+C to abort.
Getting and backing up the status of apps for later, this might take a while...
Doing pgdump of nextcloud_db...
Backing up data...
Adding required repo (multiverse).
'multiverse' distribution component is already enabled for all sources.
@zfs-auto-snap-2021-02-22-1605, 1 created, 0 destroyed, 0 warnings.

Backup OK!
Downloading nextcloud-20.0.7...
Testing if network is OK...
Waiting for network to restart...
Checking connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  100M  100  100M    0     0  18.2M      0  0:00:05  0:00:05 --:--:-- 22.7M
Checking SHA256 checksum...
tail: cannot open '/tmp/shas56/nextcloud-20.0.7.tar.bz2.sha256' for reading: No such file or directory
sha256sum: 'standard input': no properly formatted SHA256 checksum lines found

## Server configuration

**Nextcloud server version:** (see your admin page)
20.0.6
**Server OS** (Ubuntu server is default)
 Ubuntu 20.04.2 LTS
**PHP Version** (e.g. 7.4)
7.4
**How did you install the VM?** (Scripted install from master **OR** Released version)
ova appliance
## Network
**Do you use DHCP?**
no
**Is port 80 and/or 443 open?**
no

**Comment by szaimen** [comment]
That's due to the NC21 release which kills Nextcloud's update server currently. Please try again tomorrow or in a few days.

**Comment by gpz1100** [comment]
Upgrade attempt is to 20.0.7 not NC21.  Still related?

**Comment by enoch85** [comment]
> Still related?

Yes, NC 21 is a huge release and kind of hyped. Nextcloud's server went down earlier today due to the traffic.
