### ISSUE TITLE
syslog flooded with multipath errors every 5 seconds

### ISSUE THREAD

**Issue by gpz1100** [nextcloud/vm#1847]
## Steps to reproduce
1. cat /var/log/syslog | grep multi
2.
3.

## Expected behaviour
Few entries showing starting of service, not 10000 lines

## Actual behaviour
Feb 23 00:00:11 nextcloud multipathd[892]: sda: add missing path
Feb 23 00:00:12 nextcloud multipathd[892]: sda: failed to get udev uid: Invalid argument
Feb 23 00:00:12 nextcloud multipathd[892]: sda: failed to get sysfs uid: Invalid argument
Feb 23 00:00:12 nextcloud multipathd[892]: sda: failed to get sgio uid: No such file or directory
Feb 23 00:00:13 nextcloud multipathd[892]: sdb: add missing path
Feb 23 00:00:13 nextcloud multipathd[892]: sdb: failed to get udev uid: Invalid argument
Feb 23 00:00:13 nextcloud multipathd[892]: sdb: failed to get sysfs uid: Invalid argument
Feb 23 00:00:13 nextcloud multipathd[892]: sdb: failed to get sgio uid: No such file or directory
Feb 23 00:00:17 nextcloud multipathd[892]: sda: add missing path
Feb 23 00:00:17 nextcloud multipathd[892]: sda: failed to get udev uid: Invalid argument
Feb 23 00:00:17 nextcloud multipathd[892]: sda: failed to get sysfs uid: Invalid argument
Feb 23 00:00:17 nextcloud multipathd[892]: sda: failed to get sgio uid: No such file or directory
Feb 23 00:00:18 nextcloud multipathd[892]: sdb: add missing path
Feb 23 00:00:18 nextcloud multipathd[892]: sdb: failed to get udev uid: Invalid argument
Feb 23 00:00:18 nextcloud multipathd[892]: sdb: failed to get sysfs uid: Invalid argument
Feb 23 00:00:18 nextcloud multipathd[892]: sdb: failed to get sgio uid: No such file or directory

This repeats every 5 seconds.

## Server configuration

**Nextcloud server version:** (see your admin page)
20.0.7
**Server OS** (Ubuntu server is default)
ubuntu 20
**PHP Version** (e.g. 7.4)
7.4
**How did you install the VM?** (Scripted install from master **OR** Released version)
vm appliance reployment

Adding this to /etc/multipath.conf fixes.

```
blacklist {
    devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
    devnode "^sd[a-z]?[0-9]*"
}
```

The log flood behavior is present in both esxi and vmworkstation.

**Comment by enoch85** [comment]
This Hey, please have a look here: https://askubuntu.com/questions/1242731/ubuntu-20-04-multipath-configuration

**Comment by gpz1100** [comment]
Yes, I believe that's where the code I posted in the OP came from.

The .vmx edit or multipath.conf change should probably be baked into the ova?

**Comment by sulaiman35** [comment]
Through this, I have resolved my issue on VMWare

1. vi /etc/multipath.conf

defaults {
    user_friendly_names yes
}

blacklist {
    device {
        vendor "VMware"
        product "Virtual disk"
    }
}

2. Restart service
/etc/init.d/multipath-tools restart

**Comment by enoch85** [comment]
@sulaiman35 That's actually not correct. :/

It's better to fix the main issuet instead: 

https://kb.vmware.com/s/article/52815
https://sort.veritas.com/public/documents/sfha/6.2/vmwareesx/productguides/html/sfhas_virtualization/ch10s05s01.htm
