### ISSUE TITLE
ClamAV failed to start during initial setup of 2TB VM

### ISSUE THREAD

**Issue by Hitchhiker76** [nextcloud/vm#1851]
## Steps to reproduce
1.First install of VM Script
2. Failed to start ClamAV
3.

## Expected behaviour
Started ClamAV

## Actual behaviour
Tell us what happens instead
https://imgur.com/CG12ssp

## Server configuration

**Nextcloud server version:** (see your admin page)

20.XX I just purchase the 2TB last night. (24 Feb 2021)

**Server OS** (Ubuntu server is default)

**PHP Version** (e.g. 7.4)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
Yes, statically assigned via MAC
**Is port 80 and/or 443 open?**
Yes, TLS installation was successfull
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
@szaimen please?

**Comment by szaimen** [comment]
I gonna try to debug this.

@Hitchhiker76 
Could you please post some more infos how much resources you've made available for the VM?
Also it would be interesting how much resources are currently used (a screenshot of htop with the current RAM and CPU usage of the VM in IDLE should be sufficient).
And which CPU-model are you using on your host?
Thanks!

**Comment by Hitchhiker76** [comment]
https://imgur.com/9xpgNAs
https://imgur.com/Vd7tnQf
https://imgur.com/UhKcPIs

This has been all the default setup as far as the resources and the RAM for the VM. It is running on ESXi 6.7.

**Comment by szaimen** [comment]
Thanks!

One idea that I have is to increase the timespan the daemon has to start: 
Could you please run inside you VM:
```
wget https://raw.githubusercontent.com/nextcloud/vm/master/apps/clamav.sh
sed -i 's|-lt 4|-lt 12|' clamav.sh
sudo bash -x clamav.sh

```
If that doesn't work, could you for debugging purposes try to increase the core count of the VM to 4 cores and try to install clamav again?

Please report back if one of those or both together work, thanks!

**Comment by Hitchhiker76** [comment]
As soon as I have finished the install I will do that, and get back to you.

**Comment by Hitchhiker76** [comment]
Ok so after running the above commands the first screen that appears is one that informs me that I have ClamAV installed and asks if I would like to Reinstall. I select "Reinstall ClamAV".

It reported that it successfully installed and asked if I would like to schedule a weekly full scan.  After setting up the parameters of the scan it exited to the CLI.

**Comment by szaimen** [comment]
Thanks for testing! 
So apparently giving the system more time to start the daemon solves the problem. 
I'll create a PR later.

**Comment by Hitchhiker76** [comment]
Thanks for the help.
