### ISSUE TITLE
How to update PHP to newer Version then 7.2

### ISSUE THREAD

**Issue by Leviathan09** [nextcloud/vm#1856]
## Steps to reproduce
No steps take so far, i want to update php7.2 to at least 7.4 but don't know how
All guides i can find leads into a non-functional nextcloud
I don't get it how to set proper configuration files

For my initial Nextcloud setup i used your installation script...2 years ago

## Server configuration
**Nextcloud server version:** (see your admin page)
20.0.8
**Server OS** (Ubuntu server is default)
Ubuntu 18.04
**PHP Version** (e.g. 7.4)
php7.2
**How did you install the VM?** (Scripted install from master **OR** Released version)
Install script from master

**Comment by enoch85** [comment]
Hi,

Please check this out if you need help: https://shop.hanssonit.se/product/upgrade-php-version-including-dependencies/

**Comment by Leviathan09** [comment]
Is this a one-time buy or do i need to buy this everytime i need a new php version?

**Comment by enoch85** [comment]
> Is this a one-time buy or do i need to buy this everytime i need a new php version?

We'll upgrade to either PHP 7.4 or 8. When Nextcloud requires a newer PHP version to be able to run you have two options:
1. Do it yourself
2. Hire someone (like me) to do it for you.

With that said, getting PHP 8 now would be very future proof as it's just released, and it will probably take several years before Nextcloud drops support for that version.
