### ISSUE TITLE
Talk Signaling gives 403 and no error page

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#1864]
@morph027 @szaimen 

Just fixed a customers Talk Signaling integration with adding the talk domain to `/etc/hosts` as `localhost`. Without it, the Signaling server didn't work.

The issue remains though, it still shows 403 forbidden instead of the error message when visiting the talk domain. 

I don't know, but it seems that we need to have another look at this. What do you think?

**Comment by szaimen** [comment]
I think localhost is in /etc/hosts by default? `127.0.0.1 localhost` is the servers hosts file...

Also, for me it still shows
`Hi there! :) If you see this page, the Apache2 proxy for Talk Signaling Server is up and running.`
on two instances, one with NC20 and another with NC21.
But talk was on both installed before NC21.

**Comment by enoch85** [comment]
Sorry, I set 127.0.1.1 (same as for Nextcloud, but with the talk domain instead.)

**Comment by szaimen** [comment]
I don't think that this is necessary...

**Comment by morph027** [comment]
Hm...shouldn't be necessary...

**Comment by enoch85** [comment]
Turns out it didn't work so we reverted to the "regular" Talk instead. I will install the Signaling server some day when I have time on a public VPS just to see if it was their network or something wrong in the scripts.

**Comment by szaimen** [comment]
I'd say it was their network...

**Comment by enoch85** [comment]
Tested on a VPS and works!
