### ISSUE TITLE
/home/ncadmin/.bashrc is never executed on logon.

### ISSUE THREAD

**Issue by bapjg** [nextcloud/vm#1865]
NextCloud VM (500Gb) version 21.0.0 downloaded 28/02/2021.

The script /home/ncadmin/.bashrc is never executed on logon.

This is because of an error in /home/ncadmin/.bash_profile script (which IS executed).

The delivered .bash_profile script reads :
```
ncadmin@cloud:~$ cat .bash_profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.
# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022
# if running bash
if [ -n "5.0.17(1)-release" ]
then
    # include .bashrc if it exists
    if [ -f "/root/.bashrc" ]
    then
        . "/root/.bashrc"
    fi
fi
# set PATH so it includes user's private bin if it exists
if [ -d "/root/bin" ]
then
    PATH="/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
fi
bash /var/scripts/nextcloud.sh
bash /var/scripts/history.sh
```

The script should read :
```
ncadmin@cloud:~$ cat .bash_profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.
# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022
# if running bash
if [ -n "5.0.17(1)-release" ]
then
    # include .bashrc if it exists
    if [ -f "/home/ncadmin/.bashrc" ]
    then
        . "/home/ncadmin/.bashrc"
    fi
fi
# set PATH so it includes user's private bin if it exists
if [ -d "/home/ncadmin/bin" ]
then
    PATH="/home/ncadmin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
fi
bash /var/scripts/nextcloud.sh
bash /var/scripts/history.sh
```

ie replace all instances of '/root/' with '/home/ncadmin/'

**Comment by enoch85** [comment]
This is probably because you ran the script as the pure root user. 

I will double check the settings, but this is the diff:

![image](https://user-images.githubusercontent.com/4511254/109495554-bc1f1e00-7a8f-11eb-98c7-af713350b239.png)

**Comment by bapjg** [comment]
I used the script in the default form :

  *   Created VM (from .OVA file)
  *   First boot (automatically goes to user:ncadmin/pwd:nextcloud)
  *   Etc
  *   I never used the root account (ie no sudo -I or -u)

This isn't an important problem for me as I was able to fix it quite easily.

Cordialement

André Davis
andre@bapjg.com
Dom :             +33 4 7928 5014
GSM :             +33 6 8290 7233

De : Daniel Hansson <notifications@github.com>
Envoyé : lundi 1 mars 2021 13:13
À : nextcloud/vm <vm@noreply.github.com>
Cc : Andre Davis <Andre.Davis@Bapjg.com>; Author <author@noreply.github.com>
Objet : Re: [nextcloud/vm] /home/ncadmin/.bashrc is never executed on logon. (#1865)


This is probably because you ran the script as the pure root user.

I will double check the settings, but this is the diff:

[image]<https://user-images.githubusercontent.com/4511254/109495554-bc1f1e00-7a8f-11eb-98c7-af713350b239.png>

**Comment by enoch85** [comment]
You're right! Thanks for the bug report, it's now fixed. :+1:
