### ISSUE TITLE
Please provide a less secure install mode for people testing VMs PRIVATELY only.

### ISSUE THREAD

**Issue by ams-tschoening** [nextcloud/vm#1872]
I'm tasked to have a look at Nextcloud, if it is able to fulfill some of our requirements and was pretty happy to learn that pre-built VMs are available. Especially because the OVAs using UB 20.04, Apache HTTPd, Postgres, ZFS etc. are the exact same choices I would have done myself otherwise. So good job with these choices! :-) Though, when clicking through the installer, I already stumbled across multiple places where things get unnecessary difficult for a starter like me who just wants to have a first look at Nextcloud itself:

TLS is required e.g. for Collabora and without it the installer simply refuses to install it LATER in the process after it ALLOWED to disable TLS. Right now the installer asks me to choose a username for the web admin of Nextcloud and insists that it needs to be different than `ncadmin`. Even though at some places earlier, when I was forced to choose a new password, I was simply able to provide the default password of `nextcloud` again to easily start with.

Why are you making my life unnecessary difficult?! :-/

I'm hosting that VM privately using a NAT-interface, so requiring Let's Encrypt and forcing me to get a domain, open ports in the router and stuff like that doesn't make any sense. Forcing me to choose new usernames and passwords when the default ones are easily documented in the description of the VM doesn't make much sense as well. I don't want to waste my time thinking about new usernames, generate new passwords, document those in KeePass etc., when I just want to have a first look at Nextcloud instead.

So PLEASE, provide a less secure install mode without TLS, without forcing me for new credentials and whatever stuff like that I didn't trigger (yet). Just install Collabora when I ask for and simply trust me that I somewhat know what I'm doing. If you don't want people to use such a VM by default, make it available commercially, like other VMs can be bought as well already. And I did buy two of them, because I just wanted to have a QUICK look at Nextcloud instead of dealing with complex setup and stuff.

Thanks!

**Comment by szaimen** [comment]
This is going to become quite interesting! I've subscribed! 🍿

**Comment by szaimen** [comment]
@enoch85 shall I try to answer or do you wanna take this over?

**Comment by enoch85** [comment]
@szaimen Feel free. I can fill in the missing parts. :)

> So good job with these choices! :-)

Thanks!

**Comment by enoch85** [comment]
As a side note:

1. Hit enter through the whole installation to get the default stuff
2. Don't choose TLS (you could uncheck the box)
3. If you want a simple installation, don't do it more advanced by installing custom apps. 

:)

**Comment by ams-tschoening** [comment]
> Hit enter through the whole installation to get the default stuff

Which forces me at the end to choose different than the already documented credentials. Though, documenting default credentials in the VM-description is a great choice and makes life easier already. There's really no benefit in my case to choose any different credentials, nobody else than me will access that VM, it's not published anywhere or else.

> Don't choose TLS (you could uncheck the box)

I did, but some parts of the installer for additional apps check if TLS is available or not and refuse to install those apps. The problem is that one doesn't know beforehand and needs to run into the corresponding error messages about required TLS instead. Those additional checks preventing me from using the otherwise pretty easy installer seem unnecessary difficult to me. So it would be great if those could be made optional or at least TLS-requirements would be documented for the menu options. FullTextSearch is "documented" to require at least 2 GiB in the corresponding menu option as well.

> If you want a simple installation, don't do it more advanced by installing custom apps.

The integration of Collabora makes Nextcloud especially interesting for my use case and I need to test exactly that anyway. So with the current installer I'm forced to install it manually because of the TLS-checks, even though you provide all the necessary steps already. Again, those checks provide absolutely no benefit for strictly private testers like me.

**You already have multiple commercially available VMs Is it really that difficult to provide one without these strict checks, forced credential changes etc.?**

**Comment by szaimen** [comment]
> TLS is required e.g. for Collabora and without it the installer simply refuses to install it LATER in the process after it ALLOWED to disable TLS. 

Yes, Collabora needs a valid certificate and doesn't like self signed certificates, afaik. Hence we require a valid Let's encrypt certificate. Though you could try to install at least the built-in collabora or onlyoffice via the app store as an alternative. (Note that also if it is theoretically possible that it works with self signed certificates, this will most likely not get implemented, since we want to make it as secure as possible for all users.)

> Right now the installer asks me to choose a username for the web admin of Nextcloud and insists that it needs to be different than `ncadmin`. Even though at some places earlier, when I was forced to choose a new password, I was simply able to provide the default password of `nextcloud` again to easily start with.

I see it the other way around: allowing to set the default password again isn't strict enough for a secure installation, imo. So you can see it more like a feature for your usecase to allow insecure passwords here.

> Why are you making my life unnecessary difficult?! :-/

Actually, the setup is pretty straight forward, IMO. But of course it is always a balance act between simplicity and security: we try to make the setup as simple but also the default configuration as secure as possible for everyone.

> I'm hosting that VM privately using a NAT-interface, so requiring Let's Encrypt and forcing me to get a domain, open ports in the router and stuff like that doesn't make any sense. 

If you want to install onlyoffice or collabora, it is required to make it work. It is as simple as that.

Forcing me to choose new usernames and passwords when the default ones are easily documented in the description of the VM doesn't make much sense as well. I don't want to waste my time thinking about new usernames, generate new passwords, document those in KeePass etc., when I just want to have a first look at Nextcloud instead.

Since you can use the same simple password anywhere (there is no check that checks this), I think we've got you covered, already. 

> So PLEASE, provide a less secure install mode without TLS, without forcing me for new credentials and whatever stuff like that I didn't trigger (yet). 

I don't think that @enoch85 has the ressources to implement, maintain and offer yet another configuration of the NcVM so this will likely not happen.

> Just install Collabora when I ask for and simply trust me that I somewhat know what I'm doing. 

That is the point here. Collabora doesn't work without  a valid certificate, afaik. And if you know what you are doing, why don't you install it yourself or just edit the script to allow it to install it on your instance?

> If you don't want people to use such a VM by default, make it available commercially, like other VMs can be bought as well already. And I did buy two of them, because I just wanted to have a QUICK look at Nextcloud instead of dealing with complex setup and stuff.

As I've said above:
> I don't think that @enoch85 has the ressources to implement, maintain and offer yet another configuration of the NcVM so this will likely not happen.

---

> Which forces me at the end to choose different than the already documented credentials. Though, documenting default credentials in the VM-description is a great choice and makes life easier already. There's really no benefit in my case to choose any different credentials, nobody else than me will access that VM, it's not published anywhere or else.

Then just reuse the documented credentials :)
Apart from the Nextcloud admin username, you can always reuse the default username. My advice: just use `admin` as Nextcloud username, which is pretty straight forward, imo.

> I did, but some parts of the installer for additional apps check if TLS is available or not and refuse to install those apps. The problem is that one doesn't know beforehand and needs to run into the corresponding error messages about required TLS instead. Those additional checks preventing me from using the otherwise pretty easy installer seem unnecessary difficult to me. So it would be great if those could be made optional or at least TLS-requirements would be documented for the menu options. FullTextSearch is "documented" to require at least 2 GiB in the corresponding menu option as well.

The scripts are made in a way to check if all requirements are fullfilled at the start of the script. If they aren't, it has a reason. Most of the time something will not work if one of the requirements isn't fullfilled. So either you fullfill them or you are on your own.

> The integration of Collabora makes Nextcloud especially interesting for my use case and I need to test exactly that anyway. So with the current installer I'm forced to install it manually because of the TLS-checks, even though you provide all the necessary steps already. Again, those checks provide absolutely no benefit for strictly private testers like me.

Just install the built-in collabora via the appstore. There will no check happen if you are using a valid certificate. But I cannot promise that it will work afterwards. Another possibility is for you to edit the script to skip the test.

> You already have multiple commercially available VMs Is it really that difficult to provide one without these strict checks, forced credential changes etc.?

As I've said above:
> I don't think that @enoch85 has the ressources to implement, maintain and offer yet another configuration of the NcVM so this will likely not happen.

**Comment by szaimen** [comment]
BTW: @ams-tschoening I really wonder why you are ranting here: if it doesn't fit for your purposes, just use a different solution :)

**Comment by ams-tschoening** [comment]
> Yes, Collabora needs a valid certificate and doesn't like self signed certificates, afaik.[...]

The installer provides two options, one called "integrated" and one using Docker and only documents that a domain is necessary when using Docker. I DID NOT choose the latter, but the installer STILL aborts the installation with an error message saying that TLS is required. Additionally, Collabora is [documented elsewhere](https://help.nextcloud.com/t/how-o-install-collobora-without-domain-and-ssl/5995) to NOT require TLS as well.

So, is the "integrated" option of the installer different than using the app store? After what I've read, I would have expected "integrated" to be simply using the app store automatically. Of course, some docs explaining the differences beyond keywords like Docker and domain would have helped.

> I see it the other way around: allowing to set the default password again isn't strict enough for a secure installation, imo.[...]

Which proves my argument: If you don't check those cases, you don't need to force me to use new credentials, TLS etc. as well.

> [...]we try to make the setup as simple but also the default configuration as secure as possible for everyone.

And a pretty secure default config totally makes sense for a production system, but not for people like me testing privately first. At least the unnecessary TLS-requirements should be mentioned somewhere early, because I might have not bought the VMs if I had known beforehand of these system requirements, which I simply can't fulfill easily in my setup anyway.

> I don't think that @enoch85 has the ressources to implement, maintain and offer yet another configuration of the NcVM so this will likely not happen.

Then I suggest to simply drop variants with different storage sizes for data. It's far easier for people to take care of those things themself e.g. based on one VM with "external" storage than to work around the current restrictions of the installer.

> [...]And if you know what you are doing, why don't you install it yourself or just edit the script to allow it to install it on your instance?

A product has been offered which sounded good to start with, so I used that. Only because I'm able to install everything on my own, hack the installer etc., that doesn't mean I want to or that it's any faster than it could be. The offered VMs totally make sense and I have the feeling that's it's unnecessary 5% functionality that makes things unnecessary difficult with 95% of really good choices.

> Then just reuse the documented credentials :)

The installer doesn't allow that at some point, it explicitly makes clear that `ncadmin` can not be reused. After allowing me to enter the SAME password before, that doesn't make too much sense.

> Apart from the Nextcloud admin username, you can always reuse the default credentials. My advice: just use admin as Nextcloud username, which is pretty straight forward, imo.

And what exactly is the point in forcing me to NOT use `ncadmin` again? That's what this issue is about, NOT that one can't think of other easy to maintain credentials. It's an unnecessary restriction for very basic use cases like mine and not even in line with allowing to provide already used passwords. Simply make it a warning note instead to not reuse default credentials e.g. in production use cases and all would be fine.

> The scripts are made in a way to check if all requirements are fullfilled at the start of the script.[...]

But there is no documentation what is required when. I'm able to NOT choose TLS, which is good, am able to choose Collabora, choose if to install it integrated or using Docker, but later the script refuses to install because of a lack of TLS. How can integrated Collabora explicitly chosen because NOT requiring a domain etc. be less secure without TLS than Nextcloud itself, which is allowed to NOT use TLS? That doesn't make much sense and without such a check there would be a happy customer more instead, telling the whole world how good the pre-configured VMs were to at least start testing with.

Again: Those limitations are NOT documented anywhere and at least some kind of documentation would have made sense when choosing the options in the installer. Some `[...] (TLS required)` in the option name would have been a lot less surprising already. Of course, especially using "integrated", you better wouldn't care at all.

> I really wonder why you are ranting here: if it doesn't fit for your purposes, just use a different solution :)

A customer providing feedback is not automatically ranting only because you see things differently.

**Comment by szaimen** [comment]
> How can integrated Collabora explicitly chosen because NOT requiring a domain etc. be less secure without TLS than Nextcloud itself, which is allowed to NOT use TLS?

BTW: Nextcloud is running with TLS by default but is using a self-signed certificate -> that can be a problem when installing integated collabora/onlyoffice here. -> Needs to be tested.

> A customer providing feedback is not automatically ranting only because you see things differently.

Yes, but writing things in capital letters and complete sentences in bolt implies that automatically.
Also that sentence `Why are you making my life unnecessary difficult?! :-/` Does underline that, too.

BTW: I am not afiliated with Nextcloud nor with Hansson IT and just a comunity volunteer.

---

To bring this discussion forward:
Okay, I see now a three points of suggested improvements:
1. find out if integrated documentserver (Onlyoffice and collabora) can get made work without checking for a valid certificate and if yes, don't check for a valid certificate
2. allow to reuse the same username when creating new admin user in Nextcloud or just skip this step
3. document somewhere that the integrated scripts require a valid certificate (if step 1 is not possible)

Is that correct or is there something missing?

**Comment by enoch85** [comment]
@ams-tschoening Dispite the discussion here I don't see the real benefit except that you would save a couple of minutes during setup.

If we would make a custom VM for everyone that asked for it, we wouldn't have time for anything else. This VM is crafted during several years. We made some choices along the way and security is not something we are going to degrade.

As @szaimen already mentioned

> we try to make the setup as simple but also the default configuration as secure as possible for everyone.

**everyone**, so that means a VM that suits everyone and not just 10 or 1000 or 1 million people. If you want your own VM, then make something that suits *you*. You are welcome as a maintainer to this project and invest your time in a cause you believe in. 

> And a pretty secure default config totally makes sense for a production system, but not for people like me testing privately first. 

Sounds like the best option for you is the snap or the official VM ([which we also make](https://github.com/nextcloud/vm/releases/tag/21.0.0)). 

> A lot of arguments why you need this and that

Right now, you're like "hey, I demand you to do this because it's what *I* need". The whole approach to this discussion makes me very un-motivated to help you at all.

> Why are you making my life unnecessary difficult?! :-/

....

I stand for the choices made in this VM, I'm proud of the work we've achieved here. We help thousands of people (probably in the hundreds-range) to install Nextcloud and benefit from everything it offers. If you don't like it, please choose something else.

For the rest of your questions, feel free to use your favorite search engine. Everything you see here are bits and pieces of the internet put together during years of maintenance. You're welcome to maintain the documentation so that others can benefit from your findings. :+1: 

If @szaimen wants to help you with your concerns, great!

**Comment by ams-tschoening** [comment]
> Yes, but writing things in capital letters and complete sentences in bolt implies that automatically.

It does not necessarily, but simply a tool to focus on key arguments in a longer amount of text. Pretty much like `everyone` is used in bold by @enoch85.

> Is that correct or is there something missing?

Number 2 should be expanded to all aspects of forcing unnecessary security I didn't trigger/mentioned yet.

> @ams-tschoening Dispite the discussion here I don't see the real benefit except that you would save a couple of minutes during setup.

1. saving a couple of minutes was worth it paying for your product.
2. it's not only about that anyway, forcing e.g. Let's Encrypt in my setup is practically impossible to fulfill. I would need to pay for domains I don't need, I might need to lower security of my internal network by setting up port forwarding which the installer is suggesting already and stuff like that. Removing all of that would actually not save a couple of minutes only, but provide a better usable product instead.

> If we would make a custom VM for everyone that asked for it, we wouldn't have time for anything else.[...]

I'm not asking for a specific VM for me, just that overall inconsistent and unnecessary decisions of the installer are reconsidered, which would help everyone with my use case. And those are very likely many more people like who need to decide if to use 500, 1000 or 2000 GiB of "external" storage.

> [...]We made some choices along the way and security is not something we are going to degrade.

You already did by allowing unsecure, publicly documented passwords to be reused, forcing TLS only sometimes, suggesting people should put port forwardings into place to weaken their private network security or do that on your own using UPNP etc. So your argument of "strict security" doesn't hold too much.

> everyone, so that means a VM that suits everyone and not just 10 or 1000 or 1 million people.

I am `everyone` as well and submitted feedback to your decisions.

> Right now, you're like "hey, I demand you to do this because it's what I need".

Asking for changes using phrases like `please` and `suggest` is obviously not `demanding` and providing feedback as a customer is a valid approach in general of course. Your problem pretty much seems to be that you think that your decisions are the best possible already, but you might simply be wrong.

> The whole approach to this discussion makes me very un-motivated to help you at all.

Both of you seemed very unmotivated to even consider my feedback to make any valid point at all right from the start. E.g. `🍿` is a non-starter for serious arguments most of the times.

**Comment by szaimen** [comment]
I was actually motivated to help you with your concerns, but I've just lost the motivation.

My advice to you, if you want your concerns to to get fixed: create working PRs so that your suggestions can get further discussed.
