### ISSUE TITLE
Issue with first run

### ISSUE THREAD

**Issue by hibrad2003** [nextcloud/vm#1878]
## Steps to reproduce
1. Fresh spinup of nextcloud
2. Enter initial config
3. Downloading locales failed, onscreen prompt says: "Script failed to download. Please run: 'sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/locales.sh|php|py' and try again.
If it still fails, please report this issue to: https://githhub.com/nexcloud/vm/issues

## Expected behaviour
NC should install??

## Actual behaviour
Running said script results in the following error:
/usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
from collection import Iterable

Nothing else happens.

## Server configuration

**Nextcloud server version:** cant even setup to tell you
**Server OS** (Ubuntu headless server)

**PHP Version** (e.g. 7.4) ?

**How did you install the VM?** Purchased a prebuilt VM from HanssonIT and spun up in HyperV on Server 2019

## Network
Irrelevant, it can connect to the internet

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
/usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

#### Screenshots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by enoch85** [comment]
@hibrad2003 Can you please post your order ID here?

Thanks!

**Comment by enoch85** [comment]
Sorry, but that VM is too old to still be valid without manual modifications.

You can check the git commit history since that version and manually implement all the changes, or you can get a new fresh version from the shop with NC 21.
