### ISSUE TITLE
Info on update vm

### ISSUE THREAD

**Issue by silenx** [nextcloud/vm#1879]
Hello , i currently have an Ubuntu 18.04.5 LTS with vm appliance installed some time ago.
I can't update to 21 because of php .. is ok 
version is  now at 20.0.7 while 20.0.8 is out.
Running update script i get:
Trying to automatically update all Nextcloud apps...
Your apps are already up to date!
Checking for new Nextcloud version...
Latest release is: 21.0.0. Current version is: 20.0.7.
New version available, upgrade continues!

Is it possible to upgrade to 20.0.8 with script?
Thank you

**Comment by szaimen** [comment]
Hi @silenx 👋

The simplest way to update to 20.0.8 is to run `sudo bash /var/scripts/update.sh minor`. 

Hope it helps! :)

**Comment by silenx** [comment]
Thank you.
I didn't know the option "minor" 
nice to know now.

**Comment by enoch85** [comment]
Even better, run `sudo bash /var/scripts/menu.sh` and choose minor + updating the update script.

**Comment by silenx** [comment]
I don't have menu.sh in /var/scripts
