### ISSUE TITLE
'Trying to access array offset on value of type bool' during instalation

### ISSUE THREAD

**Issue by UweKrause** [nextcloud/vm#1887]
Out of curiosity I just tried the install script in a lxd container on my local machine.
It worked well :)

At an early stage of the installation (sorry, can't pinpoint it...), I stumbled upon a minor warning that I just quickly want to share with you.
Despite this warning, everything seems to be okay.

## Steps to reproduce
1. use install script

## Expected behaviour
no warnings

## Actual behaviour
warnings. See Installation log

## Server configuration

**Nextcloud server version:** 21.0.0

**Server OS** Ubuntu 20.04

**PHP Version** 7.4

**How did you install the VM?** Scripted install from master 

#### Installation log (command output)
```
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...

Notice: Trying to access array offset on value of type bool in PEAR/REST.php on line 187
PHP Notice:  Trying to access array offset on value of type bool in /usr/share/php/PEAR/REST.php on line 187

Notice: Trying to access array offset on value of type bool in PEAR/REST.php on line 187
PHP Notice:  Trying to access array offset on value of type bool in /usr/share/php/PEAR/REST.php on line 187

Notice: Trying to access array offset on value of type bool in PEAR/REST.php on line 187
PHP Notice:  Trying to access array offset on value of type bool in /usr/share/php/PEAR/REST.php on line 187

Notice: Trying to access array offset on value of type bool in PEAR/REST.php on line 187
PHP Notice:  Trying to access array offset on value of type bool in /usr/share/php/PEAR/REST.php on line 187
downloading smbclient-1.0.6.tgz ...
```

**Comment by enoch85** [comment]
Please report this to PECL and not here. You could also use your favorite search enginge and look for `Trying to access array offset on value of type bool in PEAR/REST.php on line 187`

Thanks!
