### ISSUE TITLE
certbot stop working after 3months 

### ISSUE THREAD

**Issue by lukaspavelka** [nextcloud/vm#1889]
Hello, 

My Nextcloud 20GB image for Virtualbox was working well 3 months.
But after 3 months working SSL cert from Letscrypt expired and didn't been renew automatically. So i today check VM and find out errors: 

tain -n 5 /var/log/letsencrypt/cronjob.log
```
Let's Encrypt FAILED!--2021-03-10_12:03
Let's Encrypt FAILED!--2021-03-11_00:03
Let's Encrypt FAILED!--2021-03-11_12:03
Let's Encrypt FAILED!--2021-03-11_18:06
Let's Encrypt FAILED!--2021-03-12_00:03
```

so i try to run command manually as root user: 
certbot renew

info from file: 
cat /var/log/letsencrypt/letsencrypt.log

```
2021-03-12 09:47:10,715:DEBUG:acme.client:Storing nonce: 0103nSqwlTXIJQmfgN8UhpFk2CLM954Az4zVQGVRiMEHYI4
2021-03-12 09:47:10,715:WARNING:certbot._internal.auth_handler:Challenge failed for domain office.eukos.sk
2021-03-12 09:47:10,715:INFO:certbot._internal.auth_handler:http-01 challenge for office.eucos.sk
2021-03-12 09:47:10,715:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: office.eukos.sk
Type:   unauthorized
Detail: Invalid response from http://office.eukos.sk/.well-known/acme-challenge/Z9Sc6vCArpSV6bTGnCJSycEDfVqlmSTTd3N5g08jAbs [92.245.6.12]: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>
```

My first step to fix issue i find out there is some packages need to do update so i make: apt-get upgrade
**This is what was updated but didn't help to renew cert anyway:** 

Do you want to continue? [Y/n] y
```
Get:1 http://archive.ubuntu.com/ubuntu/ focal-updates/main amd64 linux-firmware all 1.187.10 [103 MB]
Get:2 https://download.docker.com/linux/ubuntu focal/stable amd64 containerd.io amd64 1.4.4-1 [28.3 MB]
Get:3 https://download.webmin.com/download/repository sarge/contrib amd64 webmin all 1.973 [28.8 MB]
Get:4 http://archive.ubuntu.com/ubuntu/ focal/universe amd64 python3-josepy all 1.2.0-2 [28.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ focal/universe amd64 python3-mock all 3.0.5-1build1 [25.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ focal/universe amd64 python3-requests-toolbelt all 0.8.0-1.1 [35.2 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ focal/main amd64 python3-tz all 2019.3-1 [24.4 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ focal/main amd64 python3-rfc3339 all 1.1-2 [6,808 B]
Get:9 http://archive.ubuntu.com/ubuntu/ focal/universe amd64 python3-acme all 1.1.0-1 [29.6 kB]
Get:10 http://archive.ubuntu.com/ubuntu/ focal/universe amd64 python3-configargparse all 0.13.0-2 [22.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu/ focal/main amd64 python3-future all 0.18.2-2 [336 kB]
Get:12 http://archive.ubuntu.com/ubuntu/ focal/universe amd64 python3-parsedatetime all 2.4-5 [32.6 kB]
Get:13 http://archive.ubuntu.com/ubuntu/ focal/universe amd64 python3-zope.hookable amd64 5.0.0-1build1 [11.2 kB]
Get:14 http://archive.ubuntu.com/ubuntu/ focal/universe amd64 python3-zope.event all 4.4-2build1 [7,704 B]
Get:15 http://archive.ubuntu.com/ubuntu/ focal/universe amd64 python3-zope.component all 4.3.0-3 [38.3 kB]
Get:16 http://archive.ubuntu.com/ubuntu/ focal-updates/universe amd64 python3-certbot all 0.40.0-1ubuntu0.1 [223 kB]
Get:17 http://archive.ubuntu.com/ubuntu/ focal/main amd64 python3-icu amd64 2.4.2-0ubuntu3 [250 kB]
Get:18 http://archive.ubuntu.com/ubuntu/ focal-updates/universe amd64 certbot all 0.40.0-1ubuntu0.1 [17.9 kB]
Fetched 161 MB in 35s (4,588 kB/s)
```

OS="Ubuntu 20.04.2 LTS" - VM from you. Nothing changed.

 
**It is very strange issue , i double check configuration of DNS and nobody change anything in last year , so when get certification 3 months ago was working it should work today as well.** 

Nextcloud server version: 
`Version
Nextcloud 21.0.0
Your version is current`

PHP Version: 
`root@office:~# php -v
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
`
Do you use DHCP: **YES but no issue there**

Is port 80 and/or 443 open: **Yes, when i want access website from browser i can do it , only cert is expired.**  

How did you install the VM?** Downloaded VMware / VirtualBox (.OVA): Nextcloud VM Pre-installed – 40 GB**

**Comment by enoch85** [comment]
Thanks for your detailed issue! :+1: 

There are basically two causes:
1. Maybe you used the DNS validation method during setup? That doesn't renew automatically.
2. Port 80 is closed and the cert can't be renewed.

You can read more here: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6-83ePiqQz3_MrT/publish-your-server-online

**Comment by lukaspavelka** [comment]
Thanks for answer. 

1) Maybe, i don't know, how i can find out and how i can renew it now?
2) Port is opened 100% because "Is port 80 and/or 443 open: Yes, when i want access website from browser i can do it , only cert is expired."

**Comment by enoch85** [comment]
Just rerun the script from the `menu.sh` script. There's no harm in running it twice.

Please let me know the outcome.

**Comment by enoch85** [comment]
@lukaspavelka How did it go?

**Comment by lukaspavelka** [comment]
Hi @enoch85 

**Some info from my server:** 
root@office:/var/scripts# ls -la

-rwxr-xr-x  1 root    root       48 Oct  8 14:45 dockerprune.sh
-rw-r--r--  1 root    root     1159 Mar 13 18:00 fetch_lib.sh
-rwxr-xr-x  1 root    root       55 Mar 11 17:59 history.sh
-rwxr-xr-x  1 root    root      411 Oct  8 14:14 letsencryptrenew.sh
-rw-r--r--  1 root    root    53641 Mar 14 18:59 lib.sh
-rw-r--r--  1 root    root      547 Mar 13 18:00 menu.sh
-rwxr-xr-x  1 ncadmin ncadmin   448 Oct  8 14:07 nextcloud.sh
-rwxr-xr-x  1 root    root     3083 Mar 13 18:00 setup_secure_permissions_nextcloud.sh
-rwxr-xr-x  1 root    root     3474 Mar 13 18:00 updatenotification.sh
-rwxr-xr-x  1 root    root      706 Oct  8 14:07 update.sh


**Than when i start MENU script it looks like this:** 
bash /var/scripts/menu.sh


┌─────┤ Nextcloud VM - 2021 - Main Menu ├───────┐
 │ Choose what you want to do.                                                                   
 │ Navigate with the [ARROW] keys and confirm by pressing [ENTER]. Cancel by pressing [ESC].   
 │                                                                                              
 │ You can view this script later by running 'sudo bash /var/scripts/menu.sh'.                 
 │                                                                                               
 │          Additional Apps         (Choose which apps to install)                              
 │          Nextcloud Configuration (Choose between available Nextcloud configurations)        
 │          Startup Configuration   (Choose between available startup configurations)           
 │          Server Configuration    (Choose between available server configurations)            
 │          Update Nextcloud major  (Update Nextcloud to the latest major release)             
 │          Update Nextcloud minor  (Update Nextcloud to the latest minor release)                                                                                                           
 │                                                                                               
 │                          <Ok>                              <Cancel>                          
 │                                                                                               
 └────────────────────────────────────┘



**I cant find there any info about letscryt in file menu.sh, only what i can do is start direct script so:** 
bash /var/scripts/letsencryptrenew.sh

**OUTPUT is nothing so i need to dig in log files, but there i can find :** 

/var/log/letsencrypt/renew.log =` Another instance of Certbot is already running.`

/var/log/letsencrypt/renew.log = 
```
Let's Encrypt FAILED!--2021-03-14_00:08
Let's Encrypt FAILED!--2021-03-14_12:10
Let's Encrypt FAILED!--2021-03-15_00:04
Let's Encrypt FAILED!--2021-03-15_12:05
Let's Encrypt FAILED!--2021-03-15_17:42
```


/var/log/letsencrypt/letsencrypt.log = 

```
2021-03-15 13:42:12,703:DEBUG:certbot.display.util:Notifying user:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-03-15 13:42:12,703:ERROR:certbot._internal.renewal:All renewals failed. The following certificates could not be renewed:
2021-03-15 13:42:12,703:ERROR:certbot._internal.renewal:  /etc/letsencrypt/live/office.eukos.sk/fullchain.pem (failure)
  /etc/letsencrypt/live/onlyoffice.eukos.sk/fullchain.pem (failure)
2021-03-15 13:42:12,704:DEBUG:certbot.display.util:Notifying user: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-03-15 13:42:12,704:INFO:certbot.compat.misc:Running post-hook command: systemctl start apache2.service
2021-03-15 13:42:12,733:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/certbot/1042/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/main.py", line 1421, in main
    return config.func(config, plugins)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/main.py", line 1325, in renew
    renewal.handle_renewal_request(config)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/renewal.py", line 506, in handle_renewal_request
    raise errors.Error("{0} renew failure(s), {1} parse failure(s)".format(
certbot.errors.Error: 2 renew failure(s), 0 parse failure(s)
2021-03-15 13:42:12,733:ERROR:certbot._internal.log:2 renew failure(s), 0 parse failure(s)
2021-03-15 17:39:51,105:DEBUG:certbot.main:certbot version: 0.40.0
2021-03-15 17:39:51,106:DEBUG:certbot.main:Arguments: ['-q']
2021-03-15 17:39:51,106:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-03-15 17:39:51,111:DEBUG:certbot.log:Root logging level set at 30
2021-03-15 17:39:51,111:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-03-15 17:39:51,111:INFO:certbot.storage:Attempting to parse the version 1.10.1 renewal configuration file found at /etc/letsencrypt/renewal/office.eukos.sk.conf with version 0.40.0 of Certbot. This might not work.
2021-03-15 17:39:51,115:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7f2597892940> and installer <certbot.cli._Default object at 0x7f2597892940>
2021-03-15 17:39:51,120:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2021-03-11 16:26:05 UTC.
2021-03-15 17:39:51,120:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2021-03-15 17:39:51,120:INFO:certbot.renewal:Non-interactive renewal: random delay of 343.32333241339927 seconds
```

**Comment by enoch85** [comment]
It goes like this:

Menu.sh --> Server Configuration --> Activate TLS.

**Comment by lukaspavelka** [comment]
Omg omg, that's really bad. 

I just find out there was port 80 redirected to another server in my LAN network. I don't know if any of my colleague was testing something before but nobody noticed it more than month because NC instance was working well on port 443. That's why i did not check this before. All working fine and when i try in browser connect on NC i always get to the VM just with expired cert.

Lesson learned: When you need renew letscrypt cert both ports need to be working 80 + 433 !! 

I am so sorry for BAD report. Please close it. All working well after i fix FW config.

**Comment by enoch85** [comment]
Glad you found the issue.
