### ISSUE TITLE
writing in config dir not possible

### ISSUE THREAD

**Issue by cschnack24** [nextcloud/vm#189]
Hello,

after rebooting the vm I get this error:

"Das Schreiben in das „config“-Verzeichnis ist nicht möglich!
Dies kann normalerweise behoben werden, indem dem Webserver Schreibzugriff auf das Konfigurationsverzeichnis gegeben wird."

writing in config directory not possible

I am not that into linux and this is the third time I get the error,
so I hope someone can help me.

## Steps to reproduce
I don't exatcly know when it happens
Until now It happens when 

1. Server crashes 
    when it crashes the whole hypervisor crashes, can't say if the nextcloud vm causes this
2. power failure
3. sometimes on reboot

##My Solution until now
Restoring older Backups :'-( :-D

## Server configuration
running on vmware esxi 6.5
Server version: 11.0.2
VM version 30.03.2017
fresh install:
## Network
static ip
Is port 80 and/or 443 open? yes

## Log file (/var/ncdata/nextcloud.log)
cannot upload, "read only file system" when I try to access

**Comment by enoch85** [comment]
Thanks for your report! Though at first glance I don't think this has to do anything with the VM as you get a "read only" file system, and the VM doesn't come with that.

Is this problem occusring with the VM or on a separate server where you used the scripts to install? Also, how did you install the OS? Did you change anything?

**Comment by cschnack24** [comment]
I mounted the vm on a hypervisor.

Because of "no network errors" when mounting the vmdk on the esxi I first installed it on vmware workstation on my desktop. Finished everything and uploaded it to the esxi. 
Where in most cases i runs smooth.

The only thing I changed, without the official scripts is installing nfs-common and mounting some nfs drives under /mnt/nfs

**Comment by enoch85** [comment]
> The only thing I changed, without the official scripts is installing nfs-common and mounting some nfs drives under /mnt/nfs

And you mounted them as read only?

**Comment by cschnack24** [comment]
I edited etc/fstab:
`192.168.2.40:/database1  /mnt/nfs/storinator/database1   nfs      rw,sync,hard,intr  0     0`

**Comment by enoch85** [comment]
I have no clue why you got a read only drive. Must be something you did as the VM isn't shipped like that out of the box.

The crash issues maybe due to lack of RAM or disk space. Have you checked that? (`df -h && htop`)

**Comment by cschnack24** [comment]
> the VM isn't shipped like that out of the box
yes I know
the "read only" error appears later, after a few days or weeks of use.

Is there a way to see the logs, despite the read only filesystem?

I wrote back a backup, from which state I didn't changed anything until it crashed.
(everything is read and written to/from nfs or smb storages)

Here the RAM and HDD stats:

654M/1,94G doesn't seem to be the RAM
Where can I see disk space?
if I use  `df -h` everything is below 20% (except the nfs mounts)

**Comment by enoch85** [comment]
You are the first one to mention this issue in 3 years of making the VM, so I'm suspecting that your mounts' or something you did messed things up. Especially as it's working when you revert to a unchanged backup.

Still. I would be happy to know what's causing it. 

I don't know if you have `cat` available? in that case you could show the logs. You could do something like `tail -f /var/log/log.log > output.txt` and then just wait for the error to happen, and when it happens read the output log.
