### ISSUE TITLE
T&M Hansson IT - The apache conf for <nextcloud name> isn't available. This is not supported! 

### ISSUE THREAD

**Issue by herrschlupp** [nextcloud/vm#1892]
Hello,
I installed a nextcloud VM from T&M Hansson IT.

When I try to install the high performance backend (push server) I got the following issue:
**The apache conf for <nextcloud name> isn't available. This is not supported!** 

My system details are:
Linux 5.4.0-66-generic x86_64
Intel(R) Xeon(R) CPU D-1541 @ 2.10GHz (8 cores)
RAM 15.63 GB
PHP Version: 7.4.3
PostgreSQL 12.6

Thanks in advance
-herrschlupp

**Comment by szaimen** [comment]
Hi, @herrschlupp thanks for your report!
How did you enabled
 lets encrypt on your instance? Did you use the built-in script?
https://github.com/nextcloud/vm/blob/master/lets-encrypt/activate-tls.sh
Or are you using e.g. some kind of reverse proxy for the VM?

**Comment by enoch85** [comment]
What I believe @szaimen is reaching for; the script assumes some defaults in the VM that's been there for years. If you made some modifications yourself, or even did the whole installation yourself, the pre-checks will stop you from continuing.

The specific error message you got indicates that the Apache conf isn't in the default path, or isn't named to the default name.

In any case, you need TLS (with the built in script) to be able to continue. 

Maybe @szaimen can have a look at making the error messages better?

**Comment by szaimen** [comment]
> Maybe @szaimen can have a look at making the error messages better?

Some ideeas how to improve it?
Maybe: `It seems like you haven't used the built-in activate-TLS script to enable 'Let's Encrypt!' on your instance. Unfortunately is this a requirements to be able to configure $SCRIPT_NAME successfully. So cannot proceed!`
@enoch85 what do you think?

**Comment by enoch85** [comment]
If you be better do to the check more generic, e.g. not looking for an exact path in Apache.

I'll come up with something soon.

**Comment by szaimen** [comment]
> If you be better do to the check more generic, e.g. not looking for an exact path in Apache.

Since we write something to this apache conf, I guess this will always be a requirement....

> I'll come up with something soon.

Looking forward to this!

**Comment by enoch85** [comment]
Maybe something like https://github.com/nextcloud/vm/pull/1893 ?

**Comment by szaimen** [comment]
> Maybe something like #1893 ?

The PR makes sense for the documentserver but won't work for Notify Push, unfortunately!

**Comment by enoch85** [comment]
@szaimen 

> It seems like you haven't used the built-in activate-TLS script to enable 'Let's Encrypt!' on your instance. Unfortunately is this a requirements to be able to configure $SCRIPT_NAME successfully. So cannot proceed!

Please commit that text instead and close this issue.

Thanks!

**Comment by enoch85** [comment]
Please notice my latest changes to the text.

**Comment by herrschlupp** [comment]
Hello all,
i will answer tomorrow when I‘m back home. 
Thanks for your answers.
