### ISSUE TITLE
pecl.php.net/igbinary not available?

### ISSUE THREAD

**Issue by 3Dscrewer** [nextcloud/vm#1895]
Windows 10 Pro all updates, Hyper-V.
ubuntu-20.04.2-live-server-amd64.iso

Since I didn't use and update NC for a while the update.sh failed. So I tried new install by your script with clean setup.
First I found out ...
I'm using an own SSD for the VM and a virtual HD as second HD. Even if your script is saying it is deleting the data at the second VHD, it don't. First time setup script broke because I was using same admin name and the folder was still available and of course not empty.

second and third try...

Notice: Trying to access array offset on value of type bool in PEAR/REST.php on line 187
PHP Notice:  Trying to access array offset on value of type bool in /usr/share/php/PEAR/REST.php on line 187
No releases available for package "pecl.php.net/smbclient"
install failed
PHP Warning:  PHP Startup: Unable to load dynamic library 'smbclient.so' (tried: /usr/lib/php/20190902/smbclient.so (/usr/lib/php/20190902/smbclient.so: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/smbclient.so.so (/usr/lib/php/20190902/smbclient.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Notice: Trying to access array offset on value of type bool in PEAR/REST.php on line 187
PHP Notice:  Trying to access array offset on value of type bool in /usr/share/php/PEAR/REST.php on line 187
No releases available for package "pecl.php.net/igbinary"
install failed

I guess there is a typo in the script or the file is not available

**Comment by enoch85** [comment]
Thanks for posting your issue!

Maybe PECL have issues with their servers? I believe it's just temporary, it happens sometimes (like 4 times in the past 6 years that I know if) that PECL servers aren't 100%.

Just try again later.

**Comment by enoch85** [comment]
Also regarding the script, it assumes the disks are `sdb`, safest option if you're not sure is to use the second option to manually choose the disk.

**Comment by enoch85** [comment]
This should now be fixed. I noticed the same issue recently and added a commit to fix it.
