### ISSUE TITLE
End to End Encryption app won't enable

### ISSUE THREAD

**Issue by Larrikinau** [nextcloud/vm#1906]
Hi - I’ve just installed the 2TB VM from T&M Hansson IT.

I want to enable the end to end encryption app, so I click on the button “Download and enable”. I get an error message “An error occured during the request. Unable to proceed.”

The app downloads as now I am only presented with the “enable” button. When I click on enable, I get the following error message: “An error occured during the request. Unable to proceed.” Same error.

I tested to see if I could install other apps, so tried the “news” app, and that installed fine.

Bug? Deliberate action behaviour by the VM?  How do I enable it?

**Comment by szaimen** [comment]
Hi @Larrikinau, thanks for your report!
The end-to-end-encryption app is just not yet compatible with Nextcloud 21. Please follow e.g. https://github.com/nextcloud/end_to_end_encryption/issues/224 for further resolution.
Thanks!
