### ISSUE TITLE
improve the built-in backup solution to work with normal NcVM configurations?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1910]
Hey @enoch85 I wonder if I should invest the time to make the backup scripts compatible with the normal NcVM configuration?

What would be needed is the following:

0. Improve wording that you wont be able to use the built-in bavkup solution it you choose to not create the partition
1. make this partition to the default in any new installation: https://github.com/nextcloud/vm/blob/c6fab8acab4cbf1cfa8ffb2c13d5cc2627e50eae/nextcloud_install_production.sh#L67 
2. add a new option to modify a smbmount to be a backup mount here: https://github.com/nextcloud/vm/blob/c6fab8acab4cbf1cfa8ffb2c13d5cc2627e50eae/apps/smbmount.sh#L133-L134
3. allow those kind of mounts to be viable for the backup wizard script here: https://github.com/nextcloud/vm/blob/c6fab8acab4cbf1cfa8ffb2c13d5cc2627e50eae/not-supported/daily-backup-wizard.sh#L69-L70 (and don't fail if /mnt/ncdata is in mounttab) (don't allow custom mounts: can cause unexpectable problems)
4. modify the borgbackup script to create dedicated backups of the /mnt/ncdata partition
5. modify the system-restore script to be able to restore also the /mnt/ncdata partition from those backups
6. optional: modify the restore-backup script to allow to restore the /mnt/ncdata partition, too (also allow NcVM reserved in this case to not be present) (and don't check for /mnt/ncdata in the mounttab this case) also allow to use smbmount backup mounts without having to connect the device

Would you accept the changes that would be necessary? (especially point 1 is of importance)

**Comment by szaimen** [comment]
Also I wonder if, when they are compatible with the default configuration, there would be any chance of making them official (in the long run).

**Comment by enoch85** [comment]
I'm not comfortable with adding stuff I haven't tested myself.

> Also I wonder if, when they are compatible with the default configuration, there would be any chance of making at least the daily backup wizard script script official?

I tested this and it doesn't work if you didn't choose the LVM-snapshots-thing during installation. As that's not default, I would be OK with adding at least the daily backup script to the default apps menu since it won't work for most users anyway. We'll get a broader test surface since users that did choose that option during installing with the scripts may use it.

I've also seen you made a lot of PRs to improve the code. I'd say when this is 100% stable and there are no changes for at least 6 months then I'll consider adding the rest.

**Comment by enoch85** [comment]
In other words, we don't add the LVM snapshots as a default thing just yet.

**Comment by szaimen** [comment]
Okay cool! I am already working on making this possible 👍

Though, since apart from the snapshot you also need to mount a drive with the ntfs-mount script or via the smbmount script (and you need to run the update script before you can execute the wizard and you need to set up smtp-mail before), I wonder if this will already limit the amount of people that will use the feature to a manageable amount so that it wouldn't hurt to make the LVM partition already to the default? 

I fear that because of all those requirements including opting for the lvm-snapshot at the very beginning, really few people (near to none) would use it...
