### ISSUE TITLE
Disable updates to NC21.0.1 for now?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#1916]
@enoch85 I wonder if we should disable updates to NC21.0.1 for now?
See https://github.com/nextcloud/server/issues/26423

**Comment by szaimen** [comment]
If you aggree, we could just replace this string: https://github.com/nextcloud/vm/blob/c23cdb7b30ed4cc75992a73d6d91c8a9bf629424/nextcloud_update.sh#L617

**Comment by enoch85** [comment]
Yes please!

**Comment by enoch85** [comment]
Done

**Comment by szaimen** [comment]
Based on https://github.com/nextcloud/server/issues/26423#issuecomment-815718134 it should work with the final release. So should we reallow this version then? (Didn't test)

**Comment by enoch85** [comment]
Spinning up my test rig now. Soon we'll know. :)
