### ISSUE TITLE
Add support for Let's Encrypt DNS based certificate issuing

### ISSUE THREAD

**Issue by eglipeter** [nextcloud/vm#1917]
It would be great, if the user could also enable Let's encrypt on the machine via a DNS challenge, e.g. by using the https://github.com/ctrlaltcoop/certbot-dns-hetzner
plugin. We have a server that is not reachable from the internet and would like to setup autorenew on a vm based Nextcloud server thru the DNS-API of Hetzner.

**Comment by enoch85** [comment]
Related: https://github.com/nextcloud/vm/issues/734
