### ISSUE TITLE
No network interface after install

### ISSUE THREAD

**Issue by necrevistonnezr** [nextcloud/vm#192]
## Steps to reproduce
1. Installed a vanilla Ubuntu Server 16.04.2.
2. Download install script, first stage until reboot goes through without errors
3. After login and entering my sudo password, I get an error that "Network is not ok." 

## Expected behaviour
Stage 2 of the install (after login). 

## Actual behaviour
No internet connection. "journalctl -xe" gives "Failed to start Raise network interfaces". The file /etc/network/interfaces contains no eth0 device or ens192 or similar, just the loopback device. Manual ifup  does not work. "Ip link show" only lists the "lo" device. But it worked in stage 1 of the install!

## Server configuration

**Server version:** (see your admin page)
Ubuntu 16.04.2 Server
**VM version** (master / released version)
No VM, running on a ASRock Beebox N3000. 
**Updated from an older installed version or fresh install:**
Fresh
## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Please fill in the Network info as well.

Can you extract the VM again and then run it and Debug Mode (change inside the script) and post the output here please?

**Comment by enoch85** [comment]
@necrevistonnezr Please try the new master and see if the issue persist. Thanks!

**Comment by necrevistonnezr** [comment]
I did a fresh Ubuntu server install and downloaded master again. 
Now I'm stuck on DHCPDISCOVER, see https://imgur.com/a/KABJX

**Comment by necrevistonnezr** [comment]
Ok, after 5 Minutes or so the script continues

**Comment by enoch85** [comment]
@necrevistonnezr Is this the first install script or the second setup script?

**Comment by necrevistonnezr** [comment]
After a reboot, I get an error "Sorry, you are not root" although I am in fact root. I get the same error when I try "sudo bash /var/ scripts/nextcloud-startup-script.sh". 

Apparently there are errors in line 15 and 18 of said script: "debug_mode" and "is_root" are not found as commands.

**Comment by morph027** [comment]
Hm..then the remote sourcing of lib.sh is failing for whatever reasons....

Is your machine connected to the internet now?

**Comment by necrevistonnezr** [comment]
> Is your machine connected to the internet now?

No, still the same. `ip link show` shows only the `lo` device, even though the `/var/network/interfaces` file - other than the last time - now contains a section with a device `enp2s0`

**Comment by enoch85** [comment]
@necrevistonnezr What happens if you change to DHCP in the interfaces file and reboot?

**Comment by necrevistonnezr** [comment]
It's already on DHCP. The Ethernet interface just doesn't work or show up after the first part of the install script. If I clone my vanilla server image back via Clonezilla, the interface works.

**Comment by enoch85** [comment]
@necrevistonnezr Please send me an email and I'll investigate further. You can find the contact info here: https://www.techandme.se/contact/

**Comment by necrevistonnezr** [comment]
Hi,

I just tried on a OVH.net VPS - it works. So there's an issue with my hardware / network, not with your scripts.

Thanks for all your help!

**Comment by kambatx** [comment]
Hello, I have the same problem and do not know what I should do. With ifconfig only the loopback adapter is displayed. Probably I can not run the script. What can I do to solve the problem? best regards Anton
