### ISSUE TITLE
Collabora Online Version

### ISSUE THREAD

**Issue by miguelzabala** [nextcloud/vm#1925]
Hi,

First of all, please excuse me about my bad english, It's not my primary language.
Just to know: Why the version of Collabora Online installed is the Development Edition (CODE) and not the stable version? And how can I switch to the stable version?

Thank you.

**Comment by szaimen** [comment]
Hello, I am not sure what you are refering to. Collabora Online Development Edition is actually the stable version.
See https://hub.docker.com/r/collabora/code/
