### ISSUE TITLE
updater.phar does not check for app compatibility

### ISSUE THREAD

**Issue by nerrehmit** [nextcloud/vm#1926]
According to this forum post by @rakekniven I'm creating an issue in this repository.
https://help.nextcloud.com/t/nc-20-too-many-incompatible-apps-what-to-do/93869/9

It still looks like the `updater.phar` does not check if all apps are compatible with the version we want to upgrade to in contrast to the Upgrade from the Web-UI

## Steps to reproduce
1. Check the Web-UI for available upgrades. If there are upgrades it displays whether all apps have an update available.
![nextcloud-staging-19-update](https://user-images.githubusercontent.com/15264624/115526480-5f223600-a290-11eb-8bf2-6c77f8847fca.png)
2. Execute the `updater.phar` script with `sudo -u nginx php /var/www/nextcloud/updater/updater.phar` according to https://docs.nextcloud.com/server/21/admin_manual/maintenance/update.html
3. The command line upgrade has no such check (or does not provide the info prior to the upgrade).
![image](https://user-images.githubusercontent.com/15264624/115526847-bf18dc80-a290-11eb-9134-dcf65d004b91.png)

## Expected behavior
Would be nice if the console update also presents information about app compatibility during update.

## Actual behavior
updater.phar has no info about app compatibility.

## Server configuration

**Nextcloud server version:** (see your admin page)
Both NC 19.0.6 and NC 19.0.10

**Server OS** (Ubuntu server is default)
CentOS Stream 8 (was regular Centos 8 at time of install)

**PHP Version** (e.g. 7.4)
`root@nextcloud02 therren]# php -v
PHP 7.3.20 (cli) (built: Jul  7 2020 07:53:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.20, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.20, Copyright (c) 1999-2018, by Zend Technologies
`
**How did you install the VM?** (Scripted install from master **OR** Released version)
Released Version from .zip file.

**Comment by szaimen** [comment]
Hi, thanks for your report!

> Would be nice if the console update also presents information about app compatibility during update.

This is unfortunately not yet possible. It is also nothing we can implement and fix in the VM itself.

Also, if you are running the NcVM,  I would always recommend to use the update script ehen you update Nextcloud that you can find here: /var/scripts/update.sh

**Comment by nerrehmit** [comment]
Hi, thanks for getting back so quickly.

After browsing this repository for a bit it indeed seems like the forum discussion pointed to the wrong repository. At least in my case I did not install my server with NcVM.
Do you know why it's currently not possible? The info seems to be there one way or another. 
The workaround to quickly check the Web-UI before doing an update on the CLI is not too bad, just wondering.

**Comment by szaimen** [comment]
> Do you know why it's currently not possible?

Because it is not yet implemented.

> The workaround to quickly check the Web-UI before doing an update on the CLI is not too bad, just wondering.

So then I hope you are fine that I close this issue now! :)
