### ISSUE TITLE
Apache log in root directory / with extreme sizes

### ISSUE THREAD

**Issue by markkco** [nextcloud/vm#1931]
Hello!
I'm using Nextcloud VM installed with scripts (currently updated to 20.0.9). I stumbled on /access.log being few hundred MB's.

I checked why does Apache log out to /access.log. Could it be that /etc/apache2/sites-enabled/domain.com.conf
contain:
```
# Logs
LogLevel warn
CustomLog /access.log combined
ErrorLog /error.log
```
Should log files be located in /var/log/apache2/* ?

**Comment by enoch85** [comment]
@markkco Hey, great find!

Which script is this related to? Collabora?

**Comment by szaimen** [comment]
After a quick search I found out that probably all scripts with apache configs are effected since ${APACHE_LOG_DIR} isn't escaped anywhere and because it also doesn't exist in the lib.sh file, it just gets written as empty to the file...
So either we add the variable to the lib.sh file or we escape ${APACHE_LOG_DIR} in order to solve this...

**Comment by szaimen** [comment]
Also we should probably delete the file in the root folder and/or rotate it regularly?

**Comment by markkco** [comment]
Another strange thing connected to the issue is that /etc/apache2/envvars do not get loaded at startup. I'm linux newb so maybe this has to be this way. Apache should write logs to $APACHE_LOGDIR as defined in envvars.
Script which generates /etc/apache2/sites-available/domain.com.conf is [https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L682](url)
based on template default-ssl.conf (?):
```
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
```
And, Daniel, thank You for creating NC VM scripts! Also to everyone working on them!

**Comment by szaimen** [comment]
See #1932

**Comment by enoch85** [comment]
The PR is now merged. 

I think maybe we should delete the old logs as @szaimen suggested. But at the same time, that means fixing all old installations as well, so naah, let's leave it.

**Comment by enoch85** [comment]
Close?

**Comment by szaimen** [comment]
Question is if there should be something like a logrotate in place?

**Comment by enoch85** [comment]
>Question is if there should be something like a logrotate in place?

I think that's handled automatically since we use the default Apache log path.

**Comment by szaimen** [comment]
> I think that's handled automatically since we use the default Apache log path.

If thats actually the case then great 👍
