### ISSUE TITLE
Enhancement: Mail server

### ISSUE THREAD

**Issue by speakradmin** [nextcloud/vm#1936]
More details about the project here: https://123qwe.com/

Would it be possible to add the setup from this tutorial as an option in the Nextcloud VM install script? The setup is very similar seeing as it also uses Postgres instead of Mariadb. It's mainly adding users to a new DB and installing and configuring Postfix, Dovecot and Rspamd.

I'm just starting out with scripting so not sure where to start to be honest

**Comment by enoch85** [comment]
Thanks for your suggestion, but I don't see support for Ubuntu 20.04 anywhere?

**Comment by speakradmin** [comment]
Yes I was worried that might be a problem. I have gotten it mostly working on a Ubuntu 20.04 server after running the VM scripts. If I can figure out the last few things I will try get in touch with the very friendly and helpful Alexey and see if support for Ubuntu 20.04 is possible.

**Comment by enoch85** [comment]
Sounds good!

Do you want to be project lead @szaimen?

**Comment by szaimen** [comment]
> Do you want to be project lead @szaimen?

Thanks for the offer!
Though, since mail servers don't make a lot of sense to be hosted at home, I am not interested in this but @speakradmin if you need any help, please don't hesitate to ask and I'll be there to help! 
Just one wish from my side: I hope this can be implemented as optional addon like other addons in this Repo so that the user is able to choose if he/she wants to do this or not.

**Comment by speakradmin** [comment]
Thanks @szaimen will do!

**Comment by TheNomad11** [comment]
> Though, since mail servers don't make a lot of sense to be hosted at home

Many people do not host Nextcloud at home, but on a VPS

**Comment by szaimen** [comment]
> Many people do not host Nextcloud at home, but on a VPS

I know but hosting Nextcloud at home is my point of interest 😉

**Comment by enoch85** [comment]
VPS or home doesn't matter, same thing really in terms of OS and scripts to deploy. Hardware or location doesn't matter in this case.

**Comment by szaimen** [comment]
Yes, but mail servers don't work reliably on home servers because of many issues, afaik. 
E.g. the dynamic ip-adress.

**Comment by szaimen** [comment]
Btw: here are some docs about necessary external configuration which might be of some help: https://yunohost.org/en/email

**Comment by speakradmin** [comment]
Sorry for wasting everyone's time. It seems like the project at https://123qwe.com/ has gone a bit stale. I'm sure Alexey will eventually come back to it but as it stands, the two required nextcloud apps namely "Auto Mail Accounts" and "User Backend Using Raw SQL" haven't been updated for Nextcloud 21.

Although I was able to get this partially working on a vanilla Ubuntu 20.04 server, there are still some issues which I suspect are because of something broken in the required apps.

Something like https://modoboa.org/en/ might be a better option for those wanting to run a self hosted mail server. I'll do some testing and if it turns out to be promising, I'll open a new issue.

**Comment by szaimen** [comment]
What about [mailcow](https://mailcow.github.io/mailcow-dockerized-docs/i_u_m_install/): Could that be an alternative to [Modoboa](https://modoboa.readthedocs.io/en/latest/installation.html#recommended-way)?

**Comment by speakradmin** [comment]
I was actually quite surprised at the number of projects out there for self hosted mail servers. It's great that we have so many options. :-D

Yes I think mailcow is a good option as the project is well documented and already dockerised.

I see there is a helper script for setting up a Nextcloud instance on your mailcow server. This then sets up SSO so that you can sign into Nextcloud using your mailcow credentials but I would imagine that doesn't suit this projects goals.

Perhaps it can be modified to work the other way around ie use your Nextcloud credentials to sign into mailcow? Also, automatically creating the mailboxes for each user is quite handy and is something that initially drew me to the implementation at https://123qwe.com/. Perhaps Alexey's "Auto Mail Accounts" app could be forked for this purpose but I'm not a developer so wouldn't know where to start.

In any event I'll try get a docker instance of mailcow running and report back here

**Comment by speakradmin** [comment]
Hey guys, just a quick update.

So it appears that if we go for the docker method of installing Mailcow, we will run into some problems with conflicting ports. I use Nginx Proxy Manager to get around this for some of the other self hosted things I run at home and it works exceedingly well.

In essence, all of the containers behind NPM need to be on the same docker network and then it's not necessary to run any of the containers with ports 80 and 443 exposed. NPM then maps the required ports to the **container hostname** based on the FQDN you are accessing. This will then mean that 80 and 443 must be port forwarded to the host running NPM instead of the Nextcloud instance itself.

NPM also handles the issuing of Letsencrypt certs which means that it would no longer be needed on the Nextcloud server natively. It is a very popular way for people running self hosted things at home to access multiple servers behind a single IP.

One could obviously run this on two separate servers and then point the various services at each other etc but I would imagine most people would like to have everything contained on one server

So in the end I'm not sure to what extent this aligns with the Nextcloud VM project's goals. To be honest it seems like it would just be simpler to run everything in docker including Nextcloud but that comes with it's own challenges obviously not to mention losing out on all the great stuff that the Nextcloud VM scripts install and configure.

Curious to anyone's thoughts on all this

**Comment by szaimen** [comment]
@speakradmin Thanks for the update! 

How I'd imagined this could made work is the following:
- use Apache as reverse Proxy for the mail server like we already do in many scripts.
- use mailcows generate_config.sh script and modify at least HTTP_PORT and HTTPS_PORT to an unused port to make it work. Here is also an example how to use this with Apache as reverse proxy: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/ 
- use our way to generate certificates for the mailserver (here an example https://github.com/nextcloud/vm/blob/master/apps/bitwarden-rs.sh#L63-L195 - of course the apache config is wrong.)
- probably modify other things in mailcows scripts/config to make it work in the VM.

**Comment by speakradmin** [comment]
That's great thanks @szaimen. I hadn't thought of using Apache for reverse proxy.

I am happy to do any testing on my home lab if needed and provide feedback

**Comment by TheNomad11** [comment]
What about mailinabox, it is more basic and needs far less resources?
https://mailinabox.email/

**Comment by szaimen** [comment]
I guess if it is possible to make this work in the NcVM, this would be fine, too. But I would prefer mailcow...

**Comment by speakradmin** [comment]
Just my two cents after a bit of testing...

I set up mailcow on a standalone freshly installed Ubuntu 20.04 server. For the most part the setup and config was pretty straightforward. The admin console is definitely a strong point of mailcow. It's very comprehensive and as mentioned above well documented. Every setup issue I encountered was easy to resolve by following the docs. For this reason I feel it would be well suited to the self-hosted enthusiast. I did encounter one issue related to DNS and also a few tweaks needed around disabling ufw and ipv6 which I am still troubleshooting. Other than that it is in my opinion a strong choice

Mail in a box is definitely a simpler option but that's not to say it's lacking features. It appears to have more or less everything you will need to safely run a good mail server. Unfortunately it is not officially dockerized although there have been some attempts [here](https://discourse.mailinabox.email/t/miab-running-in-docker-container/6271/12) and [here](https://hub.docker.com/r/mtrnord/mailinabox/). Another downside is that it only supports Ubuntu 18.04 LTS and also installs many of the required packages from 3rd party repos instead of newer official ones. I did try to manually add 20.04 to the various scripts that check OS version but the setup script fails trying to add the aforementioned 3rd party repos which don't exist for focal

Next for me is to figure out the last few issues with mailcow and then I will move on to trying it on my Nextcloud host directly. So far the reverse proxy with Apache looks pretty straightforward but I may get stuck on the certificates part.

**Comment by speakradmin** [comment]
Another option may be something like this: https://github.com/docker-mailserver/docker-mailserver

It could be a good option for those looking for a very simple and lightweight mail server. Config and adding new users is command line only so in theory some basic config options could be presented by the script. Perhaps a helper script for adding users and certain config changes. It's also very well documented and actively maintained.

What do you guys think?

**Comment by szaimen** [comment]
Yes, this would probably fit better because it is much more leightweight and could maybe also get integrated better into the VM because it is probably easier to configure via CLI. 👍

**Comment by speakradmin** [comment]
Great stuff thanks @szaimen 

Do you know if there is a CLI/API way to set these values?
![image](https://user-images.githubusercontent.com/39113729/119321762-49cc6d00-bc7d-11eb-9e70-409cfe5bddc2.png)

I like this feature because once configured, all users will have their mailbox configured automatically. It assumes nextcloud credentials = mail user credentials.

Perhaps there is a way to "copy" nextcloud user passwords when creating the mail users using the setup.sh provide by docker-mailserver?

**Comment by szaimen** [comment]
Yes, it is possible to set this via CLI. You can retrieve the current values like this in the VM:
```
sudo -i
nextcloud_occ config:app:get mail provisioning_settings
```
which currently returns: `{"active":true,"version":1,"email":"%USERID%@domain.com","imapUser":"%USERID%@domain.com","imapHost":"imap.domain.com","imapPort":993,"imapSslMode":"ssl","smtpUser":"%USERID%@domain.com","smtpHost":"smtp.domain.com","smtpPort":587,"smtpSslMode":"tls","sieveEnabled":false,"sieveUser":"%USERID%@domain.com","sieveHost":"imap.domain.com","sievePort":4190,"sieveSslMode":"tls"}`

---

And set the config string like this:
```
sudo -i
nextcloud_occ config:app:set mail provisioning_settings --value="your json config"
```
But please note that there is currently a refactoring happenning in the mail app that could require to change this in a future mail update: https://github.com/nextcloud/mail/pull/4968

**Comment by szaimen** [comment]
One additional problem: when using the provisioning tool, you must make sure that the password of the mail server account and nextcloud account match always which is probably not doable without ldap (but I actually would prefer to not introduce ldap here).

**Comment by speakradmin** [comment]
Yes agreed, LDAP for a typical self-hosted home user should not be necessary.

Hmm yes the passwords part may be tricky. Coming back to Alexey's Auto Mail Accounts app for Nextcloud, could it be modified to interact with docker-mailserver?
https://apps.nextcloud.com/apps/auto_mail_accounts
https://github.com/PanCakeConnaisseur/auto_mail_accounts/blob/master/lib/Hooks/UserHooks.php

I am willing to put in the effort to fork that project assuming it will be viable

**Comment by szaimen** [comment]
After reading the readme of the app, I guess you will run into the same problem:
https://github.com/PanCakeConnaisseur/auto_mail_accounts#auto-mail-accounts
`This is useful if the login credentials for Nextcloud and the mail server are identical and all Nextcloud users also have a mail account.`

**Comment by szaimen** [comment]
I suppose the best thing would be if there was a way to preconfigure everything except the password and username because they might be different from the mail account. But prefilling only that is not possible, I guess?

**Comment by speakradmin** [comment]
Ah my bad I misunderstood the function of that app. I thought it was creating postfix/dovecot users etc whenever a new user was added to nextcloud. It's seems like it is just replicating most of the functionality already available in the groupware settings page.

**Comment by szaimen** [comment]
What about installing rainloop and creating the domain config in `/mnt/ncdata/rainloop-storage/_data_/_default_/domains/yourmaildomain.com.ini`
```
imap_host = "yourmaildomain.com"
imap_port = 993
imap_secure = "SSL"
imap_short_login = Off
sieve_use = Off
sieve_allow_raw = Off
sieve_host = ""
sieve_port = 4190
sieve_secure = "None"
smtp_host = "posteo.de"
smtp_port = 465
smtp_secure = "SSL"
smtp_short_login = Off
smtp_auth = On
smtp_php_mail = Off
white_list = ""
```
This should make it possible to automatically set up the domain settings.
Then the only thing is to log in to you account by entering e.g. admin@yourmaildomain.com and the mail password in rainloop.

**Comment by ChristophWurst** [comment]
> And set the config string like this

:roll_eyes: please, nobody use this. you are hacking your way around the logic in place that sets those values. Don't write values into the database that aren't explicitly listed to be written manually.

**Comment by amirhmoradi** [comment]
Very useful topic thanks for the great work.

Any updates on this integration @enoch85 ? 
It would improve our team's work experience so much.

**Comment by enoch85** [comment]
> our team's

Maybe your team would be willing to pay for development?

**Comment by szaimen** [comment]
looks like this project might actually be the best option: https://github.com/docker-mailserver/docker-mailserver
(since ldap is optional there, afaics)

**Comment by enoch85** [comment]
This is pretty dead. I don't think we will implement a mail server any time soon.
