### ISSUE TITLE
Enhancement: Allow user to input custom ports for http and https during startup installation

### ISSUE THREAD

**Issue by mithusingh32** [nextcloud/vm#1941]
I spent ~5 hours trying to get activate-tls.sh to work last night, until it dawned on my let me check if my ISP blocks those ports. Shocker, my terrible provider blocks not just 80 and 443, but a whole slew of ports. 

# Suggestion
During the startup installation, the script should ask if they'd like to use custom ports for http and https. 

## What I've Tested So Far
I've tested this with just the activate-tls.sh script by manually changing all the ports with in the script and allowing user to pass in port numbers. 

## What I haven't Tested So Far
Prompting user at startup installation for ports.

**Comment by enoch85** [comment]
Hi @mithusingh32 

In your case I think the best option is to run the deSEC script. Then you can choose which port you want as TLS will work on whichever port you choose once it's setup.

`sudo bash /var/scripts/menu.sh --> Additional Apps --> deSEC`

Please let me know how it goes.

Thanks!

**Comment by mithusingh32** [comment]
Ahh okay, I will try that next time. 
Thanks!
