### ISSUE TITLE
NCBACKUP-OLD takes a huge amount of space

### ISSUE THREAD

**Issue by ishmumx** [nextcloud/vm#1942]
First of all I would like to extend many thanks to the creators of NCVM. What a phenomenal piece of software that I have been using for years! I have a little bug for you: When you mount an SMB share, it tends to download the SMB contents. Weird...or not? You tell me. Thank you!
-->
## Steps to reproduce
1. Mount an SMB share with 100GB of data.
2. Go to disk usage
3. /mnt/smbshares has the SMB mounts all downloaded, resulting in 100GB of data in the VM too.

## Expected behavior
It should just browse the SMB share, not download the entirety of the contents.

## Actual behavior
It downloads the content, resulting in a huge uptick in disk usage. My VM actually failed because the VM is inside a 128GB SSD, and the SSD filled up from the SMB shares.

#### Log file (/var/log/nextcloud/nextcloud.log)
```
https://0bin.net/paste/RNUD6XuL#SpbmFWbJVx35H4Ijln2MiXoEpodAEdbQZmuSLLoqXMb
```

**Comment by szaimen** [comment]
Hi, thanks for your feedback and report! Could you please post the output from `sudo lsblk` and `sudo df -h` here? Thanks!

**Comment by UNlDAN** [comment]
sudo lsblk:

![image](https://user-images.githubusercontent.com/37858032/117185089-4fc1e300-ad8e-11eb-8f7f-8f2af01d6eb6.png)

sudo df -h

![image](https://user-images.githubusercontent.com/37858032/117185178-67996700-ad8e-11eb-9da7-7c08f5ac0ac1.png)


Thank you!

**Comment by szaimen** [comment]
Hm... the output looks fine. What does `du -sh /mnt/ncdata/*` return?

---

> When you mount an SMB share, it tends to download the SMB contents.

I wonder how did you come to this conclusion?

> Go to disk usage
> /mnt/smbshares has the SMB mounts all downloaded, resulting in 100GB of data in the VM too.

Could you post a screenshot from this disk usage overview?

**Comment by UNlDAN** [comment]
> Hm... the output looks fine. What does `sudo du -sh /mnt/ncdata/*` return?
> 
![image](https://user-images.githubusercontent.com/37858032/117200431-58bbb000-ada0-11eb-925b-32e52a6a55a1.png)

> > When you mount an SMB share, it tends to download the SMB contents.
> 
> I wonder how did you come to this conclusion?

Perhaps I should not have been so certain. My educated guess comes from the fact that the ubuntu VG volume took up 160GB+

![image](https://user-images.githubusercontent.com/37858032/117200875-d7b0e880-ada0-11eb-9a30-accd749b3e1f.png)

> I went to the mounted SMB folders, and 
> > Go to disk usage
> > /mnt/smbshares has the SMB mounts all downloaded, resulting in 100GB of data in the VM too.
> 
> Could you post a screenshot from this disk usage overview?

Posted a df -h above, please let me know if you need something else.

Many thanks for your help. Hell, this may just be a logical volume thing that I don't know about. All I want is my ubuntu VG volume to be small so that it does not fill up my SSD please.

**Comment by szaimen** [comment]
> Perhaps I should not have been so certain. My educated guess comes from the fact that the ubuntu VG volume took up 160GB+

Thats most likely due to some files that are resting somewhere else. 
The file from your smb-share are still resting on your smb-server, as you can see in this picture.
![image](https://user-images.githubusercontent.com/42591237/117205325-c7752980-adf1-11eb-9a41-269fa0821a4b.png)
You can find out which directories fill that much space by investigating with the command that I've shared with you (`sudo du -sh /*`) is a good starting point when you unmount the smb-share again.

**Comment by UNlDAN** [comment]
> > Perhaps I should not have been so certain. My educated guess comes from the fact that the ubuntu VG volume took up 160GB+
> 
> Thats most likely due to some files that are resting somewhere else.
> The files from your smb-share are still resting on your smb-server, as you can see in this picture.
> ![image](https://user-images.githubusercontent.com/42591237/117205325-c7752980-adf1-11eb-9a41-269fa0821a4b.png)
> You can find out which directories fill that much space by investigating with the command that I've shared with you (`sudo du -sh /*`) is a good starting point when you unmount the smb-share again.

Thank you. I took a look and my educated guess may have been right. 

1. Unmounted all SMB shares and rebooted.
2. Ran sudo du -sh /*

 /mnt had 100+GB used.  It is indeed downloading the SMB shares, it seems.

**Comment by UNlDAN** [comment]
I am scared to delete the files in /mnt/smbshares/1 as I don't know if it will delete all my files after I add an SMB mount.

**Comment by szaimen** [comment]
What seems to actually be the problem here is the /var directory as you can see. It has the 151GB you are looking for. But also /mnt seems to have stored many files.
What does `sudo du -sh /var/*` and `sudo du -sh /mnt/*` return?

**Comment by UNlDAN** [comment]
> What seems to actually be the problem here is the /var directory as you can see. It has the 151GB you are looking for. But also /mnt seems to have stored many files.
> What does `sudo du -sh /var/*` and `sudo du -sh /mnt/*` return?

Here you are, both commands:

![image](https://user-images.githubusercontent.com/37858032/117343188-e2c74f80-ae58-11eb-930b-c651054099d6.png)


I am thinking that when it backs up Nextcloud, it also backs up SMB shares for some reason. I may be wrong though. The NCBACKUP-OLD folder example:

![image](https://user-images.githubusercontent.com/37858032/117343323-05f1ff00-ae59-11eb-9bee-93bb135dbcc8.png)

Thank you again!

**Comment by szaimen** [comment]
Just a few more commands: 
`sudo du -sh /var/NCBACKUP-OLD/*` 
`sudo du -sh /var/lib/*`
`sudo du -sh /mnt/smbshares/*`

**Comment by UNlDAN** [comment]
> Just a few more commands for investigation:
> `sudo du -sh /var/NCBACKUP-OLD/*`
> `sudo du -sh /var/lib/*`
> `sudo du -sh /mnt/smbshares/*`

Here you are sir:

![image](https://user-images.githubusercontent.com/37858032/117353677-45264d00-ae65-11eb-8d94-558ff8294b06.png)

![image](https://user-images.githubusercontent.com/37858032/117353707-51120f00-ae65-11eb-8320-9cc952843176.png)

![image](https://user-images.githubusercontent.com/37858032/117353729-596a4a00-ae65-11eb-8d4b-9e2d655114f4.png)

Thank you!

**Comment by UNlDAN** [comment]
> Thanks! What does `sudo mountpoint /mnt/smbshares/1` and `sudo grep /mnt/smbshares/1 /etc/fstab` return?

Here you are boss: 
![image](https://user-images.githubusercontent.com/37858032/117357122-65580b00-ae69-11eb-8c36-8095fd2cd7cd.png)

Thank you!

**Comment by szaimen** [comment]
Thanks, that's everything I've needed!
So a few things:
1. nothing of your smb-shares is actually stored on your root partition. 
2. It seems like your database has grown to around 20-40GB. You should investigate yourself if you can do something against it
3. you can delete the `/var/NCBACKUP-OLD` by executing `sudo rm -r /var/NCBACKUP-OLD` which will clear up around 104GB on your root disk
4. @enoch85 we should discuss if we should actually store more than one old backup archive since this can take quite a lot of space as we can see here.

**Comment by UNlDAN** [comment]
> Thanks, that's everything I've needed!
> So a few things:
> 
> 1. nothing of your smb-shares is actually stored on your root partition.
> 2. It seems like your database has grown to around 20-40GB. You should investigate yourself if you can do something against it
> 3. you can delete the `/var/NCBACKUP-OLD` by executing `sudo rm -r /var/NCBACKUP-OLD` which will clear up around 104GB on your root disk
> 4. @enoch85 we should discuss if we should actually store more than one old backup archive since this can take quite a lot of space as we can see here.

1. Awesome, thank you!
2. Would you happen to know what this DB is and where it populates from? My NC is literally just NC and then 1 link to the SMB nextcloud share. Nothing is actually stored in the VM,
3. Done! Thanks

I appreciate your help!

**Comment by szaimen** [comment]
> 1. Awesome, thank you!

You are welcome!

> 2. Would you happen to know what this DB is and where it populates from? My NC is literally just NC and then 1 link to the SMB nextcloud share. Nothing is actually stored in the VM,

I would suggest to open a new support thread in the help forum: https://help.nextcloud.com to get some help for this. I suppose it has to do with the usage of the external storage app in Nextcloud itself.

> 3. Done! Thanks

Great, no problem!

**Comment by szaimen** [comment]
@ ishmumx Sry, but I am going to reopen this issue since I still need an answer from @enoch85 for this:

> 4. @enoch85 we should discuss if we should actually store more than one old backup archive since this can take quite a lot of space as we can see here.

**Comment by ishmumx** [comment]
> @ishmumx Sry, but I am going to reopen this issue since I still need an answer from @enoch85 for this:
> 
> > 1. @enoch85 we should discuss if we should actually store more than one old backup archive since this can take quite a lot of space as we can see here.

Thank you boss!

**Comment by enoch85** [comment]
Hey boss! (@szaimen) :D

I've actually been thinking about removing everything older than X days from the OLD backups, but maybe it's better to tar them or something? I mean, we don't know if some user wants to keep versions, and who are we to decide?

**Comment by szaimen** [comment]
I'd say that if you really care about backups and different versions, you should either use the daily-backup-script or implement your own backups on the host (if you run the VM in a hypervisor).
For me this backup part in the update script is more like a restore point for Nextcloud that you can restore your Nextcloud to if the update fails. So one backup and one additional old backup should be enough, imo.

**Comment by enoch85** [comment]
@ishmumx Please run the update.sh script again and the error will be gone.

Please confirm.

**Comment by ishmumx** [comment]
> @ishmumx Please run the update.sh script again and the error will be gone.
> 
> Please confirm.

Just ran bash update.sh and it went through fine. Still however it shows the ubuntu VG volume at around 57GB which is concerning. 

Thank you!

![image](https://user-images.githubusercontent.com/37858032/118016418-35e24c00-b30a-11eb-8c02-ae1567cd2060.png)

**Comment by enoch85** [comment]
It only deletes stuff from last year, but OK, might be improved. At least we have the logic in place now.

**Comment by szaimen** [comment]
> ubuntu VG volume at around 57GB

Thats mostly due to your database which we found out above...
That's also why I suggested to open a new thread on https://help.nextcloud.com to get some tips how to fight that.

**Comment by ishmumx** [comment]
> > ubuntu VG volume at around 57GB
> 
> Thats mostly due to your database which we found out above...
> That's also why I suggested to open a new thread on https://help.nextcloud.com to get some tips how to fight that.

Sorry, totally skipped that. Life has been busy as hell lately Lol. Thank you G!

**Comment by szaimen** [comment]
This new app may be useful to shrink the database https://github.com/icewind1991/root_cache_cleaner

**Comment by esaumell** [comment]
Hey, just wanted to point out that today I found this:

```
root@cloud:/mnt# du -hs NCBACKUP*
525M	NCBACKUP
6.6G	NCBACKUP-OLD
root@cloud:/mnt# du -hs NCBACKUP-OLD/*
1.1G	NCBACKUP-OLD/2022-01-29-180212
1.1G	NCBACKUP-OLD/2022-02-19-180357
1.1G	NCBACKUP-OLD/2022-02-28-010906
1.2G	NCBACKUP-OLD/2022-03-26-180243
1.1G	NCBACKUP-OLD/2022-04-23-180129
1.1G	NCBACKUP-OLD/2022-05-15-183703
```
IIRC there is no mention about this backups on NC documentation, at least I didn't find anything on May 2021 when I manually set up the backup of my instance. As far as I can understand it seems safe to `rm -rf /mnt/NCBACKUP*` right?

Otherwise, can you point me to the script that generate that backups? Thanks.

**Comment by ishmumx** [comment]
> Hey, just wanted to point out that today I found this:
> 
> ```
> root@cloud:/mnt# du -hs NCBACKUP*
> 525M	NCBACKUP
> 6.6G	NCBACKUP-OLD
> root@cloud:/mnt# du -hs NCBACKUP-OLD/*
> 1.1G	NCBACKUP-OLD/2022-01-29-180212
> 1.1G	NCBACKUP-OLD/2022-02-19-180357
> 1.1G	NCBACKUP-OLD/2022-02-28-010906
> 1.2G	NCBACKUP-OLD/2022-03-26-180243
> 1.1G	NCBACKUP-OLD/2022-04-23-180129
> 1.1G	NCBACKUP-OLD/2022-05-15-183703
> ```
> 
> IIRC there is no mention about this backups on NC documentation, at least I didn't find anything on May 2021 when I manually set up the backup of my instance. As far as I can understand it seems safe to `rm -rf /mnt/NCBACKUP*` right?
> 
> Otherwise, can you point me to the script that generate that backups? Thanks.

Yes surrrr go ahead delete it. I did so for my setup and no issues.
