### ISSUE TITLE
Nextcloud isn‘t reachable from Smartphone browser 

### ISSUE THREAD

**Issue by herrschlupp** [nextcloud/vm#1945]
Hello all,

I have the following problem with my Nextcloud and hope someone of you has another idea, because I am at the end with my ideas.

The NC is accessible from the Internet via subdomain (nc.domain.com) the domain translation is implemented by a Nginx proxy manager. Ports 80 and 443 are forwarded.
This works internally as well as externally.

However, the NC is only not reachable from the smartphone. The browser shows "Website is not reachable".
At first I thought that it might be due to IP v6 problem. But I can exclude this, because the NC is although from the WLAN, with internal IP, from the smartphone is not accessible. In this case the Smartphone has an ip v4 adress and nc.domain.com isn‘t reachable. 
This applies both, WLAN, via VPN from external or from the mobile network.

It is strange that a direct webdav (used for enpass) connection via nc.domain.com also works from the smartphone.
However, the internal IP address 192.168.x.x of the NC is also accessible from the smartphone.

What I don't understand now is that the NC is internally as well as externally accessible from any PC and via any browser, without restriction.

And finaly an other nc installation works without any issues. That means that the problem clould not come from the reverse proxy. 

Do you have another idea? I am loss.

Thanks and greetings

Ubuntu 20.04 (as VM, VM-Ware)
NC Version 21.0.01
Apache 2
PHP 7.4
Nginx Proxy Manager

**Comment by szaimen** [comment]
Thank you for taking the time to report a problem 👍

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
