### ISSUE TITLE
Quick fix for NextcloudVM with VMWare

### ISSUE THREAD

**Issue by hobbsecky** [nextcloud/vm#1947]
Hello Daniel it's me again from Chattanooga, TN, USA. Quick problem and solution for you.

After inspecting the logs @ /var/log/syslog I found:

multipathd[651]: sdb: add missing path
multipathd[651]: sdb: failed to get udev uid: Invalid argument
multipathd[651]: sdb: failed to get sysfs uid: Invalid argument
multipathd[651]: sdb: failed to get sgio uid: No such file or directory
multipathd[651]: sdb: add missing path
multipathd[651]: sdb: failed to get udev uid: Invalid argument
multipathd[651]: sdb: failed to get sysfs uid: Invalid argument
multipathd[651]: sdb: failed to get sgio uid: No such file or directory

I fixed it by editing "40GB_Nextcloud-VM_www.hanssonit.se.vmx" with Notepad++ and added the following:

`disk.EnableUUID = "TRUE"`

One other note: 
In VMWare config the NextcloudVM is currently set as:
Number of Processors = 2
Number of Cores per Processor = 1

This is not optimal.
Number of Processors = Physical processors which for most home users is the same as Physical sockets. This should be 1 for the majority of users.
Number of Cores per Processor = Physical Cores X Number of Threads (if multithread capable)

IE...Ryzen 2700X is a single CPU, 8 cores, 2 threads per core so for maximum performance in the VM you would set it like this:
Number of Processors = 1
Number of Cores per Processor = 16

Ideally out of the box for compatibility the NextcloudVM should run fine with:
Number of Processors = 1
Number of Cores per Processor = 2

One other note of interest is that Windows 10 Home Edition only supports 1 CPU for virtualization. Windows 10 Pro supports 2 CPU's. This is also important because I would bet most NextcloudVM users with the 40GB version are using Windows 10 Home.

Thanks for your work!

**Comment by enoch85** [comment]
Thanks for your suggestions, I actually just released some new disk images for the last release. Was looking for those settings but didn't find them. Now when you mention it, I feel kind of stupid not looking in the actual file :blush: :see_no_evil: I should know better.

Will definitely change that upon creation of the next base image. :+1:

**Comment by hobbsecky** [comment]
I actually use a Ryzen 2700X on my NextcloudVM and I use the 1 CPU 16 Core setup. It doesn't bog down the host at all because the VM still only uses what it needs.  

RAM allocation is a different subject. I normally leave it at 4 GB with the virtual memory 4GB as well. I have yet to see the RAM/VRAM over 80 percent peak and I have 32 GB available if needed. I tested 8GB and with the limited users I have at the moment there was really no need so I went back to 4GB.

My server is in my house on EPB's fiber network here in Chattanooga, TN. It's the fastest residential on Earth. We get 1 GB fiber U/D all the way to my router. It's less than 70 dollars a month. The other option is 10GB U/D and that is $299 per month so it's just a login away if I ever had a lot of clients. It's a community owned utility and they've had the "fastest internet on Earth" bragging right for quite a while. I'll give them credit because to this point it really has been the best ISP by far I've experienced.

Needless to say my NextcloudVM is SCREAMING FAST!

Thanks for all the work you do with this. Greatly appreciated. Any little contribs I can make are me saying thanks.

Thanks!

**Comment by kimberk** [comment]
All ubuntu and many linux distros same error messages. disk.EnableUUID solved this error but If u can move-copy the vm, maybe boot fail.

**Comment by hatclub** [comment]
For other's reference if you want to stop multipathd being irritating without fiddling with enabling UUID in VMW, you can also tell multipath to ignore vmw virtual disks:

in `/etc/multipath.conf`, add:

```
blacklist {
    device {
        vendor "VMware"
        product "Virtual disk"
    }
}
```

Then restart multipath with a `systemctl restart multipathd`


On the cpus/cores thing, I'm pretty sure it is irrelevant to vmware if you have more vCPU than pCPU, as long as:

- (vCPU * vCores) !> (pCPU * pCores), and;
- (vCPU * vCores) % (pCPU) == 0

then recent vmw (esxi/vsphere > v6.5, anyway) should work fine, as it will try to produce the optimal vNUMA layout (unless you have fiddled with advanced settings - including 'cores per socket' - which can, if you're not careful make things suboptimal on systems with multiple pCPUs / NUMA nodes).

https://frankdenneman.nl/2016/12/12/decoupling-cores-per-socket-virtual-numa-topology-vsphere-6-5/ illustrates a 10 vCPU x 1 Core-per-vCPU VM getting evaluated down to a single vNUMA in 6.5. In short, I actually wouldn't change the default VM vCPU config - it should not be slower or less compatible on single pCPU systems afaik.


(I am not sure I follow the remarks about windows 10 home / pro at all - @hobbsecky are you running your VM in VMW Workstation or Player or something? I think most users, and certainly heavier users, would be running it on ESXi / vSphere)

**Comment by hobbsecky** [comment]
I'm running NextcloudVM on a Windows 10 Pro host with VMWare Workstation. It's just family and friends using it at the moment.

**Comment by enoch85** [comment]
From this (23.0.2) release onward, we added `EnableUUID`.
