### ISSUE TITLE
Improve boot to working login of NextcloudVM

### ISSUE THREAD

**Issue by hobbsecky** [nextcloud/vm#1948]
`GRUB_CMDLINE_LINUX_DEFAULT="maybe-ubiquity"`

Change it to:

`GRUB_CMDLINE_LINUX_DEFAULT=""`

The login prompt sometimes won't accept input for another 10 or 15 seconds when "maybe-ubiquity" is still in GRUB.

**Comment by enoch85** [comment]
`sed -i "s|GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT=|g" /etc/default/grub`

**Comment by szaimen** [comment]
```
if grep -q 'GRUB_CMDLINE_LINUX_DEFAULT="maybe-ubiquity"' /etc/default/grub
then
...
fi
```
