### ISSUE TITLE
Make scripts work in WSL 2

### ISSUE THREAD

**Issue by JonCStout** [nextcloud/vm#1949]
## Steps to reproduce
1.  Install Windows Subsystem for Linux (and Virtual Machine Platform if you want WSL 2, which is much faster, though you have to manually enable v2 to take advantage)
2.  Install Ubuntu 20.04 LTS or plain Ubuntu;  launch and create login, apt update, apt upgrade
3.  wget and then run the "raw" version of the install script from https://github.com/nextcloud/vm/raw/master/nextcloud_install_production.sh
4.  My answer to the questions are yes or no for LVM snapshots (doesn't seem to matter), yes to create user, DNS doesn't seem to matter, and no to the data disk because I don't have a secondary one to format in the WSL VM.

## Expected behavior
Finish install

## Actual behavior
Errors shortly after installing the Apache server, and told me to report it, so here I am.

## Server configuration

**Nextcloud server version:**  n/a

**Server OS**  Ubuntu 20.04

**PHP Version**  n/a

**How did you install the VM?**  install script, as described

## Network
**Do you use DHCP?**  Yes, multiple layers of NAT, including whatever WSL uses

**Is port 80 and/or 443 open?**  Probably available ports, in that fresh install

#### Log file (/var/log/nextcloud/nextcloud.log)
```
doesn't exist
```

#### Installation log (command output)
```
Considering dependency mime for ssl:
Module mime already enabled
Considering dependency socache_shmcb for ssl:
Enabling module socache_shmcb.
Enabling module ssl.
See /usr/share/doc/apache2/README.Debian.gz on how to configure SSL and create self-signed certificates.
To activate the new configuration, you need to run:
  service apache2 restart
Module mpm_prefork already disabled
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart apache2.service failed
sudo: php: command not found
```

For what it's worth, this command appears to work afterward:
```
:/home/ncadmin# service apache2 restart
 * Restarting Apache httpd web server apache2
```

Also, PHP didn't appear to have been installed yet by the script, so that last line in the console output is odd.

It may also be worth mentioning that snap isn't usable in Ubuntu 20.04 LTS for WSL, though it might be in plain Ubuntu (non-LTS?)

And the script doesn't work in Debian 10 at all, just says it only works in Ubuntu 20.04, which is a shame.

#### Screenshots
Can be created if really needed

**Comment by szaimen** [comment]
Hi, I've investigated a bit and it seems like systemd isn't installed by default in WSL. To make our install script work, you need to make sure to install systemd first before running the script. I've found those options for you: https://superuser.com/a/1601950

**Comment by szaimen** [comment]
But obviously this isn't the recommended way to install the VM. Much better would be to use Hyper-V or VMPlayer to run the Nextcloud VM.

**Comment by JonCStout** [comment]
For what it's worth, I found a YouTube tutorial on how to do it more manually, and it worked!  It is for an older version of Ubuntu, but it still worked on 20.04, and it didn't require me to jump through the systemd workarounds from that superuser article:  https://www.youtube.com/watch?v=vAWe8LjSUNk

As for a "full" VM, that uses way more system resources than WSL, particularly RAM.  It can also be tricky to get it to share access to alternate storage locations on the host system, whereas WSL can just immediately go to /mnt/d for example.  I think that tutorial ended up being faster to set up than installing Ubuntu in a VM, too.  It's only an <9 minute video, and the fast forwarded parts where installs happened only took a couple minutes extra for me (thanks to WSL 2).

This all suggests to me that a scripted solution for WSL should be possible that maybe doesn't depend on systemd, though I understand if it's a lot of work to make that happen.

**Comment by szaimen** [comment]
> As for a "full" VM, that uses more system resources than WSL, particularly RAM

Thats correct.

> I think that tutorial ended up being faster to set up than installing Ubuntu in a VM, too.

Maybe concerning the installation of Nextcloud itself but definitely not if you could use some features that the VM provides. You could also have used one of the pre-built VMs which is a very fast way to get Nextcloud up and running while maintaining all features that the VM provides: https://www.hanssonit.se/nextcloud-vm/

> It can also be tricky to get it to share access to alternate storage locations on the host system.

Not necessarily since you can easily mount smb-shares with this built-in script: https://github.com/nextcloud/vm/blob/master/apps/smbmount.sh

> This all suggests to me that a scripted solution for WSL should be possible that maybe doesn't depend on systemd

Maybe it is possible but it is defnitely nothing we are willing to do.

**Comment by hobbsecky** [comment]
For me NextcloudVM is WAY faster when you start adding subdomains, CertBot for HTTPS, high performance back end for Talk, Office, Webmin, etc and VMWare is much improved both performance and stability wise and their Player is free.

Like most admins there are a lot of things I can do quickly with CLI but Webmin is great when I need to move things around and it has low overhead.

VMWare workstation is nice if you want automated snapshots to save backup space and CPU overhead but if it's a small cloud you can just copy your whole VM to another folder or drive once a day and all is good.

**Comment by hobbsecky** [comment]
I made a quick video of my NextcloudVM in real time on VMware. The link is to my self hosted website. Enjoy!

https://bit.ly/33wHZjX

**Comment by JonCStout** [comment]
I didn't know there was an SMB mount script thing, which shouldn't surprise anybody since I'm installing for the first time.  Thanks for that info.

As for WSL, I've played with it enough in node.js development vs native Windows node.js vs VM Linux node.js that I've come to actually like WSL the most out of the three.  And WSL is semi-new, yes, but already surprisingly good for cli stuff and great for Visual Studio Code (Remote-WSL) development.  (Try deleting a node_modules folder with 30,000 files in it and be amazed at how Windows takes minutes and WSL 2 takes a second or two - it's basically *really close to as fast* as native Linux, now.)  They have native X server support coming, available in preview release right now, and maybe better systemd support and/or snapd will come with that?  The main reason I went this route is I didn't want to pay for a pre-made VM.  I really didn't need enterprise level support when I'm just tinkering.  I didn't originally see a free route to getting one, so thanks for that info, too.

That video was pretty awesome, with lots more interesting things to explore than I was expecting.  Thanks for that, too!

But having said all that, I found yet another option for Windows without any VM at all:
http://www.ampps.com/apps/files/Nextcloud
It *could* be as simple as installing ampps, then installing NextCloud inside ampps, and done.  I probably won't have the time to tinker with this for a few days now, though.

I may give ampps a try and see which I like better.  Maybe that should be mentioned in the install guide as an option for Windows.  I imagine I'm not the only person that has been wanting first class support for Windows - easy, free, more readily available to the ~90% of the world that isn't using Linux or Mac...  It's like, if a big project like LibreOffice can do cross-platform open source and not go bankrupt, why not this one?  (Maybe that's not a fair comparison.)

I understand some of the reasoning for isolating in a VM, but that mainly doesn't apply when I don't intend to make my install Internet accessible.  I mean, the whole point to me is to break away from public clouds like Google and MS.  So if Internet exposure isn't such an issue, then OS isolation is moot, for me.  On the other hand, I'd rather not permanently decrease my available RAM by however many gigs the VM needs to run, when I have other things I want to do (mostly Windows apps/services) with that same box.  I may still go the VM route if I don't like the ampps or WSL routes.  We'll see.  But I guess this is veering toward philosophical arguments that only vaguely address the "why" of the original issue.

So... if someone other than a core developer (the "we" that is definitely not willing, presumably) were to submit a pull request for a script that would make it better for Windows, would that be accepted?


P.S.  node.js has a pretty slick scripted install that works in multiple distribution flavors of WSL, in case anybody wants to see how another project does it:  https://github.com/nodesource/distributions/blob/master/README.md#debinstall
I think they use .deb package management, which I think I saw somewhere NextCloud developers were trying to avoid.  It does make it easier to keep *everything* (in the Linux environment) updated with a single "apt update && apt upgrade", though.

P.P.S.  I don't need graphical Linux anything at the moment.  I tried going native Linux development for a while, but kept running into so many headaches with laptop trackpads, wifi, Spotify stability, etc., that it just wasn't worth the hassle in the end.  If you notice at the end of that video I shared before, he's logged into his NextCloud instance through a web interface, using a browser running in Windows (not WSL) - no GUI Linux X server support required for a web GUI experience.

**Comment by szaimen** [comment]
> So... if someone other than a core developer were to submit a pull request for a script that would make it better for Windows, would that be accepted?

Pinging @enoch85 for this.

**Comment by enoch85** [comment]
@JonCStout it's open source, you're free to contribute. :+1:

**Comment by szaimen** [comment]
> That won't fix tag and "definitely unwilling" talk were rather off-puting.

I am sorry. It wasn't my intention to make you feel bad. I just saw the big effort to support a platform that is currently limited in many points in comparison to "normal" VMs. Additionally, this enhancement isn't really done by adjusting only one script: many scripts need to be adjusted to make them work in WSL.

**Comment by hobbsecky** [comment]
@JonCStout 
I'm going to go out on a limb here and speculate that you have missed one key problem with WSL 2.
A lack of persistent services.

How are you going to run a cloud server without it?

WSL 2 won't let you run Nextcloud in the background.

On that note you can close the thread.

**Comment by hobbsecky** [comment]
How much RAM do you have? 3GB's? Come on man! Hahahaha!

Seriously I run my Nextcloud instance with 4GB and if you have 16GB or more available it's not going to impact your host.

For me stability, compatibility and less headache give the win to VMWare. WSL 2 is still beta. I'd rather focus my energy on improving Nextcloud then trying to get WSL 2 to work.

My gut tells me WSL 2 is Microsoft testing the waters and looking at a Linux core for future OS's. Long term it would probably save them a ton on payroll and we know the bigwigs are greedy bastards right?

**Comment by hobbsecky** [comment]
Nefarious indeed!

I'm a proponent of more facts and less BS as well as healthy debates.

Since I chose the lazy option of using VMWare 16 and Nextcloud VM I reap the reward of also being able to reconfigure the whole thing in about 30 seconds.

I set it to 2GB's. Live and learn. I was honestly very surprised to find that with just me using my Nextcloud there was NO difference in performance that I could feel. I also should note that I am running it as heavy as it can be ran at the moment because I have the high performance backends up....Talk, OnlyOffice, Push, Bitwarden. You may not use all of those features which means you'll have a smaller footprint.

2GB pics at ya' >>>>>>
![Desktop Screenshot 2021 05 10 - 17 39 37 95](https://user-images.githubusercontent.com/81445000/117729208-86499480-b1b8-11eb-804e-36d605c56598.png)
![Desktop Screenshot 2021 05 10 - 17 40 23 13](https://user-images.githubusercontent.com/81445000/117729210-86e22b00-b1b8-11eb-9d16-de3b52a6566f.png)

Firefox is the RAM hog.

**Comment by hobbsecky** [comment]
I have minimal exposure to WSL 2 because I became aware of the limited networking capabilities in comparison to VMware and I punted.

That was last year.

This conversation has been beneficial to me because I had to research the current state of WSL 2. They have made some progress but it's still lacking on the networking side.

With VMware setting up a bridge, NAT whatever is just too easy and it works.

**Comment by JonCStout** [comment]
This post is just an update of things I've figured out lately, for those who may be interested.

First issue:  **make it persistent**, and maybe fix the lack of systemd in WSL, short version:  install systemd-genie and its prerequisites of transdebian and dotnet-runtime-5.0 (not SDK or ASPNET).  Read their whole document to fix the timeout issues...  (I had to learn more about how systemd worked than I knew before.)

genie:  https://github.com/arkane-systems/genie
transdebian:  https://arkane-systems.github.io/wsl-transdebian/
dotnet:  https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

And to make the system run after Windows reboots, just launch WSL and genie with something like this:  wsl -d Ubuntu -u ncadmin -e genie -s

That command starts your Linux instance with systemd-genie running and leaves you in a command shell.  Once it finishes loading, you can even close your terminal and your WSL instance stays running in the background.  The -d selects your distribution, which you can maybe omit if you only have one, or it's the default.  The -u selects your login username, which you can maybe omit if that's your default for the instance, too.  The -e executes a command, namely genie, and genie's -s says to start a shell.  That -s can probably be changed to something else to not start a shell if you want, but I haven't experimented with it.  At any rate, that one line command can be issued from a .cmd batch file in your Startup folder, or from a Task Scheduler event after logon (or perhaps even before logon without a terminal window), or what I did for now is set up the official Microsoft Terminal to auto-start, default to my Ubuntu instance, and add genie to how that default instance starts.  When my computer reboots, WSL with genie successfully comes back automatically.  And genie (systemd) starts services like apache and mysql, thus making NextCloud run.  Oh, I have auto-logon for my main Windows account, and a script that locks the screen 30 seconds later, so other unrelated user processes that aren't true services can also run.  But that's just me.


Second issue:  **make it accessible from other computers**.  For that, I learned about netplan for Ubuntu to set a static IP within my home network's subnet, which wasn't so hard.  But then I still needed to make the services (ports) accessible, which involved  installing another Windows feature, Hyper-V, running its Manager AS ADMIN, and changing the WSL network adapter to External network (or Internal might work too, but definitely not Private, unless there's some way to mess with port forwarding, but I didn't want to bother with that).  But then I found out that apt update wasn't working.  So, I then had to follow some instructions to get WSL to stop clobbering /etc/resolv.conf with a wrong IP.  Huzzah, my WSL instance (including NextCloud) is now accessible from other computers from a fixed IP address, with DNS working inside it.

Hyper-V switch manager:  https://github.com/microsoft/WSL/issues/4210#issuecomment-822779489
Static IP:  https://www.howtoforge.com/linux-basics-set-a-static-ip-on-ubuntu
Fix DNS:  https://github.com/microsoft/WSL/issues/5420


Having figured all that out was an interesting journey for me, but frankly, I don't recommend it for most people.  The security issue is still a concern, but I'm behind a VPN, and never going to make it directly Internet accessible, so I think I'm okay there.  The memory savings weren't as much as I'd hoped.  WSL is taking over a gig to run this bare instance of NextCloud that I haven't even set up to do anything interesting with yet.  And the NextCloud admin/overview page is showing 13 things I should fix, 4 of which are critical, meaning I still have a lot of work ahead of me to set it up "well".  Most people would almost certainly be better off using a pre-made VM, for now.

However, I still see a path to where one day, much of that setup could be automated.  For example, one way of telling if someone is running in WSL, and thus may need genie set up as a prerequisite, is to simply type uname -a.  The kernel string will have Microsoft in the name.  And the kernel version may give a clue whether WSL 1 or 2 is running.  This might be an issue if someone compiles a custom kernel that excludes that string, though, so maybe there's a better way to detect WSL.

It may also be worth noting that I have Debian set up in WSL, too.  I was accidentally running in it without realizing it for like half a day and wondering where my NextCloud stuff disappeared to after getting genie working there.  So silly.  But it did help me realize Debian is probably just as supportable as WSL, with probably just minor tweaks.  For example, the Youtube instructions that worked in Ubuntu didn't work so well in Debian, probably because package names were different.  I think in particular, it choked on not being able to find mysql-server.  I think mysql-common is what might be needed on Debian, instead.


That YouTube video's comments (from an earlier post here) had several people asking about how to deal with these issues, and nobody there seemed to have come up with these solutions.  So, I'm going to cross-reference this post there to hopefully help others a little.  But like I said, most people are probably better off not even doing the WSL route for now.

**Comment by JonCStout** [comment]
One interesting question I have is:  if genie was set up in advance, would the install script then work unmodified?  I'd have to figure out how to have a second Ubuntu instance, or to maybe backup my current one, wipe it out, and start over, to answer that.  Maybe someday I'll try that, but probably not soon.

**Comment by enoch85** [comment]
From my own testing WSL really sucks. :) It's not reliable at all, even in Windows 11.

I don't think this is a way forward - trusting Windows in making great stuff in Linux. Anyone else with objections or should we close this issue?

**Comment by JonCStout** [comment]
I'd be interested in hearing more details of that testing.  What Linux OS did you use?  What setup method for NextCloud did you use?  Did you use genie, and get the service port reliably accessible?  What else did you have running on the machine (inside and out of WSL) that might have interferred  especially antivirus or firewall?  What exactly seemed unreliable, and can it really be a blanket blame of WSL 2 when there's so many factors to consider?

Despite my curiosity, I have to admit I gave up on it, mostly because I couldn't justify the resource drain when I had 4 other higher priority things running.  NextCloud would have to be rewritten to work natively on Windows, or not rely on heavy web services (Node.js perhaps?) for me to likely consider it again, or I'd have to invest in beefier hardware, which isn't in the cards soon.  I realize rewriting is not very likely, though.

**Comment by enoch85** [comment]
@JonCStout There's not much to debate really. WSL isn't a "hypervisor" - it's just a way of getting Linux to Windows, and in a hackish way if you ask me.

The reason for me stating "it sucks", is that it crashed hard (not able to even start it (unknown error - you gotta love those error messages) on me several times when using it as a secondary system to Windows - just as intended. All the times I've been equally mad over the fact that I lost several weeks of work (I use backups, but still annoying).

I don't think it's a good idea to use for Nextcloud due to it's instability, and also the fact that it's not intended to use in the way as this issue wants. Sure you could probably get it working, but I wouldn't consider it stable, and that's a key value for running Nextcloud. So, WSL? No thanks.

**Comment by JonCStout** [comment]
I don't know why you'd say it isn't a hypervisor.  WSL runs on Hyper-V, Microsoft"s VM implementation.  Indeed, if I want to run VirtualBox instead, I have to disable WSL 2 and maybe use a BCD edit to disable Hyper-V, as I can't get VirtualBox to run reliably with them on.

**Comment by JonCStout** [comment]
The "hack" they use to make it work comes mainly from a custom Linux kernel that I believe has drivers and stuff for interacting with their VM.  I see this as no different than what makes Qemu and VirtualBox and other VMs work as guest OSs.

**Comment by enoch85** [comment]
> I don't know why you'd say it isn't a hypervisor. WSL runs on Hyper-V, Microsoft"s VM implementation

Well, running the same thing in Hyper-V doesn't make it suddenly crash, so there's a big difference - believe it or not.



> It took me forever to figure out the conflict and get my VirtualBox machines to run again

Make it easy on yourself and run VMware. They have built in support to run next to Hyper-V. Just an advice.

>  Windows 11 is still somewhat new, and that could also be a stability factor. 

Sure, but WSL even worse in Windows 10. :) I've been using it in my daily work since it was released more or less. Windows gives me a hard time in general actually (work policy).

**Comment by enoch85** [comment]
Both me and @szaimen thinks this is a bad idea, and since no one else here seems to be willing to send a PR to make it happen - we'll close this.
