### ISSUE TITLE
Add spinner_loading each time lib.sh is imported

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#195]
It takes a while to import all the variables and functions, and it would be nice to have a loading spinner when that happens.

@morph027 as we agreed on.

**Comment by morph027** [comment]
In progress...right now we can't use it like we though. Invoking the source command (```. ...sh```) appended with ```$ spinner_loading``` sends the sourcing into a subshell, where all vars, functions and so on gets lost in that subshell...

Will do some brain crunching

**Comment by enoch85** [comment]
I cleaned up the lib somewhat and it loads pretty fast for me now at least. About 2-3 seconds, but still, I'm thinking of all those users with bad internet connection that will have to wait for like 10 seconds before it loads. Would be great if you came up with an idea.

**Comment by Ark74** [comment]
Maybe pv could work?

**Comment by enoch85** [comment]
@Ark74 Pv?

**Comment by morph027** [comment]
Pipeviewer ...but this would be another dependency which is not installed by default.

https://www.cyberciti.biz/open-source/command-line-hacks/pv-command-examples/

**Comment by enoch85** [comment]
@morph027 If it makes you life easier, then just add it in the install. :) Will release it in 12 in that case.

**Comment by enoch85** [comment]
```
root@cloud:~# bash -x /var/scripts/nextcloud_update.sh 
+ true
+ NC_UPDATE=1
+ . /dev/fd/63
++ curl -sL https://raw.githubusercontent.com/nextcloud/vm/master/lib.sh
++ pv
12,9KiB 0:00:01 [ 6,8KiB/s] [   <=>                                                                                                                                                                               ]
++ true
++ SCRIPTS=/var/scripts
++ NCPATH=/var/www/nextcloud
++ HTML=/var/www
++ NCDATA=/var/ncdata
++ SNAPDIR=/var/snap/spreedme
++ GPGDIR=/tmp/gpg
++ BACKUP=/var/NCBACKUP
+++ lsb_release -sd
+++ cut -d ' ' -f 2
++ DISTRO=16.04.2
+++ grep -ic Ubuntu /etc/issue.net
++ OS=1
++ '[' '!' -z '' ']'
+++ cut -d : -f 1
+++ grep UP
+++ awk '{print $2,$9}'
+++ ip -o link show
++ IFACE2='ens160
docker0'
```

As you can see here it only runs `pv` on the download, and *then* run the variables. I want to have a progress bar for loading the variables.

**Comment by enoch85** [comment]
Ping

**Comment by morph027** [comment]
Huh, sorry....to much workload.

Right now, i can just think of another wrapper script, which includes a spinner and then downloads the real lib.sh.

**Comment by enoch85** [comment]
@morph027 Any update here? 

All and all it's quite good since the improvements, but still, would be nice if this could be done.

**Comment by enoch85** [comment]
Closing this as it's not needed. It's pretty fast anyway, and we don't run all the functions all the time as we specify for certain scripts to include extra vars and functions.
