### ISSUE TITLE
Product's (GEN 2) built-in SMB function fails in NextCloud (Windows 10 Host)

### ISSUE THREAD

**Issue by RJ-Make** [nextcloud/vm#1967]
## Steps to reproduce
1. Creation of 1 SMB mount using the Product's built-in SMB function. (Using the latest HanssonIT Hyper-V GEN 2 Product on a Windows 10 Host ). From the products SMB utility the mount is created without issue.

2. I have run the product (Fresh Start) no less then 10 times (do to other issues). Each time I cannot create the mounts in the new Nextcloud instance. 

## Expected behavior
1) Should be able to easily create the shares In NextCloud using the "External Storage" module using Local.  

## Actual behavior
1) You cannot create the shares in NextCloud using Local. 

<img width="1026" alt="2021-05-18_10-32-03" src="https://user-images.githubusercontent.com/8496835/118725063-6be96980-b7fd-11eb-9141-60036d2aea42.png">

2) It may also be causing strange UI problems. Getting "This Operation is forbidden" when moving from function to function in NextCloud. Also getting  CSRF Errors when logging out. 

<img width="209" alt="2021-05-18_10-41-34" src="https://user-images.githubusercontent.com/8496835/118724618-d1892600-b7fc-11eb-97af-d92962e55ce2.png">

<img width="564" alt="2021-05-18_10-36-28" src="https://user-images.githubusercontent.com/8496835/118724881-32186300-b7fd-11eb-839d-1f03fa8234c3.png">

## Observation
1) If I don't use the products SMB functions to create the mounts, I don't get the strange UI issues.
2) If I don't use the products SMB functions to create the mounts, I am able to create shares successfully using the External Storage modules SMB function. 
3) The SMB mount string that is created is much different from a working GEN 1 product.  

Not Working String
<img width="1115" alt="Not Working SMB New Script" src="https://user-images.githubusercontent.com/8496835/118725177-93403680-b7fd-11eb-8903-9d12b21bc992.png">

Working String
<img width="1099" alt="Working SMB" src="https://user-images.githubusercontent.com/8496835/118725166-8de2ec00-b7fd-11eb-85f8-9ed69a1c84f2.png">

## Server configuration

**Nextcloud server version:** (see your admin page)
21.0.1

**Server OS** (Ubuntu server is default)
Windows 10

**PHP Version** (e.g. 7.4)
Version: 7.4.3
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 1000 MB

**How did you install the VM?** (Scripted install from master **OR** Released version)
No Ideal, it's HanssonIT Latest Product (Purchased 2 days ago)

## Network
**Do you use DHCP?**
Fixed

**Is port 80 and/or 443 open?**
Yes

#### Log file (/var/log/nextcloud/nextcloud.log)
Have no idea how to get them.

Insert your nextcloud.log file here
Have no idea how to get them.

#### Installation log (command output)
Have no idea how to get them.

Insert the CLI output here
Have no idea how to get them.

**Comment by szaimen** [comment]
Hi, thanks for your report!
As I understand it, you must have answered at this point with `Yes` to get into this situation.
https://github.com/nextcloud/vm/blob/d6b96f91ae1646c885a510deb9e2f62a63f6e955/apps/smbmount.sh#L135-L136
Solution: if you answer at this point with `No`, everything will work as expected.

---

@RJ-Make Is there maybe a way to make those lines more understandable, what do you think?

**Comment by enoch85** [comment]
@szaimen And regarding the CRSF, what's up with that?

**Comment by szaimen** [comment]
> And regarding the CSRF, what's up with that?

I actually don't know. Have never seen this error message. But the script doesn't change any apache configuration so it is not introduced by this script, I would say. Maybe a bug in Nextcloud...

**Comment by RJ-Make** [comment]
> 
> 
> Hi, thanks for your report!
> As I understand it, you must have answered at this point with `Yes` to get into this situation:
> 
> https://github.com/nextcloud/vm/blob/d6b96f91ae1646c885a510deb9e2f62a63f6e955/apps/smbmount.sh#L135-L136
> 
> **Solution**: if you answer at this point with `No`, everything will work as expected!
> 
> @RJ-Make Is there maybe a way to make those lines more understandable, what do you think? Do you have some ideas how to improve them?

Holy Cow,... While I've yet to confirm, you are indeed correct, I did answer Yes, each and every time, to the "built-in backup" option. 

I will assume, I just need to go back to the SMB function, delete the mount, recreate and answer no to the built-in backup?

If this is expected behavior, then I would add a WARNING to the question about not being able to create a share in NextCloud using the mount if selected as a backup target. This would have saved me hours. :-)

Thanks a Million for your help. 

I will test and report back tomorrow.

**Comment by szaimen** [comment]
> I will assume, I just need to go back to the SMB function, delete the mount, recreate and answer no to the built-in backup?

Yes thats the way to do it 👍

> If this is expected behavior, then I would add a WARNING to the question about not being able to create a share in NextCloud using the mount if selected as a backup target. This would have saved me hours. :-)

Yes  it is the expected behavior and I hope that it gets more with #1968. I am sorry that it isn't as clear, currently!

> Thanks a Million for your help.

No problem!

> I will test and report back tomorrow.

Yes, please do that :)

**Comment by RJ-Make** [comment]
Ok, you nailed it. Working perfectly now and no stupid UI issues. I really like the additional options in this GEN 2 SMB function you guys have added.

**Comment by szaimen** [comment]
Great! Thanks for your valuable feedback!

**Comment by enoch85** [comment]
Closing as this is solved. 

Thanks for posting @RJ-Make and thanks for the help @szaimen!
