### ISSUE TITLE
"Sorry, you are not root" VM error

### ISSUE THREAD

**Issue by chairmanfaust** [nextcloud/vm#199]
Downloaded the latest ubuntu 16.04 VM, tried both the OVA and the vmdk. Got the VM working in VMware ESX 6 with no problems. 

Logged in as ncadmin / nextcloud and the script prompted me to put in the root password for sudo which i entered nextcloud again. The script fails saying "Sorry you are not root" 

even using su and becoming root, the error persists.

Screenshots:
http://imgur.com/a/8QerK

**Comment by necrevistonnezr** [comment]
That seem similar to my error: https://github.com/nextcloud/vm/issues/192

In your screenshot, one can see that there's an error in line 15 & 18 of the script - that indicates that the script "lib.sh" has not been downloaded where those two variables ("debug_mode" and "is_root") are defined.

I suspect you don't have an internet connection after reboot. Check if you have internet connection at this stage e.g. via `nslookup google.com` or `ping google.com`. 

And what's the output of `ifconfig` and `cat /etc/network/interfaces`?

**Comment by chairmanfaust** [comment]
Thanks for this bit of advice! It was my problem. I didn't think a 'you are not root' problem had anything to do with my network settings but once i put the VM on a subnet with dhcp it started up and ran the script as expected.
