### ISSUE TITLE
Talk Connect Error with New deSEC improvements 

### ISSUE THREAD

**Issue by RJ-Make** [nextcloud/vm#1999]
## Steps to reproduce
1. Fresh NextCloud VM install using the latest GEN 2 product.
2. Add a talk deSEC subdomain using the latest GEN 2 product.
3. Install Talk using the latest GEN 2 product.

## Expected behavior
Connect and use Talk

## Actual behavior

<img width="268" alt="to" src="https://user-images.githubusercontent.com/8496835/119735147-eba0b500-be49-11eb-92d0-7c12c4909310.png">

<img width="550" alt="2021-05-26_5-45-47" src="https://user-images.githubusercontent.com/8496835/119735165-f2c7c300-be49-11eb-9fc7-d21d3a54fd39.png">

<img width="1106" alt="2021-05-26_5-52-48" src="https://user-images.githubusercontent.com/8496835/119735200-f9eed100-be49-11eb-9ae9-4283bd669e47.png">

## Server configuration
**NextCloud Version**
Nextcloud 21.0.2

**Server OS** (Ubuntu server is default)
Linux 5.4.0-73-generic x86_64 inside Windows Pro 10

**PHP Version** (e.g. 7.4)

Version: 7.4.3

**How did you install the VM?** (Scripted install from master **OR** Released version)
Not sure?

## Network
**Do you use DHCP?**
Fixed

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots
Not sure how to get any logs. I can see in "logging" there are a lot of these errors.

<img width="1515" alt="2021-05-26_17-50-05" src="https://user-images.githubusercontent.com/8496835/119735874-f871d880-be4a-11eb-8e5e-f6a9c24329d3.png">

**Comment by enoch85** [comment]
Maybe this is related? https://help.nextcloud.com/t/install-coturn-turnserver-on-centos-8/117168/6

**Comment by RJ-Make** [comment]
I don't think so, Henry stated

<img width="708" alt="2021-05-27_5-11-17" src="https://user-images.githubusercontent.com/8496835/119799475-1ae70e80-beaa-11eb-9737-66d9f1eeb551.png">

I'm on those versions and it doesn't ever work for me. It's not just a testing mechanism fault for me, talk simply will not work.

**Comment by RJ-Make** [comment]
Any word on this?

**Comment by RJ-Make** [comment]
I'll just add, Turning off the "High-performance Backend" allows the system to work.

**Comment by enoch85** [comment]
This is not 100% fixed yet, but will be in https://github.com/nextcloud/vm/issues/1994
