### ISSUE TITLE
Increase code quality

### ISSUE THREAD

**Issue by ypid** [nextcloud/vm#20]
[shellcheck](https://github.com/koalaman/shellcheck) is very nice for showing you possible problems in shell scripts.

Todos I noticed:
- [ ] Quote all variables in bash

Refs: https://github.com/enoch85/ownCloud-VM/issues/6#issuecomment-212143594

**EDIT:** Please read this: https://github.com/nextcloud/vm/issues/20#issuecomment-289817042

**Comment by enoch85** [comment]
Started a PR here: https://github.com/nextcloud/vm/pull/21 Feel free to help.

**Comment by ezraholm50** [comment]
Ran the install on a fresh vm, no problems installing. Only the documents app.

[nextcloudvminstalllog.txt](https://github.com/nextcloud/vm/files/417245/nextcloudvminstalllog.txt)

**Comment by enoch85** [comment]
Great! Yeah, the documents app fails. Please comment it out in this PR as well.

I will run the patch later and test that everything works out. Great job @ezraholm50!

**Comment by enoch85** [comment]
Btw, now @nextcloud/vm is available. FYI. :)

**Comment by ezraholm50** [comment]
@enoch85 Done! Better to have us both check it indeed. I'll run it another time somewhere tonight if i can manage to get some time off.

**Comment by enoch85** [comment]
All the files in 'static' aren't checked yet... ;)

**Comment by ezraholm50** [comment]
Actually I think they are, I git cloned the entire ShellCheck branch, moved all the scripts to /var/scripts

And I ran this just to be sure.
sed -i 's|production repo link|shellcheck repo link|g' /var/scripts/*

So that to me feels like everything that has been changed works.

**Comment by enoch85** [comment]
@ezraholm50 What I mean is that you should upload your changes to Github, the spellcheck branch. Please check for yourself, the only change I can see is that you hashed out the Documents app. :S

**Comment by ezraholm50** [comment]
I thought you pushed all the changes to the branch, haven't checked all the files in the pull req by view. So the entire /static still needs to be changed then? That will take a little while, no problem.

**Comment by enoch85** [comment]
@ypid PR failed. We followed the instructions from ShellCheck. These scripts are built over time for the past 2 years now. We have tested everything thoroughly over time, but with ShellCheck it fails . 

Feel free to open a PR if you want.

**Comment by ypid** [comment]
ShellCheck failed? It just gives suggestions :wink: Maybe you can start small. Run Shellcheck and then check the description of each issue.

Each issue has an ID with which you can visit the wiki of Shellcheck:
Example: https://github.com/koalaman/shellcheck/wiki/SC2086

**Comment by ezraholm50** [comment]
We did, most of the suggestions work, though not all. And to be honest with about 10% I really wouldn't know what to change.

This is put on long term, @enoch85? My idea was also to start small with some double quote's and few other things that work.

Thanks for the suggestion anyway!

**Comment by enoch85** [comment]
@ypid @ezraholm50 This is opensource, anyone can contribute ;) PRs are more than welcome.

For me this is not prioritized.

**Comment by enoch85** [comment]
Why did you close @ezraholm50?

**Comment by enoch85** [comment]
Ref https://github.com/nextcloud/vm/pull/36

**Comment by enoch85** [comment]
@ezraholm50 I still don't get why you closed this? It's long term, and it doesn't hurt if someone else wants to take care of this - I reopen.

**Comment by enoch85** [comment]
The code works, but doesn't look good. It needs to be consistent and properly intendented to please the eye. Stuff like: command if [ $? -eq 1 ]; then ...

Could be replaced with the if argument directly instead, like so: if command; then ...

Also use elif where possible to produce more code on fewer lines.

Exepct that the code is not consistent. In some places we use > instead of -gt which is the proper way of doing it.

And above all... intendeation!! We should use 4 spaces in a if argument for example.

There are a lot of other stuff I can't think of now, but anyone who have some time left over could do this one step at the time. My suggestion is to start with the smaller scripts and then work our way up to the main scripts (installation and setup).

There is a personal bounty for the person/persons who does this in one sweep, meaning if someone decides to spend time on this, create a PR and do everything according to my suggestions (or better) that person will be rewarded with $150 on their PayPal account. I posted a project that you can use for this if you want, it's found here: https://github.com/nextcloud/vm/projects/1

Let's get this done!

**Comment by morph027** [comment]
As bash-fetishist, i'll do this, did this for other projects too. If i'll be first one to pass review, money can be donated to [fsfe](https://fsfe.org/donate/donate.en.html) ;)

**Comment by morph027** [comment]
List of scripts...

- [ ] ./nextcloud_update.sh
- [ ] ./nextcloud-startup-script.sh
- [ ] ./nextcloud_install_production.sh
- [ ] ./static/ip.sh
- [ ] ./static/trusted.sh
- [ ] ./static/instruction.sh
- [ ] ./static/ip2.sh
- [ ] ./static/ntpdate.sh
- [ ] ./static/security.sh
- [ ] ./static/passman.sh
- [ ] ./static/temporary-fix.sh
- [ ] ./static/collabora.sh
- [ ] ./static/history.sh
- [ ] ./static/spreedme.sh
- [ ] ./static/change-ncadmin-profile.sh
- [ ] ./static/nextant.sh
- [ ] ./static/phpmyadmin_install_ubuntu16.sh
- [ ] ./static/update.sh
- [ ] ./static/redis-server-ubuntu16.sh
- [ ] ./static/nextcloud.sh
- [ ] ./static/change-root-profile.sh
- [ ] ./static/setup_secure_permissions_nextcloud.sh
- [ ] ./static/change_mysql_pass.sh
- [ ] ./static/test_connection.sh
- [ ] ./static/adduser.sh
- [ ] ./lets-encrypt/test-new-config.sh
- [ ] ./lets-encrypt/activate-ssl.sh

**Comment by enoch85** [comment]
@morph027 Thank you! If you find anything that could be improved even more let's do it. I can't remember all the thousands of lines right now. :)

**Comment by morph027** [comment]
Ok...let's start ;)

Why do we sometimes just ask to press any key to do something? What if the person does not want to take the action?

**Comment by morph027** [comment]
This is unclear to me:

```
sudo passwd "$UNIXUSER"
if [[ $? -gt 0 ]]
then
    sudo passwd "$UNIXUSER"
else
    sleep 2
fi
```

If it fails one time, it can fail a second time ;) If we really need to change the password, we should do this prompt in a loop until it was successful.

**Comment by enoch85** [comment]
Yes, that's a great example of old code that needs to be upgraded. A loop would be much better - the intention is to give the user another chance to type the correct password, and this was one of the first things I wrote some years ago.

So please, make it a loop until the attempt is successful. Thank you!

**Comment by enoch85** [comment]
> Why do we sometimes just ask to press any key to do something? What if the person does not want to take the action?

This is becuase in some cases there are information that could be useful to the user, and if he/she wouldn't press a key to continue he/she wouldn't have a chance to read what happened. Do you have a better suggestion?

**Comment by morph027** [comment]
> This is becuase in some cases there are information that could be useful to the user, and if he/she wouldn't press a key to continue he/she wouldn't have a chance to read what happened. Do you have a better suggestion?

No, fine hear...just for better understanding. Just in case of multiple runs, the user probably does not want to adjust the timezone every time ;) But this could be fixed with some markers, which indicates, that a section succeeded and we can skip it.

**Comment by morph027** [comment]
By the way...do you really want to review one HUUUUGE pull request? Just for reviewing purposes, it might be better to make small potions (e.g. for each script) to have atomic discussions in places, where it belongs.

**Comment by enoch85** [comment]
The script isn't intended to be run several times (nextcloud-startup-script.sh) and assumes certain things (don't remember everything now) but if we could make it safe to run several times that would be awesome. Like check if things are already setup and in that case skip them - :+1: :100:  from me on that. In later coding I have thought of making it possible to run several times, so the code is kind of mixed with the old where it would fail hard if that happened.

Some things I remember from the top of my head;
- It set's a new mysql password and then deletes the password file in the phpmyadmin installation, on a second run that would fail hard. (Btw, make phpMyadmin installation optional and come up with a better way of fetching the needed password for the installation. The current password should always be in .my.cnf, don't remember why I kept mysql_password.txt..)
- The UTF8 convert isn't supposed to be run twice. Maybe check if that's already done and skip if it is..?

> By the way...do you really want to review one HUUUUGE pull request?

As everything is tightly connected to eachother (some scripts depends on otheres etc, it's crucial that everything is perfect, and in a HUGE PR we could test that branch in one go on a test VM for example... So yes, I prefer a HUGE PR. :) I'm ofc counting with that you test all the scripts together and separately as well to be sure everything is bug free. :)

**Comment by enoch85** [comment]
@morph027 BTW, join #techandme on IRC if you want to discuss there instead. :)

Also, regarding the PRs, you could commit to your repo and I can check it there before you make a PR out of it.

**Comment by enoch85** [comment]
Oh, and btw. On [this](https://github.com/nextcloud/vm/issues/180) was on my todo list as well, maybe you can check why it happens sometimes?

**Comment by enoch85** [comment]
>  to have atomic discussions 

We could do that in IRC or in your repo.

**Comment by enoch85** [comment]
For reference: https://github.com/morph027/vm/tree/20-increase-code-quality

**Comment by PietsHost** [comment]
I would like to use variables for colored messages.. like this:

```
green='\e[32m'
reset='\e[0m'
[.... some code ....]
printf $green"here's my text"$reset

```
instead of
```
echo -e "\e[32m"
   read -p "Press any key to continue... " -n1 -s
   echo -e "\e[0m"
```

and also use printf instead of "echo -e", as described in the APPLICATION USAGE section of the following spec, for reliably portable code: [http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html](url)

**Comment by PietsHost** [comment]
Ah I've got another hint, bc I've just seen your variables:
All-caps environment variable names are actually reserved by POSIX-specified convention for variables with meaning to the shell or operating system, whereas lowercase names are reserved for application use. (Even if you aren't exporting your own variables to the environment, setting a shell variable overwrites any like-named environment variable, making the convention necessarily apply in both places)

**Comment by enoch85** [comment]
@PietsHost Hi there! :) So nice of you to contribute! :)

Right now we are working in @morph027 repo. Add you sugesstions there as a PR and we can discuss it. 

Thank you!

**Comment by enoch85** [comment]
@@PietsHost Also, you did some great stuff with prigress meters in you modified scripts. Would be nice to see them here as well. :+1:

**Comment by PietsHost** [comment]
Okay :)

**Comment by enoch85** [comment]
@morph027 @PietsHost How far have we come with the scripts?

**Comment by PietsHost** [comment]
No updates today, sorry.
I'm really busy right now.. maybe tomorrow

**Comment by morph027** [comment]
Same here..did some minor stuff but will have some more time tomorrow ;)

**Comment by morph027** [comment]
Ok....according to my list, every script in my branch is shellcheck'ed at least...

**Comment by enoch85** [comment]
@morph027 OK, nice! Good job! :+1: 

Now, let's improve the code in general. Things like removing unnecessary lines, compress if arguments, add functions and improve how the code works. You had some smart stuff going on with you while loops, I think they can be used in more places as we discussed earlier. 

I'm on IRC if you want to discuss.

**Comment by enoch85** [comment]
All if arguments are checked. Left some comments for you @morph027 to improve even more. Also, please do a `sed` on the file checking and dir checking. I did `if ! [ -f ...` while it should be `if [ ! -f ...`

**Comment by enoch85** [comment]
https://github.com/morph027/vm/pull/13#issuecomment-291194697 @morph027

**Comment by enoch85** [comment]
Rewrite is almost done (only 2 errors left afaik), just donated $149.71 to FSFE as @morph027 and me did everything ourselves. @PietsHost contributed with one commit but left the branch after that. Total commits will be around ~300. The code is improved very much and now Travis is included to be sure that it stays that way.

Thank you for your good work and ideas @morph027, and thanks @PietsHost for your commit.

![deepinscreenshot20170408194804](https://cloud.githubusercontent.com/assets/4511254/24831594/3418598c-1c8c-11e7-8ef1-04094b23140f.png)

**Comment by ypid** [comment]
Awesome work guys, thanks!

**Comment by morph027** [comment]
:heart: 

Great....will still continue looking at the code if my brain has some spare time left ;)
