### ISSUE TITLE
Face Recognition install Script Error.

### ISSUE THREAD

**Issue by tmsd2001** [nextcloud/vm#2000]
the script fail to add the key automatically.

+ echo 'deb https://repo.delellis.com.ar focal focal'
+ sudo apt-key add -
+ wget -qO - https://repo.delellis.com.ar/repo.gpg.key
gpg: no valid OpenPGP data found.

**Comment by szaimen** [comment]
Hi there, I've just tested it and it worked so it was probably just a short downtime of the link https://repo.delellis.com.ar/repo.gpg.key
Please try again and report back! Thanks! :)

**Comment by tmsd2001** [comment]
I had already added it manually.

**Comment by enoch85** [comment]
It's still a bug.

@szaimen We debated about this script, for exactly this reason.

I think we should move it to old.

**Comment by szaimen** [comment]
@enoch85 This is the first bug that I see regarding this script. So please let me fix that!

**Comment by szaimen** [comment]
Fixed in #2006
