### ISSUE TITLE
Feedback via Mail

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#2002]
I purchased the 2TB script yesterday for NExtCloud and BItwarden. I have run into a number of errors and have spent almost 2 full work days trying to get your scripts to function correctly.

I purchased the 2TB NextCloud OVA. Imported the OVA into vCenter. Increased CPU to 8 vcpu and 12gb vram. Power on the VM.

Geoblock error

![image](https://user-images.githubusercontent.com/42591237/120068828-10cc3800-c083-11eb-9dfa-54d448a713cc.png)

SMTP Relay for reference for later Bitwarden Mail Server Config Bugs, Manual setup, NO Encryption, Port 25, No username or Password. Test email does arrive.

![image](https://user-images.githubusercontent.com/42591237/120068872-2b9eac80-c083-11eb-91aa-e4db38bff3d0.png)

These are the apps package options

![image](https://user-images.githubusercontent.com/42591237/120068876-31948d80-c083-11eb-9847-f78390d6d227.png)

Bitwarden Setup Options

![image](https://user-images.githubusercontent.com/42591237/120068883-378a6e80-c083-11eb-9164-604f67c578df.png)

I followed the bitwarden instructions. Made sure to say no in the correct places. The apache based TLS Lets Encrypt cert installs fine. I pull up the bitwarden page as it says to in the settings and I create my first account. This completes with no issue but when I try to log that account in we see this error: 

![image](https://user-images.githubusercontent.com/42591237/120068891-3f4a1300-c083-11eb-9b52-120dc3a39c7f.png)

I waited a few minutes tried again and could login.

Then the Bitwarden Mail Config. I have tried this using the default global config as already configured and just hit OK (just leave the box empty as it states in instructions)

![image](https://user-images.githubusercontent.com/42591237/120068895-496c1180-c083-11eb-9580-e94a4818e83a.png)

But then it errors. Empty is not allowed….

![image](https://user-images.githubusercontent.com/42591237/120068899-4ec95c00-c083-11eb-9810-ada514c59d4e.png)

So next I go through the process to specify the same settings I made before as shown in the above screen shot for Mail server setup but it will not allow me to not input a user name or password. The wizard is then locked in place. You can’t back up to switch to a user based smtp auth and you cant exit the wizard. The only option is reboot server then restart the menu process from SSH. So now I went and created a new user account for bitwarden in our Office 365 which costs us $20 a month per license just so we could send email from this app (which the integration of Bitwarden in your VM app is why we bought it) and so we try to use valid office 365 SMTP email setup.

![image](https://user-images.githubusercontent.com/42591237/120068908-5db00e80-c083-11eb-9300-bcf21a20d741.png)

Confirm prior info then input STARTTLS for encryption

![image](https://user-images.githubusercontent.com/42591237/120068914-63a5ef80-c083-11eb-96e7-300fb44ed424.png)

Confirm STRATTLS, input Office 365 STARTTLS port of 587

![image](https://user-images.githubusercontent.com/42591237/120068919-6b659400-c083-11eb-80c8-1fdb4911e86d.png)

Confirm 587, input username 

![image](https://user-images.githubusercontent.com/42591237/120068933-7f10fa80-c083-11eb-9506-a09dddfba6b7.png)

Confirm Username and input password. Confirm Password.

Enter the list of admin address in name1@host.tld,name2@host.tld format per the example.

![image](https://user-images.githubusercontent.com/42591237/120068943-8c2de980-c083-11eb-86c2-2f401ed646a5.png)

Script tells me the bitwarden config is done. I go back to the bitwarden page go to the user profile click on confirm email address and we get a error

![image](https://user-images.githubusercontent.com/42591237/120068949-92bc6100-c083-11eb-8faf-90d2c8ddcf79.png)

If I try to log in as admin and I input one of the admin address specified above I get this for an error

![image](https://user-images.githubusercontent.com/42591237/120068966-9a7c0580-c083-11eb-9c0e-6d3e54740d8d.png)

All my other Nextcloud and server email settings are working fine.

![image](https://user-images.githubusercontent.com/42591237/120068970-a071e680-c083-11eb-869b-0265cb2245f1.png)

The main reason we bought this VM template was the Bitwarden Script. The Nextcloud features are going to be useful but we do not have a business need for it like we do for the Bitwarden since we also have OneDrive as part of our Office 365. But we decided we were going to make a specific use case for the nextcloud for storage of more confidential documents that we don’t want exposed to the internet and can more lock it down to our network only. I purchased this script to install them both. We were going to buy a support package for this if I could prove its use to our VP and COO for maintaining both our passwords and privileged documents that we did not want to risk exposure on. But I can’t prove my concept if I can’t get half of it to work.

**Comment by szaimen** [comment]
I've identified 2 issues in this long mail: 
1. geoblock. the csv link to the file has changed
2. we definitely need to rework the Bitwarden Mail-configuration script. Which is handled in https://github.com/nextcloud/vm/issues/1453

**Comment by enoch85** [comment]
This should be fixed now.

**Comment by szaimen** [comment]
Not completely. #2004 is missing.
