### ISSUE TITLE
master/static/index.sh

### ISSUE THREAD

**Issue by borisk1** [nextcloud/vm#2008]
## Steps to reproduce
1. Nextcloud Install script
2.
3.

## Expected behavior
We just tried to fetch 'https://raw.githubusercontent.com/nextcloud/vm/master/static/index.sh', but it seems like the server for the download isn't reachable, or that a temporary error occurred. We will   │
│ now try again.  

## Actual behavior
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**PHP Version** (e.g. 7.4)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by szaimen** [comment]
ping @enoch85 this is a big problem for files that aren't ending with .sh because we use curl_to_dir in download_script
https://github.com/nextcloud/vm/blob/b86f0079c493bd97c315eee5044f4de27e5d8874/lib.sh#L1268

**Comment by reinthal** [comment]
Just experienced the same issue. Turns out that the file is not available on github. I get 404 file not found.

**Comment by enoch85** [comment]
Aah great catch!

Will think about on how to solve this.

**Comment by enoch85** [comment]
Please try again, this should be fixed now.

Please report back!

**Comment by borisk1** [comment]
It seems ok now, it is fixed.

Thanks :)
