### ISSUE TITLE
Missing sudo causes loop in `/var/scripts/adduser.sh`

### ISSUE THREAD

**Issue by paulmenzel** [nextcloud/vm#2013]
## Steps to reproduce
1.  Install  minimal Debian bullseye/testing system with only root user.
2.  Download and run [`nextcloud_install_production.sh`](https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh).

        # md5sum nextcloud_install_production.sh
        3f2a597d6ae0ddb140d771487ed5d42e  nextcloud_install_production.sh

3.  Choose to create a user. Enter `ncadmin`.

## Expected behavior
It should succeed.

## Actual behavior

Notice, failure:

    /var/scripts/adduser.sh: line 35: sudo: command not found

The script should check, that sudo is installed.

**Comment by enoch85** [comment]
Thanks! Will add sudo as a dependency.
