### ISSUE TITLE
SSL: "It seems like no certs were generated"

### ISSUE THREAD

**Issue by ncxpert** [nextcloud/vm#202]
Hello, 

unlike in the past with the current community VM I have serious problems to finish SSL process.

There's always a error message "It seems like no certs were generated, we will do xx more tries" although  there are messages indicating that certificate process itself was successfull:

---
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for domainame.here
Waiting for verification...
Cleaning up challenges
Generating key (4096 bits): /etc/letsencrypt/keys/0000_key-certbot.pem
Creating CSR: /etc/letsencrypt/csr/0000_csr-certbot.pem

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at
   /etc/letsencrypt/live/domainname.here/fullchain.pem. Your cert
   will expire on 2017-07-13. To obtain a new or tweaked version of
   this certificate in the future, simply run certbot again. To
   non-interactively renew *all* of your certificates, run "certbot
   renew"
   
   [...]
   
   Enabling site 000-default.
To activate the new configuration, you need to run:
  service apache2 reload
It seems like no certs were generated, we will do 2 more tries.

---

Because of this issue startup script will not finish properly and / or will stop at the SSL-process.

Best regards,

Carlos

**Comment by enoch85** [comment]
@ncxpert OK, thanks for reporting. Does this happen all the time? can you run the SSL script with debug mode activated and post the full output on https://hastebin.com/ and link it here? Thanks!

@morph027 We need to improve this even more.

**Comment by Ark74** [comment]
I tested 3 times. All of them get you there.

Here the output.
https://hastebin.com/cututiyahu.diff

**Comment by enoch85** [comment]
@Ark74 What's the output of `cat /tmp/le_test`?

**Comment by enoch85** [comment]
Btw, please make sure you are running the latest version of the script: https://raw.githubusercontent.com/nextcloud/vm/master/lets-encrypt/activate-ssl.sh

**Comment by enoch85** [comment]
@Ark74 Found it, now it should work!

**Comment by Ark74** [comment]
Well, it was a clean installation, it should be the latest. I guess

**Comment by enoch85** [comment]
@Ark74 Please test again as soon as I merged this PR. Thanks!

**Comment by Ark74** [comment]
Yeah, i got it ready to test. :+1:

**Comment by enoch85** [comment]
@Ark74 Great, let me know the output. Thanks!

**Comment by Ark74** [comment]
It passes! :) Wow a 8192 bit key.
That's strong.

**Comment by enoch85** [comment]
@Ark74 Great, thanks for testing!
