### ISSUE TITLE
Wrong PHP version for sed entry when installing (21.0.2)

### ISSUE THREAD

**Issue by brdick** [nextcloud/vm#2033]
## Steps to reproduce
1. Download script version 21.0.2 from releases
2. Execute sudo bash nextcloud_install_production.sh on a clean Ubuntu Server 20 install

## Expected behavior
It appears to want to alter a configuration file in /etc/php/8.0/fpm/pool.d/(nextcloud.conf), but this file has been created in /etc/php/7.4/fpm/pool.d/ hence the usage of different PHP versions during install.

## Actual behavior
Script stops due to no configuration file in the directory of PHP8.0.

## Server configuration

**Nextcloud server version:** (see your admin page)
Intentional latest.

**Server OS** (Ubuntu server is default)
Ubuntu Server 20

**PHP Version** (e.g. 7.4)
8.0

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install from released Version

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
Yes

#### Log file (/var/log/nextcloud/nextcloud.log)
```
-- no file
```

#### Installation log (command output)
```
Getting current PHP-version...
PHPVER=8.0
grep: /etc/php/8.0/fpm/pool.d/nextcloud.conf: No such file or directory
grep: /etc/php/8.0/fpm/pool.d/nextcloud.conf: No such file or directory
grep: /etc/php/8.0/fpm/pool.d/nextcloud.conf: No such file or directory
Automatically configures pm.max_children for php-fpm...
sed: can't read /etc/php/8.0/fpm/pool.d/nextcloud.conf: No such file or directory
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sed -i s|pm.max_children.*|pm.max_children = 149|g /etc/php/8.0/fpm/pool.d/nextcloud.conf failed
```

**Comment by enoch85** [comment]
>  sudo bash nextcloud_install_production.sh on a clean Ubuntu Server 20 install

Ubuntu 20.04 comes with PHP 7.4 as default. Did you install PHP 8?

**Comment by enoch85** [comment]
Here's the code in question: https://github.com/nextcloud/vm/blob/master/lib.sh#L1780-L1782

**Comment by brdick** [comment]
Ah right, that should be it. I haven't had PHP 8 installed, but got a sources.list from a generator in order to add multiverse, and it had a repository for PHP 8 added, hence apt installs php8 with the installer script too.
Thank you for the quick reply and help, I haven't thought about this!

**Comment by enoch85** [comment]
Glad I could help!
