### ISSUE TITLE
Sabre\DAV\Exception\BadRequest Error and larger files failing to upload

### ISSUE THREAD

**Issue by matthewlswanson** [nextcloud/vm#2035]
## Steps to reproduce
1. Create base Ubuntu 20.04
2. Run the nextcloudvm install script
3. Autoupload from android app

## Expected behavior
Tell us what should happen
Files upload correctly

## Actual behavior
Files fail and produce error

## Server configuration

**Nextcloud server version:** (see your admin page)
21.0.2
**Server OS** (Ubuntu server is default)
Ubuntu 20.04
**PHP Version** (e.g. 7.4)
7.4.3
**How did you install the VM?** (Scripted install from master **OR** Released version)
wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
sudo bash nextcloud_install_production.sh

## Network
**Do you use DHCP?**
DHCP, internal only
**Is port 80 and/or 443 open?**
No
## Logs / Screenshots

```
Sabre\DAV\Exception\BadRequest: Expected filesize of 10240000 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 2621440 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.

    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:

    OCA\DAV\Connector\Sabre\File->put()

    /var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php - line 46:

    OCA\DAV\Connector\Sabre\Directory->createFile()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1098:

    OCA\DAV\Upload\UploadFolder->createFile()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 504:

    Sabre\DAV\Server->createFile()

    /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

    Sabre\DAV\CorePlugin->httpPut()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:

    Sabre\DAV\Server->emit()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:

    Sabre\DAV\Server->invokeMethod()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:

    Sabre\DAV\Server->start()

    /var/www/nextcloud/apps/dav/lib/Server.php - line 332:

    Sabre\DAV\Server->exec()

    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

    OCA\DAV\Server->exec()

    /var/www/nextcloud/remote.php - line 167:

    require_once("/var/www/ne ... p")
```
#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi,

Thanks for posting your issue!

Sorry, but I can't reproduce this. Are you on a slow network maybe? The error in question is known since before, and is an old thing that never seems to get "fixed".

https://www.google.com/search?channel=fs&client=ubuntu&q=Expected+filesize+of+10240000+bytes+but+read+nextcloud

**Comment by matthewlswanson** [comment]
I'm on a pretty fast network, it's just from local to local. I am uploading from my phone to other servers at around 350mbps, and can transfer from my workstation to my nextcloud server at gig.

**Comment by enoch85** [comment]
@szaimen Can you reproduce this?

**Comment by szaimen** [comment]
I have yometimes such entries in my logs, yes. But I don't know how to reproduce and it doesn't break anything (maybe because of retried uploads?), afaik.

**Comment by szaimen** [comment]
I'd say lets track this in https://github.com/nextcloud/server/issues/21382#issuecomment-868768448

**Comment by szaimen** [comment]
And the android issue is probably this one: https://github.com/nextcloud/android/issues/8134#issuecomment-863053005
