### ISSUE TITLE
Regression when becoming root

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#2037]
When becoming root with `sudo -i` or SSH'ing into the box as root, the installation script runs. This is incorrect and it should not run.

What can I do to prevent the installation script from running when becoming root? Thank you!

**Comment by enoch85** [comment]
It's because you failed to run the first setup properly.

The last thing that happens in the setup is that the setup script is removed.

**Comment by thejohnha** [comment]
There was no error in finishing the script. It completed successfully. Could you point me in the right direction on how to disable the script from running again please when becoming root? Thank you @enoch85

**Comment by enoch85** [comment]
Yes, you ended it to early: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L582-L585
