### ISSUE TITLE
Use the md mod for acme challenge?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#2038]
I wonder if it would make sense to implement certificate issuing with the mod_md apache mod?
I've just tested the availability and it seems to be already available on ubuntu focal :)
https://github.com/icing/mod_md

(I know that this idea might come a bit late now that desec was chosen as provider...)

**Comment by enoch85** [comment]
What's the benefits over the current implementation?

**Comment by szaimen** [comment]
It should work with almost any Domain

**Comment by enoch85** [comment]
Isn't it the same as `certbot apache`, where `certbot` configures Apache for you?

**Comment by szaimen** [comment]
Seems like I haven't read the documentation accurate enough but is a nice way of getting certificates nonetheless.
