### ISSUE TITLE
Invalid exchange / Error zfs list 134 / zfs-auto-snapshot -r ncdata failed

### ISSUE THREAD

**Issue by piridasi** [nextcloud/vm#2041]
## Steps to reproduce
1.tried to upgrade with "sudo /var/scripts/update.sh"
2.
3.

## Expected behavior
update from version 21.0.2 to 22.0.0

## Actual behavior
Backing up data...
Adding required repo (multiverse).
'multiverse' distribution component is already enabled for all sources.
internal error: Invalid exchange
Aborted (core dumped)
Error: zfs list 134:
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
zfs-auto-snapshot -r ncdata failed

## Server configuration

**Nextcloud server version:** 21.0.2
**Server OS** Ubuntu

**PHP Version** 7.4

**How did you install the VM?** Scripted install from master 

## Network
**Do you use DHCP?** no

**Is port 80 and/or 443 open?** yes 443cd

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
From root@XXXXXXX.dyndns.tv  Wed Jul  7 14:30:06 2021
Return-Path: <root@XXXXXX.dyndns.tv>
X-Original-To: root
Delivered-To: root@XXXXXXX.dyndns.tv
Received: by nextcloud2tb (Postfix, from userid 0)
        id 94EAA10065F; Wed,  7 Jul 2021 14:30:05 +0200 (CEST)
From: root@XXXXXXX.dyndns.tv (Cron Daemon)
To: root@XXXXXXX.dyndns.tv
Subject: Cron <root@XXXXXXX> which zfs-auto-snapshot > /dev/null || exit 0 ; zfs-auto-snapshot --quiet --syslog --label=frequent --keep=4 //
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <PATH=/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20210707123005.94EAA10065F@nextcloud2tb>
Date: Wed,  7 Jul 2021 14:30:05 +0200 (CEST)

internal error: Invalid exchange
Aborted (core dumped)
Error: zfs list 134:

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by piridasi** [comment]
Tried to update as written and got this message: Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!

**Comment by enoch85** [comment]
@piridasi Thanks for your report!

Never seen this before, I I would have to investigate.

What's the output of `zpool status`?

**Comment by piridasi** [comment]
zpool status:

root@XXXXXX:~# zpool status
  pool: ncdata
 state: DEGRADED
status: One or more devices has experienced an error resulting in data
        corruption.  Applications may be affected.
action: Restore the file in question if possible.  Otherwise restore the
        entire pool from backup.
   see: http://zfsonlinux.org/msg/ZFS-8000-8A
  scan: scrub repaired 0B in 0 days 03:02:43 with 0 errors on Sun May  9 03:26:45 2021
config:

        NAME                    STATE     READ WRITE CKSUM
        ncdata                  DEGRADED     0     0     0
          10636147083716686786  DEGRADED     0     0   336  too many errors

**Comment by piridasi** [comment]
dh -h:

Usage: dh [options]

  dh is a part of debhelper. See debhelper(7)
  and dh(1) for complete usage instructions.
root@XXXXXX:~# df -h
Filesystem                         Size  Used Avail Use% Mounted on
udev                               1.9G     0  1.9G   0% /dev
tmpfs                              394M  1.4M  393M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   35G  9.9G   24G  30% /
tmpfs                              2.0G   16K  2.0G   1% /dev/shm
tmpfs                              5.0M  4.0K  5.0M   1% /run/lock
tmpfs                              2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda2                          976M  203M  707M  23% /boot
/dev/loop0                          62M   62M     0 100% /snap/core20/975
ncdata                             1.9T   97G  1.8T   6% /mnt/ncdata
/dev/loop1                          43M   43M     0 100% /snap/certbot/1201
/dev/loop3                          56M   56M     0 100% /snap/core18/2066
/dev/loop2                          43M   43M     0 100% /snap/certbot/1280
/dev/loop4                          56M   56M     0 100% /snap/core18/2074
/dev/loop6                          67M   67M     0 100% /snap/lxd/20806
/dev/loop5                          62M   62M     0 100% /snap/core20/1026
/dev/loop7                          67M   67M     0 100% /snap/lxd/20840
/dev/loop9                          33M   33M     0 100% /snap/snapd/12159
/dev/loop8                          33M   33M     0 100% /snap/snapd/12398
tmpfs                              394M     0  394M   0% /run/user/1000
overlay                             35G  9.9G   24G  30% /var/lib/docker/overlay2/469eec3846590f22f12f21d374791984d01416a79ddfbe94c869ee3b5db5a5cc/merged
overlay                             35G  9.9G   24G  30% /var/lib/docker/overlay2/3090c900669aba00bfe16b309d3786889b1be5de5260cb754e6a96f9f6d6864e/merged

**Comment by enoch85** [comment]
>     NAME                    STATE     READ WRITE CKSUM
  >  ncdata                  DEGRADED     0     0     0
   >   10636147083716686786  DEGRADED     0     0   336  too many errors

Your disk isn't healthy. 

I wold run a manual scrub just to see if the errors are fixed. In any case, make a backup now before it's too late.

**Comment by piridasi** [comment]
Ok, I try it, backup is made every day......    :-)
As this is running on a VM on QNAP you think the "virtual disc's" are not healthy, because the physical ones don't give me any errors...
