### ISSUE TITLE
NC 22 - Removing "Elasticsearch" (Full Text Search) via VM Menu Kill App Store. 

### ISSUE THREAD

**Issue by RJ-Make** [nextcloud/vm#2044]
## Steps to reproduce
1.Remove Elasticsearch using VM menu

## Expected behavior
1. I don't believe this should happen.. :-)

## Actual behavior
See pics

## Server configuration

**Nextcloud server version:** 
22

**PHP Version**
7.4.3

## Logs / Screenshots

**_This is AFTER removal. (I also tried restarting the VM) _** 

<img width="1914" alt="2021-07-10_13-06-11" src="https://user-images.githubusercontent.com/8496835/125171324-a9290280-e181-11eb-8db0-e111ebe2fd4c.png">

**_This is BEFORE removal. _** 

<img width="1913" alt="2021-07-10_13-12-23" src="https://user-images.githubusercontent.com/8496835/125171345-c52ca400-e181-11eb-9df4-4c928c9b2172.png">

**Comment by enoch85** [comment]
Must be a temporary glitch with your connection to the app store.

What does the browser log say?

**Comment by RJ-Make** [comment]
> 
> 
> Must be a temporary glitch with your connection to the app store.
> 
> What does the browser log say?

If so, the glitch persisted after several VM reboots. (and server) This was not the only problem, so for now I rolled back to 21.0.3. When I try 22 again, I'll update.

**Comment by enoch85** [comment]
I can't reproduce this on Nextcloud 22.

https://cloud.hanssonit.se/s/w5j6nNc5EHYLeHw
