### ISSUE TITLE
add to documentservers script

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2048]
‘allow_local_remote_servers’ => true,

**Comment by enoch85** [comment]
@szaimen Not sure about this one. 

I've seen a lot of issues with this *not* being set, but at the same time I'm not sure about the real affects of actually setting it.

Do you have an opinion?

**Comment by enoch85** [comment]
Let's do this specifically for the Documentserver scripts and not globally.

**Comment by szaimen** [comment]
Hm... this wasn't needed on any of my installations before but if it helps, it probably makes sense. Sry for my late reply!
