### ISSUE TITLE
Zero-byte files

### ISSUE THREAD

**Issue by dannyb2100** [nextcloud/vm#2058]
## Steps to reproduce
1. Upload a file to the server
2. Check the file
3. File is zero-ed

## Expected behavior
Files to not be zero

## Actual behavior
The files are zero-ed

## Server configuration

**Nextcloud server version:** 
22.0.0

**Server OS**
Ubuntu

**PHP Version** 
7.4.3

**How did you install the VM?**
Scripted VM - 1TB version - clean and new install running on ESXi 6.7

## Network
**Do you use DHCP?**
DHCP - set static from the router

**Is port 80 and/or 443 open?**
Not public exposed

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Empty
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Thanks for the report. 

Which files are 0-byte?

**Comment by dannyb2100** [comment]
Sadly every file.
I have tried .txt, .exe and various media formats.

Sent from my iPhone

On 21 Jul 2021, at 20:27, Daniel Hansson ***@***.***> wrote:

﻿

Thanks for the report.

Which files are 0-byte?

**Comment by enoch85** [comment]
Ok, that's kind of serious...

So you say that you have 1000 files, and all 1000 files are 0-byte?

Can you reach your data at all from the web interface?

**Comment by dannyb2100** [comment]
I can reach the files through the web interface, but they're zero-ed. 

I generated 500 random data files of 5Mb each. 
Each with the same result - I then ran the script to check for zero-byte files.


/mnt/ncdata/Dan/files/Test/b1NODg3Pt4de
/mnt/ncdata/Dan/files/Test/002mfmMntU7z
/mnt/ncdata/Dan/files/Test/8CcgnxOnex57
/mnt/ncdata/Dan/files/Test/6pAW7Vc9dQ8u
/mnt/ncdata/Dan/files/Test/Bws37RMkGu1D
/mnt/ncdata/Dan/files/Test/kUvwTih37HUX
/mnt/ncdata/Dan/files/Test/rufus-3.14.exe
/mnt/ncdata/Dan/files/Test/qnbgl2UsrwYU
/mnt/ncdata/Dan/files/Test/1GlrZeDBVW9r
/mnt/ncdata/Dan/files/Test/Hx772qIxRAr9
/mnt/ncdata/Dan/files/Test/ZzpUBBt7wPc3
/mnt/ncdata/Dan/files/Test/SO6pe9wJ0CMe
/mnt/ncdata/Dan/files/Test/3qGGN1giUt0f
/mnt/ncdata/Dan/files/Test/E5ARxGnIDEEJ
/mnt/ncdata/appdata_oc8us7vsahml/avatar/PlexUser/generated
/mnt/ncdata/appdata_oc8us7vsahml/avatar/Dan/generated
ncadmin@nc:~$

**Comment by enoch85** [comment]
Okok, thanks! :+1: 

The script is made basically just to check if the files are 0-byte or not. It's an old issue in Nextcloud, and can be found here: https://github.com/nextcloud/server/issues/3056

The "goal" with the script is to create even more awareness of the bug so that it can be fixed, since it's kind of serious. Please post your findings/configuration in the issue I already mentioned.

I think it's related to the Desktop client but I'm not sure. Have you tried uploading via the webUI?
