### ISSUE TITLE
Setup script hangs when creating new web admin user

### ISSUE THREAD

**Issue by meichthys** [nextcloud/vm#2059]
Environment (I haven't been able to test on other environments yet):
Hypervisor: Proxmox 6.4-8
VM: 
![image](https://user-images.githubusercontent.com/10717998/126588696-22a17479-fcfd-4846-981b-6be0469a4412.png)

## Steps to reproduce
1. Run nextcloud_production_install.sh
2. Reboot and login to finish setup
3. On the step when entering new web admin password it hangs.

## Expected behavior
Tell us what should happen

## Actual behavior
The script should continue and finish setting up the nextcloud vm

## Server configuration

**Nextcloud server version:** (see your admin page)
22.0

**Server OS** (Ubuntu server is default)
Ubuntu

**PHP Version** (e.g. 7.4)
7.4

**How did you install the VM?** (Scripted install from master **OR** Released version)
Script from nextcloud/vm/master/nextcloud_production_install.sh

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots

![image](https://user-images.githubusercontent.com/10717998/126588874-bc6fa910-c0bd-427f-b1b9-4d476b951145.png)
Note: the characters at the bottom were not there initially - only after i  tried to use ctrl-s to take a screenshot.
#### Log file (/var/log/nextcloud/nextcloud.log)
```
empty
```

#### Installation log (command output)
```
unable to capture.
```

**Comment by enoch85** [comment]
Hi,

It probably hangs due to that their repo servers are temporarily out of service or very loaded 

Webmin usually takes a lot of time to install depending on your connection.

Please skip it for now and try again later.

Thanks!

**Comment by meichthys** [comment]
Thanks @enoch85 .
I've been trying to install without any of the extra apps/features, and it still seems to hang up after trying to add the web admin user. (Changing the cli user password works fine).

This is the point it hangs:
![image](https://user-images.githubusercontent.com/10717998/126631084-7546a67f-e642-4a99-b710-c4bb5633dd62.png)

I left it sit overnight but the extra time didn't seem to help. 

The nextcloud.log file is empty if I ctrl-c to exit the script. Is there a different log file I can look at to see why it may be hanging up?

**Comment by enoch85** [comment]
I just executed the whole installation process + the setup process without any issues at all.

I can't reproduce this.

**Comment by meichthys** [comment]
Ok, i figured this would be the case. I've tried using HyperV+Ubuntu, and that seemed to work fine so it must have something to do with the Proxmox+Ubuntu combination.

Is there an log file that the script uses by chance that may shed some more light on why it is failing?

**Comment by enoch85** [comment]
Sorry, no log file, but you could run the function in question with `bash -x /path/to/script.sh`

https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L341-L416

**Comment by meichthys** [comment]
Ok, Thanks for this. It was enough to track down that the script is hanging on the [user:add command](https://github.com/nextcloud/vm/blob/3a2fcaec7282bb996dee0b605c9e5dc1a8770b6a/nextcloud-startup-script.sh#L396). To rule out the --password-from-env option as the issue, i removed it and manually entered the password again, but with no luck. Perhaps something didn't setup correctly in the database. I'll keep digging and report back here if i find a workaround.

**Comment by meichthys** [comment]
Removing the `# NEXTCLOUD USER` section and the `# Delete old user` section from the script seemed to work, but it's not fixing the root cause which seems to be filesystem related:
![image](https://user-images.githubusercontent.com/10717998/126652135-ec0e73af-e471-4721-98ac-a3e3b1f50f1d.png)
I think the issue may be related to the fact that I'm trying to install onto a shared ZFS pool but the script may be expecting EXT4(?)

**Comment by enoch85** [comment]
> I think the issue may be related to the fact that I'm trying to install onto a shared ZFS pool but the script may be expecting EXT4(?)

You know, scripts are not that smart. They can only do what is expected. If you run a custom setup then I'm sorry but I guarantee that it will work as expected.
