### ISSUE TITLE
Environment not properly prepared.

### ISSUE THREAD

**Issue by svolmer** [nextcloud/vm#2063]
I am executing `sudo bash nextcloud_install_production.sh` on a fresh Ubuntu 20.04 VM. It runs fine until it reaches the following output: `Nextcloud was installed successfully!`. Immediately after, the script fails with the following output:

```
Nextcloud version:
Your data directory is readable by other users
Please change the permissions to 0770 so that the directory cannot be listed by other users.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /var/www/nextcloud/lib/private/Console/Application.php:162
Stack trace:
#0 /var/www/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#1 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#2 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ status failed
```

Anyone can help me with this?

**Comment by enoch85** [comment]
Thanks for reporting your issue.

Which hypervisor is this?

**Comment by svolmer** [comment]
I am using a virtual machine on Azure (Standard_B1ms) with an Ubuntu Server 20.04 LTS Gen2 image. I assume that those virtual machines use Windows Hyper-V.

**Comment by enoch85** [comment]
Do you have one "physical" disk for OS and another for DATA?

**Comment by svolmer** [comment]
I am using a 32GB standard SSD for the host OS and a ADLS Gen2 storage account container mounted with blobfuse as the data disk.

**Comment by enoch85** [comment]
> ADLS Gen2 storage account container mounted with blobfuse as the data disk.

Never heard about that before.

Are you sure the data disk is mounted? I think the reason for all this is that the data disk is lost.

**Comment by svolmer** [comment]
After some investigation it turns out that blobfuse is currently not supporting the linux file permissions. Although some people made this work with NextCloud (https://www.wintellect.com/nextcloud-and-azure-blob-storage-a-match-made-in-the-cloud/), it doesn't work in this environment. 

The idea, however, is brilliant. You pay only for the storage that is used.
