### ISSUE TITLE
Allow deSEC to use dedyn.io domain that has been pre-registered

### ISSUE THREAD

**Issue by wildd0g** [nextcloud/vm#2077]
## Steps to reproduce
1.Already have a dedyn.io domain claimed
2.Run first time setup
3.Enter your already claimed dedyn.io domain name

## Expected behavior
A flow to enter your token or otherwise setup your nextcloud instance to use your existing domain

## Actual behavior
Report domain is already taken and ask to use a different domain, or skip altogether.

## Server configuration

**Nextcloud server version: 22 

**Server OS** Ubuntu

**PHP Version** N.A.

**How did you install the VM?** 
Nextcloud VM Pre-installed – 40 GB

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
Yes

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi,

Thanks for your suggestion, you're free to start a PR which we can work on together to implement this feature.

**Comment by wildd0g** [comment]
The provided pull request should contain the needed functionality: 
If the domain is already existing and the user indicates they have the Authkey, skip the registration steps altogether and go straight to Authkey prompt and onwards.
Since I imagine this complicates the overview of the correct controll flow, I have also separated out the controll flow from the individual steps. 

Also small changes: added warnings when selecting No will exit the script, and added a message on an aborted exit on how to run the script again.

**Comment by enoch85** [comment]
Hi,

Just checking here. I see no new PR since we closed the old one?

**Comment by wildd0g** [comment]
Hey,

Went on vacation past week, will add the PR tomorrow I think.

Kind regards,

Marijn Peppelman.

https://people.utwente.nl/m.peppelman
e-mail: ***@***.***
Tel. 06-239 29 502
Calslaan 9C 303,
7522 MH,
Enschede

**Comment by enoch85** [comment]
<3

**Comment by enoch85** [comment]
hey @wildd0g any update here? It feels we were so close to make a much cleaner solution. Would be a shame if it never happened.
