### ISSUE TITLE
/bin/sh: 1: /var/scripts/spamhaus_crontab.sh: not found

### ISSUE THREAD

**Issue by konwin** [nextcloud/vm#2078]
Hello,
I installed thursday the nextcloud-vm via script and now getting every night an error via e-mail
`/bin/sh: 1: /var/scripts/spamhaus_crontab.sh: not found` from the Cron Deamon.
I searched the `/var/scripts` folder and only found `spamhaus_cronjob.sh` instead of `spamhaus_crontab.sh`!
Is it save to change this in the crontab? Think this is an typo in the install-script!?
Can't exactely determine where it belongs but I think it is the add-on "enchanced security".

**Comment by enoch85** [comment]
Thanks for your report!

You 100% correct, it's a typo. Glad you found it, will fix it right away!
