### ISSUE TITLE
no network interface and script not work

### ISSUE THREAD

**Issue by kambatx** [nextcloud/vm#208]
Hello, I have a problem and do not know what I should do. With ifconfig only the loopback adapter is displayed. Probably I can not run the script. What can I do to solve the problem? best regards Anton
![neue bitmap](https://cloud.githubusercontent.com/assets/27886926/25303970/c279d9c2-275d-11e7-97a3-d64fa998a1c3.jpg)

**Comment by enoch85** [comment]
@kambatx Download the latest script from master and use that instead. You can find that scrit here: https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud-startup-script.sh

**Comment by kambatx** [comment]
how can I do that? I have no connection to the internet and not local network.

**Comment by enoch85** [comment]
Copy paste from the file I linked.

rm /var/scripts/nextcloud-startup-script.sh
nano /var/scripts/nextcloud-startup-script.sh
PASTE
sudo bash /var/scripts/nextcloud-startup-script.sh

**Comment by kambatx** [comment]
Thank you, sometimes I think too complicated :-)

**Comment by kambatx** [comment]
Can unfortunately make over hyper-v nothing with copy and paste. Have you possibly a different tip?

**Comment by enoch85** [comment]
Add this by hand: https://github.com/nextcloud/vm/pull/203/files

That's the fix that make everything work.

**Comment by kambatx** [comment]
The network works now, but the script is still not ok.
![neue bitmap1](https://cloud.githubusercontent.com/assets/27886926/25315127/a7da6d9a-2850-11e7-87d3-8750869b6d7b.jpg)

![neue bitmap2](https://cloud.githubusercontent.com/assets/27886926/25315130/b178bbf4-2850-11e7-9f77-1c66ac0161da.jpg)

**Comment by enoch85** [comment]
@kambatx Can you post the code in the setup script please?

**Comment by enoch85** [comment]
@kambatx Or btw, change debug_mode to 1

**Comment by kambatx** [comment]
Thank you for your help, I would not have done that without you. I have the problem solved, it is embarrassing but I have in line 29 if wget -q -T 20 -t 2 http://github.com -O / dev / null the typed if wget -q -T 20 -t 2 Http://github.com -0 / dev / null. Thank you very much

I am working with an Ubuntu server for the first time, which is all new to me. I am spoiled with graphical interfaces from Windows Server :-)

**Comment by enoch85** [comment]
Glad you solved it!
