### ISSUE TITLE
bitwarden_rs docker on nextcloud_vm disappered

### ISSUE THREAD

**Issue by github-cli** [nextcloud/vm#2081]
## Steps to reproduce
not reproducible but the raspberry pi was only rebooted after which bitwarden didnt work anymore, i checked the docker images and it seems there is nor bitwarden_rs nor vaultwarden image
## Expected behavior
bitwarden_rs or vaultwarden starting on boot

## Actual behavior
data folders are still there but no docker

## Server configuration
raspberry pi4 with 4gig ram

**Nextcloud server version:** (see your admin page)
21 but nc still runs fine

**Server OS** (Ubuntu server is default)
ubuntu server

**PHP Version** (e.g. 7.4)

**How did you install the VM?** (Scripted install from master **OR** Released version)
scripted install

## Network
**Do you use DHCP?**
static

**Is port 80 and/or 443 open?**
yes

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshots

should i simply manually install vaultwarden docker and then move the data files?
not sure why it simply disappeared all of a sudden

**Comment by szaimen** [comment]
Hi, thanks for your report! Can you please post the output of `sudo docker ps -a` and `ls -l /var/scripts/bitwarden-conf`? Thank you!

**Comment by szaimen** [comment]
> should i simply manually install vaultwarden docker and then move the data files?

No. If the file `/var/scripts/bitwarden-conf` exists, you should be able to simply install the container again by running `sudo bash /var/scripts/bitwarden-conf`
If not, the easiest way is probably running the vaultwarden script again.

**Comment by github-cli** [comment]
thanks for replying.
The bitwarden-conf does not exist, there is one docker running ark74/nc_fts:latest for full text search which keeps restarting but no vaultwarden or bitwarden.
with running the vaultwarden script, do you mean running menu.sh and selecting vaultwarden for installation? because there is no separate script for vaultwarden in that directory

**Comment by szaimen** [comment]
> do you mean running menu.sh and selecting vaultwarden for installation?

Yes, simply run `sudo bash /var/scripts/menu.sh` -> choose `Additional Apps` -> choose `Bitwarden Menu` -> choose `Vaultwarden` (and reuse the domain that you've already used for bitwarsen rs).

**Comment by github-cli** [comment]
done, and same database is working :)
however... even after this the /var/scripts/bitwarden-conf does not exist!

**Comment by szaimen** [comment]
> done, and same database is working :)

Great, thanks for the confirmation! :)

> however... even after this the /var/scripts/bitwarden-conf does not exist!
Yep, the script doesn't produce this file.
I don't know why the container update failed for you but the update script should have produced the file which it most likely did but failed to move to the correct place. 
See https://github.com/nextcloud/vm/pull/2083 for a fix which will also improve the logging for cases like yours in the future.

**Comment by github-cli** [comment]
great, thanks!
I will close this now as its resolved but open another one as I just removed fulltextsearch because i noticed it does not run on arm64 (only amd64) so its useless and only kept trying to start.... now nextcloud is not reachable anymore
