### ISSUE TITLE
`security.sh` pulls `HEAD` from 3rd party git repository and runs as root

### ISSUE THREAD

**Issue by wallyhall** [nextcloud/vm#2082]
This is a proposed enhancement - for the sake of security.  `security.sh` appears to pull the latest `HEAD` from at least one 3rd party git repository, before running it as `root` (via `cron`).

I'd suggest pinning this to a specific commit - and/or verifying a hash of the script (in case anything inadvertently untoward) slips into the 3rd party git repository.

(Full disclosure: I'm the maintainer of the 3rd party git repository in question!  I have no intention of letting anything bad slipping in - but I am acutely aware of my ability to write buggy code :-))

https://github.com/nextcloud/vm/blob/e6d9133db785ca8fed14a952fbe7fb31b25cc831/addons/security.sh#L74

For the sake of the involved administrative overhead, I'd suggest perhaps pinning to a specific commit?

**Comment by wallyhall** [comment]
All that said - I just realised there is a clear warning at the top of the script:

 > Please run it own your own risk!

If this script isn't being automatically executed (and is left to the discretion of the user), I could agree to close this ticket as "not a concern".

**Comment by enoch85** [comment]
Yes, it's on my TODO to put it in our own REPO, or make an EOF out of it, but for the quick fix sake of it, we use the easy way for now.

Thanks for pointing it out though.

**Comment by enoch85** [comment]
@wallyhall Fix is in #2085
