### ISSUE TITLE
fulltextsearch uninstall on raspberry pi4

### ISSUE THREAD

**Issue by github-cli** [nextcloud/vm#2084]
## Steps to reproduce
1. Install nextcloud_vm on raspberrypi4 with fulltextsearch as additional app
2. uninstall fulltextsearch via menu.sh -> additional apps
3.

## Expected behavior
nextcloud should still work

## Actual behavior
nextcloud website wont open anymore
EDIT: the website wont open in a web browser but the nextcloud app on windows still syncs fine...

## Server configuration
Raspberry Pi4 4GB

**Nextcloud server version:** (see your admin page)
21.0.4

**Server OS** (Ubuntu server is default)
Ubuntu server

**PHP Version** (e.g. 7.4)
7.4.3

**How did you install the VM?** (Scripted install from master **OR** Released version)
scripted install

## Network
**Do you use DHCP?**
no, static ip

**Is port 80 and/or 443 open?**
yes

** NextCloud log file **
https://paste.ubuntu.com/p/Kn4VmWmnHk/

I can post additional logs if required

**Comment by github-cli** [comment]
I ended up installing fulltextsearch again, going into settings and disable all search apps and then uninstalling fulltextsearch again, now it still works.
pity that fts is not available for arm :P
maybe put this as enhancement to auto-disable the apps when uninstalling fulltextsearch?

**Comment by enoch85** [comment]
> maybe put this as enhancement to auto-disable the apps when uninstalling fulltextsearch?

Hmm, all apps should be disbaled by default when you use the menu script to do so. You're saying the apps were still there?

**Comment by enoch85** [comment]
It's already done, I double checked: https://github.com/nextcloud/vm/blob/master/apps/fulltextsearch.sh#L40-L48

**Comment by enoch85** [comment]
Thanks for posting your issue though :)

**Comment by github-cli** [comment]
maybe i didnt explain this well:
1.) I installed fulltextsearch in the original install via the additional apps and also the plugins within nextcloud
2.) months later I noticed that the docker does not even run on arm64 and just keeps restarting
3.) i went into the additional apps menu again to uninstall the fulltextsearch
4.) nexctcloud stopped working or rather the web-ui didnt open anymore
5.) I reinstalled fulltextsearch via the additional apps menu again
6.) nextcloud worked again right after and i went ahead and disabled all apps related to search within nextcloud
7.) I then uninstalled fulltextsearch again via additional apps menu and everything kept working fine

so from this my assumption was that there is an issue the search plugins are there inside nextcloud or maybe even just the fact that it was configured to use elastic search...

thats why I was suggesting to disable whatever is necessary upon uninstall of fulltextsearch automatically so it wont break the whole nextcloud installation

**Comment by enoch85** [comment]
It feels like this is more of a FTS issue than a VM issue. 

What we do is installing what's provided, the core issue I think lays with the actual app, FTS in this case.

**Comment by github-cli** [comment]
yes, most probably an issue with the uninstall routine of the fulltextsearch app I would assume
just wanted to report, for me its fine now :)
