### ISSUE TITLE
install_production_script: spamhaus section / open ports with ufw

### ISSUE THREAD

**Issue by wolframd** [nextcloud/vm#2086]
Hello Daniel,

thank you so much for your magnificent script which runs perfectly alltogether! 

There is one issue with the spamhaus script spamhaus-drop.sh|php|py 
I ran the full installation script on Ubuntu Server 20.04 directly from github. The spamhaus section does not perform, instead I get the following print (had to install pythonpy beforehand): 
/usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working from collections import Iterable.

And I have a suggestion: Perhaps you could give the possibility to open ports with ufw as well - pause the script, perform ufw allow xxx, confirm and continue the script. After installing the plain vanilla UBS 20.04 I enabled ufw and allowed ports 80 and 443, but not all the other ports. That's fine with Adminer, Webmin and so on since you can allow it after the installation, but not with talk, since it will not be installed during the script without open ports. That's no big deal, but it would be a step to a totally perfect (not "only" perfect) script ;-)

Best regards

Wolfram

**Comment by enoch85** [comment]
Sorry, it was the commit i did today that broke it. 

Thanks for your feedback, but but we won't do that. :)

Keep on Nextclouding! :robot:
