### ISSUE TITLE
Nextcloud 22.1.1

### ISSUE THREAD

**Issue by anubis-genix** [nextcloud/vm#2100]
I just have the question, if there will be an update to version 22.1.1 any time soon, since the update to 22.1.0 was skipped?

**Comment by enoch85** [comment]
Yes, we will probably release it soon, like this week. Just need to find the time.

In any case, the VM automatically updates to the latest version during first setup, and there's really no difference between 22.0.0 and 22.1.1 when it comes to how the VM works.
