### ISSUE TITLE
Add option into Nextcloud menu with the following app

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#2102]
I wonder if it makes sense to add the following app as option into the nextcloud menu including automatically backup and running the command:
https://github.com/icewind1991/root_cache_cleaner

**Comment by enoch85** [comment]
Even though it looks nice, I would prefer not to add more dependencies. We've seen it in the past, a lot of unmaintained apps that breaks Nextcloud

**Comment by szaimen** [comment]
My idea was the following flow:
1. show what this options does
2. ask if you want to do this (cancel if no)
3. test if backup is in place (cancel if no)
4. install the app (cancel if it doesn't install correclty)
5. create a backup
6. ask again if you want to do this
7. run the command
8. deinstall the app again (since it is no longer needed)

**Comment by enoch85** [comment]
Sure, you could make it a separate script and put it in like Server Configuration.

**Comment by enoch85** [comment]
Also, please add a warning that it's a very new app, and not tested in larger installations etc etc.

Would also be nice if it had some version checking. Or does the app do that itself? I mean maybe it's compatible for 22, but not for 23 etc.

**Comment by szaimen** [comment]
The app does the version checking on its own during Installation of the app. So i don't need to implement this manually.
