### ISSUE TITLE
Update to 22.1.1 not possible

### ISSUE THREAD

**Issue by malehwi** [nextcloud/vm#2105]
Hello!

I cannot update the VM from 22.0.1 to 22.1.1 with script or with terminal command. The only option is this one. 
![image](https://user-images.githubusercontent.com/78052373/133790917-f3ad6b96-545f-4477-919e-beeb0ad2764c.png)
But I don't want it to update like this. Any solutions?

**Comment by enoch85** [comment]
Check this: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration

**Comment by malehwi** [comment]
Thanks. That did the trick!
