### ISSUE TITLE
Problem with Apache2 during installation

### ISSUE THREAD

**Issue by Bazarov888** [nextcloud/vm#2111]
## Steps to reproduce
1. Install fresh copy of ubuntu server with nextcloud template on hyper-v 9 ver.
2. Start Nextcloud installation script

## Expected behavior
Installation should not interrupt

## Actual behavior
Got an error during installation:
```
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
invoke-rc.d: initscript apache2, action "start" failed.
● apache2.service - The Apache HTTP Server
     Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2021-10-07 11:16:54 UTC; 6ms ago
       Docs: https://httpd.apache.org/docs/2.4/
    Process: 104039 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)

## Network
**Do you use DHCP?** YES

**Is port 80 and/or 443 open?** YES

## Logs / Screenshots

https://0bin.net/paste/r9xvkhis#+rrinm9OKTTAvxuy8dydSOlFlVCE1Rhf93-iTY5xSbO

#### Log file (/var/log/nextcloud/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)

https://0bin.net/paste/-Jr+ICum#9QwPbkuaSnsW5UXUtmFK-ym+hnqQvWenxSyskW8VlxH

#### Screenshots
https://imgur.com/5L6qeOb

**Comment by Bazarov888** [comment]
Yes, of course.
I used ubuntu-20.04.3-live-server-amd64.iso to install it.

**Comment by enoch85** [comment]
I will do a full install later today to see if anything changed, and if I can reproduce it.

**Comment by Bazarov888** [comment]
What iso should i use instead to check the difference?

**Comment by Bazarov888** [comment]
> 
> 
> Seems to me that port 80 already is in use.
> 
> Is this a 100% clean Ubuntu Server?

Port is not used after intstall https://imgur.com/a/Cann8Wb

**Comment by Bazarov888** [comment]
I installed ubuntu with nextcloud template, that`s why it doesn`t work.
Im very sorry, my bad.

**Comment by enoch85** [comment]
Thanks for confirming!
