### ISSUE TITLE
Improve apps re-enabling

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2113]
From this issue: https://github.com/nextcloud/vm/issues/2109

*Instead of modifying the mentioned logic, I'd vote for simplifying it instead after nextcloud/server#29020 is merged, backported and released...*

**Comment by szaimen** [comment]
hm... not seen this yet (at least on my instance) but we'll improve the logic once new Nextcloud releases are out, either way... (which this ticket is about) :)

**Comment by enoch85** [comment]
@szaimen Do you have time for this soon?

I'm free tomorrow morning.
