### ISSUE TITLE
Bitwarden install fails

### ISSUE THREAD

**Issue by TiminRo** [nextcloud/vm#2114]
## Steps to reproduce
1. Using sudo bash /var/scripts/menu.sh to install apps.
2.
3.

## Expected behavior
Tell us what should happen, Bitwarden should be installed.

## Actual behavior
Tell us what happens instead, Bitwarden install fails and no SSL certificate is created.

## Server configuration

**Nextcloud server version:** 22.2.0

**Server OS** Ubuntu server 20.04.3

**PHP Version**  7.4.3

**How did you install the VM?** Scripted install from Released version

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots

Oct 11 13:10:34 (internet adres) bitwarden.sh[34910]: Copyright 2015-2021, 8bit Solutions LLC
Oct 11 13:10:34 (internet adres) bitwarden.sh[34910]: https://bitwarden.com, https://github.com/bitwarden
Oct 11 13:10:34 (internet adres) bitwarden.sh[34910]: ===================================================
Oct 11 13:10:34 (internet adres) bitwarden.sh[34905]: bitwarden.sh version 1.43.0
Oct 11 13:10:34 (internet adres) bitwarden.sh[34915]: Docker version 20.10.9, build c2ea9bc
Oct 11 13:10:35 (internet adres) bitwarden.sh[34949]: docker-compose version 1.25.0, build unknown
Oct 11 13:10:35 (internet adres) bitwarden.sh[34905]: Cannot find a Bitwarden installation at /home/bitwarden/bwdata.
Oct 11 13:10:35 (internet adres) systemd[1]: bitwarden.service: Main process exited, code=exited, status=1/FAILURE
Oct 11 13:10:35 (internet adres) systemd[1]: bitwarden.service: Failed with result 'exit-code'.
Oct 11 13:10:35 (internet adres) systemd[1]: Failed to start Bitwarden.

**Comment by enoch85** [comment]
Found the issue, and it's not us, it's Bitwarden: https://github.com/bitwarden/server/issues/1638

Stopping updates until it's fixed.

**Comment by TiminRo** [comment]
Thanks for the update! The Nextcloud VM, works indeed perfectly fine ;)
