### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by Sviskon** [nextcloud/vm#212]
## Steps to reproduce
1. Download "Ubuntu 16.04 VMDK: Pre-installed Nextcloud (PHP 7)" from https://www.techandme.se/nextcloud-vm/
2. Follow the instructions found on https://www.techandme.se/nextcloud-vm/ (mount using VMware Workstation 12 Player)
3. 

## Expected behaviour
Installation and setup of NExtcloud

## Actual behaviour
The script halts with the error message: "sudo -u www-data /var/www/nextcloud/occ config:system:set mysql.utf8mb4 --type boolean --value=true failed"

## Server configuration

**Server version:** (see your admin page)
11.0.3
**VM version** (master / released version)
VMware® Workstation 12 Player 12.0.1 build-3160714
**Updated from an older installed version or fresh install:**
Fresh install
## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
Yes
#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```"sudo -u www-data /var/www/nextcloud/occ config:system:set mysql.utf8mb4 --type boolean --value=true failed

#### Screenshoots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by enoch85** [comment]
Have you tried extracting the VM again and running the script from start on a newly extracted machine?

**Comment by mawouzo** [comment]
I have exactly the same done and the same error

**Comment by Sviskon** [comment]
Yes. I have tried it three times, each time with the image freshly extracted.

**Comment by mawouzo** [comment]
I did it once more, and I did answered "no" at the keyboard-question, then the install runs until end.

**Comment by enoch85** [comment]
@mawouzo @Sviskon Thanks for reporting this! Can you please try to run the script with debug mode enabled?

1. Extract a fresh VM, delete the old.
2. Mount the VM
3. Login
4. Press `CTRL-C` when you are about to type the sudo password
5. `wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud-startup-script.sh`
6. `sudo nano nextcloud-startup-script.sh`
7. Change `DEBUG=0` to `DEBUG=1`
8. `sudo bash nextcloud-startup-script.sh`
9. Post the whole output with [kopy.io](https://kopy.io/) or [hastebin](https://hastebin.com/) and link it in this issue.

Thanks!

**Comment by Sviskon** [comment]
Ok. Tried it but don't know how to copy the output. Is it a command or do have to do something else? I'm not very good at Linux.

**Comment by enoch85** [comment]
@Sviskon Use putty or some other SSH client, then just mark the text to copy it and paste it in one of the sites I mentioned.

**Comment by enoch85** [comment]
Any update here?

I've tried the VM several times, and also installed it on customers servers, and it works. This must be a temporary error.

**Comment by Sviskon** [comment]
I'm sorry but I haven't had the time to try it once again. Will update when I do.

**Comment by Sviskon** [comment]
Finally managed to do it. Here's the link: https://kopy.io/ghxAk

**Comment by enoch85** [comment]
@Sviskon Sorry, but that doesn't tell me much, I need the whole install log.

**Comment by enoch85** [comment]
I've tried to install several times and it works, so this is not something in the scripts. I'm closing this one. Please re-open if the issue persists with the latest VM (11.0.3).
