### ISSUE TITLE
NcVM: - Sorry but something went wrong. Please report this issue...

### ISSUE THREAD

**Issue by mamama1** [nextcloud/vm#2125]
### Steps To Reproduce

Have my VM

### Expected Result

Working VM

### Actual Result

Got a mail with

Subject: NcVM: <myFQDN> - Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!

Data: sudo -u www-data php /var/www/nextcloud/occ config:app:get theming productName failed

### Additional Context

So far, everything seems to still work, just following the instructions in the mail.

### Build Version

20.0.13

### Environment

By downloading the VM

### Environment Details

Nextcloud VM

Operating System:	Linux 5.4.0-89-generic x86_64
CPU:	Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (2 cores)
Memory:	7.78 GB

**Comment by enoch85** [comment]
Just tested and the code works, must have been a temporary error. Please try to run an manual update.

**Comment by enoch85** [comment]
Thanks I'll have a look!
