### ISSUE TITLE
Update failed - 

### ISSUE THREAD

**Issue by jstampfer** [nextcloud/vm#2126]
### Steps To Reproduce

Execute last update script

### Expected Result

update

### Actual Result

xxx.yyy.zzz: Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ config:app:get theming productName failed

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/57633002/140619554-ec17d718-c6e9-443e-99be-2739d22673bb.png)

### Build Version

22.2

### Environment

By downloading the VM

### Environment Details

Ubuntu 7.3
PostgreSQL 10.18 
php 7.4.16

**Comment by enoch85** [comment]
Just tested and the code works, must have been a temporary error. Please try to run an manual update.

**Comment by enoch85** [comment]
Thanks!

I'll have a look.
