### ISSUE TITLE
TLS Let's Encrypt not working

### ISSUE THREAD

**Issue by JKMoran** [nextcloud/vm#2127]
### Steps To Reproduce

1. Go to wget https://raw.githubusercontent.com/nextcloud/vm/master/lets-encrypt/activate-tls.sh && sudo bash activate-tls.sh
2. Click enter

### Expected Result

Installing certbot (Let's Encrypt).... Successful!

### Actual Result

Unable to connect to snap store.

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/76010768/140985754-33738ba1-8187-43ab-abd6-4693fd0d92ba.png)

![image](https://user-images.githubusercontent.com/76010768/140985822-66d6b4b4-a738-4355-942f-c3a343c2345b.png)

![image](https://user-images.githubusercontent.com/76010768/140985957-4dad0b5d-c6d9-4612-a940-f59cbea9ad5c.png)

### Additional Context

DNS is managed / proxied through CloudFlare, however this has not prevented this from successfully running until the certificate expired.  It has also been set this way since the initial build of the NextCloud server

### Build Version

22.2.0

### Environment

By downloading the VM

### Environment Details

- Custom Hansson IT VM
- VMWare EXSi 7
- Unifi UDM-Pro router

**Comment by JKMoran** [comment]
![image](https://user-images.githubusercontent.com/76010768/140987013-c6c36291-e8c8-495a-8815-00b309429694.png)
 I uninstalled snapd, then ran the script again after I removed the CloudFlare proxy setting.  No change.

**Comment by szaimen** [comment]
Hi @JKMoran this sounds like the snap store was down. Could you please try again and report back? Thanks!

**Comment by JKMoran** [comment]
Hello – thank you, yes I tried this morning and was able to get it to work.  Thank you!

**Comment by szaimen** [comment]
Thanks for confirming
