### ISSUE TITLE
https://ipv4bot.whatismyipaddress.com disabled -> dyndns update fails

### ISSUE THREAD

**Issue by user-51** [nextcloud/vm#2128]
### Steps To Reproduce

Enable automatic dynamic DNS updates via "Server Configuration Menu" -> "DDclient Configuration"

### Expected Result

Dynamic DNS records are updated

### Actual Result

Dynamic DNS records are not updated.
ddclient tries to connect https://ipv4bot.whatismyipaddress.com in order to obtain the public IP address. 
This API has been disabled on Nov. 10 2021 "due to massive abuse"

### Build Version

22

### Environment

By using the scripts

**Comment by enoch85** [comment]
Thanks for your report!

" "due to massive abuse" Hehe, I guess it's all the Nextcloud VM users. :smile: 

I'll check if there's an alternative.

**Comment by enoch85** [comment]
Please test again and see if it works in like 15 minutes.

Thanks once again!
