### ISSUE TITLE
incompatible version after 22.2.3 release

### ISSUE THREAD

**Issue by mokles-remadev** [nextcloud/vm#2138]
### Steps To Reproduce

after running the installation production script the script downloads the latest 22.2.3 version which occurs incompatible version message after startup script so the installation stops

### Expected Result

complete installation and smooth running for the startup script 

### Actual Result

Your current version is still not compatible with the version required to run this script nextcloud !!

### Build Version

22.2.3

### Environment

By using the scripts

### Environment Details

Ubuntu Server 20.04

**Comment by enoch85** [comment]
Hi, that's probably due to that you failed to mount the data drive correctly.

Please give the complete output of the whole error, not only the actual error message.
