### ISSUE TITLE
Collabora instructions out-of-date

### ISSUE THREAD

**Issue by aaaskew** [nextcloud/vm#214]
## Steps to reproduce
1.  Web page https://www.techandme.se/automated-collabora-installation-on-nextcloud/ has link to collabora.sh script that appears to have moved to apps directory

## Expected behaviour
Be able to download and run the script of a Nextcloud VM when initial install did not select this option.

## Actual behaviour
Change wget https://raw.githubusercontent.com/nextcloud/vm/master/static/collabora.sh -P /var/scripts
to
wget https://raw.githubusercontent.com/nextcloud/vm/master/apps/collabora.sh -P /var/scripts
seems to work?

Would you also consider adding a link to an FAQ on the https://www.techandme.se/nextcloud-vm/ web page?  Some points I think need authoritative answers when installing/upgrading:

Q: How to update Nextcloud VM?
A: You can not use the built in updater in Nextcloud GUI due to secure permissions on this VM. Use script...

Q: How to install options if not selected during first install? - Collabora/Nextant/...
A:

Q: How to continue from partially installed system? - You got the FQDN wrong/You put in a bad password/...
A:

Q: Does automatic update update Ubuntu and Nextcloud?
A:

Q: Can I enable-disable automatic update later of OS/Nextcloud?
A:

Q: How to backup?
A: See Nextcloud doc... ?

Q: Can I install in a VM with a NAT and port redirection of port 443 & 10000 & 22?
A: Seems to work for me

I am sure there is a better list but I could not see this sort of thing pointed out from the installation page.

## Server configuration

**Server version:** (see your admin page)
Nextcloud 11.0.3

**VM version** (master / released version)
Nextcloud VM 11.0.3

**Updated from an older installed version or fresh install:**

Fresh install

**Comment by enoch85** [comment]
This is fixed. Thanks for letting us know!
