### ISSUE TITLE
Double importing of lib.sh

### ISSUE THREAD

**Issue by vazhnov** [nextcloud/vm#2145]
### Steps To Reproduce

```
 % grep 'lib.sh' nextcloud_install_production.sh 
# shellcheck source=lib.sh
source <(curl -sL https://raw.githubusercontent.com/nextcloud/vm/master/lib.sh)
# shellcheck source=lib.sh
source <(curl -sL https://raw.githubusercontent.com/nextcloud/vm/master/lib.sh)
# Make sure add-apt-repository exists (needed in lib.sh)
```

### Expected Result

Only one import (`source`):
```
 % grep 'lib.sh' nextcloud_install_production.sh 
# shellcheck source=lib.sh
source <(curl -sL https://raw.githubusercontent.com/nextcloud/vm/master/lib.sh)
# Make sure add-apt-repository exists (needed in lib.sh)
```

### Actual Result

Double importing (`source`) of `lib.sh`.

### Additional Context

Maybe the second import is doing because of no packages (`lshw`, `net-tools`, `whiptail`) on first import. But in this case it is better to add a comment about this.

### Build Version

22.2.3

### Environment

By using the scripts

### Environment Details

- Operating system: Devuan 4 Chimaera
- Hardware: Proxmox LXC container, 1 CPU, 2 GB RAM

**Comment by enoch85** [comment]
Hmm, nice catch!

I see no reason why that should be necessary.

**Comment by vazhnov** [comment]
@enoch85 , thank you for a fix!
