### ISSUE TITLE
Automatic upgrade fails when there are drives mounted via fstab

### ISSUE THREAD

**Issue by k-wax** [nextcloud/vm#2147]
### Steps To Reproduce

Install via the script
mount additional disks to users' home directory
wait for auto-update to start
notice that you are now in recovery console (ctrl-d or enter -prompt)

### Expected Result

Upgrades should go smoothly even with drives mounted

### Actual Result

Upgrade fails and you are dropped to recovery console.
Now you can comment the lines in fstab that mount drives and reboot
System boots successfully and is up-to-date

### Screenshots, Videos, or Pastebins

ubuntu@lts-test:~$ cat /etc/fstab 
LABEL=cloudimg-rootfs   /        ext4   discard,errors=remount-ro       0 1
LABEL=UEFI      /boot/efi       vfat    umask=0077      0 1

UUID=09edb105-62b4-41c3-b2fe-67fbfc9676f7  /home/ubuntu/1hdd  ext4      auto  0  0
UUID=57414942-ae72-4942-9111-08e01a08e27b  /home/ubuntu/2hdd  ext4      auto  0  0

### Build Version

latest

### Environment

By using the scripts

### Environment Details

Host is proxmox 7.1-5, Ubuntu 20.04 LTS guest running nextcloud.

**Comment by enoch85** [comment]
There's no issues at all with mounting extra disks to `/etc/fstab` - if done correctly.

If you feel uncertain you can always google the issue, or get support directly from us.
