### ISSUE TITLE
collabora code not working after container upgrade ?

### ISSUE THREAD

**Issue by mhazan01** [nextcloud/vm#2149]
### Steps To Reproduce

1. Go to your folder
2. Click on any file you want to edit via collabora

### Expected Result

collabora load up the file and editing is avialable

### Actual Result

instead of having the document open an error is displayed, the file is available for download.

Not Found

The requested URL was not found on this server.

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/44583064/143851570-f0c35107-a063-47b1-a1f7-c1c87c384587.png)

### Additional Context

i believe an automated docker container update happened on the 25th and since then the mentioned error happen every time we try to edit a file with collabora. the docker logs don't show any error

### Build Version

22.2.3

### Environment

By downloading the VM

**Comment by mhazan01** [comment]
this was fixed here : https://forum.collaboraonline.com/t/upgrade-from-loolwsd-to-coolwsd-broke-nextcloud-use/742 what a bullshit move

**Comment by enoch85** [comment]
:open_mouth: 

So this means that we need to change the PATH in all our configs? How did you fix it?

**Comment by mhazan01** [comment]
as suggested in this comment https://forum.collaboraonline.com/t/upgrade-from-loolwsd-to-coolwsd-broke-nextcloud-use/742/4 , i edited the apache proxy file for the collabora code. it's easy to do as long as you have sudo acces to the vm

**Comment by enoch85** [comment]
@mhazan01 Thanks!

So like this: https://github.com/nextcloud/vm/pull/2150/files ?

**Comment by mhazan01** [comment]
yes, it's how i've done it.
