### ISSUE TITLE
nextcloud script update error on VM

### ISSUE THREAD

**Issue by marekmsm** [nextcloud/vm#2154]
### Steps To Reproduce

HI Guys, 

i have porblem but i could't find solution at history.
1 .
i used  scrpit sudo bash /var/scripts/update.sh for udpate nextcloud on VM

### Expected Result

will finish update

### Actual Result

1. i got error " sudo -u www-data php /var/www/nextcloud/occ upgrade failed" 
2. nextcloud is at maintenance mode.
3. i couldn't finish update

### Screenshots, Videos, or Pastebins

error 
![image](https://user-images.githubusercontent.com/95365143/144258642-70bc8589-4571-4b33-be36-a9e59d135ab5.png)

### Additional Context

Any idea what i doing worng ? 

### Build Version

20.0.5.2

### Environment

By downloading the VM

### Environment Details

ubuntu/nextcloud Hansson

**Comment by enoch85** [comment]
Hi, thanks for reporting. 

We add an extra step after the apps upgrade just to make sure that everything is updated even if some app needs migration afterwards.

In this case it seems like the Mail app somehow messed up. You could try to deactivate it and run the upgrade again like this:

1. `sudo -i`
2. `nextcloud_occ app:disable mail`
3. `nextcloud_occ upgrade`

**Comment by marekmsm** [comment]
thx, above steps solved my problem.

**Comment by enoch85** [comment]
cc @ChristophWurst FYI

**Comment by ChristophWurst** [comment]
:+1:
