### ISSUE TITLE
Talk TURN server setup behind Reverse Proxy

### ISSUE THREAD

**Issue by meichthys** [nextcloud/vm#2160]
### Steps To Reproduce

I've tried following a number of different tutorials to get a TURN Server setup for my Nextcloud VM instance however since i'm running Nextcloud behind a reverse proxy, i'm having difficulties. My steps i've taken are:

- Setup Nextcloud behind reverse proxy
    - This reverse proxy handles SSL
- Run nextcloud Talk VM Script on nextcloud vm instance
- When prompted, choose to setup TURN server
- Script tries to setup SSL and fails

### Expected Result

I would expect the script to allow setup behind reverse proxy.

### Actual Result

Script seems to fail when checking if ports are open directly to Nextcloud and/or when trying to generate it's own certificates

### Screenshots, Videos, or Pastebins

<img width="668" alt="Screen Shot 2021-12-04 at 2 47 46 PM" src="https://user-images.githubusercontent.com/10717998/144722701-b7f2d201-2fef-468a-884c-be3845393e2f.png">
<img width="673" alt="Screen Shot 2021-12-04 at 2 47 59 PM" src="https://user-images.githubusercontent.com/10717998/144722709-611852db-561e-431e-8d1e-4e64d2e0fb29.png">
:

### Additional Context

I currently have a dynamic public ip address. I use dyndns to update my domain whenever it changes. I have A records on my domain that forward all traffic to my public ip address. My router then forwards all traffic on port 80 and port 443 to nginx (nginxproxymanager) which then redirects the traffic based on subdomains to nextcloud. nextcloud.mydomain.org redirects to the nextcloud instance's ip address. 

### Build Version

22.2.0

### Environment

By using the scripts

### Environment Details

- VM on Proxmox (setup using Nextcloud VM script)

**Comment by meichthys** [comment]
One thing to add to my original report is that I am actually running nextcloud in a lxc container which may be contributing to the failure to install certificates. I'm not sure but wanted to add this in case it helps. 
I do get an error like the following:
```
error: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount:
       /tmp/sanity-mountpoint-824181801: mount failed
```

**Comment by enoch85** [comment]
> system does not fully support snapd:

That's 100% an issue, yes. We use the certbot snap for TLS.

**Comment by meichthys** [comment]
Ok, Thanks. I'll look for an workaround. 
Do you know if there is a way to run the script without fetching certificates? In my case I have my reverse proxy handle all the certs.

Feel free to close this or leave it open as a feature request to add  reverse proxy support to the script.

**Comment by enoch85** [comment]
The VM already supports using a reverse proxy.

You have the building stones, but you have to put them together. Check the already existing configs. If you need help you can buy support.

**Comment by meichthys** [comment]
Ok, Thank you. I have the reverse proxy working, but the signaling server script doesn't work when behind a reverse proxy. For now I've setup a TURN server manually, since I am just evaluating the nextcloud VM- I am looking to set one up in the workplace, but are trying to work out a few issues (mostly nextcloud in general- not the VM/scripts).
Keep up the great work!
