### ISSUE TITLE
Nextcloud Breaking over night

### ISSUE THREAD

**Issue by SP4RT4N3R** [nextcloud/vm#2161]
### Steps To Reproduce

I installed nextcloud via the script.
i just let i run and don't do much with it (mostly accessing it through the client)

### Expected Result

I just have it running

### Actual Result

When i access the nextcloud via the Web, i get shown the error message below instead of the actual nextcloud web interface

### Screenshots, Videos, or Pastebins

[error.txt](https://github.com/nextcloud/vm/files/7655873/error.txt)

### Build Version

22.2.0

### Environment

By using the scripts

### Environment Details

ubuntu lxc container on proxmox
core i7 6700
4GB RAM
php 7.4.26

**Comment by enoch85** [comment]
Thanks for reporting!

Have you tried rebooting it?

To me it seems highly unlikely that *nothing* changed and it's now broken.

**Comment by SP4RT4N3R** [comment]
> Thanks for reporting!
> 
> Have you tried rebooting it?
> 
> To me it seems highly unlikely that _nothing_ changed and it's now broken.

yes i rebooted, 
it happened to me twice now.  luckily i have a snapshot and backups i can restore it to, but it happened again after a few days

**Comment by enoch85** [comment]
Can you provide any logs?

- Apache
- PHP-FPM
- Nextcloud

**Comment by enoch85** [comment]
Also, how is your network share mounted?

**Comment by SP4RT4N3R** [comment]
> Also, how is your network share mounted?

it is mounted with the external storage app and smb

**Comment by SP4RT4N3R** [comment]
after restoring the nextcloud from a snapshot, i just ran the updatescript, now its broken again.
[apache-error.log](https://github.com/nextcloud/vm/files/7656084/apache-error.log)
[php-fpm-error.log](https://github.com/nextcloud/vm/files/7656087/php-fpm-error.log)
[nextcloud.log](https://github.com/nextcloud/vm/files/7656097/nextcloud.log)

**Comment by enoch85** [comment]
Are you updating to which version?

Where does it break? Can you post a screenshot?

**Comment by enoch85** [comment]
OK, so the Apache log, I have no clue where this comes from?

```
cat: /sys/class/net/bonding_masters/operstate: Not a directory
cat: /sys/class/net/bonding_masters/speed: Not a directory
cat: /sys/class/net/bonding_masters/duplex: Not a directory
```

From the Nextcloud log it seems like you have some apps enabled that arent' supported.

Disable / remove:
- integration_whiteboard

Please try to upgrade to the minor version of your release by:
`sudo bash /var/scripts/menu.sh`
Then choose Update Nextcloud minor.

**Comment by SP4RT4N3R** [comment]
Thanks for your help, the issue was fully resolved.
The Problem was with an attempted upgrade to php8, that was rolled back, but still interfered with parts of the script.
Thanks for your help, appreciate the effort.
