### ISSUE TITLE
How to update domain name safely

### ISSUE THREAD

**Issue by xegulon** [nextcloud/vm#2162]
**Is your feature request related to a problem? Please describe.**
I have setup a nextcloud vm on a VPS with some domain name, I would like to update the domain name.

**Describe the solution you'd like**
Either instructions to show me how to change the domain name, either a script to do this automatically.

**Describe alternatives you've considered**
Relaunching the setup script, but I fear losing files and/or configuration.

**Additional context**
Thanks a lot for the amazing script!

**Comment by enoch85** [comment]
If you want a new domain name, then just run the script again.

`sudo bash /var/scripts/menu.sh` --> Server Configuration --> Activate TLS :smiley:

**Comment by xegulon** [comment]
Hi, thanks for the answer. That won't break or change my previous configurations?

**Comment by enoch85** [comment]
>  Is it safe to try?

Make a snapshot first so that you can revert easy if it would go wrong. :+1:
