### ISSUE TITLE
Selection to run NC "native" or as docker

### ISSUE THREAD

**Issue by github-cli** [nextcloud/vm#2164]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
No problem, I just know how easy this is to use on VMs and even on raspi... (with this I mean the current script)
It would be cool to have the same if no native nor VM install is wanted

**Describe the solution you'd like**
As many things already get installed as dockers, it would be nice to be able to choose to go "all docker" and even install nextcloud inside a docker with all thats needed (e.g. smb-client, etc.)

I used to run this script on a VM but the server got too hot in the house during the summer. I moved to a raspi but am missing things like elasticsearch and even more "oomph". Now I have a laptop cpu in a miniPC but want to keep it as server and install all things possible as docker.

**Describe alternatives you've considered**
alternative is to do it all manually, which might be the way I will go in the meantime as even if this gets accepted, it will probably take a while to do (actually I dont think it will be accepted but I wanted to throw the idea into the ideas hat).

**Additional context**
I only had this idea because the VM script always made things so easy for me and currently setting up nextcloud as docker with all features is not a ready-to-go solution (there are solutions for basic functionality, just nextcloud with a database and not even smb support but thats it).

**Comment by enoch85** [comment]
Hi,
Thanks for posting!

> and even on raspi...

You can install without any issues at all on Raspberry Pi 4, just use the Ubuntu Server image crafted for RPi 4.

> As many things already get installed as dockers, it would be nice to be able to choose to go "all docker"
Check this out: https://hub.docker.com/_/nextcloud

> I only had this idea because the VM script always made things so easy for me and currently setting up nextcloud as docker with all features is not a ready-to-go solution (there are solutions for basic functionality, just nextcloud with a database and not even smb support but thats it).

Well, we try to make it as easy as possible. Hansson IT's tag line is: "With Simplicity in Mind". :) 

Thank you for being a valued user!

**Comment by github-cli** [comment]
Hi,

> You can install without any issues at all on Raspberry Pi 4, just use the Ubuntu Server image crafted for RPi 4.
exactly what I was trying to say, works even nicely on RasPi4 :)

> Check this out: https://hub.docker.com/_/nextcloud
I did but this is simply the official nextcloud docker, afaik it offers no smb out of the box nor the option to integrate talk with turnserver, elasticsearch, etc.
It will just install nextcloud with either external or built-in db
Now to have that combined with what you already offer would be pretty cool

**Comment by enoch85** [comment]
It's nothing we will work on. We produce the VM with all the "nitty gritty" stuff that comes with it.

We will likely never convert it into Docker. We don't want to re-invent the wheel.

**Comment by enoch85** [comment]
With that said, have a look at this: https://github.com/nextcloud/vm/tree/master/migrate/docker

If you want to, you can be made responsible for that part of the scripts. Make it work 100% and make the world a better place. :)
