### ISSUE TITLE
failed to install by script

### ISSUE THREAD

**Issue by Evro1979** [nextcloud/vm#2165]
### Steps To Reproduce

o the database: An exception occurred in the driver: SQLSTATE[08006] [7] FATAL:  password authentication failed for user \"ncadmin\"\nFATAL:  password authentication failed for user \"ncadmin\""}}
PostgreSQL username and/or password not valid
 -> You need to enter details of an existing account.
Trace: #0 /var/www/nextcloud/lib/private/Setup.php(354): OC\Setup\PostgreSQL->setupDatabase()
#1 /var/www/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()
#2 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#7 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#8 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#9 {main}

Previous: Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "ncadmin"
FATAL:  password authentication failed for user "ncadmin"
Trace: #0 /var/www/nextcloud/lib/private/Setup/PostgreSQL.php(99): OC\DB\Connection->connect()
#1 /var/www/nextcloud/lib/private/Setup.php(354): OC\Setup\PostgreSQL->setupDatabase()
#2 /var/www/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()
#3 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#7 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#8 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#9 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#10 {main}
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=ncadmin --database-pass=qRtrtm6pKGA@RPiEXSdYDuMUoB --admin-user=ncadmin --admin-pass=nextcloud failed
Nextcloud is not installed - only a limited number of commands are available

### Expected Result

success

### Actual Result

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=ncadmin --database-pass=qRtrtm6pKGA@RPiEXSdYDuMUoB --admin-user=ncadmin --admin-pass=nextcloud failed
Nextcloud is not installed - only a limited number of commands are available

### Build Version

23

### Environment

By using the scripts

### Environment Details

Ubuntu server lts 20.04.3

**Comment by enoch85** [comment]
Hi,

Thanks for reporting!

Can you please elaborate? It works during my testing. 

Please keep in mind that it needs to be a clean Ubuntu 20.04 server with working internet and all that.

**Comment by enoch85** [comment]
Just installed 3 servers, no issues.

**Comment by Evro1979** [comment]
> Hi,
> 
> Thanks for reporting!
> 
> Can you please elaborate? It works during my testing.
> 
> Please keep in mind that it needs to be a clean Ubuntu 20.04 server with working internet and all that.

Yep. 

Found out that when installing on pure Ubuntu , it passed to postgresql , sign that cluster isnt started (its ok i suppose) pub process is running . after script downloading nextcloud-23 and trying to install. but int postgresql no database and role was created, so it fails. tried in different ways (added user ncadmin/nextcloud, tried ncadmin with custom pass , other sudo users.. doest matter. it's looks like some string either absent either just didnt work (create role and bd ) . Its indepent of ncadmin user pass I got this error message:

**_Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=ncadmin --database-pass=s6NSNQHvv2JXdfEMUkekkaqw5# --admin-user=ncadmin --admin-pass=nextcloud failed_**
