### ISSUE TITLE
Lets Encrypt failed authorization procedure

### ISSUE THREAD

**Issue by juliuszatroch** [nextcloud/vm#217]
## Steps to reproduce
1. Nextcloud 11 under HYPER-V installation
2.
3.

## Expected behaviour
Lets Encrypt should authorise address for SSL certificate

## Actual behaviour
Failed to connect to 84.16.38.69     cloud.trynet.sk
DNS record is set correctly, NAT translation for port 80 and 443 is working
https://cloud.trynet.sk

## Server configuration
Windows Server 2008 R2 Hyper-V
**Server version:** (see your admin page)

**VM version** (master / released version)

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?**
Yes, but static reservation to local IP: 10.100.100.22
**Is port 80 and/or 443 open?**
Yes, and translated correctly to local IP: 10.100.100.22
#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
I can't reach your IP nor your domain. This is probably a firewall issue. Have you checked that it's reachable from outside, e.g. from an online Proxy?

**Comment by juliuszatroch** [comment]
Thanks for your cooperation.


NAT is OK.


Its working from SK, CZ, DE.


From some online Proxy its working but from some of them not.
https://nl.hideproxy.me/      -  not working
https://server7.kproxy.com   -  working
https://server1.kproxy.com/  -  not working


Maybe some DNS issue, I will wait 24hours to flush all DNS caches.



best regards

Julius Zatroch

TRYNET s.r.o.
Francisciho 20A

05801 POPRAD
tel: +421905905413
www.trynet.sk





 Odosielateľ:   Daniel Hansson <notifications@github.com> 
 Komu:   nextcloud/vm <vm@noreply.github.com> 
 Cc:   juliuszatroch <zatroch@trynet.sk>, Author <author@noreply.github.com> 
 Odoslané:   10.5.2017 19:14 
 Subjekt:   Re: [nextcloud/vm] Lets Encrypt failed authorization procedure (#217) 


I can't reach your IP nor your domain. This is probably a firewall issue. Have you checked that it's reachable from outside, e.g. from an online Proxy?

**Comment by enoch85** [comment]
> Maybe some DNS issue, I will wait 24hours to flush all DNS caches.

Yes, most probably a DNS issue

**Comment by enoch85** [comment]
I've tried it myself several times and it works, so this is not something in the scripts. Closing.

**Comment by juliuszatroch** [comment]
Finally we have found it, it was GeoIP filtering in firewall.
Do you know where are Lets Encrypt servers located? Only in USA?


best regards

Julius Zatroch

TRYNET s.r.o.
Francisciho 20A

05801 POPRAD
tel: +421905905413
www.trynet.sk





 Odosielateľ:   Daniel Hansson <notifications@github.com> 
 Komu:   nextcloud/vm <vm@noreply.github.com> 
 Cc:   juliuszatroch <zatroch@trynet.sk>, Author <author@noreply.github.com> 
 Odoslané:   16.5.2017 20:33 
 Subjekt:   Re: [nextcloud/vm] Lets Encrypt failed authorization procedure (#217) 


I've tried it myself several times and it works, so this is not something in the scripts. Closing.

**Comment by enoch85** [comment]
Ok great! No clue to be honest.
