### ISSUE TITLE
(Hansson IT Nextcloud VM Full) Nextcloud fails to load after enabling facial recognition

### ISSUE THREAD

**Issue by Mecallie** [nextcloud/vm#2170]
### Steps To Reproduce

Ok, here's what I did:

On initial install I got an error when installing facial recognition, stating it was not yet available for this version of NC.

So I ran it again today:
Run /var/scripts/menu.sh choose install additional apps and then facial recognition.

No errors, installed fine. I saw a bunch of PHP dependencies flashing by.

Afterwards I noticed that under the app settings no "method" or something was installed and no scan was run yet. So I decided to restart the appliance. After that I have no more Nextcloud. The site fails to load at all.

Apache logs found below.

So I tried to uninstall the plugin to see if that resolves the issue. But I get the following error message:
` Your current version is still not compatible with the version required to run this script.     │
                                                                             │                                                                                                │
                                                                             │ To upgrade between major versions, please check this out:                                      │
                                                                             │ https://shop.hanssonit.se/product/upgrade-between-major-owncloud-nextcloud-versions/  `

I am guessing this is because it wants to check the NC version using `sudo -u www-data php /var/www/nextcloud/occ -V` which fails because Apache is dead.

### Expected Result

A working and installed facial recognition app.
A working Nextcloud instance.
Or a way to roll back the changes if it did not succeed. 

### Actual Result

Facial recogntion app not installed properly.
Nextcloud no longer working.
No way to roll back (using menu.sh).

### Additional Context

Apache2 log:
`[Fri Dec 24 13:34:19.223425 2021] [access_compat:error] [pid 1863981:tid 139657243760384] [client 192.168.1.1:62266] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Fri Dec 24 13:34:19.223539 2021] [proxy:error] [pid 1863981:tid 139657243760384] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.4-fpm.nextcloud.sock (*) failed
[Fri Dec 24 13:34:19.223548 2021] [proxy_fcgi:error] [pid 1863981:tid 139657243760384] [client 192.168.1.1:62266] AH01079: failed to make connection to backend: httpd-UDS
[Fri Dec 24 13:34:21.270238 2021] [access_compat:error] [pid 1863981:tid 139657243760384] [client 192.168.1.1:62266] AH01797: client denied by server configuration: /var/www/nextcloud/apps/facerecognition/process
[Fri Dec 24 13:34:21.270317 2021] [access_compat:error] [pid 1863981:tid 139657243760384] [client 192.168.1.1:62266] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Fri Dec 24 13:34:21.270433 2021] [proxy:error] [pid 1863981:tid 139657243760384] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.4-fpm.nextcloud.sock (*) failed
[Fri Dec 24 13:34:21.270442 2021] [proxy_fcgi:error] [pid 1863981:tid 139657243760384] [client 192.168.1.1:62266] AH01079: failed to make connection to backend: httpd-UDS
[Fri Dec 24 13:34:25.635092 2021] [core:warn] [pid 1320:tid 139657344117824] AH00045: child process 1863980 still did not exit, sending a SIGTERM
[Fri Dec 24 13:34:25.909549 2021] [core:warn] [pid 1320:tid 139657344117824] AH00045: child process 1863981 still did not exit, sending a SIGTERM
[Fri Dec 24 13:34:26.976193 2021] [mpm_event:notice] [pid 1320:tid 139657344117824] AH00491: caught SIGTERM, shutting down`

### Build Version

23.0.0

### Environment

By downloading the VM

**Comment by Mecallie** [comment]
Ok, for some reason another reboot fixed the apache issues! (Whoot, make a snapshot next time!)

The error I get for facial recognition is "Current model: Not installed" under "Configuration Information". So that is still not working. I could remove it now, so I went ahead and did that.

**Comment by enoch85** [comment]
@szaimen, your creation. ;)

**Comment by szaimen** [comment]
Hello, I will have a look at this tomorrow and will try to reproduce this issue.

**Comment by szaimen** [comment]
I tried to reproduce the reported issue but only succeeded reproducing this: `Afterwards I noticed that under the app settings no "method" or something was installed and no scan was run yet.`. 
This will be fixed with #2173.
