### ISSUE TITLE
Bug au script de demarrage de la VM HYPER-V pour WEBMIN et FACE RECOGNITION

### ISSUE THREAD

**Issue by scal68** [nextcloud/vm#2171]
### Steps To Reproduce

Lancement du script en exécutant la solution #2163 

erreur Face recognition:
la version de nexcloud ne support pas face recognition.

bug webmin:
impossible d'atteindre la page web.

### Expected Result

Une VM sans erreurs

### Actual Result

pas webmin sans installation manuelle
impossible de faire fonctionner facerecognition.
si je relance le script pour facerecognytion, même problème que #2170

### Build Version

telechargé ce jour

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Should be fixed in now with latest commit.

Thanks for posting!
