### ISSUE TITLE
Collabora not loading documents after fresh install of NC23

### ISSUE THREAD

**Issue by Mecallie** [nextcloud/vm#2172]
### Steps To Reproduce

After a fresh install try to open any supported document in Collabora online.

### Expected Result

The document should be opened in Collabora online

### Actual Result

Download window for file.

### Build Version

23.0.0

### Environment

By downloading the VM

### Environment Details

Latest VM.

I have also found a simple workaround in this thread: https://help.nextcloud.com/t/psa-how-to-get-collabora-working-on-nextcloud-23/128511/37 .

If you change the setup from "Built in Code Server" to "Use you own server" and leave the pre-filled url as is it wil automagically switch back to the "Built in Code Server", but documents then will open in Collabora.

**Comment by enoch85** [comment]
Hi, please read through old issues before you post. https://github.com/nextcloud/vm/issues/2149

Thanks! :)
