### ISSUE TITLE
Daily Backup Wizard

### ISSUE THREAD

**Issue by TiminRo** [nextcloud/vm#2175]
### Steps To Reproduce

1. Go to Daily Backup Wizard and following the steps. Everything seems correctly installed and configured, When doing the first backup everything is fine till  Borgbackup is Testing how full the snapshot is and the backup gets corrupted because the snapshot is full. 

### Expected Result

Make a complete backup.

### Actual Result

 Daily backup failed! The backup archive was corrupt because the snapshot is full and has been deleted.
[0;91mDaily backup failed! The backup archive was corrupt because the snapshot is full and has been deleted.[0m

### Screenshots, Videos, or Pastebins

https://0bin.net/paste/QsP02fQB#j50i2g7OFrNRpOYZErHCXU-70ABcWwdTDnEmQGFtUuT

### Build Version

Nextcloud 22.2.3

### Environment

By using the scripts

### Environment Details

20.04.3 LTS
PHP 7.4.3
AMD Ryzen 7 4700U with Radeon Graphics (8 cores)

**Comment by enoch85** [comment]
@szaimen

**Comment by szaimen** [comment]
Hello @TiminRo, thanks for your bugreport!

It will be fixed with #2176
