### ISSUE TITLE
VirtualBox VBOX_E_FILE_ERROR (0x80BB0004)

### ISSUE THREAD

**Issue by BenediktOppitz** [nextcloud/vm#2181]
### Steps To Reproduce

1. Import 2TB hansson.it OVA into Oracle Virtual Box (Version 6.1.30 which is the latest)
2. Import fails with the error in appended Screenshot

I know Virtual box is not recommenden, but I tryed it out, as the install in VMWare was not successfull, as I am also affected by https://github.com/nextcloud/vm/issues/2163

### Expected Result

VM is imported

### Actual Result

Error occurs with message as shown in the screenshot.

### Screenshots, Videos, or Pastebins

<img width="1015" alt="VortualBox fail" src="https://user-images.githubusercontent.com/97385170/148678199-82f3a39e-2814-4802-9eb9-493e452c0f92.png">

### Build Version

22.2.2 or 23.0.0
Regarding the build version I am not sure. Date of purchase was 26th November 2021 so it should be 22.2.2 but download was on 4th December so could also be 23.0.0

### Environment

By downloading the VM

### Environment Details

Prozessor	Intel(R) Core(TM) i3-6100T CPU @ 3.20GHz   3.19 GHz
Installierter RAM	16,0 GB (15,9 GB verwendbar)
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Edition	Windows 10 Pro
Version	21H2
Installiert am	‎01.‎12.‎2021

Oracle Virtual Box (Version 6.1.30 which is the latest)

**Comment by enoch85** [comment]
It seems to me like the file is corrupted. It can happen if your WAN is laggy and the transfer isn't perfect.

Try to download it again, and extract it. Then see if it helps. If not, try the latest version of VirtualBox. If that doesn't work, revert to VMware.

**Comment by enoch85** [comment]
Any resolution yet?

**Comment by BenediktOppitz** [comment]
As the download option closed a month ago I was not able to reproduce. Along with that, I do not intend to use Virtual Box and am still waiting for the mentioned fix to run my Nextcloud clean with 23.0.1. 
It was just something that I noticed while trying to avoid the installation problem.

**Comment by enoch85** [comment]
Ok, I'll go ahead and close this since it's nothing we recommend anyway.
