### ISSUE TITLE
Issue: 💣💥 Bug Report: Spelling Mistake / Typo 

### ISSUE THREAD

**Issue by I-Cat** [nextcloud/vm#2182]
### Steps To Reproduce

go to https://www.hanssonit.se/nextcloud-vm/
on  the line    1.

spelling mistake/typo  = VHDx should be VHDX

Thanks
I-Cat

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/68921721/148817388-8de1b34b-fa9b-4702-9a1f-6d0a3ce9eb90.png)

Assignees:
@szaimen

**Comment by enoch85** [comment]
Thanks!
