### ISSUE TITLE
Change diskspace script to custom percentage or fixed GB

### ISSUE THREAD

**Issue by Mecallie** [nextcloud/vm#2184]
I am using the Nextcloud VM with a ~4TB drive.

The diskspace scripts deleting the snapshots and the recycle bin kick in at 70 and 90%. Because of this I effectively have no trashbin even though I still have over 150GB of space available on the data drive.

It would be great if I could set a custom percentage for these scripts or just a fixed number of GB's.

**Comment by enoch85** [comment]
Thanks for your suggestion.

Get a large disk ;) Just having 150 GB left on a 4 TB drive isn't good at all for ZFS anyway. One thing you could do is to disable the snapshotting altogether. That would save you some space at least.

1. Prune all the snapshots
2. Remove zfs-autosnapshot

Hope it helps!

**Comment by enoch85** [comment]
This is nothing we will change as per default. If you want to make custom changes, please edit your own scripts.

You could download nextcloud_update.sh and edit the check there, then always use that script to update. Of course, downloading the latest version from time to time would be a good thing to do.
