### ISSUE TITLE
System does not boot (Login with 

### ISSUE THREAD

**Issue by 19newbie87** [nextcloud/vm#2189]
### Steps To Reproduce

1. Start virtual Maschine (Hyper -V9, Gen 2 - WIN1020H2).
2. Press Enter at the following Screen 

![image](https://user-images.githubusercontent.com/97949340/150024352-ddc6f495-4786-448d-85e4-39b23d4c36e2.png)

### Expected Result

Start the Server

### Actual Result

pressing enter  to start "ubuntu"  resulted in a black screen (nothing happend, i wait 1 hour.... i reproduced that error three times).

### Additional Context

A) If i choose advanced options for ubuntu and start "Linux 5.11.0-1022" then the server will start and work fine.

![image](https://user-images.githubusercontent.com/97949340/150024936-f5d9d8f4-a45a-4f53-89a1-629cbec84245.png)
![image](https://user-images.githubusercontent.com/97949340/150089573-d441ef4b-b631-4930-a2b3-ac339c15fb3e.png)

B) By choosing the first option (Linux 5.11.0-1024) i will get the following screen but nothing happened (i wait also more than 1 hour):

![image](https://user-images.githubusercontent.com/97949340/150026755-b35ef11e-0979-4058-bf11-67fb1958e171.png)

C) Sometimes I got the following Screen and nothing happend (I need some restarts to get the Gnub Boot Screen). 

![image](https://user-images.githubusercontent.com/97949340/150027173-47d4649a-dde2-409e-be4f-88ab3c777012.png)

D) the installation was successfull and  If the server is runnig i can only connect via IP but I cannot connect with the Webmin or Adminer URL by using Port 10000 or 9443. I deactivated all firewalls (Server-PC and my second PC on network) und opened the Ports at my Router. Now way.

### Build Version

23.0.0

### Environment

By downloading the VM

### Environment Details

Intel I3 540, 16Gb Ram (Hyper-V 4GB Ram)
(SHUTTLE SH55J PC)

**Comment by enoch85** [comment]
Something went wrong during the first setup. Since one of the kernels work it tells me that the installation/upgrade of the kernel didn't succeed.

Please try again.
