### ISSUE TITLE
Collabora root URL shows index of empty directory

### ISSUE THREAD

**Issue by aaaskew** [nextcloud/vm#219]
If installing Nextcloud VM with Collabora included then going to the Collabora root URL shows an empty directory without needing to authenticate.  Should this not be disabled for better security?

## Steps to reproduce
1. Install Nextcloud VM with Collabora
2. Open https://collabora.domain.com/ URL
3. Server responds with empty directory listing and Apache server version and OS.

## Expected behaviour
The root URL of the Collabora domain should not respond or at least not show directory information?

## Actual behaviour
A page like index.html is displayed

## Server configuration

**Server version:**

Nextcloud 11.0.3 (stable)
PHP 7.0.15
mysql 5.7.18

**VM version** (master / released version)

Nextcloud 11.0.3 VM

## Network
**Do you use DHCP?**

No

**Is port 80 and/or 443 open?**

Only port 443

## Logs / Screenshots

N/A

#### Log file (/var/ncdata/nextcloud.log)

N/A

#### Installation log (command output)

N/A

#### Screenshoots

N/A

**Comment by enoch85** [comment]
This is the default behavior as there really are no content, the domain is just for redirecton of the Docker image. 

@LukasReschke What do you think regarding security?

**Comment by enoch85** [comment]
Anyway, it should be possible to disallow directory index with `Indexes` in Apache.

@aaaskew Please try to add this in your collabora.domain.conf file and restart Apache:
```
<Directory .>
Options -Indexes
</Directory>
```

You can also try different varieties instead of `.` you can use `/` and `/var/www/`

**Comment by enoch85** [comment]
@aaaskew Did you try to add it to the conf? --^

**Comment by aaaskew** [comment]
I have tried with . and / and /var/www  The only one that seems to work correctly is the last, added in a directory section at the bottom of the collaborative virtual server configuration file.

**Comment by enoch85** [comment]
@aaaskew Ok, great. Nothing else is affected because of the change? You can still use Collabora as normal?
