### ISSUE TITLE
Installation with the scripts ends with an error

### ISSUE THREAD

**Issue by im-evko** [nextcloud/vm#2190]
### Steps To Reproduce

1. Install ubuntu 20.04. 
2. upgrade to the latest version.
3 Give the command wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
4. Give the command sudo bash nextcloud_install_production.sh

### Expected Result

should be a clean install - but it is not

### Actual Result

PostgreSQL username and/or password not valid
 -> You need to enter details of an existing account.
Trace: #0 /var/www/nextcloud/lib/private/Setup.php(354): OC\Setup\PostgreSQL->setupDatabase()
#1 /var/www/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()
#2 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()
#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#7 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#8 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#9 {main}

Previous: Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "ncadmin"
FATAL:  password authentication failed for user "ncadmin"
Trace: #0 /var/www/nextcloud/lib/private/Setup/PostgreSQL.php(99): OC\DB\Connection->connect()
#1 /var/www/nextcloud/lib/private/Setup.php(354): OC\Setup\PostgreSQL->setupDatabase()
#2 /var/www/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()
#3 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()
#4 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#7 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#8 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
#9 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#10 {main}
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=ncadmin --database-pass=***********************  --admin-user=ncadmin --admin-pass=nextcloud failed
Nextcloud is not installed - only a limited number of commands are available

### Build Version

cannot tell - downloaded it today

### Environment

By using the scripts

### Environment Details

Esxi 6.7.0 Update 3 (Build 17167734)

**Comment by enoch85** [comment]
Thanks!

I'll have a look at it.

**Comment by enoch85** [comment]
Just made a fresh install with the scripts and everything works as expected.

**Comment by im-evko** [comment]
> Just made a fresh install with the scripts and everything works as expected.
Yes, indeed. I tried several times to install on the updated ubuntu 20.04.1. Then I reinstalled the virtual machine at once with 20.04.3 and everything installed immediately.
 Sorry for the inconvenience.
