### ISSUE TITLE
Webmin server not reachable because of outdated certificate

### ISSUE THREAD

**Issue by amcadnan** [nextcloud/vm#2191]
### Steps To Reproduce

During the installation of Nextcloud VM:
- Installation of Webmin: Error, server isn't reachable.

### Expected Result

http://webmin.com/jcameron-key.asc should be reachable for downloading.

### Actual Result

Installation is hangig, because the Webmin server isn't reachable and the installatioin can't be continued. When you opet the address over an browser, you'll notice that the server certificate is outdated since yesterday.

### Build Version

SKU:125 because i didn't see any build version on your webpage

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Hi, 

It's a known error, please reinstall Webmin with the menu script and it should be sorted.

**Comment by enoch85** [comment]
Aah, I can see now the cert isn't trusted. Webmin gaaah, happened before. I'm not sure how long it's gonna take, but I'd suggest to report this upstream.

**Comment by enoch85** [comment]
Can you try if this key works? https://gist.githubusercontent.com/enoch85/092c8f4c4f5127b99d40/raw/186333393163b7e0d50c8d3b25cae4d63ac78b22/jcameron-key.asc

**Comment by amcadnan** [comment]
Hi

Yes, that's fine, cert is valid.

**Comment by enoch85** [comment]
OK great, will make a temp fix fir this.

**Comment by amcadnan** [comment]
Ok, thanks for your effort and best.. :)

**Comment by enoch85** [comment]
Please try again

**Comment by amcadnan** [comment]
I'll do, but i have to start from the scratch, because the max trying limit from 10 times was reached.. So i had to delete the vm and import it again.. Will provide an feedback as sonn as i get to the Webmin installation.

**Comment by amcadnan** [comment]
Hi there

It's working now, Webmin installation was successfull, many thanks again for your effort and have a good time..

Best

**Comment by enoch85** [comment]
Great! Thanks for confirming!
