### ISSUE TITLE
Plex Media Server 

### ISSUE THREAD

**Issue by TiminRo** [nextcloud/vm#2192]
### Steps To Reproduce

1. Go to 'sudo bash /var/scripts/not-supported.sh'
2. Click on 'Plex Media Server install'
3. Scroll trough the menu and accept that hardware transcoding is not available(AMD)

### Expected Result

Install Plex Without Hardware Transcoding. 

### Actual Result

Plex setup startup from http://$ADDRESS:32400/web is not working. 

### Screenshots, Videos, or Pastebins

docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.

### Additional Context

The script msg_box: PLEX Media Server was successfully installed.

### Build Version

Nextcloud 22.2.3

### Environment

By using the scripts

### Environment Details

20.04.3 LTS
PHP 7.4.3
AMD Ryzen 7 4700U with Radeon Graphics (8 cores)

**Comment by szaimen** [comment]
Hello @TiminRo this should be fixed. Please try again and report back if it works. Thanks! :)

**Comment by TiminRo** [comment]
Hello Szaimen, I'll get the following message: 

Running the Not-supported Menu script...
Testing if network is OK...
Checking connection...
Downloading the PLEX Media Server script...
dpkg-query: geen pakketten gevonden die overeenkomen met plexmediaserver
Installing PLEX Media Server...
Getting Plex Media Server...
Using default tag: latest
latest: Pulling from plexinc/pms-docker
Digest: sha256:480f8b27b4af59b8f635e6a60d6d2519984b63a63a5b2883a33701e08054b0a8
Status: Image is up to date for plexinc/pms-docker:latest
docker.io/plexinc/pms-docker:latest
Installing Plex Media Server...
docker: invalid reference format.
See 'docker run --help'.

Still not working.

**Comment by szaimen** [comment]
Hi @TiminRo thanks for your report. Seems like I should have tested this but I was very sure that #2193 would fix it. Please try `curl https://raw.githubusercontent.com/nextcloud/vm/enh/fix-plex-attempt-2/not-supported/plexmediaserver.sh | sudo bash plexmediaserver.sh` and report back. Thanks! :)

**Comment by TiminRo** [comment]
Hello @szaimen It works!. Thanks! Great Nextcloud-NAS-Guide did you make, everything works now! :)

**Comment by szaimen** [comment]
> Hello @szaimen It works!. Thanks! Great Nextcloud-NAS-Guide did you make, everything works now! :)

Thats great to hear, thanks! :)
