### ISSUE TITLE
Bug in adminer.sh

### ISSUE THREAD

**Issue by xPedion** [nextcloud/vm#2195]
### Steps To Reproduce

1. New install using Nextcloud VM Pre-installed OVA Image
2. Install Adminer

### Expected Result

Working Adminer

### Actual Result

503 service unavailable

### Additional Context

In adminer.sh line 101
`        SetHandler "proxy:unix:/run/php/$PHPVER-fpm.nextcloud.sock|fcgi://localhost"`
should be 
`        SetHandler "proxy:unix:/run/php/php$PHPVER-fpm.nextcloud.sock|fcgi://localhost"`

### Build Version

22.2.3

### Environment

By downloading the VM

**Comment by szaimen** [comment]
hm... looks like a bug to me, too. I wonder why that didn't pop up earlier...
@xPedion do you mind opening a PR with that change? Thanks for your effort! :)

**Comment by xPedion** [comment]
No problem, thanks for providing the code 👍
