### ISSUE TITLE
nextcloud: cannot import 'ncdata' : no such pool available

### ISSUE THREAD

**Issue by herrschlupp** [nextcloud/vm#2196]
### Steps To Reproduce

I wan't to move the ncdate store from the 1TB virtual disk to a zfs truenas storage.
For that a mounted  this new point to /mnt/ncdata_truenas and copyed the files from the old storage to the new one and let build nextcloud a new index.
After that I deleted the 1TB virt. disk from vmware.

Nextcloud is working but I get the issue <cannot import 'ncdata' : no such pool available> always when I log as root.
I don't know why and I don't find anythink about that at google.

### Expected Result

*

### Actual Result

*

### Screenshots, Videos, or Pastebins

![nc fehler](https://user-images.githubusercontent.com/73446703/151057008-3db77e77-8902-4c9c-99ec-4231d8942e7b.jpg)

### Build Version

22.2.3

### Environment

By downloading the VM

### Environment Details

Ubuntu 20.04.3
NC 22.2.3
PHP 7.4.3
PostgreSQL 12.9  

Prozessor: | Intel(R) Xeon(R) CPU D-1541 @ 2.10GHz (8 cores)
Speicher: | 15.62 GB

**Comment by enoch85** [comment]
Hi,

Have a look here: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm-first-setup-instructions?currentPageId=c7fje9qhv0jgthl2cjk0
