### ISSUE TITLE
OCP\Files\NotFoundException

### ISSUE THREAD

**Issue by mbailey0074** [nextcloud/vm#2198]
### Steps To Reproduce

When running sudo bash /var/scripts/menu.sh>Server Configuration> deSEC>Install deSEC

I enter the sub domain and that works properly. The token is accepted. It allows me to continue with DDNS and TLS setup. I get the  everything is set up by now and we will check the connection box. There is an error that says something went wrong with ddns setup.

Then I get the option to activate TLS using Let's Encrypt. When I hit yes I get an immediate error. 

In OC_Helper.php line 496:
[OCP\Files|NotFoundException]

### Expected Result

I expected the deSEC setup process to go through with no issue.

### Actual Result

the setup failed and I received an error "OCP\Files\NotFoundException"

### Screenshots, Videos, or Pastebins

![Screenshot from 2022-01-27 04-17-08](https://user-images.githubusercontent.com/34779268/151329591-fd67674b-422a-45e6-a16e-42f1a414cf16.png)

### Build Version

Nextcloud Hub II (23.0.0)

### Environment

By downloading the VM

### Environment Details

![Screenshot from 2022-01-27 04-34-58](https://user-images.githubusercontent.com/34779268/151331965-05e015af-bde7-452b-bce4-764a4ed627c4.png)

**Comment by enoch85** [comment]
Omg, yet another bug related to NC 23...

Sorry, we stopped updates to it, and will make a new release when 23.0.1 is out. Please wait.

**Comment by mbailey0074** [comment]
> 

Awesome!! Thanks!

**Comment by szaimen** [comment]
The filesnotfoundexception gets fixed with https://github.com/nextcloud/server/pull/30890. So I guess it needs a simple git_apply_patch now.

**Comment by enoch85** [comment]
Yes, exactly what I thought! Telepathy. :)

Will put it in the first temp_fix so that it can be removed when 23.0.2 is out easily.

**Comment by enoch85** [comment]
This is now fixed in master, expect new release today!
