### ISSUE TITLE
Version 23 Upgrade 'Protection'?

### ISSUE THREAD

**Issue by RJ-Make** [nextcloud/vm#2201]
### Steps To Reproduce

1. run sudo bash /var/scripts/menu.sh
2. select Major version upgrade

### Expected Result

Update to proceed. 

### Actual Result

Get to a certain point and throws up some protection message about breaking nextcloud if upgrading to 23, and to wait for RC1. 

### Screenshots, Videos, or Pastebins

<img width="1178" alt="2022-01-07_10-39-55" src="https://user-images.githubusercontent.com/8496835/151442867-604aedac-b750-44b0-8727-d04776677233.png">

### Build Version

22.2.3

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Thanks for posting!

This is expected. We wait for 23.0.1 to be released.
