### ISSUE TITLE
UNABLE TO ACCESS AFTER SATURDAY UPGRADE

### ISSUE THREAD

**Issue by SAMCloud-IT** [nextcloud/vm#2208]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <user_ldap> ...
An unhandled exception has been thrown:
Error: Call to undefined method OC\DB\QueryBuilder\QueryBuilder::executeQuery() in /var/www/nextcloud/apps/user_ldap/lib/Migration/GroupMappingMigration.php:56
Stack trace:
#0 /var/www/nextcloud/apps/user_ldap/lib/Migration/Version1130Date20220110154717.php(54): OCA\User_LDAP\Migration\GroupMappingMigration->copyGroupMappingData()
#1 /var/www/nextcloud/lib/private/DB/MigrationService.php(528): OCA\User_LDAP\Migration\Version1130Date20220110154717->preSchemaChange()
#2 /var/www/nextcloud/lib/private/DB/MigrationService.php(426): OC\DB\MigrationService->executeStep()
#3 /var/www/nextcloud/lib/private/legacy/OC_App.php(1012): OC\DB\MigrationService->migrate()
#4 /var/www/nextcloud/lib/private/Updater.php(347): OC_App::updateApp()
#5 /var/www/nextcloud/lib/private/Updater.php(262): OC\Updater->doAppUpgrade()
#6 /var/www/nextcloud/lib/private/Updater.php(134): OC\Updater->doUpgrade()
#7 /var/www/nextcloud/core/Command/Upgrade.php(249): OC\Updater->upgrade()
#8 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#13 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#15 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ upgrade failed

### Actual Result

After normally upgrade schedule automaticaly on saturday, my nextcloud instance is on MAINTENANCE mode..

I've tried to sudo bash /var/scripts/update.sh but I've the error bellow...

### Build Version

21.0.7.0

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Hi,

Please disable LDAP and try again.

**Comment by SAMCloud-IT** [comment]
It works ! Thanks a lot 👍
