### ISSUE TITLE
Error when installing FTS

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2212]
### Steps To Reproduce

1. Install FTS with the new script
2. Make a reinstallation

### Expected Result

FTS should re-install

### Actual Result

```
Waiting for Docker bootstrapping...
ERROR: No container found for fts_os-node_1
```

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/4511254/151799024-2e9d4638-a2af-458d-949c-89be325ec018.png)

### Additional Context

cc @Ark74 

### Build Version

23.0.1

### Environment

By using the scripts

**Comment by Ark74** [comment]
please merge #2213
then we can test reinstall.

**Comment by Ark74** [comment]
testing...

**Comment by Ark74** [comment]
Testes and works! :1st_place_medal: 

I think that with new required specs for the server, is safe to use 60 instead of 120.
https://github.com/nextcloud/vm/blob/master/apps/fulltextsearch.sh#L235

**Comment by enoch85** [comment]
OK, let's change that as well.
