### ISSUE TITLE
Update FTS Docker

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2214]
@Ark74 A few things left:

- Make [this](https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L589) work.
- Create a crontab that scans for new files on a schedule. I'm thinking a refresh index like every night at 02:00 or something. Just to be sure. Alternatively, double check that the `cron.php` handles it properly.

Thanks! :rocket:

**Comment by Ark74** [comment]
Here the PR for update #2215

**Comment by Ark74** [comment]
Seems like this line...
```
docker_update_specific 'fts_os-node' 'Full Text Search'
```

...was breaking the index by stopping and removing the container running, this should not happen after this PR.

In case of a faulty index, resetting the index (occ fulltextsearch:reset) and indexing again (making sure there is a running opensearch container) will show the results.

We'll be able to confirm after the merge.
Cheers.

**Comment by Ark74** [comment]
@enoch85 
All seems to be working now :muscle:   it might take some time to show the results but they get there eventually.
Anything else missing?

cc @ArtificialOwl

**Comment by enoch85** [comment]
I haven't tested but I trust your judgement. :)

**Comment by Ark74** [comment]
It will be great to have Maxence blessing and review. :pray: 
As we could potentially improve it with his feedback, as for now it follows the default behavior the old Elasticsearch + FTS  provided.

Regards :1st_place_medal:

**Comment by enoch85** [comment]
@ArtificialOwl 

> Create a crontab that scans for new files on a schedule. I'm thinking a refresh index like every night at 02:00 or something. Just to be sure. Alternatively, double check that the cron.php handles it properly.

Is it needed, or do `cron.php` handle the indexing on it's own?
