### ISSUE TITLE
igbinary update: configuration option "php_ini" is not set to php.ini location

### ISSUE THREAD

**Issue by p-bo** [nextcloud/vm#2217]
### Steps To Reproduce

Run update script

### Expected Result

igbinary updated

### Actual Result

upgrade ok: channel://pecl.php.net/igbinary-3.2.7
configuration option "php_ini" is not set to php.ini location
You should add "extension=igbinary.so" to php.ini
/var/scripts/nextcloud_update.sh: line 498: 833557 Broken pipe             yes no
     833558 Segmentation fault      (core dumped) | pecl upgrade igbinary
Nothing to upgrade

### Build Version

22.2.4

### Environment

By downloading the VM

**Comment by enoch85** [comment]
It's been like this for years, and everything works as intended. The values in `php.ini` are correct afaik, so I think this is just cosmetic, but if anyone would like to have a look at it, feel free!

**Comment by p-bo** [comment]
Thanks for assuring that this is not harmful. Personally adding this to my admin notes among things do not worry about like this, #2108, etc.
Must admit, that first time I saw them, was nervous a bit regarding how well instance, I'm administrating for my appreciated users, will be after update. Maybe it would be helpful to provide piece on mind to "inject" there message like "disregards error above, it is not problem" placed into relevant script run output sections to don't scare us, not so die hard admins? ;-)

**Comment by p-bo** [comment]
P.S.: trying to not be troublemaker only and demanding others to fix things for me, but trying to solving things also by myself (non-coding things) - see https://gitlab.com/packaging/janus/-/issues/5
;-)

**Comment by enoch85** [comment]
@p-bo Can you please help test the upcoming Ubuntu 22.04 VM?

Check here: https://github.com/nextcloud/vm/pull/2279#issuecomment-1106782963

**Comment by p-bo** [comment]
@enoch85 Did test install (os installed in minimalized variant, as recommended by you) and it seems to be fixed in that version:

>Trying to upgrade igbinary, and smbclient...
>Nothing to upgrade
>Nothing to upgrade

(no more segfaults and broken pipes)

only to be sure that test is correct - igbinary is installed:

>pecl install -Z igbinary
>pecl/igbinary is already installed and is the same as the released version 3.2.7

Big thank you for keeping this on mind and taking care for it - appreciated!

**Comment by enoch85** [comment]
Thanks for confirming!
