### ISSUE TITLE
Script connection check times out, all other things involving a connection work fine

### ISSUE THREAD

**Issue by Plocmstart** [nextcloud/vm#2220]
### Steps To Reproduce

Run setup script.  

### Expected Result

Script either doesn't continuously check for a connection, or uses a mechanism that actually works.

### Actual Result

Everywhere it attempts to check for a network connection (very frequently) it times out and asks if github.com is accessible.  Via a ssh terminal I can successfully use nslookup and ping github.com.  All other actual tasks the script does work successfully, so this connection checking just makes the script take much longer to complete for no apparent benefit.

### Additional Context

Running .ova on VMWare.

### Build Version

23

### Environment

By downloading the VM

**Comment by enoch85** [comment]
I never had any issues with it at all. The checks are in place to help users make it easier and remind them that internet is needed to run the script. Some functions doesn't work without WAN, and if you have issues my guess it's probably on your end. 

Do you use country block maybe?

**Comment by enoch85** [comment]
Just tested the VM and had no such issues as you describe. 

Please check your firewall, you are probably blocking something that stops the scripts from working.
