### ISSUE TITLE
increase security of turnserver?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#2224]
I've recently head a look at the talk docs and I've found this section:
https://github.com/nextcloud/spreed/pull/5788/commits/71a82ec05feb8d838869a72d657e5d1435155ae9

What do you think about the security impact? Should we implement those, too?

cc @morph027 on this :)

**Comment by morph027** [comment]
Good idea. Not sure how the setup is within the VM now, if it's connected to more than one subnet etc. ... Might depend on the user setup.

**Comment by szaimen** [comment]
If I understand the docs correctly, we should be able to enable this if the hpb gets installed. Otherwise probably not...

**Comment by enoch85** [comment]
I have no opinion. Do what you feel is best.

**Comment by enoch85** [comment]
@szaimen @morph027 is this something that you will work on anytime soon you think? :)

**Comment by szaimen** [comment]
I rather not think so... I am also not sure if there is really a way to limit this to a defined set of ip-addresses because I don't know in detail how the whole stack works together...

**Comment by morph027** [comment]
Sorry, needed to catch up on my Github stream ;)

After reading through, we actually should only allow the HBP address, which - if i'm right - is the ip address of the machine the whole stack runs on. So this depends on the fact if HBP is enabled ans installed, but within the coturn script section. I'll have a closer look.

**Comment by szaimen** [comment]
So if the HPB is installed, coturn will always only connect directly to the HPB and to nothing else?

**Comment by morph027** [comment]
Looks like. In fact, the TURN server should never connect to anything else when not running with HBP, as it's purpose is to handle inbound connections from the outside to the outside. I will test-drive the settings on my personal instance.

**Comment by szaimen** [comment]
okay, I was not sure hence my question. Thanks for investigating this! :)

**Comment by morph027** [comment]
Tested some video calls and everything seems to work okay.

Only thing i've added is:

```
allowed-peer-ip=127.0.0.1
denied-peer-ip=0.0.0.0-0.255.255.255
```

to turnserver config.

**Comment by enoch85** [comment]
Would you mind making a PR? :)

**Comment by enoch85** [comment]
This is done.
