### ISSUE TITLE
tpm2-unlock.sh fails

### ISSUE THREAD

**Issue by pq2** [nextcloud/vm#2226]
### Steps To Reproduce

Run `sudo bash tpm2-unlock.sh` on an Intel NUC7CJYHN using Ubuntu 20.04.

### Expected Result

The script sets up TPM2 Unlock successfully.

### Actual Result

Line 79 `clevis luks bind -k - -d "/dev/${ENCRYPTED_DEVICE[*]}" tpm2 '{"pcr_ids":"7"}'` throws the following errors:
```
ERROR: pcr-input-file filesize does not match pcr set-list
ERROR: Could not build pcr policy
ERROR: Unable to run tpm2_createpolicy
```

### Additional Context

I was able to fix the problem by changing `{"pcr_ids":"7"}` to `{"pcr_bank":"sha256","pcr_ids":"7"}`.

### Build Version

irrelevant

### Environment

By using the scripts

**Comment by szaimen** [comment]
Thanks for the report! I will have a look soon!

**Comment by szaimen** [comment]
@pq2 what is the output of `sudo tpm2_pcrread` on your machine?
