### ISSUE TITLE
UserDeletedEvent fired without matching BeforeUserDeletedEvent

### ISSUE THREAD

**Issue by pq2** [nextcloud/vm#2227]
### Steps To Reproduce

Work through setup of Nextcloud Server until after the step where the Web Admin credentials are set.

### Expected Result

Setup completes successfully.

### Actual Result

After the "There are still some stuff left to do, but they are automated so sit back and relax" message the following error appeared:
![Screenshot_20220208_190144](https://user-images.githubusercontent.com/56400565/153048185-e2c46161-b086-4d8c-8035-55edff77af96.png)

### Build Version

~~22.2.3~~ 22.2.4

### Environment

By using the scripts

### Environment Details

Ubuntu 20.04
Intel NUC7CJYHN

**Comment by szaimen** [comment]
I fear this is a bug in Nextcloud or one of your installed apps.

---

> 22.2.3

Are you sure that it is not 22.2.4?

---

And do you mind sharing your installed apps?

**Comment by pq2** [comment]
The version should be the one currently used by nextcloud_install_production.sh. Based on the output of the script, I could only remember that a 22 version was installed. I assumed that this would then probably be the latest, which according to https://nextcloud.com/changelog/#latest22 is version 22.2.3, so I assumed it would be that one. 
I installed calendar, Contacts, PDFViewer, Extract, Text, and Deck.

**Comment by enoch85** [comment]
Please install the latest version, it works.

**Comment by pq2** [comment]
> Please install the latest version, it works.

Alright, thanks. Can confirm that it did work with Nextcloud 23.0.1.

**Comment by szaimen** [comment]
@enoch85 should we report to upstream that 22.2.4 seems to be broken in this regard?

**Comment by szaimen** [comment]
@pq2 great to hear that 23.0.1 works for you :)

**Comment by enoch85** [comment]
@szaimen Yes, please do 👍🏻
