### ISSUE TITLE
nextcloud_install_production.sh: not necessary OS upgrade breakes UTF8 support for samba mounts

### ISSUE THREAD

**Issue by daniela-waranie** [nextcloud/vm#223]
First: thanks a lot for this script.

You script requires Ubuntu 16.04 and updates kernel to 4.8.0. 
Why not requiring Ubuntu 16.10. Starting with a "clean" OS vs. OS upgrade is recommended on nearly every forum (as a general advice).

I am asking because with your script installes kernel 4.8.0-51 where nls_utf8.ko (kernel module) is missing in linux-image-extra-4.8.0-51-*.

As far as i can see there is no need to upgrade the OS to run nextcloud.
As far as i can see there is no need have hardware enablement packages within a standard virtual machine - no need to catch up with new hardware devices - no need to add "new hardware" to run nextcloud.
As far as i can see there is no need to install a virtual package optimized for virtual machines - no need to reduce the disc usage (which would only have an effect when removing the old 4.4.0 kernel after installing 4.8.0).

Please remove:

`apt dist-upgrade -y`
and
`apt install linux-tools-virtual-hwe-16.04 linux-cloud-tools-virtual-hwe-16.04  -y
apt install linux-image-virtual-hwe-16.04 -y
apt install linux-virtual-hwe-16.04 -y`

or please install a linux-image-* / linux-image-extra-*  which supports the UTF8 kernel module.
e.g.: linux-image-extra-4.8.0-22-generic

See here:
https://packages.ubuntu.com/search?suite=yakkety&arch=amd64&searchon=contents&keywords=nls_utf8.ko

**Comment by daniela-waranie** [comment]
Background:
I try to run all my application servers as immutable systems. (app update = replacing the server favor to maintaining the server)
In case of nextcloud i mount in the data dir and link the application against a separate database server.

**Comment by enoch85** [comment]
@daniela-waranie Thanks for your input. 

Ubuntu 16.10 is not LTS. 4.8 kernel is needed for Hyper-V to function properly.

There are reasons for my choices. ;)

**Comment by daniela-waranie** [comment]
@enoch85 i am no Hyper-V expert, but Hyper-V support is included since Ubuntu 12.04 and just needs to be enabled:

> There are a few Linux distributions that come with LIS already installed, including Ubuntu – Ubuntu Hyper-V Integration Services have been built into Ubuntu Linux since Ubuntu 12.04 — so there's no need for a separate download and installation. For these distributions, only activation is required to use the full features of Hyper-V

http://www.serverwatch.com/server-tutorials/installing-and-activating-hyper-v-linux-integration-services.html

Would be nice if we can have both: Hyper-V support and UTF8 for Samba mounts. 
Maybe we can stay on Ubuntu 16.04 with kernel 4.4.0-x and enable Hyper-V. 
Is LTS really a must have? (it would be very nice if your script will be updated to run on ubuntu 17.04)

**Comment by enoch85** [comment]
@daniela-waranie I don't know how familiar you are with running servers, but yes LTS is a must have as the support for e.g. 17.04 ends sooner than 16.04 LTS which would mean that security upgrades woulnd't apply when 17.04 is EOL.

Regarding Hyper-V you can run is since 12.04 yes, but what I'm talking about is full support for Checkpoint and stuff like that that are implemented in the newer kernels.

What is needed for UTF8 Samab mounts? Is it enough to install `linux-image-extra` ?

**Comment by daniela-waranie** [comment]
5 years of support (security fixes only) can prevent you from being forced to migrate to a more up-to-date system. It can reduce your maintenance costs and enable your to plan a long time ahead - in theory. 

I am not a system engineer. I am a software developer working in a DevOps minded team. And i know that more and more software development pattern are applied to system engineering tasks. Scripting (Provisioning), Scrum, DevOps mindset, smoke tests, etc. 

Running an fast moving open source (nextcloud) is fast raising requirements and respond to fast moving business needs is often requiring changes, too (demanding for newer OS). As a professional you should not try to "exclude change" / "be sticky on a OS version", you should implement a process to expect/accept change. Implement a process to iterate fast (where moving to the next OS version is a painless step). No longer treat your server, and especially a virtual server as a pet. Treat it as stock. Kill a server and launch a new one. Nextcloud is about to streamline the upgrade experience. As a community we should try to align our scripts to those needs. Launch a new server and import/restore-from-backup or link to transaction data (files and database entries; stored on a NAS or on a separate DB server) should be a matter of minutes.

An extreme thinking of this modern pattern is **immutable systems**, where the application running on top of your OS is not replaced with a new application version, where your complete server is replaced by a new (virtual) server which already includes the new application. Stop maintaining servers! Start killing them! This ensures that your provisioning scripts are executed more often and therefor better tested - which renders your process to be proven and less painful.

**For me LTS is a solution to companies which are trying to apply old thinking / old pattern to a problem even when better patterns are available.**

**Comment by enoch85** [comment]
@daniela-waranie There you go --^
