### ISSUE TITLE
Unable to boot 2TB hanssonit VM in ESXi 6.7u3

### ISSUE THREAD

**Issue by mehtaman** [nextcloud/vm#2231]
### Steps To Reproduce

**### First Issue:**
Purchased & Downloaded .OVA 
Tried to Import into VMWare and had a Manifest Error / mismatch

Solution:
Open .OVA in 7Zip 
Edit `2TB_Nextcloud-VM_www.hanssonit.se.mf` to `2TB_Nextcloud-VM_www.hanssonit.se.txt`

Data in .mf file:
```
SHA256(2TB_Nextcloud-VM_www.hanssonit.se.ovf)= 79f78358a09b897ae8d81baa1ecccac3d71f73adcf2c86fe34482dd30bc585c3
SHA256(2TB_Nextcloud-VM_www.hanssonit.se-disk1.vmdk)= b019ddbda147448a34e615e415f76dd7444cc3add97f355ac689584f9d26f991
SHA256(2TB_Nextcloud-VM_www.hanssonit.se-disk2.vmdk)= d1d1e432e8b6b6354fbcbd3d1bc97b75e9b1e25253932837f8c44e9071f1a983
```

**### Second Issue:**
Now the VM has imported, When I start the VM, It just sits on "initramfs" and doesn't progress

Is this compatible with ESXi / vSphere 6.7u3?

### Expected Result

OVA to install and boot without issue

### Actual Result

Stuck on initramfs

### Build Version

latest 

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Hi, please take a look here: https://github.com/nextcloud/vm/issues/910

**Comment by mehtaman** [comment]
> Hi, please take a look here: #910

I have renamed the .mf file to a .txt file so it is not looked at by the template import.

I have now deleted the file and tried to import again but it still stops at the initramfs screen rather than going to the nextcloud setup script.

**Comment by enoch85** [comment]
Have you tried importing it to [VMware Player 16](https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html)?

**Comment by mehtaman** [comment]
> Have you tried importing it to [VMware Player 16](https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html)?

Just tired and get the same issue:
![image](https://user-images.githubusercontent.com/16583136/153281268-6d24a314-392f-46bc-a784-6041bdbd83e1.png)

**Comment by mehtaman** [comment]
Stops at the same place as the ESXi Hosted VM:
![image](https://user-images.githubusercontent.com/16583136/153281349-944cb8c6-c4a6-4638-9c13-7ace675c6af6.png)

**Comment by mehtaman** [comment]
OVA extracted without any issues:
![image](https://user-images.githubusercontent.com/16583136/153281655-11683e9b-e6ba-4f88-8ddf-5bef8af586cc.png)

**Comment by enoch85** [comment]
OK, I will try myself.

**Comment by enoch85** [comment]
Works here: https://cloud.danielhansson.nu/s/f2cdQzMgWA44RfL
