### ISSUE TITLE
Apache2 fails to start after VM reboot

### ISSUE THREAD

**Issue by ebildebil** [nextcloud/vm#2235]
### Steps To Reproduce

1. Go to 'sudo reboot now'

### Expected Result

**Job for apache2.service failed because **the** control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.**

### Actual Result

I have used the script to create my own VM. It has been working fine for a few months.
A couple of hours ago I had to reboot the system on which the VM is running. (Qnap ts-873A, 64gb ECC, zfs file system on nas)
The VM was shutdown from within the VM.
After reboot, I get the below mesage:
**Job for apache2.service failed because **the** control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.**

I restored a snapshot from 15-Feb and then everything worked, however, upon VM reboot (sudo reboot now), Apache would not load again.

As a test, I went to the folder etc/apache2/sites-available/ and renamed the mysite.name.conf file to mysite.name.donf (to exclude it from apache load) and then apache loaded fine. This was with a bitwarden, turn and only office , conf files left as is. (was was able to access all three from the browser)

However, enabling mysite.name.conf prevents Apache2 from loading.

### Additional Context

This is my first ever post on Github and I am not an IT guy. I'm sorry if I've not reported this in the correct way.

### Build Version

23.0.1 or 23.0.2 (not able to check right now)

### Environment

By using the scripts

### Environment Details

Ubuntu server 20 Lts (latest)
Environment is as per the script. (php 7.4, postgreeSQL)
VM is running on a qnap NAS, TS-873A, 64gb ECC ram, 108TB space, 1gbps network, ZFS file system.
The Nextcloud VM is allocated 4 cores, 16gb RAM,
I am running Nextcloud, Turn, Spreed, onlyoffice docker, bitwarden, talk.

**Comment by enoch85** [comment]
What does `journalctl -xe` say?

**Comment by ebildebil** [comment]
Hello Daniel,

 

Thank you for responding.

 

Here is the output from ‘journalctl -xe’

Journalctl -xe

Defined-By: systemd

-- Support: http://www.ubuntu.com/support

-- 

-- The unit run-docker-runtime\x2drunc-moby-92e8955bb587b82471bcee4bafeca24d7e>

Feb 17 17:34:47 karfamily.net systemd[4647]: run-docker-runtime\x2drunc-moby-9>

-- Subject: Unit succeeded

-- Defined-By: systemd

-- Support: http://www.ubuntu.com/support

-- 

-- The unit UNIT has successfully entered the 'dead' state.

Feb 17 17:34:47 karfamily.net systemd[1957]: run-docker-runtime\x2drunc-moby-9>

-- Subject: Unit succeeded

-- Defined-By: systemd

-- Support: http://www.ubuntu.com/support

-- 

-- The unit UNIT has successfully entered the 'dead' state.

Feb 17 17:34:51 karfamily.net systemd[1]: run-docker-runtime\x2drunc-moby-56a4>

-- Subject: Unit succeeded

-- Defined-By: systemd

-- Support: http://www.ubuntu.com/support

-- 

-- The unit run-docker-runtime\x2drunc-moby-56a4c909b86e2f6aa297d74f50e5f2d9d5>

Feb 17 17:34:51 karfamily.net systemd[4647]: run-docker-runtime\x2drunc-moby-5>

-- Subject: Unit succeeded

-- Defined-By: systemd

-- Support: http://www.ubuntu.com/support

-- 

-- The unit UNIT has successfully entered the 'dead' state.

 

I just wanted to add some more info:

 

I had googled around a lot and had run
sudo apache2ctl -t

 

*	Thank told me that apache2.conf had an error in line 225, which subsequently pointed me to my.site.conf line 40.
*	Line 40 is: include /mnt/ncdata/.htaccess

 

*	Nexcloud login page said .htaccess file is missing. I looked in ncdata folder, and it was empty.

 

*	From a backup (12-Jan) I copy/pasted (not rsync) the .htaccess to ncdata

 

*	Then it said .ocdata is missing. I copy pasted that.

 

*	Then it gave me permission issues, so I changed owner of the ncdata folder (which had become – root) to www-data

 

*	After this Apache2 -stop-start-reload worked.

 

*	I managed to log-in and NC built most part of the ncdata folder. (no idea how)

 

*	Some missing stuff, I copy/pasted again.

 

So, likely with some problems I’m unaware of, I have a functional instance now.

 

However, thinking about what may have caused it, I think it is the backup app in NC.

I’ve added a PDF of my backup settings page.

 

Some days ago, I had set it up as below:



 

I think, this has something to do with /mnt/ncdata/ going fully empty. Although, why it should do so, I have no idea.

 

So, now I am a bit concerned if I have a stable instance. I really like having myown stuff and family + kids really started to integrate in daily lives.

Since I don’t know how to do backup/restore (rsync,pfsql dump etc), I am mainly managing by doing full VM backup at the nas level.

 

What should my next steps be?

 

I had done (after massive googling) rsync of the folders: Nextcloud, ncdata (when it had stuff) and taken a dump of pgsql.

When this happened, I tried doing a restore on a Hyper-v linux VM but that just gives me below error at login page:

Used webmin to try to restore pgsql dump. (I’m not competent enough 😊)

 



 

Thank you again, and I look forward to hear from you.

 

Best Regards, MVH

**Comment by enoch85** [comment]
You can get support from the shop and we'll have a look tomorrow if it suits you?

**Comment by enoch85** [comment]
Yes, if you get support and we book a session we could have a phone call, and a proper Teamviewer session.

**Comment by ebildebil** [comment]
I meant to ask these questions directly, but we can take it here to start with:
- My objective is:
  - set-up a clear backup/restore document that I can follow-up in future to continue to make reliable backups and restore my instance on a fresh VM/Linus install. (regardless of the VM platform)
  - a check if everything is okay with the current one.
  - May be (if not too much effort), remove the NCDATA mount and use a NAS shared folder directly for data.
  
  - the prices for everything on your site were in EUR. Since I'm based in Sweden, is it possible to do this in SEK.
  - This is a self hosted instance and used only for private purposes, is there a way we can estimate how much time this will require? I do sincerely respect the work and effort you have put into this, I'm a bit afraid, with the current cost per support slot, it might become too expensive for me. Is there a way to sort of fix/limit it? Any price considerations you believe that can be made?
  
Not sure it helps, but right now, the instance is not broken, it is accessible and functional. 

I mainly want to be able to provide at home a private solution that is really **reliable** and **can be maintained (for most part) by me.**
PS: If I need to buy support to discuss these, please let me know.

**Comment by enoch85** [comment]
Everything you just mentioned can be done. :+1: 

Let's continue the discussion by email: support at hanssonit dot se.

Jag är också från Sverige, men våra priser är i EUR, tyvärr inte SEK. Hade du haft företag så hade det gått att lösa dock.

Closing this as a support ticket.
