### ISSUE TITLE
NetData install fail

### ISSUE THREAD

**Issue by JKMoran** [nextcloud/vm#2239]
### Steps To Reproduce

Run Script sudo bash /var/scripts/menu.sh

Running the main menu script...
Testing if network is OK...
Checking connection...
Downloading the Additional Apps Menu...
Downloading the Additional Apps Menu...
Downloading the Netdata script...
Downloading the Netdata script...
Reinstalling Netdata...
Reinstalling Netdata...
/var/scripts/netdata-uninstaller.sh: line 445: /etc/netdata/.environment: No such file or directory

Something went wrong :(
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
bash /var/scripts/netdata-uninstaller.sh --force --yes failed

### Expected Result

Successful netdata installation.

### Actual Result

Failure to install

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/76010768/154748416-e7a74d01-aab2-4ee9-b745-6a7e61423620.png)

### Build Version

23.0.2

### Environment

By using the scripts, By downloading the VM

### Environment Details

Ubuntu 20.04.3
PHP 7.4

**Comment by enoch85** [comment]
Thanks for posting!

Tried to fix it but it still fails for me, how about for you? Can you please post the new output?

**Comment by JKMoran** [comment]
Still failing unfortunately
![image](https://user-images.githubusercontent.com/76010768/154767779-0e93e33a-7dca-46e8-810f-19daba278b1e.png)

**Comment by JKMoran** [comment]
Sounds good, just finished posting it to Netdata as well.

John K. Moran
Vancouver, BC
www.analyticlabs.io<http://www.analyticlabs.io/>
Email: ***@***.******@***.***>
Direct: 778-686-7787
Book a Meeting<https://calendly.com/aldc-jk/bookit>

**Comment by enoch85** [comment]
Should be fixed now.
