### ISSUE TITLE
sudo -u www-data php /var/www/nextcloud/occ -V failed

### ISSUE THREAD

**Issue by mbailey0074** [nextcloud/vm#2244]
### Steps To Reproduce

attempted to auto update through Updater and it failed and now I get an internal server error when I login to the web portal and I get and error that says "sudo -u www-data php /var/www/nextcloud/occ -V failed" when I login to the server appliance. 

### Expected Result

The update to work and to be able to login to the web portal

### Actual Result

the update is failing and I am unable to login to the web portal

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/34779268/154953203-d1e982f2-661c-45ba-ab00-717bda31f6af.png)

![image](https://user-images.githubusercontent.com/34779268/154953248-4b4e4533-5abe-4485-9cb8-fecd035d7cf7.png)

### Build Version

20

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Hi, 

Thanks for posting. It would be interesting to see the error above this message -that's the cause of the issue. Something in Nextcloud isn't working, most probably an app.

**Comment by mbailey0074** [comment]
I got a notification that I got the recent VW that doesn't work properly. I
am going to get the new one going and get back to you

**Comment by enoch85** [comment]
Please test the latest release, all bugs should be sorted in that one.
