### ISSUE TITLE
delete user ncadmin failed

### ISSUE THREAD

**Issue by dobrybobr** [nextcloud/vm#2246]
### Steps To Reproduce

just happened while script was running on a clean ubuntu2004 server

### Expected Result

ncadmin gone home :D

### Actual Result

Deleting ncadmin...

In UserDeletedFilesCleanupListener.php line 63:

  UserDeletedEvent fired without matching BeforeUserDeletedEvent

user:delete <uid>

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ user:delete ncadmin failed
Posting notification to users that are admins, this might take a while...

### Build Version

unsure wich version the script actualy installed, happend 25. february 2022

### Environment

By using the scripts

**Comment by enoch85** [comment]
Thanks for reporting.

Download the latest version and try again. This is already fixed.

**Comment by szaimen** [comment]
Hello, we need to know the Nextcloud version that you are running.
Please run `sudo cat /var/www/nextcloud/config/config.php | grep -i version` and post the output. Thanks!

**Comment by dobrybobr** [comment]
> Hello, we need to know the Nextcloud version that you are running. Please run `sudo cat /var/www/nextcloud/config/config.php | grep -i version` and post the output. Thanks!

 'version' => '23.0.2.1',
  'versions_retention_obligation' => 'auto, 180',

**Comment by dobrybobr** [comment]
sorry i am only user, no coder :)

**Comment by enoch85** [comment]
@szaimen The version won't help us much since it's auto updating during the first setup. So it could be a script downloaded which held version 23.0.0 for all we know...

Repeating myself; download the *latest* script and try again on a 100% fresh Ubuntu Server 20.04 VM. :)

**Comment by dobrybobr** [comment]
![Screenshot 2022-02-25 at 19-16-08 Benutzer - Nextcloud](https://user-images.githubusercontent.com/100437451/155766992-5f149ec8-a15b-466f-8762-ca5de95ecded.png)
anyway, the user ncadmin seems not to exist inside nextcloud :)

**Comment by szaimen** [comment]
> The version won't help us much since it's auto updating during the first setup. So it could be a script downloaded which held version 23.0.0 for all we know...
> 
> Repeating myself; download the _latest_ script and try again on a 100% fresh Ubuntu Server 20.04 VM. :)

Just asking because it could have been possible that he/she used the --not-latest flag which might let him/her run into this issue on 22.2.5 but doesn't seem to be the case here...

**Comment by enoch85** [comment]
Please test the latest release. All bugs sorted in that one.
