### ISSUE TITLE
postgresql.conf tweaks for performance

### ISSUE THREAD

**Issue by hobbsecky** [nextcloud/vm#2247]
Using NextcloudVM.
I tweaked my postgresql.conf file using the calculator [**HERE**](https://pgtune.leopard.in.ua/#/)
Modifications to postgresql.conf for my setup were:

```
# DB Version: 12
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 4 GB
# CPUs num: 2
# Connections num: 20
# Data Storage: ssd

max_connections = 20
shared_buffers = 1GB
effective_cache_size = 3GB
maintenance_work_mem = 256MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 52428kB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 2
max_parallel_workers_per_gather = 1
max_parallel_workers = 2
max_parallel_maintenance_workers = 1
```

The performance improvement is DRAMATIC especially when using the OnlyOffice backend and opening documents.

Not sure how you would want to go about sharing this info for NextcloudVM users or if you might want to alter the default config in a generic way.

Just thought I'd share this for anyone using NextcloudVM.

Thanks

**Comment by enoch85** [comment]
Thanks! But we will not use anything but the default settings in the VM. Users are free to tweak it themselves.

https://www.techandme.se/we-migrated-to-postgresql/
