### ISSUE TITLE
AH01797: client denied by server configuration

### ISSUE THREAD

**Issue by sebadamus** [nextcloud/vm#2249]
### Steps To Reproduce

No idea, I just checked the apache log after doing a CLI minor update (from within sudo bash /var/scripts/menu.sh).  Everything seems to be working, but getting these errors spamming the apache log.

### Expected Result

No errors in apache log?

### Actual Result

[Sun Feb 27 19:40:54.647777 2022] [access_compat:error] [pid 3535:tid 139833976047360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/dashboard/js/dashboard.js
[Sun Feb 27 19:40:54.648029 2022] [access_compat:error] [pid 3535:tid 139833984440064] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/core/js/dist/unified-search.js
[Sun Feb 27 19:40:54.648228 2022] [access_compat:error] [pid 3535:tid 139833992832768] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/js
[Sun Feb 27 19:40:54.648300 2022] [access_compat:error] [pid 3535:tid 139833992832768] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:40:54.648715 2022] [access_compat:error] [pid 3535:tid 139833774548736] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/recommendations/js/dashboard.js
[Sun Feb 27 19:40:54.656115 2022] [access_compat:error] [pid 3535:tid 139834001225472] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/dashboard/img/dashboard.svg
[Sun Feb 27 19:40:54.656258 2022] [access_compat:error] [pid 3535:tid 139834001225472] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/avatar
[Sun Feb 27 19:40:54.656286 2022] [access_compat:error] [pid 3535:tid 139834001225472] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:40:54.656452 2022] [access_compat:error] [pid 3535:tid 139834009618176] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/files/img/app.svg
[Sun Feb 27 19:40:54.656583 2022] [access_compat:error] [pid 3535:tid 139834018010880] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/activity/img/activity.svg
[Sun Feb 27 19:40:54.660692 2022] [access_compat:error] [pid 3535:tid 139833950869248] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/tasks/img/tasks.svg
[Sun Feb 27 19:40:54.660899 2022] [access_compat:error] [pid 3535:tid 139834009618176] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/user_status/img/app.svg
[Sun Feb 27 19:40:54.661023 2022] [access_compat:error] [pid 3535:tid 139833942476544] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/deck/img/deck.svg
[Sun Feb 27 19:40:54.661349 2022] [access_compat:error] [pid 3535:tid 139833934083840] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/calendar/img/calendar.svg
[Sun Feb 27 19:40:54.661940 2022] [access_compat:error] [pid 3535:tid 139834009618176] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/firstrunwizard/img/info.svg
[Sun Feb 27 19:40:54.662455 2022] [access_compat:error] [pid 3535:tid 139833757746944] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/contacts/img/app.svg
[Sun Feb 27 19:40:54.690783 2022] [access_compat:error] [pid 3535:tid 139833934083840] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/core/img/actions/logout.svg
[Sun Feb 27 19:40:54.812438 2022] [access_compat:error] [pid 3535:tid 139833757746944] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/img/help.svg
[Sun Feb 27 19:40:54.812545 2022] [access_compat:error] [pid 3535:tid 139833942476544] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/img/users.svg
[Sun Feb 27 19:40:54.812586 2022] [access_compat:error] [pid 3535:tid 139833950869248] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/img/apps.svg
[Sun Feb 27 19:40:54.812623 2022] [access_compat:error] [pid 3535:tid 139834018010880] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/img/admin.svg
[Sun Feb 27 19:40:56.489068 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/svg
[Sun Feb 27 19:40:56.489126 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:40:57.130292 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/recommendations/api
[Sun Feb 27 19:40:57.130378 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:40:57.462002 2022] [access_compat:error] [pid 3535:tid 139834001225472] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/dashboard/img/kamil-porembinski-clouds.jpg
[Sun Feb 27 19:40:57.462271 2022] [access_compat:error] [pid 3535:tid 139833992832768] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/user_status/heartbeat
[Sun Feb 27 19:40:57.462331 2022] [access_compat:error] [pid 3535:tid 139833992832768] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:40:57.463199 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Sun Feb 27 19:40:57.463464 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Sun Feb 27 19:40:57.463603 2022] [access_compat:error] [pid 3535:tid 139833917298432] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/user_status/heartbeat
[Sun Feb 27 19:40:57.463663 2022] [access_compat:error] [pid 3535:tid 139833917298432] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:40:57.464445 2022] [access_compat:error] [pid 3535:tid 139833766147840] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/svg
[Sun Feb 27 19:40:57.464497 2022] [access_compat:error] [pid 3535:tid 139833766147840] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:40:57.471478 2022] [access_compat:error] [pid 3535:tid 139834001225472] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Sun Feb 27 19:40:57.471681 2022] [access_compat:error] [pid 3535:tid 139833900513024] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/notifications/img/notifications.svg
[Sun Feb 27 19:40:57.471844 2022] [access_compat:error] [pid 3535:tid 139834001225472] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/notifications/api
[Sun Feb 27 19:40:57.471968 2022] [access_compat:error] [pid 3535:tid 139833858549504] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Sun Feb 27 19:40:57.472162 2022] [access_compat:error] [pid 3535:tid 139833858549504] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/search
[Sun Feb 27 19:40:57.473771 2022] [access_compat:error] [pid 3535:tid 139833732544256] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Sun Feb 27 19:40:57.473957 2022] [access_compat:error] [pid 3535:tid 139833732544256] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/weather_status/api
[Sun Feb 27 19:40:57.690016 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/theming/img/core
[Sun Feb 27 19:40:57.690016 2022] [access_compat:error] [pid 3535:tid 139833766147840] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/theming/img/core
[Sun Feb 27 19:40:57.690112 2022] [access_compat:error] [pid 3535:tid 139833766147840] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:40:57.690114 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:40:57.824129 2022] [access_compat:error] [pid 3535:tid 139833992832768] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/user_status/img/user-status-online.svg
[Sun Feb 27 19:40:58.187644 2022] [access_compat:error] [pid 3535:tid 139833732544256] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Sun Feb 27 19:40:58.187810 2022] [access_compat:error] [pid 3535:tid 139833732544256] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/weather_status/api
[Sun Feb 27 19:40:58.190590 2022] [access_compat:error] [pid 3535:tid 139834001225472] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Sun Feb 27 19:40:58.190761 2022] [access_compat:error] [pid 3535:tid 139834001225472] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/apps/weather_status/api
[Sun Feb 27 19:40:58.268933 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Sun Feb 27 19:40:58.269092 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Sun Feb 27 19:40:58.516005 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/core/img/favicon-touch.png
[Sun Feb 27 19:40:58.516362 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/core/img/favicon.ico
[Sun Feb 27 19:40:58.552159 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Sun Feb 27 19:40:58.552405 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Sun Feb 27 19:40:58.806399 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Sun Feb 27 19:40:58.806666 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Sun Feb 27 19:40:58.806802 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Sun Feb 27 19:40:58.806948 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Sun Feb 27 19:40:59.032435 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Sun Feb 27 19:40:59.032660 2022] [access_compat:error] [pid 3535:tid 139833740945152] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Sun Feb 27 19:40:59.066366 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Sun Feb 27 19:40:59.066594 2022] [access_compat:error] [pid 3535:tid 139833724143360] [client 191.85.84.169:52887] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Sun Feb 27 19:41:04.828209 2022] [access_compat:error] [pid 3536:tid 139834001225472] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/settings
[Sun Feb 27 19:41:04.828370 2022] [access_compat:error] [pid 3536:tid 139834001225472] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:41:06.952294 2022] [access_compat:error] [pid 3536:tid 139834001225472] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/usersettings.js
[Sun Feb 27 19:41:06.952682 2022] [access_compat:error] [pid 3536:tid 139834009618176] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/templates.js
[Sun Feb 27 19:41:06.956455 2022] [access_compat:error] [pid 3536:tid 139834018010880] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/federationsettingsview.js
[Sun Feb 27 19:41:06.956823 2022] [access_compat:error] [pid 3536:tid 139833715742464] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/federationscopemenu.js
[Sun Feb 27 19:41:06.957199 2022] [access_compat:error] [pid 3536:tid 139833724143360] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/settings/personalInfo.js
[Sun Feb 27 19:41:06.957584 2022] [access_compat:error] [pid 3536:tid 139833732544256] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/vue-settings-personal-info.js
[Sun Feb 27 19:41:06.964274 2022] [access_compat:error] [pid 3536:tid 139833740945152] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/settings.js
[Sun Feb 27 19:41:06.964652 2022] [access_compat:error] [pid 3536:tid 139833749346048] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/admin.js
[Sun Feb 27 19:41:06.965057 2022] [access_compat:error] [pid 3536:tid 139833757746944] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/log.js
[Sun Feb 27 19:41:06.965422 2022] [access_compat:error] [pid 3536:tid 139833766147840] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/core/js/setupchecks.js
[Sun Feb 27 19:41:06.965815 2022] [access_compat:error] [pid 3536:tid 139833774548736] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/files/js/jquery.fileupload.js
[Sun Feb 27 19:41:06.967768 2022] [access_compat:error] [pid 3536:tid 139834001225472] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/settings/js/vue-settings-nextcloud-pdf.js
[Sun Feb 27 19:41:06.984582 2022] [access_compat:error] [pid 3536:tid 139833749346048] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/serverinfo/img/app-dark.svg
[Sun Feb 27 19:41:06.985219 2022] [access_compat:error] [pid 3536:tid 139834001225472] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/core/img/facebook.svg
[Sun Feb 27 19:41:07.257843 2022] [access_compat:error] [pid 3536:tid 139833732544256] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Sun Feb 27 19:41:07.258117 2022] [access_compat:error] [pid 3536:tid 139833732544256] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/user_status/api
[Sun Feb 27 19:41:07.309431 2022] [access_compat:error] [pid 3536:tid 139833732544256] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Sun Feb 27 19:41:07.309685 2022] [access_compat:error] [pid 3536:tid 139833732544256] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/notifications/api
[Sun Feb 27 19:41:07.331388 2022] [access_compat:error] [pid 3536:tid 139833766147840] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/apps/user_status/heartbeat
[Sun Feb 27 19:41:07.331452 2022] [access_compat:error] [pid 3536:tid 139833766147840] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Sun Feb 27 19:41:07.339003 2022] [access_compat:error] [pid 3536:tid 139833715742464] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Sun Feb 27 19:41:07.339192 2022] [access_compat:error] [pid 3536:tid 139833715742464] [client 191.85.84.169:52890] AH01797: client denied by server configuration: /var/www/nextcloud/search

### Build Version

23.0.2.1

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Hi,

This is as it should be. Probably some blocked IP trying to reach different parts of the Nextcloud. 

I'm guessing you use fail2ban? If not, it could also be the built in brute force protection by Nextcloud causing it.

**Comment by sebadamus** [comment]
Hi, thanks! nop, not fail2ban.  Will try to investigate more... as also apache service wont start up unless I do it manually.  Dont worry, you can close my issue.  Thanks.

**Comment by enoch85** [comment]
Thanks for investigating!

If you find the real cause, please let me know.

**Comment by sebadamus** [comment]
> 

I reinstall Nextcloud Server with the install script you create on a new fresh virtualbox machine, the error continues to appear, anyway the nextcloud server seems to work without problem but with these errors in log file.

The IP addr you see in the errors, was my computer dynamic ip addr reaching the router addr where the linux machine running the vm behind NAT and tunneled 80,443 ports to it.... dont know why it gives these errors and anyway all seems to work fine.

If found anything else I will tell.

Thanks.

**Comment by rogerthn2019** [comment]
One more with newly installed Nextcloud Server using THE install script and AH01797 in error.log.
All seems to be working OK i.e. nothing critical but it is annoying.
Nextcloud 24.0.4
Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Server version: Apache/2.4.52 (Ubuntu)
Server built:   2022-06-14T12:30:21

**Comment by enoch85** [comment]
You're welcome to figure it out and post a PR in this repo so that everyone can enjoy the fix. :+1:

**Comment by rogerthn2019** [comment]
Seems to be resolved by update in /var/www/nextcloud/config/.htaccess and /mnt/ncdata/.htaccess
\<IfModule mod_access_compat.c>
Comments
`#  Order Allow,Deny`
`#  Deny from all`
`#  Satisfy All`
New line
`  Require all denied`
@sebadamus Maybe you can verify?

**Comment by VitalijusTelia** [comment]
I experiencing the same issue. NC updated to 25.0.2 installed via install script

**Comment by Weax** [comment]
I experiencing the same issue. NC updated to 25.0.2 installed via install script

**Comment by enoch85** [comment]
@Weax What does your Apache error log say?

**Comment by rogerthn2019** [comment]
After update to 25.0.2 I do have entries like below in Apache error log.
AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
client denied by server configuration: /var/www/nextcloud/dav

/mnt/ncdata/.htaccess # Generated by Nextcloud on 2022-12-27 15:02:12
Updated as above
#  Order Allow,Deny
#  Deny from all
#  Satisfy All
New line
  Require all denied

systemctl restart apache2.service
No entries in Apache error log

**Comment by enoch85** [comment]
OK, can someone send a PR to Nextcloud Server Core and fix this?

Thanks!
