### ISSUE TITLE
Installation of OVA file

### ISSUE THREAD

**Issue by breichardt** [nextcloud/vm#2250]
### Steps To Reproduce

1. import ova (40GB_Nextcloud-VM_www.hanssonit.se.ova)
2.  start the install and set keyboard and time zone. 
3. Your current version is still not compatible with the version required to run this script.     │
                                                           │                                                                                                │
                                                           │ To upgrade between major versions, please check this out:                                      │
                                                           │ https://shop.hanssonit.se/product/upgrade-between-major-owncloud-nextcloud-versions/           │
                                                           │                                                                                                │
                                                           │                                             <Ok>                                 
Click on the OK and get this:
/var/scripts/lib.sh: line 1406: [: : integer expression expected
/var/scripts/lib.sh: line 1444: [: : integer expression expected
Your data directory is invalid
Ensure there is a file called ".ocdata" in the root of the data directory.

Your data directory is not writable
Permissions can usually be fixed by giving the webserver write access to the root directory. See https://docs.nextcloud.com/server/23/go.php?to=admin-dir_permissions.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /var/www/nextcloud/lib/private/Console/Application.php:164
Stack trace:
#0 /var/www/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#1 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#2 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ -V failed

### Expected Result

To go smoothly

### Actual Result

/var/scripts/lib.sh: line 1406: [: : integer expression expected
/var/scripts/lib.sh: line 1444: [: : integer expression expected
Your data directory is invalid
Ensure there is a file called ".ocdata" in the root of the data directory.

Your data directory is not writable
Permissions can usually be fixed by giving the webserver write access to the root directory. See https://docs.nextcloud.com/server/23/go.php?to=admin-dir_permissions.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /var/www/nextcloud/lib/private/Console/Application.php:164
Stack trace:
#0 /var/www/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#1 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#2 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ -V failed

### Additional Context

I created a file ocdata and .ocdata in the directory of /var/www/nextcloud/data with both user/group as www-data.  I also tried the owership as root/www-data.
Still get the above message.

### Build Version

ubuntu 20.04.2 LTS Nextcloud40Gb

### Environment

By downloading the VM

### Environment Details

OS = ubuntu loaded on VM Workdataion 16

**Comment by UEMissionIT** [comment]
We are experiecing exact the same issue. No matter if using VMware ESXi, VMWare Player or other virtualization station. Please let us know if there is a solution or workaround

**Comment by Abarth91** [comment]
I have the same problem. Last week I also set up a new installation and there was no problem.

**Comment by enoch85** [comment]
Please try this:

1. Delete the VM
2. Import it again
3. Boot
4. When logged in, press CTRL+C
5. Type: `sudo zpool import -f ncdata`
6. Reboot
7. Use it as normal

That should work.

**Comment by enoch85** [comment]
This should now be fixed, uploaded new OVAs just recently.

**Comment by breichardt** [comment]
Your suggestions worked I am up and running.

 

Thanks,

 

_________________________________________________

Bob Reichardt CISSP 

***@***.***

817.478.0075
