### ISSUE TITLE
Bitwarden Install Script no longer valid

### ISSUE THREAD

**Issue by Abarth91** [nextcloud/vm#2252]
### Steps To Reproduce

1. Try to install Bitwarden via Menu (sudo bash /var/scripts/menu.sh)

### Expected Result

Installing Bitwarden

### Actual Result

Bitwarden will not be installed

### Screenshots, Videos, or Pastebins

Downloading the Bitwarden Menu...
Downloading the Bitwarden script...
Checking if Bitwarden is already installed...
RAM for Bitwarden OK! (7.81 GB)
CPU for Bitwarden OK! (2)
Specifying a certain user for Bitwarden: bitwarden...
Creating the Bitwarden service...
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|
Open source password management solutions
Copyright 2015-2022, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden
===================================================
**We have moved our self-hosted scripts to their own repository (https://github.com/bitwarden/self-host).  Your 'bitwarden.sh' script has been automatically upgraded. Please run it again.**
grep: /home/bitwarden/bwdata/config.yml: No such file or directory
grep: /home/bitwarden/bwdata/config.yml: No such file or directory
sed: can't read /home/bitwarden/bwdata/config.yml: No such file or directory
sed: can't read /home/bitwarden/bwdata/config.yml: No such file or directory
sed: can't read /home/bitwarden/bwdata/config.yml: No such file or directory
sed: can't read /home/bitwarden/bwdata/env/uid.env: No such file or directory
sed: can't read /home/bitwarden/bwdata/env/uid.env: No such file or directory
grep: /home/bitwarden/bwdata/config.yml: No such file or directory
sed: can't read /home/bitwarden/bwdata/config.yml: No such file or directory
sed: can't read /home/bitwarden/bwdata/env/global.override.env: No such file or directory

### Additional Context

Bitwarden installation script has been moved. The path in the following script must be adjusted.

https://github.com/nextcloud/vm/blob/master/apps/tmbitwarden.sh

Line 159:
curl_to_dir "https://raw.githubusercontent.com/bitwarden/server/master/scripts" "bitwarden.sh" "$BITWARDEN_HOME"
must be changed to
curl_to_dir "https://raw.githubusercontent.com/bitwarden/self-host/master" "bitwarden.sh" "$BITWARDEN_HOME"

### Build Version

23.0.2

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Thanks for posting!
