### ISSUE TITLE
deSEC Registration Script does not work correct

### ISSUE THREAD

**Issue by 19newbie87** [nextcloud/vm#2254]
### Steps To Reproduce

1. Go to ''
![image](https://user-images.githubusercontent.com/97949340/156881601-7729a2f3-ffa7-451a-850c-e0e769075e18.png)
"
2. Start the Script and typed in the domain name: ******
   was result in the following notification: 
![1](https://user-images.githubusercontent.com/97949340/156881703-a47b1fc2-a006-47c8-a63e-57b19ac36c2b.PNG)

3. 
![2](https://user-images.githubusercontent.com/97949340/156881713-f01be771-5b52-4cba-8a2b-178f58117b5b.PNG) -- choose ok.

4. after confirmation with ok
![3](https://user-images.githubusercontent.com/97949340/156881754-8d767768-9aa8-4225-98bf-9d389cdeca67.PNG)

the script will skip forward:

![4](https://user-images.githubusercontent.com/97949340/156881780-68dabfb2-f772-4297-9156-94f7f51b68bc.PNG)

There is no way to type in the Token after pressing OK. How can i type in the token and finish the set up?

### Expected Result

Log into my desec Account by using the token. 

### Actual Result

Skip over the Login input box and aks for automatic WAN IP (after pressing OK I got the error that the token is missing ...)

### Build Version

I downloaded today from https://shop.hanssonit.se/

### Environment

By using the scripts, By downloading the VM

**Comment by enoch85** [comment]
Thanks! This is now fixed, please confirm that it work as expected.
