### ISSUE TITLE
Using the VM behind nginx proxy manager

### ISSUE THREAD

**Issue by arsaboo** [nextcloud/vm#2257]
### Steps To Reproduce

I am currently using the docker installation and here's my config in NPM:

![image](https://user-images.githubusercontent.com/18319734/157697307-eab42365-e0ba-41e0-b606-761511e331e2.png)

The above works well. I am now trying to use the VM (primarily to use the elasticsearch feature). The installation and everything works fine, but I am not able to use it with NPM. Is there anyway to make the VM work with NPM (as I have other services that I am using with NPM). 

### Expected Result

I should be able to use NPM with Nextcloud. 

### Actual Result

Nextcloud does not work with NPM

### Build Version

23.0.2

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Hi,

Thanks for posting!

It's totally possible to use the VM behind any proxy, but you need to configure it correctly.

If you need support in setting this up, please check the forum, or our shop (hoover over the support tag for addresses).

**Comment by jason5545** [comment]
I use the script version and Nginx reverse proxy, it just works.


> ### Steps To Reproduce
> I am currently using the docker installation and here's my config in NPM:
> 
> ![image](https://user-images.githubusercontent.com/18319734/157697307-eab42365-e0ba-41e0-b606-761511e331e2.png)
> 
> The above works well. I am now trying to use the VM (primarily to use the elasticsearch feature). The installation and everything works fine, but I am not able to use it with NPM. Is there anyway to make the VM work with NPM (as I have other services that I am using with NPM).
> 
> ### Expected Result
> I should be able to use NPM with Nextcloud.
> 
> ### Actual Result
> Nextcloud does not work with NPM
> 
> ### Screenshots, Videos, or Pastebins
> _No response_
> 
> ### Additional Context
> _No response_
> 
> ### Build Version
> 23.0.2
> 
> ### Environment
> By downloading the VM
> 
> ### Environment Details
> _No response_

**Comment by arsaboo** [comment]
Do you have any references for configuring behind a proxy?

**Comment by enoch85** [comment]
Plenty. we even have as an option in our shop: https://shop.hanssonit.se/product/installation-of-nginx-reverse-proxy/
