### ISSUE TITLE
Is it possible to have a Proxmox VM image?

### ISSUE THREAD

**Issue by dienteperro** [nextcloud/vm#2258]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by enoch85** [comment]
There already is one in the TESTING folder. It's an old version but only like 1-2 months or so.

**Comment by p-bo** [comment]
@enoch85 do you plan to make new (test?) image there (i.e. for Proxmox) based on Ubuntu 22.04 as in case of images for other virt. platforms please?

**Comment by enoch85** [comment]
This is now live: https://www.hanssonit.se/nextcloud-vm/
