### ISSUE TITLE
VeraCrypt volumes must be unmounted before VeraCrypt upgrade

### ISSUE THREAD

**Issue by pq2** [nextcloud/vm#2259]
### Steps To Reproduce

Run the update.sh script when a veracrypt update is available.

### Expected Result

Veracrypt is updated.

### Actual Result

The following error message appears: `VeraCrypt volumes must be unmounted before upgrade` and veracrypt is not updated.

### Build Version

23.0.2

### Environment

By using the scripts

**Comment by szaimen** [comment]
Hi, thanks for the report! 
I'll have a look soon.
