### ISSUE TITLE
Disabled Redirection HTTP to HTTPS

### ISSUE THREAD

**Issue by sgermain90** [nextcloud/vm#2265]
<!--
Hello, could you help me to disable the http redirection to https, since I use Nginx Proxy Manager and from this console I obtain the certificate

Thanks

**Comment by sgermain90** [comment]
Hello, could you help me to disable the http redirection to https, since I use Nginx Proxy Manager and from this console I obtain the certificate

Thanks

**Comment by enoch85** [comment]
Hi,

You can forward the proxy to HTTPS and run self-signed on the backend. 

HTTPS all the way! <3
