### ISSUE TITLE
OVA 2TB Install Error: UserDeletedEvent fired without matching BeforeUserDeletedEvent

### ISSUE THREAD

**Issue by Pietro-Aretino** [nextcloud/vm#2268]
### Steps To Reproduce

1. Purchased and received 2TB OVA Image from T&H
2. Setup thin provisioned VM on ESXi 6.7.0 Update 3 (Build 17499825)
3. Went through installation wizard, no problems until I arrived to setup the "Web Admin".
4. Run through wizard to create Nextcloud Web Admin.
5. It begins to create my web admin with the password I provided for Nextcloud
6. It then attempts to delete the "ncadmin" but errors out.

### Expected Result

For the wizard to complete, setup the Web Admin for nextcloud with username and password provided and properly remove the "ncadmin" user.

### Actual Result

`Deleting ncadmin...
In UserDeletedFilesCleanupListener.php line 63:
UserDeletedEvent fired without matching BeforeUserDeletedEvent

user:delete <uid>

Sorry but something went wrong. Please report issue......
sudo -u www-data php /var/www/nextcloud/occ user:delete ncadmin failed`

### Screenshots, Videos, or Pastebins

![somethingwent wrong2](https://user-images.githubusercontent.com/28988728/160814886-7b9ffe26-1dae-4b68-8c07-5a253bc49476.png)

### Additional Context

ESXi 6.7.0 Update 3 (Build 17499825)

### Build Version

Latest

### Environment

By downloading the VM

### Environment Details

I purchased the 2TB Nextcloud OVA VM from _hansonit.se_

**Comment by enoch85** [comment]
Hi, this is an old bug which already is solved a long time ago in master.

Can you please give me your order ID so that I can send you a new version of the VM?

Ref: https://github.com/nextcloud/vm/issues/2163
