### ISSUE TITLE
delete user ncadmin failed during install

### ISSUE THREAD

**Issue by hottabasco** [nextcloud/vm#2272]
### Steps To Reproduce

Run a clean install of Ubuntu server 20.04
wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
sudo bash nextcloud_install_production.sh
Towards the end of the install process, after the reboot, the install script attempts to delete the user under which the install was running, it fails with error messages shown.

### Expected Result

expect the install script to complete without error messages

### Actual Result

nextcloud_install_production.sh fails with these error messages:

Deleting ncadmin...
In UserDeletedFilesCleanupListener.php line 63:
  UserDeletedEvent fired without matching BeforeUserDeletedEvent
user:delete <uid>
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ user:delete ncadmin failed

### Screenshots, Videos, or Pastebins

![Nextcloud install error](https://user-images.githubusercontent.com/115292/162757322-fe6e287e-f14a-434b-b285-29727038e5e6.PNG)

### Build Version

$OC_VersionString = '23.0.3'

### Environment

By using the scripts

### Environment Details

Ubuntu server 20.04, clean install
wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
sudo bash nextcloud_install_production.sh

**Comment by enoch85** [comment]
Thanks for posting. This is a bug in NC 23.0.3, that's why we didn't upgrade the VM to that version.

**Comment by enoch85** [comment]
You can read more here: https://github.com/nextcloud/server/issues/31092

**Comment by binojvijayakumar** [comment]
which is the version that would work with the script...??? --not-latest flag also downloads the 23.0.2 version, so that's not good...

**Comment by chrisbley** [comment]
same issue here. so... what are script install users supposed to do? when rebooting the server after error message and logging in, we'll be back at the setup script will be started automatically, and nextcloud is not up.

**Comment by binojvijayakumar** [comment]
> same issue here. so... what are script install users supposed to do? when rebooting the server after error message and logging in, we'll be back at the setup script will be started automatically, and nextcloud is not up.

for me, i didn't create a new admin user while running the production script... so, skipping the deletion process wouldn't have hurt me...

this is what i did... after running the production script, system reboots and login, enter the password for starting the startup script, but immediately press ctrl+c to cancel it... nano edit the startup script file (located in /var/scripts) and commented 5-6 lines that followed the script comment "# Delete old user"...

then ran the script manually (or exit and log back in to automatically run the script) and everything looks good till now...

**Comment by Sempro97** [comment]
Same here: https://pastebin.com/79XYf1UQ

1) Run the script https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh

2) Finish correctly the first part of installing

3) Rebooted the pc

4) During the installation i have change the password of sudo enabled user "hacker" and installation crash

**Comment by enoch85** [comment]
Have you considered donating for the work behind the script, or you just demand more free work? Just a side note but still.

I'm thinking of a workaround that will check if ncdmin exists and only then ask to change password. That would mean that script users could set their own user in the first part, and skip the second password change.

**To you that thinks the VM is setup even with the second part not finished - no, you have to start over completely. Start with a fresh VM/VPS and run the first part again.**

**Comment by enoch85** [comment]
Also, it would help to give your thumb up in the server issue.

**Comment by chrisbley** [comment]
Unfortunately, last week's workaround still doesn't work:
![image](https://user-images.githubusercontent.com/97885880/164453241-fa7fb949-791c-48b5-9e51-ef862f5b000e.png)

And I'd be more than willing to make use of Hansson's paid support to configure NcVM to work behind my reverse proxy, but I'd need to finish the script install successfully first. any chance? thank you!

**Comment by enoch85** [comment]
@chrisbley Since the fix I've installed several servers and it always worked. Are you sure that you use the latest of everything?

The VM should be NC 23.0.2 and the scripts should be the latest from master.

**Comment by chrisbley** [comment]
@enoch85 I'm applying the latest install script on a fresh Ubuntu 20.04 LTS (Server), fully updated. don't know what else I should use? only thing I'm wondering: at start I'm using my ubuntu user "chris" (with sudo permissions), later creating new user "ncadmin" following the script. after finishing first install script and rebooting, I'm logging in with user "chris" again, as when I'm using "ncadmin", the setup script won't autostart. the rest is just following the script. I don't see much space for making mistakes here.

**Comment by enoch85** [comment]
>  later creating new user "ncadmin" following the script. after finishing first install script and rebooting

Don't create a new user. Use `chris`.

**Comment by enoch85** [comment]
Hi again,

My bad. I tested another version of the script, not master.

Here you go, it's now fixed in the installer for the coming version: 

1. Install Ubuntu 22.04 server: 2 disks + OpenSSH-server.
2. `wget https://raw.githubusercontent.com/nextcloud/vm/UBUNTU-22.04/nextcloud_install_production.sh`
3. `sudo bash nextcloud_install_production.sh`
4. Enjoy!

_Originally posted by @enoch85 in https://github.com/nextcloud/vm/issues/2279#issuecomment-1106782963_

**Comment by chrisbley** [comment]
Thank you again - following your advice on not creating another user worked on 20.04, but I'll gladly try it on 22.04!

**Comment by chrisbley** [comment]
apologies for being a nuisance again! seems that the current installation script doesn't work on Ubuntu 22.04 yet, it requests 20.04. I could get around the first distribution check by disabling lines 122 and following, but then at "do you want to use all available space for your root drive" the process is getting stuck again.

**Comment by enoch85** [comment]
Did you copy and paste the commands from above?

Please note: `wget https://raw.githubusercontent.com/nextcloud/vm/`**UBUNTU-22.04**`/nextcloud_install_production.sh`

**Comment by chrisbley** [comment]
no, I took the script from here: https://github.com/nextcloud/vm
sorry again then, I'm too new on github, didn't realize there might be different places to look at within one repository!
