### ISSUE TITLE
collabora container startup command deprecated

### ISSUE THREAD

**Issue by mhazan01** [nextcloud/vm#2273]
### Steps To Reproduce

1. reboot vm after upgrade to 23.0.3
2. docker logs #collabora
3. see error about  -e "domain=$NCDOMAIN" option
4. remove #collabora container
5. start container without the -e "domain=$NCDOMAIN"
6. collabora container *seems* to start properly

### Expected Result

file opened in web browser

### Actual Result

error opening file in browser

### Build Version

22.0.3

### Environment

By using the scripts, By downloading the VM

### Environment Details

ubuntu 20.04
php 7.4.3

**Comment by mhazan01** [comment]
seems to be linked to this :
https://forum.collaboraonline.com/t/21-11-3-4-1-problem-with-multiple-domains/991
updated documentation :
https://sdk.collaboraonline.com/docs/installation/CODE_Docker_image.html

**Comment by enoch85** [comment]
Tested and works!

**Comment by enoch85** [comment]
Related: https://github.com/nextcloud/vm/issues/2149
