### ISSUE TITLE
don't remove ALL docker images when deploying the office script

### ISSUE THREAD

**Issue by KarelWintersky** [nextcloud/vm#2282]
### Steps To Reproduce

```
/bin/bash collabora_integrated.sh
```
removed all docker images/contaners 

WTF? 

### Expected Result

not this

### Actual Result

all docker images/contaners removed

### Screenshots, Videos, or Pastebins

```
root@wintersky:~/vm/apps# /bin/bash collabora_integrated.sh
Installing Collabora (Integrated)...
Press any key to continue. Press CTRL+C to abort
f42fcead371c
Deleted Containers:
f42fcead371c41bf92a6d5dbf9c74d82a5c1389b2f31c5e6f4ca6ace5500cfcd

Total reclaimed space: 30.6kB
Deleted Images:
untagged: mcr.microsoft.com/dotnet/runtime:6.0
untagged: mcr.microsoft.com/dotnet/runtime@sha256:a5c83e4f6c03d785c37eb06549f0ec5d0daa761e010805b0ad39f698d89d10c2
untagged: alpine:3.6
untagged: alpine@sha256:66790a2b79e1ea3e1dabac43990c54aca5d1ddf268d9a5a0285e4167c8b24475
untagged: collabora/code:latest
untagged: collabora/code@sha256:e8cf96a64a5e4ef0aa88523468b89fbd4c4a81b4038b05dd85c5538946e15cdb
deleted: sha256:91c8df4feb1bf1aaecd6988dd919ad708f8b8c0bfed4f669f40633916fd30129
deleted: sha256:e414a2746939c1d25343deec3e650c13be268bde3835a70894bdabd61dac6143
deleted: sha256:c6a2dc30d41efc176fd68d544c218af75fba6c0a3f58793b62d4f47c9ee00d24
deleted: sha256:d2f36e25e46769f19fcfdf952e7d83fa06052ee85b514f56fd9450276a18e048
deleted: sha256:10efeef134ca1d4d4e547075c7019e0dca7632f8e75e0c137a441c733d01b3c8
deleted: sha256:e4d2ca26bb6c152dc88c1eec290e639557140e8e31c100aa14435b24f84fff82
deleted: sha256:3e549931e0240b9aac25dc79ed6a6259863879a5c9bd20755f77cac27c1ab8c8
untagged: tyrrrz/discordchatexporter:latest
deleted: sha256:2699a734f95f3ce45f6f0d369a26213b103719fffa04dcf40262fabe7e24e0cb
deleted: sha256:5a80cd616592304e238dd541fcc5a1827eb51bdd4191cdff2521bc99ef3cedd9
deleted: sha256:334a99a7fc08e56325c5a0ebeee9b1bf87be7f168f24e0a31a396a823b72b8b5
deleted: sha256:69c9c5c99349aa1fb1e0f736d909a7dfa7aab63abb27792e8728fb0f45ac5c36
deleted: sha256:16889e77360b45b23036980ec04f34a21e620b412a7eeb8e526cd495825a256c
deleted: sha256:ecf5a8e6fee9242532c0525cbf245944fb2afdbd0f4fa20bfefd06ed16842c13
deleted: sha256:4dfba021bbd5e03d7e9472884607752eddfecd8365cf6b320635be9cea00f16a
deleted: sha256:e749028774269d4bd7ea17773294afa27168fe168d33cfcebb81dce149e22a10
deleted: sha256:55da6b697467c3539bf35ec82b424e2b06cf04e26713a39adf615dbf5c58f6f1
deleted: sha256:57158d6620e63c6f30aed865c50b4738f167d6c9cfd08cf318c85f274d304783
deleted: sha256:3fbd741c040d40ee1dd1bc9cc2ba7077fdbbbf7c0570ef092eddd5398bf2e131
deleted: sha256:1401df2b50d5de5a743b7bac3238ef3b7ce905ae39f54707b0ebb8eda3ab10bc

Total reclaimed space: 1.68GB
Total reclaimed space: 0B
Removing collabora.wintersky.ru from trusted domains...
/var/scripts/lib.sh: строка 1420: [: : ожидается целочисленное выражение
/var/scripts/lib.sh: строка 1458: [: : ожидается целочисленное выражение
Could not open input file: /var/www/nextcloud/occ
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ -V failed
```

### Build Version

23.0.2

### Environment

By using the scripts

### Environment Details

- Debian 11

**Comment by szaimen** [comment]
Basically we should prpbably improve docker_prune_this to really only prune a specific container or image that we want to remove and not all that are currently stopped.

Wdyt @enoch85 ?

**Comment by enoch85** [comment]
> Wdyt @enoch85?

Agree on that!

**Comment by szaimen** [comment]
okay, do you wanna create a PR then or shall I create a PR?

**Comment by enoch85** [comment]
@szaimen Would be super if you could make one. 

But first we need to merge the Ubuntu 22.04 PR to avoid conflicts. Want to do that today, or tomorrow.

**Comment by KarelWintersky** [comment]
Also, my nextcloud installed not in `/var/www/nextcloud/`...

**Comment by enoch85** [comment]
@KarelWintersky Then you're not running the VM. You run something else.

Please post the output of `ls -l /var/scripts`

**Comment by szaimen** [comment]
So I guess this can now be implemented? If yes I'll try to create a PR

**Comment by enoch85** [comment]
@szaimen Yes please.

**Comment by szaimen** [comment]
Will have a look 👍

**Comment by KarelWintersky** [comment]
> You run something else.

Yes. I'm trying use your scripts for install Collabora :)

**Comment by enoch85** [comment]
Oh ok! I figured as you were running Debian 11 that something was fishy here. :D

**Comment by szaimen** [comment]
I think that the function should be improved either way... I'll see how far I'll come :)

**Comment by enoch85** [comment]
@szaimen Agreed!

**Comment by KarelWintersky** [comment]
@enoch85 , The trouble is that the collaborator office in Nextcloud is broken. There is a task for this ( https://github.com/nextcloud/richdocuments/issues/2173 )

It doesn't work through docker, nor through a normal install running as a service. The javascript request just crashes on a timeout. It looks like the service is not responding.

I found your scripts, supposedly more correct - and tried to put the collabora office. 

Failed and the above bug got out in the process.

**Comment by szaimen** [comment]
Ah yes, seen that. I think in order to start correctly it needs a `occ richdocuments:activate-config` after the domain was set...

**Comment by szaimen** [comment]
Here is my attempt: https://github.com/nextcloud/vm/pull/2286

**Comment by enoch85** [comment]
@KarelWintersky Can you please test again?
