### ISSUE TITLE
Scripts menu.sh and update.sh fails to start

### ISSUE THREAD

**Issue by costib-ro** [nextcloud/vm#2284]
### Steps To Reproduce

1. SSH login
2. Become root with  `sudo -i`
3. Execute `bash /var/scripts/menu.sh` or `bash /var/scripts/update.sh` or `update_nextcloud`

### Expected Result

"Main menu dialogs" or "Update scripts" should start.

### Actual Result

Main menu and update scripts fails to start.

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/96431409/166553330-1214ca28-a0d8-4924-99c7-3a1836dfca1e.png)
![image](https://user-images.githubusercontent.com/96431409/166553355-19e8851d-972a-43e2-ac24-5dd68855ba34.png)
![image](https://user-images.githubusercontent.com/96431409/166553377-e01b4878-8c0f-47d2-8c59-33b85a6d1631.png)

### Additional Context

Last upgrade OK was on 10-April-2022 to Nextcloud 23.0.3.
I intend to upgrade this Nextcloud instance to 23.0.4 - "Stable" update channel.

### Build Version

Nextcloud HanssonIT VM 23.0.3

### Environment

By downloading the VM

### Environment Details

- Nextcloud HanssonIT VM 23.0.3
- 4 vCPU, 8GB RAM

**Comment by enoch85** [comment]
Thanks for posting! Will have a look!

**Comment by enoch85** [comment]
Should be fixed now, please try again.

**Comment by nr-plaxon** [comment]
Working now again. But latest LTS 20.04 is not supported anymore?

**Comment by costib-ro** [comment]
![image](https://user-images.githubusercontent.com/96431409/166558224-e8c98f73-6a1a-483e-afe8-e2dae9d4cb11.png)

**Comment by enoch85** [comment]
Sorry, just released a major change to master. Will fix, thanks for reporting!

**Comment by costib-ro** [comment]
OK, thanks but, should I revert now to my initial VM snapshot before starting upgrade procedure and wait for your fix?

**Comment by costib-ro** [comment]
One hour later, I've tried again and successfully upgraded to 23.0.4:
![image](https://user-images.githubusercontent.com/96431409/166568648-3f0abe46-f300-431a-99e1-6ff309995c95.png)
At the end I receive again the following message:
![image](https://user-images.githubusercontent.com/96431409/166568835-4287decc-6a30-4191-a314-14faa1ec77bb.png)
I go further and server makes a reboot, but not the upgrade.
After reboot I try to upgrade again just from curiosity(to 24.0.0) and the same reboot happens.
How it should work?

**Comment by enoch85** [comment]
It will run the update again. 

What you should do is to reinstall/uninstall automatic updates. It's also done with the menu script.
