### ISSUE TITLE
Ubuntu 22: Syntax error on install_production script, line 36 "(" unexpected

### ISSUE THREAD

**Issue by mschewie5** [nextcloud/vm#2288]
### Steps To Reproduce

Installed Ubuntu Server 22.04 iso inside a normal Proxmox VM, updated, downloaded script, run script.

### Expected Result

normal install procedure

### Actual Result

nextcloud_install_production.sh: 36: Syntax error: "(" unexpected
I*m only beginner in scripting and don't know the syntax for this

### Screenshots, Videos, or Pastebins

![grafik](https://user-images.githubusercontent.com/24593723/166826979-9712058d-7459-4ae8-9735-cdc267d955d6.png)

### Additional Context

First I needed to change Line 23 from
 if [ "$(dpkg-query -W -f='${Status}' "curl" 2>/dev/null | grep -c "ok installed")" == "1" ]
to 
if [ "$(dpkg-query -W -f='${Status}' "curl" 2>/dev/null | grep -c "ok installed")" = "1" ] 
so only one equal sign.

### Build Version

None

### Environment

By using the scripts

**Comment by enoch85** [comment]
Thanks for testing! Will have a look later today.

Please report anything else you can find 🙏

**Comment by mschewie5** [comment]
Hi, I tried the new version, but no success. I also tried the same on a virtualbox vm on my local pc. I also tried to unminimize the ubuntu server install. But I get the syntax error on line 36.

**Comment by enoch85** [comment]
The line you are referring to is this one: https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L36

Need to have a look at that.

**Comment by enoch85** [comment]
Sorry, can't reproduce this in current master.
