### ISSUE TITLE
Problem with PHP

### ISSUE THREAD

**Issue by amurdock37** [nextcloud/vm#2290]
### Steps To Reproduce

apt-get install -y php8.1-fpm php8.1-intl php8.1-ldap php8.1-imap php8.1-gd php8.1-pgsql php8.1-curl php8.1-xml php8.1-zip php8.1-mbstring php8.1-soap php8.1-gmp php8.1-bz2 php8.1-bcmath php-pear 

### Expected Result

apt-get install -y php8.1-fpm php8.1-intl php8.1-ldap php8.1-imap php8.1-gd php8.1-pgsql php8.1-curl php8.1-xml php8.1-zip php8.1-mbstring php8.1-soap php8.1-gmp php8.1-bz2 php8.1-bcmath php-pear failed

### Actual Result

E: Unable to locate package php8.1-fpm
E: Couldn't find any package by glob 'php8.1-fpm'
E: Couldn't find any package by regex 'php8.1-fpm'
E: Unable to locate package php8.1-intl
E: Couldn't find any package by glob 'php8.1-intl'
E: Couldn't find any package by regex 'php8.1-intl'
E: Unable to locate package php8.1-ldap
E: Couldn't find any package by glob 'php8.1-ldap'
E: Couldn't find any package by regex 'php8.1-ldap'
E: Unable to locate package php8.1-imap
E: Couldn't find any package by glob 'php8.1-imap'
E: Couldn't find any package by regex 'php8.1-imap'
E: Unable to locate package php8.1-gd
E: Couldn't find any package by glob 'php8.1-gd'
E: Couldn't find any package by regex 'php8.1-gd'
E: Unable to locate package php8.1-pgsql
E: Couldn't find any package by glob 'php8.1-pgsql'
E: Couldn't find any package by regex 'php8.1-pgsql'
E: Unable to locate package php8.1-curl
E: Couldn't find any package by glob 'php8.1-curl'
E: Couldn't find any package by regex 'php8.1-curl'
E: Unable to locate package php8.1-xml
E: Couldn't find any package by glob 'php8.1-xml'
E: Couldn't find any package by regex 'php8.1-xml'
E: Unable to locate package php8.1-zip
E: Couldn't find any package by glob 'php8.1-zip'
E: Couldn't find any package by regex 'php8.1-zip'
E: Unable to locate package php8.1-mbstring
E: Couldn't find any package by glob 'php8.1-mbstring'
E: Couldn't find any package by regex 'php8.1-mbstring'
E: Unable to locate package php8.1-soap
E: Couldn't find any package by glob 'php8.1-soap'
E: Couldn't find any package by regex 'php8.1-soap'
E: Unable to locate package php8.1-gmp
E: Couldn't find any package by glob 'php8.1-gmp'
E: Couldn't find any package by regex 'php8.1-gmp'
E: Unable to locate package php8.1-bz2
E: Couldn't find any package by glob 'php8.1-bz2'
E: Couldn't find any package by regex 'php8.1-bz2'
E: Unable to locate package php8.1-bcmath
E: Couldn't find any package by glob 'php8.1-bcmath'
E: Couldn't find any package by regex 'php8.1-bcmath'

### Build Version

24.0.0

### Environment

By using the scripts

### Environment Details

Ubuntu 20.0.4 LTS
Synology VMM

**Comment by enoch85** [comment]
Hi, this is not a bug. Ubuntu 20.04 doesn't support PHP 8.1.

You can either upgrade to 22.04, or [check this out](https://shop.hanssonit.se/product/upgrade-php-version-including-dependencies/).

**Comment by enoch85** [comment]
New VMs are now released, please try that instead.
