### ISSUE TITLE
Warning/error during setup script on disk access in dm-4

### ISSUE THREAD

**Issue by marcus905** [nextcloud/vm#2294]
### Steps To Reproduce

While undergoing the install script, the system will reach a point where this warning starts appearing in the middle of the operation log on screen.

### Expected Result

There should be no error.

### Actual Result

Intermittently this error appears, afterwards scripts start failing.
![image](https://user-images.githubusercontent.com/392762/167145884-10b2ec23-8be1-4e23-94b9-5f168a536efc.png)

### Additional Context

The system is a VM in a Proxmox environment. No other VMs in the same server experience this

### Build Version

23.0.1

### Environment

By downloading the VM

**Comment by enoch85** [comment]
This is something in Ubuntu or your local hardware. Please get better disks and try again.

You could also report this upstream (to Ubuntu)

**Comment by enoch85** [comment]
Btw, THANKS for reporting. :)

**Comment by marcus905** [comment]
Hi,

Sadly it's not the disks, they've been tested and all other VMS in the same
server are ok and have no issue, and it's not Ubuntu, as if I recreate a VM
and setup the VM myself I have no error.

Do you have anything to suggest?

Thanks!

**Comment by enoch85** [comment]
I've seen it in older versions of Ubuntu, like 16.04 and 18.04. It's gotten better in 20.04 though. On servers with "proper" disks I've never seen it.

My best guess is therefore slow disks with poor I/O.

**Comment by marcus905** [comment]
That is very weird.

The server is on nvme Intel Enterprise SSDs so anything but slow.

Do you have a v24 VM based on 22.04 so as to see whether it's better with
the newer version?

**Comment by enoch85** [comment]
We will release Ubuntu 22.04 soon, just need to find the time. 

Next week maybe. 

Until then, you can try install by the scripts here in this repo, using Ubuntu 22.04. It would really help to see if you can find more bugs so that we can find them before a new release.
