### ISSUE TITLE
[FIXED] Apache not starting after Activate TLS

### ISSUE THREAD

**Issue by tasover** [nextcloud/vm#2296]
### Steps To Reproduce

1) Activate TLS
2) Apache will not start and show the following error on error.log

### Expected Result

To be enabled the Let's encrypt Certificate

### Actual Result

/var/log/apache2/error.log

[Fri May 06 14:41:22.984949 2022] [mpm_event:notice] [pid 1032:tid 140195116078976] AH00489: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 configured -- resuming normal operations
[Fri May 06 14:41:22.987069 2022] [core:notice] [pid 1032:tid 140195116078976] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 06 14:46:02.418456 2022] [mpm_event:notice] [pid 1032:tid 140195116078976] AH00492: caught SIGWINCH, shutting down gracefully
[Fri May 06 14:46:02.590431 2022] [ssl:emerg] [pid 1614:tid 140194689640320] AH02407: "SSLOpenSSLConfCmd DHParameters /etc/letsencrypt/live/YOUR_NEXTCLOUDDOMAIN/dhparam.pem" failed for **YOUR_NEXTCLOUDDOMAIN**:443
[Fri May 06 14:46:02.590472 2022] [ssl:emerg] [pid 1614:tid 140194689640320] AH02311: Fatal error initialising mod_ssl, exiting. See /var/log/apache2/error.log for more information
AH00016: Configuration Failed

### Additional Context

I bypassed the issue when commented the following site:

/etc/apache2/sites-enabled/YOUR_NEXTCLOUDDOMAIN.conf

Line:
#    SSLOpenSSLConfCmd DHParameters /etc/letsencrypt/live/YOUR_NEXTCLOUDDOMAIN/dhparam.pem

### Build Version

24.0.0

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04
CPU: 4C / 8GB Ram

**Comment by enoch85** [comment]
Super, great info! Now we have a real test case.

Thanks!!

**Comment by enoch85** [comment]
This is now fixed, please try again and report back!

**Comment by xcadmin** [comment]
Fixed, but failing when generating cert for OpenOffice install and talk.also only got a A when doing the nextcloud security scan with Ubuntu server 22.04 lts. said :(The X-Download-Options response header instructs Internet Explorer not to open the file directly but to offer it for download first. This mitigates some potential Social Engineering attacks).
Using the nextcloud_install_production.sh other that that, everything else installs fine.
Just mentioning the errors I get on my side.
*Will donate to this project,thanks for making this script and making nextcloud Easier to install.

**Comment by enoch85** [comment]
OK, will have to make a real fix for this. Opening this issue again until we found one.

Regarding "The X-Download-Options response header instructs Internet Explorer not to open the file directly but to offer it for download first." - could you please test several browsers, is it only Internet Explorer that has this issue?

Thanks for reporting!

**Comment by xcadmin** [comment]
Sorry for only replying now.I have "scrapped" my nextcloud installation on the dell server.will install everything from fresh again and will reinstall wimdows 11 on the laptop.will test and let you know.tx

**Comment by enoch85** [comment]
This is now fixed in all the files (apps)

**Comment by enoch85** [comment]
Please open a seperate issue for your other issue you had.

Thanks!
