### ISSUE TITLE
Fix DHParams in openssl 3.0.2

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2297]
DHparams is deprecated in openssl 3.0.2.

Find out what replaces it. https://www.openssl.org/docs/man3.0/man7/migration_guide.html

>Deprecated i2d and d2i functions for low-level key types
>
>Any i2d and d2i functions such as d2i_DHparams() that take a low-level key type have been deprecated. Applications should instead >use the [OSSL_DECODER(3)](https://www.openssl.org/docs/man3.0/man3/OSSL_DECODER.html) and [OSSL_ENCODER(3)]>(https://www.openssl.org/docs/man3.0/man3/OSSL_ENCODER.html) APIs to read and write files. See ["Migration" in d2i_RSAPrivateKey(3)](https://www.openssl.org/docs/man3.0/man3/d2i_RSAPrivateKey.html) for further details.

**Comment by tasover** [comment]
needs fix also on the collabora docker installation process.
When create the configuration file to apache2

**Comment by small1** [comment]
This should probably work to use instead:

openssl genpkey -genparam -algorithm DH -out dhparameter.pem -pkeyopt dh_paramgen_prime_len:2048 -pkeyopt dh_paramgen_type:1

openssl genpkey -paramfile dhparameter.pem  -out dhkey.pem

**Comment by enoch85** [comment]
```
root@test:~# openssl genpkey -genparam -algorithm DH -out dhparameter.pem -pkeyopt dh_paramgen_prime_len:2048 -pkeyopt dh_paramgen_type:1
genpkey: Error setting dh_paramgen_type:1 parameter:
4067BA729C7F0000:error:1C880106:Provider routines:dh_gen_common_set_params:passed invalid argument:../providers/implementations/keymgmt/dh_kmgmt.c:535:
```
```
root@test:~# openssl genpkey -paramfile dhparameter.pem -out dhkey.pem
Can't open parameter file dhparameter.pem
4037FFF0F17F0000:error:80000002:system library:BIO_new_file:No such file or directory:../crypto/bio/bss_file.c:67:calling fopen(dhparameter.pem, r)
4037FFF0F17F0000:error:10000080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:75:
```

**Comment by small1** [comment]
Simpler variant: openssl genpkey -genparam -algorithm DH -out dhparameter.pem -pkeyopt dh_paramgen_prime_len:2048

**Comment by enoch85** [comment]
Even simpler: `openssl dhparam -out dhparam.pem 2048`

Tested and works!

**Comment by enoch85** [comment]
Fixed.
