### ISSUE TITLE
docker fulltextsearch can't install

### ISSUE THREAD

**Issue by tasover** [nextcloud/vm#2299]
### Steps To Reproduce

Install FullTextSearch from the script

### Expected Result

working FullTextSearch

### Actual Result

vm.max_map_count = 512000
Using default tag: latest
latest: Pulling from opensearchproject/opensearch
8de5b65bd171: Pull complete 
e9d0eac44ca0: Pull complete 
91d10001aa17: Pull complete 
fb855c41e959: Pull complete 
4f4fb700ef54: Pull complete 
7484278feb0d: Pull complete 
148f5d343b8a: Pull complete 
Digest: sha256:5acd42d84d0dd4910c8a98ff097b0e473525f5489db6d6a363e408c557083107
Status: Downloaded newer image for opensearchproject/opensearch:latest
docker.io/opensearchproject/opensearch:latest
Certificate request self-signature ok
subject=C = CA, ST = NEXTCLOUD, L = VM, O = OPENSEARCH, OU = FTS, CN = ADMIN
Certificate request self-signature ok
subject=C = CA, ST = NEXTCLOUD, L = VM, O = OPENSEARCH, OU = FTS, CN = YOUR_NEXTCLOUD_DOMAIN
Certificate request self-signature ok
subject=C = CA, ST = NEXTCLOUD, L = VM, O = OPENSEARCH, OU = FTS, CN = CLIENT
**mv: cannot stat 'root-ca.srl': No such file or directory**
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
**bash opensearch_certs.sh failed**
Posting notification to users that are admins, this might take a while...
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to: nxadmin

### Build Version

24.0.0

### Environment

By using the scripts

**Comment by enoch85** [comment]
@Ark74 can you please have a look?

**Comment by Ark74** [comment]
It is due to jammy's openssl behavior change due to mayor version update.

**Comment by Ark74** [comment]
Submitted #2300

**Comment by enoch85** [comment]
This should now be fixed. @tasover please try again.
