### ISSUE TITLE
Trusted IP

### ISSUE THREAD

**Issue by ezraholm50** [nextcloud/vm#23]
2 users @ IRC told me the trusted IP in config.php isn't setup properly.
Noticed it myself yesterday with installing.

**Comment by enoch85** [comment]
@ezraholm50 Great! If you find the bug (if it exists on ownCloud), please make a PR there as well. Thanks!

**Comment by enoch85** [comment]
Just installed Nextcloud on a new VM. The trusted IP settings are set in the startup-script, and if the user don't run it it will be untrusted. So this is not a bug, it's a user error.
