### ISSUE TITLE
Should we build `coturn` for Ubuntu 22.04?

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2302]
https://paul.totterman.name/posts/coturn-ubuntu-jammy/

cc @morph027 @szaimen

**Comment by enoch85** [comment]
Reason: `apt install coturn` doesn't work, as of now. (Maybe later, but who knows :man_shrugging:)

**Comment by enoch85** [comment]
Current bug: https://bugs.launchpad.net/ubuntu/+source/coturn/+bug/1967018

**Comment by morph027** [comment]
The patch looks, i can try to add a package repo.

**Comment by enoch85** [comment]
Thanks @morph027 Just as a temporary solution until it's released with Ubuntu.

**Comment by morph027** [comment]
:arrow_right: https://gitlab.com/packaging/coturn
