### ISSUE TITLE
Ubuntu 22.04: Apache2 doesn't start after initially running NextCloud VM script update

### ISSUE THREAD

**Issue by MatrixMagician** [nextcloud/vm#2304]
### Steps To Reproduce

1. Upgrade from Ubuntu 20.04 to Ubuntu 22.04
2. Apache doesn't start due to #2296
3. Instead of following workaround, decide to run "sudo bash /var/scripts/update.sh"
4. Re-compilation of a wide variety of components happens
5. Update fails due to the following error:

_dpkg-query: no packages found matching php-acpu
dpkg-query: no packages found matching php8.1-apcu
/var/scripts/nextcloud_update.sh: line 448: [: : integer expression expected
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xeu apache2.service" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart apache2.service failed
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20210902/redis.so (/usr/lib/php/20210902/redis.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/redis.so.so (/usr/lib/php/20210902/redis.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0_

### Expected Result

Update script to run successfully

### Actual Result

Update script fails due to Apache2 not starting.  The error snippet below:

[Tue May 10 00:03:02.710554 2022] [ssl:emerg] [pid 136430:tid 139712646748032] AH02407: "SSLOpenSSLConfCmd DHParameters /etc/letsencrypt/live/straylight.nsupdate.info/dhparam.pem" failed for straylight.nsupdate.info:443
[Tue May 10 00:03:02.710602 2022] [ssl:emerg] [pid 136430:tid 139712646748032] AH02312: Fatal error initialising mod_ssl, exiting.

### Additional Context

I did run the following to install PHP8 as this is a prerequisite now (I used to run PHP7.4):
sudo apt install -y php8.1-fpm php8.1-intl php8.1-ldap php8.1-imap php8.1-gd php8.1-pgsql php8.1-curl php8.1-xml php8.1-zip php8.1-mbstring php8.1-soap php8.1-gmp php8.1-bz2 php8.1-bcmath php-pear

### Build Version

23.0.2

### Environment

By using the scripts

### Environment Details

 NUC8i3BEH
Version J72753-306
CPU
    4x Intel(R) Core(TM) i3-8109U CPU @ 3.00GHz
RAM 16 GB

**Comment by MatrixMagician** [comment]
Hello again,
I followed the workaround to comment the following line in "/etc/apache2/sites-enabled/YOUR_NEXTCLOUDDOMAIN.conf":

SSLOpenSSLConfCmd DHParameters /etc/letsencrypt/live/YOUR_NEXTCLOUDDOMAIN/dhparam.pem

This allowed Apache to start again.  I am unsure if this was a good or the right thing.
However, the site is inaccessible due to a HTTP 503 error.

**Comment by MatrixMagician** [comment]
Hello again,
I fixed the PHP Redis module issue as it was not installed with PHP 8.1.  However, the issue is now with the PHP8.1-FPM. 
It is running but my NextCloud instance is still expecting the PHP7.4-FPM instead (that is not running anymore due to the PHP 8.1 upgrade).  I am going to attempt to fix this.  Thanks.

**Comment by enoch85** [comment]
Hi,

Thanks for posting! 👍🏻

Everything is working as expected as long as you do it right. We tested several servers with older PHP, and newer PH and none of them failed.

If you need help upgrading PHP, you can have a look at this package: https://shop.hanssonit.se/product/upgrade-php-version-including-dependencies/

**Comment by MatrixMagician** [comment]
Hi enoch85,
Thanks for the offer.  I did get it up-and-running in the end after ensuring that Redis was running with the correct permissions and installing all the php modules.
It seems to run well thus far.  Thanks again.
