### ISSUE TITLE
Change repo for facerecognition

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2306]
@szaimen Would be nice if you could have a look at this since you implemented it:

```
echo "deb https://repo.delellis.com.ar jammy jammy" > /etc/apt/sources.list.d/20-pdlib.list
wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
```

Please keep https://github.com/nextcloud/vm/issues/2292 in mind.

My idea of fixing `apt-key`: https://github.com/nextcloud/vm/commit/11e637d49f163d3dc20f1ac462044a8082603d70 (but use `$DISTRO` instead of sourcing `lsb_release`).

Original post: https://github.com/matiasdelellis/facerecognition/issues/570#issuecomment-1123058102

**Comment by matiasdelellis** [comment]
Hi both,
Except some Ubuntu warnings against the repository (that I want to check later), this seems to be ready.. The package to install is now `php8.1-pdlib` 😉 

Thanks for everything,
Regards,
matias

**Comment by enoch85** [comment]
This will be fixed when we merge the apt-key fix in this repo.
