### ISSUE TITLE
Mail app not shown on APPs

### ISSUE THREAD

**Issue by tasover** [nextcloud/vm#2309]
### Steps To Reproduce

1. Go to 'Apps'
2. Search for Mail

### Expected Result

show mail app

https://apps.nextcloud.com/apps/mail

### Actual Result

Doesn't show Mail on hosted nextcloud 24

<img width="1122" alt="Screenshot 2022-05-11 at 12 45 39 PM" src="https://user-images.githubusercontent.com/105101075/167821198-c89f7e32-775e-41cc-801a-64befa9de235.png">

### Build Version

24.0.0

### Environment

By using the scripts

**Comment by enoch85** [comment]
Please have a look at: https://github.com/nextcloud/mail/issues/6414

Maybe it's not supported in NC 24 yet, and in that case the only thing you have to do is wait. :)
