### ISSUE TITLE
[Stripped Down VM image]Security scan and app updates assume I am running an older version of NC

### ISSUE THREAD

**Issue by minnixtx** [nextcloud/vm#2315]
### Steps To Reproduce

1. Go to 'https://scan.nextcloud.com/'
2. Click on 'Scan'
3. Reports back 'NOT on latest patch level'

### Expected Result

You are running 'Nextcloud Hub II 23.0.4'

### Actual Result

X NOT on latest patch level
Running Nextcloud 21.0.5.1

### Screenshots, Videos, or Pastebins

![Screen Shot 2022-05-12 at 11 31 15 AM](https://user-images.githubusercontent.com/61262716/168124375-8fb56311-ac18-4795-87a0-69af94e7cb31.png)
![Screen Shot 2022-05-12 at 11 31 29 AM](https://user-images.githubusercontent.com/61262716/168124393-54605fa9-4fb8-40a1-99ad-8a3ef3567279.png)
![Screen Shot 2022-05-12 at 11 31 49 AM](https://user-images.githubusercontent.com/61262716/168124411-422b8239-b75b-4858-b493-4bceec0d8482.png)

### Additional Context

Some apps believe I am running an earlier version of NC than I actually am as well. Passwords app gives me this response under Administration > Passwords "You are using a legacy support release of the passwords app. The developers do not provide support for legacy support releases. Upgrade your server to use the regular version.

### Build Version

23.0.4

### Environment

By downloading the VM

### Environment Details

Proxmox VE 7.2
2 vCores
4GB RAM

**Comment by enoch85** [comment]
This is not an error with the VM, but the scan.nextcloud.com tool. It's always been a bit buggy actually.

Thanks for reporting though!
