### ISSUE TITLE
VM appliance installation fails - Temporary-fix-begining

### ISSUE THREAD

**Issue by IdefixRC** [nextcloud/vm#2320]
### Steps To Reproduce

Hi,

1. Downloaded the ova appliance from: https://www.hanssonit.se/nextcloud-vm/
2. Imported it into ESXi 6.7
3. Start-up and start script runs
4. Post Keyboard and Timezone -> Error, failed to download temporary-fix-begining
5. Followed instructions "sudo curl etc" to download the script
6. script download error: py not installed
7. followed the instructions to install py
8. renewed curl throws DepreciationWarning: Using or importing ABCs from 'collections' instead of from collections.abc is deprecated since Python 3.3, and in 3.9 it will stop working
9. ran install script again -> steps repeat from 3 in same fashion as above, unable to install nextcloud

Update: Found that the instructions in the script had a typo. The correct filename is temporary-fix-beginning.sh (double n).
However, running it again resulted in the same outcome (ran it also without |php|py to see if the script is correctly displayed and it is).

Thanks for the help

### Expected Result

.

### Actual Result

.

### Build Version

23.0.2

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Thanks! Will fix this!

**Comment by IdefixRC** [comment]
Thanks! 
Any tip in the meantime on how I can proceed with the install?

**Comment by enoch85** [comment]
It's fixed now, please delete the old VM and import it again.

Thanks!

**Comment by enoch85** [comment]
Tested and works.

**Comment by IdefixRC** [comment]
Thanks
