### ISSUE TITLE
Collabora can't be re-installed since docker image isn't removed

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2321]
I think this is linked to the change you made before @szaimen, not running `system prune`

**Comment by enoch85** [comment]
Please also check OnlyOffice.

**Comment by enoch85** [comment]
I think this is the commit that made it bug out: https://github.com/nextcloud/vm/commit/89ac5abb89f479f39b8d90391d516b870914d30b

**Comment by szaimen** [comment]
I'll see if I can reproruce this and how to fix it 👍
