### ISSUE TITLE
systemctl restart php8.1-fpm.service failed

### ISSUE THREAD

**Issue by danjoannis** [nextcloud/vm#2327]
### Steps To Reproduce

1. Deploy fresh Ubuntu 22.04 server minimal LTS (Hyper-V FYI)
2. wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
3. sudo bash nextcloud_install_production.sh
4. Don't create new user (use current Ubuntu user)
5. Use 1 disk
6. Fails during install/config of apache and PHP

### Expected Result

Expect setup to complete until prompt to restart.

### Actual Result

The nextcloud_install_production.sh script fails at the "Enabling HTTP/2 server wide..." step with this ere:

Enabling HTTP/2 server wide...
/etc/apache2/mods-available/http2.conf was successfully created
Enabling module http2.
To activate the new configuration, you need to run:
  systemctl restart apache2
Job for php8.1-fpm.service failed.
See "systemctl status php8.1-fpm.service" and "journalctl -xeu php8.1-fpm.service" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart php8.1-fpm.service failed

### Screenshots, Videos, or Pastebins

Creating config file /etc/php/8.1/mods-available/mbstring.ini with new version
Processing triggers for php8.1-fpm (8.1.2-1ubuntu2) ...
Job for php8.1-fpm.service failed.
See "systemctl status php8.1-fpm.service" and "journalctl -xeu php8.1-fpm.service" for details.
invoke-rc.d: initscript php8.1-fpm, action "restart" failed.
× php8.1-fpm.service - The PHP 8.1 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php8.1-fpm.service; enabled; vendor preset: enabled)
     Active: failed (Result: start-limit-hit) since Tue 2022-05-17 14:04:22 UTC;17ms ago
       Docs: man:php-fpm8.1(8)
    Process: 24129 ExecStart=/usr/sbin/php-fpm8.1 --nodaemonize --fpm-config /etc/php/8.1/fpm/php-fpm.conf (code=exited, status=0/SUCCESS)
    Process: 24132 ExecStartPost=/usr/lib/php/php-fpm-socket-helper install /run/php/php-fpm.sock /etc/php/8.1/fpm/pool.d/www.conf 81 (code=exited, status=0/SUCCESS)
    Process: 24722 ExecStopPost=/usr/lib/php/php-fpm-socket-helper remove /run/php/php-fpm.sock /etc/php/8.1/fpm/pool.d/www.conf 81 (code=exited, status=0/SUCCESS)
   Main PID: 24129 (code=exited, status=0/SUCCESS)
     Status: "Ready to handle connections"
        CPU: 20ms

May 17 14:04:20 cloud systemd[1]: Starting The PHP 8.1 FastCGI Process Manager...
May 17 14:04:20 cloud systemd[1]: Started The PHP 8.1 FastCGI Process Manager.
May 17 14:04:22 cloud systemd[1]: Stopping The PHP 8.1 FastCGI Process Manager...
May 17 14:04:22 cloud systemd[1]: php8.1-fpm.service: Deactivated successfully.
May 17 14:04:22 cloud systemd[1]: Stopped The PHP 8.1 FastCGI Process Manager.
May 17 14:04:22 cloud systemd[1]: php8.1-fpm.service: Start request repeated too quickly.
May 17 14:04:22 cloud systemd[1]: php8.1-fpm.service: Failed with result 'start-limit-hit'.
May 17 14:04:22 cloud systemd[1]: Failed to start The PHP 8.1 FastCGI Process Manager.
dpkg: error processing package php8.1-fpm (--configure):
 installed php8.1-fpm package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Processing triggers for php8.1-cli (8.1.2-1ubuntu2) ...
Errors were encountered while processing:
 php8.1-fpm
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)

### Build Version

24.0.0

### Environment

By using the scripts

### Environment Details

- Ubuntu 22.04 LTS server minimal
- 4GB RAM
- 4 vCPU
- Hyper-V Gen 2

**Comment by danjoannis** [comment]
Right - during Ubuntu setup, I created an account (cloud).  During the Nextcloud setup script, it prompts either to use current user (cloud) or create ncadmin. I selected "no" so as to not create another user. I included this detail to help guide reproduction of the issue.

**Comment by enoch85** [comment]
Thanks, but I can't reproduce.

```
No VM guests are running outdated hypervisor (qemu) binaries on this host.
Enabling conf php8.1-fpm.
To activate the new configuration, you need to run:
  systemctl reload apache2
Enabling HTTP/2 server wide...
/etc/apache2/mods-available/http2.conf was successfully created
Enabling module http2.
To activate the new configuration, you need to run:
  systemctl restart apache2
Getting current PHP-version...
PHPVER=8.1
Automatically configures pm.max_children for php-fpm...
pm.max_children was set to 32
dpkg-query: no packages found matching qemu-guest-agent
[⣾⣽⣻⣾⣽⣻]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  liburing2
The following NEW packages will be installed:
  liburing2 qemu-guest-agent
0 upgraded, 2 newly installed, 0 to remove and 29 not upgraded.
Need to get 263 kB of archives.
After this operation, 902 kB of additional disk space will be used.
Get:1 http://se.archive.ubuntu.com/ubuntu jammy/main amd64 liburing2 amd64 2.1-2build1 [10.3 kB]
Get:2 http://se.archive.ubuntu.com/ubuntu jammy/universe amd64 qemu-guest-agent amd64 1:6.2+dfsg-2ubuntu6 [252 kB]
Fetched 263 kB in 0s (1707 kB/s)      
Selecting previously unselected package liburing2:amd64.
(Reading database ... 74053 files and directories currently installed.)
Preparing to unpack .../liburing2_2.1-2build1_amd64.deb ...
Unpacking liburing2:amd64 (2.1-2build1) ...
Selecting previously unselected package qemu-guest-agent.
Preparing to unpack .../qemu-guest-agent_1%3a6.2+dfsg-2ubuntu6_amd64.deb ...
Unpacking qemu-guest-agent (1:6.2+dfsg-2ubuntu6) ...
Setting up liburing2:amd64 (2.1-2build1) ...
Setting up qemu-guest-agent (1:6.2+dfsg-2ubuntu6) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Scanning processes...                                                                                                                                             
Scanning linux images...                                                                                                                                          

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
Synchronizing state of qemu-guest-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable qemu-guest-agent
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
Fetching the latest Nextcloud version...
24.0.0
Downloading nextcloud-24.0.0...
Testing if network is OK...
Checking connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  117M  100  117M    0     0  34.8M      0  0:00:03  0:00:03 --:--:-- 34.8M
Checking SHA256 checksum...
nextcloud-24.0.0.tar.bz2: OK
```

**Comment by enoch85** [comment]
Please try again with a clean installation from step 1.

**Comment by danjoannis** [comment]
This is how I reproduced it (3 ways):
1. Clean Ubuntu Desktop 22.04 (not official way, so I didn't mention this)
2. Clean Ubuntu Server 22.04
3. Clean Ubuntu Server 22.04 + apt-get upgrade before running script

I'm using Hyper-V and have a fresh snapshot from before running the script. Reproduced multiple times from this Snapshot.

I will attempt using VirtualBox and another clean install, will advise.

**Comment by enoch85** [comment]
I've done around 10 production installations so far on different systems, none of them failed like you described.

Would be nice if you could give steps that I actually could reproduce.

**Comment by enoch85** [comment]
What's the output of `systemctl status php8.1-fpm.service`?

**Comment by danjoannis** [comment]
cloud@cloud:~$ sudo systemctl status php8.1-fpm.service
× php8.1-fpm.service - The PHP 8.1 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php8.1-fpm.service; enabled; vendor preset: enabled)
     Active: failed (Result: start-limit-hit) since Wed 2022-05-18 00:16:21 UTC; 22s ago
       Docs: man:php-fpm8.1(8)
    Process: 28267 ExecStart=/usr/sbin/php-fpm8.1 --nodaemonize --fpm-config /etc/php/8.1/fpm/php-fpm.conf (code=exited, status=0/SUCCESS)
    Process: 28270 ExecStartPost=/usr/lib/php/php-fpm-socket-helper install /run/php/php-fpm.sock /etc/php/8.1/fpm/pool.d/www.conf 81 (code=exited,                                                status=0/SUCCESS)
    Process: 28773 ExecStopPost=/usr/lib/php/php-fpm-socket-helper remove /run/php/php-fpm.sock /etc/php/8.1/fpm/pool.d/www.conf 81 (code=exited, s                                               tatus=0/SUCCESS)
   Main PID: 28267 (code=exited, status=0/SUCCESS)
     Status: "Ready to handle connections"
        CPU: 23ms

May 18 00:16:19 cloud systemd[1]: Starting The PHP 8.1 FastCGI Process Manager...
May 18 00:16:20 cloud systemd[1]: Started The PHP 8.1 FastCGI Process Manager.
May 18 00:16:21 cloud systemd[1]: Stopping The PHP 8.1 FastCGI Process Manager...
May 18 00:16:21 cloud systemd[1]: php8.1-fpm.service: Deactivated successfully.
May 18 00:16:21 cloud systemd[1]: Stopped The PHP 8.1 FastCGI Process Manager.
May 18 00:16:21 cloud systemd[1]: php8.1-fpm.service: Start request repeated too quickly.
May 18 00:16:21 cloud systemd[1]: php8.1-fpm.service: Failed with result 'start-limit-hit'.
May 18 00:16:21 cloud systemd[1]: Failed to start The PHP 8.1 FastCGI Process Manager.
cloud@cloud:~$ sudo systemctl status php8.1-fpm.service
× php8.1-fpm.service - The PHP 8.1 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php8.1-fpm.service; enabled; vendor preset: enabled)
     Active: failed (Result: start-limit-hit) since Wed 2022-05-18 00:16:21 UTC; 26s ago
       Docs: man:php-fpm8.1(8)
    Process: 28267 ExecStart=/usr/sbin/php-fpm8.1 --nodaemonize --fpm-config /etc/php/8.1/fpm/php-fpm.conf (code=exited, status=0/SUCCESS)
    Process: 28270 ExecStartPost=/usr/lib/php/php-fpm-socket-helper install /run/php/php-fpm.sock /etc/php/8.1/fpm/pool.d/www.conf 81 (code=exited, status=0/SUCCESS)
    Process: 28773 ExecStopPost=/usr/lib/php/php-fpm-socket-helper remove /run/php/php-fpm.sock /etc/php/8.1/fpm/pool.d/www.conf 81 (code=exited, status=0/SUCCESS)
   Main PID: 28267 (code=exited, status=0/SUCCESS)
     Status: "Ready to handle connections"
        CPU: 23ms

May 18 00:16:19 cloud systemd[1]: Starting The PHP 8.1 FastCGI Process Manager...
May 18 00:16:20 cloud systemd[1]: Started The PHP 8.1 FastCGI Process Manager.
May 18 00:16:21 cloud systemd[1]: Stopping The PHP 8.1 FastCGI Process Manager...
May 18 00:16:21 cloud systemd[1]: php8.1-fpm.service: Deactivated successfully.
May 18 00:16:21 cloud systemd[1]: Stopped The PHP 8.1 FastCGI Process Manager.
May 18 00:16:21 cloud systemd[1]: php8.1-fpm.service: Start request repeated too quickly.
May 18 00:16:21 cloud systemd[1]: php8.1-fpm.service: Failed with result 'start-limit-hit'.
May 18 00:16:21 cloud systemd[1]: Failed to start The PHP 8.1 FastCGI Process Manager.
cloud@cloud:~$

**Comment by enoch85** [comment]
Sorry, I can't reproduce this, just tested on Hyper-V as well (shouldn't matter, but you never know).

**Comment by deninja** [comment]
It seems I'm having exact issue on Ubuntu 22.04 clean.

**Comment by deninja** [comment]
Update - It worked fine on ubuntu 22.04 installed as am VM (not LXC container)
There was no problems at all.

Is OP running ubuntu 20.04 on LXC  ?

**Comment by enoch85** [comment]
> (not LXC container)

Well, that explains alot. :laughing:

**Comment by GrumpyMeow** [comment]
I'm also having this issue with Proxmox in a LXC container. 
I suspect the error is caused by:
* either that root-user is needed to start the service 
* the php8.1-fpm.service is restarted too many times.
* 
```
Automatically configures pm.max_children for php-fpm...
pm.max_children was set to 161
pm.max_spare_servers was set to 131
Job for php8.1-fpm.service failed.
See "systemctl status php8.1-fpm.service" and "journalctl -xeu php8.1-fpm.service" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart php8.1-fpm.service failed
Checking connection...
Home/SME Server not detected. No worries, just testing the function.
postgresql is installed, it must be a clean server.
root@nextcloud:~# systemctl restart php8.1-fpm.service 
root@nextcloud:~# systemctl status php8.1-fpm.service 
* php8.1-fpm.service - The PHP 8.1 FastCGI Process Manager
     Loaded: loaded (/lib/systemd/system/php8.1-fpm.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-05-31 14:32:33 UTC; 21s ago
       Docs: man:php-fpm8.1(8)
    Process: 22882 ExecStartPost=/usr/lib/php/php-fpm-socket-helper install /run/php/php-fpm.sock /etc/php/8.1/fpm/pool.d/www.conf 81 (code=exited, status=0/SUCCESS)
   Main PID: 22878 (php-fpm8.1)
     Status: "Processes active: 0, idle: 3, Requests: 0, slow: 0, Traffic: 0req/sec"
      Tasks: 4 (limit: 38315)
     Memory: 12.7M
        CPU: 37ms
     CGroup: /system.slice/php8.1-fpm.service
             |-22878 "php-fpm: master process (/etc/php/8.1/fpm/php-fpm.conf)" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""
             |-22879 "php-fpm: pool Nextcloud" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "">
             |-22880 "php-fpm: pool Nextcloud" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "">
             `-22881 "php-fpm: pool Nextcloud" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "">
```

**Comment by GrumpyMeow** [comment]
I'm also having this issue with an Unprivileged LXC container in Proxmox ("ubuntu-22.04-standard_22.04-1_amd64.tar.zst").
I did the following things which might be the solution:
1. Reduced the number of cores from 4 to 1
2. Created a user ncadmin without adding this user to the root-group. Here-under a part of my manual script i'd used.

```
pct start $ctid
pct console $ctid
  > login as root / .......
useradd -m ncadmin
usermod -aG sudo ncadmin
passwd ncadmin
  > give password: ....
exit
  > login as ncadmin / .....

sudo bash
  > ....
wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
sudo bash 
chmod +x nextcloud_install_production.sh
./nextcloud_install_production.sh
```

**Comment by enoch85** [comment]
I don't know how LXC works, but is there something we could do in the installation script to prep this?

**Comment by tsanghowell** [comment]
I solved the problem of lack of permissions on restart by modifying PHP-FPM's Systemd service file.
Allow it to create the necessary directories on startup.
Using the following code (note the version), it may be able to solve it:
`
# Backup the existing service file
sudo cp /lib/systemd/system/php8.3-fpm.service /lib/systemd/system/php8.3-fpm.service.bak

# Use sed to add the configuration under the [Service] section
sudo sed -i '/^\[Service\]/a RuntimeDirectory=php\nRuntimeDirectoryMode=0755' /lib/systemd/system/php8.3-fpm.service

# Reload the Systemd configuration
sudo systemctl daemon-reload

# Restart the PHP-FPM service
sudo systemctl restart php8.3-fpm
`

**Comment by enoch85** [comment]
> I solved the problem of lack of permissions on restart by modifying PHP-FPM's Systemd service file. Allow it to create the necessary directories on startup. Using the following code (note the version), it may be able to solve it:
> 
> ```
> # Backup the existing service file
> sudo cp /lib/systemd/system/php8.3-fpm.service /lib/systemd/system/php8.3-fpm.service.bak
> 
> # Use sed to add the configuration under the [Service] section
> sudo sed -i '/^\[Service\]/a RuntimeDirectory=php\nRuntimeDirectoryMode=0755' /lib/systemd/system/php8.3-fpm.service
> 
> # Reload the Systemd configuration
> sudo systemctl daemon-reload
> 
> # Restart the PHP-FPM service
> sudo systemctl restart php8.3-fpm
> ```

Can you please send a PR with this, and implement a check `if` it's an LXC container?
