### ISSUE TITLE
Create changelog before release

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2330]
Have a look at this:

https://github.com/nextcloud/vm/compare/23.0.2..24.0.0
https://github.com/nextcloud/vm/compare/24.0.0..24.0.0.1

We will release 24.0.1 for production.

**Comment by enoch85** [comment]
@szaimen Everything is tested now, only apps that aren't compatible doesn't work. All bugs are fixed from what I can tell.

Please double check the apps you introduced: Whiteboard, Face Recognition, Pico CMS and so on. I'm thinking of moving them to old, since they don't seem to be well maintained (except for Face Recognition).

**Comment by szaimen** [comment]
> Whiteboard, Face Recognition, Pico CMS

I guess then also the pdfdraw app? Is there more you did not test yet, apart from the ones in the not-supported folder?

**Comment by enoch85** [comment]
Yes, PDFdraw as well. 

No I think I covered everything, even TLS and SMB-mount.

**Comment by szaimen** [comment]
okay, will test these 4 then 👍

**Comment by enoch85** [comment]
@szaimen 24.0.1 is live, I plan to release it today! Do you have time?

**Comment by szaimen** [comment]
Oh already today... Hm I am currently in transit. 

Can probably start testing at around 23:00.

**Comment by enoch85** [comment]
I started a PR.

**Comment by enoch85** [comment]
@szaimen No stress about tonight, I'm too tired after a long day and I need to do some preparations anyway for the release. Let's aim for tomorrow instead.

**Comment by szaimen** [comment]
So tested these 4 and face recognition and pico_cms seem to work. whiteboard and pdfdraw are not compatible with 24 (and possibly php8.1) yet, so not sure if we should give them at least one patch release before moving them to the old folder...

**Comment by enoch85** [comment]
Ok, seems good to me!
