### ISSUE TITLE
Script missing

### ISSUE THREAD

**Issue by JakeHasSkill** [nextcloud/vm#2333]
### Steps To Reproduce

Go to https://github.com/nextcloud/richdocuments and click on "script" or type "wget https://github.com/nextcloud/vm/blob/master/apps/collabora.sh" in the command line and you'll get error 404 not found.

### Expected Result

The script should be available to download

### Actual Result

It's missing, doesn't download

### Screenshots, Videos, or Pastebins

<img width="777" alt="Screen Shot 2022-05-19 at 9 59 20 PM" src="https://user-images.githubusercontent.com/68882341/169447693-4a8dfea7-ed92-43df-808d-5c310c41fe8c.png">

### Build Version

23.0.4

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Thanks! This will be fixed when the PR is merged.
