### ISSUE TITLE
Scripts to do not allow to update from 22.2.8 to 23.0.5 (only 24.0.1)

### ISSUE THREAD

**Issue by MarkWieczorek** [nextcloud/vm#2337]
### Steps To Reproduce

I am trying to update a nextcloud instance from 22.2.8 to 23.0.5, however, the update scripts don't seem to allow you to do this.

If I use `sudo bash /var/scripts/menu.sh` and choose the update option, and I get the following dialog 

> We will now run the update script a second time to update to the latest major version (24.0.1). Do you want to continue?`

Clicking NO stops the upgrade script. 

If I use `sudo bash /var/scripts/update.sh 23.0.5` or `sudo bash /var/scripts/update.sh` I get the dialog
> Please note that updates between multiple major versions are unsupported! Your situation is: Current version: 22.2.8 | Latest release: 24.0.1

### Expected Result

I expect that the upgrade script will allow me to update to the next major version, not the most recent release that is more than 1 stable version away.

### Actual Result

It is not possible to update from 22.2.8 to the next major version.

### Additional Context

This is probably related to this previous issue: https://github.com/nextcloud/vm/issues/2322

### Build Version

22.2.8

### Environment

By using the scripts

### Environment Details

Nextcloud homeserver sold by Hanssonit.

**Comment by enoch85** [comment]
It's by design, you can't jump between major versions. It's recommended update manually (run the menu script) on a regular basis so that you don't miss out on the possibility to upgrade.

If you skipped major versions, [there are a way to fix it.](https://shop.hanssonit.se/product/upgrade-between-major-owncloud-nextcloud-versions/)

Wording can be changed, sure. Will fix that!

**Comment by enoch85** [comment]
Please run the menu updater again, it should have a different outcome.

Thanks for posting btw!

**Comment by mdio33** [comment]
I'm facing the same problem.
I setup a home vm to start use nextcloud for PRIVATE USE of an open source software, did not update from 25.xx to 26.xx, now I cant update to 27 because "Please note that updates between multiple major versions are unsupported" and to fix that i have to pay 25$...
