### ISSUE TITLE
Bitwarden is not updating

### ISSUE THREAD

**Issue by TiminRo** [nextcloud/vm#2338]
### Steps To Reproduce

1. Go to 'Bitwarden Admin panel'
2. Click on 'Login'
3. Scroll down to 'Latest updates'
4. Click on 'latest versions'
5. See that the version is not latest one.

### Expected Result

Bitwarden should have been updated to the latest self host version.

### Actual Result

Bitwarden keeps standing on the same version when installed.

### Build Version

23.0.5

### Environment

By using the scripts

### Environment Details

Ubuntu 20.04.4 lts

**Comment by enoch85** [comment]
The self hosted version is always a few hours / days behind. No need to worry. Just run the update script regularly. :)

**Comment by TiminRo** [comment]
Hello, i was thinking about the same but i'll got the following  versions, 

Server Installed
1.47.1 
Server Latest
1.48.1 
Web Installed
2.27.0 
Web Latest
2.28.1 

The latest server version is 1.48.1 from 20 april and the latest web version 2.28.1 is from 24 days ago. Is this normal?

**Comment by enoch85** [comment]
I ran the update script yesterday and got 1.48.1, so everything works as intended.

**Comment by TiminRo** [comment]
I"ll did a new installation and restored from the backup and everything is updated again! :)

**Comment by TiminRo** [comment]
I'll did find out when installing Bitwarden on a clean server nextcloud vm, no not-supported apps its updating and is running. But when installing daily backup, off-shore backup scripts. Bitwarden is not starting up automatic when the scripts are done and not updating itself because it's no longer running. For the automatic starting up after the backup-scripts i'l did make a cronjob to keep it running. Only the updater for Bitwarden is not working. Is it possible to make a cronjob also? When using the Bitwarden one from the one promise hosting web page, nothing happend.

**Comment by szaimen** [comment]
Do you mean Bitwarden or Vaultwarden?

**Comment by TiminRo** [comment]
I mean Bitwarden the official one. 

The last time I'll did use Vaultwarden and it works as expected with both scripts.

**Comment by szaimen** [comment]
can you please post the output of `sudo docker ps -a`?

**Comment by TiminRo** [comment]
When not using the cronjob to activate Bitwarden or manual with systemctl start bitwarden. 

CONTAINER ID   IMAGE                       COMMAND                  CREATED      STATUS        PORTS                             NAMES
e007fbd49d82   onlyoffice/documentserver   "/app/ds/run-documen…"   2 days ago   Up 14 hours   443/tcp, 127.0.0.3:9090->80/tcp   onlyoffice

When using the cronjob to activate Bitwarden or manual with systemctl start bitwarden. 

CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS                             PORTS                                                                                          NAMES
ee369851eb19   bitwarden/nginx:2022.8.4           "/entrypoint.sh"         46 seconds ago   Up 44 seconds (healthy)            80/tcp, 0.0.0.0:5178->8080/tcp, :::5178->8080/tcp, 0.0.0.0:5179->8443/tcp, :::5179->8443/tcp   bitwarden-nginx
7016e1ff4af4   bitwarden/admin:2022.8.4           "/entrypoint.sh"         47 seconds ago   Up 45 seconds (health: starting)   5000/tcp                                                                                       bitwarden-admin
838d593793a8   bitwarden/events:2022.8.4          "/entrypoint.sh"         48 seconds ago   Up 46 seconds (healthy)            5000/tcp                                                                                       bitwarden-events
4080bb5e17d2   bitwarden/identity:2022.8.4        "/entrypoint.sh"         48 seconds ago   Up 46 seconds (healthy)            5000/tcp                                                                                       bitwarden-identity
7fe12c864a7d   bitwarden/notifications:2022.8.4   "/entrypoint.sh"         48 seconds ago   Up 46 seconds (healthy)            5000/tcp                                                                                       bitwarden-notifications
cacff1a060cd   bitwarden/sso:2022.8.4             "/entrypoint.sh"         48 seconds ago   Up 46 seconds (healthy)            5000/tcp                                                                                       bitwarden-sso
09639c3034b8   bitwarden/mssql:2022.8.4           "/entrypoint.sh"         48 seconds ago   Up 47 seconds (healthy)                                                                                                           bitwarden-mssql
3cb328a95d3c   bitwarden/attachments:2022.8.4     "/entrypoint.sh"         48 seconds ago   Up 47 seconds (healthy)                                                                                                           bitwarden-attachments
430664442da8   bitwarden/icons:2022.8.4           "/entrypoint.sh"         48 seconds ago   Up 46 seconds (healthy)            5000/tcp                                                                                       bitwarden-icons
575cdac75d92   bitwarden/api:2022.8.4             "/entrypoint.sh"         48 seconds ago   Up 45 seconds (healthy)            5000/tcp                                                                                       bitwarden-api
e5493e40c835   bitwarden/web:2022.8.1             "/entrypoint.sh"         48 seconds ago   Up 47 seconds (healthy)                                                                                                           bitwarden-web
e007fbd49d82   onlyoffice/documentserver          "/app/ds/run-documen…"   2 days ago       Up 14 hours                        443/tcp, 127.0.0.3:9090->80/tcp                                                                onlyoffice

**Comment by szaimen** [comment]
I see. If I understand this correctly is bitwarden not adding automatic restart policy to their containers. So when stopping the docker service, the containers are stopped but not automatic started after docker gets started again. We can now either report this as a bug to bitwarden or try to fix this here by starting the bitwarden service after docker is started. @enoch85 WDYT?

**Comment by enoch85** [comment]
I think a bug report upstream is better. it's actually a pretty unfriendly" bug which we shouldn't work around, better to fix the original issue IMHO.

@TiminRo Please report this issue [here](https://github.com/bitwarden/server/issues) instead. Thanks!

**Comment by TiminRo** [comment]
Will do, is there a workaround for now to keep Bitwarden updated manually?
