### ISSUE TITLE
After 1st script install, Ubuntu reboot in Emergency Mode

### ISSUE THREAD

**Issue by Juludu47** [nextcloud/vm#2340]
### Steps To Reproduce

Just execute the first script and reboot at the end

### Expected Result

Ubuntu reboot in normal mode

### Actual Result

Ubuntu 22.04 reboot in Emergency Mode

### Additional Context

Hello everyone,
I have two problems while executing the first script.
the first, when the script looks for the "zfs-utils" packages, it does not find them and therefore, it cannot create my "Ncdata" volume.
The second error occurs on reboot after installation, the Ubuntu goes into "Emergency mode".
I specify that I started from an Ubuntu Server 22.04 just installed with updates, running under a Vm Esxi

Bonjour tout le monde, 
j'ai deux problèmes lors de l'execution du premier script.
la première, lorsque le script cherche les paquets "zfs-utils", il ne les trouves pas et donc, il ne peut me créer mon volume "Ncdata".
La seconde erreur survient au redémarrage après l'installation, l'Ubuntu se met en "Emergency mode".
je précise que je suis parti d'un Ubuntu Server 22.04 tout juste installé avec mises à jour, s'exécutant sous une Vm Esxi.

### Build Version

The last version on the install script 

### Environment

By using the scripts

### Environment Details

VM Ubuntu 22.04 fresh install & updates
Hypervisor : Esxi 7.0.2
Hardware : 4 cores + 4 Gb RAM + HDD 100Go + HDD 1To

**Comment by enoch85** [comment]
I fail to reproduce this. I used the script ~20 times the last few days, and this never happened. 

Are you running the Ubuntu server? Are you configuring two disks? Can you provide some more details?

**Comment by enoch85** [comment]
You should install Ubuntu before you do anything, not run the install script of the live CD.

Hope that makes sense.

**Comment by Juludu47** [comment]
I thought I understood but no, unfortunately I don't see what you mean, I only have these installation options (with the wizard) how do you want me to install Ubuntu?

Je pensais avoir compris mais non, malheureusement je ne vois pas ce que tu veux dire, je n'ai que ces options d'installation (avec l'assistant) comment voulez vous que j'installe Ubuntu ?

**Comment by enoch85** [comment]
Since this seems to be specific to your setup, I don't see it as a bug. Today I installed two more servers and none of them had this issue.

What I mean is that you need to:
1. Install Ubuntu Server 22.04 (miminal)
2. Once installed the server reboots
3. When it's back up, you then have to login, and download the script and execute it
4. Then just follow the on-screen instructions

**Comment by Juludu47** [comment]
Ok, I'll try to make the Vm again and I'll let you know
