### ISSUE TITLE
Daily Backup script not running - missing zfs-auto-snapshot

### ISSUE THREAD

**Issue by tasover** [nextcloud/vm#2341]
### Steps To Reproduce

1. Go to - run manually the daily back script from /var/scripts/daily-borg-backup.sh

### Expected Result

Complete the backup procedure.

### Actual Result

# Starting services...
Starting services...
Maintenance mode disabled
Starting docker...
**sed: can't read /usr/sbin/zfs-auto-snapshot: No such file or directory
/var/scripts/borgbackup.sh: line 326: zfs-auto-snapshot: command not found**

# Unmounting the backup drive...
Unmounting the backup drive...

# Daily backup sent error on 24.05.2022 - 16:42:20 (00 hours 00 minutes 20 seconds)
Daily backup sent error on 24.05.2022 - 16:42:20 (00 hours 00 minutes 20 seconds)

# Daily backup failed! Could not create ZFS snapshot!
Daily backup failed! Could not create ZFS snapshot!

### Additional Context

Fixed with installing  zfs-auto-snapshot:

sudo apt install zfs-auto-snapshot

### Build Version

24.0.1

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04 Minimal
PHP 8.1
CPU 4C
RAM 8GB

**Comment by enoch85** [comment]
No, I decided to remove it per default. No one knew how to use it anyway afaik. Never got any questions about it, just bug reports regarding it filled the disk.

I think it makes sense to install it if the user makes an active choice, but not otherwise.

**Comment by szaimen** [comment]
All right. So do I need to we rewrite this logic?
https://github.com/nextcloud/vm/blob/bee9db5b5ee6c9d05ad398c1f2c9fe98e65beba8/not-supported/borgbackup.sh#L322-L326

**Comment by enoch85** [comment]
> Or shall I simply install it if not installed?

Yes, that's how I would do it. Also please inform the user about what's happening in the background and the potential use case of auto snapshots with ZFS.

**Comment by enoch85** [comment]
When thatsWhen this is stable, maybe we should add this option in the default menu?

**Comment by enoch85** [comment]
I was wrong, we do install `zfs-auto-snapshot` per default... Strange that it's not installed...

**Comment by tasover** [comment]
Both on production and test environment nextcloud zfs-auto-snapshot aren't installed.

**Comment by enoch85** [comment]
Hmm... Need to investigate!

**Comment by szaimen** [comment]
If it is installed by default either way, I could also simply add install_if_not here, no?

**Comment by enoch85** [comment]
@szaimen Yes, do that please.

**Comment by enoch85** [comment]
Just checked. Installed a new VM from the ground up, everything checks out as it should:

```
root@test:~# apt-cache policy zfs-auto-snapshot
zfs-auto-snapshot:
  Installed: (none)
  Candidate: 1.2.4-2
  Version table:
     1.2.4-2 500
        500 http://se.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

**Comment by enoch85** [comment]
The case here may be because @tasover chose one disk during installation, then it's not installed.

**Comment by tasover** [comment]
No, @enoch85 i selected two disks during installation on both systems.

**Comment by tasover** [comment]
> Just checked. Installed a new VM from the ground up, everything checks out as it should:
> 
> ```
> root@test:~# apt-cache policy zfs-auto-snapshot
> zfs-auto-snapshot:
**>   Installed: (none)**
>   Candidate: 1.2.4-2
>   Version table:
>      1.2.4-2 500
>         500 http://se.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
> ```

Isn't installed

If installed will shown:

zfs-auto-snapshot:
  **Installed: 1.2.4-2**
  Candidate: 1.2.4-2
  Version table:
 *** 1.2.4-2 500
        500 http://fi.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
root@portal2:~#

**Comment by enoch85** [comment]
Aah my bad! Have to check why...
