### ISSUE TITLE
Integrity check failure

### ISSUE THREAD

**Issue by dxm765** [nextcloud/vm#235]
## Steps to reproduce
1. Updated from 11 to 12
2. Logged into web GUI

## Expected behavior
Update without error

## Actual behavior
Updated from 11 to 12 but has an error that some files have not passed an integrity check.

## Server configuration

**Server version:** (see your admin page)
12.0.0
**VM version** (master / released version)
Master
**Updated from an older installed version or fresh install:**
Updated
## Network
**Do you use DHCP?**
No , static
**Is port 80 and/or 443 open?**
Yes both 80 and 443
#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
https://pastebin.com/z1XCZqRu (hastebin complained it was too large)

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
http://imgur.com/a/vIBvc

-->

**Comment by enoch85** [comment]
@dxm765 Yes that's a bug in the server code. https://github.com/nextcloud/server/issues/5066

To fix it (as root):

1. `cd /var/www/nextcloud`
2. `rm .htaccess && wget https://raw.githubusercontent.com/nextcloud/server/master/.htaccess`
3. Make a file called whatever.... `nano prettyurls.sh` and post this content:
```
NCDB=1 && MYCNFPW=1 && NC_UPDATE=1 . <(curl -sL https://raw.githubusercontent.com/nextcloud/vm/master/lib.sh)
unset NC_UPDATE
unset MYCNFPW
unset NCDB

# Pretty URLs
echo "Setting RewriteBase to \"/\" in config.php..."
chown -R www-data:www-data "$NCPATH"
sudo -u www-data php "$NCPATH"/occ config:system:set htaccess.RewriteBase --value="/"
sudo -u www-data php "$NCPATH"/occ maintenance:update:htaccess
bash "$SECURE"
```
4. `bash prettyurls.sh`

**Comment by enoch85** [comment]
Iäll leave this open if someone else also get's it. 

Regarding the OPcache (noticed that myself on 12), just cmake a file and run it with this code in it:
```
# Enable OPCache for PHP 
# https://docs.nextcloud.com/server/12/admin_manual/configuration_server/server_tuning.html#enable-php-opcache
phpenmod opcache
{
echo "# OPcache settings for Nextcloud"
echo "opcache.enable=On"
echo "opcache.enable_cli=1"
echo "opcache.interned_strings_buffer=8"
echo "opcache.max_accelerated_files=10000"
echo "opcache.memory_consumption=128"
echo "opcache.save_comments=1"
echo "opcache.revalidate_freq=1"
} >> /etc/php/7.0/apache2/php.ini

service apache2 reload
```

**Comment by dxm765** [comment]
@enoch85 greatly appreciate the swift replies and fixes, the OPcache one fixed it right up, however the .htaccess one did not...but it was odd as I ran a integrity core check after and it no longer showed .htaccess as having a hash error , but upon reboot the message was still there.

**Comment by enoch85** [comment]
> it was odd as I ran a integrity core check after and it no longer showed .htaccess as having a hash error , but upon reboot the message was still there.

That's strange. Try do do the process again.

**Comment by enoch85** [comment]
@dxm765 Any update here?

**Comment by dxm765** [comment]
@enoch85 I reran the steps late last night as root and as before and it still produces the error with .htaccess even though after running the script and doing a check prior to reboot says everything is good, upon reboot the error message about code integrity is back.

**Comment by enoch85** [comment]
@dxm765 Strange, it works here, even after reboot. 

But hey, do the fix and don't reboot the server. ;)

This is not a script issue anyway, so I'm closing this now.
