### ISSUE TITLE
External Storage SMB not working after update to 24.0.1

### ISSUE THREAD

**Issue by Swillyums** [nextcloud/vm#2351]
### Steps To Reproduce

Add new (or have existing) SMB/CIFS external storage.

### Expected Result

External storage location becomes available. 

### Actual Result

Instead, I get a small red exclamation mark. 

the logs contain [no app in context] Warning: Icewind\SMB\Exception\InvalidArgumentException: Invalid request for / (InvalidArgumentException) at <<closure>>

 0. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php line 75
    Icewind\SMB\Exception\Exception::fromMap()
 1. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php line 92
    Icewind\SMB\Native\NativeState->handleError()
 2. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php line 351
    Icewind\SMB\Native\NativeState->testResult()
 3. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php line 305
    Icewind\SMB\Native\NativeState->getxattr()
 4. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php line 43
    Icewind\SMB\Native\NativeShare->getAttribute()
 5. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php line 69
    Icewind\SMB\Native\NativeFileInfo->stat()
 6. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php line 114
    Icewind\SMB\Native\NativeFileInfo->getSize()
 7. /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 193
    Icewind\SMB\Native\NativeShare->stat()
 8. /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 350
    OCA\Files_External\Lib\Storage\SMB->getFileInfo()
 9. /var/www/nextcloud/lib/private/Files/Storage/Common.php line 459
    OCA\Files_External\Lib\Storage\SMB->stat()
10. /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 731
    OC\Files\Storage\Common->test()
11. /var/www/nextcloud/apps/files_external/lib/MountConfig.php line 131
    OCA\Files_External\Lib\Storage\SMB->test()
12. /var/www/nextcloud/apps/files_external/lib/Controller/StoragesController.php line 288
    OCA\Files_External\MountConfig::getBackendStatus("*** sensitive parameters replaced ***")
13. /var/www/nextcloud/apps/files_external/lib/Controller/GlobalStoragesController.php line 201
    OCA\Files_External\Controller\StoragesController->updateStorageStatus("*** sensitive parameters replaced ***")
14. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Files_External\Controller\GlobalStoragesController->update("*** sensitive parameters replaced ***")
15. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
16. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
17. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
18. /var/www/nextcloud/lib/base.php line 1023
    OC\Route\Router->match()
19. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

PUT /apps/files_external/globalstorages/1

### Build Version

24.0.1

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Actually we don't recommend using the app since it's not 100% between updates.

There are a much better way of doing things, mounting it locally instead: `sudo bash /var/scripts/menu.sh` --> Apps --> SMB-mount

**Comment by enoch85** [comment]
Please report this in the server section on GitHub instead. Thanks!
