### ISSUE TITLE
zfs volume issue

### ISSUE THREAD

**Issue by tokyonfc** [nextcloud/vm#2354]
### Steps To Reproduce

1. zfs volume mounted for storage of user data
2. Triggered an update via /var/scripts/update.sh

### Expected Result

The update is expected to suceed

### Actual Result

Update failed

### Screenshots, Videos, or Pastebins

![2048-540-max](https://user-images.githubusercontent.com/107933794/174809839-f7c4d9fd-bb4c-4d74-886f-17d692952cce.png)

### Build Version

24.0.1

### Environment

By downloading the VM

### Environment Details

VMWare ESXi-7.0U3d-19482537-standard on 
Manufacturer Dell Inc.
Model PowerEdge T440
CPU Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
Memory 31.62 GB

VM 
8 CPUs 
8GB RAM
40GB volume for nextcloud itself
3.6TB zfs volume for data storage
hansson it Nextcloud VM Pre Installed

**Comment by crdxfire** [comment]
just to add this to my colleagues report  - this is the pool, we are talking about:
Disk /dev/sdb: 3.61 TiB, 3958241859584 bytes, 7730941132 sectors
Disk model: Virtual disk    
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: E4EB9982-0B2F-2442-A4B1-803C8C808F91

Device          Start        End    Sectors  Size Type
/dev/sdb1        2048 7730923519 7730921472  3.6T Solaris /usr & Apple ZFS
/dev/sdb9  7730923520 7730939903      16384    8M Solaris reserved 1

So to me it looks like it would be a zfs pool.

**Comment by enoch85** [comment]
I can see in your screenshot it's not named `ncdata`. In other words, you made modifications to the VM and that's a support issue in that case.

**Comment by crdxfire** [comment]
Thank you, Daniel! We renamed it to ncdata - all good! :)
