### ISSUE TITLE
Installation error nextcloud_install_production.sh

### ISSUE THREAD

**Issue by justinlong24** [nextcloud/vm#2355]
### Steps To Reproduce

running the install. Get this error
E: Unable to locate package php8.1-fpm
E: Couldn't find any package by glob 'php8.1-fpm'
E: Couldn't find any package by regex 'php8.1-fpm'
E: Unable to locate package php8.1-intl
E: Couldn't find any package by glob 'php8.1-intl'
E: Couldn't find any package by regex 'php8.1-intl'
E: Unable to locate package php8.1-ldap
E: Couldn't find any package by glob 'php8.1-ldap'
E: Couldn't find any package by regex 'php8.1-ldap'
E: Unable to locate package php8.1-imap
E: Couldn't find any package by glob 'php8.1-imap'
E: Couldn't find any package by regex 'php8.1-imap'
E: Unable to locate package php8.1-gd
E: Couldn't find any package by glob 'php8.1-gd'
E: Couldn't find any package by regex 'php8.1-gd'
E: Unable to locate package php8.1-pgsql
E: Couldn't find any package by glob 'php8.1-pgsql'
E: Couldn't find any package by regex 'php8.1-pgsql'
E: Unable to locate package php8.1-curl
E: Couldn't find any package by glob 'php8.1-curl'
E: Couldn't find any package by regex 'php8.1-curl'
E: Unable to locate package php8.1-xml
E: Couldn't find any package by glob 'php8.1-xml'
E: Couldn't find any package by regex 'php8.1-xml'
E: Unable to locate package php8.1-zip
E: Couldn't find any package by glob 'php8.1-zip'
E: Couldn't find any package by regex 'php8.1-zip'
E: Unable to locate package php8.1-mbstring
E: Couldn't find any package by glob 'php8.1-mbstring'
E: Couldn't find any package by regex 'php8.1-mbstring'
E: Unable to locate package php8.1-soap
E: Couldn't find any package by glob 'php8.1-soap'
E: Couldn't find any package by regex 'php8.1-soap'
E: Unable to locate package php8.1-json
E: Couldn't find any package by glob 'php8.1-json'
E: Couldn't find any package by regex 'php8.1-json'
E: Unable to locate package php8.1-gmp
E: Couldn't find any package by glob 'php8.1-gmp'
E: Couldn't find any package by regex 'php8.1-gmp'
E: Unable to locate package php8.1-bz2
E: Couldn't find any package by glob 'php8.1-bz2'
E: Couldn't find any package by regex 'php8.1-bz2'
E: Unable to locate package php8.1-bcmath
E: Couldn't find any package by glob 'php8.1-bcmath'
E: Couldn't find any package by regex 'php8.1-bcmath'
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
apt-get install -y php8.1-fpm php8.1-intl php8.1-ldap php8.1-imap php8.1-gd php8.1-pgsql php8.1-curl php8.1-xml php8.1-zip php8.1-mbstring php8.1-soap php8.1-json php8.1-gmp php8.1-bz2 php8.1-bcmath php-pear failed

### Expected Result

Clean install

### Actual Result

E: Unable to locate package php8.1-fpm
E: Couldn't find any package by glob 'php8.1-fpm'
E: Couldn't find any package by regex 'php8.1-fpm'
E: Unable to locate package php8.1-intl
E: Couldn't find any package by glob 'php8.1-intl'
E: Couldn't find any package by regex 'php8.1-intl'
E: Unable to locate package php8.1-ldap
E: Couldn't find any package by glob 'php8.1-ldap'
E: Couldn't find any package by regex 'php8.1-ldap'
E: Unable to locate package php8.1-imap
E: Couldn't find any package by glob 'php8.1-imap'
E: Couldn't find any package by regex 'php8.1-imap'
E: Unable to locate package php8.1-gd
E: Couldn't find any package by glob 'php8.1-gd'
E: Couldn't find any package by regex 'php8.1-gd'
E: Unable to locate package php8.1-pgsql
E: Couldn't find any package by glob 'php8.1-pgsql'
E: Couldn't find any package by regex 'php8.1-pgsql'
E: Unable to locate package php8.1-curl
E: Couldn't find any package by glob 'php8.1-curl'
E: Couldn't find any package by regex 'php8.1-curl'
E: Unable to locate package php8.1-xml
E: Couldn't find any package by glob 'php8.1-xml'
E: Couldn't find any package by regex 'php8.1-xml'
E: Unable to locate package php8.1-zip
E: Couldn't find any package by glob 'php8.1-zip'
E: Couldn't find any package by regex 'php8.1-zip'
E: Unable to locate package php8.1-mbstring
E: Couldn't find any package by glob 'php8.1-mbstring'
E: Couldn't find any package by regex 'php8.1-mbstring'
E: Unable to locate package php8.1-soap
E: Couldn't find any package by glob 'php8.1-soap'
E: Couldn't find any package by regex 'php8.1-soap'
E: Unable to locate package php8.1-json
E: Couldn't find any package by glob 'php8.1-json'
E: Couldn't find any package by regex 'php8.1-json'
E: Unable to locate package php8.1-gmp
E: Couldn't find any package by glob 'php8.1-gmp'
E: Couldn't find any package by regex 'php8.1-gmp'
E: Unable to locate package php8.1-bz2
E: Couldn't find any package by glob 'php8.1-bz2'
E: Couldn't find any package by regex 'php8.1-bz2'
E: Unable to locate package php8.1-bcmath
E: Couldn't find any package by glob 'php8.1-bcmath'
E: Couldn't find any package by regex 'php8.1-bcmath'
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
apt-get install -y php8.1-fpm php8.1-intl php8.1-ldap php8.1-imap php8.1-gd php8.1-pgsql php8.1-curl php8.1-xml php8.1-zip php8.1-mbstring php8.1-soap php8.1-json php8.1-gmp php8.1-bz2 php8.1-bcmath php-pear failed

### Build Version

new install

### Environment

By using the scripts

**Comment by enoch85** [comment]
The scripts are developed for Ubuntu 22.04 Server. You need that, and nothing else to run the scripts.

Hope it helps!
