### ISSUE TITLE
Timeout / Login problem

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#236]
Hi,

I made a fresh install using Nextcloud VM latest V12 with option "extra security". Duration for successful login with the web-interface is about 30 sec. 

Same behaviour like in the previous version. It comes to timeout with Nextcloud-app or desktop-client for Windows. Only by web-interface there is no timeout but a long delay.

Any ideas? Thank you!

Best regards,

nxtester

**Comment by enoch85** [comment]
Thanks for reporting!

Check the logs in `/var/logs` Especially the Apache logs and see if you can find anything useful there. Also check `/etc/apache2/mods-enabled/spamhaus.conf` and see if your IP is listed.

**Comment by enoch85** [comment]
Did you check this? @nxtester

**Comment by nxtester** [comment]
Still slow, here are the requested files:

**var/log/apache2/error.log**

[Wed May 24 20:51:19.840542 2017] [core:notice] [pid 3577] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 24 20:56:17.424834 2017] [spamhaus:crit] [pid 3583] [client 192.168.100.202:52366] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered
[Wed May 24 20:56:17.508321 2017] [spamhaus:crit] [pid 3583] [client 192.168.100.202:52366] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered
[Wed May 24 20:59:20.093310 2017] [spamhaus:crit] [pid 5073] [client 192.168.100.202:35630] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered
[Wed May 24 20:59:20.263760 2017] [spamhaus:crit] [pid 5072] [client 192.168.100.202:41060] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered
[Wed May 24 20:59:20.333563 2017] [spamhaus:crit] [pid 5073] [client 192.168.100.202:35630] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered
[Wed May 24 20:59:20.400008 2017] [spamhaus:crit] [pid 5072] [client 192.168.100.202:41060] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered
[Wed May 24 20:59:39.095717 2017] [spamhaus:crit] [pid 3581] [client 192.168.100.202:52441] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered
[Wed May 24 20:59:39.192725 2017] [spamhaus:crit] [pid 3581] [client 192.168.100.202:52441] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered

**/etc/apache2/mods-enabled/spamhaus.conf**

<IfModule mod_spamhaus.c>

#MS_Methods
#    Syntax:  MS_Methods POST,PUT,OPTIONS
#    Default: POST,PUT,OPTIONS
#    
#    The values admitted are the httpd's methods (GET,POST,etc)
#    Module verify remote ip address if the method used by the user is present
#    in the value passed to this variable. Methods must be comma-separated
MS_METHODS POST,PUT,OPTIONS,CONNECT 


#MS_WhiteList
#    Syntax:  MS_WhiteList /etc/spamhaus.wl
#    Default: no value
#    Path of whitelist file.
#    After you've edit it, you mustn't reload apache. This file will be read only
#    when 'data modification time' change. You can add an individual IP address or
#    subnets with CIDR. 
MS_WhiteList /etc/spamhaus.wl


#MS_DNS
#    Syntax:  MS_DNS sbl-xbl.spamhaus.org
#    Default: sbl-xbl.spamhaus.org
#    Name server to use for verify is an ip is blacklisted.
#    Using a local rbldnsd instance of sbl-xbl, you can increase query performance
#MS_Dns local.rbldnsd.instance.of.sbl-xbl


#MS_CacheSize
#    Syntax:    MS_CacheSize 256
#    Default:   512
#    Max value: 8192
#    This directive can manage the number of cache entries.
#MS_CacheSize 512


#MS_CustomError
#    Syntax:   MS_CustomError "My custom error message"
#    Default:  "Access Denied! Your address is blacklisted. More information about this error may be available in the server error log."
#    A custom error message that allows you to replace default error message with one you create
#MS_CustomError "Access Denied! Your address is blacklisted. More information about this error may be available in the server error log."


</IfModule>

**Comment by enoch85** [comment]
@nxtester Thanks, and how does your `/etc/spamhaus.wl` look like?

**Comment by enoch85** [comment]
@nxtester Does your IP / Subnet exist in the Whitelist? If not, what happens if you add it?

**Comment by nxtester** [comment]
spamhaus.wl

# Whitelisted IP-ranges
192.168.0.0/16
172.16.0.0/12
10.0.0.0/8

I will add 192.168.100.0/24 and report again

**Comment by nxtester** [comment]
No effect after adding 192.168.100.0/24 to spamhaus.wl and reboot. Will try it later outside intranet.

**Comment by nxtester** [comment]
[Wed May 24 22:07:12.943095 2017] [mpm_prefork:notice] [pid 1341] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Wed May 24 22:07:12.943899 2017] [core:notice] [pid 1341] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 24 22:09:50.364804 2017] [spamhaus:crit] [pid 2061] [client 192.168.100.202:49319] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered
[Wed May 24 22:09:50.769324 2017] [spamhaus:crit] [pid 2061] [client 192.168.100.202:49319] mod_spamhaus: address 192.168.100.202 is blacklisted but it's not in the 127.0.0.0/8 range. POSSIBLE WILD-CARDING TYPOSQUATTERS ATTACK! IP address will not get filtered

192.168.100.202 is the internet router
