### ISSUE TITLE
Fail2Ban doesn't start (logfile issue) - replaced default sshd port

### ISSUE THREAD

**Issue by tasover** [nextcloud/vm#2361]
### Steps To Reproduce

Replace the sshd default port:

Check the service status of fail2ban:

sudo systemctl status fail2ban

### Expected Result

 fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-07-12 12:10:16 EEST; 3s ago
       Docs: man:fail2ban(1)
   Main PID: 97704 (fail2ban-server)
      Tasks: 7 (limit: 18619)
     Memory: 12.4M
        CPU: 205ms
     CGroup: /system.slice/fail2ban.service
             └─97704 /usr/bin/python3 /usr/bin/fail2ban-server -xf start

### Actual Result

Failed during configuration: Have not found any log file for sshd jail

### Additional Context

As i have changed the sshd port from the default tried the following:

edited /etc/fail2ban/jail.conf on [sshd] and replaced 
port = ssh 
to
port = the_actual_port

the service starts but on the /var/log/fail2ban.log doesn't show the [sshd] ip as Found.

If i also change

backend = systemd 

on the log file Shows INFO [sshd] Found and the IP.

I suspect the correct approach is to use as backend the systemd.

Checked also using the default backend = %(sshd_backend)s and my ip **didn't blocked** , using the systemd backend the IP blocked.

### Build Version

24.0.1

### Environment

By using the scripts

**Comment by enoch85** [comment]
Hi, you need to change the port in fail2ban as well. 

It's in jail.local.

**Comment by tasover** [comment]
Hi, i did it and rollback to backend =  %(sshd_backend)s on jail.conf but the issue persists.

If i change the backend = systemd on jail.conf fail2ban working as excected.
