### ISSUE TITLE
fail2ban nextcloud filter

### ISSUE THREAD

**Issue by tasover** [nextcloud/vm#2362]
### Steps To Reproduce

1. Go to 'Nextcloud web interface and login with wrong password'
2. Go to terminal and check with 

tail -f tail -f /var/log/fail2ban.log

### Expected Result

[nextcloud] Found XX.XX.XX.XX - 2022-07-12 14:03:25

XX states about the ip of the client with the wrong password

### Actual Result

 INFO    [nextcloud] Found 0.0.0.1 - 2022-07-12 14:02:16

### Additional Context

replaced on /etc/fail2ban/filter.d/nextcloud.conf

```
[Definition]
failregex = Login failed.*Remote IP.*<HOST>
ignoreregex =
```

with

```
[Definition]
_groupsre = (?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*)
failregex = ^\{%(_groupsre)s,?\s*"remoteAddr":"<HOST>"%(_groupsre)s,?\s*"message":"Login failed:
            ^\{%(_groupsre)s,?\s*"remoteAddr":"<HOST>"%(_groupsre)s,?\s*"message":"Trusted domain error.
datepattern = ,?\s*"time"\s*:\s*"%%Y-%%m-%%d[T ]%%H:%%M:%%S(%%z)?"
```
as stated on

https://docs.nextcloud.com/server/stable/admin_manual/installation/harden_server.html?highlight=fail2ban

### Build Version

24.0.1

### Environment

By using the scripts

**Comment by enoch85** [comment]
You're welcome to figure it out and send a PR.

**Comment by tasover** [comment]
Added PR:
#2365

**Comment by enoch85** [comment]
Thanks! Is the PR tested? Does it work as expected, is it your running config?

**Comment by tasover** [comment]
Yes! It's my running config of /etc/fail2ban/filter.d/nextcloud.conf and works as expected!
The original nextcloud.conf produce the issue with "INFO [nextcloud] Found 0.0.0.1 - 2022-07-12 14:02:16"

Just for the record on my nextcloud instance i have installed also the notify_push and nextcloud talk with HPB from the nextcloud vm apps.

I haven't tested if the issue persists without the added apps, but i suppose as the PR created using the official documentation it will not be a problem.

**Comment by enoch85** [comment]
This is merged.
