### ISSUE TITLE
Failed to start Apache2 service.

### ISSUE THREAD

**Issue by SinaBina** [nextcloud/vm#2366]
### Steps To Reproduce

Hello,
Encountered an issue with my Nextcloud VM.This happened two times. Once after update and the second one after power outage.I managed to restore the VM from snapshots but seems that maybe I do something wrong here.
After power outage I restarted the VM and I saw an error saying "failed to start Apache service".
After investigating more i narrowed down the problem to two syntax error in Apache config file which then directed me to mnt/ncdata.
It tried to read a configuration file in ncdata folder which interestingly was empty and it caused Apache to not to start.
So am i doing something wrong here? or maybe ZFS is not reliable?

Thanks

Nextcloud VM 24.0.2 with all apps up to date.
WMware Workstation 16.2.1

### Expected Result

mnt/ncdata is empty

### Actual Result

Apache failed to start.

### Build Version

24.0.2

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Seems like your data got corrupted due to the outage.  That's nothing we can program away. You need to get an UPS ([V7](https://www.v7world.com/uk/v7-ups-1500va-rack-mount-2u-eu.html) makes really good ones).
