### ISSUE TITLE
Impossible to upgrade from 23.0.4 on Ubuntu 18.04.6 LTS

### ISSUE THREAD

**Issue by strlink** [nextcloud/vm#2367]
### Steps To Reproduce

1. Go to SSH
2. run sudo bash /var/scripts/update.sh
3. Click on 'Enter'

### Expected Result

to see my Nextcloud VM upgraded to the latest version, 23.0.7

### Actual Result

A screen (see attached) with the text:

**Nextcloud VM - 2022 - Nextcloud Update Script
Your current Ubuntu version is 18.04 but must be between 20.04 - 22.04.10 to run this script.**

Clicking OK a new message with:

**Please contact us to get support for upgrading your server:
https://www.hanssonit.se/#contact
https://shop.hanssonit.se/product/upgrade-ubuntu-os-between-major-versions/**

### Screenshots, Videos, or Pastebins

Message 1:
![screenshot_2912](https://user-images.githubusercontent.com/42774825/180179512-2d080d25-40dc-46af-985a-c5c140c65308.png)

Message 2:
![screenshot_2913](https://user-images.githubusercontent.com/42774825/180179545-fedf2aaf-720a-4777-8153-80a3f7663fbe.png)

### Additional Context

Ubuntu 18.04.6 LTS status is:

End of Standard Support: April 2023
End of Life: April 2028

[https://wiki.ubuntu.com/Releases]

### Build Version

23.0.4

### Environment

By downloading the VM

### Environment Details

Ubuntu 18.04.6 LTS
Apache 2.4.54
PHP 7.4.30
PostgreSQL 12.11

**Comment by enoch85** [comment]
It's not a bug it's by design. Please follow the instructions in the pop-ups.

Thanks!
