### ISSUE TITLE
Hyper-V (T&M Hansson IT) 500 GB VM Data Drive Stuck at ~32 Gigs (Not Expanding)

### ISSUE THREAD

**Issue by RJ-Make** [nextcloud/vm#2368]
### Steps To Reproduce

I'm probably wrong, but,... I have the above VM and I thought the data drive would expand as it gets filled?  

What brought me to this point:

This morning I tried to log in via the web browser and received a 500 error.  So, using webmin I see there are 2 errors about not being about to mount /mnt/ncdata because there was no room left (drive was full). 

Even after manually delete about 15 gigs worth of data, that apparent is not being cleared out, from the /files_trashbin folder for each user the error would not clear after a reboot.

Thankfully I had a backup from the night before and was able to go in and manual delete all those files. 

### Expected Result

1) I thought the VM would expand the data drive as needed.
2) If this is not the case, how is this performed?

### Actual Result

1) The data drive is NOT being expanded as needed.

### Build Version

24.0.3

### Environment

By downloading the VM

### Environment Details

Operating System: Linux 5.4.0-122-generic x86_64
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (4 cores)
Memory: 5.80 GB

**Comment by enoch85** [comment]
To expand the disk you need to:

1. Expand it in the hypervisor
2. Expand it in the guest system

If you need help, check this out: https://shop.hanssonit.se/product/custom-expand/

**Comment by enoch85** [comment]
You could also run the update script which will remove ZFS snapshots, and keep it that way by running a cronjob.

**Comment by RJ-Make** [comment]
> You could also run the update script which will remove ZFS snapshots, and keep it that way by running a cronjob.
> 
> `sudo bash /var/scripts/menu.sh` --> Update Nextcloud

I tried running the update script several times that did not fix the problem.

**Comment by enoch85** [comment]
OK, then you need to expand the disk as described above.

**Comment by RJ-Make** [comment]
I guess I'm confused. Why would anyone purchased a larger VM (I purchased the 500 GB version) version of the VM and then have to pay a lot more to actually use the lager VM?

It was my understanding the data drive is 500 GB and would automatically expand as space is needed in Nextcloud, but yet Nextcloud data drive is stuck at  ~32 GB?

What Am I missing here?

**Comment by enoch85** [comment]
This is what says in the description:

https://shop.hanssonit.se/product/nextcloud-vm-microsoft-hyper-v-500gb/

```
DATA disk: 500 GB
OS disk: 40 GB
```

So the OS disk is 40 GB (~32 converted) and the DATA disk is 500 GB. Everything seems to be in order. 

If you have a really large DB for some reason then you might have to enlarge the OS disk. Usually 10 GB is more than enough, so I'm not sure how you managed to fill it?

**Comment by RJ-Make** [comment]
Here is my details. Did I set this up wrong

![Capture](https://user-images.githubusercontent.com/8496835/180800149-5557ee72-1f68-4022-854f-9220c52d1a29.PNG)
?

**Comment by RJ-Make** [comment]
I used the V2 YouTube video to set this up.

**Comment by RJ-Make** [comment]
Here are the files I received. 

![Screenshot 2022-07-25 103046](https://user-images.githubusercontent.com/8496835/180801946-33a9fd43-1074-4024-be44-d6df06c7a21d.png)
e

**Comment by enoch85** [comment]
OK, so your situation seems to be that it's filled with snapshots for some reason. You can clear them with this script: https://github.com/nextcloud/vm/blob/master/disk/zfs-prune-snapshots.sh

Call it like: `sudo bash zfs-prune-snapshots.sh 1s`. Make sure to get the RAW file.

**Comment by RJ-Make** [comment]
Where do I put the zfs-prune-snapshots file?  I tried usr/bin but running your command return a not found error.

**Comment by RJ-Make** [comment]
I think I figured it out. I put in in the /var/scripts/ folder.
