### ISSUE TITLE
Failure during installation using script - apache2 controll process exited with error code, notifications app isn't enabled

### ISSUE THREAD

**Issue by kate-shen** [nextcloud/vm#2369]
### Steps To Reproduce

1. Create an Ubuntu 20.04 LTS VM, attach second virtual disk using AHCI. 
2. Go to 'https://docs.hanssonit.se/s/bj0vl1ihv0jgrmfm08j0/build-your-own/d/bj0vl4ahv0jgrmfm0950/nextcloud-vm'
3. Follow step 1 - reaches long installation process of php modules etc., but does not complete.

### Expected Result

Script completes and reboots as per page. 

### Actual Result

The last lines in the console are as follows: 

`No VM guests are running outdated hypervisor (qemu) binaries on this host.
Conf php8.1-fpm already enabled
Enabling HTTP/2 server wide...
/etc/apache2/mods-available/http2.conf was successfully created
Module http2 already enabled
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xeu apache2.service" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart apache2.service failed
The notifications app isn't enabled - unable to send notifications`

### Build Version

24.0.3

### Environment

By using the scripts

### Environment Details

OS: Ubuntu 20.04 LTS VM on TrueNAS Core

**Comment by enoch85** [comment]
20.04 is not supported. You should get 22.04.
