### ISSUE TITLE
Collabora installation in Nextcloud 12 VM fails

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#237]
Hi Guys,

I just tested installation of Collabora (collabora.sh) in latest Nextcloud 12 VM but at the end it reports:

To activate the new configuration, you need to run:
  service apache2 reload

[Exception]
  App "Collabora Online" cannot be installed because it is not compatible with this version of the server.

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!

Seems to be still in developement.

Best regards,

nxtester

**Comment by enoch85** [comment]
@nxtester Hmm, that's strange, never seen that one before. 

Which kernel do you run? Is it a fresh Nextcloud install with 12 or a updated version?

**Comment by nxtester** [comment]
It is a very fresh nextcloud install, based on your georgeous "Nextcloud VM" which is already Nextcloud Version 12 (Nextcloud_Community_VM_PRODUCTION.rar) which was released before 2 days.

I tried it second times. Installation seemed to be normal until the end, then it crashed.

Maybe good to know: I installed Collabora after Nextcloud using your newest version of script "collabora.sh" (sudo wget https://raw.githubusercontent.com/nextcloud/vm/master/apps/collabora.sh -P /var/scripts)

Best regards,

nxtester

**Comment by enoch85** [comment]
@nxtester Which were the exact steps you took? Did you install SSL on you main domain with Let's Encrypt before you tried to install Collabora?

Have you checked the Apps section in Nextcloud 12? Is Collabora updated?

**Comment by nxtester** [comment]
I had the following order:
1.) Install-Script incl. SSL successful completed but Collabora and MySQL unchecked
2.) Collabora-Script incl. SSL

I unchecked Collabora in the runtime of install-script because I had always trouble with installation in V11 by this way. Only if I separated installation of (first) NC + SSL and (after) Collabora + SSL it was successful.

Thanks for your appreciated support!

**Comment by enoch85** [comment]
@nxtester I'm not sure I follow. Did you abort the script (Collabora) while it was running? 

If you install it when setting up the VM for the first time it works, I just tested. You can also choose to install it afterwards but then you have to download the latest script from this repo with wget.

**Comment by nxtester** [comment]
I never aborted the script. The install script was running properly until the end. Then I made exactly what you wrote: I downloaded https://raw.githubusercontent.com/nextcloud/vm/master/apps/collabora.sh and started Collabora installation which was fine until the end where I got this error message.

**Comment by enoch85** [comment]
Was the error message in the end? Did the SSL certs got generated?

I think this is only an app issue. Remove the app from App Store, then re-install it and add your subdomain to Collabora settings. Let me know how it went.

**Comment by nxtester** [comment]
What I have now: 

Working Nextcloud 12 VM, all installed (incl. SSL) excluded Collabora.

**Comment by nxtester** [comment]
Now I can run 3rd time "collabora.sh" but it will maybe crash again at the end, even after generation of certificates. The crash appear after all installation steps of Collabora, maybe in the very last step.

**Comment by enoch85** [comment]
You didn't follow my instructions. Check this out: https://youtu.be/LlqY5Y6P9Oc from 17:35.

The app is not updated so you have to remove it and add it again like I wrote before. This is now solved so I'm closing.

**Comment by nxtester** [comment]
OK, I tried again to install Collabra. At the very last step: BUMM. See screenshot.

![putty_2017-05-24_17-47-15](https://cloud.githubusercontent.com/assets/28905767/26412819/42ba8b1c-40aa-11e7-9aec-999196fe9543.jpg)

**Comment by nxtester** [comment]
Ah, ok, just saw your answer. Didn't know the video- seems to be brandnew :-) Will try it now and report here. Thanks for your effort!

**Comment by enoch85** [comment]
Like I said, it's not the scripts that are wrong here, it's the Collabora app that isn't updated. Collabora is installed, you just have to reinstall the App. :)

**Comment by nxtester** [comment]
Watched ur video several times, did it all 1:1, no success. Last click (19:28) won't work, always error msg: "App "Collabora Online" cannot be installed because it is not compatible with this version of the server."

If I remove Collabora in the admin section according to your video, it always appears again if page is reloaded. Restarted server, tried again, same result.

Video is a bit messy because no sound and much pages after 17:35 w/o effect for this problem.

**Comment by enoch85** [comment]
@nxtester Send me an email

**Comment by nxtester** [comment]
ok, sent. Thank you!

**Comment by oleksavr** [comment]
Hello! I tried to install nextcloud with collabora but after installation nextcloud is working but collabora gave me an error message that internal error happened and it show me ip of my nginx web server. My installation it is virtual machine which connected to the internet through nginx web server machine. I will be appreciate for any advice or help to resolve this error. 
Thank you ,
Oleksandr
