### ISSUE TITLE
 Slow downloads and uploads

### ISSUE THREAD

**Issue by adam23450** [nextcloud/vm#2372]
### Steps To Reproduce

The whole problem was registered on the forum nextcloud, no one is able to answer what may be wrong.
https://help.nextcloud.com/t/slow-downloads-and-uploads/142881

### Expected Result

Help in solving

### Actual Result

Help in solving

### Build Version

24.0.3

### Environment

By downloading the VM

### Environment Details

Hardware Configuration - Proxmox 128 GB RAM, CPU i7-8700T
VM Configuration (CPU / RAM details) - 4 CPU, 8GB RAM, 8 GB SWAP
VM on HDD or SSD? (details of the Disk) - HDD RAID 5 - HAID 5 4x 4TB WD Red Plus
Which Hypervisor - Proxmox
Hardware accelerations enabled on VM? - Yes
VM OS? -Debian 11
NextCloud deployment details? (like snap or docker or native?) - native
SSL running or not? - Yes, running
What else are running on that same hypervisor and inside that same VM? 3 VM DNS and SAMBA
Please include your testing details,

Network to hypervisor native disk, like SMB share copy speed → ~110MB/s ~980 mb/s
Network to VM Disk, like SMB share copy speed → ~110MB/s ~980 mb/s
Network to NextCloud via WEB upload speed → link agregation 2x 1 Gb/s

**Comment by enoch85** [comment]
Sorry, but this is not a support forum. If you need support, please consider buying support in our [shop](https://shop.hanssonit.se/).
