### ISSUE TITLE
Error with desec update script

### ISSUE THREAD

**Issue by jalabaya** [nextcloud/vm#2374]
### Steps To Reproduce

From CLI: sudo bash /var/scripts/menu.sh --> Server Configuration --> deSEC

### Expected Result

Updating desec via script. Trying to update desec, as I had similar issues (no connectivity after update) in the past and thought I tried to see if it the same error again.

### Actual Result

`Script failed to download. Please run: 'sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.sh|php|py' and try again.                                                                                                                                              If it still fails, please report this issue to: https://github.com/nextcloud/vm/issues.`

### Additional Context

Running ` 'sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.sh|php|py' `

returns:

```
Command 'py' not found, but can be installed with:

apt install pythonpy
```

After installing `pythonpy`, it returns:

`/usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
`

### Build Version

24.0.3

### Environment

By using the scripts

### Environment Details

Distributor ID: Ubuntu
Description: Ubuntu 20.04.4 LTS
Release: 20.04
Codename: focal

PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

dpkg -l | grep mysql
ii libmysqlclient21:amd64 8.0.30-0ubuntu0.20.04.2 amd64 MySQL database client library
ii mysql-common 5.8+1.0.5ubuntu2 all MySQL database common files, e.g. /etc/mysql/my.cnf
ii php-mysql 2:7.4+75 all MySQL module for PHP [default]
ii php7.4-mysql 7.4.3-4ubuntu2.12 amd64 MySQL module for PHP

**Comment by enoch85** [comment]
Sorry but I can't reproduce this. To download the latest deSEC script, use the menu script and choose deSEC in the Server Configuration menu.

**Comment by jalabaya** [comment]
I am doing that. I would not have the knowledge to craft those commands myself.  ^^

`sudo bash /var/scripts/menu.sh`

![image](https://user-images.githubusercontent.com/83626396/184457224-669ab32d-e09b-46c0-97f9-763ff26cda09.png)

![image](https://user-images.githubusercontent.com/83626396/184457253-a8b107a5-5ebc-451e-8544-1caf53203551.png)

![image](https://user-images.githubusercontent.com/83626396/184457283-8f79ed92-1932-47de-8bb0-11896b4b6054.png)

Meanwhile In the terminal: 

```
# sudo bash /var/scripts/menu.sh
Running the main menu script...
Testing if network is OK...
Checking connection...
Downloading the Server Configuration Menu...
Downloading the deSEC install script...
Downloading desec failed
```

Then running the command as per info returned from the script: `sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.sh|php|py`

returns

```
/usr/bin/py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
```
(obvisouly the error about missing `py` as mentioned above is not showing up, as I had installed it at the time.)

**Comment by enoch85** [comment]
OK, please run `sudo bash /var/scripts/update.sh` to get the latest menu script, then try again.

**Comment by enoch85** [comment]
Did it help? :)

**Comment by jalabaya** [comment]
Thank you for the update,but unfortunately no, it did not help. I still get the same errors as above, when trying to start the desec procedure.

**Comment by enoch85** [comment]
Can you please post a video of the issue?

**Comment by jalabaya** [comment]
Err, ok. I hope this helps.  I already did the update at this point

https://user-images.githubusercontent.com/83626396/184897682-c7467883-e2b9-48ca-910e-b319dfbe7b84.mp4

.

**Comment by enoch85** [comment]
Sorry, I can't make a video since I'm on Wayland (Ubuntu 22.04), but doing the exact same thing as you result in a successful download.

Please check your firewall for countryblock.

**Comment by enoch85** [comment]
Here are some pictures at least. Note the date and time at the top.

![Screenshot from 2022-08-18 23-38-18](https://user-images.githubusercontent.com/4511254/185499963-c0982e60-536e-4ae3-a3ee-bc18f9fac556.png)
![Screenshot from 2022-08-18 23-38-33](https://user-images.githubusercontent.com/4511254/185499967-c382c776-9e9c-426f-9cb3-b634897a0d60.png)
![Screenshot from 2022-08-18 23-38-46](https://user-images.githubusercontent.com/4511254/185499968-7fe2f428-fc58-4972-a013-a886c84b4b0e.png)

**Comment by jalabaya** [comment]
I do not see a difference in the screenshots. Mine shows 2022 as well?

There is no countryblock.

But in that one screenshot where it says:

```Script failed to download. Please run: 'sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.sh|php|py' and try again. If it still fails, please report this issue to: https://github.com/nextcloud/vm/issues.  ```

There is only a 404 at  https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.sh . The correct link seems to be https://raw.githubusercontent.com/nextcloud/vm/master/addons/deSEC/desec.sh

It still would not run with the way the command is crafted, but I was able to get the script from the second link with `wget` and it ran successfully (appears to be the case though)..

**Comment by enoch85** [comment]
True, the path has updated, so with the latest script everything should be in order.

**Comment by jalabaya** [comment]
Other than comparing checksums, is there a way to ensure I have the latest script? I did re-run the update script several times by now. 

I also discovered the Debug functionality: 

```
sudo bash /var/scripts/desec_menu.sh
+ root_check
+ is_root
+ [[ 0 -ne 0 ]]
+ return 0
++ whiptail --title 'Nextcloud VM - 2022 - deSEC Menu' --menu 'Please choose one of the deSEC options below.
Navigate with the [ARROW] keys and confirm by pressing [ENTER]. Cancel by pressing [ESC].\n\nYou can view this script later by running '\''sudo bash /var/scripts/menu.sh'\''.' '' '' 4 'Install deSEC' '(Setup deSEC fully automated: yourdomain.dedyn.io)' 'deSEC Subdomain' '(Add or delete subdomains to an existing deSEC domain)' 'Remove deSEC' '(Remove your deSEC account completely'
+ choice='Install deSEC'
+ case "$choice" in
+ print_text_in_color '\e[0;96m' 'Downloading the deSEC install script...'
+ printf '%b%s%b\n' '\e[0;96m' 'Downloading the deSEC install script...' '\e[0m'
Downloading the deSEC install script...
+ run_script ADDONS desec
+ rm -f /var/scripts/desec.sh /var/scripts/desec.php /var/scripts/desec.py
+ download_script ADDONS desec
+ download_script_function_in_use=yes
+ rm -f /var/scripts/desec.sh /var/scripts/desec.php /var/scripts/desec.py
+ curl_to_dir https://raw.githubusercontent.com/nextcloud/vm/master/addons desec.sh /var/scripts
+ '[' '!' -d /var/scripts ']'
+ rm -f /var/scripts/desec.sh
+ '[' -n yes ']'
+ curl -sfL https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.sh -o /var/scripts/desec.sh
+ curl_to_dir https://raw.githubusercontent.com/nextcloud/vm/master/addons desec.php /var/scripts
+ '[' '!' -d /var/scripts ']'
+ rm -f /var/scripts/desec.php
+ '[' -n yes ']'
+ curl -sfL https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.php -o /var/scripts/desec.php
+ curl_to_dir https://raw.githubusercontent.com/nextcloud/vm/master/addons desec.py /var/scripts
+ '[' '!' -d /var/scripts ']'
+ rm -f /var/scripts/desec.py
+ '[' -n yes ']'
+ curl -sfL https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.py -o /var/scripts/desec.py
+ print_text_in_color '\e[0;91m' 'Downloading desec failed'
+ printf '%b%s%b\n' '\e[0;91m' 'Downloading desec failed' '\e[0m'
Downloading desec failed
+ sleep 2
+ msg_box 'Script failed to download. Please run: '\''sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.sh|php|py'\'' and try again.

If it still fails, please report this issue to: https://github.com/nextcloud/vm/issues.'
+ '[' -n '' ']'
+ whiptail --title 'Nextcloud VM - 2022 - deSEC Menu' --msgbox 'Script failed to download. Please run: '\''sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/addons/desec.sh|php|py'\'' and try again.

If it still fails, please report this issue to: https://github.com/nextcloud/vm/issues.' '' ''
+ exit 1

```

The new path is not shown. So in `/var/scripts/desec_menu.sh ` I found the difference in line 29 between Github and what is on my VM. Once I do that change on my VM the desec.sh script runs properly. So it seems to me the update of scripts was not successful. So, again, how can I know, if I run the latest scripts?

**Comment by enoch85** [comment]
Have a close look here: https://github.com/nextcloud/vm/blob/master/menu/desec_menu.sh#L29

Your script uses the legacy path. That's why it doesn't work.

**Comment by jalabaya** [comment]
You must have missed the bit in my post where I wrote how I compared Github and local and making the change manually fixed it. Sorry, if it was not clear.

My question is now, how can I ensure or check, that I am running the latest version of scripts? You said that running the update script would fetch the latest ones, but it does not in my case. Would you prefer if I opened a new issue, since it is a different topic?
