### ISSUE TITLE
Can Google Domains DDNS be supported?

### ISSUE THREAD

**Issue by 93-infinity** [nextcloud/vm#2378]
**Is your feature request related to a problem? Please describe.**
Thanks for the easy-to-use vm. Before using the Nextcloud VM, I signed up for Google Domains. I noticed that the instructions for it use ddclient, which is what the nextcloud vm uses. 

**Describe the solution you'd like**
Could Google Domains be supported in the DDNS update options? That way, I could use `nextcloud.mygoogledomain.com`.

**Describe alternatives you've considered**
I managed to get desec.io working, resulting in `mydomain.dedyn.io`. 

**Additional context**
[Page on Google Domains DDNS](https://support.google.com/domains/answer/6147083)
![nc01](https://user-images.githubusercontent.com/16083086/185412994-bdfbbf37-e78f-4b4d-a5c9-e1e9df6c0b57.png)
)

**Comment by enoch85** [comment]
If you want to implement it, sure! A PR would be reviewed and merged if done correctly.

**Comment by 93-infinity** [comment]
I made a PR, I modeled it after the existing ddns options and adding ddclient options as per google's sample ddns config [here](https://support.google.com/domains/answer/6147083?hl=en#zippy=%2Cset-up-a-client-program-on-your-gateway-host-or-server). I tested it, with junk credentials, it fails to update, with actual credentials, it succeeds.... so I think it's working. I listed what I did in the PR, if you could have a look if it is done right and let me know that'd be appreciated.
