### ISSUE TITLE
Add live indexing to FTS

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2379]
https://github.com/nextcloud/fulltextsearch/wiki/Basic-Installation#live-index-service

We should add this to continuously index files, otherwise it seems that only the first index will be the files that are indexed.

cc  @Ark74

**Comment by Ark74** [comment]
This might be a bug on the fulltextsearch-elasticsearch app, as once it completes the full index it uses cron to index the later files.
Maybe @ArtificialOwl knows more on the subject.

**Comment by szaimen** [comment]
> as once it completes the full index it uses cron to index the later files.

I talked to him and this is how it should work.

So live index is not needed and should actually not be run if you can wait for the cron execution.
