### ISSUE TITLE
Missing .ocdata on second drive (but has never had a second drive)

### ISSUE THREAD

**Issue by ozinfotech** [nextcloud/vm#2382]
### Steps To Reproduce

1. PuTTY into server
2. Type "sudo bash /var/scripts/update.sh" without the quotes
3. Wait...until error
![Error](https://user-images.githubusercontent.com/35508717/186722809-c38cac69-22c6-4d41-9ed4-13a87eb914b7.PNG)

### Expected Result

The update to finish successfully.

### Actual Result

Error message of: 

```
Your .ocdata are missing in the Nextcloud data folder. This probably means that you failed to mount the second drive, or that it failed to import during boot of the system.

We can't continue without it, so please shutdown the machine and double check that the second disk is correctly mounted in your hypervisor/server then try again.
```

### Additional Context

This was downloaded from techandme.se in October 2017. It's been upgraded multiple times without issue.

### Build Version

24.0.1

### Environment

By downloading the VM

### Environment Details

Ubuntu 20.04.4 LTS (Focal Fossa)
PHP 7.4.3
PostgreSQL 12.12
HyperV: 2 Xeon processors, 8GB RAM

**Comment by enoch85** [comment]
Thanks for posting!

What's the location of your datadir?

**Comment by ozinfotech** [comment]
It is here:
`/var/ncdata`

**Comment by enoch85** [comment]
Should be fixed, please try again and confirm it's working. 

Thanks!

**Comment by ozinfotech** [comment]
Yes! Confirmed! Thank you.
