### ISSUE TITLE
Email during update process gives error code 76

### ISSUE THREAD

**Issue by ozinfotech** [nextcloud/vm#2383]
### Steps To Reproduce

PuTTY into server
Type "sudo bash /var/scripts/update.sh" without the quotes
Wait...until error
![Empty Reply](https://user-images.githubusercontent.com/35508717/186741035-e8dbe911-038d-4057-9e4e-28aa516740cd.PNG)

### Expected Result

Expect email to be sent and received.

### Actual Result

Sending 'Update script started!' to email[@]domain[.]com
send-mail: the server sent an empty reply
send-mail: could not send mail (account default from /etc/msmtprc)
Can't send mail: sendmail process failed with error code 76

### Additional Context

I can log in to the GUI and send an email without problem. The update script, however, fails.
![Successful](https://user-images.githubusercontent.com/35508717/186741125-210bcee7-dd8f-4548-a4d8-a6ddc7824e3a.PNG)

### Build Version

24.0.1

### Environment

By downloading the VM

### Environment Details

Ubuntu 20.04.4 LTS (Focal Fossa)
PHP 7.4.3
PostgreSQL 12.12
HyperV: 2 Xeon processors, 8GB RAM

**Comment by enoch85** [comment]
Thanks for posting!

This is not a bug, it's you that entered the credentials wrong when setting it up so that it can't send emails through CLI.

CLI emails and GUI emails are two different things, so what you should do is to run the mail setup again from the `menu.sh` script in your `/var/scripts` folder.

Hope it helps!

**Comment by ozinfotech** [comment]
Cheers and thank you much! We recently migrated from Exchange to Google Workspace and I didn't think about the mail setup from the `menu.sh` script.

**Comment by ozinfotech** [comment]
I tried it again, and am still getting the same error message. I tried changing the _account_, _from_, and _account default_ names to our domain since I have it set to not accept outside domain names. Our IP address is whitelisted and I don't have any problems with any other servers sending email through the same settings, or even the GUI to send an email.

Do you know if these values are correct?
- We recommend that servers presents unique identifiers in the HELO or EHLO arguments during SMTP connections. For example, use your domain name or the server name, instead of generic identifiers such as localhost or smtp-relay.gmail.com.
- The SMTP Relay service doesn't support multiple envelope recipients (RCPT TO) when using a null envelope sender (MAIL FROM: <>).

Those seem to be the only other things that could go wrong.
![Script](https://user-images.githubusercontent.com/35508717/186942183-5f171391-207a-47fc-95ca-ec278074e97a.PNG)

**Comment by enoch85** [comment]
nextcloudvm.com is a real domain, so it should work as intended. Have you tested your changes?

**Comment by ozinfotech** [comment]
It's not that it isn't a real domain, it's that I've set Google to only allow email addresses from our domain as the sender. I've got Google set to: "The sender doesn't have to be a Google Workspace user, but must be in one of your registered domains."

Yes, I tested it by running the update script and seeing if the mail would work. It, unfortunately, didn't.

**Comment by ozinfotech** [comment]
I can confirm that the following line gets the same error message with the username@domain.com replaced with appropriate domain.
`printf "Subject: Hello there." | msmtp -a default username@domain.com`

**Comment by enoch85** [comment]
@ozinfotech If you need support, you're welcome to visit our [shop](https://shop.hanssonit.se/).

**Comment by ozinfotech** [comment]
Sounds good. I'm thinking this is more an `msmtp` problem than Nextcloud. I'll see what I can troubleshoot.
