### ISSUE TITLE
Nextcloud Install Script Wont Work

### ISSUE THREAD

**Issue by beni241** [nextcloud/vm#2386]
### Steps To Reproduce

1. Ubuntu 22.04 Server Minimal Install Clean
2. Start Install Script as described

### Expected Result

Nextcloud Installation Works

### Actual Result

After the reboot, I run the "nextcloud-startup-script.sh" with the created user

but after I set the timezone it does not go on, as it can be seen on the screenshot.

I have installed the absolutely same system before in the same way with the previous Nextcloud version. The update to due current version has not worked, there he has also at the update sometime no longer witer made without error, so I thought a reinstallation helps. 

you can also see that the CPU is permanently busy, although only the installation is running but it does not continue.

As soon as I end the process, the CPU load drops.

I have also waited 2 hours and then canceled it and run again, same result.

### Screenshots, Videos, or Pastebins

![Screenshot_3](https://user-images.githubusercontent.com/91013943/187042927-c1776c85-3835-4648-95a7-10c6e6b77cc7.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/91013943/187042928-68e4f5ac-141e-40bf-9367-0498e6da1ad0.jpg)

### Build Version

24.0.4

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04 LTS

Proxmox VM

**Comment by GitMeier** [comment]
I just encountered something that sounds related.

Tried to update by running /var/scripts/update.sh as root, as I have done many times before.

Today it hung somewhere in the process, using one of the assigned CPU cores 100%.
Waiting didn't help, had to CTRL-C the shell script.

After a bit of debugging I found the culprit to be  the line

lowest_compatible_nc 13

in   nextcloud_update.sh

After commenting out that line the update script will complete as usual.

**Comment by enoch85** [comment]
OK, will do a fresh installation here and check the result.

**Comment by xPedion** [comment]
> After commenting out that line the update script will complete as usual.

Can confirm that. I just wanted to update my nextcloud and hit the same problem.
Removing the line fixed it.

**Comment by enoch85** [comment]
Thanks for reporting, should be fixed now! Please confirm.

**Comment by GitMeier** [comment]
Just ran   /var/scripts/update.sh

and it went through everything without hanging.
Looks good.

**Comment by beni241** [comment]
@enoch85 

a clean installation via the script has now worked successfully.
thank you for the quick removal of the bug

greetings
