### ISSUE TITLE
Infinite loop in /var/scripts/update.sh when using non-default datadir

### ISSUE THREAD

**Issue by jshore1296** [nextcloud/vm#2388]
### Steps To Reproduce

When running the update.sh script with a non-default datadir, it hangs in an infinite loop.  I used `set -x` to verify that it happens in the new code from this commit https://github.com/nextcloud/vm/commit/ab4a92d5c2023a54d7a07423aa7800f30bd4da70

As best as I can tell, it's looping when /mnt/ncdata/.ocdata _does_ exist.  I unmounted /mnt/ncdata and the script continued as normal.

I'm not sure why it was looking in /mnt/ncdata at all, since I had already configured a different datadir.

### Expected Result

For update.sh to not hang.

### Actual Result

It hangs.

### Build Version

24.0.4

### Environment

By downloading the VM

### Environment Details

Ubuntu 22.04.1 LTS
PHP 8.1, Postgres 14
4 core intel alder lake i3, 16gb ram

**Comment by enoch85** [comment]
Hi, thanks for posting!

This was fixed yesterday. Please try again.

**Comment by jshore1296** [comment]
Shortly before I filed this I removed the partition from my VM, so I can't verify on my end.  Thanks for looking into this though :)
