### ISSUE TITLE
[talk] Nextcloud Talk High Performance Back-end repo will change it's structure

### ISSUE THREAD

**Issue by morph027** [nextcloud/vm#2392]
### Steps To Reproduce

Run `apt-get update`.

### Expected Result

`apt-get update` finishes without error.

### Actual Result

`apt-get update` finishes with error.

```
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
```

### Additional Context

**Not active yet, will happen with the next upstream or bugfix release**

Announcement: https://gitlab.com/packaging/nextcloud-spreed-signaling/-/issues/5

### Build Version

n/a

### Environment

By using the scripts

**Comment by morph027** [comment]
Not sure how to handle this. Adding `apt-get update --allow-releaseinfo-change` is insecure and should be executed manually, which is not ideal.

Does the VM have any possibility to announce news or notifications to the users? (motd, nextcloud notifications, ...)

**Comment by enoch85** [comment]
Question is why you decided to change your repo in the first place? Is it so important that thousands of users won't be able to run 'apt-update' without an error?

**Comment by morph027** [comment]
Reason was to allow the repo to be flagged properly for unattended-upgrades, which requires these fields. Also, it adheres to best practices to supply them. Unfortunately, i forgot to add them in the past, which leads to this hassle now.

If a user runs `apt-get update` manually, i'll ask for the change to be committed, so no problem from this side. I've also created an issue in my repo to notice anyone who stumbles upon this.

It's just annoying when being used in non-interactive scripts. That's why i created this issue here, so hopefully everybody who runs into this get's the info.

**Comment by enoch85** [comment]
@morph027 We could automatically accept it if TURN is installeld by adding a `-y` flag, right?

**Comment by morph027** [comment]
Installation from scratch would work without any issues. Updating an existing installation will suffer the problem mentioned, but will work if the user runs `apt-get update --allow-releaseinfo-change`

Just using `-y`flag does not work. Also it does not affect the TURN server but the `nextcloud-spreed-signaling`package.

**Comment by enoch85** [comment]
We can check if TURN is installed during update, and just force it with `apt-get update --allow-releaseinfo-change`. It would be the least hassle for the users.

D you think you could prep a PR?

**Comment by enoch85** [comment]
@morph027 As far as I can tell everything is still working as expected. Do you know when this will go live?

**Comment by morph027** [comment]
There is no new build since the announcement. So changes to the repo are not live. Other repos are working fine. Do we want to schedule the change? Or wait until the next upstream release?

**Comment by enoch85** [comment]
@morph027 Did you have time to check my PR?

**Comment by morph027** [comment]
Will do tonight, was travelling yesterday...

**Comment by enoch85** [comment]
Please go ahead and push your fix @morph027
