### ISSUE TITLE
Installing nextcloud server on a raspi 4

### ISSUE THREAD

**Issue by FritschM** [nextcloud/vm#2395]
### Steps To Reproduce

1. unpacked vm-master
2. started sudo bash nextcloud_install_production.sh
3. -> no new user added, no data disk, free space on root ~57GB
4. after a few minutes, script exits with error

### Expected Result

Script should finish without erros, I think

### Actual Result

...
grep: /etc/apache2/apache2.conf: No such file or directory
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xeu apache2.service" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
Running kernel seems to be up-to-date.

Failed to check for processor microcode upgrades.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
ERROR:  role "nextcloud_db_user" already exists
ERROR:  database "nextcloud_db" already exists
PostgreSQL password: t#xxxxxxxxxxxxcr
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  apache2-doc apache2-suexec-pristine | apache2-suexec-custom www-browser
The following NEW packages will be installed:
  apache2
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 0 B/97.8 kB of archives.
After this operation, 546 kB of additional disk space will be used.
Selecting previously unselected package apache2.
(Reading database ... 109449 files and directories currently installed.)
Preparing to unpack .../apache2_2.4.52-1ubuntu4.1_arm64.deb ...
Unpacking apache2 (2.4.52-1ubuntu4.1) ...
Setting up apache2 (2.4.52-1ubuntu4.1) ...
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 142.
apache-htcacheclean.service is a disabled or a static unit not running, not star
ting it.
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for ufw (0.36.1-4build1) ...
Rules updated for profile 'OpenSSH'
Skipped reloading firewall
Scanning processes...                                                           
Scanning processor microcode...                                                 
Scanning linux images...                                                        

Running kernel seems to be up-to-date.

Failed to check for processor microcode upgrades.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
ERROR: Module rewrite does not exist!
ERROR: Module headers does not exist!
ERROR: Module proxy does not exist!
ERROR: Module proxy_fcgi does not exist!
ERROR: Module setenvif does not exist!
ERROR: Module env does not exist!
ERROR: Module mime does not exist!
ERROR: Module dir does not exist!
ERROR: Module authz_core does not exist!
ERROR: Module alias does not exist!
ERROR: Module ssl does not exist!
ERROR: Module mpm_prefork does not exist!
systemctl restart apache2.service failed
sudo: php: command not found

### Additional Context

Linux version 5.15.0-1015-raspi (buildd@bos02-arm64-077) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #17-Ubuntu SMP PREEMPT Mon Sep 12 13:14:51 UTC 2022

### Build Version

Linux version 5.15.0-1015-raspi (buildd@bos02-arm64-077) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #17-Ubuntu SMP PREEMPT Mon Sep 12 13:14:51 UTC 2022

### Environment

By using the scripts

### Environment Details

Raspi 4 with 64GB Falshdisk.

**Comment by enoch85** [comment]
Sorry, but I don't have a RPi 4 to test this on. It should work to install from scratch, but it was a long time since I tested it.

**Comment by vithusel** [comment]
Can you let me know what version of Ubuntu you are running? I'll install it on my Pi4 this weekend and test it out for you.

**Comment by enoch85** [comment]
@vithusel That would be great! Please test this image: https://ubuntu.com/download/raspberry-pi/thank-you?version=22.04.1&architecture=server-arm64+raspi

**Comment by FritschM** [comment]
I did a reinstallation of ubuntu server yesterday. Now apache2 is working again. Seemed to be a wrong setting in apache2.conf (i removed it in the past, "Never do things in desperation" |-). So I looked forward now ... Thanks so far. ;-)

**Comment by vithusel** [comment]
@FritschM so all working now and i don't need to test anything?

**Comment by enoch85** [comment]
Would be nice if we could get a confirmation that the image I linked actually works out of the box. 👍🏼

**Comment by FritschM** [comment]
No. Not out of the box. Image is only ubuntu server without Nextcloud

Mit freundlichen Grüßen
Matthias Fritsch

Baden - 
Think global, sharing is caring!!

--------------------------------------------------
-- Von /e/ Mail gesendet.

Am 22. Oktober 2022 17:56:45 MESZ schrieb Daniel Hansson ***@***.***>:

**Comment by vithusel** [comment]
Understood. Will check tomorrow and report back

**Comment by enoch85** [comment]
> No. Not out of the box. Image is only ubuntu server without Nextcloud Mit freundlichen Grüßen Matthias Fritsch Baden - Think global, sharing is caring!!
> […](#)
> -------------------------------------------------- -- Von /e/ Mail gesendet. Am 22. Oktober 2022 17:56:45 MESZ schrieb Daniel Hansson ***@***.***>:
> Would be nice if we could get a confirmation that the image I linked actually works out of the box. 👍🏼 -- > Reply to this email directly or view it on GitHub: [#2395 (comment)](https://github.com/nextcloud/vm/issues/2395#issuecomment-1287834084) You are receiving this because you were mentioned. Message ID: ***@***.***>

Well, question was if the installer scripts work "out of the box" with that image?

**Comment by enoch85** [comment]
> Understood. Will check tomorrow and report back

Thanks!! ☝🏻

**Comment by vithusel** [comment]
Sorry for the delay on this. 

Had heavy winds last night and my house is currently powerless. 

Will report back on this as soon as i get power back!

**Comment by enoch85** [comment]
Hi, just curious - any progress here?

**Comment by enoch85** [comment]
@vithusel Are you still out of power? :)

**Comment by vithusel** [comment]
@enoch85 oh god. so sorry! Slipped my mind completely. Will check tomorrow and report back!

**Comment by enoch85** [comment]
@vithusel Thanks! :)

**Comment by vithusel** [comment]
> @vithusel Thanks! :)

The install script is in progress. 

Stupidly i seem to have misplaced my ssd so im stuck on installing to a slow sd card. Ill leave it to install overnight as its taking forever and will report in when im back at work tomorrow

**Comment by enoch85** [comment]
@vithusel So what's the outcome? :)

**Comment by vithusel** [comment]
> @vithusel So what's the outcome? :)

Confirmed to be working. No issues :)

**Comment by enoch85** [comment]
Horaay! :D 

Thanks for testing!
