### ISSUE TITLE
Nextcloud Install Script not accepting new User_ID / Password / Static IP Address

### ISSUE THREAD

**Issue by joe28a** [nextcloud/vm#2396]
### Steps To Reproduce

Followed install instruction for importing the Nextcloud VM [Pre-installed – 40 GB OVA to VMware ESXi 6.7.
1. Import Nextcloud 40Gb
2. Used U=ncadmin / P=nextcloud
3. Install script would automatically start

During the install script execution, it would prompt and a new User_ID / Password &  option to enter a Static IP Address, none of which were accepted.  Upon completion of the Nexcloud VM install, I was unable to login at all rendering the VM unusable.  I restarted the install process with the same result.

### Expected Result

Install to accept User_ID / Password &  Static IP Address during install which did not occur.

### Actual Result

The Nexcloud VM would start but would not accept the new credentials.

### Screenshots, Videos, or Pastebins

No screen shots available at this time.

### Additional Context

No further comment.

### Build Version

24.0.5

### Environment

By downloading the VM

### Environment Details

- VMware ESXi v6.7
- 16Gb RAM

**Comment by enoch85** [comment]
If you're using the VM console during setup, the keyboard layout might be different from when you type in your OS.

So, use an SSH client to be sure that the passwords are the same in both OS and the VM. Putty or similar works. :+1:

**Comment by joe28a** [comment]
Hi @enoch85, 
Thank you for your prompt response.  I just completed a re-installation of the Nextcloud VM and used puTTY via SSH to go through all the script steps.  Post reboot of the VM, the entered Username/Passwords for Ubuntu OS & Webmin were not accepted, however, I could login to the Nextcloud Web Page.  The credentials have been changed but have no idea what is was changed to; I still cannot login to the Ubuntu OS which will be an issue in moving forward.  Do you have any further suggestions here?, thank you.

**Comment by joe28a** [comment]
Hi @enoch85 
I managed to get the Nexcloud VM to work.  During the installation process, I manually created additional users in the Ubuntu OS & Webmin then continued on with the installation script.  The final result is what I was expecting, thank you for your assistance here, take care.
