### ISSUE TITLE
"curl didn't produce 200 status" on latest build - 24.0.5

### ISSUE THREAD

**Issue by willjukebox** [nextcloud/vm#2397]
### Steps To Reproduce

1. Import .OVA for 40gb VM thin client into VMWare
2. Type in admin "ncadmin" and password "nextcloud"
3. Type in password again
4. Error states "curl does not produce 200 status" and retries multiple times with same result
5. UI menu states "The script failed to get an address from DHCP ... You will now be provided with the option to set a static IP manually instead.
6. Follow Static IP configuration but still unable to connect

### Expected Result

VM client sets up network after second time entering password and user can move on to systems configuration.

### Actual Result

Setup is stuck at "curl does not produce 200 status" and trapped in loop of going through setting up static IP with no setup progress made.

### Screenshots, Videos, or Pastebins

<img width="494" alt="Screenshot 2022-10-09 110806" src="https://user-images.githubusercontent.com/59858115/194772730-840b19b4-2044-4cc0-8d7f-e1e93421d6e2.png">
<img width="497" alt="Screenshot 2022-10-09 110959" src="https://user-images.githubusercontent.com/59858115/194772732-08a40871-b263-49a0-9881-0ff75d5d4586.png">

### Build Version

24.0.5

### Environment

By downloading the VM

### Environment Details

- Windows 10
- Running in VMWare
- Computer connected to internet via ethernet
- VMWare bridged connection
- Network Adapters: 
--- Intel Wireless AC 9560 160MHz
--- Realtek PCIe GbE Family Controller
--- VMware Ethernet Adapter for VMnet1
--- VMware Ethernet Adapter for VMnet8

**Comment by enoch85** [comment]
Check your firewall, do you have country block enabled?
