### ISSUE TITLE
onlyoffice docker. Local.json reset after every reboot.

### ISSUE THREAD

**Issue by fabnext77** [nextcloud/vm#2402]
### Steps To Reproduce

Hello, we installed onlyoffice with docker using your script. 
In all the installations we have, we are encountering the follow problem: every time we reboot the server the local.json file is regenerated and the secret pwd in the file too, that means that we have to reinsert again in nextcloud onlyoffice setting.
any suggestion? it was working fine for months and now we have this problem.
Regards

[Nextcloud] 24.0.6
Version 7.2.0.204

### Expected Result

the pwd and the file local.json stays as they are and not change after reboot

### Actual Result

everytime we have to insert the new generated pwd into local.json file to let onlyoffice work

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/71324914/196420113-3a50750a-5116-4f87-8057-cb0625a1cc0a.png)
![image](https://user-images.githubusercontent.com/71324914/196420245-f21756ca-6653-46f2-95db-c5cec0b1ae56.png)
![image](https://user-images.githubusercontent.com/71324914/196420664-da1d5d29-4d03-4b7c-bc2f-c0bd7a3c9e6d.png)
![image](https://user-images.githubusercontent.com/71324914/196420824-c5f72e08-f95e-43a4-ae9b-c936a87ff8c8.png)

### Build Version

24.0.6

### Environment

By downloading the VM

**Comment by szaimen** [comment]
Did they already try to reinstall using the script?

**Comment by enoch85** [comment]
@fabnext77 Did you reinstall already?

**Comment by fabnext77** [comment]
Hello,

I have Nextcloud with this problem in 4 production server, sorry for delay but any test should be done in staging vm.

 

Last week try to reinstall Nextcloud docker was one of attempts and it was not working.
I decided to give a second chance and tried again last night using the script and selecting “reinstall OnlyOffice (Docker)”. First time that I tried same result as before and also I have got a major problem: the procedure was interrupted and after there was no onlyoffice and also app online were not anymore available inside Nextcloud menu.

 

Instead reverting the snapshot I decide to reboot the vm and try again by the same procedure via script: this time the process was completed and everything looks fine now! I tried to reboot few times and the encryption key doesn’t change. 

 

It is my intention to replicate the whole procedure on the production server and I will let you know, I can do that only during the night.

 

Thank you for your collaboration.

Fabio

**Comment by szaimen** [comment]
we merged an improvement 6 days ago so it makes sense if you try to reinstall

**Comment by szaimen** [comment]
> this time the process was completed and everything looks fine now! I tried to reboot few times and the encryption key doesn’t change. It is my intention to replicate the whole procedure on the production server and I will let you know, I can do that only during the night.

Thanks, sounds good!

**Comment by enoch85** [comment]
So I consider this solved. Please reopen if not. :+1:

**Comment by fabnext77** [comment]
To give you feedback, I hope is useful for you.

 

Yesterday night I have updated three production servers and they look fine now! 
In this cases I didn’t even need to do a “double” onlyoffice docker deploy.

Thank for your help
