### ISSUE TITLE
Update NC to v25 FullTextSearch problem

### ISSUE THREAD

**Issue by sebaxakerhtc** [nextcloud/vm#2404]
### Steps To Reproduce

1. Go to 'menu' => 'additional apps' => FullTextSearch
2. Click on 'reinstall'
3. Scroll down to 'error'
4. Click on 'issues'

### Expected Result

Working FullTextSearch

### Actual Result

Installing files_fulltextsearch...
App "Full text search - Files" cannot be installed because it is not compatible with this version of the server.

### Screenshots, Videos, or Pastebins

![error](https://user-images.githubusercontent.com/32651506/197334300-33e700a1-1d90-4c85-9c42-d06de7a61e2a.png)

### Additional Context

Looking for a text app in NC Applications, because it missing after update and see there are not enabled FullTextSearch, ElasticSearch, etc.
So, ssh to server, run `sudo bash /var/scripts/menu.sh` and choose to reinstall this app, but 
```
 There are no commands defined in the "fulltextsearch" namespace.


Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:configure {"search_platform":"OCA\\FullTextSearch_Elasticsearch\\Platform\\ElasticSearchPlatform"} failed
```

### Build Version

25.0.0

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04 in VM on VMWare
RAM: 16GB
CPU: Xeon E5-2680v2

**Comment by enoch85** [comment]
"It's not a bug, it's a feature." Since the app isn't compatible, it can't be installed, so everything here works exactly as it was intended.

**Comment by sebaxakerhtc** [comment]
> "It's not a bug, it's a feature." Since the app isn't compatible, it can't be installed, so everything here works exactly as it was intended.

Thank you for the answer. I create an issue, because of recommendation from terminal 😉

**Comment by enoch85** [comment]
> > "It's not a bug, it's a feature." Since the app isn't compatible, it can't be installed, so everything here works exactly as it was intended.
> 
> Thank you for the answer. I create an issue, because of recommendation from terminal 😉

Thanks! 👍🏼
