### ISSUE TITLE
No description of how to perform a full restore from daily backups

### ISSUE THREAD

**Issue by rileytroyer** [nextcloud/vm#2407]
### Steps To Reproduce

1. Create a daily backup script as per the unsupported daily-borg-backup feature and point backup directory to an external drive.
2. Allow backup script to run, so that the files are backed up on the the external drive.
3. Attempt to restore data from a clean install of the Nextcloud VM using the restore-backup.sh script.

### Expected Result

The restore-backup.sh script seems to be designed to restore from a new Nextcloud instance, though I haven't been able to find any documentation on this and I realize it's an unsupported script, so perhaps I'm wrong?

I would expect that I could boot up a completely new Nextcloud VM, download the restore-backup.sh script and it would allow me to restore from the backup drive.

### Actual Result

When I run the restore-backup.sh script on a clean Nextcloud VM install it get the error:

"Unfortunately NcVM-snapshot doesn't exist, hence you are not able to restore the system."

I was able to get passed this by running the update script, which created a NcVM-snapshot, however then I got the error:

"The '/mnt/ncdata' directory is mounted and not existing on the root drive. This is currently not supported by this script."

These errors seem odd to me as they came up on a stock Nextcloud VM install. Is this not the way the restore-backup.sh script was designed to be run? If so, how is it supposed to be run?

### Build Version

24.0.6

### Environment

By downloading the VM

### Environment Details

- Guest is newest Nextcloud VM running on a Ubuntu 22.04 server
- Host is Ubuntu 20.04 computer running VMWare Player

**Comment by enoch85** [comment]
cc  @szaimen :point_up:

**Comment by szaimen** [comment]
What is the output of 
`sudo grep /mnt/ncdata /etc/mtab` ?

**Comment by rileytroyer** [comment]
"ncdata /mnt/ncdata zfs rw,noatime,xattr,noacl 0 0"

**Comment by szaimen** [comment]
This should be supported. See https://github.com/nextcloud/vm/blob/c5a990e277dec08715d422a20b89a4fa71b80d1a/not-supported/borgbackup.sh#L164

What does `grep -q " /mnt/ncdata " /etc/mtab && ! grep " /mnt/ncdata " /etc/mtab | grep -q zfs; echo $?` return?

**Comment by szaimen** [comment]
Which script exactly fails when you try to restore? Is it the system restore script?

**Comment by szaimen** [comment]
Ah, it is the restore-backup script. Yes indeed, this use case is not supported currently by that. You can now either hope that I will find some time to implement the feature or ask @enoch85 to do it or ask him to do the migration for you.

**Comment by szaimen** [comment]
@enoch85 it is about this script: https://github.com/nextcloud/vm/blob/master/not-supported/restore-backup.sh

**Comment by rileytroyer** [comment]
Ah, okay. Thanks for the info! Is there a restore method you would recommend? For instance a clean install via docker or something similar? Just trying to test my recovery method in case of a catastrophic failure.

**Comment by szaimen** [comment]
> Is there a restore method you would recommend?

The restore-backup script is the restore method I would usually recommend.

**Comment by szaimen** [comment]
> as the stock VM is configured such that it gives the error?

You can create your own VM with a clean Ubuntu install using the script without adding the zfs partition. Then will the script work.

**Comment by rileytroyer** [comment]
Okay, thank you very much for the help!
