### ISSUE TITLE
Cannot upgrade to 25.0.0 after previously upgrading to 25.0.0RC5

### ISSUE THREAD

**Issue by meichthys** [nextcloud/vm#2408]
### Steps To Reproduce

1. Used the update.sh script to upgrade to beta version 25.0.0RC5
2. Now trying to upgrade to stable 25.0.0

Nextcloud shows:
![image](https://user-images.githubusercontent.com/10717998/198187893-6f7696c1-b809-43ec-9134-ce33ca8218e6.png)

I've tried changing branch to stable in the nextcloud web ui
I've tried using the `update.sh` script with (and without) the `beta` flag

### Expected Result

I would expect the script to update to 25.0.0

### Actual Result

The script reports that I'm already on the latest version:
```
Checking for new Nextcloud version...
You already run the latest version! (25.0.0)
```

But Nextcloud still shows:
![image](https://user-images.githubusercontent.com/10717998/198188093-397a9e34-fcf3-436c-9a1d-2c5d0809e6aa.png)

### Build Version

25.0.0 RC5

### Environment

By using the scripts

### Environment Details

- OS: Ubuntu (on Proxmox Container)
- PHP: 8.1

**Comment by enoch85** [comment]
The version checker sorts the versions with a `head` so if RC5 is after the stable version in that list, it won't update. RC5 is supposed to be super stable though, so you can wait for 25.0.1 without any issues. 

You could also check for a better way to check versions if you want: https://github.com/nextcloud/vm/blob/master/lib.sh#L143-L149

**Comment by meichthys** [comment]
Ok thanks! I'll be patient 👍
