### ISSUE TITLE
Optimized latest version detection

### ISSUE THREAD

**Issue by ypid** [nextcloud/vm#241]
[lib.sh](https://github.com/nextcloud/vm/blob/master/lib.sh) uses

```Shell
NCVERSION=$(curl -s -m 900 $NCREPO/ | tac | grep unknown.gif | sed 's/.*"nextcloud-\([^"]*\).zip.sha512".*/\1/;q')
```

to get the latest version including patch level. While working on https://github.com/debops/ansible-owncloud/pull/83, I optimized it abit which you might want to check out:

```Shell
curl -s -m 900 $NCREPO/ | sed --silent 's/.*href="nextcloud-\([^"]\+\).zip.asc".*/\1/p' | sort --version-sort --reverse
```

The previous implementation makes too much assumptions which I would like to avoid (e.g. sorted index, unknown.gif, presence of one checksum algo instead of more generic OpenPGP signature).

**Comment by enoch85** [comment]
Thanks @ypid I really appreciate it. 

Will test this tomorrow. 

Keep 'em coming ;)

**Comment by ypid** [comment]
Thanks, you are welcome :smile:
