### ISSUE TITLE
No Bootable Medium found on appliance created through OVA

### ISSUE THREAD

**Issue by coyoteconscious** [nextcloud/vm#2415]
### Steps To Reproduce

Import appliance.
select 40GB_Nextcloud-VM_www.hanssonit.se.ova
Wait for appliance to import
run apppliance

### Expected Result

The appliance should import from the ova file, and the environment should boot in a virtual machine.

### Actual Result

When virtual machine boots, it claims there is no bootable device, and will not boot.

### Build Version

24.0.7

### Environment

By downloading the VM

**Comment by enoch85** [comment]
@coyoteconscious Did you manage to bypass this?

How does the actual VM look? Are both drives imported? Which system is this running on?

I can't reproduce this.
