### ISSUE TITLE
Update from v24 to v25 failed - apache server won't start anymore

### ISSUE THREAD

**Issue by xelayz** [nextcloud/vm#2419]
### Steps To Reproduce

1. I connected with my local network at home via VPN
2. I connected via SSH to my Nextcloud instance
3. Then I started the update script
4. Then I did some other stuff and lost the connection to my VPN
5. SSH session also lost the connection for sure

Then I was like "Oh shit. But ok, update will run automatically, so I will wait 1 hour".

### Expected Result

The expected result was, that my Nextcloud is up2date. I had no problems with updates of previous versions.

### Actual Result

But then nothing happened, Nextcloud was still offline. I connected again to the VPN and the Nextcloud with SSH.

Then I started the script again and I see this:
https://privatebin.net/?7bb450c5f23a6edf#8UioKccxLbb3oeApVXV6aVTrQNtkSdkFrdGbsJ5TVNxs

Then I checked apache2:
https://privatebin.net/?a42204d780f8b08d#4byhXETSRmaRT5X49zVbJAM7rwCntgk1CR65Sj9jpyTR 3

And then I checked the apach2 site config:
https://privatebin.net/?5dd21bcdef8533e3#5HWfVvzwyvTYs6S3Pe2hrctATcEboaXxEoiAimHxvkQC 3

I think the problem is that the update was still in progress but needed confirmation from me. But instead the SSH session was closed and then at some point the server restarted. So now my Nextcloud VM is in the middle of the update process but cannot continue. Can this be? How can I fix this? ☹️ Or is there any general problem with the VM or update script? But I can only find one issue, where a user also failed to update to v25.

Also when I login to the server, I see this:

`Last login: Sat Dec 24 15:08:42 2022 from 10.8.0.2
bash: /var/scripts/instruction.sh: No such file or directory
ncadmin@cloud:~$ sudo bash /var/scripts/menu.sh
[sudo] password for ncadmin:
`
So there is a missing script. In the other logs I linked there are also some messages where some files are missing.
And I can't see the version of my Nextcloud on this message: https://pic.xelayz.com/images/4638007fd772a30e60d539a3a826ff4a.png

I can't believe that much is broken now, as I just started the update script as usual and then just lost the SSH connection. I already did a reboot. Nothing changed.

### Build Version

24

### Environment

By using the scripts

**Comment by enoch85** [comment]
Thanks for your detailed report, though how do you expect us to fix this? If you connection failed in the middle of an upgrade, that's nothing we can work around. If it's lost it's lost. 

To be 100% sure that updates run as they should, the recommended way of upgrading is through console. Then it will continue even if you loose connection. 

I'm sorry for your issue, and if you need support you can always turn to the [forum](https://help.nextcloud.com) or buy hands on support in our [shop](https://shop.hanssonit.se).

**Comment by xelayz** [comment]
Thank you for your answer. I just want a confirmation that it really can be that a lost SSH connection can break everything. And maybe there is a short way to fix this. But if you think there is no short way to fix it, please tell me that the only solution would be to reinstall everything. Or maybe you can fix everything when I buy support in your shop?

**Comment by enoch85** [comment]
Well, it seems like your whole Nextcloud folder is gone. There should be a backup, so it would be fixable.

You're welcome to buy support in our shop. 👍🏼
