### ISSUE TITLE
Unable to use Signaling Server from an external Nextcloud instance

### ISSUE THREAD

**Issue by angelovolpato** [nextcloud/vm#2424]
### Steps To Reproduce

1. Install a fresh and updated Ubuntu 22.04 server
2. Open TCP ports 3478, HTTP, HTTPS and SSH from internet
3. Install NextCloud VM with shell scripts on Ubuntu 22.04 server
4. Add Talk app and Signaling Server
5. Copy STUN, TURN and Signaling configurations from Nextcloud VM to another Nextcloud instance
6. Make sure that all checks are OK
7. Make a call with TALK

### Expected Result

The call is opened

### Actual Result

Call is not opened, in logs I see the following error:
Client error: `POST https://xxxxxxx.dedyn.io/api/v1/room/z9npf6fi` resulted in a `403 Forbidden` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>403 Forbidden</title> </head><body> <h1>Forbidden (truncated...)

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/98043039/210444835-4de4d801-21db-4c74-9144-5d8da12eb14d.png)

### Additional Context

If I place the call using the same Nextcloud VM instance everything works fine.
The issue is present if I setup the Signaling server from an external Nextcloud instance.

### Build Version

25

### Environment

By using the scripts

### Environment Details

Ubuntu with 8 GB of RAM

**Comment by enoch85** [comment]
Thanks for reporting!

Step number 5 confuses me, you installed Talk Signaling on one server, then copied to another and now you make a report about Talk Signaling doesn't work on the server you copied to? Is that correct?

In that case, why don't you just install using the scripts on the other server? Requirement, it must be the Nextcloud VM.

**Comment by angelovolpato** [comment]
Hi Daniel,

Thanks for your answer.

My goal is to use your script to install a working Talk Signaling Server on
a plain Ubuntu server and then connect an existing Nextcloud instance,
installed in a "normal way", to this Talk Signaling Server.

I can't use the script on the other server since it's not a Nextcloud VM.

I was wondering if this scenario is supported.

Thanks

Il giorno mer 4 gen 2023 alle ore 15:58 Daniel Hansson <
***@***.***> ha scritto:

**Comment by enoch85** [comment]
The VM is a "plain Ubuntu server" (minimal) with Nextcloud installed and optimized, so just use the VM and be happy with the benefits that comes along. :)
