### ISSUE TITLE
CORS fails for Pi-hole when using local IPv4 address

### ISSUE THREAD

**Issue by pq2** [nextcloud/vm#2429]
### Steps To Reproduce

This is possibly an upstream bug, but since upgrading to Ubuntu 22.04 and reinstalling Pi-hole the following problem occurred to me. Requests that require CORS to the Pi-hole admin page (e.g. when I want to change settings) fail when using the local IPv4 address (192.168.178.22) with the following error message from the server: 

Failed CORS: 192.168.178.22 vs 127.0.0.1, 127.0.0.1, pi.hole, localhost.

This is not a big problem for me, as I now simply use pi.hole:8094 instead of the IP address, which works fine. So somewhere the local IPv4 address would still have to be added to the addresses allowed for CORS.

### Expected Result

The Pi-hole admin panel works just fine

### Actual Result

Requests that require CORS fail (changing settings, loading the adlists, ...).

### Build Version

25.0.3.2

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04.1

**Comment by szaimen** [comment]
Hi, yes I think this is an upstream bug or it is our reverse proxy setup but no idea how to fix that. Good that a workaround exists!

**Comment by szaimen** [comment]
Also, I've seen that before. So it is likely unrelated to the ubuntu 22.04 update.
