### ISSUE TITLE
Nextcloud is not installed - only a limited number of commands are available

### ISSUE THREAD

**Issue by gidami** [nextcloud/vm#2434]
### Steps To Reproduce

1. Go to '/var/scripts$ sudo ./update.sh'
4. Click on '...'

### Expected Result

regular update

### Actual Result

ncadmin@nextcloud:/var/scripts$ sudo ./update.sh
Nextcloud is not installed - only a limited number of commands are available
Nextcloud is not installed - only a limited number of commands are available

  There are no commands defined in the "app" namespace.

Nextcloud is not installed - only a limited number of commands are available
Nextcloud is not installed - only a limited number of commands are available

THIS GOES ON FOREVER

  There are no commands defined in the "app" namespace.

Nextcloud is not installed - only a limited number of commands are available
Nextcloud is not installed - only a limited number of commands are available

  There are no commands defined in the "app" namespace.

### Additional Context

web server seems down.

When openic the NC web interface, this error comes out:
Not Found

The requested URL was not found on this server.

### Build Version

24?

### Environment

By downloading the VM

### Environment Details

Proxmox 7.3-3

**Comment by enoch85** [comment]
Hi again,

Seems like your Nextcloud is broken. Is this actually the VM?

Do you run HTTPS via Let's Encrypt or is it only local?

Please try: `sudo bash /var/scripts/menu.sh` --> Update Nextcloud

Also, I can't reproduce this.

**Comment by gidami** [comment]
Hi Daniel,

local only. Yes, it's the VM. Same outcome with menu.sh

Any easy way to rebuild NC without making a mess with the existing stored
data?

***@***.***:~$ sudo bash /var/scripts/menu.sh
[sudo] password for ncadmin:
Running the main menu script...
Testing if network is OK...
Checking connection...
Downloading the latest update script...
Nextcloud is not installed - only a limited number of commands are available
Nextcloud is not installed - only a limited number of commands are available


  There are no commands defined in the "app" namespace.


Nextcloud is not installed - only a limited number of commands are available
Nextcloud is not installed - only a limited number of commands are available


  There are no commands defined in the "app" namespace.


Nextcloud is not installed - only a limited number of commands are available
Nextcloud is not installed - only a limited number of commands are available

**Comment by enoch85** [comment]
Do you have automatic updates turned on, or did you in the past? Seems like an update went wrong. 

Check the contents of `/var/www/nextcloud` - post the result here.

**Comment by gidami** [comment]
If I recall correctly, automatic updates were made for minor releases but I
had to make updates for major releases manually.

***@***.***:~$ sudo ls -hal /var/www/nextcloud
total 176K
drwxr-x--- 15 root     www-data 4.0K Dec 24 18:07 .
drwxr-xr-x  4 root     root     4.0K Dec 24 18:07 ..
-rw-r--r--  1 www-data www-data    0 Dec 24 18:07 .htaccess
-rw-r-----  1 root     www-data  101 Dec  8 12:26 .user.ini
drwxr-x--- 47 root     www-data 4.0K Dec  8 12:32 3rdparty
-rw-r-----  1 root     www-data  19K Dec  8 12:26 AUTHORS
-rw-r-----  1 root     www-data  34K Dec  8 12:26 COPYING
drwxr-x--- 50 www-data www-data 4.0K Dec  8 12:27 apps
drwxr-x---  2 www-data www-data 4.0K Dec 24 18:07 config
-rw-r-----  1 root     www-data 4.0K Dec  8 12:26 console.php
drwxr-x--- 23 root     www-data 4.0K Dec  8 12:35 core
-rw-r-----  1 root     www-data 6.2K Dec  8 12:26 cron.php
drwxr-x---  2 root     www-data 4.0K Dec 24 18:07 data
drwxr-x---  2 root     www-data  12K Dec  8 12:26 dist
-rw-r-----  1 root     www-data  156 Dec  8 12:26 index.html
-rw-r-----  1 root     www-data 3.4K Dec  8 12:26 index.php
drwxr-x---  6 root     www-data 4.0K Dec  8 12:26 lib
-rwxr-x--x  1 root     www-data  283 Dec  8 12:26 occ
drwxr-x---  2 root     www-data 4.0K Dec  8 12:26 ocm-provider
drwxr-x---  2 root     www-data 4.0K Dec  8 12:26 ocs
drwxr-x---  2 root     www-data 4.0K Dec  8 12:26 ocs-provider
-rw-r-----  1 root     www-data 3.1K Dec  8 12:26 public.php
-rw-r-----  1 root     www-data 5.5K Dec  8 12:26 remote.php
drwxr-x---  4 root     www-data 4.0K Dec  8 12:26 resources
-rw-r-----  1 root     www-data   26 Dec  8 12:26 robots.txt
-rw-r-----  1 root     www-data 2.4K Dec  8 12:26 status.php
drwxr-x---  3 www-data www-data 4.0K Dec  8 12:26 themes
drwxr-x---  2 www-data www-data 4.0K Dec  8 12:27 updater
-rw-r-----  1 root     www-data  383 Dec  8 12:32 version.php

**Comment by enoch85** [comment]
All looks good as far as I can see. You can book 30 minutes in our [shop](https://shop.hanssonit.se/product/premium-support-per-30-minutes/) to have a close look.

**Comment by gidami** [comment]
Good idea. Time booked!

**Comment by enoch85** [comment]
`config.php` was missing. Probably due to a failed upgrade. Reverted from backup.
