### ISSUE TITLE
Support for Cloudflare tunnels as Reverse Proxy

### ISSUE THREAD

**Issue by nomi25home** [nextcloud/vm#2435]
Can you please investigate to add other methods to do RP, in addition to opening ports 80/443 on the router/FW for the Nextcloud VMs? Perhaps Cloudflare tunnel support could be one option? Thanks.

**Comment by enoch85** [comment]
You are welcome to investigate, then we can implement. :)

**Comment by nomi25home** [comment]
I was able to get it working. Basically, I login as root (either via console or ssh) and run the script as indicated on Cloudflare
`curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 

sudo dpkg -i cloudflared.deb && 

sudo cloudflared service install <your-token-here>`

After doing that, I deleted the nginx config and disabled port forwarding on my router, and took down the VM (both gracefully and by prematurely stopping it) and the tunnel seems to stay up


So this is a workaround IMO. It'd be nice to incorporate cloudflared as an option when you run 
`sudo bash /var/scripts/menu.sh` and you can configure cloudflare tunnel as a part of the server configuration

**Comment by vithusel** [comment]
There are known issues with using Cloudflare Tunnels with nextcloud. The main one being the NextCloud Client by default cannot upload files larger then 100mb without some configuration changes. Its also against the T&C of Cloudflare to use their tunnels for the main purpose of serving files so probably shouldn't be a option officially provided under a NextCloud Repo.
