### ISSUE TITLE
Docker Onlyoffice not working after update to 25.0.3 with script

### ISSUE THREAD

**Issue by fabnext77** [nextcloud/vm#2436]
### Steps To Reproduce

Hello, we have few installation with Nextcloud, we tried to upgrade to 25.0.3 using the script /var/scripts/menu.sh but after that Onlyoffice stopped working. We have two cases at the moment so we think it is something wrong with the update.
We tried also to remove and reinstall by script docker onlyoffice image but with no result.
In the admin menu we can change onlyoffice setting so it looks like that it is all fine but when we try to edit a file the docker can't be contacted (check image).
Please looking for support
Thanks

### Expected Result

Onlyoffice should work again

### Actual Result

Onlyoffice docker not working

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/71324914/215999505-31eded19-a94c-47d0-ad8b-989dc8f1bb9b.png)

### Build Version

25.0.3

### Environment

By downloading the VM

### Environment Details

hanssonit image, when we install onlyoffice docker all the test are passed (domain, cpu, ram)

**Comment by fabnext77** [comment]
Hello, I also just tried to revert the snapshot before the update and just reinstall onlyoffice docker: I get the same problem. So I think that the problem is in the Onlyoffice docker, if you update the docker you have the problem no matter the Nextcloud version you use.
regards

**Comment by fabnext77** [comment]
Hello, to leave feedback: the problem is with onlyoffice docker 7.3, I rolled back to 7.2 and it works.
I hope that they will fix soon.
For enoch85 is there some how to skip the upgrade of onlyoffice docker if you launch NC upgrade script?
thanks
Regards

**Comment by szaimen** [comment]
See https://forum.onlyoffice.com/t/onlyoffice-7-3-websocket-path-changed/3767/5

**Comment by enoch85** [comment]
It's now fixed, we won't upgrade OnlyOfficie automatically. https://github.com/nextcloud/vm/commit/2025411b1f079d6263455bfa7a2d2633b5d15e6e

**Comment by enoch85** [comment]
It's now fixed again. We will upgrade Onlyoffice, and you need to either reinstall or fix the config manually: https://github.com/nextcloud/vm/pull/2457
