### ISSUE TITLE
Error Message on PuTTY When Logging In

### ISSUE THREAD

**Issue by mygeek911** [nextcloud/vm#2440]
### Steps To Reproduce

1. Log in to server with PuTTY
2. View error message

### Expected Result

No error messages

### Actual Result

bash: /var/scripts/instruction.sh: No such file or directory

### Build Version

25.0.3.2

### Environment

By using the scripts

### Environment Details

- Ubuntu 22.04.1 LTS
- Intel 4 cores, 4072GB RAM

**Comment by enoch85** [comment]
This is most likley due to that it was setup with another user than `ncadmin`..? We fixed that in later versions of the VM.

You can remove the message by commenting out the line in `~/.bash_profile`.

**Comment by mygeek911** [comment]
I did setup with ncadmin. I started with another account, but it had me create a new account (which I did name ncadmin) and log in again to continue with the ncadmin account. Regardless, I've commented out the line. Thanks!

**Comment by enoch85** [comment]
You're expected to login with the account that you created during setup. You could also have run with your original user, and not create an account. Either way, I'm glad it's solved. :)
