### ISSUE TITLE
custom ssl cert

### ISSUE THREAD

**Issue by yofizane** [nextcloud/vm#2444]
hello,my ISP blocked 80&443.is there a way to add a custom ssl cert to activate the tls,I have ordered a wildcard ssl cert

**Comment by enoch85** [comment]
You can run the deSEC option in the menu script and set your own port - for free! :)

**Comment by yofizane** [comment]
is deSEC in the  /var/scripts/menu.sh?it seems a ddns service,I didnt find a place to set port

**Comment by enoch85** [comment]
Just start the script, it will ask you to set a custom port for TLS/SSL during setup.
