### ISSUE TITLE
find_log function in update script is very slow

### ISSUE THREAD

**Issue by jshore1296** [nextcloud/vm#2445]
### Steps To Reproduce

When I run the update script on my server, it sometimes takes over an hour to execute find_log.  I added a `set -x` to debug and saw that it was spending all of the time on the `find /` command.  

My guess is that this command is traversing into my data disk, which is a regular old hard disk with hundreds of thousands of files on it :(.  

### Expected Result

Perhaps check the "expected" location directly first?  And then, if the log is not found there, do a find to search elsewhere.

### Actual Result

Full disk search on every run of update.sh

### Build Version

N/A - not specific to a nextcloud version

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Yeah, it could be improved, agreed. Will make it and if statement, or even remove it completely. Everyone should have the new location by now.

**Comment by jshore1296** [comment]
Thanks for the quick fix 😄
