### ISSUE TITLE
Updating things it's downgrading and Service Unavailable

### ISSUE THREAD

**Issue by jon-bit** [nextcloud/vm#2460]
### Steps To Reproduce

Long story short I've been working on another problem for over 1 week. I can not list everything that has happened just from pure memory. I just tried to upgrade to beta hopeing it will be the fix. Just run the update script with beta, and that's all I can give detail about for the update problem. Otherwise I cant get the webserver to work.

### Expected Result

it allows me to update to beta

### Actual Result

I get this reponce
```
/dev/fd/63: line 1475: [: : integer expression expected
/dev/fd/63: line 1513: [: : integer expression expected
An unhandled exception has been thrown:
OCP\HintException: [0]: Downgrading is not supported and is likely to cause unpredictable issues (from 26.0.0.12 to 26.0.0.10) ()
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ -V failed
```

### Screenshots, Videos, or Pastebins

Website says
```
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

### Additional Context

I see the screenshot when I try to go to my nextcloud server. I tried to update and it resulted with that. I tred updating to beta and got the output.

### Build Version

26.0.0

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04

**Comment by jon-bit** [comment]
I guess some history can be found here:
https://help.nextcloud.com/t/php-update-error/158545/13

**Comment by enoch85** [comment]
Hi, sorry for late response. How did everything go?

Any new findings?

**Comment by enoch85** [comment]
Please try the latest release and reopen if the issue still exist.
