### ISSUE TITLE
Fulltextsearch 

### ISSUE THREAD

**Issue by tierschat** [nextcloud/vm#2472]
### Steps To Reproduce

Command 
sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:configure {"search_platform":"OCA\\FullTextSearch_Elasticsearch\\Platform\\ElasticSearchPlatform"} failed

### Expected Result

FulltextSearch installation

### Actual Result

...
Installing files_fulltextsearch...
App "Full text search - Files" cannot be installed because it is not compatible with this version of the server.

  There are no commands defined in the "fulltextsearch" namespace.

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ fulltextsearch:configure {"search_platform":"OCA\\FullTextSearch_Elasticsearch\\Platform\\ElasticSearchPlatform"} failed
Posting notification to users that are admins, this might take a while...
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to: ncadmin

...

### Build Version

26

### Environment

By using the scripts

### Environment Details

Ubuntu 2204LTS
HyperV
Arista Firewall
Complete config via Script

**Comment by enoch85** [comment]
Thanks, it's not s bug, but thanks for reporting! 👍🏼

The reason it can't install is due to the app is not compatible with NC 26.0.0 yet. Just try again in a few days/weeks.
