### ISSUE TITLE
Disk running full after Upgrade to Version 26

### ISSUE THREAD

**Issue by 19newbie87** [nextcloud/vm#2474]
### Steps To Reproduce

1. Please find attached the following Screenshot
2. 10 hours ago I deleted 2 GB ans installed Gnome to take the following Screenshots
3. It was not possible to find the Files which take so much space
4. Now, the Disk ist full. 
5. Please check the other Screenshots.

![speicherplatzproblem in einem Bild](https://user-images.githubusercontent.com/97949340/232498394-3cc061a8-dfb8-4d5d-91b6-933d4c500b7d.PNG)

6. May there is a Problem with the files at **/proc** because the space of the disk is max. 40 GB (+  1TB NCDATA). But the Foldersize is ca. 1,2 TB? 

![folder proc](https://user-images.githubusercontent.com/97949340/232500500-fa71ec98-beaf-451f-89d2-6ce61e3eb764.PNG)

### Expected Result

Before the Upgrade to Version 26, there was no issue with the disk usage.

### Actual Result

The disk running full. 

### Screenshots, Videos, or Pastebins

![ncdata](https://user-images.githubusercontent.com/97949340/232500956-631d7cca-fe09-4bd7-8336-0ff5b9c2130e.PNG)

![size](https://user-images.githubusercontent.com/97949340/232500983-a03fe05e-8b4a-440d-8e4e-1fd475e605b6.PNG)

![now](https://user-images.githubusercontent.com/97949340/232501374-84e2adb7-09f0-4508-84b7-663a96f1a85f.PNG)

![mnt](https://user-images.githubusercontent.com/97949340/232501564-98263efa-b47a-4494-b889-9705bae2282a.PNG)

### Additional Context

I hope you can help me.

### Build Version

26.0.0.11

### Environment

By downloading the VM

### Environment Details

![system](https://user-images.githubusercontent.com/97949340/232502938-0482eccf-4a23-4b9e-9e27-855031fff3d4.PNG)

**Comment by enoch85** [comment]
You can easily check which file is the largest on your system by running this: `sudo du -ah / 2>/dev/null | sort -n -r | head -n 20`

Please post the output here.

**Comment by 19newbie87** [comment]
HI, I got the following error:
![image](https://user-images.githubusercontent.com/97949340/232708846-ee70d46f-5150-4404-8c19-a7886718619b.png)

**Comment by 19newbie87** [comment]
The Problem is, that i the used space that i can see is ca. 13 GB, i cannot find other files: Please look at the picture from yesterday (before the space was full): 

![speicherplatzproblem in einem Bild](https://user-images.githubusercontent.com/97949340/232710069-4467dcb7-8dea-49d7-be7b-fa57bad66e88.PNG)

**Comment by 19newbie87** [comment]
![image](https://user-images.githubusercontent.com/97949340/232712613-04620742-dbd3-45f6-b18a-4a31bad7cbf7.png)

That partition was running full of space.

**Comment by 19newbie87** [comment]
df -h result in:

![image](https://user-images.githubusercontent.com/97949340/232713753-8c4d148d-26a9-430f-8552-e7b506b28b55.png)

**Comment by austriac1214** [comment]
Same here but with actually latest nextcloud-vm (40GB_Nextcloud-VM_www.hanssonit.se.ova from 2023-04-08) with Ubuntu 22.04. After some days of operation the primary disk is full. Reverted to a snapshot immediately after installation and basic configuration, after 3 days the primary disk is full again.
Suggested command to find the largest file not possible because there is no available free space.

**Comment by enoch85** [comment]
Sorry, can't reproduce this, and made several different installations the last days. Please test using VMware, just to rule out that it's not something one your end that's failing.

**Comment by 19newbie87** [comment]
Thanks für your Support. Iam not Sure how can i run Tests with VMware? 

I use virtualbox for the guest system. 
I made the following changes at the System after installing your nextcloud v23: 

1. I gave ncadmin the rigths to Read the ncdata folder
2. I add a cronjob to copy the ncdata folder to extern  drive (I Use a virtualbox shared folder wich is connected with a program to encrypt und backup the files at the Windows 10 host).
3. I installed gnome as minimal Version
4. In January I received an upgrade to version 25 from a hansson it employee
5. I made an php upgrade to version Php8.1 
6. Up to here there was no error
7. I made an upgrade 

Is it possible that one of my changes could have caused the error?

**Comment by enoch85** [comment]
Point 5, did you do the upgrade yourself?

**Comment by enoch85** [comment]
Basically, it's hard to tell which points that could have caused the error, but point 1 and 2 feels a bit off. Absolutely 5 if you made the upgrade yourself.

**Comment by 19newbie87** [comment]
Hi, yes i made the upgrade by myself (_'like'_ that way: [.](https://schroederdennis.de/tutorial-howto/nextcloud-php-7-x-update-zu-php-8-0-schritt-fuer-schritt/) After the update i compared the standard config file with nextcloud.conf and adjusted them accordingly (only the custom section), after that I saved them as "nextcloud.conf". In the next I cheked the server status at the admin section of the webinterface of nextcloud and a few days later I started the nextcloud updater .

**Comment by enoch85** [comment]
OK, and you have no PHP errors?

**Comment by 19newbie87** [comment]
Hi, I got no errors BUT iam a greenhorn, maybe there are special logfiles?  For me the Server worked fine. Further, at webmin and the nextcloud (gui) at the admin section were no errors listed.

**Comment by enoch85** [comment]
Maybe it's better if you get support from our shop to upgrade your PHP correctly, then we can have a look at the other issues as well if time allows?
