### ISSUE TITLE
curl_to_dir  failed

### ISSUE THREAD

**Issue by zhoulei135** [nextcloud/vm#2475]
### Steps To Reproduce

run "sudo bash /var/scripts/nextcloud-startup-script.sh"

### Expected Result

Script runs normally

### Actual Result

log:  Script failed to download. Please run: 'sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/index.sh|php|py' and try again.

github file does not exist “/static/index.sh”

### Build Version

26.0.0

### Environment

By downloading the VM

### Environment Details

docs: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm
2.2 VMware

**Comment by enoch85** [comment]
Thanks for reporting!

It's referring to this file: https://github.com/nextcloud/vm/blob/master/static/index.php - which does exist. 

So please try again and see if it gives you any different output.

**Comment by enoch85** [comment]
Just tested, and cannot reproduce this. Have you tested again @zhoulei135?

**Comment by zhoulei135** [comment]
Sorry, I checked the script and environment carefully. Because of dns pollution, the "raw.githubusercontent.com" A record is 0.0.0.0, and then I modified /etc/hosts to specify the correct IP, and found that the access was probabilistically blocked. This is probably the tragedy of mainland China, thank you for your reply

**Comment by zhoulei135** [comment]
> Thanks for reporting!
> 
> It's referring to this file: https://github.com/nextcloud/vm/blob/master/static/index.php - which does exist.
> 
> So please try again and see if it gives you any different output.

**Comment by enoch85** [comment]
Thanks for confirming!
