### ISSUE TITLE
Wrong address in Welcome Mail

### ISSUE THREAD

**Issue by ferengie** [nextcloud/vm#2478]
### Steps To Reproduce

I am not 100% sure, if it is really a bug.

I had the issue like: 
[Wrong adress in Welcome Mail - internal IP instead of external Domain](https://help.nextcloud.com/t/wrong-adress-in-welcome-mail-internal-ip-instead-of-external-domain/111891)
but I was not able to solve it, because i could not find a config.php with a proxy-section.

root@box:~# find / -name "config.php"
/mnt/NCBACKUP/config/config.php
/mnt/ncdata/updater-oc0bzeaff2it/backups/nextcloud-25.0.2.3-1680684065/config/config.php
/var/www/nextcloud/config/config.php

I added into /var/www/nextcloud/config/config.php - was the most logical config.php but had no effect.

### Expected Result

Want to get a correct invitation mail wit FQDN not only in text but also in link to the server

### Actual Result

Wrong link in invitation mail - local IP addresses instead of external address 

### Build Version

25

### Environment

By downloading the VM

**Comment by enoch85** [comment]
This seems to me like a proxy issue. It's not an issue right out the box. 

Dependning on which proxy you use, you need to configure the backend webserver differently. For a 100% proper solution, share the TLS cert in between so that all traffic is encrypted. A bit overkill maybe, but that's how I do it personally.

**Comment by ferengie** [comment]
yes, it was a proxy-setting topic, just found the solution in here:
[Configuring Nextcloud](https://cengelsen.no/en/blogg/nextcloud-instruks/)

Add these lines to the **bottom of the file**:
'overwritehost' => 'example.domain.com',
'overwriteprotocol' => 'https',
'overwritewebroot' => '/',_

If these lines are on the bottom it works, if thes are after:
**'overwrite.cli.url' => 'https://example.domain.com',**
it does not work

Thank you for helping
