### ISSUE TITLE
AH01797: client denied by server configuration 

### ISSUE THREAD

**Issue by parided** [nextcloud/vm#2480]
### Steps To Reproduce

4. Click on '...'

### Expected Result

No idea, I just checked the apache log after restore db as reported in restore section of nextcloud manual. While restoring the db I didn't get any errors. Everything seems to be working, but getting these errors completely fills the apache2 log. in addition to this, nextcloud shows me other errors. I report the screenshot. I don't use letsencrypt even if it's installed because i have my own certificates. I haven't installed fail2ban, just the smooth version of the vm without any additional packages. 
![screenshot-apache](https://user-images.githubusercontent.com/63407434/235108717-3907bb9f-de9f-4b37-871d-ec8a242f8ac2.png)
![screenshot-nextcloud](https://user-images.githubusercontent.com/63407434/235108757-3e7d1096-80e6-40ad-8837-62f7af87b7b7.png)

### Actual Result

[Fri Apr 28 10:52:49.448151 2023] [access_compat:error] [pid 113949:tid 140482642425408] [client 10.75.150.1:39016] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:52:49.448580 2023] [access_compat:error] [pid 113949:tid 140482642425408] [client 10.75.150.1:39016] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:52:49.448733 2023] [access_compat:error] [pid 113949:tid 140483984971328] [client 10.75.150.1:39004] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:52:49.449126 2023] [access_compat:error] [pid 113949:tid 140483984971328] [client 10.75.150.1:39004] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:52:50.507705 2023] [access_compat:error] [pid 113949:tid 140484085765696] [client 10.75.150.1:61156] AH01797: client denied by server configuration: /var/www/nextcloud/apps/logreader/poll
[Fri Apr 28 10:52:50.507857 2023] [access_compat:error] [pid 113949:tid 140484085765696] [client 10.75.150.1:61156] AH01797: client denied by server configuration: /var/www/nextcloud/index.php
[Fri Apr 28 10:52:53.738660 2023] [access_compat:error] [pid 113949:tid 140483565164096] [client 10.75.150.1:61515] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:52:53.739029 2023] [access_compat:error] [pid 113949:tid 140483565164096] [client 10.75.150.1:61515] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:52:54.565106 2023] [access_compat:error] [pid 113950:tid 140483716167232] [client 87.10.16.242:55272] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:52:54.565534 2023] [access_compat:error] [pid 113950:tid 140483716167232] [client 87.10.16.242:55272] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:52:58.804083 2023] [access_compat:error] [pid 113949:tid 140483581949504] [client 151.93.114.76:59429] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Fri Apr 28 10:52:58.804166 2023] [access_compat:error] [pid 113950:tid 140483699381824] [client 151.93.114.76:59428] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Fri Apr 28 10:52:58.804569 2023] [access_compat:error] [pid 113949:tid 140483581949504] [client 151.93.114.76:59429] AH01797: client denied by server configuration: /var/www/nextcloud/apps/user_status/api
[Fri Apr 28 10:52:58.804596 2023] [access_compat:error] [pid 113950:tid 140483699381824] [client 151.93.114.76:59428] AH01797: client denied by server configuration: /var/www/nextcloud/apps/notifications/api
[Fri Apr 28 10:52:58.866605 2023] [access_compat:error] [pid 113949:tid 140482650818112] [client 151.93.114.76:59430] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:52:58.866878 2023] [access_compat:error] [pid 113949:tid 140482650818112] [client 151.93.114.76:59430] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:53:00.247103 2023] [access_compat:error] [pid 113949:tid 140484060587584] [client 10.75.150.1:61156] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Fri Apr 28 10:53:00.247548 2023] [access_compat:error] [pid 113949:tid 140484060587584] [client 10.75.150.1:61156] AH01797: client denied by server configuration: /var/www/nextcloud/apps/notifications/api
[Fri Apr 28 10:53:01.339889 2023] [access_compat:error] [pid 113950:tid 140482709534272] [client 81.56.19.59:8822] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:53:01.340336 2023] [access_compat:error] [pid 113950:tid 140482709534272] [client 81.56.19.59:8822] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:53:03.969317 2023] [access_compat:error] [pid 113950:tid 140483741345344] [client 10.75.150.1:64196] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Fri Apr 28 10:53:03.969707 2023] [access_compat:error] [pid 113950:tid 140483741345344] [client 10.75.150.1:64196] AH01797: client denied by server configuration: /var/www/nextcloud/apps/user_status/api
[Fri Apr 28 10:53:03.972026 2023] [access_compat:error] [pid 113950:tid 140483540018752] [client 10.75.150.1:64197] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Fri Apr 28 10:53:03.972413 2023] [access_compat:error] [pid 113950:tid 140483540018752] [client 10.75.150.1:64197] AH01797: client denied by server configuration: /var/www/nextcloud/apps/notifications/api
[Fri Apr 28 10:53:03.972768 2023] [access_compat:error] [pid 113950:tid 140483959768640] [client 10.75.150.1:64198] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:53:03.973190 2023] [access_compat:error] [pid 113950:tid 140483959768640] [client 10.75.150.1:64198] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:53:04.608663 2023] [access_compat:error] [pid 113950:tid 140483531626048] [client 87.21.251.214:51393] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:53:04.609113 2023] [access_compat:error] [pid 113950:tid 140483531626048] [client 87.21.251.214:51393] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:53:04.609187 2023] [access_compat:error] [pid 113950:tid 140483732952640] [client 87.21.251.214:51394] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Fri Apr 28 10:53:04.609630 2023] [access_compat:error] [pid 113950:tid 140483732952640] [client 87.21.251.214:51394] AH01797: client denied by server configuration: /var/www/nextcloud/core/navigation
[Fri Apr 28 10:53:05.392274 2023] [access_compat:error] [pid 113949:tid 140483607127616] [client 10.75.150.1:53132] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:53:05.392303 2023] [access_compat:error] [pid 113950:tid 140483993372224] [client 10.75.150.1:53134] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
[Fri Apr 28 10:53:05.392533 2023] [access_compat:error] [pid 113950:tid 140482717926976] [client 10.75.150.1:53133] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Fri Apr 28 10:53:05.392556 2023] [access_compat:error] [pid 113949:tid 140483607127616] [client 10.75.150.1:53132] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:53:05.392563 2023] [access_compat:error] [pid 113950:tid 140483993372224] [client 10.75.150.1:53134] AH01797: client denied by server configuration: /var/www/nextcloud/dav
[Fri Apr 28 10:53:05.392608 2023] [access_compat:error] [pid 113950:tid 140483523233344] [client 10.75.150.1:53135] AH01797: client denied by server configuration: /var/www/nextcloud/ocs/v2.php
[Fri Apr 28 10:53:05.393003 2023] [access_compat:error] [pid 113950:tid 140482717926976] [client 10.75.150.1:53133] AH01797: client denied by server configuration: /var/www/nextcloud/apps/notifications/api
[Fri Apr 28 10:53:05.393129 2023] [access_compat:error] [pid 113950:tid 140483523233344] [client 10.75.150.1:53135] AH01797: client denied by server configuration: /var/www/nextcloud/apps/user_status/api
[Fri Apr 28 10:53:06.212225 2023] [access_compat:error] [pid 113950:tid 140482743105088] [client 10.75.150.1:61215] AH01797: client denied by server configuration: /var/www/nextcloud/remote.php
~
~

### Build Version

26.0

### Environment

By downloading the VM

**Comment by github-tomster** [comment]
https://github.com/nextcloud/vm/issues/2249

https://help.nextcloud.com/t/ah01797-client-denied-by-server-configuration-var-www-nextcloud-remote-php/147684

https://help.nextcloud.com/t/what-are-these-client-denied-by-server-configuration-errors/150561

**Comment by github-tomster** [comment]
@enoch85 
nice to see all these commits to the scripts 👍🏻 

any tips for the running instances with these errors 🤷🏻 
run `nextcloud_install_production.sh` again 🤔

**Comment by enoch85** [comment]
Re run the Activate TLS script again from the menu.sh in /var/scripts.

**Comment by github-tomster** [comment]
in my case the instance is reverse-proxied
so `activate TLS` is not appropriate i guess 🤷🏻‍♂️

**Comment by enoch85** [comment]
If you have a proxy in front you need to negotiate TLS on the Proxy, then use any of the tempalte configurations to finish the rest. You can find them in the default Apache2 conf directories.

**Comment by github-tomster** [comment]
@enoch85 
sorry i did not made myself clear:
on my setup the tls is managed on the rproxy and working.
afaik 'activate tls' is to manage the letsencrypt _inside_ the nextcloud-vm.
so i assumed i can not use the 'activate TLS' on my setup to correct the malformed apache rules 🤷🏻‍♂️ 
now i will search for and read-up these 'templates' mentioned by you and try to manually correct the error 🐹

**Comment by enoch85** [comment]
> afaik 'activate tls' is to manage the letsencrypt inside the nextcloud-vm.

Correct, but it will also give you a correct configuration, except from the TLS certificates. S run activate TLS, then change the certs to snakeoil instead since it doesn't need to be valid certs between the proxy and the nextcloud backend server.
