### ISSUE TITLE
Option to keep .bash_history

### ISSUE THREAD

**Issue by github-tomster** [nextcloud/vm#2481]
**Is your feature request related to a problem? Please describe.**
usually one can use the bash history unfortunately not on this VM 🙇🏻 
`/var/scripts/history.sh` prevents that 🗑️ 

**Describe the solution you'd like**
is there a non obvious reason for `truncate -s0 "$HOME/.bash_history"
` ❓ 

**Describe alternatives you've considered**
can one disable `history.sh` without breaking the VM ❓ 

**Additional context**
i searched the repo but i am not sure if this ist the first issue/question regarding the missing history 🤷🏻

**Comment by enoch85** [comment]
> can one disable history.sh without breaking the VM ❓

Yes, just comment it out in the `.bash_profile`

The idea behind it was to remove commands which the clumsy user had been making containing passwords and stuff - see it as a security mesure.

**Comment by github-tomster** [comment]
@enoch85 
thank you for confirming 👍🏻 
maybe a hint/comment like:
```
bash /var/scripts/nextcloud.sh
# comment out following line to keep bash_history at own risk!
bash /var/scripts/history.sh
```
could prevent such noise 🤷🏻

**Comment by enoch85** [comment]
Uninitiated user: Didn't even know history was saved per default
Power user: Ask the same question as you, finds the answer and fixes it. ;)

**Comment by github-tomster** [comment]
@enoch85 
was the answer already out there 🤔 
i mean the 'will it break the nextcloudvm environment' question ❓

**Comment by pjrobertson** [comment]
I just came across this 'issue' of .bash_history being cleared and was confused why. Some digging led me to the `history.sh` file and then here. I've created a PR to at least add this comment in the history.sh file see: https://github.com/nextcloud/vm/pull/2604
