### ISSUE TITLE
 vm/nextcloud_install_production.sh error

### ISSUE THREAD

**Issue by githubDiversity** [nextcloud/vm#2488]
### Steps To Reproduce

Host:
pve-manager/7.4-3/9002ab8a (running kernel: 5.15.107-1-pve)

VM OS:
Ubuntu 22.04.2 LTS

When running
https://github.com/nextcloud/vm/nextcloud_install_production.sh

as user ncadmin using sudo bash nextcloud_install_production.sh

I get an error message

### Expected Result

no error message

### Actual Result

Installing Nextcloud...
Nextcloud was successfully installed

Nextcloud version:
Your data directory is readable by other users.
Please change the permissions to 0770 so that the directory cannot be listed by other users.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /var/www/nextcloud/lib/private/Console/Application.php:167
Stack trace:
#0 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#1 /var/www/nextcloud/occ(11): require_once('...')
#2 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ status failed

### Build Version

not stated / not aware

### Environment

By using the scripts

**Comment by githubDiversity** [comment]
/mnt/ncdata is configured, via, /etc/fstab, as a cifs mount to an smb share on the host.
this share is on a ZFS filesystem accessible by the root user of the host and the smb user specific to this VM.

**Comment by enoch85** [comment]
It's most probably a configuration issue.

Use one disk setup during installation, then mount the SMB share with out SMB mounting script (found in menu.sh).

**Comment by enoch85** [comment]
@githubDiversity Did my comment solve your issue?

**Comment by githubDiversity** [comment]
My apologies. I had hoped being able to focus on nextcloud sooner.

I'll revisit the issue in a week or 2 and make sure to keep you updated.

**Comment by githubDiversity** [comment]
I have gotten around to installing nextcloud using the script.

I noticed that the SMB mount script is used to create an external data location.
My use case is that I want the whole of the data folder to be moved to an SMB share.

Is this still possible?

I will investigate a bit later. Currently it seems that I can't log in with my ncadmin user or the user I created for the web interface. I am not sure where to look in the logs to determine what is going wrong.

**Comment by githubDiversity** [comment]
Ok it was a keyboard mapping issue unrelated to the script/VM that made me not being able to login. Now I have solved that.

when I run menu.sh I no longer see the option to configure an SMB share. Should it still be there?

**Comment by enoch85** [comment]
> when I run menu.sh I no longer see the option to configure an SMB share. Should it still be there 

It's in "Additional Apps". 

And yes, it's possible to use the SMB script to create an SMB share then change in config.php for Nextcloud.

**Comment by githubDiversity** [comment]
Thank you, All seems well.

great script and VM!!
