### ISSUE TITLE
webgui no longer works

### ISSUE THREAD

**Issue by Alethio36** [nextcloud/vm#2489]
### Steps To Reproduce

im not sure what caused it,  but last week i went to the webgui and it shows a white page with the text

Index of /
Name	Last modified	Size	Description

and nothing else

### Expected Result

the normal webgui

### Actual Result

see above

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/49285292/236819940-14a6087d-797f-417e-bc90-6c39857a10e2.png)

### Additional Context

apache2 logs look clean afaict, as well as nextcloud logs and any other logs i could get my hands on

### Build Version

latest as of today i believe

### Environment

By using the scripts

## Server configuration detail

**Operating system:** Linux 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64

**Webserver:** Unknown (cli)

**Database:** pgsql PostgreSQL 14.7 (Ubuntu 14.7-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit

**PHP version:** 8.1.2-1ubuntu2.11

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache

**Nextcloud version:** 26.0.1 - 26.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

[]
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.18.0
 - admin_audit: 1.16.0
 - calendar: 4.3.3
 - checksum: 1.2.1
 - circles: 26.0.0
 - cloud_federation_api: 1.9.0
 - collectives: 2.4.0
 - comments: 1.16.0
 - contacts: 5.2.0
 - contactsinteraction: 1.7.0
 - dashboard: 7.6.0
 - dav: 1.25.0
 - deck: 1.9.0
 - federatedfilesharing: 1.16.0
 - federation: 1.16.0
 - files: 1.21.1
 - files_external: 1.18.0
 - files_pdfviewer: 2.7.0
 - files_rightclick: 1.5.0
 - files_sharing: 1.18.0
 - files_trashbin: 1.16.0
 - files_versions: 1.19.1
 - firstrunwizard: 2.15.0
 - groupfolders: 14.0.2
 - integration_dropbox: 1.0.6
 - integration_openai: 1.0.5
 - logreader: 2.11.0
 - lookup_server_connector: 1.14.0
 - mail: 3.1.1
 - nextcloud_announcements: 1.15.0
 - notifications: 2.14.0
 - oauth2: 1.14.0
 - oidc: 0.4.9
 - password_policy: 1.16.0
 - photos: 2.2.0
 - privacy: 1.10.0
 - provisioning_api: 1.16.0
 - recommendations: 1.5.0
 - related_resources: 1.1.0-alpha1
 - secrets: 1.4.2
 - serverinfo: 1.16.0
 - settings: 1.8.0
 - sharebymail: 1.16.0
 - support: 1.9.0
 - survey_client: 1.14.0
 - systemtags: 1.16.0
 - text: 3.7.2
 - theming: 2.1.1
 - twofactor_backupcodes: 1.15.0
 - updatenotification: 1.16.0
 - user_ldap: 1.16.0
 - user_status: 1.6.0
 - viewer: 1.10.0
 - weather_status: 1.6.0
 - workflowengine: 2.8.0
Disabled:
 - bruteforcesettings
 - encryption
 - extract
 - suspicious_login
 - twofactor_totp

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "10.11.21.70",
        "hostname.domainname.com",
        "hostname.domainname.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "26.0.1.1",
    "overwrite.cli.url": "https:\/\/hostname.domainname.com\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "upgrade.disable-web": true,
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": "2",
    "log.condition": {
        "apps": [
            "admin_audit"
        ]
    },
    "mail_smtpmode": "smtp",
    "remember_login_cookie_lifetime": "1800",
    "log_rotate_size": "10485760",
    "trashbin_retention_obligation": "auto, 60",
    "versions_retention_obligation": "auto, 180",
    "activity_expire_days": "120",
    "simpleSignUpLink.shown": false,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0.5,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "preview_concurrency_new": "2",
    "preview_concurrency_all": "4",
    "enabledPreviewProviders": [
        "OC\\Preview\\Imaginary",
        "OC\\Preview\\Image",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\Movie"
    ],
    "preview_imaginary_url": "http:\/\/127.0.0.1:9000",
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "preview_max_memory": "256",
    "default_phone_region": "us",
    "logtimezone": "Australia\/Adelaide",
    "htaccess.RewriteBase": "\/",
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "overwriteprotocol": "https",
    "data-fingerprint": "06698e642e110a9c0c5b7a761e1d5e13"
}
```
</details>

**Cron Configuration:** Array
(
    [backgroundjobs_mode] => cron
    [lastcron] => 1683546902
)

**External storages:** yes

<details><summary>External storage configuration</summary>

```
No mounts configured
```
</details>

**Encryption:** no

**User-backends:**
 * OC\User\Database
 * OCA\User_LDAP\User_Proxy

<details><summary>LDAP configuration</summary>
left out for privacy reasons

**Comment by Alethio36** [comment]
i did forget to mention, but let me know if i need to do more, or if this bug report is incorrectly filled out or anything.
thank yall in advance, i have been pulling my hair last few days trying to figure out whats wrong.

restarting the server doesnt help, along with restarting any services.

**Comment by enoch85** [comment]
Can you please post the output of:

`sudo ls -l /etc/apache2/sites-enabled`

**Comment by Alethio36** [comment]
root@nextcloud:/var/www/nextcloud# sudo ls -l /etc/apache2/sites-enabled
total 0
lrwxrwxrwx 1 root root 35 Apr  6 21:44 default-ssl.conf -> ../sites-available/default-ssl.conf
lrwxrwxrwx 1 root root 57 Apr  6 20:21 nextcloud_http_domain_self_signed.conf -> ../sites-available/nextcloud_http_domain_self_signed.conf
lrwxrwxrwx 1 root root 56 Apr  6 20:21 nextcloud_tls_domain_self_signed.conf -> ../sites-available/nextcloud_tls_domain_self_signed.conf
root@nextcloud:/var/www/nextcloud#

**Comment by enoch85** [comment]
You can book 30 minutes support to [get it sorted](https://shop.hanssonit.se/product/premium-support-per-30-minutes/)

If you want to try on your own, check your Apache config. Make a config from the existing templates and then enable that, and only that one.

**Comment by Alethio36** [comment]
that sorta did the trick. when connecting over port 80 solved it. ill have to take a deeper dive into what happened. 

i also think i got sites enabled and sites available mixed up for future readers coming here. 

ill post back if i get a definite answer on what went wrong, or hopefully, why it went wrong

**Comment by enoch85** [comment]
> ill post back if i get a definite answer on what went wrong, or hopefully, why it went wrong

Sounds good! :)

**Comment by Alethio36** [comment]
so after looking over everything, and given my lack of experience in apache2 as well, i cant find a specific catalyst that led to this being a issue. my best guess at this moment is the correct conf file got moved from sites enabled to sites available. maybe a nextcloud update/script borked something maybe (not to point the blame anywhere, weird things happens, and im still kinda green with all this stuff)? unfortunately im at the bottom of the rabbit hole i cant go do personally. if someone wants to help diagnose this issue, im happy to share what i got, but im tapped out.

thank you for your help, i appreciate your time
