### ISSUE TITLE
WebDAV connection with Nextcloud VM

### ISSUE THREAD

**Issue by Kaelber** [nextcloud/vm#2491]
I use a Nextcloud VM in a Synology VMM and it runs well on a NVMe Volume. from another VM which is Grommunio Groupware I want to connect over the Files module via WebDAV to the NC-VM, but the connection doesnt work as expected. I know the adress on the left below side from the NC files menu, but it seems it not valid

What are the settings from your point of view? Is it maybe a TLS problem, if I use Port 443? Can I use also Port 80?

**Comment by enoch85** [comment]
Setup a proper TLS connection with our "Activate TLS" script which can be found in the menu script: sudo bash /var/scripts/menu.sh --> server -- activate tls.

When that's done, then try again by copying the URL from the Files settings in your Nextcloud GUI.

**Comment by Kaelber** [comment]
Hello Daniel,
 
 
this point is currently activated


[cid]
 
 
mit freundlichen Grüßen
Andreas Kälber

 

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 




    --------------------Ursprüngliche Nachricht--------------------
    Von: Daniel ***@***.***>
    Gesendet: Freitag 12. Mai 2023 15:33
    An: nextcloud/vm ***@***.***>
    CC: Andreas Kaelber ***@***.***>; Author
    ***@***.***>
    Betreff: Re: [nextcloud/vm] WebDAV connection with Nextcloud VM (Issue #
    2491)

   
    Setup a proper TLS connection with our "Activate TLS" script which can be
    found in the menu script: sudo bash /var/scripts/menu.sh --> server --
    activate tls.

    When that's done, then try again by copying the URL from the Files settings
    in your Nextcloud GUI.

    —
    Reply to this email directly, view it on GitHub, or unsubscribe.
    You are receiving this because you authored the thread.*Message ID: 
    ***@***.***>

**Comment by Kaelber** [comment]
In which way I can verify, if WebDAV is well installed? Any CLI syntax?
