### ISSUE TITLE
Update to v26 issues

### ISSUE THREAD

**Issue by IdefixRC** [nextcloud/vm#2492]
### Steps To Reproduce

Current version 25.0.6

1. SSH into NC VM
2. sudo bash /var/scripts/menu.sh > update
3. Update runs -> nextcloud is already on the latest version - latest version 25.0.6 Current Version 25.0.06
4. Server restarts

5. SSH into NC VM
6. sudo bash /var/scripts/update.sh
7. Runs
        Restarting Apache2 and PHP-FPM...
        Getting current PHP-version...
        PHPVER=7.4
        Latest release is: 26.0.1. Current version is: 25.0.6.
9. Terminates with: Your PHP version isn't compatible with the new version of Nextcloud. Please upgrade your PHP stack and try again.

Thanks !

### Expected Result

Upgrade to v26

### Actual Result

Either does not recognize that there is a v26 or terminates with PhP error

### Build Version

25.0.6

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Exactly, that means you need to upgrade your PHP.

**Comment by IdefixRC** [comment]
Yes, I figured that. but why?
7.4 is still supported by v26, no?

**Comment by enoch85** [comment]
Did you check the link I posted? ;)

**Comment by IdefixRC** [comment]
(face palm emoji here)....... Just did. Damn.... Now I need to figure out
how to update the php version :-(
Any practical tips? Believe your VM version is slightly different compared
to the standard install with apache/nginx?

Thanks

**Comment by enoch85** [comment]
It shouldn't differ really much, but if you want to know, check the scripts.

If you need help: https://shop.hanssonit.se/product/upgrade-php-version-including-dependencies/

**Comment by IdefixRC** [comment]
All good. managed to upgrade PHP to 8.1 and Nextcloud after that 👍
