### ISSUE TITLE
No WebDAV connection with Nextcloud VM

### ISSUE THREAD

**Issue by Kaelber** [nextcloud/vm#2493]
### Steps To Reproduce

Using the URL from the Files settings in the Nextcloud GUI to contact via WebDAV

### Expected Result

Connection work and that a window opens to set the credentials

### Actual Result

No connection done, only a window arise that no connection be possible

### Additional Context

In which way I can test, if DAV is properly working?

### Build Version

v26.0.1

### Environment

By downloading the VM

### Environment Details

Nextcloud VM with 4 cores and 4 GB RAM

**Comment by enoch85** [comment]
Thanks for reporting, this is by design. You need to use a client to connect and it doesn't need to be only the Desktop client, it could be any client that supports WebDAV.
