### ISSUE TITLE
Reset productName value to "Nextcloud HanssonIT VM" after update.sh

### ISSUE THREAD

**Issue by vincemd22** [nextcloud/vm#2494]
### Steps To Reproduce

sudo -u www-data php occ config:app:set theming productName --value "Nextcloud"

sudo -u www-data php /var/www/nextcloud/occ status
  - productname: Nextcloud

run update.sh

sudo -u www-data php /var/www/nextcloud/occ status
  - productname: Nextcloud HanssonIT VM

### Expected Result

sudo -u www-data php /var/www/nextcloud/occ status
  - productname: Nextcloud

### Actual Result

sudo -u www-data php /var/www/nextcloud/occ status
  - productname: Nextcloud HanssonIT VM

### Additional Context

Every week when running update.sh the productName value roolback to "Nextcloud HanssonIT VM"

### Build Version

NC 26

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04

**Comment by enoch85** [comment]
It's not a bug, it's a feature. ;)

We do that to brand our VM.
