### ISSUE TITLE
ONLYOFFICE installation [integrated] not correct

### ISSUE THREAD

**Issue by fcorbelli** [nextcloud/vm#2504]
### Steps To Reproduce

(1) fresh install a VM (proxmox) , 4GB VM
(2) use something like nextcloud.mysite.it as DNS name
(4) Get the LE certificate, install failtoban (almost everything else as default)
(5) choose to install OnlyOffice (integrated)

### Expected Result

Working OnlyOffice (integrated)

### Actual Result

(1)
Onlyoffice DOCS path (in GUI) is wrong, missing "/" before "index.php"

https://nextcloud.mysite.itindex.php/apps/documentserver_community/

instead of (maybe)
https://nextcloud.mysite.it/index.php/apps/documentserver_community/

(2) Onlyoffice does not work at all. Seems some kind of misconfiguration (?)
Clicking on "save" (here https://nextcloud.mysite.it/settings/admin/onlyoffice)
```
Errore durante il tentativo di connessione (Client error: `GET https://nextcloud.mysite.it/index.php/apps/documentserver_community/healthcheck` resulted in a `404 Not Found` response
```

Using the "demo version" of ONLYOFFICE docs everything works fine

### Screenshots, Videos, or Pastebins

![onlyoffice1](https://github.com/nextcloud/vm/assets/77727889/00cd18e7-ce9a-42b2-96bf-26ee0e423eb6)
![onlyoffice2](https://github.com/nextcloud/vm/assets/77727889/5b55f650-3b37-40c1-a3ac-07e4be2e52fe)
![onlyoffice3](https://github.com/nextcloud/vm/assets/77727889/6f1bab35-9ea1-4964-843d-bf5c25747443)
![onlyoffice4](https://github.com/nextcloud/vm/assets/77727889/3ff274fc-83e0-46f8-8703-439f1a56607d)

### Additional Context

Tried reinstalling from scratch, same problem  
I have another (older) virtually identical machine (only real difference, it's called archive.mysite.it and not nextcloud.mysite.it) that works fine (on another proxmox server), on a different version Nextcloud Hub 3 (25.0.5)

https://archivio.mysite.it/index.php/apps/documentserver_community/healthcheck
get a "true" (as it should be)

Instead on the brand-new 26.0.2
https://nextcloud.mysite.it/index.php/apps/documentserver_community/healthcheck
get a  "page not found, go back to nextcloud)

### Build Version

Nextcloud Hub 4 (26.0.2)

### Environment

By downloading the VM

### Environment Details

Proxmox-based VM   
vzdump-qemu-999-2023_04_09-21_10_30.vma

**Comment by enoch85** [comment]
Thanks for a detailed report! Will have a look when time allows.

**Comment by fcorbelli** [comment]
My current "workaround" is
(1) update to version 27.0 (via menu.sh)
(2) manully enable the "community document server" that, "magically", appears (disabled, needs to be "turned on"
![workaround](https://github.com/nextcloud/vm/assets/77727889/7c538ec9-4daf-4dfe-b13f-832d2875cdcb)

Maybe just a little "glitch" in version 26
