### ISSUE TITLE
An odd one. Disk Usage doesn't get updated

### ISSUE THREAD

**Issue by GogoFC** [nextcloud/vm#2507]
### Steps To Reproduce

Disk Quota used space doesn't get updated in lower left corner.

### Expected Result

Data Usage should update when data is added. 

### Actual Result

Data Usage doesn't get updated until I use an admin account to actually to to 'Users' page (settings/users) and then everyone's data usage is updated and shows correctly. Otherwise it's stuck at the 37MB which is the initial install's data usage. 

### Build Version

27.0.0

### Environment

By using the scripts

### Environment Details

Ubuntu 22 server VM no ZFS. 
LVM
2CPU
16GB RAM

**Comment by enoch85** [comment]
Hmm, maybe this is a Nextcloud server bug and not related to the VM?

**Comment by GogoFC** [comment]
I have a regular install of Nextcloud where I installed it manually per nc documentation, it works on there.  I have no idea. I did another fresh install later just to check and it was the same thing.

**Comment by enoch85** [comment]
Thanks for reporting back! 👍🏼

**Comment by GogoFC** [comment]
OK I figured it out. It is the APCu local memcache that does that.

**Comment by enoch85** [comment]
Maybe a bug? https://github.com/nextcloud/server/issues/38447
