### ISSUE TITLE
https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh fails caused by wrong databse credentials

### ISSUE THREAD

**Issue by MSchweigart** [nextcloud/vm#2513]
### Steps To Reproduce

1. download https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
2. run nextcloud_install_production.sh
3. ... during installatio process this error occurs:
...
Installing Nextcloud...
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user" in /var/www/nextcloud/lib/private/DB/Connection.php:140
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1531): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /var/www/nextcloud/lib/private/DB/Connection.php(262): Doctrine\DBAL\Connection->executeQuery()
#3 /var/www/nextcloud/lib/private/DB/ConnectionAdapter.php(65): OC\DB\Connection->executeQuery()
#4 /var/www/nextcloud/lib/private/legacy/OC_Util.php(742): OC\DB\ConnectionAdapter->executeQuery()
#5 /var/www/nextcloud/lib/private/legacy/OC_Util.php(718): OC_Util::checkDatabaseVersion()
#6 /var/www/nextcloud/lib/private/Console/Application.php(160): OC_Util::checkServer()
#7 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#8 /var/www/nextcloud/occ(11): require_once('...')
#9 {main}

Next OC\DB\Exceptions\DbalException: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user" in /var/www/nextcloud/lib/private/DB/Exceptions/DbalException.php:71
Stack trace:
#0 /var/www/nextcloud/lib/private/DB/ConnectionAdapter.php(68): OC\DB\Exceptions\DbalException::wrap()
#1 /var/www/nextcloud/lib/private/legacy/OC_Util.php(742): OC\DB\ConnectionAdapter->executeQuery()
#2 /var/www/nextcloud/lib/private/legacy/OC_Util.php(718): OC_Util::checkDatabaseVersion()
#3 /var/www/nextcloud/lib/private/Console/Application.php(160): OC_Util::checkServer()
#4 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#5 /var/www/nextcloud/occ(11): require_once('...')
#6 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=nextcloud_db_user --database-pass=#8a65Iu00@doERJ8pBRUf6RTcv --admin-user=ncadmin --admin-pass=nextcloud failed
Nextcloud is not installed - only a limited number of commands are available

### Expected Result

database connection estabished

### Actual Result

Failed to connect to the database

### Screenshots, Videos, or Pastebins

...
Installing Nextcloud...
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user" in /var/www/nextcloud/lib/private/DB/Connection.php:140
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1531): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1029): Doctrine\DBAL\Connection->getWrappedConnection()
#2 /var/www/nextcloud/lib/private/DB/Connection.php(262): Doctrine\DBAL\Connection->executeQuery()
#3 /var/www/nextcloud/lib/private/DB/ConnectionAdapter.php(65): OC\DB\Connection->executeQuery()
#4 /var/www/nextcloud/lib/private/legacy/OC_Util.php(742): OC\DB\ConnectionAdapter->executeQuery()
#5 /var/www/nextcloud/lib/private/legacy/OC_Util.php(718): OC_Util::checkDatabaseVersion()
#6 /var/www/nextcloud/lib/private/Console/Application.php(160): OC_Util::checkServer()
#7 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#8 /var/www/nextcloud/occ(11): require_once('...')
#9 {main}

Next OC\DB\Exceptions\DbalException: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user" in /var/www/nextcloud/lib/private/DB/Exceptions/DbalException.php:71
Stack trace:
#0 /var/www/nextcloud/lib/private/DB/ConnectionAdapter.php(68): OC\DB\Exceptions\DbalException::wrap()
#1 /var/www/nextcloud/lib/private/legacy/OC_Util.php(742): OC\DB\ConnectionAdapter->executeQuery()
#2 /var/www/nextcloud/lib/private/legacy/OC_Util.php(718): OC_Util::checkDatabaseVersion()
#3 /var/www/nextcloud/lib/private/Console/Application.php(160): OC_Util::checkServer()
#4 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#5 /var/www/nextcloud/occ(11): require_once('...')
#6 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=nextcloud_db_user --database-pass=#8a65Iu00@doERJ8pBRUf6RTcv --admin-user=ncadmin --admin-pass=nextcloud failed
Nextcloud is not installed - only a limited number of commands are available

### Build Version

---

### Environment

By using the scripts

**Comment by enoch85** [comment]
Thanks dor reporting!

Please make another clean installation again, this was probably just temporary, or that you tried to do the installation several times and the DB was already created with another password.

**Comment by enoch85** [comment]
That explains it. We don't support Ubuntu 20.04 for the installation. Will add a warning.

**Comment by MSchweigart** [comment]
There is already a warning and you could not use the install script ubuntu 20.04:
- I got the error under ubuntu 22.04, when it was upgraded from Ubuntu 20.04.
- I got no error with a fresh installation of ubuntu 22.04.

**Comment by enoch85** [comment]
Ok, thanks! Then it works as intended
