### ISSUE TITLE
AntiVirus high CPU usage and skipped files

### ISSUE THREAD

**Issue by thatstheplace** [nextcloud/vm#2514]
### Steps To Reproduce

Just let Nextcloud VM run

### Expected Result

clamav not skipping files and don't use so much cpu forever

### Actual Result

Since 2 weeks, when I did a fresh install of nextcloudvm, clamav is using a lot of cpu. I think this started after I reuploaded all of my files (~130GB).

### Screenshots, Videos, or Pastebins

<img width="474" alt="Bildschirmfoto 2023-07-08 um 02 26 07" src="https://github.com/nextcloud/vm/assets/21086358/40e4b3d3-af85-4e77-aa4b-ff4b907e1808">

### Additional Context

The weekly scan is finishing:

----------- SCAN SUMMARY -----------
Known viruses: 8669986
Engine version: 0.103.8
Scanned directories: 0
Scanned files: 74019
Infected files: 0
Data scanned: 40543.21 MB
Data read: 115690.26 MB (ratio 0.35:1)
Time: 12639.262 sec (210 m 39 s)
Start Date: 2023:07:02 10:02:16
End Date:   2023:07:02 13:32:55

But clamav is scanning(?) forever and using a lot of cpu besides the weekly scan.

Additionally I'm getting this in the log of the webgui every minute:

Not Checked. No matching rule for response []. Please check antivirus rules configuration. File: 2012 Account: marius@mydomain.tld Path: /marius@mydomain.tld/files/Neu/20200730 - Fisch/20200730 - Fisch.zip

As far as I can see it's a different file every minute and only .zip files.

When I'm restarting the vm it is ok but starting againg after a few hours.

### Build Version

27.0.0.8

### Environment

By using the scripts

### Environment Details

I followed this:
https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/bj0vl4ahv0jgrmfm0950/build-your-own-nextcloud-vm

-Ubuntu 22.04.2 LTS
-Server 2019 and Hyper V role on Pentium Gold G5400 with 32GB RAM, Nextcloud VM has 4 Cores and 6GB RAM, 40GB System VHDX and 500GB Data VHDX

**Comment by enoch85** [comment]
@szaimen any idea?

**Comment by szaimen** [comment]
See https://github.com/nextcloud/vm/pull/2515

**Comment by enoch85** [comment]
@thatstheplace Please use the reinstall option. Thanks.

**Comment by thatstheplace** [comment]
Thanks for your support!

Where do I find the reinstall option?

And is it right, that every new file will be scanned besides the weekly scan?

And the weekly scan will do a kind of incremental scan?

**Comment by enoch85** [comment]
To reinstall, please use the menu script; 'sudo bash /var/scripts/menu.sh'

It won't scan files larger than 100 MB with the current setting.

**Comment by thatstheplace** [comment]
Thanks, reinstalled now.

I will report if it is better now.

But I think the current setting is 1000 MB?

Anyway, I have Zip-Files that are smaller than 100 MB.

So I don't think the size was the problem but we will see.

**Comment by szaimen** [comment]
Is this your issue?

https://github.com/nextcloud/files_antivirus/issues/223

**Comment by thatstheplace** [comment]
Hi

with the command I'm just getting:

`Error response from daemon: No such container: nextcloud-aio-nextcloud`

**Comment by enoch85** [comment]
> Error response from daemon: No such container: nextcloud-aio-nextcloud

It should be: nextcloud_occ config:app:set files_antivirus av_background_scan --value="off"

**Comment by thatstheplace** [comment]
With this I was getting "command not found".

Sorry for mayme a lot of noob questions but I'm not so familiar with the setup.

I now used this command based on the syntax I used to put Nextcloud in maintenance mode.

`sudo -u www-data php /var/www/nextcloud/occ config:app:set files_antivirus av_background_scan --value="off"`

It gave me this back:

`Config value av_background_scan for app files_antivirus set to off`

But the high CPU usage of clamav didn't stop.

I now restarted the VM and we will see if the background scan is starting again.

But if this workaround helps - do you want to fix this in the future?

And how can I set the MaxFileSize back to unlimited?

Thanks for your help.

**Comment by thatstheplace** [comment]
No more background scan with high cpu usage appearing, so this workaround helps.

How could I set the maxfilesize back so that the weekly scan is canning all files?

Thanks for your help!

**Comment by szaimen** [comment]
> How could I set the maxfilesize back so that the weekly scan is canning all files?

The weekly scan will scan all files anyway. This setting is onky about the files that get scanned on the fly while uploading.

**Comment by thatstheplace** [comment]
ok, but last week after new install it just scanned about the half of my files:

----------- SCAN SUMMARY -----------
Known viruses: 8670978
Engine version: 0.103.8
Scanned directories: 0
Scanned files: 229865
Infected files: 0
Data scanned: 53844.62 MB
Data read: 150476.67 MB (ratio 0.36:1)
Time: 18924.224 sec (315 m 24 s)
Start Date: 2023:07:16 10:02:15
End Date:   2023:07:16 15:17:39

And today it scanned this:

----------- SCAN SUMMARY -----------
Known viruses: 8671068
Engine version: 0.103.8
Scanned directories: 0
Scanned files: 67548
Infected files: 0
Data scanned: 4237.58 MB
Data read: 3980.70 MB (ratio 1.06:1)
Time: 1054.678 sec (17 m 34 s)
Start Date: 2023:07:23 10:00:32
End Date:   2023:07:23 10:18:07

**Comment by enoch85** [comment]
It scanned half of your files because the rest is bigger than the limit. 

So, high CPU usage, vs only scan smaller files than the default valu set.

**Comment by thatstheplace** [comment]
So changing the limit is no option?

It would cause endless high CPU usage again?

I wouldn't care about the high CPU usage if it wouldn't be endless.

**Comment by enoch85** [comment]
> It would cause endless high CPU usage again? 

You can try to play with it a little bit. Change it to something, run the scan (or wait for the cronjob), then post your results here. Maybe 100 MB is too small, and it would be great if you could find what's best so that we can use that as default instead.

gogogo :+1:  :)

**Comment by thatstheplace** [comment]
how can I change the limit?

GUI or CLI?

How can I start the scan manually?

**Comment by enoch85** [comment]
> GUI or CLI?

Check the command that @szaimen entered in the PR. It's done in `config.php`

**Comment by enoch85** [comment]
@thatstheplace Any update?

**Comment by tf-webdev** [comment]
We had the same issue described here by @thatstheplace with nearly 20 big .ppt, .pages and .key files within a user folder. CPU load was on average over 80%. Once there was even a server failure.
_(Nextcloud VM 500GB, Version 27.0.2 on Ubuntu 22.04.x and ClamAV / Antivirus App Version 5.2.2)_

Unfortunately, reinstalling ClamAV over /scripts/menu.sh didn't help. 

@enoch85 Thanks! That works... No more errors in nextcloud log and the CPU load is down to under 25%. 
`nextcloud_occ config:app:set files_antivirus av_background_scan --value="off"`

**Nextcloud Log / Example:**
```
[files_antivirus] Fehler: Not Checked. No matching rule for response []. Please check antivirus rules configuration. File: 1011101 Account: White-Habbit Path: /WHabbit/files/private/rabbithole/first-filedemo1.ppt

[files_antivirus] Fehler: Not Checked. No matching rule for response []. Please check antivirus rules configuration. File: 1011102 Account: White-Habbit Path: /WHabbit/files/private/rabbithole/first-filedemo2.key

[files_antivirus] Fehler: Not Checked. No matching rule for response []. Please check antivirus rules configuration. File: 1011103 Account: White-Habbit Path: /WHabbit/files/private/rabbithole/first-filedemo3.pages
```
**Details / raw format:**
`{"reqId":"ZdHKq6hBchi45zdstZt2M","level":3,"time":"2023-09-13T13:06:13+02:00","remoteAddr":"","user":"--","app":"files_antivirus","method":"","url":"--","message":"Not Checked. No matching rule for response []. Please check antivirus rules configuration. File: 1011101 Account: WHabbit Path: /WHabbit/files/private/rabbithole/first-filedemo1.ppt","userAgent":"--","version":"27.0.2.1","data":{"app":"files_antivirus"},"id":"53201Xazz23eb1"}`

**Comment by thatstheplace** [comment]
Sorry for the late reply.

I will look further into it on the weekend.

**Comment by enoch85** [comment]
@thatstheplace ?

**Comment by thatstheplace** [comment]
Hi,

sorry for the late reply again. I'm very busy in the last weeks/months.

I did a few tests in the last weeks though.

Even with the latest "5.3.0" of the Antivirus for files, the background scan leads to the failure.

So I think it's the best to disable the background scan as default until it is fixed in [https://github.com/nextcloud/files_antivirus](), because I'm thinking of the same reason like @szaimen mentioned in [https://github.com/nextcloud/files_antivirus/issues/223#issuecomment-1072515440](url).

But I added "--max-scansize=1000M" in "clamav-fullscan.sh":

`clamscan "--move=/root/.clamav/clamav-fullscan.jail" --file-list=/tmp/scanlist --max-filesize=1000M --pcre-max-filesize=1000M --max-scansize=1000M "--exclude-dir=/root/.clamav/clamav-fullscan.jail/" | tee "/var/log/nextcloud/clamav-fullscan.log" && rm -f /tmp/scanlist
`

This leads to:

"clamav-fullscan.sh" inital scan without "--max-scansize=1000M":

----------- SCAN SUMMARY -----------
Known viruses: 8677397
Engine version: 0.103.9
Scanned directories: 0
Scanned files: 301465
Infected files: 0
Data scanned: **59612.66 MB**
Data read: **159387.69 MB** (ratio 0.37:1)
Time: 13746.563 sec (229 m 6 s)
Start Date: 2023:11:04 21:40:49
End Date:   2023:11:05 01:29:56


"clamav-fullscan.sh" 1. scan after inital scan without "--max-scansize=1000M":

----------- SCAN SUMMARY -----------
Known viruses: 8677439
Engine version: 0.103.9
Scanned directories: 0
Scanned files: 173618
Infected files: 0
Data scanned: 15733.27 MB
Data read: 11354.62 MB (ratio 1.39:1)
Time: 4138.387 sec (68 m 58 s)
Start Date: 2023:11:05 23:06:15
End Date:   2023:11:06 00:15:13


"clamav-fullscan.sh" inital scan with "--max-scansize=1000M":

----------- SCAN SUMMARY -----------
Known viruses: 8677808
Engine version: 0.103.9
Scanned directories: 0
Scanned files: 297611
Infected files: 0
Data scanned: **171813.32 MB**
Data read: **160646.39 MB** (ratio 1.07:1)
Time: 29984.543 sec (499 m 44 s)
Start Date: 2023:11:08 22:28:11
End Date:   2023:11:09 06:47:56

"clamav-fullscan.sh" 1. scan after inital scan with "--max-scansize=1000M":

----------- SCAN SUMMARY -----------
Known viruses: 8678011
Engine version: 0.103.9
Scanned directories: 0
Scanned files: 39088
Infected files: 0
Data scanned: 7980.77 MB
Data read: 6055.43 MB (ratio 1.32:1)
Time: 1866.385 sec (31 m 6 s)
Start Date: 2023:11:12 10:01:08
End Date:   2023:11:12 10:32:14


I'm feeling safer with the "--max-scansize=1000M", whats your opinion? Do you consider to set this as default?

**Comment by enoch85** [comment]
> See #2515

Closing since this is fixed.
