### ISSUE TITLE
Major update case not managed by `update_nextcloud`

### ISSUE THREAD

**Issue by emericv** [nextcloud/vm#2516]
### Steps To Reproduce

When I run `update_nextcloud` where my current version has two major versions late, I have this screen without a proposed solution…

![image](https://github.com/nextcloud/vm/assets/1727636/90e73667-0e05-4cb3-9625-15b403e3ea8f)

In fact, you cannot upgrade more than one major version at once, but the `update_nextcloud` tool doesn't seem to support this case….

### Expected Result

This tool must perform an update to the next major version.

### Actual Result

This tool try to perform an update to the last major version.

### Build Version

25.0.8

### Environment

By using the scripts

### Environment Details

Ubuntu

**Comment by emericv** [comment]
I also try to `echo "26" > /tmp/nextmajor.version` but I have this screen too :

![image](https://github.com/nextcloud/vm/assets/1727636/f25215f5-d038-441e-aa13-b350f5a6d8b0)

:O

**Comment by emericv** [comment]
ok, with `echo "26.0.3" > /tmp/nextmajor.version` the update is starting but :
![image](https://github.com/nextcloud/vm/assets/1727636/ab195873-5e90-482a-ae8e-b53a2c867464)

**Comment by emericv** [comment]
![image](https://github.com/nextcloud/vm/assets/1727636/3e1ae180-8a40-418e-933b-a9cde5e9f189)
:)

I will try now to upgrade to the last version...

**Comment by emericv** [comment]
It's now OK
![image](https://github.com/nextcloud/vm/assets/1727636/065449ff-680c-457d-993b-2648ba385c90)

Ok, It needs just a way to detect and treat this case properly :)

**Comment by enoch85** [comment]
As Nextcloud writes in [their documentation](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/upgrade.html): 

> Nextcloud must be upgraded step by step:
> Before you can upgrade to the next major release, Nextcloud upgrades to the latest point release.
>  Then run the upgrade again to upgrade to the next major release’s latest point release.
>  You cannot skip major releases. Please re-run the upgrade until you have reached the highest available (or applicable) release.
> Example: 18.0.5 -> 18.0.11 -> 19.0.5 -> 20.0.2.

We will not implement a feature that will jump between releases as it's not recommended.

**Comment by emericv** [comment]
@enoch85, yes, the jump between multiple releases major as it's not recommended, but the problem is not here, this tool displays an error without a possibility and solution to perform an update to the next major release instead.

The issue : Instead and additionally, this too should propose to perform an update to the next major release.
