### ISSUE TITLE
systemctl restart apache2.service failed

### ISSUE THREAD

**Issue by Gollapaguws** [nextcloud/vm#2518]
### Steps To Reproduce

Execute Script: 
sudo bash nextcloud_install_production.sh

### Expected Result

Script complete

### Actual Result

systemctl restart apache2.service failed

### Additional Context

/etc/apache2/sites-available/nextcloud_http_domain_self_signed.conf was successfully created.
/etc/apache2/sites-available/nextcloud_tls_domain_self_signed.conf was successfully created.
Enabling site nextcloud_tls_domain_self_signed.
To activate the new configuration, you need to run:
  systemctl reload apache2
Enabling site nextcloud_http_domain_self_signed.
To activate the new configuration, you need to run:
  systemctl reload apache2
Site default-ssl already disabled
Restarting Apache2 and PHP-FPM...
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xeu apache2.service" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart apache2.service failed
Posting notification to users that are admins, this might take a while...
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to: admin

### Build Version

27

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04 LTS
Using script
VM Hyper-V 4g ram

**Comment by enoch85** [comment]
Thanks for reporting, this must be temporary. Can't reproduce it here. 

Can you try again please?

**Comment by Gollapaguws** [comment]
Thank you.  

It apears the Ubuntu I installed was desktop?  I reinstalled, but this time i went to the Ubuntu website directly for the server distro rather than the distros that come pre setup in hyper-v.  The setup was very different.

Everything went like a breeze.  It was resolved.
