### ISSUE TITLE
Implement Talk recording

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2519]
@szaimen How hard you you think it would be to implement talk recording in the VM using the docker config from AIO? Just noticed it today, great work! :raised_hands: 

Would it be sufficient to download [this](https://github.com/nextcloud/all-in-one/tree/main/Containers/talk-recording) and run start.sh?

**Comment by szaimen** [comment]
In theory it shouldnt be that difficult but you will need to do some changes to the talk config first. You can compare with https://github.com/nextcloud/all-in-one/blob/main/Containers/talk/start.sh.

Afterwards something like this could be used in principle: https://github.com/nextcloud/all-in-one/blob/70b46093ab2a5915a7844d30dd4067e966640ecb/manual-install/latest.yml#L184-L198 (but I would prefer again to not use docker-compose but instead normal docker run command for that).

**Comment by szaimen** [comment]
> Since you are maintainer here as well, do you think you could start something small just to give me pointers that I can work on, kind of like with imaginary?

Sorry, I dont have the time to look into this currently. I hoped that my pointers would have been enough? I would suggest that you start the PR and I add some comments. WDYT?

> I mean, we already have Talk and Signaling just like in AIO, so I guess it's just a matter of changing the name of the $vars?

yes, basically

**Comment by enoch85** [comment]
Sure, will make an effort when *I* have time 😄
