### ISSUE TITLE
Imaginary not pulling from Docker Repo

### ISSUE THREAD

**Issue by monday-j** [nextcloud/vm#2527]
### Steps To Reproduce

Either:

1. Choose to install Imaginary during initial script setup

or,

1. Manually pull using docker-compose or "docker pull nextcloud/aio-imaginary

### Expected Result

Image is pulled from Docker Hub as expected.

### Actual Result

Error response from daemon: Get "https://registry-1.docker.io/v2/nextcloud/aio-imaginary/manifests/sha256:930c2c843908c31db367541277d51084b63478c4ef0d30e2f9e31d2f5b600e61": dial tcp: lookup registry-1.docker.io on *LOCAL IP ADDRESS*: no such host

### Build Version

Nextcloud Hub 5 27.0.1

### Environment

By using the scripts

### Environment Details

Debian LXC Container within Proxmox VE

**Comment by enoch85** [comment]
@szaimen something temporary?

**Comment by szaimen** [comment]
Sounda like a dns issue on @monday-j server. I found this: https://stackoverflow.com/questions/47580528/error-response-from-daemon-get-https-registry-1-docker-io-v2-dial-tcp-look

**Comment by monday-j** [comment]
Yep, seems to have fixed it. My bad, I should have done more troubleshooting on my end before reporting this as a bug.
