### ISSUE TITLE
Install of Fulltextsearch failing

### ISSUE THREAD

**Issue by thatstheplace** [nextcloud/vm#2528]
### Steps To Reproduce

Install fulltextsearch.

### Expected Result

fulltextsearch installing, indexing and running.

### Actual Result

```
Waiting for a few seconds before indexing starts...
 
.Testing your current setup:  
Creating mocked content provider. ok  
Testing mocked provider: get indexable documents. (2 items) ok  
Loading search platform. (Elasticsearch) ok  
Testing search platform. fail 
In Test.php line 304:
                                          
  Search platform (Elasticsearch) down ?  
                                          

fulltextsearch:test [--output [OUTPUT]] [-j|--json] [-d|--platform_delay PLATFORM_DELAY]
```

### Additional Context

`curl -X GET "localhost:9200/?pretty"`

is giving me:

`Unauthorized`

### Build Version

27.0.1

### Environment

By using the scripts

**Comment by enoch85** [comment]
Yes, this is known. Thanks for reporting!

@Ark74

**Comment by Ark74** [comment]
You need to pass the credentials in order to get a response,

curl -XGET "credential:password@localhost:9200/"

The opensearch server is working, the nextcloud client is what changed since version 26.

**Comment by enoch85** [comment]
@Ark74 What's your opinion on this? https://github.com/R0Wi/elasticsearch-nextcloud-docker Could we replace your docker with that one?

**Comment by Ark74** [comment]
My opinion is that you'll be depending on what R0Wi does with the image he hosts.
The current setup uses the main Opensearch image, not any third user/developer hosted one, not even me.

Another thought is about the Elastic Search license from Apache to SSPL change, IIRC it will affect SaaS providers using their fts engine,  at what point that could become an issue as an automated installation system?

That was the second point we targeted while moving to the Opensearch one.

**Comment by thatstheplace** [comment]
Ok, this is getting me a response. I think for you its no surprise and because I don't know how private the response is, I don't post it here, except you need it.

`curl -XGET "credential:password@localhost:9200/"`

**Comment by enoch85** [comment]
After disucssions with @Ark74 this is something that @ArtificialOwl needs to fix (implement support for OpenSearch) since we are using that in our implementation due to licensing and other stuff - @Ark74 correct me if I'm wrong.

**Comment by Ark74** [comment]
Nope, that's the main issue.
We hope @ArtificialOwl could take our petition into account, and by restoring ES 7 retro-compatibility this can be solved.

At some point maybe we could work together with him on the future Opensearch 2.x support if he sees fit.
Regards

**Comment by dualizeo** [comment]
this might be the problem which is causing the proxmox vm to run at 100% all the time

**Comment by enoch85** [comment]
This is now fixed, please run the installer again: https://github.com/nextcloud/vm/pull/2541
