### ISSUE TITLE
Server stays in maintenance mode after running borgbackup.sh

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#2534]
### Steps To Reproduce

1. wait for borbackup.sh to get executed on a daily basis
2. Server is in maintenance mode afterwards

I suspect this is caused by https://github.com/nextcloud/vm/pull/2532 and/or https://github.com/nextcloud/vm/pull/2530 because it didnt happen formerly.

### Expected Result

Server should not be in maintenance mode after running the script

### Actual Result

Server stays in maintenance mode after running the script

### Additional Context

I suspect this is caused by https://github.com/nextcloud/vm/pull/2532 and/or https://github.com/nextcloud/vm/pull/2530 because it didnt happen formerly.

### Build Version

latest

### Environment

By using the scripts

**Comment by szaimen** [comment]
Maybe I was wrong and it was just a hickup. Closing for now.

**Comment by enoch85** [comment]
No, we changed the way nextcloud_occ works so you can't call nextcloud_occ when maintenance mode is set, since it's set directly in the function instead.

**Comment by enoch85** [comment]
Like this: https://github.com/nextcloud/vm/commit/dea4242e889d85f98d0af547d4465c4a78889f33

**Comment by szaimen** [comment]
So we would need to adjust all script where we do something with the maintenance mode correct?

**Comment by enoch85** [comment]
> So we would need to adjust all script where we do something with the maintenance mode correct?

Yes, correct. 

`nextcloud_occ maintenance:mode --on` --> `sudo -u www-data php "$NCPATH"/occ maintenance:mode --on`

**Comment by enoch85** [comment]
If at all needed, since `nextcloud_occ` now includes the maintenance check, so if maintenance mode is enabled it will stay that way, with the exeption of `nextcloud_occ` being run. Please check the code [here](https://github.com/nextcloud/vm/blob/master/lib.sh#L1181-L1195)

**Comment by szaimen** [comment]
Can we please create an exception for when maintenance:mode is called that it does not activate it automatically and just runs the command? Currently this is a bug and I dont have the time to adjust my scripts unfortunately since I am travelling. Also this brings down my instance each day.

**Comment by szaimen** [comment]
My instance was in maintenance mode again this morning so I think somehow does the check not work as expected. Can we revert the change please until I am back next week? I cannot fix this currently unfortunately since I am travelling and dont have my computer with me and it is bringing down my instance each day.

**Comment by szaimen** [comment]
It works, thanks! 💙

**Comment by enoch85** [comment]
Great to hear! Now it would be nice if you could help me with Talk recording :)
