### ISSUE TITLE
Imaginary webp NC 28

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2538]
https://github.com/nextcloud/documentation/pull/10256/files

Note to self. @szaimen I suppose this means that we need to add the config in `config.php` for everyone running Imaginary?

**Comment by szaimen** [comment]
> @szaimen I suppose this means that we need to add the config in `config.php` for everyone running Imaginary?

If the server PR gets merged until then, then we can optionally change it for everyone running imaginary, yes

**Comment by enoch85** [comment]
@szaimen I can see that this is merged now. Any advice?

**Comment by szaimen** [comment]
The preview format can be adjusted like so: `'preview_format' => 'webp',` but this should be tested first. Also regarding performance of generating the previews compared to jpg

**Comment by szaimen** [comment]
Alao there should be a check for nc28 for this setting

**Comment by enoch85** [comment]
https://theplusaddons.com/blog/jpg-vs-webp/

I'll think about this one for a while.

**Comment by enoch85** [comment]
Basically:

WebP: Better, newer, faster
JPEG: Worse, older, slower, but compatible with almost everything.

I'm thinking, if we opt for WebP, only browsers supported are newer updates ones. In 2024, do we really need compatibility?
