### ISSUE TITLE
Talk recording use a different domain

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#2544]
@szaimen Next issue...

In AIO you have hardcoded the URL for the signaling-server to https://xyz.domain.com/standalone-signaling/. In the VM, we just use the main domain, without the specific URL:  https://xyz.domain.com/ and then [proxy it to localhost](https://github.com/nextcloud/vm/blob/master/apps/talk.sh#L450-L454).

This makes it impossible to run your config, since it won't find the secret for the signaling server.

Maybe we can figure this one out together? Else, I'll have to write a separate script for this, not using AIO talk recording.

**Comment by szaimen** [comment]
see https://github.com/nextcloud/all-in-one/blob/c6c1effa6d9c3fc9c8d57c59eaf2bd53b79f6341/Containers/talk-recording/Dockerfile#L9

**Comment by enoch85** [comment]
@szaimen Aah ok, so by setting `-e HPB_PATH=$HPB_DOMIAN` it will be without your hardcoded URL?

We already set the variable here[here](https://github.com/nextcloud/vm/blob/master/apps/talk.sh#L537)

**Comment by szaimen** [comment]
> Aah ok, so by setting `-e HPB_PATH=$HPB_DOMAIN` it will be without your hardcoded URL?

No, try `-e HPB_PATH=/`

**Comment by enoch85** [comment]
Thanks a ton @szaimen! Now everything works. :1st_place_medal:
