### ISSUE TITLE
Webdav performance has subsided reagarding upload/delete of 150 Files

### ISSUE THREAD

**Issue by MSchweigart** [nextcloud/vm#2548]
### Steps To Reproduce

1. Mount nextcloud storage as described in https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html .
2. Get 150 ttf-files from https://github.com/chrisbull/font-collection.
3. Upload 150 files to the nextcloud-share takes 3 1/2 minutes. Deleting the 150 uploaded files takes 2 Minutes.
5. Login in the nextcloud with a webbrowser. Uploading 150 Files takes 15 seconds and therafter deleting 10 seconds.

### Expected Result

Uploading 150 files via mountpoint should take not more than 10 x of the uploading via webbrowser. Not 3 1/2 minutes but 10 * 15 seconds = 2 1/2 minutes. 
And deleting 150 files should take 10 * 10 seconds = 100 seconds instead of 120 seconds.

-> 3 Years ago the 150 files where uploaded in 1 1/2 minutes and deleted in 1 minute. 

### Actual Result

Uploading 150 files via mountpoint takes 3 1/2 minutes and deleting takes about 2 Minutes.
Uploading  150 files via webbrowser takes 15 saeconds and deleting takes about 10 seconds.

### Screenshots, Videos, or Pastebins

Nextcloud via webdav:
![grafik](https://github.com/nextcloud/vm/assets/28785393/e7effa90-5fc2-4f44-b8b7-91a8b7212488)

Browser-Nextcloud:
![grafik](https://github.com/nextcloud/vm/assets/28785393/77195148-43a1-482a-983b-abbeec4f6407)

### Additional Context

I think that is not your theme, because your Script generates a very well performing nextcloud. 
But i hope to hear the same from you. But perhaps you can give me a contact to talk about this issue.

### Build Version

Nextcloud 27.0.1

### Environment

By using the scripts

### Environment Details

I am using the Nexcloud on ubuntu 22.04 installed a month ago from https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh .

**Comment by enoch85** [comment]
Thanks for reporting!

I don't see how this has anything to do with how the VM is setup. That it takes 10 seconds in the WebUI, and X minutes with the mounting point, just tells me that the mounting point is slow, or that it's network related - and that the PHP setup (GUI is PHP based) is flying and we did a good job. :)

If it's SMB, did you try our SMB mount script? If not, please do.

**Comment by MSchweigart** [comment]
Thanks for your answer.
Meanwhile i tried the Nextcloud App "Client push", see https://github.com/nextcloud/notify_push .

With this App i get nearer to the desired values:
  -> Uploading 150 files via mountpoint takes 2 1/2 minutes and deleting takes about 1 /2 Minutes.
  -> Uploading 150 files via webbrowser takes 10 seconds and deleting takes about 8 seconds.

See you later.

**Comment by enoch85** [comment]
We actually have that app as an option in the VM. Just execute the install script from the `menu.sh` script in `/var/scripts/`

**Comment by MSchweigart** [comment]
Thank you very much!
You are doing a great job since many years.
