### ISSUE TITLE
sudo bash nextcloud_install_production.sh failing

### ISSUE THREAD

**Issue by thatstheplace** [nextcloud/vm#2549]
### Steps To Reproduce

Install Nextcloud VM with the script "sudo bash nextcloud_install_production.sh"

### Expected Result

Script finishes without error.

### Actual Result

igbinary PHP module installation OK!
Restarting Apache2 and PHP-FPM...
Getting current PHP-version...
PHPVER=8.1
Optimizing Nextcloud...
An unhandled exception has been thrown:
RedisException: No such file or directory in /var/www/nextcloud/lib/private/RedisFactory.php:137
Stack trace:
#0 /var/www/nextcloud/lib/private/RedisFactory.php(137): Redis->pconnect()
#1 /var/www/nextcloud/lib/private/RedisFactory.php(178): OC\RedisFactory->create()
#2 /var/www/nextcloud/lib/private/Memcache/Redis.php(66): OC\RedisFactory->getInstance()
#3 /var/www/nextcloud/lib/private/Memcache/Redis.php(72): OC\Memcache\Redis->getCache()
#4 /var/www/nextcloud/lib/private/App/InfoParser.php(58): OC\Memcache\Redis->get()
#5 /var/www/nextcloud/lib/private/App/AppManager.php(732): OC\App\InfoParser->parse()
#6 /var/www/nextcloud/lib/private/legacy/OC_App.php(434): OC\App\AppManager->getAppInfo()
#7 /var/www/nextcloud/lib/private/AppFramework/App.php(71): OC_App::getAppInfo()
#8 /var/www/nextcloud/lib/private/legacy/OC_App.php(155): OC\AppFramework\App::buildAppNamespace()
#9 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#10 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#11 /var/www/nextcloud/lib/base.php(703): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#12 /var/www/nextcloud/lib/base.php(1180): OC::init()
#13 /var/www/nextcloud/console.php(48): require_once('...')
#14 /var/www/nextcloud/occ(11): require_once('...')
#15 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
**sudo -u www-data php /var/www/nextcloud/occ db:convert-filecache-bigint failed**
An unhandled exception has been thrown:
RedisException: No such file or directory in /var/www/nextcloud/lib/private/RedisFactory.php:137
Stack trace:
#0 /var/www/nextcloud/lib/private/RedisFactory.php(137): Redis->pconnect()
#1 /var/www/nextcloud/lib/private/RedisFactory.php(178): OC\RedisFactory->create()
#2 /var/www/nextcloud/lib/private/Memcache/Redis.php(66): OC\RedisFactory->getInstance()
#3 /var/www/nextcloud/lib/private/Memcache/Redis.php(72): OC\Memcache\Redis->getCache()
#4 /var/www/nextcloud/lib/private/App/InfoParser.php(58): OC\Memcache\Redis->get()
#5 /var/www/nextcloud/lib/private/App/AppManager.php(732): OC\App\InfoParser->parse()
#6 /var/www/nextcloud/lib/private/legacy/OC_App.php(434): OC\App\AppManager->getAppInfo()
#7 /var/www/nextcloud/lib/private/AppFramework/App.php(71): OC_App::getAppInfo()
#8 /var/www/nextcloud/lib/private/legacy/OC_App.php(155): OC\AppFramework\App::buildAppNamespace()
#9 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#10 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#11 /var/www/nextcloud/lib/base.php(703): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#12 /var/www/nextcloud/lib/base.php(1180): OC::init()
#13 /var/www/nextcloud/console.php(48): require_once('...')
#14 /var/www/nextcloud/occ(11): require_once('...')
#15 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
**sudo -u www-data php /var/www/nextcloud/occ db:add-missing-indices failed**
Checking connection...
Home/SME Server not detected. No worries, just testing the function.
**postgresql is installed, it must be a clean server.**

### Build Version

Latest of today

### Environment

By using the scripts

### Environment Details

Fresh installed Ubuntu 22.04.2 but with updated installer during setup

**Comment by enoch85** [comment]
Let's track this in #2550
