### ISSUE TITLE
 nextcloud_install_production.sh failing  config:system:set redis port --value=0 failed

### ISSUE THREAD

**Issue by pym67** [nextcloud/vm#2550]
### Steps To Reproduce

Install Nextcloud VM with the script "sudo bash nextcloud_install_production.sh"

### Expected Result

Script finishes without error.

### Actual Result

System config value memcache.local set to string \OC\Memcache\Redis
System config value filelocking.enabled set to string true
System config value memcache.distributed set to string \OC\Memcache\Redis
System config value memcache.locking set to string \OC\Memcache\Redis
System config value redis => host set to string /var/run/redis/redis-server.sock
An unhandled exception has been thrown:
RedisException: No such file or directory in /var/www/nextcloud/lib/private/RedisFactory.php:137
Stack trace:
#0 /var/www/nextcloud/lib/private/RedisFactory.php(137): Redis->pconnect()
#1 /var/www/nextcloud/lib/private/RedisFactory.php(178): OC\RedisFactory->create()
#2 /var/www/nextcloud/lib/private/Memcache/Redis.php(66): OC\RedisFactory->getInstance()
#3 /var/www/nextcloud/lib/private/Memcache/Redis.php(72): OC\Memcache\Redis->getCache()
#4 /var/www/nextcloud/lib/private/App/InfoParser.php(58): OC\Memcache\Redis->get()
#5 /var/www/nextcloud/lib/private/App/AppManager.php(732): OC\App\InfoParser->parse()
#6 /var/www/nextcloud/lib/private/legacy/OC_App.php(434): OC\App\AppManager->getAppInfo()
#7 /var/www/nextcloud/lib/private/AppFramework/App.php(71): OC_App::getAppInfo()
#8 /var/www/nextcloud/lib/private/legacy/OC_App.php(155): OC\AppFramework\App::buildAppNamespace()
#9 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(119): OC_App::registerAutoloading()
#10 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC\AppFramework\Bootstrap\Coordinator->registerApps()
#11 /var/www/nextcloud/lib/base.php(703): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#12 /var/www/nextcloud/lib/base.php(1180): OC::init()
#13 /var/www/nextcloud/console.php(48): require_once('...')
#14 /var/www/nextcloud/occ(11): require_once('...')
#15 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
**sudo -u www-data php /var/www/nextcloud/occ config:system:set redis port --value=0 failed**

### Additional Context

looks to be related to the following commit :  https://github.com/nextcloud/vm/commit/09bd223ad3ab652dd3597c2b4ba2c757fb95c06b

looks to be related to to issue #2549

### Build Version

27.0.2

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04

**Comment by enoch85** [comment]
Thanks for this, will have a look later today.
