### ISSUE TITLE
Script stuck at Checking connection...

### ISSUE THREAD

**Issue by maxdoorman** [nextcloud/vm#2557]
### Steps To Reproduce

Install Nextcloud VM with the script "sudo bash nextcloud_install_production.sh"

### Expected Result

Script installs nextcloud

### Actual Result

Setting locales...
US locales are already set.
Checking connection...
curl didn't produce a 200 status, is https://download.nextcloud.com/server/releases reachable?
Checking connection...

### Build Version

latest

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04.03 LTS
LXC & Ubuntu VM both have this problem

**Comment by enoch85** [comment]
This is most likely that you have restricted some sites or use country block, in other words: a firewall setting.

Please double check and try again. I can't reproduce this.
