### ISSUE TITLE
Collabora not reliable

### ISSUE THREAD

**Issue by thatstheplace** [nextcloud/vm#2559]
### Steps To Reproduce

Open Documents with Collabora.

### Expected Result

Document getting opened.

### Actual Result

Sometimes Collabora says "can't open...".

Currently I'm running Collabora over the docker way. The integrated way caused an extreme slow frontend.

What are the real system requirements for the VM?

Currently I have 12GB RAM for the VM, is this normal?

Here you're recommending 4GB RAM: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/bj0vl4ahv0jgrmfm0950/build-your-own-nextcloud-vm

Are the RAM recommendations for the additional apps extra to this?

So 4GB RAM for Nextcloud, 4GB RAM for FTS, 4GB RAM for Imaginary = 12GB RAM total?

How much do you recommend for the different office integration? Collabora vs. OnlyOffice, Integrated vs. Docker?

What is the best practice for the office integration? Collabora vs. OnlyOffice, Integrated vs. Docker?

Which runs best and is the most reliable?

### Additional Context

In this environment there is a firewall involved and the Nextcloud VM is behind the reverse proxy (squid) of the firewall.

Over the Reverse Proxy, Collabora Docker is never opening a file, I think this is because of Nextcloud using http for the Collabora requests or is switching between http and https, squid don't likes the latter according to the firewall developer, will check this deeper with the firewall developer.

So to bypass the reverse proxy I made internal DNS entries on the firewall for cloud.domain.tld and office.domain.tld so I can reach the Nextcloud VM directly without reverse proxy. This way it's working but not 100% reliable, like I described before.

### Build Version

Latest of today

### Environment

By using the scripts

### Environment Details

-Ubuntu 22.04.03
-12 GB RAM
-4 vCPU (Intel Xeon Silver 4110 @ 2,1 GHz)

**Comment by enoch85** [comment]
The RAM doesn't add up, but is a minimum requirement for running different services.

Just running Collabora and Nextcloud doesn't require 12 GB. I think 4-8 GB would be good for that installation depending on how many users you have and the tuning settings of the VM.

I hope that answers your question.
