### ISSUE TITLE
[Please Help] Nextcloud error while upgrading to ver 12

### ISSUE THREAD

**Issue by hammeractual** [nextcloud/vm#256]
## Steps to reproduce
1. Upgrading Nextcloud using sudo bash /var/scripts/update.sh

## Expected behaviour
Nextcloud Upgraded to version 12.0

## Actual behaviour
Thrown Error Message "Something went wrong with copying your mysql password to /root/.my.cnf."

## Server configuration

Ubuntu Linux 16.04.1
Nextcloud 11.0.3
VMware from Tech and Me with Fresh Instalation

## Network
Use DHCP
Open Port 443

#### Log file (/var/ncdata/nextcloud.log)
http://s000.tinyupload.com/index.php?file_id=13687613119994094830

#### Installation log (command output)
```

```

#### Screenshoots
http://imgur.com/a/eQEjs

**Comment by enoch85** [comment]
Thanks for reporting this! 

Can you try these commands and write the output here please:

`sudo cat /root/.my.cnf`
`sudo cat /var/mysql_password.txt`

Thank you!

**Comment by enoch85** [comment]
@hammeractual PING!

**Comment by enoch85** [comment]
As you don't respond I'll close this. Please reopen if the issue persists.

Thanks!

**Comment by hammeractual** [comment]
asdasdasdasdasdas

**Comment by enoch85** [comment]
Oh, your MySQL root password is gone. :( Did you remove it?

I don't have a quick fix for recovering it but a quick googling gave me this: https://www.howtoforge.com/reset-forgotten-mysql-root-password

**Comment by hammeractual** [comment]
Thanks for the reply.

No, I didn't. 

So, I have to reset the mysql password?
And then, what should I do with the nextcloud after mysql password has been reset?

**Comment by enoch85** [comment]
When the passsword is reset you have to save it to `/root/.my.cnf` like this:

```
[client]
password='yourmysqlpasssoword'
```

Then I also recommend that you run this script https://github.com/nextcloud/vm/blob/master/static/change_mysql_pass.sh to get a secure password.

**Comment by hammeractual** [comment]
Alright, the problem is now fixed, but I did clean install, hehehe.

Thank you.
