### ISSUE TITLE
NC Upgrade 27.0.1 -> 27.0.2 | Repair error: Downloading of node binary failed

### ISSUE THREAD

**Issue by MaximilianOnGitHub** [nextcloud/vm#2560]
### Steps To Reproduce

Hi,

starting with  bash /var/scripts/update.sh after a while I'm getting some errors related to node:

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: analytics
Disabled incompatible app: cadviewer
Disabled incompatible app: drawio
Disabled incompatible app: files_automatedtagging
Disabled incompatible app: groupfolders
Disabled incompatible app: maps
Disabled incompatible app: memories
Disabled incompatible app: metadata
Disabled incompatible app: notes
Disabled incompatible app: previewgenerator
Disabled incompatible app: richdocuments
Disabled incompatible app: richdocumentscode
Disabled incompatible app: spreed
Disabled incompatible app: translate
mimetypelist.js is updated
mimetypelist.js is updated

Repair error: Downloading of node binary failed

Repair error: Downloading of node binary failed
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Optimizing Nextcloud...

[...]

     - ERROR: Downloading of node binary failed
 - Add background job to check for backup codes
 - Insert UUIDFix background job for user and group in batches
 - Remove deprecated refresh time markers for LDAP user records
 - Populating added database structures for workflows
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:repair failed
Posting notification to users that are admins, this might take a while...
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to: nchadmin

-> Nextcloud is up and running with 27.0.2 

Best regards
Max

### Expected Result

Smooth upgrade

### Actual Result

ERROR: Downloading of node binary failed
-> Reported 

### Build Version

27.0.1

### Environment

By using the scripts

### Environment Details

Ubuntu, PHP 8-1

**Comment by enoch85** [comment]
Hi,

Do you have npm installed on this server? Which apps are enabled, Recognize maybe?

**Comment by MaximilianOnGitHub** [comment]
Hi,
npm is not installed;
Recognize was installed but was deinstalled later. (But before the upgrade)

Current (and whilst upgrading) 

Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - analytics: 4.10.0
  - cadviewer: 8.80.6
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - drawio: 2.1.2
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_automatedtagging: 1.17.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - groupfolders: 15.0.2
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.1.1
  - memories: 5.4.1
  - metadata: 0.19.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.1.1
  - richdocumentscode: 23.5.301
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.0.3
  - support: 1.10.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - translate: 1.1.6
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0
  - circles: 27.0.1 (installed 22.0.0)
  - encryption: 2.15.0
  - files_external: 1.19.0 (installed 1.19.0)
  - firstrunwizard: 2.16.0 (installed 2.8.0)
  - survey_client: 1.15.0 (installed 1.7.0)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_status: 1.7.0 (installed 1.7.0)
  - weather_status: 1.7.0 (installed 1.7.0)


Kind regards
Max

**Comment by enoch85** [comment]
Recognize uses npm so I think there's your issue. How did you remove it?
