### ISSUE TITLE
The installation script will appear every time I log into my Nextcloud via SSH

### ISSUE THREAD

**Issue by DJIronic** [nextcloud/vm#2571]
### Steps To Reproduce

1. I just connect to my server and get this:
![image](https://github.com/nextcloud/vm/assets/9658012/60c56f61-8723-4872-b71e-1c991000502f)

2. After a second or so, popup shows:
![image](https://github.com/nextcloud/vm/assets/9658012/95c692f3-ee23-498c-b2fe-7d6230453352)

3. I am asked if I want to chenge Keyboard layout, timezone or change mirror
4. Then the script will open another popup with 
![image](https://github.com/nextcloud/vm/assets/9658012/8702b0b9-95f3-4122-82dd-4e53399fbb1d)

Then, I am asked if I want to continue the script. Selecting no will let me in SSH, selecting yes will let me know the script already ran.

### Expected Result

My nextcloud VM works as expected, can update and work. So I should not see the installation script.

### Actual Result

I see it every time I log in.

### Screenshots, Videos, or Pastebins

https://www.youtube.com/watch?v=juVBfs7F6S4

### Build Version

Nextcloud 26.0.7

### Environment

By downloading the VM

### Environment Details

- OS: Ubuntu
- DB: PostgreSQL 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
- PHP: Version: 8.1.2, Memory limit: 512 MB, Max execution time: 3600, Upload max size: 1000 MB
- CPU: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz (6 cores)
- Memory: 80GB

Hosted on Vmware esxi.

**Comment by enoch85** [comment]
This is because you never finished the first installation. 

If it's a fresh download then please remove it and start over. If not fresh, then do:

`rm /var/scripts/you- [TAB]`
`rm /var/scripts/nextcloud- [TAB]`

`[TAB]` means write the first characters and then hit TAB and it will auto complete.

**Comment by enoch85** [comment]
Since you seem technical, this is what wasn't run: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L621-L622

**Comment by enoch85** [comment]
Possibly also this: https://github.com/nextcloud/vm/blob/dc7017891a9450458f9e2f76ac8e4ea9e4aefe96/nextcloud-startup-script.sh#L503-L521
