### ISSUE TITLE
installation scripts inconsistent downloads

### ISSUE THREAD

**Issue by gelome** [nextcloud/vm#2577]
### Steps To Reproduce

whenever I try to download the script nextcloud_install_production.sh it says - Unable to establish SSL connection.
after multiple tries it downloads the script. when trying to run the script....some of the scripts are not downloadable. eg - Downloading format-chosen failed, Downloading lib failed, Downloading redis-server-ubuntu failed. 

I have tried on multiple servers. this has been going on since 01/10/2023.

### Expected Result

scripts download should download

### Actual Result

scripts don't download.

### Build Version

27.1.1

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04, 10gb ram, proxmox vm as well as on another machine not running proxmox.

**Comment by enoch85** [comment]
Thanks for reporting!

I actually don't know how to solve that. It seems like a local network related error. Have you contacted GitHub?

**Comment by gelome** [comment]
it was working fine prior to 01/10/2023.

I've checked my router. checked inidividual cables and the servers all work fine...except for trying to use the scripts

**Comment by gelome** [comment]
how do report to GitHub?

**Comment by enoch85** [comment]
https://docs.github.com/en/support/contacting-github-support

**Comment by gelome** [comment]
its definitely a problem with GitHub....tried changing the DNS...with and without cloudflare or Google...the issue is the same. thanks for pointing me in the right direction. your work is awesome
