### ISSUE TITLE
notify_push fails after each nextcloud update

### ISSUE THREAD

**Issue by Reis-A** [nextcloud/vm#2578]
### Steps To Reproduce

I am not sure if this only happens to me...
 after each nextcloud upgrade for the last couple of months, i have the issue that the notify_push.service fails since the executable in /var/www/nextcloud/apps/notify_push is not an executable anymore. I have to fix it each time with
chmod +x notify_push

I am not sure if this happens because of the Nextcloud VM script or if this normal Nextcloud upgrade behavior... 
 Thx for your help in advance. I  probably installed the app notify_push manually, if that could be the reason for the issue?

### Expected Result

notify_push.service is still running after the upgrade

### Actual Result

chmod +x notify_push has to be entered manually each time, nextcloud is updated

### Build Version

27.1.2

### Environment

By using the scripts

**Comment by enoch85** [comment]
Thanks for reporting!

Then it must be something in your network that changed. Please reinstall it again through the menu script and see if it installs correctly.

We already restart notify_push during upgrade: https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L763-L767

**Comment by Reis-A** [comment]
Thank you for your answer.
 I compared the VM  install script with my manual installation and added now for the executable 
`chmod 770 notify_push `instead of `chmod +x notify_push`.
Doing this, www-data got an additional write privilege.
the next update will tell if this changes anything :)
and if it doesn't work i ll try the install script :)

**Comment by enoch85** [comment]
Please repoen if the isse persist.
