### ISSUE TITLE
VM Import Fails in XCP-NG 

### ISSUE THREAD

**Issue by Alex9001** [nextcloud/vm#2579]
### Steps To Reproduce

1. install xcp-ng
2. import into xcp-ng the 40GB .ova vm from https://www.hanssonit.se/nextcloud-vm/
3. start the vm

### Expected Result

both testing and standard VM should start

### Actual Result

only testing branch starts. 
27.0.1 - HUB 5 vm cannot find boot drive.

### Build Version

27.0.1 - HUB 5

### Environment

By downloading the VM

### Environment Details

xcp-ng / xen-orchestra

**Comment by zalonic** [comment]
HI @Alex9001,

The OVA images assume the second disk is an `sdb` disk type.
XCP-NG is a fork of Xenserver which use `xvbd` as it's disk type. You'll need to install the VM manually using [this guide](https://docs.hanssonit.se/s/bj0vl1ihv0jgrmfm08j0/build-your-own/d/bj0vl4ahv0jgrmfm0950/nextcloud-vm).

**Comment by enoch85** [comment]
Also check [this](https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=bnhd4j2hv0jgro9ohd3g) out.
