### ISSUE TITLE
mount /mnt/ncdata not working after upgrade kernel

### ISSUE THREAD

**Issue by Netmees** [nextcloud/vm#2580]
### Steps To Reproduce

4. Click on '...'

### Expected Result

get normal access to nextcloud

### Actual Result

boot error.... unable to mount /mnt/ncdata

/sbin/modprobe zfs
 modprobe: ERROR: could not insert 'zfs': Key was rejected by service

trying to add support for new kernel 

dpkg-reconfigure zfs-dkms

getting error....

i had modified the grub to access to the menu and then choose last working kernel -> linux-image-5.15.0-25-generic

and the works ok....

### Build Version

27.1.2

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Thanks for posting!

Which Hypervisor is this?

**Comment by Netmees** [comment]
its KVM... but i think the proble its that the new kernel linux-image-5.15.0-8x it still cant handle zfs modprobe modules...

**Comment by enoch85** [comment]
Aah, yes that would explain it. 

Please revert to backup and wait. :)

**Comment by Netmees** [comment]
haha thast what i did... there its allways problems with automatic updates with everything.... nothing is done specting changes in the systen ;-)

**Comment by enoch85** [comment]
> haha thast what i did... there its allways problems with automatic updates with everything.... nothing is done specting changes in the systen ;-)

That's why I prefer manual updates. Automatic updates are nice if you are 99 (you can never be 100)% sure that everything will be alright. We try to make it as stable as possible, but kernels, and OS, and other dependencies are out of our control.

**Comment by enoch85** [comment]
Closing since it out of our control.
