### ISSUE TITLE
Script fails to install ElasticSearch : Elsaticsearch version tag is not available 

### ISSUE THREAD

**Issue by davros123** [nextcloud/vm#2581]
### Steps To Reproduce

Installed a few VM from the latest OVA (40GB_Nextcloud-VM_www.hanssonit.se.ova)
Select install Elasticsearch ininstall options

### Expected Result

It installs :) 

### Actual Result

![image](https://github.com/nextcloud/vm/assets/2758224/132dbe5d-d85a-42d9-86de-391931255136)

### Screenshots, Videos, or Pastebins

![image](https://github.com/nextcloud/vm/assets/2758224/7e9c01bb-e6d5-4004-bc9b-5163901cd0b6)

### Build Version

27

### Environment

By downloading the VM

### Environment Details

Ubuntu - as per 40GB_Nextcloud-VM_www.hanssonit.se.ova

**Comment by enoch85** [comment]
Thanks! Will have a look!

**Comment by enoch85** [comment]
Can you please try again? Just tested and it seems to work for me.

**Comment by enoch85** [comment]
Tested 4 times today, cannot reproduce.

**Comment by davros123** [comment]
Thanks - not sure the issues was - but I did a fresh install and it worked. So all good

**Comment by enoch85** [comment]
Thanks for confirming
