### ISSUE TITLE
Nextcloud 26 and 27 appliance VMs do not boot on Proxmox

### ISSUE THREAD

**Issue by flostyen** [nextcloud/vm#2582]
### Steps To Reproduce

1. Either you you use `qmrestore vzdump-qemu-999-2023_08_08-17_02_30.vma.zst 105 -storage local-lvm` to import Nextcloud VM v27 (also does not work with v26)...
2. ..or you use `qm importovf 105 40GB_Nextcloud-VM_www.hanssonit.se.ovf local-lvm` 
3. Optionally you may change UEFI to SeaBIOS (and also may remove EFI & TPM disk) - all wont change anything

### Expected Result

VM starts correctly as it did in the past :)

### Actual Result

VM is stuck at "Booting from Hard Disk ..."

### Screenshots, Videos, or Pastebins

![2023-11-02 23_43_52-QEMU (Nextcloud-VM-www hanssonit se) - noVNC – Mozilla Firefox](https://github.com/nextcloud/vm/assets/38085481/c44b6e4b-5dc5-45dc-9109-45bf90decb7a)

### Additional Context

The checksum shown in the readme text file is not correct: https://download.kafit.se/s/dnkWptz8AK4JZDM?dir=undefined&path=%2F27.0.1%20-%20HUB%205&openfile=26538 
I downloaded it 3x and I think there is a mistake in your readme text file.

Also I checked it with Nextcloud VM v26 too to make sure its not the downloaded file and the issue remains the same.

### Build Version

v27 and v26

### Environment

By downloading the VM

### Environment Details

Proxmox 6.4.15
Nextcloud VM v27 (https://download.kafit.se/s/dnkWptz8AK4JZDM?path=%2F27.0.1%20-%20HUB%205)
Nextcloud VM v26 (https://download.kafit.se/s/YmPiD362tBjxKTL?path=%2F26.0.0%20-%20HUB%204)

**Comment by enoch85** [comment]
Thanks for reporting!

Is this on Proxmox 7 or 8?

**Comment by flostyen** [comment]
> Thanks for reporting!
> 
> Is this on Proxmox 7 or 8?

I tried it with Proxmox 7.4-17 and Proxmox 6.4.15.

**Comment by enoch85** [comment]
Thanks for confirming, then everything is in order.

You should also consider upgrading to Proxmox 8.0.4, 6 is a bit old by now. :)

![Screenshot_2023-11-03-12-27-41-43_3aea4af51f236e4932235fdada7d1643](https://github.com/nextcloud/vm/assets/4511254/57d7d2b9-bdd9-4a7f-bf8c-bbc103e71c8a)

**Comment by enoch85** [comment]
Please also note that the VM is made with ZFS.

**Comment by flostyen** [comment]
> Thanks for confirming, then everything is in order.
> 
> You should also consider upgrading to Proxmox 8.0.4, 6 is a bit old by now. :)
> 
> ![Screenshot_2023-11-03-12-27-41-43_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/4511254/280263363-57d7d2b9-bdd9-4a7f-bf8c-bbc103e71c8a.jpg)

Have you updated the md5 checksum? I guess it is wrong in the readme.

You are correct - the solution to this issue was updating proxmox to version 7 :-)
