### ISSUE TITLE
Use APCu for local caching and Redis for file locking in VM script

### ISSUE THREAD

**Issue by n0one42** [nextcloud/vm#2584]
## Description
The current VM script for setting up Nextcloud configures Redis for all three caching mechanisms (`memcache.local`, `memcache.distributed`, and `memcache.locking`). However, according to the [official Nextcloud documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html), APCu is recommended for local caching due to its performance benefits.

Furthermore, the documentation includes a warning about using Redis for local caching:

```plaintext
Furthermore, you could use Redis for the local cache like so, but it’s not recommended (see warning below):

'memcache.local' => '\OC\Memcache\Redis',

Warning

Using Redis for local cache on a multi-server setup can cause issues. Also, even on a single-server setup, APCu (see section above) should be faster.
```

## Proposed Change
Modify the VM script to use APCu for `memcache.local` and Redis for `memcache.distributed` (if applicable) and `memcache.locking`. This change would align the script with the official recommendations and potentially improve the performance of Nextcloud instances set up using this script.

## Benefits
- Improved performance for local caching operations.
- Reduced resource usage as APCu is more lightweight for local cache.
- Alignment with the official Nextcloud documentation and best practices.

## Potential Drawbacks
- Slightly increased complexity in having two caching mechanisms.

## Script Enhancement for APCu Installation and Configuration

To ensure consistency and automate the process of setting up APCu for `memcache.local`, the following script snippet can be included in the VM script:

```bash
#!/bin/bash

# Get the PHP version
PHP_VERSION=$(php -v | head -n 1 | cut -d ' ' -f 2 | cut -d '.' -f 1,2)

# Install APCu
sudo apt-get install "php${PHP_VERSION}-apcu"

# Backup the original apcu.ini file
sudo cp "/etc/php/${PHP_VERSION}/mods-available/apcu.ini" "/etc/php/${PHP_VERSION}/mods-available/apcu.ini.bak"

# Enable APCu for CLI
sudo sed -i '$aapc.enable_cli=1' "/etc/php/${PHP_VERSION}/mods-available/apcu.ini"

# Modify the Nextcloud configuration to use APCu for local caching
NEXTCLOUD_CONFIG='/var/www/nextcloud/config/config.php'
sudo sed -i "/'memcache.local'/c\  'memcache.local' => '\\\\\\\\OC\\\\\\\\Memcache\\\\\\\\APCu'," "$NEXTCLOUD_CONFIG"

# Restart Apache to apply changes
sudo systemctl restart apache2
```
This script enhancement will automatically detect the installed PHP version, install APCu, configure it to work with the CLI, and set APCu as the memcache.local in Nextcloud's config.php. This aligns with the recommended best practices and simplifies the setup process.

**Comment by enoch85** [comment]
Thanks for your suggestion. We already did this in the past, 2 times actually. Both times it ended up in unstable servers, due to bugs with Nextcloud and APCu.

So we made the decision to **not** use APCu. The gains are milliseconds, and it's not worth the potential usability issues. Redis has been rock solid for several years, and we choose stability over performance.

https://github.com/nextcloud/vm/blob/master/CHANGELOG.md#small-changelog-9

**Comment by n0one42** [comment]
Thanks for the quick response. I totally get where you're coming from, choosing stability over a small bump in performance makes a lot of sense. 
I was just a bit thrown off by the warning in the Nextcloud docs about using Redis for local cache. It seemed like they were suggesting it might cause problems, especially on multi-server setups but also even on a single-server setup.

**Comment by enoch85** [comment]
The documentation isn't always correct. In fact, some things are even wrong in there since they weren't updated for a long time. You know, it's always documentation that lags behind. :)
