### ISSUE TITLE
Implement Certbot DNS Challenge for Cloudflare Using API Tokens for Enhanced Security

### ISSUE THREAD

**Issue by n0one42** [nextcloud/vm#2585]
## Description
The current VM script utilizes Certbot for SSL certificate generation via the DNS TXT record method. While this method is effective, it may require broad access to DNS provider accounts, which could pose a security risk. To enhance security and ease of use, I propose implementing Certbot's DNS challenge using API tokens, specifically with the Cloudflare DNS plugin as an example.

## Proposed Change
Integrate the use of Certbot's DNS plugins that support DNS challenges via API tokens. This would involve adding support for popular DNS providers' plugins, such as [Certbot DNS Cloudflare](https://certbot-dns-cloudflare.readthedocs.io/en/stable/), and enabling users to input their API tokens during the setup process. The API token approach allows for more granular permissions compared to account-wide credentials. For further guidance, the following resources may be helpful:

- [Certbot DNS Cloudflare Documentation](https://certbot-dns-cloudflare.readthedocs.io/en/stable/)
- [Tutorial on Installing Certbot DNS Cloudflare Plugin](https://zoomadmin.com/HowToInstall/UbuntuPackage/python3-certbot-dns-cloudflare)
- [Certbot DNS Cloudflare Snap Package](https://snapcraft.io/install/certbot-dns-cloudflare/ubuntu)

## Benefits
- **Enhanced Security**: API tokens can be restricted to specific domains and limited permissions, reducing the risk if they are compromised.
- **Ease of Automation**: API tokens facilitate the automation of the DNS challenge process, making the renewal of SSL certificates seamless.
- **Best Practices Alignment**: Using API tokens aligns with security best practices by minimizing the permissions and access given to external tools.

## Potential Drawbacks
- **Additional Complexity**: Implementing multiple DNS provider plugins and handling API tokens may introduce additional complexity to the script.
- **Maintenance Overhead**: Keeping the DNS plugins updated and ensuring compatibility with a range of DNS providers could increase maintenance overhead.

**Comment by n0one42** [comment]
I appreciate the suggestion to use the deSEC option for domain/TLS installation. However, I'm a bit puzzled about its advantage in my case. I already own a domain hosted by Cloudflare, and my primary objective is to streamline the SSL certificate generation process for my Nextcloud instance.

Currently, the setup involves manually creating TXT records in the DNS provided by the vm script. What I'm proposing is to utilize the Cloudflare API token method, which automates this process by using an email and token instead of manually inputting TXT records. It's a small shift from the current method.

Could you elaborate on how the deSEC option would be more beneficial in this scenario compared to the automation potential offered by the Cloudflare API token method?

**Comment by enoch85** [comment]
We are partners with deSEC. We are not partners with Cloudflare, and providing such an option would suggest that we actually recommend using Cloudflare - which we don't.

deSEC is the perfect choice for newbies just wanting their cloud up and running. No domain needed, no TLS needed - both are provided via the script, and TLS happens over DNS. deSECs API are golden!

For more advanced users, well I guess you could manage that on your own. 

You are welcome to provide a PR making it happen though. I'm using Cloudflare myself, but not their DNS, so I'm not against it. I just don't have time to implement a new feature, which in turn also needs to be maintained.
