### ISSUE TITLE
Postgres Password Prompt During Nextcloud VM menu.sh Script Execution

### ISSUE THREAD

**Issue by n0one42** [nextcloud/vm#2592]
It's-a me again..., Mario... :see_no_evil:

#### Issue Description:
My objective was to enable "userns-remap". 
To accomplish this, I used the `menu.sh` script provided with the Nextcloud VM to remove Docker containers for "FullTextSearch" and "Imaginary" with the intention of reinstalling them afterward.

#### Steps to Reproduce:
1. Executed `menu.sh` to remove "FullTextSearch" and "Imaginary" Docker containers.
2. During the process, the script prompted for the PostgreSQL password.

#### Problem:
The script execution went smoothly until it required the PostgreSQL password. I am uncertain where to find or how to retrieve this password. This information wasn't provided in the script documentation or during the initial setup.

#### Question:
Can you provide guidance on where to find the PostgreSQL password required by the script? Is there a default password set during the Nextcloud VM setup, or is there a method to reset or retrieve this password without disrupting the current setup?

Any assistance or direction on this matter would be greatly appreciated.

Thank you in advance.

**Comment by enoch85** [comment]
It seems like you're doing a lot of tweaks to your VM. It *never* happened to me, and there's no reason for it either.

Only thing I can think of is [this](https://github.com/nextcloud/vm/blob/master/apps/fulltextsearch.sh#L55-L59), but then you must have done something to your DB.

**Comment by enoch85** [comment]
Here's how the backup happens: https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L962-L996

**Comment by n0one42** [comment]
This machine is atm "clean" thats said, there were no tweaks done.
What I did was just to install "FullTextSearch" with the menu.sh script and then also with the menu.sh script to uninstall "FullTextSearch". I think, this should also happen to you if you do this.

**Comment by n0one42** [comment]
And yeah, now that I've seen what the script does, I could totally handle dropping those tables and doing the deletes with the `nextcloud_db_user`. Still curious though, where is that postgres password set?

**Comment by n0one42** [comment]
I was also able to import my docker structure and also `userns-remap` with my ansible tasks. The containers created from the main.sh are still working as it should and I am happy. Otherwise, its anyway my fault changing such stuff.
About the postgres, I will make a note and test it if needed in the future.
Thanks again for your time.
