### ISSUE TITLE
Update to Nextcloud 27.1.4 - error "sudo -u www-data php /var/www/nextcloud/occ maintenance:repair failed"

### ISSUE THREAD

**Issue by Clumpton** [nextcloud/vm#2596]
### Steps To Reproduce

1. Run 'sudo bash /var/scripts/menu.sh' --> Update Nextcloud
2. Wait

### Expected Result

Nextcloud is updated without errrors

### Actual Result

1. See several error messages "   - ERROR: searchBody is not a valid attribute" go past
2. Receive error message ""sudo -u www-data php /var/www/nextcloud/occ maintenance:repair failed"

### Build Version

Was 27.1.3, appears to have updated to 27.1.4

### Environment

By downloading the VM

### Environment Details

Running in a VirtualBox VM on an Intel NAS (Asustor)

**Comment by enoch85** [comment]
Thanks for reporting!

We generally don't recommend Virtualbox. With that said, have you tried the latest VM? Same issues on that one?

**Comment by Clumpton** [comment]
> We generally don't recommend Virtualbox. With that said, have you tried the latest VM? Same issues on that one?
Seems to run fine in VirtualBox - not a great load on the server though, just a family setup.
27.1.4 runs update.sh without the above errors.
Update to 28.0.0 has been successful. 
Looks like it was fixed in 27.1.4.
