### ISSUE TITLE
GUI's "Apps" page throws Internal Server Error

### ISSUE THREAD

**Issue by yazdishn** [nextcloud/vm#2597]
### Steps To Reproduce

Run VM, mount NFS share as data directory, Follow VM installation script, Log in with the admin account, navigate to drop down menu in GUI > +Apps to open the app page

### Expected Result

See a page full of apps

### Actual Result

Internal Server Error message with the default Nextcloud theme

### Screenshots, Videos, or Pastebins

![Screenshot from 2023-11-27 00-07-02](https://github.com/nextcloud/vm/assets/152157783/34b67d94-547e-427a-a422-a4879d53d302)

### Additional Context

I have installed the VM on proxmox using the script. Major tweak is that I have substituted the 100 GB default virtual disk with a NFS share from a local NAS following this user's documented steps:

https://help.nextcloud.com/t/tutorial-nc-vm-data-directory-nfs-integration/109252

I have not restored any backup or settings from another Nextcloud instance. After setting up the NFS share as the NC's data directory, I followed the installation script which completed successfully. I then copied some files under the Files directory and used occ scan command to add them to NC's db. At present everything in the web GUI works perfectly except the Apps page.

### Build Version

Nextcloud 27.1.4.1

### Environment

By downloading the VM

### Environment Details

The VM runs on Proxmox VE 8.0.4

**Comment by enoch85** [comment]
To much custom on this server it seems. If you like you can reach out and get some hands on support. 

Other than that, keep it small, and when that works 100%, *then* increase/add something else. Recognize is super heavy, and honestly not super stable.

**Comment by yazdishn** [comment]
It turns out it was not Recognize's fault, because the same issue happened without it. I had initiated the installer script after switching the ncdata to a mounted nfs share and creating an empty .ocdata. I repeated the all the tweaks but this time restored the pre-install contents of ncdata directory before initiating the installer and the problem is resolved. I'm closing this, thank you!
