### ISSUE TITLE
VM cannot be imported into Proxmox 8

### ISSUE THREAD

**Issue by cjohn001** [nextcloud/vm#2598]
### Steps To Reproduce

I downloaded the most recent VM image from here

https://download.kafit.se/s/YmPiD362tBjxKTL?path=%2F27.0.1%20-%20HUB%205

and tried to import it, resulting in the following error

Failed to extract config from VMA archive: zstd: /var/lib/vz/dump/vzdump-qemu-999-2023_08_08-17_02_30.vma.zst: unsupported format (500)

When trying to show configuration in Proxmox:
ERROR: couldn't determine archive info from '/var/lib/vz/dump/vzdump.vma.zst' (500)

A side note, I downloaded the VM several times and observed that the MD5 sum of the downloaded images was always different.

### Expected Result

It should be possible to import the vm without errors

### Actual Result

not possible to import vm

### Build Version

vzdump-qemu-999-2023_08_08-17_02_30.vma.zst

### Environment

By downloading the VM

### Environment Details

Proxmox V8.0.4

**Comment by enoch85** [comment]
Hi, 

Thanks for reporting. 

Please try the latest VM: https://download.kafit.se/s/YmPiD362tBjxKTL
