### ISSUE TITLE
No bootable Medium at VirtualBox 7

### ISSUE THREAD

**Issue by 19newbie87** [nextcloud/vm#2599]
### Steps To Reproduce

Import Appliance "1TB_Nextcloud-VM_www.hanssonit.se" (payment from 19.11.2023)

![image](https://github.com/nextcloud/vm/assets/97949340/3f39deb8-2130-47f9-a025-63c65a94c729)

```
Ubuntu Server 22.04 (minimal) LTS 64-bit
Apache 2.4
PostgreSQL 14
PHP-FPM 8.1
Linux Kernel: 5.15
[Redis Memcache](https://docs.nextcloud.com/server/16/admin_manual/configuration_server/caching_configuration.html#id2) (latest stable version from [PECL](https://pecl.php.net/package/redis))
[PHP-igbinary](https://github.com/igbinary/igbinary) (latest stable version from [PECL](https://pecl.php.net/package/igbinary)
[PHP-smbclient](https://github.com/eduardok/libsmbclient-php) (latest stable version from [PECL](https://pecl.php.net/package/smbclient))
Nextcloud Server [Latest](http://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=W7D3quPiqQz3_MsE)
LDAP (Nextcloud app)
SMB-ready
Collabora Online / Onlyoffice
Nextcloud Talk
DATA disk: 1000 GB
OS disk: 40 GB
```

Use the Pre-konfigurated Setup
Start Virtual machine

### Expected Result

Booting Ubuntu. 

### Actual Result

No bootable Medium found. 

### Screenshots, Videos, or Pastebins

![image](https://github.com/nextcloud/vm/assets/97949340/da292db2-3f81-4929-8243-2759e33fdb26)

### Additional Context

I tested the same procedure with the  version from 2022:

![image](https://github.com/nextcloud/vm/assets/97949340/5700945a-7ddc-4057-ae51-e497c5a5111c)

No Errors, it works. I never had problems with Virtual Box before. I bought the new next cloud version from hanssonit, because I could not upgrade php without errors... 

### Build Version

I could never boot, it should be Version 

### Environment

By using the scripts

### Environment Details

![image](https://github.com/nextcloud/vm/assets/97949340/585bbf6d-f110-4e3b-ba71-af5ba1fe695b)

![image](https://github.com/nextcloud/vm/assets/97949340/ab48c8e9-f9c4-4920-99f8-025030fa4590)

![image](https://github.com/nextcloud/vm/assets/97949340/dfe4b533-1afd-4748-aca1-8a71895240aa)

**Comment by 19newbie87** [comment]
I use the latst Version of VirtualBox. I use virtualbox for some years... for me is that not a real solution. I need to migrate my virtausl disks vom VirtualBox to VMware.

**Comment by 19newbie87** [comment]
What is the Solution for virtual Box?

**Comment by 19newbie87** [comment]
> Referen

By the way, i tested: booting with VMWare is possible.

**Comment by 19newbie87** [comment]
> We raised the minimum version in later versions of the VM. Don't know the latest version of Virtualbox, but please try to mount it in latest VMware player, it's free: https://www.vmware.com/se/products/workstation-player/workstation-player-evaluation.html

By the way, i tested: booting with VMWare is possible.

**Comment by enoch85** [comment]
We don't develop on VirtualBox, we develop on VMware. Also, please read the docs: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7Du9uPiqQz3_Mr1/nextcloud-vm-machine-configuration?currentPageId=bhjtk3ahv0jgro7odn50

It should be compatible, but we also got several reports about bugs like this. 

If (or when) I have time, I will install this on VirtualBox myself just to see. Until then, try extracting the .vmdk one by one and import it manually - disk by disk.

**Comment by 19newbie87** [comment]
Hello, the best solution for me would be a shared folder with the host. When I enable shared folder in the VMware options, no shared folder is mounted on Ubuntu... 

I installed Gnome, only to show the problem:

At virtual box was never a problem with a shared folder ... this is all  i Want. A stable and highly available shared folder...

**Comment by enoch85** [comment]
Mount it as NFS or something instead... That's also an option. I never worked with shared folders before so I don't know how they work.

**Comment by 19newbie87** [comment]
After three weeks, here is the solution for a stable shared Folder:

"Most other answers are outdated. For Ubuntu 18.04 (or recent Debian distros), try:

sudo vmhgfs-fuse .host:/ /mnt/hgfs/ -o allow_other -o uid=1000
If the hgfs directory doesn't exist, try:

sudo vmhgfs-fuse .host:/ /mnt/ -o allow_other -o uid=1000
You may have use a specific folder instead of .host:/. In that case you can find out the share's name with vmware-hgfsclient. For example:

$ vmware-hgfsclient
my-shared-folder
$ sudo vmhgfs-fuse .host:/my-shared-folder /mnt/hgfs/ -o allow_other -o uid=1000
If you want them mounted on startup, update /etc/fstab with the following:

# Use shared folders between VMWare guest and host
.host:/    /mnt/hgfs/    fuse.vmhgfs-fuse    defaults,allow_other,uid=1000     0    0
I choose to mount them on demand and have them ignored by sudo mount -a and the such with the noauto option, because I noticed the shares have an impact on VM performance.

Requirements
Software requirements may require installing the following tools beforehand:

sudo apt-get install open-vm-tools open-vm-tools-desktop
Others have claimed the following are required:

sudo apt-get install build-essential module-assistant \
  linux-headers-virtual linux-image-virtual && dpkg-reconfigure open-vm-tools 

..."

Source: [https://askubuntu.com/questions/29284/how-do-i-mount-shared-folders-in-ubuntu-using-vmware-tools?answertab=createdasc#tab-top](url)

**Comment by 19newbie87** [comment]
After three weeks, here is the solution for a stable shared Folder:

"Most other answers are outdated. For Ubuntu 18.04 (or recent Debian distros), try:

sudo vmhgfs-fuse .host:/ /mnt/hgfs/ -o allow_other -o uid=1000
If the hgfs directory doesn't exist, try:

sudo vmhgfs-fuse .host:/ /mnt/ -o allow_other -o uid=1000
You may have use a specific folder instead of .host:/. In that case you can find out the share's name with vmware-hgfsclient. For example:

$ vmware-hgfsclient
my-shared-folder
$ sudo vmhgfs-fuse .host:/my-shared-folder /mnt/hgfs/ -o allow_other -o uid=1000
If you want them mounted on startup, update /etc/fstab with the following:

# Use shared folders between VMWare guest and host
.host:/    /mnt/hgfs/    fuse.vmhgfs-fuse    defaults,allow_other,uid=1000     0    0
I choose to mount them on demand and have them ignored by sudo mount -a and the such with the noauto option, because I noticed the shares have an impact on VM performance.

Requirements
Software requirements may require installing the following tools beforehand:

sudo apt-get install open-vm-tools open-vm-tools-desktop
Others have claimed the following are required:

sudo apt-get install build-essential module-assistant \
  linux-headers-virtual linux-image-virtual && dpkg-reconfigure open-vm-tools 

..."

Source: [https://askubuntu.com/questions/29284/how-do-i-mount-shared-folders-in-ubuntu-using-vmware-tools?answertab=createdasc#tab-top](url)

**Comment by enoch85** [comment]
Thanks! Will add it in the docs. 👍🏼
