### ISSUE TITLE
Fresh install error in collabora.sh

### ISSUE THREAD

**Issue by aaaskew** [nextcloud/vm#260]
## Steps to reproduce
1. Install Nextcloud VM and install all options except for Collabora
2. Download collabora.sh and run

## Expected behaviour
Collabora installed ok

## Actual behaviour

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
wget -q https://github.com/nextcloud/richdocuments/releases/download/1.12.32/richdocuments.tar.gz -P /var/www/nextcloud/apps failed

404 File not found

Going through the web pages I get this link:

https://github.com/nextcloud/richdocuments/files/1054122/richdocuments.tar.gz

## Server configuration

**Server version:** 12.0.0

**VM version** Released OVA 12

**Updated from an older installed version or fresh install:** Fresh Install

## Network
**Do you use DHCP?** No

**Is port 80 and/or 443 open?** 443 open

## Logs / Screenshots

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
wget -q https://github.com/nextcloud/richdocuments/releases/download/1.12.32/richdocuments.tar.gz -P /var/www/nextcloud/apps failed

**Comment by aaaskew** [comment]
A side note:

Looking at the apps directory, the collabora.sh script does a

chown -R www-data:www-data $NCPATH/apps

command.  This also changes passman and and spreedme.  This is probably a good thing but maybe this command should be in the other scripts too?

drwxrwxr-x 13     1001     1001 4096 May  6 18:15 passman
drwxrwxr-x 20 root     root     4096 May 29 11:34 spreedme

**Comment by aaaskew** [comment]
Another note:

I manually ran all commands with the richdocuments.tar.gz I downloaded myself to complete the installation.

On the web interface I see in the logs

Trusted domain error. "10.0.2.2" tried to access using "office.nextclouddomain..." as host.

Looking in config.php I see the nextcloud domain twice
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '10.0.2.15',
    2 => 'nextcloud.nextclouddomain...',
    3 => 'nextcloud.nextclouddomain...',
  ),

**Comment by enoch85** [comment]
> chown -R www-data:www-data $NCPATH/apps

Good point. 

> Trusted domain error. "10.0.2.2" tried to access using "office.nextclouddomain..." as host.

That it's double doesn't change anything. But you have to add the 10.0.2.2 IP to be able to access your domain. Running Let's Encrypt script will solve this.

> I manually ran all commands with the richdocuments.tar.gz I downloaded myself to complete the installation.

Yes, that's the correct way to do it. Collabora is installed and the last part is just enabling the app. As you can see this is not a script issue, rather a release issue since the release name i inconsistent. 

I'll close this is this is not a VM issue. Please write in the linked issue to get @timar attention. Thanks!

**Comment by aaaskew** [comment]
Sorry to comment again but I hope I have this right.  According to https://help.nextcloud.com/t/adding-a-new-trusted-domain/26 the Trusted domains should 'specify every domain at which your Nextcloud can be accessed'.

So if I install Collabora the list should look like:
- Localhost
- IP address of Nextcloud VM
- FQDN of Nextcloud VM
- FQDN of Collabora proxy ?

The 10.0.2.2 from the previous comment is the source address which is accessing Nextcloud Apache rather than the Nextcloud which is at 10.0.2.15.

I would think that installing collabora.sh would call let's encrypt script and it would add the collaboration office FQDN to the list rather than the nextcloud FQDN a second time?  Sorry I have not looked at where this is being done yet.

**Comment by enoch85** [comment]
@aaaskew I'll add trusted domain to the Collabora script. Thanks for the heads up.

**Comment by enoch85** [comment]
OK, it's done.
