### ISSUE TITLE
[Documentation]: Differences between "Integrated" and "Docker" installs for docserver are confusing/unclear

### ISSUE THREAD

**Issue by pjrobertson** [nextcloud/vm#2603]
When using the "Install additional apps > DocumentServer" option of the menu.sh script, you get the following 4 options:

```
Collabora (Docker)      (Online editing - Extra Subdomain required)    
Collabora (Integrated)  (Online editing - No Subdomain required)
OnlyOffice (Docker)     (Online editing - Extra Subdomain required)
OnlyOffice (Integrated) (Online editing - No Subdomain required) 
```

It is unclear what the differences between the integrated and docker versions are, and also the differences between Collabora and OnlyOffice.

I suggest:
1. Providing documentation listing out the differences
2. Providing a "(Recommended)" text next to the recommended version

If someone can list out the differences here, I'd happily write it up into a doc.

From my searches/guesses:
1. Collabora is better supported by Nextcloud so is the recommended version (??)
2. I'd have thought 'integrated' would be preferred, since it would install the server natively, but I checked and it actually installs an 'appimage' file for collabora, which might be heavier on resources (?), so perhaps docker is recommended, unless you don't have an additional subdomain?

Thanks!

**Comment by enoch85** [comment]
Collabora (Docker)      (Online editing - Extra Subdomain required)    = Collabora with Docker
Collabora (Integrated)  (Online editing - No Subdomain required)     = Collabora from App store
OnlyOffice (Docker)     (Online editing - Extra Subdomain required)   = Collabora with Docker
OnlyOffice (Integrated) (Online editing - No Subdomain required)     = Collabora from App store

We recommend using Docker since it's more stable, and can handle more users. And yes, Collabora is also the way to go of the two of them. Onlyoffice is developed in Russia...

**Comment by enoch85** [comment]
Added a partial fix. If you want to help, please post your documentation text here, and we'll add it.

Thanks!

**Comment by pjrobertson** [comment]
Great, thank you for clarifying and the quick response! I was thinking something in either the [install](https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm) instructions or the [FAQ](https://docs.hanssonit.se/s/bj101nihv0jgrmfm09f0/faq/d/bj101pihv0jgrmfm0a10/nextcloud-vm?currentPageId=bj101sqhv0jgrmfm0a1g) would also be very helpful. Here's my suggestion:


**Q: What is the difference between each of the DocumentServer (office) installation options?**
A: The Nextcloud-vm scripts currently support 4 ways to install a document server on your nextcloud install. First, you need to decide what backend document server you with to use: Collabora or OnlyOffice. Collabora is the recommended option by the Nextcloud-vm team. Then you need to decide if you wish to install the document server as a 'docker' install or 'integrated'. Integrated may be easier to install and should work well for up to 3-4 users, but may not be as scaleable as the Docker install. The Nextcloud-vm team recommends the Docker install. For more information on the different options, see the 'Nextcloud Office' settings page in Your Nextcloud > Administration > Office.

**Comment by enoch85** [comment]
https://docs.hanssonit.se/s/bj101nihv0jgrmfm09f0/faq/d/bj101pihv0jgrmfm0a10/nextcloud-vm
