### ISSUE TITLE
Can't start the first setup.

### ISSUE THREAD

**Issue by golden-mask** [nextcloud/vm#2605]
### Steps To Reproduce

1. start the VMWare 
2. open the nextcloud 
3. inter the username and password
4. reenter the password when prompted 
5. the network check is Ok and I get green Online result

### Expected Result

startup configuration script starts normally.

### Actual Result

Script failed to download. please run : sudo curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/menu/startup_configuration.sh and try again.

### Build Version

VMware / VirtualBox (.OVA)  Nextcloud VM Pre-installed – 40 GB

### Environment

By using the scripts

### Environment Details

Operating system Win11
Vmware workstation pro 17

**Comment by enoch85** [comment]
Do you have country block enabled? Try disabling that and see what happens. :)

**Comment by golden-mask** [comment]
> Do you have country block enabled? Try disabling that and see what happens. :)

no I don't.

I found that the problem is my connection. I am using a mobile hotspot from my GSM internet.
when the connection is interrupted he VM can't reconnect to internet I have to close the VM and re-open it
and since am in the first setup some automated steps are not completed.
The best way to delete the VM Machin and start the install again. It's working for now.
Thx for help.
