### ISSUE TITLE
OVA deployment in vsphere 8 fails with error

### ISSUE THREAD

**Issue by agonzalezm** [nextcloud/vm#2607]
### Steps To Reproduce

what is wrong wit this?

vsphere 8

Wen downloading OVA 
![image](https://github.com/nextcloud/vm/assets/2251991/4d5c19a3-2ed4-42e8-b90c-74509ae08456)

When using URL
![image](https://github.com/nextcloud/vm/assets/2251991/3c327a87-8816-4d03-8fe9-477bd236e93e)

### Expected Result

deploy OVA in vsphere 8

### Actual Result

The provided manifest file is invalid: Invalid OVF checksum algorithm: SHA1 .

### Build Version

latetst

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Thanks! Will have a look at this when time allows. Meanwhile, please extract the OVA and import the VMDKs.

**Comment by agonzalezm** [comment]
it doesnt work neither

**Comment by agonzalezm** [comment]
it doesnt work neither and looks like the vdmk is thick provisioned incorrect

![image](https://github.com/nextcloud/vm/assets/2251991/e7eff47f-d1d6-46f7-8254-ac12dbcdcee4)

**Comment by enoch85** [comment]
All our vMs are thin provisioned. Strange that it's thick for you.

If thick the VM file would be 1 TB once extracted, I guess it's not?

**Comment by agonzalezm** [comment]
when extracted is not 1tb , any update on this when will be fix the import in vsphere?

**Comment by enoch85** [comment]
I don't know when I have time to setup a new vsphere 8 environment to test. Sorry.

**Comment by enoch85** [comment]
The file must be corrupted during download. Please try to download it again.

If it fails, please send an email and I'll send you a direct link.

**Comment by enoch85** [comment]
But wait! That's AIO, not this VM.

Try this VM instead: https://www.hanssonit.se/nextcloud-vm/

**Comment by enoch85** [comment]
The background is a long story, but the VM was made before the AIO, and the AIO dev worked with the VM. Then it was decided that Nextcloud wanted "their own" thing, so the dev from the VM was hired by Nextcloud and AIO was born.

The concept is the same, much like Pepsi and Coca Cola. The main difference is that AIO is Docker based, and the VM is not.

**Comment by enoch85** [comment]
Also, we only develop the latest for release and we don't save releases except for the Proxmox VM.

You can build it yourself though by downloading the released zip or tar and follow the build instructions, basically run the install script in a clean Ubuntu server 22.04

**Comment by enoch85** [comment]
Tested and works on Vsphere 8. Sorry it took so long.

![Image](https://github.com/user-attachments/assets/9a9d3a1f-7476-484e-9294-ace61edc538c)
