### ISSUE TITLE
Boolean flag missing

### ISSUE THREAD

**Issue by pboguslawski** [nextcloud/vm#2608]
`--type=boolean` should be added to 3 commands in https://github.com/nextcloud/vm/blob/386118f3baa2d331cee6664587ada6d8fcc12166/addons/smtp-mail.sh#L155 - without it string values are set and don't work correctly (tested in v28).

**Comment by enoch85** [comment]
Thanks for your advice!

Could you please add a PR? We'll merge it after review

**Comment by pboguslawski** [comment]
> Could you please add a PR? We'll merge it after review

Don't see license statement in https://github.com/nextcloud/vm/blob/master/addons/smtp-mail.sh that allows modification so won't touch it until it's clarified.

**Comment by enoch85** [comment]
You're cleared! The whole repo is under [this license](https://github.com/nextcloud/vm/blob/master/LICENSE).

**Comment by pboguslawski** [comment]
If  https://github.com/nextcloud/vm/blob/master/addons/smtp-mail.sh is GPLv3 also then [should contain license info](https://github.com/nextcloud/vm/blob/386118f3baa2d331cee6664587ada6d8fcc12166/LICENSE#L629).
