### ISSUE TITLE
Could not boot files_inotify: Could not resolve dispatcher! Class "dispatcher" does not exist - new since recent NC update

### ISSUE THREAD

**Issue by git-kick** [nextcloud/vm#2613]
### Steps To Reproduce

1. Start Nextcloud -  [Nextcloud Hub 7](https://nextcloud.com/) (28.0.1)
2. Observe Logs and Notifications

### Expected Result

No problems reported concerning iNotify - like up to a recent update (1-2 months ago)

### Actual Result

nextcloud.log has many many entries like
`Could not boot files_inotify: Could not resolve dispatcher! Class "dispatcher" does not exist`

files_inotify.log says:
`iNotify starts in 120 seconds
Mount of type "Local" does not support active update notifications
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ files_external:notify -v 13 failed
Posting notification to users that are admins, this might take a while...
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to: ...`

### Additional Context

I am not aware of any configuration changes since the tie when it worked smoothly. I only updated the Nextcloud VM.

There is a similar open [issue ](https://github.com/icewind1991/files_inotify/issues/34) for files_inotify.

### Build Version

Nextcloud Hub 7 (28.0.1)

### Environment

By using the scripts

### Environment Details

- Ubuntu 22.04.3 LTS
- PHP 8.1.2
- Hyper-V on Windows 10 22H2
- AMD Ryzen 5 PRO 5650GE

**Comment by enoch85** [comment]
Please try upgrading to 28.0.2. We don't touch the plugin, just present it. Nothing to do here- >> Closing.
