### ISSUE TITLE
Unable to update Nextcloud instance su

### ISSUE THREAD

**Issue by benhalluk** [nextcloud/vm#2614]
### Steps To Reproduce

1. Log into VM via SSH as ncadmin
2. cd /var/scripts
3. sudo ./menu.sh

### Expected Result

Script should check the network connection to github and go to the Nextcloud installer/update menu

### Actual Result

Running the main menu script...
Testing if network is OK...
Checking connection...
curl didn't produce a 200 status, is github.com reachable?
Waiting for network to restart...
Checking connection...

### Screenshots, Videos, or Pastebins

<img width="681" alt="Screenshot 2024-02-06 at 09 36 39" src="https://github.com/nextcloud/vm/assets/3511962/5ca44d8a-b94e-4629-b37b-128459a247dd">

### Additional Context

I have this issue with my existing VM set up, and the newly downloaded VM as of 2 days ago.

VM is on my main network, no NAT etc.

Tested both DHCP and Static assigned IP's with my local router IP for DNS and directly using Google.

An nslookup confirms I can both resolve and see github and external web sites.

### Build Version

27.0.2

### Environment

By downloading the VM

### Environment Details

VMware vSphere 8

**Comment by enoch85** [comment]
This sounds to me like a local DNS issue.

![1 FHMRtwmo71YhrJihYwIEZQ](https://github.com/nextcloud/vm/assets/4511254/4796bffc-21db-4f0d-b7cb-af97c43155d1)

**Comment by linus9167** [comment]
Hi, I've the same issue. When I set my internet parameters, the script say that there is an error on line 503. The script is blocked to this section and don't go on.

Best regards
