### ISSUE TITLE
Restoring the VM on Proxmox VE 8.1.4

### ISSUE THREAD

**Issue by lemonistas** [nextcloud/vm#2615]
### Steps To Reproduce

I tried to restore the vm dump on my Proxmox VE 8.1.4 and got the following error message: "error before or during data restore, some or all disks were not completely restored. VM 106 state is NOT cleaned up.
ERROR: couldn't determine archive info from .."

I don't know if it is connected with my storage being on lvm rather than ZFS but I unfortunately don't know how to convert the VM to the proper format. So in the end it might be a fault on my side.

### Expected Result

VM can be restored and converted to LVM

### Actual Result

erroremessage see above

### Build Version

28

### Environment

By downloading the VM

### Environment Details

Proxmox VE 8.1.4 on LVM

**Comment by enoch85** [comment]
It's made for ZFS. 

Create a datastore with ZFS and import it. Please report back. ✅

**Comment by lemonistas** [comment]
Thank you for your reply. In the meantime, I had created a datastore with ZFS but apparently the archive I initially downloaded was corrupted. After re-downloading I could restore the VM to the ZFS storage and then simply clone it to the lvm storage. So apparently my first download got corrupted.
