### ISSUE TITLE
Spamhaus Script Update URLS

### ISSUE THREAD

**Issue by Antwony169** [nextcloud/vm#2616]
### Steps To Reproduce

This is a simple bug fix. Spamhaus renamed the list from .lasso to .txt. Simply fix the spamhaus-drop.sh $URLS in static/spamhaus-drop.txt (/var/scripts/spamhaus-drop.sh)

1. wget https://www.spamhaus.org/drop/drop.lasso
2. wget https://www.spamhaus.org/drop/edrop.lasso

### Expected Result

--2024-03-06 12:23:30--  https://www.spamhaus.org/drop/drop.txt
Resolving www.spamhaus.org (www.spamhaus.org)... 104.16.198.238, 104.16.199.238
Connecting to www.spamhaus.org (www.spamhaus.org)|104.16.198.238|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘drop.txt’
2024-03-06 12:23:30 (7.24 MB/s) - ‘drop.txt’ saved [27467]

### Actual Result

--2024-03-06 09:03:38--  https://www.spamhaus.org/drop/drop.lasso
Resolving www.spamhaus.org (www.spamhaus.org)... 104.16.198.238, 104.16.199.238
Connecting to www.spamhaus.org (www.spamhaus.org)|104.16.198.238|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /404.html [following]
--2024-03-06 09:03:38--  https://www.spamhaus.org/404.html
Reusing existing connection to www.spamhaus.org:443.
HTTP request sent, awaiting response... 403 Forbidden
2024-03-06 09:03:38 ERROR 403: Forbidden.

### Additional Context

The Spamhaus URLS were modified.

### Build Version

28.0.3.2

### Environment

By using the scripts

**Comment by enoch85** [comment]
Thanks! Please check the PR to see if the fix is valid. :+1:
