### ISSUE TITLE
Error installing nextcloud

### ISSUE THREAD

**Issue by mramazanov** [nextcloud/vm#2625]
### Steps To Reproduce

Installing Nextcloud, it might take a while...
Console has to be executed with the user that owns the data directory
Current user id: 33
Owner id of the data directory: 0
Try adding 'sudo -u #0' to the beginning of the command (without the single quotes)
If running with 'docker exec' try adding the option '-u 0' to the docker command (without the single quotes)
{"reqId":"UuzrH2zgvxfBcdyWzmWF","level":3,"time":"2024-04-27T17:53:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fopen(/var/www/nextcloud/config/config.php): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Config.php#225","userAgent":"--","version":"","data":{"app":"PHP"}}
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=nextcloud_db_user --database-pass=XQuSRtmIE0FM4L8FNIMpwqMP74 --admin-user=ncadmin --admin-pass=nextcloud failed

### Expected Result

-

### Actual Result

-

### Build Version

29

### Environment

By using the scripts

**Comment by xKEVKx** [comment]
I ran into the same issue and reported it here: https://github.com/nextcloud/vm/issues/2624

I also tried the previous version of the install script and ran into the same issue.

-Kevin

**Comment by mramazanov** [comment]
> I ran into the same issue and reported it here: #2624
> 
> I also tried the previous version of the install script and ran into the same issue.
> 
> -Kevin

Thank you, let's hope and wait))

**Comment by enoch85** [comment]
Hi guys, just released a new OS version, so now it works on Ubuntu 24.04!

Added the `--not-latest` flag per default, and will have a closer look at the real issue. 

Please test the latest script!

**Comment by enoch85** [comment]
Just tested, working in current state!
