### ISSUE TITLE
Adminer css url changed

### ISSUE THREAD

**Issue by jahquubel** [nextcloud/vm#2627]
### Steps To Reproduce

install adminer from scripts

### Expected Result

Adminer script downlads adminer.css

### Actual Result

Fails to download the file 

### Additional Context

url changed to 
https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css
from 
https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/main/adminer.css

### Build Version

29

### Environment

By using the scripts

**Comment by enoch85** [comment]
Great catch! Thanks!

**Comment by enoch85** [comment]
This is now fixed.
