### ISSUE TITLE
Netdata installation fails

### ISSUE THREAD

**Issue by jahquubel** [nextcloud/vm#2629]
### Steps To Reproduce

attempt to install netdata from menu.sh

### Expected Result

Netdata installation completes in silent mode.

### Actual Result

Install script expects  password input it seems.

Root privileges required to run env DEBIAN_FRONTEND=noninteractive apt-get update -y
[/tmp/netdata-kickstart-T8afYMzQFZ]$ sudo -n env DEBIAN_FRONTEND=noninteractive apt-get update -y 
sudo: a password is required
 FAILED 

### Screenshots, Videos, or Pastebins

Installing Netdata...
[⣾⣽⣻⣾⣽⣻⣾⣽⣻]

 --- Using /tmp/netdata-kickstart-T8afYMzQFZ as a temporary directory. --- 
 --- Checking for existing installations of Netdata... --- 
 --- No existing installations of netdata found, assuming this is a fresh install. --- 
 --- Attempting to install using native packages... --- 
 --- Checking for availability of repository configuration package. --- 
[/tmp/netdata-kickstart-T8afYMzQFZ]$ /usr/bin/curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-T8afYMzQFZ/netdata-repo_2-2+ubuntu24.04_all.deb https://repo.netdata.cloud/repos/repoconfig/ubuntu/noble/netdata-repo_2-2+ubuntu24.04_all.deb 
 OK 

Root privileges required to run env DEBIAN_FRONTEND=noninteractive apt-get update -y
[/tmp/netdata-kickstart-T8afYMzQFZ]$ sudo -n env DEBIAN_FRONTEND=noninteractive apt-get update -y 
sudo: a password is required
 FAILED 

 WARNING  Failed to refresh repository metadata. This is usually a result of a networking issue or incompatibilities with one or more third-party package repositories in the system package manager configuration.

 WARNING  Could not install native binary packages, falling back to alternative installation method.

[/tmp/netdata-kickstart-T8afYMzQFZ]$ sh -c /usr/bin/curl https://github.com/netdata/netdata/releases/latest -s -L -I -o /dev/null -w '%{url_effective}' | grep -Eo '[^/]+$' 
 OK 

 --- Attempting to install using static build... --- 
[/tmp/netdata-kickstart-T8afYMzQFZ]$ /usr/bin/curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-T8afYMzQFZ/netdata-x86_64-latest.gz.run https://github.com/netdata/netdata/releases/download/v1.45.4/netdata-x86_64-latest.gz.run 
 OK 

[/tmp/netdata-kickstart-T8afYMzQFZ]$ /usr/bin/curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-T8afYMzQFZ/sha256sum.txt https://github.com/netdata/netdata/releases/download/v1.45.4/sha256sums.txt 
 OK 

 --- Installing netdata --- 
Root privileges required to run sh /tmp/netdata-kickstart-T8afYMzQFZ/netdata-x86_64-latest.gz.run --accept --
[/tmp/netdata-kickstart-T8afYMzQFZ]$ sudo -n sh /tmp/netdata-kickstart-T8afYMzQFZ/netdata-x86_64-latest.gz.run --accept -- 
sudo: a password is required
 FAILED 

 WARNING  Failed to install static build of Netdata on x86_64.

[/tmp/netdata-kickstart-T8afYMzQFZ]$ rm -rf /opt/netdata 
 OK 

 WARNING  Could not install static build, falling back to alternative installation method.

 --- Attempting to install by building locally... --- 
[/tmp/netdata-kickstart-T8afYMzQFZ]$ /usr/bin/curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-T8afYMzQFZ/install-required-packages.sh https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh 
 OK 

 --- Running downloaded script to install required build dependencies... --- 
Root privileges required to run /usr/bin/bash /tmp/netdata-kickstart-T8afYMzQFZ/install-required-packages.sh --dont-wait --non-interactive netdata
[/tmp/netdata-kickstart-T8afYMzQFZ]$ sudo -n /usr/bin/bash /tmp/netdata-kickstart-T8afYMzQFZ/install-required-packages.sh --dont-wait --non-interactive netdata 
sudo: a password is required
 FAILED 

 WARNING  Failed to install all required packages, but installation might still be possible.

[/tmp/netdata-kickstart-T8afYMzQFZ]$ sh -c /usr/bin/curl https://github.com/netdata/netdata/releases/latest -s -L -I -o /dev/null -w '%{url_effective}' | grep -Eo '[^/]+$' 
 OK 

[/tmp/netdata-kickstart-T8afYMzQFZ]$ /usr/bin/curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-T8afYMzQFZ/netdata-latest.tar.gz https://github.com/netdata/netdata/releases/download/v1.45.4/netdata-v1.45.4.tar.gz 
 OK 

[/tmp/netdata-kickstart-T8afYMzQFZ]$ /usr/bin/curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-T8afYMzQFZ/sha256sum.txt https://github.com/netdata/netdata/releases/download/v1.45.4/sha256sums.txt 
 OK 

[/tmp/netdata-kickstart-T8afYMzQFZ]$ tar -xf /tmp/netdata-kickstart-T8afYMzQFZ/netdata-latest.tar.gz -C /tmp/netdata-kickstart-T8afYMzQFZ 
 OK 

 --- Building netdata... --- 
[/tmp/netdata-kickstart-T8afYMzQFZ/netdata-v1.45.4]$ sudo -n ./netdata-installer.sh --dont-wait --stable-channel --disable-cloud 
sudo: a password is required
 FAILED 

The following non-fatal warnings or errors were encountered:

  - Command "sudo -n env DEBIAN_FRONTEND=noninteractive apt-get update -y" failed with exit code 1.
  - Failed to refresh repository metadata. This is usually a result of a networking issue or incompatibilities with one or more third-party package repositories in the system package manager configuration.
  - Could not install native binary packages, falling back to alternative installation method.
  - Command "sudo -n sh /tmp/netdata-kickstart-T8afYMzQFZ/netdata-x86_64-latest.gz.run --accept --" failed with exit code 1.
  - Failed to install static build of Netdata on x86_64.
  - Could not install static build, falling back to alternative installation method.
  - Command "sudo -n /usr/bin/bash /tmp/netdata-kickstart-T8afYMzQFZ/install-required-packages.sh --dont-wait --non-interactive netdata" failed with exit code 1.
  - Failed to install all required packages, but installation might still be possible.
  - Command "sudo -n ./netdata-installer.sh --dont-wait --stable-channel --disable-cloud" failed with exit code 1.

 ABORTED  netdata-installer.sh failed to run: Encountered an unhandled error in the installer code.

For community support, you can connect with us on:
  - GitHub: https://github.com/netdata/netdata/discussions
  - Discord: https://discord.gg/5ygS846fR6
  - Our community forums: https://community.netdata.cloud/
Root privileges required to run rm -rf /tmp/netdata-kickstart-T8afYMzQFZ
[/home/ncadmin]$ sudo -n rm -rf /tmp/netdata-kickstart-T8afYMzQFZ 
sudo: a password is required
 FAILED 

### Build Version

29

### Environment

By using the scripts

**Comment by enoch85** [comment]
Thanks for posting! 

I guess that Netdata didn't update their repo to match with the latest release of Ubuntu, yet.

Let's give it some time and see what happens. Until then, please skip Netdata.

**Comment by jahquubel** [comment]
It was the same on 22.04.

**Comment by enoch85** [comment]
Ok, will have a look at it. 👍🏼

**Comment by jahquubel** [comment]
I removed  -u "$UNIXUSER" from below line and it installed without issues. 

sudo -u "$UNIXUSER" bash $SCRIPTS/kickstart.sh --reinstall-even-if-unsafe --non-interactive --no-updates --stable-channel --disable-cloud

**Comment by enoch85** [comment]
Yeah, but now you installed as root. That's not wanted behavior - but great that you found a fix! :+1: 

Will have a look when time allows.

**Comment by enoch85** [comment]
Hmm, seems like it somehow doesn't work with a normal user now. So applied your fix. Thanks for posting this issue, let me know if you find anything else. :)

Thanks!
