### ISSUE TITLE
Adminer not being maintained anymore

### ISSUE THREAD

**Issue by muchachagrande** [nextcloud/vm#2630]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Apparently, Adminer is not maintained anymore, at least for the last 3 years.
The project has been forked and is being maintained. See https://docs.adminerevo.org and https://github.com/adminerevo/adminerevo

**Describe the solution you'd like**
If you consider it important/useful/necessary Adminer may be replaced by AdminerEvo

**Describe alternatives you've considered**
An alternative is to go on with Adminer, but sooner or latter it will start to give trouble as PHP upgrades.

**Additional context**
Nothing

**Comment by enoch85** [comment]
Will fix this!

**Comment by enoch85** [comment]
@muchachagrande Please test this PR: https://github.com/nextcloud/vm/pull/2632

**Comment by muchachagrande** [comment]
Hi @enoch85, how can I test this?... I just tried to update as I usually do but Adminer is not updating, I think this is because the fix is not in production yet.

**Comment by enoch85** [comment]
Do a reinstallation. I will fix the update script later.

**Comment by muchachagrande** [comment]
I reinstalled and it is still reinstalling the old version from the ubuntu repo as you can see on the logs:

> root@cloud:/home/ncadmin# main_menu 
> Running the main menu script...
> Testing if network is OK...
> Checking connection...
> Downloading the Additional Apps Menu...
> Downloading the Adminer script...
> Reinstalling Adminer...
> Conf adminer already disabled
> Restarting Apache2 and PHP-FPM...
> Getting current PHP-version...
> PHPVER=8.1
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following packages will be REMOVED:
>   adminer*
> 0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
> After this operation, 2950 kB disk space will be freed.
> (Reading database ... 148834 files and directories currently installed.)
> Removing adminer (4.8.1-1) ...
> apache2_invoke adminer prerm: No action required
> (Reading database ... 148577 files and directories currently installed.)
> Purging configuration files for adminer (4.8.1-1) ...
> apache2_invoke adminer postrm: No action required
> Restarting Apache2 and PHP-FPM...
> Getting current PHP-version...
> PHPVER=8.1
> Reinstalling Adminer...
> Module headers already enabled
> Module rewrite already enabled
> Considering dependency setenvif for ssl:
> Module setenvif already enabled
> Considering dependency mime for ssl:
> Module mime already enabled
> Considering dependency socache_shmcb for ssl:
> Module socache_shmcb already enabled
> Module ssl already enabled
> [⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻]
> dpkg-query: no packages found matching adminer
> [⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻]
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following NEW packages will be installed:
>   adminer
> 0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
> Need to get 801 kB of archives.
> After this operation, 2950 kB of additional disk space will be used.
> Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 adminer all 4.8.1-1 [801 kB]
> Fetched 801 kB in 1s (568 kB/s)  
> Selecting previously unselected package adminer.
> (Reading database ... 148574 files and directories currently installed.)
> Preparing to unpack .../adminer_4.8.1-1_all.deb ...
> Unpacking adminer (4.8.1-1) ...
> Setting up adminer (4.8.1-1) ...
> Scanning processes...                                                           
> Scanning linux images...                                                        
> 
> Running kernel seems to be up-to-date.
> 
> No services need to be restarted.
> 
> No containers need to be restarted.
> 
> No user sessions are running outdated binaries.
> 
> No VM guests are running outdated hypervisor (qemu) binaries on this host.
> Archive:  /usr/share/adminer/adminer-pgsql.zip
>   inflating: /usr/share/adminer/adminer-pgsql.php  
> ln: failed to create symbolic link '/usr/share/adminer/adminer.php': File exists
> Getting current PHP-version...
> PHPVER=8.1
> Site adminer already enabled
> Restarting Apache2 and PHP-FPM...
> Getting current PHP-version...
> PHPVER=8.1
> Restarting Apache2 and PHP-FPM...
> Getting current PHP-version...
> PHPVER=8.1

**Comment by enoch85** [comment]
Did you login to the new adminer? :)

**Comment by muchachagrande** [comment]
Yes. It is 4.8.1 version but without the customized CSS.

![imagen](https://github.com/nextcloud/vm/assets/20299175/883b756b-5068-4665-982c-5855db8ed0b8)

**Comment by enoch85** [comment]
Sorry, must have missed committing my local changes. It's now fixed, both in the update script, and when reinstalling.

Please confirm:

1. Run the update script
2. Check
3. Reinstall
4. Check

**Comment by muchachagrande** [comment]
Excellent... now it works!!
Also I could successfully login.
thank you very much and cheers...

![imagen](https://github.com/nextcloud/vm/assets/20299175/891131a4-fb1e-4da6-86e3-8d61422d2303)

**Comment by muchachagrande** [comment]
Also tried an update:

> Updating Adminer...
> Archive:  /usr/share/adminer/adminer-pgsql.zip
>   inflating: /usr/share/adminer/adminer-pgsql.php
