### ISSUE TITLE
Realtek Driver Update

### ISSUE THREAD

**Issue by patwards** [nextcloud/vm#2631]
### Steps To Reproduce

when running the update command:
sudo bash /var/scripts/update.sh following error occurs:

```text
Nextcloud VM - 2024 - PN51 Network Drivers 
It seems like there's a newer version of the Realtek Driver for the LAN network card.
Please report this to https://github.com/nextcloud/vm/issues including this link:

https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

Thanks!
```

### Expected Result

Normal update process

### Actual Result

Error message:
Nextcloud VM - 2024 - PN51 Network Drivers 
It seems like there's a newer version of the Realtek Driver for the LAN network card.
Please report this to https://github.com/nextcloud/vm/issues including this link:

https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

Thanks!

### Screenshots, Videos, or Pastebins

![image](https://github.com/nextcloud/vm/assets/36577889/76ca249e-cf5a-4c5d-b829-d1913d68d82e)

### Build Version

29.0.0

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04

**Comment by enoch85** [comment]
Realtek closed their download page, so can't update.

But added info here on how to do it: https://github.com/nextcloud/vm/commit/1cced01e6db67c4a4f0f545fe9d6d39389d89e4b
