### ISSUE TITLE
NextCloud VM installation error -Adminer

### ISSUE THREAD

**Issue by sotos2004** [nextcloud/vm#2633]
### Steps To Reproduce

During the installation of the Adminer GUI the isntallation fails with "We tried to fetch..... http://raw.github....../main/adminer.css .

I think the right path is (https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css)

### Expected Result

Installation of -Adminer during initial install

### Actual Result

Unable to proceed.

### Build Version

28.0 , Didnt'r reach the update point.

### Environment

By using the scripts

**Comment by enoch85** [comment]
Hi, thanks for reporting!

We actually removed the CSS in the latest version of the installation script: https://github.com/nextcloud/vm/blob/main/apps/adminer.sh#L60

Please use install Nextcloud, and after it's installed - run the menu script to get the latest version of the adminer script.

Have a nice day!
