### ISSUE TITLE
Installation doesn't work on Ubuntu 22.04 

### ISSUE THREAD

**Issue by shylaev** [nextcloud/vm#2635]
### Steps To Reproduce

1. install ubuntu 22.04 minimal
2. apt upgrade 
3. wget https://raw.githubusercontent.com/nextcloud/vm/main/nextcloud_install_production.sh
4. sudo bash nextcloud_install_production.sh
5. shortly after start I get error:

ERROR: Conf php8.3-fpm does not exist!
Enabling HTTP/2 server wide...
/etc/apache2/mods-available/http2.conf was successfully created
Enabling module http2.
To activate the new configuration, you need to run:
  systemctl restart apache2
Restarting Apache2 and PHP-FPM...
Getting current PHP-version...
PHPVER=8.1
dpkg-query: no packages found matching php8.1-fpm
nextcloud_install_production.sh: line 440: /etc/php/8.1/fpm/pool.d/nextcloud.conf: No such file or directory
mv: cannot stat '/etc/php/8.1/fpm/pool.d/www.conf': No such file or directory
Restarting Apache2 and PHP-FPM...
Getting current PHP-version...
PHPVER=8.1
dpkg-query: no packages found matching php8.1-fpm
Getting current PHP-version...
PHPVER=8.1
grep: /etc/php/8.1/fpm/pool.d/nextcloud.conf: No such file or directory
grep: /etc/php/8.1/fpm/pool.d/nextcloud.conf: No such file or directory
grep: /etc/php/8.1/fpm/pool.d/nextcloud.conf: No such file or directory
Automatically configures pm.max_children for php-fpm...
sed: can't read /etc/php/8.1/fpm/pool.d/nextcloud.conf: No such file or directory
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sed -i s|pm.max_children.*|pm.max_children = 148|g /etc/php/8.1/fpm/pool.d/nextcloud.conf failed

### Expected Result

normally running setup process

### Actual Result

stop process of installation

### Screenshots, Videos, or Pastebins

![image](https://github.com/nextcloud/vm/assets/93459981/27373fda-1b67-46e0-b5bf-780fe0d31ca5)

### Build Version

as described in script, I think 29

### Environment

By using the scripts

**Comment by enoch85** [comment]
You need to install this on Ubuntu 24.04 minimal.

Please try again, thanks!

**Comment by shylaev** [comment]
> You need to install this on Ubuntu 24.04 minimal.
> 
> Please try again, thanks!

nobody faults but mine
thanks for attention
