### ISSUE TITLE
Multiple available Nextcloud updates potentially lead to reboot during update process

### ISSUE THREAD

**Issue by pq2** [nextcloud/vm#2638]
### Steps To Reproduce

1. Ensure that there are multiple new Nextcloud versions available. Perhaps a new minor release and a new major release must be available. E.g. 29.0.1 and 28.0.6 while being on 28.0.5.
2. Run `sudo bash /var/scripts/menu.sh`
3. Select `Update Nextcloud` from the menu
4. Now the update to the minor version is performed. E.g. 28.0.6.
5. After the update, a reboot is scheduled in 1 minute
6. Also, you are informed that a new Nextcloud version is available (29.0.1 in the example) and are asked if you want to run the script a second time in order to update to that new version
7. Select `yes` to run the script a second time

### Expected Result

The update to the new major version is performed successfully.

### Actual Result

The scheduled reboot interferes with the second execution of the update script.
In my case, the reboot was performed while the backup of the system partition was created.
Now the backup script isn't working anymore because there is a leftover lock:
`Failed to create/acquire the lock /root/.cache/borg/<long number>/lock.exclusive (timeout).`

### Build Version

28.0.5

### Environment

By using the scripts

### Environment Details

- Operating System: Ubuntu 22.04

**Comment by enoch85** [comment]
Great point! Will fix this!

**Comment by pq2** [comment]
Thanks! Can I safely remove the lock in order to get the backup script working again? If so, how would I do that?

**Comment by pq2** [comment]
Perhaps you want to add a `borg break-lock` before [this line](https://github.com/nextcloud/vm/blob/2da7343c145fc659b88675b360f63b7bfdacfddd/not-supported/borgbackup.sh#L414).

**Comment by enoch85** [comment]
> Perhaps you want to add a `borg break-lock` before [this line](https://github.com/nextcloud/vm/blob/2da7343c145fc659b88675b360f63b7bfdacfddd/not-supported/borgbackup.sh#L414).

@szaimen Can you please have a look regarding the backup script?

**Comment by enoch85** [comment]
@pq2 I've reset the automated reboot now to 10 minutes instead. Should help at least.

**Comment by pq2** [comment]
> > Perhaps you want to add a `borg break-lock` before [this line](https://github.com/nextcloud/vm/blob/2da7343c145fc659b88675b360f63b7bfdacfddd/not-supported/borgbackup.sh#L414).
> 
> @szaimen Can you please have a look regarding the backup script?

Inserting `borg break-lock "$BACKUP_TARGET_DIRECTORY"` before this line made it work again for me. I'm not sure if it makes sense to always do this at this point.

**Comment by enoch85** [comment]
Maybe you can unset it as the final thing in the script?

**Comment by szaimen** [comment]
> Perhaps you want to add a `borg break-lock` before [this line](https://github.com/nextcloud/vm/blob/2da7343c145fc659b88675b360f63b7bfdacfddd/not-supported/borgbackup.sh#L414).

I fear this is not a good idea. Borg brwak-lock should only be performed if actually really necessary. Maybe instead the reboot can be inforced so that one does not run multiple updates in a row if a reboot is scheduled?

**Comment by pq2** [comment]
> > Perhaps you want to add a `borg break-lock` before [this line](https://github.com/nextcloud/vm/blob/2da7343c145fc659b88675b360f63b7bfdacfddd/not-supported/borgbackup.sh#L414).
> 
> I fear this is not a good idea. Borg brwak-lock should only be performed if actually really necessary. Maybe instead the reboot can be inforced so that one does not run multiple updates in a row if a reboot is scheduled?

Enforcing the reboot seems to me to be an appropriate solution.

**Comment by enoch85** [comment]
Since this issue is targeting a script in "non-supported" - I'll close it.

Thanks for the heads up @pq2!
