### ISSUE TITLE
Cron <root@cloud> which zfs-auto-snapshot > /dev/null || exit 0 ; zfs-auto-snapshot --quiet --syslog --label=frequent --keep=4 //

### ISSUE THREAD

**Issue by FrankHae** [nextcloud/vm#2643]
### Steps To Reproduce

I get an email every minutes with:
cannot create snapshots : out of space
no snapshots were created
less than 500MB of the 40GB are actually used

### Expected Result

?

### Actual Result

cannot create snapshots : out of space
no snapshots were created

### Build Version

29.0.1

### Environment

By downloading the VM

### Environment Details

Ubuntu 22.04 from Hansson IT
Vmware Fusion Professional 12.1.2
macOS 10.15.7

**Comment by enoch85** [comment]
Hi,

Run this:

1. `wget https://raw.githubusercontent.com/nextcloud/vm/main/disk/zfs-prune-snapshots.sh`
2. `sudo bash zfs-prune-snapshots.sh 1s`
3. `sudo apt purge zfs-auto-snapshot` (if you don't want it anymore)

**Comment by FrankHae** [comment]
Thanks. Now
ncdata   1K-blocks: 40086144  used: 35741056. avail: 4345088. Use 90%. ?? 
90% use, I think this value is still far too high...

**Comment by FrankHae** [comment]
sudo bash zfs-prune-snapshots.sh 1s
[sudo] password for ncadmin: 
removing ncdata@zfs-auto-snap_hourly-2024-05-27-1417: 4 hours old
removing ncdata@zfs-auto-snap_frequent-2024-05-27-1430: 4 hours old
removing ncdata@zfs-auto-snap_frequent-2024-05-27-1445: 4 hours old
removing ncdata@zfs-auto-snap_frequent-2024-05-27-1500: 3 hours old
removing ncdata@zfs-auto-snap_frequent-2024-05-27-1515: 3 hours old
removing ncdata@zfs-auto-snap_hourly-2024-05-27-1517: 3 hours old

afterwards
ncdata   40087808   39915520   172288  **100%**  /mnt/ncdata

**Comment by enoch85** [comment]
Well, there are pretty many factors which could play a role here...

Another guess is that your trashbin are full, try to delete that and cleanup: `wget https://raw.githubusercontent.com/nextcloud/vm/main/disk/prune_zfs_snaphots.sh && sudo bash prune_zfs_snaphots.sh`

Did it work?

**Comment by FrankHae** [comment]
**Yes this did work:**

**root@cloud:/# wget https://raw.githubusercontent.com/nextcloud/vm/main/disk/prune_zfs_snaphots.sh && sudo bash prune_zfs_snaphots.sh**
--2024-05-28 21:03:08--  https://raw.githubusercontent.com/nextcloud/vm/main/disk/prune_zfs_snaphots.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2857 (2.8K) [text/plain]
Saving to: ‘prune_zfs_snaphots.sh’

prune_zfs_snaphots.sh  100%[=========================>]   2.79K  --.-KB/s    in 0s      

2024-05-28 21:03:08 (17.9 MB/s) - ‘prune_zfs_snaphots.sh’ saved [2857/2857]

Posting notification to users that are admins, this might take a while...
Sending 'Disk space almost full!' to frank@xxxxxxx.com
Posting 'Disk space almost full!' to: Frank
To abort, please press CTRL+C within 10 seconds.
Freeing some space... This might take a while, please don't abort.
root@cloud:/# 

**After that:**
**root@cloud:/# df**
Filesystem                        1K-blocks     Used Available Use% Mounted on
tmpfs                                396888     2084    394804   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  37950976 17463892  18728572  49% /
tmpfs                               1984432       28   1984404   1% /dev/shm
tmpfs                                  5120        0      5120   0% /run/lock
/dev/sda2                           1992552   257692   1613620  14% /boot
/dev/sda1                           1098632     6220   1092412   1% /boot/efi
ncdata                             39916416 38101120   1815296  **96% /mnt/ncdata**
tmpfs                                396884        4    396880   1% /run/user/1000

There are actually only 2 User.....
The trashes are empty
There are ONLY files (1 User) in external storage. 
The other user has NOT any data...

**Comment by enoch85** [comment]
External storage doesn't affect the local storage since it resides on a remote location.

I suggest you book support for us to have a look: https://shop.hanssonit.se/product/premium-support-per-30-minutes/

I guess you actually use that much data, or something is very wrong.

Have you tried a reboot?

**Comment by FrankHae** [comment]
> External storage doesn't affect the local storage since it resides on a remote location.

Yes I know, but every attempt counts....
Every 30 minutes I get this

Fehler | core | Can't get app storage, app files_external, user not logged in | "28.05.2024, 22:50:02" |  
Fehler | core | Can't get app storage, app files_external, user not logged in | "28.05.2024, 22:50:02" |  
Fehler | core | Can't get app storage, app files_external, user not logged in | "28.05.2024, 22:50:02" |  
Fehler | core | Can't get app storage, app files_external, user not logged in | "28.05.2024, 22:50:02" |  
Fehler | core | Can't get app storage, app files_external, user not logged in | "28.05.2024, 22:15:02" |  
Fehler | core | Can't get app storage, app files_external, user not logged in | "28.05.2024, 22:15:02" |  
Fehler | core | Can't get app storage, app files_external, user not logged in | "28.05.2024, 22:15:02"

> I suggest you book support for us to have a look: https://shop.hanssonit.se/product/premium-support-per-30-minutes/

I think that's a good (probably the only) idea.
 
> I guess you actually use that much data, or something is very wrong.

I have no idea. Only 2 users, no data (data temporarily stored elsewhere), recycle bin empty,

> Have you tried a reboot?

Of course, several times

The installation ran smoothly for several months. Only the automated updates were installed

This error messages have only been present since the last update.

- The .htaccess file does not work...
- The server does not have a configured start time for the maintenance window...

This message was already there from the beginning.:

- The PHP module “imagick” is not activated

**Comment by enoch85** [comment]
Can we close this?
