### ISSUE TITLE
Bitwarden - Error when updating using bitwarden.sh script

### ISSUE THREAD

**Issue by FleketBreaker** [nextcloud/vm#2646]
### Steps To Reproduce

I just got a notification from the bitwarden github that the app was updated, so I ran as the bitwarden user:
```
bash bitwarden.sh updateself
bash bitwarden.sh update
```

### Expected Result

Bitwarden gets updated

### Actual Result

```
bitwarden.sh version 2024.6.0
Docker version 26.1.4, build 5650f9b
Docker Compose version v2.27.1

"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects
Error response from daemon: manifest for bitwarden/setup:2024.6.0 not found: manifest unknown: manifest unknown

```
Now Im not able to access my bitwarden isntance :(

### Build Version

Nextcloud Hub 8 (29.0.2)

### Environment

By downloading the VM

**Comment by FleketBreaker** [comment]
I have been doing some more digging and it seems that 2024.6.0 tag is not present at https://hub.docker.com/r/bitwarden/setup/tags. Why not to point it to "latest" instead of a specific version?

**Comment by FleketBreaker** [comment]
Fixed!
https://github.com/bitwarden/self-host/issues/264

**Comment by enoch85** [comment]
We actually already adress this in the update script. 

Thanks for posting a bug report, and thanks for the fix!
