### ISSUE TITLE
Script is not accessible

### ISSUE THREAD

**Issue by Der-Norden** [nextcloud/vm#2648]
### Steps To Reproduce

Under the link you get a 404 message.

https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh

### Expected Result

Under the link you get a 404 message.

https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh

### Actual Result

Under the link you get a 404 message.

https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh

### Build Version

XXX

### Environment

By using the scripts

**Comment by enoch85** [comment]
Check your DNS, or country block.

**Comment by enoch85** [comment]
Aah sorry, branch changed to 'main'.

**Comment by enoch85** [comment]
Aah sorry, branch changed to 'main'.
