### ISSUE TITLE
Sorry but something went wrong.

### ISSUE THREAD

**Issue by Bishop-trevorstuart** [nextcloud/vm#2650]
### Steps To Reproduce

No clue. I've added some info to context. 

### Expected Result

No clue. I've added some info to context. 

### Actual Result

No clue. I've added some info to context. 

### Screenshots, Videos, or Pastebins

![image](https://github.com/nextcloud/vm/assets/67986883/f03b8086-a355-4d84-bbb5-6bbfb90df0c6)
![image](https://github.com/nextcloud/vm/assets/67986883/5d153099-530b-4343-af1c-4bafd1d16c0b)

### Additional Context

I had recently run out of space on teh root partiation and cleaned that up. Completed apt update/upgrade and rebooted. After an hour or so that's when this error message popped into my notificaitons. 
The attached pic is what the messsage says. 

Outside of this message in my notifications my actual log (set to warning) is FULL of warnings from Recognize. 
Failed to generate preview of 21027 with dimension 1024 with nextcloud preview manager: No provider successfully handled the preview generation
But I've gotten that error from day one and doubt it's related. 
Filtering out warnings the errors are new/strange but related to connection to a database. I included a screenshot incase they are helpful at all. 

### Build Version

Nextcloud Hub 8 (29.0.3)

### Environment

By downloading the VM

### Environment Details

Ubuntu 22.04 LTS
VM (ESXi 6.7). 
4 vcpus/8GB ram/2 x 40 GB drives. 
I have a NAS mapped, but it's not the data folder (yet).

**Comment by enoch85** [comment]
Please reinstall SMB Share(Mount) through the menu.

It will take a while so use the VM console so that you can leave it.

**Comment by Bishop-trevorstuart** [comment]
When I run menu I can only find SMB under apps. But when I select that it wants to reconfigure, not reinstall. 
Am I in the right place to reinstall it?

**Comment by enoch85** [comment]
Remove the old shares, and add them back. When asked to install inotify, choose "yes" (or similar).

Yes, your on the right path. 👍🏼

**Comment by Bishop-trevorstuart** [comment]
Removed/deleted all the shares using menu. 
Then created again (I had rebooted after deleting just for fun). 
It said the mount was successful. When asked I did say yes to install inotify... 
Nothing took very long to install. 
When I originally setup my shares I used just the WebUI (external storage under administrator options). 
With it setup via the menu script I now see the share in External storage, but it shows a local, no auth. No issues as I'm assuming the script simply set up the share "correctly" in fstab and is mapping it that way. 

I logged into my account and re-directed the photos (in previous share config I was using users$ so this is now changed). 

In recognize I cleared queues and backgroud jobs. Then rescan all files. 
The notification returned stating to report the issue here...

**Comment by enoch85** [comment]
Hmm, ok.

What's the output of:

```
sudo -i (just to become root, post output of below commands)

tail -n 50 /var/log/nextcloud/files_inotify.log
nextcloud_occ app:list | grep files_inotify
pecl list | grep inotify
```

> With it setup via the menu script I now see the share in External storage, but it shows a local, no auth. No issues as I'm assuming the script simply set up the share "correctly" in fstab and is mapping it that way.

Yes, you now have local shares in Linux, they work much faster (and better) than with PHP.

Another possible error is that your mount ID is wrong. So you have for example mount ID 5 in the database, but Nextcloud tries to fetch mount ID 1. What you need to do is to check what the mount id is in the database, then change to the correct ID (from database) in your crontab (crontab -e -u www-data). You can check your mount ID in DB with something like: `select * from oc_external_mounts;`

**Comment by enoch85** [comment]
Also, would be interessting with the output of: `df -h`

**Comment by enoch85** [comment]
Aaand please resinstall Recognize as well with the menu script. :)

**Comment by Bishop-trevorstuart** [comment]
sudo -i = it keeps running the startup script. I posted about this on the community chat but never got a responce. 
https://help.nextcloud.com/t/vm-initial-setup/194122?u=trevor_stuart
Sorry these are screenshots, ESXi's console doesn't let me copy/paste text between it. 
Here is the tail output
![image](https://github.com/nextcloud/vm/assets/67986883/dd72006d-23b7-408b-81b5-2770780f55cd)
App list
![image](https://github.com/nextcloud/vm/assets/67986883/0faf4825-eeef-4673-8244-d03ffc781ca5)
pecl list
![image](https://github.com/nextcloud/vm/assets/67986883/a5ab5b7a-a40e-4a4c-99a1-93ac617ab1c0)
df -h (this is where I discovered my root partiion had run out of space, for now I purged the swap file but when I'm ready I'll put it back)
![image](https://github.com/nextcloud/vm/assets/67986883/15724a77-49f1-470b-aaac-8e5597a7e3eb)

Will reinstall recognize, and confirm the mount ID next.

**Comment by Bishop-trevorstuart** [comment]
reinstalling recognize didn't seem to help. Still getting the errors. 
I was going to try digging into the mount ID stuff, but I don't know how to do that. I'm clueless when it comes to anything inside the DB itself.

**Comment by enoch85** [comment]
You have it in the first prtscr. Mount not found.

Please get support here and reference this issue: https://shop.hanssonit.se/product/premium-support-per-30-minutes/

While you're at it, also get this: https://shop.hanssonit.se/product/custom-expand/
