### ISSUE TITLE
nextcloud_install_production.sh now missing?

### ISSUE THREAD

**Issue by justinclift** [nextcloud/vm#2652]
### Steps To Reproduce

1. Go to 'https://github.com/nextcloud/vm'
2. Look for `nextcloud_install_production.sh`, as instructed by the setup docs:

![image](https://github.com/nextcloud/vm/assets/406299/a6ebb8d7-2d4b-4b71-95eb-87ed3def7269)

Looks like the script was removed [a few months ago](https://github.com/nextcloud/vm/commit/4d9b13d7e9a9780d24ed20657144b666fe80efae), saying it was "unnecessary" but with no further detail as to what it's been replaced by.

### Expected Result

The script to be available for use.

### Actual Result

Missing script.

### Build Version

none, that's the point

### Environment

By using the scripts

### Environment Details

A newly installed VM on my local workstation.  Currently Debian 12, but easily changeable to something else (ie Ubuntu, etc) if that's really necessary.

**Comment by enoch85** [comment]
Thanks! Will update the documentation.

**Comment by justinclift** [comment]
Oh, the script seems to be back now or was I just getting confused somehow? :thinking:

**Comment by enoch85** [comment]
Thanks for the pointers! You're right.

Just need to get some sleep after working 16 hours. 😐

**Comment by justinclift** [comment]
No worries at all, I understand that all too well myself. :wink:
