### ISSUE TITLE
Is https://download.nextcloudvm.com supposed to be online?

### ISSUE THREAD

**Issue by justinclift** [nextcloud/vm#2653]
### Steps To Reproduce

1. Go to the main repo front page: https://github.com/nextcloud/vm
2. Click on https://download.nextcloudvm.com url on the right side under the project description.

### Expected Result

A page to load.  Maybe containing VMs to download?

### Actual Result

![image](https://github.com/user-attachments/assets/86109e8b-3708-4c08-85ba-decef45c84e7)

### Build Version

nope ;)

### Environment

By downloading the VM

**Comment by justinclift** [comment]
I guess my point with this issue is that the clickable link in the project front page is timing out.

Not really familiar enough with the project to know if that means the link needs changing, or perhaps it's just a server somewhere needing a bit of a look at. :wink:

**Comment by enoch85** [comment]
It's leading to https://www.hanssonit.se/nextcloud-vm/ and is just a redirect. :)

**Comment by justinclift** [comment]
No worries.  Sounds like it was on the "server needed some attention" side of things then. :wink:

**Comment by justinclift** [comment]
The redirect link is timing out again:

![image](https://github.com/user-attachments/assets/194590d8-3cf1-4378-82f5-97b6548a0793)

Whereas the page it's linking to is still online:

![image](https://github.com/user-attachments/assets/cc23c149-005b-45fe-a51e-4780145d78cd)

Is it feasible to change the link on the homepage directly to the target website?  The redirect link is clearly not reliable.

**Comment by enoch85** [comment]
Hmm, might be a country block thing. I will have a look at another redirect server instead.

**Comment by justinclift** [comment]
I'm in Australia if that helps.

**Comment by enoch85** [comment]
OK, the DNS wasn't migrated since I sold the company, that's fixed now, and it should start resolving soon. Please try again in around 2 hours.

**Comment by justinclift** [comment]
Trying it just now (~3 hours after you posted that), and the bounce is working again.

Hopefully it works reliably from here on. :smile:

**Comment by enoch85** [comment]
> Hopefully it works reliably from here on. 😄

It will be, changed from my own server which is locked down to another one in "the cloud". :+1: :rocket:
