### ISSUE TITLE
I'm "always welcomed" if accessing freshly installed NC via Proxy - Thus can't access NC itself.

### ISSUE THREAD

**Issue by nicoleise** [nextcloud/vm#2654]
### Steps To Reproduce

1. Finish setup script succesfully, no errors.
2. Access new/resulting NextCloud instance Web GUI though a reverse proxy. 

### Expected Result

I expect to see the Nextcloud instance Web GUI (perhaps with the exception of the first-run info page shown once), regardless of how I arrive at the URL.

### Actual Result

What I see differs (but repeats reliably) based on how I access the instance (Please note Additional Context), but the jist of it is that if I access the NextCloud instance in the way I'm "supposed to", I only see (your) welcome page, and cannot progress to NextClouds own Web GUI. 

To elaborate:

- If I access https://[NC LAN IP], I arrive at NC Web GUI over an insecure (non-TLS) connection, as expected.
- If I access https://sub.domain.tld, I arrive at the first-run information page over a secure (TLS) connection. 
- If I access https://sub.domain.tld while connected remotely, I arrive at the first-run information page over a secure (TLS) connection.
- If I access https://sub.domain.tld/nextcloud/index.php I arrive at NC Web GUI over a secure (TLS) connection.*

*) I did first get a warning about an untrusted domain. When I added sub.domain.tld to trusted domains in config/config.php, this error no longer occurs and NC Web GUI works as expected. 

However, even after the above, no matter how many times I visit https://sub.domain.tld, I am shown the first-run information page over a secure (TLS) connection. If I click the link to log in to NC, the page simply reloads. This repeats seemingly infinitely. I should add that all links (to log in) on the welcome page point to https://sub.domain.tld as expected. 

This behavior is obvious as the first-run information page is index.php in the root of /var/www/, but I'm unsure what is supposed to be done to fix this in a reliable and stable manner? What would the script normally do, when it understands that the user has been welcomed?

And obviously, I would suggest that this scenario seems like something the script should potentially be able to handle, or where the docs would cover how to "mend" the resulting installation to suit the application. Perhaps I missed it, though I did look extensively?

### Screenshots, Videos, or Pastebins

![image](https://github.com/user-attachments/assets/2c1f90d2-19be-4510-88a3-ce93b9edbf38)

### Additional Context

I use a split-horison DNS setup, in which the sub.domain.tld locally resolves to [Proxy LAN IP] and remotely resolves to my WAN IP. Requests on WAN IP are forwarded to proxy LAN IP for relevant services.

I further run two proxies, only one of which is relevant to this report. The proxy handles upgrading the incoming requests with TLS (using Lets Encrypt domain verification) and forwards the connection to the relevant backend based on $host and $request_uri. 

I'm using this setup for a multitude of other services, including another NextCloud instance, with no problems apart from this. I assume the proxied connection is the origin of this issue, although it could have other causes too. It's just "what's special" about my setup. 

The below are the results of commands run on the same client machine as the above "actual results" occur from:
```
>nslookup sub.domain.tld
Server: UnKnown
Address: 10.10.10.1

Name: sub.domain.tld
Address: [PROXY LAN IP]
```

And:

```
>ping sub.domain.tld
Pinging sub.domail.tld [NC LAN IP] with 32 bytes of data:
Reply from [NC LAN IP]: bytes=32 time=1ms TTL=63
Reply from [NC LAN IP]: bytes=32 time<1ms TTL=63
Reply from [NC LAN IP]: bytes=32 time=1ms TTL=63
Reply from [NC LAN IP]: bytes=32 time=1ms TTL=63
```

I'm keeping my domain private as it resolves publicly as well, so sub.domain.tld is just a placeholder. My domain is valid. [NC LAN IP] is 10.20.60.80. [Proxy LAN IP] is 192.168.168.168. 

### Build Version

29.0.4

### Environment

By using the scripts, By downloading the VM

### Environment Details

Downloaded the most recent VM to my Proxmox instance and restored it, then scripts executed and completed. VM settings generally not changed, but of course given a VLAN tag, DHCP reservation in firewall, etc. Physical host is 2x16core CPUs, 256 GB DDR4, 1,6 TB SSDs, 2x10G network (Link Aggregation).

**Comment by enoch85** [comment]
Haven't read everything in detail, but it seems to me like it's an issue with not running the first setup script properly. So if it's a fresh VM, please scrape it and start over. Just hit enter through the whole setup, and de-select everything regarding TLS (since you're behind a proxy). Then change the https conf and forward your proxy to 443. Disable the https conf, do the 301 in your proxy instead.

On mobile, hence short.

**Comment by enoch85** [comment]
And the reasonings behind my assumption is this line: https://github.com/nextcloud/vm/blob/99ab136370f505f746cfc71575f9ff3025a555d4/nextcloud-startup-script.sh#L260

Meaning; we change the default web root so that the welcome page isn't even shown if the setup script runs properly.

**Comment by enoch85** [comment]
You could also try.to disable all the apache confs in sites-enabled, and just enable the https one as mentioned above.

**Comment by enoch85** [comment]
> And the reasonings behind my assumption are these lines:
> 
> https://github.com/nextcloud/vm/blob/99ab136370f505f746cfc71575f9ff3025a555d4/nextcloud-startup-script.sh#L254-L260
> 
> Meaning; we change the default web root so that the welcome page isn't even shown if the setup script runs properly. We also delete the actual index file (which is the welcome page).

Sorry, that was misleading, I remember now that we actually do the opposite. Hehe :)

So you need to do the steps manually that we do in out "Activate TLS" script:

1. Disable all apache configs 
2. Enable the https config after modifyig it to suit your needs (it's just a template conf)
3. Remove index.php in /var/www/*
4. Change web root

Alternately, rum the "Activate TLS" script ( it will fail), the use that conf as your sole config in Apache. You also need to change SSL (TLS) certs to self-signefd. Tjust grab the lines from the template conf for https.

Hope it helps!

**Comment by nicoleise** [comment]
> Meaning; we change the default web root so that the welcome page isn't even shown if the setup script runs properly. We also delete the actual index file (which is the welcome page).

I see. First of all, given a couple of hours to think about it, I remembered that on my other NC instances, I've always moved /var/www/nextcloud/* into /var/www/ so NC simply is the "default appliance" in the webroot. I simply forgot that this is my doing rather than how nextcloud ships. My apologies for the confusion.  

That the webroot should have changed makes sense though, because if the above was the only "issue", then the links on that welcome page should point to https://sub.domain.tld/nextcloud instead of just the domain. 

I can confirm that my file contains:
```
/etc/apache2/sites-available/000-default.conf
<VirtualHost *:80>
[...]
DocumentRoot /var/www
[...]
```

I'll have to somehow enable TLS locally on the NC instance also though, as it complains under Security about a lack of TLS (even when I access it securely) and wont install Talk because of this. But that's a me-problem. 

Great script, thank you very much for the assistance and sorry again about the assumption I made. :) I'll mark it closed as it seems whatever little error happened has no permanent effect due to me moving the nextcloud folder into webroot anyways.

**Comment by nicoleise** [comment]
> Alternately, rum the "Activate TLS" script ( it will fail), the use that conf as your sole config in Apache. You also need to change SSL (TLS) certs to self-signefd. Tjust grab the lines from the template conf for https.
> 
> Hope it helps!

Just for the sake of completeness, as mentioned I needed to enable TLS locally on NC as well. I ran the script to activate TLS, and it worked without a hitch. :) Thanks again.

**Comment by enoch85** [comment]
😁

**Comment by enoch85** [comment]
Reading this again....

> /var/www/nextcloud/* into /var/www/

This is a a bad idea. We assume in other scripts that Nextcloud is in `/var/www/nextcloud`. It's better to change the Apache config.

If you need support for a perfect setup, please book 30 minutes in our shop: https://shop.hanssonit.se/product/premium-support-per-30-minutes/
