### ISSUE TITLE
One or more mimetype migrations are available

### ISSUE THREAD

**Issue by motionthings** [nextcloud/vm#2658]
### Steps To Reproduce

Update from 29.0.4 to 29.0.5 via 'sudo bash /var/scripts/menu.sh'
Let the server run for a day (make sure all cron jobs are done)
See error message about 'mime types'
Try the suggested method of running the command `occ maintenance:repair --include-expensive`
Try the same thing in the 'menu.sh' script

### Expected Result

I would expect the warning to go away

### Actual Result

The warning persists

### Screenshots, Videos, or Pastebins

I do get this error in the internal Nexcloud log:
`file_put_contents(/var/www/nextcloud/core/js/mimetypelist.js): Failed to open stream: Permission denied at /var/www/nextcloud/core/Command/Maintenance/Mimetype/UpdateJS.php#52 `

But the owner and permissions looks good to me

root@cloud:/var/www/nextcloud/core/js# ls -l
total 56
-rw-r----- 1 root www-data  943 Aug 20 19:56 backgroundjobs.js
-rw-r----- 1 root www-data  186 Aug 20 19:56 core.json
drwxr-x--- 2 root www-data 4096 Aug 20 19:56 login
-rw-r----- 1 root www-data   70 Aug 20 19:56 merged-template-prepend.json
-rw-r----- 1 root www-data 3633 Aug 20 19:56 mimetype.js
-rw-r----- 1 root www-data 7242 Aug 20 19:56 mimetypelist.js
drwxr-x--- 2 root www-data 4096 Aug 20 19:56 public
-rw-r----- 1 root www-data 2265 Aug 20 19:56 publicshareauth.js
-rw-r----- 1 root www-data 1479 Aug 20 19:56 select2-toggleselect.js
-rw-r----- 1 root www-data 3773 Aug 20 19:56 setupchecks.js
drwxr-x--- 3 root www-data 4096 Aug 20 19:56 tests
-rw-r----- 1 root www-data 5072 Aug 20 19:56 update.js
root@cloud:/var/www/nextcloud/core/js#

I'm getting this error on some other apps too, like draw.io

### Additional Context

Tell me if you want some more information.
I have tried -every- 'Nextcloud HUB' installation that I could find (Snap, docker-AIO, manual, Unraid)
Your script is a work of art :)

~~An aside.
I run Caddy on my OPNSense firewall, so I cant really forward port 80 and 443 to the machine I'm running your script on.
What would happen if I change the Apache ports to 81 and 444?~~
I found a way to get it through Caddy :)

I would suggest an alternative to the unsupported whiteboard app.
Excalidraw. It can run via the site or in a docker :)

### Build Version

29.0.5

### Environment

By using the scripts

### Environment Details

Ubuntu 24.04 (Clean install)
An old i7 3770k :)
16 GB ram

**Comment by enoch85** [comment]
Thanks for reporting!

> But the owner and permissions looks good to me

Yes, to me as well. Maybe this is a bug in core? Please report it in "server" instead.

> Your script is a work of art :)

<3

> I found a way to get it through Caddy :)

Nice! I would suggest using deSEC otherwise, which allows you to set a custom port.
