### ISSUE TITLE
spamhaus-drop.sh doesn't get updated

### ISSUE THREAD

**Issue by GrueneNeun** [nextcloud/vm#2659]
### Steps To Reproduce

I installed the VM some years ago (2022) and since then the URL for the spamhaus DROP list seems to have changed - indicated by an error mail I receive every now and then (I attach it as "actual result". After investigating, I found that the spamhaus-drop.sh in /var/scripts is still from 2022 while in the repo is a version from 5 months ago.

### Expected Result

spamhaus-drop.sh is automatically updated to a more recent version.

### Actual Result

Fetching 'https://www.spamhaus.org/drop/drop.lasso' ...
Fetching 'https://www.spamhaus.org/drop/edrop.lasso' ...
Flushed old rules. Applying updated Spamhaus list....
iptables v1.8.7 (nf_tables): host/network `<html> ' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<html> ' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<head><title>301' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<head><title>301' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<body> ' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<body> ' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<center><h1>301' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<center><h1>301' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `center> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `center> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `body> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `body> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `html> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `html> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<html> ' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<html> ' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<head><title>301' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<head><title>301' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<body> ' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<body> ' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<center><h1>301' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): host/network `<center><h1>301' not found Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `center> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `center> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `body> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `body> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `html> ' specified Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): invalid mask `html> ' specified Try `iptables -h' or 'iptables --help' for more information.
'Spamhaus' chain updated with latest rules.

### Build Version

Nextcloud Hub 8 (29.0.5)

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04.4 LTS

**Comment by enoch85** [comment]
Hi, thanks for reporting! 👍🏼

What happens if you reinstall the whole thing? 

1. sudo bash /var/scripts/menu.sh
2. Server Configuration
3. Extra Security

**Comment by GrueneNeun** [comment]
That updated the spamhaus-drop.sh file successfully - thanks for your quick response!

**Comment by enoch85** [comment]
I will close this issue now, but please report again if you notice it doesn't update properly.
