### ISSUE TITLE
Missing dependency for restore of borg backup

### ISSUE THREAD

**Issue by pq2** [nextcloud/vm#2660]
### Steps To Reproduce

I tried to restore a borg backup using not-supported/restore-backup.sh after upgrading to Ubuntu 24.04.

### Expected Result

The backup gets restored.

### Actual Result

The [borg mount](https://github.com/nextcloud/vm/blob/main/not-supported/restore-backup.sh#L415) command fails with the error message `borg mount not available: no FUSE support, BORG_FUSE_IMPL=pyfuse3,llfuse.` Installing `python3-pyfuse3` via `apt` fixed the issue.

### Build Version

29.0.6

### Environment

By using the scripts

### Environment Details

Ubuntu 24.04

**Comment by enoch85** [comment]
@szaimen Can you please have a look?
