### ISSUE TITLE
Nextcloud VM update.sh fails to update to Nextcloud 30

### ISSUE THREAD

**Issue by aaaskew** [nextcloud/vm#2665]
### Steps To Reproduce

1. Login as SSH root
2. run /var/scripts/update.sh

### Expected Result

Upgrade proceeds to the end and upgrades to Nextcloud 30  

### Actual Result

SHA256 checksum fails for Nextcloud 30 BZ2

### Additional Context

I hacked all of the scripts to use local copies of the scripts rather than downloading from github.

Then changed the lib.sh code SHA256 checksum to use head -n -1 rather than tail to extract the checksum. I then ran the update and it said it upgraded ok. Apache is still not giving access due to htaccess problems but that is a separate issue.

The sha256 file has two entries in it. I assume this was not the case before or the existing lib.sh code would not have worked.

My hack is not a proper fix as it is not backwards compatible. I assume a grep of the sha256 file is needed rather than head or tail?

### Build Version

29

### Environment

By downloading the VM

**Comment by eikaramba** [comment]
same problem here. using vanilla nextcloud vm instance upgrading vom 29 to 30 after receiving todays notification.

**Comment by vjatsjeslav** [comment]
Same here
![Screenshot_4](https://github.com/user-attachments/assets/9891d563-0b30-42ac-82dd-4d15e7c6c998)

**Comment by enoch85** [comment]
This is a security measure, so thank god it's actually working!

Just wait a bit, the server might be overloaded now, or the wring MD5 is uploaded by Nextcloud server team.

**Comment by aaaskew** [comment]
I am not sure it is an MD5 thing but SHA256? The lib.sh code that checks the issue is

The file content in /tmp/sha256 is

18d7a80957bb53e94fb04492f6b5213434dda3e9da12d9f789997687c8564e60  latest.tar.bz2
c44f6564b88bbdcc2895302849b921c64d8509e7888a5be435ab8c60541a0520  latest.metadata

The code is

```
# Checksum of the downloaded file
print_text_in_color "$ICyan" "Checking SHA256 checksum..."
mkdir -p "$SHA256_DIR"
curl_to_dir "$NCREPO" "$STABLEVERSION.tar.bz2.sha256" "$SHA256_DIR"
SHA256SUM="$(tail "$SHA256_DIR"/"$STABLEVERSION".tar.bz2.sha256 | awk '{print$1}')"
if ! echo "$SHA256SUM" "$STABLEVERSION.tar.bz2" | sha256sum -c
then
    msg_box "The SHA256 checksums of $STABLEVERSION.tar.bz2 didn't match, please try again."
    exit 1
fi
```

The issue is with the SHA256SUM line. Is the sha256 file changed to remove the metadata file to allow upgrades?

I thought the problem was that the tail of SHA256SUM= line would pick up the metadata file rather than the tar.bz2 file?

**Comment by enoch85** [comment]
This is fixed: https://github.com/nextcloud/vm/commit/7497b63c79e18b22826f300b8cea19038e335064

**Comment by enoch85** [comment]
To answer your question, it checks the SHA256 against the downloaded file, ie _not_ the metadata file (which has never been there from the first place, started in NC30 afaik).

**Comment by enoch85** [comment]
![image](https://github.com/user-attachments/assets/a6b5437b-db11-4f6e-b6e1-b670f89963c2)
