### ISSUE TITLE
Nextcloud VM fresh install errors seen

### ISSUE THREAD

**Issue by aaaskew** [nextcloud/vm#2667]
### Steps To Reproduce

1. Used OVA 29.0.1 HUB image
2. Ctrl+C out of initial install to correct some issues that stopped progress

- Changed interface name in netplan (Not a bug as I set interface type VirtIO)
- Correct disk size with fdisk (Not a bug as changed disks to VirtIO and imported image into zvol)
 
- /mnt/ncdata did not mount (Partially a bug/improvement needed (/etc/exports.d directory missing))

Did the following to get /mnt/ncdata to mount:
sudo bash
mkdir /etc/exports.d
zpool import -a
zfs mount -a

- Rebooted and ran install
- Bug with Locate Mirror reported
- Set manual mail relay for msmtp (Bug/improvement needed ('from' address not changeable in installer. Mail relay rejects mail if from address not the same as login name))

Manually changed from in /etc/msmtprc

- While installing saw segmentation fault in nextcloud_update.sh script. This went by too quickly. Not sure where logs would be for this.
- Let's Encrypt complained about A record not set for Nextcloud and Collabora Docker image. CNAMEs for nextcloud and office point to A record. Continued anyway.
- Install and initial update to latest Nextcloud 29 completed and rebooted.

Server showing

Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

### Expected Result

Nextcloud web interface working

### Actual Result

No access to web pages as seen in /var/log/apache2/error.log
...
[Sun Sep 15 19:58:45.122767 2024] [access_compat:error] [pid 1127:tid 133981412525760] [client x.x.x.x:50288] AH01797: client denied by server configuration: /var/www/nextcloud/index.php

### Additional Context

I also have a previous VM that has upgraded from Nextcloud 26 all the way until 29 (and also 30 manually (see other bug)) that has worked fine but the upgrade has caused this same issue as the fresh install.

Is this a CNAME vs A issue with the server? The VM is in a network behind a 80 and 443 redirect NAT.

### Build Version

29

### Environment

By downloading the VM

**Comment by enoch85** [comment]
The better option: run the OVA from scratch again and make sure not to choose any extra options. Let the script do what it's there for, and don't choose every blows and whistle during setup. Basically, just hit enter through the whole installation. :)

**Comment by aaaskew** [comment]
i will have a go with the default options will retest the issues
- /etc/exports.d directory missing
- 'from' address not changeable in installer
- saw segmentation fault in nextcloud_update.sh script

**Comment by aaaskew** [comment]
Managed to screenshot the seg fault on fresh install with no non-default options selected (apart from disabling DDNS as I have a fixed IP)

![nextcloudvminstallsqgfault](https://github.com/user-attachments/assets/3d117059-878d-4589-a606-0dcd6f09f8a4)

**Comment by enoch85** [comment]
> saw segmentation fault in nextcloud_update.sh script

You can safely ignore the segmentation faults, they are Ubuntu ones.

> /etc/exports.d directory missing 

We don't touch that. Remember it's a "minimal" install, so we only install what's nessesary. That's only needed for NFS afaik?

> 'from' address not changeable in installer 

You mean in the SMTP script setup? True, but you can edit it later in the config file.

**Comment by aaaskew** [comment]
- Good to know for the seg fault
- I assume that this due to the face that I am unpacking the OVA to install on TrueNAS Scale (I will need to send you updated docs for my TrueNAS install guide. The existing doc title should be renamed to TrueNAS Core.)
- Yes, the SMTP script setup. I have configured it manually afterwards but the improvement would be to either prompt for it or warn people if it does not work where to edit the config maybe?

The minimal install works. I now will narrow down my other failures.

**Comment by aaaskew** [comment]
All issues reported are now either fixed or have their own separate bug report.

TrueNAS Core documentation could be removed and rename the header for TrueNAS Scale to just TrueNAS as the new documentation applies to both with the new images.

**Comment by enoch85** [comment]
Perfect, thank you!
