### ISSUE TITLE
Collabora Bug when Nextcloud is installed in domain root

### ISSUE THREAD

**Issue by likeadoc** [nextcloud/vm#267]
## Steps to reproduce
1. fresh ubuntu 16.04
2. bash nextcloud_install_production.sh
3. when asked where to install the ssl certs use a domain like example.com
4. when asked to specify the path of the nextcloud install during collabora install (cloud\\.example\\.com)
enter example\\.com
5. when accessing a file in collabora an error message appears (unauthorized WOPI Host)

## Server configuration

Ubuntu 16.04 freshly installed with latest version of vm script

**Comment by enoch85** [comment]
It works here.

Did you put Nextlcoud and Collabora on the same domain?

**Comment by likeadoc** [comment]
I did it the following way:
Nextcloud - example.com
Collabora - office.example.com
During the startup script when asked to write the nextcloud domain down with backslashes example\\.com (with a single backslash.

I'm going to give it another try tommorow:)

**Comment by enoch85** [comment]
Try putting Nextcloud on a subdomain, that's "by the book".

**Comment by enoch85** [comment]
@likeadoc ping

**Comment by likeadoc** [comment]
Pronlem has been solved by clearing the dns cache:D sry for any inconvience
