### ISSUE TITLE
Upgrade to Nextcloud 30 broken

### ISSUE THREAD

**Issue by OscaAlb** [nextcloud/vm#2676]
### Steps To Reproduce

Execute update bash script
$~: sudo bash /var/scripts/menu.sh --> Update Nextcloud

### Expected Result

Update to Nextcloud 30.0.0

### Actual Result

Nextcloud instance broken

### Additional Context

The package requirements of the update script are not aligned with the requirements of Nextcloud 30.0.0 ( see PHP, Ubuntu and PostgreSQL). 

### Build Version

30.0.0

### Environment

By using the scripts, By downloading the VM

**Comment by enoch85** [comment]
Thanks for posting!

Just a quick question, do you expect us to manage your server when it comes to dependencies of the server?

**Comment by OscaAlb** [comment]
Hi thanks for reaching out to me.

No I actually don't. Yet what I expected is the bash script telling me that
the dependencies are not aligned and hence not allowing me to upgrade from
29.0.x to 30.0.0.

As far as I could see there is also no VM dump ready with the dependencies
for Nextcloud 30.0.0 available, right?

Best regards
Oscar

Am Mi., 18. Sept. 2024 um 12:37 Uhr schrieb Daniel Hansson <
***@***.***>:

**Comment by enoch85** [comment]
So can you give me a little more background? 

1. When did you first install Nextcloud with this VM?
2. OS version?
3. PHP version?
4. PostgreSQL version?
5. Any error message?
6. What do you expect should be happening in more detail?

**Comment by OscaAlb** [comment]
Hi Daniel

Sure no problem!
1. Nextcloud VM was first deployed on September 11 2023. Since then it has
been upgraded using the bash script.
2. I had Ubuntu 22.04 running.
3. I had PHP 8.1 running
4. I had PosgreSQL 14 running
5. No error messages during the update. No I get :

Internal Server Error

The server encountered an internal error and was unable to complete
your request.
Please contact the server administrator if this error reappears
multiple times, please include the technical details below in your
report.
More details can be found in the server log.

6. I updated Nextcloud 29 using your bash script without any flaws. At the
end of the update process it checked again and the script told me that it
would be upgrading to Nextcloud 30.0.0. There was no mention of any
possible issues with the dependencies so I proceeded as usual. When my
Nextcloud broke I went to check the dependencies and realised that
Nextcloud 30 requires Ubuntu 24.04 LTS, PHP 8.3 and PostgreSQL 16. I
proceeded with upgrading Ubuntu with a do-release-upgrade command and I
migrated PostgreSQL 14 to PostgreSQL 16. The Internal Server Error remains
though. The expectation would have been that the script would not be
upgrading to Nextcloud 30 since the requirements were not met. Or did I
miss a step?

Now I am trying to figure out how to rebuild the whole thing in my own
environment, hopefully without losing any data.

Best
Oscar

Am Mi., 18. Sept. 2024 um 17:00 Uhr schrieb Daniel Hansson <
***@***.***>:

**Comment by small1** [comment]
So the vm has a lock on php. did you remove that and made sure that php is intact and works ?  Have you checked the apache config to pint it to the new config?   Have you checked the apache config so you dont have any conflicting vhosts? 

If you upgraded to 30 you need to stay there. Without backups you cant downgrade.  But it is possible to fix the config so that it will start working.   I doubt that nextcloud itself is broken. But more that a config file is not right.

**Comment by enoch85** [comment]
@OscaAlb The specs you entered are valid for NC 30: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

So, it must be as @small1 is saying, check you config. We have several checks in place to prevent upgrading to an unsupported version. https://github.com/nextcloud/vm/blob/b26719d147c035bacf5a772e8c4cdcd18417f255/nextcloud_update.sh#L900

**Comment by enoch85** [comment]
Made several installations now on old servers (PHP 8.1) and it works. Closing this.
