### ISSUE TITLE
Feature request: Using IPinfo IP to Country database

### ISSUE THREAD

**Issue by abdullahdevrel** [nextcloud/vm#2682]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

I am requesting to integrate [IPinfo's IP to Country database](https://ipinfo.io/products/free-ip-database) to the project. The database has the following features:

- It is updated daily, with zero compromise to accuracy. There is no range clustering, and the database provides full accuracy.
- The data granularity reaches individual IP level.
- The database comes in MMDB database format.
- It is licensed under CC-BY-SA 4.0, permitting commercial usage.
- Available file formats include: CSV, MMDB, JSON
- The data is tabular and unnested, making it very easy to use. The dataset includes both IPv4 and IPv6 in a single file.

**Describe the solution you'd like**

I would like the NextCloud VM to switch its IP to the Country database to IPinfo's free database because it is more accurate and reliable and has more lenient licensing terms.

**Describe alternatives you've considered**
I have not considered any alternatives.

**Additional context**

## Database schema

| Field Name       | Example                      | Data Type | Description                                       |
|------------------|------------------------------|-----------|---------------------------------------------------|
| `country`        | JP                           | TEXT      | ISO 3166 country code of the location             |
| `country_name`   | Japan                        | TEXT      | Name of the country                               |
| `continent`      | AS                           | TEXT      | Continent code of the country                     |
| `continent_name` | Asia                         | TEXT      | Name of the continent                             |

Documentation: https://ipinfo.io/developers/ip-to-country-database

We also have a free database that combines country and ASN information in a single database: https://ipinfo.io/developers/ip-to-country-asn-database

Samples are available here: https://github.com/ipinfo/sample-database/tree/main/IP%20to%20Country

The database can be downloaded simply by accessing the [storage URI with an access token](https://ipinfo.io/developers/database-filename-reference).

```bash
curl -L https://ipinfo.io/data/free/country.mmdb?token=<YOUR_TOKEN> -o country.mmdb
```

Let me know what you think. Thanks

**Comment by enoch85** [comment]
@abdullahdevrel Thank for your proposal. Please check the PR and approve "attribution requirements".

**Comment by abdullahdevrel** [comment]
Hey @enoch85, thank you for considering our free database.

Could you please mention "IP address data powered by [IPinfo](https://ipinfo.io/)" in the "Special Thanks to" section of the readme (https://github.com/nextcloud/vm?tab=readme-ov-file#special-thanks-to)?

If you use our database as the primary source, we can increase the download rate to 20 downloads per day per machine.

The current download rate is 10 downloads from each unique IP address per day. Because the database is updated daily, that should be sufficient. However, if the rate limit is a concern, we can always increase it for important open-source software projects like Nextcloud/VM.

Docs: https://community.ipinfo.io/t/announcement-we-are-adding-rate-limits-to-data-downloads/358

We do not think the rate limit will ever be hit in production environments as the counts are made against unique IP addresses.

MaxMind's EULA requires end users to sign up and use their own access token. We do not have any criteria like that. You are packaging IPinfo's access token with the repo and the download happens on the user's machine using the project's specific access token. It is a zero-effort and free database.

We would really appreciate it if our database is considered as the primary database for location data. But feel free to take some time to evaluate the experience first.

**Comment by enoch85** [comment]
Thanks! Will consider it!

If we choose IP info as the sole provide, could you please add something on your website as well, like deSEC did?

![IMG_20240923_084801](https://github.com/user-attachments/assets/02e379f7-fb62-48d4-86eb-bf00f8c9b402)

**Comment by abdullahdevrel** [comment]
Hey @enoch85, 

My apologies for the late reply. We are planning to feature OSS projects that use our free database page: https://ipinfo.io/products/free-ip-database

NextCloud using our data will surely give us bragging rights so, this is major win for us and will be happy to feature NextCloud's logo. Let me know if it sounds good, and we would appreciate it if the project uses our data as the primary location data source.

**Comment by enoch85** [comment]
ccing @jospoortvliet  for the Nextcloud logo, but feel free to use this on your site: https://cloud.kafit.se/s/SdEMxM29dcMZtWH since we are behind the VM project.
