### ISSUE TITLE
During initial install the script runs but says i have no internet connection but i do?

### ISSUE THREAD

**Issue by JJDun770** [nextcloud/vm#2688]
### Steps To Reproduce

4. Click on '...'
turn it on

### Expected Result

it was supposed to install a vm with nextcloud very easy but this aint easy

### Actual Result

not working

### Screenshots, Videos, or Pastebins

im too aggravated to take pictures

### Additional Context

not a happy camper.....  thinking nextcloud might not be for me lol

### Build Version

whatever the latest is

### Environment

By downloading the VM

### Environment Details

hansonnit nextcloud vm 1tb..... this was supposed to be easy they said but i cant even get past the first step

**Comment by enoch85** [comment]
You probably have country block enabled?

**Comment by enoch85** [comment]
Closing due to no answer.
