### ISSUE TITLE
Integrity check failures and errors logged after fresh install

### ISSUE THREAD

**Issue by atusay** [nextcloud/vm#2689]
### Steps To Reproduce

Install by scripts on ubuntu 24.04
No errors during installation.

### Expected Result

Functioning Nextcloud instance without errors

### Actual Result

Multiple integrity check failures and errors logged.

**Integrity check results:**

- related_resources
	- FILE_MISSING
		- build/npm-post-build.sh
- photos
	- FILE_MISSING
		- build-js/npm-post-build.sh
- suspicious_login
	- FILE_MISSING
		- vendor/bamarni/composer-bin-plugin/.makefile/touch.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh
		- vendor/rubix/tensor/.github/workflows/ci-ext.sh
- recommendations
	- FILE_MISSING
		- build-js/npm-post-build.sh
- files_pdfviewer
	- FILE_MISSING
		- build-js/npm-post-build.sh
- twofactor_nextcloud_notification
	- FILE_MISSING
		- build-js/npm-post-build.sh

**Errors:**
[no app in context] Error: image not found: image:apps/whiteboard.svg webroot: serverroot:/var/www/nextcloud
	GET /ocs/v2.php/apps/notifications/api/v2/notifications

[core] Error: Error while running background job OCA\DAV\BackgroundJob\EventReminderJob (id: 24, arguments: null)

### Build Version

latest

### Environment

By using the scripts

**Comment by enoch85** [comment]
Remove the whiteboard app and see if it makes ant difference.

**Comment by enoch85** [comment]
Also, you could try a new install as something prova ly went very wrong during this one. This time: hit ENTER through the whole installation to choose the defaults, nothing else.

**Comment by lucbuzenval** [comment]
Hi, 
same problems with script installation with default pre-selected applications : Integrity check results and log errors.

No integrity probem with packaged VM, strange !

Best regards

**Comment by atusay** [comment]
I've tried multiple times with different options. No luck, the same errors come up. I've found a bug in the official nextcloud repo about the background job error. However, not about the others.

**Comment by rafstef** [comment]
Same problem with script and new installation

**Comment by enoch85** [comment]
I will make a new installation tonight, just to try to reproduce this.

Thanks for posting!

**Comment by OkhamG** [comment]
Hello I installed nextcloud with sctipts and a security audit asks me to close the service because the files are corrupted. Do you think it's that serious? Do you have any idea what happened? Is it a security issue?
Thanks in advance for your opinions

**Comment by tshemon** [comment]
I installed 2 servers last night, Re did one as I thought I did something wrong and got the same error no matter what I selected.
Removing and re-adding apps make no difference.

**Comment by tshemon** [comment]
Here is my list
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- photos
	- FILE_MISSING
		- build-js/npm-post-build.sh
- suspicious_login
	- FILE_MISSING
		- vendor/bamarni/composer-bin-plugin/.makefile/touch.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh
		- vendor/rubix/tensor/.github/workflows/ci-ext.sh
- recommendations
	- FILE_MISSING
		- build-js/npm-post-build.sh
- related_resources
	- FILE_MISSING
		- build/npm-post-build.sh
- calendar
	- FILE_MISSING
		- vendor/bamarni/composer-bin-plugin/.makefile/touch.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh
		- vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh
- files_pdfviewer
	- FILE_MISSING
		- build-js/npm-post-build.sh
- twofactor_nextcloud_notification
	- FILE_MISSING
		- build-js/npm-post-build.sh

Raw output
==========
Array
(
    [photos] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build-js/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )

                )

        )

    [suspicious_login] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/bamarni/composer-bin-plugin/.makefile/touch.sh] => Array
                        (
                            [expected] => d28bd83c3e865caca37e54b29e3a07879fb02e1780c4c344c6a498591fc11ceb3e927f160728811797f9fa8c7695696b169ee16cfdbe5c58568367cc4c353010
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh] => Array
                        (
                            [expected] => 5ccb610fe2c0c10d41e1ddb08ba733f0335935c3d78eff8b08fddb5897b0ba024de21ffa57244452569d67cee199a5998a607fc922a551e1e4d307082e2f214c
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh] => Array
                        (
                            [expected] => 6341889bb4ac7db801493b3a70498596c337b59786c91fa5630ebcb5e637764843c24e530b8bb258938115614b0777d642941c9e32b04b763584e37613d73459
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh] => Array
                        (
                            [expected] => 86b27023fd07647739764221036a778b86ca62a666eeba07a85a89aa3471ca5e7e3e9dce02356359b7485907600612ebd5821aade3acdbfd8c4bb03b8d3d74d3
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh] => Array
                        (
                            [expected] => 4a10e2b8829ddc18254be14793cb8f2795123effce00a2bebbd981e4a1f1a0dd6710bdce39bf6f1807508339382bbad49f7250cc0aa14c661b0a2b8e4bb6a39c
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh] => Array
                        (
                            [expected] => 53d6501288006412a99570caecfaaf83e2347d70be1e81665a70c3bcc056e487b5cd9a744c71425b91112e8bc85029d473552f59cc9fec98aeb9103069f8bb6e
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh] => Array
                        (
                            [expected] => 04a2fe8b4ca90b7a575e02959f8d48fd2b81fd95588ce53ef6fc5f351fb3a6184c5d25ee1d84fc0944e0e8bb0d16731ccb379857e25df2720979f8a0de2852f3
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh] => Array
                        (
                            [expected] => c34adbe363bb5462b207b10844d1f43d22986cfe521314224d8bea50cc23c770fee7b1601e0926d8a0877b075a2e98cdb3f73094d1e49bee6efcd03ef77872ff
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh] => Array
                        (
                            [expected] => 9160730cb306f99beac21ee9941abf1e6d6320005295e5c5658e6897625bb9fd7a47775fa62792e05376a7e89c2a2416b5941c2f66308acd258fb013faea496c
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh] => Array
                        (
                            [expected] => 10a84109f284d4dd0d3ae999efb429a977421a0f33048a63ca3c2b1bd8243414e4371a44958ff8d24e48376ce17f9203ebeccaff1d33a51eb833403e85a2b46d
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh] => Array
                        (
                            [expected] => 9fc9f67633c7d09f2b9605216f0d672eca8c0ed8f9ab824eb2cb164b76a53bfe7857a3b8a679e31a9a8a4a39a01497ee18b95190dd481a45b00dbac55ec5cac2
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh] => Array
                        (
                            [expected] => cd473f273a143ce08a8928f1040ad213a4f6b130d9d75ddf14ab6fc0fa4c6d1e41883f716267c0e8d5975f817d5074788a25ec9e85808425f1fa92ec210bb266
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh] => Array
                        (
                            [expected] => f636569c0ca7a5951b1d686b881ef45125221c2abf6b2b82fe945c5652852f9be37419ffc7e51ca8a63e516f80a5c259a37a780daa44e8aecf2b949b0af91078
                            [current] => 
                        )

                    [vendor/rubix/tensor/.github/workflows/ci-ext.sh] => Array
                        (
                            [expected] => 9b6cb083482b92051b69b5eafbb6444706592b97e7da40f8db7d4e0a9d09b22e7b0bdfcdd9a735d2e8449b31dbb27ccbc2cee57ab5bc26f2de8e35a6534175c7
                            [current] => 
                        )

                )

        )

    [recommendations] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build-js/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )

                )

        )

    [related_resources] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )

                )

        )

    [calendar] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/bamarni/composer-bin-plugin/.makefile/touch.sh] => Array
                        (
                            [expected] => d28bd83c3e865caca37e54b29e3a07879fb02e1780c4c344c6a498591fc11ceb3e927f160728811797f9fa8c7695696b169ee16cfdbe5c58568367cc4c353010
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh] => Array
                        (
                            [expected] => 5ccb610fe2c0c10d41e1ddb08ba733f0335935c3d78eff8b08fddb5897b0ba024de21ffa57244452569d67cee199a5998a607fc922a551e1e4d307082e2f214c
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh] => Array
                        (
                            [expected] => 6341889bb4ac7db801493b3a70498596c337b59786c91fa5630ebcb5e637764843c24e530b8bb258938115614b0777d642941c9e32b04b763584e37613d73459
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh] => Array
                        (
                            [expected] => 86b27023fd07647739764221036a778b86ca62a666eeba07a85a89aa3471ca5e7e3e9dce02356359b7485907600612ebd5821aade3acdbfd8c4bb03b8d3d74d3
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh] => Array
                        (
                            [expected] => 4a10e2b8829ddc18254be14793cb8f2795123effce00a2bebbd981e4a1f1a0dd6710bdce39bf6f1807508339382bbad49f7250cc0aa14c661b0a2b8e4bb6a39c
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh] => Array
                        (
                            [expected] => 53d6501288006412a99570caecfaaf83e2347d70be1e81665a70c3bcc056e487b5cd9a744c71425b91112e8bc85029d473552f59cc9fec98aeb9103069f8bb6e
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh] => Array
                        (
                            [expected] => 04a2fe8b4ca90b7a575e02959f8d48fd2b81fd95588ce53ef6fc5f351fb3a6184c5d25ee1d84fc0944e0e8bb0d16731ccb379857e25df2720979f8a0de2852f3
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh] => Array
                        (
                            [expected] => c34adbe363bb5462b207b10844d1f43d22986cfe521314224d8bea50cc23c770fee7b1601e0926d8a0877b075a2e98cdb3f73094d1e49bee6efcd03ef77872ff
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh] => Array
                        (
                            [expected] => 9160730cb306f99beac21ee9941abf1e6d6320005295e5c5658e6897625bb9fd7a47775fa62792e05376a7e89c2a2416b5941c2f66308acd258fb013faea496c
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh] => Array
                        (
                            [expected] => 10a84109f284d4dd0d3ae999efb429a977421a0f33048a63ca3c2b1bd8243414e4371a44958ff8d24e48376ce17f9203ebeccaff1d33a51eb833403e85a2b46d
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh] => Array
                        (
                            [expected] => 9fc9f67633c7d09f2b9605216f0d672eca8c0ed8f9ab824eb2cb164b76a53bfe7857a3b8a679e31a9a8a4a39a01497ee18b95190dd481a45b00dbac55ec5cac2
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh] => Array
                        (
                            [expected] => cd473f273a143ce08a8928f1040ad213a4f6b130d9d75ddf14ab6fc0fa4c6d1e41883f716267c0e8d5975f817d5074788a25ec9e85808425f1fa92ec210bb266
                            [current] => 
                        )

                    [vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh] => Array
                        (
                            [expected] => f636569c0ca7a5951b1d686b881ef45125221c2abf6b2b82fe945c5652852f9be37419ffc7e51ca8a63e516f80a5c259a37a780daa44e8aecf2b949b0af91078
                            [current] => 
                        )

                )

        )

    [files_pdfviewer] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build-js/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )

                )

        )

    [twofactor_nextcloud_notification] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build-js/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )

                )

        )

)

**Comment by enoch85** [comment]
Yep, I can confirm this on a fresh install. Super strange since we use `./occ` to make all app installs. What's even more strange is that it's affecting core apps!

Maybe this is related? https://github.com/nextcloud/server/pull/45794

For reference on the upcoming release (30.0.1): https://pastebin.com/XUMg1uwe

**Comment by enoch85** [comment]
Please add your findings here: https://github.com/nextcloud/server/issues/48773

**Comment by enoch85** [comment]
> Hello I installed nextcloud with sctipts and a security audit asks me to close the service because the files are corrupted. Do you think it's that serious? Do you have any idea what happened? Is it a security issue? Thanks in advance for your opinions

Forgot to answer this. Stay calm, it's a bug, nothing serious with this one. It's not nice, but no security risk since we know this happens on fresh installation. Would be worse if it suddenly happened on an already running setup.

**Comment by enoch85** [comment]
This is now fixed, please see PR for resolution.
