### ISSUE TITLE
Elasticsearch fails

### ISSUE THREAD

**Issue by BCofSD** [nextcloud/vm#2697]
Running the main menu script... /var/scripts/menu.sh
choose install apps
choose fulltextsearch

output is as follows:

Testing if network is OK...
Checking connection to github.com...
Downloading the Additional Apps Menu...
Downloading the FullTextSearch script...
Installing Full Text Search...
13
RAM for FullTextSearch OK! (31.30 GB)
CPU for FullTextSearch OK! (8)
Installing fulltextsearch...
vm.max_map_count = 512000
[+] Running 1/1
 ✘ elasticsearch Error manifest for docker.elastic.co/elasticsearch/elasticsearch:1.53.5 not found: manifest unknown: manifest unknown                                                    1.0s 
Error response from daemon: manifest for docker.elastic.co/elasticsearch/elasticsearch:1.53.5 not found: manifest unknown: manifest unknown
curl: (7) Failed to connect to localhost port 9200 after 0 ms: Couldn't connect to server
Waiting for ElasticSearch to come online, please don't abort...
curl: (7) Failed to connect to localhost port 9200 after 0 ms: Couldn't connect to server
Waiting for ElasticSearch to come online, please don't abort...

seems to be the TAG variable generated from the lib.sh script using a curl command.
Can't get the script to continue cleanly.

**Comment by enoch85** [comment]
Hmm..  did you try to reinstall?

**Comment by BCofSD** [comment]
I migrated from my old NC 30 machine which was one of your NC26 VM originally that had been incrementally upgraded successfully.  When I went to 30 I was experiencing issues with the App Store title page not displaying graphics and a few other minor annoyances so I figured your newest VM would be better.

I connected yourNew (NC29) VM to my Hyper-V server and ran the set up script. I imported my SQL from old instance, attached my old data drive, copied over my config.php and modified the DB section and redis section (I think I had to do that)
I then had issues with file integrity for some reason when running core check so I took a clean instance of the /var/www/nextcloud folder and just wrote it over the top of the entire installation bringing only my config.php over.

Then went about disabling or reinstalling all of my apps, hoping to just clobber my way through that part. That’s where I ran into this.
What is strange is this is the only app doing this.  I may just try migrating agin.  I have a second VM as a lab setup and I fired it up and got the same script issue which is why I contacted you.  When I post the curl command in your script, it returns 1.53.5 just as the script is getting.

I use OpenAI GPT because I have no clue how to program in bash, it came to the conclusion the issue is in lib.sh
   # Supports 0-9.0-99.0-9. Max supprted version with this function is 9.99.9. When ES 10.0.0 is out we have a problem.
    # Maybe "10\\.[[:digit:]][[:digit:]]\\.[[:digit:]]" will work?
    FULLTEXTSEARCH_IMAGE_NAME_LATEST_TAG="$(curl -s -m 900 https://www.docker.elastic.co/r/elasticsearch?limit=500 | grep -Eo "[[:digit:]]\\.[[:digit:]][[:digit:]]\\.[[:digit:]]" | sort --version-sort | tail -1)"

The current version is 8.15.3 (10 Oct 2024)
Suspiciously the 15.3 looks familiar to a malformed string.

On Nov 2, 2024, at 12:16 AM, Daniel Hansson ***@***.***> wrote:



Hmm.. did you try to reinstall?

**Comment by BCofSD** [comment]
I hardcoded 8.15.3 in place of the variable and it works.  Im guessing they changed the HTML of their page and your script grep is choking on something in the HTML
openAI keeps saying to use :latest and was trying to get hub.docker.com/_elasticsearch to work, but I kept getting blank results there too.


On Nov 2, 2024, at 9:21 AM, Brian T. Case ***@***.***> wrote:

I migrated from my old NC 30 machine which was one of your NC26 VM originally that had been incrementally upgraded successfully.  When I went to 30 I was experiencing issues with the App Store title page not displaying graphics and a few other minor annoyances so I figured your newest VM would be better.

I connected yourNew (NC29) VM to my Hyper-V server and ran the set up script. I imported my SQL from old instance, attached my old data drive, copied over my config.php and modified the DB section and redis section (I think I had to do that)
I then had issues with file integrity for some reason when running core check so I took a clean instance of the /var/www/nextcloud folder and just wrote it over the top of the entire installation bringing only my config.php over.

Then went about disabling or reinstalling all of my apps, hoping to just clobber my way through that part. That’s where I ran into this.
What is strange is this is the only app doing this.  I may just try migrating agin.  I have a second VM as a lab setup and I fired it up and got the same script issue which is why I contacted you.  When I post the curl command in your script, it returns 1.53.5 just as the script is getting.

I use OpenAI GPT because I have no clue how to program in bash, it came to the conclusion the issue is in lib.sh
   # Supports 0-9.0-99.0-9. Max supprted version with this function is 9.99.9. When ES 10.0.0 is out we have a problem.
    # Maybe "10\\.[[:digit:]][[:digit:]]\\.[[:digit:]]" will work?
    FULLTEXTSEARCH_IMAGE_NAME_LATEST_TAG="$(curl -s -m 900 https://www.docker.elastic.co/r/elasticsearch?limit=500 | grep -Eo "[[:digit:]]\\.[[:digit:]][[:digit:]]\\.[[:digit:]]" | sort --version-sort | tail -1)"

The current version is 8.15.3 (10 Oct 2024)
Suspiciously the 15.3 looks familiar to a malformed string.

On Nov 2, 2024, at 12:16 AM, Daniel Hansson ***@***.***> wrote:



Hmm.. did you try to reinstall?

**Comment by enoch85** [comment]
Well, they changed to something impossible to guess: https://www.docker.elastic.co/r/elasticsearch

So back to the drawing board...

**Comment by enoch85** [comment]
This solves it: `curl -s -m 900 https://raw.githubusercontent.com/navyau09/official-images/refs/heads/master/library/elasticsearch | grep "Tags:" | head -1 | awk '{print $2}'`

**Comment by enoch85** [comment]
Please confirm it's working @BCofSD

**Comment by BCofSD** [comment]
It is working as expected now.
