### ISSUE TITLE
Testing the scripts

### ISSUE THREAD

**Issue by eplusk** [nextcloud/vm#27]
I have tested the script in virtual machines (ubuntu-server 16.4) and they succeded.
Then I tried it with a real (old) hardware with more then one network interfaces.
see Output of lshw:
[lshw.txt](https://github.com/nextcloud/vm/files/441240/lshw.txt)

The errors could be solved with
    -  IFACE=$(lshw -c network | grep "logical name" | awk '{print $3}')
    +  IFACE=$(lshw -c network | grep "logical name" | awk '{print $3;exit}') 
        only use the first interface

in the scripts
nextcloud-startup-script.sh
nextcloud_install_production.sh
 ip.sh .
    
The server runs without any error!

Now I have some questions:
1. before you test the network Connection, you use the Connection
    nextcloud_install_production.sh
    -->    CONVER=$(wget -q https://.....
   -->     CALVER=$(wget -q https://.....
        
    it would be better to test first!

2. is there a possibility to test the type of the network connection 
    whithout disturbing the config file  /etc/network/interfaces (dhcp ore static)?

3. I think it would be better to put all the network-test and configuration together
    and afterwards make only non-disturbing tests.

Thanks Klaus

**Comment by ezraholm50** [comment]
This look promising, when we have the whole team back from vacation we'll put this up for discussion. Thank you.

**Comment by enoch85** [comment]
@eplusk Thanks for your suggestions! Do you think you could put this together in a PR?

Thanks!
