### ISSUE TITLE
documentserver_community cannot be installed

### ISSUE THREAD

**Issue by bonnepioche** [nextcloud/vm#2700]
### Steps To Reproduce

1. execute /var/scripts/menu.sh
2. Click on 'additional app', choose Document Server , Onlyoffice (integrated)
3. I have the choice between 'reinstall' or 'uninstall' (they both lead to same result)

### Expected Result

Onlyoffice is installed and running (and was working properly in version 29)

### Actual Result

Updater crashes and this is the error log:

root@nc:/var/scripts# ./menu.sh 
Running the main menu script...
Testing if network is OK...
Checking connection to github.com...
Downloading the Additional Apps Menu...
Downloading the Documentserver Menu...
Downloading the OnlyOffice (Integrated) script...
Reinstalling OnlyOffice (Integrated)...
documentserver_community is not installed
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ app:remove documentserver_community failed
Posting notification to users that are admins, this might take a while...
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!'

### Build Version

30.0.2

### Environment

By using the scripts

### Environment Details

OS: Ubuntu 22.04.5
Hardware: 16Go 4Vcpu

**Comment by TheDarkDnKTv** [comment]
I did notice it's due failure of install, as half of apps outputting: `App "Community Document Server" cannot be installed because it is not compatible with this version of the server.`

**Comment by enoch85** [comment]
> I did notice it's due failure of install, as half of apps outputting: `App "Community Document Server" cannot be installed because it is not compatible with this version of the server.`

Yeah, all apps might not be compatible when a new Nextcloud major release is out. So better to wait like 2 point releases before upgrading to be on the safe side.

@bonnepioche Just tried to install on a fresh system and as @TheDarkDnKTv is mentioning, the app isn't compatible with NC yet. Nothing to do but wait. I would suggest to uninstall OnlyOffice and get Collabora instead. Before you do that, please run 

`sudo rm -R /var/www/nextcloud/apps/documentserver_community`
