### ISSUE TITLE
Maxminddb Reinstall Failed

### ISSUE THREAD

**Issue by Antwony169** [nextcloud/vm#2701]
### Steps To Reproduce

1. Have an existing nextcloud vm server with Geoblock installed and configured
2. Update the nextcloud server via the vm scripts /var/scripts/menu.sh as root
3. Get the message "Posting 'GeoBlock needs to be reinstalled!' to: 8F3FB2EA-DCD2-4BE8-9679-EB7EADAFA336"
4. Run the /var/script/menu.sh script again. Select "Server Configuration > GeoBlock > Reinstall Geoblock"
5. Script uninstalls MaxMind and geoblock, then attempts to reinstall MaxMind and geoblock.

### Expected Result

Successfully installed GeoBlock

### Actual Result

Script fails and tells me to report to this github.

```
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
a2enmod rewrite remoteip maxminddb failed
Posting notification to users that are admins, this might take a while...
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to: 8F3FB2EA-DCD2-4BE8-9679-EB7EADAFA336
```

Edit: Console log output:
```
root@cloud:~# bash /var/scripts/menu.sh
Running the main menu script...
Testing if network is OK...
Checking connection to github.com...
Downloading the Server Configuration Menu...
Downloading the Geoblock script...
Installing GeoBlock...
No need to update /usr/share/GeoIP/IPInfo-Country.mmdb since it's newer than 1 hour.
root@cloud:~# rm /usr/share/GeoIP/IPInfo-Country.mmdb
root@cloud:~# bash /var/scripts/menu.sh
Running the main menu script...
Testing if network is OK...
Checking connection to github.com...
Downloading the Server Configuration Menu...
Downloading the Geoblock script...
Installing GeoBlock...
Downloading latest GeoIP database from https://ipinfo.io...
Repository: 'deb https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu/ jammy main'
More info: https://launchpad.net/~maxmind/+archive/ubuntu/ppa
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/maxmind-ubuntu-ppa-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/maxmind-ubuntu-ppa-jammy.list
Adding key to /etc/apt/trusted.gpg.d/maxmind-ubuntu-ppa.gpg with fingerprint F44B38CE3DB1BF64B61DBD28DE1997DCDE742AFA
Hit:1 https://repo.zabbix.com/zabbix-agent2-plugins/1/ubuntu jammy InRelease
Hit:2 https://download.docker.com/linux/ubuntu focal InRelease
Hit:3 https://repo.zabbix.com/zabbix/6.0/ubuntu jammy InRelease
Hit:4 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://packages.redis.io/deb jammy InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Get:10 https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu jammy/main amd64 Packages [1,120 B]
Get:12 https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu jammy/main Translation-en [752 B]
Fetched 19.9 kB in 2s (11.7 kB/s)
Reading package lists... Done
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻]
dpkg-query: no packages found matching apache2-dev
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libapr1-dev : Depends: libapr1 (= 1.7.0-8ubuntu0.22.04.2) but 1.7.2-2+ubuntu20.04.1+deb.sury.org+1 is to be installed
 libaprutil1-dev : Depends: libaprutil1 (= 1.6.1-5ubuntu4.22.04.2) but 1.6.3-1+ubuntu20.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking for gcc option to accept ISO C99... none needed
checking whether compiler accepts "-std=c99 -fms-extensions"... yes
checking for apxs2... no
checking for apxs... no
configure: error: apxs not found. set apxs with --with-apxs.
Module rewrite already enabled
Module remoteip already enabled
ERROR: Module maxminddb does not exist!
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
a2enmod rewrite remoteip maxminddb failed
Posting notification to users that are admins, this might take a while...
Sending 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to admin@acme.com
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to: 8F3FB2EA-DCD2-4BE8-9679-EB7EADAFA336
```

The email received says:
`a2enmod rewrite remoteip maxminddb failed`

### Build Version

29.0.9.2

### Environment

By using the scripts

### Environment Details

Operating System: Ubuntu 22.04.5 LTS
RAM: 16GB
CPU Cores: 4
Hypervisor: VMware

**Comment by enoch85** [comment]
Hi,

Thanks for posting your issue. May I ask what you external IP is? I'm asking because there's a limit on how many installa there is per day.

You could try to uninstall everything (not reinstall) then wait for 36 hours and try to install it again.

The output of 'ls -l /usr/share/GeoIP' would also be interesting.

Thanks!

**Comment by Antwony169** [comment]
It isn't an issue with Maxmind being downloaded. It is something with Apache modules.

Here is the output of 'ls -l /usr/share/GeoIP/'
`total 39188
-rw-r--r-- 1 root root 40123944 Nov 13 09:12 IPInfo-Country.mmdb`

I should have included the log output of from the console:
`root@cloud:~# bash /var/scripts/menu.sh
Running the main menu script...
Testing if network is OK...
Checking connection to github.com...
Downloading the Server Configuration Menu...
Downloading the Geoblock script...
Installing GeoBlock...
No need to update /usr/share/GeoIP/IPInfo-Country.mmdb since it's newer than 1 hour.
root@cloud:~# rm /usr/share/GeoIP/IPInfo-Country.mmdb
root@cloud:~# bash /var/scripts/menu.sh
Running the main menu script...
Testing if network is OK...
Checking connection to github.com...
Downloading the Server Configuration Menu...
Downloading the Geoblock script...
Installing GeoBlock...
Downloading latest GeoIP database from https://ipinfo.io...
Repository: 'deb https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu/ jammy main'
More info: https://launchpad.net/~maxmind/+archive/ubuntu/ppa
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/maxmind-ubuntu-ppa-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/maxmind-ubuntu-ppa-jammy.list
Adding key to /etc/apt/trusted.gpg.d/maxmind-ubuntu-ppa.gpg with fingerprint F44B38CE3DB1BF64B61DBD28DE1997DCDE742AFA
Hit:1 https://repo.zabbix.com/zabbix-agent2-plugins/1/ubuntu jammy InRelease
Hit:2 https://download.docker.com/linux/ubuntu focal InRelease
Hit:3 https://repo.zabbix.com/zabbix/6.0/ubuntu jammy InRelease
Hit:4 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://packages.redis.io/deb jammy InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Get:10 https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu jammy/main amd64 Packages [1,120 B]
Get:12 https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu jammy/main Translation-en [752 B]
Fetched 19.9 kB in 2s (11.7 kB/s)
Reading package lists... Done
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻]
dpkg-query: no packages found matching apache2-dev
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libapr1-dev : Depends: libapr1 (= 1.7.0-8ubuntu0.22.04.2) but 1.7.2-2+ubuntu20.04.1+deb.sury.org+1 is to be installed
 libaprutil1-dev : Depends: libaprutil1 (= 1.6.1-5ubuntu4.22.04.2) but 1.6.3-1+ubuntu20.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking for gcc option to accept ISO C99... none needed
checking whether compiler accepts "-std=c99 -fms-extensions"... yes
checking for apxs2... no
checking for apxs... no
configure: error: apxs not found. set apxs with --with-apxs.
Module rewrite already enabled
Module remoteip already enabled
ERROR: Module maxminddb does not exist!
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
a2enmod rewrite remoteip maxminddb failed
Posting notification to users that are admins, this might take a while...
Sending 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to admin@acme.com
Posting 'Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!' to: 8F3FB2EA-DCD2-4BE8-9679-EB7EADAFA336`

And the email sent says:
`a2enmod rewrite remoteip maxminddb failed`

**Comment by Antwony169** [comment]
I have gone back through and installed the expected versions for the following packages:
libapr1=1.7.0-8ubuntu0.22.04.2
libapr1-dev=1.7.0-8ubuntu0.22.04.2
libaprutil1=1.6.1-5ubuntu4.22.04.2
libaprutil1-dev=1.6.1-5ubuntu4.22.04.2

Then I re-ran the script after removing GeoIP db from /usr/share/GeoIP/

`root@cloud:# bash /var/scripts/menu.sh
Running the main menu script...
Testing if network is OK...
Checking connection to github.com...
Downloading the Server Configuration Menu...
Downloading the Geoblock script...
Installing GeoBlock...
Downloading latest GeoIP database from https://ipinfo.io...
Repository: 'deb https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu/ jammy main'
More info: https://launchpad.net/~maxmind/+archive/ubuntu/ppa
Adding repository.
Found existing deb entry in /etc/apt/sources.list.d/maxmind-ubuntu-ppa-jammy.list
Adding deb entry to /etc/apt/sources.list.d/maxmind-ubuntu-ppa-jammy.list
Found existing deb-src entry in /etc/apt/sources.list.d/maxmind-ubuntu-ppa-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/maxmind-ubuntu-ppa-jammy.list
Adding key to /etc/apt/trusted.gpg.d/maxmind-ubuntu-ppa.gpg with fingerprint F44B38CE3DB1BF64B61DBD28DE1997DCDE742AFA
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 https://repo.zabbix.com/zabbix-agent2-plugins/1/ubuntu jammy InRelease
Hit:3 https://download.docker.com/linux/ubuntu focal InRelease
Hit:4 https://repo.zabbix.com/zabbix/6.0/ubuntu jammy InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:9 https://packages.redis.io/deb jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/maxmind/ppa/ubuntu jammy InRelease
Reading package lists... Done
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻]
dpkg-query: no packages found matching apache2-dev
[⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻⣾⣽⣻]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apache2-data apache2-utils libasn1-8-heimdal libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal libhx509-5-heimdal libkrb5-26-heimdal libldap-2.4-2 liblua5.3-0
  libroken18-heimdal libwind0-heimdal
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  apache2-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 191 kB of archives.
After this operation, 1,078 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 apache2-dev amd64 2.4.52-1ubuntu4.12 [191 kB]
Fetched 191 kB in 1s (376 kB/s)
Selecting previously unselected package apache2-dev.
(Reading database ... 253930 files and directories currently installed.)
Preparing to unpack .../apache2-dev_2.4.52-1ubuntu4.12_amd64.deb ...
Unpacking apache2-dev (2.4.52-1ubuntu4.12) ...
Setting up apache2-dev (2.4.52-1ubuntu4.12) ...
Processing triggers for man-db (2.10.2-1) ...
Scanning processes...
Scanning candidates...
Scanning linux images...

Running kernel seems to be up-to-date.

Restarting services...
 systemctl restart containerd.service

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking for gcc option to accept ISO C99... none needed
checking whether compiler accepts "-std=c99 -fms-extensions"... yes
checking for apxs2... /usr/bin/apxs2
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking maxminddb.h usability... yes
checking maxminddb.h presence... yes
checking for maxminddb.h... yes
checking for MMDB_lib_version in -lmaxminddb... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: executing depfiles commands
Making install in src
make[1]: Entering directory '/tmp/mod_maxminddb-1.2.0/src'
make[2]: Entering directory '/tmp/mod_maxminddb-1.2.0/src'
/usr/bin/apxs2 -c  -lmaxminddb  -Wc,"-g -O2 -std=c99 -fms-extensions"  mod_maxminddb.c
/usr/share/apr-1.0/build/libtool  --mode=compile --tag=disable-static x86_64-linux-gnu-gcc -prefer-pic -pipe -g -O2 -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security  -Wdate-time -D_FORTIFY_SOURCE=2   -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/usr/include/apache2  -I/usr/include/apr-1.0   -I/usr/include/apr-1.0 -I/usr/include -g -O2 -std=c99 -fms-extensions  -c -o mod_maxminddb.lo mod_maxminddb.c && touch mod_maxminddb.slo
libtool: compile:  x86_64-linux-gnu-gcc -pipe -g -O2 -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DLINUX -D_REENTRANT -D_GNU_SOURCE -I/usr/include/apache2 -I/usr/include/apr-1.0 -I/usr/include/apr-1.0 -I/usr/include -g -O2 -std=c99 -fms-extensions -c mod_maxminddb.c  -fPIC -DPIC -o .libs/mod_maxminddb.o
/usr/share/apr-1.0/build/libtool  --mode=link --tag=disable-static x86_64-linux-gnu-gcc -Wl,--as-needed -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro -Wl,-z,now    -o mod_maxminddb.la  -lmaxminddb -rpath /usr/lib/apache2/modules -module -avoid-version    mod_maxminddb.lo
libtool: link: x86_64-linux-gnu-gcc -shared  -fPIC -DPIC  .libs/mod_maxminddb.o   -lmaxminddb  -Wl,--as-needed -Wl,-Bsymbolic-functions -flto=auto -Wl,-z -Wl,relro -Wl,-z -Wl,now   -Wl,-soname -Wl,mod_maxminddb.so -o .libs/mod_maxminddb.so
libtool: link: ( cd ".libs" && rm -f "mod_maxminddb.la" && ln -s "../mod_maxminddb.la" "mod_maxminddb.la" )
/usr/bin/apxs2 -i -a -n maxminddb .libs/mod_maxminddb.so
/usr/share/apache2/build/instdso.sh SH_LIBTOOL='/usr/share/apr-1.0/build/libtool' .libs/mod_maxminddb.so /usr/lib/apache2/modules
/usr/share/apr-1.0/build/libtool --mode=install install .libs/mod_maxminddb.so /usr/lib/apache2/modules/
libtool: install: install .libs/mod_maxminddb.so /usr/lib/apache2/modules
install: cannot create regular file '/usr/lib/apache2/modules': No such file or directory
apxs:Error: Command failed with rc=65536
.
make[2]: *** [Makefile:408: install-exec-local] Error 1
make[2]: Leaving directory '/tmp/mod_maxminddb-1.2.0/src'
make[1]: *** [Makefile:292: install-am] Error 2
make[1]: Leaving directory '/tmp/mod_maxminddb-1.2.0/src'
make: *** [Makefile:336: install-recursive] Error 1
/var/scripts/geoblock.sh: line 103: apachectl: command not found`

**Comment by enoch85** [comment]
Sorry, just made a fresh installation, and it works, so I don't know how to solve this one. Sorry.

**Comment by enoch85** [comment]
And just made a reinstall which replaced Maxminds DB with IPinfo, both are working ---> Closing.
