### ISSUE TITLE
Trouble installing postgresql

### ISSUE THREAD

**Issue by hffej01** [nextcloud/vm#2705]
### Steps To Reproduce

This install script get to the postgresql install....and than this error happens.  The script is from the Nextcloud/Linux page.

Running on Ubuntu 24.04  most current version of Nextcloud from script.  see below for script location.

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!

sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=nextcloud_db_user --database-pass=#esmYHJcWI7efsc6Qfjzt8vktt --admin-user=ncadmin --admin-pass=nextcloud failed

### Expected Result

to install Nextcloud and run it

### Actual Result

this error code appeared ...

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!

sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=nextcloud_db_user --database-pass=#esmYHJcWI7efsc6Qfjzt8vktt --admin-user=ncadmin --admin-pass=nextcloud failed

  There are no commands defined in the "app" namespace.
Nextcloud is not installed - only a limited number of commands are available

### Build Version

30

### Environment

By using the scripts, By downloading the VM

### Environment Details

Ubuntu 24.04
cores =4
Ram 10144

Install script used to install  Nextcloud

https://github.com/nextcloud/vm/blob/main/nextcloud_install_production.sh/

**Comment by enoch85** [comment]
Hmm, will do a test installation when I have time.

**Comment by hffej01** [comment]
I found this error as well


Error while trying to create admin account: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user"
connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "nextcloud_db_user"
Trace: #0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1939): Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert

**Comment by enoch85** [comment]
Hmm, is this on a 100% clean Ubuntu server with internet connection working?

**Comment by hffej01** [comment]
Question:  I am running firewalld, instead of UFW.  Do I need to open a certain for that to work ?   Sorry, I just thought about that...



    On Saturday, November 30, 2024 at 01:33:37 AM CST, Daniel Hansson ***@***.***> wrote:  
 
 


Hmm, is this on a 100% clean Ubuntu server with internet connection working?

**Comment by enoch85** [comment]
@hffej01 I will make a fresh install now. Will let you know about the result. 

Regarding ports, you need like HTTP, HTTP, NTP, and DNS - **OUT**. Then HTTP and HTTPS  - **IN** (if you need it publicly available).

**Comment by enoch85** [comment]
Just installed without any issues at all.

Link expires in 3 hours: https://cloud.danielhansson.nu/s/oxaYH49ftYJXM6G

**Comment by hffej01** [comment]
Three different browsers...all timed out.  
    On Saturday, November 30, 2024 at 01:58:42 PM CST, Daniel Hansson ***@***.***> wrote:  
 
 


Just installed without any issues at all.

Link expires in 3 hours: https://cloud.danielhansson.nu/s/oxaYH49ftYJXM6G

**Comment by enoch85** [comment]
Please download it instead.

**Comment by hffej01** [comment]
Just to let you know that it installed, and runs great.
Thank you,Jeff



    On Saturday, November 30, 2024 at 04:06:45 PM CST, Daniel Hansson ***@***.***> wrote:  
 
 


Please download it instead.
