### ISSUE TITLE
lets encrypt

### ISSUE THREAD

**Issue by DonnyHansen** [nextcloud/vm#2708]
Going through the setup scripts, getting to lets encrypt, I get failed attempts and doesn't get a reply from lets encrypt for the cert.

Any thoughts?

**Comment by enoch85** [comment]
Yeah, disable country blocking. :)

**Comment by enoch85** [comment]
@DonnyHansen Did disabling country blocking solve your issue?

**Comment by DonnyHansen** [comment]
No, it was my firewalls intrusion prevention
