### ISSUE TITLE
Documentation Webpage 502 Error

### ISSUE THREAD

**Issue by myspie55** [nextcloud/vm#2710]
### Steps To Reproduce

1. Go to 'https://docs.hanssonit.se/'

### Expected Result

View documentation

### Actual Result

502 Bad Gateway error

### Screenshots, Videos, or Pastebins

![Image](https://github.com/user-attachments/assets/f6119e1b-a81f-4adc-bd2b-1bcc78305571)

### Build Version

latest

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Thanks! Will have a look later today!

**Comment by enoch85** [comment]
Issue is fixed, sorry for the delay!
