### ISSUE TITLE
Script goes into passwd change loop

### ISSUE THREAD

**Issue by MrWessley** [nextcloud/vm#275]
## Steps to reproduce
1.Start the script as root
2.add user within the script
3.nearly at the end of the script the password should be changed for security reasons, because it doesn't recognize any user it just goes into a loop...

## Expected behaviour
Script should change password end come to an end

## Actual behaviour
Tell us what happens instead

## Server configuration

**Server version:** Ubuntu 16.4. Nextcloud 12
**VM version** (master / released version)

**Updated from an older installed version or fresh install:** fresh

## Network
**Do you use DHCP?** VPS with static IP

**Is port 80 and/or 443 open?** yes

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
@MrWessley Thanks! Which script are you talking about? 

Did you change the user before you ran the script or did you just add a random user as a variable in the script?

**Comment by enoch85** [comment]
Also, what's the output of: echo $SUDO_USER

**Comment by MrWessley** [comment]
I startet with Root User Followed the Script add a sudo User and in the Script
i was asked to Login the new User
the Script Shows that it will now Executive everything with the new sudo User

**Comment by enoch85** [comment]
You say "the script". There are like 30 scripts, which one do you mean??

**Comment by MrWessley** [comment]
There is no output

**Comment by enoch85** [comment]
@MrWessley Sorry, can't help you if you don't give me the name of the script.

Did you follow the instructions? Everything works here.

**Comment by MrWessley** [comment]
I just Started the Main Nextcloud_install_production.sh Script

**Comment by enoch85** [comment]
Please join IRC so that we can chat there: https://webchat.freenode.net/?channels=techandme

**Comment by enoch85** [comment]
@MrWessley Join again, I saw you but you quit.

**Comment by enoch85** [comment]
@MrWessley You left again...? 

Please follow the intructions and it will work. I tried it myself like 100 times. https://github.com/nextcloud/vm#installation

**Comment by MrWessley** [comment]
I used the Instructions in the readme but these 4 Points didn't help me, sorry!

**Comment by MrWessley** [comment]
I think i find my fault, just fail to read... Sorry and Thank YOU
