### ISSUE TITLE
Changing MARIADB root password failed

### ISSUE THREAD

**Issue by hammeractual** [nextcloud/vm#276]
## Steps to reproduce
1.  Fresh install Nextcloud VM from this link [https://cloud.techandme.se/s/lTjoMr5smSYHIiM/download?path=%2F&files=Nextcloud_Community_VM_PRODUCTION.rar](url)
2. System asked to input password for MySQL

## Expected behaviour
Password input successfully and setup continue as normal

## Actual behaviour
There is an Error "grep: /root/.my.cnf : No such file or directory".
Type a password <enter> but an error occurred, Thrown an error "Changing MARIADB root password failed. Your old password is : "

## Server configuration
Ubuntu 16.04.2
Ubuntu 16.04 VMDK
Fresh Install

## Network
Use DHCP
Port 80&443 are open

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots

http://imgur.com/a/6YAG9

**Comment by enoch85** [comment]
Is this this VM: https://github.com/nextcloud/vm/releases/tag/12.0.0 ?

`/root/.my.cnf` was introduced in 12.0.0 and before that we used `/var/mysql_password.txt` to store the password, so either you are using an old VM (which you shouldn't when doing a fresh install) or you are running the setup script on an old VM when really you should run the `update.sh` script.  

I tested this as late as yesterday and it worked on the newest VM. I also tested to update from an old VM (as if you were using an old VM an updated to a new with the update script, and is also worked. so this is not an issue.

**Comment by enoch85** [comment]
And btw, the link doesn't work....

**Comment by hammeractual** [comment]
Oh... Thanks for the explanation.
Now I know why my issue here [https://github.com/nextcloud/vm/issues/256](url) was happened.
I did clean install with your latest VM on that site, update the vm using update.sh script and then my Nextcloud upgraded to 12.
Thanks for the hardwork.

Btw, may I know how to install Nextant in Nextcloud on this VM?
Thanks.

**Comment by enoch85** [comment]
Glad you worked it out.
