### ISSUE TITLE
ERROR: Site nextcloud_ssl_domain does not exist!

### ISSUE THREAD

**Issue by jsahoka** [nextcloud/vm#28]
Hey,
I just downloaded and installed the VM.
The letsencrypt portion of the installer does not seem to work.
This is the last output of the script : 

> **Enabling site 000-default.
> To activate the new configuration, you need to run:
>   service apache2 reload
> 
> Apache will now reboot
> 
> Press any key to continue...
> ERROR: Site nextcloud_ssl_domain does not exist!
> Site nextcloud_ssl_domain_self_signed already disabled

Could it have something to do with this : 

> 
> +---------------------------------------------------------------+
> |    Please enter the domain name you will use for Nextcloud:   |
> |    Like this: example.com, or nextcloud.example.com (1/2)     |
> +---------------------------------------------------------------+
> 
> nc.XXXX.com
> 
> Is this correct? nc.XXXX.com ([y]es or [N]o): y
> /etc/apache2/sites-available/.conf was successfully created
> 

It seems to create a .conf without a filename? Is that supposed to be nextcloud_ssl_domain.conf?

My knowledge of linux and apache is quite underwhelming so I might also be scrwewing something up here. 
Thanks in advance.

**Comment by jsahoka** [comment]
Also, after the script exits it seems that activate-ssl.sh gets deleted, is that by design?

**Comment by invader303** [comment]
so i have had the same Problem with two deployments i did within the last few days but got it fixed after some searching around.

what i did:

- cd /etc/apache2/sites-available
- nano nextcloud_ssl_domain_self_signed.conf and change at the end the following 
![image](https://cloud.githubusercontent.com/assets/21998250/18239011/8510a644-7342-11e6-9afb-911049346304.png)
- save as nextcloud_ssl_domain.conf
- a2ensite nextcloud_ssl_domain.conf
- Service apache2 reload

that should do the trick. good luck

**Comment by jsahoka** [comment]
I was able to fix it by issuing :
sudo cp .conf nextcloud_ssl_domain.conf

**Comment by Pe46dro** [comment]
The `ssl_conf` variable is defined before the definition of `domain` variable. It should be defined at line 168

**Comment by enoch85** [comment]
Make a PR please. Thank you!

**Comment by ezraholm50** [comment]
#31 

Just ran the installer without any problems. Will investigate it...

**Comment by enoch85** [comment]
@all Please test with now when the PR is merged, thanks!

**Comment by enoch85** [comment]
I did some tests today and activate-ssl.sh seems to work, thouch I'm not yet sure about test-config.sh. But let's close this issue as the fix is merged. In case of further issues we can reopen this.
