### ISSUE TITLE
How to clean uninstall failed Nextant install?

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/vm#287]
Nextant failed to install properly about 3 weeks ago. You seem to have fixed the issue 2 weeks ago. I tried to install again, but it said it was already installed, despite it failing. Please provide instructions to clean uninstall. I am using the VM provided by this repo about 3 weeks ago. Nextcloud 12. Ubuntu 16.04, I think.
I googled for an answer but from what I saw, people weren't too sure how to uninstall or the people who gave clear instructions were for older versions of either solr or ubuntu 14.04 and didn't work with my installation. Please Advise.

**Comment by Ark74** [comment]
We are still missing idempotence on the scripts, sorry but this will require time to invest and develop on nextant specifically it requires a little more since it uses also the installer from third source (Solr engine).

You are welcome to study this issue.

**Comment by BetaLeaf** [comment]
I'm still a linux newbie. I doubt I can be helpful in any way, but if the support is lacking, I suppose I could give it a go.

**Comment by enoch85** [comment]
@BetaLeaf You learn while you try. ;)

**Comment by enoch85** [comment]
On topic: it's always good to take a snapshot before you install stuff or make modifications of the VM in case anything would go wrong.

**Comment by enoch85** [comment]
Maybe @daita knows how to solve this?

**Comment by enoch85** [comment]
ping @daita

**Comment by daita** [comment]
regarding Nextant itself, you should try:

>      ./occ config:app:delete nextant configured

If it is about Solr, you should remove the folder it installed manually.

**Comment by enoch85** [comment]
OK thanks! 

@BetaLeaf What he said. --^

**Comment by BetaLeaf** [comment]
The nextant app is easy to remove. This was more about Solr. How do I find the folder it was installed into to remove it?

**Comment by enoch85** [comment]
@BetaLeaf Run `sudo locale solr"
