### ISSUE TITLE
IP address does not change during install

### ISSUE THREAD

**Issue by wizdude** [nextcloud/vm#30]
by default the VM picks up a DHCP address during install. you are given the opportunity to edit the interfaces file where you can define a different IP address, however this never gets used.

i noticed when the letsencrypt setup started to run that it was using the wrong internal IP address for my box. i opened another console session and confirmed that the interfaces file had the correct information. i did a "service networking restart" and this didn't fix the issue - the IP was still the original DHCP assigned one.

i had to manually set the IP address using ifconfig. once I did this i was able to "service networking restart" and the correct IP address was present.

i was on my second attempt (of the three attempts it says I have) to setup letsencrypt, but then i was prompted which site configuration to use. i selected (obviously incorrectly) the first "000-default" and the setup completed successfully, however when i browse to the IP of the box i just get an "index of" and no nextcloud login page.

i have no understanding why the IP didn't change dshow ruuring the setup. all i did was change the last octet of the IP as it was in the interfaces file.

unsure if perhaps the interface could be fully flushed during the setup or similar.

i was running the VM under vSphere 5.5.

**Comment by ezraholm50** [comment]
What NIC settings have you applied in vSphere Nat, briged?

**Comment by wizdude** [comment]
vSphere doesn’t have NAT. The interface is directly bridged to my production LAN. The DHCP address is on the same network where I want the static address to be. The static address is outside of the allocated DHCP range.

**Comment by enoch85** [comment]
Just as a short notice, the address you enter manually in interfaces IS used, though the VM have to restart before it's getting used to get allocated correctly.

We could try to restart the whole interface, but I'll have to look into this when I'm back from vaccation. 

@wizdude Thanks for letting us know!

**Comment by wizdude** [comment]
@enoch85 i'd be very happy for the letsencrypt section to be broken into a second part. it's a little frustrating that if you mess this bit up, you essentially need to start from scratch. having a reboot and then letsencrypt as a second section would be good.

it would also be good to implement an easy way to enable/import SSL with your own certs. while i love letsencrypt to pieces, i do actually have valid SSL certs for my nextcloud box already. perhaps this could be done by skipping SSL altogether during the install and then a nice method of importing the certificates into the VM.

**Comment by enoch85** [comment]
Why use your own certs when Let's Encrypt is free, and in my opinion better than "valid certs"?

We won't script an import of existing scripts, at least not in the near future. You (as a user) should know some Apache at least, and making a script for importing (that might fail in many various ways) takes ALOT more effort than simply 'cp' your files into the server and link them in your vhost.

Moving the Let's Encrypt part to after a reboot is one way to handle it, sure. But there must be a even better way. I'll investigate when I'm back. :)

**Comment by wizdude** [comment]
I love Let’s Encrypt and use it wherever I can, however it’s a DV SSL. If your organisation has an EV SSL cert they may prefer to use this.

 

Anyway – point taken re change Apache configuration. No problems with that. 

 

Let us know when you’ve returned and worked out the rest.

 

cheers, wizdude J

**Comment by enoch85** [comment]
@wizdude I'm back from vacation but I can't find a way to solve this in a nice way (which means that the user doesn't have to do anything manually to get SSL). Your issue is somewhat specific and I'm sorry, but we can't cover exactly ALL use-cases even if we really want to. 

I have now added a restart of the network after changes in the interfaces file, and I hope that it solves this issue. Feel free to create a new VM and run the scripts from start to test it, it would be very appreciated.

Thanks!

**Comment by enoch85** [comment]
Just tested this and it seems to work, please reopen if that shouldn't be the case. 

Thanks!
