### ISSUE TITLE
Nextcloud v11.0.3 to v12 Something went wrong with copying your mysql password to /root/.my.cnf.

### ISSUE THREAD

**Issue by time24** [nextcloud/vm#300]
## Steps to reproduce
1. Login as admin 
2. run script /var/scripts/update.sh

## Expected behaviour
Tell us what should happen

Update v11.0.3 to v12

## Actual behaviour
Tell us what happens instead

root@kunden:~# /var/scripts/update.sh
[|] E: Failed to fetch http://artfiles.org/ubuntu.com/dists/xenial-updates/universe/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 80.252.110.38 80]
E: Failed to fetch http://artfiles.org/ubuntu.com/dists/xenial-security/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 80.252.110.38 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Trying to upgrade the Redis Pecl extenstion...
Nothing to upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.8.0-34-generic
Found initrd image: /boot/initrd.img-4.8.0-34-generic
done
Latest release is: 12.0.0. Current version is: 11.0.3.
New version available! Upgrade continues...
Something went wrong with copying your mysql password to /root/.my.cnf.
Please report this issue to https://github.com/nextcloud/vm/issues, thanks!

## Server configuration

**Windows Server 2012 R2:** (see your admin page)

**VM version** (master / released version)

Version 5.0

**Updated from an older installed version or fresh install:**

Nextcloud v11.0.3 to v12

## Network
**Do you use DHCP?**
FIXED IP
**Is port 80 and/or 443 open?**
444
#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```
root@kunden:~# /var/ncdata/nextcloud.log
-bash: /var/ncdata/nextcloud.log: Permission denied

#### Installation log (command output)
```
Insert the CLI output here
```
Sorry I'm new and I don't know how/where to get the CLI

**Comment by enoch85** [comment]
Thanks for reporting!

Can you do: `cat /var/mysql_passqord.txt` and `cat /root/.my.cnf`

**Comment by enoch85** [comment]
I just tested a 11.0.3 VM and it worked as expected.

```
Latest release is: 12.0.0. Current version is: 11.0.3.
New version available! Upgrade continues...
Please restart the upgrade process, we fixed the password file /root/.my.cnf.
root@nextcloud:/var/scripts# cat /var/mysql_password.txt 
Wb39Ci293u*WIbHP2OqPsE8YROR
root@nextcloud:/var/scripts# cat /root/.my.cnf 
[client]
password='Wb39Ci293u*WIbHP2OqPsE8YROR'
root@nextcloud:/var/scripts# 
```

Which version was the VM you first downloaded?

**Comment by time24** [comment]
Thank you for the fast response, I will test it

**Comment by time24** [comment]
Looks like no such found

ncadmin@kunden:~$ sudo /var/scripts/update.sh
[sudo] password for ncadmin:
Sorry, try again.
[sudo] password for ncadmin:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Trying to upgrade the Redis Pecl extenstion...
Nothing to upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.8.0-34-generic
Found initrd image: /boot/initrd.img-4.8.0-34-generic
done
Latest release is: 12.0.0. Current version is: 11.0.3.
New version available! Upgrade continues...
Something went wrong with copying your mysql password to /root/.my.cnf.
Please report this issue to https://github.com/nextcloud/vm/issues, thanks!
ncadmin@kunden:~$ /var/scripts# cat /var/mysql_password.txt
-bash: /var/scripts#: No such file or directory
ncadmin@kunden:~$ /var/scripts# cat /root/.my.cnf
-bash: /var/scripts#: No such file or directory
ncadmin@kunden:~$ ^C
ncadmin@kunden:~$ /var/scripts# cat /var/mysql_password.txt
-bash: /var/scripts#: No such file or directory

**Comment by enoch85** [comment]
OK, then you need to create `/root/.my.cnf` with your DB password. Like this:

```
[client]
password='SUPERSECRETPASSWORD'
```

Nothing that I can do and the scripts works as I just tested.

**Comment by time24** [comment]
I'm the only admin and I can't access the directory? Can you help?

ncadmin@kunden:~$ cat /root/.my.cnf
cat: /root/.my.cnf: Permission denied

**Comment by enoch85** [comment]
If you want to create a new file, type nano instead of cat.

**Comment by time24** [comment]
Thanks, that worked. But after that this is happening...

Latest release is: 12.0.0. Current version is: 11.0.3.
New version available! Upgrade continues...
Checking latest released version on the Nextcloud download server and if it's possible to download...
nextcloud-12.0.0.tar.bz2                                  100%[====================================================================================================================================>]  39.81M  9.84MB/s    in 4.3s
Backing up files and upgrading to Nextcloud 12.0.0 in 10 seconds...
Press CTRL+C to abort.
Backing up data...

Backup OK!
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
Doing mysqldump of all databases...
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect
root@kunden:~#

**Comment by time24** [comment]
Looks like the password is wrong, but we never used any other one. Is there a way to reset this password?

**Comment by enoch85** [comment]
Do you know your MySQL root password? That's the one you must use.
