### ISSUE TITLE
problem with the update-script

### ISSUE THREAD

**Issue by torbentt** [nextcloud/vm#302]
Hello,
i have some problems with the update-script.
I have used the following command:
_sudo bash /var/scripts/update.sh_

This error message appears:

_Latest release is: 12.0.0. Current version is: 11.0.3.
New version available! Upgrade continues...
Something went wrong with copying your mysql password to /root/.my.cnf.
Please report this issue to https://github.com/nextcloud/vm/issues, thanks!_

Any ideas? 

Thanks!
Torben

**Comment by enoch85** [comment]
@torbentt Thanks for letting me know, this seems like a bug of some kind.

Please check here: https://github.com/nextcloud/vm/issues/300

Also, which version was the first version you installed?

**Comment by enoch85** [comment]
@torbentt I actually want to check your system prior to the upgrade. Would it be possible to connect to your system after you reverted to your old backup?

**Comment by enoch85** [comment]
fixed
