### ISSUE TITLE
letsencryptrenew.sh log shows certbot not installed

### ISSUE THREAD

**Issue by kzieres61** [nextcloud/vm#307]
## Steps to reproduce
1. run the letsencryptrenew.sh with sudo bash -x /var/scripts/letsencryptrenew.sh

## Expected behavior

It SHOULD autorenew the letenscrypt SSL certs for the server
## Actual behavior

the command fails and when looking at the /var/log/letsencrypt/renew.log I get an error that says the certbot command does not exist

## Server configuration

**Server version:** (see your admin page)
System hostname	
Operating system	Ubuntu Linux 16.04.1
Webmin version	1.831
Time on system	Sat Jul 22 14:21:17 2017
Kernel and CPU	Linux 4.4.0-31-generic on x86_64
Processor information	Intel(R) Core(TM) i5 CPU M 540 @ 2.53GHz, 2 cores
System uptime	0 hours, 7 minutes
Running processes	205
CPU load averages	0.04 (1 min) 0.20 (5 mins) 0.12 (15 mins)
CPU usage	0% user, 1% kernel, 0% IO, 99% idle
Real memory	355.64 MB used, 1.95 GB total

Virtual memory	0 bytes used, 2 GB total

Local disk space	4.95 GB used, 47.11 GB total

Package updates	122 package updates are available

**VM version** (master / released version)
VM Workstation 12 player
**Updated from an older installed version or fresh install:**
fresh install

## Network
**Do you use DHCP?**
no static ip
**Is port 80 and/or 443 open?**
yes and forwarded to the proper VM client
#### Screenshoots

http://imgur.com/a/szskP  Error when running command
http://imgur.com/a/olHze  What log shows

and it was recently told to me that if certbot command is not there then I must have installed letsencrypt by not using the activate-ssl.sh script. However, when I look at the /var/scripts i only see activate-ssl_backup.sh. (there's more files in there just not the activate-ssl one.) When I try and run the ssl backup, I get a BUNCH of red lettering saying things couldn't be read cause this user doesn't have write permissions.  I run the command sudo bash /var/scripts/activate-ssl_backup.sh. How come sudo doesn't have the right permissions?

**Comment by kzieres61** [comment]
Solved:
*EDIT* Resolved
used the update.sh to fully update nextcloudVM.  Then manually installed certbot
https://certbot.eff.org/all-instructions/#ubuntu-16-04-xenial-apache

ran letsencrytprenew.sh and SUCCESS!!

**Comment by enoch85** [comment]
A PR to ensure that this doesn't break in the future: https://github.com/nextcloud/vm/pull/308
