### ISSUE TITLE
Sharing file to public nextcloud from VM nextcloud

### ISSUE THREAD

**Issue by Leftspace21** [nextcloud/vm#322]
## Steps to reproduce
1. Install on Desktop VM Nextcloud v 12
2. Share a folder from VM Nextcloud12 to a remote user on public Nextcloud12
3. On public Nextcloud server get notification of share and accepted 

## Expected behaviour
Would not expect to see folder in public Nextcloud12 as the VM machine behind router and not available publicly.
So, correctly I cannot see folder which was shared.

## Actual behaviour
However, this made the public Nextcloud 12 version unusable for me to use - taking 2 minutes to respond to each request. It is as if the public Nextcloud 12 version is still trying repeatedly to contact to private VM Nextcloud and will not let me easily use the system. When logging in as different super user then system works perfectly.

## Server configuration
Version: 7.0.18
**Server version:** (see your admin page)

**VM version** (master / released version)

fresh install:

I do not have the technical expertise to provide the information below. Please delete this report therefore if inadequate.

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
This is not a VM issue, rather a configuration issue on your end. Feel free to disagree and reopen.
