### ISSUE TITLE
Access Nextcloud fail in vps

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#324]
im install in ubuntu 16 and show me this

![pantallazo-0258](https://user-images.githubusercontent.com/428820/28799135-ed316b0a-760c-11e7-98c2-86bee170423c.png)

Clic in button

![pantallazo-0259](https://user-images.githubusercontent.com/428820/28799148-f58b4c44-760c-11e7-8f45-f6a276013717.png)

How fix that?

**Comment by enoch85** [comment]
Is this VPS a LOCAL VPS, or on a shared storage?

1. Get a domain
2. Run the Let's Encrypt script: `sudo bash /var/scripts/activate-ssl.sh`
3. Set trusted domain if needed.

**Comment by johnfelipe** [comment]
@enoch85 is LOCAL VPS:

![pantallazo-0260](https://user-images.githubusercontent.com/428820/28799498-6fcd49de-760e-11e7-9b45-4af26d5251d2.png)

**Comment by enoch85** [comment]
@johnfelipe Please follow the steps and see if it works.

**Comment by johnfelipe** [comment]
Get a domain, i have one in godaddy, then @ point to my ip?

![pantallazo-0261](https://user-images.githubusercontent.com/428820/28799836-c2b0415a-760f-11e7-926c-8a30dd0db787.png)

Its fine there?

**Comment by enoch85** [comment]
Yes, and then run step 2.

**Comment by johnfelipe** [comment]
Running hooks in /etc/ca-certificates/update.d...

	done.
	done.
	Installing Apache Solr
	It might take some time depending on your bandwith, please be patient...
	solr-6.6.0.tgz        5%[>                   ]   7.12M  14.0KB/s    eta 1h 5

Can i open new command line windows and run step 2?

**Comment by enoch85** [comment]
That's the wrong script... You should run activate-ssl.sh

**Comment by johnfelipe** [comment]
this is my step by step documentation

https://docs.google.com/document/d/1xL4dHzYOF8Q2v_fvJuqrMbFVnQBVucUYfOPjh-guIzM/edit?usp=sharing

Pls tell me what step is wrong and begin again

**Comment by enoch85** [comment]
Is this installed on DigitalOcean?

**Comment by johnfelipe** [comment]
No, my own server.

that is because 

Do you run this script on a *remote* VPS like DigitalOcean, HostGator or similar? ([y]es or [N]o): **n**

**Comment by enoch85** [comment]
Then it's not a VPS. It's a VM. 

What is your domain name?

**Comment by johnfelipe** [comment]
http://200.122.209.133/

	votandoando.com
	cloud.votandoando.com
	colabora.votandoando.com

that is all

**Comment by enoch85** [comment]
Just checked, it works. 

As I said in my first post, you need to run activate-ssl.sh which will give you a proper SSL cert and set trusted domain.

**Comment by enoch85** [comment]
Also, you should add a CNAME for you Collabora installation in your DNS.

**Comment by johnfelipe** [comment]
Do u have this steps in documentation or video?

**Comment by enoch85** [comment]
The only thing you need to do is to run: `sudo bash /var/scripts/activate-ssl.sh`.

For Collabora it's a bit more complex. 

I suggest that you run everything from start, removing the VM, and mount it fresh again then just follow the instructions in the script. Don't change anything, and when it asks you to activate SSL, enter YES.

**Comment by enoch85** [comment]
To make it easy for yourself, run this VM: https://cloud.techandme.se/index.php/s/whxC00V1I0l4CY8 It's pre-installed.

**Comment by johnfelipe** [comment]
This is not possible for me I need install on a real server, then I need
put all in cheatsheet for use in physical server
How can improve SSL for this test environment?

**Comment by enoch85** [comment]
A VM is a "real server", plus it's much easier to maintain. Or what do you think is the difference between a "real server" and a VM?

As I said, use the VM, test with that (including SSL), does it work then good! Proceed on your "real server". :)

**Comment by enoch85** [comment]
Another alternative is if we help you install everything: https://shop.techandme.se/index.php/product/installation-of-nextcloud/

**Comment by johnfelipe** [comment]
Bro, I have a server, physical server and I need install in that server, VM
I can test in VMware workstation and is good but later when need install in
physical server?, Virtual appliance not helpful, share me your knowledge
for complete this task
Tnks

**Comment by enoch85** [comment]
I've already told you several times.

Do like this: https://github.com/nextcloud/vm/blob/master/README.md#build-your-own-vm-or-install-on-a-vps 

Follow the instructions, install SSL and you're fine.

**Comment by johnfelipe** [comment]
"Also, you should add a CNAME for you Collabora installation in your DNS."

How put CNAME in Collabora?

Stay alert

**Comment by enoch85** [comment]
I noticed that you still haven't run the Let's Encrypt script (activate-ssl.sh). It feels meaningless to help you if you don't follow instructions...

CNAME: https://support.dnsimple.com/articles/cname-record/

**Comment by johnfelipe** [comment]
CNAME Not need it, colabora is working, look:

https://goo.gl/7cq7F8

Or still i need put in my godaddy DNS?

**Comment by enoch85** [comment]
No that's fine. Finally! :)

**Comment by johnfelipe** [comment]
Why in video calls only allow one gest user?

**Comment by enoch85** [comment]
Please ask in the forums: help.nextcloud.com.

Thanks!
