### ISSUE TITLE
change $NCDATA locally

### ISSUE THREAD

**Issue by manuluyten** [nextcloud/vm#325]
## Steps to reproduce
1. The file lib.sh is downloaded in every run of the install and update proces. ( expected behaviour)
2.NCDATA=/var/ncdata is defined in the lib.sh file
3.

## Expected behaviour
Behaviour is as expected. This is a feature request.
I would like to change the value of NCDATA to an additional mount point to seperate storage.
I can not make this change now without breaking the update process.

## Actual behaviour
Every run of an included script, the online version of lib.sh will be downloaded. 
I would like to be able to customise this variable locally.

## Server configuration

**Server version:** (see your admin page)

**VM version** (master / released version)

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
You can customize it, just add it with a different path in each file that you want to change. :)

**Comment by enoch85** [comment]
Closing as this is not an issue.
