### ISSUE TITLE
update method for all services

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#327]
Once installed all, how can pull / update all applications and services
Stay alert

**Comment by enoch85** [comment]
sudo bash /var/scripts/update.sh as in the description.

**Comment by johnfelipe** [comment]
but that script is for nextcloud core, what about apps?

**Comment by enoch85** [comment]
It updates;
- Redis
- Collabora/OnlyOffice
- Apps
- Server system
- Sets strong permissions
- Fix RewriteBase
- And more

**Comment by johnfelipe** [comment]
felipe@cloud:~$ sudo bash /var/scripts/update.sh
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	Calculating upgrade... Done
	0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
	Trying to upgrade the Redis Pecl extenstion...
	Nothing to upgrade
	Updating Docker container for Collabora...
	Using default tag: latest
	latest: Pulling from collabora/code
	Digest: sha256:0a621662d81b8e0e24620eb7cfbddf40c285b53e486f400051b14ba87ba48267
	Status: Image is up to date for collabora/code:latest
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	Generating grub configuration file ...
	Found linux image: /boot/vmlinuz-4.4.0-89-generic
	Found initrd image: /boot/initrd.img-4.4.0-89-generic
	Found linux image: /boot/vmlinuz-4.4.0-87-generic
	Found initrd image: /boot/initrd.img-4.4.0-87-generic
	done
	Latest version is: 12.0.1. Current version is: 12.0.1.
	No need to upgrade, this script will exit...

apps is not updating...

**Comment by enoch85** [comment]
Yes they are. That instance is already upgraded so it won't show. 

During the occ command they get updated.

**Comment by johnfelipe** [comment]
i restore from last snapshot and update with your script, im glad to say is working perfectly here is log:

https://gist.github.com/johnfelipe/62da0467ec49d520862149dc9ee2c6be

**Comment by enoch85** [comment]
Told you so. ;)
