### ISSUE TITLE
can i add onlyoffice?

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#330]
I have all working with collabora, how can add onlyoffice?
That is possible?
Share me instructions

Tnks

**Comment by enoch85** [comment]
You have to choose, Collabora or OnlyOffice. There is a script in this repo that you can use for both.

**Comment by johnfelipe** [comment]
onlyoffice.sh that is script you talking about?
Then i need other domain maybe onlyoffice.votandoando.com?
Stay alert

**Comment by enoch85** [comment]
Yes, that's the one.

**Comment by johnfelipe** [comment]
https://goo.gl/5gZ5SU

seem cant install both in same time

How can run onlyoffice and collabora at same time?

**Comment by enoch85** [comment]
You can't.

**Comment by johnfelipe** [comment]
I have onlyoffice added in first installation script, is possible
deactivate collabora for activate onlyoffice?

**Comment by enoch85** [comment]
Yes
