### ISSUE TITLE
LXC containers

### ISSUE THREAD

**Issue by zenny** [nextcloud/vm#332]
Hej,

Thanks for the nice script.

Your script seems to create two docker instances in the VM, but not in lightweight containers.

I came across this script from https://www.techandme.se/automated-collabora-installation-on-nextcloud/, and was exited, but found limited due to lxc. It would be nice if nextcloud and onlyoffice/collabora can be installed in the same instance of a lxc container. 

I installed successfully onlyoffice in one of the lxc containers in the same local network (192.168.10.1) that is running nextcloud in another lxc container (192.168.10.2). But they do not seem to connect even to use internally**. Both document server and nextcloud are running without disconnected even after adding https://192.168.10.1 in the nextcloud onlyoffice app settings for using internal purposes. 

A similar error I can find in the log as described at http://dev.onlyoffice.org/ru/viewtopic.php?p=21909

 `Connection refused at /usr/share/nginx/nextcloud/apps/onlyoffice/lib/documentservice.php`

Cheers,
/z

**without letsencrypt (a PITA), used a self-signed certificate instead for internal use.

**Comment by enoch85** [comment]
I won't manufacture a LXC container when there is Docker available already. This feels like a question for the Collabora / OnlyOffice devs more than a VM issue.

**Comment by zenny** [comment]
@enoch85, tack, Daniel. I shall try to post to the relevant forums, though the problem is not resolved.

**Comment by enoch85** [comment]
But still, it's nothing I will develop, so the "problem" isn't on my desk. :)

**Comment by enoch85** [comment]
@zenny Feel free to make a PR.

**Comment by enoch85** [comment]
Closing as this is not likely to happen. Feel free to repoen f you disagree.
