### ISSUE TITLE
peer conection error spreedme after update

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#335]
I update with your awsome script to nextcloud 12.0.2 but something happend to spreedme, show me this:

![pantallazo-0275](https://user-images.githubusercontent.com/428820/29323885-de2598e2-81a7-11e7-9367-cbc0b4d0bcee.png)

How solved?

**Comment by enoch85** [comment]
It works for me, tried it several times yesterday.

Run the Spreedme script again found in this repo.

**Comment by johnfelipe** [comment]
where is located that script?
or i need git clone all your repo?

**Comment by enoch85** [comment]
![screenshot from 2017-08-15 19 36 48](https://user-images.githubusercontent.com/4511254/29327976-3b15bdc2-81f1-11e7-9c3d-c06913cb13e7.png)

**Comment by johnfelipe** [comment]
root@cloud:~# wget https://raw.githubusercontent.com/nextcloud/vm/master/apps/spreedme.sh
	--2017-08-15 12:37:41--  https://raw.githubusercontent.com/nextcloud/vm/master/apps/spreedme.sh
	Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
	Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: 3951 (3.9K) [text/plain]
	Saving to: ‘spreedme.sh’

	spreedme.sh         100%[===================>]   3.86K  --.-KB/s    in 0s

	2017-08-15 12:37:41 (37.8 MB/s) - ‘spreedme.sh’ saved [3951/3951]

	root@cloud:~# bash spreedme.sh
	SpreeMe Snap already seems to be installed and wil now be re-installed...
	spreedme removed
	spreedme 0.29.5snap1 from 'nextcloud' installed
	spreedme disabled
	SpreedMe app already seems to be installed and will now be re-installed...
	spreedme enabled
	Module proxy already enabled
	Considering dependency proxy for proxy_wstunnel:
	Module proxy already enabled
	Module proxy_wstunnel already enabled
	Considering dependency proxy for proxy_http:
	Module proxy already enabled
	Module proxy_http already enabled
	Module headers already enabled

	Success! SpreedMe is now installed and configured.
	You may have to change SPREED_WEBRTC_ORIGIN in:
	(sudo nano) /var/www/nextcloud/apps/spreedme/config/config.php

Still have problem

**Comment by enoch85** [comment]
What does the log show?

Have you changed any settings prior to or after the installation?

What's the content of `/etc/apache2/spreedme.conf`?

**Comment by johnfelipe** [comment]
2017-08-15 12:55 GMT-05:00 Daniel Hansson <notifications@github.com>:

> What does the log show?
>
Where is path for tha file?

> Have you changed any settings prior to or after the installation?
>
Nop

> What's the content of /etc/apache2/spreedme.conf?
>
<Location /webrtc>
    ProxyPass http://127.0.0.1:8080/webrtc
    ProxyPassReverse /webrtc
</Location>

<Location /webrtc/ws>
    ProxyPass ws://127.0.0.1:8080/webrtc/ws
</Location>

    ProxyVia On
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
    # RequestHeader set X-Forwarded-Proto 'https' # Use this if you are
behind a (Nginx) reverse proxy with http backends

**Comment by enoch85** [comment]
> Where is path for tha file?

`/var/ncdata/nextcloud.log`

**Comment by enoch85** [comment]
Any news?

**Comment by johnfelipe** [comment]
Still have it but my problem I see is with external page, https error, how
can solved?

**Comment by enoch85** [comment]
This is not a support forum, sorry.

If you run the VM and follow the instructions, everything work out of the box. f you need support, you can ask in https://help.nextcloud.com or buy support from Tech and Me: https://shop.techandme.se/index.php/product/premium-support-per-30-minutes/

**Comment by johnfelipe** [comment]
@enoch85 this is log:

https://gist.github.com/johnfelipe/93af1379e0f92d44dd6924af756f4e4b

This is suggest in https://help.nextcloud.com/t/peer-conection-error-spreedme/19669:

![suggestaboutpeerconnectionerror](https://user-images.githubusercontent.com/428820/29718480-8c0d3bf4-8978-11e7-97ee-34e75b198cd8.png)

Pls tell me if i need install TURN server or what i need to do...

**Comment by enoch85** [comment]
Maybe you do, I don't know. What I provide with the script is to successfully install SpreedMe and set all the correct configs. TURN you have to fix yourself.

**Comment by johnfelipe** [comment]
@enoch85 but error about peer connection show everytime, then how solved pls....

**Comment by enoch85** [comment]
@johnfelipe https://github.com/nextcloud/vm/issues/335#issuecomment-323408059

**Comment by johnfelipe** [comment]
@enoch85 if buy that 30 min, can u help me?

**Comment by enoch85** [comment]
@johnfelipe Send me an email.

**Comment by johnfelipe** [comment]
@enoch85 i havent, pls share me your email or send me an email to ingenierofelipeurrego@gmail.com

**Comment by johnfelipe** [comment]
@enoch85 share me your email pls or send to my email, stay alert

**Comment by enoch85** [comment]
I've already wrote an email to you...

**Comment by johnfelipe** [comment]
no bro i dont get it, send again pls

**Comment by enoch85** [comment]
![screenshot from 2017-08-30 23 03 48](https://user-images.githubusercontent.com/4511254/29894929-82e83818-8dd7-11e7-8783-f6fbbd0cca03.png)
