### ISSUE TITLE
After Update, i need to reset my server !

### ISSUE THREAD

**Issue by thomasbonsirven** [nextcloud/vm#338]
Hello,

So, is 3days to my server is down, impossible to login on nextcloud : 

Day : 08/15 
- 52 packages need update, i lunche the command ```bash update.sh``` in ssh
- Reboot
- Apache2, Solr, Redis and Mysql is down.
the error is misstake files, mysql is a error2002 misstake mysqld.sock, but is not really misstake, beacause i find this file on great path. etc..

Day's : 08/16 and 08/17 
- After try to install and reinstall nextcloud, apache solr mysql etc.. i have the SAME Error ! and i dont why... 

-So, i backup the mysql folders and ncdata.

Day : 08/18
- I cleanup and reset my server, fresh install on ubuntu 16.04
- Install nano, wget, git.
- Clone git the vm soures ( this repository )
- Start the script in root : bash nextcloud_install_production.sh
- Install all apps, Passman, fail2ban, collabora etc..
The installation is success, no error excepted mdam. i think is not really important.

- Try to access on my website : 
https://office.script-news.com
White page !!

So, i try to debug : 
- i look the log apache2 : ```nano /var/log/apache2/error.log ```: 

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: cannot open shared object file:$
[Fri Aug 18 09:34:44.606313 2017] [mpm_prefork:notice] [pid 4220] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri Aug 18 09:34:44.606375 2017] [core:notice] [pid 4220] AH00094: Command line: '/usr/sbin/apache2'
[Fri Aug 18 09:37:10.590664 2017] [mpm_prefork:notice] [pid 4220] AH00169: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: cannot open shared object file:$
[Fri Aug 18 09:37:11.749473 2017] [mpm_prefork:notice] [pid 4318] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri Aug 18 09:37:11.749520 2017] [core:notice] [pid 4318] AH00094: Command line: '/usr/sbin/apache2'
[Fri Aug 18 09:40:59.238190 2017] [mpm_prefork:notice] [pid 4318] AH00169: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: cannot open shared object file:$
[Fri Aug 18 09:41:00.381339 2017] [mpm_prefork:notice] [pid 4519] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri Aug 18 09:41:00.381388 2017] [core:notice] [pid 4519] AH00094: Command line: '/usr/sbin/apache2'
[Fri Aug 18 09:41:57.827356 2017] [mpm_prefork:notice] [pid 4519] AH00171: Graceful restart requested, doing restart
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0
[Fri Aug 18 09:41:57.928712 2017] [mpm_prefork:notice] [pid 4519] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri Aug 18 09:41:57.928732 2017] [core:notice] [pid 4519] AH00094: Command line: '/usr/sbin/apache2'
[Fri Aug 18 09:42:40.605007 2017] [mpm_prefork:notice] [pid 4519] AH00171: Graceful restart requested, doing restart
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0
[Fri Aug 18 09:42:40.713894 2017] [mpm_prefork:notice] [pid 4519] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri Aug 18 09:42:40.713913 2017] [core:notice] [pid 4519] AH00094: Command line: '/usr/sbin/apache2'
[Fri Aug 18 09:46:27.658563 2017] [mpm_prefork:notice] [pid 4519] AH00169: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0
[Fri Aug 18 09:46:40.422629 2017] [mpm_prefork:notice] [pid 1468] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri Aug 18 09:46:40.422833 2017] [core:notice] [pid 1468] AH00094: Command line: '/usr/sbin/apache2'

```

## Network
I use DHCP

443 open

#### Log file (/var/ncdata/nextcloud.log)
```
{"reqId":"xp42THKL3lB8Nnp5WpiZ","level":3,"time":"2017-08-18T09:25:27+02:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"PHP","method":"GET","url":"\/",
"message":"OC\\HintException: Memcache \\OC\\Memcache\\Redis not available for local cache at \/var\/www\/nextcloud\/lib\/private\/Memcache\/Factory.php#96"
,"userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.2.0"}

```

So the probleme is clear, i think, is a redis server ... 
Please help me to resolve this...

**Comment by thomasbonsirven** [comment]
Mm, Passman, and Collabora, and OnlyOffice not activate and not installed

I restart installation with fresh server

**Comment by thomasbonsirven** [comment]
Well, after re-install with a fresh server, is work now. But the OnlyOffice is not installed and not setting. How to fixe this ?

**Comment by thomasbonsirven** [comment]
Ok, the onmyOffice is not installed : 
root@office:/home/ubuntu# sudo docker run -i -t -d -p 8080:8080 --restart=always onlyoffice/documentserver
bc45904c48c140039dd96c628b32396d860b45c6d30e1061ad1bb55c65763d1f
docker: Error response from daemon: driver failed programming external connectivity on endpoint jovial_wozniak (b4f18bbc3b39ee0e0e1ab9976b3d1b2ec57b75c0239ffc859ee860e84f33553d): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use.


Other problem : 
I have a old data and old user, i need to add all users with data per user. How to  ?

**Comment by enoch85** [comment]
Sorry, if you want support we have other channels for that like help.nextclod.com. Or if you want Tech and Me to help you you can buy support in our shop. 

The VM works fine, and I can't answer for user configuration issues or server settings.
