### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by rdebruin** [nextcloud/vm#339]
## Steps to reproduce
1. Run the installation script (makes no difference which mirror is taken). Reproduced 4 times.
2. 
3.

## Expected behaviour
Mariadb-server should be setup. I expect that  the new version 10.2.8 (instead of 10.2.7) could be the case.

## Actual behaviour
Failed to start the Mariadb server.

## Server configuration

**Server version:** (see your admin page)
Running on a QNAP TS-253a server (Virtualisation Station)
**VM version** (master / released version)
The version Ijust bought (500Gb)
**Updated from an older installed version or fresh install:**
Fresh
## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
Yes
## Logs / Screenshots
![nextcloud_community_vm_500gb_20170820 3](https://user-images.githubusercontent.com/31158197/29497010-f5696a4c-85df-11e7-81a0-3870c4650df0.png)
![nextcloud_community_vm_500gb_20170820 2](https://user-images.githubusercontent.com/31158197/29497012-f7e7b0ee-85df-11e7-9dda-842e824fec64.png)
![nextcloud_community_vm_500gb_20170820 1](https://user-images.githubusercontent.com/31158197/29497013-f9db7eb2-85df-11e7-9c4d-5835922cb8cd.png)
![nextcloud_community_vm_500gb_20170820](https://user-images.githubusercontent.com/31158197/29497014-fb66c7dc-85df-11e7-8fb0-e99fa3f73ef0.png)

Please use http://hastebin.com/ for long error messages or logs. Thanks!
-->

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
What happens if you comment out the update process on [this](https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L414) line and then run the script on a freshly mounted VM.

**Comment by rdebruin** [comment]
I can try ofc, but need some help (not a Linux expert). I load the .ova in my virtual machine and it starts off as soon as I poweron my VM. I need a way to edit this file first? Where is the file located?

**Comment by enoch85** [comment]
@rdebruin Use Putty and login via SSH: ncadmin@server-ip 

You can find Putty here: https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

The file is located at `/var/scripts`

**Comment by enoch85** [comment]
I can confirm this error. MariaDB fails to install correctly.

**Comment by enoch85** [comment]
But seems to work if you let it run. After a restart everything is fine.

**Comment by rdebruin** [comment]
Did a new install, now on VirtualBox on my Windows PC. Much faster to reproduce.
I see this files on my virtual machine, am I missing a step?

activate-ssl.sh  nextcloud_update.sh                    trusted.sh
history.sh       security.sh                            update-config.php
nextcloud.sh     setup_secure_permissions_nextcloud.sh  update.sh

**Comment by enoch85** [comment]
Those aren't the files on a newly mounted VM. It should only contain

`nextcloud.sh`
`history.sh`
`nextcloud-startup-script.sh`

It seems like you already run the setup. Remove the VM and mount it again, then follow my above instructions.

**Comment by rdebruin** [comment]
Aha, ok thx.

**Comment by enoch85** [comment]
Any update here?

**Comment by rdebruin** [comment]
Works fine with your solution:  PuTTY and remove the "update line".
