### ISSUE TITLE
Minimum system requirements 

### ISSUE THREAD

**Issue by eranj** [nextcloud/vm#347]
Maybe it should be updated.
A new official Nextcloud Community VM from OVA takes 330 MB of RAM on idle.

**Comment by enoch85** [comment]
It's for Collabora and other stuff, so 2 GB it is.

**Comment by eranj** [comment]
You can mention the amount of RAM which is required for Nextcloud without any apps.
It's misleading.

**Comment by enoch85** [comment]
If you want to run your Nextcloud on the absolute bare minimum, like 512 MB or so, fine. But I run with minimum recommended defaults for everything to work.

If you are curious to find out what your system requires, run `htop`.
