### ISSUE TITLE
Errors during scripted installation

### ISSUE THREAD

**Issue by eranj** [nextcloud/vm#348]
What is the scripted installation log file location?
I'll upload the log so you can see the errors.

**Comment by enoch85** [comment]
There are no log. What's wrong?

**Comment by eranj** [comment]
I asked what is the installation log file location?
Then I'll be able to upload it.
The installation errors was scrolled too fast.

**Comment by enoch85** [comment]
/var/ncdata/nextcloud.log

**Comment by eranj** [comment]
It's too short and doesn't contain the errors / warnings I've seen. 
I guess it's been overwritten by some process after the installation.
If you run the installation you should see it.

**Comment by enoch85** [comment]
Afaik there are no errors. If there where I would fix them ;)
