### ISSUE TITLE
Network NOT OK startup script

### ISSUE THREAD

**Issue by fantapereira** [nextcloud/vm#350]
## Steps to reproduce
1. mounted a new VM from ova file. DHCP enabled and IP address obtained
2. start the vm and run the script automatically
3.  error message stating network is not ok

## Expected behaviour
install script should run automatically

## Actual behaviour
network error message and script stop

## Server configuration

**Server version:** (see your admin page)

**VM version** (master / released version)

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?**
yes
**Is port 80 and/or 443 open?**
yes
#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
root@nextcloud:/var/scripts# ./nextcloud-startup-script.sh
Testing if network is OK...
Setting correct interface...
./nextcloud-startup-script.sh: line 63: debug_mode: command not found
Testing if network is OK...

Network NOT OK. You must have a working Network connection to run this script.
Please report this issue here:
root@nextcloud:/var/scripts# ifconfig |grep inet
          inet addr:172.30.2.230  Bcast:172.30.2.255  Mask:255.255.255.0
          inet6 addr: fe80::250:56ff:fe87:2e/64 Scope:Link
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
root@nextcloud:/var/scripts# cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto ens33
iface ens33 inet dhcp
# This is an autoconfigured IPv6 interface
iface ens33 inet6 auto

#### Screenshoots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by enoch85** [comment]
@fantapereira Thanks for your support. 

Which hypervisor are you running, and what's the output of `lshw -c networking`?

**Comment by fantapereira** [comment]
@enoch85 i'm running EXI 6.0

` lshw -c network
  *-network
       description: Ethernet interface
       product: 82545EM Gigabit Ethernet Controller (Copper)
       vendor: Intel Corporation
       physical id: 1
       bus info: pci@0000:02:01.0
       logical name: ens33
       version: 01
       serial: 00:50:56:87:00:2e
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 64 bits
       clock: 66MHz
       capabilities: pm pcix bus_master cap_list rom ethernet physical logical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=e1000 driverversion=7.3.21-k8-NAPI duplex=full ip=172.30.2.230 latency=0 link=yes mingnt=255 multicast=yes port=twisted pair speed=1Gbit/s
       resources: irq:19 memory:fd5c0000-fd5dffff memory:fdff0000-fdffffff ioport:2000(size=64) memory:fd500000-fd50ffff
`

**Comment by enoch85** [comment]
The script seems to be doing it's job.

What if you run `nslookup google.com` before you run the script?

**Comment by fantapereira** [comment]
Finally i was able to get the script working, mounting the VM on my home network.

I think the issue might be related to my work network. It requires proxy authentication in order to "talk" to internet.  However i manually added the proxy settings (proxy server, user, pass, port, etc) on bashrc, environment and apt.conf, but still failed.  I cannot tell for sure if there're any extra configuration for this particullar scrtipt.

So i think it might be a good idea to add an option to configure proxy settings on the script. I don't think i am the only one facing this issue.

Anyway it gets resolved, i've  exported the configured VM to an OVF template, and i'll import it on Monday

thanks for your great job, and i hope my "suggestion" makes sense to you.

**Comment by enoch85** [comment]
Glad you finally solved it!

Feel free to open a PR in this repo with the fix provided.

**Comment by webbird** [comment]
For those having a similar problem, create a .wgetrc and put your proxy settings there. Worked for me.

**Comment by fantapereira** [comment]
where should i locate the  .wgetrc file?

**Comment by enoch85** [comment]
@webbird Would be super nice if you could prepare a PR and create a `.wgetrc` in the second attempt somewhere here: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L45
