### ISSUE TITLE
onlyoffice script not work

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#357]
i deactivate collabora and onlyoffice to, run your script and this is log:

![collaboraonlyoffice](https://user-images.githubusercontent.com/428820/29895932-9ddeb052-8da0-11e7-9fe3-1ff4e9938811.png)

when ask you in other issue about deactivate collabora for use onlyoffice your answer was YES

https://github.com/nextcloud/vm/issues/330#issuecomment-326015463

I need solution about this

Tnks

**Comment by enoch85** [comment]
Please ask for *support* in https://help.nextcloud.com as I told you earlier. There are nothing wrong in the scripts afaik.

@jasonbayton @tflidd As you  already know you have to deactivate the docker container and purge all settings and then install the new docker. FYI if he asks in the forum. (This is not a support forum) :)
