### ISSUE TITLE
MariaDB fails to start when updated

### ISSUE THREAD

**Issue by Worikben** [nextcloud/vm#362]
I try to use a OVA file to create a VM on a QNAP with virtualization station. This worked in the pass. But building up a new one isn't possible. The script works perfect till some update of ubuntu. This installation hangs on mariadb for quit a while after that red words. The installation goes on but the server is not working. Rebooting doesn't do the trick.
Yesterday I had a working server, but after doing the ubuntu updates the same appears.
<img width="1148" alt="first error" src="https://user-images.githubusercontent.com/27916613/30316607-15baee5e-97a8-11e7-83af-7b4ad71c1beb.png">

any tricks?

**Comment by enoch85** [comment]
Yes, just let it run. It will solve itself after the script has finished. It happens when Ubuntu updates MariaDB to the latest version.

**Comment by enoch85** [comment]
Let's keep this open in case others have the same issue.

I will close this on next release.

**Comment by Worikben** [comment]
Yes, let do this. I've tried serval times to create a nextcloud VM using this script. I import the OVA file and run it. I build up a clear server and run the script by a bash command. The results are the same. 
I even downloaded an older version of Ubuntu 16.04. 
Yesterday a had a working server but after a "apt dist-upgrade" this problem occurs. The installation goes on but the nextcloud login page doesn't appear.

**Comment by Worikben** [comment]
I will set up green field server and run the script with a bash command. I wil provide the complete logging of this to you



************ Disclaimer ***********
De informatie verzonden met dit e-mailbericht (en bijlagen) is uitsluitend bestemd voor de geadresseerde(n) en zij die van de geadresseerde(n) toestemming kregen dit bericht te lezen.
Kennisneming door anderen is niet toegestaan.
De informatie in dit e-mailbericht (en bijlagen) kan vertrouwelijk van aard zijn en binnen het bereik van een geheimhoudingsplicht en/of een verschoningsrecht vallen.
Indien dit e-mailbericht niet voor u bestemd is, wordt u verzocht de afzender daarover onmiddellijk te informeren en het e-mailbericht (en bijlagen) te vernietigen.
************************************

**Comment by enoch85** [comment]
This is a `dpkg` issue and nothing I can solve with scripts, except excluding the mariadb update. But that would mean a new release, and it's not necessary since I tested this myself and it works if you just wait it out.

**Comment by enoch85** [comment]
This shouldn't be an issue in https://github.com/nextcloud/vm/releases/tag/12.0.3 anymore.
