### ISSUE TITLE
DHPARAMS to 4096 , allow IE11/Win7 to work instead of Page wont Display

### ISSUE THREAD

**Issue by gabasync** [nextcloud/vm#367]
ssllabs.com shows a standard IE11/Win7 setup will not work. For companies that do not allow alternative popular Browsers this can be a non go for internal company deployment. Lowering the DH to 4096 may alleviate this issue. Below is the ssllabs.com lab results:

IE 11 / Win 7  R		Client does not support DH parameters > 4096 bits
RSA 4096 (SHA256)   |  TLS 1.2  |  TLS_DHE_RSA_WITH_AES_128_GCM_SHA256  |  DH 8192

**Comment by enoch85** [comment]
@gabasync Thanks for noticing this. I actually had some complaints about that in the past. 

Can you please verify that that that actually is the case? If it's the case, please make a PR so that we can merge this.

Thanks!

**Comment by gabasync** [comment]
Yes it is the case. After altering the dh perm file to 4096 IE11/Win7 connects fine. Here is the link from the letsencrypt forum I opened as well:
https://community.letsencrypt.org/t/nextcloud-selecting-ciphers-to-support-ie11-on-windows-7/42643

**Comment by tchollingsworth** [comment]
Hi, I'm one of the the people who responded the the reporter's thread on the Let's Encrypt forum.

I just wanted to point out that the strength of Diffle-Hellman parameters is limited by the strength of the RSA key in the server certificate. Since this script also sets the keylength of the certificate to 4096 bits, effectively only 4096 bits of the dhparams are used anyway. Therefore making this change will not reduce security in any meaningful way.

**Comment by gabasync** [comment]
My apologies. Not sure how but I created the pull request (I think!) My only change is 8192 to 4096. Please refere to the above link. After the dh perm was reset to 4096 IE11/Win 7 works fine. This will be good for new installs. I am not sure how to approach current existing systems.

**Comment by tchollingsworth** [comment]
If you also want to fix old installations, you could change the if that guards dhparam generation to something like this:

    if [ ! -f "$DHPARAMS" ] || [ "$(openssl dhparam -in "$DHPARAMS" -noout -text | awk -F'[()]' '{print $2; exit}')" != "4096 bit" ]

This will generate the parameters if they don't exist or if they aren't exactly 4096 bits.

**Comment by gabasync** [comment]
To tchollingsworth:
The code looks good. I do not want to take credit for your code. I have created a pull request. Can you please add you code to it or add a addition pull request? If you do not want to would you mind if I did so. All I want to make sure is you get credit for the code change itself. Please let me know and thanks for the help on this issue.

**Comment by enoch85** [comment]
Closed in https://github.com/nextcloud/vm/pull/369 

Feel free to improve @tchollingsworth
