### ISSUE TITLE
NEXTCLOUD DON´T WORK AFTER RESTART

### ISSUE THREAD

**Issue by cdbm1980** [nextcloud/vm#368]
I use PRODUCTION SERVER: Ubuntu 16.04 OVA: Pre-installed Nextcloud PHP 7
I can create the VM start it, log and configure without problems and everything works ok, but whe i restart the VM the nextcloud don´t work anymore (try 3 VM installations), i can log via SSH, Webmin, etc....but the nextcloud don´t work. If log again with NCADMIN/nextcloud the installation wizard begin again.

What i´m doing bad?

**Comment by enoch85** [comment]
Hard to say what you are doing wrong without seeing what you do. The VM works for me and plenty other users so this is not a bug, rather a user error.

> If log again with NCADMIN/nextcloud the installation wizard begin again.

This tells me that you didn't run the script properly, because that file is removed in the end of the setup script when everything is finished.
