### ISSUE TITLE
/dev/fd/63: line 20: lshw: command not found

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#372]
when install production script is showing this:

`/dev/fd/63: line 20: lshw: command not found`

**Comment by enoch85** [comment]
Thanks! Instead of posting so little information, can you please refer to the correct line so that  can check the command?

**Comment by johnfelipe** [comment]
Solved, ubuntu 16.04.3 need `Standard system utilities`

**Comment by enoch85** [comment]
@johnfelipe What? Is it a bug or no?

**Comment by enoch85** [comment]
@johnfelipe Please join IRC on #techandme

**Comment by johnfelipe** [comment]
![pantallazo-0331](https://user-images.githubusercontent.com/428820/30763181-a196f184-9faa-11e7-8c31-1dec073b94f2.png)

you not answer...

**Comment by enoch85** [comment]
Send a private MSG instead.
