### ISSUE TITLE
Nextant is failing since solr 7.0.0

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#373]
```
sed: can't read /opt/solr-7.0.0/server/solr/configsets/data_driven_schema_configs/conf/solrconfig.xml: No such file or directory
sed: can't read /opt/solr-7.0.0/server/solr/configsets/data_driven_schema_configs/conf/solrconfig.xml: No such file or directory
sed: can't read /opt/solr-7.0.0/server/solr/configsets/data_driven_schema_configs/conf/solrconfig.xml: No such file or directory
sed: can't read /opt/solr-7.0.0/server/solr/configsets/data_driven_schema_configs/conf/solrconfig.xml: No such file or directory
sed: can't read /opt/solr-7.0.0/server/solr/configsets/data_driven_schema_configs/conf/solrconfig.xml: No such file or directory
tee: /opt/solr-7.0.0/server/solr/configsets/data_driven_schema_configs/conf/solrconfig.xml: No such file or directory
```

Can you please have a look @Ark74?

**Comment by enoch85** [comment]
Seems to be here: https://github.com/nextcloud/vm/blob/master/apps/nextant.sh#L81

**Comment by enoch85** [comment]
It's confirmed. Nextant is being installed but it's not connecting to Solr.

![screenshot from 2017-09-23 20 12 01](https://user-images.githubusercontent.com/4511254/30775818-893b6f88-a09b-11e7-889d-09b99981cc6b.png)

**Comment by enoch85** [comment]
@Ark74 I deactivated Nextant until this is fixed: https://github.com/nextcloud/vm/commit/582234b82750578ab90aee51bb6a11b6c3844ed1

**Comment by Ark74** [comment]
Hi!
Maybe @daita can have more info on this, but so far IIRC he stated that the supported version for nextant is 6.x, so i don't see it as a bug maybe part of a feature request to support version 7.x

Cheers!

**Comment by enoch85** [comment]
@Ark74  So what you mean is that we have to revert to a manual `$SOLR_RELEASE` so that we don't get the newest release automatically, and at the same time revert back to the latest 6.X?

@daita Please make Nextant compatible with the latest Sorl at all times. Also, do you have a solution for this one?

Thanks!

**Comment by Ark74** [comment]
@enoch85 Well, 'til @daita announce any support for 7.0, yeah pretty much!

**Comment by daita** [comment]
I am working on a new full text search app for nextcloud, more structured code that would:

- extends the base search system already in use in Nextcloud. Meaning that 3rd party client (mobile, ...) we be able to search a file.
- allow any other app to add its own Search Provider via info.xml
- separate the indexing and the search, so any search platform can be integrated (solr, elastic_search, ...)

I am afraid I won't work a compat with solr7 on nextant.

**Comment by enoch85** [comment]
Okay, let's revert to the latest Nextant 6.X.

I'll prepare a PR later.
