### ISSUE TITLE
Create a .torrent for download

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#375]
@nachoparker I saw that you made one, but I didn't manage to get it right. Could you help out?

**Comment by nachoparker** [comment]
sure,

I do it with [this function](/etc/letsencrypt/live/javicloud.ddns.net/fullchain.pem)

do you want a PR somewhere?

**Comment by nachoparker** [comment]
I also add a md5sum, do you also distribute some sort of big iso file? (or qcow or whatever)

**Comment by enoch85** [comment]
@nachoparker Nice! Will that torrent be in the guest system or what?

A PR would be nice indeed.

**Comment by nachoparker** [comment]
That's only torrent creation, then you can open that with some torrent client and it will be automatically be shared.

That would require another line like `transmission-gtk torrentfile.torrent`.

**Comment by enoch85** [comment]
@nachoparker It would be nice if you could make a gist or something like that. I'll need it locally, not in the VM.

Thanks mate!

**Comment by enoch85** [comment]
I found `ctorrent` but I don't get how to upload the torrent. This is what I did:

`ctorrent -t -u "udp://tracker.opentrackr.org -p 1337" -s Nextcloud_VM_Production.torrent /home/daniel/Desktop/Nextcloud_Community_VM_PRODUCTION.ova` 

I then put the file in Transmission but nothing happened.

**Comment by nachoparker** [comment]
I use `createtorrent` (see link above), and then I can open it with transmission. Make sure that the dir for downloads is the one where the ova is so transmission can find it.

**Comment by enoch85** [comment]
If the file is in the path, then it shouldn't matter for Transmission right? I mean, I have the file on my Desktop, but stil nothing happened when I added the torrent file in Tranmission. :/

**Comment by nachoparker** [comment]
weird. Try my function, that uses `createtorrent`. I haven't used `ctorrent`

**Comment by enoch85** [comment]
It doesn't seem to be included in Ubuntu Repos?

**Comment by nachoparker** [comment]
mmm I don't know, I use Arch...

**Comment by enoch85** [comment]
Aah, that's why. :/

**Comment by nachoparker** [comment]
yeah

```
aur/createtorrent 1.1.4-5 [installed] (28) (0.00)          
    A small and fast command line utility for all Linux and Unix operating systems to create BitTorrent files easily.
```
https://sourceforge.net/projects/createtorrent/

This is the PKGBUILD if you want to build it yourself

```
# Maintainer: nblock <nblock [/at\] archlinux DOT us>                                                                                                                                                                                          
# Contributor: pfleidi

pkgname=createtorrent
pkgver=1.1.4
pkgrel=5
pkgdesc="A small and fast command line utility for all Linux and Unix operating systems to create BitTorrent files easily."
url="http://createtorrent.sourceforge.net"
arch=('i686' 'x86_64')
license=('GPL')
depends=('openssl')
source=(http://distfiles.macports.org/createtorrent/$pkgname-$pkgver.tar.gz)
md5sums=('922b18eeec74ea81f22a3392e2680307')
sha1sums=('f96fec9b8e1daa06d180f985f58b6d57a05d262d')

build() {
   cd $srcdir/$pkgname-$pkgver
   LDFLAGS="-lssl -lcrypto -ldl -lz" ./configure --prefix=/usr
   make
}

package() {
   cd $srcdir/$pkgname-$pkgver
   make DESTDIR=$pkgdir install
}
```

**Comment by enoch85** [comment]
Thanks, will have a look.

**Comment by enoch85** [comment]
Releasing on Github works. Maybe will pink this up later. Never really got were to upload the torrent...

**Comment by ZaxLofful** [comment]
I would love to use my bandwidth to support this, a great way to make delivery faster. I wasn't able to find the torrent on the Tech and Me Website. Did you ever make a .torrent file for this?

Make sure you include the ability to use DHT, peer exchange, and other stuff like that. You will need trackers as well, [here is a list of open ones](https://github.com/ngosang/trackerslist).

Once you have you just need a few more things, if you are starting the torrent you need to host the files using some type of torrent client. There are tons of free ones, but I recommend [Deluge](https://deluge-torrent.org/).

To start the hosting...create a VM, then move the .torrent file and the actual files themselves to the VM and start the client. It should report the status immediately as "Seeding". At this point you have to leave this VM on indefinitely, so others can get to the files. Eventually there will be enough people that if the VM went down it wouldn't matter; but in the beginning it needs to be up all the time.

After that you can upload the .torrent file on GitHub and have people download it via RAW or you can generate a magnet link.

**Comment by enoch85** [comment]
> Did you ever make a .torrent file for this?

No, do you know how to do it? Would be nice with a PR!

>  if you are starting the torrent you need to host the files using some type of torrent client. There are tons of free ones, but I recommend Deluge.

Tech and Me has a server so that's no issue. :)

**Comment by enoch85** [comment]
No relevant anymore.
