### ISSUE TITLE
Not able to start activate-ssl.sh

### ISSUE THREAD

**Issue by ma-schmidt-de** [nextcloud/vm#379]
Hi guys,

after downloading the VM (version 12.0.3) two days ago I did a clean installation and skipped setup of trusted SSL certificate. A day later I logged in again and tried starting `/var/scripts/activate-ssl.sh`. This failed with error message:
> Sorry, you are not root.

Please see screenshot attached:
<img width="485" alt="screen shot 2017-09-27 at 00 34 08" src="https://user-images.githubusercontent.com/19306046/30887705-db566f4c-a31c-11e7-8a4d-d3f224d9d766.png">

Am I doing something wrong?
Clearly, last line's tip doesn't help. :)
> You need to type: sudo bash /activate-ssl.sh

Any hints appreciated.
Cheers

**Comment by enoch85** [comment]
Are you sure you have a working internet connection?

The path is fixed now btw, thanks for the heads up!

**Comment by enoch85** [comment]
Yup, this is due to that you don't have a working internet connection and thus can't fetch the $vars.

Closing.

**Comment by ma-schmidt-de** [comment]
You're absolutely right. This failed because of missing internet connection.
I did change local ip after installation via `sudo nano /etc/network/interfaces` and this did break internet connection. 
I set it back to the initial ip and `activate-ssl.sh` now runs just fine.

Thanks!
