### ISSUE TITLE
Hangs at "Started LSB: Controles Apache Solr as a Service"

### ISSUE THREAD

**Issue by mygeek911** [nextcloud/vm#385]
## Steps to reproduce
1. Download Ubuntu 16.04 OVA: Pre-installed Nextcloud PHP 7 from Tech and Me
2. Import the VM and start it
2. Wait until it gets to the part of installing the Solr service
3. Hang...

## Expected behaviour
I'm sure the script should continue, but it hangs. I let it run from Friday, September 29, at 3:30PM in the afternoon until Monday, October 2, at 12PM.

## Actual behaviour
The script was still hung with the message "Started LSB: Controls Apache Solr as a Service".

## Server configuration

**Server version:** (see your admin page)
Ubuntu 16.04 (downloaded from Tech and Me on September 29, 2017)

**VM version** (master / released version)
VMware Player v14.0.0.24051 (downloaded September 29, 2017 from www.vmware.com)

**Updated from an older installed version or fresh install:**
Fresh install.

## Network
**Do you use DHCP?**
Virtual machine is set to receive a static IP.

**Is port 80 and/or 443 open?**
Yes.

## Logs / Screenshots

https://imgur.com/a/aTqHx

#### Log file (/var/ncdata/nextcloud.log)
```
Unable to get since script is hung.
```

#### Installation log (command output)
```
Unable to get since script is hung.
```

**Comment by enoch85** [comment]
Press `Q` and it will continue.

Please confirm.

**Comment by enoch85** [comment]
And thank you for a detailed report!

**Comment by mygeek911** [comment]
You are welcome. Wish I would have left it open, but I figured you wouldn't reply so soon. I'll retry it again from scratch!

**Comment by mygeek911** [comment]
That was the issue: capital **Q** worked! The installation went smoothly after that. Thank you.

**Comment by enoch85** [comment]
@mygeek911 Great! Glad you solved it.
