### ISSUE TITLE
Only shows white /blank page after install.

### ISSUE THREAD

**Issue by Calby1988** [nextcloud/vm#397]
Hi,
Well, I have tried to install it several times with this script and after installation when I browse to it it just show a white / blank page.

I have tried different browsers etc.
Re-installed it etc.

This did not happen before you did update the script on my other machines.

**Comment by enoch85** [comment]
https://www.sweclockers.com/forum/post/17048411

**Comment by enoch85** [comment]
Fixed: https://github.com/nextcloud/vm/pull/398
