### ISSUE TITLE
redis-php-extenstion should also be added to php-cli because of cronjob

### ISSUE THREAD

**Issue by merkur-kun** [nextcloud/vm#401]
Hi,

in redis-server-ubuntu16.sh you should add
echo 'extension=redis.so' >> /etc/php/7.0/cli/php.ini
so the cronjob does its job correct.

I had the following problem, which was fixed by doing the above:

## Steps to reproduce
1. Upload a bigger file (mine had >4GB but I suspect the problem starts at >1GB)
2. wait till the upload is finished

## Expected behaviour
Upload should succeed and file appear in filelist

## Actual behaviour
Short message "file locked" and file doesn't appear in list

## Server configuration

**Server version:** Nextcloud 12.0.3

**Updated from an older installed version or fresh install:** updated

#### Log file (/var/ncdata/nextcloud.log)
```
Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\FileLocked: "filename.ext" is locked

    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 151: OCA\DAV\Connector\Sabre\File->put(Resource id #23)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile('filename...', Resource id #23)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('filename...', Resource id #23, NULL)
    [internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 76: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 162: require_once('/var/www/nextcl...')
    {main}
```

**Comment by enoch85** [comment]
Great catch! Thank you!

**Comment by enoch85** [comment]
Now when thinking about it, we don't use CLI and the Unlocking of files works. Are you really sure CLI is needed as well?

**Comment by merkur-kun** [comment]
Actually I'm not sure anymore.. Yesterday I *thought* that was the solution to my problem:
my thought was: what would interrupt my uploads and file locking? Maybe that cronjob? Shouldn't it have access to redis too? So I changed that and my upload was succesful but now that I think of it, maybe that was because of other reasons (eg. restarting the server or just got lucky)
Now today my upload test failed again, so there seems to be another problem (it does work when disabling file locking, but I know that is not recommended).
In that case: Sorry for the noise, I should go research and test my stuff more thoroughly before shooting..

**Comment by enoch85** [comment]
I just tested myself. Adding that results in `Module 'redis' already loaded at Unknown#0` as it's already loaded. So naah, I'm not so sure about this. 

Please prove me wrong.
