### ISSUE TITLE
Blank https:// page.

### ISSUE THREAD

**Issue by Calby1988** [nextcloud/vm#402]
I did write this issue before also.

After installing with this script nextcloud can't show in the webbbrowser, the page is just blank (white).
My guess is that the script are installing as root and then when the server runs with the default user it don't has the right permissions to show the pages.

**Comment by enoch85** [comment]
@Calby1988 Did you run the Let's Encrypt scripts, or is this without SSL?

**Comment by Calby1988** [comment]
I did run ti with Let's Encrypt

**Comment by enoch85** [comment]
I just did a clean install on a DO VPS with both PostgreSQL and MariaDB, with and without Lets Encrypt. In none of the setups I had a blank page when accessing https. This is an error on your end, not in the scripts.

**Comment by enoch85** [comment]
If you have time to visit them before I close them, here they are:

https://testcloud.techandme.se
https://testonly.techandme.se
