### ISSUE TITLE
Port 443 is not open when it's actually open.

### ISSUE THREAD

**Issue by haidev12** [nextcloud/vm#403]
## Actual behaviour
Tell us what happens instead
Received this message Port 443 is not open on (server IP) We will do a second try on (domainname.com) instead.
## Server configuration

**Server version:** (see your admin page)

**VM version** (master / released version)

**Updated from an older installed version or fresh install:**
Fresh Install
## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
Yes
#### Screenshoots
http://i.imgur.com/jQanxTn.png

**Comment by enoch85** [comment]
Thanks for the report.

Did it work the second time when it tried on the domain name instead?

**Comment by enoch85** [comment]
ping @haidev12

**Comment by haidev12** [comment]
No it did not. I will try to run a new VM and let you know about the results.

**Comment by enoch85** [comment]
Please run the script manually with SSH in debug mode, and copy the output to hastebin and post it here.

`sudo bash -x /var/scripts/nextcloud-startup-script.sh`

**Comment by haidev12** [comment]
@enoch85 Thank you for your help! Sorry for the delay had to prepare for uni exams. Also I found the problem. It seems like my ISP is blocking port 80 and that was one of the reasons had to change apache's port. Now everything is working and I can access nc from the internet the only issue is that I am having a new error not sure if I should open a new case or post it here. Again sorry for my ignorance and thank you for your help.

**Comment by haidev12** [comment]
@enoch85 Here is the new issue if you want to take a look into it.
Screenshot: https://i.imgur.com/Eeslqv2.png

**Comment by enoch85** [comment]
@haidev12 Please google the first error output and post in that issue instead. Thanks. :)

**Comment by haidev12** [comment]
@enoch85 I will thanks
