### ISSUE TITLE
Photon/Alpine/Centos images?

### ISSUE THREAD

**Issue by bby-bishopclark** [nextcloud/vm#404]
The Readme suggests the official VM is only a uBurntU image.  Do we have anything on Enterprise linux, or a small image like Photon?

Thanks!

**Comment by enoch85** [comment]
No, the scripts are based on Ubuntu and has always been, back since 2014.

Anyone who want's to refactor them to Alpine (good choice) or anything else are welcome to do so.

@bby-bishopclark Are you up for the task? ;)

**Comment by enoch85** [comment]
There are a lot of variations nowadays. Alpine, CentOS, and different distros already exists. Hence, this issue is not valid anymore.

**Comment by bby-bishopclark** [comment]
I'm not sure how the final answer addresses the question, but it's your decision.  It may be easier for someone else with more alpine/photon experience, so we'll look for that if nextcloud is still a solution for us.
