### ISSUE TITLE
Setup issue - no blue screen but command line

### ISSUE THREAD

**Issue by padussau** [nextcloud/vm#408]
## Steps to reproduce
1. setting up vm in VirtualBox (last version) on Windows 10.0 host
2. running script
3.

## Expected behaviour
I should have the blue screen for login

## Actual behaviour
I have a command line screen, yet the login works but I got nothing else (see attached pic)

## Server configuration

**Server version:** Cannot see any admin page

**VM version** (master / released version) VirtualBox Version 5.2.0 r118431 (Qt5.6.2)

**Updated from an older installed version or fresh install:** Fresh install

## Network
**Do you use DHCP?** no

**Is port 80 and/or 443 open?** yes

## Logs / Screenshots

![2017-11-01 1](https://user-images.githubusercontent.com/33278845/32265814-fc49c580-bee4-11e7-8609-fcf5603214bf.png)

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here   Can't find it, no access
```

#### Installation log (command output)
```
Insert the CLI output here    same
```

**Comment by enoch85** [comment]
I don't understand? Which blue screen?

Go to your internal or external IP and you will see the blue screen if you mean the login page.

**Comment by padussau** [comment]
Hello,
thanks for your fast answer.
What do you mean with external or internal IP? I just see 2 IPs: the first one (194.118.71.111) leads to my router's web interface, the other one (10.0.2.15) does not answer.
What did I miss?

**Comment by enoch85** [comment]
I don't know how you setup your network. The scripts work so this is not a scripts issue, rather a configuration issue on your end. I recommend you to go to help.nextcloud.com and ask for help there, or buy support in out shop: shop.techandme.se

**Comment by enoch85** [comment]
And btw, the scripts setup your internal IP from DHCP, and it says which IP you can connect to Nextcloud on the last page.

Internal is 10.X.X.X in your case.
