### ISSUE TITLE
spreedme - Service Unavailable

### ISSUE THREAD

**Issue by ace0024** [nextcloud/vm#409]
## Steps to reproduce
1. JiffyBox Server with a clean Ubuntu 16.04 from df.eu
2. Install NC :
apt-get install snap snapd snap-confine lshw screen snapcraft
and then with this scripts:
Get the latest install script from master:
wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
Run the script with:
sudo bash nextcloud_install_production.sh

Do you want to enable HTTP/2 system wide? ([y]es or [N]o): N
enable igbinary serializer support? [no] : no
Do you run this script on a *remote* VPS like DigitalOcean, HostGator or similar? ([y]es or [N]o): y
Do you want to install SSL? ([y]es or [N]o): y
Are you sure you want to continue? ([y]es or [N]o): y
Have you forwarded port 443 in your router? ([y]es or [N]o): y
Do you have a domain that you will use? ([y]es or [N]o): y

## Expected behaviour
Tell us what should happen

## Actual behaviour
i ve got this error during the installation. If i click at the Nextcloud Page at the SpreedMe Icon, i ve got the "Service Unavailable" Error
 
## Server configuration

**Server version:** (see your admin page)
Ubuntu 16.04
Lastest NC Version

**VM version** (master / released version)
lastest
**Updated from an older installed version or fresh install:**
fresh install
## Network
**Do you use DHCP?**
no
**Is port 80 and/or 443 open?**
both
## Logs / Screenshots

error: cannot perform the following tasks:
- Mount snap "core" (3247) ([start snap-core-3247.mount] failed with exit status 1: Job for snap-core-3247.mount failed. See "systemctl status snap-core-3247.mount" and "journalctl -xe" for details.
)

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.18 (Ubuntu) Server at c.webundstyle.com Port 443

**Comment by enoch85** [comment]
You should use the [SpreedMe script](https://github.com/nextcloud/vm/blob/master/apps/spreedme.sh), not install it by yourself.

You are also asked to install it during the first setup.

**Comment by ace0024** [comment]
Thank you, but that did not work. (during installation)

**Comment by enoch85** [comment]
In you decription it says that you are installing the snap before you run the script.

>  apt-get install snap snapd snap-confine lshw screen snapcraft
and then with this scripts:
Get the latest install script from master:
wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
Run the script with:
sudo bash nextcloud_install_production.sh

**Comment by ace0024** [comment]
without installing this at first:

snap snapd snap-confine lshw screen snapcraft

I did this because I had a few errors in the past...


only start the script...right?

i will try it...

**Comment by enoch85** [comment]
The script should take care of everything as long as it's a normal Ubuntu installation. I can't answer for all the VPS providers out there.
