### ISSUE TITLE
certbot renew fails due to conflict between apache port 443 and certbot

### ISSUE THREAD

**Issue by diddledan** [nextcloud/vm#410]
## Steps to reproduce
1. Wait for certbot to run the renew (either via the twice-daily `/etc/cron.d/certbot` or root's weekly crontab entry for `/var/scripts/letsencryptrenew.sh`
2. check the log for success `/var/log/syslog` for the twice-daily certbot run, or `/var/log/letsencrypt/renew.log` for the weekly crontab run.
3. ...
4. not profit. :-(

## Expected behaviour
The certificate should be renewed.

## Actual behaviour
The certificate is not renewed because apache is using port 443 so certbot cannot bind to that port to authorize the renewal.

## Server configuration

**Server version:** 12.0.3

**VM version:** ??? Is this recorded in the VM? I don't have the ova file any more.

**Updated from an older installed version or fresh install:** Updated

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
Yes

#### Log file (/var/log/syslog)
```syslog
Nov  9 12:00:01 cloud CRON[79487]: (root) CMD (test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(3600))' && certbot -q renew)
Nov  9 12:18:18 cloud certbot[79646]: Attempting to renew cert (cloud.bowlhat.net) from /etc/letsencrypt/renewal/cloud.bowlhat.net.conf produced an unexpected error: Problem binding to port 443: Could not bind to IPv4 or IPv6.. Skipping.
Nov  9 12:18:18 cloud certbot[79646]: All renewal attempts failed. The following certs could not be renewed:
Nov  9 12:18:18 cloud certbot[79646]:   /etc/letsencrypt/live/cloud.bowlhat.net/fullchain.pem (failure)
Nov  9 12:18:18 cloud certbot[79646]: 1 renew failure(s), 0 parse failure(s)
```

#### Log file (/var/log/letsencrypt/renew.log)
```plain
Attempting to renew cert (cloud.bowlhat.net) from /etc/letsencrypt/renewal/cloud.bowlhat.net.conf produced an unexpected error: Problem binding to port 443: Could not bind to IPv4 or IPv6.. Skipping.

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/cloud.bowlhat.net/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)
```

**Comment by enoch85** [comment]
Please add this to a file and run it with bash: https://github.com/nextcloud/vm/blob/master/lets-encrypt/test-new-config.sh#L46-L64

**Comment by enoch85** [comment]
Hmm, may not work after all. In the new scripts I've implemented the --pre and --post tags which automatically stops and starts Apache when renewing. Google it and add it if --^ doesn't work.
