### ISSUE TITLE
networking.service failed coming back up agian after the first reboot

### ISSUE THREAD

**Issue by MrLordy** [nextcloud/vm#412]
This is using the install script on a hetzner dedicated server.

NOTE: Nothing have been installed on the box before i started running this script ether.

First steps goes thru fine. but when it starts with step 3 and i loggin with the new user "ncadmin" I get this error.. 

Job for networking.service failed because the control process exited with error code. See "systemctl status networking.service" and "journalctl -xe" for details.

"systemctl status networking.service" bring up this. 

● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/generator/networking.service.d
           └─50-insserv.conf-$network.conf
   Active: failed (Result: exit-code) since Fri 2017-11-17 21:06:40 CET; 7min ago
     Docs: man:interfaces(5)
  Process: 2430 ExecStop=/sbin/ifdown -a --read-environment --exclude=lo (code=exited, status=0/SUCCESS)
  Process: 2474 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=1/FAILURE)
  Process: 2469 ExecStartPre=/bin/sh -c [ "$CONFIGURE_INTERFACES" != "no" ] && [ -n "$(ifquery --read-environment --list --exclude=lo)" ] && udevadm settle (code=exited, status=0/SUCCESS)
 Main PID: 2474 (code=exited, status=1/FAILURE)

Nov 17 21:06:34 Ubuntu-1604-xenial-64-minimal systemd[1]: Starting Raise network interfaces...
Nov 17 21:06:40 Ubuntu-1604-xenial-64-minimal ifup[2474]: Waiting for DAD... Timed out
Nov 17 21:06:40 Ubuntu-1604-xenial-64-minimal ifup[2474]: Failed to bring up eth0.
Nov 17 21:06:40 Ubuntu-1604-xenial-64-minimal systemd[1]: networking.service: Main process exited, code=exited, status=1/FAILURE
Nov 17 21:06:40 Ubuntu-1604-xenial-64-minimal systemd[1]: Failed to start Raise network interfaces.
Nov 17 21:06:40 Ubuntu-1604-xenial-64-minimal systemd[1]: networking.service: Unit entered failed state.
Nov 17 21:06:40 Ubuntu-1604-xenial-64-minimal systemd[1]: networking.service: Failed with result 'exit-code'.

And as off the above is where i am stuck atm.  is there any fix to this?  :)

**Comment by enoch85** [comment]
Did you set static IP with the script?

**Comment by MrLordy** [comment]
you referring to the first question "Do you run this script on a *remote* VPS like DigitalOcean, HostGator or similar?") ? 
if so i answered yes . and if i recall that meant it didn't do anything with ips since already got static ip.

i also uncomment this part in the production.sh script

```
# Change DNS
if ! [ -x "$(command -v resolvconf)" ]
then
    apt install resolvconf -y -q
    dpkg-reconfigure resolvconf
fi
echo "nameserver 8.8.8.8" > /etc/resolvconf/resolv.conf.d/base
echo "nameserver 8.8.4.4" >> /etc/resolvconf/resolv.conf.d/base
```

to remove the resolv error.  i also had at first.

**Comment by enoch85** [comment]
OK, then there shouldn't be any issues. I just installed with the scripts on a STRATO server for a customer, and there I had to install `curl` and `software-properties-common` as it was missing. I can confirm the scripts to work on DigitalOcean, as they provide a clean (regular) Ubuntu installation. I don't know about Hetzner, sorry.

And as this is no script error, there's not much I can do but to offer you support through our shop.

**Comment by MrLordy** [comment]
well then i just ignore the problem. and go true :)

**Comment by MrLordy** [comment]
if you want access to the server and just have a look to make sure or something to better it for users later just give me a heads up. :)

**Comment by enoch85** [comment]
I can have a quick look now. Send me an email to daniel at techandme.se

**Comment by MrLordy** [comment]
its done :)

**Comment by enoch85** [comment]
There doesn't seem to be any issues

![screenshot from 2017-11-18 19 18 44](https://user-images.githubusercontent.com/4511254/32983466-5c61b398-cc95-11e7-9d62-197bbf39b386.png)

**Comment by MrLordy** [comment]
k :)  assume that was just some ubuntu/hetzner bug then.  i also did the systemctl status networking.service now and its all seems to be working . no error.

**Comment by enoch85** [comment]
Just to confirm, the installation seems to be OK.

**Comment by MrLordy** [comment]
That's good to hear.  Really appreciate this :)  i dropped the openoffice and phpmyadmin to minimal the things that could interfere.  So i just will install that after.

**Comment by enoch85** [comment]
My default install excludes Webmin, and installs Fail2ban. I also use PostgreSQL for the speed it brings. :)

**Comment by MrLordy** [comment]
does it only bring speed ? or is there other advantages ? 

also will your nextcloud-startup-script.sh work installing openoffice after it have been run and everything is working ?   or should i just use the sudo bash /var/scripts/onlyoffice.sh  to install it ?

**Comment by enoch85** [comment]
Mostly speed, and also that it's pure UTF8, which MariaDB doesn't have. It's a better DB in general.

1. Download the raw file from this repo
2. Run it with sudo bash

**Comment by MrLordy** [comment]
might maybe want me to make a new issue ?  

i tried installing using sudo bash openoffice.sh  resultet in this at the end.. 

Running post-hook command: service apache2 start
Failed authorization procedure. office.mydomain.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Timeout

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: office.mydomain.com
   Type:   connection
   Detail: Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

domain and all is pointing to the right ip and all that. .

**Comment by enoch85** [comment]
It takes time for a domain to propagate, up to 48 hours. So did you recently create the domain Let's Encrypt won't find it and the result above is what's happening.

**Comment by MrLordy** [comment]
it was added few days ago and do resolve fine. and all that, i did find a fix for some off the error..  

by adding this too the config file..  

'onlyoffice' =>
array (
'verify_peer_off' => TRUE,
),

but still get this error

Error | onlyoffice | CommandRequest on check error: Error occurred in the document service | 2017-11-18T21:20:04+0100
-- | -- | -- | --
Error | PHP | Trying to get property of non-object at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#293

also. should onlyoffice show a  document server running page aka a welcome page on the office.domain.com ?  witch its not here.

**Comment by enoch85** [comment]
@MrLordy I've run the scripts several times without any error. As late as yesterday the script were fine, and I haven't changed anything since. I propose that you ask for help in https://help.nextcloud.com
