### ISSUE TITLE
activate-ssl.sh runs on error

### ISSUE THREAD

**Issue by ThorPrez** [nextcloud/vm#414]
I´ve downloaded the current image for vmware.
When it´s coming to SSL setup I got an error
![nextcloud_fehler_ssl](https://user-images.githubusercontent.com/33800583/32988864-45a643da-cd0d-11e7-9566-7b4a1045f259.jpg)
The Subdomain is in this list [https://publicsuffix.org/list/public_suffix_list.dat](url), so it must work.
Any solutions ?

With kind regards,
Thorsten

**Comment by enoch85** [comment]
Most often it's a firewall issue. I also see that you are using a ddns.net domain, I'm [not sure that will work](http://lmgtfy.com/?q=ddns.net+let%27s+encrypt). Also first cerificate is localhost.localdomain, which isn't correct. 

So, fix those things, Google for solutions, and it will work. This is no script error.

**Comment by ThorPrez** [comment]
I´ve run the guided installation with all skripts.
It´s definitely no firewall issue und den subdomain is listet.
I´ve not added localhost.localdomain

Your answer wasn´t really helpfull 👎

**Comment by enoch85** [comment]
@ThorPrez If it works for me on different servers, and also when installing on customers servers, and it doesn't work for you, there must be something wrong on your end.

I'm glad you reported something that you thought was wrong, otherwise the scripts wouldn't progress. But in this case, I'm pretty sure there are no bug in the scripts. 

Sorry if you thought my first answer was harsh.

**Comment by ThorPrez** [comment]
Based on the guided setup I´m having a listed subdomain, TCP443 is forwarded to the VM, so what could be the issue ? It´s also a problem to generate a self-signed certificate. HTTPS is not working on the vm with the current nextcloud vm

**Comment by enoch85** [comment]
@ThorPrez I installed a VM as late as today on a customers server, and there where no issues with SSL.

**Comment by enoch85** [comment]
@ThorPrez Did you try to install it again? Did it work?

**Comment by ThorPrez** [comment]
I`ve tried it a lot times.
Maybe the port is closed in Ubuntu, but ufw is deactivated.

**Comment by enoch85** [comment]
This is how you do it from start: https://www.youtube.com/watch?v=LlqY5Y6P9Oc

Tested the scripts yesterday, there was nothing wrong.
