### ISSUE TITLE
Downloaded ZIP archive is always corrupted

### ISSUE THREAD

**Issue by corwin78** [nextcloud/vm#415]
Hello, always, when I will download Nextcloud.Community.VM.OVA.zip it is corrupted. ZIP is reporting error, and even if I will extract the archive with errors, then it is not possible import it to VirtualBox.
I am tried download files several times, always exactly the same result.
File MD5 after download is: ca61e9d3048dc262c5e88b99afa9a30c

**Comment by enoch85** [comment]
Are you downloading from Github or from our (Tech and Me) server?

**Comment by corwin78** [comment]
From Github, this link: https://github.com/nextcloud/vm/releases/download/12.0.3_1/Nextcloud.Community.VM.OVA.zip

**Comment by enoch85** [comment]
Just tested. Works for me.
