### ISSUE TITLE
Failed to Install Nextant

### ISSUE THREAD

**Issue by hammeractual** [nextcloud/vm#416]
## Steps to reproduce
1. Install Nextcloud with latest vm
2. Choosed nextant to install

## Expected behaviour
Nextant successfully installed 

## Actual behaviour
Nextant failed to installed because solr is failed to installed

## Server configuration
Fresh install VM from https://github.com/nextcloud/vm/releases/download/12.0.3_1/VMDK_Nextcloud_Community_VM_PRODUCTION.rar

## Network
Use DHCP
Both port 80 & 443 open.

#### Log file (/var/ncdata/nextcloud.log)
```
****
```

#### Installation log (command output)
```

```

#### Screenshoots
https://imgur.com/a/T9Wds

**Comment by enoch85** [comment]
@hammeractual Can you run the script separately in debug mode and post the output here please?

**Comment by hammeractual** [comment]
Which script?
How do i run the script?
Thanks.

**Comment by enoch85** [comment]
This script: https://github.com/nextcloud/vm/blob/master/apps/nextant.sh

`wget https://raw.githubusercontent.com/nextcloud/vm/master/apps/nextant.sh`
`sudo bash nextant.sh`

**Comment by enoch85** [comment]
Fixed in latest version.
