### ISSUE TITLE
MariaDB & Fail2ban Installation Error on First Time VM Installation

### ISSUE THREAD

**Issue by hammeractual** [nextcloud/vm#417]
## Steps to reproduce
1. Install Nextcloud with latest vm
2. MariaDB installation failed
3. Fail2ban installation failed

## Expected behaviour
Installation run smoothly without any error.

## Actual behaviour
Failed to start MariaDB Server
Failed to install Fail2ban

## Server configuration
Fresh install VM from https://github.com/nextcloud/vm/releases/download/12.0.3_1/VMDK_Nextcloud_Community_VM_PRODUCTION.rar

## Network
Use DHCP
Both port 80 & 443 open.

#### Log file (/var/ncdata/nextcloud.log)
```

```

#### Installation log (command output)
```

```

#### Screenshoots
https://imgur.com/a/GJvkT

**Comment by enoch85** [comment]
@hammeractual What failed? Do you have any logs? 

It works for me.

**Comment by hammeractual** [comment]
I don't know where the log is located. 
I just deleted the vm, repeat the entire process from the scratch, and same thing happened.

Perhaps, you can try by yourself using the latest vm you've provided with similiar scenario as I did.
I'm using VMWare Workstation Pro 14, Processor setting changed to 1 core, the rest settings/config are the same/default settings.

**Comment by enoch85** [comment]
> Perhaps, you can try by yourself using the latest vm

That's what I did, and it worked.

Try VMware 12 and see if it behaves differently.

**Comment by hammeractual** [comment]
Which version of VMWare do you used?
Ok, I'll try with VMWare 12, I'll tell you the result soon.

**Comment by hammeractual** [comment]
FYI:
https://imgur.com/a/Y6kIp

I've used VMWare Workstation Pro 12 version 12.5.8 with your VM 12.0.3_1, but the error still persist.
I think, the problem is in your VM.

Please we need your help to fix those problems, thanks. :)

**Comment by enoch85** [comment]
Just tested it works: https://cloud.fsgo.se/s/QdhegPP7kCjODFO

There is nothing wrong with the VM, rather MariaDB that can't upgrade, probably due to some settings in the deb. As you can see it works if you just wait it out and let it restart.

**Comment by hammeractual** [comment]
So what's actually wrong? Of course, i've waited until the process is finished by itself and it took a lot of time.
FYI, until the process was finished, this was what happened to the nextcloud.
https://imgur.com/a/8wIvJ

**Comment by enoch85** [comment]
Post this in the Ubuntu bug tracker instead. I put mariadb* on hold for apt, so now it won't update mariadb and it should work.
