### ISSUE TITLE
Strange looping happened!

### ISSUE THREAD

**Issue by hammeractual** [nextcloud/vm#418]
I don't know why in this release, a lot of bugs & errors were happened. :(

## Steps to reproduce
1. Install Nextcloud using latest vm
2. Installation runs with MariaDB & Fail2ban error
3. Strange looping happened after changing password that requested by the automatic installation script

## Expected behaviour
Password changed & installation continued

## Actual behaviour
Strange looping happened

## Server configuration
Fresh install VM from https://github.com/nextcloud/vm/releases/download/12.0.3_1/VMDK_Nextcloud_Community_VM_PRODUCTION.rar

VMWare Workstation Pro 14

## Network
Use DHCP
Both port 80 & 443 open.

#### Log file (/var/ncdata/nextcloud.log)
```

```

#### Installation log (command output)
```

```

#### Screenshoots
https://imgur.com/a/mBCuc

**Comment by enoch85** [comment]
It works for me. Please be more precise in your description. Just saying "it doesn't work" doesn't help me much.

I think you are running with non default firewall settings or something. I never get those errors you get.

**Comment by hammeractual** [comment]
I didn't touch any settings yet.

When setting up mariadb process failed & installing fail2ban failed, bla bla suddenly those processes passed through to the next processes and the process came to change password for ncadmin, after retype new password is done, that screen (as the screenshot i've attached to you) were happened.

You can investigate by yourself.
I'm using VMWare Workstation Pro 14, Processor setting changed to 1 core, the rest settings/config are the same/default settings.

**Comment by enoch85** [comment]
Just tested it works.
