### ISSUE TITLE
No DHCP offer when installation scripts is running

### ISSUE THREAD

**Issue by Flintebassen** [nextcloud/vm#42]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Create networkcard in esx6

## Actual behaviour
No active networkcard and nextcloud do not get dhcp offer

## Server configuration

Latest 500GB vmdk version.

**VM version**
6

**Updated from an older installed version or fresh install:**
Fresh install

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

**Comment by enoch85** [comment]
@Flintebassen Is this a valid issue?

**Comment by Flintebassen** [comment]
It was. 
I closed the case because i found another solution.
I deleted the preconfigured network card in the vpshere client and added a new one.
