### ISSUE TITLE
Nextcloud sync with Nextcloud client internal server error

### ISSUE THREAD

**Issue by kzieres61** [nextcloud/vm#421]
## Steps to reproduce
1. Install nextcloud client
2. upload files to server VIA nextcloud client
3. Error in nextcloud log's

## Expected behaviour
Files should upload properly to the server

## Actual behaviour
Internal Server error on over 90% of files, from small to large ones.

## Server configuration
Nextcloud VM, with fail2ban
**Server version:** (see your admin page)
12.0.3 stable
**VM version** (master / released version)
VirtualBox 5.2.0r118431

**Updated from an older installed version or fresh install:**
Fresh install
## Network
**Do you use DHCP?**
no DHCP

**Is port 80 and/or 443 open?**
I use port 8080

## Logs / Screenshots
https://hastebin.com/miyayefaje.sql

#### Log file (/var/ncdata/nextcloud.log)
[nextcloud.log](https://github.com/nextcloud/vm/files/1515090/nextcloud.log)

**Comment by enoch85** [comment]
I don't think this is a VM issue, rather a client issue. But just to be sure, run this command in the DB: https://github.com/nextcloud/server/issues/6187#issuecomment-341457428

**Comment by enoch85** [comment]
Also, I'm surprised you don't run SSL on your server when it's free, and much more secure.

**Comment by enoch85** [comment]
@kzieres61 Did you run the command from the link I posted above --^ ?

**Comment by kzieres61** [comment]
I apoligize. I have not had a chance yet.

It's not SSL cause I can't forward port 443 to my nextcloud server, and it's used internal use only.

**Comment by enoch85** [comment]
> It's not SSL cause I can't forward port 443 to my nextcloud server, 

Just curious, why not? SSL adds much more security to your server.And it's not internal since I can reach it from here. Internal would be if you run it with an internal IP adress, and not a TLD like you do now.

Also, VirtualBox are know to have not-so-good networking. So try to change the hypervisor, increase CPU + RAM to see if it behaves differently.

**Comment by kzieres61** [comment]
I don't see any commands to enter on that link you sent?

**Comment by enoch85** [comment]
`On the database I executed
SELECT @@GLOBAL.tx_isolation, @@tx_isolation`

**Comment by kzieres61** [comment]
When I type that into the linux command line, I get  SELECT: command not
found.  Where am i supposed to put this command in?

**Comment by enoch85** [comment]
In the database, as my previous comment says. :)

**Comment by kzieres61** [comment]
How do i get to the database?

**Comment by thejohnha** [comment]
the root password for the DB is it /root/.my.cnf

**Comment by kzieres61** [comment]
Something happened over the weekend and now my client works...............
