### ISSUE TITLE
SSL Issues with forwarded port other than 443 if changed in domain.name.conf file.

### ISSUE THREAD

**Issue by ChuckNozzle** [nextcloud/vm#423]
## Steps to reproduce
1. Run 3 VM's on one server.
2. Run activate-ssl.sh using port 443 on router forwarded to each VM in turn
3. Change port in /etc/apache2/sites-available/domain.name.conf
4. Used port 4431, 4432 and 4433 for the various VM's

## Expected behaviour
I expect that the server should respond on either https://domain.name or https://domain.name:port.

## Actual behaviour
Cannot access NC via domain.name or via domain.name:port using https. Adding /login at the end does not help.

## Server configuration
**Server version:** 12.0.3

**VM version:** Assume released as downloaded VMDK over a year ago.

**Updated from an older installed version or fresh install:** Updated

## Network
**Do you use DHCP?**
Yes, but IP reserved for each machine.

**Is port 80 and/or 443 open?**
443 on each VM is forwarded to 4431, 4432, 4433 on the separate machines.

**Comment by enoch85** [comment]
@ChuckNozzle Thanks for your report, but how is this related to the scripts?

**Comment by enoch85** [comment]
Just an advice, if you want to run multiple machines on one external IP using HTTPS or HTTP, you should use a proxy to proxy all the outbound requests to the correct internal IP and port.

I wrote a guide you can try here: https://www.techandme.se/set-up-nginx-reverse-proxy/

I'll close this as it's nothing that we can control with the scripts, it's rather a custom user configuration.

**Comment by ChuckNozzle** [comment]
@enoch85 I am pretty new at this, so maybe I'm a bit mistaken here?

I thought this had most reference to the scripts, as it is the activate-ssl.sh script that determines the port in domain.name.conf, and it is from this intial determination, or a change to the .conf file that was written by the activate-ssl.sh script, that letsencryptrenew.sh derives its information from for renewal.

Thanks for the guide... I'll try it out!

**Comment by enoch85** [comment]
> activate-ssl.sh script that determines the port in domain.name.conf

443 is the standard port, and there is no such thing as "smart detection", it's default, nothing else. I don't even know if it would be possible to detect which ports are open and forwarded correctly in your router without some nasty hacking.

I don't know how your network is setup, but it sure sounds like an Nginx Reverse Proxy is the answer to your issues. With a proxy you can use the standard ports (443) on several domains, but the LE stuff happens on the proxy and not the backend. You could still use the scripts for that though.
