### ISSUE TITLE
Problems with collabora install

### ISSUE THREAD

**Issue by denhen** [nextcloud/vm#424]
Hi, 

i want so to install the collabora office with the following script: 
https://raw.githubusercontent.com/nextcloud/vm/master/apps/collabora.sh

**i Get the following error:**
Running post-hook command: service apache2 start
Failed authorization procedure. office.MYDOMAIN.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested 6fd95dc9bd4e60a9e22d2c9f71ed5887.bc8024e1b559beb4e44a8381c2ab.acme.invalid from MYIP:443. Received 3 certificate(s), first certificate had names "*.MYDOMAIN.com, MYDOMAIN.com"

Notice: i have a own wildcard certificate for the nextlcoud.
i Think it become a problem because the wildcard?

Can anybody help me?

Thanks,
Dennis

**Comment by enoch85** [comment]
PLease hash out (#) the following lines in the script and run it again: https://github.com/nextcloud/vm/blob/master/apps/collabora.sh#L215-L240 and then add your own certificate in the Apache conf file.

You also need to generate a DHParams manually.

Option 2: Ditch your wildcard cert and use LE instead, It's free and easier to maintain.

**Comment by denhen** [comment]
Hi Daniel,

thank you for reply.  The Cert Files was in the Apache config file.I add this during the installation via the Webadmin. The next cloud works with the right certificate.

Now i hash out the Lines 215-240 of the collabora.sh. No Euro message comes. But if i configure the App in next cloud an open an file i get a internal server error. can you help?

**Comment by enoch85** [comment]
If you want help with custom installations Tech and Me offers support in our shop: https://shop.techandme.se/index.php/product/premium-support-per-30-minutes/
You can also get support by Nextcloud: https://nextcloud.com/pricing/
