### ISSUE TITLE
lib.sh is downloaded and executed from raw.githubusercontent.com on every login

### ISSUE THREAD

**Issue by nkorth** [nextcloud/vm#427]
## Steps to reproduce
1. Log in as ncadmin

## Expected behaviour
Remote code is not downloaded and executed on my VM

## Actual behaviour
lib.sh is downloaded and executed (/var/scripts/nextcloud.sh:8), slowing down login and creating a nasty security hole. This kind of thing is acceptable in Javascript, but not in shell scripts. Imagine if a contributor's github account was compromised - an attacker could run arbitrary code on every instance of Nextcloud VM. Sure, that's a slightly obscure threat model, but I really don't see any reason why it's worth the risk to load this script from the network instead of bundling a local copy.

## Server configuration

**Server version:** 12.0.3

**VM version:** 12.0.3_1 from released OVA

**Updated from an older installed version or fresh install:** fresh

**Comment by enoch85** [comment]
"On every login"? WHat do you mean by that? lib.sh is used during the first setup, and also if you run a script separately from this repo. Not on every login apart from nextcloud.sh which is run on every SSH login.

As for security, nothing will be compromised as long as I live (I expect like 60 years or so from today). I'm the only one with full admin rights (except for the owners of this repo which is Nextcloud themselves) and everything goes through me. Try to commit to this repo if you'd like. You will notice that it's not possible.

It's better to fetch all the $vars everytime, as if we didn't things that might be broken couldn't be fixed and we'd have to make a new release (5 VMs in total) to fix it which is pretty time consuming.

**Comment by nkorth** [comment]
I meant on every SSH login, in nextcloud.sh.

Despite your confidence in your passwords, I maintain that this is an unnecessary security risk. The risk certainly isn't justifiable just as a way to avoid making new releases to fix bugs. Again, this isn't Javascript dev.

**Comment by enoch85** [comment]
OK, I get your point, thanks for making me activate 2FA. 

I will not change the behaviour here --> closing.

**Comment by enoch85** [comment]
@nkorth As you wish --^
