### ISSUE TITLE
Clean run fails to start nextcloud

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#436]
## Steps to reproduce
1. Install script with SSL on clean, updated Ubuntu Server 16.04
2. Loading web gui yields: `Internal Server Error` and nextcloud log indicates redis connect failure

**VM version** (Scripted install from master **OR** Released version)
Latest as of 20171220

## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
Yes
## Logs / Screenshots
![screen shot 2017-12-20 at 12 26 29](https://user-images.githubusercontent.com/6325833/34220162-9b3ca0aa-e581-11e7-8aaa-3bfb23c2558e.jpg)

#### Log file (/var/ncdata/nextcloud.log)
https://hastebin.com/xotivunosa.tex

**Comment by thejohnha** [comment]
The script finishes fine, but the GUI doesn't load. Mostly default settings with the script. Using SSL. Using HTTP/2. Using fail2ban and Nextant. Any help would be much appreciate @enoch85 Thank you!

**Comment by enoch85** [comment]
Please tell me the exact steps you took, and which apps you installed.

**Comment by enoch85** [comment]
No need, it's fixed now.

You need to change unixsock permissions to 777 instead of 770 in redis.conf then restart redis.

**Comment by thejohnha** [comment]
Amazing, thank you so much!
