### ISSUE TITLE
No Samba/SMB/CIFS Support in Hyper-V Image (TechandMe)

### ISSUE THREAD

**Issue by 3Dscrewer** [nextcloud/vm#437]
If I buy an Image for a Hyper-V installation, I'm a Beginner AND in most cases need Support for SMB/CIFS.
There should be in the Script the question if SMB/CIFS Support is necessary or not.
As a Beginner I am not able to figure out, how all the pathes I have to write in samba.conf.
Since I have tried also the NextCloudPi Image, I know it is possible to make Samba work with only one klick.
Or even a ready to work samba.conf.

Ok after weeks, days and hours, of trying, fiddling around ending up with a new setup, it seems that Windows 10 Pro has support for Linux and SMB/CIFS, but it would be nice to have a ready to use Samba.conf

Thank you

**Comment by enoch85** [comment]
There is SMB support in the VM, and has always been. 

I'm not sure what you are trying to archive here? Why not just use the External Storages App in Nextcloud?

**Comment by enoch85** [comment]
Closing in favour of post in the forums.
