### ISSUE TITLE
Include swap in mem_check

### ISSUE THREAD

**Issue by alexanderhiam** [nextcloud/vm#441]
## Steps to reproduce
1. Run `nextcloud_install_production.sh` on a machine with RAM < 2GB but RAM+swap >= 2GB

## Expected behaviour
Seems to me like `mem_check` should look at RAM +  swap. Something like:

```
mem_available="$(awk '/MemTotal/{mem=$2} ; /SwapTotal/{swap=$2}; END {print mem+swap}' /proc/meminfo)"
```

instead of the current:

```
mem_available="$(awk '/MemTotal/{print $2}' /proc/meminfo)"
```

https://github.com/nextcloud/vm/blob/master/lib.sh#L324

Any reason not to do that?

## Actual behaviour

Aborts install, throwing an error reporting not enough RAM.

## Server configuration

Fresh Ubuntu 16.04 install on 512MB RAM DigitalOcean droplet (with a 4GB swapfile).

#### Installation log (command output)
```
$ sudo bash nextcloud_install_production.sh 
curl OK
Error: 2 GB RAM required to install Nextcloud!
Current RAM is: (0 GB)
```

**Comment by alexanderhiam** [comment]
Oh and I can confirm that works FYI

```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           488M        126M         23M         19M        338M        309M
Swap:          4.0G          9M        4.0G
$ awk '/MemTotal/{print $2}' /proc/meminfo
500024
$ awk '/SwapTotal/{print $2}' /proc/meminfo
4194300
$ awk '/MemTotal/{mem=$2} ; /SwapTotal/{swap=$2}; END {print mem+swap}' /proc/meminfo
4694324
```

**Comment by enoch85** [comment]
I understand your point, but Swap isn't RAM. Please elaborate to convince me.

**Comment by enoch85** [comment]
You could comment out the check in the install script....

**Comment by enoch85** [comment]
ping @alexanderhiam

**Comment by alexanderhiam** [comment]
@enoch85 I have no strong feelings either way, just throwing it out there. With that change it means this can work on a $5/mo server, which is why I did it locally, but no idea what the long term implications of running Nextcloud mostly from swap are :woman_shrugging:

**Comment by alexanderhiam** [comment]
`nextcloud_install_production.sh` could also have a `--include-swap`/`-s` flag or something.

**Comment by enoch85** [comment]
@MorrisJobke Any idea about what the side effects there are (if any) by running NC mostly on Swap? To me it's not a good idea, but just want to confirm that's correct before I close/fix this request/issue.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Any idea about what the side effects there are (if any) by running NC mostly on Swap?

Slowless basically.



> To me it's not a good idea, but just want to confirm that's correct before I close/fix this request/issue.

Not that I'm aware of any, but adding memory here speeds thinks tremendously up. It could work with 512 MB of ram, but we have not a much experience with that.

**Comment by enoch85** [comment]
@MorrisJobke Thanks for your input!

I think I'll leave it as it is right now - 2 GB RAM. Though I'll add a message that the check could be commented out with a warning that thing's may not work as expected.
