### ISSUE TITLE
Method for git pull all scripts

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#442]
Hi bro i have NC instance one in digitalocean and one in own server, i need git pull or update all your scripts, what best method for that?

**Comment by enoch85** [comment]
`git clone https://github.com/nextcloud/vm.git nextcloudvm`

And btw, what's the status on this PR: https://github.com/nextcloud/vm/pull/361?

**Comment by johnfelipe** [comment]
That issue is good, what i need to do for continue?

**Comment by johnfelipe** [comment]
I do this:

	wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
	bash nextcloud_install_production.sh

And all is working so best, but how can update scripts and all .sh of yours?

**Comment by enoch85** [comment]
> That issue is good, what i need to do for continue?

Answer my questions.

> I do this:

Just follow the instructions in the README.
