### ISSUE TITLE
Nextant script fails to install. Solr exits

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/vm#445]
## Steps to reproduce
1. attempt to install Nextant using script in nextcloud/vm/apps/nextant.sh
2. wait
3. receive error message

## Expected behaviour
No error message

## Actual behaviour
See screenshot below

## Server configuration

**Server version:** (see your admin page)
Nextcloud 12.0.4
**VM version** (Scripted install from master **OR** Released version)
Paid Hyper-V VM (as of today, January 20, 2018)
**Updated from an older installed version or fresh install:**
Fresh Install
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
yes
## Logs / Screenshots
![image](https://user-images.githubusercontent.com/7028351/35185768-3348606a-fdd7-11e7-95f4-122237468e90.png)

#### Log file (/var/ncdata/nextcloud.log)
n/a

#### Installation log (command output)
n/a

#### Screenshoots 
see screenshot above

P.S.  I'm using your template, but there's a typo here. Should be Screenshots, not Screenshoots

**Comment by enoch85** [comment]
This is the reason: https://github.com/nextcloud/fulltextsearch/issues/247

**Comment by enoch85** [comment]
>  Should be Screenshots, not Screenshoots 

Feel free to make a PR. :)

**Comment by enoch85** [comment]
Issue solved, Please try again.

**Comment by BetaLeaf** [comment]
Confirmed working. Thanks for getting them to restore the repo. Can't wait for Full Text Search!

**Comment by enoch85** [comment]
@BetaLeaf Thanks for confirming. :+1:
