### ISSUE TITLE
How do I uninstall onlyoffice?

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/vm#447]
As the title says, how do I uninstall onlyoffice? I used the nextcloud/vm/apps/onlyoffice.sh script to install it.

**Comment by BetaLeaf** [comment]
I figured out how to delete the docker container and images, not sure if I left any residual data or how to delete it if so. I also moved the apache2 config from sites-enabled to sites-available, and office.domain.com now redirects to my nextcloud as it should. If I didn't miss anything, then we can close this issue. If there is more to cleaning this up, please post instructions below.

**Comment by enoch85** [comment]
It should be clean now.

**Comment by BetaLeaf** [comment]
Alright. I tried to install collabora but I kept getting internal errors so I just wiped and reloaded. Seems like something was left over.

**Comment by enoch85** [comment]
You can't just remove the Apache files, you have to deactivate them with `a2dissite`.

**Comment by BetaLeaf** [comment]
Well, that would probably be why it wasn't working. Memorized. Thanks.
