### ISSUE TITLE
Change from root to ncadmin wont continue installation

### ISSUE THREAD

**Issue by Ark74** [nextcloud/vm#450]
## Steps to reproduce
1. Run nstaller with root
2. create ncadmin (by script)
3. login after reboot with ncadmin won't continue the installation process.
4. if login with root installation continues (further fail with passwd: user '' does not exist)

## Expected behaviour
My guess is that if the installer creates ncadmin user then when rebooting it must be able to continue the installation logging in with ncadmin.
Complete installation.
## Actual behaviour
If logging with ncadmin installation won't continue.

If logging with root, installation continues but fails on infinite loop when trying to change root password.

`passwd: user '' does not exist`

## Server configuration

**Server version:** Didn't complete installation.

**VM version**: branch full-text-search (commit 23472e75c1b5c19f5f63b59b90e68deeae77789d)

**Updated from an older installed version or fresh install:**
Fresh install 
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes
#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```
None
#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots
https://imgur.com/a/TkYjV

**Comment by enoch85** [comment]
Hmm. I'm not sure I follow. The VM is programmed to run sudo bash with the user your created during the setup. 

Please show in a video, thanks!

**Comment by Ark74** [comment]
Here the video,

https://nc.switnet.net/s/3Cg5JnpXHa8JmL9

11:10 - reboot
11:35 - login as ncadmin
13:38 - login as root (installation continues)
15:41 - passwd user error

**Comment by enoch85** [comment]
1. You should not use the root account when logging in
2. Git clone **should** work, but it's better if you wget the script from the branch directly instead, as I wrote before.

So like this:
1. wget https://github.com/nextcloud/vm/blob/nc13-appinstall/nextcloud_install_production.sh
2. Change branch to nc13-appinstall in the curl command for the lib.sh
3. Add these parameters below the curl command:
```
GITHUB_REPO=https://raw.githubusercontent.com/nextcloud/vm/full-text-search
APP=$GITHUB_REPO/apps
```
4. Manually download the fulltextsearchscript.sh and run it: https://github.com/nextcloud/vm/blob/nc13-appinstall/apps/fulltextsearch.sh

**Comment by Ark74** [comment]
The issue here is that the installer is aware that i'm using root, it creates the ncadmin account (or whatever account other than root) and still allows you to continue 'till fail.

I found this while testing on a VPS where the provider gives default root user access.

Then if it is a requirement to use a non root user then maybe the installer should exit when it is launched by root.

Cheers!

**Comment by enoch85** [comment]
@Ark74 Just install it as per recommended in the README. I just tried on DigitalOcean (which also is root-only) and it worked. Once installed you can use the script (as described in the README) to upgrade to 13.0.0RC3. Then just run the fulltextsearch.sh to install Full Text Search.

I'm not sure why it fails for you.

**Comment by enoch85** [comment]
If you send me your SSH key I can give you a DEV server on DigitalOcean for a few days.

**Comment by enoch85** [comment]
@Ark74 Sorry, I now understand what you mean. 

In the nc13-appinstall branch I made checks for that. That's why you are prompted to create a new user. You should answer [yes] there. You can't run the setup script as root as root not is a user per-say on Ubuntu.

So, I already tried to fix this before. Now it turns out that it's not perfect. So my question is; what should we do? Any suggestions? Please have a look at the [code](https://github.com/nextcloud/vm/blob/nc13-appinstall/nextcloud-startup-script.sh#L96) and tell me what you think.

**Comment by Ark74** [comment]
> When I did my first video I answered [yes] to create a new user, and that's why it worked before. I know the logic so for me it's obvious. Thanks for testing.

I did too answered yes, but it failed 3 times.
If I ssh(ed) with the created user (ncadmin) on reboot, the installer won't continue. So the setup is halfway done.
If you ssh with root again, then it continues with the error described on the first post (the one you hit on the video).

So starting the scrip with root will fail or be incomplete.
My suggestion was: 

> not to use root then maybe the installer should exit when it is launched by root

Only accept being launched with sudoers users except by root, since using root is not secure I believe there are enough reasons to deflect it's use.

The alternative could be let the script run 'till creating the ncadmin, then ask the user to login as ncadmin (or what ever created user) and run it there, exiting the installer at that point.

What do you think?

**Comment by enoch85** [comment]
The whole logic is here: https://github.com/nextcloud/vm/blob/nc13-appinstall/nextcloud-startup-script.sh#L96-L124

I tested it before I merged, but I might have missed something. Please have a look if you have time.

**Comment by enoch85** [comment]
This should be fixed in the latest version. Please test.

**Comment by enoch85** [comment]
@Ark74 When you have time. Please test. Everything is merged to master now, and the new VMs are released.

**Comment by enoch85** [comment]
I just tested myself on a DO VM, and it worked!

**Comment by Ark74** [comment]
El mié, 07-02-2018 a las 19:26 +0000, Daniel Hansson escribió:
> I just tested myself on a DO VM, and it worked!—

Great news!
I'll test myself as soon as I find myself a window.

Cheers!

**Comment by enoch85** [comment]
Sorry, my bad. Need to fix this.

**Comment by enoch85** [comment]
Found a possible soulution: `UNIXUSER="$(getent group sudo | cut -d: -f4 | cut -d, -f1)"`

**Comment by enoch85** [comment]
Yup, that fixed it for the password at least. Merged to master, please test all scenarios.

**Comment by enoch85** [comment]
So now when this is fixed, could you please have a look at the Full Next Search script? @Ark74
