### ISSUE TITLE
activate-ssl.sh breaks nextcloud setup

### ISSUE THREAD

**Issue by feutl** [nextcloud/vm#451]
Hi downloaded the OVA (Nextcloud_Community_VM_PRODUCTION.ova) today installed everything successfully. Got access to my nextcloud instance via self signed SSL cert.
Nextcloud got updated to 12.05 perfectly, MariaDB was hold back.

After everything was fine, I setup a domain to get access to the instance and wanted to setup a lets encrypt cert using /var/scripts/activate-ssl.sh
which broke mariadb, because it started to upgrade it to the latest version which seems not to work with the nextcloud or the VM OS.

Any help ?

**Comment by feutl** [comment]
I also tried to run through the lets encrypt cert install at the beginning when the whole initialization starts and this breaks it as well:

- dpkg -l | grep mariadb
- 10.2.12+maria~xenial
- service mariadb start
- Job for mariadb.service failed because the control process exited with error code. See "systemctl status mariadb.service" and "journalctl -xe" for details.
`● mariadb.service - MariaDB 10.2.12 database server
   Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: failed (Result: exit-code) since Mon 2018-01-29 19:46:22 CET; 1min 23s ago
     Docs: man:mysqld(8)
           https://mariadb.com/kb/en/library/systemd/
  Process: 2070 ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION (code=exited, status=1/FAILURE)
  Process: 1860 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-envir
  Process: 1851 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
  Process: 1846 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
 Main PID: 2070 (code=exited, status=1/FAILURE)
   Status: "MariaDB server is down"

Jan 29 19:46:20 nextcloud mysqld[2070]: 2018-01-29 19:46:20 140301917374656 [Note] InnoDB: Transaction 11270 in prepared state after recovery
Jan 29 19:46:20 nextcloud mysqld[2070]: 2018-01-29 19:46:20 140301917374656 [Note] InnoDB: Transaction contains changes to 4 rows
Jan 29 19:46:20 nextcloud mysqld[2070]: 2018-01-29 19:46:20 140301917374656 [Note] InnoDB: 1 transactions in prepared state after recovery
Jan 29 19:46:20 nextcloud mysqld[2070]: 2018-01-29 19:46:20 140301917374656 [Note] Found 1 prepared transaction(s) in InnoDB
Jan 29 19:46:20 nextcloud mysqld[2070]: 2018-01-29 19:46:20 140301917374656 [ERROR] Found 1 prepared transactions! It means that mysqld was not shut down pr
Jan 29 19:46:20 nextcloud mysqld[2070]: 2018-01-29 19:46:20 140301917374656 [ERROR] Aborting
Jan 29 19:46:22 nextcloud systemd[1]: mariadb.service: Main process exited, code=exited, status=1/FAILURE
Jan 29 19:46:22 nextcloud systemd[1]: Failed to start MariaDB 10.2.12 database server.
Jan 29 19:46:22 nextcloud systemd[1]: mariadb.service: Unit entered failed state.
Jan 29 19:46:22 nextcloud systemd[1]: mariadb.service: Failed with result 'exit-code'.
`

**Comment by enoch85** [comment]
Fix is in: https://github.com/nextcloud/vm/commit/c8fd6ab5e4912702c5f9df7b29ff3ea348b27d14
