### ISSUE TITLE
Collabora installation (by script)

### ISSUE THREAD

**Issue by jkcpa** [nextcloud/vm#453]
Runs fine until this error message:
sudo: /var/www/nextcloud/occ: command not found
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message.
Thank you!
sudo -u www-data /var/www/nextcloud/occ config:app:set richdocuments wopi_url --value=https://office.ebcsalem.com failed

**Comment by enoch85** [comment]
Thanks! I'll have a look later.

**Comment by enoch85** [comment]
The issue should be fixed now. But please be aware, you have to use NC 13 for it to work.
