### ISSUE TITLE
2 network interfaces

### ISSUE THREAD

**Issue by hawairan** [nextcloud/vm#454]
Hello! We using Hyper-V image and we have 2 interfaces with eth0 - LAN ip address and eth1 - WAN IP with static address

Tryed different configurations, eidted /etc/network/intefaces before install, but each time we get
OK, we assume you run this locally and we will now configure your IP to be static.
Your internal IP is: External IP
And if i edit interfaces after installing we always getting same lines:
WAN IP: EXTERNAL IP
LAN IP: EXTERNAL IP

How we must prefonfigure VM to make it work as it must?

Thanks!

**Comment by enoch85** [comment]
@hawairan First of all, how much experience do you have with NAT? Second, this question is for the forums, but I'll give you a short answer.

You only need one NIC on your VM which is LAN. You the use a firewall/router to forward your ports with NAT to your WAN address. I made a simple guide a while back which you can find here: https://www.techandme.se/open-port-80-443/

Never put your VM directly on WAN as it will be totally open to the evil world of hackers and so on.
