### ISSUE TITLE
update script from NC 12.0.5 to 13.0.0

### ISSUE THREAD

**Issue by ilijoski** [nextcloud/vm#459]
When I tried to update nextcloud via update script /var/scripts/nextcloud_update.sh
I receive this error:

Checking latest released version on the Nextcloud download server and if it's possible to download...
[/] SUCCESS!
Latest release is: 13.0.0. Current version is: 12.0.5.
New version available! Upgrade continues...
Something went wrong with copying your mysql password to /root/.my.cnf.
Please report this issue to https://github.com/nextcloud/vm/issues, thanks!

## Server configuration
Nextcloud 12.0.5

Hosted by Hyper-V:
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
Fully updated

/var/mysql_password.txt is missing, but I never deleted that file or changed anything. (i read old issues connected with same output)

First NC version was 12.0.X

## Network
fix IP, behind NAT
local DNS server for resolving
port 80, 443 and 10000 are open

**Comment by enoch85** [comment]
@ilijoski Thanks for reporting!

Can you give me the output of the following commands:

`sudo cat /root/.my.cnf`
sudo cat /var/mysql_password.txt`

Don't include the passwords, if any.

**Comment by enoch85** [comment]
Aah, now I found the issue. You should run sudo bash /var/scripts/update.sh

Please let me know if that works.

**Comment by ilijoski** [comment]
**sudo bash /var/scripts/update.sh**

is doing update job very good, successful :) Thanks! 
So, the best advice is in future updates to use **update.sh** instead **nextcloud_update.sh** script?

**Comment by enoch85** [comment]
> So, the best advice is in future updates to use update.sh instead nextcloud_update.sh script?

Yes. :)
