### ISSUE TITLE
Install script fails at downloading previewgenerator

### ISSUE THREAD

**Issue by WDKevin** [nextcloud/vm#465]
## Steps to reproduce
1. Run nextcloud_install_production.sh on a brand new install of Ubuntu Server 16.04
2.
3.

## Expected behaviour
It should finish the script and install Nextcloud

## Actual behaviour
During the install it errors out with the following message:
System config value mail_smtpmode set to string smtp
System config value log_rotate_size set to string 10485760
Installing previewgenerator...
Error: Could not download app previewgenerator
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ app:install previewgenerator failed

## Server configuration

**Server version:** Ubuntu Server 16.04

**VM version** Scripted install from master

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?** Yes

**Is port 80 and/or 443 open?** Yes

## Logs / Screenshots
System config value mail_smtpmode set to string smtp
System config value log_rotate_size set to string 10485760
Installing previewgenerator...
Error: Could not download app previewgenerator
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ app:install previewgenerator failed

#### Log file (/var/ncdata/nextcloud.log)
```
It's empty
```

#### Installation log (command output)
```
System config value mail_smtpmode set to string smtp
System config value log_rotate_size set to string 10485760
Installing previewgenerator...
Error: Could not download app previewgenerator
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ app:install previewgenerator failed
```

**Comment by enoch85** [comment]
Thanks for posting this, probably it's just temporary as the code is correct. Running master it should fetch Nextcloud 13, and in that version occ app:install was introduced.

I'll close this, please reopen if the problem persist.

**Comment by WDKevin** [comment]
Do I just run the script from the beginning again or what? I'm not sure how to proceed from this point.

**Comment by enoch85** [comment]
Start over completely, make a new VM and run the script again. The script is not designed to be run twice.

**Comment by WDKevin** [comment]
I know this issue is closed but I just wanted to say thank you for your help. I recreated the VM and tried it again and everything worked. I'm up and running and on to find the answer to my next question. Thanks again!

**Comment by enoch85** [comment]
No problem, glad it works!

What are you wondering about?
