### ISSUE TITLE
Scipt say SSL OK, and then Nextcloud is not istalled or SSL not funcioning

### ISSUE THREAD

**Issue by rollanders** [nextcloud/vm#468]
## Steps to reproduce
1. I have a clean Ubuntu 16.0.4 LTS on a remote VPS server 
2. I have registered domains with DNS active - mydomain.se, cloud.mydomain.se and office.mydomain.se
3. When I run the scripts I get a message that SSL is activated, as well as other messages indicating everything is OK. 
4.  Further on I get a message "It seems like Nextcloud is not installed or that you don’t use https on:
mydomain.se." The installation goes on and it seems that Nextcloud is installed. 
5. When I open the webbpage on my domian I get a report about  Internal Server Error. 

Unfortunately I have tried so many times and different ways in running the scripts that I have reached the LetsEncrypt limit for this week. And I hade reinstalled the OS at the server so have no lag files right now. 

## Expected behaviour
I assume that the installation should proceed. I do not unc´derstand why I first get a message that SSL is OK, and then another telling that either Nextcloud is not instalklked (I think it is) or that SSL is not functioning (I thought the script should do that). 

**VM version** (Scripted install from master **OR** Released version)
Latest from github
**Updated from an older installed version or fresh install:**
Fresh install

## Network
**Do you use DHCP?**
I assume it is on a VPS at Contabo.com

**Is port 80 and/or 443 open?**
I assume they are and I have seen some logs that they were.

**Comment by enoch85** [comment]
Thanks for your report.

Do you run a DynDNS service?

**Comment by rollanders** [comment]
I can repeat the installtion next week whith new Letsencrypt keys and provide log-files. I was not aware about saving the keys, and as I used the script every time it would not make any difference. 

 

    Den onsdag, 14 februari 2018 20:23 skrev Daniel Hansson <notifications@github.com>:
 

 Thanks for your report.Do you run a DynDNS service?—

**Comment by rollanders** [comment]
The VPS server is set up at contabo.com. DNS set up by nordreg.se. The DNS is OK when checked at whatsmydns.net.  

    Den onsdag, 14 februari 2018 20:23 skrev Daniel Hansson <notifications@github.com>:
 

 Thanks for your report.Do you run a DynDNS service?—

**Comment by enoch85** [comment]
@rollanders IDEON?

**Comment by rollanders** [comment]
The problem was at Contabo.com. Their VPS did not suit for nested virtualisation.

**Comment by enoch85** [comment]
Nice of you to confirm. Thanks!
