### ISSUE TITLE
Collabora install

### ISSUE THREAD

**Issue by ezraholm50** [nextcloud/vm#469]
Collabora seems to fail here in the script, tried to run it in a few different VM's. Always it times out on the wget or curl and returns a fail. Removing this part of the script results in a good install. Please verify if this is on multi installs.

Please close if yours runs fine, then It'll be something on my connection.

```
# Check if $SUBDOMAIN exists and is reachable
echo
echo "Checking if $SUBDOMAIN exists and is reachable..."
if wget -q -T 10 -t 2 --spider "$SUBDOMAIN"; then
   sleep 0.1
elif wget -q -T 10 -t 2 --spider --no-check-certificate "https://$SUBDOMAIN"; then
   sleep 0.1
elif curl -s -k -m 10 "$SUBDOMAIN"; then
   sleep 0.1
elif curl -s -k -m 10 "https://$SUBDOMAIN" -o /dev/null; then
   sleep 0.1
else
msg_box "Nope, it's not there. You have to create $SUBDOMAIN and point
it to this server before you can run this script."
   exit 1
fi
```

**Comment by enoch85** [comment]
@ezraholm50 I haven't changed anything since I tested the last time (NC 13 release) and everything was working fine then.

**Comment by ezraholm50** [comment]
Other maintainers could have changed packages that break this install... Wasn't that anyway, was a cloudflare issue. Resolved. Can't reproduce. Install worked.

**Comment by enoch85** [comment]
> Other maintainers could have changed packages that break this install.

I'm the only one with full access to this repo (except the owners), so not so likely, but yes, it could have been.
