### ISSUE TITLE
Talk installation doesn't work

### ISSUE THREAD

**Issue by Serghei002** [nextcloud/vm#471]
## Steps to reproduce
1.Install new nextcloud vm 13.0.0
2.During installation select to install "Talk"
3.After installation, connect to nextcloud and enable Talk
4.you will get this error 
(An exception occurred while executing 'ALTER TABLE oc_talk_participants ADD inCall TINYINT(1) DEFAULT '0' NOT NULL': SQLSTATE[42S02]: Base table or view not found: 1932 Table 'nextcloud_db.oc_talk_participants' doesn't exist in engine)

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Server version:** (see your admin page)

**VM version** (Scripted install from master **OR** Released version)

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
This is a bug in Nextcloud server, not the VM. Please search for issues before posting new ones, thanks!

Take a look here: https://github.com/nextcloud/spreed/issues/578

**Comment by bjarkan** [comment]
An exception occurred while executing 'ALTER TABLE oc_talk_participants ADD inCall TINYINT(1) DEFAULT '0' NOT NULL': SQLSTATE[42S02]: Base table or view not found: 1932 Table 'nextcloud_db.oc_talk_participants' doesn't exist in engine

it's still an issue
