### ISSUE TITLE
Collabora with the script - "Checking if sub domain exist and is reachable" don't want to find

### ISSUE THREAD

**Issue by DorianBoby** [nextcloud/vm#480]
## Steps to reproduce
1. Run the script /var/scripts/collabora.sh (I have downloaded after have completed the first script at the first login). 
2. Follow the script (first is to note the sub domain of Collabora, after is to note the subdomain nextcloud). 
3.The script check if the domain exist and reachable
4. The script result to Fail "Nope, it's not there" (see screenshot) 

## Expected behaviour
The Collabora is installed. 

## Actual behaviour
The script fail when the sub domain is checked (see screenshot)

## Server configuration
**Server version:**
Ubuntu 16.04 OVA

**VM version**
Ubuntu 16.04 OVA

**Updated from an older installed version or fresh install:**
Fresh Install

## Network
**Do you use DHCP?**
NO

**Is port 80 and/or 443 open?**
Yes, for exemple the beginning script to install nextcloud and create SSL with letsencrypt have seen my domain for nextcloud. 

#### Screenshoots
test if exist and reachable : https://i.imgur.com/TPEspV6.jpg
the result with a test : https://i.imgur.com/8UeGtPz.jpg

#### tracks for diagnosis
When I type the sub-domain of the collabora in the web browser (in HTTPS), apache to redirect in the nextcloud domain.

**Comment by enoch85** [comment]
Thanks for your report. 

Are you sure you:
1. Didn't misspell the domain?
2. Have a proper internet connection?

**Comment by enoch85** [comment]
Also, what does `curl collabora.domain.fr` give you?

**Comment by enoch85** [comment]
[This](https://github.com/nextcloud/vm/blob/master/apps/collabora.sh#L53-L68) is the code that is run when testing. As you can see it tests both with `wget` and with `curl`.

**Comment by enoch85** [comment]
> I had to add the Collabora app manually in the nextcloud

You shouldn't have to do that. The script installs it for you and does all the needed settings. 

Last time I tried to install it on Digitalocean (before the NC13 release) it worked, and nothing have been changed since. 

I think it might be your DNS records that are off, or some rule in the firewall that are wrong.

**Comment by DorianBoby** [comment]
OK, thanks for your help.
I will try a few different configurations until I have a functional solution.

**Comment by enoch85** [comment]
I'll close this for now, please confirm when you succeed, or still failing.

**Comment by DorianBoby** [comment]
It's a fail for me.
I succeeded in doing everything by hand. 

# Thanks for all you doing with the automated things.

**Comment by enoch85** [comment]
@DorianBoby What do you suggest should be improved? Should we use anothe function to check existing domain according to you?

**Comment by DorianBoby** [comment]
Yes the test is done locally, but should be done by an internet machine I think.

Exemple : In the case where the VM has a local IP and the router does not do NAT reflection, the current check will not work. 
This was also my case but I activated the NAT reflection.

**Comment by enoch85** [comment]
> This was also my case but I activated the NAT reflection.

So it didn't even work **with** NAT-reflection?

**Comment by DorianBoby** [comment]
It works with NAT-reflection. 
But I did not continue the development of the "AUTOMATED" VM. 
I started from scratch to understand each piece. 
:)

**Comment by enoch85** [comment]
Yeah well, ofc you need NAT in your router/firewall for stuff to work. 

So all and all, not an error in the scripts. Thanks for confirming! I hope you learned something along the way :)
