### ISSUE TITLE
Unable to load redis.so

### ISSUE THREAD

**Issue by jaredthirsk** [nextcloud/vm#481]
## Steps to reproduce
1. Get the latest install script from master:
wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
2. Run the script with:
sudo bash nextcloud_install_production.sh

## Expected behaviour
I should be able to access nextcould via the web server.

## Actual behaviour

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request.
> Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
> More details can be found in the server log.

error.log:
```
[Mon Feb 26 14:51:06.108706 2018] [http2:warn] [pid 2087] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0

```

## Server configuration

**Server version:** (see your admin page)
Ubuntu 16.04.4 LTS

**VM version** (Scripted install from master **OR** Released version)
Ran instructions from github readme as of today.

**Updated from an older installed version or fresh install:**
Fresh install

## Network
Machine is an Azure VM.

**Do you use DHCP?**

**Is port 80 and/or 443 open?**
Yes

**Comment by jaredthirsk** [comment]
Workaround:
sudo apt install php-apcu redis-server php-redis
service apache2 restart

Notes on anomalies: I lost ssh connection one time while setting up SSL.  My VM has about 1.9GB RAM and half way thru the install I added 3GB swap.

**Comment by enoch85** [comment]
@jaredthirsk The scripts work just fine. If your SSH connection was aborted please re-install everything. I do not recommend to add extra packages, it's already perfect and checked multiple times.

**Comment by enoch85** [comment]
AKA, the scripts are designed to be runt one time, once. Not aborted or adding swap in the middle or anything like that.

Thanks for your report though.
