### ISSUE TITLE
OpenSSL Port 443 AND Port 80 mandatory?

### ISSUE THREAD

**Issue by 3Dscrewer** [nextcloud/vm#482]
Since Dec 17 I have done a lot of Installations.
may be I am the only one, but open only Port 443 didn't work for me. The script always told me 443 is open and online, but SSL was failing with "well known error". I was reading and researching a lot and found in a thread the hint that Port 80 has also to be open (and also forwarded in DNS Service).
So I have opened Port 80 and never had a problem again.

My suggestion, because I have seen I am not alone with that problem, add to the message (before installing OpenSSL) that port 80 and 443 probably has to be open.

Maybe only a problem at DS-Light (Kabel iPv6) Protokoll?

**Comment by enoch85** [comment]
You're absolutley right. Thanks for pointing that out.

Fix is here: https://github.com/nextcloud/vm/pull/486
