### ISSUE TITLE
rename existent config files instead overwrite ....

### ISSUE THREAD

**Issue by 3Dscrewer** [nextcloud/vm#483]
Since I have had a lots of problems using the hyper-v Image, I was trying a new way. I have istalled a small virtual Ubuntu Server installation and used the script.
So during setup the VM was already online and the script is re configuring the already working network.
**After reboot the machine is offline.**

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

or

iface eth0 inet static
address XXX.XXX.XXX.XXX
netmask 255.255.255.0
gateway XXX.XXX.XXX.XXX
dns-nameservers 8.8.8.8

was bringing my machin back online

the ethtool was not good. So it is (for me) a good idea to rename existent config files before overwriting.

**Comment by enoch85** [comment]
Fixed.
