### ISSUE TITLE
Cannot get Letsencryptcert to install

### ISSUE THREAD

**Issue by mikeew83** [nextcloud/vm#495]
## Steps to reproduce
1. Run through the script
2. Get to point of which Letsencrypt cert is installing
3. fails everytime indicating 
Type: unauthorized
Detail: Invalid response from
http://mydomain.com/.well-known/acme-challenge/bunch of characters

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead
cert should install
## Server configuration
purchased the 16 dollar hyper-v build from tech and me site.
**Server version:** (see your admin page)

**VM version** (Scripted install from master **OR** Released version)

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
That sounds like a DNS issue to me. There are no issues in the scripts afaik.

**Comment by mikeew83** [comment]
My provider is GoDaddy I contacted them and they were incredibly rude. They
had me make some changes to the dns and I'm not sure what else to do. I'm
fairly confident my dns is set up correctly as everything points to my
external IP and I can access other services like rdp remotely using my
domain name.

**Comment by enoch85** [comment]
There are one other alternative you can try if you can't use TLS-SNI.

Try this: [certbot -d bristol3.pki.enigmabridge.com --manual --preferred-challenges dns certonly](https://serverfault.com/a/812038)

**Comment by mikeew83** [comment]
Does the server come installed with certbot?

**Comment by enoch85** [comment]
certbot is installed when running the LE script, not before, and not after.

**Comment by mikeew83** [comment]
So I figured out my issue but still can't get https working. I ran the cert
install with the linked site and it succeeded but the site still will not
resolve when navigating via https://domain.com

**Comment by mikeew83** [comment]
I should mention I get a refused to connect error when hitting the https
landing page.

**Comment by enoch85** [comment]
Did you run the script? If not you may need to activate a valid Apache config for everything to work.

Since this is not a script issue, I'll close this one.
