### ISSUE TITLE
External access issue (security)

### ISSUE THREAD

**Issue by ilijoski** [nextcloud/vm#497]
I have installed newest version of NC 13 on Ubuntu server yesterday, and I have enabled all secure features during running of your script. 

Now i have situation when Nextcloud is up and accessible from LAN (internal IPs), but not from WAN. 

I have successfully created NAT from WAN ip to LAN ip, but nextcloud is not opening. 

From WAN i can access to webmin interface 10000, ssh 22, but not to nextcloud login page. The port 80 is opened, and also on config.php i put local and wan IPs, also fqdn. I have feeling that "something" secure feature is blocking traffic from WAN IPs. Please give me directions where to check first? 

Thanks!

*UPDATE* If on firewall rule I add feature "source NAT", where external requests are shown like local private IP, then Nextcloud is accessible, but, in this scenario all external attempts are from same local IP.

Thanks!

**Comment by enoch85** [comment]
I just installed two VMs myself with the scripts today, both had external access and secured by SSL. Both installations went fine, so there are no issues with the script. 

I'd recommend you to check this guide on how to open ports: https://www.techandme.se/open-port-80-443/ 

And just as a bonus: All ports are open on LAN that are in use, and only then. So for example if you install webmin, you will be able to access it on https://[LAN IP]:10000. If you don't install it, that port will be closed because the are no use for it.

So with that said, if you managed to access it from WAN without forwarding it in your router first, then you must have done something totally wrong. It should be impossible.

Check your settings and try again. Please use the forums for support. Thanks!

**Comment by ilijoski** [comment]
There is misunderstanding, maybe because of my bad English, or bad explanation :) Sorry.

I know how to forward ports. And as I said, i have forwarded 80, 443 and 10000 from wan to lan IP. From wan accessing nextcloud gives error "ERR_CONNECTION_TIMED_OUT". But from internal network accessing nexcloud is working good. 

From internet only webmin is accessible (port 10000).

From internet is accessible and Nextcloud ONLY if I add feature on (Kerio) firewall "source NAT", to rule for port forwards. That means anybody from internet when access to WAN, will be translated to Ubuntu server with Firewall LAN (private) IP. In this scenario nextcloud is accessable. 

Generally Nextcloud is not working with any public IP reqeusts, only from private IP. And that is not forbidden in apache or config.php either. 

I will troubleshoot this issue by myself and share with other users if they have future issues like this.

Cheers.

**Comment by ilijoski** [comment]
In current location where I am installing Nextcloud via VPN to cloud hosting system, I have configured Nexcloud desktop client with same configuration for nc server IP same like new instance what I am installing... 

After success installation of NC, my desktop client tries to connect via username/password which exist on old NC server, but not on this fresh new NC. That triggered fail2ban feature which blocks my public IP of my current location. 

Now I have cleared iptables and fail2ban jail rules, and Nextcloud is accessible from anywhere :) 

If someone have similiar scenario, please check on iptables is there anything blocked. 

Cheers

**Comment by enoch85** [comment]
Hmm, yeah. If you installed fail2ban that's where I'd start looking as well. :)

Glad you solved it. :+1:

**Comment by RIS2000** [comment]
Hello!
I have the same issue.
When my external IP changed, Nextcloud fail to answer on 443 port. Nothing helps (

**Comment by enoch85** [comment]
> When my external IP changed, Nextcloud fail to answer on 443 port. Nothing helps (

You need to change the DNS records for your domain.

**Comment by RIS2000** [comment]
Done it already. I use DDNS. To no avail. Nextcloud just fails to answer on 443 port from external IPs.

**Comment by RIS2000** [comment]
> 
> 
> > When my external IP changed, Nextcloud fail to answer on 443 port. Nothing helps (
> 
> You need to change the DNS records for your domain.

Done it already. I use DDNS. To no avail. Nextcloud just fails to answer on 443 port from external IPs.

**Comment by RIS2000** [comment]
/var/log/apache2/error.log                                                                                                                                                                                                                      31843/31843             100%
[Fri Mar 13 13:59:49.600617 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.600640 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.612978 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.690625 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.697034 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.697069 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.702714 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.702738 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.709361 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.709426 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.713828 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.713971 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.717168 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.717188 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.719809 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.719841 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.722450 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.722508 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.734671 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.744258 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.747025 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.747057 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.749516 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.749538 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.751969 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.751992 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.756320 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.756343 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.765909 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.765931 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.769304 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.769331 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:49.776455 2020] [proxy:error] [pid 1694:tid 139697441855232] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 13:59:49.776477 2020] [proxy_fcgi:error] [pid 1694:tid 139697441855232] [client 192.168.1.1:59474] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 13:59:51.002466 2020] [mpm_event:notice] [pid 1690:tid 139697839078336] AH00491: caught SIGTERM, shutting down
[Fri Mar 13 14:00:09.185131 2020] [mpm_event:notice] [pid 1707:tid 140176942574528] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Fri Mar 13 14:00:09.229892 2020] [core:notice] [pid 1707:tid 140176942574528] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 13 14:52:51.056571 2020] [proxy_fcgi:error] [pid 1709:tid 140176797148928] [client 192.168.1.1:59784] AH01067: Failed to read FastCGI header
[Fri Mar 13 14:52:51.229434 2020] [proxy_fcgi:error] [pid 1709:tid 140176797148928] (104)Connection reset by peer: [client 192.168.1.1:59784] AH01075: Error dispatching request to :
[Fri Mar 13 14:52:51.144555 2020] [proxy:error] [pid 1709:tid 140176788756224] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 14:52:51.238448 2020] [proxy_fcgi:error] [pid 1709:tid 140176788756224] [client 192.168.1.1:59784] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 14:52:51.380334 2020] [proxy:error] [pid 1709:tid 140176788756224] (2)No such file or directory: AH02454: FCGI: attempt to connect to Unix domain socket /run/php/php7.2-fpm.nextcloud.sock (*) failed
[Fri Mar 13 14:52:51.427542 2020] [proxy_fcgi:error] [pid 1709:tid 140176788756224] [client 192.168.1.1:59784] AH01079: failed to make connection to backend: httpd-UDS
[Fri Mar 13 14:52:51.775035 2020] [mpm_event:notice] [pid 1707:tid 140176942574528] AH00491: caught SIGTERM, shutting down
[Fri Mar 13 14:53:09.587923 2020] [mpm_event:notice] [pid 1647:tid 140621355326400] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Fri Mar 13 14:53:09.617378 2020] [core:notice] [pid 1647:tid 140621355326400] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 13 14:55:24.910882 2020] [mpm_event:notice] [pid 1647:tid 140621355326400] AH00491: caught SIGTERM, shutting down
[Fri Mar 13 14:55:42.615051 2020] [mpm_event:notice] [pid 1632:tid 139881454173120] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Fri Mar 13 14:55:42.717545 2020] [core:notice] [pid 1632:tid 139881454173120] AH00094: Command line: '/usr/sbin/apache2'
[Fri Mar 13 14:59:29.621333 2020] [mpm_event:notice] [pid 1632:tid 139881454173120] AH00491: caught SIGTERM, shutting down
[Fri Mar 13 14:59:47.104796 2020] [mpm_event:notice] [pid 1674:tid 140709505502144] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Fri Mar 13 14:59:47.158236 2020] [core:notice] [pid 1674:tid 140709505502144] AH00094: Command line: '/usr/sbin/apache2'

**Comment by RIS2000** [comment]
I tried to disable iptables and fail2ban. Still no luck (
