### ISSUE TITLE
Problem updating Nextcloud when using Lets encrypt

### ISSUE THREAD

**Issue by festge** [nextcloud/vm#498]
## Steps to reproduce
1. SSL-Certificate installed
2. Try to update Nextcloud

## Expected behaviour
Update runs without issues. Login is fast again

## Actual behaviour
The Update prompting an error. Trying to Update because of the very slow login
"
Check for expected files
The following extra files have been found:

    .well-known
"

## Server configuration

**Server version:13.0.0 (see your admin page)

**VM version** (Scripted install from master **OR** Released version)

**Updated from an older installed version or fresh install:**

## Network
**Do you use DHCP?** 
No

**Is port 80 and/or 443 open?**
Yes
#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
You should run: `sudo bash /var/scripts/update.sh` Not use the web-updater.
