### ISSUE TITLE
Build from scripts / VM build

### ISSUE THREAD

**Issue by ezraholm50** [nextcloud/vm#5]
This should have another option IMO when building from scripts on a clean vm since that build would probably not have ens33 set at the start right? More likely it would have eth0 I guess.
```
# Set correct interface
sed -i "s|ens33|$IFACE|g" /etc/network/interfaces
service networking restart
```

Something like if /etc/network/interfaces has ens33 then change it to IFACE else, leave it.

**Comment by enoch85** [comment]
Feel free to make a PR ;)

**Comment by ezraholm50** [comment]
fixed
