### ISSUE TITLE
File Access Control advices

### ISSUE THREAD

**Issue by ilijoski** [nextcloud/vm#500]
Can someone share experience with File Access Control ? 

My scenario is to have group of users who can upload/download images only, up to 2mb by each file, and I have created this rule:

![nextcloud_file-access-control](https://user-images.githubusercontent.com/26570266/37645571-8f1aa546-2c27-11e8-9d08-7e9885eae23c.png)

With this rule i got this results:
1. User from selected group CAN:
- upload / download JPG files bigger than 2MB via web interface
- upload / download ANY file smaller than 2MB via web interface

2. User from selected group CANT:
- upload / download JPG files bigger than 2 MB via android app
- upload / download ANY file smaller than 2 MB via android app

I need advice how to restrict one group of users to work only with images, and not bigger than 2MB, via any interface they use (web and android app)

Thanks!

BTW Server is Ubuntu server fully patched, latest version of Nextcloud, installed before 3 days.

**Comment by enoch85** [comment]
@ilijoski This is not a VM issue per say, more a support question, and for that we have the [forums](https://help.nextcloud.com).

@MorrisJobke Can you answer this maybe, I have no idea about this.

**Comment by MorrisJobke** [comment]
More a setup issue. Best to be asked and discussed in the forums. Sorry
