### ISSUE TITLE
Nextcloud eats disk space

### ISSUE THREAD

**Issue by delavandaag** [nextcloud/vm#502]
## Steps to reproduce
1. Install Nextcloud VM on ESXI (from www.techandme.se, standard 20G version)
2. Install Letsencrypt certificate
3. Deploy external storage and use only external storage (no storage on local disk (sda)). External storage consists of three separate virtual HDDs (100G, 50G and 25G) for three users. One user has 60G on external storage, another 5G and the third no more than 25MB.

## Expected behaviour
Relatively low percentage of use of local disk space
## Actual behaviour
Over time the free local disk space gets lesser and lesser and ultimately, after 3 to 6 months, Nextcloud cannot be used anymore as all local disk space is being reported as being used and a reinstall is required.

## Server configuration

**Server version:** 13.0.1

**VM version:** Ubuntu 16.04.01 that comes with the pre-configured techandme OVA

**Updated from an older installed version or fresh install:** The 'disk eating' happens with a fresh install as well as with an updated version. My first Nextcloud install was version 11. I used that one for some months and by the time it was updated to version 12 I did a fresh reinstall (as all local disk space was eaten). I made a copy of that fresh reinstall and this morning, I was on version 13.0 in the meantime, all local disk space was eaten up again. So I reinstalled the fresh install of version 12 and updated to version 13.0.1. Immediately after that reinstall 8.35G of local disk space was in use. After 12 hours 8.70G is being used whereas I have hardly touched Nextloud (added less than 10MB of files on _external_ storage). And the other two users have not touched Nextcloud.

## Network
**Do you use DHCP?** Yes, albeit with a reserved ip adress.

**Is port 80 and/or 443 open?** Only port 443.

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```
I am hesitant to insert the log file as it shows sensitive information such as filenames. It would take me hours and hours to clean up the log file from these ... The size of the log is 1.21MB.

#### Installation log (command output)
```
Insert the CLI output here
```
Not sure where to find this log file.

#### Screenshoots

Not relevant, I guess.

**Comment by delavandaag** [comment]
I am not aware of running any docker container.

The output of the above command is:

du: cannot access '/proc/31091/task/31091/fd/4': No such file or directory
du: cannot access '/proc/31091/task/31091/fdinfo/4': No such file or directory
du: cannot access '/proc/31091/fd/3': No such file or directory
du: cannot access '/proc/31091/fdinfo/3': No such file or directory
90G     /

That doesn't look good, does it?

**Comment by enoch85** [comment]
@delavandaag Run the command with `sudo` and you will get another output.

**Comment by delavandaag** [comment]
Thnx enoch85, for your attention to this issue. The output of the command is:

12K     show

**Comment by enoch85** [comment]
@delavandaag OK, so what do you have in media? Is that your external mount?

**Comment by delavandaag** [comment]
Yes, external storages are mounted in /media

**Comment by enoch85** [comment]
You just answered your own question... :)

**Comment by enoch85** [comment]
If you are using an external storage *mounted* in you VM, ofc the "local" storage shows as consumed.

So `df -h` should show how it looks like.

**Comment by delavandaag** [comment]
OK, there may be some misunderstanding and I probably did not phrase my question correctly. With 'local disk' I refer to what is highlighted in yellow in the below screendump of webmin:

![image](https://user-images.githubusercontent.com/7560459/37879031-f500fbaa-3071-11e8-843d-941cc5b8de55.png)

It is '/dev/mapper/nextcloud--vg-root' in the below output of 'df -h':

Filesystem                      Size  Used Avail Use% Mounted on
udev                            976M     0  976M   0% /dev
tmpfs                           200M  8.4M  191M   5% /run
/dev/mapper/nextcloud--vg-root   18G  7.8G  8.5G  48% /
tmpfs                           996M     0  996M   0% /dev/shm
tmpfs                           5.0M     0  5.0M   0% /run/lock
tmpfs                           996M     0  996M   0% /sys/fs/cgroup
/dev/sda1                       472M   58M  390M  13% /boot
/dev/sdb1                       100G   64G   37G  64% /media/user1
/dev/sdc1                        50G   20G   31G  39% /media/user2
/dev/sdd1                        25G  2.3G   23G   9% /media/user3
tmpfs                           200M     0  200M   0% /run/user/1000

The sdb1 - sdd1 are the external storages. Now what I am experiencing is that the used part of 'Local disk space' in webmin is growing over time whilst no file is being added by any user other than to external storage. Today I added some 2.8G to external storage and the used 'Local disk space' grew from 8.7G to 8.72G. I had no updates today and I certainly did not add 200MB of files to 'Local disk space'; again I did not add anything to 'Local disk space'. And somewhere in the coming months, the used 'Local disk space' will grow until it reaches the upper half of 90% - 100% and Nextcloud cannot be used anymore until I do a reinstall.

I understand that the used 'Local disk space' will grow somewhat by adding files on external storage as I assume that the 'record keeping' of those files will be written to 'Local disk space'. But adding 2.8G externally should not lead to 200MB grow on the 'Local disk space'.

I hope that I made it more clear what the problem is I am facing. I am sorry that I do not have very much knowledge or experience with Linux/Ubuntu, and really appreciate your attention to this.

Cheers, Dela

**Comment by enoch85** [comment]
Have you checked your logs? Seems to me like you have a log that gets spammed with info.

**Comment by delavandaag** [comment]
Well, the output of 'du -hs * | sort -h' in /var/log is as follows:

0       alternatives.log
0       apport.log
0       btmp
0       dpkg.log
0       kern.log
0       mail.log
0       previewgenerator.log
4.0K    alternatives.log.1
4.0K    alternatives.log.2.gz
4.0K    apport.log.1
4.0K    apport.log.2.gz
4.0K    btmp.1
4.0K    cronjobs_success.log
4.0K    dist-upgrade
4.0K    dmesg
4.0K    kern.log.2.gz
4.0K    mail.log.2.gz
4.0K    mail.log.3.gz
4.0K    mail.log.4.gz
4.0K    syslog.2.gz
4.0K    syslog.4.gz
4.0K    syslog.5.gz
4.0K    syslog.6.gz
4.0K    vmware-vmsvc.1.log
4.0K    vmware-vmsvc.2.log
4.0K    vmware-vmsvc.3.log
4.0K    vmware-vmsvc.log
4.0K    wtmp
8.0K    faillog
8.0K    mail.log.1
8.0K    syslog
12K     fsck
16K     auth.log.3.gz
20K     auth.log.2.gz
24K     auth.log.4.gz
28K     syslog.1
28K     unattended-upgrades
40K     auth.log.1
40K     lastlog
44K     wtmp.1
52K     auth.log
60K     bootstrap.log
64K     apt
72K     dpkg.log.2.gz
92K     syslog.7.gz
96K     kern.log.3.gz
108K    letsencrypt
224K    dpkg.log.1
244K    syslog.3.gz
384K    redis
404K    kern.log.4.gz
2.0M    kern.log.1
2.7M    apache2
15M     installer
37M     mysql

That doesn't look alarming to me. And last night the used 'Local disk space' grew from 8.72G to 8.77G without even touching it. Are there any other log files than in /var/log worth inspecting?

**Comment by enoch85** [comment]
What about the nextcloud.log then?

**Comment by enoch85** [comment]
Hmm, now when thinking about it, it might be the previewegenerator that generates new previews. You find that in /var/ncdata/app_XXX

**Comment by delavandaag** [comment]
The nextcloud.log amounts to 1.21MB. You may have nailed it with the previews. 'du -hs * | sort -h' in /var/ncdata/appdata_ocmnpoor4wsx gives the following:

4.0K    dav-photocache
28K     identityproof
52K     theming
72K     avatar
332K    css
560K    appstore
2.2M    js
4.6G    preview

There indeed are quite some photos stored on the Nextcloud. A little bit less than 30G. 4.6G of previews is enormous. I have a couple of questions/comments in this regard:

1. I assume that previews are only generated for photos (and possibly film footage). Is that correct?
2. Is it possible to redirect the previews to external storage? If so, can you direct me to a description how to achieve that?
3. If previews are only generated for photos/film, I can hardly imagine that it could lead to the used 'Local disk space' being eaten completely (18G!) unless duplicate previews are being generated without deleting the 'old versions'. Last week I added user3 (see my above comment with the screendump of webmin) who added 2.3G of photos. I think, but I am not fully certain, that shortly after that I was running out of 'Local disk space' and had to do the reinstall. I recall that prior to adding the 2.3G of photos I had some 7G to 8G of available 'Local disk space'.
4. Is there anyway to check whether duplicate previews exist? And to clean up duplicates?
5. Is there any way to force Nextcloud to produce previews in lower resolution?

Again, many thanks for your help. I really appreciate that.

**Comment by enoch85** [comment]
You can read all about it here: https://github.com/rullzer/previewgenerator

I'm no expert in certain apps.

**Comment by delavandaag** [comment]
Enoch85, that was helpful indeed! Thanks to your references I managed to delete all existing previews, rebuild my database and regenerate previews in lesser number and size. I am still looking for a way to store the previews on an external disk. Many thanks for your time and attention to this.

Kind regards, Dela
