### ISSUE TITLE
certbot renew fails due to interference with other server behind nginx reverse proxy

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#505]
## Steps to reproduce
1. `root@nc:~# certbot renew --no-self-upgrade > /var/log/letsencrypt/renew.log 2>&1`
2. My server `nc` is behind an nginx reverse proxy configured with these instructions(https://www.techandme.se/set-up-nginx-reverse-proxy/) and there appears to be a conflict with my server `json` which I am unsure how to resolve.
3.

## Expected behaviour
The certificate should be renewed.

## Actual behaviour
The certificate is not renewed.

## Server configuration

**Server version:** 12.0.5

**VM version:** master

**Updated from an older installed version or fresh install:** Updated within major version only (v12)

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
Yes

#### Log file (/var/log/syslog)
```
Apr  1 16:09:32 nc systemd[1]: Stopping The Apache HTTP Server...
Apr  1 16:09:32 nc apachectl[22564]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using nc.mydomain.com. Set the 'ServerName' directive globally to suppress this message
Apr  1 16:09:32 nc systemd[1]: Stopped The Apache HTTP Server.
Apr  1 16:09:37 nc systemd[1]: Starting The Apache HTTP Server...
Apr  1 16:09:37 nc apachectl[22604]: AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using nc.mydomain.com. Set the 'ServerName' directive globally to suppress this message
Apr  1 16:09:37 nc systemd[1]: Started The Apache HTTP Server.
```

#### Log file (/var/log/letsencrypt/renew.log)
```
-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/nc.mydomain.com.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator standalone, Installer None
Running pre-hook command: service apache2 stop
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for nc.mydomain.com
Waiting for verification...
Cleaning up challenges
Attempting to renew cert (nc.mydomain.com) from /etc/letsencrypt/renewal/nc.mydomain.com.conf produced an unexpected error: Failed authorization procedure. nc.mydomain.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for tls-sni-01 challenge. Requested 80c537b06f49c5279b406dd02d6496ce.482d5b1bb770e5cd186bd6e430af5c9c.acme.invalid from 24.193.26.188:443. Received 2 certificate(s), first certificate had names "json.mydomain.com". Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/nc.mydomain.com/fullchain.pem (failure)

-------------------------------------------------------------------------------

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/nc.mydomain.com/fullchain.pem (failure)
-------------------------------------------------------------------------------
Running post-hook command: service apache2 start
1 renew failure(s), 0 parse failure(s)
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: nc.mydomain.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for tls-sni-01 challenge.
   Requested
   nlRk9KQ2p4tY9WorBYoczUYqgDajtIuk.uzNwMwLhjBQeQMir98WPWc3l3BirL1g1.acme.invalid
   from 46.23.894.11:443. Received 2 certificate(s), first
   certificate had names "json.mydomain.com"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

```

**Comment by enoch85** [comment]
Run it without `--no-self-upgrade` and see what happens. 

I think the Let's Encrypt forums are better for this issue.

**Comment by thejohnha** [comment]
Thank you, doctor! I will post back here if I come to a resolution. Many thanks

**Comment by thejohnha** [comment]
From the Let's Encrypt forums:

```
Plugins selected: Authenticator standalone
```

ADVICE: The “standalone” plugin will conflict with a running web service.

**Comment by enoch85** [comment]
If you want to upgrade manually you have to stop apache before the renew is run. That should be done automatically with the script. Please post the output of `cat /etc/letsencrypt/renewal/yourdomain.conf`

**Comment by thejohnha** [comment]
Oh, I did forget to stop the apache server before running the updater. That was probably it! Thank you.

I destroyed the server and replaced it with a fresh v13 install from script. But I will restore the backup and see if there are any clues in /etc/letsencrypt/renewal/yourdomain.conf Thank you so much, Daniel.

**Comment by enoch85** [comment]
```
[renewalparams]
**post_hook = service apache2 start**
account = examnhh6zw4qn81q4qtojeyso33q4tyt
authenticator = standalone
rsa_key_size = 4096
**pre_hook = service apache2 stop**
installer = None
```

As you can see those parameters is already there, so there are nothing wrong in the script. Try to run the renewscript manually instead.

**Comment by thejohnha** [comment]
OK it looks like the autorenew script was never able to run successfully on my old box. I set up a new nextcloud instance and will monitor the new one, perhaps the autorenew failure was just something unique to that old box. For now, running the autorenew script looks ok `/var/log/letsencrypt/letsencrypt.log`:

```
2018-04-03 17:30:33,759:INFO:certbot.renewal:Cert not yet due for renewal
2018-04-03 17:30:33,760:DEBUG:certbot.renewal:no renewal failures
```

Thank you!
