### ISSUE TITLE
"Could not set property: Connection timed out"

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#507]
## Steps to reproduce
1. Run the script.
2. After the first reboot, after selecting which optional components to install (fail2ban, talk etc.), notice the message. This happens consistently, I've tested it three times with different domain names. I'm not sure what it means, everything seems to work fine. Just thought I would bring it to your attention.

#### Installation log (command output)
```
Setting hostname to talk.mydomain.com...
Could not set property: Connection timed out
find: ‘/sys/kernel/security/ima’: Permission denied
find: ‘/sys/kernel/security/apparmor’: Permission denied
find: ‘/sys/kernel/debug’: Permission denied
Installing Fail2ban...
Reading package lists... Done
Building dependency tree
```

**Comment by enoch85** [comment]
Seems like you are not running as root.

**Comment by thejohnha** [comment]
Hmm. Maybe I haven't been running the script properly. I first create a new user called john. Then I run the script, and it asks to reboot. After the reboot, I ssh into the box as john and the script continues. Should I ssh into the box as root instead to finish the second part of the script?

**Comment by enoch85** [comment]
You should do like this: https://github.com/nextcloud/vm#installation

**Comment by thejohnha** [comment]
Hmm... interesting... just to be clear:

After the first reboot, I ssh into the instance as john... and as soon as it connects, the `nextcloud-startup-script.sh` script runs. I have always used the script by letting it continue.

Are you saying that instead, I should CTRL+C at this point and then run `sudo bash /var/scripts/nextcloud-startup-script.sh` (as john of course) ?

**Comment by enoch85** [comment]
@thejohnha No, if the user "john" has sudo permissions you're doing it correctly. 

Is the output always the same with the timeout? Maybe it's just a temporary glitch?

**Comment by enoch85** [comment]
@thejohnha Any update here?

**Comment by thejohnha** [comment]
I tested it again, this time running `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E5267A6C && sudo apt update` before getting to the Let's Encrypt part, but I'm still getting the error:

![screen shot 2018-04-07 at 19 14 20](https://user-images.githubusercontent.com/6325833/38461550-b0b16f36-3aa1-11e8-9b78-febd34d438e0.jpg)

**Comment by enoch85** [comment]
Does it work? Is it just an esthetic issue?

Seems like the hostname is not set. Can you check with `hostname -f`?

**Comment by thejohnha** [comment]
Nextcloud is installed correctly as far as I can tell. So it may just be an aesthetic item as you say. I wanted to make you aware in case it's a deeper issue.

**Comment by enoch85** [comment]
No, I never had any issues like you described. Thank you for posting the issue though. Keep em coming. :)
