### ISSUE TITLE
nextcloud-startup-script.sh does not generate random password

### ISSUE THREAD

**Issue by wouterVE** [nextcloud/vm#516]
Hi,
I've created 2 nextcloud instances through the VM image witch the startup script. 
The welcome screen states it will generate new mariaDB pw. 
But when I look upon the /var/www/nextcloud/config/config.php and the following lines are the same in the 2 server instances:

`'mysql.utf8mb4' => true,
  'dbuser' => 'oc_ncadmin',
  'dbpassword' => 'password',
`

&
`
  'redis' =>
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
    'dbindex' => 0,
    'password' => 'password',
`

should i trust this or instead change it manually?

**Comment by enoch85** [comment]
Yes, that's because we use the same $VAR which means the passwords are the same. Feel free to commit a PR and change it.

**Comment by wouterVE** [comment]
Ok thanks, wasn't sure about that.
It's still possible to change it manually?

**Comment by enoch85** [comment]
Yes, you can put whatever password you want. You change in two files:
1. `/etc/redis/redis.conf`
2. `/var/www/nextcloud/config/config.php`

**Comment by wouterVE** [comment]
Ok thanks, thats for `redis` , what about `mysql` please?

**Comment by enoch85** [comment]
@wouterVE `/root/.my.cnf` and then you need to generate a new password with mysql command line, but don't change anything unless you are absolutely certain of what you are doing.

**Comment by wouterVE** [comment]
@enoch85 ok thanks, I'll try it on a test-server first since it seems a tricky task indeed. 
issue may be closed.

**Comment by wouterVE** [comment]
Hi,
Just for the sake of completeness; here is what i did to change mysql password:

1. Retrieve mysql master password from `/root/.my.cnf`
2. Follow [these](https://www.howtoforge.com/setting-changing-resetting-mysql-root-passwords) steps to set new password (see method 2)

- mysql -u root -p 
and enter password 
- use mysql;
- mysql> SET PASSWORD FOR 'ENTER-USER-NAME-HERE'@'localhost' = PASSWORD("newpass");
- mysql> flush privileges;
- mysql> quit


I did this for user 'root' and 'oc_ncadmin' and changed it in config.php as well.

Do I need to update it in `/root/.my.cnf` also?

**Comment by enoch85** [comment]
> Do I need to update it in /root/.my.cnf also?

Yes, for your connivance.
