### ISSUE TITLE
Upgrade from 13.0.1 to 13.0.2: Sorry but something went wrong. Please report this issue

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/vm#517]
@enoch85 Hi Daniel,

Got below messages and update fails. After a reboot I can bring 13.0.1 back working, but another update trail fail again. 

A possible reason is a modification I made since the last update. If have NC data moved to another (large) virtual drive long time ago. I haven’t had any issues updating earlier version up to 13.0.1 after that data move. A few weeks ago I also moved mysql database data to the large drive. 

It is working like a charm so far, but now this update issue. 

What I recently did basically was:
nano /etc/mysql/mysql.conf.d/mysqld.cnf
comment out:   datadir       = /var/lib/mysql
instead this; datadir         = /NCfilestore/mysql `

Can you say, if the update issue is maybe related to my database move and if yes, is there a way from script side to make it compatible to my change? 

Thanks, Stefan

--------------------------------------
Setting up mysql-server-5.7 (5.7.22-0ubuntu0.16.04.1) ...
Job for mysql.service failed because the control process exited with error code. See "systemctl status mysql.service" and "journalctl -xe" for details.
invoke-rc.d: initscript mysql, action "start" failed.

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ -V failed
root@nextcloud:~# Setting up mysql-server-5.7 (5.7.22-0ubuntu0.16.04.1) ...^C
root@nextcloud:~# systemctl status mysql.service
● mysql.service - MySQL Community Server
   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: enabled)
   Active: activating (start-post) (Result: exit-code) since Fri 2018-04-27 18:54:16 CEST; 7s ago
  Process: 4649 ExecStart=/usr/sbin/mysqld (code=exited, status=1/FAILURE)
  Process: 4641 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=0/SUCCESS)
 Main PID: 4649 (code=exited, status=1/FAILURE);         : 4650 (mysql-systemd-s)
    Tasks: 2
   Memory: 312.0K
      CPU: 210ms
   CGroup: /system.slice/mysql.service
           └─control
             ├─4650 /bin/bash /usr/share/mysql/mysql-systemd-start post
             └─4682 sleep 1

Apr 27 18:54:16 nextcloud systemd[1]: mysql.service: Service hold-off time over, scheduling restart.
Apr 27 18:54:16 nextcloud systemd[1]: Stopped MySQL Community Server.
Apr 27 18:54:16 nextcloud systemd[1]: Starting MySQL Community Server...

**Comment by enoch85** [comment]
Yes, it's most probably due to your data move. The VM is configured with specific details, and it's not supported to change the configuration.

Also, there is a reason why we are moving away from MySQL / MaraDB, it always fails and issues like this have been reported in the past. Though those issues were not related to any data move, rather pure upgrade failures.

So, I don't support this, and I recommend switching to PostgreSQL instead.
