### ISSUE TITLE
error durring installers first run

### ISSUE THREAD

**Issue by MrLordy** [nextcloud/vm#519]
## Steps to reproduce
1. running the installer
2.
3.

## Actual behaviour
  522  Origin Connection Time-out [IP: 104.19.139.75 80]
Fetched 21.5 MB in 2min 30s (143 kB/s)
E: Failed to fetch http://la-mirrors.evowise.com/ubuntu/pool/universe/s/socat/socat_1.7.3.1-1_amd64.deb  504  Gateway Time-out [IP: 104.19.139.75 80]

E: Failed to fetch http://la-mirrors.evowise.com/ubuntu/pool/main/libh/libhttp-message-perl/libhttp-message-perl_6.11-1_all.deb  522  Origin Connection Time-out [IP: 104.19.139.75 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
apt install mariadb-server-10.2 -y failed

**VM version** (Scripted install from master **OR** Released version)
Ubuntu 16.04 on Hyper-v

**Comment by enoch85** [comment]
Don't change the mirrors and you'll be fine.
