### ISSUE TITLE
no network for RC2 [SHOWSTOPPER]

### ISSUE THREAD

**Issue by nasi87** [nextcloud/vm#524]
Hello,

first of all: thanks for your work! It's really nice to see your VM developing over the years!

So I was trying out RC2 of the PostgreSQL-Ubuntu18.04-VM but the script stops immediately

## Steps to reproduce
1. import VM (PGSQL_Nextcloud_Community_VM_RC2.ova)
2. start VM
3. script starts automatically

## Expected behaviour
script runs

## Actual behaviour
script stops because of missing network

## Server configuration

**VM version** (Scripted install from master **OR** Released version)
PGSQL_Nextcloud_Community_VM_RC2.ova

**Updated from an older installed version or fresh install:**
fresh install

## Network
**Do you use DHCP?**
yes

--
I already found the problem in my case: ens3 was down

So I manually edited /etc/netplan/01-netconfig.yaml 
changed "ens32" to "ens3"
sudo netplan apply
run script again - it works

Thank you!

**Comment by enoch85** [comment]
> I already found the problem in my case: ens3 was down

So I manually edited /etc/netplan/01-netconfig.yaml
changed "ens32" to "ens3"
sudo netplan apply
run script again - it works

Thank you!

Great find! Thanks! Will have a look later.

What was the exact error output?

**Comment by enoch85** [comment]
Can you import it again and stop the script with CTRL+C and then run `sudo bash -x /var/scripts/nextcloud-startup-script.sh` and post the output here?

**Comment by enoch85** [comment]
[This](https://github.com/nextcloud/vm/blob/postgresql/nextcloud-startup-script.sh#L77-L95) is the code that should handle that situation.

**Comment by nasi87** [comment]
> Can you import it again and stop the script with CTRL+C and then run sudo bash -x /var/scripts/nextcloud-startup-script.sh and post the output here?

Of course. But output is pretty much to fast to read or screenshot properly. Any chance to read this output later? Is there some logfile? https://imgur.com/a/prn8HO3 https://imgur.com/a/AffpQwR
But it says something about some commands which are not found in lines 58, 59, 60, 65 and maybe 93.

After that it appears the same purple screen as in my post before ("Network NOT OK. ... ")

**Comment by enoch85** [comment]
If you connect with a SSH client like Putty, you can scroll in the output after you stopped it.

Please paste that in a hastebin.

**Comment by enoch85** [comment]
@nasi87 Could you please provide an answer so that I can fix this? As an alternative, could we do a Teamviewer session so that I can try it directly in your environment?

**Comment by enoch85** [comment]
@nasi87 OK, made some fixes, can you please download the latest [startup-script](https://raw.githubusercontent.com/nextcloud/vm/postgresql/nextcloud-startup-script.sh) and do this:

> Can you import it again and stop the script with CTRL+C and then run sudo bash -x /var/scripts/nextcloud-startup-script.sh and post the output here?

...after you imported the new script with the new fixes?

**Comment by enoch85** [comment]
This is now fixed.

**Comment by nasi87** [comment]
> If you connect with a SSH client [...]

Well, without network this might become complicated... ;-)

But I imported new script via usb flash drive and now it works. Thank you a lot!!

**Comment by enoch85** [comment]
> Well, without network this might become complicated... ;-)

Uhm, yeah. ;)
