### ISSUE TITLE
Letsencrypt is not able to continue due to Apache problem

### ISSUE THREAD

**Issue by tedd77** [nextcloud/vm#53]
## Steps to reproduce
1. Fresh VM download
2. Boot machine and follow steps till create lestencrypt certificates and select yes
3. Make sure you  have a registered domain and that port 443 is forwarded on the router

## steps to solve
Remove line 29 reported here 👍 Oct 23 13:25:08 nextcloud apache2[1644]: AH00526: Syntax error on line 29 of /etc/apache2/conf-enabled/phpmyadmin.conf:

Line 29  has a statement :  Require ip
This statement is for some reason empty hence preventing apache from continuing and letsencrypt would also fail

## Expected behaviour
It should carry on with the script installtion

## Actual behaviour
systemctl status apache2.service
? apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           mqapache2-systemd.conf
   Active: failed (Result: exit-code) since Sun 2016-10-23 13:25:08 CEST; 54s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1644 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

Oct 23 13:25:08 nextcloud apache2[1644]:  * The apache2 configtest failed.
Oct 23 13:25:08 nextcloud apache2[1644]: Output of config test was:
Oct 23 13:25:08 nextcloud apache2[1644]: AH00526: Syntax error on line 29 of /etc/apache2/conf-enabled/phpmyadmin.conf:
Oct 23 13:25:08 nextcloud apache2[1644]: 'require ip' requires an argument
Oct 23 13:25:08 nextcloud apache2[1644]: Action 'configtest' failed.
Oct 23 13:25:08 nextcloud apache2[1644]: The Apache error log may have more information.
Oct 23 13:25:08 nextcloud systemd[1]: apache2.service: Control process exited, code=exited status=1
Oct 23 13:25:08 nextcloud systemd[1]: Failed to start LSB: Apache2 web server.
Oct 23 13:25:08 nextcloud systemd[1]: apache2.service: Unit entered failed state.
Oct 23 13:25:08 nextcloud systemd[1]: apache2.service: Failed with result 'exit-code'.

## Server configuration
4 CPU, 3Gbyte Ram
**Server version:** (see your admin page)

**VM version**
ESXI 5.5 VMWARE
**Updated from an older installed version or fresh install:**
Fresh download of Nextcloud VM

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
Insert your ownCloud.log file here
```

**Comment by tedd77** [comment]
output of cat /etc/network/interfaces
source /etc/network/interfaces.d/*

# The loopback network interface
auto lo ens160
iface lo inet loopback

# The primary network interface
iface ens160 inet static
pre-up /sbin/ethtool -K ens160 tso off
pre-up /sbin/ethtool -K ens160 gso off

# Best practice is to change the static address
# to something outside your DHCP range.
address 192.168.xx.xx
netmask 255.255.255.0
gateway 192.168.xx.xx

# This is an autoconfigured IPv6 interface
# iface ens160 inet6 auto

# Exit and save:        [CTRL+X] + [Y] + [ENTER]
# Exit without saving:  [CTRL+X]



output of ifconfig

ens160    Link encap:Ethernet  HWaddr 00:50:xx:b2:xx:5a
          inet addr:192.168.xx.xx  Bcast:192.168.xx.255  Mask:255.255.255.0
          inet6 addr: fe80::xxx:56ff:feb2:xx5a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:59688 errors:0 dropped:0 overruns:0 frame:0
          TX packets:31578 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:66810947 (66.8 MB)  TX bytes:4466611 (4.4 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:40 errors:0 dropped:0 overruns:0 frame:0
          TX packets:40 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:4105 (4.1 KB)  TX bytes:4105 (4.1 KB)

**Comment by enoch85** [comment]
Thanks! Will have a look

**Comment by enoch85** [comment]
As I said earlier, this is probably an issue with your network setup, as the Require IP filed is blank it's a sign that the script couldn't get an IP from DHCP in the $ADDRESS variable. 

Have you changed IP address manually in the interfaces file?

**Comment by tedd77** [comment]
@enoch85 Could be, however I am able to workaround this problem. 
I have no issues concerning the initial installation anymore.
To overcome the problem I just delete the line and carry on.

**Comment by enoch85** [comment]
Nice! Still, would be nice to know if this is a bug or just a temporary glitch. If you find the time, please let me know. 

Thanks!
