### ISSUE TITLE
Cannot install samba/cifs-utill

### ISSUE THREAD

**Issue by wouterVE** [nextcloud/vm#530]
Hi,

I'm trying to mount a samba share in my nextcloud-server but having a hard time with it.

Output `sudo apt-get install cifs-utils`
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package cifs-utils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'cifs-utils' has no installation candidate
```

output `sudo apt-get install samba`

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 samba : Depends: python-dnspython but it is not installable
         Depends: python-samba but it is not going to be installed
         Depends: samba-common-bin (= 2:4.3.11+dfsg-0ubuntu0.16.04.13) but it is not going to be installed
         Depends: tdb-tools but it is not installable
         Depends: update-inetd but it is not installable
         Recommends: attr but it is not installable
         Recommends: samba-dsdb-modules but it is not going to be installed
         Recommends: samba-vfs-modules but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

output` sudo apt-get install python-samba`

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-samba : Depends: python-ldb (>= 1.1.2~) but it is not installable
                Depends: python-tdb but it is not installable
E: Unable to correct problems, you have held broken packages.
```
So, what could be removed in order to get samba working as I really need this for backup purposes. 

Fyi: I have all repositories enabled but multiverse.

**Comment by enoch85** [comment]
If you [Google](http://bfy.tw/I0f4) it you might get a quicker result than asking here. This is no support forum.

Why don't you just use the client that are built into Nextcloud? This seems kind of over complicated. Just install External Storage App and set it up from GUI instead. Should work out of the box, and needed dependencies are already installed.

**Comment by wouterVE** [comment]
ok my apologies, could have fixed it myself indeed, at first sight I thought there were broken packages in this installation hence my post. 

it turned out there was a problem with my sources.list

I chose `mirror.veracruz.co` but this resulted in a `Got NODATA issue: 'NODATA'` when doing `sudo apt-get update`
As can be found on this [post](https://askubuntu.com/questions/474549/got-nodata-issue-nodata-does-the-network-require-authentication), this means the url is not translated correct by the provider.

So I changed my repositories to an official Ubuntu one and now I can install it without problem. 

Maybe one can a take a look at `mirror.veracruz.co` , maybe I'm not the only one with this problem. 

Thanks for the excellent work with this image.

**Comment by wouterVE** [comment]
@enoch85  
You're very welcome! Would be a good idea to stick with the official Ubuntu ones, I've change my repositories to the local ones (`http://be.archive.ubuntu.com/` in my case).
Now sudo apt-get install is working like a charm :-)

Keep up the good work!

Wouter
