### ISSUE TITLE
Collabora Office issue

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#532]
Hello,
I made a fresh installation in HyperV with latest VM (converted form OVA to HyperV). All went fine, so far no problems during installation.

If I try to open a office document (one of the icluded examples) it won't work. Error message:

Error | richdocuments | GuzzleHttp\Exception\ServerException: Server error response [url] https://office.domain.tld/hosting/discovery [status code] 503 [reason phrase] Service Unavailable/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Subscriber/HttpError.php - line 32:  GuzzleHttp\Exception\RequestException  create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Event/Emitter.php - line 108:  GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete')/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 91:  GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent))/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132:  GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))/var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/react/promise/src/FulfilledPromise.php - line 25:  GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)/var/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55:  React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43:  GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134:  GuzzleHttp\Message\FutureResponse  proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165:  GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125:  GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))/var/www/nextcloud/lib/private/Http/Client/Client.php - line 138:  GuzzleHttp\Client->get('https //office....', Array)/var/www/nextcloud/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84:  OC\Http\Client\Client->get('https //office....')/var/www/nextcloud/apps/richdocuments/lib/WOPI/Parser.php - line 41:  OCA\Richdocuments\WOPI\DiscoveryManager->get()/var/www/nextcloud/apps/richdocuments/lib/TokenManager.php - line 133:  OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')/var/www/nextcloud/apps/richdocuments/lib/Controller/DocumentController.php - line 168:  OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)[internal function] OCA\Richdocuments\Controller\DocumentController->index('10')/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161:  call_user_func_array(Array, Array)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91:  OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')/var/www/nextcloud/lib/private/AppFramework/App.php - line 115:  OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:  OC\AppFramework\App  main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)/var/www/nextcloud/lib/private/Route/Router.php - line 297:  call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)/var/www/nextcloud/lib/base.php - line 999:  OC\Route\Router->match('/apps/richdocum...')/var/www/nextcloud/index.php - line 37:  OC  handleRequest(){main}
-- | -- | --

I can generate a new office document in the cloud portal but to open it won't work.

Any idea?

Thanks for your great project and appreciated help!

Best regards

**Comment by enoch85** [comment]
Please search for old issues before you post new ones: https://github.com/nextcloud/vm/issues/521

**Comment by nxtester** [comment]
Hi Daniel,

thanks for your reply but my question ist connected to Collabora Office. Sorry, I forgot to mention that. Case #521 is connected to Only Office. Could you please check it again?

Thanks for your appreciated help!

**Comment by nxtester** [comment]
Hi Daniel,

I now tried several times to get a working installation. But this error persists in all installations. My options:

- Fail2Ban
- Collabora Office, Elasticsearch
- Extra Security, Fixed IP

I am sure that this is no fault on my side.

Thanks again!

Best regards

**Comment by enoch85** [comment]
Collabora is also affected apparently.

**Comment by enoch85** [comment]
Please post in https://github.com/nextcloud/vm/issues/521 instead.
