### ISSUE TITLE
NextCloud VM on Xenserver

### ISSUE THREAD

**Issue by apatek1975** [nextcloud/vm#535]
Hello,
I am having issues with getting the current NextCloud VM to install properly on Xenserver.
When I import the appliance and start it up, it attempts to run the startup script but fails. It takes me to the purple screen that says "It appears something went wrong with the update". It says my data directory is not writable and throws an exception that says "Environment not properly prepared and references line 148 in applicatin.php file. It also says sudo -u www-data php /var/www/nextcloud/occ -V failed. I attempted many different permission changes etc, but nothing seemed to resolve this. I also made sure the data volume was not set to read only in xenserver.

**Comment by enoch85** [comment]
Have you made two disks according to the instructions?

**Comment by apatek1975** [comment]
Yes. When I import the OVA into xenserver it does create two disks. The
data drive is mounted as /mnt/ncdata.

I was actually able to get it working by changing the permissions on the
data drive to be owned by www-data user I think. By default everything  was
root:root. I am going to try it again from scratch because I made a lot of
different changes trying to get it to work.

**Comment by enoch85** [comment]
That's strange because this is how the permissions look like on a freshly mounted OVA:

**/mnt/ncdata**
```
total 28
drwxrwx--- 5 www-data www-data    9 maj 10 14:30 ./
drwxr-xr-x 3 root     root     4096 maj  7 23:45 ../
drwxr-xr-x 7 www-data www-data    7 maj 10 14:30 appdata_ocnnap7p5mox/
drwxr-xr-x 2 www-data www-data    3 maj  7 23:46 files_external/
-rw-r--r-- 1 root     www-data  324 maj  7 23:46 .htaccess
-rw-r--r-- 1 www-data www-data    0 maj  7 23:46 index.html
drwxr-xr-x 3 www-data www-data    3 maj  7 23:46 ncadmin/
-rw-r--r-- 1 www-data www-data    0 maj 10 14:30 nextcloud.log
-rw-r--r-- 1 www-data www-data    0 maj  7 23:46 .ocdata
```

**Comment by apatek1975** [comment]
I just tried a fresh install. It fails the startup script with the
following information:

ncadmin@192.168.1.103's password:
Welcome to Ubuntu 18.04 LTS (GNU/Linux 4.15.0-20-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu May 10 20:24:40 CEST 2018

  System load:  0.0               Processes:           136
  Usage of /:   6.0% of 38.14GB   Users logged in:     1
  Memory usage: 11%               IP address for eth0: 192.168.1.103
  Swap usage:   0%


3 packages can be updated.
2 updates are security updates.

Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check
your Internet connection or proxy settings


Last login: Thu May 10 20:19:42 2018
+-----------------------------------------------------------------------+
| Thanks for downloading this Nextcloud VM by the Nextcloud Community!  |
|                                                                       |
| To run the startup script type the sudoer password. This will either  |
| be the default ('nextcloud') or the one chosen during installation.   |
|                                                                       |
| If you have never done this before you can follow the complete        |
| installation instructions here: https://goo.gl/JVxuPh                 |
|                                                                       |
| You can schedule the Nextcloud update process using a cron job.       |
| This is done using a script built into this VM that automatically     |
| updates Nextcloud, sets secure permissions, and logs the successful   |
| update to /var/log/cronjobs_success.log                               |
| Detailed instructions for setting this up can be found here:          |
| https://www.techandme.se/nextcloud-update-is-now-fully-automated/     |
|                                                                       |
|  ####################### Tech and Me - 2018 ########################  |
+-----------------------------------------------------------------------+
[sudo] password for ncadmin:
Testing if network is OK...
Online!
Testing if network is OK...
Online!
/dev/fd/63: line 585: [: : integer expression expected
/dev/fd/63: line 621: [: : integer expression expected
Your data directory is invalid
Ensure there is a file called ".ocdata" in the root of the data directory.

Your data directory is not writable
Permissions can usually be fixed by giving the webserver write access to
the root directory. See
https://docs.nextcloud.com/server/13/go.php?to=admin-dir_permissions.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in
/var/www/nextcloud/lib/private/Console/Application.php:148
Stack trace:
#0 /var/www/nextcloud/console.php(89):
OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput),
Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#2 {main}Sorry but something went wrong. Please report this issue to
https://github.com/nextcloud/vm/issues and include the output of the error
message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ -V failed
root@nextcloud:~#

If I examine the ncdata directory I get this:


root@nextcloud:~# ls -lah /mnt/ncdata
total 8.0K
drwxr-xr-x 2 root root 4.0K May  6 18:15 .
drwxr-xr-x 3 root root 4.0K May  6 18:15 ..
root@nextcloud:~#

If i change ownership to www-data, it still gives the same error however,
If I make the empty .ocdata file in the root of ncdata and then run sudo
-i, the installation then will proceed.

Am I doing something wrong here, or is this a legitimate issue?

**Comment by enoch85** [comment]
I have no idea why it doesn't work. Try to download VMware Player or VirtualBox and run the OVA just to check if it's a hypervisor issue.

 I'm pretty sure it's either a configuration issue, or that the OVA isn't compatible with Xenserver.

**Comment by enoch85** [comment]
OK, so no error in the actual VM then. 

Thanks for confirming.
