### ISSUE TITLE
Collabore issue with latest Script

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#538]
Hi,

I just set up a new nextcloud machine with the latest scripts (wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh). Sorry, but Collabora ends up with the same error like before. No chance to open office documents. Also got at the end of the installation an error message from elasticsearch never seen before:

![grafik](https://user-images.githubusercontent.com/28905767/39931021-7f32bb4e-553c-11e8-932b-c25a468fe946.png)

--
Error | richdocuments | GuzzleHttp\Exception\ServerException: Server error response [url] https://office.domain.tld/hosting/discovery [status code] 503 [reason phrase] Service Unavailable/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Subscriber/HttpError.php - line 32:  GuzzleHttp\Exception\RequestException  create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response))

Best regards

nxtester

**Comment by enoch85** [comment]
The first picture doesn't have anything to do with Collabora or OnlyOffice.

I'll have a look at the log output though.

**Comment by enoch85** [comment]
A quick google search make me believe that Guzzle needs to be updated in the Docker.

https://github.com/guzzle/guzzle/issues/1956

@agolybev Anything you know how to fix?

**Comment by agolybev** [comment]
Hi Daniel, I've know nothing about it. How does it relate with OnlyOffice?

**Comment by enoch85** [comment]
@agolybev OnlyOffice is run as a docker, doesn't that mean that it's possible to raise the GuzzleHTTP version?

**Comment by MrLordy** [comment]
just to confirm . i also do get the bottom problem when using Collabora. on a clean install off ubuntu 18.04

**Comment by enoch85** [comment]
@MrLordy So a restart fixed it?

**Comment by nxtester** [comment]
For me a restart didn't change anything.

**Comment by nxtester** [comment]
I tested several times with a clean Ubuntu 18.04 installation and a quite smooth run of the script. No errors so far except mentioned fulltext error at the end of installation and not working Collabora Office (which is also not working after some restarts).

**Comment by enoch85** [comment]
Just made a clean install on Digitalocean with Collabora, all the latest scripts. Worked without a reboot even. Going to test Onlyoffice now, but it sure seems promising.

**Comment by enoch85** [comment]
OK, after a reboot I had to make a reboot of Apache2, hmm.

**Comment by enoch85** [comment]
Seem like docker isn't stable for 18.04 yet. There's the main issue. https://github.com/docker/for-linux/issues/290

**Comment by enoch85** [comment]
Anyway,workaround until then is to run `docker ps -a` after reboot. That helped in 100% of the cases for me.

**Comment by enoch85** [comment]
Same goes for Onlyoffice, just tested.

If you want to test for yourself you can use `curl -fsSL test.docker.com | sh` instead of installing `docker.io`
