### ISSUE TITLE
Consider using overlay2 instead of AUFS for docker

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#540]
https://fribeiro.org/tech/2018/02/13/collabora-docker-nextcloud/

https://docs.docker.com/storage/storagedriver/overlayfs-driver/#configure-docker-with-the-overlay-or-overlay2-storage-driver

**Comment by Ark74** [comment]
Wow! How things evolve, I still recall when AUFS was the recommended default fs by docker.
Sounds like a good move.

What would you like to be the scope?
A migrate process for running instances (on update), or just as a new default for new instances with the option to migrate (separate script)?

**Comment by enoch85** [comment]
In with the new out with the old. The script is intended for new users, so no need to migrate. If you already run docker on AUFS, why use this script?
