### ISSUE TITLE
Hyper V installing issue

### ISSUE THREAD

**Issue by meikel90** [nextcloud/vm#543]
Hi , i have the Hyper-V vhd disk1 and 2. I dont know why there a two disks.
i did everthink like in the instruction but ist start with this issue followed in th picture.

![image](https://user-images.githubusercontent.com/39386972/40201547-a7c0e134-5a1f-11e8-9fc3-30e3938fec45.png)

i need help 
thanks.

**Comment by enoch85** [comment]
I tested as late as a few days ago and everything was working.Sorry, but a picture doesn't say a 1000 words in this case,

Please tell me the exact steps you took.

**Comment by meikel90** [comment]
Hi,
I created the vm like in der German Video on the page techandme. Using the vhd disk1. 
Start the vm. 
Log in with ncadmin After Login Root password Thema the instsllation Starts and After a few seconds i get the issue

**Comment by meikel90** [comment]
a second before this notifications comes i have this 
![image](https://user-images.githubusercontent.com/39386972/40220977-4d67b454-5a7b-11e8-9367-ef067120e082.png)

**Comment by enoch85** [comment]
Yes, I know about that guide, but it doesn't work like that anymore. There are two drives that needs to be imported. One for OS (Disk 1) and one for Data (Disk 2).

So, import both drives with disk 1 as the main drive and then try again.

**Comment by meikel90** [comment]
thas what i did today same issue

**Comment by enoch85** [comment]
Well, if it didn't work you did it wrong. I tested with a customer just a few days ago and it worked without any issues. Can you please record a video of how you did and post it here?

I will see if I have time to make a guide specific for Hyper-V. Maybe next week or so.

**Comment by meikel90** [comment]
you used IDE or SCSI ?

**Comment by meikel90** [comment]
when the machine ist booting there is one issue more i think thats the problem:

> mount ZFS failes

**Comment by enoch85** [comment]
SCSI.

Try `zpool import` as root.

**Comment by meikel90** [comment]
i will try. 
SCSI don't work then nothing ist gonna boot.

**Comment by enoch85** [comment]
I'll have to double check, but if zfs fails to mount then I would start looking at that if I were you. Sorry but I can't magically solve issues, please put some effort into it yourself as well.

Thank you!

**Comment by meikel90** [comment]
hi ,
sorry i am not a special list in Unix. zpool import dont work for me.
I hope you will find time to make an quick guide. thanks.

**Comment by enoch85** [comment]
Just installed another Hyper-V server, and there where no issues. I'm closing this as it's most probably a configuration issue. Please re-open if you think I'm wrong.
