### ISSUE TITLE
service networking restart failed

### ISSUE THREAD

**Issue by neylandcd** [nextcloud/vm#547]
Running the install I am getting this error:

** server can't find github.com: SERVFAIL

Trying to restart networking service...
Failed to restart networking.service: Unit networking.service not found.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
service networking restart failed

Networking is working because I installing this over SSH. Any suggestions? I looked in the script for where it is trying to restart networking but can't seem to find it. Any help would be greatly appreciated. Thanks

**Comment by enoch85** [comment]
@neylandcd Thanks for reporting this. We just merged #542 which seems to not work optimally. We'll have a look on how we can improve it.

**Comment by enoch85** [comment]
cc @penzoiders FYI

**Comment by enoch85** [comment]
This should be fixed now, please try again.

**Comment by enoch85** [comment]
@neylandcd Did it work?
