### ISSUE TITLE
when HDD added error "appears that something went wrong with the update" comes up

### ISSUE THREAD

**Issue by BeyoncesHomeboy** [nextcloud/vm#549]
Everything on the PC is a fresh install
## Steps to reproduce
1.  I imported the VM to workstation 14, added 4 other drives. Booted the VM
2. Get the green light on everything but the install comes up I get the error listed above.
3.  I did a update and upgrade on bash and ran the script again, same error.

## Expected behaviour
Tell us what should happen
To go through the installation process without an issue but see the added drives and add them to the total storage.
## Actual behaviour
Tell us what happens instead
a )Everything installs just fine without the added drives but when you add the drives the cloud storage does not expand (still only have a 40gb limit).

b) Tried to expand storage and when running the script only one of four drives are seen and you can not expand the original storage b/c they 2 seperated drives.

c) I booted into rescuecd and booted gparted from there and even though the drives are seen you can not expand one drive or get nextcloud to see the drives.
 
d) try to install nextcloud on the one of the storage drives so then maybe I can expand them later but when imported it automatically picks the C drive and will not allow you to change it. 
## Server configuration

**Server version:** (see your admin page)
ubuntu 18? (it's the latest version of techandme next cloud)
**VM version** (Scripted install from master **OR** Released version)
workstation pro 14
**Updated from an older installed version or fresh install:**
fresh install
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
When drives are added (can't even get to this install section)
Without the drives added (it installed everything but these ports were not open)
#### Log file (/var/ncdata/nextcloud.log)
[vmware.log](https://github.com/nextcloud/vm/files/2020689/vmware.log)
[vmware-0.log](https://github.com/nextcloud/vm/files/2020690/vmware-0.log)

```
Insert your nextcloud.log file here
```

#### Installation log (command output)
Can't get nextcloud installed with these added dries. The one were nextcloud did install but didn't see the external drives, I deleted it (I know, dumb move). 
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Aah I misread. You can only have 2 drives, if you are not a Linux pro and know how to add new drives. 

So this is a configuration issue, not an error.
