### ISSUE TITLE
NextCloud Box from WDLabs lost NextCloud version 9.53 

### ISSUE THREAD

**Issue by jmartin17** [nextcloud/vm#55]
@nextcloud/vm

Per Daniel Hansson's request use Github for reporting bugs and suggest enhancements.
I purchased the NextCloud Box for WDLabs.
When I first power up and got the login screen I put a user ID and password in and logged in successfully. 
When I tried to login on another pc on the LAN it gave me the log in screen but said: Wrong password. Reset it. I tried again same message so
I clicked on the Reset it and it gave me: could not send reset email because
there is no email address for this username. I had signed off the PC that I had signed onto when I setup the username and password that I had first logged in successfully.
Now I can’t get back in on any system on the LAN always get same error. I have tried to find out how to reset using browser as there is no keyboard and monitor attached to the NextCloud box and I don't have a way of doing that. I was able to download PuTTY. I can get into the box using PuTTY SSH and I can run commands and see the nextcloud directory but how
can I reset or set the password for nextcloud box? When I use passwd it
prompt me for a password for ubuntu so I changed the password. I tried to 
sudo nextcloud.occ user:resetpassword jmartin resulting in:
[sudo] password for ubuntu:
sudo: nextcloud.occ:
command not found
I was advised by Kyle Fazzari @github.com to run
$ sudo apt update
$ sudo apt install snapd snap-confine 
snapd is already the newest version (2.12+0.16.04).
$ sudo snap refresh
$ sudo snap remove nextcloud && sudo snap install nextcloud
it removed nextcloud but gave:
error: cannot install "nextcloud": Get https://search.apps.ubuntu.com/api/v1/snaps/details/nextcloud?confinement=strict: dial tcp: lookup search.apps.ubuntu.com on 208.76.58.193:53: no such host
I tried wget https://github.com/nextcloud/vm.git
and wget http://github.com/nextcloud/vm.git 
after login on NextCloud Box with ID: ubuntu

Here is the results:
wget https://github.com/nextcloud/vm.git
--2016-09-05 05:16:53--  https://github.com/nextcloud/vm.git
Resolving github.com (github.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'github.com'

using snap seems to have a problem with finding commands for nextcloud and resolve host address.  Cannot download from any source after signing on  NextCloud Box with ID: ubuntu 
runing ubuntu@ubuntu-standard:~$ snap list
Name         Version               Rev  Developer  Notes
ubuntu-core  16.04+20160531.12-01  120  canonical  -
ubuntu@ubuntu-standard:~$ snap refresh
error: cannot list updates: cannot list snaps: cannot list updates: Post https://search.apps.ubuntu.com/api/v1/snaps/metadata: dial tcp: lookup search.apps.ubuntu.com on 208.76.58.193:53: no such host
ubuntu@ubuntu-standard:~$
appreciate any help.  jmartin@jmartinassociates.net

**Comment by enoch85** [comment]
Moved to https://github.com/nextcloud/nextcloud-snap/issues/122
