### ISSUE TITLE
Redis spams the log with Unable to load dynamic library 'redis.so' 

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#553]
Fresh installed latest Nextcloud VM 13 has an error in system logs:

```
PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20170718/redis.so (/usr/lib/php/20170718/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20170718/redis.so.so (/usr/lib/php/20170718/redis.so.so: cannot open shared object file: No such file or directory)) at Unknown#0
```

This is most likely a dependency issue. Waiting for Ubuntu to update their packages.

**Comment by enoch85** [comment]
Found this: https://bugs.launchpad.net/ubuntu/+source/php-redis/+bug/1762935

Seems like a bug in Ubuntu 18.04.

**Comment by fgrosswig** [comment]
maybe (?) a workaround => https://github.com/nextcloud/vm/issues/551#issuecomment-391639108

**Comment by enoch85** [comment]
We used PECL before in the old scripts and yes, we didn't have the log entry but users change the default value from no to yes when updating Redis, so I decided to use this solution instead of using PECL.

So which is best:
1. A log entry that spams the log but doesn't do any harm
2. The risk of users changing the default value and break Redis

I think option 1 is best.

Refs:
https://github.com/nextcloud/vm/commit/672c99778a29336f05cdeed50583b337abd3f85e
https://github.com/nextcloud/vm/commit/c3fc43cc608077ae40436c5d0292b2f7db9675ac#diff-6106caeae41ab8eab27ceea759b9a1daL40
https://github.com/nextcloud/vm/commit/c3fc43cc608077ae40436c5d0292b2f7db9675ac#diff-e8ae2ca50667181e7b480d6f8e55ad75R27

**Comment by fgrosswig** [comment]
So it should rather used with build option “no” for redis support? I don’t understand - can you be more specific why you discarded redis built in on php module ? Think this are 2 different things - unless Ubuntu php package is somehow broken and my intention was to get latest redis option to php - this was archived by PECL :-)

**Comment by enoch85** [comment]
When you build with PECL you can choose to enable support for memcache and some other stuff (I don't remember now) and most users think "hey, that sounds good, let's enable it" and then change the default [no] to [yes]. Problem is, that will break Redis as no memcache is installed.

I fixed that by always answering "no" with the `yes` command as you can sse in the code I linked, but I'd rather work with built in dependencies than using something like PECL, which is 3:rd-party.

Do you understand now?

**Comment by enoch85** [comment]
@fgrosswig Any update here?

**Comment by fgrosswig** [comment]
i rather would close this issue. I would prefer the way to have an "un-noisy" log handling so maybe this is only on Ubuntu 18 LTS. There is a problem with redis anyway and my solution above fix it sufficient. :-)

**Comment by enoch85** [comment]
OK, let's close this and hope that the maintainer of Redis in Ubuntu fixes the issue in comiong releases. :)

**Comment by pcreadycl** [comment]
The error still in NC 15... Anyone?

**Comment by enoch85** [comment]
@pcreadycl The VM uses the PECL installation method since some versions back. Just run the built in update script to fix it.

`sudo bash /var/scripts/update.sh`

**Comment by wmh** [comment]
try to change the priority of loading extension:
```
20-igbinary.ini
30-redis.ini
```

**Comment by enoch85** [comment]
@wmh Is this for the current PECL implementation or is it for the old one?

Afaik there are no issues with the new implementation.
