### ISSUE TITLE
ESXi: Unsupported Hardware Family

### ISSUE THREAD

**Issue by vampire337** [nextcloud/vm#556]
## Steps to reproduce
1. Deploy OVA using latest vSphere client.
2.
3.

## Expected behaviour
OVA deploys and a new VM is created.  Previous deploys of the NextCloud VM have worked in this environment; this just has some issues with the OVA file.

## Actual behaviour
Error: "The OVF package requires unsupported hardware. Details: Line 27: Unsupported hardware family 'vmx-12'"

## Server configuration
ESXI 6.0.0, build 3620759.  VM is the latest OVA downloaded from GitHub a half hour ago.

## Network
Managed network using a Mikrotik CRS109, DHCP, assigned IP addresses.  Haven't made it that far yet in this particular install.

**Comment by enoch85** [comment]
Thanks, could you please download VMware 12 and try with that instead? Maybe they ended support for 12, seems odd with such short time support though.

**Comment by vampire337** [comment]
12 is a virtual hardware version, not a VMWare version.  Workstation is the desktop virtualization product (for running a VM inside of Windows), and ESXi is the server hypervisor product.  Workstation 12 (obviously) supports version 12 hardware, but I did a little digging to version of ESXi 
supports hardware version 12: https://kb.vmware.com/s/article/1003746

Long story short, ESXi 6.0 supports up to hardware version 11.  Higher virtual hardware versions support newer operating systems and higher limits on RAM/disk space/CPU/etc, while lower versions are compatible with more virtualization platforms.  More info: https://kb.vmware.com/s/article/2051652

I will use the OVFtool to attempt to reformat the VM into an OVA with a lower hardware version (as long as it fits within the needs of the VM), but the file that's available right now is only going to support ESXi 6.5, Workstation/Player 12 and Fusion 8 because of its hardware version.  For compatibility reasons, I usually try to stick with hardware version 8 (10 if SATA virtual drives are needed, or when packaging Windows Server 2016).

**Comment by enoch85** [comment]
Sorry, didn't read the initial issue properly :) You're right, and it's intended. The VM had version 8 before, but who runs on that still...? I suggest you upgrade your environment, 6.5 has been out for quite some time now. I even think 6.7 is around the corner. Most people just download VMware 14 player (which is free) and run it on that.

Since you seem so versed in VMware, maybe you should try to make your own VM and install it from scratch with your version? The scripts are freely available as I'm sure you've seen in this repository.

If you run your own environment since you should know how to install a new VM and how to use a script by now. :)

Closing.

**Comment by vampire337** [comment]
I'm curious why the hardware version change was intended...  Version 10 supports everything your VM seems to need.  Surely there's some technical reason other than an arbitrary "who runs on that still?"  Per this support ticket, I still recommend using the lowest version that supports the features your VM requires.

Yes, 6.5 has been out, and 6.7 was released a month or so ago.  Because the upgrade of ESXi costs money (hundreds-to-thousands in USD), lots of people stick with what they have rather than paying for what they don't have a need for, and I am one of those people.  Also, VMWare is in their newer versions deprecating the vSphere client, and many of their users have many not-nice things to say about the web interface.  Beginning with 6.5 the vSphere client is no longer usable, so I'll be holding at 6.0 for as long as it's supported.  My intent is to deploy this as an appliance so it's easier to support (common OS provided by the developer as opposed to trying to support whatever OS and configuration I may have cooked up and scripts I may or may not have executed properly).  Perhaps this is not the right tool for my use-case tho.  Thanks for your responses.

**Comment by enoch85** [comment]
> users have many not-nice things to say about the web interface

I think it's quite nice. 

> My intent is to deploy this as an appliance so it's easier to support (common OS provided by the developer as opposed to trying to support whatever OS and configuration

I think the instructions are [pretty clear](https://github.com/nextcloud/vm#build-your-own-vm-or-install-on-a-vps), install Ubuntu 18.04 Server. I even placed checks inside the scripts for people like want to do it on their own.

**Comment by thejohnha** [comment]
@vampire337 Have you considered changing your hypervisor to Proxmox? I went from ESXi to Proxmox about a year ago and haven't looked back.

Also I agree with Daniel that running the script on a bare instance is very easy and clean. Just run it once and save your VMware image if you want to re-deploy it again later. But I find that running the latest script on a bare machine is good and Daniel works very hard to continually ensure the script is in a good working state.

**Comment by vampire337** [comment]
@thejohnha Thanks for the recommendation; I'll try to dig into that a bit.  Outside of my own Plex and RDP needs, I support a lot of customers in various industrial engineering verticals, where software packages costing hundreds of thousands of dollars run manufacturing lines & utilities distributions and are limited to VMWare environments if you intend to get answers from their respective support departments when something stops working.  If I recommend an alternative, I have to be confident I can support it if they run into problems, so I keep a working ESXi sandbox in my pocket to help support their environments.  But Proxmox might be something to play with on the side.

I'm fine running scripts myself, but for me to walk a less technical user through unfamiliar OS installs and script execution over the phone is less comfortable.  I'm sure the install script does an amazing job, but that's not the thing I was looking for that used to work.  Technical details like VM hardware version support is certainly the developer's prerogative, so I'll work with what is offered or move on.  NextCloud offers some really great features, but my takeaway is that for now this is maybe too big a bite for me to tell someone else to chew.

**Comment by enoch85** [comment]
@vampire337 Why don't you make it simple for yourself and make money at the same time? Charge for the installation and do it for them.
