### ISSUE TITLE
Stuck on “waiting for apt-get to exit” in phase 2

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#558]
Hello,
a new problem occured with latest script in phase 2 after first restart when script will start to configure additional components. This issue has never been happened before. 

Thanks for any help.

![grafik](https://user-images.githubusercontent.com/28905767/40866859-4e92a024-6600-11e8-8fdb-1de1f124eadf.png)

**Comment by enoch85** [comment]
Just wait until it finishes. Can take a while...
