### ISSUE TITLE
Phase 2 / SSL-Installation: Unable to detect open ports

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#559]
Hi,
latest script has serious issues to detect open ports 80 + 443. It always say "Ports not open" but ports are definetely open, checked several times (eg. https://www.yougetsignal.com/tools/open-ports/). 

Unfortunately this faulty port-checker will break the whole script instead to ask if I want to continue even if open ports are not detected.

Never had this issue before, VM is the same. Tried 4 times to overcome this issue / new installation.

There are also several times warnings like that:
![grafik](https://user-images.githubusercontent.com/28905767/40880847-d1fe637c-66b8-11e8-9eb4-deaa70f45a83.png)

Tried to change between fixed IP to DHCP and vice versa but port detection won't work correctly.

Remark: I did about 20 installations of this script in the last weeks so this issue is real.

Any help appreciated. Thanks.

Best regards,

nxtester

**Comment by nxtester** [comment]
Hi Daniel,

thanks for your reply. I also thought that your mentioned possible reasons are real but I checked all again and again. In the last weeks I set up many VMs with your script for testing purposes and never had any problem at this stage. Another indicator is that if VM is shutdown the portchecker at yougetsignal.com will show closed ports at 443 and 80. If I start the VM again it detects open ports.

There must be a change in the script regarding internal open port checker. Is it possible to disable this check?

Thanks for your appreciated work!

Best regards,

nxtester

**Comment by nxtester** [comment]
PS:

Path and name of my network configuration is 
/etc/netplan/50-cloud-init.yaml

I checked parts of your scripts where I see name and path like /etc/netplan/01-netcfg.yaml.

Might this be the reason for my issues? But it worked until around two weeks, never had issues running your script with my master Ubuntu VM.

**Comment by nxtester** [comment]
Here is the exact course of events:

Do you want to install SSL? ([y]es or [N]o): y
Are you sure you want to continue? ([y]es or [N]o): y
Have you forwarded port 80+443 in your router? ([y]es or [N]o): y
Do you have a domain that you will use? ([y]es or [N]o): y

+---------------------------------------------------------------+
|    Please enter the domain name you will use for Nextcloud:   |
|    Like this: example.com, or nextcloud.example.com           |
+---------------------------------------------------------------+

cloud.domain.name

Is this correct? cloud.domain.name ([y]es or [N]o): y
Testing if network is OK...
Failed to restart network-manager.service: Unit network-manager.service not found.
[/] E: Der dpkg-Prozess wurde unterbrochen; Sie müssen manuell »sudo dpkg --configure -a« ausführen, um das Problem zu beheben.
/dev/fd/63: line 277: nmap: command not found
/dev/fd/63: line 288: nmap: command not found
Press any key to exit... root@ubuntu:~#

**Comment by nxtester** [comment]
Yes, Ubuntu Server 18.04 LTS.

**Comment by enoch85** [comment]
OK, so my question is, if we both are running Ubuntu 18.04 LTS, we both are using the same scripts, and the end result is different - then what do you think? To me it seems like there is something strange with your config. 

The only thing you need is to follow the instructions, I could make a video but that shouldn't be needed as it's quite simple - install Ubuntu server 18.04 (preferably with ncadmin/nextcloud), run the install script, and then just follow the instructions. Have you done that?

**Comment by nxtester** [comment]
Of course, many many times successful. I am on HyperV, working since 2 months with same master-VM which is replaced for every new installation, sometimes working with snapshots. But for this issue I copied new master-VM which was many times a successful ground for your script and started from zero. 

VM is HyperV Gen2 but this was never a problem.

**Comment by enoch85** [comment]
You say your "master-VM", how is that configured?

**Comment by nxtester** [comment]
Exactly according your list "Build your own VM, or install on a VPS". Fixed MAC (manual changing if I use the VM another time). Rest according to https://decatec.de/home-server/ubuntu-server-18-04-lts-als-hyper-v-gastsystem-installieren-und-optimal-einrichten/.

Remember: I used this Master-VM already several times for the NC-script w/o any problems. Question: Is the setting "Activate spoofing MAC address" in the VMs configuration relevant? For NGINX it's relevant but I don't think so for Nextcloud.

**Comment by enoch85** [comment]
If you used your "master-vm" for months then it's not 18.04 since that was released just a few weeks ago. Yet you say that you

1. Are using Ubuntu 18.04

> Yes, Ubuntu Server 18.04 LTS.

2. Been using the same "master-vm" for months.

> working since 2 months with same master-VM

That kind of confuses me. 

I will test to install on Hyper-V some day when I have time, but as I installed it on Hyper-V just like 1 week ago successfully I don't think this is an issue with the script, thus I will not prioritize this.

You are free to do your own tests, and send a PR if you find something that is wrong.

**Comment by enoch85** [comment]
Also, looking at the guide you sent I can see that you use the live installer which you shouldn't.

**Comment by enoch85** [comment]
And no, you shouldn't create a second yaml netwrok file, as I said, just let the script do it's thing.

From the guide:

```
1 | nano /etc/netplan/50-cloud-init.yaml
```

**Comment by nxtester** [comment]
Thanks for your reply, Daniel.

Is it normal, that phase 1 of installation script ends with this screen?

![grafik](https://user-images.githubusercontent.com/28905767/40891921-1250a42c-678f-11e8-8db7-2ce6d9b9cd4d.png)

I think in earlier versions of the script at this stage was a message like "Press a key to reboot" or so.

**Comment by nxtester** [comment]
And here is the first screen of phase 2 of installlation script (after reboot at the stage of the last screen in phase 1 provided before) which shows this strange error message "network manager service not found":

![grafik](https://user-images.githubusercontent.com/28905767/40891980-239cb184-6790-11e8-98de-757b0ffeaf23.png)

**Comment by nxtester** [comment]
OK, I give up. Tried it now again, same error. 

My master VM is about 6 weeks old, checked it now. Used it many times for your script, never had any problems. What to do? You wrote, live installer isn't recommended. I used "ubuntu-18.04-live-server-amd64.iso". Which ISO do you recommend?

If you wanna check it I can send you a Teamviewer link by mail.

**Comment by enoch85** [comment]
@nxtester Thanks for your support and donations.

1. Follow the install instructions in the README.
2. *Don't* configure anything yourself from any guide or similar. 
3. Use the alternative (old) installer ISO.
4. Use generation 1. Generation two is untested.

Network manager is installed if not existing and is also the new default in Ubuntu 18.04. It confuses me that the script say that it's missing since it really shouldn't.

I don't have time for Teamviewer, and what you're asking for is a complete new installation of which you can make your "master-VM", and normally that's $150 per session. As I already said I never had any issues and I do several installations per week, for customers and in testing purposes.

**Comment by nxtester** [comment]
ok, thanks for your appreciated support.

I will set up a new machine with alternative installer and report again.

**Comment by nxtester** [comment]
Created a new master-vm with alternative (old) installer (File "ubuntu-18.04-server-amd64,iso") as a HyperV Gen 2 machine. All went smooth, issue with port-checker was gone away. Full text is also working.

Thanks for your support.

**Comment by enoch85** [comment]
In the future, please ask for support in the forums. Github is no place for support.
