### ISSUE TITLE
How to uninstall components if they don't work or in BETA status

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#560]
Hi,
it happens, that components installed by nc-script are still BETA or have issues.
How can they correctly uninstalled to install a fixed version of the component (e.g. fulltext-search). Could you please give an example how to act without damaging rest of NC installation?

Thank you :-)

Best regards,

nxtester

**Comment by nxtester** [comment]
@johnczer 
I only work with Collabora-Office and this rocks in Nextcloud :-)

**Comment by enoch85** [comment]
There are no beta scripts in the VM for now, and if they are it's obvious that they are because it clearly says "BETA" in the text.

Full Text Search was beta before, and if you want to uninstall it please ask in the forums, I have no idea. The new script works, but the app is still in beta though.
