### ISSUE TITLE
Fulltext doesn't work

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#569]
Hi,

I suppose to leave fulltext-search in the currect state because it produces unwanted results. I set up NC with the latest script and it went smooth. If I am logged in as "ncadmin" fulltext-search is working. But if I am logged in as another user it produces such crappy results:

![grafik](https://user-images.githubusercontent.com/28905767/41510897-e13e3564-726c-11e8-8eeb-dbd63fc58240.png)

Any idea to resolve this issue? Thank you!

**Comment by enoch85** [comment]
Please report this issue in the correct repo, not here. Thank you.
