### ISSUE TITLE
E: Unable to locate package libapache2-mod-spamhaus

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#573]
```
Building dependency tree       
Reading state information... Done
E: Unable to locate package libapache2-mod-spamhaus
Adding Whitelist IP-ranges...
sed: can't read /etc/apache2/mods-enabled/spamhaus.conf: No such file or directory
```

**Comment by Ark74** [comment]
Seems to be valid only for Xenial or on Debian.
Bionic doesn't apply.

**Comment by enoch85** [comment]
Hmm, I tested on Bionic, can you please try again?

**Comment by Ark74** [comment]
Please take a look at:
https://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=libapache2-mod-spamhaus

The package is not available on Artful nor Bionic or Cosmic.

**Comment by enoch85** [comment]
Exactly, so we need to find a replacement. Hence this report.

**Comment by Ark74** [comment]
Ohh! sorry didn't quite get the meaning. Ok, so looking for a replacement.
I'll start looking for one as well. :+1:

**Comment by enoch85** [comment]
Maybe we can download it from here? http://www.miim.com/software/linux/modspamhaus.html

**Comment by enoch85** [comment]
This is fixed by not installing the package.

We'll use another method instead.
