### ISSUE TITLE
Nextcloud 13.0.4 - Script isn't run automatically due to missing .bash_profile

### ISSUE THREAD

**Issue by starshark-ua** [nextcloud/vm#574]
## Steps to reproduce
1. download OVA from https://www.techandme.se/nextcloud-vm/
2. deploy into my esxi
3. start and open vm console, enter login and password (ncadmin/nextcloud)

## Expected behaviour
Automatic run install script?

## Actual behaviour
command promt only (ncadmin@nextcloud:~$)

## Server configuration

**Server version:** (see your admin page)

**VM version** (Scripted install from master **OR** Released version)

**Updated from an older installed version or fresh install:**
fresh install

## Network
**Do you use DHCP?**
yes
**Is port 80 and/or 443 open?**

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
You have to type `nextcloud` the first thing you do and the script should start.

**Comment by starshark-ua** [comment]
nextcloud: command not found (((

**Comment by enoch85** [comment]
I just tested and it's a bug. I will make a new release tonight.

Meanwhile please type `sudo bash /var/scripts/nextcloud-startup-script.sh`

**Comment by starshark-ua** [comment]
Not impossible. directory /var/scripts not exist

**Comment by enoch85** [comment]
> Not impossible. directory /var/scripts not exist

Eeh, ok? Hmm... Something is very wrong. I will make a new release in a few hours.

**Comment by enoch85** [comment]
Is it the same with the version on Github?

**Comment by starshark-ua** [comment]
Sorry, i am not found download refference for vm on github.

**Comment by enoch85** [comment]
Check under "Releases".

**Comment by enoch85** [comment]
https://github.com/nextcloud/vm/releases

**Comment by starshark-ua** [comment]
Yea, this iso is identical.

**Comment by enoch85** [comment]
Okay, will begin with a new release soon.

**Comment by enoch85** [comment]
@starshark-ua Please try the new release.

Thanks!

**Comment by enoch85** [comment]
Tested and works!
