### ISSUE TITLE
Update tutorial

### ISSUE THREAD

**Issue by includes08** [nextcloud/vm#575]
https://www.techandme.se/not-enough-space/

This is something that isn't accurate anymore as it now uses /mnt/ncdata. Is there a new tutorial somewhere, as i still haven't figured out the best way to do it.

**Comment by enoch85** [comment]
@includes08 Did you read the **BOLD** text?

If not, here it is: 

```
Please note that this guide won’t work for /mnt/ncdata on Nextcloud VMs from 13.0.2 and onwards due to a new file system called ZFS in the later versions of the VM. Though there’s a community member who has taken the time to write a new guide.
```
