### ISSUE TITLE
check_distro_version() gives erroneous result using Proxmox LXC standard container image

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#577]
## Steps to reproduce
1. run install script
2.
3.

## Expected behaviour
It should continue past the check_distro_version() check

## Actual behaviour
It stops saying I need Ubuntu 18.04, but I am using that OS.

## Server configuration
Proxmox LXC container image. Proxmox has standard container images. 16.04 used to work, but I tested and it doesn't work anymore.

**Server version:** (see your admin page)
Ubuntu 18.04 and 16.04, updated

**VM version** (Scripted install from master **OR** Released version)
latest as of 20180706

**Updated from an older installed version or fresh install:**
fresh install

## Logs / Screenshots
![screen shot 2018-07-06 at 03 40 12](https://user-images.githubusercontent.com/6325833/42368337-c4e710fe-80d4-11e8-9a3a-9b46660f1362.jpg)

**Comment by thejohnha** [comment]
I commented out the checker and tried to install on 16.04, but it failed later on: https://hastebin.com/vigodeluwi.scala

**Comment by enoch85** [comment]
You can't run Ubuntu 16.04, it must be 18.04.

**Comment by thejohnha** [comment]
@enoch85 I tested on 18.04 also. Same result. Please advise - thank you.

**Comment by enoch85** [comment]
It works for me on VMware with Ubuntu Server 18.04, don't know about Proxmox since I didn't test. 

You could try to find the cause and send a PR, I'll be happy to review it. :)

**Comment by thejohnha** [comment]
I believe it's line 18 in lib.sh. Here are same experiments:

```
root@bionic:~# uname -v | grep -ic "Ubuntu"
0
root@bionic:~# uname -v
#1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200)
root@bionic:~# uname -a
Linux bionic 4.15.17-1-pve #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200) x86_64 x86_64 x86_64 GNU/Linux
root@bionic:~#
```

**Comment by thejohnha** [comment]
I tested on VMWare and there is a slight difference:

```
john@bionic:~$ uname -a
Linux bionic 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by enoch85** [comment]
> would provide compatibility?

Yes, that's correct. So please send a PR with an ELIF statement to cover both scenarios.

**Comment by thejohnha** [comment]
Daniel, thank you for helping me with this. I'm trying but struggling. I replaced the OS= line with the following (and variations to try to get it to work), but to no avail. Could you help?

```
if [ uname -a | grep -ic "bionic" ] || [ uname -v | grep -ic "Ubuntu" ]
then
    OS = 1
else
    OS = 0
fi
```

**Comment by thejohnha** [comment]
p.s. I noticed an error message also. Right after the `lshw OK` part, it says this:
`/dev/fd/63: line 29: route: command not found`

I found it can be resolved by installing the `net-tools` package.

**Comment by enoch85** [comment]
@thejohnha 

Try this:
```
if uname -v | grep -ic "bionic"
then
    OS=1
elif uname -v | grep -ic "Ubuntu"  
then 
    OS=1
fi
```

**Comment by enoch85** [comment]
I fixed it. :)

**Comment by thejohnha** [comment]
Cool - thank you so much Daniel! Although one thing I see:
`if uname -v | grep -ic "bionic"` should be replaced with 
`if uname -a | grep -ic "bionic"` for it to work.

Thanks again!!

**Comment by enoch85** [comment]
What does `uname -a` give you on Proxmox?

**Comment by thejohnha** [comment]
My message from a couple days ago has it ;-)

`Linux bionic 4.15.17-1-pve #1 SMP PVE 4.15.17-9 (Wed, 9 May 2018 13:31:43 +0200) x86_64 x86_64 x86_64 GNU/Linux`

Thank you Daniel! 👍

**Comment by enoch85** [comment]
Fixed

**Comment by thejohnha** [comment]
Thank you so much Daniel, you're the best! Thanks for all your hard work on this repo.  :-)

**Comment by thejohnha** [comment]
p.s. you got the net-tools item too, thank you!! :-)
