### ISSUE TITLE
mod_status reachable from "outside" local network

### ISSUE THREAD

**Issue by burningjoe** [nextcloud/vm#58]
## Steps to reproduce
1. Let VM run it's installation scripts
2. Open https://foo.bar/server-status from outside the local network

## Expected behaviour
The server status shouldn't be reachable from outside the local network.

## Actual behaviour
Anybody can reach the stats from the internet, which leads to possible security risks

## Server configuration

**Server version:** Ubuntu 16.04.1, Nextcloud 10.0.1

**VM version** Last updated: 2016-09-29

**Updated from an older installed version or fresh install:**
fresh install

My /etc/apache2/mods-enabled/status.conf works, when I add the following lines:
```
                Deny from all
                Allow from 192.168.1.0/24
                #Require local
                #Require ip 192.0.2.0/24
```
It's not a solution for everybody of course, as the IP-range could differ.

**Comment by enoch85** [comment]
@burningjoe Thanks for your report!

Do you mean status.php as in https://cloud.techandme.se/status.php ?

**Comment by burningjoe** [comment]
@enoch85 No, like https://cloud.techandme.se/server-status

**Comment by enoch85** [comment]
WOW, didn't know that. Will fix this asap. 

Thanks!

**Comment by enoch85** [comment]
@LukasReschke Does this come from the Server Status app in Nextcloud? Is it safe to leave as is, or should an Apache rule block it?

**Comment by burningjoe** [comment]
@enoch85 Sorry for spamming. :-)
The module is enabled by default when installing Ubuntu with apache2. You could also run `sudo a2dismod status` and restart Apache to simply disable the module completely. But I don't know if anything else is depending on the status.

**Comment by enoch85** [comment]
@burningjoe I disabled it. there is no use for it afaik in Nextcloud.

Thanks for letting me know. :)
