### ISSUE TITLE
Unable to Upgrade to Nextcloud 13 - SSL Certificate Expired

### ISSUE THREAD

**Issue by ZaxLofful** [nextcloud/vm#582]
I am unable to upgrade to Nextcloud 13 due to an SSL error. I have done the upgrade process on other Nextcloud VMs, but as of today I am unable complete the process.

I am currently using Nextcloud 12.0.3, I updated my "update.sh" script to the newest version, but when I run the script I get an SSL expired error.

I have run the script three times now and fear I will not be able to update to the latest version.

#### Installation log (command output)
```
Nextcloud Updater - version: v12.0.0

Current version is 12.0.3.

Update to Nextcloud 13.0.4 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/next
cloud-13.0.4.zip

Updater run in non-interactive mode.

Start update

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Enable maintenance mode
[✔] Create backup
[✘] Downloading failed
Curl error: SSL certificate problem: certificate has expired

Update failed. To resume or retry just execute the updater again.
Creating possible missing Directories
chmod Files and Directories
chown Directories
chmod/chown .htaccess
Nextcloud is in maintenance mode - no app have been loaded

Maintenance mode disable
```

## Network
**Static IP Address**

**Is port 80 and/or 443 open?** yes

**VM version**  Released version (OVA)

#### Screenshots
![Image of Error](https://i.imgur.com/m0nR20Y.png)

**Comment by JSoko** [comment]
Should be fixed, the nextcloud download certificate was outdated...

https://help.nextcloud.com/t/ssl-certificate-expired-of-https-download-nextcloud-com/18786
