### ISSUE TITLE
сannot create directory ‘/var/run/rabbitmq’: Permission denied

### ISSUE THREAD

**Issue by setar** [nextcloud/vm#583]
Problem : docker onlyoffice not autostart in nextcloud vm (with 4 Core /4 GB RAM)

fix:
```
# docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                             NAMES
d8a9531c5fc5        onlyoffice/documentserver   "/bin/sh -c 'bash -C…"   3 days ago          Up 3 days           443/tcp, 127.0.0.3:9090->80/tcp   loving_swirles

# docker logs d8a9531c5fc5
found errors: 
сannot create directory ‘/var/run/rabbitmq’: Permission denied

# docker exec -it d8a9531c5fc5 bash
root@d8a9531c5fc5:/# chmod 777 /run
Ctrl^d

# docker restart d8a9531c5fc5
```

**Comment by enoch85** [comment]
@setar To me this is an error in the docker container and most likley a temporary one.

As we don't maintain the docker-container there isn't much I can do. Both Collabora and Onlyoffice are working here.

Maybe you get more valuble information in this thread: https://forums.docker.com/t/docker-exec-it-bin-bash-dont-work/33531/2
