### ISSUE TITLE
how to do dns trial with letsencrypt script

### ISSUE THREAD

**Issue by Jagsta2121** [nextcloud/vm#584]
how do i specify a dns trial with the letsencrypt script?

**Comment by enoch85** [comment]
What do you mean? Just follow the instructions given by Lets Encrypt. If I'm not remembering wrong, you need to add a TXT record in your DNS.

**Comment by Jagsta2121** [comment]
the only option the script gives is the one that requires port 80 and 443 open. i am unable to forward port 80 so i need to use the dns trial. does the script support that? i have tried setting a proffered challenge but it still does the regular trial. i would really prefer to use the script as i have no idea how to setup the certs manually.

**Comment by enoch85** [comment]
It's designed to handle DNS validations. So yes it's supported. Have you tried to run the script at all?

**Comment by Jagsta2121** [comment]
after the "Important! Please read this:" page I press yes to continue. it asks if i have forwarded port 80+443 if i say no it closes. if i press yes and enter my domain it starts doing the normal test for 3 tries before giving up.

**Comment by enoch85** [comment]
Aah ok, but you need those ports to be open to serve SSL anyway. So why not just open them?

You could also comment out the checks in the script, and then run it again.

**Comment by Jagsta2121** [comment]
for some reason when i ran it. it decided to do dns trial

**Comment by enoch85** [comment]
>  some reason when i ran it

It's not for some reason, it's the logic. :)

Glad it worked!
