### ISSUE TITLE
broke nextcloud vm with startup script :-/

### ISSUE THREAD

**Issue by fgrosswig** [nextcloud/vm#586]
How can i recover the nextcloud ? I have files and storage on smb but the issue turned as  soon i wanted to renew the certificate which fails of conecting issue :-/

What are the steps to be taken to recover the whole nextcloud?

Thank you.

**Comment by fgrosswig** [comment]
ok solved ... sites where under 

>  /etc/apache2/sites-available/
so enabled them manually since letsencrypt revoked the renewal of the rate limit.

**Comment by enoch85** [comment]
To renew your certs just run `certbot-renew`, or download [this](https://raw.githubusercontent.com/nextcloud/vm/master/lets-encrypt/activate-ssl.sh) script and run it with `sudo bash`.

**Comment by fgrosswig** [comment]
hm getting the following error:

> Failed authorization procedure. srvnextcloud.dom.de (tls-sni-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Error getting validation data

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: srvnextcloud.dom.de
   Type:   connection
   Detail: Error getting validation data

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided

have setup a haproxy to route by tls-sni to the server directly so i am not sure what the problems are to renew the certificate even the server is accessible from the outside.

**Comment by enoch85** [comment]
Run the script again then as I wrote in the previous post.

**Comment by fgrosswig** [comment]
now it runs through after a second attemp.

> Saving debug log to /var/log/letsencrypt/letsencrypt.log
>Plugins selected: Authenticator webroot, Installer None
>Renewing an existing certificate
>Performing the following challenges:
>http-01 challenge for srvnextcloud.dom.de
>Using the webroot path /var/www/nextcloud for all unmatched domains.
>Waiting for verification...
>Cleaning up challenges

>IMPORTANT NOTES:
> Congratulations! Your certificate and chain have been saved at:
>   /etc/letsencrypt/live/srvnextcloud.dom.de/fullchain.pem
>   Your key file has been saved at:
>   /etc/letsencrypt/live/srvnextcloud.dom.de/privkey.pem
>   Your cert will expire on 2018-10-30. To obtain a new or tweaked
>   version of this certificate in the future, simply run certbot
>   again. To non-interactively renew *all* of your certificates, run
>   "certbot renew"
> - If you like Certbot, please consider supporting our work by:
>
>   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
>   Donating to EFF:                    https://eff.org/donate-le
>
>Generating DSA parameters, 4096 bit long prime
>.....+........+...........+..............+...+.......+............+.......+............+....................+...+++++++++++++++++++++++>++++++++++++++++++++++++++++*
>....+...+..........+.+..+........+.+......................+.+............+..+++++++++++++++++++++++++++++++++++++++++++++++++++*
>We will now test that everything is OK
>Press any key to continue...
>Enabling site srvnextcloud.dom.de.
>To activate the new configuration, you need to run:
>  systemctl reload apache2
>Site nextcloud_ssl_domain_self_signed disabled.
>To activate the new configuration, you need to run:
>  systemctl reload apache2
>Site nextcloud_http_domain_self_signed disabled.
>To activate the new configuration, you need to run:
>  systemctl reload apache2
>Site 000-default already disabled
>Setting hostname to srvnextcloud.dom.de...

**Comment by enoch85** [comment]
Great!
