### ISSUE TITLE
Login issue on Webpage (not on CLI)

### ISSUE THREAD

**Issue by ferengie** [nextcloud/vm#589]
Hello

## Steps to reproduce
1. Version: Last updated: 2018-06-27. Version: 13.0.4
2. installation running on ESXi 
3. changing ncadmin Password on CLI possible 
4. login on the webpage not possible "wrong password"

I can login the vm on ESX and can change the password there, i tried complex passwords with special characters and it worked.
On my client I tried to login via HTTPS, the logon page is loading correct.
When I try to login with the ncadmin I get the error message "wrong password"
I checked the language settings of the keyboard, they are the same.

Do you have an idea?

regards 
Ferengie

**Comment by ferengie** [comment]
additional info: ssh also works, but no webGUI

**Comment by enoch85** [comment]
I think you typed the wrong password twice when you were prompted to change it during the setup script.

If not, then `occ` is broken which seems highly unlikely.

This is the line that changes the password: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L386

**Comment by enoch85** [comment]
Just tested and everything works as expected.
