### ISSUE TITLE
php-smbclient error during installation

### ISSUE THREAD

**Issue by ridgid13579** [nextcloud/vm#590]
Hello, I'm getting a php-smbclient error which lands up terminating the install. I'm running a fresh install of Ubuntu Server 18.04 every time I've tried to install it, in a ProxMox VE 5.2 vm. I've tried multiple new vms and it doesn't seem to work.

## Steps to reproduce
1.  wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
2. sudo bash nextcloud_install_production.sh
3. Errors out at the php side (see screenshots)

## Expected behaviour
It should install fine and the installation should just continue

## Actual behaviour
Error (see screenshots)

## Server configuration
**VM version** (Scripted install from master **OR** Released version)
Scripted install from master
**Updated from an older installed version or fresh install:**
Fresh Install
#### Screenshots
https://imgur.com/v7p4fQ5.png

Any ideas on what may be causing this error?
Thank you!

**Comment by enoch85** [comment]
@Ark74 What do you think, is https://github.com/nextcloud/vm/issues/585 related?

**Comment by Ark74** [comment]
Yep, that's the one :nerd_face:

**Comment by enoch85** [comment]
Hmm, seems that some vendors (like Proxmox) have a different image from the original. Or no?

**Comment by ridgid13579** [comment]
Hey @enoch85 if you're talking about the Ubuntu server Image on Proxmox, no, I manually uploaded the image which was downloaded directly from Ubuntu's website.

https://www.ubuntu.com/download/server/thank-you?version=18.04.1&architecture=amd64

It's 18.04.1, maybe the .1 has it removed? I'll try what he did in #585 though.

Thanks

**Comment by enoch85** [comment]
Aah, you need the alternative image, that's why it works for me and not you.

So, please try with that instead and let me know. I've installed Nextcloud about 15 times today without any issues.

**Comment by enoch85** [comment]
This is the repo I'm talking about: http://cdimage.ubuntu.com/releases/18.04/release/ and this is to be specific: http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.1-server-amd64.iso

**Comment by Ark74** [comment]
Maybe adding this section to lib & install production could close  #585 & #590;

```
lib.sh
UNIV="$(apt-cache policy | grep http | awk '{print $3}' | grep universe | head -n 1 | cut -d\/ -f 2)"
check_universe() {
if [ "$UNIV" = "universe" ] ; then
	echo "Seems that required repositories are ok."
else
	echo "Adding required repo (universe)."
	add-apt-repository universe
fi
}

nextcloud_install_production.sh

check_universe
```

Cheers!

**Comment by enoch85** [comment]
@Ark74 Will you make a PR please? I'm busy with PHP-FPM right now.
