### ISSUE TITLE
Disable HTTP/2

### ISSUE THREAD

**Issue by tiagoefreitas** [nextcloud/vm#592]
Hi,

I installed with HTTP/2, now I would like to disable it without reinstalling everything.
I tried sudo a2dismod http2 but that breaks the proxy, can't access onlyoffice.
In apache conf there is a "IfModule http2_module" so it should not run with it disabled, not sure what else is breaking.
Maybe make a script to enable/disable it?

Thanks

**Comment by enoch85** [comment]
Revert everything from here: https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L374-L401

I will not make a script to disable it. You are warned that some things may break, and if you still install it it's up to you. That's why it's made an option and not installed per default.

**Comment by tiagoefreitas** [comment]
Ok will test today.

I am running in a vmware vps but I'm not managing the vms myself. 
Would there be any issues with running this bare metal in a dedicated machine? I see you added a script to detect a second disk in /dev/sdb, so if not a vm it would need to be a physical disk right.

**Comment by enoch85** [comment]
Do you have shell access? If yes, then you can just log in and revert the changes from the link I posted.

No, the scripts can be run on any server, laptop, or computer that has Ubuntu 18.04 Server installed. A VM is just a virtual server and behaves in the same way as a bare metal server would do, with a few differences in setup.

And yes, it would work with a physical disk, in the same way as a VM has a virtual disk, those are the same. You could even use a USB stick, but not recommended. As long as it's /dev/sdb everything will work. It would even work without a second disk, but then you wouldn't benefit from ZFS and a seperata partition for DATA, which is highly recommended.
