### ISSUE TITLE
lowest_compatible_nc results in "/dev/fd/63: line 4: [: : integer expression expected"

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#596]
This line I think: https://github.com/nextcloud/vm/blob/master/lib.sh#L628

Looking at it with -x I get this:

```
+ '[' '' -lt 13 ']'
test.sh: line 4: [: : integer expression expected
+ NC_UPDATE=1
+ . /dev/fd/63
```

**Comment by Ark74** [comment]
Maybe using sort as described here could be of use.
https://stackoverflow.com/questions/16989598/bash-comparing-version-numbers/24067243

**Comment by enoch85** [comment]
Hmm, no the fix is to add `NC_UPDATE=1` everywhere were `CURRENTVERSION` is used, which is used by the `lowest_compatible()`

**Comment by Ark74** [comment]
Ohh, ok then.
I miss understood the 

`integer expression expected`

output, my bad.

**Comment by enoch85** [comment]
This is now fixed.
