### ISSUE TITLE
Ran the update script and now everything is deleted except default ncadmin profile, password, and data are intact...

### ISSUE THREAD

**Issue by YaTiCo** [nextcloud/vm#60]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Server version:** (see your admin page)

**VM version**

**Updated from an older installed version or fresh install:**

#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your Nextcloud.log file here
```

**Comment by enoch85** [comment]
@YaTiCo We need more information that that to be able to help you. Please fill in the issue templat, otherwise we can't help you.

Thanks!

**Comment by enoch85** [comment]
@YaTiCo Ping!

**Comment by enoch85** [comment]
@YaTiCo Still need your answer on this.

**Comment by enoch85** [comment]
This is not the behaviour of the current update script. Please reopen if it still exists after running `sudo bash /var/scripts/update.sh`
