### ISSUE TITLE
elastic search generated password contains invalid characters for http://user:password@host uri

### ISSUE THREAD

**Issue by dpavlin** [nextcloud/vm#600]
It seems that instalation plugin for elasticsearch generates nice strong password with special characters.
However, some of those characters (semicolumn for example) is not valid within password when used in
form http://login:password@elasticsearch which nextcloud uses. I would recommend to generate password without special characters.

## Steps to reproduce
1. Install VM and elasticsearch
2. try re-indexing or searching.

## Expected behaviour
Search should work

## Actual behaviour
If you are unlucky, generated password won't work because of special characters

## Server configuration

**Server version:** (see your admin page)
13.0.4

**VM version** (Scripted install from master **OR** Released version)
Released

**Updated from an older installed version or fresh install:**
fresh

## Network
**Do you use DHCP?**
no
**Is port 80 and/or 443 open?**
yes

#### Log file (/var/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
`head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 ; echo ''` would fix that. 

cc @Ark74

**Comment by enoch85** [comment]
Or this, which is cleaner: `openssl rand -hex 20`

**Comment by enoch85** [comment]
Fixed, removed the special characters.
