### ISSUE TITLE
Error when installing fail2ban

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#616]
```
find: ‘/proc/4650/task/4650/net’: Invalid argument
find: ‘/proc/4650/net’: Invalid argument
Installing Fail2ban...
Reading package lists... Done
```

**Comment by tiagoefreitas** [comment]
Wasn't this working yesterday? Will wait for fix before reinstalling again, or I can install without fail2ban and test it after on top of current install.

**Comment by enoch85** [comment]
This is not an error anymore. Was just a temporary glitch.
