### ISSUE TITLE
Improve by sharing with NextCloudPi

### ISSUE THREAD

**Issue by tiagoefreitas** [nextcloud/vm#619]
I just found out NextCloudPi, it works for Debian x86 now and has so many improvements.
However since it started as a ARM script and is meant for low-spec boards, it doesn't have ZFS or Onlyoffice, otherwise I would use it.

It makes sense for both projects to share the common bits as much as possible, and a common base would be ideal but at least cross-polinating :)

One example is modsecurity improvements and config:
https://ownyourbits.com/2017/03/23/modsecurity-web-application-firewall-for-nextcloud/

But there are many others:
https://ownyourbits.com/nextcloudpi/
https://github.com/nextcloud/nextcloudpi

web admin interface
backup and restore
scheduled rsync
etc

**Comment by enoch85** [comment]
@tiagoefreitas The two projects do the the same thing - install Nextcloud, but with different purposes. The code base are way to different to merge the projects together as one. That would mean that we would have to rewrite all the code, or @nachoparker will have to do it.

I know about the we-interface which I think is cool, but I didn't have time to look at it yet.

Other than that, we already provide modsecurity, and we do backup Nextcloud before every upgrade. We could do it with snapshots as in NextcluodPi, but it's kind of purpose less as the data is stored on a separate mount, and most often you don't backup the guest system when using a VM - you do the backups with Veeam or similar, which also would backup the disk for data in that case.

Regarding Rsync, many of our users are SME (Small and Medium Enterprises) and they often have their own backup solution, like Veeam as I mentioned before. The NextcloudPi is more towards the home user, hence Raspberry Pi.

I do agree that we can implement the same stuff. Actually, we already did as @nachoparker took inspiration from the Nextcloud VM, and I sometimes look for inspiration i his repo.

If you are willing to put some time into making the scripts, or modify existing ones, then you're very welcome to do so.

**Comment by nachoparker** [comment]
I would be happy to mix and merge any common parts that we might have. This way we would be sharing the burden of maintenance. Right now we are integrated in Armbian, and [in the process](https://github.com/Fourdee/DietPi/issues/1778) of doing the same with Dietpi.

BTW, the way NCP backups work is
- auto-backup with data included, or
- auto-backup without datadir

, and on top of that
- BTRFS autosnapshots of the datadir, which is a BTRFS subvolume.

This means that we don't snapshot the whole system. A typical usage would be

- autobackup without datadir (fast) to a second drive.
- snapshot of datadir, sync'ed to a second drive or machine through SSH with [btrfs-sync](https://ownyourbits.com/2018/03/09/easy-sync-of-btrfs-snapshots-with-btrfs-sync/).

This way we have a second copy of everything (instance + data) with minimal downtime.

**Comment by enoch85** [comment]
@nachoparker Just installed NextcloudPi on a friends rPI3, I must say I'm impressed with the /activate stuff, and the wizard. 

Will you attend the conf? I'm thinking we could sit down and have a chat about it. Would love to implement something similar in the VM.

**Comment by nachoparker** [comment]
Hi @enoch85 

I would love to have a chat. Unfortunately I just moved to the US so I won't be able to make it to the conference this year.

In any case, I am open to cooperation!!  The activation page is quite simple, and uses the Rest API provided by ncp-web. Ultimately you are launching scripts in `etc/ncp-config.d`.

Also [we have been wanting to](https://github.com/nextcloud/nextcloudpi/issues/380) improve ncp-web for a while, maybe it could be an opportunity to bring whatever features you are interested in or add some new ones.

**Comment by enoch85** [comment]
We will develop out own GUI soon and since me and @nachoparker talked about stuff related to this topic already I feel we can close this issue.
