### ISSUE TITLE
Update exits because "no need to upgrade"

### ISSUE THREAD

**Issue by nasi87** [nextcloud/vm#62]
Hello!

For me the update script aborts because it seems to think 9.0.53 is newer than 10.0.1

## Steps to reproduce
1. sudo -i
2. cd /var/scripts
3. wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_update.sh
4. rename and chmod +x
5. ./nextcloud_update.sh

## Expected behaviour
update 9.0.53 to 10.0.1

## Actual behaviour
Aptitude full-upgrade runs without problems but then script exits with:

_Script exists
Checking latest released version on the Nextcloud download server and if it's possible to download...
SUCCESS!
Latest version is: 10.0.1. Current version is: 9.0.53.
No need to upgrade, this script will exit..._

## Server configuration

**Server version:** 
9.0.53

**VM version**
2016-07-27

**Updated from an older installed version or fresh install:**
fresh install, first try to update to NC10

**Comment by enoch85** [comment]
@nasi87 Thanks for your report!

What happens if you change [this line](https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L67) to "<" instead if ">"?

Also please always use the update.sh and not the nextcloud_update.sh.

**Comment by nasi87** [comment]
You're welcome.

Sorry I did not mention that I used update.sh at first what didn't work - then I tried nextcloud_update.sh itself.

So I changed to if [[ "$NCVERSION" < "$CURRENTVERSION" ]] and now it seems to work:

_Checking latest released version on the Nextcloud download server and if it's possible to download...
SUCCESS!
Latest version is: 10.0.1. Current version is: 9.0.53.
New version available! Upgrade continues...
Backing up files and upgrading to Nextcloud 10.0.1 in 10 seconds...
Press CTRL+C to abort._


It's failing with "Exception: files can't be disabled.
Update failed" but that's a completely different problem I'll investigate later this week...


Thanks for your quick help anyway!

**Comment by enoch85** [comment]
@nasi87 Thanks! I'll try to see if there is a better way to compare versions. Please try ti run the script again after it is upgraded to see if it tries to upgrade even if the version numbers are the same.

Regarding the other bug, I've heard about it, but that's really a server issue: https://github.com/nextcloud/server/

**Comment by nasi87** [comment]
@enoch85 I performed upgrade manually. Modified nextcloud_update.sh now seems to behave as it should:

_Checking latest released version on the Nextcloud download server and if it's possible to download...
SUCCESS!
Latest version is: 10.0.1. Current version is: 10.0.1.
No need to upgrade, this script will exit..._

**Comment by enoch85** [comment]
So what did you change? Did you change it the way I told you, or did you do something else? @nasi87

**Comment by enoch85** [comment]
This is fixed in https://github.com/nextcloud/vm/commit/20932d3d53d1d94272302792585894634059c586
