### ISSUE TITLE
Configuring openssh-server prompt during instalation

### ISSUE THREAD

**Issue by tiagoefreitas** [nextcloud/vm#623]
During the startup script, I chose webmin, and after I select the timezone I get this:

──────────────────────────────────────────────────────────────┤ Configuring openssh-server ├──────────────────────────────────────────────────────────────┐
          │ A new version (/tmp/fileDzCmLq) of configuration file /etc/ssh/sshd_config is available, but the version installed currently has been locally modified.  │ 
          │                                                                                                                                                          │ 
          │ What do you want to do about modified configuration file sshd_config?                                                                                    │ 
          │                                                                                                                                                          │ 
          │                                                   install the package maintainer's version                                                               │ 
          │                                                   keep the local version currently installed                                                             │ 
          │                                                   show the differences between the versions                                                              │ 
          │                                                   show a side-by-side difference between the versions                                                    │ 
          │                                                   show a 3-way difference between available versions                                                     │ 
          │                                                   do a 3-way merge between available versions                                                            │ 
          │                                                   start a new shell to examine the situation                                                             │ 
          │                                                                                                                                                          │ 
          │                                                                                                                                                          │ 
          │                                                                          <Ok>                                                                            │ 
          │                                                                                                                                                          │ 
          └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by tiagoefreitas** [comment]
Also after installing everything onlyoffice is not working.

**Comment by enoch85** [comment]
> │ A new version (/tmp/fileDzCmLq) of configuration file /etc/ssh/sshd_config is available, but the version installed currently has been locally modified. 

There's your answer. It installed a new version and the default config changed between versions. Normally the best thing to do is to keep the currently installed if you're on a VPS. But, if you didn't touch the file and you know for sure that nothing will break by updating the defaults, then that's the best option.

> Also after installing everything I had to reboot again for onlyoffice to work.

Well, it even says in the description that that may be needed: https://github.com/nextcloud/vm/blob/master/apps/onlyoffice.sh#L217
