### ISSUE TITLE
Failed to complete install, password fails for db login on XCP-ng Center (Nigtly build)

### ISSUE THREAD

**Issue by HippiekillerOG** [nextcloud/vm#626]
Hey guys, I've been fighting this install for a little while now and I've just given up. I may be just too tired now (1:41am). To get to this point, I had to edit config.php and fix the datadir to point to /var/www/nextcloud/data. Additionally, I had some permission issues and also had to create the .ocdata file. I over came those issues, and got through the whole install except the very end. Does anyone have an idea? Thanks!

 Steps to reproduce
1. Install latest version on XCP-ng using XCP-ng Center

Expected behaviour
Unknown because technically XCP-ng (xenserver) is not supported

Actual behaviour
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "ncadmin"

Server configuration:

Server version: 13.0.5
Installed from OVA from https://www.techandme.se/nextcloud-vm/

Network:
DHCP
Ports 80 and 443 are both open

Logs / Screenshots

#### Log file (/mnt/ncdata/nextcloud.log)
```
Log is  0 bytes
```

#### Installation log (command output)
```
https://hastebin.com/olaleloyav.shell
```

#### Screenshoots
https://imgur.com/SMHgQzL

**Comment by enoch85** [comment]
> I had to edit config.php and fix the datadir to point to /var/www/nextcloud/data

The datadir is mounted as ZFS in /mnt/ncdata, you can't just move it around as you like without moving the ZFS mountpoint.

Also the other stuff you did shouldn't be necessary. 

Please download the [latest release](https://github.com/nextcloud/vm/releases/tag/13.0.5) and try again. https://github.com/nextcloud/vm/issues/622#issuecomment-412368024

Thanks!

**Comment by HippiekillerOG** [comment]
https://youtu.be/YHrmbVy5Vdg

Here's a video attempting to use XCP-ng. You can pretty much skip 2:10 - 8:50. It took that long to spin up the VM. I'm not too sure what the initial error XCP spits out, but it doesn't stop the process.

You will be able to see what led me to mess with the .ocdata and permissions

I'm not expecting anything from you guys really. Afterall, it's not VirtualBox or VMware, it's a brand new open source citrix xenserver. I was just crossing my fingers and hoping for the best. However, if you have an idea on how to get this over the hump, that would be great!

Thanks for playing!

**Comment by enoch85** [comment]
Without looking at the whole video I can say that it would be much easier for you to use the scripts directly instead: https://github.com/nextcloud/vm#build-your-own-vm-or-install-on-a-vps

I also noticed now that you are using a Nightly build in production(!) Don't do that. :) 

If the scripts doesn't work then try using a stable release instead.

Maybe @zalonic could help you better than me as I know that they use Xen in production.

**Comment by HippiekillerOG** [comment]
Thank you both for your time and awesome support. I just switched to the nightlies to try some things but I'm going to revert to the stable and see if that error goes away.

XCP support would be awesome! Just sayin! Lol.

Thanks so much for the schooling as to the differences with the naming conventions.

I look forward to the future of nextcloud!

**Comment by enoch85** [comment]
@zalonic Please send me an email so that we can discuss the future. :) And thanks for confirming.

@HippiekillerOG Good luck in your endeavors. :)
