### ISSUE TITLE
Installation freezes during "Installing issuetemplate"

### ISSUE THREAD

**Issue by BonziBuddyMonkey** [nextcloud/vm#627]
Thank you!
-->
## Steps to reproduce
1. wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
2. sudo bash nextcloud_install_production.sh
3. Follow the steps on screen. (Not using root) 
4. Created new user
5. Disk check
6. Nextcloud is installed
7. installing issuetemplate
8. Ubuntu freezes and I have to forcefully shut it down in esxi.

## Expected behaviour
It should continue, but it dosnt. I have succesfully installed it on hyper v on an other PC.

## Actual behaviour
It freezes and has to be forcefully shutdown.

## Server configuration
HP ProLiant DL180 G6
CPU	12 CPUs x Intel(R) Xeon(R) CPU E5645 @ 2.40GHz
Memory	63.99 GB
8TB  running in raid 10.

**Server version:** (see your admin page)
Image profile	ESXi-6.5.0-20170404001-standard (VMware, Inc.)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Installed through ESXI using Ubuntu-18.04.1-live-server-amd64.iso
## Network
Static Ip

**Is port 80 and/or 443 open?**
both

#### Screenshoots
![image](https://user-images.githubusercontent.com/42281490/44042665-214ccb26-9f21-11e8-9c77-af260fa5d273.png)

**Comment by enoch85** [comment]
Thanks for posting your issue!

Yup, I've seen that as well. It seems like a timeout happens to the App Store, maybe because of weak servers, or temporarily high load, most likely the latter.

It works again after some time. What happens if you wait for like 20 minutes?

In any case, this is not a VM error per say as the logic that's used is based on the `occ` command: `occ app install: [app]`. So if you want to report it in the proper channels I would do it in nextcloud/server and refer to the `occ` command that's used.

**Comment by BonziBuddyMonkey** [comment]
Thank You for your very quick answer! 

When you say it happens, maybe because of weak servers. Is that due to my server or the remote download server? ive given the vm 6gb ram and 4 cores. 

I have not tried waiting for 20 minutes, but I do suspect, it will not work unfortunately.

I am going to report it, in the right channel. Thank you.

**Comment by enoch85** [comment]
> I am going to report it, in the right channel. Thank you.

The lines I'm referring to is here](https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L326-L327) and the function is [here](https://github.com/nextcloud/vm/blob/master/lib.sh#L527-L541).

> Is that due to my server or the remote download server?

The remote download server in this case.
