### ISSUE TITLE
update.sh-> Update failed

### ISSUE THREAD

**Issue by sebsom** [nextcloud/vm#631]
Hi,
after running the update.sh I got an issue telling me to report here. Anyway I have no access to my nextcloud via browser. Any Ideas?

Thanks!

`root@XXX:/var/www/nextcloud# sudo bash /var/scripts/update.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  python3-ndg-httpsclient
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  linux-cloud-tools-4.15.0-32 linux-cloud-tools-4.15.0-32-generic
  linux-headers-4.15.0-32 linux-headers-4.15.0-32-generic
  linux-image-4.15.0-32-generic linux-modules-4.15.0-32-generic
  linux-modules-extra-4.15.0-32-generic linux-tools-4.15.0-32
  linux-tools-4.15.0-32-generic
The following packages will be upgraded:
  linux-cloud-tools-virtual linux-generic linux-headers-generic
  linux-headers-virtual linux-image-extra-virtual linux-image-generic
  linux-image-virtual linux-tools-virtual linux-virtual
9 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 67.2 MB of archives.
After this operation, 342 MB of additional disk space will be used.
Get:1 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-cloud-tools-4.15.0-32 amd64 4.15.0-32.35 [44.7 kB]
Get:2 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-cloud-tools-4.15.0-32-generic amd64 4.15.0-32.35 [1,860 B]
Get:3 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-cloud-tools-virtual amd64 4.15.0.32.34 [2,576 B]
Get:4 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-image-extra-virtual amd64 4.15.0.32.34 [1,864 B]
Get:5 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-modules-4.15.0-32-generic amd64 4.15.0-32.35 [13.0 MB]
Get:6 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-image-4.15.0-32-generic amd64 4.15.0-32.35 [7,887 kB]
Get:7 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-modules-extra-4.15.0-32-generic amd64 4.15.0-32.35 [32.7 MB]
Get:8 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-generic amd64 4.15.0.32.34 [1,860 B]
Get:9 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-image-generic amd64 4.15.0.32.34 [2,568 B]
Get:10 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-virtual amd64 4.15.0.32.34 [1,856 B]
Get:11 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-image-virtual amd64 4.15.0.32.34 [2,552 B]
Get:12 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-headers-virtual amd64 4.15.0.32.34 [1,840 B]
Get:13 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-headers-4.15.0-32 all 4.15.0-32.35 [11.0 MB]
Get:14 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-headers-4.15.0-32-generic amd64 4.15.0-32.35 [1,090 kB]
Get:15 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-headers-generic amd64 4.15.0.32.34 [2,532 B]
Get:16 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-tools-4.15.0-32 amd64 4.15.0-32.35 [1,452 kB]
Get:17 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-tools-4.15.0-32-generic amd64 4.15.0-32.35 [1,952 B]
Get:18 http://ny-mirrors.evowise.com/ubuntu bionic-updates/main amd64 linux-tools-virtual amd64 4.15.0.32.34 [2,552 B]
Fetched 67.2 MB in 10s (7,011 kB/s)
Selecting previously unselected package linux-cloud-tools-4.15.0-32.
(Reading database ... 160163 files and directories currently installed.)
Preparing to unpack .../00-linux-cloud-tools-4.15.0-32_4.15.0-32.35_amd64.deb ...
Unpacking linux-cloud-tools-4.15.0-32 (4.15.0-32.35) ...
Selecting previously unselected package linux-cloud-tools-4.15.0-32-generic.
Preparing to unpack .../01-linux-cloud-tools-4.15.0-32-generic_4.15.0-32.35_amd64.deb ...
Unpacking linux-cloud-tools-4.15.0-32-generic (4.15.0-32.35) ...
Preparing to unpack .../02-linux-cloud-tools-virtual_4.15.0.32.34_amd64.deb ...
Unpacking linux-cloud-tools-virtual (4.15.0.32.34) over (4.15.0.23.25) ...
Preparing to unpack .../03-linux-image-extra-virtual_4.15.0.32.34_amd64.deb ...
Unpacking linux-image-extra-virtual (4.15.0.32.34) over (4.15.0.23.25) ...
Selecting previously unselected package linux-modules-4.15.0-32-generic.
Preparing to unpack .../04-linux-modules-4.15.0-32-generic_4.15.0-32.35_amd64.deb ...
Unpacking linux-modules-4.15.0-32-generic (4.15.0-32.35) ...
Selecting previously unselected package linux-image-4.15.0-32-generic.
Preparing to unpack .../05-linux-image-4.15.0-32-generic_4.15.0-32.35_amd64.deb ...
Unpacking linux-image-4.15.0-32-generic (4.15.0-32.35) ...
Selecting previously unselected package linux-modules-extra-4.15.0-32-generic.
Preparing to unpack .../06-linux-modules-extra-4.15.0-32-generic_4.15.0-32.35_amd64.deb ...
Unpacking linux-modules-extra-4.15.0-32-generic (4.15.0-32.35) ...
Preparing to unpack .../07-linux-generic_4.15.0.32.34_amd64.deb ...
Unpacking linux-generic (4.15.0.32.34) over (4.15.0.23.25) ...
Preparing to unpack .../08-linux-image-generic_4.15.0.32.34_amd64.deb ...
Unpacking linux-image-generic (4.15.0.32.34) over (4.15.0.23.25) ...
Preparing to unpack .../09-linux-virtual_4.15.0.32.34_amd64.deb ...
Unpacking linux-virtual (4.15.0.32.34) over (4.15.0.23.25) ...
Preparing to unpack .../10-linux-image-virtual_4.15.0.32.34_amd64.deb ...
Unpacking linux-image-virtual (4.15.0.32.34) over (4.15.0.23.25) ...
Preparing to unpack .../11-linux-headers-virtual_4.15.0.32.34_amd64.deb ...
Unpacking linux-headers-virtual (4.15.0.32.34) over (4.15.0.23.25) ...
Selecting previously unselected package linux-headers-4.15.0-32.
Preparing to unpack .../12-linux-headers-4.15.0-32_4.15.0-32.35_all.deb ...
Unpacking linux-headers-4.15.0-32 (4.15.0-32.35) ...
Selecting previously unselected package linux-headers-4.15.0-32-generic.
Preparing to unpack .../13-linux-headers-4.15.0-32-generic_4.15.0-32.35_amd64.deb ...
Unpacking linux-headers-4.15.0-32-generic (4.15.0-32.35) ...
Preparing to unpack .../14-linux-headers-generic_4.15.0.32.34_amd64.deb ...
Unpacking linux-headers-generic (4.15.0.32.34) over (4.15.0.23.25) ...
Selecting previously unselected package linux-tools-4.15.0-32.
Preparing to unpack .../15-linux-tools-4.15.0-32_4.15.0-32.35_amd64.deb ...
Unpacking linux-tools-4.15.0-32 (4.15.0-32.35) ...
Selecting previously unselected package linux-tools-4.15.0-32-generic.
Preparing to unpack .../16-linux-tools-4.15.0-32-generic_4.15.0-32.35_amd64.deb ...
Unpacking linux-tools-4.15.0-32-generic (4.15.0-32.35) ...
Preparing to unpack .../17-linux-tools-virtual_4.15.0.32.34_amd64.deb ...
Unpacking linux-tools-virtual (4.15.0.32.34) over (4.15.0.23.25) ...
Setting up linux-tools-4.15.0-32 (4.15.0-32.35) ...
Setting up linux-cloud-tools-4.15.0-32 (4.15.0-32.35) ...
Setting up linux-cloud-tools-4.15.0-32-generic (4.15.0-32.35) ...
Setting up linux-modules-4.15.0-32-generic (4.15.0-32.35) ...
Setting up linux-headers-4.15.0-32 (4.15.0-32.35) ...
Setting up linux-image-4.15.0-32-generic (4.15.0-32.35) ...
I: /vmlinuz.old is now a symlink to boot/vmlinuz-4.15.0-23-generic
I: /initrd.img.old is now a symlink to boot/initrd.img-4.15.0-23-generic
I: /vmlinuz is now a symlink to boot/vmlinuz-4.15.0-32-generic
I: /initrd.img is now a symlink to boot/initrd.img-4.15.0-32-generic
Setting up linux-cloud-tools-virtual (4.15.0.32.34) ...
Setting up linux-tools-4.15.0-32-generic (4.15.0-32.35) ...
Setting up linux-headers-4.15.0-32-generic (4.15.0-32.35) ...
Setting up linux-modules-extra-4.15.0-32-generic (4.15.0-32.35) ...
Setting up linux-image-virtual (4.15.0.32.34) ...
Setting up linux-image-generic (4.15.0.32.34) ...
Setting up linux-tools-virtual (4.15.0.32.34) ...
Setting up linux-headers-generic (4.15.0.32.34) ...
Setting up linux-image-extra-virtual (4.15.0.32.34) ...
Setting up linux-headers-virtual (4.15.0.32.34) ...
Setting up linux-generic (4.15.0.32.34) ...
Setting up linux-virtual (4.15.0.32.34) ...
Processing triggers for linux-image-4.15.0-32-generic (4.15.0-32.35) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-4.15.0-32-generic
/etc/kernel/postinst.d/x-grub-legacy-ec2:
Searching for GRUB installation directory ... found: /boot/grub
Searching for default file ... found: /boot/grub/default
Testing for an existing GRUB menu.lst file ... found: /boot/grub/menu.lst
Searching for splash image ... none found, skipping ...
Found kernel: /boot/vmlinuz-4.15.0-23-generic
Found kernel: /boot/vmlinuz-4.15.0-20-generic
Found kernel: /boot/vmlinuz-4.15.0-32-generic
Found kernel: /boot/vmlinuz-4.15.0-23-generic
Found kernel: /boot/vmlinuz-4.15.0-20-generic
Replacing config file /run/grub/menu.lst with new version
Updating /boot/grub/menu.lst ... done

/etc/kernel/postinst.d/zz-update-grub:
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.15.0-32-generic
Found initrd image: /boot/initrd.img-4.15.0-32-generic
Found linux image: /boot/vmlinuz-4.15.0-23-generic
Found initrd image: /boot/initrd.img-4.15.0-23-generic
Found linux image: /boot/vmlinuz-4.15.0-20-generic
Found initrd image: /boot/initrd.img-4.15.0-20-generic
device-mapper: reload ioctl on osprober-linux-sdc1  failed: Device or resource busy
Command failed
done
Thu Aug 16 10:19:08 CEST 2018 : INFO:  Running on a terminal - (this script also supports running headless from crontab)

Thu Aug 16 10:19:08 CEST 2018 : INFO:  Updating netdata source from github...
Already up to date.
Thu Aug 16 10:19:10 CEST 2018 : INFO:  Nothing to be done! (use -f to force re-install)
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  linux-cloud-tools-4.15.0-20 linux-cloud-tools-4.15.0-20-generic
  linux-headers-4.15.0-20 linux-headers-4.15.0-20-generic
  linux-image-4.15.0-20-generic linux-modules-4.15.0-20-generic
  linux-modules-extra-4.15.0-20-generic linux-tools-4.15.0-20
  linux-tools-4.15.0-20-generic python3-ndg-httpsclient
0 upgraded, 0 newly installed, 10 to remove and 0 not upgraded.
After this operation, 342 MB disk space will be freed.
(Reading database ... 195807 files and directories currently installed.)
Removing linux-cloud-tools-4.15.0-20-generic (4.15.0-20.21) ...
Removing linux-cloud-tools-4.15.0-20 (4.15.0-20.21) ...
Removing linux-headers-4.15.0-20-generic (4.15.0-20.21) ...
Removing linux-headers-4.15.0-20 (4.15.0-20.21) ...
Removing linux-modules-extra-4.15.0-20-generic (4.15.0-20.21) ...
Removing linux-image-4.15.0-20-generic (4.15.0-20.21) ...
/etc/kernel/postrm.d/initramfs-tools:
update-initramfs: Deleting /boot/initrd.img-4.15.0-20-generic
/etc/kernel/postrm.d/x-grub-legacy-ec2:
Searching for GRUB installation directory ... found: /boot/grub
Searching for default file ... found: /boot/grub/default
Testing for an existing GRUB menu.lst file ... found: /boot/grub/menu.lst
Searching for splash image ... none found, skipping ...
Found kernel: /boot/vmlinuz-4.15.0-32-generic
Found kernel: /boot/vmlinuz-4.15.0-23-generic
Found kernel: /boot/vmlinuz-4.15.0-20-generic
Replacing config file /run/grub/menu.lst with new version
Found kernel: /boot/vmlinuz-4.15.0-32-generic
Found kernel: /boot/vmlinuz-4.15.0-23-generic
Replacing config file /run/grub/menu.lst with new version
Updating /boot/grub/menu.lst ... done

/etc/kernel/postrm.d/zz-update-grub:
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.15.0-32-generic
Found initrd image: /boot/initrd.img-4.15.0-32-generic
Found linux image: /boot/vmlinuz-4.15.0-23-generic
Found initrd image: /boot/initrd.img-4.15.0-23-generic
device-mapper: reload ioctl on osprober-linux-sdc1  failed: Device or resource busy
Command failed
done
Removing linux-modules-4.15.0-20-generic (4.15.0-20.21) ...
Removing linux-tools-4.15.0-20-generic (4.15.0-20.21) ...
Removing linux-tools-4.15.0-20 (4.15.0-20.21) ...
Removing python3-ndg-httpsclient (0.4.4-1) ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.15.0-32-generic
Found initrd image: /boot/initrd.img-4.15.0-32-generic
Found linux image: /boot/vmlinuz-4.15.0-23-generic
Found initrd image: /boot/initrd.img-4.15.0-23-generic
device-mapper: reload ioctl on osprober-linux-sdc1  failed: Device or resource busy
Command failed
done
Latest release is: 13.0.5. Current version is: 13.0.4.
New version available! Upgrade continues...
Checking latest released version on the Nextcloud download server and if it's possible to download...
nextcloud-13.0.5.ta 100%[===================>]  42.72M  6.63MB/s    in 6.5s
Backing up files and upgrading to Nextcloud 13.0.5 in 10 seconds...
Press CTRL+C to abort.
Doing pgdump of nextcloud_db...
Backing up data...

Backup OK!
gpg: key D75899B9A724937A: 8 signatures not checked due to missing keys
gpg: key D75899B9A724937A: "Nextcloud Security <security@nextcloud.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: Signature made Mon 23 Jul 2018 12:54:53 PM CEST
gpg:                using RSA key D75899B9A724937A
gpg: Good signature from "Nextcloud Security <security@nextcloud.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2880 6A87 8AE4 23A2 8372  792E D758 99B9 A724 937A
/var/www/nextcloud-13.0.5.tar.bz2 exists
/var/NCBACKUP/config/ exists
/var/NCBACKUP/apps/ exists
/var/NCBACKUP/themes/ exists

All files are backed up.
Maintenance mode enabled
Removing old Nextcloud instance in 5 seconds...
[/] Creating possible missing Directories
[-] chmod Files and Directories
[-] chown Directories
[|] chmod/chown .htaccess
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app calendar in appstore
Update app calendar from appstore
Checked for update of app "calendar" in appstore
Checking for update of app caniupdate in appstore
Update app caniupdate from appstore
Checked for update of app "caniupdate" in appstore
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore
Checking for update of app contacts in appstore
Update app contacts from appstore
Checked for update of app "contacts" in appstore
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore
Checking for update of app files in appstore
Checked for update of app "files" in appstore
Checking for update of app files_fulltextsearch in appstore
Update app files_fulltextsearch from appstore
Checked for update of app "files_fulltextsearch" in appstore
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app files_texteditor in appstore
Checked for update of app "files_texteditor" in appstore
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app fulltextsearch in appstore
Update app fulltextsearch from appstore
An unhandled exception has been thrown:
Error: Class 'OCA\FullTextSearch\AppInfo\Application' not found in /var/www/nextcloud/apps/fulltextsearch/lib/Settings/AdminSection.php:55
Stack trace:
#0 /var/www/nextcloud/lib/private/Settings/Manager.php(274): OCA\FullTextSearch\Settings\AdminSection->getID()
#1 /var/www/nextcloud/lib/private/Settings/Manager.php(236): OC\Settings\Manager->updateSection(Object(OCA\FullTextSearch\Settings\AdminSection), 'admin_sections')
#2 /var/www/nextcloud/lib/private/Settings/Manager.php(140): OC\Settings\Manager->setupSectionEntry('OCA\\FullTextSea...', 'admin')
#3 /var/www/nextcloud/lib/private/legacy/app.php(1061): OC\Settings\Manager->setupSettings(Array)
#4 /var/www/nextcloud/lib/private/Installer.php(199): OC_App::updateApp('fulltextsearch')
#5 /var/www/nextcloud/lib/private/Updater.php(473): OC\Installer->updateAppstoreApp('fulltextsearch')
#6 /var/www/nextcloud/lib/private/Updater.php(277): OC\Updater->upgradeAppStoreApps(Array)
#7 /var/www/nextcloud/lib/private/Updater.php(139): OC\Updater->doUpgrade('13.0.5.2', '13.0.4.0')
#8 /var/www/nextcloud/core/Command/Upgrade.php(270): OC\Updater->upgrade()
#9 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(264): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/console.php(90): OC\Console\Application->run()
#15 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#16 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ upgrade --no-app-disable failed
You have new mail in /var/mail/root
root@XXX:/var/www/nextcloud#`

**Comment by enoch85** [comment]
Hi @sebsom, thanks for your report.

```
An unhandled exception has been thrown:
Error: Class 'OCA\FullTextSearch\AppInfo\Application' not found in /var/www/nextcloud/apps/fulltextsearch/lib/Settings/AdminSection.php:55
Stack trace:
#0 /var/www/nextcloud/lib/private/Settings/Manager.php(274): OCA\FullTextSearch\Settings\AdminSection->getID()
#1 /var/www/nextcloud/lib/private/Settings/Manager.php(236): OC\Settings\Manager->updateSection(Object(OCA\FullTextSearch\Settings\AdminSection), 'admin_sections')
#2 /var/www/nextcloud/lib/private/Settings/Manager.php(140): OC\Settings\Manager->setupSectionEntry('OCA\FullTextSea...', 'admin')
#3 /var/www/nextcloud/lib/private/legacy/app.php(1061): OC\Settings\Manager->setupSettings(Array)
#4 /var/www/nextcloud/lib/private/Installer.php(199): OC_App::updateApp('fulltextsearch')
#5 /var/www/nextcloud/lib/private/Updater.php(473): OC\Installer->updateAppstoreApp('fulltextsearch')
#6 /var/www/nextcloud/lib/private/Updater.php(277): OC\Updater->upgradeAppStoreApps(Array)
#7 /var/www/nextcloud/lib/private/Updater.php(139): OC\Updater->doUpgrade('13.0.5.2', '13.0.4.0')
#8 /var/www/nextcloud/core/Command/Upgrade.php(270): OC\Updater->upgrade()
#9 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(264): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/console.php(90): OC\Console\Application->run()
#15 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#16 {main}Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ upgrade --no-app-disable failed
You have new mail in /var/mail/root
root@XXX:/var/www/nextcloud#`
```
Here's where the error happen, and it seems to have something to do with Full Text Search being updated.

Remember that the app itself still is in beta. Maybe @daita can answer this better than me?

**Comment by enoch85** [comment]
@sebsom Try to deactivate Full Text Search via the occ command: `sudo -u www-data php /var/www/nextcloud/occ app:disable [name of app]`

Then run `sudo -u www-data php /var/www/nextcloud/occ upgrade` again.

**Comment by enoch85** [comment]
@sebsom Please close this issue if deactivating Full Text search solved it.

**Comment by sebsom** [comment]
Sorry, I wasn't able to work on it till now. Deactivating full text search solved the problem.
Thanks for your help!

**Comment by enoch85** [comment]
@Ark74 FYI

**Comment by Ark74** [comment]
FTS got and update on their way to v1.0, maybe that's the reason.

**Comment by daita** [comment]
it is.
