### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by dnsinformatic** [nextcloud/vm#632]
After installing your VM (Ubuntu 18.04 ) on VirtualBox (Windows 10 host), I get a 500 error on login page (can't even login).

Tryed several times reinstalling the VM always with the same error...

Any clue on what's happening??

Best regards

**Comment by enoch85** [comment]
@dnsinformatic Do you have any logs? Please fill out the issue template with logs and everything included. 

I can't say anything with that little information.

**Comment by dnsinformatic** [comment]
Error lloading this URI: Could not load the source for https://dnscloud.dnsolutions.pt/index.php.
[Exception... "Component returned failure code: 0x80470002 (NS_BASE_STREAM_CLOSED) [nsIInputStream.available]"  nsresult: "0x80470002 (NS_BASE_STREAM_CLOSED)"  location: "JS frame :: resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js :: onResponse :: line 569"  data: no]
Stack: onResponse@resource://devtools/shared/base-loader.js -> resource://devtools/shared/DevToolsUtils.js:569:23
onStopRequest@resource://gre/modules/NetUtil.jsm:126:17
Line: 569, column: 0

**Comment by enoch85** [comment]
OK, that doesn't say much. Which log is that?

Can you give me the log from:
- Nextcloud
- Apache2 (error.log, other-vhosts.log, access.log)
- PHP-FPM

What are the step to reproduce? What did you do prior to getting this error?
