### ISSUE TITLE
Change onlyoffice port

### ISSUE THREAD

**Issue by tiagoefreitas** [nextcloud/vm#637]
Hi,

I wanted to change the ports of nextcloud and onlyoffice to 8080/444 and then configure a reverse proxy.

I changed the apache config files and nextcloud is working, but onlyoffice integration stops working.

Then I will probably have to disable ssl too?

Thanks

**Comment by tiagoefreitas** [comment]
Its working now, I had to change the Document Editing Service address in Nextcloud onlyoffice settings and add the port there.

**Comment by enoch85** [comment]
@tiagoefreitas Please only report bugs and issues here. Please use the [forum](https://help.nextcloud.com) for help or support.
