### ISSUE TITLE
install failed with - "Error: Could not download app issuetemplate"

### ISSUE THREAD

**Issue by ajayramaswamy** [nextcloud/vm#639]
## Steps to reproduce
1. install ubuntu-18.04.1 from http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.1-server-amd64.iso on a fedora 27 host in kvm with libvirt
2. vm HW is 4G RAM 40 GB vda 500 GB vdb nat network
3. create 2 users me & ncadmin
4 enable sudo for both
5 login via ncadmin
6 download wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
7 run with sudo bash nextcloud_install_production.sh

## Expected behaviour
Tell us what should happen
see a fully installed server

## Actual behaviour
Tell us what happens instead
gpg: WARNING: unsafe ownership on homedir '/home/ncadmin/.gnupg'
gpg: keybox '/home/ncadmin/.gnupg/pubring.kbx' created
gpg: key D75899B9A724937A: 8 signatures not checked due to missing keys
gpg: /home/ncadmin/.gnupg/trustdb.gpg: trustdb created
gpg: key D75899B9A724937A: public key "Nextcloud Security <security@nextcloud.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
gpg: WARNING: unsafe ownership on homedir '/home/ncadmin/.gnupg'
gpg: Signature made Monday 23 July 2018 04:24:53 PM IST
gpg:                using RSA key D75899B9A724937A
gpg: Good signature from "Nextcloud Security <security@nextcloud.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2880 6A87 8AE4 23A2 8372  792E D758 99B9 A724 937A
[/] Creating possible missing Directories
chmod Files and Directories
[|] chown Directories
[-] chmod/chown .htaccess
Nextcloud is not installed - only a limited number of commands are available
Nextcloud was successfully installed

Nextcloud version:
  - installed: true
  - version: 13.0.5.2
  - versionstring: 13.0.5
  - edition:

no crontab for www-data
Setting max_upload size in PHP...
'/var/www/nextcloud/.htaccess' -> '/var/www/nextcloud/.user.ini'
System config value mail_smtpmode set to string smtp
System config value log_rotate_size set to string 10485760
Installing issuetemplate...
Error: Could not download app issuetemplate
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ app:install issuetemplate failed
$ $ $ 

## Server configuration
4GB RAM 4 CPU 40 GB OS 500 GB data, nat network 

**Server version:** (see your admin page)
download in /var/www was 13.0.5
**How did you install the VM?** (Scripted install from master **OR** Released version)
script
## Network
**Do you use DHCP?**
yes
**Is port 80 and/or 443 open?**
not yet / will do that after the server comes up
#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Yup, I've seen this as well. It's just a temporary issue with the connection to the AppStore or your internet connection and if you try again it will work, 100%.

We use the function `occ app:install` which is provided by `nextcloud/server` so maybe it's better that you create an issue there and reference this comment.

**Comment by enoch85** [comment]
Added to FAQ.

**Comment by enoch85** [comment]
Ref https://github.com/nextcloud/server/issues/11070
