### ISSUE TITLE
update.sh 13.04 ->13.05 failed to restart php7.2-fpm.service .. service not found

### ISSUE THREAD

**Issue by Bitsauger** [nextcloud/vm#640]
## Steps to reproduce
1. Have a Nextcloud 13.04 up and running, all updates installed via Webmin.
2. bash update.sh
3. something went wrong with .htaccess

## Expected behaviour
Update from 13.04 to 13.05. I updated every Version from 13.00 without any issues with this script.

## Actual behaviour
Failed to restart php7.2-fpm-service: Unit php7.2-fpm.service not found.

## Server configuration
I don't know what admin page means, but i think its 13.04, and Ubuntu 16.04. - Not the newest one with Ubuntu 18.04.

**How did you install the VM?** (Scripted install from master **OR** Released version)
Dont know the difference... I downloaded the OVA file, imported it in Virtual Box (in Openmediavault) and started the script...

## Network
DHCP but with fixed IPs in the router

Port 443 only with self signed certificate.

## Logs / Screenshots
Im not familiar with rdp-clients and i didnt get any log files or text to copy out of the VM sorry. Remmina seems to work like a picture not like text and im on a headless server.

#### Log file (/mnt/ncdata/nextcloud.log)
same here

#### Installation log (command output)
and here

#### Screenshoots
Hope this helps, if not, i'll try to get the logfiles.

<blockquote class="imgur-embed-pub" lang="en" data-id="a/3vQSuhR"><a href="//imgur.com/3vQSuhR"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

Thanks for your help! Sorry for my bad english...

![ncupdate](https://user-images.githubusercontent.com/42753280/44747457-87702b80-ab0d-11e8-9e3e-136e6cc98255.png)
![nc_error](https://user-images.githubusercontent.com/42753280/44747502-a53d9080-ab0d-11e8-8d67-96fe1bf93b8f.png)

**Comment by sooner591** [comment]
Same problem using the script from 13.0.5 to 13.0.6

**Comment by Bloodboy1986** [comment]
Same Error here.

Using an older installation:
Ubuntu 16.04

**Comment by hardcastle64** [comment]
Here is the same problem when using the script 13.0.5 to 13.0.6

Ubuntu 18.04.1

**Comment by enoch85** [comment]
Thanks for your report!

I will fix this asap.

**Comment by enoch85** [comment]
Can you please test the update again?

**Comment by Bloodboy1986** [comment]
Perfect, now it´s woking again :)

**Comment by enoch85** [comment]
Thanks for confirming!

**Comment by hardcastle64** [comment]
Thank you for your quick support. Now works again!

**Comment by Bitsauger** [comment]
Works now, thanks for your fast support!
