### ISSUE TITLE
Table update error NC 13.0.5 -> 13.0.6

### ISSUE THREAD

**Issue by copemande** [nextcloud/vm#644]
## Steps to reproduce
1. Update NC 13.0.5 to 13.0.6 via update.sh
2.
3.

## Expected behaviour
Should finish without errors

## Actual behaviour
db-convert-filecache-bigint failed with General Error 1114 The table '#sql-68a_3227' is full

![ncupdate error](https://user-images.githubusercontent.com/22273465/44894086-67e42900-acee-11e8-9993-a9dcff0d626a.PNG)

## Server configuration

**Server version:** (see your admin page)
13.0.5 to 13.0.6
**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
no
**Is port 80 and/or 443 open?**
yes
#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Thanks for your report!

Is this on MariaDB or PostgreSQL?

**Comment by Ark74** [comment]
Maybe he ran out of space on root.
What is the output of:
`df -h`

**Comment by copemande** [comment]
After freeing the root partition and manual run the db-convert it ran through.
