### ISSUE TITLE
Install failed  Command "maintenance:install" is not defined. 

### ISSUE THREAD

**Issue by reinistihovs** [nextcloud/vm#648]
Hello, 
I tried to install on fresh ubuntu 18.04.1 VM, but got an error.
Virtualization: QEMU/KVM
RAM: 6GB
CPU: 4 VCPU  ( i5)
Second volume : NO  ( I want to mount data to ssh drive to NAS )

Heres the error output:

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "maintenance:install" is not defined.
  Did you mean one of these?
      app:install
      maintenance:data-fingerprint
      maintenance:mimetype:update-db
      maintenance:mimetype:update-js
      maintenance:mode
      maintenance:repair
      maintenance:theme:update
      maintenance:update:htaccess

Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=ncadmin --database-pass=z4QNM*o                                                                                                                                         5EuBA03qo@AyGsxJai --admin-user=ncadmin --admin-pass=nextcloud failed

**Comment by enoch85** [comment]
This must be a temporary error. Please try again and report back. 

Thanks!

**Comment by reinistihovs** [comment]
failed again, i did a clean install prior to run the script, this time i made a clean vm blackup :)

error now: 
Nextcloud version:
  - installed: true
  - version: 13.0.6.1
  - versionstring: 13.0.6
  - edition:

no crontab for www-data
Setting max_upload size in PHP...
'/var/www/nextcloud/.htaccess' -> '/var/www/nextcloud/.user.ini'
System config value mail_smtpmode set to string smtp
System config value log_rotate_size set to string 10485760
Installing issuetemplate...
Error: Could not download app issuetemplate
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ app:install issuetemplate failed
rm: cannot remove '/var/scripts/adduser.sh': No such file or directory
Checking server OS and version...
Seems that required repositories are ok.
apache2 is installed, it must be a clean server.

**Comment by reinistihovs** [comment]
i made a clean VM with a second drive and install went further, so thats the problem.
Can you please make it optional to use second drive as zfs volume?

**Comment by enoch85** [comment]
If you don't install a second drive it will put the datadir in /mnt/ncdata, so no harm done there.

Regarding the `occ` commands I've noticed they fail sometimes, and I really don't know why. It's the Nextcloud way of installing stuff, so to me it's something that is broken in either the Nextcloud code, or something that fails due to bad networking.

I will try to install a new VM here to see if I get the same errors.

**Comment by reinistihovs** [comment]
I can confirm, that installation with the second HDD went successful! 

Can you please give info, how to undo this ZFS drive setup ?
As i understand it is mounted on startup, and if i just remove it it will probably break the system.  and wont boot up.

**Comment by enoch85** [comment]
Yup, and the installation was successful here as well. Just temporary then as I thought :)

I never tried to remove it so I'm not 100% sure. [Duckduckgo](https://duckduckgo.com/) is your friend I'm afraid. 

Closing this issue as the original issue was solved.
