### ISSUE TITLE
Full Text Search script breaks installation during first setup

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#649]
As a routined tester of this wonderful script I encountered two serious glitches trying to install latest NC VM. Double verified, so it might be serious:

1. "Read Error" during installation of "Nextcloud Talk" if system ask "Do you want change port?" (see screenshot)

![putty_2018-09-04_20-46-00](https://user-images.githubusercontent.com/28905767/45054552-9f0b5f00-b08d-11e8-80ee-345cdf0d06eb.png)

2. At the end of the main script (and after all components have been installed) system will ask for a new UNIX password. At this stage script will fall in a endless loop and script can't finish properly and has to be stopped by CTRL+C

![putty_2018-09-04_20-52-06](https://user-images.githubusercontent.com/28905767/45054561-a468a980-b08d-11e8-95d7-a50f0a0b4968.png)

If I restart the so stopped installation, script will start again and has to be stopped to prevent damaging existing installation. Anyway it seems that all is working properly.

Assumed faulty part of https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh:

Line 502 - 527

Q: Can I manually finish those steps which have been left out because of the endless loop? I need manually execute all lines from 502 until the end of script.

Best regards,

nxtester

**Comment by enoch85** [comment]
@nxtester Thanks for your report!

Just tested and everything works here. Not sure what could be wrong: https://cloud.techandme.se/s/Lp4W5426zmei8HQ

**Comment by enoch85** [comment]
Did you install any other apps during the setup? There have been issues with Full Text Search before.

**Comment by enoch85** [comment]
I could reproduce it if I installed ALL apps.

Which apps did you install to be exact?

**Comment by enoch85** [comment]
OK, I didn't install Full Text Search this time, and it worked. Will run it once more and see if that's the issue here.

**Comment by enoch85** [comment]
Yup, same error as last time. FTS script breaks the password change.

@Ark74 Please have a look at this. Indexing FTS does something nasty with the shell.

**Comment by enoch85** [comment]
Frst hit on Google, didn't read: https://www.tecmint.com/fix-passwd-authentication-token-manipulation-error-in-linux/

**Comment by Ark74** [comment]
Weird.
Sounds like a printf "\n" is being passed to password change.

I'll have a look later today.

**Comment by enoch85** [comment]
@Ark74 I made some minor changes to the `any_key` function and corrected some vars. I don't know if it fixed it, but you could try.

**Comment by nxtester** [comment]
Hi Guys,
thanks for your fast response.
I installed: Talk, Collabora, Full-Text-Search, Password-Manager
Allow one more question: Do I have to repeat whole installation from the scratch if this issue will be fixed or is it possible to finish VM installation properly by manual investigation?
Thanks for your appreciated work!
Best regards,
nxtester

**Comment by enoch85** [comment]
@nxtester Full Text Search is the failing one here. 

> Allow one more question: Do I have to repeat whole installation from the scratch if this issue will be fixed or is it possible to finish VM installation properly by manual investigation?

I'd recommend a clean install for a clean experience. 

As I've changed some $vars and functions, could you please try again without enabling SSL? Just do a local installation with only Full Text Search to see if the issue is solved.

Thanks!

**Comment by nxtester** [comment]
OK, tried it but script stopped by error:

![putty_2018-09-05_16-45-29](https://user-images.githubusercontent.com/28905767/45101210-4d191680-b12b-11e8-893b-2971220a3ed6.png)

Thanks!

**Comment by enoch85** [comment]
@nxtester It fails because the `curl` command isn't run and the vars and functions isn't imported. You're testing it the wrong way. 

Can you please tell me how you did the test?

**Comment by Ark74** [comment]
@enoch85 did you enable debug by default?

**Comment by enoch85** [comment]
@Ark74 No?

**Comment by Ark74** [comment]
Weird installing fts (default) the output seems like debug ON.

**Comment by Ark74** [comment]
Ok, I can confirm that latest master keeps looping the "passwd: Authentication token manipulation error".
Looking into it.

**Comment by nxtester** [comment]
Hello Guys,

I simply tested it by running your script according to https://github.com/nextcloud/vm.

Greetings
