### ISSUE TITLE
App "Calendar" breaks VM script during installation

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#655]
As a routined tester of this wonderful script I encountered a unexpected end of installation trying to install latest NC VM. Double verified, so it might be serious:

![putty_2018-09-06_12-06-03](https://user-images.githubusercontent.com/28905767/45151190-eef13f80-b1cd-11e8-83f5-c3c027d9cd66.png)

Thanks for fixing it and your appreciated work!

Best regards,
Nxtester

**Comment by enoch85** [comment]
@nxtester This is not due to a configuration issue in the VM, it's the `occ` module in Nextcloud that is faulty, I think. 

Ref: https://github.com/nextcloud/server/issues/11070

**Comment by nxtester** [comment]
Just tried to install NC but script stopped in the first seconds with this error:

![putty_2018-09-07_18-26-13](https://user-images.githubusercontent.com/28905767/45232194-db79cd80-b2ce-11e8-8481-535cfa1ebfd7.png)

So no chance to run the script successfully. Maybe it would be better to remove this faulty "occ" function and replace it with approved functions (if possible)?

It also would be great to have a "stable branch" of the script and a "developement branch". Because people will need much time to realize, that script, Nextcloud or both will not work. For instance, I try about 10 days to get a working NC instance but it's impossible.

So it wold be pleasant to have a lesser innovative script but much more robust to get a working NC instance.

That's my five cent together with a BIG THANKS for all your appreciated work!

nxtester

**Comment by enoch85** [comment]
@nxtester  

> Ref: nextcloud/server#11070

**Comment by nxtester** [comment]
There is a known DNS issue in Ubuntu 18.04, see https://medium.com/@ahmadb/fixing-dns-issues-in-ubuntu-18-04-lts-bd4f9ca56620.

After modifying DNS entries in /etc/systemd/resolved.conf I had lesser issues regarding resolving servers.

But in the end (stage 2 / after creating certs) script anyway stopped by error:

![putty_2018-09-09_17-14-08](https://user-images.githubusercontent.com/28905767/45265955-ca0dfe00-b453-11e8-813a-132006feb83d.png)

nxtester

**Comment by nxtester** [comment]
@enoch85, thanks for your reply.

Test was quite short because script stopped in the first seconds:

![firefox_2018-09-09_20-27-26](https://user-images.githubusercontent.com/28905767/45267539-eec39f00-b46e-11e8-9599-f8ba81bf6207.png)

**Comment by enoch85** [comment]
Please try again @nxtester

**Comment by nxtester** [comment]
@enoch85

**Comment by nxtester** [comment]
@enoch85

**Comment by nxtester** [comment]
@enoch85 network-manager-service error seems to be fixed and first stage until reboot/ssl runs flawlessy. But finally script stopped again at this stage:

![putty_2018-09-09_23-50-15](https://user-images.githubusercontent.com/28905767/45269286-80410a00-b48b-11e8-8816-ccc6aea2e825.png)

Really strange...

**Comment by nxtester** [comment]
@enoch85 Tested again with unchecked installation option "Passman". Script finished properly and no more breaks noticed. Indeed I have to wait testing it with SSL because I reached certificate limit.
