### ISSUE TITLE
error (every few minutes): Module 'redis' already loaded at Unknown#0

### ISSUE THREAD

**Issue by thibaultmol** [nextcloud/vm#665]
## Steps to reproduce
1. I installed Nextcloud using the script and then later updated to v14

## Behaviour
Everything seems to be working, just get that error in my nextcloud log window constantly

## Server configuration

**Server version:** 14.0.0

**How did you install the VM?** master

## Network
**Do you use DHCP?** no, (DO Droplet)

**Is port 80 and/or 443 open?** yes

#### Log file (/mnt/ncdata/nextcloud.log)
```
https://0bin.net/paste/4ClWw3eWe9Yba6jZ#nAJ-n8yZJldfKM2Hdf7J4Kd7Y5jzM3ycgchXt7WnAe6
```

**Comment by enoch85** [comment]
What's the output of: `cat /etc/php/7.2/fpm/php.ini | grep redis`?

**Comment by thibaultmol** [comment]
extension=redis.so

**Comment by enoch85** [comment]
Issue solved
