### ISSUE TITLE
Full Text Search Docker can't be run at the same time as other Dockers

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#667]
I have tested for a few hours now, and it always ends with the same result. The `fts_esror` is restarting over and over and over again and never stays online.

I run Collabora at the same time with 8 GB RAM and 4 vCPUs. There is plenty of space and resources.

When I enter the bash of the container with `docker exec` I can see that the load of java is like 400%. Something isn't right with the docker it seems and it crashes before it's completely booted.

@Ark74 Do you think you can have a look?

**Comment by Ark74** [comment]
I'll have a look.

Did you upgraded?
If so, how did you do it?

Could you share 
`docker ps -a`

With 6.4.1 there are some new features, and take a little bit longer to index, but it does launch and runs fine on my end, maybe because I'm only using 1 docker at the time.

**Comment by Ark74** [comment]
On a clean install I got no issue.
2 cores / 2.5 gb ram.

Maybe it is the update script which needs attention.

Could you list the steps to reproduce the error.
Cheers!

**Comment by enoch85** [comment]
@Ark74 No it's not the update script - I think. The reson I don't think that is because I didn't run it after the FTS installation. I think it's due to that the container is started too early after a reboot has been made on the VM. I thought of it yesterday - you do a "bootstrapping" before starting it, but that doesn't happen on a normal VM reboot, right?

**Comment by enoch85** [comment]
https://docs.docker.com/engine/reference/run/#exit-status

**Comment by enoch85** [comment]
Fixed
