### ISSUE TITLE
Its not possible to make Updates for Ubunto etc.

### ISSUE THREAD

**Issue by VaroBiker** [nextcloud/vm#672]
Hello,

I tried using Webmin to run the listed updates. Unfortunately, the service ends with the error: No package has been installed.

What's wrong?

Course of the update of 2 points (Phyton modules)

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libpython3.6 libpython3.6-minimal libpython3.6-stdlib
Suggested packages:
  python3.6-venv python3.6-doc binfmt-support
The following packages will be upgraded:
  libpython3.6 libpython3.6-minimal libpython3.6-stdlib python3.6
  python3.6-minimal
5 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
Need to get 5472 kB of archives.
After this operation, 25.6 kB disk space will be freed.
Err:1 http://se.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6 amd64 3.6.6-1~18.04
  Temporary failure resolving 'se.archive.ubuntu.com'
Err:2 http://se.archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3.6 amd64 3.6.6-1~18.04
  Temporary failure resolving 'se.archive.ubuntu.com'
Err:3 http://se.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6-stdlib amd64 3.6.6-1~18.04
  Temporary failure resolving 'se.archive.ubuntu.com'
Err:4 http://se.archive.ubuntu.com/ubuntu bionic-updates/main amd64 python3.6-minimal amd64 3.6.6-1~18.04
  Temporary failure resolving 'se.archive.ubuntu.com'
Err:5 http://se.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpython3.6-minimal amd64 3.6.6-1~18.04
  Temporary failure resolving 'se.archive.ubuntu.com'
E: Failed to fetch http://se.archive.ubuntu.com/ubuntu/pool/main/p/python3.6/libpython3.6_3.6.6-1~18.04_amd64.deb  Temporary failure resolving 'se.archive.ubuntu.com'
E: Failed to fetch http://se.archive.ubuntu.com/ubuntu/pool/main/p/python3.6/python3.6_3.6.6-1~18.04_amd64.deb  Temporary failure resolving 'se.archive.ubuntu.com'
E: Failed to fetch http://se.archive.ubuntu.com/ubuntu/pool/main/p/python3.6/libpython3.6-stdlib_3.6.6-1~18.04_amd64.deb  Temporary failure resolving 'se.archive.ubuntu.com'
E: Failed to fetch http://se.archive.ubuntu.com/ubuntu/pool/main/p/python3.6/python3.6-minimal_3.6.6-1~18.04_amd64.deb  Temporary failure resolving 'se.archive.ubuntu.com'
E: Failed to fetch http://se.archive.ubuntu.com/ubuntu/pool/main/p/python3.6/libpython3.6-minimal_3.6.6-1~18.04_amd64.deb  Temporary failure resolving 'se.archive.ubuntu.com'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by enoch85** [comment]
Please don't use Webmin to do updates, use the built in script: `sudo bash /var/scripts/update.se` from CLI.

The error itself is that it can't resolve the repositories, probably just temporary.

**Comment by enoch85** [comment]
And btw, thanks for posting your issue! :)
