### ISSUE TITLE
Let user decide which disk to use as data disk

### ISSUE THREAD

**Issue by ggeorgg** [nextcloud/vm#675]
I have played around with my server now for quite a while. 
I have 3 disks in my server. On disk 1 I installed Ubuntu Server 18.x. I set up the two other disks as a raid 1. Afterward I ran the nextcloud_install_production.sh script. Then I ran into an error here:
https://github.com/nextcloud/vm/blob/829d1713ccdb41d4d2158e2701ae6527dda96db7/static/format-sdb.sh#L127
I had a look into this file and found out that for this installation ZFS is used for the nextcloud data disk. I removed the label that the disks are part of a raid with these commands:
```
mdadm --stop /dev/md0
mdadm --zero-superblock /dev/sdd
```
Then I started over again. This time the installation was good and the disk was formated with ZFS. Unfortunatley I made an other mistake, so I wanted to start over again.
I installed Ubuntu Server on disk 1 and ran the script. I ran into an issue caused by the same line like mentioned above. 
The command complains, that the disk is already in use.

Now the command 
`lsblk -l -n  grep -v mmcblk | grep disk`
gives me this list:

```
sda   8:0    1   28,7G   0   disk
sdb   8:16  0  149,1G  0  disk
sdc  8:32   0  238,5G  0  disk
sdd  8:48   0  238,5G  0  disk
```
I am not sure, but the script wants to format sdb, than this would be a bad idea because my system is installed to sdb.

Would it be possible to change the script so that we show the user a list of disks that we can use and propose a disk but let the user decide which one to format?

**Comment by enoch85** [comment]
@ggeorgg Thanks for you suggestion.

The script is made with the intention of making it as easy for new Linux users to use it. If it's possible to automate which disk is used, then fine. For more advanced Linux users they can do it themselves.

Of course I would want it to be more flexible, but I haven't given it any thought as it works as is right now, and all the instructions are based on the current way of doing it.

Are you versed in bash? Maybe you could prepare a PR?

**Comment by ggeorgg** [comment]
I understand. 
Normally I can read bash scripts, but unfortunately I am not really an experienced user. I hope some day I will have more skills in scripting. But for now, I am still struggling with setting up onlyoffice in nextcloud with one external IP...

**Comment by enoch85** [comment]
@ggeorgg Any progress on this?
