### ISSUE TITLE
 $REPO is empty

### ISSUE THREAD

**Issue by ggeorgg** [nextcloud/vm#677]
I searched all files of this repositories for $REPO but I couldn't find where it is set. Where does it come from?
In my case, when I execute the script nextcloud_install_production and it comes to this line:

https://github.com/nextcloud/vm/blob/829d1713ccdb41d4d2158e2701ae6527dda96db7/nextcloud_install_production.sh#L116

then $REPO is empty.

**Comment by enoch85** [comment]
Yeah sometimes a race condition happens which will leave an empty $REPO variable. But that's like 2% of the time.

Any suggestions on how to improve it?

**Comment by ggeorgg** [comment]
Sorry, no I don't have suggestions. The problem is, I still don't understand where this variable is set in the code. Or is it a system variable?
This is how it looks like when I open all files in notepad++ and search for "$REPO".

![grafik](https://user-images.githubusercontent.com/13244552/46569378-6d1f3e00-c954-11e8-9f12-5591eee7cf22.png)

The variable is not set at any place in the code.

**Comment by enoch85** [comment]
@ggeorgg All the variables are imported from lib.sh upon script run. The specific variable is set here: https://github.com/nextcloud/vm/blob/master/lib.sh#L24

In which of the scripts are this happening? Maybe it's a bug?

**Comment by ggeorgg** [comment]
I had another look into this and I found out, that
`sudo apt-get update | grep -m 1 Hit` is already emtpy.
It is because my system is installed with german language and therefore it is not "Hit" but "OK" what I have to search for.
So it is no bug. But as an enhancement we could make it independent of the users os language.

**Comment by enoch85** [comment]
We use English as that's the common standard. Or do you propose we have an `elif` statement for every language available?

**Comment by ggeorgg** [comment]
No not really, that would just blow up the code.
