### ISSUE TITLE
update 13.0.5 => 14.0.1

### ISSUE THREAD

**Issue by fgrosswig** [nextcloud/vm#678]
I can not get the update script running.

here is the output of the update script which hangs on mysql error

>  bash /var/scripts/nextcloud_update.sh
mariadb-common auf Halten gesetzt.
mariadb-server auf Halten gesetzt.
mariadb-client auf Halten gesetzt.
mariadb-client-10.1 auf Halten gesetzt.
mariadb-client-core-10.1 auf Halten gesetzt.
mariadb-plugin-connect auf Halten gesetzt.
mariadb-server-10.1 auf Halten gesetzt.
mariadb-plugin-cracklib-password-check auf Halten gesetzt.
mariadb-plugin-gssapi-client auf Halten gesetzt.
mariadb-plugin-gssapi-server auf Halten gesetzt.
mariadb-plugin-mroonga auf Halten gesetzt.
mariadb-plugin-oqgraph auf Halten gesetzt.
mariadb-plugin-spider auf Halten gesetzt.
mariadb-plugin-tokudb auf Halten gesetzt.
mariadb-server-core-10.1 auf Halten gesetzt.
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Halten-Markierung für mariadb-common entfernt.
Halten-Markierung für mariadb-server entfernt.
Halten-Markierung für mariadb-client entfernt.
Halten-Markierung für mariadb-client-10.1 entfernt.
Halten-Markierung für mariadb-client-core-10.1 entfernt.
Halten-Markierung für mariadb-plugin-connect entfernt.
Halten-Markierung für mariadb-server-10.1 entfernt.
Halten-Markierung für mariadb-plugin-cracklib-password-check entfernt.
Halten-Markierung für mariadb-plugin-gssapi-client entfernt.
Halten-Markierung für mariadb-plugin-gssapi-server entfernt.
Halten-Markierung für mariadb-plugin-mroonga entfernt.
Halten-Markierung für mariadb-plugin-oqgraph entfernt.
Halten-Markierung für mariadb-plugin-spider entfernt.
Halten-Markierung für mariadb-plugin-tokudb entfernt.
Halten-Markierung für mariadb-server-core-10.1 entfernt.
If you want to upgrade MariaDB, please run 'sudo apt update && sudo apt dist-upgrade -y'
Trying to upgrade the Redis Pecl extenstion...
Nothing to upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.15.0-36-generic
Found initrd image: /boot/initrd.img-4.15.0-36-generic
Found linux image: /boot/vmlinuz-4.15.0-34-generic
Found initrd image: /boot/initrd.img-4.15.0-34-generic
Found linux image: /boot/vmlinuz-4.15.0-29-generic
Found initrd image: /boot/initrd.img-4.15.0-29-generic
done
Latest release is: 14.0.1. Current version is: 13.0.5.
New version available! Upgrade continues...
Checking latest released version on the Nextcloud download server and if it's possible to download...
nextcloud-14.0.1.tar.bz2                            100%[==================================================================================================================>]  47,46M  6,34MB/s    in 7,2s
Backing up files and upgrading to Nextcloud 14.0.1 in 10 seconds...
Press CTRL+C to abort.
Doing pgdump of nextcloud_db...
grep: /root/.my.cnf: No such file or directory
Enter password:
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Doing mysqldump of all databases...
/dev/fd/63: line 487: mysqldump: command not found

any hints ? thank you :)

**Comment by enoch85** [comment]
Yeah, you probably did one of these things:

1. Manually changed the password for MySQL/MariaDB
2. Deleted the /root.my.cnf (where the password are fetched from
3. A combintation of 1 and 2.

Please confirm.

The reason why I don't think it's a bug is because I maintain like 10 servers as we speak with the old MariaDB code, and all of them worked when updating. One was even from 12.0.2 --> 14.0.1 without any issues.

**Comment by fgrosswig** [comment]
Sorry, i dont have mysql in use. Its a postressql installation

>  'dbtype' => 'pgsql',
  'version' => '13.0.5.2',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ncadmin',

**Comment by fgrosswig** [comment]
So resolved the issue by manually installing mysql server and creating the nextcloud_db.
