### ISSUE TITLE
UnexpectedValueException: The files of the app "files" were not correctly replaced before running the update

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#68]
## Steps to reproduce
1. Run the Tech and Me update script

## Expected behaviour
Update should finish without errors

## Actual behaviour
Update fails due to that the apps folder isn't "replaced correctly".

```
ncadmin@nextcloud:~$ sudo -u www-data php /var/www/nextcloud/occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
UnexpectedValueException: The files of the app "files" were not correctly replaced before running the update
Update failed
Maintenance mode is kept active
Reset log level
``` 

![screenshot from 2016-12-13 00-46-42](https://cloud.githubusercontent.com/assets/4511254/21121583/a4b2cbde-c0cd-11e6-8134-4fb76f29bf1c.png)

## Server configuration
**Server version:** (see your admin page)
Nextcloud 11.0.0 (updates succeeds but with errors) Can't login after update.

**VM version**
10.0.2

**Updated from an older installed version or fresh install:**
Update from 10.0.2 to 11.0.0

### Code snippet
https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L121-L137

@nextcloud/developers How should I replace the apps folder correctly?

**Comment by enoch85** [comment]
This is solved by removing the apps folder in the update script.

Backup still exists at /var/NCBACKUP/apps though.

**Comment by cosenal** [comment]
@enoch85 Please do not mention everyone for this kind of issues!

**Comment by etam** [comment]
I have the same issue

**Comment by enoch85** [comment]
@etam What was your path then? What did you change? The script expects nothing to be tampered with.
