### ISSUE TITLE
Provide pre-set email sender (SMTP relay service)

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#682]
@LukasReschke I create this issue mostly as a question if you think it would be OK to use SMTP2GO as a pre-set email sender server for SMTP in the Nextcloud VM?

The email address would be something like change-this-email@hanssonit.se

As there is no inbox it wouldn't be possible to read emails. I wouldn't be able to see anything either as SMTP2GO is just a SMTP service.

If yes, I will implement.

**Comment by enoch85** [comment]
ping @LukasReschke Do I have your approval?

**Comment by jospoortvliet** [comment]
@rullzer @MorrisJobke what do you think of this?

**Comment by enoch85** [comment]
Please let me know your final decision.

**Comment by MorrisJobke** [comment]
> Am I correct in thinking mails go unencrypted through that so you (or whoever runs it) would be able to intercept and read them, AND know who's running a Nextcloud instance of course?
> 
> That is a privacy issue, I don't think the standard Nextcloud VM should call home to anyone this way.

Ack ...

I can understand the desire to have this baked into the VM ... on the other side the dependency on a third party to transfer the emails unencrypted makes it weird. Especially when share links are sent out. :(

**Comment by rullzer** [comment]
Can't you just trigger a notification to anybody in the admin group that they need to configure a mail server?

**Comment by enoch85** [comment]
> Am I correct in thinking mails go unencrypted through that so you (or whoever runs it) would be able to intercept and read them, AND know who's running a Nextcloud instance of course?

Emails are sent over TLS, and they are not saved anywhere, they are just sent and lands in the users inbox. SMTP2GO is just a "sending service". So yes, it's encrypted, and no, there are no inbox.

> Can't you just trigger a notification to anybody in the admin group that they need to configure a mail server?

How would I do that? With `occ`?

I'd still prefer to use a SMTP relay though.

**Comment by rullzer** [comment]
@enoch85 TLS is just the connection to SMTP2GO. SMTP2GO still can read all the e-mails that pass their system.

> How would I do that? With occ?

`./occ notification:generate`

**Comment by enoch85** [comment]
OK, so SMTP2GO just answered, they will be able to read the emails so no go on that one.

I will implement the notification instead as suggested. Thanks!
