### ISSUE TITLE
NC 13 -->14.01 Apps are gone

### ISSUE THREAD

**Issue by Bitsauger** [nextcloud/vm#686]
Hi there,

I've got a new problem updating to 14.01 via script.
The Update itself works fine, but all my Apps are gone. I tried to copy them from /var/NCBACKUP/apps/ to /var/www/nextcloud/apps but then I've got "433 Forbidden"

I think all apps are ready for NC14

calendar
contacts
bookmarks
Notes
spreed.me

but will be disabled while the update....

## Server configuration
Ubuntu 16.064LTS

## Network
**Do you use DHCP?**
Fixed IPs in the router

port  is 443 open

What can I do to migrate the "old" apps with data, or just update all the apps while NC update?

Thanks a lot! Its a great project!

**Comment by enoch85** [comment]
Since Nextcloud 14 all 3dparty apps are disabled by default. I already asked for a change [here](https://github.com/nextcloud/server/issues/11102)

Please like the issue and maybe it will be prioritized.

**Comment by enoch85** [comment]
And yeah, you need to be root to access files and folders in NCBACKUP.

But the easiest way to enable the apps again is to download and install them from Apps Store.
