### ISSUE TITLE
Update broke Collabora Office

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#687]
Hi,
today I tried to update Nextcloud VM (Version: 14.0.0.19) to latest version (14.0.0.3) by /var/scripts/update.sh which ran flawlessy and reported "Update OK".
However, after this update I missed "Collabora Office" which was blown away. Huh, thanks God I could make a revert to latest snapshot and all was good but older version again.
What to do to keep Collabora Office after update?
Best regards,
Nxtester

**Comment by enoch85** [comment]
I never seen this before. Did the docker run after you rebooted?

Please give me more exact information regarding what happened.

Thanks!

**Comment by nxtester** [comment]
Hello,
nothing special happened. Update went fine and after Login Collabora Office was no longer available. I restarted system but Collabora Office wasn't even available after reboot. It seems, that update removed Collabora Office.
Do you need special file(s) or log(s)?
Thanks for your appreciated effort!

**Comment by enoch85** [comment]
Aah, the app was disabled due to 3dparty. It's not a bug it's a feature: https://github.com/nextcloud/vm#faq

Ref: https://github.com/nextcloud/server/issues/11102#issuecomment-427685621

**Comment by enoch85** [comment]
Just run: `sudo -u www.data php /var/www/nextcloud/occ app:install richdocuments`

**Comment by nxtester** [comment]
Hello,
thanks for your support.
I executed as ncadmin "sudo -u www.data php /var/www/nextcloud/occ app:install richdocuments" and got an error message:  "sudo: Unknown user www.data"
Did I something wrong?
Thanks!

nxtester

sudo: Unbekannter Benutzer: www.data
sudo: Regelwerks-Plugin konnte nicht initialisiert werden

**Comment by enoch85** [comment]
It should be `sudo -u www-data php /var/www/nextcloud/occ app:install richdocuments"`

**Comment by nxtester** [comment]
It worked :-) Thank you!
