### ISSUE TITLE
passwd: user '' does not exist after second login ssh

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#689]
## Steps to reproduce

	Adding user `felipe' ...
	Adding new group `felipe' (1000) ...
	Adding new user `felipe' (1000) with group `felipe' ...
	Creating home directory `/home/felipe' ...
	Copying files from `/etc/skel' ...
	Enter new UNIX password: xxxxxxxxxxxxx
	passwd: password updated successfully
	Changing the user information for felipe
	Enter the new value, or press ENTER for the default
			Full Name []:
			Room Number []:
			Work Phone []:
			Home Phone []:
			Other []:
	Is the information correct? [Y/n] y

	visudo
	felipe  ALL=(ALL:ALL) ALL
	.
	.
	felipe ALL=NOPASSWD: ALL

1. Install
2. Reboot
3. Second login with visudo user

## Expected behaviour
normally finish installation

## Actual behaviour
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist
	passwd: user '' does not exist

## Server configuration

ubuntu 18 - Digitalocean

## Logs / Screenshots
![snag-0042](https://user-images.githubusercontent.com/428820/46914239-ba586c80-cf5f-11e8-829e-85820c737659.png)

#### Log file (/mnt/ncdata/nextcloud.log)
https://gist.githubusercontent.com/johnfelipe/3b9d8028464e96b27ae83860d3a61823/raw/437e7520b8dcaaf587e48c06729d4b914b26c8ee/nextcloud.log

How solved, or which step im doing wrong

**Comment by enoch85** [comment]
Don't add the user yourself, let the script handle everything for you. During the installation, you will be asked to create a new sudo user as you can't run the script with the root user (it will produce errors)

Just [follow these instructions](https://github.com/nextcloud/vm#installation) and you should be fine.

Please close this issue if it works.

**Comment by enoch85** [comment]
@johnfelipe Did it work?

> Please close this issue if it works.

**Comment by johnfelipe** [comment]
Yes bro
