### ISSUE TITLE
only office integrations fails

### ISSUE THREAD

**Issue by claushviid** [nextcloud/vm#692]
## Steps to reproduce
1. Followed the instructions when logginged in first time
2.Chose Only office from menu
3. continue installation no errors at all
4 install only office app via nexcloud
5 save only office configuration ERROR trying to connect BAD request

## Expected behaviour
nextcloud integraded with only office docker

## Actual behaviour
ERROR trying to connect BAD request from only office 

## Server configuration

**Server version:** (see your admin page)
Nextcloud 14.0.3 Automatic upgraded during installation
**How did you install the VM?** (Scripted install from master **OR** Released version)
Released version https://github.com/nextcloud/vm/releases/tag/14.0.1
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes
## Logs / Screenshots

Error | onlyoffice | HealthcheckRequest on check error: Bad Request or timeout error | 2018-10-15T20:10:24+0200
-- | -- | -- | --
Error | PHP | file_get_contents(https://office.rejstrup1.dk/healthcheck): failed to open stream: operation failed at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#381 | 2018-10-15T20:10:24+0200
Error | PHP | file_get_contents(): Failed to enable crypto at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#381 | 2018-10-15T20:10:24+0200
Error | PHP | file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure at /var/www/nextcloud/apps/onlyoffice/lib/documentservice.php#381

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
A few questions:
- Do you run SSL on both your main domain and the Only Office subdomain?
- Did you create a subdomain and pointed the DNS to the server?

**Comment by claushviid** [comment]
Yes i run ssl on borh domains, and yes i created a subdomain and pointed DNS to the server
port 80 and 443 are forwarded and open against nexcloud (Checked)
The installation was straight forward without any errors, and certificates for nextcloud and onlyoffice (Docker) was created

**Comment by claushviid** [comment]
I tried to change rejectUnauthorized in /etc/onlyoffice/documentserver/default.json to false

that did not solve the problem

**Comment by claushviid** [comment]
Before installation
At hostmaster i created TWO A RECORDS nextcloud.XXXX.DK and office.XXXX.DK
In my router i forwarded port 80 and 443 to next cloud IP. At my DHCP server i reserved the MAC adress for nextcloud. At my internal DNS server i created a primary domain XXXX.DK and two host adresses Nextcloud an oOffice and pointed both to the nextcloud IP. 

Checked that nslookup work from outside and inside. Checked that port 80 and 443 in reality was open from outside in and pointed to nextcloud

**Comment by enoch85** [comment]
@claushviid Can you reach the office domain? How does it look like?

Also, how does this look like: https://office.yourdomain.dk/hosting/discovery ?

**Comment by enoch85** [comment]
OK, is the Apache vHOST configured and activated, and if yes ho does it look like?

**Comment by enoch85** [comment]
Are you using a Proxy in front of your Nextcloud server?

**Comment by enoch85** [comment]
Also, how does `docker ps -a` look like?

**Comment by claushviid** [comment]
no i am not using any proxy, just a standard gateway with firewall (Port 80 and 443 forwarded)

Docker says

1c5b6f860890        onlyoffice/documentserver   "/bin/sh -c /app/onl…"   17 hours ago        Up 13 hours         443/tcp, 127.0.0.3:9090->80/tcp                  onlyoffice

I Didnt change the Apache Vhost configuration. Just followed the instructions from the downloaded VM, 
(Import VM -start -login- answer question -done)

**Comment by enoch85** [comment]
OK, I will try this on a DO VPS later tonight. I'll come back with the results.

**Comment by enoch85** [comment]
Sorry, can't test this tonight. Have to push this to later.

**Comment by claushviid** [comment]
For information, I have updated another instance of nextcloud (running in a different environment) from 13.05 to 14.03 based on an older version of your VM images. This without problems. Onlyoffice integration works flawlessly. The update has been run via /vars//scrips/update.sh

This version is based on ubuntu 16.04 and MySql 10.2

**Comment by enoch85** [comment]
So the Ubuntu 16.04 version worked, but not the Ubuntu 18.04?

**Comment by enoch85** [comment]
Is there a difference in amount of RAM on the different systems?

**Comment by enoch85** [comment]
Also, this shouldn't be needed as the script both installs and enables the app with the correct information:

> 4 install only office app via nexcloud
5 save only office configuration ERROR trying to connect BAD request

**Comment by enoch85** [comment]
https://cloud.hanssonit.se/s/ka2FjMjQbsnoMK3 it works here, so nothing wrong in the script.

If you need help setting up ONlyOffice, please ask in the [forums](https://help.nextcloud.com), or [visit our shop](https://shop.hanssonit.se/product/premium-support-per-30-minutes/).

Thanks for posting your issue though.
