### ISSUE TITLE
adminer is good or bad for NC14 in production

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#695]
![snag-0054](https://user-images.githubusercontent.com/428820/47049960-594db600-d164-11e8-9426-9918847887da.png)

i put NOT in installation, if HTTP/2 protocol will be inactive which one will be consequences?

**Comment by enoch85** [comment]
It's your decision. That's why we put the warning.

I would not install it myself as I handle all the DB stuff from CLI. 

And please @johnfelipe [use the forums for questions](https://github.com/nextcloud/vm/issues/693#issuecomment-430208190).
