### ISSUE TITLE
Collabora script install but 

### ISSUE THREAD

**Issue by markovp** [nextcloud/vm#698]
## Steps to reproduce
1. Install new Nextcloud from your image https://github.com/nextcloud/vm/releases/download/14.0.3/Official_Nextcloud_VM_www.hanssonit.se.ova
2. Install Collabora integration through your script https://raw.githubusercontent.com/nextcloud/vm/master/apps/collabora.sh with no error
3. Tray to open one odf file from Documents folder or any folder

## Expected behaviour
Document should open with Collabora CODE.

## Actual behaviour
Colabora CODE start, but document is not open. Instead throws error:
"Failed to read document from storage. Please contact your storage server (cloud.domain.com) administrator."

## Server configuration
Server configuration is by your startup script. Evrything alse is working BP. I install 3 servers from version 13.0.2 to 14.0.3 and the result is the same. If I upgrade older installations where Collabora was priviously working everything is OK.

We use Let's Encrypt certificate for both domains cloud and office and are accesible from internal and external network from ports 80 and 443

**Server version:** (see your admin page)
Ubuntu 18.04.1 LTS
Nextcloud 14.0.3

**How did you install the VM?** (Scripted install from master **OR** Released version)
Released version

## Network
**Do you use DHCP?**
No

**Is port 80 and/or 443 open?**
Yes

#### Log file (/mnt/ncdata/nextcloud.log)
```
{"reqId":"rOrVdtDIC6G6z5THRUtG","level":3,"time":"2018-10-18T12:34:45+02:00","remoteAddr":"192.168.177.100","user":"ncadmin","app":"PHP","method":"GET","url":"\/apps\/systemtags\/lastused","message":"Module 'redis' already loaded at Unknown#0","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}
{"reqId":"1gtoguYjppQQ5V9OH4aO","level":3,"time":"2018-10-18T12:35:03+02:00","remoteAddr":"192.168.177.100","user":"ncadmin","app":"PHP","method":"GET","url":"\/apps\/richdocuments\/index?fileId=12&requesttoken=nZLJYaccBbc%2BU1dMMSON2ZpRHkm6LOAJqDj%2BYpk5Zig%3D%3A%2Bcu%2FEcosQt1sNBo0ZlP9j%2FZnKwDDRYNchxeVL%2FNYJVg%3D","message":"Module 'redis' already loaded at Unknown#0","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}

```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by markovp** [comment]
docker logs --follow "ContainerID"

wsd-00028-00038 2018-10-18 11:30:25.883676 [ websrv_poll ] WRN  WOPI host did not pass optional access_token_ttl| wsd/FileServer.cpp:608
wsd-00028-00124 2018-10-18 11:30:26.688260 [ docbroker_00f ] ERR  WOPI::CheckFileInfo failed with 404 Not Found| wsd/Storage.cpp:522
wsd-00028-00124 2018-10-18 11:30:26.690013 [ docbroker_00f ] ERR  Failed to add session to [/apps/richdocuments/wopi/files/12_oc2l2aw21s3i] with URI [https://mcloud.msistem.si/apps/richdocuments/wopi/files/12_oc2l2aw21s3i?access_token=LRdzeJOuozDNPKAzRsy5pcrFlfXL9W3i&access_token_ttl=0&permission=edit]: WOPI::CheckFileInfo failed| wsd/DocumentBroker.cpp:1002
wsd-00028-00124 2018-10-18 11:30:26.895435 [ docbroker_00f ] WRN  Child session [0070] not found to forward message: load url=https://mcloud.msistem.si/apps/richdocuments/wopi/files/12_oc2l2aw21s3i?access_token=LRdzeJOuozDNPKAzRsy5pcrFlfXL9W3i&access_token_ttl=0&permission=edit readonly=0 lang=sl-SI| wsd/DocumentBroker.cpp:1494
kit-00125-00030 2018-10-18 11:30:26.900221 [ loolkit ] WRN  Waking up dead poll thread [kit], started: false, finished: false| ./net/Socket.hpp:550
wsd-00028-00124 2018-10-18 11:30:26.904404 [ docbroker_00f ] ERR  Invalid or unknown session [0070] to remove.| wsd/DocumentBroker.cpp:1069
wsd-00028-00029 2018-10-18 11:30:27.691414 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_00f], started: true, finished: true| ./net/Socket.hpp:550
wsd-00028-00029 2018-10-18 11:30:27.691530 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_00f], started: true, finished: true| ./net/Socket.hpp:550
1mmwsd-00028-00029 2018-10-18 11:30:27.691612 [ prisoner_poll ] WRN  Prisoner connection disconnected but without valid socket.| wsd/LOOLWSD.cpp:1573kit-00121-00030 2018-10-18 11:30:27.691354 [ loolkit ] WRN  Waking up dead poll thread [kit], started: false, finished: false| net/Socket.hpp:5500m

kit-00121-00030 2018-10-18 11:30:27.691726 [ loolkit ] WRN  Waking up dead poll thread [kit], started: false, finished: false| net/Socket.hpp:550
mwsd-00028-00029 2018-10-18 11:30:27.691709 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_00f], started: false, finished: true| ./net/Socket.hpp:550m
kit-00121-00030 2018-10-18 11:30:27.691760 [ loolkit ] WRN  Kit connection lost without exit arriving from wsd| kit/Kit.cpp:2040
1mwsd-00028-00029 2018-10-18 11:30:27.691822 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_00f], started: false, finished: true| ./net/Socket.hpp:550

**Comment by markovp** [comment]
Screenshot:
https://0bin.net/paste/Kws5cCNbabBfE1JM#Fv4+oEPsiRVtbMXvCjTnTtxKnnbd0Ef9wM-+iHr8kKc

**Comment by enoch85** [comment]
Have you rebooted the whole server after you did the installation?

Maybe related: https://github.com/nextcloud/vm/issues/692

I will test both soon on a DO VPS.

**Comment by enoch85** [comment]
https://cloud.hanssonit.se/s/JHCxkawiHSRpTwm it works here, so nothing wrong in the script.

If you need help setting up Collabora, please ask in the [forums](https://help.nextcloud.com), or [visit our shop](https://shop.hanssonit.se/product/premium-support-per-30-minutes/).

Thanks for posting your issue though.
