### ISSUE TITLE
collabora script installation error

### ISSUE THREAD

**Issue by arrabica** [nextcloud/vm#704]
## Steps to reproduce
1. bash collabora.sh

## Expected behaviour
script should to install collabora

## Actual behaviour
`Installing Collabora...
/dev/fd/63: line 64: sudo: command not found
/dev/fd/63: line 695: [: : integer expression expected
/dev/fd/63: line 64: sudo: command not found
/dev/fd/63: line 731: [: : integer expression expected
/dev/fd/63: line 487: sudo: command not found
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ -V failed
`
"occ" folder in debian is in /var/www/html/nextcloud/occ. How change it? mayby I should do something else?
## Server configuration

Debian GNU/Linux 9 

**Server version:** (see your admin page)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
Yes

**Comment by enoch85** [comment]
@arrabica OK, but have you tried it on Ubuntu 18.04 since Debian is not supported?

**Comment by arrabica** [comment]
ubuntu no, because I have nextcloud installed on debian.

**Comment by enoch85** [comment]
Debian is not supported
