### ISSUE TITLE
only office integrations fails #692

### ISSUE THREAD

**Issue by claushviid** [nextcloud/vm#705]
Hi enoch85
This is not a new issue. I just owe you an explanation of why I could not get the office integration to work, according to the closed case number 692.

As described, I created on my internal DNS server an additional primary domain XXXX.DK and two host addresses Nextcloud an Office and pointed both to the nextcloud IP. I already have another primary domain and DHCP in my setup.

In connection with the installation, nextcloud will be assigned an IP address via DHCP and will also be automatically registered on my original DNS server. During installation, I choose to get the assigned IP address converted to a fixed IP address.

The installation runs through without errors, but integration to the only office does not work. The fact is that Nexcloud is now registered in both internal DNS domains. I removed the address assigned via DHP in DNS ........ Result: integration works as intended.

I would suggest that it becomes possible during the installation to specify a fixed ip address, gateway and DNS server. In addition, it would be great if a small script was created from which you can later change the IP address, gateway and DNS as needed. I can see that this issue is already adressed in case 683

I would also recommend changing the OVA file so Nexcloud does not automatically start up after finishing installation. In my scenario, I do not want to use E1000 as adapter type but vmxnet 3 instead. It gives little challenges to change this afterwards.

By the way, thanks for all your hard work on this project.

regards / Claus Hviid

**Comment by enoch85** [comment]
> I would suggest that it becomes possible during the installation to specify a fixed ip address, gateway

It will be possible [in the next release](https://github.com/nextcloud/vm/pull/697).

Thanks for your feedback!
