### ISSUE TITLE
Something happend when ask about /boot/grub/menu.lst

### ISSUE THREAD

**Issue by johnfelipe** [nextcloud/vm#706]
![snag-0109](https://user-images.githubusercontent.com/428820/47899052-4dd9da80-de46-11e8-937b-ed3b7a201d15.png)

https://drive.google.com/file/d/1JQgX_wyFKQaA9bh-Rv6QUpLBMFRtB7jA/view?usp=drivesdk

I cant continue, with ENTER or TAB
How solved?

**Comment by enoch85** [comment]
This is a regular update question, nothing wrong.

Update or keep, you decide.

**Comment by johnfelipe** [comment]
you not understand me not allow choose any item, pls review this video
https://drive.google.com/file/d/1JQgX_wyFKQaA9bh-Rv6QUpLBMFRtB7jA/view?usp=drivesdk

**Comment by enoch85** [comment]
@johnfelipe Are your trying to use the mouse? Don't, use the keyboard.

I told you before, please don't use the Github *issue* tracker for stuff that is for the forums.

**Comment by enoch85** [comment]
This is an Ubuntu issue as it's nothing that the scripts control. The update script runs `apt dist-upgrade` which is a very basic Ubuntu command.

I don't know what do do here, and I can't reproduce it.

Please ask in the forums.

**Comment by johnfelipe** [comment]
> @johnfelipe Are your trying to use the mouse? Don't, use the keyboard.
> 
> I told you before, please don't use the Github _issue_ tracker for stuff that is for the forums.

bro im use only keyword, mouse in ssh cli never, i install perfectly 10 days ago, but now i have problems for continue...

**Comment by enoch85** [comment]
Sorry, I never seen it before, and I can't reproduce it. 

Force close it with CTRL+C maybe?
