### ISSUE TITLE
Nextcould and Collabora Online Part II

### ISSUE THREAD

**Issue by ferengie** [nextcloud/vm#708]
Hello
### Actual ### behaviour
Empty Screen when editing a document

I was able to recreate the issue. 
Basics like in https://github.com/nextcloud/vm/issues/679

Ok
*** first**
 i did exactly the same on the demo system online - there it worked great
*** second:**
i did exact the same on my new deployed VM. but in this case i used ie11 instead of ff62.x
ie showed me an error message which was not shown in ff.
* what i did
- "activate" Collabora Office under "+Apps"
- under "Settings", "Management", "Collabora Online" i set the server like "https://ourcloud.xxx.com"
- selected menu "Files"
- created a new file "test.odt"
- double clicked it
** IMPORTANT **

- in firefox i just got an empty screen
- in ie i got a part of an error "Webpage can not be displayed", a part means only the top part of the letters, they are cutted in about half high!
![clipboard01](https://user-images.githubusercontent.com/42039634/48051425-5cf1bd00-e1a5-11e8-8a16-86d3d5d8e3c1.jpg)

### question
is there a way to solve this?

**Comment by enoch85** [comment]
@ferengie 

Collabora on the VM isn't designed to be accessed locally, you need a subdomain and a real DNS to make it work. You shouldn't even be able to install it with the script if you don't use a subdomain.

**Comment by ferengie** [comment]
Hi;
ok, have done the redesign:
ourcloud.xxx.local = nextcloud is running with IP 192.168.123.27
ouroffice.xxx.local = collabora office is running with IP 192.168.123.27

now I have two DNS names for the VM
but still not working

*****
understanding (maybe I am wrong)
 nextcloud and Collabora can running on the same VM, so I need a DNS entry for nextcloud and a separate DNS entry for the Collabora.
![2018_11_06_19_02_07_window](https://user-images.githubusercontent.com/42039634/48083891-a74f5a00-e1f6-11e8-8d96-5e4ae92d35b7.jpg)

*****
question
why do I get "page can not be displayed?
![2018_11_06_19_05_25_dateien_nextcloud_internet_explorer](https://user-images.githubusercontent.com/42039634/48084041-001ef280-e1f7-11e8-953f-3b72928bbd7e.png)

**Comment by ggeorgg** [comment]
As far as I understand the script, it is currently only working with a subdomain. 
But you could install e.g. OnlyOffice manually on the same machine with the help of this link:
[https://decatec.de/home-server/nextcloud-online-office-mit-onlyoffice/](https://decatec.de/home-server/nextcloud-online-office-mit-onlyoffice/)
As in this tutorial OnlyOffice is used as docker, I think it is also possible to use a Collabora docker instead. But I have not tested it yet...

**Comment by enoch85** [comment]
This is a question for the forum, not Github. You can find the forum [here](help.nextcloud.com).

If you want pro support, you can go [here](https://shop.hanssonit.se/product/premium-support-per-30-minutes/)

**Comment by ferengie** [comment]
https://github.com/nextcloud/vm/issues/help.nextcloud.com
does not work for me :-(
"Die Webseite wurde nicht gefunden"

**Comment by ferengie** [comment]
https://help.nextcloud.com/t/collabora-on-nextcloud/40677
