### ISSUE TITLE
NextCloud Microsoft Hyper-V and Windows Server 2016

### ISSUE THREAD

**Issue by elnea** [nextcloud/vm#709]
Hi,

I've buy Microsoft Hyper-V (.VHDX) of Nextcloud on hanssonit.se.

I try to follow instructions (video youtube).
https://www.youtube.com/watch?v=UOqn3p198d8

I've two file : 
C:\NextCloud\Official_Nextcloud_VM_www.hansonit.se.vhdx (5,81Go)
C:\NextCloud\Official_Nextcloud_VM_www.hansonit.se-DATA.vhdx (228Mo)

When I try to create Virtual Machine in Hyper V (Windows Server 2016 Std)

I've error :
"Le serveur a rencontre une erreur lors de la création de NextCloud-VM"
"Echec de la création d'un nouvel ordinateur virtuel"
"Echec de la réalisation de NextCloud-VM"

"The Encountered an Error while creating a Virtual Machine"

Could you please help me ? 
Thanks,
Franck.

**Comment by enoch85** [comment]
Hi @elnea, 

I have no idea actually. It works for me, so I can't reproduce it. 

Have you tried on a regular Windows 10 machine? Does that work?

**Comment by enoch85** [comment]
Ping @elnea

**Comment by enoch85** [comment]
It works here so you are probably doing it wrong.

**Comment by elnea** [comment]
Hi,
I downloaded again and unzipped again...
Everything is working well now.
Thanks!

**Comment by enoch85** [comment]
Thanks for confirming!
