### ISSUE TITLE
fail2ban config in VM appliance inadvertently creates two ssh chains

### ISSUE THREAD

**Issue by hatclub** [nextcloud/vm#725]
Debian default jail appears to be called "sshd" whereas jail.local defines a jail titled "ssh" which is likely where this behaviour stems from.

Probably meant to override sshd in local rather than create a new one?

## Steps to reproduce
1. enable fail2ban when installing appliance
2. observe both f2b-ssh and f2b-sshd chains in iptables -L
3. observe that ssh bans, when created, end up in both

## Expected behaviour
Only one chain should exist with SSH bans in

## Actual behaviour
Two chains are created/maintained, doubling the number of firewall rules

## Server configuration
Issue not specific to NextCloud itself
**How did you install the VM?** (Scripted install from master **OR** Released version)
nextcloud appliance, ~9 days ago

**Comment by enoch85** [comment]
Since we don't change anything in Fail2ban it's default behavior. Maybe it's better to report this upstream instead?

**Comment by hatclub** [comment]
jail.local doesn't exist in the fail2ban package, so it can't be unmodified Ubuntu:

```
root@files:/etc/fail2ban# dpkg -S /etc/fail2ban/jail.local
dpkg-query: no path found matching pattern /etc/fail2ban/jail.local
```

**Comment by enoch85** [comment]
jail.local *should* be used for configuring your own set of rules rather than disabling/enabling all the rules that you want/don't want in jail.conf.

That's best practice.

From the fail2ban manual:
*Modifications should take place in the .local and not in the .conf. This avoids merging problem when upgrading. These files are well documented and detailed information should be available there.*

**Comment by enoch85** [comment]
Yup, it's created here: https://github.com/nextcloud/vm/blob/master/apps/fail2ban.sh#L63

**Comment by enoch85** [comment]
@hatclub Any progress on this?

> It’s ok, I’ll see if it’s possible to create a PR that fixes this later this week.

**Comment by enoch85** [comment]
This is now fixed.
