### ISSUE TITLE
Theming does not work correct (Override issue?)

### ISSUE THREAD

**Issue by yirias** [nextcloud/vm#73]
## Steps to reproduce
1. Installed Nextcloud VM (Version 10) in Virtualbox
2. Update Nextcloud to Version 11 using the delivered update.sh script
3. Use the Theming App to theme Nextcloud

## Expected behaviour
All colors, Links to the Cloud, Names and Logos should be the one's set in the Theming App.

## Actual behaviour
Almost everything works fine, but the Favicon doesn't geht the set color and it does not change the logo. It stays the standard, blue Nextcloud Icon.

## Server configuration

**Server version:** (see your admin page)
Ubuntu 16.4 LTS Server
Apache 2.4
PHP 7.0.8
MySQL 5.7.16

**VM version**
VirtualBox Version 5.1.12 r112440 (Qt5.6.2) running on a Windows 7 64Bit host

**Updated from an older installed version or fresh install:**
See above at ## Steps to reproduce

## Logs (from today back to the December 16th)
https://hastebin.com/efomocojag.tex

#### Log file (/var/ncdata/nextcloud.log)
https://hastebin.com/ujezuvejup.tex

#### Installation log (command output)
```
I don't know how to get this, sorry.
```

By the way, I already wrote to the nexcloud.com forums. Maybe what I wrote there can help to.
See: https://help.nextcloud.com/t/different-theme-output-on-two-nextcloud-11-instances/6432?source_topic_id=4722

I also made a clean install of a new Nextcloud VM this morning. It behaves the same way, which means Theming does not work correctly.

I hope someone can help or clear things out to me.

Cheers yiria

**Comment by enoch85** [comment]
This is not a bug, this is per default. The favicon doesn't change afaik. Please make a request in https://github.com/nextcloud/server so the devs can add this option.

Thanks for a detailed issue!

**Comment by yirias** [comment]
> This is not a bug, this is per default. The favicon doesn't change afaik.
As far as I know it is a feature since Nextcloud 11. I have two instances running on public servers for testing and the Themeing App works just as I mentioned in **Expected behaviour** including the change of the favicon. See https://ncdev.yiria.org for example. There is no extra theme folder, everything is done by the Theming App.

Cheers yiria

**Comment by enoch85** [comment]
Please email me a admin login so that I can test. https://www.techandme.se/contact/

**Comment by yirias** [comment]
I just sent you an email, I hope that helps.
