### ISSUE TITLE
docker_overlay2.sh

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/vm#730]
Hi @enoch85 

I ran docker_overlay2.sh but it looks it does not change anything. I guess the script expects the ncdata folder on a different location. (I have moved ncdata to a separate virtual disk).

I suggest to let the Script parse the real location from the Nextcloud config.php. 
In my case config.php. says:   'datadirectory' => '/NCfilestore/ncdata',

Here is the full shell output I got when running the script:

/var/scripts/docker_overlay2.sh: line 103: /mnt/ncdata/DOCKERBACKUP/dockerps.txt: No such file or directory
/var/scripts/docker_overlay2.sh: line 104: /mnt/ncdata/DOCKERBACKUP/mydockersimages.list: No such file or directory
cat: /mnt/ncdata/DOCKERBACKUP/mydockersimages.list: No such file or directory
Create /mnt/ncdata/DOCKERBACKUP/images.db
/var/scripts/docker_overlay2.sh: line 29: /mnt/ncdata/DOCKERBACKUP/images.db: No such file or directory
Read /mnt/ncdata/DOCKERBACKUP/images.db
cat: /mnt/ncdata/DOCKERBACKUP/images.db: No such file or directory
Create /mnt/ncdata/DOCKERBACKUP/images
mkdir: cannot create directory ‘/mnt/ncdata/DOCKERBACKUP/images’: No such file or directory
Setting overlay2 in /etc/docker/daemon.json
Reloading daemon
Restarting the docker service
Canceled hold on docker-ce.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  containerd.io docker-ce-cli
The following packages will be upgraded:
  docker-ce
1 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 50.2 MB of archives.
After this operation, 44.4 MB of additional disk space will be used.
Get:1 https://download.docker.com/linux/ubuntu xenial/stable amd64 containerd.io amd64 1.2.0-1 [19.9 MB]
Get:2 https://download.docker.com/linux/ubuntu xenial/stable amd64 docker-ce amd64 5:18.09.0~3-0~ubuntu-xenial [17.4 MB]
Get:3 https://download.docker.com/linux/ubuntu xenial/stable amd64 docker-ce-cli amd64 5:18.09.0~3-0~ubuntu-xenial [13.0 MB]
Fetched 50.2 MB in 3s (15.7 MB/s)
Selecting previously unselected package containerd.io.
(Reading database ... 111640 files and directories currently installed.)
Preparing to unpack .../containerd.io_1.2.0-1_amd64.deb ...
Unpacking containerd.io (1.2.0-1) ...
Preparing to unpack .../docker-ce_5%3a18.09.0~3-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-ce (5:18.09.0~3-0~ubuntu-xenial) over (18.06.1~ce~3-0~ubuntu) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a18.09.0~3-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-ce-cli (5:18.09.0~3-0~ubuntu-xenial) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up containerd.io (1.2.0-1) ...
Setting up docker-ce-cli (5:18.09.0~3-0~ubuntu-xenial) ...
Setting up docker-ce (5:18.09.0~3-0~ubuntu-xenial) ...
update-alternatives: using /usr/bin/dockerd-ce to provide /usr/bin/dockerd (dockerd) in auto mode
Importing saved docker images to overlay2...
No /mnt/ncdata/DOCKERBACKUP/images.db to read

**Comment by enoch85** [comment]
Thanks @steve-s-71!

It actually already checks if that folder exists, if it doesn't it puts it in /var/ instead:

https://github.com/nextcloud/vm/blob/master/static/docker_overlay2.sh#L19-L22

**Comment by enoch85** [comment]
I improved it a bit and moved the mkdir command to the top instead.

From the script I can see that younow have overlay2. What you need to do is to pull the docker image again.

**Comment by enoch85** [comment]
Revert from your snapshot (if you took any) and then run the scrtip again. It now parses the datadir in config.php
