### ISSUE TITLE
docker_overlay2.sh fails to 'docker save' - no output

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/vm#733]
@enoch85 sorry Daniel, docker_overlay2.sh still does not work for me.

The latest Scipt correcly parse my ncdata dir, but it cant write into it (I call the script via sudo bash, just FYI). I speculate this is because ncdata is owned by www-data and/or due to hardened security on that folder applied by the VM deloper (you :-) 

What I then did was, I manually created a subfolder called "DOCKERBACKUP" under ncdata (va FTP as root, thus the DOCKERBACKUP folder is owned by root). I chmod the subfolder to 775. Then the script runs a bit furhter but still ends in an error message.

If I check DOCKERBACKUP folder after the script ran, it contains 3 files (dockerps.txt, images.db, mydockersimages.list) and an entirely empty subfolder named "images". 

The content of images.db is "onlyoffice/documentserver  <none>  6fc16dba5bc0"

This is the terminal output:
sudo bash /var/scripts/docker_overlay2.sh
Create /NCfilestore/ncdata/DOCKERBACKUP/images
Create /NCfilestore/ncdata/DOCKERBACKUP/images.db
Read /NCfilestore/ncdata/DOCKERBACKUP/images.db
[DEBUG] save 6fc16dba5bc0 onlyoffice/documentserver:<none> to /NCfilestore/ncdata/DOCKERBACKUP/images/6fc16dba5bc0.dim
real    0m0.124s
Setting overlay2 in /etc/docker/daemon.json
Reloading daemon
Restarting the docker service
Canceled hold on docker-ce.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  containerd.io docker-ce-cli
The following packages will be upgraded:
  docker-ce libperl5.22 perl perl-base perl-modules-5.22
5 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 57.8 MB of archives.
After this operation, 44.4 MB of additional disk space will be used.
Get:1 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libperl5.22 amd64 5.22.1-9ubuntu0.6 [3,405 kB]
Get:2 https://download.docker.com/linux/ubuntu xenial/stable amd64 containerd.io amd64 1.2.0-1 [19.9 MB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 perl amd64 5.22.1-9ubuntu0.6 [237 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 perl-base amd64 5.22.1-9ubuntu0.6 [1,283 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/main amd64 perl-modules-5.22 all 5.22.1-9ubuntu0.6 [2,629 kB]
Get:6 https://download.docker.com/linux/ubuntu xenial/stable amd64 docker-ce amd64 5:18.09.0~3-0~ubuntu-xenial [17.4 MB]
Get:7 https://download.docker.com/linux/ubuntu xenial/stable amd64 docker-ce-cli amd64 5:18.09.0~3-0~ubuntu-xenial [13.0 MB]
Fetched 57.8 MB in 6s (8,958 kB/s)
(Reading database ... 111640 files and directories currently installed.)
Preparing to unpack .../libperl5.22_5.22.1-9ubuntu0.6_amd64.deb ...
Unpacking libperl5.22:amd64 (5.22.1-9ubuntu0.6) over (5.22.1-9ubuntu0.5) ...
Preparing to unpack .../perl_5.22.1-9ubuntu0.6_amd64.deb ...
Unpacking perl (5.22.1-9ubuntu0.6) over (5.22.1-9ubuntu0.5) ...
Preparing to unpack .../perl-base_5.22.1-9ubuntu0.6_amd64.deb ...
Unpacking perl-base (5.22.1-9ubuntu0.6) over (5.22.1-9ubuntu0.5) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up perl-base (5.22.1-9ubuntu0.6) ...
(Reading database ... 111640 files and directories currently installed.)
Preparing to unpack .../perl-modules-5.22_5.22.1-9ubuntu0.6_all.deb ...
Unpacking perl-modules-5.22 (5.22.1-9ubuntu0.6) over (5.22.1-9ubuntu0.5) ...
Selecting previously unselected package containerd.io.
Preparing to unpack .../containerd.io_1.2.0-1_amd64.deb ...
Unpacking containerd.io (1.2.0-1) ...
Preparing to unpack .../docker-ce_5%3a18.09.0~3-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-ce (5:18.09.0~3-0~ubuntu-xenial) over (18.06.1~ce~3-0~ubuntu) ...
Selecting previously unselected package docker-ce-cli.
Preparing to unpack .../docker-ce-cli_5%3a18.09.0~3-0~ubuntu-xenial_amd64.deb ...
Unpacking docker-ce-cli (5:18.09.0~3-0~ubuntu-xenial) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up perl-modules-5.22 (5.22.1-9ubuntu0.6) ...
Setting up libperl5.22:amd64 (5.22.1-9ubuntu0.6) ...
Setting up perl (5.22.1-9ubuntu0.6) ...
Setting up containerd.io (1.2.0-1) ...
Setting up docker-ce-cli (5:18.09.0~3-0~ubuntu-xenial) ...
Setting up docker-ce (5:18.09.0~3-0~ubuntu-xenial) ...
update-alternatives: using /usr/bin/dockerd-ce to provide /usr/bin/dockerd (dockerd) in auto mode
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Importing saved docker images to overlay2...
Read /NCfilestore/ncdata/DOCKERBACKUP/images.db
[DEBUG] load 6fc16dba5bc0 onlyoffice/documentserver:<none> from /NCfilestore/ncdata/DOCKERBACKUP/images/6fc16dba5bc0.dim
open /NCfilestore/ncdata/DOCKERBACKUP/images/6fc16dba5bc0.dim: no such file or directory
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
load_images failed

**Comment by enoch85** [comment]
Hmm, that's strange. It works every time for me, even with several docker images.

Can we book a session so that I can try it myself and debug it? Please send me an email. Thanks!

**Comment by enoch85** [comment]
@steve-s-71 Some pointers:

1. Is the VM working and running when you do this?
2. Have you tested to run `sudo bash /var/scripts/update.sh`?

**Comment by steve-s-71** [comment]
@enoch85 

> Can we book a session so that I can try it myself and debug it? Please send me an email. 

you have mail.

**Comment by steve-s-71** [comment]
@enoch85
>Is the VM working and running when you do this?
Yes, the VM so the NC installation is running an avaiable via the Webfront end when I do this  

>  Have you tested to run sudo bash /var/scripts/update.sh?
Yes, I sucessfully run update.sh every time when a new NC version is announced. Just recently I used it to upgrate to 14.0.4. It worked seamlessly.

**Comment by enoch85** [comment]
>  It worked seamlessly.

Ah ok, so when did you do that? Because running the fix for overlay2 was imported yesterday and is only run if you are using devicemapper. So, if you are running on overlay2 already, then this fix isn't running and maybe that's why it doesn't work when you run it directly either...?

**Comment by enoch85** [comment]
Ah ok, then running docker_overlay2 has no effect since it's only changing if you have the devicemapper storage driver. But it should still work though. I mean import/export (save/load) isn't depending on which driver you use. Can you please post the output of `docker info` before you run anything?

**Comment by enoch85** [comment]
And also, please run update.sh again just to make sure that it won't trigger any change.

**Comment by enoch85** [comment]
@steve-s-71 Ping :)

**Comment by steve-s-71** [comment]
This is the output from docker info. What to do next - run update.sh then docker_overlay2.sh?  Or run  docker_overlay2.sh then update.sh?


Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.842GiB
Name: nextcloud
ID: 6F76:KECD:5M57:2COI:DNEB:HYM4:3CNF:XI7O:DROV:DF6O:LKIE:O6QT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

**Comment by enoch85** [comment]
@steve-s-71 

Aaah you're running aufs! That explains it. 

I haven't tested this with the aufs driver, but it shouldn't matter.

Do you have time now? I didn't get your last email, please send a new one with your Teamviewer details. Thanks!

**Comment by steve-s-71** [comment]
Sorry I’m back to back booked till Friday evening. How about Friday 19:00 German time? 

 

Viele Grüße,

Stefan Sieber

 

Von: Daniel Hansson <notifications@github.com> 
Gesendet: Mittwoch, 5. Dezember 2018 17:49
An: nextcloud/vm <vm@noreply.github.com>
Cc: Stefan Sieber <github.com@sieber-em.de>; Mention <mention@noreply.github.com>
Betreff: Re: [nextcloud/vm] docker_overlay2.sh fails to 'docker save' - no output (#733)

 

@steve-s-71 <https://github.com/steve-s-71> 

Aaah you're running aufs! That explains it.

I haven't tested this with the aufs driver, but it shouldn't matter.

Do you have time now? I didn't get your last email, please send a new one with your Teamviewer details. Thanks!

**Comment by enoch85** [comment]
Sure, I'll send you an invite!

**Comment by enoch85** [comment]
Reason, the image isn't tagged and needs a manual `docker pull [IMAGE]` to update to the latest image, after that a reboot is needed to make the old image "dangling" and then remove it.

I tried to tag the dangling image but has not yet succeeded. For now, AUFS driver is unsupported. But I'll open a new issue to check this out. Since the script is fixed (not supporting AUFS) I'll close this issue.

**Comment by enoch85** [comment]
To be clear: ALL images without a tag is unsupported. So when running a `docker images` and one of the images shows `TAG none` then the script won't work, yet.
