### ISSUE TITLE
Renew LE SSL DNS with Cloudflare and Dehytrated

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#734]
https://github.com/sineverba/cfhookbash

- [ ] Create a Clodflare account with bash/python (not possible afaik)
- [ ] Change DNS to Cloudflare with bash/python (not possible afaik)
- [ ] Script the rest of the instructions from the link above.

**Comment by enoch85** [comment]
Maybe this is possible with deSec API?

cc @peterthomassen

**Comment by gpz1100** [comment]
Have you considered acme-dns?  https://github.com/joohoi/acme-dns

This works without using the cloudflare global api key or zone token.  In fact should be compatible with most registrars as no periodic records are actually updated at renewal time, just during initial setup.  Initial set up is more complicated, requiring port 53/udp inbound availability (also needed during updates).  Renewal script can open necessary ufw ports, start service, perform renewal, stop service, close ports.

https://gauravsohoni.wordpress.com/2020/07/21/renewing-letsencrypt-wildcard-ssl-certificate-with-acme-dns/ has a good guide on setting this up.

**Comment by peterthomassen** [comment]
It is possible to use the deSEC API for set up the records for the Let's Encrypt ACME DNS challenge. Our API is also integrated in a bunch of libraries (e.g. acme.sh, lego). For a more detailed list, see https://talk.desec.io/t/tools-implementing-desec/11

> Maybe this is possible with deSec API?

Can you be a bit more specific what you mean by "this"? Is this about automating TLS certificates for users who already have connected their VM to a domain?

**Comment by enoch85** [comment]
What I want to do here is to be able to automatically update the TXT records for LE TLS when renewed. Since the deSEC can do so much, can it also update TXT records grepped from the output of the LE TLS (DNS) challenge?

In that case we could still use certbot.

**Comment by peterthomassen** [comment]
Yes, we have a hook script for that: https://github.com/desec-io/desec-certbot-hook It can be enabled using `--manual-auth-hook` / `--manual-cleanup-hook`. For details, see the README in the repo.

There's also a certbot plug-in here: https://github.com/akararsse/certbot-dns-desec However, we have not reviewed it yet, and I have not tried to use it. It's possible that it simplifies things, but it's also possible it's broken -- so in case you want to use it, I'd recommend to do some quality assurance first.

**Comment by enoch85** [comment]
Thanks @peterthomassen!

Once we implemented the deSEC script here, we might take a look at this issue as well.

Basically as I see it we can present the user with two options when the only option left is to generate TLS with DNS:
1. Add the DNS TXT themselves (no auto renew)
2. Change (or add) DNS to deSEC and in that case make it possible to automatically renew DNS-challanges made by LE (certbot).
