### ISSUE TITLE
issuetemplate not compatible with nc15

### ISSUE THREAD

**Issue by ggeorgg** [nextcloud/vm#739]
Not sure how to handle this, but issuetemplate and CanIUpdate are not compatible with nc15 yet. 
Just tried to install nc in my virtualbox and failed:
![2018-12-11 20_34_45-ubuntu server fstab eintrag wird ausgefuhrt - oracle vm virtualbox](https://user-images.githubusercontent.com/13244552/49825253-44685a00-fd84-11e8-9780-ef723dc237d5.png)

Maybe we should wait for the apps to be compatible with the latest nc version before we use the latest nc version? what do you think?

**Comment by enoch85** [comment]
It's because the issue template app is not compatible with NC 15 yet. We download all the apps from the App Store with `occ`.

Please check here: https://github.com/nextcloud/vm/releases/tag/15.0.0

**Comment by ggeorgg** [comment]
Ah, now I saw the "Known errors:" section. 
But this didn't prevent me to run into this error. I can imagine, that others also run into this error. 
I know that the apps will apparently be not available for a "short" time, but nevertheless we should either not display the apps in the install process or we should make sure, that we don't runt into this error. Or even better: If we run into this problem, it should be a warning and not an error as this is not a show stopper when this app (or an app in general) can not be installed. 
So I would propose to display a message to the user that specific apps couldn't be installed and ask for "OK" confirmation to continue the script.

**Comment by enoch85** [comment]
Better to use `#` in front of the installer script for the app in that case and then remove it when it's fixed.

**Comment by ggeorgg** [comment]
This would be possible and easy to do, but we would have to check every time we use a new release if all the apps we offer to install are compatible. 
I think we should display a message that an app has not been installed (and that it has to be installed after finishing the script manually) and then proceed with the installation. 

This would avoid to start all over again or the need to manually edit the install_nextcloud_production.sh file after an error to be able to contintue the installation.
