### ISSUE TITLE
Upgrade from 14.0.4 to 15.0.0 failed

### ISSUE THREAD

**Issue by johansenmeister** [nextcloud/vm#742]
## Steps to reproduce
1. Rebooted VM
2. Ran sudo /var/scripts/./nextcloud_update.sh
3. Failed after "Updated Database"

## Actual behaviour
Latest release is: 15.0.0. Current version is: 14.0.4.
New version available! Upgrade continues...
Checking latest released version on the Nextcloud download server and if it's possible to download...
nextcloud-15.0.0.tar.bz2                                           100%[=============================================================================================================================================================>]  34,50M  3,92MB/s    in 12s     
Backing up files and upgrading to Nextcloud 15.0.0 in 10 seconds... Press CTRL+C to abort.
mysql: [Warning] Using a password on the command line interface can be insecure.
Doing mysqldump of nextcloud_db...
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Backing up data...

Backup OK!
gpg: requesting key A724937A from hkp server p80.pool.sks-keyservers.net
gpg: key A724937A: "Nextcloud Security <security@nextcloud.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: Signature made ma. 10. des. 2018 kl. 11.27 +0100 CET using RSA key ID A724937A
gpg: Good signature from "Nextcloud Security <security@nextcloud.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2880 6A87 8AE4 23A2 8372  792E D758 99B9 A724 937A
/var/www/nextcloud-15.0.0.tar.bz2 exists
/var/NCBACKUP/config/ exists
/var/NCBACKUP/apps/ exists

All files are backed up.
Maintenance mode enabled
Removing old Nextcloud instance in 5 seconds...
[\] Creating possible missing Directories
chmod Files and Directories
[/] chown Directories
[|] chmod/chown .htaccess
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode already disabled
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
UnexpectedValueException: The files of the app "user_external" were not correctly replaced before running the update
Update failed
Maintenance mode is kept active
Reset log level
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ upgrade failed

## Server configuration

**Server version:** Ubuntu 16.04.1 (4.15.0-42-generic) w/Nextcloud VM 14.0.4 w/Apache and mariadb

**How did you install the VM?** (Scripted install from master **OR** Released version)
From github.com/nextcloud/vm in cirka April 2016

## Network
Static IP both local and external

**Is port 80 and/or 443 open?**
Yes, forwarded

#### Log file (/mnt/ncdata/nextcloud.log)
```
{"reqId":"1X1FJxYDkACjR4PcUsoq","level":3,"time":"2018-12-14T09:00:03+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":{"Exception":"Icewind\\SMB\\Exception\\ForbiddenException","Message":"Invalid request for \/ (ForbiddenException$
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:32+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceEnabled: Turned on maintenance mode","userAgent":"--","version":"14.0.4.2"}
{"reqId":"AWFP41biArhUd69Qgu8b","level":0,"time":"2018-12-14T09:10:32+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"starting upgrade from 14.0.4.2 to 15.0.0.10","userAgent":"--","version":"14.0.4.2"}
{"reqId":"AWFP41biArhUd69Qgu8b","level":3,"time":"2018-12-14T09:10:32+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"file_put_contents(\/var\/ncdata\/.htaccess): failed to open stream: Permission denied at \/var\/www\/nextcloud\/l$
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:32+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"--","version":"14.0.4.2"}
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:32+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: All tables already have the correct collation -> nothing to do","userAgent":$
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:32+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair SQLite autoincrement","userAgent":"--","version":"14.0.4.2"}
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:32+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Copy data from accounts table when migrating from ownCloud","userAgent":"--"$
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:33+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Drop account terms table when migrating from ownCloud","userAgent":"--","ver$
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:33+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::dbUpgradeBefore: Updating database schema","userAgent":"--","version":"14.0.4.2"}
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:36+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::dbUpgrade: Updated database","userAgent":"--","version":"14.0.4.2"}
{"reqId":"AWFP41biArhUd69Qgu8b","level":3,"time":"2018-12-14T09:10:36+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"UnexpectedValueException","Message":"The files of the app \"user_external\" were not correctly repl$
{"reqId":"AWFP41biArhUd69Qgu8b","level":3,"time":"2018-12-14T09:10:36+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::failure: UnexpectedValueException: The files of the app \"user_external\" were not correctly r$
{"reqId":"AWFP41biArhUd69Qgu8b","level":3,"time":"2018-12-14T09:10:36+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"--","version":"14.0.4.2"}
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:36+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"--","version":"14.0.4.2"}
{"reqId":"AWFP41biArhUd69Qgu8b","level":1,"time":"2018-12-14T09:10:36+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"14.0.4.2"}

```

**Comment by enoch85** [comment]
Hi!

Thanks for your report! 

Since the upgrade is done with `occ upgrade` please report this in [server](https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md) section instead.
