### ISSUE TITLE
Update to Nextcloud 15 fails "Error: ncdata is not a ZFS filesystem or volume."

### ISSUE THREAD

**Issue by nxtester** [nextcloud/vm#749]
Hi,
I regularly run the update script "/var/scripts/update.sh" to keep installed modules up-to date.

Today I had a strange error. The update script  broke irregularly during the upgrade to Nextcloud 15 with messsage "Error: ncdata is not a ZFS filesystem or volume.". This is kinda strange because "ncdata" was formatted by installation script as ZFS. The drive was before inital installation a Hyper-V raw type without any format.

Any help quite appreciated. Thank you!

Full status messages / error:

Latest release is: 15.0.0. Current version is: 14.0.3.
New version available! Upgrade continues...
Checking latest released version on the Nextcloud download server and if it's possible to download...
nextcloud-15.0.0.tar.bz2                 100%[=================================================================================>]  34,50M  11,1MB/s    in 3,3s
Backing up files and upgrading to Nextcloud 15.0.0 in 10 seconds... Press CTRL+C to abort.
Doing pgdump of nextcloud_db...
Backing up data...
ii  libzfs2linux                          0.7.5-1ubuntu16.4                           amd64        OpenZFS filesystem library for Linux
/dev/sdb1 /mnt/ncdata ext4 rw,relatime,data=ordered 0 0
Adding required repo (multiverse).
»multiverse«-Distributionskomponente ist bereits für alle Quellen aktiviert.
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
zfs-auto-snapshot ist schon die neueste Version (1.2.4-1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Error: ncdata is not a ZFS filesystem or volume.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
zfs-auto-snapshot -r ncdata failed
ncadmin@cloud:~$ https://github.com/nextcloud/vm/issues

**Comment by enoch85** [comment]
Does it work if you run the updater again?

Also, please post the output of (as root):

- `df -h`
- `fdisk -l`
- `cat /etc/mtab`
- `zpool status`

Thanks!

**Comment by nxtester** [comment]
Second try also won't work, same issue.

![image](https://user-images.githubusercontent.com/28905767/50388601-b5f8be80-071b-11e9-86fa-04c9e5d36c24.png)

![image](https://user-images.githubusercontent.com/28905767/50388603-e2acd600-071b-11e9-888e-cada67bc6a68.png)

![image](https://user-images.githubusercontent.com/28905767/50388606-f6f0d300-071b-11e9-912f-fe2fbff139c4.png)

![image](https://user-images.githubusercontent.com/28905767/50388608-08d27600-071c-11e9-9390-6dc48459033d.png)

Thanks for your appreciated work!

**Comment by enoch85** [comment]
It seems like the ZFS pools are missing.

Please try `zpool import ncdata`

**Comment by nxtester** [comment]
![image](https://user-images.githubusercontent.com/28905767/50400441-fe00fb00-0786-11e9-8715-30d64f033447.png)

Thanks for ur help!

**Comment by enoch85** [comment]
Which hypervisor do you run?

**Comment by nxtester** [comment]
Hyper-V / Server 2012R2

**Comment by nxtester** [comment]
I never expanded the pool by myself. NC was installed before some months and never touched anything except updates by regular script. I don't know how it is with a new VM because I don't have a new one.

Could I remove this ZFS option for the update?

**Comment by enoch85** [comment]
I tested yesterday myself on an old installation and didn't have any issues. 

Since I maintain several servers with the "new" ZFS mount and run the updater script regularly without any interruption or errors like these, I don't think it's a bug in the VM. --> closing

> Could I remove this ZFS option for the update?

You could move the data to a EXT4 mount if you want. Nothing stops you from doing your own changes. :)

**Comment by enoch85** [comment]
Aah, when reading more carefully I can see that this is not even ZFS. It tries to mount as ext4 as you can see in the `mtab`. That's nothing the script would even try to do, so something is manually changed here.

This is a support question rather than a bug I'd say. Please use the [forums](https://help.nextcloud.com) or buy support.

**Comment by CupricReki** [comment]
The problem arises because the script _seems_ to check for the ability to run the zfs commands, not whether or not there actually are zpools. Removing zfs-auto-snapshot and zfsutils resolved the issue for me.

**Comment by enoch85** [comment]
@CupricReki Hmm, could you be more specific please? What you're describing seems like a bug to me. 

A PR would be most welcome!

**Comment by crdxfire** [comment]
is it possible to use ./update.sh, if ncdata is located on an ext4 partition?
