### ISSUE TITLE
.htaccess permissions error

### ISSUE THREAD

**Issue by FriedCircuits** [nextcloud/vm#75]
Error when install script updates .htaccess. I have to change then update .htaccess with occ and then set permissions back. 
## Steps to reproduce
1. Setup VM
2.
3.

## Expected behavior
Should update .htaccess

## Actual behaviour
Permissions error and therefore Apache rewrite doesn't work correctly and shows /index.php

## Server configuration

**Server version:** (see your admin page)
Ubuntu 16
**VM version**
Latest, NC 11 running on ESXi 6.0
**Updated from an older installed version or fresh install:**

**Comment by enoch85** [comment]
This is a known error: https://github.com/nextcloud/vm/releases/tag/11.0.0

And fixed in master: https://github.com/nextcloud/vm/commit/a92bebe0af70b01dd460a7eb92f0aa5b34330c4e

Thanks for your report.

**Comment by FriedCircuits** [comment]
Thank you! I manually ran chown on my copy.
