### ISSUE TITLE
/mnt/ncdata is blank on shifting disks to new system

### ISSUE THREAD

**Issue by igor-kaleta** [nextcloud/vm#751]
I am not sure if this is an issue with Nextcloud VM, but I am facing this problem and unable to shift my Nextcloud VM from ESXi to KVM. Any help is appreciated.

## Steps to reproduce
1. Copy Nextcloud-flat.vmdk and Nextcloud-flat_1.vmdk from a working ESXi VM to a KVM machine
2. Create a new VM and provide it both these disk files

## Expected behaviour
Nextcloud-flat_1.vmdk(/dev/vdb) should be mounted as /mnt/ncdata

## Actual behaviour
VM boots up via /dev/vda but /mnt/ncdata is blank, /dev/vdb1 doesn't exist and cannot mount it.

## Server configuration

**Server version:** (see your admin page)

**How did you install the VM?** (Scripted install from master **OR** Released version)
Released version

## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
Yes
#### Log file (/mnt/ncdata/nextcloud.log)
```
Cannot provide it.
```

**Comment by enoch85** [comment]
Hi, 

This is more of a support question than a bug so I'd recommend you to post this question in the [forum](https://help.nextcloud.com) instead.

Thanks!

**Comment by enoch85** [comment]
In short, the ZFS pool is formatted and mounted based on which Hypervisor you use. So you can't just move the disks straight off and expect it to work.

What I would do is to create a new KVM VM, run the scripts, and then export / import data + db into the new one.

**Comment by igor-kaleta** [comment]
Could you guide me to the information on how to export and import data+DB into new VM ?

And thank you for doing the great work and enabling less techy people to setup their own nextcloud. I find your work to be the most easy one for people to use.
