### ISSUE TITLE
Shutdown Issue

### ISSUE THREAD

**Issue by graphixillusion** [nextcloud/vm#753]
Hi there. I'm usually having a problem when i need to shutdown the vm. With those commands:

1. sudo shutdown
2. sudo halt

the machine turns off but when i restart it, i will always get: "The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."
If i restart the VM a second time, it will works again. This problem just occur with nextcloud, webmin works without problems. I'm using the preconfigured vm in vmware. I tried also to stop and restart apache service through the webmin panel but nothing, if i don't restart the virtual machine a second time it will keeps not working with the message as above. Any clue?

**Comment by enoch85** [comment]
OK, I never use shutdown. Use `poweroff` instead. Does that work better?

**Comment by graphixillusion** [comment]
I tried now with "sudo poweroff" and at the first restart it works without problems. Thank you for now. I'll keep using this command and i'll report it back if something wrong will happen again.

**Comment by graphixillusion** [comment]
During the shutdown process, expecially when the vm is on for few days, when i turn off the machine i'll get this error:

Failed deactivating swap /dev/mapper/nextcloud--vg-swap_1

and then it stucks in a neverending cycle at this point:

A stop job is running for: 
/dev/dm-1
/dev/nextcloud-vg/swap_1
/dev/disk/somenumbers
/dev/disk/someothernumbers
/dev/disk/..-nextcloud--vg-swap_1

Any clue?

**Comment by enoch85** [comment]
Maybe a hardware issue?

**Comment by graphixillusion** [comment]
I'm using other virtual machines too and i don't have any problems so i don't think so...
