### ISSUE TITLE
Newbie: nextcloud_occ not found

### ISSUE THREAD

**Issue by ctmorgen** [nextcloud/vm#757]
Hi,

great work (testing VMware 80GB image). A problem, when trying to start "nextcloud_occ":

Getting "Could not open input file: nextcloud_occ" or "nextcloud_occ: command not found".

Tried this with various variants of sudo as ncadmin or as ncadmin native. root password not known.

System is working fine, but without occ a tools for debugging is missing.

thanks in advance
T.

**Comment by enoch85** [comment]
```
root@cloud:~# cat .bash_aliases 
alias nextcloud_occ='sudo -u www-data php /var/www/nextcloud/occ'
alias run_update_nextcloud='bash /var/scripts/update.sh'
root@cloud:~# nextcloud_occ user:list
  - enoch85: Daniel Hansson
```

It works as intended, please see above.

**Comment by ctmorgen** [comment]
Thanks. Usefull(?) feedback;

This solved the problem, because I didn't know the path to occ, BUT:

.bash_alias simply doesn't exist. .bash[_history|_logout|_profile|rc] do.

hope that helps

**Comment by enoch85** [comment]
@ctmorgen OK, sorry, I should have been more clear. The alias is added from version 14, if you don't have it then it's not included in the VM you downloaded but it exists in later versions. 

Anyway, you can find more information about the Nextcloud `occ` command in the documentation: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html
