### ISSUE TITLE
Nextcloud PHP Startup: Unable to load dynamic library 'tidy.so' after Update to 14.0.4

### ISSUE THREAD

**Issue by Ch-Otte** [nextcloud/vm#758]
PHP Startup: Unable to load dynamic library '/opt/keyhelp/php/7.2/lib/php/extensions/no-debug-non-zts-20170718/tidy.so' (tried: /opt/keyhelp/php/7.2/lib/php/extensions/no-debug-non-zts-20170718/tidy.so (libtidy.so.5: cannot open shared object file: No such file or directory), /opt/keyhelp/php/7.2/lib/php/extensions/no-debug-non-zts-20170718//opt/keyhelp/php/7.2/lib/php/extensions/no-debug-non-zts-20170718/tidy.so.so (/opt/keyhelp/php/7.2/lib/php/extensions/no-debug-non-zts-20170718//opt/keyhelp/php/7.2/lib/php/extensions/no-debug-non-zts-20170718/tidy.so.so: cannot open shared object file: No such file or directory)) at Unknown#0

The File is existing at /opt/keyhelp/php/7.2/lib/php/extensions/no-debug-non-zts-20170718/tidy.so and i tried to fix it with "apt-get install php-tidy"
It looks like there are a few typing failures. "../tidy.so.so" or "../no-debug-non-zts-20170718//opt/.."

**Comment by enoch85** [comment]
@Ch-Otte Thanks for your report.

Tidy is nothing that is installed per default in the VM afaik, so I'd suggest you ask in the forums instead: https://help.nextcloud.com.
