### ISSUE TITLE
Renew letsencrypt cert

### ISSUE THREAD

**Issue by kostyainmadness** [nextcloud/vm#759]
Hi!
Im trying to renew certificate from letsencrypt with command "sudo -H bash /var/scripts/letsencryptrenew.sh" and it always work perfect, but now when i try to renew it give me this error:

> All renewal attempts failed. The following certs could not be renewed:
>   /etc/letsencrypt/live/cloud.%mydomain%.ru/fullchain.pem (failure)
> - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> 1 renew failure(s), 0 parse failure(s)
> IMPORTANT NOTES:
>  - The following errors were reported by the server:
> 
>    Domain: cloud.%mydomain%.ru
>    Type:   connection
>    Detail: Fetching
>    http://cloud.%mydomain%.ru/.well-known/acme-challenge/Jy12FZhM5sELCucSNeHXd4fsTjxpi_T0W0vi4HdUnTo:
>    Timeout during connect (likely firewall problem)

Both ports (80 and 443) is opened and accesseble. What I see after scipt, is that service Apache2 web server is stopped. And my cloud is down too. After i manualy start service - all working well.

Thank you!

**Comment by enoch85** [comment]
You shouldn't have to renew, that's done on a schedule in a cronjob.

`sudo -H`? Any specific reason to use `-H`?

**Comment by kostyainmadness** [comment]
Hi! 
When u said, i check:

`rogue@cloud:~$ crontab -l
no crontab for rogue
rogue@cloud:~$ sudo crontab -l
[sudo] пароль для rogue:
@monthly /var/scripts/letsencryptrenew.sh
@weekly /var/scripts/dockerprune.sh
@weekly /var/scripts/dockerprune.sh
@weekly /var/scripts/dockerprune.sh
rogue@cloud:~$
`
But its never work on schedule. I read that many people added a script to cron so as not to do it with hands, but it didn't bother me much.
I used with -H because without this parameter the script gave an error. I do not remember what was a error, but everything worked perfectly with this parameter.

**Comment by enoch85** [comment]
Ok, I never had any issues for the past 3 years with SSL renew and I'm using two VMs. One 16.04 and one 18.04 installed with the scripts in this repo.

The latest version works, so there are no "bug" to fix here. It seems more like an support issue to me which is best solved in the forums @ https://help nextcloud.com

Thanks for your report though!
