### ISSUE TITLE
Any plan to incorporate Live index service for Full text search app script?

### ISSUE THREAD

**Issue by Cliffhou** [nextcloud/vm#761]
Any plan to incorporate Live index service for Full text search app script?

**Comment by Cliffhou** [comment]
Please refer to this website:

https://github.com/nextcloud/fulltextsearch/wiki/Basic-Installation

Live index service

(will work with NC 14 and later)

To have your files continuously indexed, you'll need to run fulltextsearch:live. This can be easily achieved on systems running systemd with an unit /etc/systemd/system/nextcloud-fulltext-elasticsearch-worker.service file like this (make sure to adjust WorkingDirectory and path to occ):

[Unit]
Description=Elasticsearch Worker for Nextcloud Fulltext Search
After=network.target

[Service]
User=www-data
Group=www-data
WorkingDirectory=/var/www/nextcloud
ExecStart=/usr/bin/php /var/www/nextcloud/occ fulltextsearch:live
Nice=19
Restart=always

[Install]
WantedBy=multi-user.target

Enable and start:

systemctl enable nextcloud-fulltext-elasticsearch-worker.service
systemctl start nextcloud-fulltext-elasticsearch-worker.service

Note: If you want to index external SMB shares, add this to /usr/lib/tmpfiles.d/samba.conf:

d /var/run/samba 2775 root www-data - -

**Comment by Ark74** [comment]
Well, they are continuously indexed, just not in "real time".
Once your first fulltextsearch:index completes, then it will make a cronjob that will run periodically.

Now if you want a permanent monitoring & indexing for new files, the example you just give should work for the VM, since it manages php and fts, it doesn't touch ES, docker or any other component directly.

You might wanna test and submit a PR, right now I can't.

**Comment by Ark74** [comment]
@Cliffhou  also make sure that's what you want, since ES is no joke, it can consume a lot of resources depending on your setup and environment  see #755

**Comment by Ark74** [comment]
@enoch85 do you think this would be a good idea?

I mean, if the default of the VM is shipped with 2 GB RAM, and most vps plans comes with 1 GB / 2 GB RAM on the low tier.
This can backfire on performance, I believe that the default behavior is good enough for most users, maybe for single app users using FTS as a permanent live index could work fine.

But most don't stop at one :nerd_face:

**Comment by enoch85** [comment]
I don't think this is something the VM should handle per default. If the end user wants to tweak it, sure. But not per default in the VM due to

>the default of the VM is shipped with 2 GB RAM, and most vps plans comes with 1 GB / 2 GB RAM on the low tier.

Feel free to close.
