### ISSUE TITLE
Is this image supported for VirtualBox as well

### ISSUE THREAD

**Issue by smihael** [nextcloud/vm#762]
On my system VMware is unavailable, so I'm wondering if this configuration is supported for VirtualBox as well or has at least been tested

**Comment by enoch85** [comment]
@smihael It works, but VirtualBox network stack kind of sucks tbh. So I wouldn't recommend running VirtualBox. VMware is much better, and free.

Read more about it here: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm

Thanks for answering @MariusBluem :)
