### ISSUE TITLE
Error trying to install on server

### ISSUE THREAD

**Issue by frankont** [nextcloud/vm#765]
Steps to reproduce
Install on remote server with networked storage drive
Expected behaviour
Should install

Actual behaviour
Error

Server configuration
4cores 4gb ram 20GB installation 500GB data
Server version: (see your admin page)

How did you install the VM? (Scripted install from master OR Released version)
Master

Network
Do you use DHCP?
no
Is port 80 and/or 443 open?

Logs / Screenshots
https://0bin.net/paste/j-vKYxSJpu7E7JPx#Lk7+tG7dJpNLQqVWZgdtB+Z7IiO1X8V7oG9fJiRJVsB

Log file (/mnt/ncdata/nextcloud.log)
Insert your nextcloud.log file here
Installation log (command output)
Insert the CLI output here
Screenshoots

**Comment by frankont** [comment]
just stalled in the same place.. I’m not criticising your script, have been running this at home for a few months successfully  clearly an issue with my setup  and I’m looking for help

**Comment by enoch85** [comment]
OK,

**Comment by Ark74** [comment]
Also, just to mention, try to avoid running bash from curl.
Unless stated by the developers the bash scripts need to be run from a standard console tty, piping bash may cause issues.

I would recommend,
```
git clone repo/project
cd repo/project
bash script.sh
```
Cheers!

**Comment by frankont** [comment]
> OK, so what OS do you run?
> 
> Please provide more information. Thanks

Ubuntu 18.04, fresh installation on 20GB drive data drive 500GB 

I tried cloning the git repo and installing from there as suggested above and it was the same result

**Comment by enoch85** [comment]
@frankont Most likely this is a provider issue. Some providers doesn't install a full version of the OS and make custom changes that breaks the script. 

Digitalocean is fully supported, do you get the same result on with them?

**Comment by frankont** [comment]
I haven't tried on digital ocean, I need to make it work with my other provider. Would it work to not specify a separate data drive for install and then replace the data folder with a symbolic link to a folder on data drive?

**Comment by enoch85** [comment]
OK, then it's not supported. 

The scripts are fully tested on Digitalocean. It may work on other providers as well as long as it's a full installation of Ubuntu Server. 

If you find a solution to your problem, I'm happy to fix it but for now I don't have time. Sorry.

**Comment by enoch85** [comment]
> Would it work to not specify a separate data drive for install and then replace the data folder with a symbolic link to a folder on data drive?

No, you need a second drive, and I don't think that's related to the issue.

Note, the second drive should be unformatted, and unmounted.
