### ISSUE TITLE
fresh install, no network

### ISSUE THREAD

**Issue by bobdig** [nextcloud/vm#766]
## Steps to reproduce
1. Installing the current nextcloud VM from the website

## Expected behaviour
it is not reachable 

## Actual behaviour
the problem begins right @ the beginning of the installation, it says that the script failed to get an address from DHCP. 

If I am looking @ my homerouter I see it has got one. Then the script is telling me I should specify an IP Address. But even when I am doing this, it still uses the dhcp provided one.  
Then the installation goes on normally till the end and is doing updates and everything. But after the last restart it has no connectivity. When I log on to the machine as ncadmin there is no IP-Address shown @ IPv4 and 6, so no wonder it is not reachable. 

I installed it now 6 times in a row, every time the same error. The last try I only changed keyboard layout and timezone...

**Comment by enoch85** [comment]
Thanks for your report!

So, when you add static IP, exactly what do you type?

**Comment by enoch85** [comment]
Please also provide the full console output.

**Comment by bobdig** [comment]
Hm you got me rigth there, forgot the subnet...

**Comment by bobdig** [comment]
So I had overlooked it all the time to give a subnet, my bad.
Thank you for your fast reply.
