### ISSUE TITLE
startup script Invalid country. latam is not in ISO 3166-1 alpha-2 format

### ISSUE THREAD

**Issue by fantapereira** [nextcloud/vm#772]
## Steps to reproduce
1. log in as root
2. autorun the script
3. select keyboard and country

## Expected behaviour
the script should start

## Actual behaviour
after run the script i got the following errors

```
Current timezone is Etc/Universal
/var/scripts/nextcloud-startup-script.sh: line 301: ask_yes_or_no: command not found

Current default time zone: 'America/Argentina/Buenos_Aires'
Local time is now:      Mon Jan 21 11:55:53 -03 2019.
Universal Time is now:  Mon Jan 21 14:55:53 UTC 2019.
Checking current mirror...
Your current server repository is:
/var/scripts/nextcloud-startup-script.sh: line 319: ask_yes_or_no: command not found
Locating the best mirrors...
/var/scripts/nextcloud-startup-script.sh: line 325: spinner_loading: command not found
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-pip is already the newest version (9.0.1-2.3~ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (18.1)
Requirement already up-to-date: apt-select in /usr/local/lib/python2.7/dist-packages (2.1.0)
Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python2.7/dist-packages (from apt-select) (2.21.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from apt-select) (4.7.1)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->apt-select) (1.24.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->apt-select) (2018.11.29)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->apt-select) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->apt-select) (2.8)
Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in /usr/local/lib/python2.7/dist-packages (from beautifulsoup4->apt-select) (1.7.2)
Requirement already satisfied, skipping upgrade: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve>=1.2->beautifulsoup4->apt-select) (1.5)
Invalid country. latam is not in ISO 3166-1 alpha-2 format
Sorry but something went wrong. Please report this issue to  and include the output of the error message. Thank you!
apt-select -m up-to-date -t 5 -c -C latam failed
root@nextcloud:~#
```

## Server configuration

**Nextcloud server version:** 13

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
downloaded VM ova
## Network
**Do you use DHCP?**
yes
**Is port 80 and/or 443 open?**
yes
#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Thanks for the report.

> log in as root

You should not run the script as a pure root user.

Check the description [here](https://github.com/nextcloud/vm#installation) and [here](https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm). If you run the VM it's the same thing. Login with the sudo user, not root.

The `Invalid country. latam is not in ISO 3166-1 alpha-2 format` error is something in the `apt-select` software (for changing mirrors), so I suggest you report it [there](https://github.com/jblakeman/apt-select)

What you could do as a workaround is using UTC as time instead of your own timezone.

**Comment by fantapereira** [comment]
> Thanks for the report.
> 
> > log in as root
> 
> You should not run the script as a pure root user.
> 
> Check the description [here](https://github.com/nextcloud/vm#installation) and [here](https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm). If you run the VM it's the same thing. Login with the sudo user, not root.
> 
> The `Invalid country. latam is not in ISO 3166-1 alpha-2 format` error is something in the `apt-select` software (for changing mirrors), so I suggest you report it [there](https://github.com/jblakeman/apt-select)
> 
> What you could do as a workaround is using UTC as time instead of your own timezone.

Thanks for que quick reply...

i did logged as "ncadmin" and automatically ask me for the sudo password in order to run the script, so i assume is ok.

Regarding the ISO 3166-1 alpha2 i'll open an issue with they. the UTC workaround didn't work

thanks again!
