### ISSUE TITLE
Update from Version 13 to 15 VM Fails

### ISSUE THREAD

**Issue by kzieres61** [nextcloud/vm#773]
## Steps to reproduce
1. run the sudo bash /etc/var/scripts/update.sh and get an error screen saying that you can't got from version 13-15. 
Tried running the nextcloud ap updater to get version 14 and it fails with permission issues.

How do I get version 15 to install on my vm?

**Server OS** Ubuntu 16.0.4

**How did you install the VM?** Downloaded the OVA file

## Network
**Do you use DHCP?** Static

**Is port 80 and/or 443 open?** yes

**Comment by enoch85** [comment]
Hey @kzieres61 

The scripts are not designed to go from 13-15 or jump over major versions.

You have two options:
1. Ask in the [forum](https://help.nextcloud.com)
2. Buy [premium support](https://shop.hanssonit.se/product/premium-support-per-30-minutes/) and get it done while you sit back and relax.
