### ISSUE TITLE
nextcloud path

### ISSUE THREAD

**Issue by Omnimercador** [nextcloud/vm#778]
## Steps to reproduce
1. run script
2. [manually set NCPATH=/var/www/nextcloud and HTML=/var/www]
3.

## Expected behaviour
script should install . Instead, it aborts because of non-standard nextcloud/occ path (/www/var/html/nextcloud)  because of hardcoded occ in lib.sh

## Actual behaviour
process aborts with
/dev/fd/63: line 868: [: : integer expression expected
and 

+ occ_command -V
+ check_command sudo -u www-data php /var/www/nextcloud/occ -V
+ sudo -u www-data php /var/www/nextcloud/occ -V
Could not open input file: /var/www/nextcloud/occ

## Server configuration

**Nextcloud server version:** (see your admin page)
15

**Server OS** (Ubuntu server is default)
18.04 

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
yes
**Is port 80 and/or 443 open?**
yes
#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
You have to change it everywhere for it to work. So fork this repo and make your changes, then use that fork to install Nextcloud. This is nothing we will fix in the main scripts, and I don't see why you would want it in .../html..?
