### ISSUE TITLE
Setupscript didn't work

### ISSUE THREAD

**Issue by Zacke04** [nextcloud/vm#780]
## Steps to reproduce
1. Login to ubuntu for the first time
2.
3.

## Expected behaviour
The script should setup all things automaticly

## Actual behaviour
These errors came from the script
/dev/fd/63: line 833: [: : integer expression expected
/dev/fd/63: line 869: [: : integer expression expected

## Server configuration

**Nextcloud server version:** (see your admin page) 
cant access admin page

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
I used the realesedversion

## Network
**Do you use DHCP?**
yes

**Is port 80 and/or 443 open?**
no

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
I just tested the whole thing and there were no errors. 

Please be more specific.

**Comment by enoch85** [comment]
Closing as not valid.

**Comment by jon-bailey-nstar** [comment]
Hello @enoch85 - 
  I have reproduced something very similar to this bug report.

Steps:

1. Downloaded 17.0.1 of nextcloud/vm .OVA from github


  I just converted 17.0.1 from Github to an Amazon EC2 instance following the directions in the [AWS vm-import User Guide](https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-image-import.html) section of the

**Comment by enoch85** [comment]
@jon-bailey-nstar The second drive isn't mounted. Please install the VM correctly and mount the needed disks and it will work.

Good luck! :)
