### ISSUE TITLE
Increase Max Upload Size

### ISSUE THREAD

**Issue by xadox-1st** [nextcloud/vm#782]
I am using the **500GB_Nextcloud_Community_VM** Version.
Could you please explain how to increase the max_upload_size?

Actually it is set to 1000MB.
While looking into the /var/www/nextcloud/.htaccess I am not able to find the 1000 setting.

**Nextcloud server version:** 15.0.4

**Comment by enoch85** [comment]
There's no reason to make it larger than 1000 MB IMHO. If you want to upload large files, use the desktop client instead.

It's been a while since I wrote this, and stuff have changed since, but at least here's a start: https://www.techandme.se/increase-max-file-size/
