### ISSUE TITLE
ISP blocked ports and custom SSL install

### ISSUE THREAD

**Issue by odesey** [nextcloud/vm#784]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen
Need a way to use my own SSL certificate and ports other than 80\443

## Actual behaviour
Tell us what happens instead
Install is stuck while checking for ports 80\443

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
No, blocked from ISP

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots

This is more of a pre-sales issue that a support issue. 

I would prefer to do the NextCloud install via the script provided here( https://github.com/nextcloud/vm#installation ), and would buy the VM to show support for your great work. I have 2 issues that I need to get resolved however:

1.  My ISP blocks port 80 and 443 so that I can be forced to upgrade to the business account for more $$$. Is there anyway around this from the NextCloud side?

2. I have my own wildcard SSL certificate paid for and generated via GoDaddy, how can I use that SSL certificate instead of Letsencrypt?

Thanks.

**Comment by enoch85** [comment]
Please send me an email here: https://www.hanssonit.se/#contact
