### ISSUE TITLE
Add snapshot restore

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#791]
The VM uses ZFS in `/mnt/ncdata` and snapshots are automatically made on a schedule + every time the update script is run.

Why not then make it easier to restore if the user would want that?

**Comment by enoch85** [comment]
https://www.howtoforge.com/tutorial/how-to-use-snapshots-clones-and-replication-in-zfs-on-linux/

**Comment by enoch85** [comment]
@szaimen Is this something you could work on for 18.0.1?

**Comment by szaimen** [comment]
Hm probably not :/

**Comment by szaimen** [comment]
Yes, but that is no problem since there will be no differences between database and files if both are backed up while Nextcloud is in maintenance mode...

**Comment by szaimen** [comment]
I would say this enhancement is implemented with https://github.com/nextcloud/vm/pull/1913, no?
(it includes a system-restore option, too.)

**Comment by enoch85** [comment]
No, since BTRFS isn't supported.

**Comment by szaimen** [comment]
> ~~No, since BTRFS isn't supported~~

Why do you bring this up here? I know that BTRFS isn't supported hence I want to add it to the **not-supported folder**. I really don't get what the problem with that is. Maybe we should have a call to discuss this?

**Comment by enoch85** [comment]
Just an edit, didn't read properly :)

**Comment by sgtpepperaut** [comment]
why do you want to support snaphots in the machine itsself when most hypervisors offer this functionally already? file level versioning is implement in NC itself so I dont see the advantage. unless of course you have no control over the hypervisor :)

**Comment by szaimen** [comment]
Because one some instances it is installed without hypervisor so not in a VM ;)

**Comment by enoch85** [comment]
I've been thinking about this. Let's remove snapshots all togheter, or at least not make it default.

**Comment by szaimen** [comment]
> snapshots

Which snapshots? Zfs snapshots?
This problem will not occur with LVM snapshots since they occupy a pre-defined amount of space and don't get you into any space problems.
