### ISSUE TITLE
Missing the activate-ssl.sh

### ISSUE THREAD

**Issue by Disorganise** [nextcloud/vm#792]
## Steps to reproduce
1.  try to execute "sudo bash /var/scripts/activate-ssl.sh"
2.  list the contents of the /var/scripts folder

## Expected behaviour
1.  expected some info to kick off the SSL registration (actually I want to change the domain name and plan to follow https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6-83ePiqQz3_MrT/publish-your-server-online but didn't deactivate yet)
2.  expected to see the sh file

## Actual behaviour
1. `bash: /var/scripts/activate-ssl.sh: No such file or directory`

2. ```
ncadmin@dlmw:/var/scripts$ ls
history.sh  letsencryptrenew.sh  nextcloud.sh  setup_secure_permissions_nextcloud.sh  update.sh
```


## Server configuration

**Nextcloud server version:** (see your admin page)
Nextcloud 15.0.4

**Server OS** (Ubuntu server is default)
Description: Ubuntu 18.04.2 LTS
Release: 18.04
Codename: bionic

**How did you install the VM?** (Scripted install from master **OR** Released version)
Downloaded your image for hyper-v

## Network
**Do you use DHCP?**
yes

**Is port 80 and/or 443 open?**
yes (had to open 80 for the certificate renewal to work)

## Logs / Screenshots
<!--
ncadmin@dlmw:~$ sudo bash /var/scripts/activate-ssl.sh
bash: /var/scripts/activate-ssl.sh: No such file or directory
ncadmin@dlmw:~$ ls
releases
ncadmin@dlmw:~$ cd /var/scripts/
ncadmin@dlmw:/var/scripts$ ls
history.sh  letsencryptrenew.sh  nextcloud.sh  setup_secure_permissions_nextcloud.sh  update.sh
ncadmin@dlmw:/var/scripts$ sudo bash /var/scripts/activate-ssl.sh
bash: /var/scripts/activate-ssl.sh: No such file or directory
ncadmin@dlmw:/var/scripts$

-->

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by enoch85** [comment]
Thanks for your report!

If you activated SSL since before you need to download the latest version with `wget` to be able to activate it for the new domain as well since the script is removed on a successful run the first time.

You can find the script [here](https://github.com/nextcloud/vm/blob/master/lets-encrypt/activate-ssl.sh) and you need it in RAW format to be able to run it.

**Comment by Disorganise** [comment]
Great,  thanks.  I see the wget command is there on the instructions page.  Apologies if I missed it before.   I'm a Linux noob so if you added it as a result of this report, I cannot thank enough :)

**Comment by enoch85** [comment]
> I'm a Linux noob so if you added it as a result of this report, I cannot thank enough :)

I did. :)
