### ISSUE TITLE
avoid unnecessary chmod during updates

### ISSUE THREAD

**Issue by penzoiders** [nextcloud/vm#795]
Just a suggestion, I find the whole update process really smooth and I love it.

I just see a glitch in this smoothness... why is the update script chowning recursively the whole datastore? IMHO is not necessary at all and this will greatly speed up the update on large instances (also avoiding a lot of I/O on the underlying storage).

I would suggest to make a separate script to fix wrong ownerships and avoid running it every update.

feel free to close this issue if there is a real reason behind it, I'm curious to know why if so.

cheers!

**Comment by enoch85** [comment]
Yeah, you're right. I haven't had the time to test it yet though. I think I put it there for some reason.

Feel free to test and make a PR where it's removed, the last one in that case would make most sense to remove.

Thanks! :)

**Comment by enoch85** [comment]
I've checked it now, and it's there for a reason. When setting "pretty urls" it needs to be `www-data:www-data` but as the VM runs secure permissions we use the script to set the correct permissions again. That includes the datadir I'm afraid.

Maybe we could add another script just for that purpose, but it seems unnecessary. What do you think?

**Comment by penzoiders** [comment]
OK, let's do something like: keep the recursive ownership but exclude the data dir.
instead of a brutal -R I'm going to make an array of all folders and files in the NC directory and grep out the data dir before xarg-ing the chown.

as soon as I have a slice of time I'll take care.

wait for my PR.

cheers!

**Comment by enoch85** [comment]
Maybe check the current permissions of the datadir, and if it's set to `www-data:www-data`, then don't run the `chmod`?

**Comment by penzoiders** [comment]
oh, yes, it could be, maybe not recursively... just check the first level of subfolders.. if all is right then skip...

if some root:root or anything else than www-data:www-data is found on the first level of dirs under ncdata, then fix.

**Comment by enoch85** [comment]
if ! [ $(ls -ld ${NCDATA} | awk '{print$3$4}') == ${htuser}${htgroup} ]
then
    chown -R ${htuser}:${htgroup} ${NCDATA}/
fi
