### ISSUE TITLE
Lets Encrypt fails everytime (Godaddy domain)

### ISSUE THREAD

**Issue by supra89t** [nextcloud/vm#796]
## Steps to reproduce
1. Run the script sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh)"
2. After installing and rebooting nextcloud, login with the account ncadmin. Follow along and enter your domain for LE
3. Double check the names, ip's and all settings in router and domain host

## Expected behaviour
LE should certify the server and finish the installation

## Actual behaviour
LE times out and tries 2 more times. I entered in the _acme-challenge info into my domain and checked it with dnslookup and it sees the txt value. Yet it still fails.

## Server configuration

**Nextcloud server version:** 15

**Server OS** Ubuntu Server 18..04.02 Alt installer

**How did you install the VM?** (Scripted install from master **OR** Released version)
I used sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh)"
## Network
**Do you use DHCP?**
DHCP but reserved the mac to a static IP in my rounter
**Is port 80 and/or 443 open?**
yes both are open and after MANY failed attempts I even DMZ the ip of the VM
#### Log file (/mnt/ncdata/nextcloud.log)
Its empty...
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```
Checking if cloud.bohbotsystems.ca exists and is reachable...
certbot 0.28.0
certbot 0.28.0
/etc/apache2/sites-available/cloud.bohbotsystems.ca.conf was successfully created.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Running pre-hook command: service apache2 stop
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for cloud.bohbotsystems.ca
Waiting for verification...
Cleaning up challenges
Running post-hook command: service apache2 start
Failed authorization procedure. cloud.bohbotsystems.ca (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://cloud.bohbotsystems.ca/.well-known/acme-challenge/EU2U6p_xDZDS5TkWPgiBzTH2VxL3SWuiqbFAROr3nrc: Timeout during connect (likely firewall problem)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: cloud.bohbotsystems.ca
   Type:   connection
   Detail: Fetching
   http://cloud.bohbotsystems.ca/.well-known/acme-challenge/EU2U6p_xDZDS5TkWPgiBzTH2VxL3SWuiqbFAROr3nrc:
   Timeout during connect (likely firewall problem)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
It seems like no certs were generated, we will do 2 more tries.

#### Screenshoots
<!--
Please use http://imgur.com/ for screenshots. Thanks!
-->

**Comment by enoch85** [comment]
Thanks for your report.

> LE times out and tries 2 more times. I entered in the _acme-challenge info into my domain and checked it with dnslookup and it sees the txt value. Yet it still fails.

You need to wait for the domain to propagate properly before you continue. I couldn't find any TXT record when doing a lookup: https://www.whatsmydns.net/#TXT/cloud.bohbotsystems.ca

I tested myself just a few hours ago (installed a server for a customer) and it worked without a hitch.

If you need help installing you have two options:
1. Ask in the [forum](https://help.nextcloud.com/)
2. Get [paid support](https://shop.hanssonit.se/product/premium-support-per-30-minutes/)

**Comment by supra89t** [comment]
Thanks for the quick reply, but should it not be _acme-challange.cloud.domain.com ? and not cloud.domain.com ?

I had this working fine months ago, but a recent ISP upgrade forced my IP to change and I wanted to have a larger pool for storage so I upgraded the disks. Now it just does not want to work. I'll go check the forums but I was confused by the no txt @ cloud.domain.com when reading online Im seeing to just add _acme-challenge.subdomain 

Thanks.
