### ISSUE TITLE
nextcloud pre-configured does not start and does not start command line

### ISSUE THREAD

**Issue by alecsdc** [nextcloud/vm#797]
Vm does not start for the following errors:
- failed to start Network Name Resolution
- failed to start System Logging Service
- failed to start Login Service

## Steps to reproduce
1. Click Start on VMMachine (Oracle VM Virtual BOx)
2. Error 
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:  (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots

![snapcrab_vmcogesa in esecuzione - oracle vm virtualbox_2019-3-7_12-37-46_no-00](https://user-images.githubusercontent.com/48008783/53954229-e83c7a00-40d5-11e9-9c46-f0f46b7e4d14.png)

**Comment by enoch85** [comment]
My guess the import went wrong.

Have you checked the documentation at https://docs.hanssonit.se?

**Comment by alecsdc** [comment]
It worked perfectly until a few days ago. Had a problem with cluster10postgresql, I simply renamed the replorigin_checkpoint or maintenance = "true" in the config.php.

Only ceh now I do not even start the login and I do not know how to access the command line.

**Comment by enoch85** [comment]
>It worked perfectly until a few days ago. 

> I simply renamed the replorigin_checkpoint or maintenance = "true"

OK then this is not a bug, rather a configuration issue and can best be helped at the [forum](https://help.nextcloud.com).
