### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by ezraholm50** [nextcloud/vm#8]
1#
![deepinscreenshot20160614213129](https://cloud.githubusercontent.com/assets/13510720/16056855/acabecf6-3277-11e6-9b35-cb24a9c99fce.png)

Fresh Ubuntu 16.04
wget startup_script
bash startup_script

2#
Changing the password for the linux user and ncuser fails at "enter to fill in password" on both occasions. 

#3

**Comment by enoch85** [comment]
Have you tested the scripts separately? Because that's not how it's suppose to be. It works here, please revert back the latest change. Thx.

**Comment by enoch85** [comment]
Not valid, as discussed on IRC.
