### ISSUE TITLE
nextcloud_update.sh “extenstion” typo

### ISSUE THREAD

**Issue by unamundan** [nextcloud/vm#801]
https://github.com/nextcloud/vm/blob/9a2074c0537fe150594d7b353c3cafc71cf9422d/nextcloud_update.sh#L67

**`extenstion`**  should be  **`extension`**

**Comment by enoch85** [comment]
Thanks! Maybe you would want to fix it yourself? :) It's a great first starter issue.

**Comment by unamundan** [comment]
Would love to. Github for newbies can be _overwhelming._ If you can point me in the right direction this one time, I won’t ask again.

**Comment by enoch85** [comment]
Go to the file and press "edit" here:
![Screenshot from 2019-03-17 14:43:33](https://user-images.githubusercontent.com/4511254/54491993-10d92680-48c3-11e9-8b67-93cbceffc320.png)

The correct the typo and send a PR.

**Comment by unamundan** [comment]
I _think_ I just did. I clicked the pencil icon and was told I had to be on a branch (fork?). I chose master, and then I was able to edit. Thanks, Daniel. Hope my little piddly effort helps. I’ll keep my eyes open for more!

**Comment by enoch85** [comment]
Great!

Now you need to send it to this repo with a PR.

**Comment by unamundan** [comment]
Thanks for the hand-holding @enoch85 — I thought I’d finished it the first time but apparently I didn’t complete all steps. Looks like it stuck this time.
