### ISSUE TITLE
OnlyOffice & BitWarden: Port 8443

### ISSUE THREAD

**Issue by unamundan** [nextcloud/vm#804]
The Nextcloud VM v15.0.5 script offers to install OnlyOffice & BitWarden. Both require port 8443. Is this safe / reliable? The script offers no option to change the port for either.

**Comment by enoch85** [comment]
Onlyoffice isn't run on 8443. It's 443.

**Comment by unamundan** [comment]
Can I simple delete this issue ... as it’s a NON-issue?

**Comment by enoch85** [comment]
Yes, :)

**Comment by unamundan** [comment]
Thank you, Sir.
