### ISSUE TITLE
please enhance the readme

### ISSUE THREAD

**Issue by bish0polis** [nextcloud/vm#805]
1. What does it do?

It's understood it's a VM .. maybe.  Or maybe a script to build some kind of VM .  But on what platform, in what format (more than one?) or using which tools?  Is it a packer-built VM template, an AMI or just a docker image?

So many READMEs are missing their Elevator Speech.

2. what does it need?

Which versions of tools does it need in order to start it up?

BONUS:

3. what's its release structure?

4. what's its upstream sources, if any?  We want to reassure ourselves of its stability.

5. What's its license?

**Comment by enoch85** [comment]
Hi! Thanks for the suggestions! You are welcome to create a PR for this, or work on the current one linked in this issue.

**Comment by bish0polis** [comment]
Love to, except

1. I can't answer

2. I can't answer

3. I can't answer

4. I can't answer

5. GPL3.  Fantastic!

I'm going to have to defer to someone who knows enough about the project.  Me on a drive-by isn't going to provide the info required (see also "blind leading the blind").

But thanks for the well-considered response.

**Comment by unamundan** [comment]
Hey @bish0polis —

As a matter of fact, I’ve been working behind the scenes _on exactly that_ for the past couple of days. I’m taking a shot at transmogrifying the Nextcloud VM’s README.MD into a fleshier feast. With  @enoch85’s help, it’s my goal to address all the questions you raise and more.

I’m new to the project, having found it when I decided I wanted a home-hosted cloud service. Nextcloud seemed to be the best choice, and NVM seemed to put it within reach for a generally-confidant computer dude with _no Linux confidence_.

I believe my immersion over the past couple of months puts me in a relatively good, _fresh_ position to address average end user questions with enough technical shellack for folks to grok The Beast, if only a tad better. At the beginning, I wasn’t even sure _what_ to ask. The landscape was a  foreign film with equally foreign subtitles.

I had a zillion unanswered questions and found scattered shards of evidence in a zillion places. When I sensed I’d discovered a relevant clue, it often felt like staring at indecipherable mystic runes: _the answer was **right there** (wasn’t it?) but somehow no less esoteric or confusing._ I, possibly like you and many others, found the patient’s grisly _body parts_ sprinkled all over the ’net. For the longest time — perhaps even still now — I could only conjure a forensically indistinct Rorschach of the _corpus vile_.

Hopefully I can help pave at least a few city blocks of the informational potholes that bruised my brain on this bumpy road ... so others’ quests aren’t quite as injurious.

I aims t’ _try_ an’ fixit within the next week.

And no: It won’t be an extended linguistic riff like this too-long response. I trust Billy Shakesdude said it best: _“Brevity is the soul of wit.”_ So ... let’s ... _drop some briefs?_

**Comment by bish0polis** [comment]
Ok, neat.  If your ticket is a better ticket, then link to it and close this one.

**Comment by unamundan** [comment]
My ticket was literally one after yours, @bish0polis. It’s [here](https://github.com/nextcloud/vm/pull/806). The rewrite is _not_ there yet.

**Comment by enoch85** [comment]
@bish0polis So I merged some improvements. Feel free to work on the rest. Editing a README is very simple, just change the text basically.

**Comment by enoch85** [comment]
@bish0polis Should we consider this done?

**Comment by bish0polis** [comment]
> link to it and close this one 

Yep.  Thanks !
