### ISSUE TITLE
ONLYOFFICE cannot be reached

### ISSUE THREAD

**Issue by BurningTheSky** [nextcloud/vm#808]
## Steps to reproduce
Try and open a document in OnlyOffice via the web interface

## Expected behaviour
Document to be opened in OnlyOffice

## Actual behaviour
New tab is opened with "ONLYOFFICE cannot be reached. Please contact admin" at the top

## Server configuration

**Nextcloud server version:** 15.0.5

**Server OS** Ubuntu 18.04

**How did you install the VM?** Followed instructions from main page, OnlyOffice installed later using "sudo bash onlyoffice.sh"

## Network
Static, both ports open

## Screenshot
[https://oi1068.photobucket.com/albums/u460/BurningTheSky/onlyoffice%20error_zps0a6ovsk8.png](url)

**Comment by enoch85** [comment]
Thanks for your report. 

It works here, so most likely a configuration issue. 

- Is port 80 + 443 open against the server?
- Did the script end with a successful status?
- Is SSL activated on both the main domain and the office domain?

**Comment by BurningTheSky** [comment]
Ports are open, it’s hosted on the same server as the Nextcloud install and browsing to the office url appears to direct to the nextcloud installation, should there be a difference in config? Should office be on a separate server or ports if the same server?

Script ended successfully and SSL is configured for both.

$ sudo docker ps -a
[sudo] password for: 
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                            NAMES
94bcb6f4a3ca        onlyoffice/documentserver   "/bin/sh -c /app/onl…"   About an hour ago   Up 31 minutes       443/tcp, 127.0.0.3:9090->80/tcp                  onlyoffice
198e19576ea8        v2tec/watchtower            "/watchtower --clean…"   7 days ago          Up 31 minutes                                                        watchtower
815139853fce        ark74/nc_fts                "/usr/local/bin/dock…"   7 days ago          Up 31 minutes       0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp

Also, whenever I ssh to the server I get this:
bash: /var/scripts/instruction.sh: No such file or directory
[sudo] password for : 

What is causing that? Can I stop it?

**Comment by enoch85** [comment]
OK, so the initial script didn't run properly, or got aborted before it was finished.

Please download the OVA again, remove the old one, and import the new then run the installation from start again.

**Comment by BurningTheSky** [comment]
Ah ok, I have just been running the script rather than using the pre-built OVA

**Comment by enoch85** [comment]
Create a new server and run the script again.

**Comment by enoch85** [comment]
I just made a new release. Please try that and re-open this ticket if you think there's a bug.

Thanks!
