### ISSUE TITLE
systemctl reload apache2 failed

### ISSUE THREAD

**Issue by 23571A** [nextcloud/vm#818]
Steps to reproduce
1. Try installing Nextcloud

## Expected behaviour
Tell us what should happen
I should see a "Nextcloud has finished installing!"
## Actual behaviour
Tell us what happens instead
I see the error "systemctl reload apache2 failed", and after inspecting journalctl -xe, it tried stopping and starting the service too quickly, therefore not completing the installation
## Server configuration

**Nextcloud server version:** (see your admin page) 15.0.5

**Server OS** (Ubuntu server is default) Ubuntu 18.04 LTS server

**How did you install the VM?** (Scripted install from master **OR** Released version) Released version

## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes
#### Log file (/mnt/ncdata/nextcloud.log)

Don't have one

#### Installation log (command output)
```
systemctl reload apache2 failed 
```
(i think, i accidentally rebooted the machine before copying lol)

**Comment by enoch85** [comment]
Did you install with the VM or with the scripts?

**Comment by enoch85** [comment]
Also, where in the installation process did you get this error?

**Comment by 23571A** [comment]
With VM, after installing onlyoffice, talk, etc.

**Comment by enoch85** [comment]
OK, please try again, probably it was just a temporary error.

If not, please let me know and try to be more specific. It's hard to debug "it doesn't work".

Thanks.
