### ISSUE TITLE
Deploy Appliance 

### ISSUE THREAD

**Issue by y-tech100** [nextcloud/vm#823]
Hi,
when I deploy Hyper-V VM of nextcloud on ubuntu 18,
we get error 503 when I check the MySQL/mariadb not installed with the script,

why when I want to download new appliance I need to pay money again.

pleace advice how resolve deploy appliance.

regard

yossi bar.

**Comment by enoch85** [comment]
Hi @y-tech100 

Thanks for reaching out!

Since the VM is continuously updated you can't use an old version with the new scripts. If you want to run your old VM (Ubuntu 16.04) on Ubuntu 18.04 you need to migrate to a new VM.

Please send me an email instead here: https://www.hanssonit.se/#contact
