### ISSUE TITLE
Won't recognize my second drive (on Proxmox LXC container)

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#825]
## Steps to reproduce
1. Run the script: `sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh)"`

## Expected behaviour
Should complete.

## Actual behaviour
Script fails.

## Server configuration
```
df -h
Filesystem                        Size  Used Avail Use% Mounted on
/dev/mapper/pve-vm--200--disk--0   20G  2.4G   17G  13% /
/dev/mapper/pve-ncdata             40G   49M   38G   1% /mnt/ncdata
```

**How did you install the VM?** (Scripted install from master **OR** Released version)
Released version

## Network
**Do you use DHCP?**
YES

**Is port 80 and/or 443 open?**
YES

I investigated `format-sdb.sh` and on line 28 I found that when I run `cat /sys/devices/virtual/dmi/id/sys_vendor` on my machine, I get a value that's not in the list (on lines 29-57).

What I get is `Apple Inc.` because I'm running Debian/Proxmox on a Mac Pro...

@enoch85 Daniel, any chance you could help me figure out how to figure this out for my use case?

The 1st script completes even though it tells me that "It seems like you didn't mount a second disk. To be able to put the DATA on a second drive formatted as ZFS you need to add a second disk to this server. This script will now exit. Please mount a second disk and start over."

But after the reboot, it fails. Here is the output after the reboot: https://0bin.net/paste/34URELcBn7-040Wu#MNPsVg3fGeDAfCOo2tH-2TyYhYhEnnQR+F8qMFiF2m5

Thank you so much!

I think the issue might be that on line 53 of format-sdb.sh, the `partprobe /dev/sdb` fails because my ncdata drive is not mounted at /dev/sdb, but instead at /dev/mapper/pve-ncdata

Thank you again! 🙏

**Comment by enoch85** [comment]
If you want to run it in Proxmox you have to do the scripted installation.

**Comment by enoch85** [comment]
If it doesn't work, please reopen.

**Comment by thejohnha** [comment]
@enoch85 Hi Daniel - thanks for your help. I ran the script initially via:
`sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh)"`

Are you saying I should git clone the repo and try to run the scripts individually?

Thank you!

**Comment by enoch85** [comment]
No, you don't need to clone. Running that command fixes everything.

**Comment by thejohnha** [comment]
> If you want to run it in Proxmox you have to do the scripted installation.

OK I think you may have misunderstood because I did run this with the scripted installation.

I tried with both Yes and No to the question `Do you want to choose disk by yourself?`

**Comment by enoch85** [comment]
To choose the default, just hit Enter through the whole installation.

I don't own a Proxmox box, nor an Apple computer so I can't test I'm afraid. 

Feel free to dig in and solve the issue. :)

**Comment by enoch85** [comment]
cc @zalonic on this one which is the largest contributor of the format-sdb script.

**Comment by thejohnha** [comment]
> To choose the default, just hit Enter through the whole installation.
> 

Yep I did try with the defaults and with manually choosing the disk. What is strange is when I select to `choose disk by yourself` it never gives me a choice.. Is it supposed to give a menu of disks to choose from?

**Comment by enoch85** [comment]
> Is it supposed to give a menu of disks to choose from?

Just to be clear here, you need to add two separate drives to the VM. One for OS and one for DATA. It seems like you added one when reading the `df- h` output, but then again, I never used or owned a Proxmox Hypervisor.

**Comment by enoch85** [comment]
What's the complete output of `cat /sys/devices/virtual/dmi/id/sys_vendor`?

**Comment by enoch85** [comment]
Also, what's the output of `fdisk -l`?

**Comment by thejohnha** [comment]
> cat /sys/devices/virtual/dmi/id/sys_vendor
`Apple Inc.`

> Also, what's the output of `fdisk -l`?
blank - nothing

**Comment by thejohnha** [comment]
> > Is it supposed to give a menu of disks to choose from?
> 
> Just to be clear here, you need to add two separate drives to the VM. One for OS and one for DATA. It seems like you added two drives correctly when reading the `df- h` output, but then again, I never used or owned a Proxmox Hypervisor.

Yes, I spent some time trying to figure out how to add the second drive... If this helps:

![Screen Shot 2019-04-29 at 17 14 45](https://user-images.githubusercontent.com/6325833/56927516-60a23480-6aa2-11e9-8d9a-b828158dfe2d.jpg)

**Comment by enoch85** [comment]
What I would like to know is the name of your second disk. Typically it's sd**b** in a "normal" Linux environment, but could differ depending on which hypervisor you use.

Try to setup a new enviroment, without running the script, then try to figure out the drive "letter" of the second disk.

Windows: C:, D:
Linux: sda, sdb
Proxmox on Apple?

**Comment by enoch85** [comment]
It seems like your second disk isn't mounted properly upon reboot, or it doesn't get the correct permissions for some reason. My best guess is the first option.

**Comment by enoch85** [comment]
Please post the output of: `pvesm status`

**Comment by enoch85** [comment]
Here is some interesting info: https://pve.proxmox.com/wiki/Physical_disk_to_kvm

Try `lshw -class disk -class storage`

**Comment by enoch85** [comment]
You can also try: `lsblk`

**Comment by thejohnha** [comment]
> It seems like your second disk isn't mounted properly upon reboot, or it doesn't get the correct permissions for some reason. My best guess is the first option.

The disk is mounted correctly at /mnt/ncdata... I made sure of that...

I ran this on the Proxmox host:

```root@proxmox:~# pvesm status
Name             Type     Status           Total            Used       Available        %
Mobius1           dir     active       960380628       646313504       265212664   67.30%
local             dir     active        98559220         4384420        89125252    4.45%
local-lvm     lvmthin     active       851013632       563626328       287387303   66.23%```


The `local-lvm` uses most of the primary SSD, and I used [these instructions](https://pve.proxmox.com/wiki/LVM2#Create_a_extra_LV_for_.2Fvar.2Flib.2Fvz) to create a new logical volume and then mount it as a second drive in the guest.

`lsblk' lists all of the physical drives I have connected to the Proxmox node...  I think I have 16 drives connected at the moment:

```
root@nc:~# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0   2.7T  0 disk
└─sda1   8:1    0   2.7T  0 part
sdb      8:16   0   2.7T  0 disk
└─sdb1   8:17   0   2.7T  0 part
sdc      8:32   0   7.3T  0 disk
└─sdc1   8:33   0   7.3T  0 part
sdd      8:48   0   7.3T  0 disk
└─sdd1   8:49   0   7.3T  0 part
sde      8:64   0   1.8T  0 disk
└─sde1   8:65   0   1.8T  0 part
sdf      8:80   0   1.4T  0 disk
└─sdf1   8:81   0   1.4T  0 part
sdg      8:96   0 931.5G  0 disk
└─sdg1   8:97   0 931.5G  0 part
sdh      8:112  0   1.8T  0 disk
└─sdh1   8:113  0   1.8T  0 part
sdi      8:128  0 931.9G  0 disk
├─sdi1   8:129        1M  0 part
├─sdi2   8:130      256M  0 part
└─sdi3   8:131  0 931.6G  0 part
sdj      8:144  1 931.5G  0 disk
└─sdj1   8:145  1 931.5G  0 part
sdk      8:160  1 931.5G  0 disk
└─sdk1   8:161  1 931.5G  0 part
sdl      8:176  1 931.5G  0 disk
└─sdl1   8:177  1 931.5G  0 part
sdm      8:192  1 931.5G  0 disk
└─sdm1   8:193  1 931.5G  0 part
sdn      8:208  1   1.4T  0 disk
└─sdn1   8:209  1   1.4T  0 part
sdo      8:224  1   2.7T  0 disk
└─sdo1   8:225  1   2.7T  0 part
sdp      8:240  1   2.7T  0 disk
└─sdp1   8:241  1   2.7T  0 part
```

**Comment by thejohnha** [comment]
> Just to be clear here, you need to add two separate drives to the VM. One for OS and one for DATA.

p.s. why the new requirement to have 2 drives to use this script? Just curious... It feels like it adds more complexity and not a lot of advantage. Perhaps the script could allow the user to choose installation on a single drive machine? (default it to 2 drives if you want..)

**Comment by enoch85** [comment]
> p.s. why the new requirement to have 2 drives to use this script?

Because it's better. With this setup the OS disk can fail without affecting the data, and the data drive can fail without affecting the OS. It's easier to backup. It uses ZFS and so on.

You need two drives, not logical volumes.

**Comment by thejohnha** [comment]
> You need two drives, not logical volumes.

The logical volume is at the host level. It exposes it as a drive at the guest level.

**Comment by enoch85** [comment]
It seems to me that you have like 10 drives from that `lsblk -f` output.

Don't mount anything before running the install script, just two plain drives. Simple as that. The script handles the mounting and so on.

> Under static/format-chosen.sh:27 it should have a separate if clause that recognizes this correctly.

Yes, that's probably the case.

**Comment by thejohnha** [comment]
> Don't mount anything before running the install script, just two plain drives. Simple as that. The script handles the mounting and so on.

The drives are mounted automatically by proxmox. You don't need to mount the drives manually. It is very reliable - I have this type of setup for several guest machines...

**Comment by thejohnha** [comment]
When I select to choose disk by yourself it never gives me a choice.. Is it supposed to give a menu of disks to choose from?

**Comment by enoch85** [comment]
Related: https://github.com/nextcloud/vm/issues/699

**Comment by enoch85** [comment]
> The drives are mounted automatically by proxmox. 

If the disk is mounted it can't format it with ZFS. I'm not sure we mean the same thing when we say "mounted".

> Is it supposed to give a menu of disks to choose from? 

Yes

**Comment by thejohnha** [comment]
> If the disk is mounted it can't format it with ZFS. I'm not sure we mean the same thing when we say "mounted".

I see. Is the script forcing the use of ZFS for the data drive?

> > Is it supposed to give a menu of disks to choose from?
> 
> Yes

It never gives me a menu...

**Comment by enoch85** [comment]
> So the script is expecting an unformatted drive as the data drive? 

Yes

> I see. Is the script forcing the use of ZFS for the data drive?

Yes

**Comment by thejohnha** [comment]
Feels like this script has gone beyond just installing nextcloud and is now making architecture decisions about your computer. Just consider... this script, which is supposed to install Nextcloud, is now _formatting drives on your computer!_ Seems like an overreach.

I'd like to propose some user questions in the script to bypass some of these opinionated system setup items.

Perhaps instead of mandating these system-level items, allow the user to choose between:

- Using a single disk versus two separate disks
- Install TLS cert or not
- ?

Keep the opinionated setup as defaults if you like. But I think this would allow more flexible usage of the install scripts...

For example, I'm using haproxy which terminates TLS at the proxy... on a trusted network, this means I don't need to use letsencrypt on the nextcloud box.

What do you think?

**Comment by enoch85** [comment]
> ...........Seems like an overreach.

Well... the thought behind the VM is that you should only need to download Ubuntu Server 18.04, `wget` the script, run it, and then you have Nextcloud installed in the best possible way, and at the same time as easy as possible. That includes formatting drives and setup the system that will run Nextcloud. 

You should never setup Nextcloud on a previous used system, and if you do there are checks in place that will stop you from doing so. You are also warned that the disk are being formatted (which shouldn't even be needed as it should be installed on a clean system).

You are free to edit the script to fit your needs, and I would appreciate if you send a PR this way to help others with the same issues that you are facing. You are also free to use something else than the VM if it doesn't suit you. 

> For example, I'm using haproxy which terminates TLS at the proxy... on a trusted network, this means I don't need to use letsencrypt on the nextcloud box.

Yes, I also run a proxy in front of my servers so the TLS happens on that. You are not forced to use Let's Encrypt in the VM if you don't want to, so I don't follow what your point is here.

I do this on my spare time and have a full time job besides this and been doing so since Nextcloud was founded back in 2016. Due to lack of time I do my best to keep it updated and add new features, but I'm not a magician.

**Comment by thejohnha** [comment]
> Yes, I also run a proxy in front of my servers so the TLS happens on that. You are not forced to use Let's Encrypt in the VM if you don't want to, so I don't follow what your point is here.

Yes - exactly like this. I'm suggesting to put a question in the script to allow the user to choose between 2 disks or 1.

I do know this is a volunteer effort for you - and I appreciate your time and attention to making it great.  :-)

**Comment by enoch85** [comment]
OK, so it turns out that LXC is not supported. --> closing.

Please open a new ticket as a Feature Request for LXC instead and I'll have a look when I have time.
