### ISSUE TITLE
Check whether gpg is installed

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#826]
## Steps to reproduce
1. sudo bash nextcloud_install_production.sh
2.
3.

## Expected behaviour
There should be no errors

## Actual behaviour
These 2 errors occur:
```
...
/dev/fd/63: line 715: gpg: command not found
/dev/fd/63: line 716: gpg: command not found
[\] Setting secure permissions...
Creating possible missing Directories
chmod Files and Directories
[/] chown Directories
[\] chmod/chown .htaccess
...
```

**Server OS** (Ubuntu server is default)
Proxmox Ubuntu 18.04 LXC container image

**How did you install the VM?** (Scripted install from master **OR** Released version)
```
git clone https://github.com/nextcloud/vm
cd mv
sudo bash nextcloud_install_production.sh
```

Just wondering if we should add a check for whether gpg is installed at the beginning of `nextcloud_install_production.sh` with a few lines like:

```
# Install gpg if not existing
if [ "$(dpkg-query -W -f='${Status}' "gpg" 2>/dev/null | grep -c "ok installed")" == "1" ]
then
    print_text_in_color "$IGreen" "gpg OK"
else
    apt update -q4 & spinner_loading
    apt install curl -y
fi
```

**Comment by enoch85** [comment]
I will fix it. 

Thanks for noticing!
