### ISSUE TITLE
Unable to upload if shared as "Allow upload and editing"

### ISSUE THREAD

**Issue by SchmelAtWork** [nextcloud/vm#827]
Hello!

Steps to reproduce:
1. Domain user shares a folder with permission "Allow upload and editing". 
2. Some user, let's say, Nick, that have link to shared folder can't upload files - nothing is happened (either via drag'n'drop or via +) but can create new folders, see files and able to download them.
3. If domain user change permission to "File drop (upload only)" then Nick able to upload files.

While Nick tries to upload no data is written to apache access.log and nextcloud.log

NC 16.0
Ubuntu 19.04 installed from iso. 
80 and 443 is opened. 443 secured by LetsEncrypt.
Address - static, public
HTTP server - Apache/2.4.39.
PHP 7.2.

**Comment by enoch85** [comment]
> Ubuntu 19.04 installed from iso

Strange that that even works. It shouldn't be supported.

Please use Ubuntu 18.04 **server** and see if you get the same error. Most probably it's a bug in **nextcloud/server**

**Comment by enoch85** [comment]
I'll close this for now, please reopen if you think this is a bug with the VM and not the Nextcloud Server itself.

**Comment by SchmelAtWork** [comment]
Hello!

Sorry for delay, we had 5 holidays in the row.

I confirm the same behavior in 18.04.2 LTS

root@nc:/tmp# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
root@nc:/tmp# php -v
PHP 7.2.17-0ubuntu0.18.04.1 (cli) (built: Apr 18 2019 14:12:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
root@nc:/tmp# apache2 -v
Server version: Apache/2.4.39 (Ubuntu)
Server built:   2019-04-02T20:30:26

**Comment by enoch85** [comment]
This is a Nextclod bug, not in the VM: https://github.com/nextcloud/server/pull/15173
