### ISSUE TITLE
This version of Nextcloud requires at least PHP 7.1

### ISSUE THREAD

**Issue by fabiankhh** [nextcloud/vm#830]
## Steps to reproduce
1. root@cloud:/var/scripts# bash nextcloud_update.sh
2.
3.

## Actual behaviour
This version of Nextcloud requires at least PHP 7.1<br/>You are currently running 7.0.33-0ubuntu0.16.04.4. Please update your PHP version.Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ -V failed

## Server configuration

**Nextcloud server version:** 15.0.6

**Server OS** Ubuntu 18.04.2 LTS

**How did you install the VM?** Scripted install from master

## Network
DHCP

**Is port 80 and/or 443 open?**
443

#### Log file (/mnt/ncdata/nextcloud.log)
```
[nextcloud.zip](https://github.com/nextcloud/vm/files/3138519/nextcloud.zip)
```

#### Installation log (command output)
```
[UpdateBefehl.txt](https://github.com/nextcloud/vm/files/3138498/UpdateBefehl.txt)

```

**Comment by enoch85** [comment]
This is intentional as you can't run PHP 7.0 with Nextcloud 16. 

If you need help, please visit the shop. Upgrading PHP would take around 1 hour: https://shop.hanssonit.se/product/premium-support-per-30-minutes/
