### ISSUE TITLE
Found an error when installing Fail2Ban

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#831]
![Screen Shot 2019-05-06 at 15 27 07](https://user-images.githubusercontent.com/6325833/57249679-9059bb00-7013-11e9-9297-d643de37ef02.jpg)

**Comment by enoch85** [comment]
It's from here: https://github.com/nextcloud/vm/blob/master/apps/fail2ban.sh#L28 most probably.

It searches the whole root dir . I never saw it before so maybe it's a glitch.

**Comment by enoch85** [comment]
This would solve it I think: 

`NCDATA="$(grep 'datadir' "$NCPATH"/config/config.php | awk '{print $3}' | cut -d "'" -f2)"``

In other words, only search in the NC datadir.

**Comment by enoch85** [comment]
But... https://ubuntuforums.org/showthread.php?t=2151624

And it's already run as root. Strange.

**Comment by enoch85** [comment]
@thejohnha Do you get the same error every time?

**Comment by thejohnha** [comment]
> @thejohnha Do you get the same error every time?

@enoch85 I do.

**Comment by enoch85** [comment]
Could you try to change to the suggested fix and see if that helps?

**Comment by enoch85** [comment]
I can't reproduce this on VMware.

**Comment by enoch85** [comment]
@thejohnha Hey, did you figure out what's causing this?

**Comment by enoch85** [comment]
I've installed Fail2ban several times now, never saw this. Feel free to reopen if the issue persists.
