### ISSUE TITLE
Nextcloud would not load from freshly deployed OVA

### ISSUE THREAD

**Issue by soleroitsolutionsltd** [nextcloud/vm#853]
## Steps to reproduce
1. Navigate to nexcloud login page

## Expected behaviour
Login page would show up

## Actual behaviour
Internal Server Error

## Server configuration

**Nextcloud server version:**  
No access to it but the one packaged in https://github.com/nextcloud/vm

**Server OS** (Ubuntu server is default)
18.04.2

**How did you install the VM?** (Scripted install from master **OR** Released version)
Deployed OVA to ESX server

## Network
**Do you use DHCP?**
No

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots
From Apache log:
----
[Tue Jun 18 06:24:53.289718 2019] [proxy_fcgi:error] [pid 10314:tid 140448264894208] [client 172.16.110.27:58506] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.50' (T_DNUMBER), expecting ')' in /var/www/nextcloud/config/config.php on line 8\n'
[Tue Jun 18 06:24:53.527928 2019] [proxy_fcgi:error] [pid 10314:tid 140448264894208] [client 172.16.110.27:58506] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.50' (T_DNUMBER), expecting ')' in /var/www/nextcloud/config/config.php on line 8\n'
[Tue Jun 18 06:28:59.338095 2019] [proxy_fcgi:error] [pid 10314:tid 140448264894208] [client 172.16.110.27:58573] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.50' (T_DNUMBER), expecting ')' in /var/www/nextcloud/config/config.php on line 8\n'
[Tue Jun 18 06:28:59.691515 2019] [proxy_fcgi:error] [pid 10314:tid 140448264894208] [client 172.16.110.27:58573] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.50' (T_DNUMBER), expecting ')' in /var/www/nextcloud/config/config.php on line 8\n'
[Tue Jun 18 06:29:21.892206 2019] [proxy_fcgi:error] [pid 10314:tid 140447687034624] [client 172.16.110.27:58574] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.50' (T_DNUMBER), expecting ')' in /var/www/nextcloud/config/config.php on line 8\n', referer: http://172.16.50.210/nextcloud/
[Tue Jun 18 06:40:28.765177 2019] [mpm_event:notice] [pid 10311:tid 140448385133504] AH00491: caught SIGTERM, shutting down
[Tue Jun 18 06:40:57.151215 2019] [ssl:warn] [pid 1761:tid 140656946125760] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 18 06:40:57.329618 2019] [ssl:warn] [pid 1797:tid 140656946125760] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 18 06:40:57.416237 2019] [mpm_event:notice] [pid 1797:tid 140656946125760] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jun 18 06:40:57.416308 2019] [core:notice] [pid 1797:tid 140656946125760] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 18 06:47:48.864025 2019] [mpm_event:notice] [pid 1797:tid 140656946125760] AH00491: caught SIGTERM, shutting down
[Tue Jun 18 06:48:23.542776 2019] [ssl:warn] [pid 1840:tid 140242662824896] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 18 06:48:23.569050 2019] [ssl:warn] [pid 1897:tid 140242662824896] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 18 06:48:23.571351 2019] [mpm_event:notice] [pid 1897:tid 140242662824896] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Jun 18 06:48:23.571400 2019] [core:notice] [pid 1897:tid 140242662824896] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 18 06:51:51.814636 2019] [proxy_fcgi:error] [pid 1899:tid 140242006759168] [client 172.16.110.27:58633] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '.50' (T_DNUMBER), expecting ')' in /var/www/nextcloud/config/config.php on line 8\n', referer: http://172.16.50.210/nextcloud/

**Comment by enoch85** [comment]
Please redo the whole setup again by re-imnporting the VM and deleting the old one. I can't reproduce the errors you are getting.

If you want me to investigate, please be more precise in your "Steps to reproduce." 

Thanks.

**Comment by enoch85** [comment]
@soleroitsolutionsltd Please redo the whole setup again by re-importing the VM and deleting the old one. I can't reproduce the errors you are getting.

Please be more precise in your "Steps to reproduce." What *exact* steps did you take?

Thanks.

**Comment by enoch85** [comment]
@soleroitsolutionsltd Any update here? Did it work to re-import the OVA and try again? It seems to me from the log that you made some manual change to the config file and got it wrong. Is that the case, or do you think it's a bug in the scripts?

**Comment by soleroitsolutionsltd** [comment]
Hi
I did re-deploy the exact same VM and everything went well. I deliberately elected nor to install/ configure any of the optional modules so it might be related... not sure. In any case a happy camper here :)
