### ISSUE TITLE
Restarted and now NO IPv4

### ISSUE THREAD

**Issue by cbacit** [nextcloud/vm#855]
## Steps to reproduce
1. I was configuring the system set lets's encrypt and DNS etc.  I had run the static ip... Then I restarted the host via putty and now there is no IPv4 address...
2.
3.

## Expected behaviour
Tell us what should happen
The config should have stayed for the static but didn't.
## Actual behaviour
Tell us what happens instead
I lost the ipv 4 address. The name of the host there but there is no IPV 4 address or anything why?
## Server configuration

**Nextcloud server version:** (see your admin page)
16.01
**Server OS** (Ubuntu server is default)
18.x
**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes...
#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file herels

```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi and welcome to Github!

You probably entered the values wrong, or gave the host a wrong IP address.

Please import the VM again and be extra careful when adding the static IP. Please also do the static IP from the CONSOLE as it will break over SSH since the SSH connection happens on the current IP.

Thanks.

**Comment by cbacit** [comment]
Right now in the esxi console... I still have access...
![Annotation 2019-06-26 122833](https://user-images.githubusercontent.com/47609657/60201576-2e952080-980e-11e9-9656-778fb64f9a73.png)


I had the right host and static ip... I was working in the config...  What command would you suggest to add my static ip back?

**Comment by cbacit** [comment]
I would really prefer not to have to re-run through the script again..

**Comment by enoch85** [comment]
You need to re-run the [static IP script](https://github.com/nextcloud/vm/blob/master/static/static_ip.sh).

So fetch the RAW version with `wget` and then run it with `sudo bash`.

**Comment by cbacit** [comment]
![2019-06-26_12-34-26](https://user-images.githubusercontent.com/47609657/60201897-12de4a00-980f-11e9-8f0b-4a33cbe0ddae.jpg)


Where is that static IP script located?...

**Comment by enoch85** [comment]
> So fetch the RAW version with wget and then run it with sudo bash.

You need to get a copy of the script to your VM.

**Comment by cbacit** [comment]
Ok... I can do line 8 b/c it can't talk to the internet...  just the vmware infrastructure...

**Comment by cbacit** [comment]
Is that okay?

**Comment by enoch85** [comment]
The you need to set the IP manually with netplan: https://netplan.io/examples

**Comment by cbacit** [comment]
Ok... When I nano or vi... To that file... It is blank... I don't mind populating it... But what Ethernet: should I set?... I mean which of the original screenshot network port should I modify?

**Comment by cbacit** [comment]
![2019-06-26_13-02-40](https://user-images.githubusercontent.com/47609657/60203825-1e337480-9813-11e9-801e-95837f6bb646.jpg)


Please see the attached image also... to answer the question above...

**Comment by enoch85** [comment]
Please ask in https://help.nextcloud.com or buy [hands on support](https://shop.hanssonit.se/product/premium-support-per-30-minutes/). 

Thanks.

**Comment by cbacit** [comment]
How long do you think it would take to get this setup?

**Comment by enoch85** [comment]
> How long do you think it would take to get this setup? 

Probably like 10 minutes depending on the IP we set actually have internet.

**Comment by cbacit** [comment]
It did before... B/c let's us encrypt... had obtained a SSL just when I was loggin into the domain it said certified for nextcloud not the domain I had tied to it...  Are you in the US? Because I have a GEO..

**Comment by cbacit** [comment]
Also if we fix this in 10 min... do I still have credit for the 20 min later?
