### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by hovbjo** [nextcloud/vm#856]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by hovbjo** [comment]
sudo -u www-data php /var/www/nextcloud/occ -V failed

**Comment by enoch85** [comment]
@hovbjo 

> sudo -u www-data php /var/www/nextcloud/occ -V failed

That doesn't tell me anything. :)

Please provide the fill out the issue template at least.
