### ISSUE TITLE
Add DNS to set Static IP

### ISSUE THREAD

**Issue by cbacit** [nextcloud/vm#857]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen
I am able to set Gateway & Static IP ... Please allow met set DNS also...
## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?** NO

**Is port 80 and/or 443 open?**
Yes
#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
You can edit it afterwards in /etc/netplan/[your-config.yaml]. I won't add this back.
