### ISSUE TITLE
Nextcloud-vm integration with onlyoffice

### ISSUE THREAD

**Issue by 8853spa** [nextcloud/vm#858]
## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by 8853spa** [comment]
Hi.
Sorry for my bad english. I hope you can understand me.

We have bought your nextcloud-vm 1TB  (as 8853 spa, our company) and followed the installation steps for the configuration.

Everything seems to be fine but after onlyoffice installation we don't have the right nextcloud integration and it's impossible create or modify existing office document (xlsx,docx,etc).

Unfortunately I do not have a great knowledge of linux but i can say you this:

The onlyoffice is installed in the docker.

The nextcloud site is ok and https://cloud.8853.it works.

The document server site is ok and https://office.cloud.8853.it works.

I searched the internet but the various solutions tested do not work.

Can you send me all the commands for solve the problem?

Or (and it would be better) can you connect by teamviewer at my server and check the configuration?

I hope you can solve the problem soon, to show my boss that your product is excellent.

Thank you.

Zamberletti Mauro
8853 spa
Pero (MILANO) - Italy
+39 02 8853 506
robot@88dent.com

**Comment by enoch85** [comment]
Invalid. You didn't even fill out the issue template.
