### ISSUE TITLE
Problem after upgrading to 16.0.3

### ISSUE THREAD

**Issue by ronaldoantoni** [nextcloud/vm#870]
## Steps to reproduce
1.I do not know specifically what happened. The update script was run on the server. Nothing more.

## Expected behaviour
It should display all the nextcloud tabs after the update, but only files and activities are displayed. The applications deck, contacts, calendar are not displayed.
When accessing "applications", they are not being displayed (neither installed nor new for installation).

## Actual behaviour
It should display all the nextcloud tabs after the update, but only files and activities are displayed. The applications deck, contacts, calendar are not displayed.
When accessing "applications", they are not being displayed (neither installed nor new for installation).

## Server configuration

**Nextcloud server version:** 16.0.3

**Server OS** (Ubuntu server is default) 18.04

**How did you install the VM?** (Scripted install from master **OR** Released version)
Script

## Network
**Do you use DHCP?** YES

**Is port 80 and/or 443 open?** YES

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```
[nextcloud.log](https://github.com/nextcloud/vm/files/3375067/nextcloud.log)
![03](https://user-images.githubusercontent.com/52723174/60929067-2addb100-a286-11e9-9fba-c0c673842e35.png)
![04](https://user-images.githubusercontent.com/52723174/60929068-2addb100-a286-11e9-87f1-df5ea2a01989.png)
![01](https://user-images.githubusercontent.com/52723174/60929070-2b764780-a286-11e9-8f33-976e5b820fd1.png)
![02](https://user-images.githubusercontent.com/52723174/60929071-2b764780-a286-11e9-9291-87b7539ab1f4.png)

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by ronaldoantoni** [comment]
Sorry for the english of google.

**Comment by enoch85** [comment]
Thanks for posting this issue and welcome to Github/Nextcloud!

Was this run in an automatic update schedule, or manually run?

It seems like the update didn't finish properly, hence the apps aren't activated back to normal state. I just ran an upgrade here to 16.0.3 to check and everything except "expected files" works. 

Regarding the expected files, that's nothing to worry about. It will probably solve itself on the next update of Nextcloud.

**Comment by enoch85** [comment]
Related: https://github.com/nextcloud/server/issues/16229

**Comment by ronaldoantoni** [comment]
Thanks for the quick response!
Access to applications has been restored!
However reading the thread, I noticed that there are also problems in accessing the application store (problem that occurs for me too and so far I had not noticed).
In fact, I would need a paid support, but the Brazilian economy and the real / euro conversion rate make this impossible!
We look forward to the solution!

**Comment by enoch85** [comment]
> the Brazilian 

Aah, meu esposa e Brazilera. :)

The solution right now is to wait for 16.0.4 to be released.

Regarding the "lost" apps, just run this: 

```
wget https://raw.githubusercontent.com/nextcloud/vm/master/static/recover_apps.py && pyhton recover_apps.py
```
