### ISSUE TITLE
Problems with OnlyOffice Installation with NAT, Virtual IP Alias

### ISSUE THREAD

**Issue by entjunicorn** [nextcloud/vm#872]
## Steps to reproduce
1. Installed NC via your script, and the installation was a success. I obtained a cert from LetsEncrypt, and everything is fine. 

The problems start when I run onlyoffice.sh to try and install OnlyOffice and integrate it with NC. 

## Expected behaviour
OnlyOffice and Nextcloud should integrate.

## Actual behaviour
onlyoffice.sh script cannot find port 80 or 443 open, yet it is.
 
I've tried commenting out the port check in the onlyoffice.sh script, and the install works. The OnlyOffice subdomain works, it obtains a cert from LetsEncrypt and everything seems like a success.

I then try to use OO within NC, and it does recognize the integration. I open a file in OO, and the interface loads, but then I get an error saying that it cannot communicate with NC (or similar). I close it, go into the OO settings in NC to see if there's something I can change. I don't change anything, leave the standard settings that onlyoffice.sh provides but when I hit save I get a CURL 60 error, something about the chain being invalid. 

I now go back into NC, and it no longer recognizes the OO integration and there's no option to create or view OO files. 

## Server configuration

**Nextcloud server version:** (see your admin page)
16.03

**Server OS** (Ubuntu server is default)
Ubuntu 18.04 LTS

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install from master 

## Network
**Do you use DHCP?**
Yes, but the NC VM is given a static lease with an internal IP.

**Is port 80 and/or 443 open?**
It is, but not according to the onlyoffice.sh script!

**Other Pertinent Information**
Running NAT + Firewall with a virtualized pfSense installation. The pfSense and NextCloud are virtualized on the same hypervisor (Proxmox). The public network is SoYouStart (OVH) which allows for IP aliasing.

Within the NAT, a dedicated public IP alias was given to the NC VM, and 1:1 NAT and port forwarding was setup for 80 + 443 to the VM. Doing a public IP check, the 1:1 NAT works and the machine sees its public IP.

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Apologies
I'm not able to get logs & screenshots right now because I thoroughly messed up the installation trying to fix this myself. This is definitely a bug/unintended outcome with the script, unfortunately. It's likely due to my unique virtualized NAT + OVH environment.

**Comment by entjunicorn** [comment]
Figured it out, had to do with NAT and DNS. 

My apologies, thank you for this awesome script & app!

**Comment by enoch85** [comment]
Glad you solved it!
