### ISSUE TITLE
Issue With PHP Memory Limits

### ISSUE THREAD

**Issue by nuc3boys** [nextcloud/vm#873]
![image](https://user-images.githubusercontent.com/52842650/61164519-d2e3bc00-a4ca-11e9-80c2-6bd83c8cf8f7.png)

How do I resolve this?

**Comment by nuc3boys** [comment]
![image](https://user-images.githubusercontent.com/52842650/61164553-281fcd80-a4cb-11e9-916e-9be326426b22.png)

**Comment by enoch85** [comment]
The VM comes with 1000 MB predefined.

Have you made any changes yourself?

**Comment by enoch85** [comment]
Just to point out; here is where the magic happens: https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L517-L528

**Comment by nuc3boys** [comment]
No, I haven’t changed anything at all. 

Sent Via Mobile

**Comment by enoch85** [comment]
Please fill out the issue template properly. 

Also, please provide the output of this command: `sudo cat /var/www/nextcloud/.user.ini` 

Thanks!

**Comment by enoch85** [comment]
I just released a new version, tested it and this issue is gone. 

Please download the latest version and try again. 

Thanks!
