### ISSUE TITLE
Not possible to host Collabora on same server with script

### ISSUE THREAD

**Issue by CorruptComputer** [nextcloud/vm#875]
## Steps to reproduce
1. Install NextCloud via script.
2. Choose to install Collabera as well.
3. Set Collabera domain to the same as your NextCloud domain.
4. Once install completes try to go to your website and you'll get a 403.

## Expected behaviour
The script should ask if you want to host Collabora on a different port when you install it on the same server.

## Actual behaviour
The Collabora installer overwrites your NextCloud instance on port 80, making it impossible to use your site.

## Server configuration

**Nextcloud server version:** 16.0.3

**Server OS** Ubuntu 18.04 LTS

**How did you install the VM?** Scripted install from master

## Network
**Do you use DHCP?** No

**Is port 80 and/or 443 open?** Yes

## Logs / Screenshots
![image](https://user-images.githubusercontent.com/5573038/61183056-b72f0180-a601-11e9-8680-02653049da57.png)

#### Log file (/mnt/ncdata/nextcloud.log)
The file is empty.
![image](https://user-images.githubusercontent.com/5573038/61183071-ee051780-a601-11e9-800f-ede1f60b5352.png)

#### Installation log (command output)
Server auto-reboots, was not able to get the log.

**Comment by CorruptComputer** [comment]
Re-installing and making a note of choices made:
* Run `nextcloud_install_production.sh` as root
* Created new user: `ncadmin`
* 1 disk mode
* Cloudflare DNS
* Add apps: Calendar, Contacts, IssueTemplate, PDFViewer, Extract, Webmin
* **- Reboot -**
* Login as: `ncadmin`
* Setup SSL as: `demeter.[domain.tld]`
* Add apps: Fail2Ban, Collabora, FullTextSearch
* Collabora subdomain: `demeter.[domain.tld]`
* NextCloud URL: `demeter\.[domain\.tld]`
* Keep existing certificate (I don't think it needs a new one if they are both hosted on the same server)
* Change `ncadmin` password
* Create NextCloud admin
* Configure: Automatic Updates
* **- Reboot -**
* Open browser and go to `demeter.[domain.tld]`, get a 403 forbidden error.

**Comment by enoch85** [comment]
> Set Collabera domain to the same as your NextCloud domain. 

This is not how the script works. You need to put Collabora on a different domain e.g. office.yourdomain.com.

Please read the instructions during the setup, the provide useful and critical information.

Thanks!

**Comment by enoch85** [comment]
Just as a reference: https://github.com/nextcloud/vm/blob/master/lib.sh#L75-L77

**Comment by CorruptComputer** [comment]
So this is not possible to host Collabora on the same server as NextCloud? I am also using a subdomain here, note the `demeter.[domain.tld]` I added to the steps I followed. The instructions linked say nothing about being be able or not being able to host it on the same server, they only ask what the subdomain is.

**Comment by enoch85** [comment]
Sorry if I was a bit unclear.

Nextcloud is hosted on: cloud.yourdomain.com (Server A)
Collabora is hosted on: office.yourdomain.com (Server A = same server but different DNS entry)

So esentially, create two DNS records that points to the same server. NAT 443 + 80 to the same server. Run the scripts. :)

**Comment by CorruptComputer** [comment]
Would that still not cause the Apache record for NextCloud to be overwritten with the one for Collabora? Also for DNS, would it need to be an A/AAAA record for this to work properly or would a CNAME of lets say `collabora.demeter.[domain.tld]` work as well? The documentation for this is very much lacking, and I apologize for any confusion I had or may have caused.

**Comment by enoch85** [comment]
> Would that still not cause the Apache record for NextCloud to be overwritten with the one for Collabora?

No, since the VHOSTs are named per domain. 

> Also for DNS, would it need to be an A/AAAA record for this to work properly or would a CNAME of lets say collabora.demeter.[domain.tld] work as well?

A CNAME would work just as well. 

Not sure if cname.domain.somthing.somethingelse.somethingthird.com would work though, since there are certain rules (in general) on how domains should be setup.

to be 100% sure, just use `demeter` and `demeteroffice` or similar. The domain isn't shown in public anyway.

> The documentation for this is very much lacking

Following the on screen instructions when given to you would have resulted in a working installation. Hence, no need for documentation since everything is "documented" in the scripts itself.

Or do you think that could be improved? You are very welcome with a PR in that case. :rocket:

**Comment by CorruptComputer** [comment]
Created one :)

Thanks for all the help!
