### ISSUE TITLE
ZFS running out of space at 1.7GB?

### ISSUE THREAD

**Issue by Bitsauger** [nextcloud/vm#877]
Hey,

my NC instance is running in "Internal Server errors" since I updated yesterday from 16.01 to 16.03.

Webmin says that the ZFS has 0kb free disk space but only 1.7GB are used.
Virtualbox knows 2 SCSI Disks with 40GB each

## Steps to reproduce
Updated like described from 16.01 to 16.03 yesterday via update script.
(I dont know if this is important, because my Backup size before the Update was 49GB!)

First all looks fine
Today its impossible to login via Browser. APPs or external access is working.

## Expected behaviour
I think the ZFS should have about 37GB of free disk space.

## Actual behaviour
Running out of space with 1.7GB used. Cant find, where 40GB of Data should be used.

## Server configuration

**Nextcloud server version:** 16.03

**Server OS** 18.04

**How did you install the VM?**
Via script of the 40GB version

## Network
Static IP in the Router for the NC

**Is port 80 and/or 443 open?**

Port 443 is open

## Logs / Screenshots
If it helps, i will update logs, but i dont know exactly how to exctract these via Reminna...?
![Screenshot_2019-07-14 Dashboard — Webmin 1 920 (Ubuntu Linux 18 04 1)](https://user-images.githubusercontent.com/42753280/61189673-e9d40b00-a690-11e9-9091-cb46cc40e0df.png)

**Comment by enoch85** [comment]
Maybe you lost connection to the drive? Virtualbox is known for being troublesome, and is not the recommended way of installing the VM, though supported.

Also, since 16.0.1, Redis got upgraded and a reboot is needed for it to resolve the internal server error. Did you try that?

Please also check existing issue here: https://github.com/nextcloud/vm/issues/870

**Comment by Bitsauger** [comment]
Thanks for your fast reply!

Hmm,

reboot was the first I've tested. Now I see only 1.35GB total for ZFS in Webmin - seems to shrink. 
Virtualbox means that ZFS has 39,75 used space...

The wohle VM is on a 500GB SSD but with over 100GB of free space. Smart says everything is fine.

I use Openmediavault so for "easy to use" is only Virtualbox as plugin available.
I'll try the Bakups to see whats going wrong. Maybe its really a Virtualbox Problem.

I will reply for news here.

Thanks!

**Comment by Bitsauger** [comment]
Puh oh man... -.-

ZFS is taking snapshots hourly and some frequent. I deleted all Snapshots of ncdata and voila 38.3GB free for ZFS.

Now I have to figure out how to deactivate the Snapshots - maybe a wonderful feature of ZFS but I dont need them.

Think this is now solved!

**Comment by enoch85** [comment]
Glad you managed to solve it!
