### ISSUE TITLE
Rerun redis install on update script

### ISSUE THREAD

**Issue by Ark74** [nextcloud/vm#88]
The [update](https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh) script has the line,
`apt dist-upgrade -y`

That would update the php version on the server, then leave php with no redis support, thus a Nextcloud website unusable since config.php would require redis use.

Ubuntu just released an update from php-7(.8) to php-7(.13), and that might be the case.
It happened to me today. :sweat_smile:
Cheers.

**Comment by enoch85** [comment]
Wow! Forgot about that. Can you please create a PR?

Let's go with just `upgrade` instead of `dist-upgrade`

**Comment by enoch85** [comment]
Okay, just tested and it works as expected even after upgrade. I guess you chose to use the new file, never do that in case you really must. 

This is not an issue --> closing.

**Comment by Ark74** [comment]
If you run the update script right after the production_install you won't see any behaviour since the packages are up to date.
But if you do `dist-upgrade`, right after ubuntu pushed php7 updates (this week they moved from 7.0.3 to 7.0.13) it will brake the redis support since the script it builds it from git.
I've had the same config file **for over a year now**.
My two cents.

**Comment by enoch85** [comment]
@Ark74 I hear you. 

Though, my test was on my own server (1.5 years with the same config) and also on another server that is about 6 months (with a Nextcloud VM) and both performed well. No errors and I could login to redis-cli without any issues. both servers are in production.

**Comment by enoch85** [comment]
Ok, I just tried again, but this time I chose to install the package maintaners version, and yes, redis fails to load. But it's really easy to fix.

`echo extension=redis.so >> /etc/php/7.0/apache2/php.ini`

So as I said, always keep the local version and there will be no issues. :)
