### ISSUE TITLE
Nextcloud - Install .OVA to Xenserver, install script won't run

### ISSUE THREAD

**Issue by theancients89** [nextcloud/vm#882]
Hi guys!

I've managed to get Nextcloud working with no issues on VMWare however trying to import the .OVA file into Xenserver is problematic. The .OVA imports and runs but I get the error that Nextcloud can't update and refers me to this section of GitHub, I think it must be a network issue, although it can get online it just won't move past the 'cannot update', screen and run the installer.

Any ideas?

Cheers!

**Comment by enoch85** [comment]
Hi!

Yeah, I don't think Xenserver can handle an OVA from VMware. First hit on Google: https://discussions.citrix.com/topic/363466-how-to-import-ova-file-into-xen/

If you want to run on Xen, then the safest way is to build the VM yourself. Or buy support.

**Comment by theancients89** [comment]
Hi!

I've managed to import a .OVA image several years ago on a different version of Nextcloud, I think the probmlem is network related, I'm not sure how or if I can replicate the same settings as VMWare where I can change from Bridged networking to NAT instead, any ideas?

Cheers!

**Comment by enoch85** [comment]
No ideas as I don't run Xen myself, sorry.
