### ISSUE TITLE
Check open port externally

### ISSUE THREAD

**Issue by enoch85** [nextcloud/vm#888]
Do something with this, from @nachoparker 

```
is_port_open() {
PORT=$1
wget -T2 -t1 -q  https://portchecker.co/check --post-data "port=$PORT" -O - \
| grep -q '<span class="green">open</span>' && { echo "open"; return 1; }
echo "closed"
}

is_port_open 80
is_port_open 443
```

**Comment by enoch85** [comment]
@nachoparker Crafted something cleaner IMHO: https://github.com/nextcloud/vm/pull/891/files

```
curl -s 'https://ports.yougetsignal.com/check-port.php' --data "remoteAddress=${WANIP4}&portNumber=${1}" \
| grep -q "is open on"
```

**Comment by enoch85** [comment]
Btw, thanks for the inspiration @nachoparker!

**Comment by nachoparker** [comment]
nice! it's only a two liner but glad that it was useful :)

**Comment by enoch85** [comment]
@nachoparker The benefit being that you:
1. Use curl
2. Lesser "junctions"
3. You can do something with the result, which I found to be hard with the wget command.
4. You can choose which external IP (or domain) you want to try against.

Maybe something to update for the pi project? 

Thanks again.

**Comment by nachoparker** [comment]
maybe :)
