### ISSUE TITLE
when running the auto install

### ISSUE THREAD

**Issue by razorfish-sl** [nextcloud/vm#89]
clean install
## Steps to reproduce
1. start vm 
2.run auto install

get warning at:
Setting Rewrite base to / in config.php
system config value htaccess.RewriteBase set to string /

Error updating .htaccessfile, not enough permissions?

2nd error (needs clear instructions)
modified configuration file

related to /usr/lib/php/7.0/php.ini
which php to install?  
keep local or update to maintainers version?

**Comment by enoch85** [comment]
@razorfish-sl Thank you for your report! 

This isa duplic<te of https://github.com/nextcloud/vm/issues/75

**Comment by enoch85** [comment]
> which php to install?
keep local or update to maintainers version?

Keep local, always! :)
