### ISSUE TITLE
Setting static IP address doesn't work

### ISSUE THREAD

**Issue by Crazee** [nextcloud/vm#895]
## Steps to reproduce
1. Start from .ova
2. Near end give static IP adresses, gateway address
3. VM reboots

## Expected behaviour
Tell us what should happen
Should be able to get to the system via HTTP/HTTPS

## Actual behaviour
Tell us what happens instead
If login via vmware console (not ssh) and run ifconfig, only 'lo' is listed.

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
released

## Network
**Do you use DHCP?**
yes and no

**Is port 80 and/or 443 open?**
yes

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
nextcloud.log is zero length
```

#### Installation log (command output)
used vmware serial console so no log file
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi!

Did you forget to add the subnet (/24) at the end maybe?

**Comment by enoch85** [comment]
Please download the latest `static_ip.sh` script and read the instructions carefully.

Run this in your console:
`wget https://raw.githubusercontent.com/nextcloud/vm/master/static/static_ip.sh && sudo bash static_ip.sh`

**Comment by enoch85** [comment]
Just tested the whole install script with all the settings and it works perfectly fine.

**Comment by Crazee** [comment]
If a /24 (or whatever) subnet is required, the UI *must* say so or give you an error if omitted.

**Comment by enoch85** [comment]
> the UI must say

@Crazee It says in the description that you must enter it. 

You are welcome to send a PR with a fix for the issue. :)
