### ISSUE TITLE
VM aborted

### ISSUE THREAD

**Issue by ezraholm50** [nextcloud/vm#9]
Install stops somewhere after the webmin install. VM status is aborted.

[log.txt](https://github.com/nextcloud/vm/files/315696/log.txt) SSH Log

[log1.txt](https://github.com/nextcloud/vm/files/315704/log1.txt) VM Log

**Comment by enoch85** [comment]
This is known: https://github.com/nextcloud/vm/issues/6

Please reopen if not related.
