### ISSUE TITLE
psql is not installed

### ISSUE THREAD

**Issue by supra89t** [nextcloud/vm#903]
## Steps to reproduce
1. Run the VM script : sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh)"
2. Finish the first script
3. Login remotely or local and the error pops up during the check up

## Expected behaviour
Install should continue

## Actual behaviour
Error reporting "psql is not installed"

## Server configuration

Nextcloud 16

Ubuntu Server 18.04

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted from Master

## Network
**Do you use DHCP?**
Yes DHCP

**Is port 80 and/or 443 open?**
Yes Both are open

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```
+-----------------------------------------------------------------------+
| Thanks for downloading this Nextcloud VM by the Nextcloud Community!  |
|                                                                       |
| To run the startup script type the sudoer password. This will either  |
| be the default ('nextcloud') or the one chosen during installation.   |
|                                                                       |
| If you have never done this before you can follow the complete        |
| installation instructions here: https://bit.ly/2S8eGfS                |
|                                                                       |
| To be 100% sure that all the keystrokes work correctly (like @),      |
| please use an SSH terminal like Putty. You can download it here:      |
| https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html        |
| Connect like this: ncadmin@local.IP.of.this.server                    |
|                                                                       |
| You can schedule the Nextcloud update process using a cron job.       |
| This is done using a script built into this VM that automatically     |
| updates Nextcloud, sets secure permissions, and logs the successful   |
| update to /var/log/ncvm/update_run.log                                |
| Just choose to configure it when asked to do so later in this script. |
|                                                                       |
|  ##################### T&M Hansson IT - 2019 #######################  |
+-----------------------------------------------------------------------+
[sudo] password for ncadmin:
Testing if network is OK...
Checking connection...
Online!
Testing if network is OK...
Checking connection...
Online!
Checking if psql is installed...
dpkg-query: no packages found matching psql
psql is not installed.
This script is intended to be run on then PostgreSQL VM but PostgreSQL is not installed.
Aborting...

**Comment by enoch85** [comment]
@supra89t Thank you for this! Just made some changes yesterday. Please let me know if you find something else.

Another question, what do you think about the scripts? Easy to understand/install? To much (verbose) output?

**Comment by supra89t** [comment]
@enoch85 Thank you, seems to be working now. Near the end there were 2 errors during the updates saying that mysql was not installed. Besides that everything is fine. Keep the verbose, its super helpful and it also acts as ping to see if your server is hanging.

Side note, my ISP does block port 80 so I'm using cloudflare as a DNS and SSL certificates. I can import them and everything works. But When I try to install office or talk it tries to install LE SSL and I can just never get it to work via LE due to my ISP blocking 80. Is there another way for me to be able to install them without having to use LE?

**Comment by enoch85** [comment]
@supra89t Thanks for the feedback. If you run PostgreSQL and MySQL is missing, that's expected. Quite some time ago now, the VM was using MySQL, so the update script is backwards compatible. Hence the check for MySQL. :)

You could run LE with the DNS option, that's not included in the apps scripts though, only the `activate-ssl.sh` script. I have no good solution to offer if port 80 is blocked except "change ISP!" :)

Everything regarding SSL in the scripts is based on LE, so without port 80 it's a hard nut to crack. You could install your own cert and comment out the SSL-generating lines in the scripts though.

**Comment by supra89t** [comment]
Is this normal ?

![SSL_Error via activation script](https://user-images.githubusercontent.com/25457950/62150802-e6659400-b2cc-11e9-9895-014d254e0570.png)

**Comment by enoch85** [comment]
That A-record looks strange. Are you sure you entered everything correctly?

Does it work if you try again?

**Comment by enoch85** [comment]
I just ran the same check, everything works, but your domain isn't propagated. So the error you got is expected.

**Comment by supra89t** [comment]
I just switched back to godaddy name servers as you did that test. So
that's perhaps why. I'll try again once it's propaganded.
