### ISSUE TITLE
MOTD

### ISSUE THREAD

**Issue by gh0stwolf** [nextcloud/vm#905]
Can someone please tell me how to disable the nextcloud MOTD? I don't see any scripts in the regular motd folder.. I tried disabling Pam motd and still nothing. I'm not the most Linux savvy person. Would like to have the option to disable..

**Comment by enoch85** [comment]
It's not a MODT, it's a script that runs from the users profile. 

So visit /home/[user]/.bash_profile and remove the line with `nextcloud.sh`

Hope it helps!
