### ISSUE TITLE
oc_Filecache ist blowing up Size now 28 GB

### ISSUE THREAD

**Issue by kaoschris** [nextcloud/vm#908]
## Steps to reproduce
1. Import VM into VAPcenter VMware and Setup
2. Setup an Fileserver (windows) with 1 Million Files
3. Konfig Nextcloud to use External CIFS Shares from Windows
4. Import LDAP User from Windows

## Expected behaviour
It works like it should but see below

## Actual behaviour
there are select request hold open for a long time in nextcloud_db 

## Server configuration

**Nextcloud server version:** (see your admin page)
16.02
**Server OS** (Ubuntu server is default)
Ubuntu 18.04
**How did you install the VM?** (Scripted install from master **OR** Released version)
From Master
## Network
**Do you use DHCP?**
Yes
**Is port 80 and/or 443 open?**
Yes
## Logs / Screenshots

https://fileshare.kelobit.de/s/WLfJWbq2B246aNa

**Comment by enoch85** [comment]
Please report this to [Nextcloud Server](https://github.com/nextcloud/server/issues). Thanks!
