### ISSUE TITLE
Re-evaluate apcu for memcache.local

### ISSUE THREAD

**Issue by kesselb** [nextcloud/vm#917]
Please re-evaluate apcu for memcache.local: https://docs.nextcloud.com/server/16/admin_manual/configuration_server/caching_configuration.html#recommendations-based-on-type-of-deploymentre-evaluate

**Comment by enoch85** [comment]
Why? :)

**Comment by enoch85** [comment]
I can also add that the VM was using APCu from the get go, and it was replace by Redis which has worked extremely well.

**Comment by kesselb** [comment]
Apcu is a php module and therefore available with low performance overhead. Redis is a external service and for each request a connection is required. There are some more explanations at the doc.

**Comment by enoch85** [comment]
Haven't checked, but would it be possible to run both APCu and Redis at the same time?

**Comment by kesselb** [comment]
> Haven't checked, but would it be possible to run both APCu and Redis at the same time?
> 
> APCu for local and Redis for distributed.

Yes. It's the recommended setup for "Organizations with single-server and clustered setups". But if the current setup works well for your users don't change it. Never change a running system :smile: I just wanted to mention it.

**Comment by enoch85** [comment]
I will think about it.

Worth testing to implement at least and see if it works well. If that's the case I'll put it in production. :rocket:

**Comment by enoch85** [comment]
Naah, seems like a "no go" for this. Did my usual stress test with the desktop client and:
1. Got ALOT of locked files
2. The desktop client didn't even upload all files.
3. Seems like APCu crashed.

Also saw that there were some issues when using PHP-FPM (which we do in the VM), so I'm not convinced yet. Maybe you can help me on this @kesselb?

**Comment by kesselb** [comment]
Anything in the logs (Nextcloud, PHP)?

**Comment by enoch85** [comment]
OK,[ I'm convinced](https://github.com/owncloudarchive/pi-image/issues/24), let's make this work!

Will do some more testing with the defaults.

**Comment by enoch85** [comment]
For the tuning part: https://markus-blog.de/index.php/2018/05/30/how-to-install-apcu-object-cache-in-php7-and-integrate-in-nextcloud/

**Comment by enoch85** [comment]
Check stats with this: https://raw.githubusercontent.com/krakjoe/apcu/master/apc.php

**Comment by github-tomster** [comment]
hello world

is it just me:
```
PHP modules
This instance is missing some recommended PHP modules.
For improved performance and better compatibility it is highly recommended to install them:
- apcu
```
or 🤷🏻‍♂️ 

the environment was setup two days ago via the 'if you feel brave' way.
maybe 'apcu' turned better over the years ❓
