### ISSUE TITLE
extended time to get web front end

### ISSUE THREAD

**Issue by razorfish-sl** [nextcloud/vm#92]
people complain that they cannot get the front end web up when logging in for variable amounts of time upto 30 seconds.

I have had same problem as well as issues related to showing the apps tab, taking hour to get a result.

This appears to be a combination of VM settings and network settings related to  packet size on the outgoing interface.

since the vm assumes it is running as a 'real' computer, it uses real computer setting with the MTU set to 1500 bytes, normally this is not an issue.
However the packet size is increased beyond this size in some VM setups, this ALWAYS causes the packets to fragment on external interfaces. Depending on the network settings this causes the packet no ends of issues.

simply setting the interface MTU to a smaller size should fix this problem for all

in nextcloud  linux CLI do:

sudo ifconfig -a   #to list networks

then
sudo ip link set dev {interface from above list} mtu 1400

it may be worth configuring the VM with a slightly smaller MTU to fix  this issue globally.

**Comment by enoch85** [comment]
Thank you so much for posting this issue! 

A PR is welcome :)

**Comment by enoch85** [comment]
Ok, a PR is here; https://github.com/nextcloud/vm/pull/96

And here is some confirming information about the issue: https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1359

**Comment by razorfish-sl** [comment]
Thats the problem with the internet.... all the info is there ,
 it's just linking a problem to the right solution...

**Comment by enoch85** [comment]
@razorfish-sl Are you happy with the fix? It broke the internet in the scripts so I had to comment it out: https://github.com/nextcloud/vm/commit/e24196af357a625edac5d1535c0a432a628f6eed
