### ISSUE TITLE
Corrupted OVA (40 GB)?

### ISSUE THREAD

**Issue by jansppenrade2** [nextcloud/vm#921]
## Steps to reproduce
1. Import OVA (40 GB) into VirtualizationStation 3 (or another virtualization software)

## Expected behaviour
A successful import process

## Actual behaviour
Import failed cause of a Check-sum error (it seems that the OVA is corrupted)
"Failed to import VM: Check-sum error: [SHA256(Nextcloud_VM_www.hanssonit.se.ovf)= 0effdd80ec0b38b21ac9baa28768dea2e93ee7ec70141826a6d76facfecbc649]."

## Server configuration
QNAP TS-451+ with VirtualizationStation 3

**Nextcloud server version:** (see your admin page)
-

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
-

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi, thanks for your report. 

Please read this: https://help.nextcloud.com/t/qnap-virtualization-station-failed-to-import-file-checksum-error/58645/11
and this: https://help.nextcloud.com/t/installing-on-qnap-nas/19344/8

**Comment by enoch85** [comment]
Related: https://github.com/nextcloud/vm/issues/910
