### ISSUE TITLE
ask_yes_or_no: command not found

### ISSUE THREAD

**Issue by kesselb** [nextcloud/vm#924]
![VirtualBox_vm with apcu_01_09_2019_18_47_05](https://user-images.githubusercontent.com/3902676/64079554-0a136400-cce9-11e9-8bee-a49958628f51.png)

Testing box with apcu from the apcu pull request.

**Comment by enoch85** [comment]
That tells me you lost internet connectivity as it fetches all the variables from this Github repo.

I tried that script yesterday, and it worked without a hitch.

Thanks for the heads up though.

**Comment by kesselb** [comment]
Yes. The box was without internet. But this is the dialog to configure the network.

**Comment by enoch85** [comment]
Best way to test is to download the latest beta from the link I gave you in another issue. Testing from branches won't work as the curl command will be in master anyway.

I will do one more test just to check.

**Comment by kesselb** [comment]
OK. I was using the box "Nextcloud_VM_www.hanssonit.se_17.0.0b2_APCu_TESTING".

**Comment by enoch85** [comment]
I see what's wrong here, I'm fixing that one now. Thanks for this issue!

**Comment by enoch85** [comment]
Solved in 17.0.0
