### ISSUE TITLE
caulculate_php_fpm vs calculate_php_fpm

### ISSUE THREAD

**Issue by kesselb** [nextcloud/vm#925]
https://github.com/nextcloud/vm/blob/1aecb02962846e76186d8f2e77d8d246dfb9a346/lib.sh#L293-L366

https://github.com/nextcloud/vm/blob/1aecb02962846e76186d8f2e77d8d246dfb9a346/lib.sh#L368-L441

I wonder why there are two methods with different name but same code :thinking:

**Comment by enoch85** [comment]
Yes indeed, good catch! :+1:
