### ISSUE TITLE
I got this just after installing nextcloud using the production script

### ISSUE THREAD

**Issue by DiyaaAlkanakre** [nextcloud/vm#928]
![Screenshot from 2019-09-01 16-09-23](https://user-images.githubusercontent.com/26883110/64083012-b1869b80-ccd5-11e9-8a10-96e314c9084e.png)
![Screenshot from 2019-09-01 16-12-58](https://user-images.githubusercontent.com/26883110/64083013-b1869b80-ccd5-11e9-9a8d-fb26bf6d0e2b.png)
![Screenshot from 2019-09-01 16-15-56](https://user-images.githubusercontent.com/26883110/64083014-b1869b80-ccd5-11e9-9ce5-7586d465077f.png)

**Comment by DiyaaAlkanakre** [comment]
let me know if you need any more information

**Comment by enoch85** [comment]
Hi!

Thanks for your report.

Did you choose any extra apps or settings during the first setup, or did you just choose the default (nothing but Let's Encrypt)?

**Comment by enoch85** [comment]
There was an error in the code regarding PHP like 12 hours ago, maybe you did the setup just then. 

Please try to delete the VM from your host, then try again to see if it's solved.

Thanks.

**Comment by DiyaaAlkanakre** [comment]
oh yeah it was latterly a few minutes before I submitted this report.
I reinstalled it and now it's working just fine.

Thank you very much for spreading privacy and freedom freely.
