### ISSUE TITLE
[Bitwarden] Changed environment variables, won't start now.

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/vm#944]
## Steps to reproduce
1. Install bitwarden from apps script
2. Update email environments via tutorial: <https://help.bitwarden.com/article/install-on-premise/#post-install-environment-configuration>
3. Replace `/root/bwdata/scripts/*.sh` because files were missing. From: `https://github.com/bitwarden/server/tree/master/scripts`
4. `chown nobody:nogroup /root/bwdata/scripts/*.sh`
5. `chmod 755 /root/bwdata/scripts/*.sh`
6. `bash /root/bitwarden.sh rebuild`
7. `bash /root/bitwarden.sh start`

## Expected behaviour
rebuild and restart docker container with new environment values

## Actual behaviour
Rebuilds but doesn't start. See logs (last line)

## Server configuration

**Nextcloud server version:** (see your admin page)
16.0.4

**Server OS** (Ubuntu server is default)
18.04 LTS

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
Yes, Static via Router

**Is port 80 and/or 443 open?**
Yes, used by Nextcloud. Port 8080 and 8443 open and ready for use for bitwarden.

#### Log file (/mnt/ncdata/nextcloud.log)
```
N/A
```

#### Installation log (command output)
```
root@cloud:~# root@cloud:~# bash bitwarden.sh start
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2019, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.2, build 6a30dfc
docker-compose version 1.17.1, build unknown

Removing network docker_default
WARNING: Network docker_default not found.
Pulling web (bitwarden/web:2.12.0)...
2.12.0: Pulling from bitwarden/web
Digest: sha256:4216ab50ad5519da1ceddac537aea8b36e9c2cc4194aa72864c440d91ce31a8e
Status: Image is up to date for bitwarden/web:2.12.0
Pulling attachments (bitwarden/attachments:1.32.0)...
1.32.0: Pulling from bitwarden/attachments
Digest: sha256:d578a62562bae8359b47dfbb7ff31bccb5836ab0d4d7f2c97b29b2e2c0e91b9a
Status: Image is up to date for bitwarden/attachments:1.32.0
Pulling icons (bitwarden/icons:1.32.0)...
1.32.0: Pulling from bitwarden/icons
Digest: sha256:56d1a77ce7877e8fb2002e592fd06b9a003675f2c4aad670a876b9456a00ccdf
Status: Image is up to date for bitwarden/icons:1.32.0
Pulling events (bitwarden/events:1.32.0)...
1.32.0: Pulling from bitwarden/events
Digest: sha256:af1f8c6fa8dbad499b3a39472a728ebef13f60a270fe02db0befb6015e8eb254
Status: Image is up to date for bitwarden/events:1.32.0
Pulling notifications (bitwarden/notifications:1.32.0)...
1.32.0: Pulling from bitwarden/notifications
Digest: sha256:fa41c981423008c7c7aa2863b3cf84c6dd1846f5098c821981fbcdc511fe4c80
Status: Image is up to date for bitwarden/notifications:1.32.0
Pulling api (bitwarden/api:1.32.0)...
1.32.0: Pulling from bitwarden/api
Digest: sha256:9eb269a060145283a1910d736ed71e7c6113647004b6950596723aa5c92a5482
Status: Image is up to date for bitwarden/api:1.32.0
Pulling mssql (bitwarden/mssql:1.32.0)...
1.32.0: Pulling from bitwarden/mssql
Digest: sha256:fbc017d4cd16aa148d44c24884527bf3a591dbc25f0d1c46b0356d2d6ba200da
Status: Image is up to date for bitwarden/mssql:1.32.0
Pulling admin (bitwarden/admin:1.32.0)...
1.32.0: Pulling from bitwarden/admin
Digest: sha256:16d6ef6d786efc407237c355ff1d537b1879a296d9dc550cf4da75f9fc7781d6
Status: Image is up to date for bitwarden/admin:1.32.0
Pulling identity (bitwarden/identity:1.32.0)...
1.32.0: Pulling from bitwarden/identity
Digest: sha256:3df6785c82da4fbff9a2053062b82c4969c576f93b3d35ef54404658c0d85ebd
Status: Image is up to date for bitwarden/identity:1.32.0
Pulling nginx (bitwarden/nginx:1.32.0)...
1.32.0: Pulling from bitwarden/nginx
Digest: sha256:9fd9bb69305b8c84e1f8239ff0d9db4b531707bd1424a82c73672b64bca6bd7a
Status: Image is up to date for bitwarden/nginx:1.32.0
Using default tag: latest
latest: Pulling from certbot/certbot
Digest: sha256:ded8b629e36e410abd3dcfd4c12fac6108b5c84bd98aa28ae57a212e90bbeabf
Status: Image is up to date for certbot/certbot:latest
docker.io/certbot/certbot:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint certbot (eb9aece74469040ae66fd56819094e575067310e8ad64b6d9649061066203690): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use.

```
#### Screenshoots

N/A

**Comment by enoch85** [comment]
Thanks for this issue, though it's already fixed some time ago: https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L519-L539

In other words; always use `update.sh` to get all the bug fixes and latest version of everything. Thatäs why the script exists. Everything other than that is unsupported.

Your Bitwarden is probably messed up now and if that's the case you need to reinstall. Replacing all your scripts is not a good idea. `bitwarden.sh` (from Bitwarden) will take care of upgrading old versions as well and only change stuff that is needed.

**Comment by enoch85** [comment]
Well, while reading everything again I see what's going on. You need to stop Apache2 to be able to run Bitwarden, as certbot talks on port 443 and 80, and that's already occupied with LE.

So, stop Apache2, then try again.

**Comment by BetaLeaf** [comment]
I see. Thanks. Also, I had to replace the script files because they were missing. I recreated the file structure from source.

**Comment by BetaLeaf** [comment]
Yup that was it. Thanks. Got a new issue, but seems more appropriate to post that in bitwarden/server.

**Comment by enoch85** [comment]
>  I had to replace the script files because they were missing

That's what [update.sh](https://github.com/nextcloud/vm/blob/master/nextcloud_update.sh#L533) does for you.

1. It fetches the latest `bitwarden.sh`
2. `bitwarden.sh` makes the necessary changes.

Glad you solved it!

**Comment by enoch85** [comment]
Just to be clear: SSL in the VM for your "regular" domains are generated standalone from Bitwarden. Bitwarden use the certbot Docker which conflicts with the standalone LE. Hence, Apache2 needs to be stopped.

I plan to integrate the standalone LE into Bitwarden as well, but the current solution works  (update.sh stops Apache2 before Bitwarden is updates), so I haven't prioritized it.
