### ISSUE TITLE
Auto update configuration fails

### ISSUE THREAD

**Issue by supra89t** [nextcloud/vm#945]
## Steps to reproduce
1. Install cloud via script
2. When prompted at the end if you want to configure auto updates select yes
3. Select yes that you want the updates to reboot after each update

## Expected behaviour
Tell us what should happen

## Actual behaviour
Error restarting PHP

## Server configuration

Latest from the script

Ubuntu Server

Scripted

## Network
**Do you use DHCP?**
Yes

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots

Configuring automatic updates...
Do you want to enable automatic updates? ([y]es or [N]o): y
Do you want to reboot your server after every update? ([y]es or [N]o): y
Automatically configures pm.max_children for php-fpm...
Job for php7.2-fpm.service failed because the control process exited with error code.
See "systemctl status php7.2-fpm.service" and "journalctl -xe" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart php7.2-fpm.service failed
root@cloud:~#

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by BetaLeaf** [comment]
Hi. Thanks for letting us know of this issue. Would you mind running the following command with sudo? 
`systemctl status php7.2-fpm.service`

**Comment by BetaLeaf** [comment]
I'd also like to know when you installed using the script.

**Comment by supra89t** [comment]
I install this server about 2 hours ago.

ncadmin@cloud:~$ sudo systemctl status php7.2-fpm.service
[sudo] password for ncadmin:
● php7.2-fpm.service - The PHP 7.2 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.2-fpm.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-09-15 09:10:11 EDT; 46min ago
     Docs: man:php-fpm7.2(8)
  Process: 1744 ExecStart=/usr/sbin/php-fpm7.2 --nodaemonize --fpm-config /etc/php/7.2/fpm/php-fpm.conf (code=exited, status=78)
 Main PID: 1744 (code=exited, status=78)

Sep 15 09:10:10 cloud.bohbotsystems.ca systemd[1]: Starting The PHP 7.2 FastCGI Process Manager...
Sep 15 09:10:11 cloud.bohbotsystems.ca php-fpm7.2[1744]: [15-Sep-2019 09:10:11] ALERT: [pool Nextcloud] pm.min_spare_servers(2) and pm.max_spare_servers(118) cannot be greater than pm.max_children(106)
Sep 15 09:10:11 cloud.bohbotsystems.ca php-fpm7.2[1744]: [15-Sep-2019 09:10:11] ERROR: failed to post process the configuration
Sep 15 09:10:11 cloud.bohbotsystems.ca php-fpm7.2[1744]: [15-Sep-2019 09:10:11] ERROR: FPM initialization failed
Sep 15 09:10:11 cloud.bohbotsystems.ca systemd[1]: php7.2-fpm.service: Main process exited, code=exited, status=78/n/a
Sep 15 09:10:11 cloud.bohbotsystems.ca systemd[1]: php7.2-fpm.service: Failed with result 'exit-code'.
Sep 15 09:10:11 cloud.bohbotsystems.ca systemd[1]: Failed to start The PHP 7.2 FastCGI Process Manager.
ncadmin@cloud:~$

**Comment by BetaLeaf** [comment]
Yup thought so. Dup of #943 
When did you download the script? Happen to know which commit?

**Comment by enoch85** [comment]
Let's continue the discussion in #943 instead. 

Thanks!
