### ISSUE TITLE
'Port 80 is not open' upon trying to install SSL on DigitalOcean

### ISSUE THREAD

**Issue by rubenmoor** [nextcloud/vm#947]
## Steps to reproduce
1. set up DNS on DigitalOcean with A record for my domain
2. run set-up script on DigitalOcean droplet, reboot and continue setup
3. reach the point where setup tries to install SSL

## Expected behaviour
continue SSL setup

## Actual behaviour
error message about 'Port 80 is not open on either `IP address` or `mydomain.com`.

## Server configuration

**Nextcloud server version:** 16.04

**Server OS** Ubuntu 18.04.3

**How did you install the VM?** master

## Network
**Do you use DHCP?** no

**Is port 80 and/or 443 open?** on DigitalOcean all ports are open by default

**Comment by enoch85** [comment]
Hi!

Thanks for your issue. 

I will fire up a DO droplet to see if I get the same results.

**Comment by enoch85** [comment]
It works here: https://cloud.hanssonit.se/s/WFTRGYqDBA7X3Nk

The fun begins at ~ 14:00

**Comment by enoch85** [comment]
Btw, probably a DNS propagation issue.

**Comment by rubenmoor** [comment]
Thanks! Basically, after waiting one day, everything works now. 

I used digital ocean dns first, then switched to cloudflare for my DNS. Apparently, it took a while until the desired state was reached DNS-wise.
