### ISSUE TITLE
Duplicate "Do you want to change port?" message for Talk

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/vm#949]
![image](https://user-images.githubusercontent.com/7028351/64984087-0f97af00-d890-11e9-9a6b-75b4c53f3433.png)

Low Priority, it is just cosmetic.

**Comment by BetaLeaf** [comment]
Happens elsewhere too

**Comment by enoch85** [comment]
> Happens elsewhere too

You you mean this? https://github.com/nextcloud/vm/blob/master/apps/talk.sh#L51-L69

**Comment by enoch85** [comment]
Here's the function: https://github.com/nextcloud/vm/blob/master/lib.sh#L165-L175

So, the function and the use of the function seems correct. Strange level 9000.

**Comment by BetaLeaf** [comment]
Yea I looked at both, looks correct to me as well, but still this happened.

**Comment by enoch85** [comment]
@BetaLeaf Do you think you can debug it?

Run the function with `bash -x` and post the result here.

Thanks!

**Comment by BetaLeaf** [comment]
Sleeping now, will later

**Comment by enoch85** [comment]
It works here:

```
NC_UPDATE=1 && TURN_INSTALL=1 . <(curl -sL https://raw.githubusercontent.com/nextcloud/vm/master/lib.sh)
unset NC_UPDATE
unset TURN_INSTALL

ask_yes_or_no() {
    read -r -p "$1 ([y]es or [N]o): "
    case ${REPLY,,} in
        y|yes)
            echo "yes"
        ;;
        *)
            echo "no"
        ;;
    esac
}


if [[ "yes" == $(ask_yes_or_no "Do you want to change port?") ]]
then
    while true
    do
    # Ask for port
cat << ENTERDOMAIN
+---------------------------------------------------------------+
|    Please enter the port you will use for Nextcloud Talk:     |
+---------------------------------------------------------------+
ENTERDOMAIN
    echo
    read -r TURN_PORT
    echo
    if [[ "yes" == $(ask_yes_or_no "Is this correct? $TURN_PORT") ]]
    then
        break
    fi
    done
fi
```
![Screenshot from 2019-09-17 12:09:17](https://user-images.githubusercontent.com/4511254/65032749-ff410c00-d943-11e9-9bad-b02bc1d939ea.png)

**Comment by BetaLeaf** [comment]
Found yet more instances. I know there is at least one more.
![image](https://user-images.githubusercontent.com/7028351/65056931-c7d06080-d93f-11e9-844b-d875c99b5717.png)
![image](https://user-images.githubusercontent.com/7028351/65057020-ef272d80-d93f-11e9-9694-552a03d805e6.png)

**Comment by enoch85** [comment]
Hmm, I'm starting to think that you are not running master. Are you running from a certain commit?

**Comment by enoch85** [comment]
Hey, any update here? I fail to reproduce this and I've done like 10 installations since this issue.

**Comment by BetaLeaf** [comment]
Sorry for the delay. I've been taking a few personal days.
When I install Nextcloud, I run the following commands:
```
sudo -i
curl https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh | bash
```

**Comment by enoch85** [comment]
OK, don't pipe it through bash and curl, download it first, then run it. That's the problem.

**Comment by enoch85** [comment]
Also, don't run it as root.

**Comment by enoch85** [comment]
@BetaLeaf Did you have the chance to try yet? 

Thanks!

**Comment by enoch85** [comment]
I installed Talk several times now on different servers, and I never got this. It must be user specific. 

Please reopen if you don't agree.
