### ISSUE TITLE
activate-ssl.sh apache2 error

### ISSUE THREAD

**Issue by StreamEnviro** [nextcloud/vm#950]
Steps to reproduce
1. install ubuntu 18.04.3LTS with nextcloud
2. install apache2
3. run activate-ssl.sh

Testing if network is OK...
Checking connection...
Checking if port 80 is open with https://ports.yougetsignal.com...
Port 80 is open on vault.viveur.co!
Checking if port 443 is open with https://ports.yougetsignal.com...
Port 443 is open on xxx.xxx.40.217!
certbot 0.31.0
certbot 0.31.0
/etc/apache2/sites-available/vault.viveur.co.conf was successfully created.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Running pre-hook command: service apache2 stop
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for vault.viveur.co
Waiting for verification...
Cleaning up challenges
Running post-hook command: service apache2 start
Hook command "service apache2 start" returned error code 1
Error output from service:
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/vault.viveur.co/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/vault.viveur.co/privkey.pem
   Your cert will expire on 2019-12-16. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 
Generating DSA parameters, 4096 bit long prime

We will now test that everything is OK
Press any key to continue...
Enabling site vault.viveur.co.
To activate the new configuration, you need to run:
  systemctl reload apache2
ERROR: Site nextcloud_ssl_domain_self_signed does not exist!
ERROR: Site nextcloud_http_domain_self_signed does not exist!
Site 000-default disabled.
To activate the new configuration, you need to run:
  systemctl reload apache2
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
systemctl restart apache2 failed
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
bash /var/scripts/test-new-config.sh vault.viveur.co.conf failed

Nextcloud server version: 15.0.11

VM installed from released ISO

**Comment by enoch85** [comment]
Thanks for posting this issue!

Please try the latest [activate-ssl.sh](https://github.com/nextcloud/vm/blob/master/lets-encrypt/activate-ssl.sh) script an report back how it went.

Thanks!

**Comment by enoch85** [comment]
Closing due to no response. Feel free to reopen if the issue still persists.
