### ISSUE TITLE
Error when configuring Only Office on NextcloudVm Preinstalled 500 Gb Get converted Uri

### ISSUE THREAD

**Issue by Laurent-grain** [nextcloud/vm#954]
## Steps to reproduce
1. I use the preinstalled Vm nextcloud 500 Gb that I 've bought. Everything is ok during installation and after 
2. I deploy OnlyOffice with the script onlyoffice.sh  (curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/apps/onlyoffice.sh && sudo bash onlyoffice.sh) Everything is OK
3. I connect to my nextcloud and try to open an office document. The document is downloadeded but not open in onlyoffice.
4. I connect on webpage of my nextcloud and in onlyoffice parameter, I have no parameters below the button "save" => common setting.
5. I clic on save  this message appear in logging:

Error | onlyoffice | GetConvertedUri on check error: Error occurred in the document service: Error while downloading the document file to be converted.

6. I uninstall and re install only always with scritp onlyoffice.sh. All is Ok during and after the install, but I've the same result.
7. If I choose the option Connect to demo onlyoffice document server, It's works well.
8. If I uncheck the "demo onlyoffice server", I've the same result.

## Expected behaviour
Tell us what should happen
A office document open in onlyoffice 
## Actual behaviour
Tell us what happens instead
The document is downloaded
## Server configuration

**Nextcloud server version:** (see your admin page)
Nextcloud 16.0.3
**Server OS** (Ubuntu server is default)
Linux version 4.15.0-54-generic (buildd@lgw01-amd64-014) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019
**How did you install the VM?** (Scripted install from master **OR** Released version)
It's the Vm bought on www.hanssonit.se, I used the script which is with
## Network
**Do you use DHCP?**
No
**Is port 80 and/or 443 open?**
Yes, and during install the script say it's OK
#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
[nextcloud.log](https://github.com/nextcloud/vm/files/3638450/nextcloud.log)

```

#### Installation log (command output)
```
Insert the CLI output here
```

#### Screenshoots
https://imgur.com/jUb8XxC
[nextcloud.log](https://github.com/nextcloud/vm/files/3638466/nextcloud.log)

**Comment by Laurent-grain** [comment]
Hello
I've forgot to say some thing
From my Vm , a wget https on the 2 website next and document server works well.
I can access on the website of my document server with https (letsencrypt deploy by script)

Have a nice day

**Comment by enoch85** [comment]
Thanks for such  a detailed issue!

I think this is an OnlyOffice bug, so I will transfer this issue to that repo instead. I've seen they have issues with templates and other strange issues in the later releases.

**Comment by enoch85** [comment]
Hm, turns out I couldn't transfer. Please open this issue here instead: https://github.com/ONLYOFFICE/onlyoffice-owncloud

Thanks!

**Comment by BetaLeaf** [comment]
I referenced it above

**Comment by enoch85** [comment]
@Laurent-grain Please add the description you added here to the issue that @BetaLeaf created. Thanks!

**Comment by enoch85** [comment]
And btw, I was closing because:

> Everything is OK

>  All is Ok during and after the install, 

> demo onlyoffice document server, It's works well.

> Yes, and during install the script say it's OK

**Comment by Laurent-grain** [comment]
THanks , I going to copy the problem too the new issue.

Have a nice day.

**Comment by BetaLeaf** [comment]
Btw @lcalaresu there was no need to copy paste your original post in the issue I referenced earlier today. Referencing the issue does that automatically. They just need to click the link to be brought here.

**Comment by enoch85** [comment]
@BetaLeaf That's not how you open an issue. ;) It's much better if the maintainer can see the issue directly instead of clicking on a link which leads to another repo.

Thanks for your input and help though. :rocket: :+1:
