### ISSUE TITLE
setting to make /var/scripts/update.sh update to specific stable version

### ISSUE THREAD

**Issue by penzoiders** [nextcloud/vm#957]
I'd love to have a setting to define which update to get on the VM where you run /var/scripts/update.sh.

Since a stable release is defined only at [major].0.2 (and many extensions are updated a bit later than the release date of [major].0.0) it will be nice to have a kind of "switch" to select between "latest" and "stable" update channels.

Or at least it would be nice to have an option to pin [major] release number, in order to update to the maintenance patches before jumping to the next [major] release.

Just my2cents, what do you think?

**Comment by enoch85** [comment]
Thanks for your proposal. 

It will always run the latest as it automatically fetches the latest release from Nextcloud [here](https://github.com/nextcloud/vm/blob/master/lib.sh#L66). Maybe you could hold off with updating instead if you don't want the latest. :)

I get your point though, but to me that would be reverting to be doing manual stuff (changing the version you want to update to in the script). There's a use case for everything, but to me, the easiest way of not getting the latest major, is to not update, or manually enter `NCVERSION` in the update script.

**Comment by penzoiders** [comment]
yes, I saw that line, but lib.sh is pulled from the main repo at each run (didn't want to tweak it all).

the point here is: since the update script is so freaking good and stable I wanted to set it to cron.

I won't touch the default behavior, but if the VM admin sets a marker file (eg: `touch /var/ncdata/vm-stable-updates` ), the update.sh senses it and re-calculates the NCVERSION accordingly.

I'll make a PR then if you agree.

of course if you have better suggestions instead of marker file let me know daddy. =)

**Comment by penzoiders** [comment]
maybe I'll add a commandline parameter to the update script to pass this mode.
`/var/scripts/update.sh [stable|latest]` 

when $1=stable then checks if minor release and point release is at least x.0.2 goes with next major, otherwise will go with previous major relase minor patch.

**Comment by enoch85** [comment]
@penzoiders Or even better, always run latest if [minor] (stable) is not set.

If you provide a PR we can discuss it there?

**Comment by GeoGR9999** [comment]
Hello all.
Not sure if it is related to this issue, but I have informed from Administration/Overview that a  new version is available: Nextcloud 15.0.11. But when I run the upgrade script, the vm is updated OK (apt packages etc) but the nextcloud version stays on 15.0.7 . What is wrong?

**Comment by enoch85** [comment]
@GeoGR9999 It's not possible to jump between 2 major versions at once (15 --> 17). You need to upgrade to the next major version (16), and then use the built in upgrade script in the VM.

There are support to get if you don't know how to do it yourself: https://shop.hanssonit.se/product/upgrade-between-major-owncloud-nextcloud-versions/

(And no, this issue is not related) Thanks for posting though. :)

**Comment by enoch85** [comment]
@penzoiders Just for the record:

**in update.sh**
```
if [ -n $1 ]
then
    export NCVERSION=$1
fi
```

The problem is that `NCVERSION` is set again when `nextcloud_update.sh` is run, so `NCVERSION` must be set again - after the curl command to fetch the `lib.sh` somehow. Maybe a bit unclear, but yeah, it's complicated if you want to set the version in `update.sh`

**Comment by enoch85** [comment]
You could solve it with putting the `$1` to a file, and only run the specific version if that file is **not** empty. Also deleting that file after each run.

Needs some development though.

**Comment by penzoiders** [comment]
yes I thought of setting a $1, if = to "stable" then will do the math and check if latest version reached X.0.2 otherwise will go for previous Y.YY.YYY .

working on it on spare time, will PR when working.

**Comment by enoch85** [comment]
Great! Looking forward to that. :+1:

**Comment by enoch85** [comment]
This is now done!
