### ISSUE TITLE
issue running activate ssl script 

### ISSUE THREAD

**Issue by dunworth1** [nextcloud/vm#958]
![2019-10-01 12_12_43-Window](https://user-images.githubusercontent.com/26854851/65957668-50252a00-e445-11e9-9a8d-90552e24d3f8.png)

## Steps to reproduce
1. sudo bash /var/scripts/activate-ssl.sh

## Expected behaviour
Tell us what should happen

should download certbot

## Actual behaviour
fails to connect as per screenshot

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)
scripted install

## Network
**Do you use DHCP?**
static ip

**Is port 80 and/or 443 open?**
yes

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hi thanks for your issue.

Was this after you selected to use some other mirrors than the default for Ubuntu?

**Comment by dunworth1** [comment]
Hi No i left everything as default

**Comment by enoch85** [comment]
Just tested here and everything works as expected, I can't reproduce it.

To me, it seems like your internet connection died so that it couldn't fetch the needed packages, or that your country blocked that domain, or region.
