### ISSUE TITLE
Occasionally getting HTTP Error 403 on OnlyOffice. Happens more often when I haven't used it for a while. Happens more often when used frequently.

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/vm#961]
Occasionally OnlyOffice will fail to load with HTTP Error 403.
It happens more often when OnlyOffice hasn't been used in a while
It happens more often when OnlyOffice is used frequently and rapidly

I will get either 
`ONLYOFFICE cannot be reached. Please contact admin` [log](https://github.com/nextcloud/vm/files/3694064/cloud.betaleaf.net-1570345027304-failed.cannot.be.reached.log) or 
`Connection is lost. You can still view the document, but it will not be able to download or print until the connection is restored.` [log](https://github.com/nextcloud/vm/files/3694066/cloud.betaleaf.net-1570343486084-failed.screenshot.log). 

When it does work, it loads with some issues 
[log](https://github.com/nextcloud/vm/files/3694067/cloud.betaleaf.net-1570343519603-working.log)

## Server configuration

**Nextcloud server version:** (see your admin page)
17

**Server OS** (Ubuntu server is default)
18.04.3 LTS

**How did you install the VM?** (Scripted install from master **OR** Released version)
Scripted install from master

## Network
**Do you use DHCP?**
No, Static

**Is port 80 and/or 443 open?**
Yes

#### Log file (/mnt/ncdata/nextcloud.log)
```
[nextcloud.log](https://github.com/nextcloud/vm/files/3694052/nextcloud.log)

```

#### Screenshots
![image](https://user-images.githubusercontent.com/7028351/66265375-50c21580-e7e3-11e9-9f7f-8c5be6aa05f0.png)
![image](https://user-images.githubusercontent.com/7028351/66265513-02624600-e7e6-11e9-80ac-febc7692a3fa.png)

[other_vhosts_access.log](https://github.com/nextcloud/vm/files/3694053/other_vhosts_access.log)
[error.log](https://github.com/nextcloud/vm/files/3694054/error.log)

**Comment by BetaLeaf** [comment]
The inconsistency is driving me up a wall, can you help?

**Comment by enoch85** [comment]
Try increasing the RAM. Does that help?

**Comment by BetaLeaf** [comment]
I gave it 12GB. Shouldn't that be enough? That's 3x more than what the installer script says it needs.

**Comment by enoch85** [comment]
Hmm, yeah that should be more than enough. 

What's strange is that I never get the errors you are getting and I do several installations per week. There's nothing special in the installation, it's just the default docker installation by Collabora/OnlyOffice.

So, my best guess it's:
1. Something with your hardware
2. Something wrong with the docker.

**Comment by BetaLeaf** [comment]
Ok so what should I do to resolve the issue?

**Comment by BetaLeaf** [comment]
Like I looked at docker logs and nothing of interest shows up. I know how to get shell inside the docker container, I just need to know what log files to look at and where.

**Comment by BetaLeaf** [comment]
Any suggestions @enoch85?

**Comment by enoch85** [comment]
No idea as I can't reproduce it.

**Comment by BetaLeaf** [comment]
It's been a day of testing, so it may be too soon, but I think I resolved this issue. I had ModSecurity enabled with active defense turned off. It seems even with active defense off, ModSecurity still causes issues for onlyoffice. I disabled ModSecurity entirely. Since I disabled it, I haven't run into the issue again.
```Bash
sudo apt autoremove -y libapache2-mod-security2 modsecurity-crs
sudo rm -rf /etc/modsecurity/
```

**Comment by BetaLeaf** [comment]
Ok I ran into issues again so the above wasn't the solution. 

I looked at my `/etc/apache2/sites-enabled/*.conf` files and realized that CustomLog and ErrorLog value was not set correctly or at all. After changing them to working values, I was able to analyze the log files by setting the `LogLevel` to `debug`. Then I loaded one of my spreadsheets. Immediately I saw logs for mod_evasive
```
[evasive20:error] [pid 83923:tid 139999130650368] [client 192.168.86.1:53877] client denied by server configuration: proxy:http://127.0.0.3:9090/web-apps/apps/api/documents/api.js
```
Now I am not knowledgeable enough to figure out how to set the server configuration properly, so I just disabled mod_evasive entirely and that seems to solve the issue.

```
sudo a2dismod evasive
sudo systemctl restart apache2
```

@enoch85 If you have some insight on this, please chime in.

**Comment by enoch85** [comment]
Before you install ModSecurity, exactly this is what you are warned about. 

I will remove the feature to avoid further confusion. Thanks for the heads up.

**Comment by BetaLeaf** [comment]
I know about the warning. That's why I disabled active defense

**Comment by BetaLeaf** [comment]
Besides, modsecurity wasn't the real cause, it was mod_evasive @enoch85

**Comment by enoch85** [comment]
Read this now @BetaLeaf I might bring back modsecurity again some time in the future if it's requested. 

Thanks for the info!

**Comment by BetaLeaf** [comment]
No problem.
