### ISSUE TITLE
SU password to modify fstab

### ISSUE THREAD

**Issue by Hydro8** [nextcloud/vm#963]
Hi

I want to modify fstag to mount external storage on boot. I try to edit it but I can't save because I don't have permission (I'm log with ncadmin).

So I try "su -" and nextcloud or my custom password but it doesn't work.

What's the password for su ?

Thank

**Comment by enoch85** [comment]
In Ubuntu, try `sudo -i`

**Comment by enoch85** [comment]
You can also check here: docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W6fMquPiqQz3_Moi/nextcloud-vm-first-setup-instructions?currentPageId=W6yn7ePiqQz3_Mpi
