### ISSUE TITLE
Error while trying to create admin user

### ISSUE THREAD

**Issue by raw1bin** [nextcloud/vm#969]
## Steps to Reproduce
- get a Linux VM form a hosting provider
- created user ncadmin
- become that user
- copy the install script from GitHub to the server
- start the script
- change keyboard layout
- don't change mirror

## Expected behaviour
Installation script should install nextcloud.

## Actual behaviour
Script ran into an error.

## Server configuration

**Nextcloud server version:** (see your admin page)
17

**Server OS** (Ubuntu server is default)
Ubuntu 18.04

**How did you install the VM?** (Scripted install from master **OR** Released version)
scripted install

## Network
**Do you use DHCP?**
no

**Is port 80 and/or 443 open?**
yes

#### Installation log (command output)
```
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "ncadmin"
FATAL:  password authentication failed for user "ncadmin"
 ->
PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 85
{"reqId":"DwQUcBXZAMlPJdP1ieEL","level":3,"time":"2019-10-31T07:37:25+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fileperms(): stat failed for \/var\/www\/nextcloud\/data\/nextcloud.log at \/var\/www\/nextcloud\/lib\/private\/Log\/File.php#85","userAgent":"--","version":"17.0.0.9"}
{"reqId":"DwQUcBXZAMlPJdP1ieEL","level":3,"time":"2019-10-31T07:37:25+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"chmod(): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Log\/File.php#86","userAgent":"--","version":"17.0.0.9"}
Sorry but something went wrong. Please report this issue to https://github.com/nextcloud/vm/issues and include the output of the error message. Thank you!
sudo -u www-data php /var/www/nextcloud/occ maintenance:install --data-dir=/mnt/ncdata --database=pgsql --database-name=nextcloud_db --database-user=ncadmin --database-pass=HSyUnr4AO8zDxMSb#pty2SpaD9cK --admin-user=ncadmin --admin-pass=nextcloud failed
```

**Comment by enoch85** [comment]
Thanks for posting your issue!

I can't reproduce it here. Can you please give the ### Steps to reproduce?

**Comment by raw1bin** [comment]
The first time i ran the script, it said that it would be better to not use root to execute it. So i created the user ncadmin and started the script with that, as suggested from the script itself.

**Comment by enoch85** [comment]
Possible bug, I will investigate when time allows.

**Comment by enoch85** [comment]
Sorry I couldn't reproduce this. I just released 7 different versions of the VM, and none of them had this error.

**Comment by raw1bin** [comment]
That's ok. My service provider provided me with a admin overlay called Plesk and with that i was able to simlpy install Nextcloud on my server.
