### ISSUE TITLE
Public share link not show all items 

### ISSUE THREAD

**Issue by avitiellonc** [nextcloud/vm#972]
Hi all, 

I've upgraded the NextcloudVM to latest version 17.0.0 , esecuted the update script, all done perfectly.
The only issue have noticed was about the applications list.
The problem was be caused to a timeout issue, modified the fetcher.php file solve the problem:

nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php

 		 		 }
 
 		 		 $options = [
-		 		 		OLD 'timeout' => 10,
+		 		 		NEW 'timeout' => 300,
 		 		 ];

Now I have a similar issue with the file showed in a public sharelink, example:

I have shared 160 files in the root folder but the browser show me sistematically only 19 files and there isn't the possibility to scroll the list, consider that the files have alphabetical sort.

![image](https://user-images.githubusercontent.com/57347847/68110233-cc030e00-feec-11e9-93ec-cdf83cffc49a.png)

I tried with Firefox and Chrome with the same result, Internet explorer charge more slowly the page and show minus items than other browsers.

It seems a timeout issue as app page.

In the logs there are no errors.

If it is a timeout issue, where can I change the values?

Thanks

Antonio

**Comment by avitiellonc** [comment]
Find the solution, the issues depend to talk, disabled it the problem is gone.

**Comment by enoch85** [comment]
Glad you solved it!
