### ISSUE TITLE
missing sudo at dpkg-reconfigure keyboard-configuration

### ISSUE THREAD

**Issue by tavinus** [nextcloud/vm#980]
Hi,

I was trying the installer and noticed that I didn't get a prompt to change my Keyboard after I have chosen to change it.  
  
Seems like we are missing a `sudo` here:  
https://github.com/nextcloud/vm/blob/a3755dc4964660a545af5e27c9f9b7fbe2fcaf4a/nextcloud_install_production.sh#L69
  
```
sudo dpkg-reconfigure keyboard-configuration
``` 
Cheers!

**Comment by enoch85** [comment]
@tavinus The script is run as root so no `sudo` needed.

Thanks for reporting though! :rocket: 

Just try again, and follow the instructions during the setup.

**Comment by tavinus** [comment]
hummm...  
should remove from here then 

![image](https://user-images.githubusercontent.com/8039413/69030325-fc9b7b00-09b5-11ea-983d-a011e904b74b.png)

**Comment by enoch85** [comment]
`sudo` works even when running as root, so I don't see the issue here?

Sure, I could remove `sudo` everywhere but how would that help? Did that solve the issue for you?

**Comment by tavinus** [comment]
LOL ... sure .. my b
