### ISSUE TITLE
Script relies on Curl before it is installed

### ISSUE THREAD

**Issue by mitch-birti-sp** [nextcloud/vm#986]
## Steps to reproduce
1. Follow the "install with scripts" steps [here](https://docs.hanssonit.se/s/bj0vl1ihv0jgrmfm08j0/build-your-own/d/bj0vl4ahv0jgrmfm0950/nextcloud-vm)

## Expected behaviour
The first install script completes successfully.

## Actual behaviour
The script runs, but doesn't include any `lib.sh` functions. The most noticeable issue is a bunch of these types of errors:
```
nextcloud_install_production.sh: line 29: print_text_in_color: command not found
nextcloud_install_production.sh: line 38: print_text_in_color: command not found
```
I stopped the script before it finished.

I think the problem is in `nextcloud_install_production.sh`, on line 11 where `lib.sh` is loaded. Ubuntu doesn't ship with curl, so loading that file fails. There's a curl install check starting on line 17 that should probably happen before `lib.sh` is loaded.

**Server OS** (Ubuntu server is default)
Ubuntu 18.04.1 LXE container, created from stock template in Proxmox 5

**Comment by enoch85** [comment]
`curl` is installed by default in Ubuntu if you download their ISO, but in some cases some VPS providers use a different image which doesn't include `curl`. 

The issue is now resolved anyway. Thanks for the heads up!
