### ISSUE TITLE
OVA import on ESX6.7

### ISSUE THREAD

**Issue by jdutsler** [nextcloud/vm#987]
I am not sure if this is a bug or not - please direct me to appropriate resource if already solved.

I have downloaded: Nextcloud_VM_www.hanssonit.se.ova
I'm logging into the esx server from a windows host, and I've tried using Internet Explorer, Chrome, and Edge browsers with same results.

I am trying to register a new VM under VMware ESX 6.7.  Steps:

- Create/Register VM
- Select "Deploy a virtual machine from an OVF or OVA file", and Next
- add name "vmnextcloud", select ova file from gui, click Next
- choose datastore (has 850gb free)
- leave default bridged VM network, Thin, and Power on Automatically, click Next
- pop up error message as explained below.  In background is "Ready to Complete" screen where you hit "finish" to continue.

Recieve browser Error:
Unhandled Exception (1)
 
Unfortunately, we hit an error that we weren't expecting.

The client may continue working, but at this point, we recommend refreshing your browser and submitting a bug report.

Press the Esc key to hide this dialog and continue without refreshing.

The pop up has two choices, Details and Reload.

When I click "Esc", the browser just goes back to the vmware gui and no vm has been created. 
When I click "Reload" it takes me back to the web login screen for the ESX server (no vm created)
When I click "Details" I get the following:
Cause: Possibly unhandled rejection: {}
Version: 1.33.3
Build: 12923304
ESXi: 6.7.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363

Exception stack:

TypeError: Unable to get property 'keyValue' of undefined or null reference
   at updateSummaryPortlet (https://192.168.1.144/ui/scripts/main.js:375:269)
   at Anonymous function (https://192.168.1.144/ui/scripts/main.js:375:3463)
   at Anonymous function (https://192.168.1.144/ui/scripts/main.js:324:23172)
   at m.prototype.$digest (https://192.168.1.144/ui/scripts/main.js:324:28765)
   at Anonymous function (https://192.168.1.144/ui/scripts/main.js:324:30491)
   at e (https://192.168.1.144/ui/scripts/main.js:323:10069)
   at Anonymous function (https://192.168.1.144/ui/scripts/main.js:323:11510)

Please point me in the right direction.

## Steps to reproduce
1.
2.
3.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

## Server configuration

**Nextcloud server version:** (see your admin page)

**Server OS** (Ubuntu server is default)

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**

**Is port 80 and/or 443 open?**

#### Log file (/mnt/ncdata/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Installation log (command output)
```
Insert the CLI output here
```

**Comment by enoch85** [comment]
Hey! Thanks for your issue.

Have you tried looking for any answers by pasting the error messages in your favorite search engine? There were some issues with people using 5.5 because VMware decided to change the SHA algorithm in newer versions, maybe there''s some similar issue with 6.7?

I've never seen this before.

**Comment by enoch85** [comment]
@jdutsler Any update here?

**Comment by enoch85** [comment]
I just tested on 6.7 and it worked without a hitch.

![Screenshot from 2019-11-28 11-19-10](https://user-images.githubusercontent.com/4511254/69798042-fd5fb880-11d0-11ea-8c73-0c4536d5655a.png)
![Screenshot from 2019-11-28 11-19-22](https://user-images.githubusercontent.com/4511254/69798044-fd5fb880-11d0-11ea-82ec-6ba2c319046c.png)

**Comment by jdutsler** [comment]
Hi Enoch85, thanks for the response.  I'm new at working esx in a home environment.  I've been up and running only a couple months with two VMs running on a host.  I've tried quite a bit of googling without clear success.  

Ever since I got started my browser always gives certificate warnings when I go to log into the esx server.  I've found a few good threads on how to build and install the certs on both host and esx server, so I'm going to try that as next troubleshooting step.  If nothing else, I'd like to rule that out as a culprit.

In order to avoid the web interface, I've looked for a way to register a VM via SSH and command line, but esx doesn't seem to have a way to do that.

**Comment by enoch85** [comment]
> Ever since I got started my browser always gives certificate warnings when I go to log into the esx server

@jdutsler It seems like you over-complicate things.

The certificate warning in the browser will always be present if you're not running a real TLS cert and run the host locally.

In my opinion you don't need a real cert as long as the installation is strictly local.

> next troubleshooting step

A certificate for logging in to the host has nothing to do with the VM itself.

> register a VM via SSH and command line, but esx doesn't seem to have a way to do that.

I'm not sure, but I think you could use VMware Console (Powershell like console bundled especially for VMware. But why really, just register in the web interface as you normally would.
