### ISSUE TITLE
can't login after Scripted install from master

### ISSUE THREAD

**Issue by bobdig** [nextcloud/vm#989]
-->
## Steps to reproduce
1. Installed Ubuntuserver as user:ncadmin pass:private
2. run the scripts and in the end created a new user
3. 

## Expected behaviour
after everything is setup I should be able to login as the newly created user

## Actual behaviour
no login possible: login incorrect
But it was possible to login as ncadmin

## Server configuration

**Server OS** Ubuntu server

**How did you install the VM?** 
Scripted install from master

**Comment by enoch85** [comment]
Hey, you probably misstyped the password, please try again.

**Comment by bobdig** [comment]
My bad, thought the initial user in ubuntu would be deleted but that isn't the case.
