### ISSUE TITLE
Adding a smb share as datafolder

### ISSUE THREAD

**Issue by quintz** [nextcloud/vm#990]
good Morning,

I wanted to install Nextcloud via your script but I was wondering if I could use a smb share as data directory?

**Comment by enoch85** [comment]
Yes, that's possible. You need to prep the VM with mounting the SMB share in `/etc/fstab` first.

**Comment by quintz** [comment]
i did that, i mounted the share via 

/etc/fstab/

//192.168.0.11/Nextcloud /mnt/Nextcloud cifs iocharset=utf8,file_mode=0770,dir_mode=0770 0 0

But unfortunately I now get an error because I cannot write there even though, when I try to nano a helloworld.txt there, it works....

do you have any clue why this happens?

**Comment by enoch85** [comment]
Sorry, this is not a support forum. Please ask in https://help.nextcloud.com.

Thanks!
