### ISSUE TITLE
Allow Talk to be installed even without SSL cert

### ISSUE THREAD

**Issue by thejohnha** [nextcloud/vm#991]
## Steps to reproduce
1. Run the script.
2. Opt to install Nextcloud Talk

## Actual behaviour
Installer fails if you have previously chosen not to install SSL cert. This is because I use haproxy and have SSL terminated at the proxy. I don't want to install SSL directly on the VM.

**How did you install the VM?** Scripted install from master

**Comment by enoch85** [comment]
This will not happen.
