### ISSUE TITLE
WAN IPv4

### ISSUE THREAD

**Issue by glacroix71** [nextcloud/vm#994]
Hi,

     When I login to the next-cloud-VM console, I see:

Hostname:  Nextcloud
WAN IPv4: xxx.xxx.xxx.xxx
WAN IPv6:
LAN IPv4: server internal nextwork IP

The WAN IPv4 is not the right one, how can I modify that IP.  

Thanks.

**Comment by enoch85** [comment]
It's a function which checks the WAN IP: https://github.com/nextcloud/vm/blob/master/static/nextcloud.sh#L6

So in other words, it gets the IP external WAN address from an external site. So if the IP is wrong, your Firewall must be setup in such a way that it shows that IP instead.

Hopes it makes sense. :)
