### ISSUE TITLE
PHP Incompatibility on Update (running Nextcloud 17.0.1 on PHP 7.4.1, but Nextcloud 17.0.2 says won't work with > PHP 7.3)

### ISSUE THREAD

**Issue by ozinfotech** [nextcloud/vm#995]
## Steps to reproduce
1. Attempt to update Nextcloud to the latest version

## Expected behaviour
Update should complete successfully.

## Actual behaviour
Error message appears: "This version of Nextcloud is not compatible with > PHP 7.3. You are currently running 7.4.1."

## Server configuration

**Nextcloud server version:** (see your admin page)
17.0.1

**Server OS** (Ubuntu server is default)
Ubuntu 16.04.6 LTS

**How did you install the VM?** (Scripted install from master **OR** Released version)

## Network
**Do you use DHCP?**
No

**Is port 80 and/or 443 open?**
Yes

## Logs / Screenshots
https://imgur.com/a/Ffry1We

**Comment by enoch85** [comment]
Try downgrade to 7.3 and see if that helps.

The VM is released with 7.2.

**Comment by ozinfotech** [comment]
I'll be keeping current version of PHP unless Nextcloud has severe security issues. Thanks!

**Comment by enoch85** [comment]
I haven't checked but I think PHP 7.4 will be supported in Nextcloud 18.
