### ISSUE TITLE
Nextcloud Talk script for installing

### ISSUE THREAD

**Issue by TimurC1** [nextcloud/vm#998]
Hello, Nextcloud! I want to install Nextcloud Talk by script (Ubuntu 18.04), but it says:
      ┌─────────────┤ Nextcloud VM - T&M Hansson IT - 2019 ├─────────────┐
      │                                                                  │ 
      │ It appears that something went wrong with the update.            │ 
      │ Please report this to https://github.com/nextcloud/vm/issues     │ 
      │                                                                  │ 
      │                              <Ok>

**Comment by enoch85** [comment]
Hi,

Sorry, but that doesn't tell me anything. 

Please fill out the complete issue template. Especially "Steps to reproduce."

Thanks!

**Comment by TimurC1** [comment]
Hello, Daniel! Ok, I am filling that now.

**Comment by TimurC1** [comment]
Hahahahah, i forgot that I need Nextcloud VM, not only Nextcloud))) Thanks, it was my trouble)
