### ISSUE TITLE
Backup: which files/directorys do I need do backup over rsync?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/vm#999]
First of all, thank you for your nice working VMs.
I would like to know which files/directorys I have to Backup in the standard config?
So with other words: which files/directorys do I have to copy to a new instance when starting all over? (So that I don't have to backup the whole vmdk files and use them to the end of time once I have setup the VM)
Would be really nice to know that. Couldn't find anything about it in the docs.

**Comment by enoch85** [comment]
I never tried this myself, but maybe this helps you a bit? https://codeberg.org/DecaTec/Nextcloud-Backup-Restore

**Comment by enoch85** [comment]
Usually I recommend Veeam which in my opinion is the best backup tool.

With Rsync you could backup both the whole VM and the Nextcloud dir itself which is:
`/var/www/nextcloud/`
`/var/NCBACKUP´
`/mnt/ncdaa`

Hope it helps!

**Comment by szaimen** [comment]
> Usually I recommend Veeam which in my opinion is the best backup tool.
> 
> With Rsync you could backup both the whole VM and the Nextcloud dir itself which is:
> 
> * `/var/www/nextcloud/`
> * `/var/NCBACKUP`
> * `/mnt/ncdata`
> 
> Hope it helps!

Thanks!
Actually, I couldn't find the /var/NCBACKUP directory. It is not existing on my installation.
And what about the database, where do I find it?

**Comment by enoch85** [comment]
>  I couldn't find the /var/NCBACKUP directory.

Aah, that was the old path. Check here instead: https://github.com/nextcloud/vm/blob/master/lib.sh#L15

Regarding DB, check the `nextcloud_update.sh` script.

**Comment by szaimen** [comment]
> I never tried this myself, but maybe this helps you a bit? https://codeberg.org/DecaTec/Nextcloud-Backup-Restore

That sounds really nice!
Do you think that something like this could be used some day as the "normal way" of migrating the Nextcloud VM between Ubuntu LTS versions? 
Of course better would be beeing able to just upgrade the VM to a newer version of Ubuntu LTS but I think this will not be feasable?

So I imagine something like this:
1. Configure the Backup as an additional app with whiptails or just pre-configured,  since this should be always the same e.g. on Ubuntu 18.04, start the backup to an external drive
2. download the new VM from your website with the newest Ubuntu LTS website
3. during the first startup beeing able to choose if you want to restore a Nextcloud-VM-Installation (based on the last Ubuntu LTS version; so e.g. no upgrade from 16.04 to 20.04 but e.g. from 18.04 to 20.04) from a backup and choose to restore from the same directory that you have chosen to backup to or just set up a new instance?
4. automatically migrate between versions e.g. postgresql or e.g. from mysql to postgresql (e.g. when changing the VM from Ubuntu 16.04 to 18.04 )
5. having the choice to resetup the additional apps afterwards (don't need to get backuped to my knowledge since they aren't storing any files? apart from bitwarden of course...)

Since all VMs e.g. based on Ubuntu 18.04 have always the same setup (like postgresql)... this could define a working upgrade process, couldn't it?
So if you later on choose to take another db system e.g. for the 20.04 VM, then you could just migrate the users to it during this first restore setup...?

**Comment by enoch85** [comment]
Thanks for your offer, really!

Send me an email and we'll discuss it further.
